2단계 - 로또(자동)
next-step/java-lotto pull request #1002
Opened 2020-11-29 14:13 UTC by joongs

### 제목
2단계 - 2단계 - 로또(자동)

### 작업내용 (step1 피드백)
- [ ] 메소드 순서대로 parseOperands , sumOperands 위치 변경
- [ ] Pattern 객체 캐싱 처리
`private static final Matcher customMatcher = Pattern.compile(customRegex).matcher(userInput);`
- [ ] 상수로 처리
`private static final String customRegex = "//(.)\n(.*)";`
`private static final String customRegex = "//(.)\n(.*)";`
- [ ] Object 클래스를 활용한 null 검사
`return Object.isNull(userInput) || userInput.isEmpty();`
- [ ] `RuntimeException` --> `IllegalArgumentExceptinon으로 핸들링`
- [ ] testcase에대해서도 리팩토링(반복제거) 수행하기 (ParameterizedTest 도입)
- [ ] `@DisplayName`을 활용해서 test의도 나타내기
### 작업내용
- [ ] LotteryNumber class를 구현한다.
  * 1~ 45 이내의 숫자만 허용한다.
- [ ] LotteryTicket class를 구현한다.
  * 6개 숫자는 중복이 없다.
  * 오름 차순으로 정렬한다.  
- [ ] LotteryGame class를 구현한다.
  * 입력한 금액 만큼 로또 티켓을 발행한다.
  * 당첨 번호를 입력 받는다.
  * 로또 1장을 구입한다.
  * 로또 당첨을 확인한다.
- [ ] LotteryResult class를 구현한다.
  * 3,4,5,6개 맞춘 결과를 저장한다.
  * 수익성을 계산한다. (ing)
- [ ] LotteryWinNumbers class를 구현한다.(? 구현이 필요한가)
  * 당첨번호를 입력한다.
  * 로또 티켓이 당첨되었는 확인한다.
- [ ] InputView class를 구현한다.
  * 금액을 입력 받는다.
  * 6개의 당첨 번호를 입력 받는다.
- [ ] ResultView class를 구현한다.
  * 구매한 복권 개수를 출력한다.
  * 당첨 통계를 출력한다.
- [ ] LotteryGameManager class를 구현한다.

### 학습내용
[2단계 - 로또(자동)](https://edu.nextstep.camp/s/MNii0Puk/ls/uYOLrcvU)

### 참고 
[junit - parameterized](https://www.baeldung.com/parameterized-tests-junit-5)
[assertj 활용](https://www.baeldung.com/introduction-to-assertj)

### 한줄일기
TDD로 최대한 개발을 하려고 노력을 했다. 그런데 결과물은 편하게 읽히는 코드가 아닌것 같다. 간단한 프로그램이 복잡해진 느낌이다.

2020-11-30 11:42 UTC, sah3122 requested changes
로또 구현 잘해주셨네요 👍 
몇가지 생각거리를 남겨두었는데 확인해주세요. 
아마도 구조적으로 변경이 일어날것 같은데 고민하시다 어려운점이 있으시면 편하게 DM 주셔서 같이 풀어나가요 😄

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryGame.java
> +    public List<LotteryTicket> buyLotteryTickets(int numberOfTickets) {
로또를 구입하는 책임은 LotteryGame 클래스가 담당하기에 적절한것 같아요. 
하지만 구입 방식 예를 들면 자동 로또 구입과 같은 비즈니스 로직이 LotteryGame에 녹아있는건 적절하지 못한 모델링인것 같습니다. 
적절한 클래스에 해당 책임을 위임하거나 새로운 클래스를 만들어 보는것이 어떨까요 ?

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryGame.java
> +    public LotteryResult matchLotteryTickets(String winningNumbers, List<LotteryTicket> lotteryTickets) {
마찬가지로 LotteryGame클래스가 가져야하는 책임을 분산 시켜보세요. 
제가 생각하기에 가장 알맞는 구조는 
```java
public LotteryResult matchLotteryTickets(...) {
LotteryResult lotteryResult = someDomain.match();
return lotteryResult;
}
```
위와 같이 도메인 객체에게 메시지를 던지고 전달 받은 값을 외부로 리턴해주는 구조라고 생각해요. 
도메인 객체가 자율적인 행위를 할수 있도록 변경해보세요 !

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryNumber.java
> +    public int isContainNumber(LotteryTicket winningLotteryTicket) {
로또 번호의 불변객체가 `LotteryTicket` 내부의 어떤 값의 존재 유무를 판단하는것은 올바르지 않다고 생각합니다. 
불변객체는 외부 클래스에서 특정한 의미를 지니고 사용하기 위함인데, LotteryTicket 클래스에 종속적인 행위를 담당할 필요는 없어보여요.

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +    public LotteryResult() {
당첨과 관련된 Enum을 정의하여 사용해보는것은 어떻게 생각하시나요 ㅎ ㅎ

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +                put(6, 2000000000);
Java 7 버전 부터 숫자 자료형의 가독성을 높일수 있도록 언더스코어를 사용할수 있게 되었습니다. 
```suggestion
                put(6, 2_000_000_000);
```

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +        }
```suggestion
        if (this.lotteryResultMap.containsKey(key)) {
            this.lotteryResultMap.replace(key, lotteryResultMap.get(key) + value);
        }
        this.lotteryResultMap.put(key, value);
```
위와같이 사용할수 있을것 같아요 !

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +        if (key < LIMIT_MATCHED_NUMBER) return;
한줄짜리 코드라도 중괄호를 생략하지 않는것을 권장 드려요.
https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +    public void update(int key, int value) {
메소드 명만 봐서는 어떤 행위를 하는지 알수 없는데 다른 메소드명을 고민해보세요 !

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +    public double getProfit(int purchaseAmount) {
Java 에서는 금액과 같이 정확한 계산을 위해 BigDecimal이라는 클래스를 제공해주고 있어요. 
BigDecimal에 대해 알아보고 활용해보세요 !

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +    public String toString() {
만약 LotteryResult 클래스를 다른 요구사항에서 사용한다고 가정 했을때 이와 같은 출력 결과물이 항상 필요하지는 않을것 같아요. 
UI를 위한 코드는 Output 클래스로 이동하는것이 어떨까요 ?

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
> +    private final List<LotteryNumber> lotteryNumbers;
List 자료형 보다는 중복을 허용하지 않는 자료형을 사용하는것이 더 적절해보여요 ㅎㅎ

2020-11-30 11:42 UTC, sah3122 commented on src/main/java/lottery/view/InputViewLotteryGame.java
> +        Scanner scanner = new Scanner(System.in);
Scanner 객체를 매번 생성하기 보다는 상수로 만들어 사용한다면 자원을 아낄수 있을것 같습니다. !

2020-11-30 16:17 UTC, joongs commented on src/main/java/lottery/domain/LotteryGame.java
> +    public List<LotteryTicket> buyLotteryTickets(int numberOfTickets) {
자동 구매를 위한 행위를 별도 `AutoBuyBehavior` class`로 빼서 해보겠습니다.

2020-11-30 16:17 UTC, joongs commented on src/main/java/lottery/domain/LotteryGame.java
> +    public LotteryResult matchLotteryTickets(String winningNumbers, List<LotteryTicket> lotteryTickets) {
`LotteryResult`에게 해당 기능을 위힘해보도록 하겠습니다.

2020-11-30 16:24 UTC, joongs commented on src/main/java/lottery/domain/LotteryNumber.java
> +    public int isContainNumber(LotteryTicket winningLotteryTicket) {
해당 기능은 로또 티켓으로 옮겨보겠습니다.

2020-11-30 16:25 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +                put(6, 2000000000);
아네 언더스코어 사용은 제가 몰랐던 부분입니다.
피드백 감사합니다. :)

2020-11-30 16:27 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    public void update(int key, int value) {
`addLotteryResult`로 변경해보겠습니다.

2020-11-30 16:29 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +        }
앗, 네 확인했습니다. 해당건으로 반영해보겠습니다. 👍

2020-11-30 16:30 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +        if (key < LIMIT_MATCHED_NUMBER) return;
네 의견 반영하겠습니다. 👍

2020-11-30 16:44 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    public double getProfit(int purchaseAmount) {
`BigDecimal`사용으로 변경해보겠습니다.

2020-11-30 16:52 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    public String toString() {
네 해당코드는 이동해보겠습니다.

2020-11-30 16:55 UTC, joongs commented on src/main/java/lottery/view/InputViewLotteryGame.java
> +        Scanner scanner = new Scanner(System.in);
Scanner 객체를 상수로 만들어서 사용하면 아래와 같은 문제가 있습니다.
```
public final class InputViewLotteryGame {
    final static Scanner scanner = new Scanner(System.in);
    public static int getUserInvestAmount() {
        //Scanner scanner = new Scanner(System.in);
        System.out.println("구입금액을 입력해 주세요.");
        return scanner.nextInt();
    }

    public static String getWinningNumbers() {
        //Scanner scanner = new Scanner(System.in);
        System.out.println("지난 주 당첨 번호를 입력해 주세요.");
        return scanner.nextLine();
    }
}
```
이렇게 하면 실행시 아래와 같은 에러가 발생합니다.
```
지난 주 당첨 번호를 입력해 주세요.
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
```

제가 잘못사용한걸까요?

2020-11-30 16:59 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
> +    private final List<LotteryNumber> lotteryNumbers;
`set`은 sorting이 불가해서 `List`를 사용은 했습니다.
`List`는 `sorting`이 되지만 `중복은 알아서 필터링이 필요합니다.`
어떤 트레이드오프를 선택해야 할지에 고민이 있었습니다.

2020-12-03 14:52 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    public LotteryResult() {
DM으로 장문으로 문의를 드렸었는데, 의견 및 답변 감사드립니다.
해당건에 대해서 적용해서 PR올리겠습니다. :)

2020-12-04 08:53 UTC, sah3122 commented
![image](https://user-images.githubusercontent.com/24941604/101142741-5cb09e00-3659-11eb-8778-ce28a33c3319.png)
로또 번호에 대한 중복 검사가 필요해보입니다. 

![image](https://user-images.githubusercontent.com/24941604/101142877-8bc70f80-3659-11eb-9f30-21c7ed36dfc0.png)
출력 결과가 미션에서 주어진 포맷과 다른데 확인 부탁 드려요 🙏

2020-12-04 08:54 UTC, sah3122 requested changes
피드백 반영 잘해주셨네요 💯 
몇가지 생각거리를 추가로 남겨두었는데 확인 부탁 드립니다. 😄

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/AutoBuyBehavior.java
> +                .collect(Collectors.toList());
로또 번호를 매번 생성하지 않고 static 영역에 캐싱하여 동일한 자원에 대한 생성 비용을 줄여 보세요 ㅎ

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/AutoBuyBehavior.java
> +    private List<LotteryNumber> createLotteryNumbersByNumbers(List<Integer> numbers) {
lotteryAllNumbers 의 스트림을 활용하여 코드를 줄여볼수 있을것 같아요 ! 
```java
List<LotteryNumber> lotteryNumbers = IntStream.rangeClosed(START_INCLUSIVE, END_INCLUSIVE)
                .boxed()
                .map(LotteryNumber::new)
                .collect(Collectors.toList());
```
스트림의 익숙하지 않으시다면 이번 기회에 익숙해지려고 노력해보는것도 좋을것 같습니다.

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryGame.java
> +        AutoBuyBehavior autoBuyBehavior = new AutoBuyBehavior();
buyLotteryTickets 메소드가 AutoBuyBehavior에 종속되어 있네요. 
BuyBehavior를 주입 받는 구조로 변경한다면 조금더 유연하게 사용할 수 있지 않을까요 ?

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +    public LotteryResult(String winnerNumbers, int key, int value) {
테스트 작성을 위한 생성자라면 현시점에서는 불필요한것 같아요. 다른 방법으로 테스트를 작성해보는것을 권장 드립니다.

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
>      Map<Integer, Integer> lotteryResultMap;
Integer Key 가 아닌 구현해주신 LotteryValue를 선언한다면 조금더 깔끔한 구현이 될것 같은데 고민해보세요 !

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +        if (key < LIMIT_MATCHED_NUMBER) {
당첨되지 않은 로또를 판단하는건 당첨 기준을 가지고 있는 `LotteryValue`객체가 담당하는것이 어떨까요 ?

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +    public void addLotteryResult(int key, int value) {
개인적으로 메소드의 선언 순서는 사용되는 메소드 아래에 선언하는것을 권장 드립니다. 
다른 개발자들이 코드를 읽는것이 편한것 같더라구요 !

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
>      public int getCountsMatched(LotteryTicket winningLotteryTicket) {
당첨 로또 클래스를 만들어 당첨 여부를 판단하는 책임을 부여하는 것도 좋을것 같아요.

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
> +        return "[" + lotteryTicket.subSequence(0, lotteryTicket.length() - 2).toString() + "]";
출력을 담당하는 기능은 도메인 클래스가 아닌 UI 클래스에서 담당하는것이 어떨까요 ?

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryValue.java
> +                        String.format("%d에 해당하는 당첨금액은 없습니다.", place)));
MISS와 같이 당첨되지 않은 상태를 정의하여 리턴해주는것도 고려해보시면 좋을것 같아요. 
매번 예외를 던지는 것과 MISS 와 같은 상태를 리턴하는것들이 어떤 차이점이 있는지 고민해보세요 !

2020-12-04 08:54 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
> +    private final List<LotteryNumber> lotteryNumbers;
Set 컬렉션중 Sorting을 지원하는 컬렉션들이 존재합니다 😄 
어떤 구현체가 Sorting을 지원하는지 찾아보고 활용해보세요 !

2020-12-05 06:43 UTC, joongs commented
> ![image](https://user-images.githubusercontent.com/24941604/101142741-5cb09e00-3659-11eb-8778-ce28a33c3319.png)
> 로또 번호에 대한 중복 검사가 필요해보입니다.
> 
> ![image](https://user-images.githubusercontent.com/24941604/101142877-8bc70f80-3659-11eb-9f30-21c7ed36dfc0.png)
> 출력 결과가 미션에서 주어진 포맷과 다른데 확인 부탁 드려요 🙏

제가 요구 사항을 잘못 이해를 했었습니다. 
네 해당건은 추가로 변경하겠습니다.

2020-12-05 07:02 UTC, joongs commented on src/main/java/lottery/view/InputViewLotteryGame.java
> +        Scanner scanner = new Scanner(System.in);
해당건은 의견 주신것처럼 `nextInt`대신 `nextLine()`을 사용해서 final static으로 빼서 처리를 했습니다.

2020-12-05 07:24 UTC, joongs commented on src/main/java/lottery/domain/AutoBuyBehavior.java
> +                .collect(Collectors.toList());
네 의견 감사합니다.
코드를 보니 그렇네요, 한번만 생성해두고 `shuffle`을 통해서 섞으면 되네요. 👍

2020-12-05 07:36 UTC, joongs commented on src/main/java/lottery/domain/AutoBuyBehavior.java
> +    private List<LotteryNumber> createLotteryNumbersByNumbers(List<Integer> numbers) {
네 제가 `map` 메소드를를 몰랐었습니다.
`map` 메소드를 사용하며 아래 별도로 생성했던 private 메소드를 사용할 필요가 없었네요. 
좋은 리뷰 감사합니다.

2020-12-05 12:51 UTC, joongs commented on src/main/java/lottery/domain/LotteryGame.java
> +        AutoBuyBehavior autoBuyBehavior = new AutoBuyBehavior();
네 `AutoBuyBehavior`를 주입하는 방법으로 개선해보겠습니다.

2020-12-05 13:04 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    public LotteryResult(String winnerNumbers, int key, int value) {
네 테스트 용도로 사용하려고 했었는데, 다른 방법으로 테스트를 작성하는것으로 개선하겠습니다.

2020-12-05 14:33 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
>      Map<Integer, Integer> lotteryResultMap;
네 해당건으로 `key`를 `LotteryValue`로 변경해보겠습니다.

2020-12-05 14:37 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    public void addLotteryResult(int key, int value) {
네 해당 위치에 대해선 사용하는 함수 아래로 이동해보겠습니다. 👍

2020-12-05 15:01 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +        if (key < LIMIT_MATCHED_NUMBER) {
`LotteryValue`로 옮겨보겠습니다.

2020-12-05 15:01 UTC, joongs commented on src/main/java/lottery/domain/LotteryValue.java
> +                        String.format("%d에 해당하는 당첨금액은 없습니다.", place)));
`LotteryValue`에 `MISS(-1,0)` 상태를 추가해서 변경해보겠습니다.

2020-12-05 15:27 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
> +        return "[" + lotteryTicket.subSequence(0, lotteryTicket.length() - 2).toString() + "]";
네 옮겨보겠습니다.

2020-12-06 14:43 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
>      public int getCountsMatched(LotteryTicket winningLotteryTicket) {
네 해당 책임은 `LotteryWining` 클래스로 옮기겠습니다.

2020-12-06 15:10 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
> +    private final List<LotteryNumber> lotteryNumbers;
네 해당건은 `SortedSet`을 활용해서 개선해보겠습니다.

2020-12-07 07:42 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
몇가지 생각거리를 남겨두었는데 다음 미션을 진행하며 반영해주세요 😄 
미션 진행중 어려움이 있거나 고민거리가 있으면 편하게 DM 주세요 !

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/AutoBuyBehavior.java
> +    public static final List<LotteryNumber> lotteryAllNumbers = IntStream.rangeClosed(START_INCLUSIVE, END_INCLUSIVE)
로또 번호에 대한 캐싱 👍

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryGame.java
> +    public List<LotteryTicket> buyLotteryTickets(int numberOfTickets, AutoBuyBehavior behavior) {
```suggestion
    public List<LotteryTicket> buyLotteryTickets(int numberOfTickets, BuyBehavior behavior) {
```
구체적인 클래스 보다는 인터페이스로 선언한다면 더욱 유연하게 코드를 구현할수 있을거에요 😄

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +    Map<LotteryValue, Integer> lotteryResultMap;
접근제어자를 package-private으로 설정한 이유가 있을까요 ?

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryResult.java
> +    private final LotteryWinning winningTicket;
당첨 로또를 LotteryResult에서 가지고 있는것도 좋지만 당첨 로또를 통해 LotteryResult를 알아내는 구현은 어떻게 생각하시나요 ㅎㅎ
로또의 당첨 여부를 알기 위해서는 당첨 번호가 필요하고, 구입한 번호와 당첨 번호를 대조하여 결과를 알수 있어요. 
당첨 번호를 가지고 있는 LotteryWinning 클래스에서 LotteryResult를 제공한다면 자연스러운 모델링이 될것 같습니다 😄

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
>  public class LotteryTicket {
사용하지 않는 코드들은 주석으로 처리하기 보다는 삭제 하는것이 어떨까요 ㅎ
추가적으로 생성자가 많아졌으니 주 생성자 / 부 생성자를 도입 하여 부 생성자에서는 주 생성자를 호출하는 구조로 변경해보는건 어떨까요 ? 
중요한 유효성 검사와 같은 로직들을 주 생성자에서만 처리 한다면 중복도 줄일수 있을것 같아요 😄

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
> +    private final SortedSet<LotteryNumber> lotteryNumbers;
```suggestion
    private final Set<LotteryNumber> lotteryNumbers;
```
마찬가지로 구체적인 클래스로 선언하기 보단 상위 클래스로 선언하여 유연하게 구현해보세요. 
https://stackoverflow.com/questions/2279030/type-list-vs-type-arraylist-in-java

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
> +        this.lotteryNumbers = new TreeSet<>();
```suggestion
        this.lotteryNumbers = new TreeSet<>(lotteryNumbers);
```
위와 같이 구현가능하지 않을까요  ?

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/AutoBuyBehavior.java
>      public List<LotteryTicket> buyLotteryTickets(int pickCounts, int numberOfTickets) {
자동 구입에 관한 전략을 구현해주셨는데 한가지 아쉬운 부분은 전략 자체가 `List<LotteryTicket>` 을 제공해주고 있는 부분인것 같아요. 
LotteryTicket의 생성자 또는 정적 팩토리 메서드를 구현하여 전략을 주입하고 LotteryTicket 클래스가 자동 로또와 같은 객체를 제공해 주는 방향으로 구현한다면 전략 자체가 `자동 번호 발급의 역할`만 할수 있을것 같습니다 !

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
>          this(winningNumbers.replace(" ", "").split(","));
매직넘버는 상수로 관리하여 가독성을 높일수 있을것 같습니다. 😄

2020-12-07 07:42 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
> +        if (lotteryNumbers.size() != NUMBER_OF_LOTTERY_NUMBERS) {
코드가 중복되고 있네요. 중복을 없앨수 있는 방법을 고민해보세요 ㅎㅎ 힌트는 주 / 부 생성자 입니다.

2020-12-07 07:43 UTC, merged

2020-12-07 15:12 UTC, joongs commented on src/main/java/lottery/domain/LotteryGame.java
> +    public List<LotteryTicket> buyLotteryTickets(int numberOfTickets, AutoBuyBehavior behavior) {
네 해당거는 의견 주신대로 해당 방법이 맞는것 같습니다. 👍

2020-12-07 15:12 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    Map<LotteryValue, Integer> lotteryResultMap;
해당 클래스에서만 사용하는 것으로 생각해써 `package-private`을 설정을 했습니다. ?

2020-12-07 15:14 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    private final LotteryWinning winningTicket;
제가 생각을 반대로 했어야 자연스러운 모델링이 되는군요? :)
`LotteryWinning` 클래스에서 `LotteryResult`를 제공하는 건으로 변경을 해보겠습니다.

2020-12-07 15:14 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
>  public class LotteryTicket {
네 맞습니다. 해당건에 대해서 저도 중복이 많아지고 있다고 생각했고, 말씀해주신 방법으로 개선해보겠습니다.
그리고 주석코드 삭제는 제가 삭제를 안했네요....해당건도 삭제 하겠습니다.

2020-12-07 15:16 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
> +    private final SortedSet<LotteryNumber> lotteryNumbers;
![image](https://user-images.githubusercontent.com/8574015/101368465-87655580-38ea-11eb-990e-592f0fe45e6b.png)

해당 그림 통해서 확인했습니다. 유연하게 가려면 Set으로 해야 하는게 옮은 방향이었네요 👍

2020-12-07 15:19 UTC, joongs commented on src/main/java/lottery/domain/AutoBuyBehavior.java
>      public List<LotteryTicket> buyLotteryTickets(int pickCounts, int numberOfTickets) {
이부분은 다음 시작전에 해당건 고려해서 반영해보겠습니다.

2020-12-07 15:20 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
> +        if (lotteryNumbers.size() != NUMBER_OF_LOTTERY_NUMBERS) {
네 해당건 다음 PR전에 반영해서 할 수 있도록 하겠습니다. 👍

2020-12-07 15:22 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
>          this(winningNumbers.replace(" ", "").split(","));
요기에서 매직넘버가 어떤 것일까요?
`NUMBER_OF_LOTTERY_NUMBERS`이것 말고 또 매직넘버가 있을까요?

2020-12-08 15:48 UTC, joongs commented on src/main/java/lottery/domain/LotteryResult.java
> +    Map<LotteryValue, Integer> lotteryResultMap;
![image](https://user-images.githubusercontent.com/8574015/101505631-e775fd80-39b7-11eb-9cc4-2c2417fca22b.png)

기본이 `package private`이네요, 해당 클래스에서만 사용하는것으로 `private`으로 변경하겠습니다.

2020-12-08 15:56 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicket.java
> +        this.lotteryNumbers = new TreeSet<>();
네 해당건으로 하겠습니다.
간단하게 되는걸 제가 돌아서 처리를 했네요. 👍