🚀 3단계 - 로또(2등)
next-step/java-lotto pull request #1015
Opened 2020-12-03 14:33 UTC by jaehee0145

안녕하세요 😄 
3단계 리뷰 부탁드립니다 🙏 

LottoNumber 테스트는 혹시 테스트 값을 수정하라는게 아니라 
아예 다른 방법을 사용하라는 말씀이실까요? 🤔 
답변해주시면 다시 수정해보겠습니다.

감사합니다 🍒🍒

2020-12-04 01:43 UTC, yongdae requested changes
안녕하세요. 재희님. 😄

미션 3단계를 잘 진행해주셨네요. 👍👍

질문하신 내용에 대해서는 테스트 코드에 의견을
남겨놓았으니 확인하시면 될 것 같아요.

미션 진행해주신 내용에 대해 의견 남겨 놓았습니다.
리뷰 확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

수고하셨습니다. 🔥🔥

2020-12-04 01:43 UTC, yongdae commented on src/main/java/lotto/view/ResultView.java
>      }
출력 결과가 미션과 다른 부분이 있어요. :)

<img width="476" alt="Screen Shot 2020-12-04 at 10 20 11 AM" src="https://user-images.githubusercontent.com/4317804/101109552-80a0bf00-361a-11eb-87e6-03d392b29cad.png">
미션

<img width="413" alt="Screen Shot 2020-12-04 at 10 20 29 AM" src="https://user-images.githubusercontent.com/4317804/101109572-88f8fa00-361a-11eb-9cc9-826db43325d6.png">
재희님 미션 결과

보너스볼 일치에 대한 출력 부분과 수익률을 기준으로 손해인지 아닌지 판별해주는 부분이
미션에서 요구하는 것과 달라요. 확인부탁드려요~ 😄

2020-12-04 01:43 UTC, yongdae commented on src/main/java/lotto/domain/Rank.java
> +    }
보너스 번호에 대한 확인까지 잘 구현해주셨네요. 👍👍

2020-12-04 01:43 UTC, yongdae commented on src/main/java/lotto/domain/Rank.java
> +    int profit;
접근제한자를 추가하면 어떨까요? :)

접근제한자가 없는경우 default 접근제한자를 사용하지만
제한자를 표현해주면 명확하게 이해하기 쉬워질것 같아요 ~ 😄

2020-12-04 01:43 UTC, yongdae commented on src/main/java/lotto/domain/Scanner.java
> +    private List<LottoNumber> winningNumbers;
winningNumbers도 일급컬렉션을 활용해보면 어떨까요?

단순히 목록형 LottoNumber를 쓰는것보다 일급컬렉션을 이용하면
이름까지 지어줄수 있어서 의미를 분명하게 인지시켜줄수 있을것 같아요. :)

2020-12-04 01:43 UTC, yongdae commented on src/main/java/lotto/domain/Scanner.java
>      }
메소드를 위치를 옮겨보면 어떨까요?

Scanner 대신에 LottoResult가 scanAll 기능을 가지게하면 어떨까요?
메소드명도 바꾸면 더 좋을것 같아요. 😄

2020-12-04 01:43 UTC, yongdae commented on src/test/java/lotto/LottoNumberTest.java
>      public void new_lotto_number(int input) {
지금은 예외상황에대한 테스트만 있어요.

경계값 분석을 여기서 활용하면 정상적으로 생성되는 경우와
정상적이지 않은 경우의 값을 이용하면 될 것 같아요. 😄

예를 들면 0, 1, 45, 46 이 값을 넣었을때 테스트가 통과가되면 되지 않을까요?

2020-12-05 02:27 UTC, jaehee0145 commented
안녕하세요 용대님 😄 
말씀해주신대로 수정해봤습니다! 

`Scanner 대신에 LottoResult가 scanAll 기능을 가지게하면 어떨까요?`
이 피드백은 설명을 부탁드려도 될까요? 
LottoResult 로 옮기는게 좋아보이기는 하는데 말로 설명하기는 어려운거 같아서 
설명해주시면 좋을거 같습니다 🙏 

즐거운 주말보내세요!
감사합니다 🍎

2020-12-05 04:46 UTC, yongdae requested changes
피드백을 잘 반영해주셨네요. 👍👍
수고하셨습니다!! 🔥

일단 질문해주신 부분에대해 답변드리면
Scanner의 scanAll은 당첨 결과를 반환하는 기능을 구현하고 있는데 이런 질문을 해볼 수 있을 것 같아요.

1. 로또 당첨 결과 반환 이라는 책임은 Scanner이 가지고 있는게 맞을까?
2. 로또 당첨 결과 반환이라는 기능을 표현하면 scanAll 보다 더 적합한 표현은 없는가?

추가로 반영해주신 내용에대해 의견 남겨놓았습니다.
확인하시고 다시 리뷰 요청 부탁드려요~ 😄

언제든 필요하시다면 DM으로 편하게 이야기해주세요. 🙇

2020-12-05 04:46 UTC, yongdae commented on src/test/java/lotto/LottoNumberTest.java
>      public void new_lotto_number(int input) {
테스트가 실패해요. 😭
<img width="1592" alt="Screen Shot 2020-12-05 at 1 04 55 PM" src="https://user-images.githubusercontent.com/4317804/101233228-95548400-36fa-11eb-8344-327ba25d1aa8.png">

2020-12-05 04:46 UTC, yongdae commented on src/main/java/lotto/domain/WinningNumbers.java
> +public class WinningNumbers {
포함 관계를 이용해서 잘 분리해주셨네요. 👍

2020-12-05 04:46 UTC, yongdae commented on src/main/java/lotto/view/ResultView.java
> +        if (lottoResult.getProfitRatio() < 1) System.out.println("(기준이 1이기 떄문에 결과적으로 손해라는 의미)");
손해에대한 출력도 같이 해주면 어떨까요? 😄

미션에서는 손익률을 기준으로 손해만 표현해주었지만
추가적으로 이득인 경우도 보여주면 더 좋을 것 같아요 ~

2020-12-05 08:58 UTC, jaehee0145 commented on src/test/java/lotto/LottoNumberTest.java
>      public void new_lotto_number(int input) {
실패, 성공 테스트를 분리해서 작성했습니다!

2020-12-05 08:58 UTC, jaehee0145 commented on src/main/java/lotto/view/ResultView.java
> +        if (lottoResult.getProfitRatio() < 1) System.out.println("(기준이 1이기 떄문에 결과적으로 손해라는 의미)");
손익 출력 메서드를 추가했습니다!

2020-12-05 10:27 UTC, yongdae approved these changes
안녕하세요. 재희님 ~

주말에도 열심히 피드백을 반영해주셨네요. (🔥 - 🔥)/
수고하셨습니다. 🙇

이제 마지막 단계를 진행해주시면 될 것 같아요~
추가로 의견도 남겨놓았습니다. 확인 부탁드려요. 😄

2020-12-05 10:27 UTC, yongdae commented on src/main/java/lotto/domain/Scanner.java
> +    public static void scan(LottoTicket lottoTicket, LottoResult lottoResult) {
https://github.com/next-step/java-lotto/pull/1015#discussion_r535771522
이 내용과 같은 부분인 것 같아요.

https://github.com/next-step/java-lotto/pull/1015#pullrequestreview-545408213
문의를 주셔서 추가적으로 의견을 드렸었는데 아니라고 생각하신다면 한번 더 이야기 부탁드려요. 😄

2020-12-05 10:27 UTC, merged