[로또] 3단계 - 로또(2등)
next-step/java-lotto pull request #1024
Opened 2020-12-06 00:02 UTC by hsik0225

안녕하세요. 이번 피드백도 잘 부탁드립니다😄

### 지난 미션 피드백 적용
- 로또가 로또 숫자를 가지고 있는지 여부를 반환하는 메소드를 구현함으로써 디미터 법칙을 지키도록 수정
- WinningRecord#record() 에서 WinningCount를 반환하도록 수정

2020-12-06 14:25 UTC, enemfk777 requested changes
안녕하세요 현식님 :)
전단계에서 구조를 잘 잡아주셔서 수월하게 미션을 진행해 주신것 같네요 👍
불변과 관련된 몇가지 간단한 피드백 드렸으니 반영후 다시 PR 부탁드립니다!!
코로나가 극심한데 건강 조심하세요!!

2020-12-06 14:25 UTC, enemfk777 commented on src/main/java/lotto/domain/WinningRecord.java
> +            Rank rank = Rank.valueOf(matchCount, matchBonus);
```suggestion
        Map<Rank, Long> collect = lottoes.getLottoes()
            .stream()
            .map(lotto -> Rank.valueOf(winningLotto.countContainNumbers(lotto), lotto.contains(bonusBall)))
            .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
```

winningCount는 WinningRecord에서 생성된 이후 내부의 값은 불변인 편이 좋을 것 같은데요,
현재 구조에서는 아쉽게도 increaseCount를 통해 언제든지 변경이 가능한 구조네요 😊

코멘트 드린 방법처럼 Map을 만들어서 winningCount 생성자에 바로 넘기고, 
winningCount 내부에서는 unmodifiableMap으로 가지고 있는다면 불변이 보장되는 좀 더 안전한 코드가 될 것 같습니다 :)

2020-12-06 14:25 UTC, enemfk777 commented on src/main/java/lotto/view/InputView.java
> +    private static final String EMPTY = "";
접근제한자를 변경해주셨네요 👍

2020-12-06 14:25 UTC, enemfk777 commented on src/main/java/lotto/domain/Lotto.java
> +        final List<LottoNumber> numbers = new ArrayList<>(lottoNumbers);
final 키워드를 사용하신 이유가 어떤게 있을까요 ?  😊
혹시 불변 객체를 반환하려고 의도하셨던 걸까요?? 
final은 재할당을 막는 키워드로, final을 선언해도 해당 변수의 객체가 불변이 되지는 않습니다.
불변 리스트를 반환하실 땐 Collections.unmodifiableList를 사용해주세요!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Lotto 특성상 numbers가 한번 정해지면 바뀔일이 없는데요,
그렇다면 생성 할때 Collections.unmodifiableSet을 이용해서 불변 Set으로 만들어 주시는 편이 좋을 것 같습니다 :)
Set을 List로 바꾸신 이유는 정렬 때문이실까요?? 그렇다면 TreeSet에대해서 한번 알아보시면 좋을 것 같습니다 😊

2020-12-06 14:25 UTC, enemfk777 commented on src/main/java/lotto/domain/Lotto.java
> +public final class Lotto {
클래스에 final 키워드를 사용하신 이유는 어떤게 있을까요? 😊

2020-12-06 14:25 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoNumber.java
> +    protected static final String OUT_BOUND_MESSAGE = "숫자는 1 ~ 45 사이의 값을 가져야 합니다!";
final키워드 때문에 상속이 불가능한 클래스가 되었는데 protected 접근제한자를 사용하신 이유가 있을까요? 
test코드에서 사용할 목적이셨다면, default 접근제한자를 사용하셔도 괜찮을 것 같습니다.

그리고, protected 접근 제한자는 public 접근제한자 아래 위치하는 것이 java 코딩 컨벤션이랍니다 😊
아래 링크의 3. 1. 3 Class와 Interface 선언을 참고해주세요!
https://myeonguni.tistory.com/1596

2020-12-06 19:15 UTC, hsik0225 reviewed
좋은 리뷰 감사합니다!

피드백을 적용하여 다음과 같이 수정해보았습니다.
- 상수 및 메소드의 접근 제한자를 가능하다면 `defalut` 로 수정
- List, Set, Map의 Collection들을 Unmodifiable로 설정
- 기존 WinningRecord에서 하던 당첨 결과 카운트를 `Lottoes` 클래스 당첨 로또 번호와 보너스 볼을 입력받아 카운트하도록 수정

2020-12-07 14:06 UTC, enemfk777 approved these changes
빠르게 피드백 반영해주셔서 감사합니다!! 😊
final 키워드를 사용해 주신 이유에 대해서도 이해가 됐습니다 👍
final 키워드로 의도를 잘 나타내 주셨네요 💯 

이번 step은 이만 Merge하겠습니다!!
그럼 다음 step으로 가볼까요? 😊

2020-12-07 14:06 UTC, merged