[로또] 4단계 - 로또(수동)
next-step/java-lotto pull request #1036
Opened 2020-12-08 16:18 UTC by hsik0225

안녕하세요, 이번 리뷰도 잘 부탁드립니다😄

+ 이번에 미션하면서 궁금한 점이 있는데, `InputView`에서만 사용하는 `Validator` 클래스들은 `domain` 패키지에 있느 것이 맞을까요? `view` 패키지에만 있는 것이 맞을까요? 
하는 일이 무언가를 보여준 `view` 와는 맞지 않아서 일단 `domain` 패키지에 넣었는데, `view`패키지에서만 사용한다면 `view`패키지에 있어도 괜찮을 것 같아서 헷갈리네요.

2020-12-09 14:52 UTC, enemfk777 commented
> 이번에 미션하면서 궁금한 점이 있는데, InputView에서만 사용하는 Validator 클래스들은 domain 패키지에 있느 것이 맞을까요? view 패키지에만 있는 것이 맞을까요?
> 하는 일이 무언가를 보여준 view 와는 맞지 않아서 일단 domain 패키지에 넣었는데, view패키지에서만 사용한다면 view패키지에 있어도 괜찮을 것 같아서 헷갈리네요.

Validator 클래스에 대한 의문이 생기셨군요 😊
개인적으로 질문 주시길 기대하던 부분이었습니다! 
질문 해주셔서 감사해요 🙇‍♂️ 👍

LottoValidator, LottoNubmerValidator와 같이 분명 domain 객체와 함께 있어야 할 것 처럼 보이는 Validator클래스가 현재 View에서만 쓰이고 있어 패키지를 나누려니 어색함을 느끼신 것 같네요 😁

객체가 스스로 책임을 지는 객체지향 프로그래밍에서는 사실 Validator 클래스가 따로 분리되어 있는게 어색한 형태입니다.
객체 스스로 생성 - 검증 - 행위를 책임지는게 응집도가 높은 형태겠죠 😊?

그래서 권해드리고 싶은 형태는 각 도메인 클래스에서 검증해야 하는 행위는 생성자에서 검증을 해주시는 것 입니다. (Lottonumber는 1-45범위 검증, Lotto는 중복값이 없는지 등)

그리고 지금 있는 Validator 역시 필요합니다. 도메인 객체 뿐만 아니라 Input값에 대한 검증 역시 필요하니까요.
InputView내에서 비슷한 코드를 줄이는 측면에서 현재 Validator는 효과적인 것 같습니다.
단, view 패키지로 옮기고, InputValidator와 같이 view에서 쓰이는 Validator라는 것이 나타나는 이름이 되면 좋을 것 같습니다 😊

도메인 로직과 뷰가 java 안에서 만들어져 중복 로직을 생성 하는 것 처럼 느껴지실 수 있는데요,
보통 어플리케이션을 만들 때 사용자 view에서도 validation을 하고, 서버에서도 validation을 하는걸 생각해 보신다면 자연스러운 로직이라고 생각되실 것 같습니다 😊

답변이 꽤 길어 졌는데, 현식님이 이해하시는데 도움이 되었다면 좋겠네요!

2020-12-09 14:53 UTC, enemfk777 requested changes
안녕하세요 현식님! 😊
마지막 단계까지 오신만큼 피드백 드릴부분이 많지않아
질문주신 내용에 대한 답변과 더불어 한가지 피드백을 드렸습니다!!

확인 후 다시 PR 부탁드립니다!! 🙇‍♂️

2020-12-09 14:53 UTC, enemfk777 commented on src/main/java/lotto/LottoMachine.java
> +        Lottoes autoLottoes = new Lottoes(autoLottoCount);
Lottoes가 Manual과 auto 둘로 나뉘어져 있지 않아도 될 것 같습니다 😊
하나의 Lottoes에 들어가도 괜찮을 것 같은데요, 이번 구매애 산 로또들이니까요!
manual auto 구분을 하려면 Lottoes 객체를 변수명으로 나누기 보다는, Lotto 클래스 내에 멤버 변수로 가지고 있는 편이 좀 더 자연스러울 것 같습니다 :)

2020-12-09 14:53 UTC, enemfk777 commented on src/main/java/lotto/LottoMachine.java
> +        LottoResult result = new LottoResult(lottoChecker, manualLottoes, autoLottoes);
LottoChecker 클래스 내에 Lottoes를 인자로 받아 LottoResult를 만들어 반환하는 메서드를 만들어 보시는건 어떨까요? 😊

2020-12-10 00:01 UTC, hsik0225 commented
### 수정 사항
- 하나의 Lottoes 안에 자동, 수동 로또가 모두 포함되도록 수정
- LottoResult는 수동 WinningCount와 자동 WinningCount를 담은 클래스였다. 하나의 Lottoes안에 수동, 자동 모두 담기게 되었으므로 필요없어지게 되었으므로 LottoResult 클래스 삭제
- Lotto 클래스와 LottoNumber 클래스에 유효성 검사 기능 추가

2020-12-10 16:51 UTC, enemfk777 approved these changes
안녕하세요 현식님 :)
마지막 피드백까지 잘 반영해주셨네요!! 💯 👍
고생 많으셨습니다 🙇‍♂️ 저와의 미션은 여기까지입니다!
마지막 단계까지 열심히해주셔서 감사했어요 😊
제 피드백이 앞으로도 현식님께 도움이 되었으면 좋겠네요.
끝까지 완주하시길 응원할게요!!
그럼 다음 미션인 사다리 미션을 수행하러 가시죠!!

2020-12-10 16:51 UTC, merged