[Step 1] String add Calculator
next-step/java-lotto pull request #1051
Opened 2020-12-11 13:00 UTC by jaenyeong

안녕하세요 로또 미션 첫번째 과제 문자열 덧셈 계산기 제출 합니다!

잘못된 설계 방향으로 진행중이거나 안좋은 코딩 습관 등
개의치 마시고 조언 및 피드백 부탁드립니다. ㅎㅎ

감사합니다!

2020-12-11 23:51 UTC, seogi89 requested changes
안녕하세요 😄 두번째 미션 리뷰어를 맡은 이재석입니다.

문자열 계산기 미션을 잘 구현해주셨네요 💯
다만 문제의 요구사항에 비해 코드가 너무 어려운 것 같아요.
관련하여 코멘트 남겨 놓았으니 리펙토링 진행해주세요 :)

앞으로 과정 진행하면서 저와 의견이 다르거나 궁금한점 있으면 편하게 코멘트 또는 DM 남겨주세요.

재녕님과 함께 할 수 있게 되어 무척 기쁜 마음입니다. :)
모쪼록 다음 코드 기대하며 기다리고 있을게요. 🙇

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Output.java
> +    }
앗 여지껏 생각해보지 못한 발상이네요. 👍 
입력에 관련한 문구는 입력에서 처리해 왔는데 🤔 

어떤 장/ 단점이 있을까요?

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Input.java
> +}
값을 입력받는 객체라기보다는 UI 라고 생각해보면 어떨까요?

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +    private static int parseInt(final String exp) {
바이패스의 역할만 하는 메소드가 필요 할까요?
`import static` 을 활용 할 수 있을 것 같아요.

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Validator.java
> +        return (exp.length() == 1);
각각 괄호에는 어떤 의미가 있나요?

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +        final Matcher matcher = Pattern.compile(CUSTOM_SEPARATOR).matcher(exp);
> 아이템 6. 불필요한 객체 생성을 피하라

Pattern은 매우 비싼 자원입니다.
미리 생상해두고 재활용한다면 어떠한 장점이 있을까요?

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +    protected static List<Integer> splitWhenNumberIsNaturalNumber(final String exp) {
별도로 분리해서 얻을 수 있는 장점이 무엇일까요?

하나의 숫자를 입력받아도 구분자로 나눈 후 덧셈하면 똑같은 값이 나올 수 있을 것 같아요.

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +    protected static List<Integer> splitWhenNumberIsNaturalNumber(final String exp) {
리소스를 아끼기 위해서는 하나의 숫자라면 바로 결과를 응답해주는게 좋을 것 같구요

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +public class Parser {
클린 코드를 의식하여 오히려 복잡도가 올라간 것 같아요.
스프트웨어는 `최소한의 노력으로 최대한의 효율`을 내는 것이 가장 좋다고 생각합니다.
최대한 쉽게 문제를 해결할 수 있는 방법을 고민보면 좋겠습니다.

외부로 제공되는 메소드와 아닌 메소드의 구분도 어렵네요. 불필요한 메소드를 제거하고 간단하게 작성해보면 좋을 것 같아요.

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +        exp = exp.trim();
[규칙 5: 축약 금지](https://developerfarm.wordpress.com/2012/01/30/object_calisthenics_6/)

>누구나 실은 클래스, 메서드, 또는 변수의 이름을 줄이려는 유혹에 곧잘 빠지곤 한다. 
그런 유혹을 뿌리쳐라. 축약은 혼란을 야기하며, 더 큰 문제를 숨기는 경향이 있다.

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Validator.java
> +        return (exp.length() == 1);
`1` 대신 의미를 명시하는 상수를 사용하면 좋을 것 같습니다 :)
이외 다른 부분에 대해서 매직넘버를 사용하는 부분도 상수로 치환하여 사용해보는것을 추천드립니다.

> 클린코드 > G25: 매직 숫자는 명명된 상수로 교체하라

2020-12-11 23:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Validator.java
> +public class Validator {
>아이템 4. 인스턴스화를 막으려거든 private 생성자를 사용하라

유틸리티 클래스의 경우 인스턴스를 만들기 위해 설계된 것이 아니기 때문에 해당 규칙을 적용할 수 있을 것 같아요!"

2020-12-12 09:53 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Output.java
> +    }
아 저는 개인적으로 UI 부분 또한 입력과 출력이 별개의 역할과 책임을 가진 객체로 나뉘어야 한다라고 생각합니다.
그래서 무의식적으로 나눠버렸는데요
물론 주요 이유는 확장성과 솔리드 원칙에 의해 단일 책임 원칙을 지켜야 하기 때문인데
이와 같은 간단한 요구사항에는 하나의 UI로 작성해도 괜찮다고 생각 합니다.

2020-12-12 09:56 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Input.java
> +}
위와 같은 내용으로 답변할 수 있겠네요
하나의 UI 처럼 리팩토링 해보겠습니다.

2020-12-12 09:56 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +    private static int parseInt(final String exp) {
음 제가 이해를 제대로 못했는데 import static 을 활용하라는게 어떤 의미인가요?
예시를 들어주실 수 있나요??

2020-12-12 10:00 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +    protected static List<Integer> splitWhenNumberIsNaturalNumber(final String exp) {
조언 감사합니다 해당 부분은 말씀 하신 방향으로 처리하겠습니다!

2020-12-12 10:04 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Validator.java
> +        return (exp.length() == 1);
해당 질문은 (exp.length() == 1); 이 부분에서 바깥 괄호의 역할을 물어보시는건가요?

2020-12-12 10:06 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +        final Matcher matcher = Pattern.compile(CUSTOM_SEPARATOR).matcher(exp);
인스턴스 생성 시간 혹은 정규식 패턴을 처리하는 리소스가 줄어들겠죠.
해당 부분은 그냥 복붙하느라 거기까진 생각하지 못했네요!
메서드 밖으로 추출하는 방식으로 리팩토링 하겠습니다.

2020-12-12 10:06 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +public class Parser {
말씀하신 부분을 유념하여 수정해보겠습니다.

2020-12-12 10:09 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +        exp = exp.trim();
저도 해당 부분을 알고 있습니다만
MIN, MAX와 같이 대다수가 알고 있는 축약어거나
해당 부분처럼 문맥상 해당 축약어를 쉽게 알 수 있는 흐름을 갖고 있다면 굳이 풀네임으로 작성하지 않아도 괜찮다고 생각합니다.
이에 대해 더 확실한 기준이 있나요?

2020-12-12 10:09 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Validator.java
> +        return (exp.length() == 1);
네 해당 부분은 수정하도록 하겠습니다.

2020-12-12 10:11 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Validator.java
> +public class Validator {
이펙티브 자바를 인용하신것 같네요
해당 책을 2판도 보고 3판도 봤는데.. 까먹었네요.. ㅠ
모든 내용이 그렇듯 해당 조언들이 습관이 되기전에 까먹어 버리는 경우가 흔해서 참 힘이 드네요 ㅎㅎ
상기 시켜 주신대로 변경하겠습니다.

2020-12-12 10:40 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Validator.java
> +        return (exp.length() == 1);
네. 바깥 괄호가 꼭 필요할까요 ? 🤔

2020-12-12 10:43 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +    private static int parseInt(final String exp) {
```
import static java.lang.Integer.parseInt;

public void foo(String number){
...
parseInt(number)
...
}
```

위와 같이 사용해도 괜찮을 것 같아요.

2020-12-12 10:48 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +        exp = exp.trim();
저는 문맥, 즉 앞 뒤 관계를 모르더라도 이해할 수 있도록 변수명을 지어야 한다고 생각하는 편입니다.
특히나 exp 같은 경우에는 예를 드신 max,  min 보다 모호함이 더 큰 변수명이라고 생각하는데요

개인적으로 exp 는 expression 보다는 exponential function 가 먼저 떠오르는 변수명이네요 😁 

추가적으로 해당 수업에 의미를 생각했을때 과하다 싶을 정도로 규칙을 지키면서 코딩을 해보면 좋을 것 같아요 :)

2020-12-12 10:51 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/Parser.java
> +    private static int parseInt(final String exp) {
메소드를 한번 감싸서 사용하는 이유를 딱히 찾을 수 없네요.

2020-12-12 11:11 UTC, jaenyeong commented on src/main/java/com/jaenyeong/mission01/calculator/Validator.java
> +        return (exp.length() == 1);
꼭 필요하지 않습니다만 저는 가독성을 위해 비교 조건 구문 등에는 괄호를 항상 치는 습관을 들이고 있습니다
꼭 두 개 이상의 조건을 나열해서 구분할 때만이 아닌 위와 같은 상황에서도 괄호를 가급적 사용하고 있습니다.

2020-12-13 07:10 UTC, seogi89 approved these changes
피드백 잘 반영해주셨네요 :) 

본격적으로 로또 미션 진행해주시면 될 것 같아요.

2020-12-13 07:10 UTC, seogi89 commented on src/main/java/com/jaenyeong/mission01/calculator/StringAddCalculator.java
> +        return getSum(inputNumbers);
```suggestion
        return getSum(inputNumbers);
```

해도 동일한 결과를 리턴 할 것 같아요. 어떻게 생각하시나요?

2020-12-13 07:10 UTC, merged