Step2 : 로또(자동)
next-step/java-lotto pull request #1070
Opened 2020-12-13 04:29 UTC by rlapwl

안녕하세요 리뷰어님.😊
문자열 계산기 부분 저번에 달아주신 대로 좀 수정하였습니다.
이번에도 로또 리뷰 잘 부탁드립니다!!

2020-12-13 07:55 UTC, wbluke requested changes
구현해주신 step2 로또 미션 잘 봤습니다!
전체적으로 구조를 깔끔하게 잘 잡아주셨네요 👍 
다음 단계 넘어가기 전에 한번 짚고 넘어가면 좋을 것 같아서 피드백 남겼습니다.
확인해주시고 재요청 부탁드려요! 🙂

2020-12-13 07:55 UTC, wbluke commented on src/main/java/calculator/domain/ExpressionSplitter.java
>          Matcher m = Pattern.compile(CUSTOM_REGEX).matcher(expression);
저번 리뷰 때 놓쳐서 말씀드리지 못했던 부분인데요.
- split할 때마다 Pattern이 계속 재생성되는 구조라, 정규식 문자열 대신 Pattern을 상수화하면 좋을 것 같아요.
- 축약어는 사용하지 않는 것이 좋습니다!

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/domain/Money.java
> +    private static final int MONEY_OF_ONE_TICKET = 1000;
애플리케이션 전체적으로 Money가 long 타입이니 이 상수도 long이면 좋을 것 같네요 :)

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/domain/LottoTicketFactory.java
> +    private final static int SPLIT_END_INDEX = 6;
```suggestion
    private static final int LOTTO_START_NUMBER = 1;
    private static final int LOTTO_END_NUMBER = 45;
    private static final int SPLIT_START_INDEX = 0;
    private static final int SPLIT_END_INDEX = 6;
```

다른 코드에도 순서를 잘못 쓴 상수가 있는 것 같은데 같이 확인해주세요!

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/domain/numbers/LottoNumber.java
> +            throw new IllegalArgumentException("숫자는 1부터 45까지여야 합니다.");
error message에도 위에 정의해 놓은 상수를 이용할 수 있겠네요.
`String.format`

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/domain/LottoMachine.java
> +                .forEach(i -> lottoTickets.add(lottoTicketFactory.makeLottoTicket()));
많은 부분에서 반복문 대신 Stream을 많이 사용하셨는데요.
가독성, 유지보수 측면에서 반복문으로 명시하는 것이 훨씬 좋을 때가 많습니다.
Stream은 꼭 필요한 순간에만 사용해보시기를 권장드려요 :)
https://johngrib.github.io/wiki/java-stream/#%EC%A3%BC%EC%9D%98%ED%95%A0-%EC%A0%90

+) list.forEach() 문도 일반 for-each로 작성하는게 더 명확하다고 생각합니다ㅎㅎ

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/view/OutputView.java
> +    }
LottoTickets와 LottoTicket이 모두 일급컬렉션인데요. (구조 잘 잡아주셨네요 👍 )
일급컬렉션으로서의 역할을 좀 더 주면 좋을 것 같아요.
내부 필드를 직접 꺼내서 사용하는 방법 대신에 내부에서 가공해서 반환하는 방법을 사용한다면 어떤 부분들이 개선될 수 있을까요?
한번 애플리케이션 전반적으로 고민해보시면 좋을 것 같아요! :)

Tip) getter가 없다고 생각하면서 구현해 나가다가 정말 필요한 순간에만 getter를 만든다.

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/domain/MatchPrize.java
> +    SIX(6, 2000000000);
enum 사용 💯 
여기 금액도 long 타입이면 좋겠네요. (보통 금액은 int 범위를 넘어갈 수 있어서 long을 씁니다)

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/domain/LottoGame.java
> +    private static final int INTI_COUNT = 0;
오타같네요 :)

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/domain/LottoGame.java
> +            lottoResult.put(MatchPrize.valueOf(matchCount), lottoResult.get(MatchPrize.valueOf(matchCount)) + 1);
공통인 부분 추출할 수 있을 것 같아요 :)

2020-12-13 07:55 UTC, wbluke commented on src/main/java/lotto/domain/LottoResult.java
> +                .mapToLong(matchPrize -> matchPrize.getMoney() * result.get(matchPrize))
좀 더 객체지향적으로 코드를 작성하려면 어떻게 하면 좋을까요? :)

2020-12-13 09:00 UTC, rlapwl commented on src/main/java/calculator/domain/ExpressionSplitter.java
>          Matcher m = Pattern.compile(CUSTOM_REGEX).matcher(expression);
네!!

2020-12-13 09:08 UTC, rlapwl commented on src/main/java/lotto/domain/LottoTicketFactory.java
> +    private final static int SPLIT_END_INDEX = 6;
네! 제가 실수했네요!!ㅠ

2020-12-13 12:27 UTC, rlapwl commented on src/main/java/lotto/domain/LottoMachine.java
> +                .forEach(i -> lottoTickets.add(lottoTicketFactory.makeLottoTicket()));
네~ 감사합니다!!

2020-12-13 13:01 UTC, rlapwl commented on src/main/java/lotto/domain/LottoResult.java
> +                .mapToLong(matchPrize -> matchPrize.getMoney() * result.get(matchPrize))
MatchPrize가 책임을 가지도록 구현해보았습니다.

2020-12-13 13:27 UTC, rlapwl commented
안녕하세요 리뷰어님!
자세한 리뷰 감사합니다. 하나씩 읽어가며 수정해보았는데요.
제가 놓친 부분들을 확인해가며 작업할 수 있어서 좋았습니다.
다시 한번 리뷰 잘 부탁드립니다!!

2020-12-13 15:28 UTC, wbluke approved these changes
리뷰 반영 감사합니다 👍 
간단한 코멘트 남겼는데요, 다음 단계 진행하시면서 같이 확인 부탁드려요 🙂

2020-12-13 15:28 UTC, wbluke commented on src/main/java/lotto/domain/LottoResult.java
> +    public LottoResult(final Map<MatchPrize, Integer> result) {
개인적인 견해입니다 :)
저도 한때 final 명시를 모든 메소드 파라미터에 해줬었는데요. (인텔리제이 설정으로)
복잡한 도메인 상황에서는 파라미터 수가 굉장히 많아지고, 그에 따라 파라미터 final 선언은 가지고 있는 효과 대비 가독성을 해치기만 하는 경우가 많더라구요.
간단하게 고민만 해보셔도 될 것 같아요 ㅎㅎ (특별히 수정은 안해주셔도 됩니다)

2020-12-13 15:28 UTC, wbluke commented on src/main/java/lotto/domain/MatchPrize.java
> +    public long multiplyMoney(int num) {
역할을 잘 분배해주셨네요 👍

2020-12-13 15:28 UTC, wbluke commented on src/main/java/lotto/domain/MatchPrize.java
> +                + money + ")- ";
toString()의 역할이 콘솔에 출력하기 위한 역할인가? 를 고민해보시면 좋을 것 같아요.
**핵심 도메인에서 출력을 위한 로직을 가지고 있는게 맞을까?** 라는 질문으로 바꿔볼 수도 있겠네요.
toString()의 본래 역할은 무엇일까요? :)

2020-12-13 15:28 UTC, merged

2020-12-14 13:12 UTC, rlapwl commented on src/main/java/lotto/domain/LottoResult.java
> +    public LottoResult(final Map<MatchPrize, Integer> result) {
네!! 조언 감사합니다!!

2020-12-14 13:19 UTC, rlapwl commented on src/main/java/lotto/domain/MatchPrize.java
> +                + money + ")- ";
되도록 get 함수를 안쓰려고 하다 보니 좀 어긋난 방향으로 구현하고 있었네요.
감사합니다!