Step2 : 로또(자동)
next-step/java-lotto pull request #1099
Opened 2020-12-15 07:25 UTC by nawhew

코드리뷰 부탁드립니다 :)
아직  TDD가 익숙하지 않아 몇가지 질문도 함께 드립니다!

질문 1. TDD로 개발이 서툴러서 테스트 하나에서 시작하다보면 어느순간 생각보다 더 많은 범위를 개발하는 것 같습니다.
혹시 지금보다 커밋을 더 세분화 해서 해야할까요?

질문 2. 
홈페이지에 보면
2-1. [모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다.]에서 모든 기능이 test에서 접근 할 수 있는 모든 public, defalut 메소드를 말하는 건가요?
2-2. 그렇다면 여기에는 getter, setter, constructor까지 모두 포함되는 개념일까요??
2-3. 만약 하나의 test에서 다른 메소드도 자연스럽게 테스트가 된다면 (위에서 말한 getter, setter, constructor) 하나의 테스트로 대체 되어도 상관없을까요?

2020-12-15 14:04 UTC, young891221 requested changes
안녕하세요, 위환님!
엄청 열심히 코드, 주석 작성해 주셨네요 👍 
구조에 대해서 피드백 드렸습니다. 확인 부탁드립니다.

2020-12-15 14:04 UTC, young891221 commented on src/main/java/lotto/LottoRunner.java
> +        this.lottoWinCalculator.setWinLottoNumbers(
조금 직접적으로 힌트를 드리자면 위의 내용을 모두 반영해서 아래와 같이 해보면 어떨까요?

```java
 private void win(Lottos lottos) {
   lottoWinCalculator calculator = new lottoWinCalculator(new Lotto(this.inputView.insertWinLottoNumbers()));
   calculator.findPirizes(lottos);
   ...
```

2020-12-15 14:04 UTC, young891221 commented on src/main/java/lotto/LottoWinCalculator.java
> +
상수는 칸 띄어쓰기를 안하셔도 괜찮습니다ㅎ

2020-12-15 14:04 UTC, young891221 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final int LOTTO_MAX_VALUE = 46;
46이 중복으로 사용되는데 상수는 한곳에서 집결해서 관리하도록 해주세요

2020-12-15 14:08 UTC, young891221 commented
질문 1. TDD로 개발이 서툴러서 테스트 하나에서 시작하다보면 어느순간 생각보다 더 많은 범위를 개발하는 것 같습니다.
혹시 지금보다 커밋을 더 세분화 해서 해야할까요?
답변 : 커밋 세분화해서 하는 방법도 전략이지만 집중하다 보면 하기 힘든것 같습니다. 테스트를 먼저 만들었는데 해당 테스트가 완료될 때 커밋을 찍는 정도로 진행하셔도 좋을것 같습니다.

질문 2.
홈페이지에 보면
2-1. [모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다.]에서 모든 기능이 test에서 접근 할 수 있는 모든 public, defalut 메소드를 말하는 건가요?
답변: 아닙니다. 말 그데로 기능에 대한 부분입니다. 예를 들어, 로또 생성하는 기능을 테스트 한다면 유효한 범위로 생성되었는지, 6개가 맞는지 기타 등에 대해서만 체크하면 됩니다.

2-2. 그렇다면 여기에는 getter, setter, constructor까지 모두 포함되는 개념일까요??
답변: 아닙니다. 기능 단위로만 해주셔도 충분 합니다.

2-3. 만약 하나의 test에서 다른 메소드도 자연스럽게 테스트가 된다면 (위에서 말한 getter, setter, constructor) 하나의 테스트로 대체 되어도 상관없을까요?
답변: 넵

2020-12-15 14:29 UTC, nawhew commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final int LOTTO_MAX_VALUE = 46;
한곳의 상수만 사용하도록 변경하였습니다

2020-12-15 14:30 UTC, nawhew commented on src/main/java/lotto/domain/LottoNumbers.java
> +    private static final int LOTTO_NUMBERS_DEFAULT_SIZE = 46;
변경하였습니다~

2020-12-15 14:35 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +        int payToSum = this.inputView.insertPayToSum();
넵 변경하였습니다

2020-12-15 15:36 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +            LottoNumbers lottoNumbers = new LottoNumbers();
LottoNumbers에서 같은 값(6개의 로또번호)에 대해 List<LottoNumber>와 List<Integer>로 나누어 넣고 빼고 형변환도 계속하게 되어
여러가지로 비효율적으로 하는 느낌이었는데, Lotto클래스를 만들어 주고 받으니 많은 부분이 해결되었습니다!

2020-12-15 15:37 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +        for (int i = 0; i < payToSum; i++) {
변경하였습니다~

2020-12-15 15:38 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +            List<Integer> pickedLottoNumbers = lottoNumbers.pickLottoNumber();
생성자에서 pickLottoNumber() 및 다른 메소드를 처리하여 로또번호 6개를 뽑아서 가지도록 변경하였습니다.

2020-12-15 15:38 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +    private int pickLotto(){
변경하였습니다

2020-12-15 16:20 UTC, nawhew commented on src/main/java/lotto/LottoWinCalculator.java
> +
적용했습니다~

2020-12-15 16:22 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +            this.lottoWinCalculator.addPickedLottoNumbers(pickedLottoNumbers);
Lottos를 추가하니 자연스럽게 win에서 당첨 관련 처리로직이 모아졌습니다.

2020-12-15 16:22 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +        this.lottoWinCalculator.setWinLottoNumbers(
네 Lottos를 추가하여 win에서 당첨 관련 작업을 하도록 반영하였습니다.

2020-12-16 00:45 UTC, young891221 requested changes
리뷰 반영 감사합니다ㅎㅎ
훨씬 깔끔해진 느낌입니다. 몇 가지 추가 개선 포인트가 보여서 코멘트 남겼습니다.
확인 부탁드립니다:)

2020-12-16 00:45 UTC, young891221 commented on src/main/java/lotto/LottoRunner.java
> +        }
이 부분은 `new Lottos()`로 옮기면 더 적절할것 같습니다.

2020-12-16 00:45 UTC, young891221 commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(LottoNumbers lottoNumbers) {
이런식의 구성 좋네요 👍

2020-12-16 00:45 UTC, young891221 commented on src/main/java/lotto/domain/LottoWinPrize.java
> +    public static void addCount(int inputMatchedCount) {
enum은 상수인데 count를 증가시키는 구조네요. 이런식으로 풀 수 있지만 만약, 게임이 끝나고 다음 게임을 그대로 진행하는 구조로 만든다면 여기 count값은 초기화되지 않습니다.
`Map<LottoWinPrize, Integer>` 형식을 들고 있는 `WinResults`와 같은 형식의 클래스로 분리하여 처리하면 어떨까요?

2020-12-16 00:45 UTC, young891221 commented on src/main/java/lotto/LottoRunner.java
> +        this.win(lottos);
win()의 반환값이 있었으면 좋겠습니다. `lottoRunner.run()`을 하는 테스트를 할 수 없기 때문입니다.
`List<LottoWinPrize>` 이 정도가 반환되면 좋을것 같네요.
나머지는 `printResult` 정도의 메서드로 분리하는 방향도 괜찮을것 같습니다.

2020-12-16 09:33 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +        }
생성자 추가하여 반영하였습니다

2020-12-16 09:34 UTC, nawhew commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(LottoNumbers lottoNumbers) {
감사합니다 :)

2020-12-16 10:52 UTC, nawhew commented on src/main/java/lotto/domain/LottoWinPrize.java
> +    public static void addCount(int inputMatchedCount) {
LottoWinResult클래스를 만들어 적용하였습니다.
앞으로 enum에 동적인 값을 넣지 않고, enum을 감싸는 클래스를 만들어서 사용하겠습니다

2020-12-16 11:10 UTC, nawhew commented on src/main/java/lotto/LottoRunner.java
> +        this.win(lottos);
메소드를 분리하면서 수익률 계산에 대한 부분을 생각하다보니
해당 로직에 필요한 메소드들이 자연스럽게 알맞는 곳으로 이동되었습니다.

2020-12-16 13:33 UTC, young891221 approved these changes
리뷰 반영 감사합니다. 위환님!
조금 많은 코멘트를 드렸는데 모두 잘 적용해 주셨네요 💯 
다음 미션 이어서 진행 부탁드립니다ㅎㅎ

2020-12-16 13:33 UTC, merged