Step2 로또 자동
next-step/java-lotto pull request #1127
Opened 2020-12-17 12:34 UTC by deviscreen

2020-12-18 07:25 UTC, slamdunk7575 commented
- 로또 추첨 카운팅 부분 확인 부탁드립니다.

![스크린샷 2020-12-18 오후 4 23 06](https://user-images.githubusercontent.com/15867808/102586462-90a5bc00-414d-11eb-8c51-ee3cbf0ae004.png)

2020-12-18 07:32 UTC, slamdunk7575 requested changes
로또 미션 구현하시느라 고생하셨습니다. 👍 
지난 피드백도 반영해주시고 열심히 하시는 모습 좋습니다.

로또 번호 추첨 카운팅 관련 코멘트와 좀 더 리팩토링 해보시면 좋을 것 같아 몇가지 피드백 남겨 놓았습니다. 
확인해보시고 다시 리뷰요청 부탁드립니다.

궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 남겨주세요. 함께 고민해보아요.🔥_🔥
건강조심하시고😷  끝까지 화이팅 입니다!

2020-12-18 07:32 UTC, slamdunk7575 commented on src/main/java/lotto/util/NumberUtil.java
> +        return numbers;
미리 1부터 45까지의 숫자를 하나씩 넣어 두었으면 어떨까요?

매번 만드는 것보다 초기화 블럭 안에서 미리 캐싱하여 사용하는 편이 좋겠네요 😄

```
   static {
        lottoNumbers = new ArrayList<>();
        IntStream.rangeClosed(LOTTO_START_NUMBER, LOTTO_END_NUMBER)
                .boxed().distinct().forEach(lottoNumbers::add);
    }
```

2020-12-18 07:32 UTC, slamdunk7575 commented on src/main/java/lotto/util/NumberUtil.java
> +    public static List<Integer> generatelottoNumberSet(){
`generateLottoNumberSet()` `카멜 케이스`를 지키는게 코드 가독성에 좋겠네요.

2020-12-18 07:32 UTC, slamdunk7575 commented on src/test/java/lotto/domain/LottoMachineTest.java
> +    }
테스트 검증 부분이 없네요 🤔 

테스트 작성시 `given-when-then`에 맞춰 작성하시면 좋습니다.
[Given-When-Then Pattern](https://brunch.co.kr/@springboot/292)

2020-12-19 03:02 UTC, deviscreen commented on src/test/java/lotto/domain/LottoMachineTest.java
> +    }
아래의 테스트 checkWinningNumbers() 의 기능은 생성된로또들을 등수를 검사해서 추출해주는 기능인데,  lottoMachine에 있는   LottoBucket에 테스트 데이터를 추가 해주기 위해서는 테스트를 위한 메서드를 만들어야할 것 같은데 좋은 방법이 있는지 궁금합니다

2020-12-19 04:29 UTC, slamdunk7575 commented on src/test/java/lotto/domain/LottoMachineTest.java
> +    }
https://github.com/next-step/java-lotto/pull/1127#discussion_r545606360

` LottoResult` 클래스를 만들어 로또 번호를 추첨하는 역할을 위임하고 `LottoBucket`을 외부에서 주입 받는 구조로 변경하면 
Test시 데이터를 만들어 테스트 해볼 수 있을 거 같아요.

아래 코드는 참고만 해주세요😄 
` public void analyzeLottoRank(LottoBucket lottoBucket, WinningLotto winningLotto) {`

참고로 `지난주 당첨 번호`도 `Lotto 클래스`(=로또 번호)로 보면 좋을 거 같아요.

2020-12-19 04:32 UTC, slamdunk7575 commented on src/main/java/lotto/view/InputView.java
> +}
`DisplayView`의 입력과 관련된 역할을 `InputView`로 옮기는게 좋을 것 같아요.

2020-12-19 05:03 UTC, deviscreen commented on src/test/java/lotto/domain/LottoMachineTest.java
> +    }
답변 감사합니다! 😊

2020-12-20 10:01 UTC, slamdunk7575 commented
출력 관련해서 아래사항 한번 확인 부탁드립니다.
- 로또 번호는 오름차순으로 출력
- 로또 번호 추첨 카운팅

![스크린샷 2020-12-20 오후 6 56 51](https://user-images.githubusercontent.com/15867808/102710438-a8b83f80-42f5-11eb-8899-8553401d22a6.png)

2020-12-20 10:17 UTC, slamdunk7575 approved these changes
피드백 반영하시느라 고생하셨습니다.

아래 사항 관련해서 코멘트 남겨드렸는데 꼭! 확인해보시고
다음 미션 진행하시면서 같이 반영부탁드립니다. 🙇 

- 몇가지 리팩토링 할 부분
- 출력 결과 확인
- 코드 컨벤션

Step2는 이만 머지하도록 하겠습니다.

궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 남겨주세요. 함께 고민해보아요.🔥_🔥 
건강 유의하시고 끝까지 화이팅 입니다!

2020-12-20 10:17 UTC, slamdunk7575 commented on src/main/java/lotto/domain/LottoResult.java
> +public class LottoResult {
`LottoResult `구현 잘해주셨네요 👍

2020-12-20 10:17 UTC, merged