🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #1139
Opened 2020-12-18 21:04 UTC by lsb156

안녕하세요 이상배입니다. 
지난번엔 포비가 리뷰해주어 이번에 처음 리뷰를 받아보네요 잘 부탁드립니다!

![image](https://user-images.githubusercontent.com/5360858/102660661-bcad5580-41be-11eb-8a8b-1f387f1b3a64.png)
이번에 구현하는데 클래스가 많아 리뷰하시는데 조금이나마 도움이 될까 싶어 대략적인 흐름을 그려보았습니다.
Domain이랑 View Package는 철저히 분리하여 테스트 가능한 객체들을 Domain에 몰아놓았습니다.

이번 과제는 DDD 스타일로 구현을 하였습니다
실제로 로또 매장가서 구매하는 방식처럼 구현을 하여 책임과 기능을 각자가 가지고 있게 분리하였습니다.

여기저기 많은 지적 부탁드립니다.

2020-12-19 08:29 UTC, serverwizard requested changes
로또(자동) 구현을 잘 해주셨습니다! 👍 

무엇보다 애플리케이션 흐름도를 작성해주신 부분 인상적이었어요 ^^

몇 가지 코멘트 남겨두었으니 확인 부탁드릴게요~
궁금한점 있으시면 편하게 코멘트 또는 DM 남겨주세요.

2020-12-19 08:29 UTC, serverwizard commented on src/main/java/com/ssabae/nextstep/lotto/domain/lotto/LottoTicket.java
> +    private final LottoNumber[] numbers;
List 자료구조를 사용하지 않으시고 Array를 사용하신 이유가 있으실까요? (개인적인 궁금함)

2020-12-19 08:29 UTC, serverwizard commented on src/main/java/com/ssabae/nextstep/lotto/view/ResultView.java
> +            earnMoney = earnMoney.plus(getWinningAmount(reward, lottoResultDto));
View에서 비즈니스 로직을 수행하기 보단, View는 받은 데이터를 가지고 화면을 그리는 역할만 수행하도록 하는 건 어떨까요?

2020-12-19 08:29 UTC, serverwizard commented on src/main/java/com/ssabae/nextstep/lotto/domain/lotto/LottoTickets.java
> +public class LottoTickets {
로또 티켓 그룹핑 역할을하는 LottoTickets(일급 콜렉션)에서 수행할 만한 일은 없을까요?
예를 들어, 당첨 번호를 LottoTickets에게 전달하며 `너가 가진 로또 티켓들과 모두 비교해서 결과를 돌려줘`란 일을 수행할 수도 있을 것 같아서요.

2020-12-19 08:29 UTC, serverwizard commented on src/main/java/com/ssabae/nextstep/lotto/domain/lotto/LottoTicket.java
> +public class LottoTicket {
LottoTicket에게 당첨번호를 전달하면 결과를 반환해주는 책임을 가지게 하는 건 어떨까요?

2020-12-19 08:29 UTC, serverwizard commented on src/main/java/com/ssabae/nextstep/lotto/domain/LottoTicketsAnalyzer.java
> +    public LottoResultDto convertToDto(LottoTickets lottoTickets, WinningNumber winningNumber) {
도메인 객체에서 Dto를 반환해주기 보단, 도메인에선 LottoResult 도메인 객체를 반환해주는 건 어떨까요?
Dto는 컨트롤러에서 View 쪽으로 데이터를 전달할 때 만들어서 반환해주시면 좋을 것 같아요.

2020-12-19 08:29 UTC, serverwizard commented on src/test/java/com/ssabae/nextstep/lotto/domain/LottoTicketsAnalyzerTest.java
> +        assertThat(countOfTicket).isEqualTo(dummyLottoTickets.getLottoTickets().size());
여러 검증을 하나로 묶어서 테스트 할 수 있게 해주는 assertAll()을 학습해보시면 좋을 것 같아요!

2020-12-19 08:29 UTC, serverwizard commented on src/test/java/com/ssabae/nextstep/lotto/domain/lotto/ticketgenerator/TestLottoTicketGenerator.java
> +public class TestLottoTicketGenerator implements LottoTicketGenerator {
테스트를 위한 TestLottoTicketGenerator 생성 :+1:

2020-12-20 11:45 UTC, lsb156 commented on src/main/java/com/ssabae/nextstep/lotto/domain/lotto/LottoTicket.java
> +    private final LottoNumber[] numbers;
그냥 단순히 varargs를 사용하기 위함이였습니다.
LottoTicket을 생성할때 list로 묶어서 생성해야 하는 오버헤드를 한번 줄이기 위함이였는데
아무래도 Collections, Arrays를 병행해서 사용하다보니 일관성이 더 없어지는거 같아서 List로 변경해놓겠습니다

2020-12-20 13:31 UTC, lsb156 commented on src/main/java/com/ssabae/nextstep/lotto/application/LottoApplication.java
> +        LottoResultDto lottoResultDto = analyzer.convertToDto(lottoTickets, winningNumber);
Service역할하는 객체를 하나 만들어서 적용하면 좋을거같다고 생각해서 만드려 했었는데
LottoTicketMachine이 이미 많은 역할을 하여 Analyzer를 LottoTicketMachine안에 넣어서 Domain Service 하는 객체로 만들어 주었습니다.
우리가 실제로 로또를 사거나 로또 당첨금 수령할때도 로또 기계에서 처리를 하여 일부러 DomainService라는 이름대신 LottoTicketMachine 그대로를 사용하였습니다.

2020-12-20 13:58 UTC, lsb156 commented on src/main/java/com/ssabae/nextstep/lotto/domain/LottoTicketsAnalyzer.java
> +    public LottoResultDto convertToDto(LottoTickets lottoTickets, WinningNumber winningNumber) {
LottoResult를 반환하게 하고 그걸 LottoResultDto로 변환해서 반환하는 형태로 변경하였습니다.

2020-12-20 14:11 UTC, lsb156 commented
구조를 다시한번 정리하게 되었네요
꺼림찍했던 것들이 조금은 많이 해결된거 같아서 좋습니다.
더 수정할 내용있으면 많이 남겨주세요

2020-12-21 12:42 UTC, serverwizard approved these changes
로또(자동) 구현을 잘 해주셨습니다! 크게 피드백 드릴게 없었어요!! 👍 

간단한 코멘트만 남겼으니 다음 Step 진행하실 때 참고만 부탁드릴게요~

다음 Step도 화이팅입니다! 🔥 
감사합니다!

2020-12-21 12:42 UTC, serverwizard commented on src/main/java/com/ssabae/nextstep/lotto/domain/lotto/ticketgenerator/AutoLottoTicketGenerator.java
> +    private final List<LottoNumber> lottoNumbers;
객체가 생성되기 전에 미리 LottoNumber를 만들어서 List < LottoNumber > lottoNumbers에 초기화 해두는 건 어떨까요?
```
힌트: static 블록
```

2020-12-21 12:42 UTC, serverwizard commented on src/main/java/com/ssabae/nextstep/lotto/domain/LottoResult.java
> +        return (float) earnMoney.amount.longValue() / spendMoney.amount.longValue();
객체에서 값을 꺼내지 말고, 메시지를 전달하는 건 어떨까요?

2020-12-21 12:42 UTC, merged