4단계 - 로또(수동)
next-step/java-lotto pull request #1155
Opened 2020-12-21 14:59 UTC by joongs

### 제목
4단계 - 로또(수동)

### 작업내용 (step3 피드백)
- [x] static 으로 이루어진 클래스는 기본 생성자를 private으로 선언하여 객체 생성을 막아보세요.- `LotteryTicketFactory.java`
      https://ktko.tistory.com/entry/Effective-Java-4-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EC%9D%84-%EB%A7%89%EC%9D%84-%EB%95%8C%EB%8A%94-private-%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC?category=753411
- [x] 이번 미션을 진행하면서 삼항 연산자 보다는 조건문을 풀어서 사용해보세요 ! (`LotteryWinning.java`)
- [x] 매번 Integer.parseInt 코드를 사용하는것 보단 LotteryNumber 의 생성자를 늘려보거나 정적 팩토리 메소드를 사용해보세요 - `LotteryWinning.java`
      https://johngrib.github.io/wiki/static-factory-method-pattern/
- [x] 일반적으로 getXXX 는 객체가 가진 상태값을 반환하는것을 기대하게 되는것 같아요. - `LotteryWinning.java`
      LotteryResult 는 상태값이 아니니 조금더 의미있는 메소드명을 고민해보면 좋을것 같습니다 ㅎㅎ - `LotteryResult.java`
- [x] purchaseAmount에 따라서 profit 값이 자주변경될것 같은데, 상태값으로 가지고 있기보다는 calculateProfit 을 호출하는 시점에 계산하여 전달해주는것이 어떨까요 ? - `LotteryResult`

### 작업내용 (step4)
- [ ] xxx

### 학습내용
[4단계 - 로또(수동)](https://edu.nextstep.camp/s/MNii0Puk/ls/uF3PX0mB)

### 참고 
[junit - parameterized](https://www.baeldung.com/parameterized-tests-junit-5)
[assertj 활용](https://www.baeldung.com/introduction-to-assertj)

### 한줄일기
to be updated

2020-12-23 15:04 UTC, joongs commented on src/main/java/lottery/domain/BuyBehavior.java
> +    List<LotteryNumber> getLotteryNumbersBy(String numbers);
리뷰어님, 
파라미터가 다른게 2개의 메소드를 이렇게 생성하는게 이상하게 느껴집니다.
이렇게 되면 `BuyBehavior`를 inferface로 만든 이유가 퇴색된다는 기분이 듭니다.

같은 인터페이스를 사용해서 수동/자동을 처리해야하는데 그러게 되지가 않은것 같습니다.
제가 잘못 설계를 했다는 생각이 듭니다만, 현재로써는 개선책이 떠오르지 않아서 문의 드립니다.

2020-12-24 07:35 UTC, sah3122 requested changes
요구사항 구현 잘해주셨네요 👍 
질문주신 부분에 대한 답변을 남겨드렸는데 확인 부탁드립니다 😄

2020-12-24 07:35 UTC, sah3122 commented on src/main/java/lottery/LotteryGameManager.java
> +        int numberOfManual = Integer.parseInt(InputViewLotteryGame.getNumberOfLotterysByManual());
로또 구입에 필요한 파라미터를 DTO로 정의해보는것도 좋을것 같습니다 ㅎㅎ

2020-12-24 07:35 UTC, sah3122 commented on src/main/java/lottery/domain/BuyBehavior.java
> +    List<LotteryNumber> getLotteryNumbersBy(String numbers);
좋은 고민해주시고 계시네요 👍 
이해하고 계신것 처럼 인터페이스를 정의하는것이 항상 올바른 방향은 아니라고 생각합니다. 
개인적으로는 인터페이스를 정의할때 변경될 가능성이 있는 기능 또는 클래스에 한해 정의하곤 하는데, 로또 수동, 자동 구입과 같이 로또 구입방식은 충분히 변경될수 있지만 파라미터가 다른 경우에는 또 다른 고민이 생기게 되는것 같아요. 
제가 생각하기엔 두가지 방식정도가 해결법이 될것 같습니다.

1. 로또 구입행위를 인터페이스가 아닌 Lotto클래스의 책임으로 위임한다. 
로또 생성 자체를 Lotto 객체를 통해 구현 할 수 있다면 인터페이스는 더이상 사용되지 않을것 같아요. 
```java
Lotto autoLotto = Lotto.auto();
Lotto manualLotto = Lotto.manual(manualNumber);
```
위 예시와 같은 방향으로 구현한다면 가독성도 뛰어나고 로또 클래스가 로또를 생성하는 모델링도 자연스러운 모델링이 되는것 같습니다. 

2. 인터페이스를 사용한다면 default 메소드를 활용한다.
Java 8 부터 인터페이스에 Default 메소드를 선어할 수 있게 되었어요.
Default 메소드는 하위 호환성을 유지하기 위해 추가된 기능이라고도 볼수 있습니다. 
자동 로또구입행위와 수동 로또 구입 행위에 대한 Default 메소드를 정의하고, 구현체에서는 필요한 메소드만 정의할 수 있다면 구현체의 코드 자체는 이상없어 보이지만 외부 클래스에서 구현체를 사용하는 경우 default 메소드를 호출할 수 있게 되므로 어떤 방식이 나을지는 고민해보시면 좋을것 같습니다. 
https://siyoon210.tistory.com/95

2020-12-24 07:35 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryGame.java
> +    private void buyLotteryTicketBy(BuyBehavior behavior, int numberOfBuying) {
메소드 명이 부자연스러운것 같은데 수동 로또 구입, 자동 로또 구입과 같이 의미를 확실하게 나타내보세요 !

2020-12-24 07:35 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicketFactory.java
> +        throw new AssertionError("해당 클래스는 객체를 생성할 수 없습니다.");
private 접근 제어자는 외부에서 생성을 막으려고 사용한것입니다. 
만약 내부에서 생성하는 코드가 추가된 경우 예외를 던지는것이 적절한 행위인지 판단해보시면 좋을것 같아요 ㅎㅎ

2020-12-24 07:35 UTC, sah3122 commented on src/main/java/lottery/domain/ManualBuyBehavior.java
> +                .map(s -> lotteryAllNumbers.get(s - 1))
스트림 내부에서도 변수명을 줄여쓰기보다는 의미를 가지도록 고민해보세요 ㅎㅎ

2020-12-25 11:11 UTC, joongs commented on src/main/java/lottery/domain/LotteryTicketFactory.java
> +        throw new AssertionError("해당 클래스는 객체를 생성할 수 없습니다.");
네 내부에서 생성하는 코드가 존재하지 않아서, assertion을 넣었는데, 
추후 내부에서 객체를 생성하게 되는 로직이 생긴다면 문제가 되겠네요.
해당건에는 assertion 부분은 삭제하는걸로 해야겠습니다. 👍

2020-12-25 11:11 UTC, joongs commented on src/main/java/lottery/domain/ManualBuyBehavior.java
> +                .map(s -> lotteryAllNumbers.get(s - 1))
의미있는 이름으로 개선하겠습니다.

2020-12-25 11:21 UTC, joongs commented on src/main/java/lottery/domain/LotteryGame.java
> +    private void buyLotteryTicketBy(BuyBehavior behavior, int numberOfBuying) {
네 해당건에 대해서는 다시 개선하겠습니다.

2020-12-25 11:22 UTC, joongs commented on src/main/java/lottery/LotteryGameManager.java
> +        int numberOfManual = Integer.parseInt(InputViewLotteryGame.getNumberOfLotterysByManual());
`DTO`가 익숙치 않은데 찾아보고 적용해겠습니다. 👍

2020-12-26 18:33 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
마지막 수동 로또미션까지 깔끔하게 구현해주신것 같습니다 ㅎㅎ
세중님을 리뷰하는동안 저도 많은것들을 배울수 있는 시간이었습니다. 😄 
그동안 적지않은 피드백들을 반영해주신다고 수고많으셨습니다. 🙏

2020-12-26 18:33 UTC, sah3122 commented on src/main/java/lottery/LotteryGameManager.java
> +                Integer.parseInt(InputViewLotteryGame.getNumberOfLotterysByManual()));
InputViewLotteryGame.getLottoInfo() 와 같이 선언할수도 있을것 같습니다 ㅎㅎ

2020-12-26 18:33 UTC, sah3122 commented on src/main/java/lottery/domain/LotteryTicket.java
>  public class LotteryTicket {
정적 팩토리 메소드를 활용하여 LotteryTicket 클래스가 자동, 수동 로또 객체를 생성할 수 있게되었네요 💯

2020-12-26 18:33 UTC, sah3122 commented on src/main/java/lottery/dto/LotteryUserDTO.java
> +public class LotteryUserDTO {
DTO 클래스 활용 👍

2020-12-26 18:33 UTC, merged