[Step4] 리뷰요청 드립니다.
next-step/java-lotto pull request #1162
Opened 2020-12-22 10:05 UTC by charllossdev

안녕하세요. :)
마지막 Step4 과제 리뷰 요청드립니다.

로또 수동 객체를 관리하려다 보니 생각보다 많은 수정을 하게 됬습니다.
테스트 코드를 작성하면서, 수동 객체 만들기가 생각보다 까다로워서 새로운 래퍼객체를 통해서 리펙토링을 하면서 진행하였습니다.

질문이 하나 있습니다.
지금 컨트롤러인 메인 메소드에 try/catch문으로 예외처리를 하고 있는데, 이부분이 비효율적이라고 생각이 드는데,
좋은 방법이 있는지 궁금해서 질문을 드립니다.

마지막 리뷰도 잘 부탁드리겠습니다.

2020-12-22 10:19 UTC, seogi89 requested changes
수정이 많이 발생하였다는 것은 구조(설계)적인 부분에 개선점이 있다는 신호 일 것 같아요.
질문하신 내용에 더불어 몇가지 코멘트 남겨 놓았으니 리펙토링 진행해보면 좋을 것 같아요.

2020-12-22 10:19 UTC, seogi89 commented on src/main/java/lotto/modal/Game.java
> +		ManualLotto randomLotto = new ManualLotto(randomCount);
이름과 변수명이 일치하지 않네요.  ManualLotto 란 객체가 필요할지 의문이에요.

2020-12-22 10:19 UTC, seogi89 commented on src/main/java/lotto/LottoMain.java
>  		} catch (IllegalArgumentException illegalArgumentException) {
IllegalArgumentException 을 상속받은 각각 개별 익셉션을 사용하는건 어떤가요.
출력을 해주기 위해서라면 해당방법외에는 좋은방법이 떠오르지는 않네요.

2020-12-22 10:19 UTC, seogi89 commented on src/main/java/lotto/LottoMain.java
>  public class LottoMain {
로또와 수동 발급 로또의 성질은 다르지 않을 것 같은데 불필요한 객체가 생성 된 것 같아요.
메인 함수에서
로또 생성 부분과 로또 매칭 부분을 나눠서 개발해보면 어떤가요?

2020-12-22 10:19 UTC, seogi89 commented on src/main/java/lotto/LottoMain.java
> +	private static GameCondition condition;
어떤 역할을 하는 인스턴스일까요?

2020-12-22 10:19 UTC, seogi89 commented on src/main/java/lotto/modal/GameCondition.java
> +public class GameCondition {
입력객체에서 할 수 있는 유효성검증 아닐까요?

2020-12-22 10:19 UTC, seogi89 commented on src/main/java/lotto/modal/ManualLotto.java
> +public class ManualLotto {
이름과 행위가 일치 하지 않는것 같아요.

2020-12-22 10:19 UTC, seogi89 commented on src/main/java/lotto/modal/ManualLotto.java
> +		return Stream.concat(this.lottoBundle.stream(), randomLotto.getLottoBundle().stream())
`addAll` 메소드도 활용 할 수 있을 것 같아요.

2020-12-22 10:19 UTC, seogi89 commented on src/main/java/lotto/modal/WinnerLotto.java
> +		if (this.winner.getLotto().contains(number)) {
이번 과정에서 GETTER 사용을지양하고 있어요. 어떻게하면 GETTER를 없앨 수 있을까요?

2020-12-28 12:14 UTC, charllossdev commented
안녕하세요. :)

좋은 코멘트를 주셔서 고민을 굉장히 많이했습니다.

생각을 정리하고 보니 
제 코드가 전체적으로 가독성도 좋지 않을 정도로 느껴져서 열심히 리펙토링을 했습니다.

더욱 완성도를 올리고 싶은데, 좋은 리뷰 부탁드리겠습니다.

2020-12-29 07:18 UTC, seogi89 approved these changes
피드백 반영 잘해주셨네요 👍 
많은 피드백 반영하시느라 너무 고생 많으셨습니다.

좋은 개발자로 성장하시는대 보탬이 되기를 바라봅니다.

이걸로 저와의 미션은 종료되었지만, 궁금한점이나 어려운점 있으면 편하게 DM 주세요.

감사합니다.

2020-12-29 07:20 UTC, merged