Step3 3단계 로또(2등)
next-step/java-lotto pull request #1187
Opened 2020-12-29 14:38 UTC by carry1126

리뷰 요청합니다.
당첨금액에 대한 오버플로우 발생하는 부분은 고민해봐야될거 같아요><

2020-12-29 22:30 UTC, seogi89 requested changes
자바에서는 큰 숫자를 다루기 위해 
[[Java] 큰 숫자(실수) 다루기 BigDecimal 사용법 & 예제 총정리](https://coding-factory.tistory.com/605) 을 제공하고 있습니다.

추가로 코멘트 남겨놓았으니 확인하시고 리펙토링 진행해주세요.

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/Rank.java
> +    FIRST(6, 2000000000),
```suggestion
    FIRST(6, 2_000_000_000),
```

위와 같이 가독성을 좋게 만들 수 있어요.

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/ui/InputView.java
> +    private Map<Integer, String> winNumberInfo = new HashMap<>();
Map 보다 객체를 만드는데 좀 더 객체지향적인 것 같네요

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/Rank.java
> +    public static Rank valueOf(int countOfMatch, boolean matchBonus) {
countOfMatch 가 보너스 번호를 포함하면서 조건식이 어려워 진것 같아요

countOfMatch 는 로또와 당첨번호를 비교한 카운트로 제한하면 조건식이 좀 더 간편해질것 같아요.

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoNumber.java
> +    public int checkLotto(int[] numbers, String bonus) {
인자의 타입을 맞춰주고 checkBonusball 을 활용하면 코드 재사용성이 좋아질 것 같아요.

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoNumber.java
>      private List<Integer> number = new ArrayList<>();
어디에 쓰이는 필드일까요?

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoIssue.java
> +        return 3;
`3` 대신 의미를 명시하는 상수를 사용하면 좋을 것 같습니다 :)
이외 다른 부분에 대해서 매직넘버를 사용하는 부분도 상수로 치환하여 사용해보는것을 추천드립니다.

- 클린코드 > G25: 매직 숫자는 명명된 상수로 교체하라

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoIssue.java
> +        this();
어떤 역할을 할까요 ?

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoIssue.java
>          this.count = count;
생성자에서 초기화 한다면
`resultList = 초기화 메소드();`
count 를 인스턴스 필드로 가지고 있을 필요가 없을 것 같아요.

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoIssue.java
> +    public void checkNumber(String[] numbers, String bonus) {
String[] numbers 와 LottoNumber 는 같은 성질일 것 같은데 같은 객체를 활용할 수 있지 않을까요?

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoIssue.java
> +        if (numberConvertInt[i] >= 46) {
-1이 입력되면 어떻게 될까요.

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoIssue.java
> +        if (numberConvertInt[i] >= 46) {
보너스 볼에 대한 제약 사항은 확인하지 않아도 될까요 ?

2020-12-29 22:30 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoNumber.java
> +    private boolean bonusCheck;
값을 인스턴스 필드로 유지해야 할까요 ?

일전에 말씀드린것처럼
로또 객체의 상호작용으로 결과로 변화는 메소드를 구현하면 좋을 것 같아요.

2020-12-29 22:30 UTC, seogi89 commented on src/test/java/lotto/oop/domain/LottoIssueTest.java
> +        String[] numList = numbers.split("");
```suggestion
        String[] numList = numbers.split(" ");
```
의도하지 않은 다른 이유로 에러가 발생하고 있을 것 같아요.

2020-12-30 06:59 UTC, carry1126 commented on src/main/java/lotto/oop/ui/InputView.java
> +    private Map<Integer, String> winNumberInfo = new HashMap<>();
넵 그렇네요 재석님 피드백 덕분에 객체지향에 대한 감이 조금은 잡힌거 같아요^^//

2020-12-30 07:51 UTC, carry1126 commented on src/main/java/lotto/oop/domain/LottoNumber.java
>      private List<Integer> number = new ArrayList<>();
number는 로또 넘버 45개를  저장하고 suffle한 것을 담고 있습니다. 거기서 6개의 숫자를 가지고 generateNumbers에 담아서 사용하고 있습니다.

2020-12-30 14:07 UTC, seogi89 requested changes
피드백 반영 잘해주셨네요.
BigDecimal 을 활용하여 큰 숫자를 정밀하게 계산 할 수 있었어요 💯 
결과를 객체로 분리하는 것에 대해서 몇번 말씀드린 것 같은데 분리를 꺼리시는 이유가 있으실까요? 결과를 LottoIssue 에서 분리하고 다음 단계로 넘어가면 좋을 것 같아요.
저와 의견이 다르시다면 편하게 코멘트 남겨주세요.

2020-12-30 14:07 UTC, seogi89 commented on src/main/java/lotto/oop/ui/ResultView.java
>  public class ResultView {
출력 객체에서 계산하지 말고 결과 객체에서 계산하고
출력 객체는 말그대로 이쁘게 뿌려주는데에 집중해보는건 어떤가요?

2020-12-30 14:07 UTC, seogi89 commented on src/main/java/lotto/oop/ui/ResultView.java
>      }
```       
String msg = "총 수익률은 " + Math.floor((grossReturn) * 100) / 100.0 + "입니다.";
if( return < 1d ) {
   msg += " (기준이 1이기 때문에 결과적으로 손해라는 의미임")";
}	 
System.out.println(msg)
```

2020-12-30 14:07 UTC, seogi89 commented on src/main/java/lotto/oop/domain/LottoIssue.java
>              throw new IllegalArgumentException("당첨 볼이 46보다 큽니다.");
조건이 바뀌었으면 메세지도 바뀌는게 좋겠죠.
이러한 변화에 유연하게 대처하지 못하는 것은 잘못 된 설계를 하셨을 확률이 높습니다.

2020-12-30 14:30 UTC, carry1126 commented on src/main/java/lotto/oop/domain/LottoIssue.java
>              throw new IllegalArgumentException("당첨 볼이 46보다 큽니다.");
detail을 놓쳤네요><

2020-12-30 15:21 UTC, carry1126 commented
> 피드백 반영 잘해주셨네요.
> BigDecimal 을 활용하여 큰 숫자를 정밀하게 계산 할 수 있었어요 💯
> 결과를 객체로 분리하는 것에 대해서 몇번 말씀드린 것 같은데 분리를 꺼리시는 이유가 있으실까요? 결과를 LottoIssue 에서 분리하고 다음 단계로 넘어가면 좋을 것 같아요.
> 저와 의견이 다르시다면 편하게 코멘트 남겨주세

2020-12-31 04:37 UTC, carry1126 commented on src/main/java/lotto/oop/ui/ResultView.java
> +        BigDecimal first = new BigDecimal("2000000000");
> 피드백 반영 잘해주셨네요.
> BigDecimal 을 활용하여 큰 숫자를 정밀하게 계산 할 수 있었어요 💯
> 결과를 객체로 분리하는 것에 대해서 몇번 말씀드린 것 같은데 분리를 꺼리시는 이유가 있으실까요? 결과를 LottoIssue 에서 분리하고 다음 단계로 넘어가면 좋을 것 같아요.
> 저와 의견이 다르시다면 편하게 코멘트 남겨주세요.

PR 닫아서 미안합니다;;
결과를 분리한다는 의미가 issuteStatats 당첨 통계를 담고 있는 부분을 일급 콜렉션으로 분리하는 것을 의미하는 것인가요?
설계를 잘하고 코딩을 했어야됐는데 기능을 추가하려고 할수록 어렵네요><

2020-12-31 08:35 UTC, seok-2-o commented on src/main/java/lotto/oop/ui/ResultView.java
> +        BigDecimal first = new BigDecimal("2000000000");
네 issuteStatats 만가지고 있는 객체가 하나 작성되면 좋을 것 같아요.

2020-12-31 08:47 UTC, seok-2-o requested changes
피드백 반영 잘해주셨네요..

조금만 더 개선하면 결과 객체를 완성 할 수 있을 것 같아요
관련하여 코멘트 남겨놓았으니 리펙토링 진행해주세요.

정신없이 한 해가 지나가고 있는데요, 
한 해도 너무 수고하셨고, 내년에도 함께 할 수 있어 영광일 것 같습니다. :)

새해복 많이 받으세요 🙇

2020-12-31 08:47 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/LottoIssue.java
>      }
i 가 인덱스 번호 였군요

Integer 를 로또 번호 하나로 만든다면 어떵 장점이 있을까요 ?

2020-12-31 08:47 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/IssueStats.java
> +    public double getDoubleTotalSum() {
Rank 에 금액이 있기때문에 로직을 쉽게 작성 할 수 있을 것 같아요.

심플한 예를 들면 아래와 같습니다.
```
        Map<BigDecimal, Integer> maps = new HashMap<>();
        maps.put(BigDecimal.valueOf(20_000_000_000L), 2);
        maps.put(BigDecimal.valueOf(100_000_000L), 2);
        
        BigDecimal total = maps.entrySet().stream()
            .map(entry -> entry.getKey().multiply(BigDecimal.valueOf(entry.getValue())))
            .reduce(BigDecimal::add)
            .orElse(BigDecimal.ZERO);
```

2020-12-31 08:47 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/IssueStats.java
> +        this.amount = amount;
map 의 valuese 의 합 * 가격은 총 구매가격입니다.

2020-12-31 08:47 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/IssueStats.java
> +        int key = issuelotto.checkLotto(numbers, bonus);
Map<Rank, Integer> result = issuelotto.check(List<Integer> numbers, int bonus) 로 반환하는건 어떻게 생각하시나요 ?

2021-01-01 08:09 UTC, carry1126 commented on src/main/java/lotto/oop/domain/LottoIssue.java
>      }
Integer를 로또 번호 하나로 만든다는 것이 무슨 의미인지 잘 모르겠습니다.

2021-01-01 10:55 UTC, carry1126 commented on src/main/java/lotto/oop/domain/IssueStats.java
> +        int key = issuelotto.checkLotto(numbers, bonus);
값을 변경하지 못하게  final로 Map을 정의해서 사용하고 있습니다.  제시한 방법도 나쁘지 않다고 생각하는데 큰 차이가 없는 이상 기존대로 가도 괜찮다고 생각합니다.

2021-01-02 02:12 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요.

LottoIssue (로또 티켓) 가 LottoNumber (로또 게임) 의 모임이라고
한다면 LottoNumber  은 6개의 숫자로 콜렉션으로 구현되어 있는데요
현재 `List<Integer` 의 형태의 구조를 새로운 객체의 콜렉션으로 만들어주면
 `-> List<LottoNo>` 어떤 장점이 있을까요?

다음 미션 진행하면서 고려해보면 좋겠네요.
새해 복 많이 받으세요! 올 한해는 더 많이 행복하고 더 많이 웃는 한 해 되시길 바랍니다~

2021-01-02 02:12 UTC, merged