Step4 4단계 로또(수동)
next-step/java-lotto pull request #1189
Opened 2021-01-02 08:16 UTC by carry1126

리뷰 요청 드립니다. 
LottoNo로 Inteager 원시타입을 감싸면 그 안에서 숫자에 대한 validate 체크를 할 수 있는 장점이 있습니다.
제 코드 같은 경우 수동으로 번호 입력하고 당첨번호 입력하는 부분에서 유효할거 같습니다. 그 값을 발행된 로또 값과 같은 타입  List<Integer>으로 변환해줘야될거 같아서 고민 해봐야 될것 같아요.

2021-01-02 12:35 UTC, seok-2-o requested changes
![image](https://user-images.githubusercontent.com/34270397/103457364-08750880-4d42-11eb-9854-5c21c7803546.png)
![image](https://user-images.githubusercontent.com/34270397/103457402-643f9180-4d42-11eb-8235-8187e287a41b.png)


기본적인 게임 규칙이 하나도 적용 되지 않고 있어요.
새로운 조건이 추가될때마다 새롭게 규칙을 적용하는것은 객체지향 원리에 맞지 않는 것 같아요

지난단계에서 말씀드린 것처럼

로또가 가져야 갈 규칙 로또 번호가 가져야할 규칙을 각 객체로 하여금 잘 지킬 수 있도록 리펙토링 진행해주세요.

2021-01-02 12:35 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/LottoIssue.java
> +        resultList = handOperationLotto;
12 라인은 의미가 없어진 것 같아요.

2021-01-03 07:41 UTC, seok-2-o requested changes
오 많은 부분을 객체로 만들어주셨네요 💯

만들어진 객체들은 검증뿐만 아니라 비지니스 로직에도 사용 하면 좋을 것 같아요.
로또넘버를 객체를 List<LottoNo> 형태로 만들어 보면 어떨까요?

2021-01-03 07:41 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/LottoNumber.java
>      private List<Integer> generateNumbers;
LottoNo 을 활용하면 좋지 않을까요?

2021-01-03 07:41 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/WinNumber.java
>      private int bonusNumber;
지난 당첨 번호는 
```
private LottoNumber number
private LottoNo bonus
```
로 나타낼 수 있을 것 같아요.

2021-01-03 07:41 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/LottoNo.java
> +    }
💯

2021-01-03 07:41 UTC, seok-2-o commented on src/main/java/lotto/oop/ui/InputView.java
> +        int autoLottoCount = amount.getCount() - handCount.getLottoCount();
getter를 사용하기 보다 hmount.substract(handCount)와 같은 꼴을 지향해요.

2021-01-04 02:13 UTC, carry1126 commented on src/main/java/lotto/oop/domain/LottoNumber.java
>      private List<Integer> generateNumbers;
자동으로 로또 발행하는 부분에서는 1~45까지의 값만 들어가게  generateNumbers()에서 해주고 있고  수동으로 하는 경우에는 convertInt(String result)에서 LottoNo으로 생성해서 validate 체크해주고 있기 때문에 이부분에서는 사용안해도 될 것 같습니다. ^^

2021-01-04 03:31 UTC, seok-2-o commented on src/main/java/lotto/oop/domain/LottoNumber.java
>      private List<Integer> generateNumbers;
`List< LottoNo> ` 를 권장하는 이유는 책임을 명확하게 하기 위해서 입니다.

지금처럼 체크하는 부분과 validate 이 분리되어 있을 경우에 추후에 수정하기가 어려워진다고 생각해요.

2021-01-04 03:33 UTC, seok-2-o approved these changes
피드백 반영 잘 해주셨네요 :) 

다소 많은 피드백을 드린것 같은데 너무 고생 많으셨습니다 👍 
마지막으로 코멘트 하나 남겨드렸으니 고민해보시면 좋겠네요.

저와의 미션은 종료되었지만 앞으로도 궁금한점이나 어려운점 있다면 편하게 연락주세요.

다른 사람과 비교하지 않고 끝까지 과제 완주하시리라 믿습니다 :fire:
감사합니다.

2021-01-04 03:34 UTC, merged

2021-01-04 03:35 UTC, carry1126 commented on src/main/java/lotto/oop/domain/LottoNumber.java
>      private List<Integer> generateNumbers;
네 재성님 생각에 공감은 합니다.

2021-01-04 03:39 UTC, carry1126 commented
> 다소 많은 피드백을 드린것 같은데 너무 고생 많으셨습니다 👍
> 마지막으로 코멘트 하나 남겨드렸으니 고민해보시면 좋겠네요.
> 
> 저와의 미션은 종료되었지만 앞으로도 궁금한점이

감사합니다. 재석님 
이번 미션을 진행하면서 초반에 뒤쳐져서 조급해지고 엉망인 코드에 피드백을 주신 덕분에 마음을 다잡고 진행할 수 있었습니다. 덕분에 객체지향에 대해서 조금은 생각해보고 코드 작성한것 같아요.
쉽지 않았지만 이번 미션을 통해서 많이 배우고 끝낼 수 있어서 감사하게 생각합니다.