[11번가.최문경] 문자열 덧셈 계산기, 1단계 로또(자동)
next-step/java-lotto pull request #1205
Opened 2021-01-31 08:25 UTC by mk0324

리뷰 부탁드립니다!

2021-02-01 15:27 UTC, gyumin-kim requested changes
전반적으로 구현을 잘 해주셨습니다! 페어프로그래밍과 리팩토링 과정을 거치면서 많이 고민하신 흔적이 느껴지지네요. 고생 많으셨습니다🔥
몇가지 의견과 궁금한 점들을 코멘트로 남겼으니 확인해주시고, 같이 의견을 나누면서 점진적으로 개선해 나가면 좋겠습니다. 사소한 내용들일 수도 있지만, 미션 수행 기간이 며칠 연장되었으니 일단 Request changes로 리뷰를 제출하겠습니다.

2021-02-01 15:27 UTC, gyumin-kim commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int compareTo(LottoNumber lottoObject) {
테스트를 위해 작성된 메서드인가요~?

2021-02-01 15:27 UTC, gyumin-kim commented on src/test/java/lotto/view/OutputViewTest.java
> +    void printWinningResultTest() {
단언문(assertion)이 없어 무조건 성공하는 테스트로 보입니다(중간에 예외가 발생하지 않는다면).
`System.out.println()`의 출력 결과에 대해서도 단언문 작성이 가능합니다.
- [Unit Testing of System.out.println() with JUnit](https://www.baeldung.com/java-testing-system-out-println)

2021-02-01 15:27 UTC, gyumin-kim commented on src/main/java/calculator/CalculatorMain.java
> +
불필요한 라인은 삭제하고, 중괄호나 소괄호 주위의 공백 컨벤션은 모든 클래스에서 일관성 있게 관리하면 좋을 것 같아요!
(여러 클래스에서 중복되는 내용이어서, 여기에만 코멘트를 남길게요)

2021-02-02 05:11 UTC, mk0324 commented on src/main/java/calculator/InputValidator.java
> +            throw new RuntimeException("음수를 입력하셨습니다.");
예외 항목에 대해 공부할 수 있었습니다 감사합니다👏👍

2021-02-02 07:50 UTC, mk0324 commented on src/main/java/calculator/InputValidator.java
> +
private 생성자를 선언해야하는군요! 감사합니다🙌

2021-02-02 08:12 UTC, mk0324 commented on src/main/java/calculator/StringCalculator.java
> +        return splitByDelimiter(text);
splitByCondition 이라는 메서드를 추가하여 
custom delimiter인지 여부에 따라 splitByDelimiter, splitByCustomDelimiter 내부메서드를 호출해 split 책임만 갖게 하고,
기존에 있던 add 메서드에서 받아온 배열에 대해 연산을 진행하도록 수정하였습니다🙌

2021-02-02 08:19 UTC, mk0324 commented on src/main/java/calculator/StringCalculator.java
> +            return res;
리뷰 이후 add 함수에서 split을 한 배열에 대한 덧셈 연산을 수행하려다보니 유효한 연산인지 확인하고 예외를 발생시키는 로직이 들어가게 되었는데요.
확인해보니 스트림 내에서 예외가 발생하면 예외에서 로직이 멈추지 않고 남은 원소에 대한 로직이 실행이 되더라구요.
그래서 스트림말고 for 문으로 유지하였습니다!🤔

2021-02-02 08:23 UTC, mk0324 commented on src/main/java/lotto/domain/LottoMatcher.java
> +    private final Map<Prize, Integer> PrizeBoard = new EnumMap<>(Prize.class);
제가 확인하지 못한 부분이네요👀 꼼꼼하게 봐주셔서 감사합니다! 수정해서 반영하였습니다

2021-02-02 08:28 UTC, mk0324 commented on src/main/java/calculator/StringCalculator.java
> +    }
해당 부분은 고려하지 못했네요! 전반적으로 다시한번 살펴봐야할것 같습니다 감사합니다👀

2021-02-02 08:47 UTC, mk0324 commented on src/main/java/lotto/view/OutputView.java
> +            }
오 좋은 코딩 습관인것 같아요. 
그리고 저렇게 return을 줄 수 있군요! 
스트림 동작 범위에 대해 좀 더 공부해봐야겠습니다👀

2021-02-02 08:50 UTC, mk0324 commented on src/main/java/lotto/view/OutputView.java
> +        System.out.println(stringBuffer.toString());
구현하면서 고려하지 못한 부분이네요 링크 감사합니다!🙌

2021-02-02 08:53 UTC, mk0324 commented on src/test/java/lotto/view/OutputViewTest.java
> +    void printWinningResultTest() {
출력문도 단언문이 가능하군요! 링크 감사합니다👍

2021-02-02 09:15 UTC, mk0324 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int compareTo(LottoNumber lottoObject) {
앗 페어프로그래밍을 과정에서 기능을 나누어 코딩하다 보니 
사용하지 않는 코드가 남겨졌네요😅😅 
사용하지 않는 함수와 코드들을 삭제하였습니다!

2021-02-02 12:46 UTC, mk0324 commented on src/main/java/lotto/domain/Lotto.java
> +public interface Lotto {
1. Lotto 클래스를 페어 분께서 도출하셨는데 제가 추측하기로는 
`로또구매자의 로또(PlayersLotto)`와 `당첨 로또(WinnerLotto)`라는 개념을 나누다가 보니 
Lotto 라는 추상개념을 상위에 두고 싶으셨던게 아닐까 추측이 됩니다.
2.  getWinnerLottoWithSplitting 메서드의 경우는 원래 WinnerLotto 라는 클래스 내부에 있었는데요.
입력 받은 당첨번호를 split 하기 위해 만든 메서드이고 사실 리팩토링을 진행하면서 2단계를 염두해서 로또를 수동으로 입력을 하게 되면 이 부분이 중복되지 않을까 하여 default 메서드로 인터페이스에 구현하였습니다. 확장가능성을 생각하고 고민해서 옮기게 되었는데 여전히 어디에 위치해야 적합한 메서드인가 고민이 되는 부분인것 같아요. 너무 앞서나가서 구현하였나 하는 생각도 드네요😅

2021-02-02 13:02 UTC, mk0324 commented on src/main/java/lotto/controller/LottoController.java
> +        money = inputView.getMoneyToBuyLotto();
Money 라는 객체가 하는일이 없는것 같아 삭제하고 원시값으로 작성했었는데 
inputView.getMoneyToBuyLotto() 에서 입력받은 값을 검증하는 부분에 책임이 전가되어 있다는 점을 생각하지 못했네요.
객체관계를 좀더 넓게 바라봐야 한다는 것을 배웠습니다!👍
객체지향을 향해가는게 참 멀군요😓

2021-02-02 13:56 UTC, gyumin-kim commented on src/main/java/lotto/domain/LottoMatcher.java
> +    private final Map<Prize, Integer> PrizeBoard = new EnumMap<>(Prize.class);
IntelliJ에 linter plugin을 설치하면 이런 것들도 다 잡아주더라구요! SonarLint 추천합니다 ㅎㅎ

2021-02-02 15:20 UTC, gyumin-kim requested changes
수정하신 코드와 달아주신 코멘트 재미있게 보았습니다~!
그냥 approve 해도 될 것 같지만, 실패하는 로또 테스트가 일부 있어서 다시 수정 요청을 하게 되었습니다🙇‍♂️
재요청 주시면 빠르게 확인하도록 할게요!

2021-02-02 15:20 UTC, gyumin-kim commented on src/main/java/lotto/domain/Lotto.java
> +public interface Lotto {
아하 그렇군요! 👍
`getWinnerLottoWithSplitting()`이 당첨번호를 생성하는 목적으로만 쓰이는 것 같은데 인터페이스에 구현이 되어 있길래, 궁금해서 여쭤보았습니다 😊 
그런 의도이신거라면 메서드 이름은 약간 수정이 필요할 수도 있겠네요.

2021-02-02 15:20 UTC, gyumin-kim commented on src/main/java/lotto/domain/Money.java
> +        this.money = Integer.parseInt(input);
validation check 후 값 할당 👍

2021-02-02 15:20 UTC, gyumin-kim commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    }
`compareTo()` 테스트 코드도 같이 삭제되어야 하는 거겠죠~?

2021-02-02 15:20 UTC, gyumin-kim commented on src/test/java/lotto/domain/LottoMatcherTest.java
> +class LottoMatcherTest {
실패하는 테스트가 존재합니다! 🚨

2021-02-02 15:20 UTC, gyumin-kim commented on src/test/java/lotto/domain/WinnerLottoTest.java
> +class WinnerLottoTest {
실패하는 테스트가 존재합니다! 🚨

2021-02-03 00:40 UTC, mk0324 commented on src/main/java/lotto/domain/LottoMatcher.java
> +    private final Map<Prize, Integer> PrizeBoard = new EnumMap<>(Prize.class);
오오 바로 설치했습니다👀👍

2021-02-03 01:41 UTC, mk0324 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    }
앗 리팩토링과 테스트코드에 대한 수정이 함께 진행됐어야 겠군요👀

2021-02-03 05:58 UTC, mk0324 commented on src/test/java/lotto/domain/LottoMatcherTest.java
> +class LottoMatcherTest {
LottoNumber 에서 삭제했던 equals 메서드가 여기서 객체간 비교 역할을 수행하고 있었네요,,
한참 디버깅하다가 발견했네요ㅎㅎ
제가 equals, hashCode 의 쓰임을 고려하지 못하고 삭제한 것을 알고 계셨던 걸까요..! 놓치고 갈뻔했던 부분을 짚어주셔서 감사합니다👍
이번 미션에서 규민님이 남겨주신 리뷰들을 통해 정말 많이 배우고 있어요! 그리고 어떻게 리뷰를 남겨야할지, 뭘 봐야할지도 규민님의 리뷰를 통해서 배워가고 있어요 멋지십니다👍

2021-02-03 05:58 UTC, mk0324 commented on src/test/java/lotto/domain/WinnerLottoTest.java
> +class WinnerLottoTest {
LottoNumber 에서 삭제했던 hashCode 메서드가 여기서 중복검사 역할을 하고 있었네요.
그리고 🚨 이모지 너무 귀엽네요ㅋㅋㅋㅋㅋ

2021-02-03 06:26 UTC, mk0324 commented on src/main/java/calculator/StringCalculator.java
> +        return res;
와 이렇게 가능하군요 적용해보겠습니다! 스트림 잘쓰고 싶네요..😹

2021-02-03 06:27 UTC, mk0324 commented on src/main/java/calculator/StringCalculator.java
> +        return res;
의견주신대로 sum 메서드를 추출해서 가독성을 높여보았습니다! 🙌

2021-02-03 06:29 UTC, mk0324 commented on src/main/java/calculator/StringCalculator.java
> +        inputs = splitByCondition(text);
오 이런 디테일은 매번 고민하다가 딱히 답을 찾지 못해서 그냥 넘겼던 것들이었어요! 좋은 정보 감사합니다👍

2021-02-03 07:35 UTC, gyumin-kim commented on src/main/java/calculator/StringCalculator.java
> +        return res;
저도.... ㅎ

2021-02-03 07:40 UTC, gyumin-kim commented on src/test/java/lotto/domain/LottoMatcherTest.java
> +class LottoMatcherTest {
앗 사실 어제 시간이 늦어서 그렇게 자세히 들여다 보진 못했...고.. ㅋㅋㅋㅋ
전체 테스트를 돌려보니 실패하는게 몇개 있더라구요~
뭔가 수정을 할 때마다 그때그때 테스트들을 돌려보면, 수정해도 이상이 없는지, 영향도가 다른 객체로 미치진 않았는지 등을 확인해볼 수 있어서 좋은 것 같아요!
다른 분들도 열심히 리뷰를 해주셔서 제 리뷰가 좀 부족한건 아닐까 싶었는데 그리 말씀해주시니 정말 감사합니다 😊

2021-02-03 07:41 UTC, gyumin-kim commented on src/test/java/lotto/domain/WinnerLottoTest.java
> +class WinnerLottoTest {
테스트는 소중하니까요 🤣

2021-02-03 07:51 UTC, gyumin-kim approved these changes
고생 많으셨습니다!! 🔥

2021-02-03 07:52 UTC, merged