[2단계] 로또(수동)
next-step/java-lotto pull request #1214
Opened 2021-02-02 15:08 UTC by hakzzang

# 내용
로또(수동)

# 느낀 점
- 객체가 많으니 많은 객체를 사용했을 때 장점들이 보인다.
- 객체를 통해서 수정에 쉽게 대응할 수 있었다.
- 객체를 통해서 검증로직을 쉽게 처리할 수 있다.
- 검증된 객체는 코드에 안정성을 부여해준다.
- 테스트 코드는 내가 변경하는 사항들에 대해서 안정성을 부여해준다.
- 기타 등등..

 '옳은(?) 코드로 작성했을까?' 라는 고민은 있겠지만, 완성하고 난 후에 나름 만족스러운 코드를 작성한 것 같습니다.
이번에 스텝2를 진행하면서 스텝1 때와 다르게 '오류를 처리하는 로직'을 통해서 프로그램에 안정성을 부여하기 위해서 노력을 했습니다.
이러한 과정 속에서 더 다양한 객체를 만들어서 검증하는 로직을 처리했고, 각 객체마다 관심사를 명확하게 나누기 위해서 노력을 했습니다.
 또한, 조금은 더 많은 테스트 코드를 작성했습니다. 제가 코드 리뷰를 하면서 배운 기술들도 사용해보고, 모든 객체를 테스트하기 위해서 노력했습니다.
 TDD를 열심히 하지 못 했지만, 이번 단계들을 진행하면서 일급컬렉션 사용하기, 테스트 코드 작성하면서 코드 작성하기, enum, 예외 처리 등을 적극적으로 사용하기와 같은 것들을 할 수 있게 되었습니다.
 다음에는 조금 더 TDD를 프로젝트에 반영하도록 노력해야겠다는 생각이 들었습니다.

 코드 리뷰 또한 편하게 과감하게 해주시면 감사하겠습니다 🐧

2021-02-04 11:31 UTC, mk0324 requested changes
병학님 저번에 코드구조가 워낙 잘 잡혀있었어서 이번에도 저번 코드의 바톤터치를 받아 잘 읽을 수 있었습니다! 제가 정성가득한 리뷰를 받다보니 저도 뭔가 꼼꼼하게 봐드리고 싶어서 리뷰가 늦어졌어요😢
제 생각을 몇가지 코멘트로 남겨놨으니 한번 확인해보시면 좋을것 같아요! 
그리고 스트림 정말 잘 사용하시는것 같습니다 부러워요👍

2021-02-04 16:23 UTC, hakzzang commented on src/main/java/lotto/domain/ManualNumbersPicker.java
> +                .map(LottoTicket::new)
조금 더 고민해보겠습니다!

2021-02-04 16:54 UTC, hakzzang commented on src/main/java/lotto/view/InputView.java
>          String[] winningTicketNumbers = inputText.trim().split(",");
## 의도
 InputView에서 최대한 입력을 받는 행위를 제외하고,다른 것을 하지 않으려는 의도를 갖고 코드를 작성했습니다.
`getWinningTicketNumbers()`에서도 `scanner.nextLine()`에서 받은 값을 바로 `new LottoTicket(inputData)`로 넣으려고 했습니다. 하지만, LottoTicket이라는 객체에는 번호 객체가 외부에서 전달되어 진다면 조금 더 명시적인 코드가 될 것 같아서, 밖에서 문자열을 처리하고, 내부로 진입시켰습니다.

## 고민사항
 inputText.trim().split() 과 같이 메소드 체이닝으로 문자 배열을 만드는 것은 코드를 작성하면서도, 약간의 불편함이 있었습니다.
체이닝을 하고 있기 때문에, 약간은 이상하게 보일 수 있겠다는 생각이 있었습니다.

## 우선, 의견에 대한 생각은 이렇습니다.
 - trim()과 split() 을 한 번에 처리해주는 메소드가 있으면 좋겠다고는 생각합니다. 👍 
 - 일반적으로 유틸리티 클래스로 볼 수 있는 static 키워드가 들어간 메소드는 선호하지 않습니다. 😢 
 ```java  
ex)
class StringUtlity{
  //StringUtility.splitTrim(); 으로 무분별하게 호출됨
  static public splitTrim(String input){//logic...}
}
``` 
   -> 개인적인 이유는 static으로 이루어진 유틸리티 클래스는 잠깐의 편의성으로 사용할 때는 만족스럽겠지만, 필요할 때마다 만들어지게 되고, 최종적으로는 무분별하게 해당 클래스를 불러와서 사용하기 때문에 코드가 지저분해진다고 생각을 합니다. 
- 그렇다면, '일반적인 메소드나 클래스를 통해서 처리하는 것은 어떨까?' 라는 생각에는 split()과 trim()의 단위가 너무 작지 않을까 생각을 해서 손이 가지 않겠지만, 만약 진행을 한다면 `new TrimSplit()` 객체를 만들어보도록 하겠습니다.

## 어쩌다가 찾은 자료 공유
- 제가 갖고 있는 생각보다 정리된 자료를 통해서 설득을 시키려고 검색을 해보니, 약간의 결은 다르지만 이런 내용도 있었습니다.
[읽을 자료의 링크](https://www.mimul.com/blog/oop-alternative-to-utility-classes/)

2021-02-07 11:58 UTC, hakzzang commented on src/main/java/lotto/domain/ManualNumbersPicker.java
> +                .map(LottoTicket::new)
스트림을 메소드로 빼서 관리하는 것을 생각해볼 수 없었는데, 
확실히 스트림이 길어지면 메소드화 시키면 깔끔해지는 것을 배울 수 있었습니다. 👍

2021-02-09 00:30 UTC, hakzzang commented
피드백 반영한 것을 위주로 수정했고, 유틸리티 클래스는 고민고민하다가 현재가 최선이지 않을까라는 생각을 하게 되었습니다!
너무 작은 단위이고, 두 곳에서만 사용되어지다보니, 번쩍이는 아이디어를 떠올리지 못 했습니다.

2021-02-10 16:20 UTC, mk0324 commented on src/main/java/lotto/view/InputView.java
>          String[] winningTicketNumbers = inputText.trim().split(",");
의견과 답변을 주시려고 고민하신 흔적 그리고 자료까지! 궁금증에 정성스레 의견을 주셔서 감사합니다🥺👍
병학님의 생각을 잘 이해할 수 있었고 저도 유틸 클래스의 생성에 대해 좀 더 찾아볼 수 있는 계기가 되었습니다
저도 제 생각을 전달할때 이런 방법으로 정리해서 의견을 남겨야겠다는 점도 배울 수 있었습니다👍

2021-02-10 16:21 UTC, mk0324 commented
정성스레 남겨주신 의견, 그리고 리뷰 피드백 반영까지! 고샘 많으셨습니다!👍

2021-02-10 16:21 UTC, merged