[ 11번가-정다은 ] 로또 2단계 (수동)
next-step/java-lotto pull request #1217
Opened 2021-02-03 14:26 UTC by jeongdaeun98

동희님 덕분에 좀 더 객체지향적으로 코드를 표현할 수 있게 된 거 같아서 감사합니다!! 이번에도 잘 부탁드립니다 👍

2021-02-04 13:08 UTC, dhsimpson requested changes
수고하셨습니다!!!
request, error 등 view 의 카테고리를 좀 더 명확하게 나눠 주셨군요!!
덕분에 View를 Input, Output View 로만 나누자는 우물안 개구리 사고에서 벗어날 수 있었습니다.
코멘트만 한 번 봐 주시구 다시 PR 보내 주세요!

2021-02-04 13:08 UTC, dhsimpson commented on src/main/java/lotto/LottoApplication.java
> +        Tickets tickets = priceController.getPriceAndGenerateTickets();
view가 다시 controller 안으로 들어왔군요!!
어떤 의도인지 알 수 있을까용??
워낙 깔끔하게 짜셨고 지난 번 PR 때 정리 잘 해주셔서
이 것 외에는 달리 보이는 부분이 없습니다!!!

2021-02-08 12:45 UTC, jeongdaeun98 commented on src/main/java/lotto/LottoApplication.java
> +        Tickets tickets = priceController.getPriceAndGenerateTickets();
MVC 패턴으로 프로그래밍을 할 때, controller는 사용자의 요청사항을 파악해서 그 요청과 알맞은 모델의 데이터를 가져오고, 그 데이터를 view에 반영해서 사용자에게 알려주는 역할을 하므로 철저하게 view와 컨트롤러를 독립적으로 나누기엔 어려운 구조라고 판단했습니다! 그래서 이러한 코드를 작성하게 되었습니다!!

2021-02-12 18:35 UTC, dhsimpson commented on src/main/java/lotto/LottoApplication.java
> +        Tickets tickets = priceController.getPriceAndGenerateTickets();
cli로 하는 과제는 충분히 그렇게 판단하실 수 있다고도 생각 돼요!!!
정말 수고 많으셨습니다 ㅎㅎㅎ

2021-02-12 18:35 UTC, dhsimpson approved these changes
수고 많으셨습니다!!

2021-02-12 18:36 UTC, merged