11번가.한석현 로또 2단계 미션 제출합니다!
next-step/java-lotto pull request #1219
Opened 2021-02-04 12:59 UTC by HanSeokhyeon

리뷰 잘 부탁드립니다!!

2021-02-06 07:08 UTC, KimDoubleB requested changes
석현님, 늦어서 죄송합니다 😂 코드를 보다보니 생각보다 늦어졌네요 😂
step2에선 새로운 기능 추가 뿐 아니라 Money 클래스 추가 등 리팩터링 등 더 좋은 코드를 작성하기 위해 노력하신 것 같았어요 ! 저도 본 받아야겠습니다 ☺️

이번은 서로 성장을 위해 step1보다 꼼꼼히 보았는데요 ! 
몇가지 놓치신 점들이 있는 것 같아 이렇게 적어두어요 !

- 구입금액과 구매할 수 있는 로또의 개수가 맞지 않는 것 같습니다. 
   - 예를 들어, 구입금액으로 1000원을 입력해도 수동 구매로 2개 이상 구매를 할 수가 있네요 ! 이에 맞게 validate코드를 작성하시면 좋을 것 같습니다.
- 로또의 번호에 대해서 검증하고 있지 않습니다. 로또번호로 0, 999 등 로또 숫자의 범위를 벗어난 숫자도 허용이 되고 있네요 !
  - 제이슨이 했던 것 처럼 LottoNumber라는 일반 숫자를 감싸는 클래스를 추가해 생성시 검증하는 식으로 하는 것은 어떨까요? LottoNumber를 사용하는 모든 곳에선 1~45 숫자 이내의 값이라는 것을 보장할 수 있을 것이라고 생각해요 !

그럼 남은 step2 과정도 화이팅입니다 !

2021-02-06 07:08 UTC, KimDoubleB commented on src/main/java/lotto/view/ResultView.java
> -    private static final String STATISTIC_REVENUE_MESSAGE = "총 수익률은 %.2f입니다.";
이 부분을 다 삭제하고 Message enum을 활용하신 것이 엄청 좋아보였어요 ! 훨씬 깔끔한 것 같아요 👍

2021-02-09 15:31 UTC, HanSeokhyeon commented on src/main/java/lotto/controller/LottoController.java
> +        ResultView.printPurchaseNumber(lottos.size()); // 개를 구입했습니다.
우선 자동으로 뽑는 로또티켓의 수를 구하는 메서드를 추출해 급한 불을 껐습니다... 수동구매와 자동구매로 분할하는 것은 대규모 리팩터링이 될 것 같아서 천천히 진행해보겠습니다!

2021-02-09 15:45 UTC, HanSeokhyeon commented on src/main/java/lotto/controller/LottoController.java
> +        List<List<Integer>> manualLottoNumbers = InputView.getManualLottoNumbers(numberOfManualLottoTicket);
저도 이 부분에 대해서 고민 많이 했었는데요 ㅎㅎ

제가 너무 까다롭게 생각한 것 같긴한데 로또머신한테 번호들을 입력하지 로또로 만들어서 입력한다고 생각하지는 않았거든요...ㅎㅎ

그래서 저런 코드가 탄생했습니다 ㅎㅎ 보배님 의견 듣고 나니 또 고민이네요...ㅎㅎ

2021-02-09 15:46 UTC, HanSeokhyeon commented on src/main/java/lotto/view/ResultView.java
> -    private static final String STATISTIC_REVENUE_MESSAGE = "총 수익률은 %.2f입니다.";
ㅎㅎㅎ칭찬은 항상 감사합니다

2021-02-09 15:49 UTC, HanSeokhyeon commented on src/main/java/lotto/domain/LottoMachine.java
> +        if (money.getValue() < 1000) {
ㅋㅋㅋ매직넘버는 바로 교체했습니다 ㅎㅎ

제가 객체지향구조에 대해 많은 경험이 없어서 문의 드리는데

저는 이 프로젝트를 구현할 때 실제 로또의 가격을 로또 기계가 알까 로또가 알까에 대해 고민을 하고 구현을 했거든요 ㅎㅎ
근데 이게 실제 세계로 보면 로또 기계가 로또의 가격을 알고 있는 것이 맞긴한데 이런거에 집착하는게 좋은 객체지향 구조인지 아니면 적당하게(?) 생각하는게 맞는 걸까요...ㅎㅎ

2021-02-10 04:21 UTC, KimDoubleB commented on src/main/java/lotto/domain/LottoMachine.java
> +        if (money.getValue() < 1000) {
앗, 석현님 이야기 들어보니 그것도 맞다는 생각이 드네요. 로또의 가격이 유동적이라면 로또의 가격은 로또의 정보이지만 로또 기계가 정해주는 것이므로.... 더 나아가서, 가격이 많이 유동적이라면 setter 또는 LottoTicket에 대해 가격을 주입하는 방식으로도 만드는 것도 하나의 방법이겠네요 !
저는 이런 구조에 대해 집착하는 것이 좋다고 생각하는 편인데요. 요구사항에 대해 단순하게 구현한다면 사실 java 파일1~2개로도 구현이 가능할 것이라 생각해요. 하지만 코드 구조, 여기서의 가격을 누가 가지고 있을 것인가 같은 정보들을 잘 생각하고 구현해야 코드의 재활용성, 유지보수 측면에서 비용을 감소시킬 수 있다고 생각합니다. 이게 단순하지만 제일 어려운 것 같지만요😂.

2021-02-10 04:45 UTC, KimDoubleB commented on src/main/java/lotto/controller/LottoController.java
> +        List<List<Integer>> manualLottoNumbers = InputView.getManualLottoNumbers(numberOfManualLottoTicket);
보통 로또를 수동을 구매한다고 하면, 로또 번호를 직접 색칠하고(고르고) 로또티켓을 만들어서 로또 머신에 입력하므로 저는 로또 티켓을 만들어서 로또 머신에 넣어주는게 더 좋다고 생각했어요 :) 가독성도 더 좋아질 것이라고 생각했구요 !
만약 석현님께서 말씀하신 프로세스가 더 좋다고 생각이 드신다면, 그대로 유지하셔도 좋을 것 같습니다.

2021-02-10 06:24 UTC, HanSeokhyeon commented on src/main/java/lotto/controller/LottoController.java
> +        List<List<Integer>> manualLottoNumbers = InputView.getManualLottoNumbers(numberOfManualLottoTicket);
오 생각해보니 그렇네요 ㅋㅋ 수동으로 하는 경우에는 색칠해서 이미 로또를 만드니깐 보배님 의견이 맞네요...

2021-02-11 06:09 UTC, HanSeokhyeon commented on src/main/java/lotto/domain/LottoMachine.java
> +        if (money.getValue() < 1000) {
https://t1.daumcdn.net/cfile/tistory/234C863A52CFFE8234

ㅋㅋㅋ찾아보니 로또 가격도 로또에 있었네요...ㅎㅎ

2021-02-12 07:31 UTC, HanSeokhyeon commented
리뷰 감사합니다! 이리저리 리팩토링하다보니 양이 또 많이 늘어났네요...ㅎㅎ

2021-02-12 15:16 UTC, KimDoubleB approved these changes
수고 많으셨습니다, 석현님 !
LottoNumber, LottoPaper를 보며 리팩터링하려고 얼마나 노력하셨는지 알 수 있을 것 같습니다 !
또한 도메인에 대해 알아보며 공유 및 소통해주시면서 저 또한 더 생각해보게 되었던 것 같습니다.

완벽하지 않은 리뷰지만 석현님께 도움이 되었길 바라면서, PR 드리겠습니다. 그럼, 다음 미션도 화이팅입니다 !

2021-02-12 15:17 UTC, merged