[로또 - 2단계] 리뷰요청 드립니다.
next-step/java-lotto pull request #1231
Opened 2021-03-11 16:14 UTC by JuJinPark

안녕하세요 리뷰어님 😄 😄

나름 구현한다고 했는데 이번에도 고민이 많은 미션이었습니다.

제가 설계할때 고민했던 부분을 보시면  피드백을 좀 더 정확하게 받을 수 있지 않을까해서 남깁니다
- 로또가격,로또번호(1-45),로또우승 상금 및 일치갯수 등 로또 게임의 룰과 같은 값들이 변화에 대응하기 위해서는 어떻게 관리하는게 좋을까요? 현재는 해당 값들이 필요한 객체에 상수로 정의되어 있는데 룰객체와 같이 한곳에서 관리하는게 더 좋을까요?
- Lottery,LotteryNumber,LotteryTicket과 같은 객체들이 어디까지는 공개가 되어도 문제가 없을까요? 현재 lotteryTicketList밖으로는  LotteryTicket이 아닌 lotteryTicketDto객체를 노출 시켰는데 적절하다고 볼 수 있을까요? 

리뷰 잘 부탁 드립니다.🙇🙇🙇

2021-03-11 23:41 UTC, wheejuni requested changes
로또 과제의 본격적인 시작을 하시느라 수고 많으셨습니다. 👍 💯 
그러나 아쉽게도 구조상에 많은 변화가 필요할 거라고 생각됩니다.
우선 **LotteryStatisticMatchResult** 와 **LotteryPrizeResult**, **LotteryMatchResult** 클래스는 제거하는 것을 목표로 설계를 다시 구상해보시면 어떨까 싶습니다.
`LotteryTicket` 과 `Lottery` 가 더 많은 일을 하도록 역할 부여해주시고, `LottoPrize` 를 더 적극적으로 사용하는 방향도 생각해볼만 합니다. 
자세한 내용은 코드 안에도 코멘트를 통해 남겨 드렸으니 확인해 주시면 감사하겠습니다!
2단계에서 충분한 경험을 통해 남은 과제들을 수행할 수 있는 힘을 얻으셨으면 좋겠습니다. 힘내세요! 🥇

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/domain/Lottery.java
> +    private static final int LOTTERY_NUMBER_SIZE = 6;
로또의 번호 선택 개수가 여섯개인 것은 변동성이 매우 적은 규칙이므로,
지금처럼 상수로 관리되는 것이 적절해보이고, `Rule` 과 같은 클래스가 생기는 것은 과도한 분리일 수 있다고 생각합니다.

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/domain/Lottery.java
> +        }
이 로직은 `LottoNumberRandomGenerator` 에게 온전히 맡기는게 더 좋아보이는데 어떻게 생각하시나요.
`LottoNumberRandomGenerator` 가 완전한 형태의 `Set<LotteryNumber>` 를 리턴하는 것이 더 좋아보입니다.

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/domain/Lottery.java
> +    public boolean isMatch(LotteryNumber lotteryNumber) {
`public` 보다 더 가려져도 괜찮을 것 같은데요?

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/domain/LotteryGame.java
> +        WinningLotteryTicket lastWinningLotteryTicket = new WinningLotteryTicket(winningLotteryNumbersRequest.getLastWinningLotteryNumbers());
적절한 시점에 강제 개행을 통해서 변수명과 타입이 한 줄에 위치하도록 수정해주세요.

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/domain/LotteryPrize.java
> +    }
두 개의 `Lottery` 객체를 전달받아 매칭 카운트를 계수하는 로직을 여기에 위치시키면 어떨까요?
카운트한 다음 적합한 enum을 찾아 리턴할 수 있을 것 같아요. 그대신 "꽝" 도 enum을 통해 관리돼야겠네요.

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/domain/LotteryTicketList.java
> +    }
`add` 보다는, static factory method로 전환하는 것이 좋지 않을까 생각합니다.
기본 생성자를 `private` 으로 가린 후에 `LotteryTicketList.ofCountAndPrice()` 와 같은 스태틱 생성자 메소드 구현하여 로직 만들 수 있을 듯합니다.

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/domain/LottoNumberRandomGenerator.java
> +    public static LotteryNumber generate() {
여기서 완전체 `Lottery` 를 만들어주는 것이 더 자연스러워 보입니다.

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/dto/LotteryMatchResult.java
> +public class LotteryMatchResult {
당첨 결과에 대한 추상화는 `LottoPrize`로 충분하다고 생각하는데요.
`LotteryTicket` 이 직접 자신의 당첨내역을 관리할 수 있다면 이 클래스는 없어져도 될 것 같습니다.
`LotteryTicket` 에 `LottoPrize` 필드 추가하고 당첨 여부를 스스로 관리하게 넘겨주는 게 어떨까요?

2021-03-11 23:41 UTC, wheejuni commented on src/main/java/lotto/dto/LotteryStatisticMatchResult.java
> +    private LotteryPrizeResult fourthPrizeLotteryResult;
`LotteryPrize` 리스트를 순회하면서 몇 등짜리 enum인지 순회하는 것만으로도 충분히 몇 등짜리가 몇 개 당첨되었는지 카운트할 수 있어서, 이런 필드를 갖는 지금과 같은 클래스는 불필요하다고 생각합니다.

2021-03-12 02:46 UTC, JuJinPark commented on src/main/java/lotto/domain/Lottery.java
> +        }
안녕하세요 리뷰어님 😄 😄
저는 두가지 이유에서 저렇게 구현했습니다. 
-  Lottery를 수동으로 생성할 시에 validateSize를 하기위해서는 LOTTERY_NUMBER_SIZE를 알아야하는데 그렇게되면 LottoNumberRandomGenerator 안에서도 LOTTERY_NUMBER_SIZE를 가지고 있고 lottery에서도 가지고있는 형태가 될것 같았습니다.
- LottoNumberRandomGenerator 는 로또번호를 무작위로 생성하는 책임만 부여하는게 맞다고 생각했습니다. 중복된 로또 번호가 없게 그리고 LOTTERY_NUMBER_SIZE에 맞게 생성하는 책임까지 부여하면 한가지 이상의 책임이 아닐까요?

2021-03-12 02:50 UTC, JuJinPark commented on src/main/java/lotto/domain/Lottery.java
> +    public boolean isMatch(LotteryNumber lotteryNumber) {
저는 향후 쓸일이 있지 않을까 해서 열어놓은 건데 현재는 굳이 열어놓을 필요가 없음으로 가리는게 더 나아 보이네요 👍👍

2021-03-12 03:04 UTC, JuJinPark commented on src/main/java/lotto/domain/LotteryTicketList.java
> +    }
안녕하세요 리뷰어님 😄 😄
add 관련 모든 메서드는 제거 하고  static factory method로 전환하는게 좋을 것 같다는 말씀이신거죠?
혹시 static factory method가 더 좋은 이유에 대해 설명 해 주실수 있을까요?
일단 저는 조금 과도하다고 생각될수 있지만 LotteryTicketList를 통해 중간에 새로운 로또 티켓이 추가될 수도 있는 변화에 대응하고자 add메서드를 넣었습니다.
어떻게 생각하시는지 의견 부탁드리겠습니다. 🙇

2021-03-12 03:20 UTC, wheejuni commented on src/main/java/lotto/domain/LotteryTicketList.java
> +    }
`LotteryTicketList` 는 불변하게 관리하고 새로운 티켓이 추가돼야한다면 새로운 객체를 처음부터 생성하는 방향은 어떨까요?

스태틱 팩토리를 통해 객체의 불변성을 통제하고 규칙에 맞는 객체만을 생성토록 강제하는 이점이 크다고 보았습니다.

2021-03-12 04:04 UTC, JuJinPark commented on src/main/java/lotto/dto/LotteryMatchResult.java
> +public class LotteryMatchResult {
네 정말 삭제해도 무방한 객체가 되었네요 👍 😄 
하지만 조금 의문이 남는 점이 있습니다.
애초에 LotteryStatisticMatchResult 라는 객체가 나오게 된것도 view 클래스가 도메인 객체들에 대한 의존성을 끊고 숨기기 위함이었습니다. 그렇다면 LotteryPrize는 view객체까지 노출되어도 무방한가에 대해 고민이 됩니다.

어떻게 생각하시는지 의견 부탁드리겠습니다. 🙇

2021-03-12 04:59 UTC, JuJinPark commented on src/main/java/lotto/dto/LotteryStatisticMatchResult.java
> +    private LotteryPrizeResult fourthPrizeLotteryResult;
해당 객체는 lotteryPrizeList와 로또생성시 사용된 돈을 담는 객체로 간소화 하였습니다.
😄😄😄

2021-03-12 06:17 UTC, JuJinPark commented on src/main/java/lotto/domain/Lottery.java
> +        }
의견 정말 감사합니다. 😄 
현재 LottoNumberRandomGenerator가 "로또 숫자 자체" 만 랜덤으로 생성하는것은 너무 지엽적인 책임분리라고 하셨는데 그 판단기준이 어떻게 될까요? 
현재 미션에서 LottoNumberRandomGenerator 처럼 지엽적으로 책임을 가지면서 나타나는 또는 향후에 나타날 수 있는 문제가 있을까요?

2021-03-12 06:39 UTC, JuJinPark commented on src/main/java/lotto/domain/LotteryTicketList.java
> +    }
의견 감사합니다 😄 😄 
-정적 팩토리 메서드의 장점은 알고 있는데(https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C) 여기서 나열된 어떤 ​장점 때문에 지금 LotteryTicketList가 생성자 대신 선택을 해야 하는지 알고 싶습니다.
- 객체불변성을 지키면 오는 장점을 알고 있지만 현재 상황에서 과연 추가할때마다 새로운 lottoTicketList를 생성할 필요가 있을까요?  LotteryTicketList 밖으로 LotteryTicket은  출되고 있지 않음으로 개인적으로 어느정도 불변성은 잘 지켜져 있다고 생각합니다. 

어떻게 생각하시나요?

2021-03-12 08:22 UTC, wheejuni commented on src/main/java/lotto/domain/LotteryTicketList.java
> +    }
@JuJinPark 네 생각하신 방향대로 진행하시면 되겠습니다.

2021-03-12 08:23 UTC, wheejuni approved these changes
빠르게 반영해주셔서 수고 많으셨습니다. 👍 추가로 수정하실 부분은 3단계에서 반영해 주시고, 여기선 충분한 경험을 하신 것 같아 merge 할게요.

2021-03-12 08:23 UTC, wheejuni commented on src/main/java/lotto/domain/LotteryPrize.java
> +    }
아 네, 그 방법이 낫겠습니다.

2021-03-12 08:23 UTC, wheejuni commented on src/main/java/lotto/domain/LotteryPrize.java
> +    }
👍

2021-03-12 08:23 UTC, merged