[로또 - 4단계] 리뷰요청 드립니다.
next-step/java-lotto pull request #1238
Opened 2021-03-14 12:25 UTC by JuJinPark

안녕하세요 리뷰어님 😄 😄😄 😄
이번 미션도 아래와 같은 고민 포인트가 있는 미션이었네요 

- 자동/수동 판별을 위한 적절한 방법은 무엇일까요?  1)LotteryTicketList에서 아예 분리된 두개의 개별리스트로 관리 vs 2)LotteryTicket에 필드 추가 vs 3) LotteryTicketList에서 count필드(int)만 생성후 관리 
저는 아래와 같은 단점들 중에 고민한후 2번 방법을 선택하였는데 리뷰어 님의 생각은 어떤가요?
 1번 단점- 모든 티켓에 대한 작업을 진행할때 두개의 리스트에 작업을 진행해야 한다.
 2번 단점- 화면에만 필요한 정보이고 실제 비지니스 로직을 수행하면서는 불필요한 정보가 생김
 3번 단점 - 향후 티켓이 추가로 생성되거나 삭제될떄마다 count필드 동기화 필요

- 향후 만약 수동 로또티켓과 자동 로또티켓이 로직이 달라져야 한다면 (예)당첨조회 방법) 인터페이스를 기반으로 두개의 클래스로 분리후 어떻게 관리하는게 좋을까요? 그때는 1번 방법이 좋을까요? 

설계에는 항상 답이 있지 않다느 걸 알지만 리뷰어님의 생각이 궁금합니다.🙇🙇🙇

2021-03-14 14:43 UTC, wheejuni requested changes
4단계 진행하시느라 수고 많으셨습니다. 👍 
저도 2번 방법이 나쁘다고 생각하지는 않는데 사실 제 생각이 중요한 건 아닙니다. 어떤 설계로도 좋은 코드와 나쁜 코드가 다 나올 수 있고요, 제가 섣불리 설계 방향에 대한 의견을 드리면 다른 방향으로 생각해보실 기회를 빼앗는 것이기에 앞으로도 제 생각은 최소한만 들려드리겠습니다. 

또한 두번째 질문은 조금은 이해가 어려웠습니다. _어떻게 관리하는 게 좋을까_ 를 여쭤보셨는데 **어떻게** 는 다소 모호하다는 생각이 듭니다. 제가 판단하기에는 이미 질문 중에 "인터페이스 기반으로 분리" 라는 좋은 방향을 잡으셨고, 그렇다면 인터페이스에 대한 상세 구현을 두 클래스가 다르게 가져가면 자료구조나 필드에 대해 고민하지 않으셔도 충분히 대응할 수 있는 방향이라고 생각이 듭니다. 

질문에 대한 답변은 이정도로 드리겠습니다. 더불어서 작성하신 코드에 대한 피드백도 남겨 드렸는데요, 확인해 보시고 반영하거나 의견 남겨주세요. 🥇

2021-03-14 14:43 UTC, wheejuni commented on src/main/java/lotto/dto/LotteryPurchaseRequest.java
> +    private List<List<Integer>> listOfManualLotteryNumberList;
`ManualLotteryNumberList` 를 클래스로 분리하면 되겠네요.

2021-03-14 14:43 UTC, wheejuni commented on src/main/java/lotto/view/InputView.java
> +        }
`String[]` 에서 `int` 로 가는 로직이 반복되는 것 같은데 적절한 `private` 메소드로 분리해 주세요.

2021-03-15 02:54 UTC, JuJinPark commented on src/main/java/lotto/controller/LotteryController.java
> +        ResultView.printFinalResult(lotteryGame.getLotteryTickets());
조금 과한지는 모르겠지만 view에서 도메인에 대해 의존하지 않아야 된다고 생각했습니다. 그래서 도메인과 view는 dto를 통해서만 서로 통신하다 보디 저렇게 작업을 하였습니다.
또한 도메인 에서 넘어오는 데이터를 적절한 형태로 가공해서 보여주는 책임은 view에 있다고 생각합니다. 그래서 만약 lotteryGame에서 콘솔아웃 직전에 문자열을 만들어준다면 출력되는 문자열이 변경되거나 또는 다른 형태에 view가 추가되고 콘솔과 다른 형태로 출력이 되어야 한다면 변경이 고스란히 LotteryGame에 퍼진다고 생각합니다.
리뷰어님의 생각은 어떠신가요? 😄   😄

2021-03-15 02:58 UTC, JuJinPark commented on src/main/java/lotto/domain/LotteryNumber.java
> +    private static Map<Integer, LotteryNumber> lotteryNumberMap = new HashMap<>();
lotteryNumberMap은 지금 상황에서는 과한 부분이 없지 않지만 피드백 강의 영상을 보고 LotteryNumber생성시 인스턴스의 과도한 생성을 막기위해 캐싱개념을 적용해 보았습니다.
list로 관리하면 특정 LotteryNumber을 찾기위한 작업이(o(n)) map(o(1))보다 비효율적이다고 생각해 map을 이용하였습니다.
리뷰어님의 생각은 어떠신가요? 😄 😄

2021-03-15 03:04 UTC, JuJinPark commented on src/main/java/lotto/domain/LotteryTicket.java
> +    }
현재 getCreatedType() 메서드는 dto로 변환하기 위해서만 사용되고 있습니다.
getter를 최소화 해야 된다는걸 알고 있지만  화면 노출을 위한 용도로는 괜찮지 않을까요?? 😄

2021-03-15 03:10 UTC, JuJinPark commented on src/main/java/lotto/domain/LotteryNumber.java
> +        if (!lotteryNumberMap.containsKey(value)) {
네 위에서 언급한건 처럼 조금 과하지만 피드백 강의 영상을 기반으로 적용해보았습니다. value에 대한 validation은 containsKey로 대처할 수 있을것 같아서 제거 하였습니다.
리뷰어님의 생각은 어떠신가요? 😄 😄

2021-03-15 03:24 UTC, JuJinPark commented on src/main/java/lotto/domain/LotterySeller.java
> +        int numberOfTickets = purchaseRequest.getAmountOfMoney() / LOTTERY_TICKET_PRICE;
dto는 getter가 자연스럽고 그럼으로 데이터를 자꾸 가져와서 연산을 하려고 했던거 같아요 
피드백 감사합니다. 👍 👍

2021-03-15 03:37 UTC, JuJinPark commented
제 질문에 대한 의견 감사합니다. 🙇 🙇 🙇 
> 제가 섣불리 설계 방향에 대한 의견을 드리면 다른 방향으로 생각해보실 기회를 빼앗는 것이기에
위에서 말씀하신 부분은 매우 동의합니다.
하지만 저는 저 나름대로 여러가지 방향으로 생각을 해보고 그중에 하나의 방법을 선택 했습니다. 하지만 제가 생각하지 못했던 방법 또는 제가 생각한 방향에 대한 다른 의견이 있는지에 대해 궁금해 질문을 올렸습니다. 이런 방식으로 의견을 공유를 통해 설계에 대한 시각을 넓힐수 있지 않을까 하여 그렇게 진행했습니다. 이런 방식은 설계에 대해 배우는데 도움이 되지 않는 방식일까요? 🤔 🤔 
두번째 질문은 인터페이스 기반으로 클래스를 분리한후에도 화면에서 자동 몇개 수동 몇개 이런식으로 출력이 필요하다면 list를 2개로 관리 또는 자동 수동 로또티켓 갯수 필드와 같은 방법이 필요해 보여 어떤 방식이 나을지에 대한 질문 이었습니다.

2021-03-15 09:25 UTC, wheejuni commented on src/main/java/lotto/controller/LotteryController.java
> +        ResultView.printFinalResult(lotteryGame.getLotteryTickets());
전 생각이 다르지만 확신을 갖고 계신듯 하여 더 이상 피드백은 드리지 않겠습니다. ㅎㅎ 좋습니다!

2021-03-15 09:26 UTC, wheejuni commented on src/main/java/lotto/domain/LotteryTicket.java
> +    }
앞으로도 DTO 생성을 위해서만 사용될거란 보장이 가능한가요?

2021-03-15 09:34 UTC, wheejuni commented
@JuJinPark 설계에 대한 시각을 넓히기 위해 질문한다고 하셨지만, 제가 느끼기엔 이미 정해진 의사결정에 대해 확신을 얻고자 제게 질문을 던지시는 것으로 받아들여져 리뷰어로써 다소 힘든 부분이 있었습니다. ㅠㅠ 그러나 어떤 마음으로 그렇게 하셨는지 이제 이해합니다. 

코멘트 다신 것, 저와 생각이 다른 부분도 있지만 어쨌거나 주진님이 확신을 갖고 계시다면 제 생각과 무관하게 구현하시면 되고, 그것이 전혀 나쁜게 아니라서 생각이 다른 부분에 대해서도 제가 동의하는 취지로 댓글 몇 개 남겼습니다. 

이외에 더 의견이 필요하면 알려주세요. 추가 수정이 덜 된 것으로 보이는데요, 다 진행하시고 리뷰 요청 보내주시고요.

2021-03-15 09:53 UTC, wheejuni approved these changes
수고하셨습니다. 👏👏

2021-03-15 09:53 UTC, merged