2단계 -  로또(자동)
next-step/java-lotto pull request #1239
Opened 2021-03-14 13:18 UTC by meme2367

2021-03-15 15:14 UTC, vagabond95 requested changes
업무가 많아 리뷰가 늦어져 죄송합니다. (_ _) enum 으로 등수를 구분하는 것, statistic 클래스를 통해 스스로 계산이 가능한 것 등 클래스 설계에서 많은 고민을 하신 흔적이 느껴졌습니다 👍 

MVC 구조 관점에서의 역할과 메소드의 책임, 예외처리의 관점에서 코멘트를 남겼는데요!
확인 후 다시 리뷰요청 부탁드릴게요 ㅎㅎ

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/view/ResultView.java
> +        if(earningRate < 1) {
손해인지, 이득인지 판단하는 것은 도메인(모델)의 영역에서 판단해야하는 정보 아닐까요~?

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/view/ResultView.java
> +        System.out.println(lottoCount + "개를 구매했습니다.");
문자열을 상수로 관리하면 가독성 및 관리에 용이할 것 같아요!

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/view/InputView.java
> +        String winngLottoNumbers = new Scanner(System.in).nextLine();
View 에서 Lotto 라는 도메인 클래스를 만드는 정보를 알고 있을 필요가 있을까요~?
Lotto 라는 도메인의 생성방식이 바뀌면 View 에서 변경이 발생하는 것이 적절할까요~?!

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoStatistics.java
> +    public String toString() {
toString() 은 클래스를 문자열로 표현하기 위한 수단일뿐, View 에서 그려져야하는 로직이 담겨져 있어서는 안된다고 생각되어요!

View 에서 표현하는 요구사항이 변할때 도메인에 변경이 발생하면 MVC 로 계층을 분리한 이점이 반감되지 않을까요~?

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoStatistics.java
> +            lottoStaticResult.put(rank,lottoStaticResult.get(rank)+1);
```suggestion
            lottoStaticResult.put(rank, lottoStaticResult.get(rank) + 1);
```
이러한 컨벤션 규칙은 ide 에서 제공하는 reformat 기능을 활용하시면 일괄적으로 변경이 가능합니다 :)

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoRank.java
> +    FIRST(6, 2_000_000_000),
가독성을 확보한 숫자표기 👍

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoRank.java
> +    public static LottoRank findByMatchingCount(int matchingCount) {
n < 0 || n > 6 의 수가 들어오면 ZERO 가 반환될 것으로 보이는데요, 별도 예외처리가 필요하지 않을까요~?

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/domain/Lotto.java
> +            count += lastWeekWinningLotto.increaseCount(lottoNumber);
```suggestion
            count += contains(lottoNumber) ? 1 : 0;
```
과 같은 표현식으로 가독성을 확보해보는 것은 어떨까요?
increaseCount 메소드 내부는 엄밀히얘기하면 count 를 증가시키는게 아니라 증가시킬 count 를 반환하는 메소드인데 현재 네이밍으로는 혼동이 올 수 있을 것 같아요!

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoList.java
> +        this.lottoList = lottoList;
중복된 숫자가 없는지 체크로직이 필요하지 않을까요~?

2021-03-15 15:14 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoNumber.java
> +        this.value = value;
value 범위에 대한 체크로직이 필요하지 않을까요~?

2021-03-16 15:27 UTC, meme2367 commented on src/main/java/lotto/domain/LottoStatistics.java
> +    public String toString() {
아하 그렇네요 굳이 tostring을 쓸 필요가 없었네요 좋은 의견 감사합니다!

2021-03-16 16:17 UTC, meme2367 commented on src/main/java/lotto/domain/LottoStatistics.java
> +            lottoStaticResult.put(rank,lottoStaticResult.get(rank)+1);
꿀팁 감사합니당

2021-03-16 17:43 UTC, meme2367 commented on src/main/java/lotto/domain/LottoStatistics.java
> +    public String toString() {
그런데 toString을 쓰지 않고 ResultView 클래스에서 출력을 하려고 getter를 사용했는데요.. 전에 수업에서 getter를 쓰지 말라고 들어서..리팩토링한 코드에 확신이 들지 않네요ㅠㅠ 보통 getter는 아예 사용하지 않나요? 그리고 또 궁금한 사항이 테스트 코드를 작성하다 보니 도메인 클래스의 예외처리 메서드를 static으로 바꾸어서 사용해보았는데, 메모리 관점에서 좋지 않다는 생각도 듭니다. 보통 static은 어떤 경우 사용할까요? 도메인 클래스의 메서드들을 static으로 해서 테스트코드에서 사용해도 되는걸까요?

2021-03-17 13:55 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoStatistics.java
> +    public String toString() {
getter 조건때문에 혼동이 오셨군요 ㅎㅎ

사실 getter 가 없으면 도메인 클래스가 가지고 있는 데이터를 다른계층에 전달할 수 있는 방법이 없기때문에 말씀하신 것처럼 toString() 과 같은 우회코드가 발생하게 됩니다. 따라서 getter 자체는 아예 배제하기 어렵다고 생각됩니다.

조건을 다시 정의해보면 'getter 는 다른 계층에 데이터를 전달할때를 제외하고는 사용하지 말아라' 가 될 것 같아요.
getter 를 최대한 지양하는 이유는 다음 글(https://www.slipp.net/questions/559) 에서 힌트를 얻으실 수 있습니다!

static 메소드의 경우 제가 질문을 잘 이해한것인지 모르겠으나, 제가 사용하는 기준은 static 메소드가 수행하고자 하는 로직에 일반 멤버변수가 필요하지 않은가? 여부입니다. 가령 String 의 null or empty 여부를 체크하는 메소드는 주어진 string 인자로만 수행이 가능하기 떄문에 static 메소드로 제공이 가능하겠죠. 해당 이유외에 일반 메소드를 static 메소드로 변환하는 것은 static 키워드의 본래 목적을 살리지 못한다고 생각합니다.

2021-03-17 13:59 UTC, vagabond95 approved these changes
전달드린 피드백 잘 반영해주셨습니다 👍 
질문주신 내용은 하위 코멘트로 남겼는데 확인 부탁드려요!

2단계는 머지하도록 하겠습니다 :)

2021-03-17 13:59 UTC, vagabond95 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +      LottoNumber.validateNumber(input);
validateNumber 메소드를 단지 테스트하기위해 public 으로 드러낼 이유는 없다고 생각해요!
이렇게 내부에서 사용되는 메소드가 외부에 드러날수록 해당 객체와의 의존성이 강해지기 때문입니다.
LottoNumber 객체를 생성하는것으로도 동일한 테스트를 진행할 수 있지 않을까요?

2021-03-17 14:00 UTC, merged

2021-03-17 14:02 UTC, meme2367 commented on src/main/java/lotto/domain/LottoStatistics.java
> +    public String toString() {
getter와 static이 많이 헷갈렸는데 의견 감사합니다..!