[로또 - 4단계] 리뷰 요청 드립니다.
next-step/java-lotto pull request #1273
Opened 2021-03-19 18:47 UTC by SeokRae

안녕하세요 리뷰어님 !

4단계 진행은 기존의 테스트 케이스가 깨지지 않도록 하는 것과 최대한 클래스를 생성하지 않고 재사용 할 수 있는 방법으로 생각해보았습니다.

결국엔 생성자와 필요한 메서드가 생성되었으며 자동 생성하는 인터페이스의 구현체와 수동 생성하는 인터페이스의 구현체가 생성되었습니다.

뭔가 억지로 껴 맞추는 느낌도 없지 않고 요구사항이 늘어갈때 마다 기존코드를 뒤엎어야 하나 고민하는게 그나마 줄어들고 있어서 다행인 것 같습니다.

고생스러우시겠지만 피드백 잘 부탁드립니다. !
감사합니다.

2021-03-20 08:06 UTC, siyoon210 requested changes
안녕하세요 석래님!
마지막 단계까지 잘 구현해주셨습니다. 👏 
미션을 마무리하기 앞서서 고민해보셨으면 하는 사항에 대해서 의견을 남겨드렸습니다. 😁

2021-03-20 08:06 UTC, siyoon210 commented on src/main/java/study/lotto/view/InputView.java
>  public class InputView {
View의 모든 로직들이 staic이 되었네요.
static만을 제공하는 Util 클래스라면 private 기본생성자를 명시적으로 선언해서, 외부에서 사용하는 사용자들이 임의로 객체를 만들지 않게 강제할 수 있습니다. (자바의 매력은 이런거라고 생각이 드네요. 😁 )

---

(이 부분은 수정을 권하는 피드백이 아닙니다.)
기능을 static으로 제공하면 어떤 장점과 단점이 있을까요? 🤔 
제가 생각하는 장점은 편리함입니다. 별도의 객체선언 없이 사용할수 있으니까요.
단점은 너무 강한 결합이라고 생각해요. 객체가 아니게되니 디자인 패턴을 적용하기도 어려워지고 결합도를 낮추는 고민을 해볼수 있는 기회가 없어집니다. 저는 static으로 제공할때는 정말로 이 강한 결합을 허용해도 될까? 고민하는 편입니다. 😁

2021-03-20 08:53 UTC, SeokRae commented on src/test/java/study/lotto/service/LottosTest.java
> +        assertThat(of.toString()).isEqualTo(expected);
오 !! API에 대해서 좀 더 찾아봐야 겠습니다. 감사합니다. !!

2021-03-20 09:00 UTC, SeokRae commented
정말 소중한 피드백 감사드립니다. ㅠㅠ!
열심히 고민해서 수정하도록 하겠습니다.

2021-03-26 20:45 UTC, SeokRae commented
안녕하세요 리뷰어님 ~
몇 번씩 바꿔보다가 wrapper 클래스를 이용하는 것과 
인터페이스로 구성했음에도 재사용? 했다고 하기에 애매한 점으로 방식을 바꿔야 했습니다.

코드나 책 많이 보고 학습해야 할 것 같습니다..  ㅠㅠ

리뷰 해주시느라 고생 많으십니다.
감사합니다.~

2021-03-27 01:10 UTC, siyoon210 requested changes
안녕하세요 석래님!
대대적인 리팩토링을 하셨네요. 👍👍  💯 
고민하는 과정중에 더 성장하셨을꺼라 믿습니다. 😄 

몇몇 테스트코드가 실패하고 있어요. 👀
이 부분만 수정해주시면 로또 과정을 마무리 하도록 하겠습니다. 🚀

2021-03-27 01:10 UTC, siyoon210 commented on src/main/java/study/lotto/util/Constants.java
> +public class Constants {
이 클래스에 대해서는 고민이 많이 되네요. 🤔 
상수를 모아두는 측면에서는 기능적으로 도움이 되겠지만 클래스란 무엇인가?에 대해서 고민을 해보게 되었어요.
클래스란 객체를 위한 '틀, 프로토타입, 분류...' 라고 생각했을때 이 클래스는 이런 의도로 씌여지는건 아니니까요.
만약 여러 객체에서 공유해야하는 상수라면 enum을 사용해서 제공하면 될것이고, 공유되지 않는 메세지는 사용되는 객체에서 선언하는것이 더 낫지 않을까 생각했습니다.
정답은 없는 영역 같습니다. 💭

2021-03-27 01:10 UTC, siyoon210 commented on src/main/java/study/lotto/view/InputView.java
> -    }
non-static 메서드로 제공하시기 위해서 대대적인 공사가 있었군요. 👍

2021-03-27 01:10 UTC, siyoon210 commented on src/test/java/study/lotto/service/LottosTest.java
> +public class LottosTest {
몇몇 테스트가 실패해요.. 👀

2021-03-27 03:43 UTC, SeokRae commented on src/main/java/study/lotto/domain/Money.java
> +                .intValue();
아 비용이 더 들어간다라는 측면에서는 생각하지 못했습니다.
이 부분에 대해서는 다시 한 번 꼭 생각해보겠습니다.
감사합니다.

2021-03-27 03:46 UTC, SeokRae commented on src/main/java/study/lotto/domain/Money.java
> +    }
데이터를 가공하여 사용할 때 처리가 항상 고민인 것 같습니다. 😭
boolean 값으로 체크를 해서 parse 해야할 지
아니면 parse를 해서 그냥 exception 처리 해야할지..

2021-03-27 03:47 UTC, SeokRae commented on src/main/java/study/lotto/domain/LottoNumber.java
> +    protected LottoNumber(final String bonusNumber) {
팩토리 패턴으로 제공을 하고 있기 때문에 기본 생성자의 접근 제한자를 default로 수정해도 되는거죠?

2021-03-27 14:03 UTC, SeokRae commented on src/test/java/study/lotto/service/LottosTest.java
> +public class LottosTest {
테스트 코드 수정하여 정상 테스트로 수정하겠습니다. ~

2021-03-27 14:06 UTC, SeokRae commented on src/main/java/study/lotto/generator/NumberGenerator.java
> +    List<LottoNumber> generate(String text);
다형성으로 코드의 확장성을 위해 인터페이스로 코드를 구성하였으나
인터페이스의 장점을 살리지 못하여 Factory 클래스로 구현하였습니다.

2021-03-28 06:50 UTC, siyoon210 commented on src/main/java/study/lotto/domain/LottoNumber.java
> +    protected LottoNumber(final String bonusNumber) {
아뇨 기본생성자를 접근하고 있는 부분이, 클래스 내부와 같은 패키지인 WinningLotto에서 접근하고 있으니 protected 보다 더 좁은 접근제어자를 쓰는게 어떨까 하는 의견이었습니다.

근데 지금보니까 아예 private로 바꾸고 외부에서는 모두 정적팩토리 메서드로 접근하게 해도 좋겠다는 생각이 드네요. 🤔

2021-03-28 08:22 UTC, SeokRae commented on src/main/java/study/lotto/domain/LottoNumber.java
> +    protected LottoNumber(final String bonusNumber) {
아 접근하는 객체의 범위가 패키지 내부에서 사용했기 때문에 그런거였군요. !
private -> protected로 수정했던 이유는 테스트 코드에서 new 키워드를 통해 생성하여 진행했던 내용을
정적 팩토리 메서드로 수정하지 않아도 동작하는 상태를 유지 하기위해서 였었는데

그냥 private로 다 바꾸고 팩토리 메서드를 통해 테스트 코드를 진행하도록 하는게 좋을까요?

2021-03-28 08:43 UTC, SeokRae commented on src/main/java/study/lotto/domain/LottoNumber.java
> +    protected LottoNumber(final String bonusNumber) {
수정을 계속 하다보니 테스트 코드에 대한 일관성있는 코드로 하기 위해서는 
팩토리 메서드로 제공하는 것이 좋다 생각이 들어서, 도메인 코드는 최대한 통일해보려합니다.

2021-03-28 11:37 UTC, SeokRae commented on src/main/java/study/lotto/util/Constants.java
> +public class Constants {
`공통적으로 많이 사용하게 되는 경우라면 상수 클래스로 만드는 것이 좋을 것 같다`라는 생각을 했는데
상수가 도메인 클래스에 강하게 엮여있는경우 외부 클래스 없이도 혼자서 돌아가야 한다는 기준으로 보면 해당 도메인 클래스에 있는 것이 좋을 것 같다는 생각을 했습니다.

2021-03-29 01:39 UTC, siyoon210 approved these changes
안녕하세요 석래님!
로또 미션은 여기서 마무리 하도록 하겠습니다. 고생하셨습니다. 🙇 

작은 리뷰사항도 적용해주시고 고민하시는 모습에 진심으로 감명했습니다. 
다른 리뷰이분들에게 제가 드리는 리뷰가 혼란이 되지는 않을지 한번 더 고민해보겠습니다. 🤔  좋은 영향 주셔서 감사합니다. 😄 

부족한 리뷰였지만 도움되셨기를 바랍니다. 미션 이후로도 이야기 해보고 싶으신 부분이 있다면 언제든지 메세지 주세요! 🚀🚀🚀

2021-03-29 01:39 UTC, siyoon210 commented on src/main/java/study/lotto/domain/Lotto.java
> +    private Lotto(final Collection<LottoNumber> lottoNumbers) {
제 생각에도 private로 하고 정적팩토리로만 제공하는게 일관성있고 좋은거 같습니다. 🙂  👍

2021-03-29 01:39 UTC, siyoon210 commented on src/main/java/study/lotto/domain/Money.java
> +        this.money = new BigDecimal(money);
혹시 `new BigDecimal()` 과 `BigDecimal.valuOf()`의 차이점을 알고 계신가요? 😄 
참고자료 첨부하겠습니다. (인자로 들어온 money는 자료형이 int라서 어떤걸 써도 차이가 없겠네요.)

[Java, BigDecimal 사용법 정리](https://jsonobject.tistory.com/466)

2021-03-29 01:39 UTC, merged