로또 미션 - Step3
next-step/java-lotto pull request #1280
Opened 2021-03-20 09:29 UTC by jhLim97

이번 미션에서는 6개의 로또 번호를 갖는 컬렉션을 감싸는 일급 컬렉션과 모든 로또를 관리하는 일급 컬렉션을 생성하였습니다!
추가적으로 기존의 Enum 클래스에서 보너스에 해당하는 금액을 관리하기 위해 로직에 수정이 있었습니다!

부족한 부분은 피드백 주시면 채워 나가도록 하겠습니다!!

2021-03-21 07:37 UTC, dbeod2 requested changes
일급 컬렉션을 활용해서 로또 미션 3번째 잘 구현해주셨네요 💯 💯 
2단계에서 잘 구현해 주신 부분들이 있어서 큰 수정없이 잘 진행하신 것 같아요
수고하셨습니다.
 
추가로 생각해보면 좋을 것같아 몇가지 의견남겨두었습니다. 🙇‍♀️
확인해보시고 재요청주세요 👍 👍

2021-03-21 07:37 UTC, dbeod2 commented on README.md
>    * 로또 1장의 가격은 1000원이다.
요구사항 정리 👍

2021-03-21 07:37 UTC, dbeod2 commented on src/main/java/lotto/domain/LottoPlay.java
> -    };
로또 번호에 대한 부분을 캐싱사용을 위해 선언하셨던거로 기억하는데 별도의 클래스로 분리해서 사용하게 된 이유가 무엇일까요? 🤔 
로또 번호를 일급콜렉터로 사용하시면서 분리하신걸까요 ?

2021-03-21 07:37 UTC, dbeod2 commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
금액을 관리 로직을 Enum 클래스로 분리 잘하셨어요💯💯💯

2021-03-21 07:37 UTC, dbeod2 commented on src/main/java/lotto/dto/LottoNumbers.java
> +    }
작성해주선 코드를 확인해보면 stream미사용시 for문안에 if문이 포함되어 있기 때문에 2depth가 됩니다.
프로그래밍 요구사항을 다시 확인해주세요 :)

```suggestion
     public boolean isContain(int bonusNumber) {
        for (LottoNumber lottoNumber : lottoNumbers) {
            if (bonusNumber == lottoNumber.getLottoNumber()) {
                return true;
            }
        }
        return false;
    }
```

2021-03-21 07:37 UTC, dbeod2 commented on src/main/java/lotto/dto/LottoNumbers.java
> +    }
위에 리뷰와 동일한 피드백드립니다. 🙇‍♀️

2021-03-21 07:37 UTC, dbeod2 commented on src/main/java/lotto/domain/MatchRank.java
> +
Rank Enum클래스가 있기때문에 작성해주신 클래스에 대한 부분도 
Rank클래스에서 해도 충분하다고 생각드는데 어떻게 생각하시나요? 🤔

확인부탁드립니다 ~

2021-03-21 09:10 UTC, jhLim97 commented on src/main/java/lotto/domain/LottoPlay.java
> -    };
1~45의 숫자는 각각의 로또게임의 상관없이 고정되어 있는 값이기에 한 클래스에서 static으로 생성해두고 가져다가 사용하면 될 것 같아서 별도의 클래스로 분리했었습니다! 현재 다시 step2에서 구현했던 대로 LottoPlay로 옮겨둔 상태이고 혹시 별도의 클래스로 옮기면 지금의 코드보다 효율이나 안좋은 부분이 있는지 알고싶습니다!

2021-03-21 09:11 UTC, jhLim97 commented on src/main/java/lotto/dto/LottoNumbers.java
> +    }
step2에서 받은 피드백인데 이번에도 똑같은 실수를 한 것 같아서 죄송합니다... 피드백 반영했습니다!!

2021-03-21 09:11 UTC, jhLim97 commented on src/main/java/lotto/dto/LottoNumbers.java
> +    }
네 반영했습니다!

2021-03-21 09:11 UTC, jhLim97 commented on src/main/java/lotto/domain/MatchRank.java
> +
네 Rank클래스에서 해당 로직처리하도록 수정했습니다!

2021-03-22 02:59 UTC, dbeod2 commented on src/main/java/lotto/domain/LottoPlay.java
> -    };
아하 그런이유로 별도 클래스로 분리하셨군요! 
제가 판단하기엔 로또게임에 사용되는 부분이기도 했고,작성해주신 객체안에서만 사용된다고 판단하기도 했고 
그부분을 별도의 클래스로 분리하셨길래 질의만 드린 부분이었습니다.! 
ㅇ

2021-03-22 03:17 UTC, dbeod2 approved these changes
피드백 빠르게 적용해주셨네용! 
몇가지 봐두시면 좋을 것같아 코멘트 남겼습니다. 
다음미션 진행시 반영해주셔도 좋을 것 같아 여기서 마무리 하겠습니다. 🙇‍♀️
수고하셨습니다 : )

2021-03-22 03:17 UTC, dbeod2 commented on src/main/java/lotto/dto/LottoNumbers.java
>      }
isMatching메소드에 trueOrFalse값을 인자값으로 넣고 보너스 번호와 로또 번호가 같을때 받아온 인자값을 true로 해주고 아닌경우 값을 바로 리턴해주시네용 이부분을 아래와 같이 수정이 가능할 것 같습니다 : ) 확인부탁드립니다

    public boolean isContain(int bonusNumber) {
        boolean trueOrFalse = false;

        for (LottoNumber lottoNumber : lottoNumbers) {
            trueOrFalse = isMatching(lottoNumber, bonusNumber);
        }

        return trueOrFalse;
    }

    public boolean isMatching(LottoNumber lottoNumber, int bonusNumber) {
        return bonusNumber == lottoNumber.getLottoNumber();
    }

2021-03-22 03:17 UTC, dbeod2 commented on src/main/java/lotto/dto/LottoNumbers.java
> +        }
이렇게도 표현이 가능하네요 :) 참고만 부탁드립니다.!!


    public int countMatchNumber(List<Integer> winningNumber) {
        return lottoNumbers.stream()
                .mapToInt(lottoNumber -> matchNumber(winningNumber, lottoNumber))
                .sum();
    }

2021-03-22 03:17 UTC, merged