[로또 4단계] 리뷰 부탁드립니다
next-step/java-lotto pull request #1304
Opened 2021-03-23 07:13 UTC by loop-study

안녕하세요. 박현철입니다.
피드백 반영하면서 역할이 변경되었습니다.
적절한지 확인 부탁드립니다!🧐🧐🧐🧐

진행하면서 의문사항 질문드리겠습니다.
가장 낮은 단계에서 테스트를 진행하다보면 
하위 객체를 이용하는 상위 객체는 어떤 테스트를 해야할지 잘 모르겠습니다 😭😭😭😭
피드백 부탁드립니다!.

2021-03-23 14:31 UTC, yongdae requested changes
현철님 이번 단계도 빠르게 진행해주셨네요. 👍

진행해주신 내용에 대해 의견드렸습니다.
코멘트와 별도로 2가지 의견을 드려요!

1. LottoNumber에 [정적 팩토리 메소드](https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C) 를 적용해보면 좋을 것 같아요.
2. 테스트 클래스와 테스트 메소드의 public 접근제한자를 지워보면 어떨까요?
  내용은 [테스트 참고 가이드](https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods)의 2.2 절을 참고해주세요. 

피드백 반영 후에 다시 리뷰 요청 부탁드리겠습니다. 🙇

2021-03-24 07:16 UTC, loop-study commented on src/test/java/lotto/domain/LottoMachineTest.java
> +        LottoTickets lottoTickets = LottoMachine.createLottoTickets(lottoQuantity);
테스트만을 위한 프로덕션 코드를 제대로 이해 못했었네요.😭😭😭

2021-03-24 07:17 UTC, loop-study commented on src/test/java/lotto/domain/LottoQuantityTest.java
> +        assertThat(lottoQuantity.isAutoQuantityCheck(ticketCount)).isTrue();
자동과 수동을 개수를 구별하기 위해 만든거였는데
실제로 테스트를 제외하곤 프로덕션에선 사용될 일이 없네요.

2021-03-24 07:17 UTC, loop-study commented on src/test/java/lotto/domain/LottoYieldTest.java
> +import java.net.Inet4Address;
알겠습니다.

2021-03-24 07:17 UTC, loop-study commented on src/main/java/lotto/domain/LottoMachine.java
>  public class LottoMachine {
넵!

2021-03-24 07:18 UTC, loop-study commented on src/main/java/lotto/domain/LottoMachine.java
> +import java.util.Optional;
😂😂

2021-03-24 07:18 UTC, loop-study commented on src/main/java/lotto/domain/LottoMachine.java
>      }
한번에 처리하겠다는 생각에 2가지 기능을 하나로 합쳐버렸네요.
자동발급과 수동발급으로 나누겠습니다.

2021-03-24 10:29 UTC, loop-study commented
안녕하세요 박현철입니다.
피드백 반영했습니다.
 - 테스트를 위한 불필요한 프로덕션 코드 제거했습니다.
 - jUnit 공식가이드에 나온 라이프사이클에 대한 내용 확인하여, 테스트마다 public, private 제거 했습니다. @BeforeAll 사용하지 않아 static 는 없습니다.
 - 언급해주신 정적 팩토리 메소드에 대해 블로그와 이펙티브 자바로 학습 후 적용했습니다.
 - 무의미한 import 제거 했습니다.

확인 후 피드백 부탁드립니다.
감사합니다!

2021-03-24 13:14 UTC, yongdae requested changes
현철님 피드백을 잘 반영해주셨네요. 👍👍

진행해주신 내용에대해서 의견 남겨놓았습니다 ~
이번 피드백 같은 경우에는 `로또를 구매 할 때 수동과 자동을 나누어서 티켓을 발급받는다`
라는 가정하에 고민해보시면 좋을 것 같아요. 😄

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

2021-03-24 13:14 UTC, yongdae commented on src/main/java/lotto/domain/LottoQuantity.java
>      }
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

이 부분도 일종의 getter이라고 생각되는데
getter을 사용하지 않고 쓸 수 있는 방법은 없을까요? 🤔

2021-03-24 13:14 UTC, yongdae commented on src/main/java/lotto/domain/Quantity.java
> +    public boolean isQuantityCheck(int quantity) {
이 메소드는 사용하지 않네요. 😢

2021-03-24 13:14 UTC, yongdae commented on src/main/java/lotto/domain/Quantity.java
> +    }
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

LottoQuantity와 동일하게 이 규칙을 적용해보면 좋을 것 같아요. :)

2021-03-24 13:14 UTC, yongdae commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    void numberRangeTest(int inputNumber) throws Exception {
`throws Exception` 구문을 삭제하면 어떨까요?

예외를 던지는 구문은 지우는게 좋을 것 같은데 (테스트 메소드 전체)
혹시 의도하신 내용이 있으신가요?? 🤔

2021-03-24 13:16 UTC, loop-study commented on src/main/java/lotto/domain/Quantity.java
> +    public boolean isQuantityCheck(int quantity) {
아. 😭😭 처리하겠습니다.

2021-03-24 13:17 UTC, loop-study commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    void numberRangeTest(int inputNumber) throws Exception {
아. 템플릿으로 만들어서 사용하다보니 throw Exception 이 들어갔습니다
템플릿을 수정하겠습니다.

2021-03-25 03:43 UTC, loop-study commented
안녕하세요 박현철입니다.
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.
반영하기 어렵네요😂😂
확인 부탁드립니다.

2021-03-25 12:26 UTC, yongdae requested changes
현철님 ~ 피드백 반영해주신 내용에대해 다시 의견 드렸습니다. 😄
DM을 통해 나누었던 대화를 반영해서 의견드린 부분이니 확인해주시면 될 것 같습니다.

그럼 확인 후 다시 리뷰 요청 부탁드리겠습니다. 🙇

2021-03-25 12:26 UTC, yongdae commented on src/main/java/lotto/domain/LottoQuantity.java
>      }
이 메소드는 없어도 될 것 같아요. :)

ResultView.printLottoQuantity() 메소드 내부에서 수동, 자동 값을 출력하기 위해 사용하고 있는데
Controller에 있는 buyAmount, manualQuantity 이 값을 전달해서 사용해도 되지 않을까요?

2021-03-25 12:26 UTC, yongdae commented on src/main/java/lotto/domain/LottoQuantity.java
> +    }
테스트를 위한 코드에요. 😢

테스트에서만 사용되는 코드인 것 같아요 삭제하는게 좋을 것 같아요. :)

2021-03-25 12:26 UTC, yongdae commented on src/test/java/lotto/domain/LottoQuantityTest.java
> +class LottoQuantityTest {
자동 구매만, 수동 구매만 할 수 있는 테스트가 없어요 ~

이전 피드백에서 수동과 자동을 고민해보시는 것에대해 이야기 드렸었는데요.
DM에서 대화를 통해 결정이 난 것처럼 이 부분이 번거롭다고 생각하시면
이 테스트에대한 내용은 넘어가시면 될 것 같습니다. :)

2021-03-25 12:26 UTC, yongdae commented on src/test/java/lotto/domain/LottoFactoryTest.java
> +class LottoFactoryTest {
LottoQuantity를 사용하지 않고 LottoFactory를 테스트 할 수는 없을까요? 🤔

지금은 LottoQuantity가 있어야만 LottoFactory를 사용할 수 있는데요.
꼭 LottoQuantity 있어야만 로또를 구매가 가능해야한지 고민해보면 좋을 것 같습니다.

2021-03-25 13:07 UTC, loop-study commented
안녕하세요 박현철입니다.
피드백 반영했습니다.
금액과 수량을 랩핑하여 Quantity 로 관리해야한다는 생각만 하다보니 잘못된걸 놓치고있었네요
말씀대로 저 역할을 ResultView, LottoMachine 사용할 필요가 없어보였습니다...
LottoMachine 에서 수량 계산하는게 훨씬 더 깔끔하다고 느껴질 정도네요😂😂😂
자동, 수동 따로 발급하여 합치도록 수정했습니다. 테스트에서도 자동, 수동 테스트가 가능해졌습니다.
확인 부탁드리곘습니다.🙈🙈🙈🙈

2021-03-25 13:27 UTC, yongdae approved these changes
안녕하세요. 현철님 ~ 마지막 피드백도 잘 반영해주셨네요. 👍👍

로또 미션은 여기서 마무리하면 될 것 같습니다~
미션 마지막까지 잘 따라와주셔서 감사합니다. 🙇

짧은 시간이었지만 로또 미션을 함께하신 경험이 현철님께 조금이나마 도움이 되었으면 하는 바램입니다!

고생 많으셨고 남은 미션들도 완주하시길 응원하겠습니다! 🙏

2021-03-25 13:28 UTC, merged

2021-03-25 13:31 UTC, loop-study commented
감사합니다. 로또를 하면서 매번 새로운걸 하나씩 알아갔습니다!