[로또 - 2단계]리뷰 요청 드립니다.
next-step/java-lotto pull request #1307
Opened 2021-03-23 12:34 UTC by jaystar13

안녕하세요.
여러번 갈아 엎느라 또 시간이 많이 걸렸네요.😂
로또 2단계 리뷰 요청 드립니다.

이번 단계 진행하면서 생각한 고민들 입니다.
저에게 조언을 주실 수 있으시다면 많은 도움이 될 것 같습니다.

1. TDD적용을 위해 실패하는 테스트 케이스를 먼저 작성 후 빠르게 구현체를 만들어서 테스트를 성공하도록 작업했습니다.
작성한 기능목록을 기반으로 클래스도 나름 여러개로 쪼개어서 각 테스트 케이스를 구현했었는데요,
작업을 진행하면서 보니까 처음에 쪼개 놓았던 클래스보다 더 여러개로 쪼개어 지기도 하고
어떤건 삭제를 하기도 하였습니다.
그러다 보니까 든 생각이 **'과연 처음부터 테스트케이스를 각 클래스로 분리하는 작업이 의미가 있나?'** 라는 것이였습니다.
구현을 진행하면서 필수적으로 설계가 변경이 되는거라면,
처음부터 클래스를 나누기 보단 그냥 하나의 클래스에 테스트 케이스를 쭉 구현하고 나중에 나누는게
더 효율적이란 생각이 들었습니다.
테스트 작성에 익숙하지 않다 보니 별 생각을 다 하는지 모르겠습니다.🤣

2. 이번에도 테스트 케이스 고민입니다.
`LottoGame#makeNumbers` 라는 로또 번호 자동 생성 메서드를 만들었습니다.
이 녀석은 6개의 번호를 자동으로 생성하는 핵심 로직인데요,
정확히 어떤 번호가 생성되는지 판단은 불가하기 때문에
생성된 숫자의 갯수, 범위(1~45)을 테스트하고 싶었습니다.
근데 그러자면 반환값 `Number` 객체에 숫자리스트를 가져오는 getter가 필요하다고 생각했습니다.
이 테스트만을 위해 getter를 생성해야 하는 건 아닌거 같다는 생각인데요,
**getter를 생성해야 테스트가 가능한건지 혹시 제가 놓친 다른 테스트 구조가 있는지** 조언 부탁드리겠습니다.

몰랐던 것을 하나둘 알아가면서 요즘 개발의 재미를 조금씩 다시 느끼고 있습니다.

좋은 리뷰 항상 감사드립니다.😄

2021-03-24 06:40 UTC, dbeod2 requested changes
안녕하세요.!

고민많이하신 흔적이 보이시네요! 
클래스도 작은 단위로 많이 나누시려고 노력하신게 보여요 ㅎㅎ
고민해서 작성해주셔서 그런지 테스트코드도 잘 작성해주신 것같아요!
수고많으셨습니다.! 

질문에 주신 답변은 DM으로 전달드리겠습니다!

2021-03-24 06:40 UTC, dbeod2 commented on src/main/java/lotto/domain/NumberGenerator.java
> +public class NumberGenerator {
NumberGenerator 클래스를 만드셨네요! :)

2021-03-24 06:40 UTC, dbeod2 commented on src/main/java/lotto/domain/Numbers.java
> +    private final List<Integer> numbers;
일급컬렉션 사용 👍🏻

2021-03-24 06:40 UTC, dbeod2 commented on src/main/java/lotto/domain/Prize.java
> +public enum Prize {
로또 카운트와 금액에 대한 부분을 enum 클래스로 정의하셨네요 역할분리 👍🏻👍🏻👍🏻

2021-03-24 06:40 UTC, dbeod2 commented on src/main/java/lotto/util/InputViewUtil.java
> +public class InputViewUtil {
InputView클래스가 존재하는데 InputViewUtil클래스를 만드신 의도가 무엇일까요 ?

2021-03-24 06:40 UTC, dbeod2 commented on src/main/java/lotto/util/StringUtil.java
> +        return inputString == null || "".equals(inputString.trim()) ? true : false;
"".equals(inputString.trim()) 검증으로도 원하시는 리턴값이 나올 것 같습니다! 

```suggestion
        return inputString == null || "".equals(inputString.trim());
```

2021-03-24 06:40 UTC, dbeod2 commented on src/main/java/lotto/domain/HitMoney.java
> +        return (double) this.hitMoney;
hitMondy를 double로 형변환 하려고 하시는 의도가 궁금하네요! 🤔

2021-03-24 22:11 UTC, jaystar13 commented on src/main/java/lotto/LottoGameApplication.java
> +        inputView.inputPayMoney("구입금액을 입력해 주세요.");
저 메세지를 어디에 두면 좋을까 하고 고민하다가
비즈니스로직의 흐름을 가지고 있는 main에 두면 나중에 유지보수에 좋지 않을까?
라는 개인적인 판단으로 밖으로 빼놓았는데요,
지금 다시 보니까
출력 메세지는 또 View 단에서 관리를 하도록 만들었네요.🤣
피드백 주신 것처럼 View에 두는게 좋을거 같아서 수정했습니다.

2021-03-24 22:14 UTC, jaystar13 commented on src/main/java/lotto/domain/HitResult.java
> +    public int isHitPrize(Prize prize) {
의도는...
저 편할려고 그랬던거 같습니다.😭
true = 1, false = 0 으로 대체되는 인식이 있기 때문에,
'그래 이렇게 쓰면 계산로직에 바로 사용할 수 있겠다!'라는 안일한 생각같아요.
다시 수정했습니다.!!

2021-03-24 22:20 UTC, jaystar13 commented on src/main/java/lotto/util/InputViewUtil.java
> +public class InputViewUtil {
Scanner클래스를 사용하여 사용자에게 값을 입력받고 있는데요,
제 짧은 생각엔
이 Scanner클래스가 자바에서 제공하는 util이긴 하지만 외부API 성격이 강하다는 생각을 했어요.
그렇다면 한번더 래핑하는게 좋겠다는 개인적인 판단에 util클래스를 만들었고
View 에서 이 util클래스를 사용하도록 하였습니다.
이런 의도였는데 혹시 다른 조언을 주실 부분이 있다면 감사히 생각하겠습니다.😃

2021-03-25 13:58 UTC, dbeod2 commented on src/main/java/lotto/util/InputViewUtil.java
> +public class InputViewUtil {
그런 의도셨군요! :) 
단순히 저도 짧게 생각했을때 ui로직이라고만 판단되는 부분이었어서 의도에 대해 질문 드린 것 입니다. 
재성님의 선택이시겠지만 한번 더 래핑하지 않고 사용해도 좋을 것 같다는 저의 의견입니다!

2021-03-25 14:00 UTC, dbeod2 approved these changes
2단계도 구현 잘 해주셨습니다 👍 👍 
피드백 반영 빠르게 해주셨네요! 
다른 이견 없어서 이번 미션은 여기에서 머지하겠습니다.

다음 미션 진행하시죠 ! 수고하셨습니다 🙇‍♀️

2021-03-25 14:00 UTC, dbeod2 commented on src/main/java/lotto/util/StringUtil.java
> +        return inputString == null || "".equals(inputString.trim());
피드백 반영 💯💯💯

2021-03-25 14:00 UTC, merged