[Step2] 로또(자동) 리뷰 부탁드립니다.
next-step/java-lotto pull request #1316
Opened 2021-03-24 13:04 UTC by jer122

안녕하세요 리뷰어님! :smile:

이번 로또 과제를 진행하면서
저번 피드백 기반으로 객체에 값을 전달할 땐 최대한 생성자를 통해 값을 전달 하려고 노력했더니,
조금 더 깔끔한 코드가 된 거 같습니다 :smile:

이번 로또 과제를 진행하면서 테스트 코드에 대한 질문이 있는데요,
아무래도 로또가 랜덤인 요소가 있기 때문에 결과 값에 대한 테스트 작성을 어떻게 해야할지 감이 안잡힙니다.
혹시 이럴 경우에는 어떤 방식으로 테스트 코드를 작성해야 될까요?

이번 로또(자동) 과제도 더 좋은 피드백 부탁 드립니다.

2021-03-25 09:14 UTC, parkeeseul requested changes
2단계 미션 잘 진행해주셨습니다! 👍 
몇 가지 피드백과 질문주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드립니다!
요즘 날씨가 참 좋네요! 😄  남은 하루 잘 보내시기 바라요! 
화이팅 입니다 🔥

2021-03-26 08:33 UTC, jer122 commented
안녕하세요! 리뷰어님! 

저번 피드백 때 접근 제어자나 메소드,변수 네이밍같은 기초적인 실수를 해버렸네요 :cry:
`NumbersSelector` 클래스는 Number를 입력받을때 자동으로 생성하는 것과 수동으로 생성되는 것들을 생각하고 만들었지만,
너무 많은 생각을 한 거 같습니다.  :cry:

이번 피드백도 잘부탁드립니다.

2021-03-29 05:24 UTC, parkeeseul requested changes
피드백 잘 반영해주셨습니다! 👍 
잘 반영해 주셔서 몇 가지 추가 코멘트 남겨드렸는데요
확인 부탁드립니다 😄

2021-03-29 05:24 UTC, parkeeseul commented on src/main/java/lotto/domain/Lottos.java
> +    }
해당 생성자는 테스트를 위해 만들어주신 걸까요? 🤔 

Lotto의 랜덤 요소를 외부에서 주입받도록 잘 수정해주셨는데요
Lottos 도 랜덤요소가 내부에 존재하고 있어 해당 생성자를 제거 한다면 테스트가 힘들어 집니다
랜덤 요소를 외부에서 주입 받도록 수정 해보면 어떨까요? 😄

2021-03-30 10:53 UTC, jer122 commented
안녕하세요! 리뷰어님 😄 

저번 피드백에서 몇 가지 질문이 있어 어쭤봅니다!

```java
    public Lottos(List<Lotto> lottos) {
        this.lottos = lottos;
    }
````
이 생성자는 테스트를 위해서 만들었는데, 혹시 다른 방법을 통해 테스트를 진행해야되는지 궁금하네요!

2021-03-31 13:46 UTC, merged