[Step2 - 로또 2단계] 리뷰 요청합니다
next-step/java-lotto pull request #1344
Opened 2021-03-28 11:07 UTC by abcdsds

일이 바빠서 오래걸렸습니다.
질문이 두가지 있습니다.

1. 랜덤한 숫자들을 테스트하기 위해 테스트를 위한 코드 LottoNumberGenerator 를 만들었는데 이런 테스트를 위한 코드가 어느정도 허용이 되는것인지 궁금합니다. 
2. 처음에는 생성자로 로또숫자를 받는 생성자를 만들었었는데 이경우는 자동과 숫자를받는 생성자가 다른 생성자를 사용하기에 같은 생성자를 사용하기위해 전부 LottoNumberGenerator로 통일해서 로또숫자를 주입했었습니다. 이렇게 생각한게 맞는지 궁금하네요.

2021-03-28 11:52 UTC, JunilHwang requested changes
안녕하세요 대식님! 로또 미션 2단계 잘 구현해주셨네요 👍 
몇 가지 리뷰 남겼으니 확인 후 다시 피드백 부탁드립니다!

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/Lotto.java
> +    }
이 부분은 의미 없는 메소드 같습니다.

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoFixedLottoNumberGenerator.java
> +public class LottoFixedLottoNumberGenerator implements LottoNumberGenerator {
도메인에 테스트를 위한 클래스를 두는건 좋지 않은 것 같아요~
단순하게 Lotto를 만들 때 LottoNumber의 Collection을 넘겨주면 어떨까요?

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/Lotto.java
> +    }
```suggestion
    public Lotto(Set<Integer> lottoNumbers) {
        this.lottoNumbers = lottoNumbers;
    }
```
이렇게만 표현해도 좋을 것 같습니다.
굳이 지금은 Generator를 주입할 필요는 없을 것 같아요!
아니면 Generator가 Lotto class를 만들어내는 방법도 있습니다.

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoMatchResult.java
> +    }
오히려 이 부분은 상수때문에 무슨 역할을 하는지 이해하기 힘든 코드 같아요.
명확하게 100 그 자체로 의미가 있는게 아닐까요?

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoMatchResultCount.java
> +            (matchedCount) -> 2000000000 * matchedCount);
Messge는 View에서 표현하면 어떨까요?

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoMatchResultCount.java
> +            (matchedCount) -> 2000000000 * matchedCount);
숫자의 경우 5_000, 50_000, 1_500_000, 20_000_000 처럼 표현할 수도 있습니다!

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoMatchResultCount.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 입력값 입니다."));
Custrom Exception을 만들어서 관리해보면 어떨까요?

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoMatchResultCount.java
> +        return Arrays.stream(LottoMatchResultCount.values())
```suggestion
        return Arrays.stream(values())
```
이렇게 표현할 수 있습니다!

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +public class LottoNumber {
LottoNumber 보단 Lotto라고 표현하면 더 좋을 것 같습니다!

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +    }
- 이 부분은 원시값 포장 객체로 분리한 다음에 이러한 검증 로직을 위임하면 어떨까요?
- 현재 작성해주신 LottoNumber의 대부분의 기능은 사실 Lotto의 기능이라고 볼 수 있지 않을까요?
- 그리고 다시 LottoNumber는 원시값 포장 객체의 형태로 재 정의 한 다음에 만든 후에 Lotto가 Set<LottoNumber>를 가지도록 하면 더 좋을 것 같습니다~

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +    }
이 부분은 아예 새로운 클래스로 만들어서 분리하면 더 좋을 것 같습니다!

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +                .map(number -> lottoNumbers.isContains(number))
```suggestion
                .map(lottoNumbers::isContains)
```
이렇게 표현할 수 있습니다.

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +                .sum();
```suggestion
                .count();
```
이렇게 표현할 수 있습니다.

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +    }
이제보니 이미 generator가 있는데 이렇게 메소드를 만들어주신 이유가 있을까요?

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoRandomLottoNumberGenerator.java
> +    }
static 변수로 관리해주면 어떨까요?

2021-03-28 11:52 UTC, JunilHwang commented on src/main/java/step2/domain/LottoRandomLottoNumberGenerator.java
> +        this.numbers = IntStream.range(1, 46)
1, 46도 상수로 변경할 수 있을 것 같습니다.

2021-04-03 07:11 UTC, abcdsds commented on src/main/java/step2/domain/LottoNumber.java
> +    }
제가 처음에 lotto에 set을 주입하는 방식으로 개발했었는데 이렇게 개발하면 자동번호가 아니다라고 잘못생각했어서 제너레이터를 만들었는데 이과정에서 삭제를 안한것같습니다..

2021-04-03 07:30 UTC, abcdsds commented on src/main/java/step2/domain/LottoNumber.java
> +    }
감사합니다. 좋은방법인거같아요

2021-04-03 14:49 UTC, abcdsds commented
바빠서 오랜만에 리뷰요청드립니다.
궁금한것이 하나있는데요 Lotto는 LottoNumber를 원시값 포장 객체의 형태로 가지고 있는데 
Lotto 내부에서 LottoNumber를 생성할 숫자를 직접 생성하는게 아닌 외부에서 가져와서 생성하는 이유가 무엇인지 헷갈려서 질문드립니다.

2021-04-04 12:28 UTC, JunilHwang approved these changes
안녕하세요 대식님! 피드백 반영 잘 해주셨습니다 👍 

> 바빠서 오랜만에 리뷰요청드립니다.
궁금한것이 하나있는데요 Lotto는 LottoNumber를 원시값 포장 객체의 형태로 가지고 있는데
Lotto 내부에서 LottoNumber를 생성할 숫자를 직접 생성하는게 아닌 외부에서 가져와서 생성하는 이유가 무엇인지 헷갈려서 질문드립니다.

음.. 사실 어떤 피드백 때문에 이렇게 생각하셨는지 잘 모르겠습니다. 일단 제가 선호하는 방법은

문자열/숫자/배열/리스트 등의 타입과 상관 없이 **Lotto로 만들 수 있는 형태의  Input**을 넘겨주면 Lotto에서 `Set<LottoNumber> lotto`로 변환하여 가지고 있는 것입니다. 개별 input에 대한 검증은 LottoNumber에게 넘기고, 전체적인 폼(예를 들자면 숫자가 6개인지, 중복되진 않는지, 순서가 맞는지 등)은 Lotto에 검증하는거죠

의문이 풀리셨길 바랍니다!

이 외에도 몇 가지 리뷰 남겼습니다. Step2는 여기서 마무리하고, Step3 진행하실 때 참고해주시면 될 것 같습니다 😁

회사일 때문에 바쁜 와중에도 포기하지 않고 계속 진행해주셔서 감사합니다 🙇‍♂️
조금만 더 힘내주세요! 화이팅 💪

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/controller/Main.java
> +    }
이 메소드들은 도메인에게 위임하면 어떨까요?

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/GenerateLotto.java
> +public class GenerateLotto {
class는 명사 형태로 작성해주세요!

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/LottoBenefitCalculator.java
> +public class LottoBenefitCalculator {
[📖 3주차 - 엘레강트 오브젝트 1](https://edu.nextstep.camp/s/ApJ4Ca71/ls/jzHfJMpw)에 보시면 `~er 로 끝나는 클래스 이름을 사용하지 않기` 라는 부분이 있습니다.
한 번 참고해서 리팩토링 해보면 어떨까요?

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/LottoMatchResultCount.java
> +            (matchedCount) -> 2_000_000_000);
matchedCount는 불필요해보입니다.

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +            throw new IllegalLottoNumberException("1 ~ 45 이내의 숫자만 입력할수 있습니다");
이 부분은 validate 메소드로 분리하면 어떨까요?

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +    private final Integer lottoNumber;
특별한 경우(예를들자면 null 값이 필요한 경우)가 아니라면 원시타입(int)을 사용해주세요.
관련자료: [불필요한 객체 생성을 피하라](https://velog.io/@yundleyundle/Item6-%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EC%9D%84-%ED%94%BC%ED%95%98%EB%9D%BC)
- 오토박싱 부분만 살펴봐도 좋습니다.

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +public class LottoNumber {
보통 원시값 포장 객체의 경우 valueOf라는 메소드를 사용합니다.
`Integer.valueOf()` `Float.valueOf()` `String.valueOf()` 처럼요!

다음 코드 처럼 사용할 수 있도록 구현해보면 어떨가요?
```java
LottoNumber number1 = LottoNumber.valueOf(1);
LottoNumber number2 = LottoNumber.valueOf(1);
System.out.println(number1 == number2); // 값만 똑같은 게 아니라 메모리 까지 동일해야 함
```

지금은 `==` 연산으로 비교할 경우 false가 나올 것입니다.

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/LottoNumber.java
> +    }
이 메소드는 불필요한 것 같습니다.

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/Lotto.java
> +    }
이렇게 내보낼 경우 lottoNumbers 내부의 값을 수정할 수 있게 됩니다. 이를 방지하기 위해선 어떤 조치를 취해야할까요?

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/domain/GenerateLotto.java
> +    }
이 부분은 Lotto에게 위임해도 되지 않을까요?

2021-04-04 12:28 UTC, JunilHwang commented on src/main/java/step2/controller/Main.java
> +    public static final int LOTTO_NUMBER_RANGE_MAX = 46;
이미 LottoNumber에서 똑같은 값으로 선언된 상수가 존재하는데, 이렇게 다시 Controller에서 선언할 필요가 있을까요?

2021-04-04 12:28 UTC, merged

2021-04-04 13:50 UTC, abcdsds commented on src/main/java/step2/domain/Lotto.java
> +    }
새로 list를 생성해서 반환해줘야될것 같습니다.

2021-04-06 12:53 UTC, abcdsds commented on src/main/java/step2/domain/GenerateLotto.java
> +    }
감사합니다 위임하니까 코드가 더 줄어들고 깔끔해졌네요