Lotto step3
next-step/java-lotto pull request #1351
Opened 2021-03-28 16:36 UTC by wkdehdlr

[로또 3단계] 리뷰요청드립니다.

2021-03-30 09:07 UTC, wheejuni requested changes
리뷰가 늦어져서 대단히 죄송합니다. ㅠㅠ
우선 `Candidate` 클래스에 대해 말씀을 더 나눠보고 싶습니다. 
이 클래스를 없애는 방향으로 리팩토링을 시도해보면 어떨까 싶은데요, 피드백 남겨보았으니 해당 피드백 댓글로 계속 소통하며 새로운 설계를 만들어봤으면 합니다.

리뷰가 늦었는데 한번에 머지도 못 드려 죄송합니다. 꼭 확인해주시고 의견 남겨주세요! 🥇

2021-03-30 09:07 UTC, wheejuni commented on src/main/java/step2/domain/Candidate.java
> +    private final Map<Rank, List<Game>> rank;
`Candidate` 라는 클래스의 역할에 대해 생각해보고 싶습니다. 
우선 `List<Game>` 이 왜 `Rank` 와 연관 관계를 가져야하는지 궁금한데요, 각 `Game` 이 직접 자신의 당첨 여부를 관리하면 안되나요. `Game` 에 `Rank` 필드가 추가되면, `Game` 에게 당첨된 등수를 관리하는 책임 맡길 수 있을 것 같습니다.

이렇게 구조를 개선하면 총 당첨금을 계산하는 로직에서도 구현이 간편해집니다.

2021-04-02 12:22 UTC, wkdehdlr commented on src/main/java/step2/domain/Bonus.java
> +    }
[9e14b28](https://github.com/next-step/java-lotto/pull/1351/commits/9e14b281714c37bd75d1a0f12f5fccecd018efe9) 아예 보너스 클래스를 삭제해봤습니다.

2021-04-02 12:23 UTC, wkdehdlr commented on src/main/java/step2/LottoApplication.java
> +        lotto.init(seed.amount() / PRICE_PER_GAME, LENGTH_PER_GAME);
[9e14b28](https://github.com/next-step/java-lotto/pull/1351/commits/9e14b281714c37bd75d1a0f12f5fccecd018efe9) Lotto에 책임을 부여하도록 수정했습니다.

2021-04-02 13:06 UTC, wkdehdlr commented on src/main/java/step2/domain/Candidate.java
> +    private final Map<Rank, List<Game>> rank;
[24fa523](https://github.com/next-step/java-lotto/pull/1351/commits/24fa52365f6573492cb32bac7dce20c9572e5deb) ```Candidate```를 삭제해서 진행했습니다.

2021-04-02 13:22 UTC, wkdehdlr commented on src/main/java/step2/domain/Candidate.java
> +    private final Map<Rank, List<Game>> rank;
초기의도는 games를 랭킹별로 grouping하여 출력이나 당첨금계산에 관련된 로직을
분리하려는 목적이었습니다.

리뷰내용을 생각해보니...Game이 랭킹을 들고있는것이 좀 더 바람직한 책임으로 보여지네요 👍

2021-04-03 00:48 UTC, wheejuni approved these changes
피드백 반영하시느라 수고 많으셨습니다. 👍 💯

2021-04-03 00:48 UTC, merged