Step02 리뷰 요청드립니다.
next-step/java-lotto pull request #1368
Opened 2021-03-30 16:43 UTC by sonAJin1

지난번에 피드백 주신부분 수정했습니다!
회사 다니면서 미션을 진행하다보니 모든 요구사항 및 기능을 충족시킨 후에 pr을 올리려면 생각보다 텀이 너무 많이 길어져서
부분적이라도 중간 기능 구현한걸 올리면서 최대한 매일 pr을 남겨보려고 합니다!
README에 정리해 둔 기능 요구사항중에 구현되지 않은 부분들과 구현된 부분이 함께 있어서 보시기에 번거로우시겠지만 😢 
꼼꼼한 리뷰 잘 부탁드립니다!🙇‍♀️
이번에는 random number를 출력하는 로또 부분을 만들어봤습니다.
감사합니다!

2021-03-30 21:55 UTC, neojjc2 commented
#tag @neojjc2

2021-03-31 01:39 UTC, neojjc2 requested changes
안녕하세요 아진님 🙇 

2단계 구현 (및 시작) 잘해주셨습니다 💯 💯 💯 💯 💯 
코멘트로 따로 남겨 드렸지만 아진님 방식 응원하고 
저도 열심히 한번 해보겠습니다 😅  
몇 가지 의견 드렸습니다 😄  

검토 부탁 드리겠습니다 🙇

2021-03-31 01:39 UTC, neojjc2 commented on README.md
> +## 기능 요구사항
요구사항 정리 좋습니다 👍

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step01/Numbers.java
> +        Matcher m = Pattern.compile(REGEX).matcher(value);
지난 요청사항 반영 좋습니다 👍

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step02/Config.java
> +public class Config {
`LottoConfig`로 하면 좀 더 어디에서 사용되는 `Config`인지 알기 쉬울 것 같습니다 😄

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step02/Lotto.java
> +    public Lotto() {
기본 생성자를 사용하는 곳이 없다면 굳이 명시적으로 만들지 않으셔도 될 것 같습니다 😄

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step02/Lotto.java
> +    public Lotto(int count, MakeNumberRule makeNumberRule) {
이 생성자는 좀 어색합니다 😄 

`buyLotto`에서 `makeLotto`를 사용하고 있는 구조 입니다 
그리고 만드신 생성자들은 `Lotto`를 인스턴스화 하기 위해 억지로 만들어진 느낌인데요 😅 

정적 팩토리 메소드를 이용하여 한번 개선보시는건 어떨까요?? 🤔 
이부분 개선 검토 부탁 드립니다 🙇 

도움 되실 만한 내용 공유 드립니다 
> https://johngrib.github.io/wiki/static-factory-method-pattern/

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step02/MakeNumberRule.java
> +    List<Integer> integers = IntStream.range(NUMBER_RANGE_START, NUMBER_RANGE_END).boxed().collect(Collectors.toList());
Interface서 이렇게 사용하셔도 안되는건 아니지만 
이런 용도를 생각하시고 설계 하셨다면 `abstract class`가 더 적합해 보입니다 😄 

`MakeNumberRule`은 로또게임 뿐만아니라 
숫자를 생성하는 모든 곳에서 사용하고 싶은 `Interface`로 자유롭게 해주시고
로또 게임만을 위한 다양한 룰을 가지고 1~45만 추출하는 용도시라면 `abstract class`로 고려 부탁 드리겠습니다 🙇 

도움 되실 만한 내용 공유 드립니다 
> https://velog.io/@gillog/Java-Interface-vs-Abstract-Class-%EC%A0%95%EB%A6%AC

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step02/MakeRandomNumberRule.java
> +public class MakeRandomNumberRule implements MakeNumberRule {
로또번호 생성만 담당하는 `Rule` 객체 좋습니다 💯

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step02/MakeRandomNumberRule.java
> +        return integers.stream().limit(LOTTO_NUMBER_MAX_COUNT).collect(Collectors.toList());
람다식 활용 좋습니다 😄 
저는 개인적으로 가독성을 위해 한줄에 하나씩 내려쓰는데요 😅 
이 부분은 참고만 부탁 드립니다 🙇 

```
return integers.stream()
    .limit(LOTTO_NUMBER_MAX_COUNT)
     .collect(Collectors.toList());
```

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step02/Numbers.java
> +    public void makeNumbers(MakeNumberRule numberRule) {
이 부분도 생성자와 동일한 역할을 하는 `method` 로 보입니다 😄 
위에서도 의견 드렸지만 정적팩토리 메소드 활용 검토 부탁 드립니다 🙇

2021-03-31 01:39 UTC, neojjc2 commented on src/main/java/step02/Numbers.java
> +    private List<Integer> numbers = new ArrayList<>();
Interger가 아니라 로또번호랑 관련된 내용을 담당하는 객체로 추출되면 더 좋을 것 같습니다 😄 
`List<Number>` 나 `List<LottoNumber>` 가 되면 어떨까요?? 🤔

2021-04-04 15:25 UTC, sonAJin1 commented
피드백 주신 내용을 참고해서 다시 전체적으로 구조를 바꿔봤습니다. 
감사합니다!

2021-04-05 06:56 UTC, neojjc2 approved these changes
안녕하세요 아진님 🙇 

새로 다시 구현 해주셨네요 👍 💯 💯 💯 💯 💯 
많이 바쁘실 텐데 😭 
큰 리팩토링 작업해주시느라 정말 고생 많으셨습니다 🙇 

전체적으로 객체들의 역할이나 구조가 잘 균형 잡힌 것 같습니다
다만 조금 만 더 개선되면 좋을 것 같아서 의견 드렸습니다 😄 
다음단계 진행하시면서 개선 검토 해주시면 감사하겠습니다 🙇 
(그리고 다음 단계 진행하시면 자연스럽게 왜 개선을 해야 할지 필요성을 느끼실 것 같습니다 😅)

일단 merge 하겠습니다 🙇 

다음단계에서 기다리고 있겠습니다 🔥

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/Main.java
> +        Lottos lottos = lottoShop.buyLotto(new RandomNumberRule());
이 부분 수정이 필요할 것 같습니다 😄 

![image](https://user-images.githubusercontent.com/68527004/113542872-27748680-9620-11eb-954c-3e4894e4b52e.png)

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/InputNumberRule.java
> +        return lottoNumbers;
람다식을 이용하여 한번에 변경 가능할 것 같습니다 😄 
이 부분은 참고만 부탁 드립니다 🙇 
```suggestion
        return Arrays.stream(numbers.trim().split(REGEX))
                .map(Integer::parseInt)
                .collect(Collectors.toList());
```

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
초기화 및 재 할당 방지 차원에서 `final`도 추가되면 좋을 것 같습니다 😄  
```suggestion
    private static final Scanner SCANNER = new Scanner(System.in);
```

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/LottoConfig.java
> +public class LottoConfig {
👍 💯

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/LottoCount.java
> +    private int count = 0;
클래스 변수이므로 따로 0으로 초기화는 안하셔도 될 것 같습니다 😄 
그리고 `count`를 초기화 하는 생성자가 있으므로 `final`로 선언하셔도 될 것 같습니다 🙇 
```suggestion
    private final int count;
```

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/LottoCount.java
> +    public LottoCount(int count) {
`LottoCount` 객체 추출 좋습니다 😄 
개인 적인 의견을 드리자면 `count` 보다는 구매금액에 대한 객체추출은 어떨까요?? 🤔 

`count`는 구매금액과 로또 하나당 얼마인지에 따라 계산되어지는 값입니다
객체로 추출하기엔 결과 값이라서 할 수 있는 부분이 많지는 않습니다 😅 

반면에 구매 금액은 
금액에 대한 검증이나  수익률을 구하는 부분 그리고 `count`에 대한 부분도 위임할 수 있을 것 같습니다 😄 

예를 들면 이런 부분도 포함될 수 있겠습니다 😅 
![image](https://user-images.githubusercontent.com/68527004/113543528-88508e80-9621-11eb-80dc-2d3a2e1732a4.png)

이 부분 개선 검토 부탁 드리겠습니다 🙇

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/LottoNumber.java
> +public class LottoNumber {
로또 번호에 대한 객체 추출 좋습니다 😄

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/LottoNumbers.java
> +    public String toString() {
출력과 관련된 부분을 도메인이 가지고 있게 되면 출력에 대한 수정이 발생할 때 마다 도메인이 수정되어야 합니다 😄 

도메인은 도메인 고유의 기능에 대한 변경이 필요 할 때 수정되어야 합니다 
게다가 출력과 관련된 부분이 단순 `console`이 아닌 `json`, `html` 등등으로 확장 되어야 한다면
이 부분에 계속적인 수정이 발생합니다 😄 

`ResultView`를 생성하셨으니 그 쪽으로 위임 해보시는건 어떨까요?? 😅 

그리고 추가적으로 의견 드리자면 `toString()`을 `Override` 하셨는데, 
일반적으로는 객체들의 고유 상태 값에 대한 출력을 위해 `toString()`을 `Override` 합니다 😄 

이 부분은 사용자에게 보여주기 위한 부분이므로 별도로 분리 하는게 구조적으로 더 깔끔할 것 같습니다 🙇  

그리고 추가적으로 정렬도 되면 더 좋을 것 같습니다 🙇 
![image](https://user-images.githubusercontent.com/68527004/113543841-2ba1a380-9622-11eb-8c61-284ea14bf5d0.png)

이 부분 개선 검토 부탁 드립니다 🙇

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/LottoResultDTO.java
> +public class LottoResultDTO {
DTO 사용 좋습니다 👍 
하지만 `math3`, `math4`, `math5`, `math6` 등이 이름이 모호합니다 😄 
좀 더 의미있는 이름으로 변경해보시는건 어떨까요??

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/LottoShop.java
> +    int money = 0;
```suggestion
    private int money;
```
or
```suggestion
    private final int money;
```

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/Lottos.java
> +public class Lottos {
일급 컬렉션 좋습니다 👍

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/Lottos.java
> +            if (matchCount == Rank.RANK.FOURTH.getMatchCount()) {
`Enum`을 `Rank.RANK`로 생성하신 다른이유가 있을 까요?? 😄 
`Rank`로 바로 생성하셔도 무방할 것 같습니다 😮 

그리고 `matchCount`를 Enum에서 꺼내서 비교하지 마시고 
`Enum`에게 `matchCount`를 주고 맞는 `Enum`을 **달라!** 라고 하시면

이 부분을 훨씬 더 깔끔하게 개선해 볼 수 있을 것 같습니다 🙇 

그리고 `LottoResultDTO` 에도 의견 드렸지만 `Map` 형태로 당첨 결과를 가지고 있도록 해보시는건 어떨까요?? 😅 

이 부분도 개선 검토 부탁 드리겠습니다 🙇

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/NumberRule.java
> +public abstract class NumberRule {
`NumberRule` 추상화 너무 좋습니다 👍

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/NumberRule.java
> +    List<Integer> integers = IntStream
상속 받은 곳에서 재 할당하지 못하도록 그리고 한번만 초기화 되도록 `static` `final`로 선언 되면 좋을 것 같습니다 😄 
```suggestion
    static final List<Integer> INTEGERS = IntStream
```

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/Rank.java
> +        FOURTH(3, 5000);
이렇게도 표현할 수 있습니다 😄 
이 부분은 참고만 부탁 드립니다 🙇 

 ```
        FIRST(6, 2_000_000_000),
        SECOND(5, 1_500_000),
        THIRD(4, 50_000),
        FOURTH(3, 5_000);
```

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/Rank.java
> +public class Rank {
별도의 `Enum`만 선언하셔도 될 것 같습니다 😄 

이 참에 `Enum` 한번 정리하고 가시면 더 좋겠습니다 🙇 
> https://www.nextree.co.kr/p11686/

Java enum 활용기
> https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/Rank.java
> +    public static double calculateTotalReward(int money, LottoResultDTO lottoResultDTO) {
이 부분은 당첨결과 혹은 구매금액 쪽 객체들이 가지고 있는게 더 자연스러울 것 같습니다 😄 
적절한 객체에게 위임검토 부탁 드립니다 🙇

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/ResultView.java
> +    private ResultView() {}
인스턴스화 방지 👍

2021-04-05 06:56 UTC, neojjc2 commented on src/main/java/step02/Validation.java
> +public class Validation {
`Validation` 좋습니다 👍

2021-04-05 06:56 UTC, merged