3단계 - 로또(2등)
next-step/java-lotto pull request #1373
Opened 2021-03-31 11:57 UTC by djoon

안녕하세요
3단계 리뷰 입니다..
부족한점 피드백 주시면 감사하겠습니다...~~

2021-04-01 12:19 UTC, karian7 requested changes
안녕하세요! 동준님.
커밋을 잘 나눠수져서 리뷰하기 좋았습니다 👍 지난번과 다르게 리베이스도 잘 해 주셨네요 😀 

라인댓글로 드린 부분외에 아래 부분도 추가로 반영해 주실 수 있을까요?
> 로또번호 검증추가: 중복번호 있는지
> 번호 하나를 객체로 포장해 보기
> ㄴ 하나의 번호 검증: 하나의 로또 번호는 1~45 이내에 있는지 검증
> DTO 사용 최소화 하기(라인 댓글에 말씀드린 부분 외에도 DTO 사용을 줄일 수 있는가 찾아보기
> ㄴ 도메인 패키에서 DTO 를 의존하지 않도록 하기

이번 단계에서는 피드백이 많습니다. ^^; 어려운 도전인만큼 더 많은 성장도 기대해 볼 수 있을것 같아요.
만약 막히는 부분이 있다면 언제든 DM 주세요.

수정해 보시고 다시 리뷰요청 부탁드리겠습니다~

2021-04-01 12:19 UTC, karian7 commented on src/test/java/lotto/AutomatedLottoTest.java
> +        LottoShop lottoShop = new LottoShop(2000, new TestLottoGenerator());
`TestLottoGenerator` 를 개선해 보면 좋겠습니다.
내부적으로 번호를 증가시키는 부분이 있지만 테스트에서는 알기가 어려워 보입니다.
테스트에서 명시적으로 `TestLottoGenerator` 객체가 생성하는 번호를 알 수 있게 해보면 어떨까요?

2021-04-01 12:19 UTC, karian7 commented on src/main/java/lotto/domain/stats/LottoScoreBoard.java
> +        if (equalNumberCount == 5 && lotto.traverseCompareTo(bonusNumber) > 0) {
`5` 매직넘버 대신 `Prize` enum 에 정의되어 있는걸 활용해보면 어떨까요?

2021-04-01 12:19 UTC, karian7 commented on src/main/java/lotto/domain/prize/Prize.java
> +    public static long getPrizeAmountByEqualNumberCount(long equalNumberCount) {
```suggestion
```
이 메소드는 안쓰는것 같네요 😀

2021-04-01 12:19 UTC, karian7 commented on src/main/java/lotto/LottoApp.java
> +                new LottoDto(inputView.inputWinnerNumbers(), inputView.inputBonusNumbers()), lottoOrderResultDto);
보너스 번호에 대한 검증을 추가하면 좋겠습니다. 어떤 조건이 있을끼요 🤔

2021-04-02 14:44 UTC, djoon commented
피드백 주신 것을 수정을 해보았는데... 잘 된 건지 모르겠네요 😢

2021-04-03 10:58 UTC, karian7 approved these changes
안녕하세요! 동준님. 
피드백 드린 내용들 열심히 적용해 주셨군요! 감사합니다. 🙇 

> 피드백 주신 것을 수정을 해보았는데... 잘 된 건지 모르겠네요 😢

저는 점점 나아지고 있다고 느끼는데 동준님은 어떤부분에서 고민이 있으신지 알고 싶습니다. 과정 목적이 리뷰어의 피드백대로 코드를 바꾸어 미션을 완료하는것이 아닌 리뷰어와 함께 어떤 코드가 더 나은지 토론해가며 더 나은 코드를 만드는 방법을 발견해가는 것이기 때문입니다. 이를위해 많은 소통이 일어나기를 바라고 있습니다.

몇가지 추가로 피드백을 드렸습니다. 😀 
핵심 피드백은 각각의 클래스를 만들어가면서 각 클래스의 기능을 확인하는 테스트 클래스를 만들어 나가셨으면 합니다. 그리고 그 테스트들은 되도록 작은 범위를 테스트 하도록 구현해 보면 좋겠습니다. (이번 미션뿐만 아니라 다음 미션에서도 고려해 주시면 좋겠습니다)

TDD 는 내가 구현하려는 기능을 가장 빠른 방법으로 확인할 수 있는(피드백 받을 수 있는) 방법입니다. 처음부터 TDD를 하긴 쉽지 않기 때문에 이러한 규칙들을 지켜보면서 느낌을 알아가시길 희망하고 있습니다. 

빠른 진행을 위해 이번 단계는 여기서 머지하고 다음 단계를 진행하면서 반영해보시면 좋겠습니다. 고생하셨습니다~

2021-04-03 10:58 UTC, karian7 commented on src/main/java/lotto/service/LottoShopping.java
>  package lotto.service;
(일반적으로) `service` 패키지는 어떤 의미일까요? `LottoShopping` 이 `service` 패키지에 있어야 하는 이유가 있을까요? 

현재 구현으로 미루어 봤을 때 service 패키지는 서비스 레이어를 구현하는것으로 보입니다. 그런데 서비스 레이어는 도메인간 경계역할을 하거나 트랜젝션같은 기술적인 영역을 담당해야 합니다. 이 어플리케이션의 경우 도메인을 구분할만큼 크지 않고 트랜젝션 같은 기술적인 부분도 존재하지 않습니다. 그렇다면 service 패키지에 있는 `LottoShopping`, `LottoScoring` 클래스는 도메인 패키지로 옮기는것이 타당해 보입니다. 동준님 생각은 어떠신지 궁금합니다. 😀

2021-04-03 10:58 UTC, karian7 commented on src/main/java/lotto/domain/stats/LottoEarningRateCalculator.java
> +            Long winnings = lottoScoreBoard.getWinnerCountByPrize(prize);
```suggestion
            long winnings = lottoScoreBoard.getWinnerCountByPrize(prize);
```
불필요한 Boxing 이 일어나네요 😀

2021-04-03 10:58 UTC, karian7 commented on src/main/java/lotto/domain/stats/WinningLotto.java
> +            throw new IllegalArgumentException("보너스볼은 중복되지 않아야 합니다.");
이부분도 테스트를 추가해 볼까요?
`WinningLottoTest` 를 만들어 봅시다.  또한 공개된 메소드인 `getScoreIfMatchingBall` 에 대한 테스트도 만들어 보아요.

2021-04-03 10:58 UTC, karian7 commented on src/main/java/lotto/domain/lotto/Lotto.java
> +            throw new IllegalArgumentException("중복되는 숫자가 없어야 합니다.");
이부분도 테스트를 추가해 볼까요?

2021-04-03 10:58 UTC, karian7 commented on src/test/java/lotto/AutomatedLottoTest.java
> +    void lottoBallLegitTest() {
이 테스트는 `LottoBallTest` 에 있는것이 적합해 보입니다.

2021-04-03 10:58 UTC, karian7 commented on src/test/java/lotto/AutomatedLottoTest.java
> +        LottoMachine lottoMachine = new LottoMachine(new TestLottoGenerator(0));
이 테스트는 `LottoMachineTest` 에 있는게 적합해 보이네요 
다른 테스트 메소드들도 각각의 클래스에 대응하는 테스트 클래스를 만들어서 나눠 보아요. 😀

2021-04-03 10:58 UTC, karian7 commented on src/main/java/lotto/domain/stats/PrizeBoard.java
> +public class PrizeBoard {
이 클래스도 테스트를 만들어 보아요. 😀

2021-04-03 10:58 UTC, merged

2021-04-04 14:45 UTC, djoon commented on src/main/java/lotto/service/LottoShopping.java
>  package lotto.service;
> 저는 점점 나아지고 있다고 느끼는데 동준님은 어떤부분에서 고민이 있으신지 알고 싶습니다  

쭉 생각하다보니 DTO 때문인 것 같네요... 요구 사항이 변경되면 도메인 계층에서는 어떻게 적절히 대응하겠으나, DTO를 추가하게 되면 조금 막막해지는게 있습니다. 메소드 15줄 제한, 인덴트 1 제한 조건 등에 맞게 DTO 변환, 추가를 어떻게 할 것인가??

공감이 안가실지도 모르겠으나 솔직히 개인적으로 구현 시간 중에 DTO 변환이 가장 시간이 많이 걸린 것 같네요... 😢 
DTO가 본 미션이 메인이 아닐텐데 이상한 방향으로 가고 있다는 느낌이 계속 들기도 하구요..??

어쨌든 전부 저의 설계 경험이 부족한 것 같아 생기는 일이겠지요...?  



원래 의도는 `service` 패키지에서 DTO->Entity, Entity->DTO로 대응시키는(?) 계층 역할로 만들려고 하였습니다.
개인적으로도 Entity<->DTO를 어디서 담당 해야되는지 확실하게 감을 못잡겠습니다. (사라진 컨트롤러 단에서 해야할까요?)

말씀주신 `LottoShopping`, `LottoScoring`는 현재 두 가지 기능이 담겨있습니다.

1. Entity<->DTO 변환
2. 비지니스 처리의 흐름 처리 ( 로또 기능들을 처리하기 위해 도메인 객체들에게 메시지를 주고, 받고하고 있습니다 )

아마 2번 때문에 도메인 패키지로 옮기라고 피드백을 주신 것 같은데, 그것은 저도 동의하는 편 입니다...
그렇게 되면 1번은 따로 빼서 어디 다른데다 구현을 해야한다고 생각하고 있습니다. 이게 맞는 방향일까요?

2021-04-05 01:41 UTC, karian7 commented on src/main/java/lotto/service/LottoShopping.java
>  package lotto.service;
저는 개인적으로 객체지향에서 DTO 는 계륵같은 존재라고 생각합니다. 쓰자니 객체지향적이지 않고 안쓰자니 의존성이 생기고.. 그래서 적당히 타협하는 선(비용을 최소화하는 선)에서 사용하려고 노력합니다. 
제가 리뷰하는 관점에서 "이정도 어플리케이션에서는 서비스객체는 사용할 필요 없어" 라고 단정한 부분이 있었습니다. 그러다 보니 동준님에게 "그렇게 하면 안돼요" 라고 메시지를 드렸는데요, 이부분은 잘못된 것 같습니다. 사과 드립니다. 저도 이번기회에 서비스 객체와 DTO에 대해 정리해 보았습니다. 같이 보시고 의견 나눌 수 있으면 좋겠습니다.

---

먼저 DTO를 사용하지 않는다면 View 가 Entity 를 직접 의존하게 됩니다. 저는 개인적으로 Entity 의 크기가 작거나 앞으로 어떨지 모른다면 이렇게 하는게 더 좋다고 생각합니다. 변경가능성이 높은경우 부채가 쌓이는것이기도 하죠.
```
Entity <--- View
```

부채를 줄이기 위해서 (보통 큰 어플리케이션에서) DTO를 사용하는데 이때 올바른 의존성 방향은 아래와 같다고 생각합니다.
```
Entity --(의존성없음)-- DTO <--- View
```
또는
```
Entity <--- DTO <--- View
```
Entity 와 DTO 가 의존성이 없도록 하려면? Service 에서 직접 변환합니다. 또는 이 부분을 기술적으로 플기도 합니다. 대표적으로 [MapStruct](https://mapstruct.org) 가 있습니다. 역시 Service 객체가 담당합니다.

조금더 나아가 컨트롤러와 서비스까지 등장시켜 보겠습니다.
```
    Service <--- Controller ----> View
       ㄴ--(creation)--> DTO
```

다소 엄격하게 한다면 컨트롤러는 서비스와 DTO 를 주고받습니다. 이때 DTO는 서비스 계층의 응답값이므로 서비스 패키지 내에 존재해야 합니다. 서비스 레이어는 도메인의 경계 역할을 하며 도메인을 보호하기 위해 만든 DTO 역시 서비스의 일부이기 때문입니다. 
전체적으로 동준님이 구현하신 내용에서 서비스 객체 사용과 방법은 훌륭합니다. Entity와 컨트롤러 사이에서 DTO를 만들어 제공하고 있죠. 다만 딱 거기까지 해야합니다. 의존성 끊기, 기술적 변환외에는 도메인 객체에 있어야 합니다. 이번 PR 내 코드에서 제안을 해 본다면 `LottoScoring#getResult` 에서 등수별 카운트를 만드는 부분역시 도메인으로 옮길 수 있을것 같습니다.

---

동준님께 드릴 의견을 정리하면 다음과 같습니다.

- DTO(서비스) 는 어플리케이션 규모에 따라 사용하는 비용임을 고려하여 사용하자
- DTO 와 서비스의 역할을 최소화 하고 대부분의 로직을 도메인으로 옮기자
- 이 교육과정에서 대부분의 내용은 서비스레이어가 필요할정도로 크지 않다(이부분은 리뷰어마다 다를 순 있습니다.^^)

저도 동준님 덕분에 정리하고 배울 수 있었습니다. 감사합니다. 🙇