[로또 - Step3] 코드리뷰 요청 드립니다!
next-step/java-lotto pull request #1385
Opened 2021-04-03 01:59 UTC by juniqlim

정휘준님, 안녕하세요!
로또 3단계 - 로또(2등) 코드리뷰 요청드립니다.

이번 단계를 진행하면서 잘 안풀리는 부분이 있는데요. for문 안에 if문을 사용하지 않는(indent depth 1까지 허용) 것 이었습니다.

아래의 코드의 인덴트 깊이를 1로 만들기 위해
```java
public static Winning findByMatchedCount(int numberOfMatchedWinningNumber, boolean matchedBonus) {
	for (Winning winning : Winning.values()) {
		if (winning.matchedCount == numberOfMatchedWinningNumber) {
			if (winning.matchedBonus && matchedBonus) {
				return winning;
			}
			if (!winning.matchedBonus) {
				return winning;
			}
		}
	}
	return Winning.LOSING;
}
```

for문과 if문으로 인덴트 깊이를 낮출 수 없어서 아래처럼 stream을 사용했습니다.
```java
public static Winning findByMatchedCount(int numberOfMatchedWinningNumber, boolean matchedBonus) {
	return Arrays.stream(Winning.values()).filter(winning -> comparison(numberOfMatchedWinningNumber, matchedBonus, winning)).findFirst().orElse(LOSING);
}

private static boolean comparison(int numberOfMatchedWinningNumber, boolean matchedBonus, Winning winning) {
	return equalMatchedCount(numberOfMatchedWinningNumber, winning) && eligibleBonus(matchedBonus, winning)
		|| equalMatchedCount(numberOfMatchedWinningNumber, winning) && ineligibleBonus(winning);
}

private static boolean equalMatchedCount(int numberOfMatchedWinningNumber, Winning winning) {
	return winning.matchedCount == numberOfMatchedWinningNumber;
}

private static boolean eligibleBonus(boolean matchedBonus, Winning winning) {
	return winning.matchedBonus && matchedBonus;
}
```
혹시 stream를 사용하지 않고 인덴트 깊이를 1로 만드는 방법, 팁이 있을까요? 

위의 상황 말고도 아래 코드처럼
```java
public int numberOfLottoesMatched(Winning winning, WinningNumbers winningNumbers) {
	int countMatchedLotto = 0;
	for (Lotto lotto : lottoes) {
		countMatchedLotto += countMatchedLottoes(winning, lotto, winningNumbers);
	}
	return countMatchedLotto;
}

private int countMatchedLottoes(Winning winning, Lotto lotto, WinningNumbers winningNumbers) {
	if (lotto.winning(winningNumbers) == winning) {
		return 1;
	}
	return 0;
}
```
for문과 if문을 사용하면서 인덴트 깊이를 1로 맞춰봤는데, 코드가 매끄럽지 못하다는 느낌이 들었습니다.

더 좋은 방법이 혹시 없을지 궁금하여, 문의드립니다. 🙇🏻

2021-04-03 10:43 UTC, wheejuni requested changes
3단계까지 구현하시느라 수고 많으셨습니다. 👍 
질문에 대한 답변에 더불어 간단한 구조 개선 의견까지 더해 피드백 남겨 드렸습니다.
확인해주시고 피드백을 반영해주시거나, 추가 질문 남겨주시면 감사하겠습니다. 
수고 많으셨습니다. 🥇

2021-04-03 10:43 UTC, wheejuni commented on src/main/java/im/juniq/lotto/domain/Lotto.java
> +		}
이 부분도 stream API 기반으로 리팩토링 진행해보면 의미있을 것 같습니다.
한 줄로 가능하고, 또 지역 변수의 할당이 없어서 불필요한 사이드 이펙트가 나지 않을 것 같거든요.

```java
numbers.stream().map(....).sum();

2021-04-03 10:43 UTC, wheejuni commented on src/main/java/im/juniq/lotto/domain/Lottoes.java
> +		winningAmount += Winning.FIFTH.amount() * numberOfLottoesMatched(Winning.FIFTH, winningNumbers);
어떻게 생각하시나요? `Lotto` 각각이 당첨금 규모를 관리하게 하고, 여기선 `.sum()` 만 할 수 있으면 훨씬 간결할 것 같은데요. 
그러자면 `Lotto` 에 어떤 메소드 추가돼야 할까요?

```java
public Winning getPrize();

2021-04-03 10:43 UTC, wheejuni commented on src/main/java/im/juniq/lotto/domain/Winning.java
> +	}
무리하게 2등에 대한 로직을 섞다보니 조금 복잡한 구현으로 변모했습니다.
`findByMatchedCount` 에서의 조기 분기처리를 통해 2등에 관한 건만 다른 로직으로 분리해서 보고, 나머지 등수에선 필요 없는 로직이므로 이 `private` 메소드들을 간소화할 수 있을 거라 생각합니다.

2021-04-04 01:36 UTC, juniqlim commented on src/main/java/im/juniq/lotto/domain/Lotto.java
> +		}
지역변수가 사이드 이펙트의 여지를 줄 수 있겠네요. stream 를 사용할 때 가질 수 있는 추가적인 장점인 것 같습니다. 👍🏻

2021-04-04 01:41 UTC, juniqlim commented on src/main/java/im/juniq/lotto/domain/Lottoes.java
> +		winningAmount += Winning.FIFTH.amount() * numberOfLottoesMatched(Winning.FIFTH, winningNumbers);
말씀 하신데로 당첨금에 대한 책임은 Lotto가 가지는 것이 코드도 심플해지고 유지보수하기도 좋을 것 같습니다!

2021-04-04 01:44 UTC, juniqlim commented on src/main/java/im/juniq/lotto/domain/Winning.java
> +	}
하드코딩(?)을 줄여보자는 아이디어로 저렇게 구성을 해보았습니다. 그런데 현재 상황에선 코드가 읽기 어려워지고 실효성이 없다는 생각도 듭니다. 빠른 분기 처리로 심플하게 바꿔보겠습니다.

2021-04-04 01:54 UTC, juniqlim commented
피드백 주신 내용을 적용해보았습니다.

코드리뷰 부탁드립니다!

2021-04-04 06:03 UTC, wheejuni approved these changes
수고 많으셨습니다 👍 다음 스텝으로 넘어가주세요.

2021-04-04 06:03 UTC, wheejuni commented on src/main/java/im/juniq/lotto/domain/Lottoes.java
> +		return lottoes.stream().mapToLong(lotto -> lotto.prize(winningNumbers)).sum();
👍

2021-04-04 06:03 UTC, wheejuni commented on src/main/java/im/juniq/lotto/domain/Winning.java
> +	LOSING(2, 0L);
👍 좋네요

2021-04-04 06:03 UTC, merged