Step4 - 로또 (수동)
next-step/java-lotto pull request #1399
Opened 2021-04-05 12:21 UTC by keke0123

로또 수동 완성했습니다~

2021-04-06 12:49 UTC, karian7 requested changes
안녕하세요! 효범님. 
간결한 구현과 능숙한 함수형 구현이 인상적이었습니다 👍👍👍

지난 PR 에 드렸던 피드백도 잘 반영해 주셨습니다. `buy` 와 `match` 두 부분에서 객체 분리를 통해 단일책임을 가질 수 있도록 하는 개선을 진행해 보면 좋겠습니다.
자세한 내용은 라인피드백에 남겼으니 확인해 주시고 혹시 궁금하신 부분 있다면 DM주세요 😀

2021-04-06 12:49 UTC, karian7 commented on src/main/java/step02/code/domain/Outcome.java
> +  public Map<GradeEnum, Integer> statistic(Lotto winningNumber, Number bonus) {
https://github.com/next-step/java-lotto/pull/1361#discussion_r607796959 참고하세요 😀

2021-04-06 12:49 UTC, karian7 commented on src/main/java/step02/code/Main.java
> +      });
https://github.com/next-step/java-lotto/pull/1361#discussion_r607802329 참고하세요 😀

2021-04-06 12:49 UTC, karian7 commented on src/test/java/step02/code/domain/OutcomeTest.java
> +    prizes.forEach((prize) -> outcome.add(prize));
```suggestion
    prizes.forEach(outcome::add);
```

2021-04-06 12:49 UTC, karian7 commented on src/main/java/step02/code/domain/Lottos.java
> +  }
두개 static 함수 `buy` 를 `구매금액과 수동추첨 번호를 통해 전체 로또 목록을 생성` 하는 객체로 만들어 볼 수 있을것 같습니다. 이전단계 까지 `buy` 함수는 정적팩토리 메소드로서 존재 할 수 있었는데 요구사항이 바뀌어서 더 복잡도 높은 책임을 가지게 되었으며 또한  책임은 `Lottos` 객체의 책임과 분리가능하기 때문입니다.

2021-04-06 12:49 UTC, karian7 commented on src/main/java/step02/code/domain/Lottos.java
> +    Lottos autoLottos = null;
여기 null 때문에 56라인에 널체크가 생긴것 같습니다. null 이 없다면 널체크도 필요없어지겠죠. 개선해 봅시다 😀

2021-04-07 12:59 UTC, keke0123 commented on src/main/java/step02/code/domain/GradeEnum.java
> +    if(gradeEnum.matched != SECOND_OR_THIRD_NUMBER) {
넵 함수 이름 알기쉽게 수정했습니다~

2021-04-07 13:03 UTC, keke0123 commented on src/test/java/step02/code/domain/GradeEnumTest.java
> +  @MethodSource("gradeTestCase")
아 Enum 은 이런 방식으로도 값을 받을수 있네요? 이방식으로 수정해보았습니다~ 다음번에 기억해보고 또 써봐야겠어요 ㅋㅋ

2021-04-07 13:03 UTC, keke0123 commented on src/main/java/step02/code/domain/Outcome.java
> +  public Map<GradeEnum, Integer> statistic(Lotto winningNumber, Number bonus) {
함수 분리해서 적용해보았습니다~

2021-04-07 13:04 UTC, keke0123 commented on src/main/java/step02/code/Main.java
> +      });
이부분도 for loop 를 각 함수 안으로 넣도록 해보았습니다.

2021-04-07 13:05 UTC, keke0123 commented on src/test/java/step02/code/domain/OutcomeTest.java
> +    prizes.forEach((prize) -> outcome.add(prize));
넵 항상 좀더 깔끔하게 변환 가능할지 확인해보도록 하겠습니다~

2021-04-07 13:10 UTC, keke0123 commented on src/main/java/step02/code/domain/Lottos.java
> +    Lottos autoLottos = null;
빈 list 값을 넣는 방식으로 수정해서 null 체크를 없애보았습니다~

2021-04-07 13:30 UTC, keke0123 commented
수정 완료했습니다~ 두번째 미션에서도 많은걸 배워갈수 있었던것 같습니다.
그리고 지난 강의에서 생성자에 interface 를 넘기시는 부분 말씀해주신 함수를 인자값으로 넘기는 부분에 대해 조금 눈이 띄인것 같습니다~ 감사합니다.

2021-04-08 12:55 UTC, karian7 approved these changes
안녕하세요 효범님. 마지막 피드백까지 잘 적용해 주셨습니다. 👍 💯 
효범님이 구현하신 코드는 군더더기 없이 간결하고 가독성도 훌륭해서 리뷰하는데 좋았습니다.

저와의 리뷰는 여기서 마무리 하겠지만 앞으로 남은 사다리와 볼링미션도 많이 기대합니다.
짧은기간이지만 즐겁고 성장하는 만남이었기를 바랍니다.
고생하셨습니다!!

2021-04-08 12:55 UTC, karian7 commented on src/test/java/step02/code/domain/ResultCalculatorTest.java
> +public class ResultCalculatorTest {
클래스와 테스트 분리 👍

2021-04-08 12:55 UTC, karian7 commented on src/main/java/step02/code/domain/ResultCalculator.java
> +      .reduce((total, value) -> total + value)
```suggestion
      .reduce(Integer::sum)
```

2021-04-08 12:55 UTC, karian7 commented on src/main/java/step02/code/Main.java
> +    // 불변 객체로 구현해 보고 싶어서 이런식으로 구현해봤습니다.
좋습니다. 👍

2021-04-08 12:55 UTC, karian7 commented on src/main/java/step02/code/Main.java
> +    ResultCalculator resultCalculator = new ResultCalculator(money);
main 이 더 간결해졌네요!

2021-04-08 12:55 UTC, karian7 commented on src/main/java/step02/code/common/ResultView.java
> +      .stream()
```suggestion
```

2021-04-08 12:55 UTC, karian7 commented on src/test/java/step02/code/domain/GradeEnumTest.java
>    @ParameterizedTest
```suggestion
  @ParameterizedTest(name = "당첨번호가 {0}개이고 보너스볼 포함여부가 {1} 일때 Grade 는 {2} 이다")
```

2021-04-08 12:55 UTC, karian7 commented on src/test/java/step02/code/domain/GradeEnumTest.java
>    @DisplayName("보너스 숫자가 맞을때 2등, 틀릴때 3등 return")
```suggestion
  @DisplayName("당천번호와 보너스볼여부에 따라 Grade 가 결정된다")
```

2021-04-08 12:55 UTC, karian7 commented on src/main/java/step02/code/domain/Buy.java
> +  public static Lottos lottos(int money, List<Lotto> lottos) {
이 클래스의 메소드들이 static 이 아니었으면 더 좋았겠다는 생각입니다.
`money` 와 `passiveLottos` 라는 상태를 가지고 `Lottos` 객체를 생성하는 책임을 가진 객체로 디자인 할 수 있기 때문입니다. 조금 더 객체지향적인 접근은 모든 책임을 가진 대상을 객체로 보고 객체간 협업을 도모하기 때문입니다.

2021-04-08 12:55 UTC, karian7 commented on src/main/java/step02/code/domain/Buy.java
> +    return new Lottos(list);
```suggestion
    Lottos result = new Lottos(lottos);
    if(change > 0) {
      result = result.plus(lottos(change)); // 일급 컬렉션에 메소드 추가
    }
    return result;
```
이렇게 하면 더 간결해질 것 같아요.

2021-04-08 12:55 UTC, merged

2021-04-08 13:20 UTC, keke0123 commented on src/main/java/step02/code/domain/Buy.java
> +    return new Lottos(list);
아직도 너무 절차지향적으로 생각을 하네요 ㅜㅜ