Step4 리뷰요청 드립니다.
next-step/java-lotto pull request #1421
Opened 2021-04-11 14:56 UTC by ttokey

resultView에서 수동과 자동의 갯수를 노출시키기 위해 lottos 객체에서 size를 관리하는 것이 아니라.
main controller에서 수동 lottos collection을 파라미터로 전달하여 size를 노출시키게 하였는데요~
이를 lottos 객체에서 가져가는게 맞지 않나? 라는 고민을 해보았습니다. 리뷰어님은 어떻게 생각하시나요?

```
    public static void printPurchaseLotto(Lottos lottos, List<Lotto> manualLottos) {
        System.out.println(String.format("수동으로 %d장, 자동으로 %d개를 구매했습니다."
                , manualLottos.size()
                , lottos.size() - manualLottos.size()));
        lottos.stream()
                .forEach(lotto -> System.out.println(lotto.toString()));
    }
```
size에 대한 부분을 해결 하기 위해 lottos 일급 컬렉션 객체를 일반 객체의 개념으로 가져가고
객체 안의 인스턴스 변수로 일급 컬렉션을 넣는 방식으로 해볼까? 
고민을 해보았습니다.

* lottos
   * 수동lottos
   * 자동lottos
    
리뷰어님의 의견을 들어보고자 풀리퀘를 날려봅니다.

2021-04-12 10:48 UTC, siyoon210 commented
### 수동과 자동을 구분하기 위한 고민에 대해서

수동과 자동을 구분하기 위한 방법으로 별도의 객체를 선언하는건 괜찮은 방법이라고 생각해요! 🙂 
다만 지금은 수동로또의 타입은 List<Lotto>이고 자동 로또는 Lottos 일급컬렉션을 사용하니까 일관적이지 않다는 생각이 들었습니다.
말씀하신 것 처럼 별도의 객체를 선언하되 같은 타입으로 통일하는건 어떨까요? 아래는 석희님의 생각을 제가 구상한 코드 입니다.
```java
public class Ticket {
    private Lottos autoLottos;
    private Lottos manualLottos;

    //...
}
```

2021-04-12 10:55 UTC, siyoon210 commented
![image](https://user-images.githubusercontent.com/15173693/114383790-e7397900-9bc8-11eb-96c2-53b8bea81a34.png)

2등하나 3등하나가 되어야 할 거 같은데 결과는 2등 2개로 나와요. 💭 💭

2021-04-13 16:30 UTC, ttokey commented on src/main/java/lotto/domain/Lotto.java
> +        boolean isBonusMatch = winningNumber.isContained(this.lottoNumbers);
허허 여태까지 문제가 있었네요... lottoNumbers를 비교하는 것이 아니라 lotto 변수와 비교했어야 했는데.... 수정하였습니다

2021-04-13 16:32 UTC, ttokey commented
리뷰어님
한번 Ticket 객체를 만들면서 수동과 자동을 나누어 보았습니다. 확실히 Lottos 객체를 적절히 만들어 두었더니, 활용하기는 편하더라구요~!

사실 이번에도 고민이 있습니다.
Ticket 객체에서 수동과 자동 로또 인스턴스 변수에 대해 각각 메소드를 만들어주게 되었습니다.
ex) 
```
    public int autoLottoSize() {
        return autoLottos.size();
    }

    public int manualLottoSize() {
        return manualLottos.size();
    }
```
저 변태인가요?? 너무 못생겼어요.. 리뷰어님이라면 어떻게 하실 것 같나요?

2021-04-14 10:01 UTC, siyoon210 commented
### 수동 로또 자동 로또의 중복된 로직과 관련해서
다른 멤버변수이니 다른 메서드가 비슷하게 제공되어도 괜찮다고 생각해요.ㅋㅋㅋ

만약에 극단적으로 줄여본다면 어떤 방법이 있을까 고민해봤습니다. 🤔 
autoLottoSize(), manualLottoSize(), autoStream(), manualStream()을 사용하는 곳은 ResultView에서 출력을 위해서 사용하더라구요. auttoLottos와 manulLottos를 다루는 일급함수를 제공하고 방법은 어떤가요? 

```java
public class Ticket {
    public final Lottos autoLottos;
    public final Lottos manualLottos;

    public <R> R handleLottos(BiFunction<Lottos, Lottos, R> lottosFunction) {
        return lottosFunction.apply(autoLottos, manualLottos);
    }
}
```
size, stream 메서드는 모두 없애구 위와같은 메서드를 제공합니다.

```java
public class ResultView {
    public static void printPurchaseLotto(Ticket ticket) {
        BiFunction<Lottos, Lottos, String> lottosBiFunction = (autoLottos, manualLottos) -> {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("수동으로 %d장, 자동으로 %d개를 구매했습니다.", autoLottos.size(), manualLottos.size())).append(System.lineSeparator());
            autoLottos.forEach(lotto -> sb.append(lotto.toString()).append(System.lineSeparator()));
            manualLottos.forEach(lotto -> sb.append(lotto.toString()).append(System.lineSeparator()));
            return sb.toString();
        };
        String lottoPrintingMsg = ticket.handleLottos(lottosBiFunction);
    
        System.out.println(lottoPrintingMsg);
    }
}
```
autoLottos와 manualLottos를 어떻게 다룰건지 ResutView에서 함수형으로 선언해요!

- System.lineSeparator()는 `\n`처럼 줄바꿈을 나타내는 명령어입니다. 이것을 사용하면 OS마다 다른 줄바꿈에 대응할 수 있습니다.
- `manualLottos.forEach()` 에서 forEach를 스트림없이 바로 호출할 수 있는 이유는 Iterable 인터페이스를 구현했기 때문입니다. 🙂 
    
    ```java
    public class Lottos implements Iterable<Lotto> {

      @Override
      public Iterator<Lotto> iterator() {
          return lottos.iterator();
      }
    }
    ```

2021-04-15 08:58 UTC, siyoon210 requested changes
중복된 로직과 관련해서 코멘트 드렸습니다. 🙂

2021-04-18 08:26 UTC, ttokey commented
안녕하세요 리뷰어님.
이미 머지 직전까지 갔다는 생각으로, 테스트 코드에서 이것 저것 해보았습니다... (나중에 공부를 위해)

덕분에 함수형 인터페이스라는 아주 재밌는 것도 배우게 되었네요. 다른 과제에서 어떻게 활용할 방안이 있는지 고려해서 넣어보려고 합니다 ㅎㅎ 감사합니다.

+ 정답이 없기에, Size를 Enum을 이용해 return값을 다르게 하는 건 어떨까? 라는 고민을 해보았습니다. 함수형 인터페이스로 resultView를 만드니 뭔가 객체에서 메소드를 줄이기 위해 코드를 많이 쓰게 되는 느낌이어서?? ㅎㅎ
```
    public int lottoSize(LottoKinds kinds) {
        if (kinds.equals(LottoKinds.MANUAL)) {
            return manualLottos.size();
        }

        if (kinds.equals(LottoKinds.AUTO)) {
            return autoLottos.size();
        }

        return 0;
    }
```

+ 당분간 lotto에 대한 고민은 잠시 접어두려고 합니다 ㅋㅋㅋ 과제를 다 끝내고 다시 한번 리팩토링 해보겠습니다. 제 코드가 통과되었다면 머지 부탁드려요

2021-04-18 09:10 UTC, siyoon210 approved these changes
안녕하세요 석희님!
마지막 단계까지 잘 구현해주셨습니다. 👏 👏 
던져주신 이슈에 대해서 고민해보는 과정도 재밌었어요! 😄 중복로직 이슈에 대해서 Enum으로 타입을 구분하는 방법도 간결하고 좋은것 같아요. 간단하게 할 수 도 있는걸 멀리 돌아온 느낌도 드네요. 🙂 
리뷰드리고 같이 생각해보는 과정에서 저 역시 흥미로웠습니다.

부족한 리뷰였지만 조금이라도 도움이 되셨으면 좋겠네요. 이번 단계는 여기서 마무리 하도록 하겠습니다. 😄 
🚀🚀🚀

2021-04-18 09:10 UTC, merged