Step3 lotto bonus number
next-step/java-lotto pull request #1423
Opened 2021-04-12 18:16 UTC by gmoon92

안녕하세요 이슬님 ~
꼼꼼한 피드백 덕분에 이전 미션에 비해 이번 미션은 수월하게 진행할 수 있었습니다.😁

한 가지 궁금한 점이 있다면, 보너스 볼을 추가하면서 많은 코드가 변경되어 제 설계가 잘못된건 아닌지 생각이 들었습니다.

단편적으로 [1,2]아래 코드 처럼 보너스 볼이 추가되면서 연관된 코드들이 수정이 되었는데,
혹여 메서드 배치가 잘못되었는지도 고민도 했었는데...😥 이와 관련되서 피드백을 주시면 감사하겠습니다.

``` java
class LottoStore {
 // ... 생략
  public LottoStore exchange(LottoTicket ticket) {
    return new LottoStore(lottoWiningNumbers
          , lottoBonusBall
          , ticket.getMatchedLottoPlaces(lottoWiningNumbers, lottoBonusBall));
             // ^-- [1] 사용자가 구매한 로또에 당첨 번호와, 보너스 볼을 넘겨 당첨 결과(LottoPlaces) 클래스를 반환
  }
}

class LottoTicket {
// ... 생략
  public LottoPlaces getMatchedLottoPlaces(LottoWiningNumbers lottoWiningNumbers, LottoBonusBall lottoBonusBall) {
    LottoPlaces lottoPlaces = LottoPlaces.create();
    for (LottoNumbers lottoNumbers : values) {
      int countOfMatch = lottoWiningNumbers.countOfMatch(lottoNumbers);
      boolean matchBonus = lottoBonusBall.isMatch(lottoNumbers);
      lottoPlaces = lottoPlaces.record(countOfMatch, matchBonus);
                    // [2] 보너스 볼 추가로 인한 코드 수정   --------^
    }
    return lottoPlaces;
  }
}
```

2021-04-13 09:50 UTC, parkeeseul requested changes
미션 잘 진행해주셨습니다 ! 👍 
몇 가지 피드백과 질문 주신 사항에 대한 저의 의견 남겨두었으니
확인 부탁드립니다! 😄

2021-04-13 09:50 UTC, parkeeseul commented on src/main/java/lotto/domain/place/BaseRank.java
> +  int FIFTH_COUNT_OF_MATCH = 3;
이펙티브 자바 에서는 인터페이스 상수를 안티패턴이라고 이야기 하는데요
관련해서 한번 보시면 좋을 것 같아요! 😄 
https://songiam.tistory.com/59

2021-04-13 09:50 UTC, parkeeseul commented on src/main/java/lotto/domain/place/Rank.java
> +  THIRD(THIRD_COUNT_OF_MATCH, 1_500_000, (countOfMatch, matchBonus) -> countOfMatch == THIRD_COUNT_OF_MATCH && matchBonus == false),
다음과 같이 해볼 수도 있을 것 같아요! 😄 
```suggestion
  SECOND(SECOND_COUNT_OF_MATCH, 30_000_000, (countOfMatch, matchBonus) -> countOfMatch == SECOND_COUNT_OF_MATCH && matchBonus),
  THIRD(THIRD_COUNT_OF_MATCH, 1_500_000, (countOfMatch, matchBonus) -> countOfMatch == THIRD_COUNT_OF_MATCH && !matchBonus),
```

2021-04-13 09:50 UTC, parkeeseul commented on src/main/java/lotto/domain/LottoTicket.java
> +      lottoPlaces = lottoPlaces.record(countOfMatch, matchBonus);
> Q1.한 가지 궁금한 점이 있다면, 보너스 볼을 추가하면서 많은 코드가 변경되어 제 설계가 잘못된건 아닌지 생각이 들었습니다.
> 
> 단편적으로 [1,2]아래 코드 처럼 보너스 볼이 추가되면서 연관된 코드들이 수정이 되었는데,
> 혹여 메서드 배치가 잘못되었는지도 고민도 했었는데...😥 이와 관련되서 피드백을 주시면 감사하겠습니다.

객체를 잘 분리해주셔서 큰 수정 없이 최소한의 변경으로 요구사항을 잘 반영해주신 것 같네요! 👍 
혹시 의문이 드시는 부분이 따로 있으실까요? 😄

2021-04-13 12:07 UTC, gmoon92 commented on src/main/java/lotto/domain/place/BaseRank.java
> +  int FIFTH_COUNT_OF_MATCH = 3;
헙... 감사합니다. 인터페이스보다는 enum 클래스 안에 정의하는게 맞는거 같네요 !

2021-04-13 12:40 UTC, gmoon92 commented on src/main/java/lotto/domain/LottoTicket.java
> +      lottoPlaces = lottoPlaces.record(countOfMatch, matchBonus);
어제부터 곰곰히 생각해보니 객체를 분리해서 서로 협력하는 관계니 최소한의 변경으로 개발되었네요!

당시에 제가 의문이 드는점은 보너스 볼이 추가되면서 보너스 볼을 체크하는

- LottoStore.java -> 사용자의 보너스 볼을 전달
- LottoTicket.java -> 당첨번호와, 보너스 볼을 매치 하기 위해 매개변수로 전달

매개변수로 많은 곳을 추가되면서 그런 고민을 했었던거 같습니다.

하지만 기능이 추가하면서 당연히 객체들간의 협력관계 때문에 그럴 수 있다고 생각이 드네요😄

2021-04-14 07:36 UTC, parkeeseul requested changes
피드백 잘 반영해주셨습니다! 👍 
한 가지 코멘트와 질문주신 사항에 대해 DM 드렸으니 확인 부탁드려요! 😄 
날씨가 좋네요! 화이팅! 🔥

2021-04-14 07:36 UTC, parkeeseul commented on src/main/java/lotto/domain/place/Rank.java
> +  public static final int FIFTH_COUNT_OF_MATCH = 3;
enum 은 일종의 상수로 enum 내부에 따로 상수를 두지 않아도 될 것 같아요!
어떠한 의도로 설계를 하셨을까요? 😄 
https://webdevtechblog.com/enum%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%9C-%EC%83%81%EC%88%98%EA%B0%92-%EA%B4%80%EB%A6%AC-a3e3fb73eae1

2021-04-15 13:26 UTC, gmoon92 commented on src/main/java/lotto/domain/place/Rank.java
> +  public static final int FIFTH_COUNT_OF_MATCH = 3;
enum 클래스가 열거형 상수 클래스라는건 알고 있지만
저는 countOfMatch의  `6`이라는 매직넘버로 보았고 상수화 했습니다~

``` java
enum Rank {
  FIRST(6, 2_000_000_000, (countOfMatch, matchBonus) -> countOfMatch == 6)
  // 이하 생략

  private final int countOfMatch;
  private final int winningMoney;
  private final BiPredicate<Integer, Boolean> matchedConditional;
}
```

2021-04-15 13:56 UTC, gmoon92 commented
enum 클래스가 열거형 상수 클래스라는건 알고 있지만
음...저는 countOfMatch의  `6`이라는 매직넘버로 보았습니다.
또한, 중복 변수(`countOfMatch == 6` )라 생각해봤는데요. 🤔

``` java
enum Rank {
  FIRST(6, 2_000_000_000, (countOfMatch, matchBonus) -> countOfMatch == 6)
  // 이하 생략

  private final int countOfMatch;
  private final int winningMoney;
  private final BiPredicate<Integer, Boolean> matchedConditional;
}
```

아래 코드처럼 상수화하여 개발자의 실수를 줄이는게 좋지 않을까 라는 생각에 설계했습니다. 😁

``` java
public enum Rank {
  FIRST(Rank.FIRST_COUNT_OF_MATCH, 2_000_000_000, (countOfMatch, matchBonus) -> countOfMatch == Rank.FIRST_COUNT_OF_MATCH),

  // 이하 생략
  public static final int FIRST_COUNT_OF_MATCH = 6;
```

2021-04-16 02:28 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨습니다! 👍 
소소한 피드백 남겨드렸으니 확인 부탁드려요! 😄 
다음 단계 미션 진행해주세요! 화이팅! 🔥

2021-04-16 02:28 UTC, parkeeseul commented on src/main/java/lotto/domain/place/Rank.java
>  public enum Rank {
``` java
public enum Rank {
    FIRST(6, 2_000_000_000),
    SECOND(5, 30_000_000, true),
    THIRD(5, 1_500_000),
    FOURTH(4, 50_000),
    FIFTH(3, 5_000),
    MISS(0, 0);

    private final int countOfMatch;
    private final int winningMoney;
    private final boolean matchBonus;

    Rank(int countOfMatch, int winningMoney, boolean matchBonus) {
        this.countOfMatch = countOfMatch;
        this.winningMoney = winningMoney;
        this.matchBonus = matchBonus;
    }

    Rank(int countOfMatch, int winningMoney) {
        this(countOfMatch, winningMoney, false);
    }

    public static Rank valueOf(int countOfMatch, boolean matchBonus) {
        return Arrays.stream(Rank.values())
                .filter(rank -> rank.countOfMatch == countOfMatch && rank.matchBonus == matchBonus)
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("입력 값이 맞지 않습니다."));
    }
```

다음과 같이 해볼 수도 있을 것 같아요! 😄

2021-04-16 02:28 UTC, merged

2021-04-16 09:57 UTC, gmoon92 commented on src/main/java/lotto/domain/place/Rank.java
>  public enum Rank {
와....... 놀랍네요 정말 한수 배웠습니다 감사합니다!