[로또 TDD] 2단계 - 문자열 덧셈 계산기
next-step/java-lotto pull request #1517
Opened 2021-05-18 18:44 UTC by enemfk777

안녕하세요 :) 리뷰어님
로또 미션 2단계 문자열 덧셈 계산기 리뷰 요청드립니다.

졸린 눈 부벼가며 짜서 퀄리티가 떨어질것 같아 걱정이네요..

의견 주실 코드리뷰는 맑은 정신에 보도록 하겠습니다
감사합니다.

2021-05-19 14:51 UTC, kingbbode requested changes
안녕하세요.
코멘트 작성해두었습니다 :)
확인 부탁드려요.

2021-05-19 14:51 UTC, kingbbode commented on src/main/java/stringadder/StringAdder.java
> +  private StringAdder() {
👍

2021-05-19 14:51 UTC, kingbbode commented on src/main/java/stringadder/domain/Number.java
> +  public static final int ZERO = 0;
0 이 ZERO 라는 것은 누구나 아는 정보이므로, 해석해줄 필요는 없어보여요 :)

2021-05-19 14:51 UTC, kingbbode commented on src/main/java/stringadder/StringAdder.java
> +  private static final String EMPTY_STRING = "";
""이 빈 문자열이란 것도 누구나 아는 정보이므로, 해석해줄 필요는 없어보입니다.

2021-05-19 14:51 UTC, kingbbode commented on src/main/java/stringadder/domain/OperatorSelector.java
> +  }
`isInputMatched` 은 `static` 으로 구현되기보다는 `OperatorSelector` 가 가져야할 책임이지 않을까요?

2021-05-19 14:51 UTC, kingbbode commented on src/main/java/stringadder/domain/OperatorSelector.java
> +  DEFAULT_DELIMITER(Pattern.compile("(\\d+[,:])+\\d+"), input -> makeDefaultDelimiterOperatorFromOperatorSelector(input).sum());
전략으로 구분한 시도는 좋았으나 `CustomDelimiterOperator` ,  `DefaultDelimiterOperator` 까지 동일 수준으로 추상화되었으면 더 좋았을 것 같습니다.

2021-05-19 14:51 UTC, kingbbode commented on src/main/java/stringadder/domain/OperatorSelector.java
> +public enum OperatorSelector {
`OperatorSelector` 라는 네이밍을 가졌지만, 이 클래스는 계산의 책임까지 가지고 있네요.
네이밍과 역할이 잘 맞지 않는 느낌입니다.

2021-05-19 14:51 UTC, kingbbode commented on src/test/java/stringadder/domain/CustomDelimiterOperatorTest.java
> +    assertThat(makeCustomDelimiterOperatorFromOperatorSelector(given)).isEqualTo(makeCustomDelimiterOperatorFromOperatorSelector(given));
이 테스트의 의미는 무엇일까요?
동일 메서드를 두번 실행했을 때 같은 값이 나오는 것을 테스트하는 것일까요?

테스트의 기대값은 테스트 대상이 아닌 곳으로부터 작성 되어야합니다.

2021-05-19 14:51 UTC, kingbbode commented on src/main/java/stringadder/domain/Number.java
> +  }
일반 생성자는 값을 초기화하는 정도의 일만하고 그 외의 일을 하지 않도록 순수하게 작성해야 합니다.
일반 생성자 내에 로직은 확장을 제한시키고, 각종 예외처리와 테스트를 더 어렵게 만들게 됩니다.

2021-05-19 14:51 UTC, kingbbode commented on src/main/java/stringadder/domain/Number.java
> +  }
생성 단계에서 의미있는 비지니스를 처리하고 싶다면 정적 생성자를 통해 의도를 드러내도록 네이밍하여 작성할 수 있습니다.

2021-05-20 13:12 UTC, enemfk777 commented on src/main/java/stringadder/domain/Number.java
> +  public static final int ZERO = 0;
극단적 연습? 으로 매직넘버 or 매직스트링을 없애 보았습니다 ㅎㅎ

2021-05-20 13:19 UTC, enemfk777 commented on src/main/java/stringadder/domain/OperatorSelector.java
> +  }
OperatorSelector가 predicate를 갖게 구현했다가 matcher, match를 쓰는게 지저분해서 분리했는데,

2021-05-20 14:56 UTC, enemfk777 commented
리뷰 주신 사항 반영해 보았습니다 😊

2021-05-20 15:24 UTC, enemfk777 commented on src/test/java/stringadder/domain/CustomDelimiterOperatorTest.java
> +    assertThat(makeCustomDelimiterOperatorFromOperatorSelector(given)).isEqualTo(makeCustomDelimiterOperatorFromOperatorSelector(given));
습관적으로 테스트코드 맨위에는 생성된 객체간의 동등성이 보장되는 지 확인하는 테스트코드를 작성하고 있어서 적어둔 코드입니다!

2021-05-20 17:06 UTC, kingbbode approved these changes
잘 반영해주셨네요 :)
이만 머지하겠습니다.
추가로 코멘트도 작성해두었으니 확인 부탁드립니다.

2021-05-20 17:06 UTC, kingbbode commented on src/main/java/stringadder/domain/Operator.java
> +  private final Function<String, Number> calculator;
이런 두 가지 요구사항을 `interface` 로 작성하였다면 더 깔끔한 코드가 되지 않았을까 싶네요 :)

2021-05-20 17:06 UTC, kingbbode commented on src/main/java/stringadder/domain/Operator.java
> +public enum Operator {
enum 클래스에 interface 를 상속받도록 하여 `enum` 사용을 극대화하는 방법도 있습니다 :)

2021-05-20 17:06 UTC, kingbbode commented on src/main/java/stringadder/domain/Number.java
> +    this.inputNumber = inputNumber;
이 부분은 아직 반영되지 않은 것으로 보이네요 :)
다음에 반영해보시거나, 의견에 대한 의문이 있으시면 말씀주셔요.

2021-05-20 17:06 UTC, merged