[Step 4] 로또(2등)
next-step/java-lotto pull request #1573
Opened 2021-05-21 14:52 UTC by ohgillwhan

리뷰 감사합니다 :)

2021-05-21 15:50 UTC, hhlyn0328 requested changes
이전 단계에서 구조를 잘 잡아주셔서 큰 변경사항 없이 잘 구현하셨네요  👍 
크게 피드백 드릴 사항이 없지만, 빠진 케이스가 있는 듯 하여 코멘트 드렸습니다!
확인 부탁드립니다 :)

2021-05-21 15:50 UTC, hhlyn0328 commented on src/main/java/lotto/domain/rank/LottoRank.java
> +        return this.countOfMatched == countOfMatched && this.bonusMatched == bonusMatched;
당첨번호와 3개가 일치하고 보너스가 일치한 경우 또는 4개가 일치하고 보너스 번호가 일치한 경우에
각각 5등과 4등을 해야하는데 실행결과 모두 미당첨으로 분류될 것 같아요!

2021-05-22 14:22 UTC, ohgillwhan commented on src/main/java/lotto/domain/rank/LottoRank.java
> +        return this.countOfMatched == countOfMatched && this.bonusMatched == bonusMatched;
아! 그렇군요 :) 수정해보도록 하겠습니다! 감사합니다 ㅎㅎ

2021-05-23 08:08 UTC, hhlyn0328 approved these changes
리뷰 내용 반영을 잘해주셨네요 💯 

로또 피드백 영상 한 번 보신뒤에 다음 단계 진행 해주세요 !
마지막까지 화이팅!

2021-05-23 08:08 UTC, merged