Step3 - 로또(자동) 리뷰 요청드립니다.
next-step/java-lotto pull request #1576
Opened 2021-05-21 16:15 UTC by jhh992000

안녕하세요.
금방 끝낼줄 알았는데 생각보다 이번 미션은 오래걸렸네요.
기능 정리와 도메인설계를 할때부터 시간을 꽤 쓴거같고..
어제 강의를 듣고 나서 클린코드를 작성하기위해서 어떻게 해야할지 고민을 계속하게 되네요..
getter를 만들지 않으려고 노력을 하고는 있는데, 실행 결과를 별도의 객체에 담아서 반환하고
반환받은 결과를 출력용 클래스에서 따로 처리하려다보니, 어쩔수없이 결과를 담은 객체에 getter가 필요하게 되네요.
이 부분 이렇게 해도 괜찮은건지...
혹시 좋은 방법이 있다면 조언부탁드립니다.
그럼 리뷰 부탁드립니다.
감사합니다.

2021-05-22 06:18 UTC, parkeeseul requested changes
미션 잘 진행해주셨네요! 👍 
몇 가지 코멘트와 질문주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드립니다!
중복되는 피드백에 대해서는 추가로 코멘트를 남기지 않았음으로 다른 부분들도 함께 확인 부탁드릴게요! 😄 
즐거운 주말 날씨가 참 좋네요! 좋은 하루 되세요! 미션 화이팅 입니다! 🔥

2021-05-22 06:18 UTC, parkeeseul commented on src/test/java/lotto/domain/LottoNumberTest.java
> +	}
해당 테스트는 로또 숫자 생성 테스트라기 보다는
잘못된 범위의 로또 숫자에 대한 실패 테스트 인것 같아요! 적절한 네이밍을 부여해주면 어떨까요?

또한 @ParameterizedTest 를 통해 중복 코드를 줄여볼 수 있을 것 같아요! 😄

2021-05-22 06:18 UTC, parkeeseul commented on src/test/java/lotto/domain/LottoNumbersTest.java
> +	}
생성된 로또 번호에 대한 성공 테스트와 실패에 대한 테스트가 함께 존재하네요.
현재는 테스트 코드가 복잡하지는 않지만 
테스트에 여러 개념이 들어가게 되면 각 절이 존재하는 이유와 테스트 하는 개념을 모두 이해해야 하기 때문에 가독성이 좋지 않을 것 같아요! 
한 가지의 개념만 테스트하도록 분리해보면 어떨까요? 😄

2021-05-22 17:46 UTC, jhh992000 commented on README.md
> +# 로또 - TDD
UI에서 단순히 화면에 출력하기 위해 객체의 값을 getter로 사용하는것은 괜찮다는 말씀이시군요. 잘 알겠습니다.

2021-05-22 17:55 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +	private final int purchaseAmount;
숫자값에 언더바 표기도 이번에 처음 알았는데 빠뜨린부분이 있었네요^^

2021-05-22 17:57 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +	private void validationpurchaseAmount(int purchaseAmount) {
구매금액 변수명을 money에서 purchaseAmount로 변경한적이 있었는데 대소문자체크를 하지않고 replace를 했더니 
다른부분에서 이상하게 변경이 되었었군요. 감사합니다.

2021-05-22 18:04 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +			throw new IllegalArgumentException("로또를 구입하려면 최소 1000원 이상 있어야 합니다.");
세심한 처리가 부족했네요. 감사합니다.

2021-05-22 18:42 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +	private final RandomNumbersGenerator randomNumbersGenerator;
생각해보니 해당 클래스에서는 상태값을 가질 필요가 없을것 같습니다. 메서드로 필요한 값들을 받아서 처리만 하고 반환하면 될것같네요.

2021-05-22 18:44 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +		this.purchaseLottos();
저도 객체의 속성을 나타내는 변수에는 this를 사용하는 것이 좋고, 메서드는 생략해주는것이 좋을것 같습니다. 
그동안 기준없이 this를 사용했던것 같습니다. 정리해주셔서 감사드립니다.

2021-05-22 18:46 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +	}
앞서 리뷰해주신 LottoGame의 상태값 제거 리팩토링을 하면서 해당부분에서 구매한 로또 번호 리스트를 반환하도록 처리했습니다.

2021-05-22 18:48 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +	}
네, 저도 동의합니다.
LottoGame에서는 로또 구입하는 기능만 제공하고, 당첨결과는 다른 객체에서 확인해주는것이 좋을것 같네요.

2021-05-22 18:50 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumber.java
> +			throw new IllegalArgumentException("로또번호는 1~45 이내의 숫자여야 합니다.");
네 앞선 피드백과 동일한 부분이네요. 수정하겠습니다.

2021-05-22 18:56 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumber.java
> +	}
네 이미 동일한 기능을 제공하는 equals 메서드가 있었네요. 
그동안 equals와 hashCode 메서드 재정의를 자주 사용해오지 않아서 있는지도 몰랐네요. 😂

2021-05-22 18:59 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumbers.java
> +	public static final int LOTTO_NUMBER_LENGTH = 6;
네 이미 클래스에 로또넘버라는 의미가 내포되어있으니 LENGTH 로 짓는것이 조금더 중복이 없고 깔끔하겠네요 😄

2021-05-22 19:09 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumbers.java
> +	private List<Integer> removeDuplicateNumbers(List<Integer> numbers) {
오우 그렇네요. 왜 그 생각을 못했을까요! 일급콜렉션을 생성할때 항상 고민후에 자료구조를 선택해야겠네요. 감사합니다.😄

2021-05-22 19:12 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumbers.java
> +	protected int findMatchCount(LottoNumbers winLottoNumbers) {
테스트하려고 했었던것 같네요. 해당 메서드를 호출하는 findRank 에 대응하는 테스트코드가 이미 있어서 private으로 처리하는것이 맞을것 같습니다.

2021-05-22 19:26 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumbers.java
> +	}
음..hasSize() 메서드는 테스트를 위해서 추가한 메서드인데요.
이 부분은 좀 궁금한것이 있습니다. 리뷰요청드릴때 질문드리겠습니다.

2021-05-22 19:27 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumbers.java
> +	}
옳으신말씀입니다. 😄

2021-05-22 19:35 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +		this.randomNumbersGenerator = new LottoRandomNumbersGenerator();
상태값을 가지지않는것이 좋겠다는 앞선 피드백에서 해당부분을 같이 수정했습니다.
로또를 구입하는 메서드에서 RandomNumbersGenerator 인터페이스를 주입받도록 수정했습니다.

2021-05-22 19:42 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoRandomNumbersGenerator.java
> +		}
생성자에서 숫자 45개를 생성하고 재사용하도록 변경했습니다.

2021-05-22 19:44 UTC, jhh992000 commented on src/main/java/lotto/domain/RandomNumbersGenerator.java
> +	int MAX = 45;
또 중복된 코드가 나왔군요 ㅠ
당연히 LottoNumber의 상수를 사용하는것이 좋을것 같습니다!

2021-05-22 19:52 UTC, jhh992000 commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
헛 그렇네요. 
Rank 클래스를 작성할때 TDD를 하지 않아서 발생한 누락건이군요.
결과를 반환하는 기능에만 집중하다보니 빠뜨렸네요.🥲

2021-05-22 19:58 UTC, jhh992000 commented on src/main/java/lotto/domain/Rank.java
> +	}
indent 제한때문에 for문을 사용하지 않았었어요. 코드가 너무 지저분해지는것 같아서..
stream도 사용도 제한을 하는줄 알았는데 이제부터는 사용해도 괜찮은가보군요. 
미션요구사항을 확인해보니 stream 사용하지 말라는 항목이 없네요.
(사실 stream 사용이 익숙하진 않습니다^^; 앞으로 자주 활용해보도록 하겠습니다.)

2021-05-22 20:31 UTC, jhh992000 commented on src/main/java/lotto/service/InputService.java
> +public class InputService {
사용자가 입력하는 기능들을 따로 모아두려고 작성한 클래스입니다.
유효하지 않은 값을 입력했을 경우에 재입력을 받도록 예외처리를 하는 기능들이 들어가다보니 도메인 로직이 포함되게 되었네요.
요구사항에 없는 기능들을 추가하려고 했었네요. 오버엔지니어링일까요?
암튼 InputService 는 제거하였고, 입력받는 기능을 담당하는 메서드들은 InputView로 이동조치했습니다!

2021-05-22 20:35 UTC, jhh992000 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +	}
보다 정확한 테스트 메서드명과 설명으로 변경하였습니다.
그리고 @ParameterizedTest 를 사용해서 중복코드를 제거했습니다. 😀

2021-05-22 20:37 UTC, jhh992000 commented on src/test/java/lotto/domain/LottoNumbersTest.java
> +	}
hasSize 함수가 제거되면서 해당부분은 예외발생하는 코드만 남게 되었습니다.
보다 정확한 테스트코드 설명으로 변경처리했습니다.

2021-05-23 13:14 UTC, parkeeseul requested changes
피드백 잘 반영해주셨네요! 👍 
몇 가지 추가 코멘트 남겨두었으니 확인 부탁드립니다! 😄 
확인하시다 의견이 다르시거나 궁금하신 부분이 있으시다면 언제든 말씀해주세요!
주말이 끝나가네요 😢  남은 시간 즐겁게 보내시길 바라요! 미션 화이팅 입니다! 🔥

2021-05-23 13:41 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumber.java
> +	private final int number;
정적변수와 클래스변수를 구분하기 위한 줄바꿈 추가했습니다. 👌

2021-05-23 13:48 UTC, jhh992000 commented on src/main/java/lotto/domain/Rank.java
> +	int winningMoney;
헛 ㅠ 이유 없습니다. 저의 불찰입니다.

2021-05-23 13:49 UTC, jhh992000 commented on src/main/java/lotto/view/InputView.java
> +	public static final String MESSAGE_INPUT_PURCHAGE_AMOUNT = "구입금액을 입력해 주세요.";
흑흑 계속해서 오타가 발생하네요. 타이핑시에 주의를 해야겟네요.

2021-05-23 14:00 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResult.java
> +			sumWinAmount += rank.winningMoney * statMap.get(rank);
getter 보다는 객체에 메시지를 보내라!!
생각처럼 쉽게 잘 되지는 않는군요. 사고를 객체지향적으로 하려는 노력을 꾸준히 해야할것같습니다.

2021-05-23 14:32 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +	}
오.. insight!
원시값을 포장하니 다른 메서드들이 해당 객체로 이동을 하게 되는군요!  👍

2021-05-23 14:33 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumbers.java
> +		validationNumbers(numbers);
넵! 옳으신 말씀입니다.

2021-05-23 14:53 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoRandomNumbersGenerator.java
> +	private final List<Integer> numbers;
네 그러고보니 매번 초기화할 필요가 없는 상태값입니다. 정적변수로 사용하면 보다 효율적이겠네요! 👍

2021-05-23 14:57 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResult.java
> +	}
Set을 foreach로 돌리면 되었군요! 
저도 모르게 iterator로 while문을 돌리는 습관이 베어 있던것 같습니다.

2021-05-23 15:10 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResult.java
> +	private final HashMap<Rank, Integer> statMap;
총 구매금액 (totalPurchases) 상태값은 없어도 될 것 같습니다.

2021-05-23 18:37 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResult.java
> +	private final HashMap<Rank, Integer> statMap;
로또 결과를 담당하는 클래스가 마음에 들지 않아서 재설계했습니다. 확인부탁드립니다.

2021-05-24 11:56 UTC, parkeeseul requested changes
피드백 잘 반영해주셨네요! 👍 
몇 가지 추가 코멘트 남겨드렸으니 확인 부탁드립니다! 😄 
미션 화이팅 입니다! 🔥

2021-05-24 11:56 UTC, parkeeseul commented on src/main/java/lotto/domain/Rank.java
> +	}
다음과 같이 바로 return 해줘도 좋을 것 같아요 😄 
```suggestion
	public boolean isGreaterThan(Rank rank) {
		return this.matchCount > rank.getMatchCount();
	}
```

2021-05-24 12:00 UTC, jhh992000 commented on src/main/java/lotto/domain/PuchaseAmount.java
> +public class PuchaseAmount {
헐 또 오타 ㅠㅠ 밤샘코딩의 폐해인가요

2021-05-24 12:12 UTC, jhh992000 commented on src/main/java/lotto/domain/PuchaseAmount.java
> +	}
동일클래스내의 상수참조변수였군요! 수정했습니다.

2021-05-24 12:16 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResult.java
> +public class LottoResult {
네 저도 이 클래스 만들면서 찜찜했습니다. 역쉬나 매의 눈으로 따끔한 지적을 주시는군요! 해당 클래스는 제거조치했습니다.

2021-05-24 12:21 UTC, jhh992000 commented on src/main/java/lotto/domain/Lotto.java
> +	}
불필요한 변수로 할당받았네요. 바로 리턴하도록 변경했습니다!

2021-05-24 12:23 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResults.java
> +	}
넵 바로 리턴하도록 변경했습니다.

2021-05-24 12:30 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResults.java
> +				.filter(lottoResult -> lottoResult.getRank().equals(rank))
불필요한 lottoResult 클래스를 제거해서 getter 사용이 불필요해졌습니다.

2021-05-24 12:35 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoGame.java
> +	}
넵 생성자로 초기화해서 반환해주는게 좀더 명확하고 안전한것 같습니다!

2021-05-24 12:38 UTC, jhh992000 commented on src/main/java/lotto/domain/Rank.java
> +	}
아 그러네요! 앞으론 좀더 맑은정신에 코딩을 해야겟어요 ㅠㅠ

2021-05-25 03:01 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
몇 가지 소소한 코멘트 남겨드렸으니 확인 부탁드립니다.
많은 피드백 반영해주시느라 고생 많으셨습니다! 다음 단계 진행해주세요! 😄 
추가적인 수정 사항은 다음 단계에서 함께 반영 부탁드릴게요!
화이팅 입니다! 🔥

2021-05-25 03:01 UTC, merged

2021-05-25 03:05 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResults.java
>  	private final List<Rank> renderRanks;
DTO를 사용해보도록 하겠습니다.

2021-05-25 03:12 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResults.java
> +				.filter(r -> r.equals(rank))
넵. resultRank 라는 네이밍으로 변경했습니다.

2021-05-25 04:26 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoResults.java
>  	private final List<Rank> renderRanks;
당첨통계정보를 가지는 데이터유형을 Map 으로 변경처리했습니다. 관련하여 영향이 있는 메서드의 리팩토링도 진행하였습니다.