[주지민] step3 - 로또(자동)
next-step/java-lotto pull request #1580
Opened 2021-05-21 19:21 UTC by joojimin

로또(자동) 기능 구현 및 리뷰 해주신 부분 적용해봤습니다. 
null 처리 부분이 어색한 느낌이 드는데 의견부탁드립니다. 감사합니다 :)

2021-05-22 12:58 UTC, slamdunk7575 requested changes
안녕하세요:) 지민님. 로또 미션 구현하시느라 고생하셨습니다 👍 
열심히 해주셔서 저 또한 덕분에 동기부여가 되는 것 같습니다!

피드백 드린 부분들을 반영하여 구조를 다듬고 가면 
다음 미션을 원할하게 수행하실 수 있을 것 같아 Request Changes 하였습니다.

궁금한점이나 어려운점 있으면 코멘트나 슬랙으로 DM 남겨주세요. 함께 고민해보아요 🔥
리팩토링 해보시고 다시 리뷰요청 부탁드립니다~ 끝까지 화이팅 입니다!

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/lotto/LottoManager.java
> +		return lottoNumbers;
> null 처리 부분이 어색한 느낌이 드는데 의견부탁드립니다. 감사합니다 :)

당첨번호도 `LottoNumbers` 로 리턴하도록 하면 `해당 객체내에서 검증이 이루어져`
`isValidLottoCount()` 같은 처리에 대한 중복들은 제거할 수 있겠네요 :)

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/utils/NumberUtils.java
> +	}
`수익률` 계산은 `LottoResult`가 하도록 위임해보면 어떨까요? 

자바에서는 금액과 같이 정확한 계산을 지원하기 위해 `BigDecimal`를 제공합니다.  
`BigDecimal`를 적용해보는 것도 좋을것 같네요 😄 

[Java, BigDecimal 사용법 정리](https://jsonobject.tistory.com/466)

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/ui/InputView.java
> +
여기도  `private 생성자`를 통하여 불필요한 객체 생성을 방지하면 좋을 것 같아요.

[[이펙티브 자바] 인스턴스화를 막으려거든 private 생성자를 사용하라](https://madplay.github.io/post/enforce-noninstantiability-with-private-constructor)

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/utils/ConsoleUtils.java
> +		return new Scanner(System.in).nextLine();
`ConsoleUtils` 를 분리해보셨네요 👍 

매번 `Scanner`를 생성하기 보다는 상수로 선언하여 관리해보면 좋겠네요 :)

`private static final Scanner SCANNER = new Scanner(System.in);`

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/lotto/LottoGenerator.java
> +		}
`로또 구매 금액`을 관리하는 `예: LottoMoney` 라는 클래스를 분리해보면 어떨까요?

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/lotto/LottoGenerator.java
> +		for(int i = 0; i < lottoNumber; ++i){
이곳엔 `로또 번호 갯수`를 나타내는 다른 `네이밍`을 주는게 좋겠네요.
lottoNumber는 로또 번호 하나를 의미하는 것 같네요 :) 

```suggestion
		for (int i = 0; i < lottoNumber; ++i) {
```

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/lotto/LottoResult.java
> +	}
> 모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외
핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

UI 로직은 `InputView, ResultView` 객체에서 처리해야 할것 같네요.
`비즈니스 로직`과 `UI 로직`은 분리 해주세요.

이를 분리해야 하는 이유는 `유지보수 및 확장성`을 높이기 위해서 입니다.
요구사항이 변경되어 View의 수정이 필요한데 비즈니스 로직과 섞여 있다면 코드를 읽기도 힘들뿐더러 
View 코드를 수정하다가 비즈니스 로직에 영향을 끼쳐서 다른 버그가 생깁니다.

꼭 제가 피드백 드린 부분외에도 확인해보시고 리팩토링 해보시면 좋을것 같아요 🙏

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/lotto/SumResult.java
> +}
`인터페이스`를 정의하신 이유가 있으신가요?

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/lotto/LottoNumber.java
> +	private final int number;
LottoNumber 원시값 포장 잘해주셨네요 👍  💯 

해당 객체내에서 `로또 번호는 1 ~ 45 사이의 숫자`에 대한 검증 메소드를 추가해보면 좋겠네요 :)

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/utils/DrawNumber.java
> +	}
`DrawNumber` 객체가 `로또 번호를 생성`하는 책임을 가지고 있는것 같은데요.

아래처럼 `캐싱`된 숫자를 DrawNumber 내에서 관리하면 좋을것 같은데 지민님 생각은 어떠신가요?

<img width="789" alt="스크린샷 2021-05-22 오후 9 33 52" src="https://user-images.githubusercontent.com/15867808/119226720-8eed8380-bb45-11eb-8cb4-3cd15a6c9cde.png">

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/utils/DrawNumber.java
> +	public List<Integer> draw(int size) {
`List<LottoNumber>` 를 리턴하도록 해보면 어떨까요? 😄

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/utils/DrawNumber.java
> +		}
해당 검증이 꼭 필요한지 고민해보시면 좋을것 같아요 :)

2021-05-22 12:58 UTC, slamdunk7575 commented on src/main/java/lotto/LottoNumbers.java
> +	private final List<LottoNumber> lottoNumberList;
로또 볼은 번호마다 한 개씩 존재(1 한개, 2 한개, 45 한개...)
중복을 허용하지 않는 컬렉션을 사용해보고 아래와 같은 검증도 객체내에서 해보면 좋겠네요 😄 

`Set<LottoNumber> lottoNumbers;`

<img width="1001" alt="스크린샷 2021-05-22 오후 9 45 20" src="https://user-images.githubusercontent.com/15867808/119227061-20a9c080-bb47-11eb-8ea5-96fa00ed2f57.png">

2021-05-24 06:07 UTC, joojimin commented on src/main/java/utils/StringAddCalculator.java
>  		}
세세한 부분까지 신경써주셔서 감사합니다. 
해당 컨벤션 피드백은 
d0fe336 에서 적용했습니다.

2021-05-24 06:08 UTC, joojimin commented on src/main/java/utils/NumberUtils.java
> +	}
넵! 기존 클래스 따로 다시 분리했습니다 ( d0fe336 )

2021-05-24 06:10 UTC, joojimin commented on src/main/java/lotto/LottoManager.java
> +	}
LottoManager 클래스를 정의할 당시 static 하나로 가능할 줄 알고 시작했기에 클라이언트가 좀더 수월하게 호출할 수 있을걸로 생각했습니다.
클래스가 커지다보니 오히려 역할이 애매해진 것 같아 다시 클래스의 책임에 맞게 분리해봤습니다. ( d0fe336 )

2021-05-24 06:11 UTC, joojimin commented on src/main/java/lotto/LottoManager.java
> +		return lottoNumbers;
말씀해주신 객체 생성자 내부에서 검증이 훨씬 깔끔하고 같은 처리에 대해 중복을 제거할 수 있을 것 같습니다!
해당 내용은 d0fe336 에서 적용해봤습니다.

2021-05-24 06:13 UTC, joojimin commented on src/main/java/lotto/LottoNumber.java
> +	private final int number;
초기에 DrawNumber에서 1~45의 범위를 주어지기 때문에 해당 클래스에서 추가 검증은 필요 없을 것이라 생각했습니다.
하지만 각 클래스가 상호 베타적인 관계가 되어야할 것 같아 말씀해주신 검증 메서드도 적용해봤습니다! ( d0fe336 )

2021-05-24 06:17 UTC, joojimin commented on src/main/java/utils/DrawNumber.java
> +	}
설계당시 DrawNumber 클래스를 Util성이 높은 클래스로 생각했습니다. 
( 해당 어플리케이션처럼 로또 번호도 뽑을 수 있지만 다른 숫자 뽑는 로직도 적용할 수 있는 )
따라서 도메인(로또)에 관련된 로직이 DrawNumber에 종속되지 않게 설계했습니다! 지금 당장의 어플리케이션에서는 해당 확장성이 필요가 없을 것 같기도한데.. @slamdunk7575 님의 의견을 한번 더 들어보고싶습니다!

2021-05-24 06:18 UTC, joojimin commented on src/main/java/utils/DrawNumber.java
> +	public List<Integer> draw(int size) {
다시보니 List<Integer>를 리턴할 이유가 전혀 없어보입니다. 말씀하신 내용으로 리팩토링 해봤습니다 ( d0fe336 )

2021-05-24 06:19 UTC, joojimin commented on src/main/java/utils/DrawNumber.java
> +		}
Draw(숫자뽑기)하는 size가 해당 클래스를 생성할때 만들어놓았던 값을 벗어나면 subList에서 Exception이 발생해 검증 로직으로 추가해놨습니다!

2021-05-24 06:22 UTC, joojimin commented on src/main/java/lotto/LottoNumbers.java
> +	private final List<LottoNumber> lottoNumberList;
DrawNumbers에서 미리 생성한 중복되지않은 값들을 shuffle하여 뽑기때문에 중복이 일어날 수 없는 환경이라고 판단했습니다.
하지만 Set을 이용하여 중복자체가 일어날 수 없는 컬렉션을 사용하는 것이 의도를 더 명확히 드러낼 수 있을 것 같아 d0fe336 에서 리팩토링했습니다!

변수명에 List, Set, Map 같은 네이밍을 습관처럼 썼던 것 같습니다. 앞으로 해당 부분도 신경써보겠습니다! 감사합니다 ㅎㅎ

2021-05-24 06:24 UTC, joojimin commented on src/main/java/lotto/LottoManager.java
> +		LottoManager lottoManager = new LottoManager();
Static을 사용해 한줄로 표현하려했던 것이 오히려 LottoManager 클래스에 단점을 준것 같아서 말씀하신 내용으로 리팩토링하였습니다. 
( d0fe336 )

2021-05-24 06:26 UTC, joojimin commented on src/main/java/utils/NumberUtils.java
> +	}
감사합니다! BigDecimal은 많이 안써봤는데 이번 기회에 공부하게 됐습니다. 리뷰해주신 내용이 각 클래스의 의도를 더 명확하게 해주는 것 같아 d0fe336에서 리팩토링했습니다.

2021-05-24 06:26 UTC, joojimin commented on src/main/java/ui/InputView.java
> +
다 적용한 줄 알았는데 빠진 부분이 있었네요 ㅠㅠ.. d0fe336 에서 추가했습니다!

2021-05-24 06:27 UTC, joojimin commented on src/main/java/lotto/LottoGenerator.java
> +		}
해당 부분까지 나눠볼 생각을 미쳐 못했던 것 같습니다. 리뷰해주셔서 감사합니다!!
해당 내용은 d0fe336에서 분리해봤습니다!

2021-05-24 06:29 UTC, joojimin commented on src/main/java/utils/ConsoleUtils.java
> +		return new Scanner(System.in).nextLine();
@slamdunk7575 명확한 내용을 찾지 못했는데 혹시 Scanner도 재사용이 가능할까요?? 
입력을 안받고 스킵되는 부분이 생겨 헷갈리네요..

2021-05-24 06:29 UTC, joojimin commented on src/main/java/lotto/LottoGenerator.java
> +		for(int i = 0; i < lottoNumber; ++i){
의도랑 전혀 상관없이 네이밍된 것 같습니다. d0fe336에서 수정했습니다.

2021-05-24 06:31 UTC, joojimin commented on src/main/java/lotto/LottoResult.java
> +	}
클래스 내부에 들어가있는 원소들을 출력할 방법을 찾다가 오히려 클래스 분리가 안된 것 같습니다... d0fe336에서 최상위 클래스 레벨까지 UI 클래스의 의존을 안하게 수정했습니다. ( d0fe336 )

2021-05-24 06:39 UTC, joojimin commented on src/main/java/lotto/SumResult.java
> +}
이번 1주차 박재성님의 클래스 분리 강의를 듣고 적용해본 내용이였습니다! ㅎㅎ LottoResult의 SumRevenue 메서드를 테스트하기 위해서 여러개의 로또 당첨 조건들을 줘서 테스트가 가능한 것 보다, 테스트 의도가 sumRevenue를 가져와 수익률을 계산하는 것이기 때문에 해당 부분을 바로 값을 리턴하는 시그니처로 변경할 수 있기 때문에 정의해봤습니다.



- 인터페이스 적용 전 ( sumRevenue를 가져오기위한 로직 )

```
Map<LottoRewardType, Integer> lottoRewardMap = new EnumMap(LottoRewardType.class);
lottoRewardMap.put(....) // 원하는 당첨금액만큼 적용
LottoResult result = new LottoResult(lottoRewardMap);

new LottoMoney().calculateRevenue(result.sumRevenue());
```


- 인터페이스 적용 후

```
new LottoMoney().calculateRevenue(()->10000));
```

2021-05-24 15:17 UTC, slamdunk7575 commented on src/main/java/utils/ConsoleUtils.java
> +		return new Scanner(System.in).nextLine();
`Scanner`가 다른 상태를 가지거나 바뀔 일이 없으니 상수로 선언해서 재사용 함으로써 불필요한 객체 생성 줄일 수 있을 것 같아요 :)

2021-05-24 15:24 UTC, slamdunk7575 commented on src/main/java/utils/DrawNumber.java
> +	}
`Utility` 클래스로 만드신 거였군요!
저는 `로또 번호를 발행하는 역할`을 하는 `예: LottoMachine` 클래스 같은 생각이 들어 피드백을 드렸던거였습니다.
정답이 있는 것이 아니니 지민님이 미션 진행하시면서 더 좋은 방향으로 고민해보시면 좋을것 같네요 :)

2021-05-24 16:46 UTC, slamdunk7575 approved these changes
피드백 반영하시느라 고생많으셨습니다 👍 
질문에 대한 답변과 몇가지 피드백 남겨 드렸는데 다음 미션 진행하면서 같이 반영해보시면 좋을것 같아요.
끝까지 화이팅 입니다~! 🥇

2021-05-24 16:46 UTC, slamdunk7575 commented on src/main/java/utils/DrawNumber.java
> +	public List<Integer> draw(int size) {
https://github.com/next-step/java-lotto/pull/1580#discussion_r637713713 이부분도 확인부탁드려요!

2021-05-24 16:46 UTC, merged

2021-05-25 03:44 UTC, joojimin commented on src/main/java/utils/SeparatedText.java
>  		}
말씀하신대로 불필요한 검증인 것 같습니다. 2985fb 에서 반영했습니다.

2021-05-25 03:45 UTC, joojimin commented on src/main/java/lotto/LottoManager.java
> +	}
해당 컨벤션에 대한 내용을 몰랐습니다.. 시간나는대로 틈틈히 컨벤션 내용 숙지해보겠습니다. 리뷰감사합니다!
해당 내용은 22985fb 에서 반영했습니다~!

2021-05-25 03:46 UTC, joojimin commented on src/main/java/lotto/LottoManager.java
> +	}
말씀하신대로 LottoMoney의 책임을 벗어나는 메소드라고 생각되어 LottoResult에서 담당하도록 개선했습니다! 
( 22985fb )

2021-05-25 03:46 UTC, joojimin commented on src/main/java/lotto/LottoNumbers.java
> +	}
22985fb 에서 메소드로 분리해봤습니다 ㅎㅎ

2021-05-25 03:47 UTC, joojimin commented on src/main/java/lotto/LottoResult.java
> +	}
미쳐 체크 못한 부분인데 리뷰해주셔서 감사합니다! ResultView 의존 제거 제거하였습니다! 
( 22985fb )

2021-05-25 03:51 UTC, joojimin commented on src/main/java/utils/DrawNumber.java
> +	public List<Integer> draw(int size) {
@slamdunk7575 https://github.com/next-step/java-lotto/pull/1580#discussion_r637713250 에서 말씀드린 설계의 연장선이였습니다! DrawNumber 클래스가 utility 클래스로 만들어졋다보니 특정 도메인에 종속되지 않게 반환형도 List<Integer>로 작성하였습니다!