Step3 작업 PR입니다. cupeanimus
next-step/java-lotto pull request #1597
Opened 2021-05-22 12:36 UTC by cupeanimus

로또를 추상화하는데 생각보다 많이 헤맸습니다.
최대한 객체지향적으로 생각을 하며 TDD를 하였으나, 부족함이 많아 잘 부탁드립니다.
가격을 사용하기 때문에 BigDecimal 타입을 사용하였는데, 사서 고생을 한 것 같습니다.
현재 값을 입력받는게 아닌 자동으로 생성하기 때문에 input에 대한 생각들을 다음단계로 미뤄두고
최대한 요구하는대로 작업을 하려고 하였는데, 
어진 요구사항과 이를 바탕으로 이해한 것을 코딩하는데 약간의 괴리감이 생겨
많은 연습으로 자연스러운 코드를 짤 수 있도록 노력하겠습니다.
예외상황이나 검증은 보통 어느정도를 생각해야하는지 잘 모르겠습니다.
기회가 된다면 백엔드 개발자로서 보통 에러에 대해 어떤 태도와 어디까지 예외상황을 고려해야하는지 듣고 싶습니다.

감사합니다.

2021-05-24 15:43 UTC, tearight commented
안녕하세요, 이번 단계를 진행하시면서 많은 혼란과 고민이 있으셨을 것 같아요.
객체지향 코드로는 보이지만 내부에 상태(변수)를 가지게 됨으로써 각 객체들이 재사용이 불가능한 구조가 되어버린 걸로 보여요.
이러한 결함은 테스트로는 밝혀내기 어려워서 제품이 운영중일때 결함이 발견되고, 또 계산이 잘못 되는 등 크리티컬한 현상을 만들어낼 가능성이 보입니다.
(단위테스트, 통합테스트는 대부분 한번만 함수를 호출하게 되죠. 즉, 상태에 대한 변경, 검증을 한번만 합니다.)

예를 들면 lottoGame.checkPrize() 를 여러번 호출하게 되면 어떨까요 ?
현재 갖고 있는 winningLotto에 add 를 하기 때문에 결과가 점점 누적될 것이고 사용자에게 보이는 결과는 왜곡될거에요.

따라서 내부적인 변수를 제거하는 리팩토링을 제안드립니다.
제거할 수 있는 변수는 코멘트를 통해서 **[변수 제거 대상]** 이라고 남겨드릴게요.
이 제안은 선택이며 원하지 않으면 진행하지 않으셔도 됩니다. 🙂

내부적인 변수를 제거할 경우 가져갈 수 있는 이점은 다음과 같습니다.
1. 객체의 method 의 결과는 객체의 상태보다 파라메터에 의존하게 되기 때문에 테스트시에 다양한 상황을 파라메터로써 넣어줄 수 있어서 테스트의 자유도가 늘어난다. (객체의 상태를 사전에 설정해야 하는 과정이 필요 없게 됩니다. mocking 을 해야하는 불편함도 줄어듭니다.)
2. 내부의 값을 계속 지켜보지 않아도 되기 때문에 데이터와 객체간 메세지 전달의 흐름이 보인다.
(return 값과 parameter 로 입력되는 값만 보면 되기 때문에 디버깅이 훨씬 쉬워집니다.)
(예를 들면 현재 inputView 를 테스트 하기 위해 lottoGame 의 멤버변수를 지켜봐야 하는 상황이죠.)

2021-05-24 15:55 UTC, tearight commented
입력 값에 대한 검증에 대한 제 의견을 말씀드리겠습니다.

저는 입력값은 입력/생성되는 즉시 빠르게 검증하는 편을 선호합니다.
그리고 입력/생성 이후에는 따로 검증하지 않습니다.
(순수한 객체지향 프로그래밍일수록 이 경향이 강한 것 같습니다.)

입력받은 값이 각 객체들 간에 함수를 통해 전달이 될 경우 전달 받을 때마다 각 함수에서 검증을 해야하는데 코드가 매우 지저분해집니다.
어디서 잘못된 값이 넘어올 지 모르기 때문에 항상 예외를 방어하기 위한 코드를 만들어야 하기 때문이지요.
이러한 방향을 담은 것이 값을 객체로써 wrapping 하는 방법이지 않나 싶습니다.

https://github.com/next-step/java-lotto/pull/1630/files
다른 분의 PR 인데요, LottoNumber.java 파일을 보시면 숫자 값을 객체로 wrapping 하였고,
객체 인스턴스 생성시에 validate 를 하는 것을 볼 수 있습니다.
이 이후에 LottoNumber 객체를 값으로써 자유롭게 사용하게 되는 데요, 이 LottoNumber 를 인자로 받는 곳에서는
값이 1~45 일거라고 확정짓고 값을 사용하게 됩니다. 왜냐면 객체 생성시 1~45 사이의 숫자임을 무조건 검사하기 때문이지요.

2021-05-24 16:18 UTC, tearight commented
예외상황에 대한 제 의견을 말씀드리겠습니다.

비지니스 로직에 대해서는 예외를 적극적으로 사용하는 편입니다.
더 이상 진행할 수 없을 때 값을 return 하게 될 경우에는 결과가 왜곡되기 때문에 차라리 예외를 던지는 것으로 로직오류를 최소화 하는 편입니다.

이렇게 던져진 예외를 API 레벨에서 catch 하여 return 을 정제하는데에 사용합니다.
(스프링의 경우에는 Exception Handler 와 같겠네요.)

2021-05-24 16:23 UTC, tearight requested changes
안녕하세요, 이번 단계를 진행하시느라 고생많으셨습니다. 👍

피드백을 남겼으니 확인을 부탁드립니다.

2021-05-26 10:39 UTC, cupeanimus commented on src/main/java/study/lotto/LottoPaper.java
> +    private int matchCount;
맨 처음 MarkedLottoNumbers 일급컬렉션이 든 값을 포장하는 개념으로 설계하였는데 matchCount까지 변수가 추가되면서 본질이 흐려진 것 같습니다. 변수 제거를 고민하다가 lottoPaper는 마킹된 로또 번호만 존재하는 일급 컬렉션 객체로 정의하고, MarkedLottoNumbers객체가 아닌 List<Integer> markedLottoNumbers 값만 가지도록 수정해 보았습니다.

2021-05-27 09:55 UTC, cupeanimus commented on src/main/java/study/lotto/LottoGame.java
> +    public LottoGame(WinningNumbers winningNumbers, PurchasedLottos purchasedLottos) {
인터페이스를 통해 상황에 따라 입력값을 제어하는 방법은 좋은 것 같습니다.
다만 이 객체가 서비스 영역과 비슷한 개념으로 설계되고 작업을 하다보니 이렇게 내부 변수가 필요하고, 다른 객체와 의존관계를 맺게 되었는데, 필요 값을 입력 받아 LottoGame의 역할만 수행하고 리턴하는 개념으로 수정하여 조언해 주신 방향 수정이 불필요하게 되었습니다.

2021-05-27 09:58 UTC, cupeanimus commented
> 예외상황에 대한 제 의견을 말씀드리겠습니다.
> 
> 비지니스 로직에 대해서는 예외를 적극적으로 사용하는 편입니다.
> 더 이상 진행할 수 없을 때 값을 return 하게 될 경우에는 결과가 왜곡되기 때문에 차라리 예외를 던지는 것으로 로직오류를 최소화 하는 편입니다.
> 이렇게 될 경우 테스트에서도 예외를 캐치하면 되기 때문에 작성이 쉬워집니다.
> 
> 이후 이렇게 던져진 예외를 Context 레벨에서 catch 하여 사용자에게 응답을 전달하는데에 사용합니다.
> (스프링의 경우에는 Exception Handler 와 같겠네요.)
> 
> 결론적으로는 비지니스/도메인에 대해서는 예외를 아낌 없이 사용하고
> 이를 호출하고 있는 바깥쪽, 즉 프로그램 흐름을 처리하는 곳에서 전체적인 예외를 catch 하여 프로그램이 종료되지 않도록 핸들링하게 되는 것 같습니다.

2021-05-27 13:28 UTC, tearight approved these changes
피드백 반영해주신 것 잘 봤습니다!
질문에 대한 코멘트를 남겼으니 다음 단계를 진행하시면서 확인 부탁드립니다.

2021-05-27 13:28 UTC, tearight commented on src/main/java/study/lotto/LottoNumber.java
> +    }
다른 분 커밋에서 본 코드인데 숫자간 비교는
`return this.lottoNumber - lottoNumber.lottoNumber`
로 하시는 분도 있더라구요.

-1, 0, 1 만 반환해야 하는 것 아닌가 했는데 
동등한 상황(0)을 제외하고는 양의 정수, 음의 정수만 반환하면 된다고 공식 문서에도 써있네요.
https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html

고쳐야 하는 점은 아니고 혹시나 나중에 도움이 될까 싶어 코멘트 남깁니다.

2021-05-27 13:28 UTC, tearight commented on src/main/java/study/lotto/Play.java
> +        resultView.winningResult(winningResult,profitRate);
여기에는 객체들간의 메소드 호출순서 등의 흐름이 있는데요.(로직이죠)
이런 로직 또한 테스트의 대상이 되므로 객체화하여 실행이 됐으면 좋겠습니다.

2021-05-27 13:28 UTC, tearight commented on src/main/java/study/lotto/PurchasedLottos.java
>          }
Stream 으로 대체하면 반복문이 사라질 뿐 아니라 lottoNumbers 도 final 이 될 것 같아요.

2021-05-27 13:28 UTC, tearight commented on src/main/java/study/lotto/WinningPrize.java
> +    private int matchCount;
final 이 아니면 런타임 중에 값이 변할수도 있어요. 상수로써 역할을 하기 힘들어 질 것 같네요.

2021-05-27 13:28 UTC, tearight commented on src/main/java/study/lotto/util/LottoNumberGenerator.java
> +    //이런 경우 이처럼 그냥 static method로 하는지, 아니면 제너레이터 메서드를 non static 메서드로 해야하는지 의견을 듣고 싶습니다.
상태를 가질 필요가 없으면 static 도 괜찮아보입니다. 저는 이게 정석이라고 생각합니다.
그럼에도 불구하고 실무에서 static 메소드를 꺼려하시는 분도 계시는데요.
static 은 자바 프로그램 실행시 정의되기 때문에 mocking, stubbing 할 수 없다는 단점이 있습니다.
개발 편리성 때문에 인스턴스 메소드로 하시는 분들도 많습니다.

2021-05-27 13:28 UTC, tearight commented on src/main/java/study/lotto/util/LottoNumberGenerator.java
> +    //이런 경우 이처럼 그냥 static method로 하는지, 아니면 제너레이터 메서드를 non static 메서드로 해야하는지 의견을 듣고 싶습니다.
이러한 주석은 제가 읽으면 최대한 답변을 남기려고 하는데요,
만약에 놓칠 경우는 답변을 못할수도 있기 때문에 github 에 코멘트로 남겨주시면 좋을 것 같습니다. 👍

2021-05-27 13:28 UTC, tearight commented on src/main/java/study/lotto/LottoGame.java
> +    public static final List<Integer> AVAILABLE_LOTTONUMBERS = IntStream.rangeClosed(1, 45).boxed().collect(Collectors.toList());
List 의 경우에는 final 을 붙이는 것이 의미가 조금 덜 할 수 있는데요.
컬렉션이기 때문에 remove, add 등의 메소드를 그대로 사용할 수 있기 때문이죠.
따라서 Collections.unmodifiableList(List) 로 한번 더 감싸는 것을 추천드립니다.
remove, add 등 컬렉션에 변경을 가하는 메소드가 호출될 경우 안전장치로써 예외를 던지는 컬렉션으로 감싸줍니다.

2021-05-27 13:29 UTC, merged

2021-05-27 14:02 UTC, cupeanimus commented on src/main/java/study/lotto/LottoNumber.java
> +    }
감사합니다. 좀 더 파고들어서 소스를 좀 더 효율적으로 짜도록 노력해야겠네요

2021-05-27 14:13 UTC, cupeanimus commented on src/main/java/study/lotto/WinningPrize.java
> +    private int matchCount;
변경하는 부분이 없어서 무심코 넘어갔는데 상수인 값엔 final 사용을 좀 더 적극적으로 해봐야겠네요