[로또-Step3] 리뷰 요청드립니다.
next-step/java-lotto pull request #1599
Opened 2021-05-22 13:26 UTC by Donghui-Lee

2021-05-23 08:00 UTC, hhlyn0328 requested changes
전체적으로 구조를 잘 잡고 진행해주셨네요 :) 
소소한 코멘트 남겼으니 참고해주세요 !

2021-05-23 10:20 UTC, Donghui-Lee commented on src/main/java/lotto/domain/LottoRank.java
> +    public int hit() {
음.. 엘레강트 오브젝트 책을 읽다가 
getAmount() 보다는 amount() 메소드 사용이 객체를 데이터의 저장소로 취급하지 않고 
좀 더 존중한다는 의미가 들어 사용하게 되었습니다.
또, getter의 사용을 지양해야 한다는 내용이 있어 지켜보려고 하는데.. 메서드 명 짓는게 참으로 어렵네요...ㅎㅎ :)

2021-05-23 10:23 UTC, Donghui-Lee commented on src/main/java/lotto/domain/LottoMachine.java
> +        lottos.forEach(lotto -> lottoWin.hit(lotto.match(winLotto.lottoNumbers())));
한 줄에 점 하나를 찍는걸 지켜보려고 하는데 먼가 매끄럽지 않다고 생각되어 코드를 조금 변경했습니다 ..
저 부분을 어떻게 변경하는게 매끄러워 보일까요??

2021-05-23 10:23 UTC, Donghui-Lee commented on src/main/java/lotto/domain/Lotto.java
> +            .map(i -> LottoNumber.of(i.trim()))
넵 감사합니다. :)

2021-05-23 10:24 UTC, Donghui-Lee commented on src/main/java/lotto/domain/Lotto.java
> +        return matchCount;
넵 감사합니다. :)

2021-05-23 10:24 UTC, Donghui-Lee commented on src/main/java/lotto/domain/LottoWin.java
> +            int multiple = lottoWinType.amount() * lottoWin.get(lottoWinType);
굳이 한번 더 담을 필요는 없는것 같습니다. 감사합니다 :)

2021-05-23 10:24 UTC, Donghui-Lee commented on src/main/java/lotto/domain/LottoRank.java
> +    private final int amount;
감사합니다 :)

2021-05-24 02:04 UTC, hhlyn0328 commented on src/main/java/lotto/domain/LottoRank.java
> +    public int hit() {
이게 정답이 없다보니 사람마다 생각이 달라 더 혼란스러운거 같아요 
사실 다른거 보다 hit 처럼 단어가 명사/동사의 의미를 다 가지는 경우,  `lottorank.hit()` 이라고 호출했을 때
이게 단순 getter의 역할인지 객체를 타고 넘어와서 확인해야 알겠더라구요 

getter의 사용은 지양하지만 무조건 사용하지 말라는 아니고 
`정말 필요한 경우에만 사용해보도록 노력해보자` 고 이해하시면 좋을 거 같아요
setter는 웬만하면 사용하지말자

2021-05-24 02:30 UTC, hhlyn0328 approved these changes
리뷰 반영을 잘해주셨네요 :)  
질문 주셨던 내용에 대한 답변은 코멘트로 남겨두었으니
다음 미션 진행하시면서 참고해주세요 !

2021-05-24 02:30 UTC, hhlyn0328 commented on src/main/java/lotto/domain/LottoMachine.java
> +        });
winLotto가 가지는 number들을 지금 여기서 꺼낼 필요가 없어보여요
Lotto.match 가 List<LottoNumber>를 받지않고 Lotto 를 받으면 어떨까요?

2021-05-24 02:30 UTC, merged

2021-05-24 09:00 UTC, Donghui-Lee commented on src/main/java/lotto/domain/LottoRank.java
> +    public int hit() {
그렇게도 생각될수 있군요 감사합니다 ㅎㅎ 
제가 사용하고도 혼란스러운 부분이 있었는데 
리뷰어님 말씀대로 '정말 필요한 경우에만 사용해보도록 노력해보자'라고 이해하는게 좋을것같네요 ㅎㅎ
감사합니다 :)