[1주차 - step3] 리뷰 요청드립니다.
next-step/java-lotto pull request #1608
Opened 2021-05-22 18:17 UTC by chajs226

테스트 가능한 코드를 작성하는게 쉽지가 않네요. 계속 연습이 필요할 것 같습니다. ㅠㅠ 보완이 필요한 점 리뷰 부탁드립니다.

2021-05-23 03:04 UTC, ssosso requested changes
준성님~ 로또 3단계 진행하시느라고 고생 많으셨습니다ㅠ
피드백 남겼는데 확인 부탁드려요~
그리고 코드를 refactoring하면서 기존 로직이 분리되어 신규 객체들이 생기게 되었을 때, 테스트 또한 분리하면서 진행해보시면 어떨까요~? 지금은 PurchaseLotto 대상으로 1개의 기능을 테스트할 때 여러 상태를 신경써야 하는데 기능을 가진 각 객체에 대해 테스트를 하게 되면 더 쉽고 더 풍부하게 테스트하실 수 있습니다:)

2021-05-25 05:07 UTC, ssosso requested changes
준성님~ 점점 객체간의 역할이 정리되어 가고 있네요:)
step4를 진행하시기 전에 제가 남긴 피드백이 도움이 되실 거 같아서 추가 피드백에 대해서 고민해보시면 어떨까요~?
그리고 중요한 로직이 있는 ResultAll 등의 클래스에 대한 테스트가 아직 없는거 같아요, 추가해보시면 어떨까요~?

2021-05-25 05:07 UTC, ssosso commented on src/main/java/lotto/PurchaseLotto.java
> +            wonCountForOneLotto = lottoCompare.countWonNumbers(lottoNumberList.get(i).getLottoNumbers(), lastWonLottoNumber.getLastWonLottoNumbers());
lottoNumberList에게 lastWonLottoNumbers를 주고 count를 계산하도록 하면 어떨까요~?

2021-05-25 05:07 UTC, ssosso commented on src/main/java/lotto/ResultScoreEnum.java
> +    SIX("6개 일치 (2000000000원)", 2000000000);
👍

2021-05-25 05:07 UTC, ssosso commented on src/main/java/lotto/ResultAll.java
> +                ResultScoreEnum.SIX.getWonMoney(resultMap.get(ResultScoreEnum.SIX))) / (float) purchaseAmount);
👍

2021-05-25 06:09 UTC, chajs226 commented on src/main/java/lotto/LottoNumber.java
> +    public void makeLottoNumber(LottoNumberGeneratorStrategy lottoNumberGeneratorStrategy) {
step4에서 일괄 반영하겠습니다. ^^

2021-05-25 06:09 UTC, chajs226 commented on src/main/java/lotto/ResultAll.java
> +            resultMap.put(ResultScoreEnum.SIX, resultMap.get(ResultScoreEnum.SIX)+1);
step4에서 일괄 반영하겠습니다. ^^

2021-05-25 06:09 UTC, chajs226 commented on src/main/java/lotto/PurchaseLotto.java
>      private void updateResultLotto(int wonCountForOneLotto) {
step4에서 일괄 반영하겠습니다. ^^

2021-05-25 06:09 UTC, chajs226 commented on src/main/java/lotto/Lotto.java
> +
step4에서 일괄 반영하겠습니다. ^^

2021-05-25 06:09 UTC, chajs226 commented on src/main/java/lotto/PurchaseLotto.java
> +            wonCountForOneLotto = lottoCompare.countWonNumbers(lottoNumberList.get(i).getLottoNumbers(), lastWonLottoNumber.getLastWonLottoNumbers());
step4에서 일괄 반영하겠습니다. ^^

2021-05-25 06:12 UTC, ssosso approved these changes
두번째로 피드백 드린 내용은 다음 step4단계 진행하실 때 함께 고려해주신다고 하여 본 PR은 step4 진행을 위해 merge하도록 하겠습니다:) 고생많으셨습니다~

2021-05-25 06:12 UTC, merged