[3단계 - 로또(자동)]  리뷰요청 드립니다!
next-step/java-lotto pull request #1636
Opened 2021-05-24 08:45 UTC by byunghakjang1230

확실히 이전 과제들 보다 구현해야 할 내용도 많고 고려해야 할 사항도 많다 보니 도메인을 도출하고 기능을 어디에 두는게 맞을지를 고민하는 과정이 상당히 어려웠습니다. 
지난주 같은 기수 분들과 페어 프로그래밍을 하면서 기능 요구사항을 도출해 내는 과정을 연습했던 것을 토대로 다시한번 기능 요구사항을 작성해 보았는데 속성을 가지는 부분들은 요구사항 작성 및 도메인 도출이 조금 수월 했으나 어떠한 기능에 대한 부분을 정리해나가는게 개인적으로 어려웠던 것 같습니다. 위에 언급한 것 처럼 기능을 담당할 도메인이 적합한지 판단하는것도 너무 어려웠고, 나중에 어떤 기능을 다른 도메인으로 옮기는 과정에서 너무 넓은 범위의 코드 수정도 일어나면서 기능단위의 개발 및 커밋을 지키는 것도 뒤로 갈수록 점점 어려둬 지더군요. 개인적으로는 좀 더 세분화된 기능 요구사항을 도출하고 도메인의 역할을 명확하게 하는 연습을 많이 해봐야겠다는 생각을 아주 많이 한 시간이었습니다.ㅜㅜ

공격적인 코멘트 부탁드립니다! (이전 코멘트들도 기억하면서 한다고 했는데 뭔가 많이 놓친것 같은 기분이 드네요.🥲)

2021-05-24 12:34 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드려요.

2021-05-24 12:34 UTC, kingbbode commented on src/main/java/lotto/controller/LottoController.java
> +    }
필드로 가지고 있는 객체와, 지역 변수로 사용하는 객체는 어떤 기준으로 분리하셨을까요? :)

2021-05-24 12:34 UTC, kingbbode commented on src/main/java/lotto/domain/LottoNumbers.java
> +        this.lottoNumbers = lottoNumbers;
일반 생성자는 값을 초기화하는 정도의 일만하고 그 외의 일을 하지 않도록 순수하게 작성해야 합니다.
일반 생성자 내에 로직은 확장을 제한시키고, 각종 예외처리와 테스트를 더 어렵게 만들게 됩니다.

의미를 부여하는 생성 로직을 만들어야한다면 다른 객체와 상호작용하거나, 정적 팩터리 생성자를 활용할 수 있습니다.

2021-05-24 12:34 UTC, kingbbode commented on src/main/java/lotto/domain/Lotto.java
> +                .count();
`LottoNumbers` 가 만들어진게 일급 객체로서 상태를 관리하기 위함일텐데, `Lotto` 를 따로 만들어서 `LottoNumbers` 의 상태를 대신 관리하는 이유는 무엇일까요?

2021-05-24 12:34 UTC, kingbbode commented on src/main/java/lotto/domain/LottoMachine.java
> +    public Lottos getLottos() {
`get` 은 `getter` 와 같은 단순 값을 반환하는 의미로 사용됩니다.
이 메서드는 `get` 보다는 더 직관적인 이름으로 변경되면 좋겠네요 :)

2021-05-24 12:34 UTC, kingbbode commented on src/main/java/lotto/domain/Price.java
> +    public static final int LOTTO_PRICE = 1000;
`Price` 가 로또의 비지니스를 가지고 있는 것이 어색해보이네요.

"돈의 개념"과 "로또의 비지니스"라는 역할을 분리해볼 수도 있을 것 같습니다. 분리된 역할에 대한 책임을 누가 가져야할지도 고민해보시면 좋을 것 같습니다.

2021-05-24 12:34 UTC, kingbbode commented on src/main/java/lotto/domain/LottoMachine.java
> +        return new Lottos(lottos);
`generateRandomLottoNumbers` 는 값이 랜덤으로 생성되는 코드입니다.
이러한 코드가 순수한 클래스 내부에 숨어있을 때 이 코드를 사용하는 모든 코드는 난수값 생성에 대한 제어권이 없으므로, 항상 성공한다고 보장할 수 없으므로 신뢰할 수 없는 코드가 됩니다.

https://www.slipp.net/questions/557

참고하여 모든 코드를 신뢰할 수 있는 코드로 개선 부탁드리겠습니다 :)

2021-05-24 12:34 UTC, kingbbode commented on src/main/java/lotto/domain/Lottos.java
> +    }
`LottoStatistics ` 가 아닌  `Lottos` 가 `LottoStatistics` 를 생성해야하는 책임을 갖는 기준은 무엇일까요?
`LottoStatistics` 와 `Lottos` 간의 의존관계 방향을 고민해보시면 좋을 듯 합니다 :)

2021-05-24 12:34 UTC, kingbbode commented on src/main/java/lotto/domain/WinningAmounts.java
> +}
나열성 데이터는 `enum` 으로 해결했을 때 보다 명시적이고 응집된 역할을 만들어낼 수 있습니다.
https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

2021-05-24 12:34 UTC, kingbbode commented on src/test/java/lotto/domain/LottoNumbersGeneratorTest.java
> +    @DisplayName("로또번호 객체 생성")
전체적으로 테스트를 꼼꼼히 작성해주셨네요 :)
하지만 아쉬운 점은 테스트명이 구현을 염두하여 작성된 느낌을 받습니다. 테스트는 주어진 비지니스 요구사항을 옮겨주시면 좋을 듯 합니다.

객체 생성은 우리가 요구하는 비지니스 조건이 아닙니다. 이런 테스트는 큰 의미가 없는 테스트입니다 :)
요구사항을 테스트하면 자연스럽게 모든 코드들이 검증될 수 밖에 없다는 것이 TDD 의 중요한 가치 중 하나입니다 :)
("객체","생성","예외" 와 같은 용어를 테스트 이름에 사용하지 않는 연습을 해보시는 것을 추천드립니다.)

2021-05-24 14:03 UTC, byunghakjang1230 commented on src/test/java/lotto/domain/LottoNumbersGeneratorTest.java
> +    @DisplayName("로또번호 객체 생성")
페어 프로그래밍 때 함께 하신 분과 잠깐 지나가면 했던 내용인데 좀 더 명확한 방향성을 짚어주셔서 감사합니다! 음...요구하는 비지니스 요구사항 단위로 테스트 코드를 작성한다라... 요구사항이 더 구체적이고 명시적으로 도출되어야 겠군요! 
말씀하신 방향성, 가치를 가지고 테스트 코드 작성하는 부분을 고민하고 연습해보겠습니다!

2021-05-24 18:30 UTC, byunghakjang1230 commented on src/test/java/lotto/domain/LottoNumbersGeneratorTest.java
> +    @DisplayName("로또번호 객체 생성")
페어 프로그래밍 때 함께 하신 분과 잠깐 지나가면 했던 내용인데 좀 더 명확한 방향성을 짚어주셔서 감사합니다! 음...요구하는 비지니스 요구사항 단위로 테스트 코드를 작성한다라... 요구사항이 더 구체적이고 명시적으로 도출되어야 겠군요!
말씀하신 방향성, 가치를 가지고 테스트 코드 작성하는 부분을 고민하고 연습해보겠습니다!

2021-05-24 19:04 UTC, byunghakjang1230 commented on src/main/java/lotto/domain/Price.java
> +    public static final int LOTTO_PRICE = 1000;
해당 값은 로또의 가격 표시가 아닌 금액을 관리하는 최소단위로 명칭을 변경하여 입력값을 검증하는데 사용하도록 수정하였습니다. 그리고 로또 구매 가능한 개수를 계산하는 메소드를 제거하여 금액과 로또의 속성, 비지니스 로직을 분리하였습니다.

2021-05-24 19:05 UTC, byunghakjang1230 commented on src/main/java/lotto/domain/LottoMachine.java
> +    public Lottos getLottos() {
명칭은 신경 쓴다고 해도 자꾸 놓치게 되네요.ㅜㅜ createLottos로 메소드 명칭을 변경하였습니다.

2021-05-24 19:08 UTC, byunghakjang1230 commented on src/main/java/lotto/domain/Lotto.java
> +                .count();
LottoNumbers와 Lotto를 구분하는 기준으로 고민을 많이 했었습니다. Lotto는 6개의 번호를 가지지만 번호의 집합체로만 봐야 하는것이가 하는 궁금증이 있었거든요. 즉...Lotto객체와 번호의 집합체인 일급 콜렉션을 따로 관리해야 할지 Lotto 자체를 일급 콜렉션으로 두고 번호를 관리할지 고민하다가 분리하기로 하면서 현재의 모습이 되긴 했는데 어떤 방향이 더 나은 방향일까요? 음...우선은 언급해주신 문제점을 가지고 중간에 존재했던 Lotto를 제외하고 Lottos가 LottoNumbers 목록을 가지도록 코드를 수정하였습니다. 확실히 중간단계가 사라지니 불필요한 메서드나 코드가 많이 제거되었습니다.

2021-05-24 19:09 UTC, byunghakjang1230 commented on src/main/java/lotto/controller/LottoController.java
> +    }
처음 의도는 controller의 메서드를 더 세분화 하려고 했었는데 하나로 두면서 정리가 되지 않았습니다. 코멘트 받고 리팩토링을 진행하면서 처음 생각했던데로 메서드를 분리하고 클래스 전역에서 공유되어야 하는 객체만 맴버변수로 포함시는 기준을 두고 수정을 진행하였습니다!😓

2021-05-24 19:10 UTC, byunghakjang1230 commented on src/main/java/lotto/domain/LottoNumbers.java
> +        this.lottoNumbers = lottoNumbers;
이 부분은 일급 컬렉션으로 만들면서 입력된 값에 대한 유효성 검증하는 코드인데 이것도 문제가 되는 부분일까요??😮

2021-05-24 19:11 UTC, byunghakjang1230 commented on src/main/java/lotto/domain/Lottos.java
> +    }
항상 긴가 민가 했던 것들이 결국 다른 방향으로 가는 것 같아서 아쉽다는 생각이 들면서도 조금 더 고민해 볼껄 하는 후회도 같이 드네요.ㅜㅠ 새로운 통계 처리 클래스를 만들어서 로또 목록과 당첨번호를 받아 내부에서 통계결과를 만들어 내도록 구현하여서 Lottos와 통계기능의 역할을 분리하였습니다.

2021-05-24 19:12 UTC, byunghakjang1230 commented on src/main/java/lotto/domain/WinningAmounts.java
> +}
다음 Step 미션으로 구현하려고 했는데 코드도 보기가 그렇고 코멘트도 달린 김에 Enum 구현하였습니다!

2021-05-25 10:17 UTC, byunghakjang1230 commented on src/main/java/lotto/domain/LottoMachine.java
> +        return new Lottos(lottos);
generateRandomLottoNumbers를 인터페이스로 구현하였습니다.(메소드 명도 약간 변경하였습니다.)  LottoMachine 내부에서 해당 객체를 생성 했었는데 생성자 매개변수로 인터페이스를 받는 형식으로 수정하여 결과적으로 컨트롤러에서 해당 객체를 주입해주는 형태로 구현하였습니다. 주신 링크 참고하여 테스트 코드에서도 해당 인터페이스 구현한 임시클래스를 반환하는 메서드를 만들어 테스트에 필요한 데이터를 쉽게 만들수 있는 형태로 구현하였습니다.
어제 새벽부터 쭉 고민했었는데 코멘트의 의도가 반영된 내용인지 모르겠네요..ㅜㅜ

2021-05-26 00:23 UTC, kingbbode commented on src/main/java/lotto/domain/LottoNumbers.java
> +        this.lottoNumbers = lottoNumbers;
네 :) 일반 생성자는 일급 객체라 할지라도 비지니스를 포함할 때 생기는 문제점이 많습니다.
대부분의 객체는 스스로 생성 규칙을 갖기보다는 비지니스와 상호작용이 되면서 생성 규칙이 생기게 됩니다.

극단적인 예시로 이런 요구사항이 들어왔다고 할게요.
- 로또 게임의 모드가 추가된다.
- EAZY 모드에서는 3개의 번호로 추첨한다.
- HARD 모드는 기존과 동일하다.
- 두 모드를 모두 지원해야 한다.

`LottoNumbers` 의 일반 생성자는 HARD 모드를 기준으로 만들어졌기 때문에 더 이상 확장할 수 없는 구조입니다. 현재의 규칙을 유지한다면 불필요하게 `LottoNumbers` 클래스를 복사하여 새로운 `LottoNumbers` 클래스를 만들어야겠지요.

극단적인 예시입니다만, 이러한 이유로 일반생성자는 어떠한 비지니스도 포함하지 않는 것이 가장 좋습니다. 현재의 요구사항만을 바라보고 객체의 규칙을 형성할 수 없을뿐더러, 위의 예시에서 보여주듯 객체의 규칙은 비지니스와의 상호작용으로 만들어지기 때문입니다.

2021-05-26 00:26 UTC, kingbbode approved these changes
잘 구현해주셨네요!
이만 머지하겠습니다 :)
코멘트 확인 부탁드립니다.

2021-05-26 00:26 UTC, kingbbode commented on src/main/java/lotto/controller/LottoController.java
> +        lottoStatistics.initStatistics();
객체를 생성하고 `initStatistics` 을 하는 것은 객체 생성의 필수 규칙입니다 :)
외부에 드러내기보다는 객체의 생성을 담당하는 곳에서 책임을 다 해야합니다.

2021-05-26 00:26 UTC, merged

2021-05-26 15:21 UTC, byunghakjang1230 commented on src/main/java/lotto/domain/LottoNumbers.java
> +        this.lottoNumbers = lottoNumbers;
이야기 하신것 처럼 로또의 번호 개수의 기준이 다양해 지는 등 여러 옵션을 사용해야 하는 상황이 되면 분명이 기능 확장, 재활용이 어렵게 되는 구조인 것 같습니다. 예시까지 들어주셔서 빨리 이해가 되었습니다!
클래스 생성자에 유효성검사를 넣는다는 생각을 너무나도 자연스럽게, 당연하게 여기고 있었네요.😓 
"비지니스와 상호작용이 되면서 생성 규칙이 생기게 된다" 라는 말이 조금 더 구체적으로 와 닿도록 개발과정 가운데 이런 상황에 직면할 때 마다 한번 더 생각하고 고민을 해보아야 할 것 같습니다.👍