Step3
next-step/java-lotto pull request #1637
Opened 2021-05-24 09:03 UTC by sanola2

리뷰 요청 드립니다! 감사합니다.

2021-05-24 17:13 UTC, hhlyn0328 requested changes
로또 (자동) 미션을 잘 진행해주셨네요 !! 
몇 가지 코멘트 남겼습니다  확인 부탁드려요 :)

2021-05-24 17:13 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +				.map(it -> it.getMatchedNumberCount() + "개 일치 (" + it.getPrizeMoney() + "원)- " + getNumberOfLottosMatchedWith(it.getMatchedNumberCount()) + "개")
현재 LottoPrizeType 의 수만큼 getNumberOfLottosMatchedWith 를 호출하고 있습니다 
즉, lottoResults를 N번 순회하게 되는데요  
한 번만 돌면서 EnumMap을 구성해 활용해보면 어떨까요?

2021-05-25 02:17 UTC, sanola2 commented on src/test/java/lotto/LottoDrawerTest.java
> +	@CsvSource(value = {"500:0", "1000:1", "5000:5", "14000:14", "14500:14", "16100:16", "19122140:19122"}, delimiter = ':')
에고 코드를 수정해 놓고 테스트코드를 신경쓰는걸 깜빡 했네요..!

2021-05-25 06:11 UTC, sanola2 commented on src/main/java/lotto/LottoResult.java
> +				.map(it -> it.getMatchedNumberCount() + "개 일치 (" + it.getPrizeMoney() + "원)- " + getNumberOfLottosMatchedWith(it.getMatchedNumberCount()) + "개")
혹시 enumMap 은 stream, Collectors의 groupnigBy를 이용해서는 만들지 못하는 걸까요?😢

2021-05-25 09:28 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +								.sum())
내부의 stream 구문은 별도의 함수로 빼면 좋을 거 같아요 !

2021-05-25 09:28 UTC, hhlyn0328 commented on src/main/java/lotto/LottoResult.java
> +				.map(it -> it.getMatchedNumberCount() + "개 일치 (" + it.getPrizeMoney() + "원)- " + getNumberOfLottosMatchedWith(it.getMatchedNumberCount()) + "개")
아래와 같이 전달하여 생성가능합니다 😄 
```
        .collect(Collectors.groupingBy(Function.identity()
                        , () -> new EnumMap(LottoRank.class)
                        , Collectors.counting()))
```

2021-05-25 09:29 UTC, hhlyn0328 approved these changes
리뷰 반영을 잘해주셨네요 ! 
질문 주셨던 내용 코멘트 남겼으니 확인해주세요 :) 

추가적으로 고민하실 부분은 다음 미션과 함께 진행하실 수 있을 것 같아 머지하겠습니다!!

2021-05-25 09:29 UTC, merged

2021-05-25 09:43 UTC, sanola2 commented on src/main/java/lotto/LottoResult.java
> +				.map(it -> it.getMatchedNumberCount() + "개 일치 (" + it.getPrizeMoney() + "원)- " + getNumberOfLottosMatchedWith(it.getMatchedNumberCount()) + "개")
와 감사합니다!! 함수 자체를 classifier 로 넘기면 되는거였네요..!