[Step4] 로또(2등) 리뷰 요청드립니다.
next-step/java-lotto pull request #1645
Opened 2021-05-24 15:15 UTC by 7271kim

안녕하세요 리뷰어님 :)
4단계 완료하여 리뷰요청 드립니다.
3단계를 리뷰 수정까지 거진 2박3일 밤새고 진행하여 4단계도 오래 걸릴까 걱정했는데..
수정점이 많지가 않아 생각보다 금방 끝났습니다.
보시면서 이상하다 싶은 부분 속 시원히 말씀해 주세요~
감사합니다.

2021-05-24 23:42 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
빡센 피드백을 요청하셨는데 별로 빡세지 않은 것 같아 걱정입니다.
마지막 리팩토링 과제로 시도해볼만한 변화들을 제안해 드렸습니다. 한번 죽 읽어보시고 적용해주세요.

2021-05-24 23:42 UTC, wheejuni commented on src/main/java/step3/game/Lotto.java
> +        }
메소드를 설계할때는 항상 메소드에 의존하는 측의 관점에서 설계하는 것이 바람직한데요,
지금 `Price.getBuyCount()` 가 정수형 리턴 타입을 갖기때문에 for loop로 순회하게 되었는데,
만약 여기서 `IntStream` 과 같은 리턴 타입을 가진다면 어떤 유연한 설계가 가능해질까요?
이렇게 개선해보시고 한번 느껴보시는 건 어떨지요?

2021-05-24 23:42 UTC, wheejuni commented on src/main/java/step3/game/Lotto.java
> +        }
다만 메소드 이름도 변경돼야 하겠네요.

2021-05-24 23:42 UTC, wheejuni commented on src/main/java/step3/game/Lotto.java
> +        } catch (Exception e) {
`Exception` 을 캐치할 때는 가장 지엽적인 범위로 캐치하는 것이 명시적으로 예외 처리 로직을 태우는데 도움이 됩니다.
어떤 예외를 캐치하고자 하신 건가요? `Exception` 이라는 클래스 하나로 캐치하기에는 너무 범위가 넓지 않을까요.

2021-05-24 23:42 UTC, wheejuni commented on src/main/java/step3/game/Lotto.java
> +    }
왜 이렇게 프라이빗 메소드가 많이 필요했을까요?
자기 자신의 상태를 드러내는 문자열 정도는 `TotalLotto` 가 직접 만들어도 되는데, 그렇지 않고 `.size()` 와 단순 `.toString()` 을 그냥 가져와 사용하고 있기 때문이고, 무엇보다 `ResultView` 에게 위임될 책임이 제대로 넘어가지 않았기 때문입니다.

이 관점에서 설계 한 번만 다시 해보시면 좋겠어요.

2021-05-24 23:42 UTC, wheejuni commented on src/main/java/step3/game/Lotto.java
> +        String[] numbers = inputView.getVictoryNumbers();
단순 문자열 배열 말고, 입력 문자열을 감싸는 다른 객체가 설계된다면 여기서 밸리데이션 로직까지 수행할 수 있을 것 같네요.

2021-05-24 23:42 UTC, wheejuni commented on src/main/java/step3/model/LottoNumbers.java
> +    }
밑의 스태틱 팩토리 메소드들이 잘 기능하고 있으므로 이 생성자들은 `private` 으로 숨겨도 되겠습니다.

2021-05-24 23:42 UTC, wheejuni commented on src/main/java/step3/model/LottoNumbers.java
> +    public String toString() {
`.toString()` 은 이런 목적으로 사용하는 메소드는 아닙니다. 객체에 대해 디버그 목적이나 개발간의 필요성을 위해 사용할 수 있도록 고려해 주시고요,
특히 `.toString()` 안에 복잡한 로직이 들어가면 디버그하기도 어렵고 때로는 어이없는 사이드 이펙트가 나는데 그 원인을 찾기 어렵게 되는 경우도 많습니다.

가급적 이 메소드의 생성은 IDE의 도움을 받아 자동 생성하는 것을 원칙으로 해주시고 커스텀 로직은 최소화해주세요.

2021-05-25 13:22 UTC, 7271kim commented on src/main/java/step3/game/Lotto.java
> +        }
IntStream을 return 타입으로 갖는다면 filter, map등 다양한 방법으로 stream을 응용할 수 있다는 생각이 듭니다.
우선 제 생각대로 로직을 바꾸어 보았는데.. 혹시 제가 수정한 코드가 리뷰어님께서 생각한 코드가 맞는지, 아니라면 혹시 리뷰어님이라면 어떻게 짰을 것 같은지 팁 부탁드립니다~

2021-05-25 13:23 UTC, 7271kim commented on src/main/java/step3/game/Lotto.java
> +    }
음.. "ResultView 에게 위임될 책임이 제대로 넘어가지 않았기 때문" 이라는 멘트가 아직 마음에 와 닿지가 않습니다.
과도하게 생성된 private 메서드 수 는 줄였지만, 조금 더 자세한 설명을 해주신다면 감사하겠습니다 :)

2021-05-25 13:24 UTC, 7271kim commented on src/main/java/step3/model/LottoNumbers.java
> +    }
꼼꼼한 리뷰 감사드립니다. ^^

2021-05-25 13:25 UTC, 7271kim commented on src/main/java/step3/model/LottoNumbers.java
> +    public String toString() {
임의적인 toString() 오버라이드는 지양하도록 하겠습니다.
감사합니다.

2021-05-25 13:45 UTC, 7271kim commented on src/main/java/step3/game/Lotto.java
> +        String[] numbers = inputView.getVictoryNumbers();
좋은 의견 감사합니다!

2021-05-25 13:46 UTC, 7271kim commented
안녕하세요 리뷰어님 ~
피드벡 사항 수정 완료했습니다.
피드백을 수정하다보니, 보기 좋지 않았던 코드들이 깔끔해지고 있어 뿌듯합니다.
피드백을 통해 생각하지 못했던 부분에 대해 한번 더 고민 할 수 있는 시간이 되어서 좋았습니다 :)

Step 4 코드 수정 중 문의사항, 피드백 주셧던 댓글에 문의드렸습니다.
시간되실 때 답변 부탁드리겠습니다.
항상 감사합니다.

2021-05-25 14:13 UTC, wheejuni commented on src/main/java/step3/game/Lotto.java
> +    }
@7271kim 네, 실제 `TotalLotto` 를 풀어서 문자열로 구성할 책임이 `ResultView` 에게 넘어가야 할 것 같다는 말씀이었습니다.
`ResultView` 자체에 `TotalLotto` 객체 전체가 넘어가야 한단 말씀이었죠. 풀어서 하나하나 데이터를 넘기는게 아니구요.

2021-05-25 14:21 UTC, wheejuni approved these changes
수고 많으셨습니다. 👍 질문 남겨주신 부분도 답변 남겼습니다. 확인 부탁드릴게요~

2021-05-25 14:23 UTC, merged

2021-05-26 12:02 UTC, 7271kim commented on src/main/java/step3/game/Lotto.java
> +    }
그런 의미였군요 !
다음 피드백에 같이 반영하도록 하겠습니다 :)