Step4 윤병현 코드리뷰 부탁드립니다!
next-step/java-lotto pull request #1657
Opened 2021-05-25 04:03 UTC by ybh89

안녕하세요!
step3 피드백과 step4 보너스 볼 기능 추가하였습니다.
코드리뷰 부탁드립니다
감사합니다!

2021-05-25 04:20 UTC, JunilHwang requested changes
안녕하세요 병현님! Step4 구현을 빠르게 해주셨네요 👍 
몇 가지 리뷰 남겼으니 확인 후 다시 피드백 요청 부탁드립니다 😁

2021-05-25 04:20 UTC, JunilHwang commented on src/main/java/com/lotto/controller/LottoManager.java
> +        }
이보다 더 단순하게 구현해볼 수 있지 않을까요?

2021-05-25 04:20 UTC, JunilHwang commented on src/main/java/com/lotto/controller/LottoManager.java
>          return lottoWinningNumbers;
while 안에 try / catch 형태로 하기보다 더 직관적인 로직으로 만들어보면 좋을 것 같아요!

2021-05-25 04:20 UTC, JunilHwang commented on src/main/java/com/lotto/domain/LottoReward.java
> +        }
for / if가 중첩되지 않게 만들어주세요!

2021-05-25 04:20 UTC, JunilHwang commented on src/main/java/com/lotto/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
생성자는 private로 해주면 어떨까요? valueOf를 통해서만 생성되도록 해보세요!

2021-05-25 04:20 UTC, JunilHwang commented on src/main/java/com/lotto/domain/LottoNumber.java
> +    private static class LottoNumberCache {
지금은 이렇게 클래스로 분리할 필요는 없어보이네요!

2021-05-25 04:20 UTC, JunilHwang commented on src/main/java/com/lotto/domain/LottoWinningBonusNumber.java
> +public class LottoWinningBonusNumber extends LottoNumber {
BonusNumber를 따로 구현할 필요가 있을까요?
Lotto와 LottoNumber를 가지고 있는 WinningLotto를 하나 만들어보면 어떨까요?

2021-05-25 08:04 UTC, ybh89 commented on src/main/java/com/lotto/domain/LottoReward.java
> +        }
이 부분에 대해서 저도 많이 고민했었는데, 
for-if-return 패턴은 메서드를 빼거나 다른 방법을 사용하니 오히려 더 가독성이 나빠지더라구요, 
방금 4단계 피드백 영상 보고왔는데 포비님은 스트림으로 해결하시던데, 
미션 중에 스트림도 사용하지 말라고하셔서 
스트림 이외에 혹시 좋은 방법이 있다면 힌트를 얻을 수 있을까요?

2021-05-25 11:33 UTC, ybh89 commented on src/main/java/com/lotto/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
비즈니스 로직에 new로 로또넘버를 사용하는 곳이 하나 있어 수정하였습니다.
private로 변경할 경우 기존 테스트에 영향을 주게 되는데 변경 하는게 맞을까요?
포비님이 테스트를 위한 생성자는 괜찮다고 하셨던것 같아서요 혹시 제가 놓친 부분이 있으면 알려주시면 감사하겠습니다^^

2021-05-26 00:18 UTC, JunilHwang commented on src/main/java/com/lotto/domain/LottoReward.java
> +        }
단순하게 생각한다면 메소드로 분리하면 되지 않을까요? 혹은 그냥 Stream 써도 무방할 것 같습니다 ㅎㅎ

2021-05-26 00:23 UTC, JunilHwang approved these changes
안녕하세요 병현님! 피드백 반영 잘 해주셨네요 👍 
질문에 대한 답변은 해당 코멘트에 달아놨습니다!
Step4는 여기서 마무리하겠습니다.
이제 마지막 스텝이네요! 조금만 더 힘내봅시다 💪

2021-05-26 00:23 UTC, JunilHwang commented on src/main/java/com/lotto/domain/WinningLotto.java
> +    }
setter로 주입받기보단 생성시점에 주입하는게 어떨까요?

2021-05-26 00:23 UTC, merged

2021-05-26 05:29 UTC, ybh89 commented on src/main/java/com/lotto/domain/WinningLotto.java
> +    }
저도 생성자로 주입받는게 더 좋다고 생각하고 있어서 처음엔 당첨로또를 생성할 때, 당첨번호와 보너스볼을 주입하여 생성하면 좋겠다는 생각을 했습니다.
그런데 이렇게 되면 사용자로부터 당첨번호와 보너스볼을 모두 받은 후에 당첨로또를 생성할 수 있게 됩니다.
저는 사용자 편의성을 더 생각해서 설계를 했기 때문에
사용자가 당첨번호를 잘 못 입력했을 경우, 바로 다시 입력하여 받을 수 있게끔 설계를 해서요.

만약에 당첨 번호, 보너스 번호를 전부 받은 후에 당첨로또를 생성하게 되면 이 두 가지를 한 번에 유효성 체크를 해야하고,
만약, 사용자가 보너스볼을 잘못 입력했을 경우, 당첨번호까지 다시 입력해야하는 상황이 생겨서 보너스볼은 setter로 따로 받아서 주입 시점에 유효성 체크를 할 수 있게 설계 했는데

혹시 이것에 대해서는 어떻게 생각하시나요?