로또3단계 pr입니다. 통계 도메인에서 랜덤 값을 테스트하는 부분이 아직 어렵네요 ㅠ 코딩 재밌습니다 > <
next-step/java-lotto pull request #1673
Opened 2021-05-25 16:49 UTC by accidentlywoo

2021-05-26 21:59 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드립니다.

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/LottoNumberMatch.java
> +public class LottoNumberMatch {
객체로 만들어지지 않는 클래스 작성시에는 객체가 만들어질 수 없도록 private 생성자를 만들어두는게 좋습니다 :)

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/Lotto.java
> +public class Lotto {
로또 번호를 감싸기만 할뿐, 어떠한 책임도 가지지 않는 객체네요 :)
객체가 의미있는 책임을 가지도록 구성을 구성해주세요.

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/Lotto.java
> +	private final Integer[] numbers;
`Array` 보다는 `Collection` 으로 관리하는 것은 어떨까요?
`Collection` 은 `Array`의 기능을 포함하면서, 더 많은 인터페이스를 제공합니다.

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/LottoNumberMatch.java
> +            matchCount = Arrays.asList(lottoNumber).contains(number) ? matchCount+1 : matchCount;
`Arrays.asList(lottoNumber)` 역시 객체를 생산하는 일입니다.
매번 순회할 때마다 객체를 생성하는 것은 불필요해보입니다.
성능에 대한 최소한의 최적화를 고려하여 작성되면 좋을 것 같습니다 :)

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/LottoNumberMatch.java
> +        return matchCount;
하는 일에 비해 코드가 어렵게 작성되어있네요.

```
if(lottonumbers.contains(number)) {
    matchCount++;
}
```

`stream` 을 활용한다면 더 가독성있게 작성할 수도 있습니다.

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/LottoOrderGroup.java
> +			lottos.add(new Lotto(LottoRandomNumber.numbers()));
`LottoRandomNumber.numbers()` 는 값이 랜덤으로 생성되는 코드입니다.
이러한 코드가 순수한 클래스 내부에 숨어있을 때 이 코드를 사용하는 모든 코드는 난수값 생성에 대한 제어권이 없으므로, 항상 성공한다고 보장할 수 없으므로 신뢰할 수 없는 코드가 됩니다.

https://www.slipp.net/questions/557

참고하여 모든 코드를 신뢰할 수 있는 코드로 개선 부탁드리겠습니다 :)

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/generate/LottoRandomNumber.java
> +	public static Integer[] numbers () {
메서드명은 동사로 시작하는 것을 권장합니다.
https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/LottoOrderGroup.java
> +	}
일반 생성자는 값을 초기화하는 정도의 일만하고 그 외의 일을 하지 않도록 순수하게 작성해야 합니다.
일반 생성자 내에 로직은 확장을 제한시키고, 각종 예외처리와 테스트를 더 어렵게 만들게 됩니다.

의미를 부여하는 생성 로직을 만들어야한다면 다른 객체와 상호작용하거나, 정적 팩터리 생성자를 활용할 수 있습니다.

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/LottoOrderGroupAnalysis.java
> +	}
`LottoReward` 가 스스로 일치하는 개수에 대한 비지니스를 책임지도록 하는 것은 어떨까요?

`LottoOrderGroupAnalysis` 는 너무 많은 책임을 가지고 있는 것으로 보입니다.

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/LottoOrderGroupAnalysis.java
> +	public String yield () {
계산된 결과는 숫자인데, 반환값이 `String` 인 이유는 무엇인가요?

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/generate/LottoRandomNumber.java
> +		return lottoNumbers;
로또번호를 생성하는 과정이 다소 복잡하네요.
45개의 숫자풀에서 6개의 번호를 추출하면 쉽게 해결할 수 있지 않을까요?

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/ui/IOMessage.java
> +public enum IOMessage {
객체로서의 책임이 없어보이는데, `enum` 으로 구성한 이유는 무엇인가요?

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/ui/LottoController.java
> +	public void insertMoney () {
메서드 네이밍과 실제 하는 일이 일치하지 않아보입니다.

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/ui/LottoController.java
> +			System.out.printf("총 수익률은 %s입니다.%n", analysis.yield());
2단계 미션에서의 구조와는 많이 달라보이네요.

의미있는 단위로 책임과 역할을 응집시켜보는 것은 어떨까요?

2021-05-26 21:59 UTC, kingbbode commented on src/main/java/domain/LottoOrderGroupAnalysis.java
> +public class LottoOrderGroupAnalysis {
주어진 비지니스와 `Analysis` 라는 네이밍은 어울리지 않습니다.

`Analysis` 는 흔히 데이터 기반의 통계를 가공하여 의미있는 새로운 결과를 생성할 때 사용하는 용어입니다.

로또를 구입하는 비지니스와는 어울리지 않습니다.

또한 다소 범위가 넓은 의미를 갖는 `Analysis` 를 사용했기 때문에 이 객체가 너무 만은 책임을 갖게 되었을 수도 있다고 생각합니다 :)

2021-05-26 21:59 UTC, kingbbode commented on src/test/java/domain/LottoNumberMatchTest.java
> +class LottoNumberMatchTest {
무엇을 테스트해야할지 고민해보시면 좋을 듯 합니다.
현재의 테스트들은 그저 행위를 나열할 뿐 어떠한 요구사항을 테스트하는 것인지 전혀 알 수 없습니다. 이런 행위 기반의 테스트때문인지 테스트되어야할 다양한 내용들이 거의 테스트되지 못한 것으로 보입니다.

우리가 테스트해야할 것은 주어진 요구사항입니다.  비지니스 관점에서 "번호일치테스트_GREEN", "번호일치테스트_RED" 와 같은 테스트명과 테스트 내용은 나올 수 없는 테스트인 것이지요.

요구사항을 테스트하면 자연스럽게 모든 코드들이 검증될 수 밖에 없다는 것이 TDD 의 중요한 가치 중 하나입니다 :)

전체 테스트가 이렇게 작성되어 있는 것으로 보입니다. 전체 테스트를 의미있는 비지니스 단위로 테스트 작성 부탁드립니다.

2021-05-27 02:16 UTC, accidentlywoo commented on src/main/java/domain/Lotto.java
> +public class Lotto {
고민해보곘습니다

2021-05-27 02:17 UTC, accidentlywoo commented on src/main/java/domain/Lotto.java
> +	private final Integer[] numbers;
길이를 단호하게 지정하고 싶어서 사용했습니다. 리팩터링 해보겠습니다

2021-05-27 02:18 UTC, accidentlywoo commented on src/main/java/domain/LottoNumberMatch.java
> +        return matchCount;
앗! stream을 못쓴다는 강박에 갖혔는데, 사용하겠습니다

2021-05-27 02:19 UTC, accidentlywoo commented on src/main/java/ui/IOMessage.java
> +public enum IOMessage {
static 상수로 사용했었는데, enum을 써볼까... 해서 사용해봤습니당..

2021-05-27 02:20 UTC, accidentlywoo commented on src/main/java/ui/LottoController.java
> +			System.out.printf("총 수익률은 %s입니다.%n", analysis.yield());
ui파트를 단순화하려고 대 통합을 해봤습니다. 리팩터링 하겠습니다

2021-05-27 02:21 UTC, accidentlywoo commented on src/main/java/domain/LottoOrderGroupAnalysis.java
> +public class LottoOrderGroupAnalysis {
통계가 더 좋을까요? (statics) 영어공부가 필요하네요

2021-05-27 02:24 UTC, accidentlywoo commented on src/test/java/domain/LottoNumberMatchTest.java
> +class LottoNumberMatchTest {
요구사항을 작성하고 기능개발을 시작했는데, 훈련이 많이안됀 상태에서, 정신줄을 놓고 만들기 시작했더니...
스스로 코드를 짜면서 느껴졌던 부분입니다.. ㅠㅠ

2021-05-30 22:50 UTC, kingbbode requested changes
코멘트 작성해두었습니다.
확인 부탁드립니다 :)

2021-05-30 22:50 UTC, kingbbode commented on src/main/java/domain/LottoOrderGroupStatics.java
> +public class LottoOrderGroupStatics {
대부분의 객체가 비지니스를 생성단계에서 구현하고 있는 것으로 보입니다.
객체는 정보와 상태를 통해 비지니스를 구현해야 보다 확장성 있는 코드가 만들어질 수 있습니다 :)

```
class Numbers {
...
   public Numbers(int a, int b) {
          this.sum = a + b;
          this.subtract = a - b
   }
...
}
```

가 아닌

```
class Numbers {
...
   public Numbers(int a, int b) {
          this.a = a;
          this.b = b;
   }

   public int sum() {
       return a + b;
   }

   public int subtract() {
       return a - b;
   }
...
}
```

와 같이 객체를 사용해주세요 :)

2021-05-30 22:50 UTC, kingbbode commented
코멘트로 작성해두었던 내용을 전부 반영하신 것이 맞으실까요?
어려운 점이 있으시다면 편하게 DM 부탁드립니다 :)

2021-05-31 14:14 UTC, accidentlywoo commented on src/main/java/domain/LottoOrderGroupStatics.java
> +public class LottoOrderGroupStatics {
리뷰어님 말에 동감합니다만, LottoOrderGroupStatics 는 통계라는 명확한 행위가있는 클래스라서 생성자에 초벌작업까지 넣었습니다.

2021-06-01 13:40 UTC, kingbbode approved these changes
수고하셨습니다 :)
머지하겠습니다.

2021-06-01 13:40 UTC, merged

2021-06-06 04:29 UTC, accidentlywoo commented on src/main/java/domain/LottoOrderGroup.java
> +			lottos.add(new Lotto(LottoRandomNumber.numbers()));
너무 좋은 내용이네용! 놓칠뻔했습니다 꺄