5단계 - 로또(수동) 리뷰 요청드립니다~
next-step/java-lotto pull request #1679
Opened 2021-05-26 05:02 UTC by KwakTaeMin

TTD로 리펙토링하며 기능 추가하는 재미있는 경험이였습니다. 리뷰 부탁드리요~

2021-05-27 00:03 UTC, hhlyn0328 requested changes
로또 마지막 단계 구현도 잘 해주셨네요 !
몇 가지 피드백 남겼으니 확인 부탁드립니다 

이 다음이 마지막 PR이 될 수도 있겠네요 화이팅 🔥

2021-05-27 01:54 UTC, KwakTaeMin commented on src/main/java/lotto/domain/LottoPurchaseHistory.java
> +	private LottoCount manualLottoCount;
아 그럼 LottoPurchaseHistory에서 뭘 샀는지 어떤 것을 샀는지 산 번호가 무엇인지 까지 알 수 있는 객체가 되겠군요!

2021-05-27 01:55 UTC, KwakTaeMin commented on src/main/java/lotto/utils/LottoUtils.java
> +	public static Lottos getStringListToLottos(List<String> lottosStringList) {
아 A -> B 로 변환되는 메소드명은 map으로! 감사합니다.

2021-05-27 01:56 UTC, KwakTaeMin commented on src/main/java/lotto/utils/LottoUtils.java
> +		lottosStringList.forEach(lottoString -> lottos.addLotto(getStringToLotto(lottoString)));
아 그럼 코드도 간결해지고 함수를 호출할 때 마다 초기화하진 않을 것 같아서 좋을 것 같아요!

2021-05-27 01:59 UTC, KwakTaeMin commented on src/main/java/lotto/view/LottoInputView.java
> +		input = new Scanner(System.in);
아 저도 이부분에 대해서 질문드리고 싶었는데, 
nextInt 입력 받은 후에 
nextLine으로 입력하려고하면 "" 빈 String이 바로 입력되어지더라고요..
그래서 초기화를 했던 건데,

**nextLine으로 전체 string을 받아오면 뒤에 enter를 뺀 나머지가 들어오므로 이를 parseInt 해주시면 어떨까요?**

이 부분이 잘 이해가 가지 않아요 ㅠㅠ

2021-05-27 02:01 UTC, KwakTaeMin commented on src/main/java/lotto/view/LottoOutputView.java
>  	private LottoOutputView() {
아 결과 부분에서 로또 번호가 정렬이 되있었군요. 제가 놓친 부분인 것 같아요!  수정하도록 하겠습니다!

2021-05-27 03:35 UTC, hhlyn0328 commented on src/main/java/lotto/view/LottoInputView.java
> +	}
```suggestion
	public static int inputManualLottoCount() {
		System.out.println(INPUT_MANUAL_LOTTO_COUNT_MESSAGE);
		return Integer.parseInt(input.nextline());
	}
```

이처럼 숫자하나 입력후 enter 치는 곳에서는 nextInt 대신 
Integer.parseInt(scanner.nextLine()) 하시면 됩니다 

바로 parseInt를 해도 오류가 나지 않는 이유는 스캐너에서 nextLine 할 때 뒤에 개행문자는 제외하고 입력받기 때문이에요!

2021-05-27 03:36 UTC, hhlyn0328 commented on src/main/java/lotto/view/LottoInputView.java
> +		input = new Scanner(System.in);
추가 코멘트 남겼습니다  또 이해가 잘 안되시면 편하게 이야기해주세요  :)

2021-05-27 04:22 UTC, KwakTaeMin commented on src/main/java/lotto/view/LottoInputView.java
> +	}
아.. 이제 이해했어요! 친절한 답변 감사합니다!!

2021-05-28 09:45 UTC, hhlyn0328 approved these changes
리뷰 내용을 잘 반영해주셨네요 !!
리뷰드리지 않았던 부분도 고민하셔서 개선해주셔서 좋았습니다 👍 

로또 미션은 이것으로 마무리 되었네요 
고생 많이 하셨습니다, 끝까지 완주하시길 응원할게요 🔥

2021-05-28 09:45 UTC, hhlyn0328 commented on src/main/java/lotto/domain/LottoNumber.java
> +	public static LottoNumber of(final int number) {
캐싱 좋아요 👍

2021-05-28 09:45 UTC, hhlyn0328 commented on src/main/java/lotto/domain/LottoPurchaseHistory.java
> +	public void setAutoLottos(Lottos autoLottos) {
setter 사용은 지양해주세요 :)

2021-05-28 09:45 UTC, merged