3단계-로또(자동)
next-step/java-lotto pull request #1680
Opened 2021-05-26 05:33 UTC by ascii92der

아직 TDD가 익숙하지 않은 건지... 생각보다 구현에 시간이 많이 걸리네요
지난 주말에 다른 분들과 페어 프로그래밍으로 해당 단계를 진행해봤고, 일부러 그걸 까먹을 쯤에 구현을 했더니 처음 하는 것처럼 느껴지네요
물론 enum을 사용하는 힌트 같은 건 다른 분들의 말을 듣고 힌트삼아 사용해보았습니다

미션 진행 중 가장 어려웠던건...
기존과 다르게 테스트 케이스부터 구현하니까...
각각의 도메인에 대해서는 테스트 케이스라던지 코드 구현이 할만하다고 생각 되었는데
도메인과 도메인을 연결하는... 예를 들어 인풋값을 받아 Lotto 객체에 어떻게 set해주며, 그 결과를 계산하는 부분에서 필요한 데이터의 이동을 어떻게 해줘야하는지에 대해 생각보다 많이 헤맸습니다.
(기존에 짜듯이 getter setter를 쓰면 더 쉬웠겠지만....ㅠ)

미션을 진행하면서 몇가지 질문이 있습니다.

1. TDD로 하려다 보니, 테스트를 위한 메소드를 구현하는 경우가 있습니다.
예를 들어, 로또 번호가 6자리인지 확인하기 위해 size 메소드를 추가하는 등 코드 구현단에서는 사용되지 않으나, 테스트 케이스를 위해 구현되는 코드가 있고 그게 대체가 안될 경우엔 설계가 잘못된건가요? 아니면 그런 경우가 발생할 수도 있는건가요?

2. 제가 commit한 히스토리를 다 보시는지는 모르겠지만, 미션 진행 중에 LottoNumber, Lottos와 같은 클래스를 만들었다가 미션 구현에 필요하지 않거나 List의 contain 메소드를 사용할 수 없어 삭제하였는데... 이렇게 구현단계에서 만들어졌던 클래스들이 삭제되는 부분도 처음 요구사항 목록 정리(설계)에서 문제가 된 부분인지, 자주 발생하는 경우인지 모르겠습니다.

3. 구현을 하다보니 exception 처리에 대해 메시지를 constant 변수로 빼게 되는 경우가 많은데..
이럴 땐, ErrorMassge class나  Enum으로 별도의 빼는게 나은가요? 아니면 해당 도메인과 관련된 내용이므로 그냥 두는게 나을까요?

4. Lotto에서 vaild 체크를 위해 메소드를 만들어 사용하였는데... 실제로 필요한 리턴 값이 없어 void 로 만들었는데...
void로 사용해도 문제 없는지, 또 저런 valid 체크를 좀 더 깔끔하게 할 수 있는 방법이 있을까요?

쓰다보니 장문이 되었네요 ㅠㅠ

일단 PR 요청합니다.

2021-05-26 12:09 UTC, tearight requested changes
안녕하세요.
전체적으로 각각의 함수 구현이 깔끔하네요. 👍
코멘트를 남겼으니 확인 부탁드립니다~

2021-05-26 12:09 UTC, tearight commented on src/main/java/study/ascii92der/lotto/step3/LottoWinner.java
> +    int matchNumberCount;
final 이 아니면 enum 의 값이 변경될 수 있어요.
결국 상수가 아니게 되지 않을까요 ?

2021-05-26 12:09 UTC, tearight commented on src/main/java/study/ascii92der/lotto/step3/WinResult.java
> +    public WinResult() {
이 생성자가 공개됨으로써 바깥에 떠돌아 다니는 WinResult는 그 안에 값이 들어있는 것인지 아닌지 검사할 필요가 생겼어요.
단지 내부적으로 초기화를 해야하는 것이라면 private 메소드로 만들어서 사용하면 어떨까요?
이 객체를 만드는 방법이 한정됨으로써 아 항상 이 객체는 결과가 집계가 되어있구나. 생각할 수 있게 돼요.

2021-05-26 12:09 UTC, tearight commented on src/main/java/study/ascii92der/lotto/step3/InputView.java
> +    public static int inputMoney() {
LottoPrice 를 반환하도록 바꿔보면 어떨까요 ?
누군가가 이 객체를 확장하거나 흉내낼 때 항상 validation 된 값을 반환하도록 하여 다른 곳에서 검증할 필요 없게 만들 수 있어요.

2021-05-26 12:09 UTC, tearight commented on src/main/java/study/ascii92der/lotto/step3/InputView.java
> +    public static String inputWinnerNumbers() {
마찬가지로 List\<String\> 을 반환해보면 어떨까요 ?

2021-05-26 12:09 UTC, tearight commented on src/main/java/study/ascii92der/lotto/step3/LottoPrice.java
> +    private int money;
이후에는 값이 변화될 때 마다 새로운 값 객체를 만들어서 return 하도록 권장되고 있어요.

2021-05-26 15:33 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/Lotto.java
> +    public int hasNumber(int value) {
boolean 형으로 변경하였습니다.

2021-05-26 15:34 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/LottoMain.java
> +    public static void main(String[] args) {
별도의 클래스로 분리하였습니다.

2021-05-26 15:35 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/LottoMain.java
> +        }
해당 로직을 LottoGenerator 내부로 리팩토링 하였습니다.

2021-05-26 15:36 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/LottoMain.java
> +        WinResult winResult = new WinResult(lottoResults);
해당 로직도 WinResult 내부로 넣었습니다.

2021-05-26 15:37 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/LottoPrice.java
> +    private int money;
final 추가하엿습니다. 생각하고 있었는데... 누락된게 몇개 있네요 ㅠ

2021-05-26 15:37 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/LottoWinner.java
> +    int matchNumberCount;
private final을 추가하였고 getter 메소드를 만들었습니다
근데 enum의 경우 getter를 사용해도 상관이 없는 건가요?

2021-05-26 15:38 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/WinResult.java
> +    public WinResult() {
초기화 부분을 init 메소드로 분리하였고, 불필요한 기본 생성자를 제거하였습니다.

2021-05-26 15:39 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/InputView.java
> +    public static int inputMoney() {
return을 LottoPrice로 wrapping 시켰습니다.

2021-05-26 15:39 UTC, ascii92der commented on src/main/java/study/ascii92der/lotto/step3/InputView.java
> +    public static String inputWinnerNumbers() {
동일하게 return을 List<String>로 wrapping 시켰습니다.

2021-05-27 03:45 UTC, tearight commented on src/main/java/study/ascii92der/lotto/step3/LottoWinner.java
> +    int matchNumberCount;
> 

물론 객체간의 상호작용이 복잡해질 경우 일일히 값을 꺼내쓰기보다 내부적으로 결론을 도출해 낸 함수가 낫습니다.
작성하신 코드에서는 그런 경우가 없어보이네요.

2021-05-27 09:28 UTC, tearight approved these changes
변경사항 잘 확인했습니다.
머지하겠습니다.
다음 단계도 화이팅입니다!

2021-05-27 09:28 UTC, merged