Step5 - 로또 (수동) 리뷰 요청드립니다.
next-step/java-lotto pull request #1701
Opened 2021-05-27 02:13 UTC by jhh992000

드디어 마지막 5단계 미션이네요. 마지막이라니 무언가 아쉬운 기분이 듭니다.
이슬님께서 코드 한줄 한줄 세심한 코치를 해주셔서, 
TDD, 객체지향, 클린코드 작성하는 법등에 대해서 많은 배움이 있었던 시간이었던것 같습니다.
이번에도 아낌없는 피드백 부탁드리겠습니다. 감사합니다. 🙏

2021-05-27 22:32 UTC, parkeeseul requested changes
미션 잘 구현해주셨네요! 👍 
몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다!
미션 화이팅 이에요! 🔥

2021-05-28 00:19 UTC, jhh992000 commented on src/main/java/lotto/domain/PurchaseAmount.java
> +	}
아 메서드는 메서드 오버로딩을 제공해주려고 추가한건데요.
밑에 보시면 int 타입의 인자를 받는 동일한 메서드가 한개 더 있거든요.
그 메서드를 재활용하려고 했습니다.

2021-05-28 00:34 UTC, jhh992000 commented on src/main/java/lotto/domain/PurchaseLottos.java
> +	private final Lottos autoLottos;
아 수동생성된 로또번호와 자동생성된 로또번호를 따로 출력한다던지의 요구사항이 있다면 필요할것 같은데..
지금은 그런 요구사항이 없으니 필요가 없을것 같습니다.
해당 클래스는 제거했습니다.

2021-05-28 01:37 UTC, jhh992000 commented on src/main/java/lotto/domain/PurchaseAmount.java
>  	public int findNumberOfAvailablePurchases() {
단순계산식같은 경우에는 find 보다는 값의 의미로 네이밍짓는게 좋아보이네요. 👍

2021-05-28 06:16 UTC, jhh992000 commented on src/main/java/lotto/domain/Lottos.java
> +	}
수동로또와 자동로또의 정보를 가진 객체를 삭제하고 보니 필요가 없어졌네요. 해당 메서드는 제거했습니다.

2021-05-28 06:19 UTC, jhh992000 commented on src/main/java/lotto/domain/PurchaseRequest.java
> +public class PurchaseRequest {
PurchaseLottos를 왜 만들려고 했었는지 생각해보았어요.
이번에도 요구사항에 없는 기능을 고려해서 생각하다보니
수동로또와 자동로또 번호를 한곳에서 관리할수 있으면 좋겠다고 생각을 했었네요.
해당 객체를 제거하고 보니 자연스럽게 Lottos로 제거된 기능들이 이동하게 되었습니다.

2021-05-28 06:23 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumber.java
> +		return str.matches(regex);
아 그러네요. 어차피 숫자로 변환하면서 숫자가 아니면 예외가 발생하게 되어있지요.
숫자인지 여부 검증하는 로직을 구현하고 에러가 나지 않도록 처리하는 습관이 몸에 베어있는것 같습니다.
해당 메서드를 제거 조치하고 NumberFormatException 이 발생하면 예외처리를 해주도록 변경했습니다.

2021-05-28 15:22 UTC, parkeeseul requested changes
피드백 잘 반영해주셨네요! 👍 
몇 가지 추가 피드백 남겨두었으니 확인 부탁드립니다!
즐거운 토요일이네요! 즐거운 주말 되시길 바라요! 😄

2021-05-28 17:15 UTC, jhh992000 commented on src/main/java/lotto/controller/LottoGameController.java
> +		Lottos purchaseLottos = lottoGame.purchaseLottos(purchaseRequest);
해당 클래스(LottoGame)에서는 구매요청이라는 정보를 받아서 "로또구매" 라는 행위를 하는 메서드만 달랑 남게 되었는데요.
저도 이 메서드 하나 쓰자고 과연 클래스가 있어야 되는건인가... 싶기는 했습니다. 
바로 생성하는것이 간결한것같습니다. 👍

2021-05-28 17:21 UTC, jhh992000 commented on src/main/java/lotto/domain/LottoNumber.java
> +	}
헛! 중복코드가 숨어있었네요. 기가막히게 꼼꼼하십니다. 👍

2021-05-28 17:44 UTC, jhh992000 commented on src/main/java/lotto/domain/Lottos.java
> +	}
PurchaseRequest를 왜 만들었을까 다시 고민해보았습니다.
구매한 수동수량과 자동수량을 출력하기 위한 정보를 가진 객체가 필요하다고 생각을 했던것 같습니다.
해당 정보들은 그냥 입력받는부분에서 모두 가지고 있기 때문에, 곧바로 출력처리하는것이 간결한것 같네요.

2021-05-28 17:54 UTC, jhh992000 commented on src/main/java/lotto/domain/PurchaseAmount.java
> +	public int availablePurchasesQuantityMinusManualQuantity(int manualQuantity) {
해당 메서드의 네이밍을 바꿔도 될것 같지만, 

다시 생각해보니 일단 구매금액이라는 객체에서 제공하는 기능으로는 조금 어울리지 않는것 같습니다.
해당 메서드를 호출하는 부분에서 그냥 자동로또의 갯수를 구하는것이 좋은것 같습니다.

2021-05-29 07:54 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨습니다! 👍 
드디어 로또 미션을 완주하셨네요! 🎉 
너무 많은 피드백을 드린건 아닌가 하고 걱정을 했었는데
잘 반영해주셔서 정말 감사합니다.  🙇‍♀️ 
남은 미션들도 꼭 완주하셔서 많은 인사이트 얻어가시길 바라겠습니다!
고생하셨습니다! 남은 미션들도 화이팅 입니다! 🔥

2021-05-29 07:55 UTC, merged