Lotto 2nd
next-step/java-lotto pull request #1735
Opened 2021-05-30 14:45 UTC by tinyhhj

안녕하세요 이슬님
로또 4단계 리뷰요청드립니다. 

간략하게 제가 수정했던 부분들을 적어보자면
기존의 CustomNumber와 RandomNumber를 제거한뒤 LottoNumber는 단순히 번호를 지니는 객체로 사용됩니다.

LottoNumber의 생성은 LottoNumberFactory를 통해서 수행되고,
번호 생성은 Strategy를 통해서 생성하도록 변경하였습니다.

마지막 2등 구분을 위해서 WinLotto클래스를 새로 생섬하여, 보너스 매칭을 체크하도록 하였습니다.

2021-05-31 02:06 UTC, parkeeseul requested changes
미션 잘 구현해주셨습니다 ! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드려요! 😄 
즐거운 월요일 되시길 바라겠습니다 ! 화이팅 입니다! 🔥

2021-05-31 02:06 UTC, parkeeseul commented on src/main/java/lotto/domain/WinLotto.java
> +    private final LottoNumber bonusNumber;
Lotto 를 상속받으신 이유가 있으실까요? 😄 
```suggestion
public class WinLotto {
    private final LottoNumber bonusNumber;
    private final Lotto winLotto;
```

2021-05-31 17:57 UTC, tinyhhj commented on src/main/java/lotto/domain/Lotto.java
> +    }
이 부분의 경우에는 6개의 번호가 모두 생성되었는지 체크하는 부분인데요.
위 부분을 Lotto static method로 변경해서 사전에 중복 숫자를 체크하는 식으로 변경했습니다.

2021-05-31 18:09 UTC, tinyhhj commented on src/main/java/lotto/domain/Lottos.java
> +        lottos.add(new Lotto(factory));
넵 public으로 한 이유는 Lottos를 빈객체로 생성한뒤 Manager에서 수동 갯수, 랜덤 갯수 만큼 호출하는 방식은 어떨까라는
생각이 들어서 public으로 설정했습니다.

Strategy의 주입의 경우에는 CustomStrategy 생성자는 한게임(숫자 6개)씩 새로 생성하게끔 만들어뒀기 때문에,
다음 게임의 숫자를 생성하려면 새로운 CustomStrategy를 생성하도록 했습니다. 
 
한가지 이유를 더 붙이자면, 수동과 랜덤이 무작위 순서로 섞여있을 경우 stateless로 동작하기 위해서, 위와 같이 작성했는데요.

이부분에 대해서 이슬님은 어떻게 생각하시는지 궁금합니다 😄

2021-05-31 18:29 UTC, tinyhhj commented on src/main/java/lotto/domain/LottoStatics.java
>  public class LottoStatics {
맞습니다. 어차피 rankCounts를  계산해서 resultView로 표현해야하는  상황에서
Statics를 생성할때 미리 상태값으로 가지고 있도록 하는 방법으로 수정하니 코드도 더 깔끔해지네요. 👍

2021-05-31 18:33 UTC, tinyhhj commented on src/main/java/lotto/domain/WinLotto.java
> +    private final LottoNumber bonusNumber;
제 생각에 Lotto는 6숫자를  지니는 한게임의 단위로 생각을 했는데, 보너스 번호의 경우에는 당첨번호에만 해당하는 특수케이스 인것 같아서 상속으로 이용해서 구현했습니다.

이 부분에 대해서는 어떻게 생각하시는지 궁금합니다!

2021-05-31 18:34 UTC, tinyhhj commented on src/main/java/lotto/domain/RandomStrategy.java
> +    }
미리 생성해서 재사용한다는 의미를 잘 이해를 못한것 같은데, 힌트를 조금 더 주실 수 있나요?

2021-06-01 00:55 UTC, parkeeseul commented on src/main/java/lotto/domain/Lottos.java
> +        lottos.add(new Lotto(factory));
> public으로 한 이유는 Lottos를 빈객체로 생성한뒤 Manager에서 수동 갯수, 랜덤 갯수 만큼 호출하는 방식은 어떨까라는
> 생각이 들어서 public으로 설정했습니다.

-> 개인적으로는 굳이 public 으로 설정할 필요가 없다고 생각됩니다.  현재는 지불한 금액에 따라 로또를 생성하게 되는데요 만약 외부에서 addCustomLotto() 나 addRandomLotto()를 호출할 경우 추가적으로 로또가 생성되는 경우가 발생할 수 있을 것 같네요! 😄 

> Strategy의 주입의 경우에는 CustomStrategy 생성자는 한게임(숫자 6개)씩 새로 생성하게끔 만들어뒀기 때문에,
> 다음 게임의 숫자를 생성하려면 새로운 CustomStrategy를 생성하도록 했습니다.
> 한가지 이유를 더 붙이자면, 수동과 랜덤이 무작위 순서로 섞여있을 경우 stateless로 동작하기 위해서, 위와 같이 작성했는데요.
> 이부분에 대해서 이슬님은 어떻게 생각하시는지 궁금합니다 😄

-> 일단 랜덤으로 생성된 로또와 수동으로 생성된 로또의 순서가 중요할지에 대해 고민해보면 좋을 것 같아요! 순서에 상관없이 자동으로 생성할 로또와 수동으로 생성할 로또를 구분해서 생성하면 될것 같은데 어떻게 생각하시나요?
또한 다음과 같이 CustomStrategy 를 사용하지 않고 바로 Lotto를 생성할 수 있을 것 같은데 이 부분에 대해서는 어떻게 생각하시나요? 😄 
``` java
public class Lottos implements Iterable<Lotto>{
    private List<Lotto> lottos = new ArrayList<>();

    public Lottos(LottoNumberFactory factory, int money) {
        int lottoCount = money / Lotto.PRICE;
        for (int i = 0; i < lottoCount; i++) {
            this.addRandomLotto(factory);
        }
    }

    public Lottos(List<List<Integer>> lottos) {
        for( List<Integer> lotto  : lottos) {
            this.addCustomLotto(lotto);
        }
    }

    private void addCustomLotto(List<Integer> customNumbers) {
        lottos.add(new Lotto(customNumbers));
    }

    private void addRandomLotto(LottoNumberFactory factory) {
        lottos.add(new Lotto(factory));
    }
```

2021-06-01 00:57 UTC, parkeeseul commented on src/main/java/lotto/domain/WinLotto.java
> +    private final LottoNumber bonusNumber;
[이팩팀브 자바에서는 상속보다는 컴포지션을 활용하라](https://ckddn9496.tistory.com/92) 라고 이야기 하는데요
관련해서 한번 고민해보시면 좋을 것 같아요! 😄

2021-06-01 01:03 UTC, parkeeseul commented on src/main/java/lotto/domain/RandomStrategy.java
> +    }
이 부분은 제가 착각했네요! 🙇‍♀️

2021-06-01 01:12 UTC, parkeeseul requested changes
피드백 잘 반영해주셨네요! 👍 
질문주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드립니다!
다시 또 비가 내리네요! 비가 오지만 좋은 하루 되시길 바라요! 😄 
미션 화이팅 입니다 🔥

2021-06-02 14:56 UTC, tinyhhj commented on src/main/java/lotto/domain/WinLotto.java
> +    private final LottoNumber bonusNumber;
조언해주신대로 WinLotto를 컴포지션을 이용해서 수정하였습니다. 

이 부분에 대해서는 상속과 컴포지션에 대해서 의문이 살짝 남아있는데요.
제가 생각하는 상속과 컴포지션의 차이는 
1. 인스턴스 변수로 객체를 의존하는지, extends로 의존하는지
2. 다형성 이용이 가능한지
3. 구현의 변경 여부( override)
가 크게 당장은 떠오르네요.
인터넷으로 찾아보니 다음과 같은 차이점이 존재하네요[inheritance vs composition](https://www.tutorialspoint.com/difference-between-inheritance-and-composition-in-java)

저는 이부분에 대해서 아직은 걸음마 단계라서 사실 컴포지션과 상속이 나올때마다 궁금했던 부분이기도 한데요.
이슬님이 생각하시는 컴포지션의 이점과 상속과 컴포지션은 언제 활용하는게 좋을지 판단하시는 노하우를 공유해주시면 정말 감사하겠습니다:)

링크에서 언급한것처럼 is-a 관계이면 상속을 이용하고, has-a 관계이면 composition을 이용하는 방식도 잊고있었던 좋은 방법인것 같습니다.

2021-06-03 06:06 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
몇 가지 코멘트 남겨드렸으니 확인 해보시고
추가적인 변경 사항은 다음 단계에서 함께 반영 부탁드릴게요! 😄 
이제 로또 마지막 단계네요! 다음 단계 진행해주세요! 화이팅 ! 🔥

2021-06-03 06:06 UTC, merged