Step5 로또(수동) 리뷰요청입니다.
next-step/java-lotto pull request #1751
Opened 2021-06-02 19:37 UTC by cupeanimus

안녕하세요. 
몸이 조금 아프다보니 매일 코딩을 조금씩 해도 이번 단계를 마무리하는데 시간이 오래 걸렸습니다.
(몸 조심하세요)
해당 기능 개발 후, 피드백 동영상 참고하여 객체 네이밍과, 로또 번호 생성부분을 수정하였습니다.
최대한 TDD를 실천하려 하였으나, 마지막 단계에선 UI 로직과 함께 기능이 들어가, 어려움이 있었습니다.
이런 경우 어떤 식으로 테스트를 하는지 궁금합니다.
그리고,  step4에서 리뷰 요구사항에 맞춰 LottoGame 에 로직을 위치하였고, 코멘트로 실행 로직도 테스트 할 수 있다고 달아주셨는데
UI가 있어 각 부분을 테스트 할 수 없어, 할 수 있는데까지만 테스트를 하였으나 뭔가 완벽한 느낌이 들지 않아 좀 더 설명을 부탁드립니다.

조언을 들을 수 있는 마지막 단계라 아쉽지만, 이번에도 잘 부탁드립니다.
감사합니다.

2021-06-03 13:26 UTC, tearight requested changes
드디어 마지막 단계네요!
코멘트 남겼으니 확인 부탁드립니다.

2021-06-03 13:26 UTC, tearight commented on src/main/java/study/lotto/domain/Lotto.java
> +        return LOTTO_SIZE - numbers.size();
수를 구하는 과정이 직관적이어서 좋네요. 👍

2021-06-03 13:26 UTC, tearight commented on src/main/java/study/lotto/domain/LottoGame.java
>          printResult(purchaseAmount, winningResult);
이전에 이 객체의 테스트에 대해서 말씀드렸는데 제가 설명이 부족했던 것 같아요.🙂
이 객체는 TDD 와 같은 순서로 테스트를 먼저 작성하고 구현하기는 조금 애매하죠.
그럼에도 불구하고 테스트가 작성되있으면 좋겠다는 생각이 있었는데요.

이 테스트는 통합테스트이기 때문에 모듈의 통합을  실행해볼 수 있기 때문에 테스트 작성을 추천드렸어요.
함수의 입출력을 검증하는 것(단위테스트) 뿐만 아니라 각 모듈의 결합(객체간 메세지 전달)이 잘 되었는지 테스트 하는 것이기도 하죠.
내가 수정한 코드가 전체적으로 예외없이 실행이 잘 되는가를 파악할 수 있는 방법인 것 같아요.

따라서 **_아무것도 검증하지 않더라도_**, 이 테스트가 존재한다면 매번 빌드할 때마다 적어도 프로그램이 아예 실행이 안되는지 테스트가 확인해주기 때문에 유지보수에서도 이점이 있고 개발자의 불안한 마음을 해소해주기도 해요.

----

InputView, OutputView 를 주입하면 좋을 것 같다고 피드백을 드렸었는데,
직접 구현하신 InputView 는 사용자로부터 키보드 입력을 받아야만 값을 반환해주는 뷰죠.
테스트에서 이것과 동일한 타입을 주입하되 사용자로부터 키보드 입력을 받는게 아닌 바로 데이터를 리턴하는 객체를 넣어주시면
테스트 실행이 가능해질 것 같네요.
그렇다면 InputView 가 인터페이스면 같은 타입을 주입해주기 좋지 않을까요 ?

2021-06-03 13:26 UTC, tearight commented on src/main/java/study/lotto/domain/LottoGame.java
> +    public int purchaseableNumber(BigDecimal amount) {
이런 금액 계산도 값 객체를 만들어서 리팩토링을 진행할 수도 있을 것 같아요.

2021-06-03 13:26 UTC, tearight commented on src/main/java/study/lotto/domain/TotalPrize.java
> +        totalPrize = totalPrize.add(prize);
값 객체의 값은 전부 불변(final) 으로 처리하는게 어떨까요 ?

https://velog.io/@conatuseus/Java-Immutable-Object%EB%B6%88%EB%B3%80%EA%B0%9D%EC%B2%B4

2021-06-03 13:26 UTC, tearight commented on src/main/java/study/lotto/domain/LottoRank.java
> +    public static LottoRank of(int matchCount, boolean matchBonus) {
Optional 반환이 없어져서 좋네요. 👍

2021-06-03 15:34 UTC, cupeanimus commented on src/main/java/study/lotto/domain/LottoGame.java
>          printResult(purchaseAmount, winningResult);
해당 테스트를 위해 UI를 인터페이로 분리하여 각각 작성하는 것에는 충분히 그럴 가치가 있다고 보시는 의견인거군요?
처음 리뷰때 언급해주신 내용은 제가 바깥 로직으로 분리하며 필요성이 없어져서 뺏는데 
다시 한 객체에 로직을 담으면서 처음 리뷰내용을 생각 못했네요.
말씀하신대로 인터페이스로 분리하여 미리 입력값이 들어간 테스트용과 실제 입력 받을 수 있는 것 두개로 인터페이스를 상속받아 구현하였습니다. 
말씀하신 대로 제가 잘 이해했는지 몰라 추가 보완할 점이 있다면 이번에도 코멘트 부탁드립니다.
(개발 리뷰 경험이 적어 즐겁네요)

2021-06-03 15:35 UTC, cupeanimus commented on src/main/java/study/lotto/domain/LottoGame.java
> +    public int purchaseableNumber(BigDecimal amount) {
구매개수로 wrapping해보았습니다.

2021-06-03 16:36 UTC, cupeanimus commented on src/main/java/study/lotto/domain/TotalPrize.java
> +        totalPrize = totalPrize.add(prize);
이렇게 되면 add할때마다 totalPrize객체를 생성하게 되는데 비효율적인 작업이 아닌가 생각됩니다.
보기엔 조금 불편한데 리뷰 부탁드립니다.
WinningResult 내에서 totalPrize는 불변으로 수정했습니다.

2021-06-04 11:40 UTC, tearight commented on src/main/java/study/lotto/domain/TotalPrize.java
> +        totalPrize = totalPrize.add(prize);
값 객체는 장점과 단점이 있지요.
값 객체를 무조건 사용해야 하는 것은 아니지만 우테캠 과정에서는 객체지향의 극단적인 연습을 하기 위해 값 객체를 사용하는 방향으로 추천하고 있죠. 따라서 효율보다는 연습의 의미로 사용하는쪽을 지향한다 라고 인지해주시면 좋을 것 같아요.

값 객체에 대한 불편함이 느껴지는 것은 정말로 value 를 가지는 것 이외에 기능이 제공되고 있지 않기 때문인 것 같아요.
값 객체라는 개념을 뽑아낼 수 있음에도 불구하고 기능이 없다면 아직 관련 로직들이 값 객체로 모아지지 않았다로 보시면 될 것 같아요.
현재 바깥에서 BigDecimal 을 사용하는 코드가 몇몇 보이는데요, 그런 부분들을 옮겨올 수 있지 않을까요?
그리고 불편함을 느끼는 이유 두번째로는 BigDecimal 을 wrapping 하기 때문에 BigDecimal 의 함수를 제공할 수 없게 되었기 때문인 것 같습니다. wrapping 되는 객체의 기능 또한 이용하고 싶을 경우에는 상속(extend) 를 이용할 수도 있겠네요.
대신 상속을 하면 많은 내부 동작이 슈퍼클래스에 은닉되기 때문에 알 수 없는 동작이 발생할 수도 있다는 점이 있습니다. 상속할 클래스에 대해서 잘 알고 계시다면 이 부분은 큰 문제가 되지 않을 수도 있겠네요.

2021-06-04 11:48 UTC, tearight approved these changes
피드백 반영 잘해주셨습니다. 🙂
저는 이만 여기서 리뷰를 마치도록 하겠습니다. 고생하셨습니다.
값 객체에 대한 질문에 대해서 답변을 달아드렸는데요, 읽어보시고 다음 미션에서 좀 더 개선된 코드를 작성하시면 좋을 것 같습니다. 현재 코드에서 다소 부족한 부분이 있을지라도 아직 첫번째 미션이기 때문에 앞으로도 이런 연습을 할 기회가 많이 주어질거라 생각합니다. 완벽한 것도 좋지만 꾸준히 미션을 진행하셔서 다양한 상황을 느끼셨으면 좋겠네요. 
그럼 우테캠 미션을 완주하는 날까지 응원하겠습니다. 화이팅입니다 !

2021-06-04 11:50 UTC, merged

2021-06-04 11:54 UTC, tearight commented on src/main/java/study/lotto/domain/LottoGame.java
>          printResult(purchaseAmount, winningResult);
코드를 확인해보니 제가 설명드린 의도를 잘 이해하고 계신 것 같습니다.👍
이러한 구조는 꾸준히 연습을 하시면 좋을 것 같은데요, 앞으로도 몇몇 요구사항에 대해서 클래스를 먼저 구현하기보다 인터페이스로 설계할 수 있는 상황이 종종 올 것 같습니다. 그럴때 오버엔지니어링이라 생각치 마시고 연습삼아 인터페이스로 설계해보시는 것이 어떨까요 ?

2021-06-05 05:08 UTC, cupeanimus commented on src/main/java/study/lotto/domain/TotalPrize.java
> +        totalPrize = totalPrize.add(prize);
말씀하신대로 제가 크게 불편하게 생각한 이유가 감싼 값이 자료형이 아닌 BigDecimal값이라서 그런거였네요.
그리고 지금 단계가, 당장 잘 짜여진 소스를 위한게 아닌 학습하는 과정이란 것을 잘 인지하고 수행하도록 하겠습니다.

2021-06-05 05:09 UTC, cupeanimus commented on src/main/java/study/lotto/domain/LottoGame.java
>          printResult(purchaseAmount, winningResult);
네. 팀 내부에서 상속을 지양하는 분위기여서 인터페이스와 추상메서드 사용 경험이 많지 않았는데 이 과정에서는 좀 더 적극적으로 사용해봐야겠습니다. ㅎㅎ