[java-lotto] Step5 리뷰 요청드립니다.
next-step/java-lotto pull request #1759
Opened 2021-06-06 22:16 UTC by chajs226

로또게임 Stpe 5 리뷰 요청드립니다. 부족한 부분에 대해 많은 코멘트 부탁드립니다.
step5 까지 오니까, 앞서 만들었던 구조로는 답이 안나오는 것 같아서, 많은 부분에서 재설계하느라 시간이 많이 소요되었습니다.
하면서 궁금했던 점이 있어서 함께 문의드립니다. ^^;
예외 처리에 대한 부분인데, 
만약에 로또번호가 6개 미만으로 들어왔을 때 new throw로 예외를 생성시키고 끝내는게 좋은 건지, inputView 단에서 사용자에게 메시지를 보내서 다시 숫자 6개를 받을 수 있게 유도해야되는건지가 좀 애매했습니다. 지금 프로젝트는 서버단을 구현하는거라고 생각하면 예외를 throw한 것을 클라이언트 단에서 받아서 사용자 interaction을 처리한다고 가정하고, 그냥 throw 하고 끝내는 걸까요?? ㅎ 
같은 내용으로 scan.nextInt()로 값을 받았는데, 일반 문자열이 들어오는 경우도 문자가 들어오면 exception이 발생하는데, 이부분의 예외 처리를 별도로 해야 되는 건지 궁금합니다. (해당 exception은 클라이언트 단에서 처리를 하도록 둬도 되는건지..)

2021-06-07 02:50 UTC, ssosso requested changes
준성님~ 피드백 드리오니 확인부탁드립니다!
아무래도 5단계를 진행하시면서 코드가 많이 변경되어 피드백의 내용도 많아진 점 양해 부탁드립니다!

------
Q. 로또번호가 6개 미만으로 들어왔을 때 new throw로 예외를 생성시키고 끝내는게 좋은 건지, inputView 단에서 사용자에게 메시지를 보내서 다시 숫자 6개를 받을 수 있게 유도해야되는건지가 좀 애매했습니다. 지금 프로젝트는 서버단을 구현하는거라고 생각하면 예외를 throw한 것을 클라이언트 단에서 받아서 사용자 interaction을 처리한다고 가정하고, 그냥 throw 하고 끝내는 걸까요?? ㅎ
같은 내용으로 scan.nextInt()로 값을 받았는데, 일반 문자열이 들어오는 경우도 문자가 들어오면 exception이 발생하는데, 이부분의 예외 처리를 별도로 해야 되는 건지 궁금합니다. (해당 exception은 클라이언트 단에서 처리를 하도록 둬도 되는건지..)

A. 비즈니스로직을 수행하는 객체들과 inputView의 관계를 api를 제공하는 서버와 그 api를 사용하는 뷰로 생각하시면 어떨까요~? 서로 독립되어 있는 상태에서 한쪽은 기능을 제공하고 한쪽은 이를 사용하는 관계로 생각하면 좋을 거 같습니다~ 그렇게 되면, 객체에서는 예외상황에 대해서 어떻게 처리할지를 정할 때 객체 외부, 더 크게는 객체들이 협동하여 제공하는 기능 외부의 사용자를 고려하여 정하고, inputView에서는 객체입장에서 정한 예외상황 처리방식을 고려하여 다시 입력을 받게 하든 예외순간에 프로그램을 종료하든 inputView 자신이 결정하여 행동하게 하면 됩니다:)

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/common/LottoNoComparator.java
> +public class LottoNoComparator implements Comparator<LottoNo> {
Comparator를 별도로 구현하기 보다는 LottoNo가 Comparable 인터페이스를 구현하도록 하여 compare 메서드를 만들어보면 어떨까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/LottoNo.java
> +        if (lottoNo > 45 || lottoNo < 1)
LottoNo 클래스 내 상수로 45, 1을 관리하면 어떨까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/LottoNo.java
> +            throw new IllegalArgumentException(MessageCode.INVALID_LOTTO_NUMBER_RANGE.message());
Custom Exception을 만들어 MessageCode에서 message를 꺼내어 사용하지 않아도 되도록 하면 어떨까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +        }
lottoNumberRange는 static 변수인데 인스턴스 생성시 마다 초기화 되게 되어 있네요~
의도하신 부분인가요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/common/LottoNoComparator.java
> +public class LottoNoComparator implements Comparator<LottoNo> {
아하 혹시 내림차순으로 정렬하기 위해 Comparator를 사용하신걸까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/LottoNumbers.java
> +        return new LottoNumbers(numbers);
LottoNumbers입장에서는 WinningLotto를 몰라도 되지 않을까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/LottoNumbers.java
> +            lottoNumbers.add(new LottoNo(Integer.parseInt(number)));
parsing에러가 그대로 발생하지 않도록 정규식을 통해 조치하면 어떨까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/LottoNumbers.java
> +        if (lottoNumbers.size() > 6)
6이란 숫자를 상수로 Numbers가 가지고 있으면 어떨까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +        for (LottoNo lottoNo : lottoNumbers.lottoNumbers()) {
lottoNumbers로 값을 꺼내오지 않고 forEach 등의 순회 메서드를 LottoNumbers에 만들어 외부에서 사용하도록 유도하면 어떨까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +        if (containsMain(targetLottoNo.lottNo()))
lottoNo와 같이 LottoNo의 값을 외부로 꺼내지 않고 확인할 수 있는 방법이 있지 않을까요~?

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/ResultScoreEnum.java
> +                        (countOfMatch == 5 && resultScoreEnum.countOfMatch == countOfMatch && resultScoreEnum.matchBonus == matchBonus))
countOfMatch == 5 조건이 없어도 괜찮지 않을까요~?

2021-06-07 02:50 UTC, ssosso commented on src/test/java/lotto/domain/LottoNumbersListTest.java
> +
append 에 대한 테스트가 누락되어 있어요~

2021-06-07 02:50 UTC, ssosso commented on src/test/java/lotto/domain/WinningLottoNumbersTest.java
> +
외부에 열려있는 containsMain, containsBonus에 대한 테스트가 누락되어 있어요~

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/LottoGame.java
> +    public void LottoStart() {
메서드명인데 대문자로 시작하고 있어요~

2021-06-07 02:50 UTC, ssosso commented on src/main/java/lotto/domain/LottoGame.java
> +    public WinningLottoNumbers generateWinningLottoNumbers() {
public으로 열려있는데 외부에서 사용하지 않고 내부에서만 사용하고 있어요
LottoGame의 역할이 분불명한 현상과 엮여 있는거 같은데 확인 부탁드립니다~

2021-06-08 21:18 UTC, chajs226 commented on src/main/java/lotto/common/LottoNoComparator.java
> +public class LottoNoComparator implements Comparator<LottoNo> {
네~ 정렬을 위해서 사용했습니다.

2021-06-08 21:20 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNo.java
> +        if (lottoNo > 45 || lottoNo < 1)
상수로 변경했습니다.

2021-06-14 21:49 UTC, chajs226 commented on src/main/java/lotto/domain/LottoGame.java
> +    public void LottoStart() {
소문자로 변경했습니다.

2021-06-14 21:52 UTC, chajs226 commented on src/test/java/lotto/domain/WinningLottoNumbersTest.java
> +
테스트 코드 추가했습니다.

2021-06-14 21:59 UTC, chajs226 commented on src/test/java/lotto/domain/LottoNumbersListTest.java
> +
테스트 코드 추가했습니다.

2021-06-14 22:03 UTC, chajs226 commented on src/main/java/lotto/domain/ResultScoreEnum.java
> +                        (countOfMatch == 5 && resultScoreEnum.countOfMatch == countOfMatch && resultScoreEnum.matchBonus == matchBonus))
아, 그렇군요.. ^^;; 삭제했습니다.

2021-06-15 20:46 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +        }
음.. lottoNumberRange는 static으로 한번 생성되어서 메모리에 올려져 있으면 재사용 가능하겠다는 생각에 static으로 선언했던 것 같은데,, 생성자에서 객체를 계속 생성하고 있었네요;; 싱글톤 구현으로 변경해봤는데, 이 방법이 맞을까요?

2021-06-15 20:58 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNumbers.java
> +        return new LottoNumbers(numbers);
LottoNumbers를 사용하는 입장에서 WinniingLotto를 만든다는 것을 명시적으로 표현하려고 별도의 정적팩토리를 만들었습니다. 기능적으로는 generateManualOf와 동일합니다. 굳이 그렇게까지 할 필요는 없을 것 같다는 말씀이시죠? generateWinningLottoOf 는 삭제하고 generateManualOf를 사용하도록 수정했습니다.

2021-06-15 21:02 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNumbers.java
> +            lottoNumbers.add(new LottoNo(Integer.parseInt(number)));
generateWinningLottoOf 제거하면서 미사용 메소드가 되어 삭제했습니다.

2021-06-15 21:06 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNumbers.java
> +        if (lottoNumbers.size() > 6)
상수로 변경했습니다. 상수를 Constant 모아뒀는데,, Numbers 내부에 정의하는게 더 좋은 방법일까요??

2021-06-15 21:15 UTC, chajs226 commented on src/main/java/lotto/domain/LottoGame.java
> +    public WinningLottoNumbers generateWinningLottoNumbers() {
LottoGame 클래스를 중심으로 inputView, resultView, Lotto를 생성하는 클래스들과 서로 호출하고 데이터를 주고 받으면서 게임을 진행시키려는 의도였습니다. LottoGame 외부에서 호출하는 부분이 없는 메소드는 private으로 바꾸긴 했는데, 구조적인 변경이 필요하다는 말씀이실까요?

2021-06-15 21:49 UTC, chajs226 commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +        if (containsMain(targetLottoNo.lottNo()))
equals 를 통해 비교하도록 변경했습니다.

2021-06-15 22:20 UTC, chajs226 commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +        for (LottoNo lottoNo : lottoNumbers.lottoNumbers()) {
lottoNumbers.foreach((x)->increaseIfSameNumber(x, sameNumberCount)); 이와 같은 형식으로 호출하는 걸 말씀하시는건가요? 근데 메소드 리턴값을 sameNumberCount에서 가지고 있어야 되는데,, 어떻게 구현해야할지 모르겠습니다. 가이드를 좀 더 주시면 감사하겠습니다 :)

2021-06-16 12:33 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNo.java
> +            throw new IllegalArgumentException(MessageCode.INVALID_LOTTO_NUMBER_RANGE.message());
Custom Exception으로 변경했습니다.

2021-06-16 12:48 UTC, chajs226 commented
꼼꼼한 리뷰 감사합니다 :)
입력값 검증이나, 로또 번호 검증에 대한 부분이 모두 도메인 영역에서 수행되어야 되겠네요~ 제가 구현한 것처럼 InputView에서 바로 throw exception을 하면 exception을 처리하기가 좀 애매한 것 같네요.. InputView를 클라이언트로 가정을 하고 Controller 계층을 하나 둬서 거기서 throw Exception을 하도록 변경하는게 맞을까요??

2021-06-17 02:56 UTC, ssosso commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +        }
아하 현재 동시 트래픽이 들어오는 경우나 여러번 게임을 하는 경우가 없기 때문에 싱글톤으로 구현할 필요까지는 없을 것 같아요~
(그리고 만약 동시에 게임을 진행할 수 있다는 전제하에 보면, 지금 상태에서는 generateLottoNumber를 동시에 호출하게 되면 lottoNumberRange를 shuffle하는 과정에서 문제가 발생할 거 같습니다ㅠ)

2021-06-17 02:56 UTC, ssosso commented on src/main/java/lotto/domain/LottoNumbers.java
> +            lottoNumbers.add(new LottoNo(Integer.parseInt(number)));
winningLottoNumber를 받을 때 정해진 형식대로 입력하지 않으면 여전히 parsing에러가 발생할거 같아요~

2021-06-17 02:57 UTC, ssosso commented on src/main/java/lotto/domain/LottoNumbers.java
> +        if (lottoNumbers.size() > 6)
상관없다고 생각하지만.. 굳이 선택해야 한다면 외부에서 알 필요가 없는 값은 클래스 내부에 상수로 선언하는 것을 선택할 거 같습니다:)

2021-06-17 03:13 UTC, ssosso requested changes
준성님~ 변경해주신 부분 확인하고 질문주신 내용에 답글을 달아두었습니다:)
확인 부탁드립니다~

2021-06-17 03:13 UTC, ssosso commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +        for (LottoNo lottoNo : lottoNumbers.lottoNumbers()) {
네네! 결국 목표는 다음과 같은 코드가 되는 것입니다:)
```java
lottoNumbers.forEach(lottoNo -> {
    sameNumberCount = increaseIfSameNumber(lottoNo, sameNumberCount);
    isSameBonusNumber = setTrueIfSameBonusNumber(lottoNo, isSameBonusNumber);
});
```

java.lang.Iterable.forEach 메서드를 참고해 보시면 어떨까요~?

2021-06-17 03:14 UTC, ssosso commented on src/main/java/lotto/domain/LottoGame.java
> +    public WinningLottoNumbers generateWinningLottoNumbers() {
아하~ 네네 그런 의도셨군요:) public으로 열어두어 LottoController에서 lottoGame의 실행 순서를 제어하는 줄 알았어요:)

2021-06-17 09:31 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +        }
네~ 그렇군요. 기존 소스로 변경하고 static을 제거했습니다.

2021-06-17 10:15 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNumbers.java
> +            lottoNumbers.add(new LottoNo(Integer.parseInt(number)));
InputView부분에서 String을 받아서 입력 형식을 검증하도록 수정했습니다.

2021-06-17 10:16 UTC, chajs226 commented on src/main/java/lotto/domain/LottoNumbers.java
> +            lottoNumbers.add(new LottoNo(Integer.parseInt(number)));
LottoNumbers 부분은 이미 파싱된 데이터를 받고 있어서,, InputView에 검증 하는 것을 추가했는데,, 구조가 좀 잘못된 것 같네요 ㅠㅠ

2021-06-17 11:34 UTC, chajs226 commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +        for (LottoNo lottoNo : lottoNumbers.lottoNumbers()) {
foreach 문에서 자꾸 막히는데,,, 이렇게 했을 때 foreach 문 내부에서는 로컬 변수로 리턴 값을 받을 수가 없어서요. 좋은 방법이 있을까요?

2021-06-17 21:11 UTC, chajs226 commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +        for (LottoNo lottoNo : lottoNumbers.lottoNumbers()) {
Iterator 를 사용해서 리스트를 순회하는 방법으로 변경했습니다. 다만, 궁금한게 변경을 하고 보니 for문을 통해서 list 값을 꺼내는 방식이 좀 더 직관적이고 간단한 방법인것 같은데, iterator를 사용하거나 foreach를 이용하는 이유가 있을까요? 일급컬랙션의 내부 요소를 외부에서 직접 꺼내서 쓰지 않도록 하기 위함인가요?

2021-06-18 00:49 UTC, ssosso commented on src/main/java/lotto/domain/LottoNumbers.java
> +            lottoNumbers.add(new LottoNo(Integer.parseInt(number)));
아하 inputView가 담당하는 역할로 봐도 어색하지는 않을 거 같아서 저는 괜찮다고 생각합니다:)

2021-06-18 00:54 UTC, ssosso commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +        for (LottoNo lottoNo : lottoNumbers.lottoNumbers()) {
네네 맞습니다 일급 컬랙션의 내부 요소를 직접 꺼내어 쓰게 되면 외부에서 add, remove 등의 액션을 할 수 있기 때문에 말씀드렸어요~
best는 foreach의 사용인데 람다에서 지역변수를 그대로 사용하지 못하고 캡쳐하도록 되어 있어서 난관이 있었네요ㅠ

2021-06-18 00:55 UTC, ssosso approved these changes
준성님~ 수정해주신 부분 확인하고 질문주신 부분에 댓글 달았습니다:)
고생많으셨습니다:)!

2021-06-18 00:55 UTC, merged