[Step5 - 로또(수동)] 리뷰 요청드립니다.
next-step/java-lotto pull request #1774
Opened 2021-06-14 09:47 UTC by KyungSik9870

안녕하세요 리뷰어님 :)
로또의 마지막 PR 입니다. 여전히 부족한게 많아 보입니다만 제가 처음 PR을 날리기전에 기능만 동작하게 만들어보자!
하며 무턱대고 작성했던 코드보다 훨씬더 깔끔해지고 구조가 개선되었습니다.
정말 많이 배웠습니다 ㅠ

많이 알수록 표현이 간결해지면서 알아듣기 쉽게 이야기 할 수 있다고 생각하는데, 리뷰어님의 피드백이 딱 그런것같습니다!
마지막 단계에서도 열심히 피드백반영해보겠습니다!
감사합니다 👍 :)

2021-06-15 01:27 UTC, kang-hyungu requested changes
경식님 미션 구현 잘해주셨네요
몇 가지 코멘트 남겼는데 수정해보시고 리뷰 재요청주세요
궁금한 점 생기면 dm 주시거나 코멘트 남겨주세요

2021-06-15 01:27 UTC, kang-hyungu commented on src/main/java/com/nextstep/lotto/LottoMain.java
>  	public static void main(String[] args) {
main 메서드가 너무 무겁네요. 게임을 관리하는 클래스를 만들어보는게 어떨까요

프로그래밍 요구사항
함수(또는 메소드)의 길이가 15라인을 넘어가지 않도록 구현한다.

2021-06-15 01:27 UTC, kang-hyungu commented on src/main/java/com/nextstep/lotto/lotto/LottoFactory.java
> +	public Lottos createManualLottos(List<Lotto> lottos) {
이 메서드는 단순하게 Lottos 객체만 생성하고 있는데, 로또 팩토리에서 실행하도록 만들 필요가 있을까요?

2021-06-15 01:27 UTC, kang-hyungu commented on src/main/java/com/nextstep/lotto/lotto/Lottos.java
> +		for (Lotto lotto : lottos.userLottos) {
```suggestion
		this.userLottos.addAll(lottos.userLottos);
```

2021-06-15 01:27 UTC, kang-hyungu commented on src/test/java/com/nextstep/lotto/store/LottoFactoryTest.java
>  		assertThat(lottos).isNotNull();
로또 3개를 생성했으면 3개가 잘 만들어졌는지 갯수를 비교해봐야하지 않을까요?
isNotNull로 검증하면 1개나 2개가 만들어져도 통과되는데 정상 테스트라고 봐야할까요?

2021-06-15 09:25 UTC, KyungSik9870 commented on src/main/java/com/nextstep/lotto/lotto/LottoFactory.java
> +	public Lottos createManualLottos(List<Lotto> lottos) {
맞습니다. 사용자의 입력을 받아 생성만 해주면 되는부분이라 팩토리에서 제거하였습니다!

2021-06-15 09:26 UTC, KyungSik9870 commented on src/main/java/com/nextstep/lotto/LottoMain.java
>  	public static void main(String[] args) {
main 메서드가 무거워지고 있다는것은 놓치고 있었네요ㅠ LottoGame 클래스를 만들어 분리하고, LottoGame 클래스에서도 역할별로 메소드를 나누어 작성해보았습니다 :)

2021-06-15 09:27 UTC, KyungSik9870 commented on src/test/java/com/nextstep/lotto/store/LottoFactoryTest.java
>  		assertThat(lottos).isNotNull();
맞습니다. 수정하였습니다! :) 감사합니다

2021-06-16 01:25 UTC, kang-hyungu approved these changes
경식님 피드백 반영 잘 해주셨어요 👍 
코멘트 하나 남긴 것은 참고만 하세요.
pr은 머지 처리하겠습니다. 수고하셨어요!

2021-06-16 01:25 UTC, kang-hyungu commented on src/main/java/com/nextstep/lotto/LottoGame.java
> +	private final LottoInput lottoInput = new LottoInput();
LottoMain에서 객체를 주입해주는 방식으로 바꿔보면 어떨까요?
스프링에서 빈 주입해주는 것처럼요

```java
	private final LottoInput lottoInput;
	private final LottoOutput lottoOutput;
	private final LottoFactory lottoFactory;

	public LottoGame(LottoInput lottoInput, LottoOutput lottoOutput, LottoFactory lottoFactory) {
		this.lottoInput = lottoInput;
		this.lottoOutput = lottoOutput;
		this.lottoFactory = lottoFactory;
	}
```

2021-06-16 01:25 UTC, merged

2021-06-16 01:50 UTC, KyungSik9870 commented on src/main/java/com/nextstep/lotto/LottoGame.java
> +	private final LottoInput lottoInput = new LottoInput();
감사합니다! 머지해주셨지만 소스에 반영해놓겠습니다! 🙂