Step1 - 문자열 덧셈 계산기
next-step/java-lotto pull request #1807
Opened 2021-07-29 12:41 UTC by kimdonggyu-dev

안녕하세요 선동님~
이번 로또 미션 함께하게 되어서 반갑습니다 😁

step1 - 문자열 덧셈 계산기 완료했습니다.
앞으로 많은 피드백 부탁드리겠습니다.

감사합니다!!

2021-07-29 15:42 UTC, ksundong requested changes
안녕하세요. 동규님! 😊

저와 함께 로또 미션🎱 을 진행하게되어서 정말 반갑습니다!! 👏 👏 👏

미션을 열심히 노력하신 부분이 보여서 좋았습니다.
이번 단계에서는 클래스 분리에 대해서 중점적으로 연습해보시면 좋을 것 같네요!

고생하셨습니다~
확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-29 15:42 UTC, ksundong commented on src/main/java/calculators/Calculator.java
> +    private final String COLON = ":";
정규표현식은 상수로 만들어주는 편이 어떨까요?
그리고, COMMA, COLON은 상수를 의도하신 것 같은데
`static`이 빠져서 그냥 변경할 수 없는 상태가 되어버린 것 같습니다!

2021-07-29 15:42 UTC, ksundong commented on src/main/java/calculators/Calculator.java
> +                .collect(Collectors.toList());
메서드의 라인이 너무 긴 것 같은데요.
적절한 호흡으로 분리를 해보면 어떨까요?

또한, group을 나누는 것도 리터럴이 사용되고 있는데, 이것도 적절한 의미를 담아 상수로 추출해보면 어떨까 싶습니다.

2021-07-29 15:42 UTC, ksundong commented on src/main/java/calculators/Calculator.java
> +                .collect(Collectors.toList());
그리고 이렇게 split해주는 역할을 담은 클래스를 추출해보는 것도 좋을 것 같아요.
그러면 자연스럽게 `private` 메서드가 `public`으로 바뀔 것이고, 테스트가 가능해지겠죠?

2021-07-29 15:42 UTC, ksundong commented on src/main/java/calculators/Calculator.java
> +    }
validation을 담당하는 부분도 따로 나눠보면 어떨까요?
제일 좋은건 숫자 자체를 포장하는 클래스를 만들어서 생성시에 예외가 발생하는 것이라고 생각됩니다~

2021-07-29 15:42 UTC, ksundong commented on src/main/java/calculators/Calculator.java
> +    }
예외를 이용해서 로직을 만들어내기 보다는
그냥 예외가 발생하도록 두는것도 나쁘지 않다는 생각이듭니다.
이건 제가 프로그래밍하는 방식이라서 강요하고 싶지는 않아요~

2021-07-29 15:42 UTC, ksundong commented on src/test/java/calculators/CalculatorTest.java
> +        int sum = c.calculate(input);
단위테스트에서도 의미있는 이름을 사용해주세요.

2021-07-29 15:42 UTC, ksundong commented on src/test/java/calculators/CalculatorTest.java
> +        int sum = c.calculate(input);
Calculator는 여러군데에서 초기화가 되고 있는데, `@BeforeEach`를 이용해보는게 어떨까요?

2021-07-30 13:12 UTC, kimdonggyu-dev commented on src/main/java/calculators/Calculator.java
> +    private final String COLON = ":";
https://zorba91.tistory.com/275

말씀해주신 부분 참고하여 위 글 참고하였습니다. 
감사합니다 😄

2021-07-30 13:12 UTC, kimdonggyu-dev commented on src/main/java/calculators/Calculator.java
> +                .collect(Collectors.toList());
말씀하신 부분을 생각해보니, Calculator에는 단순히 계산하는 책임만 주고 Input을 받아 Number를 구하는 클래스를 만들어주면 될거같아서 클래스로 추출해봤습니다 

감사합니다.

2021-07-30 13:12 UTC, kimdonggyu-dev commented on src/main/java/calculators/Calculator.java
> +    }
처음에 InputValidator 라는 클래스로 빼려다가 public static으로 제공하자니 유틸성 성격이 커져 God class 가 될거같았고,
또한 Calculator와의 결합도가 생길거같았어요. 그래서 말씀하신부분 참고하여 value object로 빼게되니 저러한 로직을 다 없앨 수 있었네요.

감사합니다

2021-07-30 13:14 UTC, kimdonggyu-dev commented
@ksundong 

안녕하세요 선동님~
어제 밤에 피드백을 주셨는데 슬랙알림이랑 메일이 안왔더라구요 🤔

그래서 뒤늦게 확인해서 피드백 반영완료했습니다.

클래스 분리를 중점적으로 생각해볼 수 있어서 좋았던거 같아요.
이번 로또미션에서도 집중해봐야겠어요.

그리고 클래스간에 테스트코드가 좀 중복되는게 많은거같아요.
그래도 다 작성하는게 좋을거같아서 다 작성해봤습니다.

드디어 주말이네요!!
즐거운 주말 보내시길 바라겠습니다.
감사합니다 🙏🏻

2021-07-31 04:13 UTC, ksundong approved these changes
안녕하세요. 동규님! 😊
헉, 알림이 가지 않았었군요! 저는 어제 리뷰를 남긴줄 알았는데, 리뷰를 안남기고 잠이 들어버렸네요. 😅

피드백 열심히 반영해주셨네요.
클래스 분리는 어떻게보면 우리가 Java라는 클래스기반 객체지향 언어를 사용하는데 있어서 중요한 부분이라고 생각됩니다.
이번 로또미션에서도 도전해보시면 좋을 것 같아보입니다.

테스트 코드의 중복은 클래스가 변경하기 힘들어지지 않는 이상 리팩토링시에 도움을 주기 때문에 충실히 만들어두는게 좋다고 생각합니다.
그런 면에서 정말 잘 해주신 것 같아요.

고생하셨습니다~ 피드백 확인해주시고, 다음단계에서 뵙겠습니다!
즐거운 주말 잘 보내세요!!

궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-07-31 04:13 UTC, ksundong commented on src/main/java/calculators/Calculator.java
> +    }
이렇게 필요한 의존성을 직접 생성하는 것은 가급적이면 지양해주는게 좋습니다.
보통은 의존성 주입을 통해서 구현하는 것이 객체지향 설계에서 중요한 부분입니다.

2021-07-31 04:13 UTC, ksundong commented on src/main/java/calculators/Calculator.java
> +        List<Number> numbers = numberGenerator.getNumbers(input);
`get`이라는 이름보다는 다른 이름이 좋지 않았을까 하는 생각이드네요.
더 좋은 이름을 고민해보시면 좋지 않았을까? 하는 생각이듭니다.

2021-07-31 04:13 UTC, ksundong commented on src/main/java/calculators/NumberGenerator.java
> +    private static final String REGEX = "//(.)\n(.*)";
어떤 REGEX인가요? 네이밍이 좀 더 구체적이면 좋을 것 같습니다.

2021-07-31 04:13 UTC, ksundong commented on src/main/java/calculators/NumberGenerator.java
> +    private static final int SECOND_GROUP_INDEX = 2;
이 상수명을 보고, 의도를 파악할 수 있을까요? 이건 그냥 상수화만 시켜준 형태여서, 코드를 읽는 사람에게 어떠한 정보도 제공해주기 힘들 것 같습니다.

2021-07-31 04:13 UTC, ksundong commented on src/main/java/calculators/NumberGenerator.java
> +                .collect(Collectors.toList());
메서드가 너무 길지 않나요?
적절하게 분리를 해보면 좋을 것 같습니다.

힌트는 빈 줄이 바로 메서드 분리의 포인트가 된다는 것입니다.

2021-07-31 04:13 UTC, ksundong commented on src/main/java/calculators/vo/Number.java
> +        }
각각을 `CustomException`을 만들어주는 것은 어떨까요?
`RuntimeException`은 포괄적인 예외기 때문에, 코드에서는 둘이 같은 종류의 예외로 처리될 것 같습니다.

2021-07-31 04:13 UTC, ksundong commented on src/test/java/calculators/NumberTest.java
> +    }
정상 생성은 정상적으로 생성되었을 때, 해당 객체가 정상적으로 생성되었음을 검증하는 로직을 두는 것이 맞지 않을까요?
단순히 예외만 발생하지 않는다고, 해당 객체가 사용할 수 있는 상태임을 보장할 수는 없지 않을까요?

2021-07-31 04:13 UTC, merged