[2단계 - 로또(자동)] 리뷰 요청드립니다.
next-step/java-lotto pull request #1809
Opened 2021-07-29 14:47 UTC by seondongpyo

안녕하세요, 준호님 👋
2단계 로또(자동) 구현한 코드 리뷰를 부탁드립니다.

코드 양이 이전 미션에서 작성하던 것보다 많아서 진이 빠질 정도네요;; 😵
최대한 객체를 나누고 메시지를 보내 처리하도록 해보려고 했는데 잘됐으려나 모르겠습니다. 😅
그래도 테스트 코드를 먼저 작성하니, 추후에 잦은 리팩토링을 하더라도 
테스트 코드가 로직이 정상적으로 동작하는지를 보장해주기 때문에 확실히 리팩토링에 대한 자신감이 생겼습니다.

궁금한 점이 하나 있는데 질문 드립니다.
Q. 로또 번호의 중복을 제거하기 위해 현재 코드에서는 `stream`의 `distinct()`를 사용했는데,
`new ArrayList<>(new LinkedHashSet<>('로또 번호 리스트'))`로도 중복을 제거할 수 있지 않을까 생각합니다.
제가 아직 자바에 대한 실력이 부족하여 어떤 로직이 더 나은지 몰라 준호님의 의견을 듣고 싶습니다.
혹시 더 좋은 방법이 있다면 추천해주시면 감사드리겠습니다.

부족하거나 개선해야 할 부분 있으면 날카로운 피드백 부탁드리겠습니다. 감사합니다. 🙏

2021-07-30 11:02 UTC, JunHoPark93 requested changes
안녕하세요 선동님!
로또 2단계 잘 구현해주셨어요!
메서드 분리도 잘되어있고 테스트도 꼼꼼히 잘 작성해주셨네요 👍 전체적으로 읽기 좋았습니다.
질문주신 부분과 간단한 피드백 몇가지 남겼는데요, 잘해주셔서 금방 보실 수 있을거에요~

2021-07-30 11:26 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoTicket.java
> +	private final List<LottoNumber> lottoNumbers;
최근에 리팩토링하면서 실수해버렸군요. 😅 확인 감사합니다.

2021-07-30 11:26 UTC, seondongpyo commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +			throw new InvalidLottoNumberSizeException();
저번 단계에선 잘 처리해놓고 이번엔 놓쳤네요 ㅎㅎ

2021-07-30 11:33 UTC, seondongpyo commented on src/test/java/lotto/domain/LottoPrizesTest.java
> +	private static Stream<Arguments> earningsRateArguments() {
> 쓰이지 않는것 같네요

37라인 총 수익률을 계산하는 테스트에서 매개변수 전달용으로 생성했는데 확인 부탁드릴게요

2021-07-30 11:38 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoPrize.java
> +	ALL_NUMBERS(6, 2_000_000_000);
'꽝'이라는 enum 값을 지정해서 처리하는 게 더 깔끔해보일 것 같네요. 좋은 의견 감사합니다. 😄

2021-07-31 05:05 UTC, JunHoPark93 approved these changes
안녕하세요 선동님~
리뷰반영 잘 해주셨어요!
3단계 바로 진행해주셔도 될 것 같네요 👍
의견 나누고싶은 부분 또 생기면 언제든 말씀주세요~ 고생하셨습니다!

2021-07-31 05:05 UTC, JunHoPark93 commented on src/main/java/lotto/domain/WinningLottoNumbers.java
> +		return Collections.unmodifiableList(winningNumbers);
👍

2021-07-31 05:05 UTC, JunHoPark93 commented on src/main/java/lotto/domain/LottoPrize.java
> +				.orElse(LottoPrize.NONE);
훨씬 좋아진거같습니다 :)

2021-07-31 05:05 UTC, JunHoPark93 commented on src/main/java/lotto/view/ResultView.java
> +			.filter(lottoPrize -> lottoPrize != LottoPrize.NONE)
isNone()같은 메서드를 정의해서 객체에 메세지를 보내봐도 좋겠네요 :)

2021-07-31 05:05 UTC, merged