2단계 - 로또(자동)
next-step/java-lotto pull request #1827
Opened 2021-08-01 05:07 UTC by giwankim

리팩토링하다 힘들어서 혼자 끙끙대는 것보다 코드 리뷰 한 번 받고 새로운 관점을 DI 받으려 합니다. 😄

2021-08-02 01:00 UTC, JunilHwang requested changes
안녕하세요 기완님! 로또 미션 잘 진행해주셨네요 👍
미션 초반임에도 불구하고 설계를 무척 잘 해주셨어요!
다만 몇 가지 고민할 부분이 있어서 리뷰 남겼으니 확인 후 다시 피드백 요청 부탁드려요!

2021-08-02 12:40 UTC, giwankim commented on src/main/java/lotto/utils/RandomUtils.java
> +}
아, 사용 안하는데 있었군요. 근데, [Guide to ThreadLocalRandom in Java](https://www.baeldung.com/java-thread-local-random#implementation-details) 쓰레드마다 정적 변수로 Random을 갖고 있다고 하는데, 그러면 방어적 복사를 하지 않아도 괜잖은 것인가요? "생성자 방어 로직"이라면 적절한 예외 처리 말씀이신가요? 그건 그냥 기본적인 IllegalArgumentException 으로 하지 하고 넘어갔어어요.

2021-08-02 13:42 UTC, giwankim commented on src/main/java/lotto/domain/model/LottoTicket.java
> +    }
그렇군요. String 으로부터 생성하는 팩토리 메서드가 더해지니 여기저기 간결해지는 부분이 많군요...

2021-08-03 11:11 UTC, JunilHwang commented on src/main/java/lotto/utils/RandomUtils.java
> +}
아예 RandomUtils가 사용되고 있진 않지만, 일단 설명드리자면
이 클래스의 메소드는 nextInt 하나 뿐이며, 정적메소드입니다.
즉, 인스턴스를 만들어서 사용하는 메소드가 없는 상태입니다.
그래서 인스턴스를 아예 생성되지 않도록
```java
private RandomUtils() {}
```
생성자를 private으로 지정하는 것을 `생성자 방어`라고 한답니다!

2021-08-03 11:17 UTC, JunilHwang approved these changes
안녕하세요 기완님! 피드백 반영 잘 해주셨네요 👍 
이번 단계는 여기서 마무리하겠습니다. 바로 다음 단계 진행해주세요!
그리고 질문에 대한 답변은 해당 코멘트에 남겨놨습니다.

2021-08-03 11:17 UTC, JunilHwang commented on src/main/java/lotto/controller/LottoController.java
> +            LottoMoney lottoMoney) {
개행이 어색한 것 같아요.
차라리 이렇게 표현해보면 어떨까요?
```suggestion
    private LottoController(
        LottoTickets userTickets,
        LottoTicket winningTicket,
        LottoMoney lottoMoney
    ) {
```

2021-08-03 11:17 UTC, JunilHwang commented on src/main/java/lotto/utils/RandomUtils.java
> +}
사용되고 있는 클래스가 아니기 때문에 아예 제거해주세요

2021-08-03 11:17 UTC, merged