Step2 - 로또(자동)
next-step/java-lotto pull request #1831
Opened 2021-08-01 13:38 UTC by SeoYoungDuk

안녕하십니까 현수님~ 서영덕입니다 ㅎㅎ

Step1 리뷰도 저에게 많은 도움이 됬고, 많은 공부가 됬습니다.

Step2 리뷰도 잘 부탁 드리겠습니다.

항상 고생 많으십니다!

감사합니다.

2021-08-01 15:24 UTC, hyunssooo requested changes
안녕하세요 영덕님 🙂
주말간 미션 진행하신다고 수고 많으셨습니다! 
몇 가지 코멘트 남겼어요. 확인 부탁드립니다! 
궁금하시거나 고민중이신 부분이 있다면 언제든 편하게 DM이나 코멘트 남겨주세요! 
미션 진행하면서 함께 고민하는 시간을 가지면 좋을 것 같아요 :)

2021-08-01 15:24 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoNumberTests.java
> +    }
생성에 대한 테스트는 생성시 아무 문제가 없음을 검증하는 테스트가 아닐까요? 
테스트할때 내부 필드 값을 검증할 필요가 있을까요? 
toString() 을 이용해 문자열이 같은지 검사하는 것이 이 테스트의 목적은 아닐 것 같아요.

2021-08-01 15:24 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoMachineTests.java
> +    }
🤔

2021-08-01 15:24 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoNumbers.java
> +        return matchingRecords;
배열을 사용할 필요가 있을까요? 배열은 리스트보다 다루기 힘듭니다. List, Set, Map 같은 컬렉션이랑 친해져봐요 :) 
또한, count를 가지고 있는 로또 결과를 나타내는 클래스를 작성해보는 것은 어떨까요? 힌트는 Enum 입니다 :)

2021-08-01 15:24 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
> else 예약어를 쓰지 않는다.

자연스럽게 없어지겠지만 프로그래밍 요구사항을 지켜주세요 :)

2021-08-01 15:24 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoMachine.java
> +    }
사용하는 메서드인가요?

2021-08-01 15:24 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoMachine.java
> +
LottoMachine 필드에 lottoNumber를 가지고 있는 이유가 따로 있나요?

2021-08-01 15:24 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoMachine.java
> +
접근제어자가 디폴트가 맞을까요?

2021-08-01 15:24 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoMachine.java
> +    }
없어질 구조지만 배열의 인덱스가 뭘 의미할까요? 가독성을 높이는 방법은 없을까요? 
5000, 50000, ... 은 뭘 의미할까요? 
코드를 작성할 때 가독성을 높이는 것은 매우 중요합니다.

2021-08-02 13:27 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumber.java
> +    private List<Integer> pickedNumbers;
네!  6개를 숫자를 가진 LottoNumber 말고 한개의 int형 변수를 갖는 객체로 만들어 보겠습니다 ㅎㅎ

2021-08-02 13:45 UTC, SeoYoungDuk commented on src/test/java/lotto/domain/LottoNumberTests.java
> +    }
네 생성시 생성이 제대로 되는지만 검증하는 테스트로 변경 하는게 목적이 맞는것 같습니다. 그렇게 수정해 보도록 하겠습니다!

2021-08-02 13:47 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final int COUNT_OF_PICK = 6;
네 컨벤션에 따라 모두 순서를 바꿨습니다 ! 감사합니다 :)

2021-08-02 13:48 UTC, SeoYoungDuk commented on src/test/java/lotto/domain/LottoMachineTests.java
> +    }
이 부분은 제거 했습니다! ㅎㅎ

2021-08-02 13:49 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoMachine.java
> +    }
사용 하지 않는 메서드는 모두 제거하겠습니다 ㅎㅎ

2021-08-02 13:49 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoMachine.java
> +
final을 빼먹었네요 ㅎㅎ 수정하였습니다!

2021-08-02 15:39 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoMachine.java
> +
재 설계 하면서 다시 생각해보니 필요 없는 부분이어서 , 이 부분은 삭제 했습니다!

2021-08-02 15:53 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
Set 자료구조를 을 사용 하면 될 것 같습니다 ! 
사이즈가 10인 경우, 중복인 경우에 대한 테스트도 작성 하였습니다 ㅎㅎ
확인 부탁 드리겠습니다 :)

2021-08-03 08:29 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoMachine.java
> +    }
관련 내용은 Enum 사용 하면서 상수 처리 해버렸습니다. 감사합니다.

2021-08-03 08:29 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
관련 내용은 Enum 사용 하면서 제거 했습니다 ㅎㅎ

2021-08-03 11:30 UTC, hyunssooo approved these changes
안녕하세요 영덕님 🙂
정말 많이 고민하신거 같습니다! 👍
몇 가지 추가 코멘트 남겼습니다! 
다음 스텝 진행하시면서 새로운 요구사항 구현전에 확인 해보시면 좋을 것 같아요 🙂
다음 pr도 기다리고 있겠습니다!

2021-08-03 11:30 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoResult.java
> +    private LottoResult(Set<LottoNumbers> totalLottoNumbers, LottoNumbers winningLottoNumbers) {
`Set<LottoNumbers>` 를 일급컬렉션으로 만든다면 winningLottoNumbers와의 결과라는 책임을 가질 수 있지 않을까요?

2021-08-03 11:30 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoResult.java
> +    }
`Collections.unmodifiableMap()`에 대해 학습해보는 것은 어떨까요?

2021-08-03 11:30 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoNumberTests.java
> +
공백도 의미있게 사용하면 좋을 것 같아요 :)

2021-08-03 11:30 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoNumberTests.java
> +
추가로 엣지케이스인 0도 테스트 해보는 것은 어떨까요?

2021-08-03 11:30 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoNumbersTests.java
> +//    }
주석은 지우는 것은 어떨까요?

2021-08-03 11:30 UTC, hyunssooo commented on src/main/java/lotto/LottoRankEnum.java
> +public enum LottoRankEnum {
클래스명에 Enum은 빠져도 괜찮을 것 같아요 :)

2021-08-03 11:30 UTC, hyunssooo commented on src/main/java/lotto/LottoRankEnum.java
> +    }
Enum은 생성자를 디폴트로 하시면 됩니다 :)

2021-08-03 11:30 UTC, hyunssooo commented on src/main/java/lotto/LottoRankEnum.java
> +    }
0, 1, 2 인 경우는 예외가 맞을까요? 
1등 - 6
2등 - 5, 보너스 넘버 
3등 - 5
4등 - 4
5등 - 3 
등수 밖 3개 이하

3개 이하인 경우의 객체도 만드는 것은 어떨까요? 그럼 따로 예외처리를 하지 않아도 괜찮을 것 같아요 :)

2021-08-03 11:30 UTC, hyunssooo commented on src/main/java/lotto/LottoRankEnum.java
> +    ALL_MATCH(6, 2000000000);
금액 부분을 언더바를 사용하시면 가독성을 높일 수 있습니다!
`2_000_000_000`

2021-08-03 11:30 UTC, hyunssooo commented on src/main/java/lotto/LottoApplication.java
> +        }
중복된 LottoNumbers 같은 경우 요구사항은 아니였는데 구현하신 이유가 따로 있을까요? 
이 경우라면 1등은 1장만 당첨 가능하겠네요!

2021-08-03 11:30 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoMachine.java
> +
렌덤은 테스트하기 어려운 영역입니다. 이번 미션에서도 테스트하기 어려운 부분은 최대한 분리 해보는 것은 어떨까요? 
수동 구매가 들어간다면 해당 부분은 수정이 필요해보여요.
바로 반영하시지 마시고 수동 구매 요구사항까지 고민해보면 좋을 것 같습니다!

2021-08-03 11:30 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoNumbersTests.java
> +
`contains()`, `getMatchCount()` 같은 메서드도 테스트가 필요해 보이네요.

2021-08-03 11:31 UTC, merged

2021-08-03 13:58 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
넵 수정했습니다 ㅎㅎ

2021-08-03 14:23 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
네 private 처리 했습니다!

2021-08-03 14:25 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final int MAX_LOTTO_NUMBER = 45;
effective java에서 나오는 아이템1. 생성자 대신 정적 팩터리 메서드를 고려하라. 
에서 나오는 인스턴스 통제 클래스를 참고 하여 적용 하였습니다 :)

인스턴스 통제(instance-controlled) 클래스는 싱글턴과 같이 인스턴스를 1개 혹은 N개로 제어하고 있는 클래스를 말한다.
ex. public static Boolean valueOf(boolean b) { return b ? Boolean.TRUE : Boolean.FALSE; }

2021-08-03 14:27 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
넵 인터 페이스를 사용해서 다형성을 이용하도록 노력하겠습니다 ㅎㅎ

2021-08-03 14:50 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoResult.java
> +    private LottoResult(Set<LottoNumbers> totalLottoNumbers, LottoNumbers winningLottoNumbers) {
네 set<LottoNumbers> 도 일급 컬렉션으로 만드는게 좋 을것 같습니다!!

2021-08-03 15:14 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoResult.java
> +    }
아래와 같은 경우에 사용하네요!! ㅎㅎ 

- Map이나 List의 변수의 내용을 "읽기"만 하고 싶을때 , 변경하지 않을 때 사용합니다
  즉, read-only 한 객체를 만들고 싶은 경우인데 이럴 때 다음의 메소드를 사용하면 좋을 것 같다.
  Collections.unmodifiableMap
  Collections.unmodifiableList
  해당 메소드는 파라미터로 전달 받은 컬렉션 객체에 어떠한 변경이라도 발생하면 예외를 return한다.

**저는 아래와 같이 View 에서 getter 를 사용 해야 할 때  readonly 한 객체로 return 하여 적용 해 보았습니다!

public Map<LottoRankEnum, Integer> getLottoResult() {
        return Collections.unmodifiableMap(lottoResult);
}**

2021-08-03 15:18 UTC, SeoYoungDuk commented on src/test/java/lotto/domain/LottoNumberTests.java
> +
앗 공백이!! 수정하였습니다 ㅎㅎ 그리고 엣지케이스도 구현 했습니다! 감사합니다~

2021-08-03 15:20 UTC, SeoYoungDuk commented on src/main/java/lotto/LottoRankEnum.java
> +public enum LottoRankEnum {
넵 좋은 것 같습니다 ㅎㅎ

2021-08-03 15:44 UTC, SeoYoungDuk commented on src/main/java/lotto/LottoRankEnum.java
> +    }
OUT_OF_RANK 라는 객체를 만들어서 예외처리 하지않고 등수 밖의 경우를 처리 하는 것으로 바꿨습니다! ㅎㅎ

2021-08-03 15:46 UTC, SeoYoungDuk commented on src/main/java/lotto/LottoApplication.java
> +        }
음 .. 그렇네요 ! 1등이 여러명 나올 수도 있겠네요!! 잘못 생각 하고 있던 것 같습니다!
해당 부분은 제거하는게 좋겠네요 ㅎㅎ

2021-08-03 15:50 UTC, SeoYoungDuk commented on src/test/java/lotto/domain/LottoNumbersTests.java
> +
해당하는 테스트들도 구현 하였습니다 !! ㅎㅎ

2021-08-04 08:23 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoMachine.java
> +
네 해당 내용은 고민 한번 해보겠습니다 !! 감사합니다 ㅎㅎ

2021-08-04 08:58 UTC, SeoYoungDuk commented on src/main/java/lotto/LottoRankEnum.java
> +    }
앞에 private를 제거하라는 말씀이시죠 ??

2021-08-04 09:05 UTC, hyunssooo commented on src/main/java/lotto/LottoRankEnum.java
> +    }
넵넵 enum의 생성자는 디폴트로 두시면 됩니다!
인텔리제이에서 지우라고 제안할 것 같아요 🙂

2021-08-04 11:23 UTC, SeoYoungDuk commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
넵 기본 toString은 IntelliJ가 만들어 준것을 이용하고, view 에서는 getter를 이용하는 것으로 변경 했습니다.