[step1] 문자열 덧셈 계산기
next-step/java-lotto pull request #1847
Opened 2021-08-03 15:11 UTC by iiaii

안녕하세요 요한님!
이번 로또 - TDD 과제 리뷰 잘 부탁드립니다~

2021-08-03 16:18 UTC, bass84 requested changes
정헌님 안녕하세요~! 
이번 단계에서 함께 하게 될 박요한이라고 합니다.
몸풀기인데 많은 정성을 들여서 작성하셨네요.
몇몇 부분은 Object로 구현했어야 했을까 하는 부분도 있지만,
그만큼 많은 고민을 하고 무엇이든 객체로 접근하려고 하는 태도는 좋다고 생각합니다! 👍 👍 👍 

코멘트 남긴 것 확인해보시고 수정 후 PR 다시 주세요.
얼른 2단계로 넘어가시죠!^^
화이팅입니다!!

2021-08-03 16:18 UTC, bass84 commented on src/main/java/adder/Expression.java
> +public class Expression {
equals와 hashcode를 오버라이딩 하신 이유가 있을까요?

2021-08-03 16:18 UTC, bass84 commented on src/main/java/adder/PositiveNumber.java
> +public class PositiveNumber {
equals와 hashcode를 오버라이딩 하신 이유가 있을까요?

2021-08-03 16:18 UTC, bass84 commented on src/main/java/adder/StringAdder.java
> +        return CustomTokenizeStrategy.containCustomDelimiter(expression)
이 수행 내용을 구현체인 CustomTokenizeStrategy에서 하기 보다는 Factory를 만들어 처리하는 게 더 좋을 것 같네요.
1. 만약 구현체들이 더 많아진다면 여기 구현 내용들이 더 추가된다는 점이 
2. 구현체 중에 CustomTokenizeStrategy에 했는지도 기준점이 없다는 점

이 두가지의 이유로 그렇습니다. 
만약 Factory를 사용 안한다면 상위 인터페이스인 TokenizeStrategy에서 하는 게 좀 더 맞는 것 같네요.

2021-08-03 16:18 UTC, bass84 commented on src/main/java/adder/TokenizeStrategy.java
> +public interface TokenizeStrategy {
구분자 값에 따라서 처리하도록 인터페이스를 사용하신 점은 좋은 접근 방법이라고 생각됩니다! 👍 👍 👍

2021-08-04 14:40 UTC, bass84 commented on src/main/java/adder/Expression.java
> +public class Expression {
현재 비교하는 상황이 없는데 구현하는 것은 다소 오버 엔지니어링적인 측면은 있습니다만,
그런 의미에서라면 잘 구현하신 것 같습니다.^^

2021-08-04 14:56 UTC, bass84 approved these changes
정헌님 수고하셨어요!
간단한 코멘트 남겼는데 해당 사항은 2단계 때 반영해서 올려주셔도 될 것 같습니다.^^

그럼 2단계 고고하시죠!!! 🔥 🔥 🔥

2021-08-04 14:56 UTC, bass84 commented on src/main/java/adder/CustomTokenizeStrategy.java
> +    private List<String> getExpressionAndSplit(Matcher matcher) {
메서드명이 `getExpression~`이면 Expression 객체를 가져올 것을 기대하는데 String이네요.
`getSplitedExpressions`이라고 하면 클라이언트에게 조금 더 이해가 쉬울 것 같아요.

2021-08-04 14:56 UTC, bass84 commented on src/main/java/adder/CustomTokenizeStrategy.java
> +        return getExpressionAndSplit(expression.getMatchers(DELIMITER_PATTERN));
바로 다른 메서드를 호출하는데 이렇게 나눌 필요는 없어 보이긴 하는데 다소 취향 차이라서 연급 드릴까 말까 했다가 참고 사항으로 말씀드립니다.ㅎㅎ

2021-08-04 14:56 UTC, bass84 commented on src/main/java/adder/StringAdder.java
> +    public List<PositiveNumber> getPositiveNumbers(Expression expression) {
요 메서드는 이 클래스 내부에서만 사용하는데 private으로 변경하는 게 좋겠네요. 앞 리뷰 때 언급 드린다는 걸 빠뜨렸습니다.ㅎ

2021-08-04 14:56 UTC, bass84 commented on src/main/java/adder/TokenizeStrategyFactory.java
> +public class TokenizeStrategyFactory {
결국 Factory 구현을 하셨군요!
귀찮은 작업이었을텐데 이런 태도는 보기 좋습니다!^^

2021-08-04 14:57 UTC, merged

2021-08-04 15:26 UTC, iiaii commented on src/main/java/adder/CustomTokenizeStrategy.java
> +    private List<String> getExpressionAndSplit(Matcher matcher) {
보다 명확한 네이밍인 것 같네요 👍  리뷰 반영했습니다!

2021-08-04 15:26 UTC, iiaii commented on src/main/java/adder/StringAdder.java
> +    public List<PositiveNumber> getPositiveNumbers(Expression expression) {
미처확인하지 못했네요 😅  리뷰 반영했습니다!