🚀 4단계 - 로또(수동)
next-step/java-lotto pull request #1848
Opened 2021-08-03 15:27 UTC by Hae-gun

4단계 시작

2021-08-04 01:32 UTC, Hae-gun commented
해당이 Comment 아래 커밋부터 봐주시면 될 것 같습니다.

2021-08-04 07:37 UTC, Hae-gun commented on src/test/java/lotto/domain/LottoTest.java
> +        );
숫자를 LottoNum 으로 포장하면서 해당 Test를 수정하게 되었는데요.. 해당 테스트가 애초에 숫자를 LottoNum으로 바꾸어도 수정없이 테스트가 수행할수 있게 설계할수 있는 방법이 있을까요?

2021-08-06 03:07 UTC, jaeyeonling requested changes
로또 수동 미션도 잘 구현해주셨습니다 👍 
추가적인 코멘트와 질문의 답변 남겨두었으니 확인 부탁드려요!

2021-08-06 03:07 UTC, jaeyeonling commented on src/test/java/app/domain/LottoTest.java
> +        );
```java
        assertThat(lotto.getNumbers()).containsExactlyElementsOf(
                List.of(1, 3, 4, 5, 8, 9)
                        .map(LottoNum::of)
                        .collect(toList())
        );
```

https://github.com/next-step/java-lotto/pull/1848#discussion_r682365432의 답변을 드리자면!
와 같은 방법으로 테스트해볼 수 있을 것 같은데, 의도하신 내용이 맞는지 모르겠네요 T.T 
핵심은 정렬이 됐는지 확인하는 것이기 떄문에 값에 대한 결과를 검증하는 것 보다 정렬이 됐는지 확인하는 것이기 떄문에 

```java
        assertThat(lotto.getNumbers()).isSorted();
``` 

와 같이 검증해볼 수도 있을 것 같습니다 ㅎㅎ

2021-08-10 08:30 UTC, jaeyeonling requested changes
코멘트 잘 반영해주셨습니다!
추가 코멘트 남겨두었으니 확인 부탁드려요~

2021-08-10 08:30 UTC, jaeyeonling commented on src/main/java/app/domain/Money.java
> +    }
getCount라는 이름으로 해당 기능을 설명할 수 있을까요!?

2021-08-10 08:30 UTC, jaeyeonling commented on src/main/java/app/domain/lotto/Lotto.java
> +    public int matchLotto(List<LottoNum> winnerNumberList) {
```suggestion
    public int matchLotto(List<LottoNum> winnerNumbers) {
```

List와 같은 자료형을 변수명으로 사용하면 어떠한 단점이 있을지 고민해보아요

2021-08-10 08:30 UTC, jaeyeonling commented on src/main/java/app/strategy/LottoMatcher.java
>          if (myLotto.getNumbers().contains(bonus)) {
해당 기능도 getter 없이 메시지로 전달이 가능할 것 같습니다!
전체적으로 비즈니스 로직을 getter로 가져와 처리하는 부분을 리팩토링해보아요

2021-08-10 08:30 UTC, jaeyeonling commented on src/main/java/app/domain/lotto/Lotto.java
> +    public int matchLotto(List<LottoNum> winnerNumberList) {
해당 기능은 어디서 사용중일까요!?

2021-08-16 03:06 UTC, jaeyeonling requested changes
코멘트 반영을 잘 해주셨습니다 👍 
소소한 코멘트 남겨두었으니 확인 부탁드려요!
마지막까지 화이팅입니다 😄

2021-08-16 03:06 UTC, jaeyeonling commented on src/main/java/app/domain/lotto/Lotto.java
> +    public Winning getWinning(List<LottoNum> winner, LottoNum bonus){
```suggestion
    public Winning getWinning(List<LottoNum> winner, LottoNum bonus) {
```

매의 눈 @_@

2021-08-16 03:06 UTC, jaeyeonling commented on src/main/java/app/action/LottoMarket.java
> +            Winning winning = myLotto.getWinning(winner.getLotto().getNumbers(), winner.getBonus());
WinningLotto가 Lotto를 가지고 있는 형태를 가지고 있기 때문에, WinningLotto에게 해당 역할을 넘겨주면 외부에서 getLotto을 하지 않고 해당 기능을 사용할 수 있을 것 같은데 어떻게 생각하시나요?

코드를 작성할 때 테스트를 먼저 작성해보면 테스트를 하기 좋은 코드를 만들 수 있고, 자연스럽게 좋은 구조를 만들 수 있습니다 :)
위와 같은 관점에서 해댱 코드들 또한 테스트를 먼저 작성하여 테스트하기 좋은 구조를 만들어보아요

2021-08-21 15:54 UTC, jaeyeonling approved these changes
마지막까지 코멘트 잘 반영해주셨습니다 👍 
수 많은 코멘트 반영하시느라 고생 많으셨어요 😄 
해당 요청은 머지하도록 하겠습니다 다음 미션도 화이팅입니다!!

2021-08-21 15:54 UTC, merged