🚀 3단계 - 로또(2등)
next-step/java-lotto pull request #1853
Opened 2021-08-04 06:57 UTC by shirohoo

2021-08-04 13:54 UTC, JunilHwang requested changes
안녕하세요 창훈님! 3단계 미션 잘 진행해주셨네요 👍 
몇 가지 리뷰 남겼으니 확인 부탁드려요 🙇‍♂️

2021-08-04 13:54 UTC, JunilHwang commented on src/main/java/lotto/model/Lotto.java
> +        return numbers.contains(bonusNumber);
```java
    public int getMatchCount(Lotto winningLotto) {
        return toIntExact(
          winningLotto.numbers.stream()
            .filter(this::contains)
            .count()
        );
    }

    public boolean contains(final LottoNumber lottoNumber) {
        return numbers.contains(lottoNumber);
    }
```
이렇게 표현해주면 어떨까요?

2021-08-04 13:54 UTC, JunilHwang commented on src/main/java/lotto/model/LottoNumber.java
> +    }
이건 LottoNumber의 역할이 아닌 것 같아요

2021-08-04 13:54 UTC, JunilHwang commented on src/main/java/lotto/model/WinningLotto.java
> +    private final Set<LottoNumber> winningNumber;
```suggestion
    private final Lotto winningLotto;
```
이렇게 Lotto 객체를 가지고 있는게 자연스럽지 않을까요?

2021-08-04 13:54 UTC, JunilHwang commented on src/main/java/lotto/prize/LottoPrize.java
> +    private final Function<MatchInformation, Boolean> judge;
judge는 불필요해보여요!

2021-08-04 13:54 UTC, JunilHwang commented on src/main/java/lotto/prize/LottoPrize.java
> +    private final Function<MatchInformation, Boolean> judge;
더 쉽게 표현할 수 있는 방법이 있지 않을까요?

2021-08-04 13:55 UTC, JunilHwang requested changes
뭐지.. 알림이 안가네요.. ㅠㅠ

2021-08-05 12:33 UTC, shirohoo commented on src/main/java/lotto/prize/LottoPrize.java
> +    };
암만 생각해도 좋은 솔루션이 생각이 안납니다. 😣

2021-08-06 10:19 UTC, JunilHwang approved these changes
안녕하세요 창훈님! 피드백 반영 잘 해주셨네요 👍 
3단계는 여기서 마무리하겠습니다.
몇 가지 리뷰 및 힌트 남겼으니 다음 단계 진행하실 때 참고해주시면 좋을 것 같아요!

2021-08-06 10:19 UTC, JunilHwang commented on src/main/java/lotto/model/Lotto.java
> +            throw new IllegalArgumentException("Set<LottoNumber> size must be " + NUMBER_OF_LOTTO_COUNT);
CustomException을 만들어주면 어떨까요?

2021-08-06 10:19 UTC, JunilHwang commented on src/main/java/lotto/model/WinningLotto.java
> +    private final Lotto winningNumber;
```suggestion
    private final Lotto winningLotto;
```
이렇게 표현해주면 더 좋을 것 같아요!

2021-08-06 10:19 UTC, JunilHwang commented on src/main/java/lotto/prize/LottoPrize.java
> +    }
```suggestion
    public static LottoPrize valueOf(final MatchInformation matchInformation) {
        return stream(values())
                   .filter(prize -> matchInformation.isMatchCountEq(prize.matchCount))
                   .filter(prize-> !prize.equals(SECOND) || matchInformation.isMatchBonus())
                   .findAny()
                   .orElse(LottoPrize.NONE);
    }
```
이렇게 표현할 수 있지 않을까요?

2021-08-06 10:19 UTC, JunilHwang commented on src/main/java/lotto/prize/LottoPrize.java
> +    }
그러면 각각의 enum에서 선언해준 judge도 필요없을 것 같아요~

2021-08-06 10:36 UTC, merged

2021-08-06 10:40 UTC, shirohoo commented on src/main/java/lotto/prize/LottoPrize.java
> +    }
😮