3단계 - 로또(2등)
next-step/java-lotto pull request #1861
Opened 2021-08-05 01:20 UTC by testrace

2021-08-06 10:53 UTC, JunilHwang requested changes
안녕하세요 용주님! Step3 진행 잘 해주셨네요 👍 
몇 가지 리뷰 남겼으니 확인 후 다시 피드백 요청 부탁드려요!

2021-08-06 10:53 UTC, JunilHwang commented on src/main/java/lottosecond/domain/Lotto.java
> +	}
```suggestion
	public int matchingQuantityFrom(Lotto lastWeekNumbers) {
		int matchedCount = 0;
		for (LottoNumber lastWeekNumber : lastWeekNumbers.numbers) {
			matchedCount += contains(lastWeekNumber) ? 1 : 0;
		}
		return matchedCount;
	}

	public boolean contains(LottoNumber lottoNumber) {
		return numbers.contains(lottoNumber);
	}
```
이렇게 표현해주면 어떨까요?

2021-08-06 10:53 UTC, JunilHwang commented on src/main/java/lottosecond/domain/LottoResult.java
> +		result.put(LottoProfit.SIX, 0);
한 번에 표현할 수 있는 법이 있지 않을까요?

2021-08-06 10:53 UTC, JunilHwang commented on src/main/java/lottosecond/domain/Lottos.java
> +	private final List<Lotto> lottoList = new ArrayList<>();
```suggestion
	private final List<Lotto> lottos = new ArrayList<>();
```
복수형으로 표현해주세요!

2021-08-06 10:53 UTC, JunilHwang commented on src/main/java/lottosecond/domain/Lottos.java
> +	}
생성시점에 한 번에 만들어주도록 해주면 어떨까요?

2021-08-06 10:53 UTC, JunilHwang commented on src/main/java/lottosecond/ui/InputView.java
> +
input은 domain을 모르는 형태로 작성해주세요!
그리고 변환 작업은 domain의 역할이 아닐까요?

2021-08-06 10:53 UTC, JunilHwang commented on src/main/java/lottosecond/ui/ResultView.java
> +	private final Lottos lottos;
굳이 멤버변수로 가지고 있을 필요는 없을 것 같아요!

2021-08-07 12:06 UTC, testrace commented on src/main/java/lottosecond/domain/Lotto.java
> +	}
코드 가독성이나 메소드의 의미 전달이 부드러워지는 느낌이네요!
피드백 감사합니다!

2021-08-07 12:07 UTC, testrace commented on src/main/java/lottosecond/domain/LottoResult.java
> +		result.put(LottoProfit.SIX, 0);
반복문 말고는 떠오르는게 없어서 반복문으로 변경했습니다.
반복문 말고 다른 좋은 방법이 있을까요?

2021-08-07 12:24 UTC, testrace commented on src/main/java/lottosecond/ui/ResultView.java
> +	private final Lottos lottos;
멤버 변수 제거하는 김에 상태가 없는 ui 관련 클래스들의 메소드들을 모두 static으로 변경했습니다.
이부분에 대한 의견이 궁금합니다!

2021-08-07 13:15 UTC, testrace commented on src/main/java/lottosecond/ui/InputView.java
> +
피드백 주신대로 생각해보니 Input 뿐 아니라 Output 까지 도메인 의존을 없애는게 맞다고 생각되는데요,
InputView는 DTO 객체를 사용할 필요까진 없어보이지만 ResultView에서는 DTO를 통해서 도메인 의존성을 완전히 없애는게 맞는건가요?

2021-08-07 16:39 UTC, JunilHwang commented on src/main/java/lottosecond/ui/InputView.java
> +
@testrace 꼭 DTO를 사용하지 않아도 되지만, 사용해주면 좋답니다!

2021-08-07 16:43 UTC, JunilHwang approved these changes
안녕하세요 용주님! 피드백 반영 잘 해주셨네요 👍 
질문에 대한 답변도 각각의 피드백에 남겨놨으니 확인해보시면 될 것 같아요 ㅎㅎ
Step3는 여기서 마무리하겠습니다! 수고하셨습니다 🙇‍♂️

2021-08-07 16:43 UTC, JunilHwang commented on src/main/java/lottosecond/domain/LottoResult.java
> +		}
잘 표현해주셨습니다 👍

2021-08-07 16:43 UTC, JunilHwang commented on src/main/java/lottosecond/ui/InputView.java
> +}
static method만 있는 class의 경우, 인스턴스가 만들어지는걸 방지할 수 있게 
```java
private InputView () {}
```
이렇게 생성자를 private으로 지정해주면 좋답니다!

2021-08-07 16:43 UTC, JunilHwang commented on src/main/java/lottosecond/ui/ResultView.java
> +}
앞선 리뷰를 참고해주세요!

2021-08-07 16:45 UTC, merged