2단계 - 로또(자동)
next-step/java-lotto pull request #1875
Opened 2021-08-06 17:11 UTC by 0n1dev

안녕하세요 리뷰어님 😄 

최대한 TDD를 열심히 연습해보려고 하였고, 이전에 리뷰주신 내용에 대해서 최대한 신경써서 개발하였습니다.

- `원시값 포장 객체`를 적극적으로 이용해볼 것
- `자료구조`로 해결할 수 있는 부분에 대해 고민해볼 것

이번에도 좋은 리뷰 부탁드립니다!

2021-08-07 12:51 UTC, JunilHwang requested changes
안녕하세요 재원님! 로또 미션 잘 진행해주셨네요 👍 
몇 가지 리뷰 남겼으니 확인 후 다시 피드백 요청 부탁드려요!

2021-08-07 12:51 UTC, JunilHwang commented on src/main/java/LottoMain.java
> +	}
이렇게 두 개의 메소드는 잘 생각해보면 클래스로 분리해서 관리할 수 있지 않을까요?

2021-08-07 12:51 UTC, JunilHwang commented on src/main/java/lotto/domain/Lotto.java
> +	private final List<Integer> lottoNumbers;
- TreeSet을 사용해보세요!
- LottoNumber라는 원시값 포장 객체를 만들어주면 어떨까요?

2021-08-07 12:51 UTC, JunilHwang commented on src/main/java/lotto/domain/Lotto.java
> +		}
custom exception을 만들어서 관리해주면 어떨까요?

2021-08-07 12:51 UTC, JunilHwang commented on src/main/java/lotto/domain/LottoCount.java
> +}
검증로직도 필요하지 않을까요?

2021-08-07 12:51 UTC, JunilHwang commented on src/main/java/lotto/domain/Records.java
> +		this.records.put(Rank.FIRST, 0);
한 번에 표현할 수 있는 방법이 있지 않을까요?

2021-08-07 12:51 UTC, JunilHwang commented on src/main/java/lotto/enums/Rank.java
> +	FIRST(6L, 2000000000L);
```suggestion
	NOTHING(0L, 0L),
	FOURTH(3L, 5_000L),
	THIRD(4L, 50_000L),
	SECOND(5L, 1_500_000L),
	FIRST(6L, 2_000_000_000L);
```
이렇게 표현하면 숫자를 읽을 때 더 수월하답니다!

2021-08-07 12:51 UTC, JunilHwang commented on src/main/java/lotto/utils/RandomUtils.java
> +}
RandomUtils 라는 이름 때문에 `Random` class를 사용하는 줄 알았는데 아니네요 ㅎㅎ;
이름을 조금 더 Lotto에 종속적인 형태로 지어주면 어떨까요? 너무 범용적인 이름인데 범용적인 일을 하고 있지 않은 것 같아요 ㅠㅠ

2021-08-09 10:29 UTC, JunilHwang requested changes
안녕하세요 재원님! 피드백 반영 잘 해주셨네요 👍 
다시 몇 가지 리뷰 남겼으니 확인 부탁드려요!

2021-08-09 10:29 UTC, JunilHwang commented on src/main/java/lotto/controller/LottoController.java
> +	private Lotto winLotto;
멤버변수는 최대 3개 이하로 유지해주세요

2021-08-09 10:29 UTC, JunilHwang commented on src/main/java/lotto/controller/LottoController.java
> +	}
`new Lotto(winLottoNumbers)` 로 생성할 수 있도록 만들어주면 어떨까요?
이걸 객체지향에서 `다형성`이라고 한답니다!

2021-08-09 10:29 UTC, JunilHwang commented on src/main/java/lotto/domain/Lotto.java
> +	}
```suggestion
	public Lotto(Set<LottoNumber> lottoNumbers) {
	    this.lottoNumbers = lottoNumbers;
	}
	
	public static Lotto of(Set<LottoNumber> lottoNumbers) {
	    return new Lotto(lottoNumbers);
	}
	
	public static Lotto of(List<LottoNumber> lottoNumbers) { /** 구현 ** / }
	
	public static Lotto of(String lottoNumbers) { /** 구현 ** / }
```
이렇게 표현할 수 있도록 만들면 좋을 것 같아요!

2021-08-09 10:29 UTC, JunilHwang commented on src/main/java/lotto/domain/LottoNumber.java
> +}
검증로직이 필요하지 않을까요?

2021-08-09 10:29 UTC, JunilHwang commented on src/main/java/lotto/domain/LottoNumber.java
> +	}
LottoNumber라는 도메인에 대해 잘 생각해보면, 1 ~ 45 까지의 값만 가질 수 있습니다.
다른 의미로 해석해보면 아무리 인스턴스가 많아봤자 45개면 충분하다는 이야기입니다.

더 명확한 힌트를 드리자면,
```java
new Integer(1) == new Integer(1); // false
Integer.valueOf(1) == new Integer(1); // true
LottoNumber.valueOf(1) == LottoNumber.valueOf(1); // true
```
위의 코드를 보고 곰곰히 생각해보시면 좋을 것 같아요!

2021-08-09 10:29 UTC, JunilHwang commented on src/main/java/lotto/domain/Lottos.java
> +	private static final int LOTTO_NUMBERS_LENGTH = 6;
이건 Lottos에서 관리해야할 상수가 아닌 것 같아요!

2021-08-09 10:29 UTC, JunilHwang commented on src/test/java/lotto/domain/LottoTest.java
> +}
LottoNumber에 대한 테스트 코드도 필요할 것 같아요!

2021-08-09 12:51 UTC, 0n1dev commented
최대한 `LottoNumber`을 수정해보았습니다. 말씀하신 의미에 맞게 수정한건지 잘 모르겠네요...

2021-08-09 13:19 UTC, JunilHwang requested changes
안녕하세요 재원님~ 피드백 반영 빠르게 잘 해주셨네요 👍 
다만 `LottoNumber` 부분은 너무 어렵게(?) 사용되도록 리팩토링이 된 것 같아요 ㅎㅎ
더 간단하게 구현할 수 있습니다!
그리고 `LottoNumbers`는 아예 필요없는 객체라서 제거해주세요!
`LottoNumbers`에 있는 내용을 `LottoNumber`에서 관리한다고 생각하면 좋을 것 같습니다.

2021-08-09 13:19 UTC, JunilHwang commented on src/main/java/lotto/domain/number/LottoNumber.java
> +		}
이 부분은 validate method로 분리하면 좋을 것 같아요!

2021-08-09 13:19 UTC, JunilHwang commented on src/main/java/lotto/domain/number/LottoNumber.java
> +	}
- `valueOf` 라는 메소드를 통해서만 인스턴스를 반환할 수 있게 해주세요!
- `LottoNumber.valueOf(1) == LottoNumber.valueOf(1);`이 `true`가 되도록 작업해주세요!

2021-08-09 13:19 UTC, JunilHwang commented on src/main/java/lotto/domain/number/LottoNumbers.java
> +}
이 class는 제거해주세요! 불필요합니다.

2021-08-09 16:14 UTC, 0n1dev commented
말씀하신대로 적용했습니다!

2021-08-09 23:58 UTC, JunilHwang approved these changes
안녕하세요 재원님! 피드백 반영 잘 해주셨네요 👍 
몇 가지 리뷰 더 남겼는데, 이건 다음 단계 진행하실 때 참고하시면 좋을 것 같아요 ㅎㅎ
이번 단계는 여기서 마무리하겠습니다! 수고하셨습니다.

2021-08-09 23:58 UTC, JunilHwang commented on src/main/java/lotto/domain/LottoCount.java
> +		}
validate method 로 분리하면 좋을 것 같아요!

2021-08-09 23:58 UTC, JunilHwang commented on src/main/java/lotto/domain/LottoNumber.java
> +		IntStream.range(1, 46)
```suggestion
		IntStream.rangeClosed(1, 45)
```
이렇게도 표현할 수 있습니다!
그리고 1고 45는 상수로 관리해주면 어떨까요?

2021-08-09 23:58 UTC, JunilHwang commented on src/main/java/lotto/domain/LottoNumber.java
> +	}
여기서 검증로직이 필요할 것 같아요~
1 ~ 45 범위의 숫자가 들어오지 않을 수도 있는데, 이럴 경우에  null을 반환하게 될 것 같아요!

2021-08-09 23:58 UTC, JunilHwang commented on src/test/java/lotto/domain/LottoNumberTest.java
> +}
검증 과정에 대한 테스트도 필요하지 않을까요?

2021-08-09 23:58 UTC, JunilHwang commented on src/test/java/lotto/domain/LottoTest.java
> +	}
다양한 케이스에 대해 테스트해야할 것 같아요!

2021-08-09 23:58 UTC, JunilHwang commented on src/test/java/lotto/domain/LottoTest.java
> +	}
`ParameterizedTest`를 사용해보세요!
같이 이용하면 좋은게 `MethodSource` 입니다.

2021-08-09 23:58 UTC, merged