Step2 - 로또(자동)
next-step/java-lotto pull request #1885
Opened 2021-08-07 16:04 UTC by harrisleesh

- 로또게임 구현
- 각 entity 별 테스트 구현
- 랜덤 생성, 정렬 생성 전략으로 로또번호 생성
- view 분리

2021-08-07 18:05 UTC, hyunssooo requested changes
안녕하세요 성훈님 🙂
몇 가지 코멘트 남겼습니다. 확인 부탁드립니다!
궁금한 점이나 함께 고민해보고 싶은 부분이 있으시다면 언제든 편하게 연락주세요.

2021-08-07 18:05 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoTest.java
> +        sortedLotto = new Lotto(new ListSortStrategy());
어떤 차이가 있나요??

2021-08-08 01:57 UTC, harrisleesh commented on src/main/java/calculator/StringAddCalculator.java
> +                .findAny().isPresent();
오..!! 감사합니다 👍

2021-08-08 02:42 UTC, harrisleesh commented on src/main/java/lotto/domain/Lotto.java
> +    }
오 그렇군요!! 생각해보니 저기서 삼항연산자를 굳이 쓰지않아도 됐었네요;; ㅎㅎ

2021-08-08 02:54 UTC, harrisleesh commented on src/main/java/lotto/domain/Award.java
> +    UNIDENTIFIED(-1, 0);
오.. 0~2개는 미당첨으로 묶는게 좋을 것 같네요!! 감사합니다!

2021-08-08 04:15 UTC, harrisleesh commented on src/main/java/lotto/domain/LottoNumbers.java
> +
오 넵!! LottoNumber 일급 객체를 만들어서 반영해보겠습니다 :)

2021-08-08 04:30 UTC, harrisleesh commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
넵! 중복된 숫자에 대한 검증 로직과 테스트를 추가했습니다 :)

2021-08-08 04:37 UTC, harrisleesh commented on src/main/java/lotto/util/LottoNumberGenerator.java
> +    }
오.. 넵 보다 명시적이네요 감사합니다 :)

2021-08-08 04:42 UTC, harrisleesh commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
winnerNumber와 같은 갯수를 세는 함수인데 네이밍이 잘못되었네요!!
변경했습니다.

2021-08-08 04:59 UTC, harrisleesh commented on src/main/java/lotto/domain/Lottos.java
> +    }
네! 감사합니다:) 각 entity에 toString methods 지우고 ResultView에서는 getter를 활용해서 보여주게 변경했습니다!

2021-08-08 05:01 UTC, harrisleesh commented on src/main/java/lotto/strategy/ListMixStrategy.java
> +        Collections.shuffle(list, new Random(seed));
shuffle 함수를 찾아봤을 때 랜덤 시드를 저런식으로 넣어주어서 사용해봤습니다. 근데 시드를 주지않아도 랜덤 생성이 잘 되네요 ;;
지우고 반영했습니다 👍

2021-08-08 05:03 UTC, harrisleesh commented on src/main/java/lotto/domain/Lottos.java
> +
엇 실수로 안들어간 것 같아요! private을 넣어서 반영했습니다!!

2021-08-08 05:18 UTC, harrisleesh commented on src/main/java/lotto/view/InputView.java
> +    }
넵!! InputView에서는 List<Integer> 를 받아오게 하고 객체의 생성은 LottoMain에서 하게 했습니다:)
Stream 개행도 반영했어요 감사합니다:)

2021-08-08 06:24 UTC, harrisleesh commented on src/test/java/lotto/domain/LottoTest.java
> +        sortedLotto = new Lotto(new ListSortStrategy());
정렬된 로또와 랜덤 로또를 둘 다 테스트해보고싶었어요!

2021-08-08 06:25 UTC, harrisleesh commented on src/main/java/lotto/util/LottoNumberGenerator.java
> +    }
넵! 테스트를 위해서 전략패턴으로 랜덤생성 로또와 정렬 로또를 구분하고싶었는데 전략패턴 없이 테스트가 가능한 설계가 가능하더라구요;;
그래서 변경해서 적용했습니다:) 감사합니다

2021-08-08 16:48 UTC, hyunssooo requested changes
안녕하세요 성훈님 🙂
추가로 몇 가지 코멘트 남겼습니다. 확인 부탁드립니다!
궁금한 점이나 함께 고민해보고 싶은 부분이 있으시다면 언제든 편하게 연락주세요.

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoGame.java
> +    }
LottoGame 클래스는 도메인 객체로 보이는데 resultView에 의존하고 있네요. 

<img width="935" alt="image" src="https://user-images.githubusercontent.com/25217343/128638690-ce0c3734-6fcd-471f-bc0f-9be9d08043c4.png">

mvc를 학습하고 적용해보면 좋을 것 같아요.

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoNumber.java
> +
`이펙티브 자바 아이템 61. 박싱된 기본 타입보다는 기본 타입을 사용하라.`
를 읽어보시면 좋을 것 같아요 :)

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
테스트에서 사용하는 메서드네요. 테스트를 위한 코드가 프로덕션에 존재하는 것에 대해서 고민해보면 좋을 것 같아요 :)

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
if 문에 중괄효는 생략하지 않는 것이 좋습니다. 

boolean을 리턴할 것 같은 메서드인데 int 값을 리턴하네요. 🤔

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
`Collections.unmodifiableList()` 를 찾아보고 적용해보는 것은 어떨까요? 
어떤 장점이 있을까요? 
아래 두 글이 도움이 될 것 같아요 :) 

https://woowacourse.github.io/tecoble/post/2020-05-08-First-Class-Collection/
https://brainbackdoor.tistory.com/140

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +
Award가 필드에 존재하는 이유가 따로 있나요?? 🤔

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +    private LottoNumbers lottoNumbers;
궁금한 점이 있는데 

LottoNumber 1개의 숫자를 의미
LottoNumbers 6개의 숫자를 의미 실질적인 로또 1개

로 보이네요 그럼 Lotto 클래스는 어떤걸 의미할까요? 저는 LottoNumbers와 다를게 없어보이네요! 
일급컬렉션의 이름이 꼭 복수일 필요는 없습니다.

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
이번 기회에 getter는 극단적으로 사용하지 않는 연습을 해보는 것은 어떨까요??

```suggestion
    public int countContains(LottoNumbers winnerNumbers) {
        int numbers = 0;
        for (LottoNumber winnerNumber : winnerNumbers.lottoNumbers) {
            numbers += contains(winnerNumber);
        }
        return numbers;
    }
```

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/view/ResultView.java
> +    }
lottoGame는 도메인 객체인데 view에서 도메인 객체의 메서드를 사용하고 있어요. 
현재는 콘솔기반이지만 환경이 웹으로 변경된다면 해당 메서드를 호출할 수 있을까요?
view에서는 도메인 객체의 메서드는 getter를 제외하고는 사용하시면 안됩니다. 
이번 기회에 mvc에 대해서 학습하고 적용해보는 것은 어떨까요?

2021-08-08 16:48 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoNumbersTest.java
> +    }
이런 테스트는 의미 있는 테스트일까요? 
어떤 의도의 테스트일까요? 
테스트를 작성한다는 것은 클래스 내부 구현을 테스트하는 것이 아닙니다. 해당 객체의 명세(보통은 public method)를 테스트한다고 생각하시면 됩니다.
보통 getter 같은 경우는 내부의 필드를 그대로 꺼내주고 있습니다. 이 경우에는 테스트가 필요할까요?

2021-08-08 16:48 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoTest.java
> +        sortedLotto = new Lotto(lottoNumbers);
정렬된 로또와 랜덤 로또는 어떤 차이가 있나요? 
1,2,3,4,5,6
6,5,4,3,2,1
이 2가지는 다른 로또일까요?

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/util/LottoListGenerator.java
> +    }
```suggestion
    public static LottoNumbers createLottoNumbers() {
        Collections.shuffle(lottoNumbersPool);

        return new LottoNumbers(
                lottoNumbersPool.stream()
                        .limit(6)
                        .collect(Collectors.toList())
        );
    }
```

이런 방법도 있겠네요!

2021-08-08 16:48 UTC, hyunssooo commented on src/main/java/lotto/util/LottoListGenerator.java
> +    }
이 메서드는 클래스 내부에서만 사용하는데 private이 더 어울리지 않을까요??

2021-08-09 12:56 UTC, harrisleesh commented on src/main/java/lotto/LottoMain.java
> +import lotto.view.InputView;
오 넵 감사합니다 :)

2021-08-09 13:11 UTC, harrisleesh commented on src/main/java/lotto/strategy/ListMixStrategy.java
> +@Deprecated
네!!

2021-08-09 13:35 UTC, harrisleesh commented on src/main/java/lotto/domain/Lotto.java
> +    private LottoNumbers lottoNumbers;
앗.. 생각해보니 Lotto와 LottoNumbers 는 중복이 맞는것 같아요! 수정해서 반영하겠습니다 :)

2021-08-09 13:37 UTC, harrisleesh commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
앗.. 그렇네요!! 감사합니다!

2021-08-09 13:55 UTC, harrisleesh commented on src/main/java/lotto/domain/Award.java
> +    private final int amount;
넵 :)

2021-08-09 13:56 UTC, harrisleesh commented on src/main/java/lotto/domain/Award.java
> +    }
와... 감사합니다..!!! Stream 많이 배우네요 감사해요!

2021-08-09 13:59 UTC, harrisleesh commented on src/main/java/lotto/domain/LottoNumbers.java
> +
넵!! List 대신 Set을 사용하는게 훨씬 효율적인 것 같아요!

2021-08-09 14:02 UTC, harrisleesh commented on src/main/java/lotto/domain/LottoNumber.java
> +
오.. 넵넵 감사합니다!!
기본타입이 훨씬 빠르고 다양한 장점이 있네요!!

2021-08-09 14:12 UTC, harrisleesh commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
오.. 넵 해당부분은 Stream으로 풀어낼 수 있었네요 :) 감사합니다!!

2021-08-09 14:25 UTC, harrisleesh commented on src/main/java/lotto/util/LottoListGenerator.java
> +    }
오... 네넵!! 스트림 사용하는게 훨씬 간결하네요!

2021-08-09 14:25 UTC, harrisleesh commented on src/main/java/lotto/util/LottoListGenerator.java
> +    }
private으로 변경했습니다 :)

2021-08-09 14:27 UTC, harrisleesh commented on src/test/java/lotto/domain/LottoNumbersTest.java
> +    }
그렇군요!! getter에 대한 메서드는 크게 유의미한 테스트가 아닌거 같아요!

2021-08-09 14:27 UTC, harrisleesh commented on src/test/java/lotto/domain/LottoTest.java
> +        sortedLotto = new Lotto(lottoNumbers);
Set으로 변경하면서 생각해봤는데 차이가 없어보입니다!! 감사합니다 :)

2021-08-09 14:32 UTC, harrisleesh commented on src/main/java/lotto/domain/LottoGame.java
> +    }
앗.. 넵!! MVC를 좀 더 생각하면서 설계해야겠군요!! 감사합니다 :)

2021-08-09 14:33 UTC, harrisleesh commented on src/main/java/lotto/domain/Lotto.java
> +
로또의 상태가 변경될 수 있을 것 같아서 필드에 유지했습니다!

2021-08-09 14:33 UTC, harrisleesh commented on src/main/java/lotto/domain/Lotto.java
> +
당첨로또가 나온 시점에 로또의 상태가 당첨 유무로 판단될 수 있을 것 같아서요!

2021-08-09 15:09 UTC, harrisleesh commented on src/main/java/lotto/view/ResultView.java
> +    }
넵 ResultView에서 최대한 도메인 객체를 분리하고자 했습니다 :)

2021-08-09 15:10 UTC, harrisleesh commented
전체적으로 상세한 코드리뷰 정말 감사드립니다!! 해당 부분 반영하여 다시 푸시합니다~! 👍

2021-08-09 16:03 UTC, hyunssooo approved these changes
성훈님 코멘트 반영해주신다고 정말 수고 많으셨습니다! 👏👏👏
다음 step 진행 부탁드릴게요!

2021-08-09 16:03 UTC, hyunssooo commented on src/main/java/lotto/util/LottoListGenerator.java
> +
아 여기서 캐싱해두셨군요 👍
수동 로또의 요구사항이 추가된다면 조금 바뀔 거 같습니다 :) 
그때까지 고민해보시면 좋을 것 같아요! 👍

2021-08-09 16:03 UTC, merged

2021-08-11 12:48 UTC, harrisleesh commented on src/main/java/lotto/LottoMain.java
> +    }
오 넵!! 고민했던 부분인데 Set<Integer> winnerNumbers 는 로또로 추상화 할 수 있을 것 같네요!

2021-08-11 12:49 UTC, harrisleesh commented on src/main/java/lotto/util/LottoListGenerator.java
> +
네넵!! 감사합니다 :)