Step3
next-step/java-lotto pull request #1888
Opened 2021-08-08 08:00 UTC by kimdonggyu-dev

안녕하세요 선동님~~

벌써 한주가 훌쩍 지나 일요일이네요 😂

저번에 주신 피드백으로 고민을 많이 해봤어요.
그래서 전체적으로 코드 변경량이 많은점 양해부탁드립니다 ㅠ

- 결국 비지니스의 복잡성이 조금 더 증가하게 되니 선동님 말씀하신대로 일급클래스인 `Numbers` 와 value object인 `Number` 를 추가하게 되었어요.
- 그리고 기존엔 당첨로또와 로또를 같이 사용했는데, `WinningLotto`를 따로 분리하였습니다.
  - match 로직은 `WinningLotto` 에만 넣었어요.
- 그 외 클래스를 분리와 역할과 책임을 집중해서 코드를 작성해봤습니다.

### 질문

- `Lotto`나 `WinningLotto`에서 생성자로 Numbers를 받는게 나을까요? 현재 처럼 List<Integer> numbers 를 받는게 나을까요?
- `WinningLotto`가 `Lotto` 를 상속하게 하는게 낫지 않을까 생각했는데, 어떻게 생각하는지 의견을 여쭤보고싶어요 

주말 마무리 잘 하세요!!
꼼꼼한 피드백 항상 감사드립니다.  😄

2021-08-08 11:54 UTC, ksundong requested changes
안녕하세요! 동규님! 😊  리뷰어 김선동입니다.
정말 시간이 참 빠르네요!!

3단계 미션도 열심히 진행해주셨네요. 전체적으로 코드 퀄리티가 많이 좋아진 것 같습니다. 👍
다만, 커밋이 충분하게 나눠져있지 않아서 이 부분에 대해서 좀 더 신경써주시면 좋을 것 같습니다.

- `Wrapper` 클래스와, 일급 컬렉션을 적절히 잘 활용해주신 것 같아요.
- `static`이 조금 많이 등장하게 되었는데, 없애는 방향으로 생각해봐주세요!

## 답변

- `Lotto`나 `WinningLotto`에서 생성자로 `Numbers`를 받는게 나을까요? 현재 처럼 `List` numbers 를 받는게 나을까요?
  - 둘 다 받으면 되지 않을까요? 생성자는 많아도 괜찮습니다!
- `WinningLotto`가 `Lotto` 를 상속하게 하는게 낫지 않을까 생각했는데, 어떻게 생각하는지 의견을 여쭤보고싶어요
  - 상속은 참 어려운 문제입니다. 보통 설계의 안티패턴으로 여겨지는 경우가 많아요. '상속보다는 합성'이라는 주제에 대해서 학습하시는 것도 추천드리고, 왜 상속하는게 낫지 않을까? 하고 생각하셨는지도 궁금합니다!

피드백이 조금 많아서 변경요청 드리고 변경된 후에 다시 리뷰하고자 합니다!!
확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

동규님도 주말 마무리 잘 하세요!!

2021-08-08 11:54 UTC, ksundong commented on src/main/java/lottos/domain/Lottos.java
> +    private static final LottoGenerator generator = new LottoRandomGenerator();
`LottoRandomGenerator`를 직접 생성해주셨는데, 혹시 테스트가 어렵진 않으셨나요?

2021-08-08 11:54 UTC, ksundong commented on src/main/java/lottos/domain/Lottos.java
> +            List<Integer> numbers = generator.generate().subList(0, 6);
0, 6이라는 숫자는 특정한 의미를 가집니다.
상수로 추출해보시고, `subList`를 이곳에서 해주는게 좋을지, `Integer` `List`를 반환하는게 맞을지도 고민해보시기 바랍니다.

2021-08-08 11:54 UTC, ksundong commented on src/main/java/lottos/domain/WinningLotto.java
> +    }
이런 입력을 정제하는 과정은 `Controller`에서 수행해주면 어떨까요?

2021-08-08 11:54 UTC, ksundong commented on src/main/java/lottos/domain/WinningLotto.java
> +        checkDuplicateNumbers(numbers, bonusNumber);
순서상 validation이 먼저 등장하는것이 맞지 않을까요?

2021-08-08 11:54 UTC, ksundong commented on src/main/java/lottos/domain/WinningLotto.java
> +    }
👍

2021-08-08 11:54 UTC, ksundong commented on src/main/java/lottos/domain/numbers/Number.java
> +    private void checkRangeNumber(final Integer number) {
좀더 자연스러운 표현은 checkNumberRange가 아닐까 싶네요!

2021-08-08 11:54 UTC, ksundong commented on src/main/java/lottos/view/LottoConsoleOutputView.java
> +                    .collect(Collectors.toList());
디미터 법칙을 준수하는 코딩을 해보시면 어떨까요?

2021-08-08 11:54 UTC, ksundong commented on src/main/java/lottos/view/LottoConsoleOutputView.java
> +        }
출력로직은 결과만 전달받아 출력만 하도록 하는 것이 어떨까요?

2021-08-08 11:54 UTC, ksundong commented on src/test/java/lottos/domain/LottoTest.java
> +        }
랜덤이 정상 동작함을 보장하는 것을 확인하기 보다.
위에서 말씀드린 것처럼 `Random`과 관련된 의존성을 추출해서 테스트하기 쉽게끔 해보는게 어떨까요?

2021-08-08 11:54 UTC, ksundong commented on src/test/java/lottos/domain/LottosTest.java
> +    void 금액으로_로또_구매_불가능(final int purchaseAmount) {
어떤 금액인가요?

2021-08-08 11:54 UTC, ksundong commented on src/test/java/lottos/domain/LottosTest.java
> +        // 장당 1000원
이 주석은 만약 가격이 변경되었을 때, 같이 변경될 수 있을까요?

2021-08-08 11:54 UTC, ksundong commented on src/test/java/lottos/domain/LottosTest.java
> +        Assertions.assertThrows(IllegalArgumentException.class, () -> new Lottos(purchaseAmount));
단순히 `Exception`의 `class`만 확인한다고 해당 테스트가 맞는지를 보장하긴 힘들 것 같습니다.

2021-08-08 11:54 UTC, ksundong commented on src/test/java/lottos/domain/LottosTest.java
> +    }
이 테스트들은 잘 작성해주셨네요.

2021-08-08 11:54 UTC, ksundong commented on src/test/java/lottos/domain/WinningLottoTest.java
> +    }
깔끔한 테스트 잘 작성해주셨네요.

2021-08-08 11:54 UTC, ksundong commented on src/test/java/lottos/domain/numbers/NumberTest.java
> +        Assertions.assertDoesNotThrow(() -> Number.valueOf(number));
예외만 안던진다고 잘 생성된 것이 아니라, 해당 객체가 정상적으로 동작함까지 확인해주는 것이 좋다고 생각됩니다.

2021-08-09 11:43 UTC, kimdonggyu-dev commented on src/main/java/lottos/domain/WinningLotto.java
> +        checkDuplicateNumbers(numbers, bonusNumber);
`Numbers` 생성자에서 6개의 정수인지 확인하고, `Number` 생성자에서 1~45 사이의 숫자인지 확인한 다음에
정상적인 숫자들로 이루어져있을경우 중복된 숫자가 있는지 확인해야 할거같아서 순서를 조정하였습니다 😁

2021-08-09 11:50 UTC, kimdonggyu-dev commented
안녕하세요 선동님
이번에도 많은 피드백 감사합니다. 🙏🏻

피드백을 반영했는데, 

**질문1**
- `LottoGenerator` 를 의존성 주입해줌으로써 테스트코드에선 람다를 통해 항상 같은 값을 반환할 수 있게 테스트 할 수 있게된거같아요.
이렇게 수정하는게 말씀하신 피드백이 맞을까요? 

**질문2**
```java
public Lottos(final int purchaseAmount, final LottoGenerator generator) {
    this.generator = generator;
    this.lottos = issue(purchaseAmount);
}
```
해당 코드에서 

```java
this.lottos = issue(purchaseAmount);
this.generator = generator;
```
생성자 주입 순서가 바뀌게 되면 동작 안하는 이슈가 있는데 괜찮을까요?

한주 시작 월요일 파이팅입니다 😁

2021-08-09 23:30 UTC, ksundong commented on src/main/java/lottos/domain/WinningLotto.java
> +        checkDuplicateNumbers(numbers, bonusNumber);
아 중복된 숫자가 있는지 검증하는 것이군요!

2021-08-09 23:33 UTC, ksundong commented
안녕하세요 동규님! 리뷰어 김선동입니다. 😊

> **질문1**
> 
> * `LottoGenerator` 를 의존성 주입해줌으로써 테스트코드에선 람다를 통해 항상 같은 값을 반환할 수 있게 테스트 할 수 있게된거같아요.
>   이렇게 수정하는게 말씀하신 피드백이 맞을까요?
>

네 맞습니다. 그렇게 되면, `LottoGenerator`의 구현에 관계없이 단위테스트가 가능해지게됩니다.

> **질문2**
> 
> ```java
> public Lottos(final int purchaseAmount, final LottoGenerator generator) {
>     this.generator = generator;
>     this.lottos = issue(purchaseAmount);
> }
> ```
> 
> 해당 코드에서
> 
> ```java
> this.lottos = issue(purchaseAmount);
> this.generator = generator;
> ```
> 
> 생성자 주입 순서가 바뀌게 되면 동작 안하는 이슈가 있는데 괜찮을까요?
> 

그럼 이렇게도 생각해볼 수 있겠죠. `Lottos`가 `LottoGenerator`를 상태로 가지는 것이 아니라 외부에서 `LottoGenerator`를 이용해서 `Lottos`를 만들어줘야 하는게 아닐까? 하고요. ㅎㅎ

동규님도 이번 주 파이팅입니다!

2021-08-10 11:53 UTC, ksundong approved these changes
안녕하세요! 동규님! 리뷰어 김선동입니다! 😊

이번 단계 피드백 반영하느라 고생많으셨습니다!

실행해보았는데 수익률이 1보다 낮은경우 '(기준이 1이기 때문에 결과적으로 손해라는 의미임)' 이라는 요구사항이 지켜지지 않았네요!
또, '5개 일치, 보너스 볼 일치(30000000원)' 도 ','가 누락되어있습니다!

또한, `LottoPrize.winningValues()`가 테스트로 커버되지 않았습니다. (부족한 테스트가 있다는 것이겠죠?)

해당 부분 다음 단계에서 꼭 확인해주세요!

고생하셨습니다!
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-10 11:53 UTC, ksundong commented on src/main/java/lottos/view/LottoConsoleOutputView.java
> +        int purchaseCount = lottos.elements().size();
디미터 법칙을 준수하는 방향으로 코딩해보면 어떨까요?

2021-08-10 11:53 UTC, ksundong commented on src/test/java/lottos/domain/LottoTest.java
> +        }
랜덤을 테스트하는 이유가 있나요?
이 테스트가 정확함은 어떻게 보장할 수 있나요?

2021-08-10 11:53 UTC, ksundong commented on src/test/java/lottos/domain/WinningLottoTest.java
> +    void 로또_비교() {
Parameterized Test면 더 좋겠네요!

2021-08-10 11:53 UTC, ksundong commented on src/test/java/lottos/domain/numbers/NumberTest.java
> +    }
경계값 테스트를 잘 작성해주셨네요. 👍

2021-08-10 11:53 UTC, ksundong commented on src/test/java/lottos/domain/numbers/NumbersTest.java
> +    void 매치수_검증() {
여기도 Parameterized Test면 좋겠네요!

2021-08-10 11:53 UTC, merged

2021-08-14 06:23 UTC, kimdonggyu-dev commented on src/main/java/lottos/controller/LottoConsoleController.java
>      }
만약 오류가 발생할 경우 `NumberFormatException` 을 의도한건데 custom exception을 사용하는걸 권장하시는건가요~? 😄