[ 로또 ] 3단계 - 로또(2등)
next-step/java-lotto pull request #1892
Opened 2021-08-08 14:23 UTC by YooInKeun

안녕하세요 이슬님!
시간 되실 때, 로또 3단계 피드백 부탁드립니다~ :bowing_man:

2021-08-09 03:47 UTC, parkeeseul requested changes
3 단계 미션 잘 진행해주셨네요! 👍 
몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다! 😄 
한 주의 시작이네요! 좋은 하루 되시길 바라요!
미션 화이팅 입니다! 🔥

2021-08-09 04:09 UTC, YooInKeun commented on src/main/java/lotto/model/LotteryNumbers.java
> +public class LotteryNumbers {
> 해당 객체의 네이밍으로 보았을때는 우승 번호들에 관련된 클래스라고 보기 힘들 것 같은데 인근님의 생각은 어떠신가요?

제 처음의 의도는 추첨 번호에 대한 개념을 다음과 같이 가져가려고 했는데요.
`추첨 번호(LotteryNumbers) = 우승 번호(WinningNumbers) + 보너스 번호(BonusNumber)`
`LotteryNumbers`가 '추첨 번호' 보다는 '복권 번호' 라는 의미가 더 커서, 네이밍이 적절치 못한 거 같네요. 좀 더 고민해보겠습니다. :thinking:  

> WinningNumbers 클래스와 Lotto 클래스를 나눌 필요가 있을까 하는 생각도 드는데 이부분에 대해서는 어떻게 생각하시나요?

구현상으로 Lotto 클래스 하나만 있어도 괜찮을 거 같습니다! 하지만 헷갈리고 잘 모르겠는 부분이, Lotto 클래스를 통해 당첨 번호까지 구현하게 됐을 때, Lotto 클래스가 로또의 역할과 당첨 번호 역할 총 2가지 역할을 하게 되는 건 아닌가 생각이 드는데요.
타자를 치면서 또 드는 생각은 역할이라는 개념을 기능에 초점을 맞춰서 생각한다면 Lotto와 WinningNumbers가 하는 역할이 크게 다를 게 없네요..! 실제로 중복되는 메소드도 존재하고... 합치는 것이 좋을 거 같습니다 :+1:

2021-08-09 04:23 UTC, YooInKeun commented on src/main/java/lotto/model/WinningRank.java
> +    static WinningRank findWinningRank(Lotto lotto, LotteryNumbers lotteryNumbers) {
테스트 코드에서 사용하고 있기 떄문에 default 접근 제어자로 지정했습니다!

2021-08-09 04:33 UTC, YooInKeun commented on src/main/java/lotto/model/WinningRank.java
> +    }
해당 메소드는 단순히 `findWinningRank` 메소드를 여러 번 실행한 결과를 List에 담아 반환하고 있는데요.
그래서 `findWinningRank` 메소드만 테스트해도 단위(기능) 테스트로는 충분하지 않을까 라는 생각에 해당 메소드에 대한 테스트 코드는 작성하지 않았습니다! 추후에 기능 요구 사항이 변경되어 테스트 코드 작성이 필요한 상황이 발생할 수 있지만, 추후 변경 사항을 감안해 테스트 코드를 미리 작성하는 것도 좋지는 않은 것 같아 작성하지 않았는데요. 

이슬님의 생각은 어떠신지 궁금합니다! :thinking:

2021-08-09 10:40 UTC, YooInKeun commented on src/main/java/lotto/model/WinningRank.java
> +    private static List<WinningRank> findBy(int matchedWinningNumberCount) {
해당 메소드도 테스트를 하고자 했는데, 테스트를 위해 접근 제어자를 default나 public으로 바꾸는 것이 꺼림직해 일단 하지 않았습니다. 테스트를 위해 접근 제어자를 수정할 일이 있을 때, 이슬님은 어떻게 개발하시는지 궁금합니다!

2021-08-09 10:53 UTC, YooInKeun commented on src/main/java/lotto/model/WinningRank.java
> +    static List<WinningRank> findBy(int matchedWinningNumberCount) {
(https://github.com/next-step/java-lotto/pull/1892#discussion_r684895197 이 메소드도 테스트를 위해 접근 제어자를 수정하게 됐습니다)

2021-08-10 01:01 UTC, parkeeseul commented on src/main/java/lotto/model/LotteryNumbers.java
> +public class LotteryNumbers {
인근님의 말씀처럼 Lotto 와 WinningNumbers 의 기능이 동일하다고 생각되서 해당 피드백을 남겨드렸습니다 👍 
객체를 설계할 때는 객체가 어떠한 책임을 가지고 있는지가 가장 중요하다고 생각하는데요, 
 WinningNumbers 가 가지고 있는 기능들을 살펴보았을 때 당첨 번호와 관련된 기능이라기 보다는 사실상 Lottos 와 동일한 기능을 가지고 있었습니다. 때문에 굳이 해당 객체를 설계해줄 필요가 있을까에 대해 의견을 드렸었습니다.
우승번호에 대한 책임은 구현해주신 DrawNumbers 가 가진다고 볼 수 있을 것 같네요! 😄

2021-08-10 01:17 UTC, parkeeseul commented on src/main/java/lotto/model/WinningRank.java
> +    }
해당 과정은 TDD 를 학습해보는 과정으로 TDD 사이클로 구현이 되었다면 테스트 코드가 작성되야 하는 메서드는
외부에 공개되는 findWinningRanks 여야 한다고 생각합니다.
또한 테스트 코드를 위해 프로덕션 코드가 변경이되는 것은 지양해야 한다고 생각하는데요
private 메서드에 대한 테스트는 해당 메서드를 호출하는 public 메서드를 테스트 함으로써 자연스럽게 테스트가 된다고 볼 수 있을 것 같아요. 만약 private 메서드가 테스트가 필요하다고 생각이 든다면 코드스멜을 의심해볼 필요가 있을 것 같은데요, 해당 로직이 winningRank 에 위치하는 것은 맞을지 다른 클래스로 분리가 필요한 것은 아닌지에 대한 고민을 한번 해보시면 좋을 것 같아요! 😄

2021-08-10 01:19 UTC, parkeeseul commented on src/main/java/lotto/model/WinningRank.java
> +    static WinningRank findWinningRank(Lotto lotto, LotteryNumbers lotteryNumbers) {
[해당 피드백](https://github.com/next-step/java-lotto/pull/1892#discussion_r685621749)을 통해 저의 의견 남겨두었습니다! 😄

2021-08-10 01:23 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
질문 주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드리고
추가적인 수정사항은 다음 단계에서 함께 반영 부탁드립니다! 😄 
다음 단계 진행해주세요! 화이팅 입니다! 🔥

2021-08-10 01:23 UTC, merged