Step3 리뷰 요청드립니다.
next-step/java-lotto pull request #1899
Opened 2021-08-09 08:15 UTC by kdh85

용대님 안녕하세요.
step2 마지막 남은 리팩토링 내용과 step3 2등 당첨 기능을 포함한 리뷰를 요청 드립니다.

이번 step에서 가장 관심 깊게 생각한 부분은 당첨정보의 객체화였습니다.
기존에는 로또 객체 자체끼리의 비교만 하면 되었는데, 이제는 보너스 번호를 포함하도록 변경되었는데요.
기존에는 당첨된 로또번호 == 당첨정보 였는데 이제는 그 개념에서 벗어나야해서
새로운 객체의 필요성을 느꼈습니다.
그래서 당첨번호를 주입받아 생성된 로또객체 + 보너스볼을 담은 당첨정보객체를 만들어서
주입하도록 변경해보았습니다.

위와같이 주입객체가 변경됨에 따라 기존 서비스, 도메인단 프로덕션 코드와 테스트코드의 일부를 리팩토링해야 했는데요.
여기서 약간 고통을 받았어요... 제가 만든 테스트코드가 어느 순간 이렇게 늘어나 있는걸 몰랐습니다...
그래도 고치는게 많아서 힘들었지만, 반대로 에러가 발생한 부분이 수정 대상인 셈이라
일종에 리팩토링 지표로 삼을 수 있어서 좋았어요.

그리고 허술하더라도 자잘하게 최대한 기능단위 코드를 작성하게 되니, 리팩토링할때 구조 파악하는데 도움을 많이 받았습니다.
제가 짠 소스인데도 며칠 지나고 복잡해지고 하니간 한 눈에 안들어 왔었는데, 이래서 테스트코드와 객체지향으로 약한 연결 관계를 가지려고 하는 것 인가 하는 생각이 들었습니다.

하지만 여기서도 수정사항이 분명히 생기겠지요...
바쁘실텐데 리뷰! 잘 부탁 드립니다.

오늘도 좋은 하루 되세요.
항상 감사합니다.

2021-08-09 12:56 UTC, yongdae requested changes
안녕하세요. 동현님 :)

빠르게 3단계 미션을 진행해주셨네요. 👍
이전 단계의 피드백도 잘 반영해주셨네요!

진행해주신 내용에 대해 몇 가지 의견을 드렸습니다~
확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

2021-08-09 12:56 UTC, yongdae commented on src/main/java/lotto/domain/WinLottoInfo.java
> +public class WinLottoInfo {
당첨 번호를 객체로 잘 표현해주셨네요. 👍 
추가로 WinLottoInfo를 이용해서 당첨 결과(Rank)를 반환하게 만들어보면 어떨까요?

2021-08-09 12:56 UTC, yongdae commented on src/main/java/lotto/domain/Lotteries.java
> +  private LottoResult lottoResult;
Lotteries가 LottoResult를 가지고 있어야 할 이유가 있을까요? 🤔

2021-08-09 12:56 UTC, yongdae commented on src/main/java/lotto/domain/Lotteries.java
> +    if (lotto.getLotto().contains(lottoNumber)) {
Lotto에 한가지 메소드를 추가해보면 좋을 것 같아요!

lotto.getLotto() 를 통해 값을 가져오고 contains(lottoNumber)를 이용하는 것도 좋지만
lotto.match(lottoNumber) 이런 형태로 Lotto에게 일을 시켜보면 어떨까요? 🤔

2021-08-09 12:56 UTC, yongdae commented on src/main/java/lotto/domain/Lotto.java
> +    return numberPull.stream().distinct().count();
```suggestion
    return numberPull.stream()
            .distinct()
            .count();
```
이런 식으로 코드를 변경해보면 좋을 것 같아요. :)

메소드를 통해 기능을 분리하는 것도 좋지만
스트림이나 메소드 체이닝을 사용하는 경우에는 줄바꿈을 통해 표현하는 것도 가능합니다.

이렇게 하는 이유는 한 줄에 모든 일을 나열하면 코드가 길어지고,
보기가 어려운 동시에 이해하기가 어려워지기 때문입니다~

2021-08-09 12:59 UTC, kdh85 commented on src/main/java/lotto/domain/Lotto.java
> +    return numberPull.stream().distinct().count();
코드의 가독성에 조금 더 신경쓰란 말씀이시군요.
확인 후 수정하도록 하겠습니다.

2021-08-09 13:02 UTC, kdh85 commented on src/main/java/lotto/domain/Lotteries.java
> +    if (lotto.getLotto().contains(lottoNumber)) {
아 이 부분도 메세지로 할 수 있었네요.
getter를 덜 사용하도록 좀 더 신경 써보겠습니다.

2021-08-09 14:05 UTC, kdh85 commented on src/main/java/lotto/domain/Lotteries.java
> +  private LottoResult lottoResult;
WinLottoInfo 클래스에서 당첨매칭 관련 프로세스를 기존에 당첨서비스에서 기능을 이관시켰습니다.
이를 통해 불필요하게 lotteris 클래스에 당첨정보를 주입할 필요가 없어지고, 당첨정보가 주체가되어 로또내용을 비교하도록 변경하려 합니다. 이로 인해 당첨정보 객체가 단순 값 포장에서 당점매칭까지를 담당하게 되는데요.
위에 언급하신 WinLottoInfo를 통한 당첨정보반환 작업과 연계될 예정입니다.

2021-08-09 14:06 UTC, kdh85 commented on src/main/java/lotto/domain/WinLottoInfo.java
> +public class WinLottoInfo {
아래 주신 Lotteries의 수정내용과 함께 리팩토링을 해보도록 하겠습니다.

2021-08-10 12:54 UTC, yongdae requested changes
안녕하세요. 동현님 :)

이번에도 열심히 피드백을 반영해주셨네요. 👍 
수고하셨습니다.

반영해주신 내용에 대해 의견 남겨 놓았습니다~
확인하시고 다시 리뷰 요청 부탁드려요. 😄

2021-08-10 12:54 UTC, yongdae commented on src/main/java/lotto/domain/Lotto.java
> +  public boolean match(final LottoNumber lottoNumber) {
Lotto에 판별하는 기능을 넣어주셨네요. 👍 
추가로 boolean 대신 일치하는 숫자 갯수(int)를 반환하게 해보면 좋을 것 같아요.

갯수를 이용하면 Rank에도 응용이 가능 할 것 같은데 어떻게 생각하시나요. 🤔 
힌트: lotto.getLotto().contains()를 완전히 사용 안 할 수 도 있어요!

2021-08-10 12:54 UTC, yongdae commented on src/main/java/lotto/domain/LottoResult.java
>    public Map<Rank, List<Lotto>> getCategoriesRank() {
categoriesRank를 있는 그대로 반환하게 되면
외부에서 마음대로 categoriesRank를 변경 할 수 있는데 그래도 괜찮을까요?

2021-08-10 12:54 UTC, yongdae commented on src/main/java/lotto/domain/WinLottoInfo.java
> +  }
이 3개의 메소드는 테스트를 위해서만 사용되는 것 같아요.
테스트만을 위해서 프로덕션 코드가 만들어지는 일은 지양해야합니다. 😢

2021-08-10 12:54 UTC, yongdae commented on src/main/java/lotto/service/Rank.java
>  public enum Rank {
public static Rank matchRank(int countOfMatch) 메소드도 테스트에서만 사용되는 것 같아요.

2021-08-10 12:54 UTC, yongdae commented on src/main/java/lotto/domain/WinLottoInfo.java
> +  private LottoResult lottoResult;
lottoResult는 사용하지 않는 변수인 것 같아요~

2021-08-10 12:54 UTC, yongdae commented on src/test/java/lotto/domain/WinLottoInfoTest.java
> +  void 로또등급생성자별비교()
WinLottoInfo를 통해 원하는 당첨 결과를 확인 할 수 있게 되었네요. 💯

2021-08-10 13:24 UTC, kdh85 commented on src/main/java/lotto/domain/LottoResult.java
>    public Map<Rank, List<Lotto>> getCategoriesRank() {
Collections.unmodifiableMap을 이용해서 categoriesRank를 불변객체로 만들어 보면 어떨까요?

2021-08-10 13:31 UTC, kdh85 commented on src/main/java/lotto/domain/WinLottoInfo.java
> +  }
TDD로 개발하면서 기본적인 테스트를 하기 위해서 만들었던 코드였던것 같습니다.
GETTER를 쓸일이 없어서 아이러니하게도 테스트용 코드로만 남게되었나 봐요..  아이러니하게도 그만큼 프로덕션 코드에서 GETTER 사용을 안했다는 것이 다행이라는 생각도 듭니다.
여기서 질문을 하나 드리고 싶은데요. 보통 저런 GETTER를 이용한 값 비교보다는 객체자체를 equals 비교를 권장하는 것으로 알고 있습니다.  비교를 위해 equals를 override해야 하는데요.  이러한 행위도 테스트코드에서만 필요해서 하는 것이라면 굳이 만들지 말아야 하는 걸까요? 순수하게 객체를 만드는 초기 tdd 상태에서의 검증할 수단이 애매해지는 기분이긴 합니다. 일단 해당코드는 삭제 할 예정입니다.

2021-08-10 13:31 UTC, kdh85 commented on src/main/java/lotto/domain/WinLottoInfo.java
> +  private LottoResult lottoResult;
코드 리팩토링하는 과정에서 제거를 미쳐 못한 것 같습니다. 제거하도록 하겠습니다.

2021-08-10 14:01 UTC, kdh85 commented on src/main/java/lotto/domain/Lotto.java
> +  public boolean match(final LottoNumber lottoNumber) {
제가 java8을 많이 다루지 않아서 stream과 람다표현식에 많이 서툴어서요.
혼자서 이것저것 만들어보면서 연습중인데요.
(int)lotto.stream()
        .filter(lottoNumber1 -> lottoNumber1.equals(lottoNumber))
        .count();
이런식으로 스트림을써서 조건에 일치하는 카운트 1을 반환하는 식으로 만들어봤습니다.

2021-08-10 14:04 UTC, kdh85 commented on src/main/java/lotto/service/Rank.java
>  public enum Rank {
tdd로 개발하면서 이러한 부분이 가장 난감한 것 같습니다.
어느정도 규모로 프로덕션 코드들이 완성되고, 상호간에 결합도가 아직 있어서 값을 주입하는 부분이 남아있는데요.
한번에 모든걸 리팩토링하지 않을 경우, 컴파일에러가 발생하기 때문에 이런식으로 파라메터기준의 오버라이드식으로 as-is와 to-be가 공존을 종종하게 되었는데요.
놓치면서 삭제를 못하는 일이 자꾸 생기네요.

2021-08-11 01:43 UTC, yongdae commented on src/main/java/lotto/domain/WinLottoInfo.java
> +  }
좋은 질문을 해주셨네요. 👍

이 부분은 개발자마다 견해의 차이가 있는 부분이라고 생각합니다.
개인적인 성향으로는 오로지 테스트만을 위한 코드는 추천하지 않아요. 😢

또한, 객체가 잘 만들어졌는지 확인하는 척도는 "값(변수)"에 있지 않고 "행동(메소드 혹은 함수)"에 있습니다.
이 관점에서 본다면 단순히 값을 확인하기 위해 equals()를 오버라이드해서 사용하는 것보다는
값을 비교하거나 확인해야하는 상황이 발생했기 때문에 equlas()를 오버라이드해서 사용하는 것이 좋습니다.

2021-08-11 02:10 UTC, yongdae requested changes
안녕하세요. 동현님~ :)
빠르게 피드백을 반영해주셨네요. 👍 

진행해주신 내용에 대해 몇가지 의견을 추가로 다시 드렸습니다~
확인하시고 다시 리뷰 요청 부탁드려요. 🙇

2021-08-11 02:10 UTC, yongdae commented on src/main/java/lotto/domain/LottoResult.java
> +    unmodifiableMap(categoriesRank);
unmodifiableMap를 잘못 사용 하게 계신 것 같아요.
반환 값을 이용해야하는데 지금은 호출만하시고 끝내시는 것 같습니다.

지금도 categoriesRank는 변경이 가능해요.

2021-08-11 02:10 UTC, yongdae commented on src/main/java/lotto/domain/LottoResult.java
> +    return this;
반환문을 보면 this를 이용해서 자신을 반환하고 있는데,
새로운 객체나 불변한 객체를 반환하지 않고 자신을 반환했을 때의 이점이 무엇일까요? 🤔

2021-08-11 02:10 UTC, yongdae commented on src/main/java/lotto/domain/WinLottoInfo.java
> +    if(lotto.getLotto().contains(new LottoNumber(bonus))){
Lotto의 match를 사용하면 getLotto()를 사용하지 않아도 될 것 같아요~ :)

2021-08-11 02:10 UTC, yongdae commented on src/main/java/lotto/domain/WinLottoInfo.java
> +    return lotto.getLotto().contains(bonusNumber);
이 부분도요!

2021-08-11 02:10 UTC, yongdae commented on src/main/java/lotto/service/Rank.java
> +  private final boolean matchBonus;
matchBonus를 변수로 가지고 있지 않고 2등 여부를 판별 할 수 있는 방법은 없을까요?

2021-08-11 03:56 UTC, kdh85 commented on src/main/java/lotto/domain/LottoResult.java
> +    unmodifiableMap(categoriesRank);
제가 너무 성급하게 수정한 것 같아요..
그래서 이번에는 확실하게 수정하기 위해 테스트코드를 동반했습니다.
불변으로 선언 후, map에 put을 시도하면 UnsupportedOperationException가 발생한다는 점을 착안해서
에러발생 유도 테스트코드를 작성해 보았습니다.

2021-08-11 04:21 UTC, kdh85 commented on src/main/java/lotto/domain/Lotto.java
> +  public int match(final LottoNumber lottoNumber) {
해당 메소드명 수정 및 테스트코드 추가했습니다.

2021-08-11 04:22 UTC, kdh85 commented on src/main/java/lotto/service/Rank.java
> +  private final boolean matchBonus;
만약 해당 판별값을 사용하지 않고 한다면, 기존에 matchRank 에서 직접 2등 3등을 먼저 판별하는 식으로 접근해야 할 것 같아요. 둘 다 match값이 5인 상태에서, matchBonus 값을 true/false 기준으로 각각 2등과 3등을 반환하는 조건을 먼저 수행하게 하면 될 것 같습니다.

2021-08-11 04:27 UTC, kdh85 commented on src/main/java/lotto/domain/WinLottoInfo.java
> +    if(lotto.getLotto().contains(new LottoNumber(bonus))){
match  반환 값이 1인지 여부를 따지는 방식으로 수정해 보겠습니다.

2021-08-11 04:28 UTC, kdh85 commented on src/main/java/lotto/domain/WinLottoInfo.java
> +    return lotto.getLotto().contains(bonusNumber);
위에 수정안과 동일하게 작업하겠습니다.

2021-08-11 14:07 UTC, yongdae requested changes
안녕하세요~ 동현님 😄

이야기하신 것처럼 지금의 구조는 좋은 의미로 처음과 달라진 부분이 많은 것 같아요!
피드백도 잘 반영해주셨네요. 👍 

자 이제는 "규칙 9: 게터/세터/프로퍼티를 쓰지 않는다." 이 규칙을 적용해보면 좋을 것 같아요.
리뷰를 통해 부분적으로 getter를 사용하지 않았으면 하는 부분에 대해 의견드렸습니다.

확인하시고 다시 리뷰 요청 부탁드려요. 🔥🔥

2021-08-11 14:51 UTC, kdh85 commented on src/main/java/lotto/service/Rank.java
>          .findFirst()
아! 어짜피 findFirst 때문에 SECOND를 먼저 확인하게 되니, matchBonus false만 가지고 Third를 리턴받게 하면 되겠네요.
왜 이런생각을 못했을가요... 감사합니다.

2021-08-11 14:52 UTC, kdh85 commented on src/test/java/lotto/domain/LottoTest.java
> +    Lotto lotto = new Lotto(getSampleLottoNumbers(7));
공통으로 만드는게 더 효율적이라고 생각했었는데, 그냥 간략히 만드는것도 좋은 방법이 될 수 있겠네요.
다시한번 메소드를 공통화 하는 것에 대해서 생각해 봐야겠어요.

2021-08-12 09:56 UTC, kdh85 commented on src/main/java/lotto/domain/Lotteries.java
> +  private List<Lotto> lottos = new ArrayList<>();
객체에서 직접 처리하여 값을 반환하는 방식으로 접근해보겠습니다.

2021-08-12 09:57 UTC, kdh85 commented on src/main/java/lotto/domain/Lotto.java
>    private final List<LottoNumber> lotto = new ArrayList<>();
matchCount에서 힌트를 얻어서 작업해보라는 말씀 이신거 같아요.
비슷한 방식으로 접근해 보겠습니다.

2021-08-12 15:16 UTC, merged

2021-08-13 02:19 UTC, kdh85 commented on src/main/java/lotto/domain/Lotto.java
>    }
matchCount는 로또 번호를 1:1 비교해서 같은 경우 값 1을 로또번호 건단위로 반환하고 있고
matchLotto는 이 것을 받아서 전부 더한값을 Rank에게 전달해서 matchCount에 활용중인데요.
matchCount의 기능은 값을 1:1로 비교하는 것이지만  이 메소드를 호출하여 2등 판별값도 구분하는 곳에서 사용 중이고
당첨로또생성시 보너스번호와 입력한 로또6개의 번호간의 중복성 검사에도 활용하고 있습니다.
제가 생각할때는 이 메소드를 하나로 만든다는건 역할을 별도로 또 부여하는 무엇인가를 다시 만들어야 한다는 말씀으로 들리거든요. 내가 볼 때는 이 두 메소드의 역할이 같다고 생각되지는 않았어요.
일단 이 메소드 두개를 수행하면 각각 리턴하는 값이 다릅니다. 하는 1또는 0을 반환하지만 다른 하나는 0~6을 반환하죠.
여기서 단순히 로또의 객체를 비교하는 행위가 같다는 점에는 동의하지만,  메소드의 리턴값의 용도가 다르다는 점이 다른 역할을 부여한다고 생각합니다.

2021-08-13 02:23 UTC, kdh85 commented on src/main/java/lotto/domain/LottoResult.java
>    private static List<Rank> creatRankInfo() {
로또결과 객체를 만드는 부분을 좀 고민을 해봤었는데요.
처음에 바로 new를 생성하면서 주입해서 인스턴스를 생성하는 방법도 있지만
인스턴스 생성하기전에 결과를 먼저 만들어 내는게 순서가 맞다는 생각이 들었습니다.
결과가 없는 상태에서 불필요하게 new를 먼저 선언할 이유가 없다고 생각했어요.
그래서 static을 이용해서 생성전에 값을 클래스에 주입받아 필요한 정보를 생성하여 new를 통해서 반환해서 하고 싶었습니다.

2021-08-13 02:24 UTC, kdh85 commented on src/main/java/lotto/domain/WinLottoInfo.java
> +  public static final int MATCH_COUNT_NUMBER = 1;
이 부분은 자동생성이 자꾸 public으로 만들어 버리네요. 수정하겠습니다.

2021-08-13 02:25 UTC, kdh85 commented on src/main/java/lotto/domain/LottoNumber.java
> +    return "" + number;
String.valueOf를 사용하면 null에 대한 대응이 되서 문자열일때는 많이 사용했었지만
해당 객체 값이 int인 점을 생각해서 굳이 사용을 하진 않았었는데요.
이 부분이 더 깔끔해보이네요. 수정하겠습니다.

2021-08-13 02:26 UTC, kdh85 commented on src/main/java/lotto/domain/Lotto.java
> +        .collect(Collectors.toList()).toString();
개행을 좀 해서 코드의 가독성을 높이도록 수정하겠습니다.

2021-08-13 02:26 UTC, kdh85 commented on src/main/java/lotto/domain/Lotteries.java
> +    lotteries.lottos.stream().map(Lotto::toString).forEach(System.out::println);
개행을 좀 해서 코드의 가독성을 높이도록 수정하겠습니다.