문자열 덧셈 계산기
next-step/java-lotto pull request #1902
Opened 2021-08-09 09:52 UTC by Woogie924

2021-08-09 13:03 UTC, ksundong requested changes
안녕하세요! 성욱님, 로또 미션 리뷰어로 지정된 김선동입니다. 😊
이번 미션 저와 함께 진행해주셔서 감사합니다!

테스트 코드를 열심히 잘 작성해주셨고, 몇가지 피드백을 남깁니다.
피드백 내용을 수정하시고 다시 리뷰요청을 보내주세요!

고생하셨습니다!
확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-09 13:03 UTC, ksundong commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    private StringAddCalculator stringAddCalculator = new StringAddCalculator();
`JUnit5` 에서는 `class`와 `method`에 `public` 접근제어자를 붙여주지 않아도 괜찮고
일반적으로 붙이지 않고 많이씁니다.

2021-08-09 13:03 UTC, ksundong commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    }
`@ParameterizedTest`로 개선해보세요!

2021-08-09 13:03 UTC, ksundong commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    public void splitAndSum_숫자하나() throws Exception {
왜 모든 메서드가 `throws Exception`이 작성되어있을까요?

2021-08-09 15:15 UTC, Woogie924 commented on src/main/java/calculator/StringAddCalculator.java
> +    private static String negative = "-";
delimiters가 가변적인 멤버변수를 이유로 사용하여서 final을 사용하지 않았는데요,
static final하게 하고
thread safe하게 수정하도록 하겠습니다 :)

2021-08-09 15:16 UTC, Woogie924 commented on src/main/java/calculator/StringAddCalculator.java
> +    private void validate(String data) {
네넵 감사합니다!!

2021-08-09 15:18 UTC, Woogie924 commented on src/main/java/calculator/StringAddCalculator.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(data);
네넵! 문제에 주어진 로직을 그대로 사용하였는데요
리뷰어님 말씀대로 리팩토링이 필요할 것 같아요 진행하도록 할게요!

2021-08-09 15:18 UTC, Woogie924 commented on src/main/java/calculator/StringAddCalculator.java
> +            data = m.group(2);
네넵!!

2021-08-10 13:40 UTC, ksundong approved these changes
안녕하세요! 성욱님!! 리뷰어 김선동입니다. 😊

피드백 내용 수정하시느라 고생 많으셨습니다.
일부 피드백을 추가로 남깁니다. 다음단계 진행하시면서 같이 진행해주세요!

고생하셨습니다!
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-10 13:40 UTC, ksundong commented on src/main/java/calculator/StringAddCalculator.java
> +    }
이부분 개선이 안되었네요 ㅠㅠ

2021-08-10 13:40 UTC, ksundong commented on src/main/java/calculator/StringAddCalculator.java
> +            return 0;
0도 상수로 꺼내면 좋을 것 같아요.
`DEFAULT_RESULT`와 같은 식이면 어떨까요?

2021-08-10 13:40 UTC, ksundong commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    void splitAndSum_null_또는_빈문자(String data) {
`@NullAndEmptySource`를 사용해보시면 어떨까요?

2021-08-10 13:40 UTC, ksundong commented on src/test/java/calculator/StringAddCalculatorTest.java
> +        assertThat(result).isEqualTo(0);
여기는 이제 하나만 있어도 충분하지 않을까요?

2021-08-10 13:40 UTC, merged