3단계 - 로또(2등)
next-step/java-lotto pull request #1914
Opened 2021-08-10 14:54 UTC by jung0930

안녕하세요 리뷰어님! 이번 리뷰도 잘 부탁드립니다 👍

2021-08-11 11:03 UTC, jaeyeonling requested changes
3단계 미션을 잘 구현해주셨어요 👍 
소소한 코멘트 남겨두었으니 확인 부탁드립니다 😄

2021-08-11 11:03 UTC, jaeyeonling commented on src/main/java/lotto/domain/WinningsStatistics.java
> +        List<Result> results = new ArrayList<>();
Result에서 Map<Rank, Integer> 를 가지고 있다면 List를 사용하지 않아도 해당 메서드의 기능들도 넘겨줄 수 있을 것 같은데 어떻게 생각하시나요!?

2021-08-12 08:13 UTC, jung0930 commented on src/main/java/lotto/domain/WinningsStatistics.java
> +        List<Result> results = new ArrayList<>();
말씀해주신대로 진행해보니
List<Result>가 삭제되고 EnumMap<Rank, Integer> rankEnumMap을 가진 일급컬렉션이 만들어졌습니다.
일급컬렉션으로 만들게 되니 자연스럽게 비즈니스 로직이 모이게 되고 알맞는 역할을 가지게 되는거 같습니다. 나중에 사용할 때도 안에 비즈니스 로직을 만들고 사용하면 되니 외부에서 쓸데없는 로직도 줄어드는 것 같구요...!
좋은 의견 주셔서 변경해보았습니다. 확인 한번 부탁드립니다 😊

2021-08-12 08:22 UTC, jung0930 commented on src/main/java/lotto/domain/Rank.java
> +    private static Rank findMatchingRank(final MatchingCount matchingCount, final boolean matchBonus, final Rank rank, final Rank matchingRank) {
Rank에서 험수형인터페이스를 사용하여 하드코딩을 없애보았습니다.
그리고 지금 로직이 외부에서 '맞춘 번호수', '보너스볼 유무' 값을 가지고 해당하는 Rank를 가져와야 하기 때문에 static을 사용하고 있어서, static을 안쓰고 사용하려면 로직이 변경되어야 할 것 같은데요,
static을 쓸 수 밖에 없는 제 로직이 이상한걸까요, 아니면 이 정도는 괜찮은걸까요....?

2021-08-12 08:22 UTC, jung0930 commented on src/main/java/lotto/domain/Rank.java
> +    MISS(new MatchingCount(0), 0),
의견 감사합니다!

2021-08-12 08:23 UTC, jung0930 commented on src/main/java/lotto/domain/purchaseStrategy/AutoNumberGenerationImpl.java
> +public final class AutoNumberGenerationImpl implements NumberGenerationStrategy {
다시 수정하였습니다...!

2021-08-13 10:59 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨어요 👍 
해당 요청은 머지하도록 하겠습니다 마지막 단계도 화이팅입니다~

2021-08-13 10:59 UTC, merged