Step2 로또 자동
next-step/java-lotto pull request #1917
Opened 2021-08-11 04:58 UTC by sangnyyy

리뷰 잘 부탁드립니다!

2021-08-11 12:02 UTC, JunHoPark93 requested changes
안녕하세요 상민님~
본격적으로 로또 미션 시작하셨네요!
잘 구현해주셨습니다 👍
간단한 피드백 몇가지 남겨두었는데요, 확인 후 반영 부탁드릴게요!
궁금한점 편하게 남겨주세요~

2021-08-11 13:13 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> lottoElements = (List<Integer>) LOTTO_ELEMENTS.clone();
List 인터페이스 형의 경우 Clonable 인터페이스을 상속받지 않아서 clone()을 사용할 수 없기 때문에
ArrayList 형으로 해두었습니다 :)

2021-08-11 13:13 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> drawnElements = lottoElements.subList(0, 6);
네이밍을 말씀주시는것일까요?

2021-08-11 13:14 UTC, sangnyyy commented on src/main/java/lotto/service/RankingService.java
> +    public LottoResults calculateMatchHits(List<Integer> lastWeekWinning, Lottos lottos, RankingCalculator calculator) {
넵! 한줄 추가 해두겠습니다! ^^

2021-08-11 13:16 UTC, sangnyyy commented on src/main/java/lotto/domain/Lotto.java
> +    }
말씀하신 부분 동의합니다. 
헌데 궁금한것이 toString() 의 경우 그렇다면 어떤 경우에 사용하는게 적합하다고 생각하실까요?

2021-08-11 13:17 UTC, sangnyyy commented on src/main/java/lotto/domain/WinningNumberParser.java
> +package lotto.domain;
이것도 고민해보겠습니다!

2021-08-11 13:18 UTC, sangnyyy commented on src/main/java/lotto/common/Ranking.java
> +                .orElseThrow(() -> new RuntimeException("2개 이하로는 금액을 보상받을 수 없습니다."));
인자 expect를 받아서 벨리데이션 하는 부분을 말씀주신걸까요?

2021-08-11 13:41 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> lottoElements = (List<Integer>) LOTTO_ELEMENTS.clone();
아래 커밋과 같이 처리해뒀습니다.
https://github.com/next-step/java-lotto/pull/1917/commits/c99007c77f64684948e141a47709d9c0ac2e0ae4

2021-08-11 13:41 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> drawnElements = lottoElements.subList(0, 6);
아래 커밋과 같이 처리해뒀습니다.
https://github.com/next-step/java-lotto/pull/1917/commits/c99007c77f64684948e141a47709d9c0ac2e0ae4

2021-08-11 13:42 UTC, sangnyyy commented on src/main/java/lotto/service/RankingService.java
> +    public LottoResults calculateMatchHits(List<Integer> lastWeekWinning, Lottos lottos, RankingCalculator calculator) {
아래 커밋과 같이 처리해뒀습니다.

https://github.com/next-step/java-lotto/pull/1917/commits/f0a67d459a669c3d50a04bde45e26962d331e28b

2021-08-11 13:50 UTC, sangnyyy commented on src/main/java/lotto/domain/Lotto.java
> +    }
불변리스트와 일급컬렉션간의 관계에 대해 잘 이해가 안되어서 부연설명 좀 더 해주실 수 있을까요?

2021-08-11 14:13 UTC, JunHoPark93 commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> lottoElements = (List<Integer>) LOTTO_ELEMENTS.clone();
클론이 꼭 필요한 부분일까요?
작성해주신 아래의 코드에서,

`List<Integer> drawnElements = lottoElements.subList(0, 6);`

이런식으로 해도 되지않을까요?
`List<Integer> drawnElements = new ArrayList<>(LOTTO_ELEMENTS.subList(0, 6));`

2021-08-11 14:14 UTC, JunHoPark93 commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> drawnElements = lottoElements.subList(0, 6);
이게 한줄만 찝히질 않았네요.. 25line에 0과 6에 대한 상수 추출을 의미했습니다!

2021-08-11 14:16 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> lottoElements = (List<Integer>) LOTTO_ELEMENTS.clone();
@JunHoPark93

우선 clone() 부분은 제거를 했구요! 말씀해주신대로 해서 불필요한 변수를 없앨 수 있을 것 같긴합니다.

2021-08-11 14:17 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> drawnElements = lottoElements.subList(0, 6);
@JunHoPark93

명확하게 해주셔서 감사합니다. 고민해볼게요!

2021-08-11 14:19 UTC, JunHoPark93 commented on src/main/java/lotto/domain/Lotto.java
> +    }
일급컬렉션으로 만든 자료구조를 보호하기위해 사용한다고 생각하시면 좋을 것 같아요. 외부에서 의도치 않게 elements를 수정하는 일을 사전에 아예 방지함으로써 사이드이펙트를 없앨 수 있는 장점이 있습니다.
컬렉션에 원소를 추가할때는 자료구조가 바뀌는것 아닌가? 라고 생각하실 수 있어요. 그때는 추가하는 메서드 내부에 validation을 걸어주면 됩니다. 
설명이 되었을까요?

2021-08-11 14:22 UTC, JunHoPark93 commented on src/main/java/lotto/domain/Lotto.java
> +    }
객체의 정보를 잘 나타내기 위해 사용하는데요, 이 부분은 찾아보시면 많은 자료들을 보실 수 있을거에요.
물론 대괄호로 감싼 숫자의 집합이 로또를 잘 나타낼 수 있는건 맞아요.

하지만 작성해주신 코드형태로 유추해보아 값을 꺼내오는 부분과 대괄호를 감싸는 부분을 나누어주셨어요. 그렇기 때문에 뷰를 그려주는 역할로써 의도가 되었다고 보았습니다.

추가적으로 요구사항이 대괄호가 아닌 중괄호 혹은 다른 기호로 바뀌게된다면 계속해서 도메인 코드를 수정해야합니다. 그런일들을 방지하기 위해 그려주는 로직을 분리하는게 좋구요. 클라이언트 변경사항에 도메인이 영향을 받지 않는 구조가 좋습니다.

2021-08-11 14:25 UTC, sangnyyy commented on src/main/java/lotto/domain/Lotto.java
> +    }
@JunHoPark93

아! 저는 일급컬렉션을 래핑하는 것과 불변(Immutable)의 관계에 대해서 이해가 되지 않는다고 말씀드린것인데
불변객체(혹은 컬렉션)을 이용하는 것에 대해서는 이견이 없습니다.
실제로 코틀린이나 스칼라 같은 언어는 디폴트가 Immutable이고 실제로 이는 말씀주신대로 여기저기서 상탯값이 바뀔 수 있는
사이드 이펙트를 제거할 수 있죠. 말씀주신대로 변경을 해보도록 하겠습니다 :)
(제가 말씀을 이해를 잘못했네요 ㅎㅎ)

2021-08-11 14:30 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> drawnElements = lottoElements.subList(0, 6);
재처리 해뒀습니다. 
https://github.com/next-step/java-lotto/pull/1917/commits/7a6b947a09dbd6a9a03e62788552df8d8d94044d

2021-08-11 14:30 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> lottoElements = (List<Integer>) LOTTO_ELEMENTS.clone();
이 부분도 다시 처리해뒀습니다.

https://github.com/next-step/java-lotto/pull/1917/commits/7a6b947a09dbd6a9a03e62788552df8d8d94044d

2021-08-11 14:40 UTC, sangnyyy commented on src/main/java/lotto/domain/Lotto.java
> +    }
아래와 같이 처리해뒀습니다.
https://github.com/next-step/java-lotto/pull/1917/commits/1a9b65253cb6f7bb5b477a6c71af7808437aaef4

2021-08-11 14:45 UTC, sangnyyy commented on src/main/java/lotto/domain/Lotto.java
> +    }
좋은 의견 감사합니다.
지금까지 작성해온 코드의 형태까지 고려해서 코멘트를 주시다니 그저 감사할 따름이에요 :)
처음 피드백 주셨을땐 큰 이슈 없다고 생각했는데, 같이 코드를 짜는 입장에서 사이드 이펙트가 생길 여지가 있을 수 있다는데 공감하였구요.
클라이언트 변경사항과 도메인 간의 결합도가 낮아지는 것도 공감되는 말씀이네요! 
(toString이 View 레벨로 그려질 때 사용되기 보다는 정말 그 객체의 특징을 잘 보여주기 위한 용도로만 사용해야겠네요 ㅎ)

요 부분도 수정해두겠습니다.

2021-08-11 14:49 UTC, sangnyyy commented on src/main/java/lotto/domain/WinningNumberParser.java
> +package lotto.domain;
말씀주신대로 유틸성  느낌이 강한 관계로 common 으로 이동해보겠습니다.
https://github.com/next-step/java-lotto/pull/1917/commits/20209e191e16f9d6207e32770dff471fa31f8838

2021-08-11 14:50 UTC, sangnyyy commented on src/main/java/lotto/domain/WinningNumberParser.java
> +import java.util.stream.Stream;
아래 커밋과 같이 제거 하였습니다.
https://github.com/next-step/java-lotto/pull/1917/commits/4f3fc51c0794d6eb31d97bf0a381f53fc7c3dc91

2021-08-11 14:50 UTC, sangnyyy commented on src/main/java/lotto/common/Ranking.java
> +                .orElseThrow(() -> new RuntimeException("2개 이하로는 금액을 보상받을 수 없습니다."));
네 맞습니다. 이 부분은 제가 실수한거 같네요. 수정해두겠습니다.

2021-08-11 15:06 UTC, sangnyyy commented on src/main/java/lotto/common/Ranking.java
> +                .orElseThrow(() -> new RuntimeException("2개 이하로는 금액을 보상받을 수 없습니다."));
아래와 같이 테스트코드와 함께 변경해뒀습니다.
https://github.com/next-step/java-lotto/pull/1917/commits/3af3a3f1a3585ce83132da6f07a678e14859f2ab

2021-08-11 15:16 UTC, sangnyyy commented on src/main/java/lotto/domain/Lotto.java
> +    }
아래 커밋과 같이 변경해뒀습니다.

https://github.com/next-step/java-lotto/pull/1917/commits/9ff77af3bcdc1bdec90bca178fc121c9585dbcc2

2021-08-11 15:17 UTC, sangnyyy commented on src/main/java/lotto/domain/Lotto.java
> +    }
포맷팅이 안되어서 ㅎㅎ 수정해두겠습니다. (감안해주세요 ㅎ)_

2021-08-11 15:41 UTC, sangnyyy commented on src/main/java/lotto/domain/Lottos.java
> +public class Lottos {
아래와 같이 수정해뒀습니다.

https://github.com/next-step/java-lotto/pull/1917/commits/8a601d97d8e03584c17973f837f0ac4e2a44d4b1

2021-08-11 15:48 UTC, sangnyyy commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> elements;
아래와 같이 수정해뒀습니다.
https://github.com/next-step/java-lotto/pull/1917/commits/8a601d97d8e03584c17973f837f0ac4e2a44d4b1

다만, 제 생각을 말씀드리면 Integer 를 LottoNumber로 만들어서 말씀주신것과 같이 도메인 검증, 정책등이 들어갈 수 있곘지만
LottoNumber 가 사실상 compareTo() 메서드 한개 밖에 쓰는게 없어서 오버엔지니어링이 되지 않았나 하는 조심스런 견해를 드려봅니다.

물론 이 교육과정이 극단적 OOP 를 지향하기 때문에 프리미티브 타입을 래핑하는 것이 학습 목표에 있고, 또한 LottoNumber 라는 객체가 그 기능을 확장해 나간다는 전제가 있다면 이는 훌륭한 설계가 될 것이라는 것에는 이견이 없습니다. 하지만, XP 에서 말하고 있는 [YAGNI](https://ko.wikipedia.org/wiki/YAGNI)와 같은 원칙도 존재하듯이 Integer로 사용중인 로또 원소들에 뭔가 변경이나 기능추가가 필요하다고 판단이 설 때 위와 같이 래핑클래스를 사용하는것도 방법이지 않을까 생각이 들어 말씀드려 봅니다 :)

2021-08-11 23:49 UTC, JunHoPark93 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> elements;
맞습니다. 저도 상민님 의견에 전적으로 동의합니다. 저도 실무에서는 필요에 의해서 생성해야한다고 생각해요.
하지만 지금 저희가 하고있는 과정은 극단적으로 훈련을 함으로써 좋은 설계를 할 수 있는 힘을 기르는데있습니다.

예를 들자면, 운동선수가 모래주머니를 차고 훈련을 하는모습을 보신적이 있을거에요. 실제 경기에서는 모래주머니를 차고 경기에 뛰는것은 당연히 아니겠죠. 
촉박한 시간, 어떻게보면 아름다운 골보다는 어떻게든 골을 넣어야 한다는 강박, 심리를 흔들 수 있는 여러 주변 환경들.. 등등.
이런 주변환경들을 이겨낼 수 있는 원초적인힘이 어떻게 보면 모래주머니를 차고 힘들게 훈련했던 기본도 한몫했을거에요.

이와 마찬가지로 저희가 함께하고있는 미션은 여유로운시간, 편한환경에서 극단적으로 메서드의 길이를 줄여보고, 원시값을 전부 포장해보고 하는 고된 작업들을 하고있는거구요. 
실제 서비스환경에서 촉박한 일정과 힘든 환경에서 고객에게 가치를 어떻게 전달해야 하나라는 비지니스적 고민이 우선순위가 높을일이 많기 때문에 지금하는 훈련들이 위의 환경에서 개발적으로 좋은 결과물을 만들 수 있는 힘이 될거에요.

말이 장황해졌는데요, 의도가 잘 전달 됐으면 좋겠네요. 조금이라도 이해가 더 필요한 부분은 언제든 다시 남겨주세요 :)

2021-08-11 23:50 UTC, JunHoPark93 commented on src/main/java/lotto/domain/Lotto.java
> +    }
이 부분은 제가 모호하게 전달 했던거 같아요. 다음에는 좀 더 명확히 전달하도록 하겠습니다 :)

2021-08-11 23:57 UTC, JunHoPark93 approved these changes
안녕하세요 상민님~
피드백 빠르게 반영해주셨네요!
잘해주셨습니다. 몇 가지 코멘트 남겨두었는데요 다음 step진행하실떄 참고부탁드려요.
많은 의견교환 및 소통이 있어서 좋았습니다 👍
질문주신 부분들은 재코멘트 남겨두었습니다. 추가적으로 궁금한점은 언제든 남겨주세요~
다음 step에서 뵙겠습니다!

2021-08-11 23:57 UTC, JunHoPark93 commented on src/main/java/lotto/common/Ranking.java
> +        return getCompensationIfExpectMatchOverThree(expect);
로직이 좀 더 견고하게 된것 같아요 👍

2021-08-11 23:57 UTC, JunHoPark93 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
잘해주셨습니다 👍
다만 인스턴스 변수 선언의 위치를 상단으로 올려야 될 것 같아요 :) 다음 step진행하시면서 컨벤션도 한번씩 확인 부탁드릴게요!
객체를 포장하면서 이 객체의 역할이 어떤것이 있을지 생각해보시면 좋을 것 같습니다. 
예를 들어, 로또 번호는 숫자의 제한이 있기 때문에 생성자에서 생성할때 해당 숫자를 validation하는것도 방법이 될 수 있구요, 정답은 없으니 고민해보셔요!

2021-08-11 23:57 UTC, JunHoPark93 commented on src/main/java/lotto/domain/LottoTickets.java
> +        return lottoTickets;
```suggestion
        return Collections.unmodifiableList(lottoTickets);
```

2021-08-11 23:57 UTC, merged

2021-08-12 01:05 UTC, sangnyyy commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
IDE 를 통해서 getter 를 찍어내다보니 ㅎㅎㅎ 주의하겠습니다.