Step2
next-step/java-lotto pull request #1933
Opened 2021-08-13 14:06 UTC by sangw0804

2021-08-14 06:12 UTC, dbeod2 requested changes
안녕하세요! 상우님
로또 2단계 미션 잘 해주셨습니다.👏🏻👏🏻👏🏻

몇가지 코멘트 드린 부분이 있습니다! 
확인 부탁드리며 리뷰 재요청 주세요! 🙇🏻‍♀️

2021-08-14 06:12 UTC, dbeod2 commented on src/main/java/lotto/model/LottoResult.java
> +    public static LottoResult from(int winningCount) {
from이라는 네이밍이 조금 어색하네요 
좀더 명확한 네이밍으로 수정해보시는건 어떠실까요?

2021-08-15 07:33 UTC, sangw0804 commented on src/main/java/lotto/model/LottoNumbers.java
> +    private final Set<LottoNumber> numbers;
로또에서 번호는 
- 1.순서가 없고
- 2. 중복되면 안됨
이 조건이 맞아야 한다고 생각해서 Set 으로 구현하였는데요, 중복 번호를 입력하면 오류가 발생하는 부분은 의도한 부분이었습니다!
아니면, 해당 익셉션을 뷰 레벨이서 잡아서 다시 입력하도록 처리를 구현하는게 나으려나요?

2021-08-15 07:35 UTC, sangw0804 commented on src/main/java/lotto/model/RandomLottoNumbersGenerator.java
> +        List<Integer> numbers = IntStream.range(LottoNumber.MIN_NUMBER, LottoNumber.MAX_NUMBER + 1).boxed().collect(Collectors.toList());
요부분은 view에서 출력할때 정렬하는걸로 해결해 보았습니다!

2021-08-15 07:42 UTC, sangw0804 commented on src/main/java/lotto/view/InputView.java
> +        while (raw == null || raw.isEmpty()) {
```java
System.out.println("지난 주 당첨 번호를 입력해 주세요.");
String raw = scanner.nextLine();
while (raw == null || raw.isEmpty()) {
  System.out.println("지난 주 당첨 번호를 입력해 주세요.");
  raw = scanner.nextLine();
}
```

요렇게 구현해도 되긴 하는데요, sout 두번 중복으로 쓰여지는 것보다 처음에 null 세팅하고 무조건 반복문으로 한번 진입하는 게 더 깔끔해 보여서 저는 코드처럼 구현하였습니다!

2021-08-15 07:43 UTC, sangw0804 commented on src/main/java/lotto/view/InputView.java
> +        while (raw == null || raw.isEmpty()) {
```java
return Arrays.stream(raw.split(","))
            .map(String::trim)
            .map(Integer::parseInt)
            .collect(Collectors.toList());
```

이 코드를 말씀하시는 걸까요?? 음, 제가 느끼기에는 요부분은 확실히 인풋값 처리에 대한 부분이라고 생각했습니다. 예를 들어, 만약 입력 로또 번호를 , 가 아니라 & 로 구분해서 받는것으로 요구사항이 바뀌면, LottoNumber 클래스를 수정하는 것 보다 InputView 클래스를 수정하는 것이 자연스러운거 같아서요!

2021-08-15 07:58 UTC, sangw0804 commented on src/main/java/lotto/model/LottoChecker.java
> +public class LottoChecker {
우승 로또 번호를 가지고 있고, 한 로또를 받아서 해당 로또의 결과를 리턴하는 역할을 합니다( 로또 검사기?판정기? 같은 역할을 생각했습니다.)

2021-08-15 09:00 UTC, sangw0804 commented on src/main/java/lotto/model/LottoResult.java
> +public enum LottoResult {
이름 부분은 수정해 두었습니다 (_ _)

Lose 는 2개 / 1개 /  0개 맞춘 경우에 모두 Lose 이기 때문에 요렇게 두었는데, 어떤 부분이 걸리실까용??

2021-08-16 01:23 UTC, dbeod2 approved these changes
안녕하세요! 상우님 

피드백 잘 반영해주셨고, 질문해주신 부분에 대해서 답변도 달았습니다. 👍🏻
한 가지 코멘트 답변 드렸는데 그부분은 다음단계에서 반영해주셔도 될 것 같아서 
이번미션 머지하겠습니다!!

2021-08-16 01:23 UTC, merged