step2 - 리뷰 요청 드립니다.
next-step/java-lotto pull request #1939
Opened 2021-08-14 09:40 UTC by sixthou

2021-08-15 04:55 UTC, ep1stas1s requested changes
이전 스텝 리팩토링 잘 해주셨네요 👍 
이번 스텝도 코멘트 참고해보시고 리팩토링 진행 부탁드릴게요~!
혹시나 궁금한 사항 있으면 언제든 DM주세요 ^_^

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/view/InputView.java
> +    Scanner scanner = new Scanner(System.in);
deafault 접근제한자를 사용하신 이유가 있으실까요~?

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoGame.java
> +    private final int ONE_GAME_PRICE = 1000;
```suggestion
    private static final int ONE_GAME_PRICE = 1000;
```

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumberSelector.java
> +import java.util.ArrayList;
사용하지 않는 코드는 지워주세요ㅎㅎ

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoTicket.java
> +    private int collectNumber = 0;
모든 클래스들을 최대한 불변객체로 만들어보는게 어떨까하는데요~
비록 priavte이지만 나중에 set하는 방식보다, 생성자에서 의미있는 값들을 전달받아 초기화 하는게 어떨까요??

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumberSelector.java
> +public class LottoNumberSelector {
Private 생성자를 만들어주면 오용을 줄일 수 있겠네요 ^_^

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumberSelector.java
> +        }
subList(...)메서드를 쓰면 더 깔끔하게 가능할 거 같아요ㅎㅎ

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumberSelector.java
> +    private static final Integer LOTTO_NUMBER_SIZE = 6;
wrapper class를 사용하신 이유가 있을까요~?

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final List<Integer> lottoNumbers;
클래스명만 봐서는 하나의 로또 숫자를 뜻할 것 같았는데, 실제로는 여러 개의 로또 숫자를 가지고 있네요 🤔

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumber.java
> +    public LottoNumber() {
숫자를 주입받으면 조금 더 테스트하기 용이할 것 같네요 :)

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumber.java
> +    public String getNumberString() {
요 메서드는 뷰에서 사용하는데요~
만약 콘솔환경이 아니라, 웹 환경으로 변경되면 어떻게 될까요?

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoRank.java
> +    RANK_1ST(6, 2000000000),
일반적으로 사용할 때 `LottoRank.Rank_1ST`와 같이 사용하므로 FIRST로만해도 의미가 잘 전달될 것 같아요~!

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoRank.java
> +    RANK_2ND(5, 1500000),
```suggestion
    RANK_2ND(5, 1_500_000),
```
언더스코어를 통해 가독성을 높일 수 있습니다 ^_^

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoRank.java
> +    RANK_7TH(0, 0);
로또 도메인 상, 5등, 6등, 7등은 모두 `꽝!`을 의미하니, 통합해보는건 어떨까요ㅎㅎ

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoRank.java
> +        return LOTTO_RANK_MAP.get(collectNumber);
Map의 다른 API를 사용하여 null처리도 해보시면 좋을 것 같습니다 :)

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/LottoApplication.java
> +        lotto.setWinningNumber(inputView.getNumber());
미션 진행동안 `set`은 아예 사용하지 않는다고 생각하시고 코드를 작성해주세요 😅

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoWinningNumber.java
> +    private final List<Integer> winningNumbers = new ArrayList<>();
`LottoNumber` 클래스와 크게 다른 부분이 없는 것 같은데 같이 사용하는건 어떨까요?

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoWinningNumber.java
> +    public void selectWinningNumbers(final String winningNumbersString) {
`LottoWinningNumber`가 파싱하는 것까지 해야할까요...?

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoGame.java
> +public class LottoGame {
이름만 봐서는 `LottoGame`와 `Lotto`의 역할이 반대같다는 느낌이 드네요...ㅎㅎㅎ;

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoWinningPolicy.java
> +    private final Map<LottoRank, Integer> result = Arrays.stream(LottoRank.values())
EnumMap이란 친구를 사용해보셔도 좋을 것 같습니다

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoWinningPolicy.java
> +    public int getPrice() {
계산한다는 의미의 메서드명이면 좋겠네요!

2021-08-15 04:55 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoWinningPolicy.java
> +        sum += result.get(LottoRank.RANK_1ST) * LottoRank.RANK_1ST.getPrice();
하드코딩을 줄여볼 수 있을까요~?

2021-08-15 08:25 UTC, sixthou commented on src/main/java/lotto/view/InputView.java
> +    Scanner scanner = new Scanner(System.in);
접근제한자 설정을 빼먹었네요. 수정했습니다!

2021-08-15 08:25 UTC, sixthou commented on src/main/java/lotto/domain/LottoGame.java
> +    private final int ONE_GAME_PRICE = 1000;
반영했습니다!

2021-08-15 08:25 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumberSelector.java
> +import java.util.ArrayList;
넵!

2021-08-15 08:26 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumberSelector.java
> +public class LottoNumberSelector {
private 생성자 생성 추가했습니다.

2021-08-15 08:26 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumberSelector.java
> +        }
subList가 있었네요..

2021-08-15 08:27 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumberSelector.java
> +    private static final Integer LOTTO_NUMBER_SIZE = 6;
프리미티브 타입으로 변경했습니다.

2021-08-15 08:27 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final List<Integer> lottoNumbers;
LottoNumbers로 변경하였고, WinningNumber도 동일하게 WinningNumbes로 변경하였습니다.

2021-08-15 08:28 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumber.java
> +    public String getNumberString() {
리스트를 그대로 출력해도 됐네요. getNumberString 삭제 했습니다.

2021-08-15 08:28 UTC, sixthou commented on src/main/java/lotto/domain/LottoRank.java
> +    RANK_1ST(6, 2000000000),
수정했습니다.

2021-08-15 08:29 UTC, sixthou commented on src/main/java/lotto/domain/LottoRank.java
> +    RANK_2ND(5, 1500000),
숫자에 언더스코어를 사용할 수 있었네요...

2021-08-15 08:29 UTC, sixthou commented on src/main/java/lotto/domain/LottoRank.java
> +    RANK_7TH(0, 0);
FAIL을 만들어 통합했습니다.

2021-08-15 08:31 UTC, sixthou commented on src/main/java/lotto/domain/LottoWinningPolicy.java
> +        sum += result.get(LottoRank.RANK_1ST) * LottoRank.RANK_1ST.getPrice();
변경했습니다.

2021-08-15 08:31 UTC, sixthou commented on src/main/java/lotto/domain/LottoWinningPolicy.java
> +    public int getPrice() {
변경했습니다.

2021-08-15 08:33 UTC, sixthou commented on src/main/java/lotto/domain/LottoWinningPolicy.java
> +    private final Map<LottoRank, Integer> result = Arrays.stream(LottoRank.values())
EnumMap을 사용하여 변경하였습니다. stream으로 초기화 해보고 싶은데 HashMap과는 방법이 다른 것 같아. 일단 하드코딩 형태로 초기화 하였습니다.

2021-08-15 09:11 UTC, sixthou commented on src/main/java/lotto/domain/LottoGame.java
> +public class LottoGame {
이름만 봐서는 그렇게 보이기도 하겠어요. 수정했습니다.

2021-08-15 11:12 UTC, sixthou commented on src/main/java/lotto/domain/LottoWinningNumber.java
> +    public void selectWinningNumbers(final String winningNumbersString) {
파싱부분 분리하여 숫자만 받도록 수정하였습니다.

2021-08-15 15:31 UTC, sixthou commented on src/main/java/lotto/domain/LottoWinningNumber.java
> +    private final List<Integer> winningNumbers = new ArrayList<>();
LottoNumbes로 통합하였습니다.

2021-08-15 16:09 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumber.java
> +    public LottoNumber() {
인터페이스 생성해서 주입 받도록 수정 했습니다.

2021-08-15 19:13 UTC, sixthou commented on src/main/java/lotto/domain/LottoTicket.java
> +    private int collectNumber = 0;
LottoRank와 collectNumber는 추후에 입력되는 당첨 번호에 따라 변화되는 값인데 이것도 불변객체로 만들어서 진행이 가능한가요?

2021-08-15 19:13 UTC, sixthou commented on src/main/java/lotto/domain/LottoRank.java
> +        return LOTTO_RANK_MAP.get(collectNumber);
optional 을 사용하여 처리 했습니다.

2021-08-15 19:15 UTC, sixthou commented on src/main/java/lotto/LottoApplication.java
> +        lotto.setWinningNumber(inputView.getNumber());
추후에 입력되는 당첨번호를 set없이 어떻게 처리할까 고민하다보니, lotto 가 WinningNumber을 가지고 다닐 필요가 없었습니다. 
의존성을 분리 하였고, 입력되는 값을 넘겨 처리하도록 수정 했습니다.

2021-08-16 07:22 UTC, ep1stas1s requested changes
리팩토링 잘 진행해주셨네요 👍 
추가적으로 짚고 넘어가면 좋을 것 같아서... 몇 가지 코멘트를 더 남겼습니다ㅎㅎㅎ;
혹시라도 의미가 제대로 전달되지 않은 부분이 있을 수 있으니 궁금하신 부분있으면 언제든 DM주세요~!

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumberRandomSelector.java
> +    private final int LOTTO_NUMBER_SIZE = 6;
```suggestion
    private static final int LOTTO_NUMBER_SIZE = 6;
```

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumberRandomSelector.java
> +    private final List<Integer> numbers = Stream.iterate(1, i -> i + 1)
요 친구도 미리 만들어놓고 재사용해도 좋겠네요!

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoRank.java
> +            .orElse(LottoRank.FAIL);
엇 위에 코멘트의 의도는 요런 방식이었습니다ㅎㅎ
```suggestion
        return LOTTO_RANK_MAP.getOrDefault(collectNumber, LottoRank.FAIL);
```

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoResult.java
> +    };
map의 getOrDefault(...)를 사용하면 꼭 0을 초기화하지 않아도 될 것 같아요
(만약 초기화가 필요하다면 생성자를 사용하면 더 깔끔할 것 같습니다ㅎㅎ)

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoResult.java
> +    public void setResult(final Lotto lotto) {
반복되는 내용이긴하지만...
LottoTicket들과 당첨 번호들을 비교하면서 생성되는 map을 통해 LottoResult 객체를 생성하면, setter가 필요 없을 것 같은데 어떻게 생각하시나요~?

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoResult.java
> +        for (LottoRank lottoRank : LottoRank.values()) {
지금은 result가 모든 LottoRank를 키로 가지고 있어 동일하게 동작하지만
result의 entrySet를 추출하여 계산하는게 더 명확할 것 같습니다!

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/view/OutputView.java
> +    public void printResult(Map<LottoRank, Integer> result) {
요기의 하드코딩도 변경해보면 좋을 것 같습니다ㅎㅎ

2021-08-16 07:22 UTC, ep1stas1s commented on src/test/java/lotto/domain/LottoGameTest.java
> +package lotto.domain;
테스트가 많이 빈약하네요 😢 
도메인에 해당하는 클래스의 public method는 전부 테스트한다고 생각하고 진행해주세요ㅎㅎ!

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/view/OutputView.java
> +        System.out.println("총 수익률은" + profitRatio + "입니다.(기준이 1이기 때문에 결과적으로 손해라는 의미임)");
printf 라는 친구도 있느니 활용해보시면 좋을 것 같습니다ㅎㅎ

2021-08-16 07:22 UTC, ep1stas1s commented on src/main/java/lotto/domain/Lotto.java
> +        return tickets;
```suggestion
        return Collections.unmodifiableList(tickets);
```

2021-08-16 08:34 UTC, sixthou commented on src/main/java/lotto/controller/LottoController.java
> +        LottoResult lottoResult = new LottoResult();
변경했습니다.

2021-08-16 08:34 UTC, sixthou commented on src/main/java/lotto/controller/LottoController.java
> +        int price = Integer.parseInt(inputView.inputPrice());
view에서 파싱하도록 변경 하였습니다.

2021-08-16 08:35 UTC, sixthou commented on src/main/java/lotto/domain/LottoGame.java
> +        lotto = buyLotto(lottoNumberSelectPolicy);
생성자에서 처리하도록 변경 하였습니다.

2021-08-16 08:39 UTC, sixthou commented on src/main/java/lotto/domain/LottoGame.java
> +        return lotto.getTicketSize();
size로 수정 하였습니다. LottoGame에서의 size 뿐이라 다른쪽에도 size관련 메소드가 있는데 동일하게 size로 통일하는게 맞는건가요?
어떤 사이즈인지에 대해서 메소드명을 작성하는게 더 명시적이라고 생각이 되어 질문 드립니다.

2021-08-16 08:39 UTC, sixthou commented on src/main/java/lotto/controller/LottoController.java
> +        outputView.printTickets(lottoGame.getLotto());
view에서 lottoGame을 넘겨 받고 처리하도록 수정하였습니다.

2021-08-16 08:44 UTC, sixthou commented on src/main/java/lotto/controller/LottoController.java
> +        }
view에서 파싱까지 저리하도록 수정 하였고, 유틸 신규로 생성하였습니다.

2021-08-16 08:44 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumbers.java
> +    public Boolean contains(int number) {
변경하였습니다.

2021-08-16 08:45 UTC, sixthou commented on src/main/java/lotto/domain/LottoNumberRandomSelector.java
> +    private final int LOTTO_NUMBER_SIZE = 6;
변경하였습니다.

2021-08-16 08:45 UTC, sixthou commented on src/main/java/lotto/domain/LottoRank.java
> +            .orElse(LottoRank.FAIL);
이런 메소드가 있었네요...

2021-08-16 08:46 UTC, sixthou commented on src/main/java/lotto/view/OutputView.java
> +    public void printResult(Map<LottoRank, Integer> result) {
변경하였습니다!

2021-08-16 08:47 UTC, sixthou commented on src/main/java/lotto/view/OutputView.java
> +        System.out.println("총 수익률은" + profitRatio + "입니다.(기준이 1이기 때문에 결과적으로 손해라는 의미임)");
printf 를 사용하도록 변경하였고, printResult 에도 적용하였습니다.

2021-08-16 08:47 UTC, sixthou commented on src/main/java/lotto/domain/Lotto.java
> +        return tickets;
여기서는 또 빼먹었었네요..ㅠㅠ

2021-08-16 10:32 UTC, sixthou commented on src/main/java/lotto/domain/LottoResult.java
> +        for (LottoRank lottoRank : LottoRank.values()) {
넵  변경 했습니다.

2021-08-16 16:07 UTC, sixthou commented on src/main/java/lotto/domain/LottoTicket.java
> +    private int collectNumber = 0;
private LottoRank lottoRank;
    private int collectNumber = 0;
    삭제 하였습니다. 
    당첨번호를 입력받아 LottoRank를 반환하도록 수정하였습니다 .

2021-08-19 00:27 UTC, ep1stas1s approved these changes
스텝2 정말 고생많으셨습니다 👍 
다음 스텝 진행해주세요~
(알림을 못 봤더니 많이 늦어졌네요ㅠ_ㅠ 죄송합니다... 🙏 )

2021-08-19 00:27 UTC, ep1stas1s commented on src/test/java/lotto/domain/LottoTicketsTest.java
> +class LottoTicketsTest {
테스트 추가 👍

2021-08-19 00:27 UTC, merged

2021-09-02 00:38 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoGame.java
> +        return lotto.getTicketSize();
다른 쪽이라는건 아예 다른 클래스를 말씀하시는 거 겠죠?
클래스 성향에 따라 다를 것 같은데 컬렉션이 메인이 되는 클래스인 경우엔 size만으로도 충분하다고 생각합니다ㅎㅎ
반면에 컬렉션이 서브인 필드의 경우는 명시해줘도 나쁘지 않을 것 같네요 ^_^