Step4 로또 수동
next-step/java-lotto pull request #1947
Opened 2021-08-15 05:09 UTC by yongsoo-kim

안녕하세요 지훈님!
이번 로또 수동기능을 추가하면서, 기존에 부족하다고 느꼈던 코드의 많은 부분을 수정했습니다.
대표적으로는 다음과 같습니다.

1. 수동티켓장수, 입력금액등 원시타입으로 선언되었던 변수들을 원시값 포장객체로 포장함.
2.  사용자 -> 로또판매자(vendor) -> 로또 티켓 판매기기 의 흐름을 명확하게 하기위해 메서드 재분배및 변수명 수정.
3. 로또당첨정보(LottoReward)를 if절을 사용해 "빠른리턴 "을 하도록 구현

이정도가 되겠네요. 개인적으로 로또 티켓 발행기기안에 중첩클래스를 사용해 좀더 캡슐화를 시도해보았으나, 잘 되지 않았습니다.  혹시 같이 고민해 주실수 있으신가요?

2021-08-15 05:15 UTC, yongsoo-kim commented on src/main/java/lotto/domain/IssueInput.java
> +public class IssueInput {
이 클래스는 로또티켓기계(LottoTicketMachine)에 사용자의 입력을 전달하기 위해 작성되었습니다.
즉, DTO의 역할을 하고 있는데... 이러한 DTO클래스는  로또티켓기계 클래스 내부에 static inner클래스로 선언해도 될까요? 제가 찾아보니 그러는게 좋다는 의견도 있어서 어떻게 할지 고민입니다.

장점: 이미 생성된 클래스 안에 생성하므로, 새로운 클래스를 만들지 않아도 된다.
단점: static inner클래스가 들어간 외부 클래스의 코드 크기가 커져 보기 싫다.

참고:
https://velog.io/@p4rksh/Spring-Boot%EC%97%90%EC%84%9C-%EA%B9%94%EB%81%94%ED%95%98%EA%B2%8C-DTO-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

2021-08-15 05:17 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
전단계에서 Stream의 filter를 이용해 2등과 3등의 구분을 하려는 시도를 해보았습니다만,  개인역량의 문제인지 코드가 더 지저분해 보였습니다. 저는 오히려 이런 빠른 리턴으로 구분을 해주는것이 훨씬 읽기 좋다고 판단, 이렇게 되돌려보았습니다.  각각 장단점이 있겠습니다만, 어떻게 생각하시나요?

2021-08-15 05:26 UTC, yongsoo-kim commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +
이부분은 중첩클래스를 써서 "로또발행방법"과 "발행후 결과타입"을 한데 묶고 싶었으나, 잘 해결이 안되었습니다.
예를 들자면 이렇습니다.
`private enum  IssueType{
        AUTO(new AutoWay(),e -> new AutoLottoTickets(e)),
        MANUAL(new ManualWay(),e -> new ManualLottoTickets(e))
    }`
  이렇게 작성할시 AutoLottoTickets단에서 "List파라메터를 기대했는데 lambda파라메터가 넘어왔습니다." 라는 에러가 뜹니다.  해결할 방법이 있을까요? 아니면 더 좋은 접근 방식이 있을까요?
 
![image](https://user-images.githubusercontent.com/13756541/129468078-2d218c2c-b55e-4763-b6a8-f84acb69e8a0.png)

2021-08-15 07:25 UTC, vagabond95 requested changes
전반적으로 크게 리펙토링이 이루어졌네요! 쉽지 않으셨을텐데 열정을가지고 하시는 모습 멋지십니다 👍 

질문주신 내용과 몇가지 구현 내용에 대해 코멘트 남겼는데요, 확인 후 다시 리뷰요청 부탁드립니다!

2021-08-15 07:25 UTC, vagabond95 commented on src/main/java/lotto/domain/AutoLottoTickets.java
> +public class AutoLottoTickets {
ManualLottoTickets 와 AutoLottoTickets 는 내부 코드 차이가 없어보이는데요, 
굳이 각각의 클래스로 분리할필요가 있을까요?

2021-08-15 07:25 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoGameVendor.java
> +        TicketCount availableCnt = getAvailableTicketCount(order);
축약어 사용은 지양해주세요~!

2021-08-15 07:25 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +    public AutoLottoTickets issueTicketsByAutoWay(IssueInput input) {
```suggestion
    public AutoLottoTickets buyTicketsByAutoWay(IssueInput input) {
```
와 같은 네이밍이 좀 더 직관적이지 않을까요?

2021-08-15 07:25 UTC, vagabond95 commented on src/main/java/lotto/domain/IssueInput.java
> +public class IssueInput {
저는 static inner 클래스로 DTO 선언하는것을 선호하지는 않습니다.

이유는, inner 클래스로 선언된다는 것은 해당 모델의 하위 도메인의 속성을 가진다고도 이해할 수 있는데 해당 DTO 가 꼭 그 모델에서만 쓰인다는 법이 없기 때문입니다. 공용 클래스로 쓰고자 하면 inner 에서 다시 뺴내는 작업이 필요하여 불필요한 diff 가 생기고, inner 에 존재하는 것을 알지 못해 중복된 클래스를 생성하는 경우도 많았어서 개인적으로는 지양하는 편입니다 ㅎㅎ

2021-08-15 07:25 UTC, vagabond95 commented on src/main/java/lotto/domain/IssueInput.java
> +public class IssueInput {
위 질문과 별개로 IssueInput 이 꼭 필요한 클래스인지는 의문이 생기는 것 같습니다.

로또 번호를 추출하는 방법을 인터페이스화하고 해당 인터페이스에 단일한 파라미터를 던져주기 위해 사용되는 것으로 보이는데요, 

각 LottoTicketingWay 의 구현체를 보면 IssueInput 의 필드를 모두 활용하는 것이 아니라 필요한 것만 골라서 사용이 되고 있습니다. 만약 LottoTicketingWay 를 구현할 수 있는 방법이 N 개라면 N개의 필드가 들어가게 될텐데 사용하는 입장에서는 알아야할 정보/신경써야할 포인트가 너무 많아질 것 같습니다.

2021-08-15 07:25 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +
람다식의 정의를 어떻게 구현하신지는 모르겠으나, 람다식의 인자인 e 에 대한 정보가 모호하므로 생기는 이슈인 것 같습니다. 

그리고 다른 코멘트에 남겼듯이 ManualLottoTickets 와 AutoLottoTickets 가 각각 구분되어져 만들어질 이유가 없을 것 같고, 해당 클래스가 통합된다면 enum 으로 묶는 시도도 크게 의미는 없을 것 같습니다!

2021-08-15 07:25 UTC, vagabond95 commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
저는 오히려 해당 코드의 가독성이 훨씬 떨어질 수 있는 코드라고 생각됩니다.

특정 등수에 영향을 받는 코드가 들어가게 되면, 이 코드를 보는 개발자의 입장에서는 1) 등수 자체의 비즈니스 로직과 2) 특정 등수의 비즈니스 로직을 모두 이해해야 합니다.

또한, 이러한 방식은 변경에도 취약한 것이 특정 등수에 대한 요구사항 하나만 바뀌더라도 코드에 무조건적으로 변경이 발생할 수 밖에 없습니다.

2021-08-15 09:15 UTC, yongsoo-kim commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +    public AutoLottoTickets issueTicketsByAutoWay(IssueInput input) {
"로또티켓기계(LottoTicketMachine)" 는 로또를 "발행해주는" 일을 하지, "로또는 사는" 행위는 하지 않는다고 생각해서 이러한 이름으로 짓게되었습니다. 돈에 관련된 파라메터도 없구요.
실제로 돈을 받는쪽은 "로또게임업자(LottoGameVendor)" 이고, 이클래스에는 "buyLottos"라는 메서드가 있습니다.
저는 이 이름이 그렇게 나쁘지 않다고 생각합니다만 어떻게 생각하시나요?

2021-08-15 09:24 UTC, yongsoo-kim commented on src/main/java/lotto/domain/IssueInput.java
> +public class IssueInput {
그렇군요. 저는 "티켓을 발행한다" 라는 행위를 추상화해서, 가령 새로운 로또티켓 발행방법이 생기더라도 거기에 유연하게 대처할수 있지 않을까라고 생각해서 이러한 구조를 생각하게 되었습니다. 제생각은 이런데 어떻게 생각하세요?

지금주신 답변을 바탕으로, 지훈님은   "티켓을 발행한다(LottoTicketingWay)"  라는 추상행위 즉 인터페이스를 삭제하는게 좋다고 생각하시나요?

2021-08-15 09:34 UTC, yongsoo-kim commented on src/main/java/lotto/domain/AutoLottoTickets.java
> +public class AutoLottoTickets {
내부코드의 차이는 없지만, 다음과 같은 장점들이 있습니다.
1.발행된 티켓들이 어떤 방식으로 발행된 티켓인지 알기 쉽다.
2.발행된 티켓들의 수동, 자동 각각의 타입이 몇장인지 금방셀수있다.

"어떤 방식으로" 발행된 로또 티켓인지를 구별하는 또하나의 방법으로는 ManualLottoTickets  과 AutoLottoTickets 쓰지 말고, LottoTicket에 "발행타입"변수를 추가해서 만드는 방법이 있는데요, 

이경우에는 다음과 같은 단점들이 있을것 같습니다.
1. "자동 및 수동" 타입을 구별하기 위해 Stream이나 For문을 사용해야합니다.  티켓이 많아질수록 처리속도가 느려지지 않을까요?
2. 티켓한장을 생성하기위해서 "6개의 숫자"뿐만 아니라 "어떤타입으로 발행되었는지"를 일일이 지정해주어야합니다.  당첨티켓은 "수동"타입일까요? "자동"타입일까요?

저도 꽤 많이 고민했지만, 이방식을 택했습니다. 어떻게 생각하시나요?

2021-08-15 09:40 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
답변 감사합니다.
"특정등수에 영향을 받는 코드" 는 반드시 만들어질수 밖에 없지않나요?
"5 개의 숫자가 일치하고"와 "보너스번호가 일치여부" 라는 조건은 2등 3등 구분을 위해  어딘가에서는 반드시 처리되어야할텐데요. if문을 쓰지않고 이것을 처리할수 있을까요? 선뜻 이해가 가지 않습니다.

혹시 괜찮으시다면 어떻게 처리하면 좋을지 예제코드로 알려주실수 있나요?

2021-08-15 09:44 UTC, yongsoo-kim commented on src/main/java/lotto/domain/LottoGameVendor.java
> +        TicketCount availableCnt = getAvailableTicketCount(order);
답변 감사합니다! 
수정했습니다.

2021-08-17 02:21 UTC, vagabond95 commented on src/main/java/lotto/domain/IssueInput.java
> +public class IssueInput {
LottoTicketingWay 와 IssueInput  는 분리해서 생각해볼 수 있을 것 같습니다.

1. LottoTicketingWay 와 같이 로또를 생성하는 방법을 추상화하는 것은 이점이 많으며 저도 제거할 이유가 없다고 생각합니다.
2. IssueInput 의 경우 위에서 서술한 것 처럼 LottoTicketingWay 라는 인터페이스를 구현하기 위한 구현체에 필요한 데이터를 전달하기 위한 용도로 사용되고 있는데요, 이러한 방식은 구현체가 늘어날 수록 IssueInput 필드도 매번 추가 되어야하고 구현체에서도 사용해야할 데이터 정보를 '정확히' 결정해야하는 이슈가 있습니다. 추상화를 했을 때의 이점이 변경사항이 발생하더라도 그 전파를 끊을 수 있다는 이점이 있는데, IssueInput클래스는 그 이점을 활용하지 못하는 것 같습니다. 제가 생각한 방향은 AutoWay 등의 구현체에서 issusInput 같은 공용클래스를 통해 데이터를 전달받는게 아니라 생성자 시점에 필요한 필드를 받는 방법이 있을 것 같습니다.

2021-08-17 03:10 UTC, vagabond95 commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
각 등수가 '보너스 번호를 맞췄는지 체크해야하는지' 여부를 판단할 수 있는 flag 를 (ex/ shouldCheckMatchedBonusNumber) 두고 다음과 같이 체크하면 되지 않을까요?

```
            .filter(reward -> !reward.shouldCheckMatchedBonusNumber || hasMatchedBonusNumber)
            .filter(reward -> reward.isSameMatchedCount(matchedNumberCount))

```

2021-08-17 03:15 UTC, vagabond95 commented on src/main/java/lotto/domain/AutoLottoTickets.java
> +public class AutoLottoTickets {
타입으로 자동/수동을 구별할 필요가 있을까요~?

현재 스펙상으로는 로또가 발행된 이후에는 자동으로 발급되었든, 수동으로 발급되었든 처리방식에 차이는 없습니다. 주어진 금액 내에서 수동으로 먼저 구매후, 자동 티켓을 남은 금액으로 구매할 수 있기 때문에 수동으로 발행된 티켓의 개수에 대해 최초 1회 전달받을 필요가 있긴하지만 이는 수동 티켓이 생성되는 시점에 충분히 구할 수 있을 것 같습니다.

자동/수동 티켓을 별도로 관리하고 싶을 경우 LottoTicketBundle 에서 같은 타입이되, 다른 네이밍으로 구별할 수 있을 것 같아요.
```
LottoTickets manualLottoTickets;
LottoTickets autoLottoTickets;

```

2021-08-17 03:16 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +    public AutoLottoTickets issueTicketsByAutoWay(IssueInput input) {
그런 맥락이라면 괜찮을 것 같습니다!

2021-08-17 04:40 UTC, yongsoo-kim commented on src/main/java/lotto/domain/IssueInput.java
> +public class IssueInput {
답변감사합니다. 
1번 항목에 대해서는 저랑 같은 의견이시군요.
2번 항목에서 "각 구현체에서 굳이 필요없는 데이터가 IssueInput"에 들어가면 복잡도가 증가한다"라는 관점은 이해했습니다.
다만 이 부분이 구체적으로 어떤 의미인지 잘 모르겠습니다. 

`제가 생각한 방향은 AutoWay 등의 구현체에서 issusInput 같은 공용클래스를 통해 데이터를 전달받는게 아니라 생성자 시점에 필요한 필드를 받는 방법이 있을 것 같습니다.`

현재 Tickettingway는 다음과 같은 추상화된 인터페이스를 가집니다.
` List<LottoTicket> issueLottoTickets(IssueInput input);`

자동티켓을 발행하는데는 "티켓장수"만 필요합니다. 반대로 수동티켓을 발행하는데는 "입력받은 수동로또 번호" 가 필요합니다.
지훈님이 생각하시는 방식은 파라메터를 달리한 같은 이름의 인터페이스를 지정하는 것인가요?
예)
`
//자동티켓용 인터페이스 (티켓 장수)
List<LottoTicket> issueLottoTickets(TicketCount count);
//수동티켓용 인터페이스(입력받은 수동번호들)
 List<LottoTicket> issueLottoTickets(int[][] manualNumbers);
`
이경우는 구현체에서는 필요하든 필요없든 2개의 메서드를 오버라이드 해야 합니다. 저는 이 방식이 주는 이점을 잘 모르겠습니다.
아니면, 아예 인터페이스 메서드를 2개로 나누는 방식을 말씀하시고 계시는건가요?

`AutoTickettingWay{
    List<LottoTicket> issueLottoTickets(TicketCount count);
}

class ManualTickettingWay {
    List<LottoTicket> issueLottoTickets(int[][] manualNumbers);
}
`

2021-08-17 05:15 UTC, yongsoo-kim commented on src/main/java/lotto/domain/AutoLottoTickets.java
> +public class AutoLottoTickets {
답변감사합니다.
`주어진 금액 내에서 수동으로 먼저 구매후, 자동 티켓을 남은 금액으로 구매할 수 있기 때문에 수동으로 발행된 티켓의 개수에 대해 최초 1회 전달받을 필요가 있긴하지만 이는 수동 티켓이 생성되는 시점에 충분히 구할 수 있을 것 같습니다.`
↑
네. 이 자동/수동티켓이 몇장인지 계산하는 부분은 "로또게임업자(LottoGameVendor)"에서 해주고 있습니다.

`자동/수동 티켓을 별도로 관리하고 싶을 경우 LottoTicketBundle 에서 같은 타입이되, 다른 네이밍으로 구별할 수 있을 것 같아요.`
이경우 확실히 제가 지정한 일급컬렉션인 "AutoLottoTickets"와 "ManualLottoTickets"는 필요가 없다고 생각합니다.
그러나 `다른네이밍으로 구별할수 있다` 라는 부분에서 생각을 한번 더 했습니다. 
LottoTicketBundle객체를 생성할때 생성자가 다음과 같다고 가정합니다.
`public LottoTicketBundle(List<LottoTicket> autoLottoTickets, List<LottoTicket> manualLottoTickets);`
이경우, "수동티켓,자동티켓"순으로 변수를 주입해주어야하는데 같은 타입이므로 이런 실수도 일어날수 있습니다.
**"수동티켓,수동티켓", "자동티켓,자동티켓","자동티켓, 수동티켓"**
이런 관점에서 봤을떄, 저는 조금더 복잡하더라도, 한번더 일급콜렉션으로 감싸는게 확실한 방법이라 생각했습니다.
가독성도 조금더 낫다고 생각했구요.  제 의견은 어떻게 보시나요?

2021-08-17 06:24 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
답변감사합니다. 계속 읽다보니 많은 의미가 함축된 답변이라 느껴져 다시질문 드립니다.

1. `각 등수가  보너스 번호를 맞췄는지 체크해야하는지 여부를 판단할 수 있는 flag `는 LottoReward에새로운 필드추가를 고려하라는 말씀으로 이해되는데 맞나요?  이런형식의 Enum을 말씀하시는건지 궁금합니다.

```
    NO_MATCHED(0, false, 0),
    THREE_NUMBERS_MATCHED(3, false, 5_000),
    FOUR_NUMBERS_MATCHED(4, false, 50_000),
    FIVE_NUMBERS_MATCHED(5, false, 1_500_000),
    FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED(5, true, 30_000_000),
    SIX_NUMBERS_MATCHED(6, false, 2_000_000_000);
```
이경우 보너스번호를 맟췄는지 체크해야하는 여부는 오직 `FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED`만이 true가 되는데요, 이 한부분만을 위해서 다른 관계없는 등수에 boolean값을 붙이는게 조금 위화감이 들어서 지금같은 형태를 취하게 되었습니다.

2021-08-17 06:28 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
2. 개인적으로 이코드의 로직이 읽기가 쉽지 않았습니다.
```
   .filter(reward -> !reward.shouldCheckMatchedBonusNumber || hasMatchedBonusNumber)
   .filter(reward -> reward.isSameMatchedCount(matchedNumberCount))
```
필터안에 부정(!) 이 들어가고, 그후에 OR을 취하고 있는데 얼핏 보면 "보너스넘버 일치여부를 체크하지 않거나 일치하는 보너스 넘버가 있을경우, 참이다" 라고 읽혀서 무슨 의미인지 이해하기가 어려웠습니다. 지금도 이해가 잘 안가는데, 제 해석이 맞나요?

2021-08-17 06:30 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
똑같이, 코드에 관한 내용입니다. 2등과 3등의 차이는 "5개의 숫자가 일치하고.... "라는 전제조건이 먼저입니다. 따라서, 제가 생각했을때는 숫자일치에 관한 필터가 먼저오는것이 자연스럽고, 더 읽기 쉽게  느껴졌습니다. 이런변화는 어떻게 생각하시나요?

```
(제시해주신 코드)
  .filter(reward -> !reward.shouldCheckMatchedBonusNumber || hasMatchedBonusNumber)
  .filter(reward -> reward.isSameMatchedCount(matchedNumberCount))

```

```
(제가 생각하는 순서)
 .filter(reward -> reward.isSameMatchedCount(matchedNumberCount))
 .filter(2동과 3등을 구분하는 로직이 들어갈 자리)
```

2021-08-17 06:39 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
마지막으로, 사양에 관한 이야기 입니다. 
어찌어찌 3개일치~6개일치 및 보너스 번호 일치까지 스트림으로 처리를 해도, 다음과 같은 2가지 사양이 남습니다.
```
* 0~2개의 숫자가 일치하는경우 꽝이다.
* 7개이상의 숫자가 일치(matchedNumberCount)한다는  입력은 예외로 처리한다.
```
이부분들까지 스트림으로 처리하려고 하니, 아직 이해가 부족해서 그런지 좋은 예시가 떠오르지 않았습니다.
저는 그래서 제가 아는한에서 if문으로 처리하는것이 오히려 읽기 쉽고, 깔끔하다고 생각했는데,  어떻게 하는게 좋은 방법일까요? 그래도 계속 스트림으로 처리를 도모하는게 맞을까요?

2021-08-18 01:17 UTC, vagabond95 commented on src/main/java/lotto/domain/AutoLottoTickets.java
> +public class AutoLottoTickets {
말씀하신 부분도 충분히 일리가 있다고 생각합니다 ㅎㅎ 실제로 파라미터의 타입이 같을 경우 흔히 발생하는 휴먼에러이고 저도 여러번 겪어봤네요 😢 

저도 답변주신 것을 곰곰히 더 생각해보니, 현재 수동/자동 티켓s 의 구현체는 크게 차이가 없으나 추후에 스펙이 추가될 경우에는 각각의 비즈니스 로직을 분리하여 관리할 수 있으므로 나중을 고려한다면 좋은 선택이라고 생각됩니다!

2021-08-18 01:30 UTC, vagabond95 commented on src/main/java/lotto/domain/IssueInput.java
> +public class IssueInput {
제가 설명이 부족하여 혼동을 드린 것 같습니다 😢 

우선 제가 생각했던 복잡도의 실제적인 예는 다음과 같습니다.

인터페이스에서 제공하는 메소드 시그니쳐 특성상 티켓을 만들기 위해서는 IssueInput 을 통해서만 필요한 데이터를 전달할 수 있으므로
```List<LottoTicket> issueLottoTickets(IssueInput input)```

IssueInput 의 필드 개수는 최소 (Tickettingway 인터페이스의 구현체 개수) 가 될 것입니다. 왜냐하면 각 구현체가 요구하는 필드가 보통은 다를 것이기 때문입니다. 현재 구현에서는 자동/수동 2가지 구현체가 있으므로 2개의 필드가 존재하고 있습니다.

문제는 향후에 Tickettingway 의 구현체가 몇개가 늘어날지 예측할 수 없는 상황이고, 구현체가 늘어날때마다 그 구현체가 요구하는 필드가 IssueInput 에 추가되어야할 것입니다. 
예를들어 Tickettingway 구현체가 수동/자동 외에 8개의 방식이 더 추가됐다고 가정해보겠습니다. 각 구현체가 요구하는 필드가 모두 다를경우 IssueInput 에는 최소 10개의 필드가 존재할 것입니다. 여기서 맞이하게 되는 문제는 특정 구현체에서 IssueInput 에서 어떤 데이터를 이용하여 구현해야하는지 '정확히' 알고 있어야 한다는 점입니다. 이러한 상황은 필드개수가 많아질수록 개발상의 피로도가 높아지고 실수할 여지가 커질수 있다고 생각합니다.

따라서 제가 드리고 싶었던 논지는 
```List<LottoTicket> issueLottoTickets(IssueInput input)```
이러한 형태의 단일한 객체를 통해 티켓 생성에 필요한 데이터를 전달하는 방식은 추후 변경을 고려했을 때 좋은 구조가 아니라는 생각이 듭니다.

이에 대해 제가 생각했던 해결방안은 우선 메소드 시그니쳐를 아래와 같이 단순화 하는 것입니다.
```List<LottoTicket> issueLottoTickets()```

그리고 생성에 필요한 데이터는 구현체의 생성자 시점에서 받을 수 있을 것 같습니다.
```
class AutoTickettingWay {
    public AutoTickettingWay(TicketCount count) {
    ....
    }
    
    List<LottoTicket> issueLottoTickets() {
    ....
    }
}

물론 해당 방식도 장/단점이 있습니다. 장점은 위의 이슈를 해결할 수 있다는 것이고 단점은 생성 시점에 TicketCount 가 결정된다는 점입니다. 유동적으로 값이 변경될경우 대응이 어렵겠죠. (setter 를 제공하는 방식이 있지만 상태 관리 측면에서 추천드리고 싶지는 않습니다.)

결국 각 방식에는 장/단점이 존재하는데 제 기준에서는 위 방식이 장/단점을 비교했을 때 좀 더 나은 방식이라고 생각되어 제시 드렸습니다!
물론 정답인 구현은 없으므로 위의 내용정도만 인지하고 적절히 선택해주시면 될 것 같습니다!

```

2021-08-18 01:42 UTC, vagabond95 commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
깊이 고민해주셔서 감사합니다! 제가 너무 성의없이 답변을 드린 것 같아 죄송하네요 ㅠ.ㅠ

하나씩 살펴보면 

1. 생각해주신 방식이 맞습니다! 다만, 한 부분만을 위하여 처리한다는 것이 위화감이 드신다는 부분은 어색하게 느껴질 수 있으나 추후 스펙이 어떻게 바뀔지 모르기 때문에 (ex/보너스 번호를 고려하는 등수가 추가된다면?) 문제될 부분은 없다는 생각이 듭니다!

2-1. 해석해주신 방법이 맞습니다! 논리식에 의해 생략된 부분이 있는데 좀 더 풀면 이런식으로도 표현이 가능할 것 같습니다.
```
   .filter(reward -> !reward.shouldCheckMatchedBonusNumber || 
   (reward.shouldCheckMatchedBonusNumber && hasMatchedBonusNumber)
   
  
```
2-2. 순서를 바꿔도 무방할 것 같습니다! 기본적으로 등수는 맞춘횟수를 기준으로 분기가 되므로 말씀해주신 부분이 좀 더 직관적으로 이해하기 쉽겠네요 ㅎㅎ

3. 각 조건이 다른 성격을 가지고 있다고 생각되는데요, 
* 0~2개의 숫자가 일치하는경우 꽝이다. -> 해당 조건은 '등수 스펙'의 일부이므로 orElse() 와 같은 연산자를 통해 처리할 수 있을 것 같습니다.
* 7개이상의 숫자가 일치(matchedNumberCount)한다는  입력은 예외로 처리한다. -> 해당 조건은 예외처리이므로, if 문으로 빠지는 것이 맞다고 생각합니다~!

저도 개인적으로 stream 만으로 처리를 하는 것은 가독성측면에서 선호하는 편은 아닙니다. 다만 stream 으로 풀든 단순 for-each 문으로 풀든 등수를 순회하며 조건을 체크하는 로직은 필요하고 이때 등수 체크 로직이 특정 등수에 연관되면 추후에 변경을 하기 어려워지는 코드가 될 것이라는 생각은 변함이 없습니다 :)

2021-08-19 20:36 UTC, yongsoo-kim commented on src/main/java/lotto/domain/IssueInput.java
> +public class IssueInput {
답변 감사합니다! 이제는 왜 한클래스에 갖은 변수를 모아 넣고 전달하는방식이 복잡도를 늘리는지 잘 알게되었습니다.
또한, "티켓을 발행한다"는 행위를 추상화는 유지하면서, 어떻게하면 그 구현체에 알맞는 파라메터를 생성자를 통해 넘기는지 확실히 이해할수 있었습니다. 정말 좋은 코멘트 감사드립니다. 공부가 되었습니다.

2021-08-19 21:16 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
답변감사합니다! 굉장히 정성들여 써주신 코멘트에 먼저 감사드립니다. 하나씩 답변드리겠습니다.
1번, 2번항목 -> 코드 수정은 굉장히 쉬웠습니다. 하지만 다음코드는 생각하시느것처럼 동작하지 않습니다.
```
...
 FIVE_NUMBERS_MATCHED(5, false, 1_500_000),
 FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED(5, true, 30_000_000),
...
   .filter(reward -> reward.isSameMatchedCount(matchedNumberCount))
   .filter(.filter(reward -> !reward.shouldCheckMatchedBonusNumber || reward.shouldCheckMatchedBonusNumber && hasMatchedBonusNumber))
   .findFirst()
   .orElse(NO_MATCHED);
```
말씀해주신 2등과 3등을 구별하는 로직인데요. "숫자5개일치, 보너스 넘버 일치(2등)"의 조건이 들어왔을때  다음과 같이 동작합니다.

1. 5개의 숫자가 일치하는 ` FIVE_NUMBERS_MATCHED` 와 ` FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED` 가 첫번째 filter를 통과.
2. 두번째 filter에서 "!reward.shouldCheckMatchedBonusNumber" 조건에 의해 `FIVE_NUMBERS_MATCHED` 가 통과.  그다음 조건인 "reward.shouldCheckMatchedBonusNumber && hasMatchedBonusNumber" 에의해 `FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED` 도 통과. 
3. 결과적으로,` FIVE_NUMBERS_MATCHED` ,`FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED` 모두 필터를 통과함.
4. "findFirst()"에의해 순서상 먼저인 `FIVE_NUMBERS_MATCHED`가 선택됨.

즉 원하는 결과가 나오지 않습니다. 유닛 테스트 결과입니다.
![image](https://user-images.githubusercontent.com/13756541/130145353-7a1b21a7-86d5-4478-9d51-b135c6cef36a.png)

2021-08-19 22:26 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
계속해서 1번, 2번항목 ->
이러한 2등 당첨문제를 해결하기 위해서는 Enum에 정의된 "로또 당첨" 결과의 순서를 바꾸는것으로 해결 가능합니다. 즉,
```
FIVE_NUMBERS_MATCHED(5, false, 1_500_000),
FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED(5, true, 30_000_000),
↓
FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED(5, true, 30_000_000),
FIVE_NUMBERS_MATCHED(5, false, 1_500_000)
```
이번에는 필터가 이렇게 동작합니다.

1.  5개의 숫자가 일치하는FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED 와  FIVE_NUMBERS_MATCHED 가 첫번째 filter를 통과.
2.  "!reward.shouldCheckMatchedBonusNumber" 조건 -> false
   "reward.shouldCheckMatchedBonusNumber && hasMatchedBonusNumber"  조건 -> true
   이조건에 의해 `FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED ` 가 먼저 통과.
   이후 "!reward.shouldCheckMatchedBonusNumber" 조건에 의해 `FIVE_NUMBERS_MATCHED` 가 통과.
6.결과적으로, FIVE_NUMBERS_MATCHED ,FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED 모두 필터를 통과함.
7. 4."findFirst()"에의해 순서상 먼저인 `FIVE_NUMBERS_AND_BONUS_NUMBER_MATCHED` 가 선택됨.

이렇게 2등이 당첨되게 할수는 있습니다. 이런 로직은 다음과 같은 문제를 야기합니다.

1. Enum의 선언순서에 의해 등수가 결정되므로, 당초 목적이었던 사양변경에 유연하게 대처한다는 목적을 달성하지 못합니다. 오히려 엔지니어가 당첨정보를 애매한곳에 추가할경우, 어디가 잘못되었는지 알기 매우 힘듭니다.
2. 코드가 읽기 어렵습니다. 원하는 결과를 위해 2등과 3등의 순서를 바꾸었는데, 1,2,3등순서를 기대하고 읽는 엔지니어가 왜 순서가 바뀌었는지 예측하기 어렵습니다.
3. filter안에 있는 조건인 " !reward.shouldCheckMatchedBonusNumber || reward.shouldCheckMatchedBonusNumber && hasMatchedBonusNumber)" 은 길기도 길지만 읽기 어렵습니다. `보너스넘버 일치여부를 체크하지 않거나 일치하는 보너스 넘버가 있을경우, 참이다` 보너스 넘버체크에 관한 "`부정(!)" 이 한번 나온데 이어, 곧바로 보너스 넘버에 대한 긍정"||(OR)"이 바로 언급되므로, `보너스 번호에 대해 부정/긍정 어느쪽에 관한 제한인가?`를 알기 어려운 문제가 있습니다.

이러한 이유로 인해, 저는 If문을 고르는것이 그나마 읽기 쉽다고 생각했습니다.
코드는 일단, 제대로 움직여야하므로 If문으로 2,3등을 구별하게는 해놨습니다.
사양변경에 유연하게 대처하고자 하는 지훈님의 의견도 저는 적극 찬성하는 바입니다. 어떻게 생각하시나요?

2021-08-19 22:45 UTC, yongsoo-kim commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
3번항목:  이코멘트는 매우 좋은 관점을 제게 제시해주었습니다.
`등수 스펙`은 Stream안에서, `예외처리`는 If문 안에서 해결한다는 관점은 이해하기도 쉽고 코드도 깔끔해진다고 생각합니다. 즉각 수정했습니다.

언제나 좋은 코멘트 감사드립니다!
부끄럽지만 저는 객체지향적인 코드를 별로 다뤄보지 못해서, 지금 주어진 미션을 통해 정말 많은 것을 배우고 있습니다.  다 지훈님 덕분입니다. 감사합니다!

2021-08-19 22:46 UTC, yongsoo-kim commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +
답변 감사드립니다. 이부분은  ManualLottoTickets 와 AutoLottoTickets 이 구분되는 방향으로 코드가 가고 있기에, 여유가 된다면 그때 Enum으로 묶는 시도를 해보겠습니다.

2021-08-19 22:48 UTC, yongsoo-kim commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +    public AutoLottoTickets issueTicketsByAutoWay(IssueInput input) {
답변 감사합니다!

2021-08-19 22:50 UTC, yongsoo-kim commented on src/main/java/lotto/domain/AutoLottoTickets.java
> +public class AutoLottoTickets {
답변 감사합니다. 부족한 코드인데 좋은선택이라 말씀해주셔서 감사합니다.

2021-08-20 11:45 UTC, vagabond95 commented on src/main/java/lotto/enumeration/LottoReward.java
> +        if (THREE_NUMBERS_MATCHED.matchedNumberCount > matchedNumberCount) {
아~ 그렇군요! 저는 등수가 높은것부터 선언하는 케이스만 생각했는데, 확실히 이런 문제가 있네요. 

말씀해주신 부분 모두 공감하는 바입니다. 특히 선언 순서 변경에 따라 결과가 달라지는 것은 제가 얘기했던 변경에 유연한 코드라는 케이스에 적합하지 않습니다. 실전에서 저런 코드를 만났다면 무척 애먹었을 것 같습니다 ^^;

얘기주신 맥락을 모두 고려하였을 때 if 문도 충분한 근거가 된다고 생각합니다! 저도 설득이 되었네요 :) 끝까지 고민하시는 모습 멋지십니다!!!

2021-08-20 11:47 UTC, vagabond95 approved these changes
오랜 기간 논의하고 수정하는 것이 쉽지 않으셨을텐데 정말 고생많으셨습니다!

저도 같이 고민해보면서 그동안 당연하게 생각했던 것들을 다시 생각해보는 좋은 미션이었습니다. 마지막까지 꼼꼼하게 생각을 남겨주셔서 정말 감사합니다 :)

이번 미션에서 조금이라도 얻어간 것이 있으셨길 바라며, 마지막 단계도 머지하도록 하겠습니다! 마지막 미션까지 화이팅이십니다!

2021-08-20 11:47 UTC, merged