Step3 - 로또 2등 리뷰 요청드립니다.
next-step/java-lotto pull request #1948
Opened 2021-08-15 08:03 UTC by holeman79

로또 2등 리뷰 요청드립니다. 감사합니다.

2021-08-16 01:23 UTC, dbeod2 requested changes
안녕하세요! 원진님 

로또 2등 미션 잘 진행해주셨네요! 
추가 코드에 대한 테스트도 잘 작성해 주신 것같아요! 

의견 드린 부분이 몇가지 있는데 확인 부탁드리고, 리뷰 재요청 주세요! 👍

2021-08-16 01:23 UTC, dbeod2 commented on src/main/java/lotto/domain/LottoStatus.java
> +                        || lottoStatus.isMatched(bonusNumberStatus))
BonusNumberStatus.MATCH 아닐때만 체크해주면 조금 더 코드가 간결해질 것 같습니다 
어떻게 생각하시나용 ?🤔

2021-08-16 01:23 UTC, dbeod2 commented on src/main/java/lotto/domain/WinningNumbers.java
> +    }
보너스볼에 대한 상태를 관리해주신 만큼 보너스볼 체크에 대한 로직도 BonusNumberStatus에 위임을 할 수 있을 것같은데 어떻게 생각하시나용?

2021-08-16 10:17 UTC, holeman79 commented on src/main/java/lotto/domain/WinningNumbers.java
> +    }
BonusNumberStatus는 보너스 번호에 대한 확인 결과를 나타내는 상수입니다. 결과 값을 정의한 상수 내에 결과를 확인하는 로직이 들어가는 것은 조금 이상하게 느껴지는 것 같습니다. 이럴 경우 BonusNumberStatus.MATCH.checkContainsBonusNumber(winningNumbers, bonusNumber); 이런 형태로 사용이 가능해지는데 결과가 다시 보너스 볼을 체크하여 결과를 리턴하게 됩니다.
게다가 보너스번호는 WinningNumbers가 갖고 있고 보너스 볼 확인 또한 WinningNumbers 내에서만 이루어질 것으로 예상되기 때문에 
체크 로직이 다른 곳에 중복으로 발생하진 않을 것 같아서 제 생각엔 WinningNumbers 내에 있는 것이 맞다고 생각합니다.

2021-08-16 12:10 UTC, holeman79 commented on src/main/java/lotto/domain/LottoStatus.java
> +                        || lottoStatus.isMatched(bonusNumberStatus))
어느 부분에서 MATCH가 아닐때 체크를 하는건지 잘 이해가 안되는데 
.filter(lottoStatus -> lottoStatus.isMatched(BonusNumberStatus.NOT_APPLY)
                        || lottoStatus.isMatched(bonusNumberStatus))
이 부분을 그냥 .filter(lottoStatus -> !lottoStatus.isMatched(BonusNumberStatus.MATCH) 로 말씀하신게 맞을까요?

2021-08-16 12:15 UTC, dbeod2 commented on src/main/java/lotto/domain/LottoStatus.java
> +                        || lottoStatus.isMatched(bonusNumberStatus))
엇..네네 제가 match로 기준을 잡으라고 말씀을 드리려했는데; 코드 읽다가 혼자 생각했던 부분이 정리 안되서 코멘트로 적은 것같네요.. 찰떡같이 ; 이해해주셨네요 네네 지금 보시면 두개의 상태로 체크하시는 것 같아 코멘트 드렸습니다

2021-08-16 12:16 UTC, dbeod2 commented on src/main/java/lotto/domain/WinningNumbers.java
> +    }
아! 네넵 ㅎ 의도가 분명하신거면! 그대로 진행하셔도 됩니다! 
저도 보다보니 의견 한번 드린 부분이었어서요!

2021-08-17 04:28 UTC, dbeod2 approved these changes
안녕하세요! 원진님

피드백 잘 반영해주시고 일부 코드수정도 해주신 것 같네용 ! 
로또 3단계 미션은 여기서 머지해도 될 것같아요! 👍 

그럼 로또 마지막 미션 수행해주세요!!

2021-08-17 04:28 UTC, merged