Step2 리뷰 요청드립니다 :)
next-step/java-lotto pull request #1956
Opened 2021-08-16 03:54 UTC by Woogie924

안녕하세요 리뷰어님
최대한 TDD 적용해서 진행을 해보았는데,
생각 못했던 케이스가 생기더라구요,,
그래서 중간에 클래스를 새로 설계하는 과정을 거치고 하는 식으로 진행했는데,,
 리뷰 요청드립니다!!

2021-08-16 11:04 UTC, ksundong requested changes
안녕하세요! 성욱님, 로또 미션 리뷰어로 지정된 김선동입니다. 😊

2단계 미션을 진행하느라 대단히 고생많으셨습니다.
일단 1차적으로 코드의 디테일적인 측면에서 리뷰를 해보았습니다.
요구사항이 지켜지지 않은 부분이 많이 보입니다. 요구사항은 꼭 지켜주세요!!

고생하셨습니다!
확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-16 11:04 UTC, ksundong commented on src/main/java/lotto/util/CollectionUtil.java
> +public class CollectionUtil {
해당 클래스가 담고 있는 내용은 `Collection`과 관련되어있지도 않고
`Utility`로 처리되면 안될 부분으로 보입니다.

2021-08-16 15:55 UTC, Woogie924 commented
@ksundong 
안녕하세요 리뷰어님!!
공휴일인데도 불구하고, 시간 할애 해주셔서 감사합니다

1. CollectionUtil 제거 후 해당 로직 Number객체 메소드로직으로 이관
2. indent depth 조건 
3. Collection.sort()활용해서 불필요한 stream sort로직 수정
4. 무의미한 변수명을 의미를 가진 변수명으로 변경 (변수명 map 리뷰)
를 진행했는데요, 
5. 컨트롤러 역할 수정

크게 5가지로 리뷰 반영 진행하였는데요,,
컨트롤러의 역할을 너무 벗어났다고 리뷰해주신것에서 고민을 해보고
로또를 생성하는 객체를 추가했는데요,
컨트롤러는 모델에 요청하기 쉽게 데이터를 가공하고, 결과를 뷰에게 전달해주는 역할이라고 생각하는데,
이게 리뷰어님이 의도하신 피드백인지 아니면 다른 생각으로 말씀하신건지 여쭤보고 싶습니다 :)

2021-08-17 12:24 UTC, ksundong commented on src/main/java/lotto/LottoController.java
> +    }
@Woogie924

> 컨트롤러는 모델에 요청하기 쉽게 데이터를 가공하고, 결과를 뷰에게 전달해주는 역할이라고 생각하는데,
> 이게 리뷰어님이 의도하신 피드백인지 아니면 다른 생각으로 말씀하신건지 여쭤보고 싶습니다 :)

네 결과를 전달해주어야 하지 결과출력을 직접해선 안되겠죠?

컨트롤러는 뷰와 모델의 연결부라고 저는 생각해요. 별도의 로직이 수행되는 부분이 아니라 로직이 수행될 수 있는 흐름을 만들어주는 것이라고 생각하시면 좋을 것 같아요.
실질적인 로직은 도메인에서 이뤄지도록 하고, 순서가 필요한 부분을 적절히 컨트롤러가 연결지어준다! 라고 생각해보시면 좋을 것 같아요.

2021-08-17 13:29 UTC, ksundong requested changes
안녕하세요! 성욱님, 로또 미션 리뷰어로 지정된 김선동입니다. 😊

2단계 미션 피드백을 진행하느라 고생많으셨습니다!! 💪
코드를 보면서 추가적인 피드백이 있어 변경요청을 드립니다.

고생하셨습니다!
확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-17 13:29 UTC, ksundong commented on src/main/java/lotto/domain/Number.java
> +    }
`static` 메서드가 아니면 어떨까요?

2021-08-17 13:29 UTC, ksundong commented on src/main/java/lotto/domain/PurchaseAmount.java
> +        }
해당 요구사항이 있었나요?

2021-08-17 13:29 UTC, ksundong commented on src/main/java/lotto/util/RandomUtil.java
> +    }
자동차 경주 때를 잘 생각해보시면 힌트가 될 수도 있겠네요
`Utility` 클래스는 전혀 객체지향적이지 않기 때문에 최대한 지양해주세요!

2021-08-17 13:29 UTC, ksundong commented on src/main/java/lotto/view/InputView.java
> +    private static final InputView INPUT_VIEW = null;
필요할까요?

2021-08-17 13:29 UTC, ksundong commented on src/main/java/lotto/view/InputView.java
> +    }
싱글턴 패턴을 의도하신 것 같은데
`INPUT_VIEW`가 항상 `null`이지 않을까요?

2021-08-17 13:29 UTC, ksundong commented on src/test/java/lotto/domain/LottoTest.java
> +    private static final int DEFAULT_LOTTO_SIZE = 6;
해당 상수는 도메인 클래스에 있는게 낫지않을까요?

2021-08-17 13:29 UTC, ksundong commented on src/test/java/lotto/domain/LottoTest.java
> +    }
스트림을 활용하면 좋을 것 같아요~

2021-08-17 13:29 UTC, ksundong commented on src/test/java/lotto/domain/LottosTest.java
> +    Lottos lottos = new Lottos();
테스트하려는 코드의 초기화 코드는 왠만하면 `@BeforeEach`에 넣는 습관을 들여주세요~

2021-08-17 13:29 UTC, ksundong commented on src/test/java/lotto/domain/NumberTest.java
> +    private static final boolean IS_SMALLER_THAN = false;
이런 상수는 추출하지 않는 편이 나을 것 같습니다.

2021-08-17 13:29 UTC, ksundong commented on src/test/java/lotto/domain/PurchaseAmountTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
단순히 `IllegalArgumentException`인지만 테스트 하는 것이 과연 유효한 테스트일까요?

2021-08-18 07:15 UTC, Woogie924 commented on src/test/java/lotto/domain/PurchaseAmountTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
음 정상동작되는 해피케이스와
블루케이스로 나눠서 작성해봤는데요,
`IllegalArgumentException`  후처리까지 봐야한단 말씀인지 여쭙고 싶습니다!
현재 프로그램에서는 천원단위 구매라는 요구사항만 있으므로,
비정상적인 입력값으로 걸러주고 예외 발생하는 것으로 의미가 있다고 생각하는데,
리뷰어님 의견 여쭙고 싶습니다!

후처리를 의도해서 피드백해주셨다고 판단해서 후처리까지 추가했습니다 :)

2021-08-18 07:16 UTC, Woogie924 commented on src/main/java/lotto/LottoController.java
> +    }
너무 많은 도움이 되었습니다!
제대로 된 분리를 하지 않았다는게 느껴지더라구요 
감사합니다 !

2021-08-18 07:17 UTC, Woogie924 commented on src/main/java/lotto/domain/Lottos.java
> +        return Winner.findWinningInfo(matchCounts);
애매모호한 명인거 같아서
`Rank`로 수정작업했습니다 :)

2021-08-18 14:33 UTC, ksundong commented on src/test/java/lotto/domain/PurchaseAmountTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
`IllegalArgumentException` 이면 원하는 예외가 발생했는지에 대해서 알 수 있는걸까요?
저같은 경우에는 예외 메시지까지 검증해주는 편입니다!
더 구체적인 정보가 필요하면 더해주고요!

2021-08-18 14:42 UTC, ksundong approved these changes
안녕하세요! 성욱님, 리뷰어 김선동입니다. 😊

2단계 미션 피드백을 진행하느라 고생많으셨습니다!! 💪
간단한 피드백을 남깁니다! 다음단계 진행하시면서 확인해주세요~

고생하셨습니다!
다음단계에서 좀 더 설계에 대해서 고민해보면 좋을 것 같습니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-18 14:42 UTC, ksundong commented on src/main/java/lotto/LottoApplication.java
> +        int cash = lottoController.inputPurchaseAmount();
사실 컨트롤러는 입력까지 받지는 않습니다!

2021-08-18 14:42 UTC, ksundong commented on src/main/java/lotto/LottoApplication.java
> +        int cash = lottoController.inputPurchaseAmount();
출력역시 View의 책임이죠!

2021-08-18 14:42 UTC, ksundong commented on src/main/java/lotto/LottoApplication.java
> +        int cash = lottoController.inputPurchaseAmount();
그래도 잘 추출해주셨어요!

2021-08-18 14:42 UTC, ksundong commented on src/main/java/lotto/domain/Lotto.java
> +    }
`shuffleNumbers`는 살짝 애매하네요. 구현에 관련이 있어보여요.

2021-08-18 14:42 UTC, ksundong commented on src/main/java/lotto/domain/Number.java
> +    }
`Random`을 다루는건 자동차 경주때를 한 번 생각해보시면 좋을 것 같아요!

2021-08-18 14:42 UTC, merged