Step4 - 로또 (수동)
next-step/java-lotto pull request #1976
Opened 2021-08-19 17:14 UTC by bgc8214

안녕하세요 :) 4단계 로또(수동) 구현 완료하여 리뷰요청드립니다

기능을 구현하면서, 헷갈렸던 부분은 "수동으로 구매할 번호를 입력해주세요" 라는 부분의 출력입니다. 

LottoManager가 Lottos 를 만들기 위해서는 자동으로 만든 로또, 수동으로 만든 로또가 모두 필요합니다. 로또 매니저가 두 타입의 로또를 하나의 메소드안에서 만들어 Lottos를 생성하면 되는데, 이러려면 "수동으로 구매할 번호를 입력해주세요" 라는 출력이 로또 매니저의 메소드 안에 같이 들어가게 되었습니다.

이런 로또 매니저 같은 도메인에서는 아예 출력 메소드가 없어야하는 것인지가 궁금합니다 😕  ( 없어야 한다면, 자동 로또를 만드는 메소드 / 수동 로또를 만드는 메소드 / Lottos를 만드는 메소드 세 개를 분리해서 호출하게 될 것 같네요 ) 

추가적으로 이전 리뷰 주신 것 중에서 궁금한 사항이 있어서 함께 코멘트 추가하였습니다 :) 감사합니다. ( [이전 리뷰](https://github.com/next-step/java-lotto/pull/1958) )

2021-08-20 19:06 UTC, jaeyeonling requested changes
수동 로또 미션을 잘 구현해주셨습니다 👍 
질문의 답변과 코멘트 남겨두었으니 확인 부탁드려요~

2021-08-20 19:06 UTC, jaeyeonling commented on src/main/java/domain/LottoManager.java
> +        System.out.println("수동으로 구매할 번호를 입력해주세요");
Q. 기능을 구현하면서, 헷갈렸던 부분은 "수동으로 구매할 번호를 입력해주세요" 라는 부분의 출력입니다.

LottoManager가 Lottos 를 만들기 위해서는 자동으로 만든 로또, 수동으로 만든 로또가 모두 필요합니다. 로또 매니저가 두 타입의 로또를 하나의 메소드안에서 만들어 Lottos를 생성하면 되는데, 이러려면 "수동으로 구매할 번호를 입력해주세요" 라는 출력이 로또 매니저의 메소드 안에 같이 들어가게 되었습니다.

이런 로또 매니저 같은 도메인에서는 아예 출력 메소드가 없어야하는 것인지가 궁금합니다 😕 ( 없어야 한다면, 자동 로또를 만드는 메소드 / 수동 로또를 만드는 메소드 / Lottos를 만드는 메소드 세 개를 분리해서 호출하게 될 것 같네요 )


A. 답을 먼저 말씀드리면 출력 메서드가 없어야 하는 것이 맞습니다!
도메인의 경우 View의 변경에 영향을 받지 않도록 설계를 해야 하는데요
만약 해당 서비스가 발전해서 웹으로도 서비스한다면 View는 API를 통해 요청을 받게 되고, 그러면 해당 도메인은 영향을 받을 것 같습니다 :)

2021-08-20 19:06 UTC, jaeyeonling commented on src/main/java/domain/ManualNumberStrategy.java
> +                String winningNumber = InputView.enterLottoNumber();
해당 도메인에도 View의 요소가 들어갔네요 @_@ 
위에 남긴 도메인에서 View를 사용하면 안되는 이유를 확인해주시고, 같이 수정해주세요~

2021-08-20 19:06 UTC, jaeyeonling commented on src/main/java/view/InputView.java
> +                SCANNER = new Scanner(System.in);
스캐너를 매번 생성해주도록 작성하신 이유가 있을까요!?

2021-08-20 19:06 UTC, jaeyeonling commented on src/main/java/view/InputView.java
> +    private static Scanner SCANNER = new Scanner(System.in);
static 변수의 경우 final을 같이 붙여주는 것이 관례인데요!
멀티 스레딩 환경에서 static 변수를 재할당하는 코드가 존재할 경우 어떠한 문제가 있을지 고민해보아요 :)

2021-08-22 16:01 UTC, bgc8214 commented on src/main/java/domain/LottoNumbers.java
>      private void validate() {
넵 감사합니다 :) 어떤 말씀인지 이해가 갔어요. 말씀해주신 내용으로 한번 수정해봤습니다 😃

2021-08-22 16:02 UTC, bgc8214 commented on src/main/java/domain/LottoPrizeType.java
> -    public boolean isExposure() {
넵 답변 감사합니다! View 와 분리할 수 있도록 수정하겠습니다 👍

2021-08-22 16:06 UTC, bgc8214 commented on src/main/java/view/InputView.java
> +                SCANNER = new Scanner(System.in);
잘못된 값을 입력받고 나서, 무한루프로 Exeception이 발생해서, scanner 를 초기화 하는 방식으로 구현했었어요. 새로 스캐너를 생성하는 것이 아니라 Scanner.next()로 해당 값을 넘기고, 다시 값을 받을 수 있도록 수정했습니다.

2021-08-22 16:09 UTC, bgc8214 commented on src/main/java/view/InputView.java
> +    private static Scanner SCANNER = new Scanner(System.in);
넵. 여러 쓰레드에서 동일한 메모리에 접근하는데, Thread-safe 하지 않게 값이 변경되면 값이 꼬일 수 있을 거 같네요. 마찬가지로 수정하였습니다 !

2021-08-23 13:00 UTC, jaeyeonling requested changes
코멘트 잘 반영해주셨네요 👍 
추가적으로 소소한 코멘트 남겨두었으니 확인 부탁드릴게요~!

2021-08-23 13:00 UTC, jaeyeonling commented on src/main/java/domain/Lotto.java
> +        return lottoNumbers.getValues().contains(lottoNumber);
```suggestion
        return lottoNumbers.contains(lottoNumber);
```

getter없이 기능을 제공해주면 좋겠네요 :)

2021-08-23 13:00 UTC, jaeyeonling commented on src/main/java/controller/LottoController.java
> +        int manualLottos[][] = InputView.enterManualLotto(manualLottoCount);
```suggestion
        int[][] manualLottos = InputView.enterManualLotto(manualLottoCount);
```

컨벤션 위반 발견!

2021-08-24 09:45 UTC, jaeyeonling approved these changes
마지막까지 코멘트 잘 반영해주셨습니다 👍 
수 많은 코멘트 반영하시느라 고생 많으셨어요 😄 
해당 요청은 머지하도록 하겠습니다 다음 미션도 화이팅입니다!!

2021-08-24 09:46 UTC, merged