🚀 1단계 - 문자열 덧셈 계산기
next-step/java-lotto pull request #1982
Opened 2021-08-20 17:44 UTC by 39roc

1단계 문자열 덧셈 계산기 리뷰 요청 드립니다.

2021-08-21 11:53 UTC, JunilHwang requested changes
안녕하세요 상구님! 로또 미션을 함께하게 된 리뷰어 황준일입니다 🙇‍♂️
앞으로 잘 부탁드려요 !

문자열 덧셈 계산기 미션 잘 진행해주셨네요 👍
조금 개선할 점들이 있어서 몇 가지 리뷰 남겼으니 확인 부탁드려요!

2021-08-21 11:53 UTC, JunilHwang commented on src/main/java/step1/StringParser.java
> +    return convertToIntArray(text.split("[,:]"));
정규식과 group에 매칭되는  패턴 숫자 등은 상수로 만들어서 관리해주면 어떨까요?

2021-08-21 11:53 UTC, JunilHwang commented on src/main/java/step1/StringParser.java
> +    return convertToIntArray(text.split("[,:]"));
그리고 if 조건을 반대로하여 if문 내부에서는 바로 return하도록 하고, if문 외부에서 로직을 수행하도록 하는게 좋을 것 같아요!
if 내부의 내용은 최대한 짧게 유지하는것이 제일 좋습니다 ㅎㅎ

2021-08-21 11:53 UTC, JunilHwang commented on src/main/java/step1/StringParser.java
> +  }
`NationalNumber` 라는 원시값 포장 객체를 만들고 검증로직도 위임해주면 어떨까요?

2021-08-21 14:36 UTC, 39roc commented on src/main/java/step1/StringParser.java
> +    return convertToIntArray(text.split("[,:]"));
해당 부분에서 로직을 if문 외부에서 수행하는 것이 좋다라고 말씀하시는 이유를 알 수 있을까요?

외부 수행시 가지는 장점에 대해서 아래와 같은 영상을 참조하였는데 준일님께서는 어떻게 생각하는지 궁금합니다.
[참조 영상](https://www.youtube.com/watch?v=z4qE_IfSrD4)

2021-08-21 14:37 UTC, 39roc commented on src/main/java/step1/StringParser.java
> +    return convertToIntArray(text.split("[,:]"));
> 그리고 if 조건을 반대로하여 if문 내부에서는 바로 return하도록 하고, if문 외부에서 로직을 수행하도록 하는게 좋을 것 같아요!
> if 내부의 내용은 최대한 짧게 유지하는것이 제일 좋습니다 ㅎㅎ

해당 부분에서 로직을 if문 외부에서 수행하는 것이 좋다라고 말씀하시는 이유를 알 수 있을까요?

외부 수행시 가지는 장점에 대해서 아래와 같은 영상을 참조하였는데 준일님께서는 어떻게 생각하는지 궁금합니다.
[참조 영상](https://www.youtube.com/watch?v=z4qE_IfSrD4)

2021-08-21 14:38 UTC, 39roc commented on src/main/java/step1/StringParser.java
> +  }
> `NationalNumber` 라는 원시값 포장 객체를 만들고 검증로직도 위임해주면 어떨까요?

원시값 포장 객체 및 일급 컬렉션 활용하여 수정하였는데요.
NationalNumber 란 단어를 처음 들어봐서 무엇을 의미하는지 알 수 있을까요?

2021-08-22 09:13 UTC, JunilHwang commented on src/main/java/step1/StringParser.java
> +    return convertToIntArray(text.split("[,:]"));
```java
    Matcher matcher = Pattern.compile("//(.)\n(.*)").matcher(text);

    if (matcher.find()) {
      return convertToIntArray(text.split("[,:]"));
    }

    final String customDelimiter = matcher.group(1);
    final String[] numbers = matcher.group(2).split(customDelimiter);

    return convertToIntArray(numbers);
```
일단 이렇게 표현하면 if 블록을 작은 단위로 유지할 수 있기 때문에 로직 자체에 집중할 수 있어요!
if 블록이 길어질수록 if 외부의 일에 집중하기 힘들어집니다.
즉, if에 매몰될 수 있다는 이야기이죠.
그러다보면 if 내부에 if가 많아지게 되고, 자연스럽게 코드는 읽기 힘들어진답니다!

2021-08-22 09:14 UTC, JunilHwang commented on src/main/java/step1/StringParser.java
> +  }
앗.. `NaturalNumber(자연수)`  인데 제가 잘못 표현햇네요 ㅠㅠ 죄송합니다 🙇‍♂️

2021-08-22 09:18 UTC, JunilHwang approved these changes
안녕하세요 상구님! 피드백 반영 잘 해주셨네요 👍 
National이 아니라 Natural 인데 제가 단어를 헷갈렸네요 ㅎㅎ; 죄송합니다 ㅠㅠ
이외에 질문해주신 내요에 대해 답변 달아놨으니 확인 부탁드려요!
문자열 덧셈 계산기 미션은 여기서 마무리하겠습니다.

이제 본격적으로 로또 미션 시작이네요!
미션 진행하면서 다음과 같은 부분을 참고해주세요.
- 자료구조를 적극적으로 사용해보기
  - 로또번호는 정렬되어야하며 중복숫자가 없어야함.
  - ex) 중복처리 + 정렬에 적합한 자료구조는?
- 원시값 포장 객체를 적극적으로 사용해보기
  - 로또번호는 1~45의 숫자만 가짐
  - 즉, 최대 45개의 인스턴스가 필요함

2021-08-22 09:18 UTC, JunilHwang commented on src/main/java/step1/NationalNumber.java
> +public class NationalNumber {
`NaturalNumber(자연수, 0이상)` 인데 제가 잘못 안내한 것 같아요!

2021-08-22 09:18 UTC, JunilHwang commented on src/main/java/step1/NationalNumbers.java
> +}
일급 컬렉션 사용 👍

2021-08-22 09:18 UTC, merged