Step4(로또 수동) : 리뷰 요청드립니다.
next-step/java-lotto pull request #1997
Opened 2021-08-22 12:18 UTC by holeman79

2021-08-23 11:06 UTC, dbeod2 requested changes
안녕하세요 원진님! 

로또4단계 미션 잘진행해주셨네요! 
코멘트 남긴 부분이있는데 확인 부탁드립니다.🙏

그럼 리뷰 재요청 기다리고있겠습니다!!

2021-08-23 11:06 UTC, dbeod2 commented on src/main/java/lotto/domain/LottoGame.java
> +        int autoTicketCount = calculateAutoTicketCount(money, manualLottoTickets.size());
티켓 수량에 대한 객체가 있는데요! 활용해보시는건 어떠실까용?
그렇게 된다면 calculateAutoTicketCount메서드도 TicketCount객체로 이동 될 수 있을 것 같습니다! 🙏
확인 부탁드려요!

2021-08-29 03:25 UTC, holeman79 commented on src/main/java/lotto/domain/LottoGame.java
> +        List<LottoNumbers> manualLottoTickets = makeManualLottoTickets(manualLottoNumbers);
해당 객체 활용하여 다시 생성하는 방법으로 리팩토링 해보았습니다.

2021-08-29 13:34 UTC, dbeod2 approved these changes
안녕하세요 원진님! 

로또 수동 미션 피드백 반영 잘해주셨네요! 
리팩토링까지 같이 진행해 주셨더라구요! 👍🏻

추가 이견없어서 여기서 로또미션 마무리하겠습니다! 

앞으로 남은 미션 잘해내실거라 믿고 
부족한 리뷰 잘 따라와주셔서 너무 감사했습니다 🙏

2021-08-29 13:34 UTC, merged