Step2 - 로또(자동)
next-step/java-lotto pull request #2016
Opened 2021-08-27 04:59 UTC by brawman2

이번에도 잘 부탁드리겠습니다~~!

리뷰어님~~!

🙇

2021-08-28 01:12 UTC, dbeod2 requested changes
안녕하세요. 희운님! 

로또 2단계 미션 잘 진행해주셨습니다 👏🏻
커밋로그도 잘 남겨주셨더라구요 🙏

추가로 고민해보면 좋을 것 같은 부분 코멘트 달아두었는데 확인부탁드립니다 🙇🏻‍♀️

리뷰 재요청 기다리고 있겠습니다! 🔢🔢🔢

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/lotto/LottoNumbers.java
> +		numbers.forEach(number -> union.add(number));
numbers.forEach(number -> union.add(number)); 로직은 결국 union에 numbers전체를 넣는 과정이므로 
set에 addAll메서드를 활용해 아래처럼 표현 가능합니다 :-) 
```suggestion
	union.addAll(numbers);
```

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/lotto/LottoNumbers.java
> +		this.numbers = numbers.stream().map(number -> new LottoNumber(number)).collect(Collectors.toList());
아래와 같이 표현이 가능하겠네요! 👍🏻
```suggestion
			this.numbers = numbers.stream().map(LottoNumber::new).collect(Collectors.toList());
```

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/lotto/LottoNumbers.java
> +		return (int)this.numbers.stream().filter((number -> other.contains(number))).count();
constains도 아래 처럼 작성가능합니다 
```suggestion
				return (int)this.numbers.stream().filter((other::contains)).count();
```

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/lotto/LottoRank.java
> +public enum LottoRank {
로또 랭크에 대해 enum관리를 해주셨네요! 
가독성을 위해 아래와 같이 작성해도 좋을 것 같네요!

	FIRST(6, 2_000_000_000) {
		@Override
		protected boolean isWinning(int matchCount) {
			return this.isSameMatchCount(matchCount);
		}
	},

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/lotto/LottoReport.java
> +			.collect(Collectors.summingInt(Integer::intValue));
아래와 같이 작성 가능합니다 :-) 
```suggestion
  int totalProfit = ranks
		  .stream()
		  .map(LottoRank::reward)
		  .mapToInt(Integer::intValue).sum();
```

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/lotto/LottoReport.java
> +	}
프러덕션 코드 안에 view를 사용하기 위한 코드는 단일 책임 원칙에 위배됩니다 
프러덕션 코드에서 분리해주시면 좋을 것 같습니다 🙏

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/lotto/LottoUtil.java
> +		Random random = new Random();
메소드가 실행될때마다 new Random() 인스턴스가 반복적으로 생성되는 것보다
한개를 만들어 놓고 사용하는게 자원적인 측면에서 더 좋을 것 같아요.

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/lotto/LottoUtil.java
> +			}
for안에 if구문이 들어가 있네용 
저희 프로그래밍 요구사항을 보시면 2indent를 넘지 않아야 한다는 요구사항이 있는데요
어떻게 분리하면 좋을지 고민해보시면 좋을 것 같습니다! 🙏

2021-08-28 01:12 UTC, dbeod2 commented on src/main/java/Application.java
> +		List<List<Integer>> lottoNumbers = LottoUtil.createRandomLottoNumbers(money / lottoPrice, lottoNumberCount);
List<List<Integer>> 를 선택하신 이유가 무엇인지 궁금합니다 🤔

2021-08-29 08:12 UTC, brawman2 commented on README.md
> +### 요구 사항
감사합니다~!

2021-08-29 08:12 UTC, brawman2 commented on src/main/java/lotto/LottoGroup.java
> +			.map(list -> new Lotto(list))
감사합니다~!

2021-08-29 08:16 UTC, brawman2 commented on src/main/java/lotto/LottoGroup.java
> +public class LottoGroup {
흠... 일급컬렉션이면서 당첨번호를 통해서 로또객체들의 결과들로 통계 정보를 얻을 수 있는 역할을 생각해봤어요~!

혹시 네이밍에 조금 문제가 있을까요???

2021-08-29 08:17 UTC, brawman2 commented on src/main/java/lotto/LottoNumber.java
> +		if (number < MIN || number > MAX) {
넵 외부에서 주입하는 방식으로 변경하면 더 유연할듯 싶습니다~!

2021-08-29 08:17 UTC, brawman2 commented on src/main/java/lotto/LottoNumbers.java
> +		numbers.forEach(number -> union.add(number));
감사합니다~!

2021-08-29 08:19 UTC, brawman2 commented on src/main/java/lotto/LottoReport.java
> +			.collect(Collectors.summingInt(Integer::intValue));
감사합니다~!(이번 교육시작하면서 자바를 써봐서 아무래도 많이 어설프네요🥲)

2021-08-29 08:27 UTC, brawman2 commented on src/main/java/Application.java
> +		List<List<Integer>> lottoNumbers = LottoUtil.createRandomLottoNumbers(money / lottoPrice, lottoNumberCount);
흠... List형식으로 출력이 되고 있는듯 싶어서 List<List>로 선택했어요😓

Map으로 변경하는게 좋을까요??

2021-08-29 08:28 UTC, brawman2 commented on src/main/java/lotto/LottoUtil.java
> +			}
넵 감사합니다. util부문에서 약간 집중력이 떨어졌었나봐요😓

2021-08-29 08:29 UTC, brawman2 commented on src/main/java/lotto/LottoUtil.java
> +		Random random = new Random();
감사합니다~!

2021-08-29 08:32 UTC, brawman2 commented on src/main/java/lotto/LottoReport.java
> +	}
말씀하셔서 다시 살펴보니 그렇네요~!

감사합니다~~!😃

2021-08-29 10:07 UTC, dbeod2 commented on src/main/java/lotto/LottoGroup.java
> +public class LottoGroup {
LottoGroup이라고 되어있어서 로또를 담는곳인가?라고 생각을 했어서요! 
조금 더 의미가 담긴 네이밍이면 좋을 것 같기는합니다! 🙏
고민 한번 해주시면 감사하겠습니다 🙇🏻‍♀️

2021-08-29 10:08 UTC, dbeod2 commented on src/main/java/lotto/LottoReport.java
> +			.collect(Collectors.summingInt(Integer::intValue));
아하! 그러셨군요! 그래두 잘하고 계신걸요! 👍🏻 화이팅

2021-08-29 10:08 UTC, dbeod2 commented on src/main/java/Application.java
> +		List<List<Integer>> lottoNumbers = LottoUtil.createRandomLottoNumbers(money / lottoPrice, lottoNumberCount);
음 그래도 될 것 같다는 생각이 들어서요! ㅎㅎ 
key,value로 받아도 괜찮을 것 같은데 
이부분도 고민해보시면 좋을 것 같습니다!

2021-09-03 18:59 UTC, brawman2 commented on src/main/java/lotto/LottoGroup.java
> +public class LottoGroup {
기존 LottoGroup의 기능을 LottoGame, LottoGroup으로 분리했습니다~~!

2021-09-03 19:01 UTC, brawman2 commented on src/main/java/lotto/LottoNumber.java
> +		if (number < MIN || number > MAX) {
로또의 최소, 최대값, 갯수, 가격을 최상단 클래스인 LottoGame에서 결정할 수 있도록 수정하면서

LottoNumber를 삭제했습니다~!

2021-09-03 19:04 UTC, brawman2 commented on src/main/java/Application.java
> +		List<List<Integer>> lottoNumbers = LottoUtil.createRandomLottoNumbers(money / lottoPrice, lottoNumberCount);
LottoGame이 도출되면서 인터페이스 부분이 변경되면서 자연스럽게 List<List>가 사라졌습니다~! 😶

2021-09-04 13:10 UTC, dbeod2 approved these changes
안녕하세요! 희운님

로또 2단계 미션 잘 수행해주셨네요 피드백 반영도 잘해주셨구요! 👏🏻
코멘트 남긴 부분 확인해주시고 다음번 미션에서 반영해도 될 것 같아서
바로 머지 하겠습니다! 

다음미션을 진행해주세요 🙇🏻‍♀️

2021-09-04 13:10 UTC, dbeod2 commented on src/main/java/lotto/LottoGame.java
> +		});
return 안에 로직 부분이 원래 메소드로 되어있었던 것 같은데요! 
return문에서 바로 로직을 작성해주신 부분이 가독성이 떨어지는 부분이 있습니다.
메서드로 분리해서 명확하게 어떤 역할을 하는 로직인지 설명되면 좋을 것 같습니다!

2021-09-04 13:10 UTC, dbeod2 commented on src/main/java/lotto/LottoGame.java
> +		}, 0));
아래처럼 표현이 가능하겠네요! 
```suggestion
                 return lottoGroup.lottoResultReport(new Lotto(() -> Arrays
			.stream(winningNumbers.split(", "))
			.map(Integer::parseInt)
			.collect(Collectors.toList()), 0));
```

2021-09-04 13:10 UTC, dbeod2 commented on src/main/java/lotto/LottoGroup.java
> +		}
foreach문을 사용하셔도 될 것같네요 :-)
```suggestion
		for (Lotto unknownLotto : this.lottoGroup) {
			Lotto knownLotto = unknownLotto.unmaskedLotto(winningNumbers);
			lottoReport = knownLotto.write(lottoReport);
		}
```

2021-09-04 13:10 UTC, dbeod2 commented on src/main/java/lotto/LottoPaper.java
> +public class LottoPaper implements LottoReport {
미사용 객체이던데 구현해두신 이유가 있을까요?🤔

2021-09-04 13:10 UTC, merged

2021-09-06 13:25 UTC, brawman2 commented on src/main/java/lotto/LottoGroup.java
> +		}
감사합니다~!

2021-09-06 13:26 UTC, brawman2 commented on src/main/java/lotto/LottoGame.java
> +		}, 0));
감사합니다~!

2021-09-06 13:28 UTC, brawman2 commented on src/main/java/lotto/LottoPaper.java
> +public class LottoPaper implements LottoReport {
ResultView에서 LottoReport 형태로 사용하도록 했는데요.

lottoMatchCount와 profit만 외부에서 사용하도록하려고 LottoReport인터페이스를 만들어봤네요~!

흠 개념상 인터페이스 사용이 잘못되었는지 알려주시면 감사하겠습니다😅

2021-09-06 13:29 UTC, brawman2 commented on src/main/java/lotto/LottoGame.java
> +		});
넵 감사합니다~!

2021-09-06 13:31 UTC, brawman2 commented on src/main/java/lotto/Lotto.java
> +	public String toStringLottoNumbers() {
InputView에서 사용되고 있어요~! 아래 LottoReport와 같이 외부에서 사용하는 함수를 인터페이스로 정의해봤는데요.

잘못된 사용인지 피드백 부탁드려요~!😓

2021-09-06 13:31 UTC, brawman2 commented on src/main/java/lotto/Lotto.java
> +public class Lotto implements LottoTicket {
외부에서 사용하는 인터페이스로 분리해봤는데요.. 이상할까요??

2021-09-06 13:31 UTC, brawman2 commented on src/main/java/lotto/LottoRank.java
> +	FIRST(6, 2_000_000_000) {
감사합니다~!

2021-09-06 13:32 UTC, brawman2 commented on src/main/java/Application.java
> +		LottoGame game = LottoGame.of(1000, 1, 45, 6);
흠 로또 숫자들의 범위도 변경 가능할 수도 있다고 생각해서 외부에서 주입 받도록 구현해봤네요;;

이상할까요??😓

2021-09-08 00:36 UTC, dbeod2 commented on src/main/java/lotto/Lotto.java
> +public class Lotto implements LottoTicket {
아하 네네 의도 확인차 물어봤던 것 이었습니다!

2021-09-08 00:36 UTC, dbeod2 commented on src/main/java/lotto/Lotto.java
> +	public String toStringLottoNumbers() {
네 ㅠ.ㅠui로직은 프로덕트 로직에서 분리해주시는게 좋을 것 같습니다! 🙏