Step2 - 로또(자동)
next-step/java-lotto pull request #2019
Opened 2021-08-28 10:49 UTC by devchang202

로또 Step 2 리뷰 부탁드립니다.

한 가지 질문이 있습니다.
TDD에서는 Test case들은 기능 사양서(동작의 문서)와 같다는 말씀을 듣기도 했고, 
이전 step1 문자열 덧셈 계산기의 예시 Test case를 보니까 명확히 기능 단위로 Test case를 나누어 작성되어 있는 것을 보았습니다.

그래서 자동자 경주 미션까지는 Test case 작성 연습 위주로 진행하면서 거의 메소드 단위로 Test Case를 작성했었는데 저도 제가 분류한 기능 요구 사항 단위로 Test case를 먼저 작성해서 코드를 작성해 보았습니다. 
이렇게 해보니까 한편으로는 세세한 메소드 단위의 Test를 작성하는게 맞나 싶기도한 생각이드는데요, 혹시 어떻게 생각하시는지 의견을 여쭤보고 싶습니다.

2021-08-29 07:06 UTC, vagabond95 requested changes
2단계 미션 잘 진행해주셨습니다 ㅎㅎ

제가 생각하는 테스트 코드의 목적은 말씀하신 것 처럼 기능의 명세를 테스트하기 위한 것이라 생각됩니다.

또한 하나의 기능은 하나의 메소드로 수행될수도, 그 이상이 필요할 수도 있으므로 단순히 메소드단위로 보기보단 기능단위로 보는게 맞을 것 같습니다! 그런 측면에서 잘 작성해주신 것 같습니다 :)

구현하신 내용에 대하여 몇가지 코멘트 남겼는데요, 확인 후 다시 리뷰 요청 부탁드립니다!

2021-08-29 07:06 UTC, vagabond95 commented on src/main/java/lotto/domain/Prize.java
> +    public int index() {
index 가 꼭 필요한 값일까요~?

다른 것을 key 값으로 대체할 수 있을까요?

2021-08-29 07:06 UTC, vagabond95 commented on src/main/java/lotto/domain/Lottos.java
> +        if (Prize.FIRST.matchingCount() == matchingCount) {
이러한 로직은 특정 등수가 추가될 때마다 코드에 변경사항이 발생할 것 같습니다.
특정 등수를 따로 검사하지 않는 로직으로 변경해볼 수 있을까요?

2021-08-29 07:06 UTC, vagabond95 commented on src/main/java/lotto/domain/Lotto.java
> +    void checkValidNum(int num) {
각 번호가 중복되지 않는지에 대한 검사도 필요하지 않을까요?

2021-08-29 07:06 UTC, vagabond95 commented on src/main/java/lotto/domain/AutoGenerateStrategy.java
> +        for (int i = 0; i < totalLottosNum; i++) {
Lotto 가 단일로 필요할 케이스도 있을 것 같고, 개인적으로 2중 배열은 가독성을 많이 해친다고 생각되는데요, 

Lotto 는 단일로 제공하고 외부에서 N 번 반복하여 Lottos 를 만드는 것은 어떨까요?

2021-08-29 07:06 UTC, vagabond95 commented on src/main/java/lotto/domain/AutoGenerateStrategy.java
> +public class AutoGenerateStrategy implements GenerateNumStrategy {
Generate 하는 대상이 드러나면 좋을 것 같습니다!

2021-08-30 06:44 UTC, devchang202 commented on src/main/java/lotto/view/InputView.java
> +    static boolean isValidMoney(int money) {
피드백 감사합니다. 관련 부분에 대해 질문이 있습니다.

1. Domain의 money에서도 checkValidMoney 메소드를 이용해서 데이터 유효성 검사를 합니다. InputView에서 isValidMoney는 UI 측면에서 적합하지 않은 형태의 money 값을 입력하면 재입력을 요청하는 기능을 만들기 위해서 만든 메소드 인데, View에서의 부가적인 기능을 위해 작성된 것이라도 불필요하다고 생각하시나요?

2. 저도 코드 작성할 때 지적하신대로 domain의 참조가 최대한 분리되어야 된다고 생각하시면서도, domain의 상수값을 사용하는 방식에 대해서 확신이 없어서 일단 그렇게 작성해보았습니다.
그렇다면 한가지 의문이, ResultView에서 처럼 Domain의 값을 가져오기 위해서 어쩔 수 없이 domain의 class를 사용하여 인스턴스를 매개변수를 전달받고, domain에 선언된 함수 (getLottoList 등)을 사용하였는데, 이 또한 옳지 못한 domain 코드 참조라고 보시는 건지 궁금합니다.

2021-08-30 10:17 UTC, devchang202 commented on src/test/java/lotto/domain/LottoMachineTest.java
> +        LottoMachine lottoMachine = new LottoMachine(new GenerateNumStrategy() {
해당 어노테이션은 제가 숙지를 못하고 있었네요.
@BeforeEach를 사용해서 반영했습니다.

그런데  @BeforeEach에 작성한 공통된 동작을 필요로 하지 않는 Test Case 들에 한해서는 Test Class를 분리해서 작성하는 게 아무래도 더 낫겠죠?

2021-08-30 10:19 UTC, devchang202 commented on src/main/java/lotto/domain/LottoMachine.java
> +    public int buyableLottos() {
넵 반영하였습니다.
그런데 Enum 객체들의 데이터 요소를 가져오는 메소드들도 똑같이 동사로 시작하는게 맞을까요?
ordinal()처럼 Enum의 key값을 가져오는 메소드 명칭과 통일성은 없겠다 싶은생각이 들어서요.

2021-08-30 10:20 UTC, devchang202 commented on src/main/java/lotto/domain/Prize.java
> +    int winningMoney(int count) {
넵 반영하였습니다.

2021-08-30 10:20 UTC, devchang202 commented on src/main/java/lotto/domain/Prize.java
> +    FIRST(0, 6, 2000000000),
넵 반영하였습니다.

2021-08-30 10:22 UTC, devchang202 commented on src/main/java/lotto/domain/Prize.java
> +    public int index() {
아 Enum의 ordinal()을 사용할 수 있다는 것을 생각을 못했네요.
index를 삭제하고 ordinal()을 사용하도록 반영하였습니다.

2021-08-30 10:22 UTC, devchang202 commented on src/main/java/lotto/domain/Lottos.java
> +        if (Prize.FIRST.matchingCount() == matchingCount) {
넵 반영하였습니다.

2021-08-30 10:23 UTC, devchang202 commented on src/main/java/lotto/domain/Lotto.java
> +    void checkValidNum(int num) {
넵 반영하였습니다.

2021-08-30 10:23 UTC, devchang202 commented on src/main/java/lotto/domain/AutoGenerateStrategy.java
> +        for (int i = 0; i < totalLottosNum; i++) {
넵 반영하였습니다.

2021-08-30 10:23 UTC, devchang202 commented on src/main/java/lotto/domain/AutoGenerateStrategy.java
> +public class AutoGenerateStrategy implements GenerateNumStrategy {
넵 반영하였습니다.

2021-08-31 11:13 UTC, vagabond95 commented on src/test/java/lotto/domain/LottoMachineTest.java
> +        LottoMachine lottoMachine = new LottoMachine(new GenerateNumStrategy() {
넵 공통되지 않는 부분들은 말씀해주신 부분대로 해주셔도 무방할 것 같습니다 ㅎㅎ

2021-08-31 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoMachine.java
> +    public int buyableLottos() {
말씀하신 것처럼 동사형으로 시작되지 않는 케이스도 있습니다!
ex) list.length() 

그런데 요런 메소드도 명사로는 표현이 되어있더라도 형용사 식의 표현은 거의 없는 것 같더라구요! 사실 컨벤션은 정하기 나름이지만 정말 특별한 이유가 없다면 동사형으로 맞춰주면 좋을 것 같습니다 ㅎㅎ
https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names

2021-08-31 11:21 UTC, vagabond95 approved these changes
리뷰 확인이 너무 늦었네요 😢  

피드백 잘 반영해주셨습니다 👍 👍 질문 주신내용에 대해서도 하위 코멘트로 남겼는데 확인 부탁드려요!
2단계는 머지하도록 하겠습니다~!!!

2021-08-31 11:21 UTC, vagabond95 commented on src/main/java/lotto/view/InputView.java
> +    static boolean isValidMoney(int money) {
1. isValidMoney 는 전달받은 인수가 특정 범위내에 속하는지를 검사하는 로직인데요~! 요러한 로직의 유무를 판단할 때는 View 에서 활용이 가능한지 여부보다는, Domain 영역에서 변경이 발생했을 때 View 에도 영향이 가는지를 살펴보면 좋을 것 같습니다 ㅎㅎ 현재는 재입력을 요청하는 곳에만 쓰이지만 추후에 사용범위가 늘어나게 된다면 View 에는 Domain 의 제약사항에 대해 여러곳에서 영향을 받으므로 분리되는 것이 더 적절하지 않을까 싶습니다!

2. 좋은 질문이십니다 :) ResultView 에도 원칙을 지킨다면 Domain 모델을 그대로 전달하기 보다 View 에 그리기위한 모델르 한번 변환하여 전달하는 것이 좋다고 생각합니다. 소위 말하는 DTO 클래스가 이러한 역할을 수행한다고 보시면 될 것 같습니다~! 

어디까지느 옳지 못한 코드는 없다고 생각합니다. 다만 변경이 없는 코드 또한 없으니 어느것이 변경에 좀 더 유연하게 대처가 가능할지를 초점으로 두고 고민을 해봤습니다 :)

2021-08-31 11:21 UTC, merged