step3 리뷰요청드립니다.
next-step/java-lotto pull request #2029
Opened 2021-08-31 15:42 UTC by sixthou

2021-09-02 00:33 UTC, ep1stas1s requested changes
미션 잘 구현해주셨네요 👍 
코멘트 참고해보시고 궁금한 점 있으시면 언제든 DM주세요ㅎㅎㅎ

2021-09-02 00:33 UTC, ep1stas1s commented on src/main/java/lotto/view/InputView.java
> +        List<Integer> numbers = splitStringToIntegerList(numberString);
음 view에서 직접적으로 도메인을 사용하기보단, List<Integer>정도로만 넘겨주는건 어떨까요~?

2021-09-02 00:33 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoTicket.java
> +        final LottoNumberSelectPolicy lottoNumberSelectPolicy) {
```suggestion
    public LottoTicket(final int ticketSize,
                       final LottoNumberSelectPolicy lottoNumberSelectPolicy) {
```
팀마다 컨벤션은 다르겠지만... 자바에선 일반적으로 파라미터 기준으로 정렬을 맞출거에요ㅎㅎㅎ
(자동 포멧팅으로 설정가능합니다!)

2021-09-02 00:33 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoTicket.java
> +                winningNumbers.checkBonusNumber(lottoNumbers)));
메서드에서 바로바로 객체를 반환해주면 더 깔끔해질 것 같아요~
예를 들어
```java
// WinningNumbers.java
public LottoRank match(LottoNumbers lottoNumbers) {
    // matching logic...
    return LottoRank.findRank(...);
}
```

2021-09-02 00:33 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoTicket.java
> +    public List<LottoRank> getLottoRanks(final WinningNumbers winningNumbers) {
(위 코멘트에 이어서)
그럼 여기도 바로 `LottoResult`를 반환해주는 방식으로도 할 수 있을 것 같습니다 :)

2021-09-02 00:33 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumbers.java
> +    public int getMatchCount(LottoNumbers winningNumbers) {
get보다는 조금 더 의미있는 동사를 사용해보면 어떨까요ㅎㅎ

2021-09-02 00:33 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumbers.java
> +    public boolean isContained(LottoNumber lottoNumber) {
요기도 size 메서드랑 비슷한데요ㅎㅎ 아래 라인처럼 contains를 사용하면 더 명확할 거 같아요!

2021-09-02 00:33 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumbers.java
> +            + lottoNumbers.stream().map(Object::toString).collect(Collectors.joining(", "))
toString()메서드가 View에 의존적으로 사용되는것 같아요~
toString()은 보통 객체의 상태를 표현하기 위해 사용되어, 정해진 규칙에 의해서 재정의하는게 좋습니다.
(일반적으로 generate - toString()을 사용하여 생성합니다)

2021-09-02 00:33 UTC, ep1stas1s commented on src/main/java/lotto/domain/WinningNumbers.java
> +public class WinningNumbers {
간단하게나마 TDD 습관을 만들어보셔도 좋을 것 같습니다 ^_^

2021-09-02 00:33 UTC, ep1stas1s commented on src/test/java/lotto/domain/LottoResultTest.java
> +        assertThat(lottoResult.getProfitRate(price)).isEqualTo(
`LottoResult.java` 파일에 변경사항이 없어서 여기 남깁니다ㅎㅎㅎ
생성자에 아래와 같은 코드가 있는데, Map의 getOrDefault(...) 메서드를 사용하면 초기화를 진행하지 않아도 의도대로 사용할 수 있을 것 같아요ㅎㅎ
```java
Arrays.stream(LottoRank.values()).forEach(
            lottoRank -> result.put(lottoRank, 0)
        );
```

2021-09-02 15:34 UTC, sixthou commented on src/main/java/lotto/constraint/Constraint.java
> +    public static final int MIN_NUMBER = 1;
동일한 제약조건을 각각의 도메인마다 위치시키면 코드의 중복이 발생하고, 하나의 클래스에서 관리하는 것이 더 관리에 편하지 않을까 싶어서 Constraint를 생성했습니다. 제약조건을 각 도메인마다 위치시키는게 더 효율적인가요?

2021-09-02 15:40 UTC, sixthou commented on src/main/java/lotto/domain/LottoTicket.java
> +    public List<LottoRank> getLottoRanks(final WinningNumbers winningNumbers) {
위에 남겨주신 피드백은 메서드를 계속 호출하면서 코드가 지저분해진 부분인데 이 부분은 어떤걸 말씀하시는지 잘 모르겟네요,,

2021-09-03 10:16 UTC, ep1stas1s approved these changes
리팩토링 잘 해주셨네요 👍 
답변과 코멘트 몇가지 남겼으니 참고해서 다음 스텝 진행해주세요^_^

2021-09-03 10:16 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoTicket.java
> +    }
```suggestion
    public LottoResult getLottoRanks(final WinningNumbers winningNumbers) {
        List<LottoRank> lottoRanks = new ArrayList<>();
        for (LottoNumbers lottoNumbers : tickets) {
            lottoRanks.add(winningNumbers.match(lottoNumbers));
        }
        return new LottoResult(lottoRanks);
    }
```
https://github.com/next-step/java-lotto/pull/2029/files#r701206704 요런 의미였습니다

2021-09-03 10:16 UTC, ep1stas1s commented on src/main/java/lotto/constraint/Constraint.java
> +    public static final int MIN_NUMBER = 1;
어떤식으로 중복이 생긴다는 말씀이실까요...?
혹시 priavte으로 생각하셨다면, 위 코드와 동일하게 public 으로 사용한다고 보시면 될 것 같습니다

2021-09-03 10:16 UTC, ep1stas1s commented on src/main/java/lotto/domain/WinningNumbers.java
> +    private void ValidBonusNumberDuplication() {
```suggestion
    private void validBonusNumberDuplication() {
```

2021-09-03 10:16 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumbers.java
> +            + lottoNumbers.stream().map(Object::toString).collect(Collectors.joining(", "))
만약 콘솔환경에서 웹환경으로 변경된다면, 해당 메서드는 사용되지 않겠네요...!
꼭 toString() 메서드가 아니더라도 도메인에서 뷰에 의존적으로 사용하는 방식은 잦은 코드 변경을 초래할 수 있습니다 :)

2021-09-03 10:16 UTC, merged