Step4 - 로또(수동)
next-step/java-lotto pull request #2043
Opened 2021-09-07 11:55 UTC by devchang202

코드 리뷰 부탁드립니다.

2021-09-08 12:35 UTC, vagabond95 requested changes
자동 번호와 수동 번호를 관리하는 클래스를 두신 선택이 좋은 것 같습니다 👍 
이전 단계에서 피드백 드렸던 부분도 모두 잘 반영해주셨네요!

아주 작은 코멘트 드렸는데 마지막으로 확인 부탁드릴게요! 로또미션 진행하시느라 고생많으셨습니다 :)

2021-09-08 12:35 UTC, vagabond95 commented on src/main/java/lotto/domain/AffordableLottoCount.java
> +    void validate(int totalAffordableCount, int manualLottoCount) {
private 으로 제공해도 되지 않을까요~?

2021-09-08 12:35 UTC, vagabond95 commented on src/main/java/lotto/domain/AffordableLottoCount.java
> +    void validate(Money money, int manualLottoCount) {
private 으로 변경해도 괜찮지 않을까요? :)

2021-09-08 12:35 UTC, vagabond95 commented on src/main/java/lotto/domain/AffordableLottoCount.java
> +public class AffordableLottoCount {
수동 로또 개수와 자동 로또 개수를 분리 👍

2021-09-08 14:39 UTC, devchang202 commented on src/main/java/lotto/domain/AffordableLottoCount.java
> +    void validate(int totalAffordableCount, int manualLottoCount) {
아 그러네요 접근제어자를 신경 잘 써야겠네요 :)
리뷰 감사합니다 ㅎ

2021-09-09 15:54 UTC, vagabond95 approved these changes
로또 미션 진행하시느라 정말 고생 많으셨습니다! 
남은 기간이 얼마 남지 않았지만 마지막 미션까지 화이팅 이십니다!

2021-09-09 15:54 UTC, merged