Step3 - 로또(2등)
next-step/java-lotto pull request #2047
Opened 2021-09-09 14:44 UTC by brawman2

안녕하세요~!

2단계에서 피드백 주신 내용 반영했습니다~!

2등 기능을 위해서 보너스 숫자를 추가했습니다.

잘 부탁 드려요😀

2021-09-10 05:10 UTC, dbeod2 requested changes
안녕하세요! 

로또 (2등) 미션 잘 진행해주셨습니다! 
추가로 확인필요한 부분이 있어서 코멘트 남겨드렸는데 확인해보시고 리뷰 재요청 주세요 🙇🏻‍♀️

2021-09-10 05:10 UTC, dbeod2 commented on src/main/java/Application.java
>  	public void startLottoGame() {
로또 구입 최소 금액은 1000원 입니다 🥲
확인 부탁드립니다! 

<img width="757" alt="스크린샷 2021-09-10 오후 1 59 39" src="https://user-images.githubusercontent.com/70149382/132802042-ac4a2f6f-4ac2-493f-a9f4-0ab19b458b37.png">

2021-09-10 05:10 UTC, dbeod2 commented on src/main/java/lotto/LottoRank.java
>  public enum LottoRank {
5개 로또가 맞은 후 보너스볼까지 맞았을때 결과가 5개로 잡히고있네요 🥲
이부분도 확인 부탁드려요! 
<img width="782" alt="스크린샷 2021-09-10 오후 2 02 12" src="https://user-images.githubusercontent.com/70149382/132802220-db32c1d5-6b2c-460c-a040-f3fa10e722ff.png">

2021-09-10 05:10 UTC, dbeod2 commented on src/main/java/lotto/LottoNumbers.java
> +	private final int bonusNumber;
로또 번호는 최대 45입니다
45 이상 번호가 들어 왔을때의 예외처리도 필요해 보여요 🙏
<img width="723" alt="스크린샷 2021-09-10 오후 2 07 47" src="https://user-images.githubusercontent.com/70149382/132802749-f1f7dc7d-059d-481c-8f6e-094bc5346b4d.png">

2021-09-11 11:13 UTC, brawman2 commented on src/main/java/lotto/Lotto.java
> +	public List<Integer> lottoNumbers() {
감사합니다~!

2021-09-11 11:14 UTC, brawman2 commented on src/main/java/lotto/LottoGame.java
> +			return makeLottoNumbers(minimum, maximum, count);
감사합니다~!

2021-09-11 11:14 UTC, brawman2 commented on src/main/java/Application.java
>  	public void startLottoGame() {
예외처리가 부족했었네요😥

2021-09-11 11:14 UTC, brawman2 commented on src/main/java/lotto/LottoRank.java
>  public enum LottoRank {
제가 로또 규칙을 잘못 이해하고 있어서 수정했습니다~!😓

2021-09-12 00:50 UTC, dbeod2 approved these changes
안녕하세요! 희운님

로또(2등)미션 잘 수행해주셨네요 
몇가지 코멘트 남겨드린부분이 있는데 다음단계에서 반영해주셔도 될 것 같아서 
이번미션 머지하겠습니다 :-) 

그럼 다음미션을 진행해주세요!

2021-09-12 00:50 UTC, dbeod2 commented on src/main/java/lotto/Lotto.java
> +			.collect(Collectors.toList());
생성자에서는 변수 초기화에 집중되면 좋을 것 같은데요! 
현재도 잘 해주셨는데 lottoNumbers를 생성자 주입 전 가공 후 생성자로 값만 넘겨주면 어떨지 의견드립니다!

2021-09-12 00:50 UTC, dbeod2 commented on src/main/java/lotto/Lotto.java
> +		return true;
if문 조건절 자체 return값이 boolean값이네요! :-) 
아래와 같이 표현 가능 하겠네요! 
```suggestion
		return lottoNumbers.size() == LottoRule.LOTTO_NUMBER_COUNT;
```

2021-09-12 00:50 UTC, dbeod2 commented on src/main/java/lotto/LottoNumber.java
> +	}
위에 리뷰와 동일합니다.! :-) 
아래처럼 바로 return해주셔도 될 것 같아요! 
```suggestion
			return number >= LottoRule.LOTTO_MINIMUM_NUMBER && LottoRule.LOTTO_MAXIMUM_NUMBER >= number;
```

한가지 더  의견을 드리자면 현재 지난주 당첨 번호와 보너스볼에 45이상 숫자를 입력하면 오류가 나는데요! 
오류가 나는 시점이 보너스 볼까지 입력 후 나오는 오류라서 정확히 어떤 숫자에서 나타나는 오류인지 인지가 잘 되지 않고 있습니다!  확인 부탁드릴께요!

2021-09-12 00:50 UTC, dbeod2 commented on src/main/java/lotto/LottoRule.java
> +public class LottoRule {
여러곳에서 사용하는 상수들을 모아두셨네요! 👏🏻

2021-09-12 00:50 UTC, merged