Step4
next-step/java-lotto pull request #2049
Opened 2021-09-10 06:37 UTC by minyul

안녕하세요! 정말 정말 너무 감사하게 생각하고 있습니다.
일정이 빠듯하여 빠르게 리뷰를 받고 해야하는 부분에 있어서 정말 빠르게 리뷰해주시고
또한, 정말 잘알려주세요 ㅠ- ㅠ 너무 감사합니다!

2021-09-10 13:32 UTC, yongdae requested changes
안녕하세요~ 민율님. :)

빠르게 4단계 미션을 진행해주셨네요. 👍 
수고하셨습니다!!

진행해주신 내용에 대해 몇가지 의견을 드렸습니다.
확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

2021-09-10 13:32 UTC, yongdae commented on src/main/java/util/Result.java
> +	private static final Map<Rank, Integer> rankMap = new HashMap<>();
이전 단계의 피드백을 잘 반영 해주셨네요. 👍

2021-09-10 13:32 UTC, yongdae commented on src/main/java/controller/LottoGame.java
>  		LottoCalculator calculator = new LottoCalculator();
![스크린샷 2021-09-10 오후 10 15 31](https://user-images.githubusercontent.com/4317804/132859099-a85ff407-872d-45d2-b062-55ece09f6387.png)

수익룰 표기가 맞지 않아요. 😢

2021-09-10 13:32 UTC, yongdae commented on src/main/java/controller/LottoGame.java
>  		LottoCalculator calculator = new LottoCalculator();
![스크린샷 2021-09-10 오후 10 17 37](https://user-images.githubusercontent.com/4317804/132859285-abf2c406-b296-4e2c-b662-0cb9b7966233.png)
LottoCalculator에 대한 테스트 코드가 컴파일 단계에서 오류가 생겨요.

2021-09-10 13:32 UTC, yongdae commented on src/main/java/service/LottoCalculator.java
>  	}
수동 구매와 자동 구매에 대한 테스트 코드를 추가해보면 어떨까요?

테스트 코드는 미션 요구 사항을 만족시켰다는 증거라고 생각해요.
4단계에서 이야기하는 수동 구매에 대한 테스트 코드를 추가하면 좋을 것 같아요. :)

2021-09-10 13:32 UTC, yongdae commented on src/main/java/util/Input.java
> +		return lottos;
수동으로 로또 구매하는 부분은 UI와 분리하면 어떨까요?

수동 구매를 위해 사용자에게 입력 값은 받는 것은 맞지만
그렇다고 UI와 비지니스가 결합 될 필요는 없다고 생각해요.

이부분은 UI와 비지니스를 나누어 생각해보면 좋겠습니다. 😄

2021-09-10 13:32 UTC, yongdae commented on src/test/java/domain/AccountTest.java
> +	void test_return_lotto() {
Account를 사용해서 로또 구매에 대한 테스트를 잘 만들어 주셨네요. 👍

2021-09-11 01:01 UTC, minyul commented on src/main/java/util/Input.java
> +		return lottos;
궁금한게 있습니다. 혹시 코드는 어떤가요!?
`List<Lotto> lottos = new ArrayList<>();` 이렇게 초기화를 해주고 넣어주는게 좋은 방법인지 궁금합니다!

2021-09-11 02:03 UTC, minyul commented on src/main/java/controller/LottoGame.java
>  		LottoCalculator calculator = new LottoCalculator();
3000원에 샀고 30_000_000원을 벌었으면..... 3000/30_000_000 ... 이 맞겠죵!? 수정했습니다!

2021-09-11 06:55 UTC, yongdae commented on src/main/java/util/Input.java
> +		return lottos;
현재 구조에서는 이야기 해주신 방법이 좋은 방법이라고 생각합니다. :)

2021-09-11 07:13 UTC, yongdae requested changes
안녕하세요. 민율님 ~ :)
주말에도 열심히 피드백을 잘 반영해주셨네요. 👍 

소소하지만 테스트를 통해 매듭지었으면 하는 부분이 있어 다시 의견을 드렸습니다.
확인하시고 다시 리뷰 요청 부탁드려요 ~ 🔥

2021-09-11 07:13 UTC, yongdae commented on src/main/java/util/Input.java
> +		return new Lotto(numbers.stream().map(data -> new Number(Integer.parseInt(data))).collect(Collectors.toList()));
Stream을 사용해주셨네요. 👍 

List를 선언해서 사용하는 방법에 대해 어떤지 의견을 물어보셨는데 더 좋은 방법을 활용해주셨네요. :)

2021-09-11 07:13 UTC, yongdae commented on src/main/java/service/LottoCalculator.java
> +	public Integer getAutoLottoCount(Account account, List<Lotto> manualLottos) {
이 기능을 Account로 옮겨보면 어떨까요?

Account를 사용하면 금액(Account)만으로 자동으로 구매 할 수 있는 로또 갯수를 구할 수 있지않을까요?
아니면 List<Lotto> manualLottos를 받지 않고 수동 구매 갯수를 받아서 사용하는게 좋을것 같아요. :)

2021-09-11 07:13 UTC, yongdae commented on src/test/java/service/LottoCalculatorTest.java
> +	void test_auto_size() {
자동 로또 갯수를 확인하는 테스트를 잘 만들어 주셨네요. 👍

2021-09-11 10:34 UTC, yongdae approved these changes
안녕하세요. 민율님 ! :)

주말에도 열심히 미션을 진행해주셨네요. 💯 
물론 피드백도 잘 반영해주셨구요!

민율님이 피드백을 잘 따라와주셔서 재미있게
리뷰를 진행 할 수 있었던 것 같습니다. 😄 

미션 마지막까지 열심히 해주셔서 감사드립니다!
진행해주신 내용에 대해 소소하지만 의견을 드린 부분이 있으니 확인만 부탁드려요~

그럼 볼링 미션까지 완주하시길 응원하겠습니다. 🙏 
수고하셨습니다. :)

2021-09-11 10:34 UTC, yongdae commented on src/test/java/domain/AccountTest.java
> +	void test_return_yield() {
수익률를 테스트하는 코드를 잘 만들어주셨네요. 👍

2021-09-11 10:34 UTC, yongdae commented on src/main/java/domain/Account.java
> +	public Integer lottoCountByUnit(Integer count) {
lottoCountByUnit 대신 spend나 buy 같은 이름으로 바꾸면 어떨까요? 🤔 

메소드명 뿐만 아니라 매개변수로 로또 1장의 가격(UNIT)도 같이 받을 수 있게 메소드를 변경하면
Account는 로또 뿐만 아니라 여러가지를 구매 할 수 있게 될 수 있어요.

뿐만 아니라 구매에 대한 유효성 검사를 추가 한다면
Acount는 구매에 대한 역할을 더 충실히 수행 할 수 있다고 생각해요. :)

2021-09-11 10:34 UTC, merged