[로또] 2단계 - 로또(자동)
next-step/java-lotto pull request #2059
Opened 2021-11-09 19:16 UTC by simjunbo

휘준님 안녕하세요!
로또 구입과 당첨번호 구현까지는 최대한 TDD로 짰는데
마지막 당첨 통계 부분이 생각보다 구현이 잘 안되서 TDD로 하진 못했고 기능개발 후, 나중에 테스트 추가했습니다. (ㅠㅠ 아직 TDD가 익숙하지 않네요)

자동차 경주 구현때 부터 최대한 게터를 사용하지 않으려고 노력중인데
그러다 보니 어떤 객체에 메시지를 던져서 작업을 해야 할까 고민이 많이 되고
그로인해 클래스가 많아 지더라고요. 객체를 역할에 따라 잘 나눈것인지 모르겠네요.
부족하지만 피드백 많이 부탁드립니다 :)

## 고려 사항
- getter 사용하지 않기 (view, dto 제외)
- 모든 원시값과 문자열을 포장
- 3개 이상의 인스턴스 변수를 가진 클래스 배제
- 일급 컬렉션 사용
- 함수 길이가 15라인 넘어가지 않도록 구현
- 핵심 로직을 구현하는 코드와 UI 로직 분리
- 최대한 비즈니스 로직은 단위 테스트 구현 (가급적 TDD)
- 객체 생성 시, 최대한 사전 체크 조건 추가

2021-11-09 19:20 UTC, simjunbo commented on src/main/java/lotto/service/domain/types/Rank.java
> +    FIRST(6, 2_000_000_000),
요 부분은 로또 3단계 좀 보다 가지고 왔습니다 ...

2021-11-09 19:35 UTC, simjunbo commented on src/main/java/lotto/service/domain/LottoTicket.java
> +    public String toString() {
레이싱 카에서 UI에 정보를 뿌려줄때 일급컬렉션 => 객체 => 객체  이런식으로 타고 타고 getter를 추가해야되더라고요...
그래서 이번에 최대한 toString 을 이용해서 정보를 출력하게 했습니다.
UI 로직이 비즈니스 까지 침투 되는것 같아서 ㅠㅠ 고민을 좀 했지만 우선 최대한 getter를 없애는 방향으로 처리했습니다.
요 부분에 대해서 피드백 주시면 감사하겠습니다.

2021-11-09 23:56 UTC, wheejuni requested changes
대단히 수고 많으셨습니다. 👍 
특히 View 단에서 그간의 수고와 노력이 느껴집니다. 뷰 작업은 늘 삽질이죠 ㅠㅠ
궁금해하실 만한 사항과 질문에 대한 답변 위주로 피드백 퀵하게 남겨 보았습니다.
사실 이거 말고도 손대보면 좋을 부분들이 좀 있긴한데 우선 첫 스텝이라 가볍게 시작해 봅니다.
피드백 체크해주시고 코드 수정 부탁드려요. 대단히 고생 많으셨습니다. 💯

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/LottoApplication.java
> +    }
한 클래스에 `private` 메소드가, 그것도 `static` 한 것들이 이렇게 많다면 뭔가 잘못되어 가고 있다는 강력한 신호인데요,
이런 코드가 발생하지 않도록 구조를 조금만 더 고민해보시면 좋을 것 같습니다.

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/LottoApplication.java
> +        LottoTicket winningLottoTicket = getWinningLottoTicket();
로또를 구입하고, 당첨 번호를 받아오고.... 다 한 클래스 안에서 이뤄져야 하는 역할일까요?

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/controller/LottoController.java
> +    public LottoController() {
`LottoService` 를 외부 주입 받을 수 있는 생성자 하나 있으면 좋을 것 같습니다!

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/controller/LottoController.java
> +        return purchasePrice.getLottoQuantity();
한 줄짜리 로직이고 `LottoPrice` 에 이미 위임되어 있는 만큼 이 프라이빗 메소드는 무의미한 것 같습니다.

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/controller/dto/LottoPurchaseRequest.java
> +public class LottoPurchaseRequest {
`Request` 라면 외부와 소통할 수 있는 인터페이스성 생성자나 메소드가 하나 있어야 할 것 같은데 보이지 않네요.
이를테면 `String` 에서 타입 변환할 수 있는 편의 메소드 등이 구현되어 있어야 할 것 같은데 없네요.
이 부분 고민해주세요. 있으면 유용할 것 같은데요...
혹은 제가 이름만 보고 이 클래스의 역할을 추론했기 때문에, 잘못된 추론을 한 것일 수도 있습니다.
그렇다면 이 클래스의 명칭을 다시 고민해주시면 좋겠네요.

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/rule/LottoRule.java
> +    }
어차피 `private` 으로 가려놔서 외부 접근은 안될 겁니다.

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/service/LottoService.java
> +    }
이 부분은 따로 빼내어서 독립된 컴포넌트(클래스) 로 구성하는 것이 어떨까요?

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/service/domain/LottoTicket.java
> +    public String toString() {
`.toString()` 을 이런 목적으로 사용하시면 안됩니다.
별도의 표현 문자열을 만들어주는 메소드를 따로 설계해주세요.

2021-11-09 23:56 UTC, wheejuni commented on src/main/java/lotto/service/domain/types/Rank.java
> +    }
👍 좋긴 한데 메소드명이 다소 모호한 것 같습니다. 한번만 더 고민해주세요

2021-11-10 09:43 UTC, simjunbo commented on src/main/java/lotto/service/domain/LottoTicket.java
> +    public String toString() {
역시 toString을 뷰 목적으로 사용하는게 좀 찝찝했는데 제거 하고
별도 처리했습니다. 피드백 감사합니다! 😄

2021-11-10 09:46 UTC, simjunbo commented on src/main/java/lotto/LottoApplication.java
> +    }
요 부분은 사실 view(UI) 쪽을 분리하고 싶어서 LottoApplication 에서 호출하게
만들었는데요. 우선 별도 메서드 분리 없이 main에서 호출 하는 부분으로 변경했습니다.

만약 필요하다면 controller 쪽에서 뷰까지 제어할 수 있도록 변경하겠습니다. 😄

2021-11-10 09:47 UTC, simjunbo commented on src/main/java/lotto/LottoApplication.java
> +        LottoTicket winningLottoTicket = getWinningLottoTicket();
안그래도 3단계에서 보너스 볼 입력을 받으려면 분리를 해야되서
마지막에 작업하려 했는데 까먹었네요! 😄 
분리 처리 하겠습니다. 피드백 감사합니다

2021-11-10 09:48 UTC, simjunbo commented on src/main/java/lotto/controller/LottoController.java
> +    public LottoController() {
넵 요 부분은 생성자 주입할 수 있게 변경했습니다 👍

2021-11-10 09:50 UTC, simjunbo commented on src/main/java/lotto/controller/LottoController.java
> +        return purchasePrice.getLottoQuantity();
넵 요 부분은 LottoPrice 직접 호출 하는 형태로 변경하겠습니다!

2021-11-10 09:51 UTC, simjunbo commented on src/main/java/lotto/controller/dto/LottoPurchaseRequest.java
> +public class LottoPurchaseRequest {
DTO 역할이였는데 네이밍이 애매했던것 같네요.
해당 클랙스 역할이 좀 불필요한것 같아서 삭제 후, LottoPrice 를 직접 넘기도록 처리했습니다.

2021-11-10 09:53 UTC, simjunbo commented on src/main/java/lotto/rule/LottoRule.java
> +    }
Utils 성 클래스 생성시 습관처럼 사용하고 있는데 (내부에서도 인스턴스화 금지하기위해서)
해당 클래스에서는 크게 필요 없어 보이네요. 삭제 하겠습니다!
참고) https://icarus8050.tistory.com/62

2021-11-10 09:54 UTC, simjunbo commented on src/main/java/lotto/service/LottoService.java
> +    }
넵 요부분 분리해서 별도 LottoResultMaker 란 클래스로 처리 시키겠습니다!

2021-11-10 09:54 UTC, simjunbo commented on src/main/java/lotto/service/domain/types/Rank.java
> +    }
넵 네이밍 변경하겠습니다!

2021-11-10 10:26 UTC, wheejuni approved these changes
👍 좋습니다. 3단계로 ㄱㄱ 부탁 드리겠습니다.

2021-11-10 10:27 UTC, merged