🎰 로또 - 로또(자동) (Step2)
next-step/java-lotto pull request #2067
Opened 2021-11-12 09:49 UTC by ChangmoKang

안녕하세요 리뷰어님:)

step1 문자열 덧셈 계산기 조언 주신 부분과 step2 기능구현 및 테스트 작성해보았습니다.

해당 기능을 구현하기 위한 객체들을 아래와 같이 정의하여 구현해보았는데요.
* Bag
* Money
* Lotto

객체 단위를 조금 더 늘려야 하거나 불필요한 부분과
리뷰 중 조금이라도 개선할 부분이 있다면 말씀 부탁드립니다🙏

2021-11-12 12:51 UTC, yongdae requested changes
안녕하세요. 창모님!
이전 단계 피드백을 포함해서 빠르고 멋지게 2단계 로또 미션을 진행해주셨네요. 👍 

설계해주신 내용에 대해 몇 가지 의견을 드렸습니다.
확인하시고 다시 리뷰 요청 부탁드려요~ 🔥 🔥

2021-11-12 12:51 UTC, yongdae commented on README.md
> +## 2단계 로또
2단계에서도 1단계에서와 마찬가지로 요구사항 분석을 토대로 기능을 잘 정리해주셨네요. 👍

2021-11-12 12:51 UTC, yongdae commented on src/test/java/lotto/BagTest.java
> +public class BagTest {
Bag을 이용해서 로또 구매에 대한 기능을 정의하고 테스트 해주셨네요. 👍

2021-11-12 12:51 UTC, yongdae commented on src/test/java/lotto/LottoTest.java
> +public class LottoTest {
로또노 Lotto 객체를 통해 잘 구현하고 테스트 해주셨네요. 👍

2021-11-12 12:51 UTC, yongdae commented on src/test/java/lotto/MoneyTest.java
> +public class MoneyTest {
금전과 관련 된 부분도 테스트 코드를 통해 잘 구현해주셨네요. 💯

2021-11-12 12:51 UTC, yongdae commented on src/main/java/lotto/Lotto.java
> +    private final List<Integer> numbers;
로또 번호에 해당하는 Integer에 규칙 3: 모든 원시값과 문자열을 포장한다. 이 규칙을 적용해보면 어떨까요? 🤔

미션에서 정의된 내용은 아니지만 로또 번호는 1 ~ 45 범위의 가진 숫자를 의미합니다.
즉 로또 번호는 유효 범위를 가지는 번호 객체라고도 볼 수 있는데요.

이 조건을 가지고 테스트를 포함한 로또 번호 객체를 만들어보면 좋을 것 같습니다. :)

2021-11-12 12:51 UTC, yongdae commented on src/main/java/lotto/Lotto.java
> +        this.numbers = LOTTO_NUMBERS.stream().limit(6).collect(Collectors.toList());
`LOTTO_NUMBERS.stream().limit(6).collect(Collectors.toList())`
번호를 만드는 부분을 메소드로 만들어보면 어떨까요?

2021-11-12 12:51 UTC, yongdae commented on src/main/java/lotto/Money.java
> +        if (unitPrice.value == 0) {
0은 매직 넘버 같아요!

2021-11-12 12:51 UTC, yongdae commented on src/main/java/lotto/view/ResultView.java
> +    private static final List<Double> PRIZE_LIST = Arrays.asList(
Enum을 활용해보면 좋을 것 같아요. 😄 

List를 이용해서 로또 당첨을 확인하는 것보다 Enum을 이용해 명시적으로 당첨 등급을 의미하는 객체를 만들어보면 어떨까요?
무의미한 0D, 0D, 0D도 지울 수 있고 한발 더 나아가서는 의도가 명확한 설계를 보여 줄 수도 있지 않을까요?

더불어 화면(ResultView)과 상관없이 당첨 등급에 대한 테스트도 만들 수 있어요!

2021-11-17 06:06 UTC, ChangmoKang commented on src/main/java/lotto/Lotto.java
> +        this.numbers = LOTTO_NUMBERS.stream().limit(6).collect(Collectors.toList());
@yongdae 피드백 주셔서 감사드립니다:)

좀 과한 감이 있지만 아래와 같이 메소드를 만들어 limit 부분을 parameter 로 받으려고 하는데요.
아직은 사용하지 않을 예정이고 추후에도 발생하지 않을 것 같다는 생각이 들어도
이렇게 해놓는게 좋은 습관인지 피드백 부탁드립니다🙏 (매직넘버는 일단 따로 처리하지 않았습니다)

```java
    public Lotto() {
        Collections.shuffle(LOTTO_NUMBERS);
        this.numbers = getNumbers(6);
    }

    private List<Integer> getNumbers(int numberCount) {
        return LOTTO_NUMBERS.stream().limit(numberCount).collect(Collectors.toList());
    }
```

2021-11-17 07:57 UTC, ChangmoKang commented on src/main/java/lotto/view/ResultView.java
> +    private static final List<Double> PRIZE_LIST = Arrays.asList(
피드백 주셔서 감사합니다!
해당 부분 List 를 사용하면서 이상하다고 생각했는데 enum 을 사용할 생각을 못했네요😅
enum 사용하여 리팩토링 후 다시 리뷰요청 드리겠습니다!

2021-11-17 12:48 UTC, yongdae commented on src/main/java/lotto/Lotto.java
> +        this.numbers = LOTTO_NUMBERS.stream().limit(6).collect(Collectors.toList());
이 부분은 얼마만큼 추상화를 시켜서 사용할지에 대한 고민이라고 생각되요.

개인적으로 이런 상황에서 판단하는 요소는 `필요성`입니다.
꼭 추상화를 시켜야하나? 라는 질문을 했을 때 필요하다라는 판단이 들면 작성해주신 코드처럼 일을 세분화하는 설계를 합니다.

이외에도 간혹 테스트 코드를 작성하다보면 기능의 분리가 필요한 부분이 보이고 자연스럽게 리팩토링을 하게 됩니다. :)

2021-11-17 13:28 UTC, yongdae requested changes
의견드린 부분을 잘 반영해주셨네요. 💯 

진행해주신 내용에 대해 의견을 드렸습니다~
확인하시고 다시 리뷰 요청 부탁드려요!! 🙇

2021-11-17 13:28 UTC, yongdae commented on src/test/java/lotto/LottoTest.java
> +    void 로또비교() {
로또 비교하는 부분까지 테스트를 추가해주셨네요. 👍

2021-11-17 13:28 UTC, yongdae commented on src/test/java/lotto/PrizeTest.java
> +public class PrizeTest {
Prize에 대한 테스트도 잊지 않고 해주셨네요. 👍

2021-11-17 13:28 UTC, yongdae commented on src/main/java/lotto/Prize.java
> +    public static Prize of(int hitCount) {
이 기능에 대한 테스트를 추가하면 더 좋을 것 같아요. :)

2021-11-17 13:28 UTC, yongdae commented on src/main/java/lotto/Prize.java
> +                .filter(p -> p.hitCount == hitCount)
변수 이름을 축약하지 않고 사용하면 좋을 것 같아요.

2021-11-17 13:28 UTC, yongdae commented on src/main/java/lotto/Lotto.java
> +    public Prize result(Lotto target) {
Lotto는 `맞은 갯수`를 반환하게 해보면 어떨까요? 🤔 

로또가 당첨 결과까지 반환하는 책임을 가지는게 좋을지 고민해보는게 좋을 것 같아요.
만약 당첨 내용이 변경되면 Lotto도 같이 수정되는 상황이 발생하지 않을까요?

2021-11-17 13:28 UTC, yongdae commented on src/main/java/lotto/Lotto.java
> +    private List<LottoNumber> getNumbers() {
로또 번호들(List<LottoNumber>)를 만드는 부분을 Lotto에서 분리해보면 어떨까요?

로또 번호들을 미리 만들어놓고 로또 번호가 필요할 때 마다 가져다 쓰는 형태의
클래스를 만들어 이 부분을 분리해보면 좋을 것 같아요!

2021-11-17 13:28 UTC, yongdae commented on src/main/java/lotto/Bag.java
> +        while (lottoCount-- > 0) {
0은 매직 넘버 같아요. 상수로 치환해서 의미를 주는게 어떨까요?

2021-11-17 13:28 UTC, yongdae commented on src/main/java/lotto/Bag.java
> +    public Map<Prize, Integer> lottoResult(Lotto target) {
Map<Prize, Integer> 대신 로또 당첨 결과를 표현하는 객체를 추가해보아도 좋을 것 같아요.

2021-11-17 13:28 UTC, yongdae commented on src/main/java/lotto/view/Client.java
> +    public static void main(String[] args) {
![스크린샷 2021-11-17 오후 10 21 30](https://user-images.githubusercontent.com/4317804/142208754-13c1af2e-a2c1-4f8c-baa3-02d42d6908fd.png)

[미션에서 제시한 결과](https://edu.nextstep.camp/s/Hn1vR4Vs/ls/8rS5bOT2)와 비슷한 화면을 출력해보면 좋을 것 같아요.

- 로또 구매 갯수 및 자동으로 생성한 로또 내용 출력 없음
- 등수별 당첨 통계 출력 없음(현재는 일부만 표기됨)
- 수익률에 따른 '손해' 또는 '이득' 표기 출력 없음

2021-11-17 13:28 UTC, yongdae commented on src/main/java/lotto/view/InputView.java
> +        this.winNumbers = Arrays.stream(new Scanner(System.in).nextLine().trim().split(", ")).map(Integer::parseInt).collect(Collectors.toList());
규칙 4: 한 줄에 점을 하나만 찍는다.

이 규칙을 적용해보면 어떨까요?

2021-11-18 05:30 UTC, ChangmoKang commented on src/main/java/lotto/Lotto.java
> +    public Prize result(Lotto target) {
Lotto 클래스가 Prize 와 강하게 결합되어 있었네요😅 조언 감사합니다!

2021-11-18 05:34 UTC, ChangmoKang commented on src/main/java/lotto/Lotto.java
> +    private List<LottoNumber> getNumbers() {
@yongdae 우선 조언 감사드립니다:)
LottoGenerator 느낌의 객체를 만들어야 한다는 말씀이신건가요?

위와 같은 객체가 있다고 했을 때
자동이면 lottoGenerator.auto()
수동이면 lottoGenerator.manual(1,2,3,4,5,6)
으로 하여 List<LottoNumber> 를 반환하는 방식을 말씀해주신건가요?

위와 관련하여 조금만 더 설명 부탁드립니다!

2021-11-18 05:36 UTC, ChangmoKang commented on src/main/java/lotto/Bag.java
> +        while (lottoCount-- > 0) {
@yongdae 리뷰어님 조언 감사드립니다:)

ZERO 와 같은 경우 많은 class 에서 발생하는데 Util 클래스를 만들어 static 으로 관리해야할까요?

결합도 측면에서 위와 같이 해서는 안되지만 그렇다고 수와 관련된 클래스에 모두 ZERO 를 선언하기는 좀 애매하여 질문드립니다.

2021-11-18 05:38 UTC, ChangmoKang commented on src/main/java/lotto/Bag.java
> +    public Map<Prize, Integer> lottoResult(Lotto target) {
Collection 을 사용할 때 코드가 조금 읽기 어려워진다고 생각하였는데 조언주신 방향으로 LottoResult 클래스를 만들어 진행해보겠습니다.

2021-11-18 05:39 UTC, ChangmoKang commented on src/main/java/lotto/view/InputView.java
> +        this.winNumbers = Arrays.stream(new Scanner(System.in).nextLine().trim().split(", ")).map(Integer::parseInt).collect(Collectors.toList());
다음 코드리뷰에 요청 전에 수정해 놓도록 하겠습니다:)

2021-11-18 05:41 UTC, ChangmoKang commented on src/main/java/lotto/view/Client.java
> +    public static void main(String[] args) {
해당 부분 모두 반영하여 리뷰요청 드리겠습니다!

2021-11-18 07:29 UTC, yongdae commented on src/main/java/lotto/Lotto.java
> +    private List<LottoNumber> getNumbers() {
@ChangmoKang 네 이야기하신 것처럼 LottoGenerator를 만들어보시면 어떨까요?
다만 자동에 개념은 필요하겠지만 수동인 경우는 필요가 없을 수도 있다고 생각되요.

2021-11-18 07:36 UTC, yongdae commented on src/main/java/lotto/Bag.java
> +        while (lottoCount-- > 0) {
@ChangmoKang

상수로 선언해서 사용하는 이유는 `값` 자체에 의미를 두기보다는 `어떤 용도로 사용되기 위한 값`인지를 상수 이름을 통해 표현한다고 생각해보셔도 좋을 것 같아요.

아무리 같은 0의 값이라지만 어느 곳에서는 empty를 표현 할 수도 있고 시작 위치 값이 될 수도 있어요. 즉 사용하는 용도에 따라 같은 0 이어도 다른 이름으로 선언해서 사용하는게 좋지 않을까요?

2021-11-18 12:32 UTC, yongdae approved these changes
피드백을 멋지게 반영해주셨네요! 👍 
하나의 의견을 드리면 그 이상을 고민해서 적용해주시네요!

감사합니다. 😄 

자 그럼 다음 단계로 넘어가도록하겠습니다.
진행해주신 내용에 의견을 드린 부분이 있으니 다음 단계에서 같이 반영 부탁드려요~

수고하셨습니다. 🙇

2021-11-18 12:32 UTC, yongdae commented on src/test/java/lotto/PrizeTest.java
> +    void constructorMethod(Prize self, int hitCount, int money) {
피드백을 잘 반영해주셨네요. 👍

2021-11-18 12:32 UTC, yongdae commented on src/main/java/lotto/view/ResultView.java
> +        final double yield = totalPrize / money;
수익률 부분도 LottoResult가 계산 할 수 있다면
테스트를 통해 수익률 계산도 검증 해볼 수 있지 않을까요? 🤔

2021-11-18 12:32 UTC, yongdae commented on src/main/java/lotto/view/Client.java
> +    public static void main(String[] args) {
구매한 로또 번호를 구매와 동시에 출력하게 하면 좋을 것 같아요!

지금은 당첨 번호 후 입력 후 출력이 되는 구조라 테스트 코드가 없다면 로또 당첨에 대한 확인이 어려워요. 😢

2021-11-18 12:32 UTC, yongdae commented on src/main/java/lotto/Money.java
> +    private static final int ZERO = 0;
상수는 위로 멤버 번수는 아래로 선언 순서를 바꿔보면 어떨까요?

2021-11-18 12:32 UTC, yongdae commented on src/main/java/lotto/LottoResult.java
> +        return result.containsKey(prize)
3항 연산자를 사용하지 말아주세요.

3항 연산자는 if else 문을 사용하는 것과 같아요.
즉 `규칙 2: else 예약어를 쓰지 않는다.` 이 규칙을 적용 할 수 있다는 의미이기도 합니다. :)

2021-11-18 12:32 UTC, yongdae commented on src/main/java/lotto/view/InputView.java
> +        return new Scanner(System.in).nextLine().trim().split(DELIMITER);
규칙 4: 한 줄에 점을 하나만 찍는다.

이 규칙을 적용해보면 좋겠어요!

2021-11-18 12:32 UTC, yongdae commented on src/main/java/lotto/LottoGenerator.java
> +                .collect(Collectors.toList());
로또 번호들은 미리 선언해놓고 사용해도 좋을 것 같아요. 😄 

로또 번호들은 [static 초기화](https://scshim.tistory.com/205)를 이용해서 생성하고
추첨된 번호를 필요로 할 때는 생성된 번호들을 이용해 반환하게 해보면 어떨까요?

2021-11-18 12:32 UTC, yongdae commented on src/main/java/lotto/Bag.java
> +    }
사용하지 않는 내용은 제거하는게 좋을 것 같아요~

2021-11-18 12:32 UTC, merged

2021-11-18 13:30 UTC, ChangmoKang commented on src/main/java/lotto/LottoResult.java
> +        return result.containsKey(prize)
간단한 문장이어서 3항 연산자를 사용하였는데 early return 의 가독성이 더 좋은 것 같습니다:) 조언 감사합니다~

2021-11-18 13:37 UTC, ChangmoKang commented on src/main/java/lotto/LottoGenerator.java
> +                .collect(Collectors.toList());
불필요하게 매번 `allLottoNumbers` 를 생성하고 있었네요😅 수정하겠습니다:)

2021-11-18 13:59 UTC, ChangmoKang commented on src/main/java/lotto/view/ResultView.java
> +        final double yield = totalPrize / money;
@yongdae 조언 감사드립니다!!

저도 이 부분이 조금 애매하다고 생각합니다.🤔

현재 아래와 같은 로직이어서 기존에 얼마를 들고 있는지 또는 로또 한장당 가격을 알 수가 없는데요.
1. 로또를 구매할 때 가지고 있던 돈을 unitPrice 에 맞추어 차감 됨
2. 로또 한장당 가격은 현재 Bag 에 있는 `buyLotto(unitPrice)` 에서 파라미터 형태로만 전달 받음

제가 위에처럼 설계한 이유는 제 코드에는 없지만 LottoStore 라는 객체가 있어서 해당 unitPrice 를 전달해 준다고 가정하였고 Bag 이나 다른 클래스들이 로또 한장당 가격을 알고있는게 제 생각에는 맞지 않다고 생각했기 때문입니다.

그래서 View 에서는 어짜피 사용자의 정보를 다 받아 놓았으니 전체 합산 당첨금만 반환해주고 View 에서 처리하는게 좋다고 생각하였습니다.

이 부분에 대해 조언 부탁드립니다!

2021-11-19 08:52 UTC, yongdae commented on src/main/java/lotto/view/ResultView.java
> +        final double yield = totalPrize / money;
이야기해주신 대로라면 수익률 계산 하는 부분은 별도의 수익률 계산기를 만들어보는게 좋을 것 같아요!

Bag이 처음에 입력한 사용자의 금액을 알고 있다고 생각했는데
의견 주신 부분을 참고해서 확인하니 Bag은 알고 있는 정보가 변경되기 때문에 수익률까지는 계산이 어렵다고 생각되네요. 😢