[로또] 1단계
next-step/java-lotto pull request #2078
Opened 2021-11-16 11:58 UTC by han0102

안녕하세요 리뷰어님.

1단계 문자열 덧셈 계산기에 대한 PR입니다.
그럼 리뷰 부탁드립니다.

감사합니다 👍

2021-11-16 13:47 UTC, sah3122 requested changes
안녕하세요. 2단계 미션 리뷰를 맡게된 이동철 입니다. 
미션 구현 너무 잘해주셨네요 👍 
이대로 넘어가기 아쉬워 추가 미션을 남겨두었는데 확인 부탁 드립니다 😄

2021-11-16 13:47 UTC, sah3122 commented on src/main/java/StringAddCalculator.java
> +    private static final Pattern CUSTOM_DELIMITER_PATTERN = Pattern.compile("//(.)\n(.*)");
패턴 객체 캐싱 좋습니다 👍

2021-11-16 13:47 UTC, sah3122 commented on src/main/java/StringAddCalculator.java
> +            return 0;
0라는 매직넘버를 사용하기 보단 기본값에 해당하는 상수를 정의하는것이 어떨까요 ? 
https://ljlm0402.netlify.app/javascript/clean-code.1/

2021-11-16 13:47 UTC, sah3122 commented on src/main/java/StringAddCalculator.java
> +        return input == null || input.isEmpty();
Objects.isNull() 을 사용한다면 가독성을 더 높일수 있어요 😄

2021-11-16 13:47 UTC, sah3122 commented on src/test/java/StringAddCalculatorTest.java
> +class StringAddCalculatorTest {
DisplayName과 ParameterizedTest를 활용한다면 테스트의 의도를 분명히 나타내고 다양한 값에 대해 테스트 할 수 있을것 같아요 😄

2021-11-16 13:47 UTC, sah3122 commented on src/test/java/StringAddCalculatorTest.java
> +}
파일의 마지막은 new line으로 끝나는것을 권장 드려요 😄 
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-11-16 13:47 UTC, sah3122 commented on src/test/java/StringAddCalculatorTest.java
> +        assertThatThrownBy(() -> StringAddCalculator.splitAndSum("-1,2,3"))
Exception을 테스트 할 때는 assertThatExceptionOfType() 을 활용해보는건 어떨까요 ? 
assertThatThrownBy 과 동작은 동일하지만 조금더 자연스러운 표현을 할 수 있게 됩니다. 
`This method is more or less the same of assertThatThrownBy(ThrowableAssert.ThrowingCallable) but in a more natural way.`

2021-11-16 13:47 UTC, sah3122 commented on src/main/java/StringAddCalculator.java
> +public class StringAddCalculator {
요구사항을 분석하면 구현해야 하는 기능들이 나올거에요. 
클래스를 기능에 맞추는것이 아닌 기능(책임)을 담당할 수 있는 클래스를 만들어 보는것을 권장 드립니다. 

우선은 StringAddCalculator가 맡고있는 책임들이 너무 많은것 같으니 양수를 책임지는 클래스를 만들어 StringAddCalculator 맡고 있는 책임들을 분산 시키는것부터 시작해보세요 😄

2021-11-17 11:10 UTC, han0102 commented on src/main/java/StringAddCalculator.java
> +            return 0;
상수로 정의하는 이유는, 왜 0을 리턴하는 지 알려주기 위함일까요?

2021-11-17 13:34 UTC, han0102 commented on src/main/java/StringAddCalculator.java
> +public class StringAddCalculator {
`양수를 책임지는 클래스` 가 정확히 어떤 클래스를 말씀하시는 지 잘 모르겠어요.
혹시 좀 더 설명해주실 수 있나요?

2021-11-18 00:10 UTC, sah3122 commented on src/main/java/StringAddCalculator.java
> +            return 0;
0이라는 값은 요구사항에 정의는 되어 있지만 코드상 아무 의미를 내포하고 있지 않고 있어요. 
코드 상에서 이러한 의미를 알수 없는 값이 사용된다면 다른 개발자들이 의미를 알수 없을 뿐더러 가독성도 저하되게 됩니다. 😄

2021-11-18 00:12 UTC, sah3122 commented on src/main/java/StringAddCalculator.java
> +public class StringAddCalculator {
미션 요구사항에서 숫자는 음수가 될 수 없다고 정의되어 있으니 로직상에서 처리를 하는것 보단 PositiveNumber라는 객체를 만들어 음수가 될수 없는 객체를 만들어 보라는 코멘트 였습니다.
추가로 이러한 객체들을 불변 객체로 만들면 시스템의 견고함은 더욱 상승하게 되요 😄 
아래 문서를 참고해주세요 ! 
https://meetup.toast.com/posts/217

2021-11-18 00:19 UTC, sah3122 requested changes
질문에 대한 답변과 몇가지 추가 요구사항을 남겨드렸습니다. 
이해가 되지 않는 부분이 있다면 편하게 DM 부탁드려요 🙏

2021-11-18 00:19 UTC, sah3122 commented on src/main/java/constant/CalculatorConstant.java
> +public class CalculatorConstant {
개인적으로는 constant 클래스를 정의하는것을 지양하지 않아요. 
조금더 자세하게는 public 상수를 사용하는것을 지양하지는 않습니다. 
이러한 상수값들이 여러 클래스에서 사용하게 된다면 응집도가 떨어지며 불필요한 결합이 발생하게 되요. 
이번 과정을 진행하면서는 상수는 필요한 클래스에서 private 접근 제어자로 지정하는것이 어떨까요 ?
https://jessyt.tistory.com/147

2021-11-18 00:19 UTC, sah3122 commented on src/main/java/helper/CollectionHelper.java
> +public class CollectionHelper {
Helper, Util 클래스도 마찬가지로 응집도 저하, 결합도 증가를 불러오게 됩니다. 
이번 과정을 진행하면서는 이과 같은 클래스정의를 하지 않고 필요한 클래스에서 제공할 수 있도록 해보는건 어떨까요 ? 
아래 문서의 첫번째 내용이네요 😄 
https://jessyt.tistory.com/155

2021-11-18 00:19 UTC, sah3122 commented on src/main/java/helper/StringHelper.java
> +public class StringHelper {
다른 코멘트를 참고해주세요 😄

2021-11-18 00:19 UTC, sah3122 commented on src/test/java/helper/StringHelperTest.java
> +}
파일의 마지막은 new line 으로 끝나는것을 권장 드립니다 😄 
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-11-18 00:19 UTC, sah3122 commented on src/test/java/helper/StringHelperTest.java
> +class StringHelperTest {
테스트 코드를 깔끔하게 잘 작성해주셨네요 💯

2021-11-18 13:21 UTC, han0102 commented on src/main/java/helper/CollectionHelper.java
> +public class CollectionHelper {
제안 감사합니다.
Helper 클래스를 제거하고, PositiveNumber 객체를 생성하였습니다.

2021-11-18 13:21 UTC, han0102 commented on src/main/java/constant/CalculatorConstant.java
> +public class CalculatorConstant {
네 말씀해주신 방법대로 해볼게요!

2021-11-19 00:32 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
몇가지 코멘트를 남겨두었는데 다음 미션을 진행하며 반영해주세요 😄

2021-11-19 00:32 UTC, sah3122 commented on src/main/java/calculator/PositiveNumber.java
> +    }
주 생성자 부 생성자 개념을 알고 계실까요 ? 
양수를 파라미터로 받는 생성자를 주 생성자로 정의하고, 부 생성자에서는 String 문자열을 받고 주 생성자를 호출하는 구조로 구현해보세요. 😄 
생성자가 많아 질수록 객체를 풍부하게 사용할수 있답니다. 
https://jackjeong.tistory.com/148

2021-11-19 00:32 UTC, sah3122 commented on src/main/java/calculator/StringAddCalculator.java
> +            .sum();
PositiveNumber 클래스가 add와 같이 덧셈을 지원할수 있으면 현제 구조와는 어떤 장점이 생길지 고민해보세요 😄

2021-11-19 00:32 UTC, sah3122 commented on src/main/java/calculator/PositiveNumber.java
> +public class PositiveNumber {
추가된 클래스에 대한 테스트 코드가 필요해보여요 😄

2021-11-19 00:32 UTC, sah3122 commented on src/main/java/calculator/StringAddCalculator.java
> +    }
private 메소드는 호출되는 메소드 아래에 선언하는것이 코드읽기가 편한것 같아요 😄

2021-11-19 00:32 UTC, sah3122 commented on src/main/java/calculator/StringAddCalculator.java
> +        return Collections.emptyList();
emptyList를 반환하기 보다는 splitByCommaOrColon 메소드를 호출하는것이 어떨까요 ?
메소드 네이밍이 변경된다면 충분히 합칠수 있을것 같으며 emptyList에대한 분기문을 제거할수 있을것 같아요 😄

2021-11-19 00:32 UTC, sah3122 commented on src/main/java/calculator/StringAddCalculator.java
> +        return Arrays.asList(input.split(",|:"));
매직넘버는 의미를 가지는 상수로 정의하여 가독성을 높여보세요.

2021-11-19 00:32 UTC, merged