Step2 - 로또(자동)
next-step/java-lotto pull request #2127
Opened 2021-11-25 13:37 UTC by LeeJeongGi

요번 리뷰도 잘 부탁드립니다~

2021-11-26 00:02 UTC, catsbi requested changes
안녕하세요 정기님, 2단계 로또(자동)미션 잘 구현해주셨네요. 
정기님의 코드 스타일을 볼 수 있었습니다. 👍 
몇 가지 피드백이 필요한 부분들에 대해서 코멘트를 남겼으니 확인 후 다시 리뷰요청 해주세요!

2021-11-26 00:02 UTC, catsbi commented on src/main/java/lotto/domain/LottoWinning.java
> +    private final static int LOTTO_SIZE = 6;
```suggestion
    private static final int LOTTO_SIZE = 6;
```

2021-11-26 00:02 UTC, catsbi commented on src/main/java/lotto/view/InsertView.java
> +public class InsertView {
클래스를 보니 모두 정적 메서드로 유틸리티 클래스로 보여요.
그런데 해당 클래스를 생성자를 요청해서 사용하는사람은 어떻게 될까요? 막아야 하지 않을까요 ㅎㅎ

2021-11-26 00:02 UTC, catsbi commented on src/main/java/lotto/view/ResultView.java
> +public class ResultView {
여기도 마찮가지로 생성자에 대한 방어가 안되어있네요!

2021-11-26 08:41 UTC, LeeJeongGi commented on src/main/java/lotto/domain/Lotto.java
> +            checkDuplicationNumber(autoNumbers, randomNumber);
다른 자료구조라는 말씀이 무슨 말인지 이해가 잘 안됩니다! ㅜㅜ

2021-11-27 01:45 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
> +            checkDuplicationNumber(autoNumbers, randomNumber);
@LeeJeongGi 
`ArrayList`는 중복을 허용하고 순서가 있는 자료구조이죠. 그렇다보니 중복값 검사를 매번 직접 구현해서 호출해줘야 하죠.
반면 다른 자료구조(ex: set, tree, linkedlist, graph...)등은 각각 다른 특징을 가지고있죠 중복을 허용하거나 하지않건, 순서를 보장하거나 보장하지 않거나등등.. ㅎㅎ 적절한 자료구조를 선택한다면 따로 비즈니스 로직을 또 구현해서 코드를 늘리지 않아도 되지 않을까요

2021-11-30 03:42 UTC, catsbi approved these changes
안녕하세요 정기님 2단계 피드백 빠르게 적용해주셨네요. 
무엇보다, 커밋을 상세하게 작성해주셔서 코드를 확인하는데 아주 편했습니다. 👍 
몇가지 피드백을 남겨드렸으니 확인하시고 다음 단계에서 적용 해주시면 좋을 것 같습니다 😄 
그럼 이만 Merge하겠습니다. 다음 미션도 화이팅입니다 👏👏

2021-11-30 03:42 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
> +    private static Random random = new Random();
`final` 을 붙혀서 불변성을 확보해도 될 것 같아요

2021-11-30 03:42 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
> +    private Set<LottoNumber> numbers;
로또번호도 `final`을 붙혀줘도 될 것 같네요

2021-11-30 03:42 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
> +                .collect(Collectors.toSet()));
```suggestion
        return new Lotto(new TreeSet<>(number));
```
이렇게만해도 될 것 같습니다 ㅎ

2021-11-30 03:42 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
>          }
```suggestion
        for (Integer integer : number) {
            numbers.add(new LottoNumber(integer));
        }
```
향상된 for문을 사용하면 내부적으로 iterator를 사용해서 바로 내부 값을 순회할 수 있습니다. 코드를 더 단축시킬 수 있죠. 

그리고 여기서 Stream API를 쓸 수도 있겠죠. ㅎ(이건 취향입니다. )

2021-11-30 03:42 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
> +        }
반복문안에 if문이 들어가면서 indent가 2를 넘어버렸네요. 
어떻게 낮출 수 있을까요?

2021-11-30 03:42 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
> +        return false;
```suggestion
        return lottoNumber.equals(winningNumber);
```
이렇게만 해도 될 것 같아요

2021-11-30 03:42 UTC, catsbi commented on src/main/java/lotto/domain/LottoTicket.java
> +        Map<Rank, Integer> repository = new HashMap<>();
Enum을 key로 사용한다면 EnumMap을 사용해보는건 어떨까요? 
여러모로 HashMap보다 성능적인 부분에서 이점을 가지고 있는 자료구조인데 해보시겠어요?

2021-11-30 03:42 UTC, catsbi commented on src/main/java/lotto/domain/Rank.java
> +//    SECOND(5, 30_000_000),
사용하지 않는 코드는 삭제해주세요 ㅎ

2021-11-30 03:42 UTC, merged