[4단계] 로또(수동)
next-step/java-lotto pull request #2142
Opened 2021-11-27 09:05 UTC by jjoylee

안녕하세요 4단계 리뷰 요청드립니다!
최대한 Input을 객체 밖에서 받고 싶은데 이게 로직때문인지 객체 않에서 Input을 받지 않기가 힘든 것 같습니다. 혹시 좋은 의견 있으면 알려주시면 감사하겠습니다.
리뷰 감사합니다!!!!

2021-11-28 00:05 UTC, dbeod2 requested changes
안녕하세요 정희님! :-)  

로또 (수동)미션 잘 진행해주셨어요 테스트도 꼼꼼하게 해주셨네요.
몇가지 코멘트 드린 부분있는데 확인 부탁드리고! 
리뷰 재요청 주세요 🙏

2021-11-28 00:05 UTC, dbeod2 commented on src/main/java/lotto/controller/LotteryGameApp.java
>      public static void main(String[] args) {
구매 금액이 1000원 이하 일 때, 예외처리 잘해주셨습니다. 
다만 한가지 의견을 드리자면, 게임 종료 되는 시점이 구매 금액 입력시 바로 종료가 되는게 아니라 수동 로또 구매 input 메시지가 나온 후 입력 후에 노출되고 있습니다. 구매 금액이 1000원 이하로 입력 된 경우 바로 게임이 종료되면 어느 시점에서 종료가 되는지 더 확실하게 알 수 있을 것 같네요 🙏
<img width="436" alt="스크린샷 2021-11-28 오전 8 58 49" src="https://user-images.githubusercontent.com/70149382/143723841-cc719398-b022-41fa-96f0-c9724e6b0d18.png">

2021-11-28 00:05 UTC, dbeod2 commented on src/main/java/lotto/model/domain/PurchaseInfo.java
> +    private void checkCountValidation(int count) {
예외처리 잘해주셨어용! 👍🏻

2021-11-28 00:05 UTC, dbeod2 commented on src/test/java/lotto/model/domain/PurchaseInfoTest.java
> +    @ParameterizedTest
꼼꼼한 테스트👏🏻

2021-11-28 11:59 UTC, jjoylee commented on src/main/java/lotto/model/ticket/generator/ManualTicketGenerator.java
> +public class ManualTicketGenerator implements LotteryTicketGenerator {
@dbeod2 제가 피드백을 이해를 잘 못했는데 어떤 의미신지 자세히 설명 부탁드려도 될까요?

2021-11-28 12:00 UTC, jjoylee commented on src/main/java/lotto/controller/LotteryGameApp.java
> +            if(purchaseInfo.haveManualLottery()) InputView.inputManualLottery();
@dbeod2 아 제 전의 습관때문에 ㅠㅠ 주의하고 있는데 더 조심하겠습니다!!

2021-11-28 17:04 UTC, jjoylee commented on src/main/java/lotto/view/InputView.java
> +        return new LotteryTicket(numbers.stream()
이부분은 지금 보니 수동생성때 중복되는 로직도 있어서 그대로 사용하는게 더 좋을 것으로 생각됩니다.

2021-11-29 04:16 UTC, dbeod2 commented on src/main/java/lotto/model/ticket/generator/ManualTicketGenerator.java
> +public class ManualTicketGenerator implements LotteryTicketGenerator {
제가 생각하는 제네레이터의 역활은 반복적인 작업을 제어하기 위함이고, 랜덤한 값을 가지고 올때 자주 사용했는데요.
수동으로 숫자를 받아오는 경우는 딱 한번이라고 생각해서 질문드렸습니다 :-)

2021-11-29 06:07 UTC, dbeod2 requested changes
안녕하세요! 

로또 (수동) 미션 피드백 잘 반영해주셨습니다. 
추가로 의견드린 부분이 있습니다 :-) 
확인 부탁드리며, 리뷰 재요청 주세요🙏

2021-11-29 06:07 UTC, dbeod2 commented on src/main/java/lotto/model/domain/CountInfo.java
> +public class CountInfo {
피드백 반영 👏🏻

2021-11-29 06:07 UTC, dbeod2 commented on src/main/java/lotto/model/ticket/generator/LotteryTicketGenerator.java
> +    }
중복 로직이네요 :-) 어떻게하면 중복되지 않게 할 수 있을지 고민해보셔도 좋을 것 같습니다

2021-11-30 00:58 UTC, dbeod2 approved these changes
안녕하세요! 정희님 ☺️

벌써 로또미션 마지막이네요 🙏
피드백 반영 마지막까지 잘해주셨어요! 👏🏻👏🏻👏🏻

남은 미션도 더 잘해내실거라 믿고 여기서 바로 머지하겠습니다 🙇🏻‍♀️

다음 미션을 진행해주세요

2021-11-30 00:58 UTC, merged