Step2 로또(자동)
next-step/java-lotto pull request #2144
Opened 2021-11-27 12:16 UTC by hungrytech

로또(자동) 구현완료되어 PR요청드립니다.

리뷰부탁드리겠습니다!

2021-11-28 08:17 UTC, heesunjeong requested changes
2단계 미션 깔끔하게 잘 구현해주셨네요 👍 
테스트 코드 중에 실패하는 테스트가 있어서 관련한 부분과 몇가지 고려해보시면 좋을 것 같은 부분에 코멘트를 추가했는데요, 확인 해보시면 좋을 것 같습니다 :)
확인해보시고 다시 리뷰 요청 부탁드리겠습니다~!

2021-11-28 08:17 UTC, heesunjeong commented on src/main/java/lotto/domain/WinningNumbers.java
> +        validateSize(numbers);
WinningNumbers에 중복된 숫자가 입력될 수 없도록 테스트 코드와 함께 예외처리 추가해보시면 어떨까요? :)

2021-11-28 08:17 UTC, heesunjeong commented on src/main/java/lotto/domain/WinningNumbers.java
> +    private final List<Integer> winningNumbers;
지금은 winningNumbers로 음수 값이나 45이상의 값 가질 수 있네요! 원시값을 포장해서 이에 대해 예외처리를 해보시면 어떨까요?! :)

2021-11-28 08:17 UTC, heesunjeong commented on src/test/java/lotto/domain/PriceTest.java
> +class PriceTest {
정상적으로 Price가 잘 생성되는 것에 대한 테스트도 추가해보시면 좋을 것 같아요 :)

2021-11-28 09:33 UTC, hungrytech commented on src/main/java/lotto/utils/LottoNumberGenerator.java
> +        return new ArrayList<>(numbers.subList(FROM_INDEX, TO_INDEX));
힌트를 활용한다는 말씀이 이해가 안가서 코멘트 남겨요! 😹

2021-11-28 09:34 UTC, hungrytech commented on src/main/java/lotto/utils/LottoNumberGenerator.java
> +        return new ArrayList<>(numbers.subList(FROM_INDEX, TO_INDEX));
>힌트를 활용한다는 말씀이 이해가 안가서 코멘트 남겨요! 😹 어떤 힌트를 말씀하시는걸까요..?

2021-11-28 09:43 UTC, hungrytech commented on src/main/java/lotto/utils/LottoNumberGenerator.java
> +                .collect(Collectors.toList());
static 변수로 캐싱하도록 하겠습니다~😄

2021-11-28 09:45 UTC, hungrytech commented on src/main/java/lotto/domain/LottoTickets.java
> +        return rankMap;
LottoTickets이 당첨번호를 받고 자신이 가지고 있는 티켓들에 대한 책임을 가지고 있어 결과를 내어 반환하는것이 맞다고 생각되어 해당 로직을 작성했는데요.  LottoTickets가 결과를 반환하는건 어떻게 생각하시나요?

2021-11-28 09:45 UTC, hungrytech commented on src/test/java/lotto/controller/LottoControllerTest.java
> +    void createLottoResult() {
수익율이 잘못된것 같네요 수정할께요~😅

2021-11-28 09:51 UTC, hungrytech commented on src/main/java/lotto/utils/InputUtils.java
> +        validatePrice(input);
InputUtil가 담당하는 책임이 만들면서도 상당히 고민이 많았습니다.  현재 Price와 WinningNumbers를 생성과 validate책임을 둘다 담당하는 부분중 단위 validate를 Price만이 고유하게 담당할 수 있는 validate의 책임을 부여했습니다. 특히 "공백과, 숫자가 아닌 문자열이 들어올 경우 이것을 Price가 검증을 해야할까?"에 대한 고민이 많았어요. Price를 생성할때 공백, 문자열 체크까지 책임을 가지는것에 대해 어떻게 생각하시나요?

2021-11-28 09:54 UTC, hungrytech commented on src/main/java/lotto/domain/WinningNumbers.java
> +    private final List<Integer> winningNumbers;
지적해주신 부분을 놓친것 같네요! 추가 해놓을게요~😄

2021-11-28 09:59 UTC, hungrytech commented on src/test/java/lotto/domain/PriceTest.java
> +class PriceTest {
테스트 코드를 작성하면서 객체생성 부분에서 고민이 많아요..😹  
제대로 생성되는지에 대한 테스트가 과연 필요할까?에 대한 의문때문이에요. 객체생성 테스트로서 얻을 수 있는 장점이 무엇이 있을까요?

2021-11-28 10:46 UTC, heesunjeong commented on src/main/java/lotto/domain/LottoTickets.java
> +        return rankMap;
LottoTickets이 자신이 가지고 있는 티켓들에 대해서 결과를 반환하는 역할을 가지는 것은 좋은 것 같아요 👍 
다만, createInitialMap() 메소드는 단순히 Rank enum 값들을 key로 가지고 value가 모두 0인 map 객체를 생성하기 때문에 LottoTickets의 역할과 조금 멀어보이는 것 같아요...!

2021-11-28 11:08 UTC, heesunjeong commented on src/main/java/lotto/utils/InputUtils.java
> +        validatePrice(input);
많은 고민을 통해서 이와 같은 구조로 설계를 해보셨군요! 👍 👍 

저도 고민해보고 말씀드리자면, 정적 팩토리 메소드나 생성자를 통해 string을 인자로 받아 Price객체를 생성할 수 있다면 해당 인자의 유효성 체크 역할도 가지는게 맞다고 생각합니다 :) 
저는 이런 경우에 주로 멤버변수와 다른 인자에 대한 유효성 체크는 해당 자료형을 인자로 가지는 정적 팩토리 메소드에서 한 후에 생성자는 하나만 선언 후에 그 생성자에서 그 객체 고유의 유효성을 체크하는 식으로 주로 설계해보았던 것 같아요! 
```
    private Price(int price) {
        validateUnit(price);
        this.price = price;
    }

    public static Price of(String price) {
        validateBlank(price);
        int value = Integer.parseInt(price);
        return new Price(value);
    }
```
혹시 또 다른 의견 있으시다면 편하게 말씀 주세요 :)

2021-11-28 11:09 UTC, heesunjeong commented on src/main/java/lotto/utils/LottoNumberGenerator.java
> +        return new ArrayList<>(numbers.subList(FROM_INDEX, TO_INDEX));
강의 자료에 나와있는 힌트를 말씀드렸어요 :) 아래의 힌트를 적어주셨네요! 
- 로또 자동 생성은 Collections.shuffle() 메소드 활용한다.
- Collections.sort() 메소드를 활용해 정렬 가능하다.
- ArrayList의 contains() 메소드를 활용하면 어떤 값이 존재하는지 유무를 판단할 수 있다.

2021-11-28 11:35 UTC, heesunjeong commented on src/test/java/lotto/domain/PriceTest.java
> +class PriceTest {
우선 의문을 가지신 것처럼 꼭 작성이 필요한 부분은 아닙니다!!ㅎㅎ 그렇지만 이번 실습을 통해서 작성해주신 모든 프로덕션 코드에 대해서 많은 테스트코드를 작성하는 경험을 해보시면 좋을 것 같아서 말씀드렸어요~!

지금은 Price객체가 1000원 단위로 잘 생성되었는지 객체 생성 테스트 작성으로 검증해본다면 그것도 의미가 있을 것 같아요! 

추가로 객체생성에 대한 테스트가 작성되는 타이밍이 있는데요! 테스트코드 작성 후 프로덕션 코드를 작성하는 TDD를 하실때 가장 먼저 쉽게 작성할 수 있는 테스트 코드가 객체 생성에 대한 테스트 코드이기도 하답니다~! 새로운 객체가 추가될 때 `새로운 객체 생성 테스트 코드작성 > 객체 생성하여 테스트코드 성공 > 추가할 메소드에 대한 테스트코드 작성 > 메소드 프로덕션 코드 작성하여 테스트코드 성공` 이런 사이클을 지켜서 해보셔도 재미있으실 것 같아요 :)

2021-11-29 14:46 UTC, hungrytech commented
피드백 반영하여 다시 리뷰요청드립니다.
리뷰중 "LottoTicket List 에 대한 역할을 일급컬렉션으로 도출해주신 LottoTickets가 가질 수 있도록 고려해보시면 어떨까요? :)"

2021-11-29 14:51 UTC, hungrytech commented
피드백 반영하여 다시 리뷰요청드립니다.

2021-11-30 11:36 UTC, heesunjeong approved these changes
피드백 잘 반영해주셨네요 👍 👍 
몇가지 추가로 참고해보시면 좋을 부분에 코멘트 추가했는데요, 다음 단계 진행하시면서 참고해보세요 :)
이어서 다음 단계 진행해주시면 됩니다~! 🔥

2021-11-30 11:36 UTC, heesunjeong commented on src/main/java/lotto/utils/LottoNumberGenerator.java
> +    private static final List<Integer> LOTTO_NUMBERS;
숫자를 만들어 캐싱하고 사용할 수 있게 되었네요 👍

2021-11-30 11:36 UTC, heesunjeong commented on src/main/java/lotto/utils/LottoNumberGenerator.java
> +    private static final int LOTTO_MAX_NUMBER = 46;
로또 번호가 46까지 생성되네요?! 👀
<img width="229" alt="스크린샷 2021-11-30 오후 8 15 53" src="https://user-images.githubusercontent.com/13251407/144037869-d85ba051-2526-4ce3-a790-a70dd4f35a26.png">

2021-11-30 11:36 UTC, heesunjeong commented on src/main/java/lotto/domain/LottoResult.java
> +                .reduce(0, Integer::sum);
지금은 Rank의 전체 PrizeMoney를 합쳐서 항상 값이 2001555000이 나오고 있네요~

2021-11-30 11:36 UTC, merged

2021-11-30 13:02 UTC, hungrytech commented on src/main/java/lotto/utils/LottoNumberGenerator.java
> +    private static final int LOTTO_MAX_NUMBER = 46;
👀  45로 수정하겠습니다..

2021-11-30 13:02 UTC, hungrytech commented on src/main/java/lotto/domain/LottoResult.java
> +        return result;
toMap에 대해서 학습하고 이해할 수 있었습니다 감사합니다~ :)

2021-11-30 13:03 UTC, hungrytech commented on src/main/java/lotto/domain/LottoResult.java
> +                .reduce(0, Integer::sum);
👀   전부 계산을 하고있었네요.. 다음스탭에서 바로 수정하겠습니다.