🚀 3단계 - 로또(2등)
next-step/java-lotto pull request #2165
Opened 2021-11-29 13:24 UTC by sidthefaker

2021-11-30 13:03 UTC, hyunssooo requested changes
안녕하세요. 
이번 step도 빠르게 잘 진행해 주셨네요! 
몇 가지 코멘트 남겼습니다. 확인 부탁드릴게요!

2021-11-30 17:00 UTC, sidthefaker commented on src/main/java/edu/nextstep/camp/lotto/domain/LottoNumber.java
> +    }
이렇게 원시타입을 래핑하는 클래스에는 습관적으로 만들어두게 되는 메소드였습니다.
말씀하신대로 getter라고 볼 수도 있지만,  이 클래스가 갖고 있는 필드는 명확하게 하나뿐이라, get~~ 보다는 이 클래스가 갖고 있는 필드를 다른 원시타입으로 변환한다는 의미로 toString과 비슷한 느낌으로 추가한 메소드입니다.

별개로 사용되지 않는 것이라 메소드는 삭제했습니다.

2021-11-30 17:34 UTC, sidthefaker commented on src/main/java/edu/nextstep/camp/lotto/domain/Lottos.java
>      }
지난 로또(자동)에서부터 고민하던 메소드였습니다.
그때는 List<Lotto>형태로 리턴하고 있었는데, 메소드를 사용하는 쪽에서 좀더 쉽게 사용할 수는 없을까 하는 생각으로 리팩토링을 해본것입니다.
결과적으로는 래핑을 풀어서 원시타입형태로 사용하기 좋고, 그 로직이 Lotto와 Lottos에 분산되서 가독성은 좋아지긴 했지만,
반대로 메소드의 의도는 모호해지 않았나 싶네요.

2021-12-01 01:28 UTC, hyunssooo commented on src/main/java/edu/nextstep/camp/lotto/domain/LottoNumber.java
> +    }
`클래스가 갖고 있는 필드를 다른 원시타입으로 변환한다는 의미` 로는 괜찮다고 생각합니다. 
제 기억으로는 `toInt()` 는 테스트에만 사용하고 있었던 것 같아요 :) 하지만 개인적으로 toString과는 조금 다른 느낌인 것 같습니다. toString 같은 경우는 디버깅용으로 보통 사용합니다.

2021-12-01 12:20 UTC, sidthefaker commented on src/main/java/edu/nextstep/camp/lotto/domain/Lottos.java
>      }
GameResult를 없애고 Ranks만으로 구현했다가 의미는 GameResult가 더 잘통하는 것 같아 기존 Ranks를 GameResult로 이름을 바꿨습니다.
당첨번호 클래스로 좀더 winningResult 메소드가 좀더 간단히 된 것 같네요

2021-12-01 15:14 UTC, hyunssooo approved these changes
안녕하세요 :) 
이번 미션 잘 진행해 주셨습니다. 
다음 step 진행 부탁드립니다!

2021-12-01 15:14 UTC, hyunssooo commented on src/main/java/edu/nextstep/camp/lotto/domain/Lotto.java
> +    }
winningNumber.numbers() 와 winningNumber.bonus() 같은 경우는 사실상 getter 로 보이네요. 
Lotto에 winningNumber를 받는것을 반대로 해보면 어떨까요? 
winningNumber에 lotto를 받으면 getter를 사용하지 않을 수 있습니다 :)

2021-12-01 15:14 UTC, hyunssooo commented on src/main/java/edu/nextstep/camp/lotto/domain/GameResult.java
> +        }
```java
Map<Rank, Long> collect = ranks.stream()
    .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
```

으로도 가능하겠네요 :)

2021-12-01 15:14 UTC, hyunssooo commented on src/main/java/edu/nextstep/camp/lotto/LottoGame.java
> +        OutputView.printGameResult(gameResult.collect(), gameResult.totalPrize().toLong(), gameResult.priceEarningRate());
OutputView로 데이터를 가공해서 보내주고 있는데요. 개인적으로는 굳이? 라는 생각이 조금 들어요 :) 
우선 lottos 같은 경우는 불변이지 않나요? view로 나가도 사이드 이펙트는 없을 것 같아요 :) 
개인적으로는 Lottos 객체를 그냥 view로 던질 것 같습니다. 
이 부분은 참고만 해주세요.

2021-12-01 15:14 UTC, merged