Step2 - 로또(자동)
next-step/java-lotto pull request #2192
Opened 2021-12-04 01:01 UTC by guswnt

선동님 안녕하세요
2단계 로또 진행했습니다
리뷰 부탁드립니다🙇‍♀️

2021-12-04 02:56 UTC, seondongpyo requested changes
2단계 미션 구현하시느라 고생하셨습니다.
고민해보실만한 부분들에 대해 코멘트 드렸으니 확인 부탁드리겠습니다.
코멘트가 다소 많은데, 반영하시면서 의견 있으시면 언제든지 DM 주세요.
그럼 다시 리뷰 요청 부탁드릴게요! 🔥

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/LottoNumbers.java
> +public class LottoNumbers {
`LottoNumbers`는 6개의 번호를 상태로 가지면서 당첨 번호와 비교하는 기능도 수행하고 있습니다.
마치 `로또` 한 장의 역할을 하는 것처럼 보여 `Lotto`라는 이름이 더 어울려보이는데 어떻게 생각하시나요?

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/LottoNumbers.java
> +        List<Integer> copyOfNumbers = new ArrayList<>(numbers);
여기서 `방어적 복사`를 한 번 수행하신 이유가 궁금한데 설명해주실 수 있을까요?

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/LottoWinningRules.java
> +        lottoPrize.put(6, 2000000000);
언더스코어(`_`)를 활용하면 숫자의 가독성이 더 좋아질 것 같습니다.
https://countryxide.tistory.com/52

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/LottoWinningRules.java
> +        return winLotto(numberOfMatching) ? lottoPrize.get(numberOfMatching) : LOSE_PRIZE;
여기도 `if-else`의 축약형인 `삼항 연산자`가 보이는데, 다른 방법으로 작성해보시면 좋을 것 같아요.

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/LottoWinningRules.java
> +    private final Map<Integer, Integer> lottoPrize = new HashMap<>();
여기도 `상수`와 `인스턴스 변수`의 구분을 위해 공백 라인을 추가해주시면 좋을 것 같습니다.

```suggestion
    private static final int LOSE_PRIZE = 0;
    
    private final Map<Integer, Integer> lottoPrize = new HashMap<>();
```

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/dto/WinningInformationDto.java
> +public class WinningInformationDto {
다음 질문에 대해 설명해주실 수 있나요?
1. `인스턴스 변수`들의 접근 제어자를 `public`으로 설정하신 이유
2. `getter`와 `setter`를 추가하지 않으신 이유

2021-12-04 02:56 UTC, seondongpyo commented on src/test/java/step2/domain/LottoTest.java
> +        assertThat(earningRate).isEqualTo(5);
예상 수익률 결과를 잘못 전달하신 것 같아요. 확인 부탁드리겠습니다.

2021-12-04 02:56 UTC, seondongpyo commented on src/test/java/step2/domain/LottoTest.java
> +        Constructor<LottoNumbers> declaredConstructor = LottoNumbers.class.getDeclaredConstructor(List.class);
`LottoNumbers`의 생성자가 `private`이라서 리플렉션까지 활용해야 하는 상황인데요.
테스트를 더 쉽게 수행할 수 있는 구조를 고민해보시면 어떨까요?

2021-12-04 02:56 UTC, seondongpyo commented on src/test/java/step2/domain/LottoWinningNumbersTest.java
> +    @DisplayName("로또 당첨 번호가 6개가 아니면 LottoException이 발생한다.")
또 다른 경계값인, 로또 당첨 번호가 5개인 경우도 추가로 테스트해보시면 좋을 것 같아요.

2021-12-04 02:56 UTC, seondongpyo commented on src/test/java/step2/domain/LottoTest.java
> +    @DisplayName("로또 당첨 번호를 전달하면 일치하는 개수가 몇 개 있는지 알 수 있다.")
`@ParameterizedTest`, `@MethodSource` 등을 활용하여 다른 경우들도 테스트해보시면 좋을 것 같아요.

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/Lotto.java
> +    }
`기능 요구사항`을 보면 총 수익률은 소수점 둘째 자리까지 출력해야 하는데, `int`로 반환하면 어떻게 될까요?

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/Lotto.java
> +    public int earningRate(Map<Integer, Integer> countNumberOfMatching) {
해당 메서드에 대한 테스트 코드가 없는데 추가해보면 어떨까요?

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/LottoFactory.java
> +        int money = Integer.parseInt(moneyString);
전달 받은 `moneyString`이 숫자가 아니라면 어떤 문제가 발생할 수 있을까요?

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/LottoWinningRules.java
> +    public boolean winLotto(int numberOfMatches) {
`boolean` 타입을 반환한다면 메서드의 이름을 `isWinLotto()` 정도로 지어보는 건 어떨까요?

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/LottoNumbers.java
> +    private final List<Integer> lottoNumbers;
6개의 로또 번호를 `List<Integer>`를 통해 상태로 가지고 있는데요.
원시 값 `Integer`를 `하나의 로또 번호`라는 의미에서 `LottoNumber`라는 클래스로 포장해보면 어떨까요?

2021-12-04 02:56 UTC, seondongpyo commented on src/main/java/step2/domain/Lotto.java
> +    Lotto(LottoWinningRules lottoWinningRules, List<LottoNumbers> lottoNumbersList, int price) {
해당 생성자의 접근 제어자를 `default`로 설정하신 이유가 따로 있으신가요?

2021-12-07 17:35 UTC, guswnt commented on src/main/java/step2/domain/Lotto.java
> +    Lotto(LottoWinningRules lottoWinningRules, List<LottoNumbers> lottoNumbersList, int price) {
Lotto는 LottoFactory에서만 생성되기 때문에 다른 패키지에서 생성될 일이 없어서 default로 설정했습니다!

2021-12-07 18:14 UTC, guswnt commented on src/main/java/step2/domain/LottoNumbers.java
> +        List<Integer> copyOfNumbers = new ArrayList<>(numbers);
NUMBERS가 1-45까지 로또 번호를 나타내는 리스트이고 static으로 공유되다 보니 변경을 막으려고 방어적 복사를 사용했습니다!

2021-12-07 18:30 UTC, guswnt commented on src/main/java/step2/domain/LottoNumbers.java
> +public class LottoNumbers {
로또 구매할 때 한 장에 여러개의 로또 번호가 있어 이렇게 클래스 이름을 지었는데, 요구사항과 선동님 리뷰를 보니 Lotto를 6개 번호를 가지는 하나의 객체로 보는게 맞을것 같습니다!

2021-12-07 18:30 UTC, guswnt commented on src/main/java/step2/domain/Lotto.java
> +    private final List<LottoNumbers> lottoNumbersList;
로또 구매할 때 한 장에 여러개의 로또 번호가 있어 이렇게 클래스 이름을 지었는데, 요구사항과 선동님 리뷰를 보니 Lotto를 6개 번호를 가지는 하나의 객체로 보는게 맞을것 같습니다!

2021-12-07 19:53 UTC, guswnt commented on src/main/java/step2/dto/WinningInformationDto.java
> +public class WinningInformationDto {
1.  이건 제가 Public으로 설정해놓은줄 몰랐는데 private으로 다시 바꾸겠습니다😭
2. getter는 추가가 필요할것 같고, setter는 WinningInformationDto 불변객체로 만들기 위해서 추가하지 않았습니다.

2021-12-15 01:49 UTC, seondongpyo approved these changes
피드백 반영하시느라 고생하셨습니다 👍
추가로 고민해보실만한 부분들에 대해 코멘트 드렸으니
다음 단계 진행하시면서 확인해주시면 좋을 것 같습니다.
궁금하신 점이나 의견 있으시면 편하게 DM 주세요.
그럼 다음 단계 진행 부탁드리겠습니다 🔥

2021-12-15 01:49 UTC, seondongpyo commented on src/main/java/step2/Runner.java
> +        lottoController.winningInformationOf(lottos);
해당 로직들은 `main method`가 아닌 `LottoController` 내부에서 처리해보면 좋을 것 같습니다.

2021-12-15 01:49 UTC, seondongpyo commented on src/main/java/step2/domain/Lotto.java
> +    private static final int NUMBER_OF_LOTTONUMBERS = 6;
띄어쓰기를 추가하면 조금이나마 가독성이 괜찮아질 것 같습니다.
```suggestion
    private static final int NUMBER_OF_LOTTO_NUMBERS = 6;
```

2021-12-15 01:49 UTC, seondongpyo commented on src/main/java/step2/domain/LottoNumber.java
> +    public static final int MAX_LOTTONUMBER = 45;
- 해당 상수들은 `LottoNumber` 내부에서만 사용하니 접근 제어자를 `private`으로 선언해보면 어떨까요?
아니면 `LottoFactory`에서 해당 상수들을 활용해볼 수도 있을 것 같아요.
- 여기도 띄어쓰기를 추가하면 조금이나마 가독성이 좋아질 것 같습니다.
```suggestion
    public static final int MIN_LOTTO_NUMBER = 1;
    public static final int MAX_LOTTO_NUMBER = 45;
```

2021-12-15 01:49 UTC, seondongpyo commented on src/main/java/step2/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
- `LottoNumber`에 대한 테스트 코드도 추가해보시면 좋을 것 같습니다.
- `LottoNumber`에서 `Comparable` 인터페이스를 구현하신 이유가 궁금합니다.

2021-12-15 01:49 UTC, seondongpyo commented on src/main/java/step2/domain/LottoWinningRules.java
> +public class LottoWinningRules {
이 부분은 다음 단계에서 `enum`으로 구현해보시면 좋을 것 같습니다.

2021-12-15 01:49 UTC, seondongpyo commented on src/main/java/step2/domain/LottoNumber.java
> +    private final int number;
상수와 인스턴스 변수의 구분을 위해서 공백 라인을 추가해보시면 좋을 것 같습니다.
```suggestion
    public static final int MAX_LOTTONUMBER = 45;
    
    private final int number;
```

2021-12-15 01:49 UTC, seondongpyo commented on src/main/java/step2/domain/Lotto.java
> +        return numberOfMatching;
이 부분은 자바의 `stream`을 활용해보시면 좋을 것 같습니다.

2021-12-15 01:49 UTC, seondongpyo commented on src/main/java/step2/domain/Lottos.java
> +    private final List<Lotto> lottoList;
개인적으로 변수 이름에 특정 자료형을 명시하는 건 좋지 않다고 생각하는데요.
지금은 자료형이 `List<Lotto>`이지만, 만약 요구사항이 변경되어 다른 자료형을 사용해야 한다면
변수 이름인 `lottoList`도 같이 변경해야하는 불필요함이 발생할 것 같은데 어떻게 생각하시나요?

2021-12-15 01:49 UTC, seondongpyo commented on src/test/java/step2/domain/LottoTest.java
> +        assertThat(lottoNumber).isGreaterThan(0);
특정 범위를 테스트한다면 `isBetween()`을 활용해보시는 방법도 있다는 점 참고차 말씀드려 봅니다.
```suggestion
        assertThat(lottoNumber).isBetween(1, 45);
```

2021-12-15 01:49 UTC, merged