Feat: 로또 게임 1단계 구현
next-step/java-lotto pull request #2243
Opened 2022-01-01 04:13 UTC by yunhalee05

로또 게임 1단계를 구현하였습니다!

✔️ 로또 구입 금액을 입력하면 구입 금액에 해당하는 갯수의 로또를 생성
✔️ 로또 번호 자동 생성하는 randomNumberStrategy에서 1~45까지 랜덤 숫자 6가지를 Collections.shuffle()을 이용해 생성
✔️ 입력된 로또 당첨 번호와 일치하는 갯수를 matchCount()메소드를 이용해서 반환하도록 설정
✔️ 3~6가지의 번호 일치할 경우 열거형 MatchType에서 알맞은 타입 정보를 찾아 LottoResult에 각각의 일치 개수와 일치하는 로또의 개수를 map형태로 보관
✔️ LottoGame의 draw(List<Integer> winningNumbers)메소드에서 수익률, 매치 정보를 반환하는 LottoResult를 반환하도록 구현

2022-01-03 01:23 UTC, brainbackdoor requested changes
깔끔하게 잘 작성해주셨네요! 👍🏻 
몇가지 피드백 드렸는데요. 반영해보시고 다시 리뷰 요청 부탁해요~
좋은 하루 보내세요!

2022-01-03 01:23 UTC, brainbackdoor commented on src/test/java/lotto/domain/LottoGameTest.java
> +    }
```suggestion
    @ParameterizedTest
    @MethodSource("lottoGame")
    @DisplayName("추첨 번호를 이용하여 올바를 로또 결과를 반환한다.")
    void match_counts_with_winning_numbers(LottoGame lottoGame, Set<Integer> winningNumbers, int actual) {
        //when
        LottoResult lottoResult = lottoGame.draw(winningNumbers);

        //then
        assertEquals(lottoResult.getMatchResult().get(MatchType.FOUR), actual);
        assertEquals(lottoResult.getMatchResult().get(MatchType.FIVE), actual);
    }

    private static Stream<Arguments> lottoGame() {
        return Stream.of(
            Arguments.of(new LottoGame(list(
                new Lotto(new FixNumberStrategy(list(1, 3, 4, 5, 7, 9))),
                new Lotto(new FixNumberStrategy(list(2, 3, 4, 5, 6, 8))))
            ), newHashSet(asList(1, 2, 3, 4, 5, 6)), 1)
        );
    }
```

ParameterizedTest를 적극적으로 활용해보는건 어떨까요

2022-01-03 01:23 UTC, brainbackdoor commented on src/test/java/lotto/domain/LottoResultTest.java
> +        }
테스트 코드에 로직이 있으면 가독성이 떨어집니다. 메서드로 추출해서 추상화해보시겠어요?

2022-01-03 01:23 UTC, brainbackdoor commented on src/test/java/lotto/domain/LottoTest.java
> +        List<Integer> invalidFixNumbers = new ArrayList<>(Arrays.asList(-1, 0, 46, 47, 48, 49));
어떤 값 때문에 예외가 발생했는지 알기 어렵지 않나요? 이 부분도 ParameterizedTest을 활용하여 테스트해보시겠어요?

2022-01-03 01:23 UTC, brainbackdoor commented on src/test/java/lotto/domain/LottoTest.java
> +        assertEquals(exception.getMessage(), INVALID_SIZE_EXCEPTION);
```suggestion
        assertThatThrownBy(() ->  new Lotto(numberStrategy))
            .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining(INVALID_SIZE_EXCEPTION);
```
assertJ를 활용해보는 건 어떨까요

2022-01-03 09:14 UTC, yunhalee05 commented on src/main/java/lotto/domain/LottoGame.java
> +        List<Lotto> lottoList = new ArrayList<>();
해당부분 확인하여 리스트 이름을 변경하였습니다!

2022-01-03 09:15 UTC, yunhalee05 commented on src/main/java/lotto/domain/LottoGame.java
> +    }
winningNumber를 Lotto를 상속받는 클래스로 도출하여 match 메소드를 가지고 기능할 수 있도록 하였습니다!

2022-01-03 09:15 UTC, yunhalee05 commented on src/main/java/lotto/domain/LottoResult.java
> +        }
해당 로직을 메서드로 추출하여 의도를 나타내도록 변경하였습니다!

2022-01-03 09:16 UTC, yunhalee05 commented on src/main/java/lotto/utils/RandomNumberStrategy.java
> +        return numbers.stream().limit(LOTTO_NUMBER_SIZE).sorted().collect(Collectors.toList());
해당부분 확인하여 개행을 변경하였습니다!

2022-01-03 09:16 UTC, yunhalee05 commented on src/main/java/lotto/view/InputView.java
> +    private static final int LOTTO_PRICE = 1000;
해당부분 확인하여 돈 단위를 구분하기 위해 언더바를 사용하도록 변경하였습니다!

2022-01-03 09:18 UTC, yunhalee05 commented on src/test/java/lotto/domain/LottoGameTest.java
> +    }
해당부분 ParameterizedTest를 이용하여 MethodSource로 뽑아내도록 적용하였습니다!

2022-01-03 09:18 UTC, yunhalee05 commented on src/test/java/lotto/domain/LottoResultTest.java
> +        }
해둥부분 total 메서드로 꺼내어 추상화 되도록 변경하였습니다!

2022-01-03 09:19 UTC, yunhalee05 commented on src/test/java/lotto/domain/LottoTest.java
> +        List<Integer> invalidFixNumbers = new ArrayList<>(Arrays.asList(-1, 0, 46, 47, 48, 49));
해당부분 중복되는 부분과 발생되는 요소들을 쉽게 확인하도록 ParameterizedTest를 적용하고 invalidLottoNumber MethodSource를 적용하도록 변경하였습니다!

2022-01-03 09:21 UTC, yunhalee05 commented on src/test/java/lotto/domain/LottoTest.java
> +        assertEquals(exception.getMessage(), INVALID_SIZE_EXCEPTION);
해당부분 확인하여 예외 발생으로 테스트 코드를 assertJ를 사용하도록 적용하였습니다!

2022-01-03 13:21 UTC, brainbackdoor approved these changes
이번 미션은 여기서 merge 할게요~ 💯 
다음 단계 진행해주세요~

2022-01-03 13:21 UTC, brainbackdoor commented on src/test/java/lotto/domain/LottoTest.java
> +    @DisplayName("범위 밖의 숫자, 개수가 6보다 작은 숫자, 중복된 숫자는 로또를 생성하지 않고 각각 알맞은 예외를 발생시킨다.")
각 예외상황별로 테스트케이스를 분리하는 게 맞습니다.
테스트 메서드도 SRP 를 준수해야 합니다.

2022-01-03 13:21 UTC, brainbackdoor commented on src/test/java/lotto/domain/LottoResultTest.java
> +    }
흠.. 메서드를 추출했다면, ParameterizedTest 를 통해 여러 상황에 대한 수익률을 테스트하여 재사용하는 것은 어떨까요
그게 아니라면 기댓값을 값으로 표현해도 괜찮다고 생각하구요.

2022-01-03 13:21 UTC, merged

2022-01-04 05:33 UTC, yunhalee05 commented on src/test/java/lotto/domain/LottoTest.java
> +    @DisplayName("범위 밖의 숫자, 개수가 6보다 작은 숫자, 중복된 숫자는 로또를 생성하지 않고 각각 알맞은 예외를 발생시킨다.")
해당부분확인하여 예외별로 테스트케이스를 분리하여 실행하도록 변경하였습니다!

2022-01-04 05:34 UTC, yunhalee05 commented on src/test/java/lotto/domain/LottoResultTest.java
> +    }
해당부부 확인하여 parameterizedTest를 사용하고 methodSource에 여러가지 경우를 테스트 할 수 있도록 값을 추가하도록 하였습니다!