[전지원] 문자열 덧셈 계산기 및 로또 (1단계)
next-step/java-lotto pull request #2251
Opened 2022-02-03 12:41 UTC by kworkbee

안녕하세요! 전지원이라고 합니다. 😄 
두 번째 리팩터링 프로젝트로, 여전히 부족한 부분이 많지만 더 좋은 코드를 작성할 수 있는 안목을 키울 수 있도록 많은 조언과 격려를 부탁드립니다. 👍🏼 

이번 프로젝트는 김윤경님(@fpal95)과 함께 페어로 구현하였습니다.

감사합니다!

## 요구사항

### 문자열 계산기

- [X] **문자열을 입력**받는다. --> `Calculator#calculate`
- [X] **식을 검증하다**. --> 검증 : `Calculator#validateExpression`
  - [X] **`,`, `:`은 기본 구분자**이다.
  - [X] 기본 구분자 이외에 `//`와 `\n` 사이에 사용자 임의의 구분자를 설정할 수 있다.
    - [X] 이 때 숫자는 들어올 수 없다.
  - [X] 구분자를 기준으로 *Operand*를 파싱한다.
  - [X] `빈 문자열` 같은 경우에는 `0`이 반환한다.
  - [X] `0, 양수` 이외에는 `RuntimeException`을 throw 한다.
- [X] **구분자로 나눈다**. --> 분할 : `Tokenizer#splitExpression`
- [X] 계산 결과를 출력한다.
  - [X] **합**을 계산 --> `Calculator#getSum`

### 로또

- [X] 구입금액을 입력받는다.
  - [X] 사야하는 장 수를 결정한다.
    - [X] 장 수를 기반으로 로또 넘버를 생성한다.
- [X] 지난 주 당첨 번호를 입력받는다.
  - [X] 보너스볼도 입력받는다.
- [X] 각 티켓마다 비교해서 일치여부 계산한다.
  - [X] 수익률을 계산한다.

2022-02-03 15:49 UTC, vsh123 requested changes
지원님 안녕하세요!
로또 미션 1단계 잘 구현해주셨네요!! 💯 

몇가지 코멘트를 남겼으니 확인부탁드리겠습니다~!
궁금하신 점은 언제든지 DM주세요!

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/calculator/Tokenizer.java
> +public class Tokenizer {
해당 클래스에 있는 public 메서드에 대한 테스트를 만들어보면 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/test/java/calculator/CalculatorTest.java
> +    @ParameterizedTest
ParameterizedTest 💯

2022-02-03 15:49 UTC, vsh123 commented on README.md
> +#### 추가된 요구 사항
추가된 요구 사항은 반영을 하지 않은걸까요~?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/calculator/Calculator.java
> +    private static final String EXCEPTION_MESSAGE = "음수가 포함될 수 없습니다.";
`EXCEPTION_MESSAGE`가 2개 이상이됐을 경우 확장성이 용이하지 않은 네이밍인 것 같아요! 조금 더 좋은 네이밍을 해보는 건 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/Application.java
> +        new LottoController(InputView.getAmount())
`getAmount`만 Controller 생성시 주입해주는 이유가 있을까요?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/controller/LottoController.java
> +    private final int amount;
`모든 원시 값과 문자열을 포장한다`라는 요구사항에 맞게 해당 값도 포장해보면 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Tickets.java
> +public class Tickets {
해당 클래스는 일급컬렉션을 염두해두고 만드신 클래스가 맞을까요?
그렇다면 [이 글](https://jojoldu.tistory.com/412)을 읽고, 해당 클래스가 일급컬렉션에 부합하는 클래스인지 고민해보면 어떨까요~?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/controller/LottoController.java
> +    public void run() {
저는 개인적으로 `public`메서드를 위에 두고, 하위에 호출하는 `private`메서드를 두는 것을 선호하는데요! 지원님은 지금 메서드 위치에 대해 어떻게 생각하시나요~?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/domain/generator/AutoGenerator.java
> +public class AutoGenerator implements LottoGenerator {
`AutoGenerator`만 봐서는 어떤 역할인지 모호해보여요! `AutoLottoGenerator`는 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/domain/generator/AutoGenerator.java
> +    private List<Integer> numberPool;
컬렉션의 네이밍은 복수형으로 지어주면 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Numbers.java
> +    private final List<Integer> numberList;
Collection의 네이밍을 지일때는 특정 Collection명(List, Set 등)보다는 복수형(numbers)로 선언해주면 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Ticket.java
> +        return (int) lotto.get().stream()
`lotto.get()`을 하지않고, Numbers객체에게 메세지를 보내면 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Ticket.java
> +        return lotto.get().stream()
마찬가지로 lotto.get()을 하지않고, Numbers객체에게 메세지를 보내면 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Rank.java
> +public enum Rank {
헤딩 enum에도 테스트 코드 작성한 부분이 보이는 것 같아요! 테스트코드를 작성해보면 어떨까요?

2022-02-03 15:49 UTC, vsh123 commented on src/test/java/lotto/domain/lotto/PrizeRatioTest.java
> +        return PRICE_PER_TICKET * tickets.get().size();
여기도 `get()`을 없애보세요!

2022-02-04 06:44 UTC, kworkbee commented on src/main/java/calculator/Tokenizer.java
> +public class Tokenizer {
`Tokenizer` 테스트를 작성안했군요! `splitExpression` 메서드를 테스트하는 테스트를 작성했습니다.

2022-02-04 06:45 UTC, kworkbee commented on README.md
> +#### 추가된 요구 사항
확신이 없어서 리뷰 과정에서 조금씩 체크해 나갈 예정입니다!

2022-02-04 06:45 UTC, kworkbee commented on src/main/java/calculator/Calculator.java
> +    private static final String EXCEPTION_MESSAGE = "음수가 포함될 수 없습니다.";
구체적인 이름을 부여해보겠습니다!

2022-02-04 06:46 UTC, kworkbee commented on src/main/java/lotto/Application.java
> +        new LottoController(InputView.getAmount())
아예 컨트롤러를 싱글턴 인스턴스로 변환해서 실행시키고, `run()` 메서드에서 `amount`를 입력받도록 변환했습니다!

2022-02-04 06:48 UTC, kworkbee commented on src/main/java/lotto/domain/lotto/Tickets.java
> +public class Tickets {
주입할 때 이미 값이 삽입된 `List<Ticket>`을 입력받도록 하고, 기존의 `addTicket` 메서드는 제거했습니다!

2022-02-04 06:48 UTC, kworkbee commented on src/main/java/lotto/controller/LottoController.java
> +    public void run() {
호출하는 메서드가 상위로 올 수 있도록 하는 것이 더 읽기 좋아보입니다!

2022-02-04 06:49 UTC, kworkbee commented on src/main/java/lotto/domain/lotto/Ticket.java
> +        return (int) lotto.get().stream()
`Numbers`에게 위임하고, `Ticket`은 해당 메서드를 호출해오는 방식으로 변경했습니다!

2022-02-04 06:49 UTC, kworkbee commented on src/main/java/lotto/domain/lotto/Rank.java
> +public enum Rank {
`enum`을 고려 못했네요! 테스트를 작성했습니다!

2022-02-04 06:53 UTC, kworkbee commented
첫 리뷰 감사합니다!
페어와 함께 보완사항에 대해서 고민해보고 수정하는 시간을 가져봤습니다.

## 보완사항

### 공통

- 일부 메서드 / 변수명의 수정

### Calculator

- Tokenizer 테스트 추가 

### Lotto

- `LottoController` -> 싱글턴 인스턴스로 변경
  - 상태를 가지지 않도록 멤버 변수 제거
  - 기존의 `amount`는 `run`메서드에서 입력받도록 변경
- `Tickets`의 `addTicket` 제거 -> 생성 시 `List<Ticket>` 주입, `Collections.unmodifiableList` 통해 불변 리스트 반환
- `Numbers`에 번호 비교 역할 위임
- `Rank` 테스트 구현

---

감사합니다! 🔥

2022-02-08 11:41 UTC, vsh123 approved these changes
지원님 안녕하세요!!
피드백 반영 잘해주셨네요! 💯 

몇가지 코멘트를 남겼으니 다음 단계에서 함께 확인부탁드리겠습니다!!
이번 단계는 머지하도록 할게요! 다음 단계도 화이팅하세요!

2022-02-08 11:41 UTC, vsh123 commented on src/main/java/lotto/controller/LottoController.java
> +        tickets = purchase(count);
`Tickets`객체 선언을 여기서해주는 건 어떨까요?

```suggestion
        int amount = InputView.getAmount();
        int count = amount / PRICE_PER_ONE_TICKET;

        Tickets tickets = purchase(count);
```

2022-02-08 11:41 UTC, vsh123 commented on src/main/java/lotto/controller/LottoController.java
> +        int amount = InputView.getAmount();
> 모든 원시 값과 문자열을 포장한다

위 내용에 따라 `amount` 라는 원시값을 포장해보면 어떨까요?

2022-02-08 11:41 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Numbers.java
> +        return numbers.stream()
`contains`를 사용하지않고 `stream`을 이용하신 이유가 있으실까요?

2022-02-08 11:41 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Answer.java
> +            comparisonNumbers)) {
```suggestion
if (!validateEachNumberInRange(comparisonNumbers) || !validateCountOfNumbers(comparisonNumbers)) {
```

2022-02-08 11:41 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Answer.java
> +        return comparisonNumbers.get().size() == LottoGenerator.LOTTO_NUMBERS;
`comparisonNumbers.get()` 없이 구현해볼 수 없을까요?

2022-02-08 11:41 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Answer.java
> +        return comparisonNumbers.get().stream()
여기도 gettter없이 구현해보면 어떨까요?

2022-02-08 11:41 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Answer.java
> +    private boolean isNumberInRange(final int number) {
해당 validation이 `Answer`의 책임이 맞을지 고민해보면 좋을 것 같아요!

2022-02-08 11:41 UTC, merged

2022-02-09 15:07 UTC, kworkbee commented on src/main/java/lotto/domain/lotto/Answer.java
> +    private boolean isNumberInRange(final int number) {
각 숫자에 관련한 `Number` 클래스로 포장하고, 이 클래스에 검증 권한을 위임하면 좋을 것 같다는 생각입니다 😃

2022-02-09 15:07 UTC, kworkbee commented on src/main/java/lotto/domain/lotto/Answer.java
> +            comparisonNumbers)) {
검증 권한을 타 객체에 위임함에 따라서 해당 부분은 제거시켰습니다!

2022-02-09 15:08 UTC, kworkbee commented on src/main/java/lotto/domain/lotto/Numbers.java
> +        return numbers.stream()
`contains()`를 바로 사용할 수 있다는 생각을 미처 못했네요 ㅠㅠ

2022-02-09 15:08 UTC, kworkbee commented on src/main/java/lotto/controller/LottoController.java
> +        int amount = InputView.getAmount();
수동 기능을 구현하면서 총 구매장수와 자동/수동 구매장수를 포함하는 `TicketMachine`을 생성하면 어떨까라는 생각입니다!