[이세라] 문자열 덧셈 계산기 및 로또 (1단계)
next-step/java-lotto pull request #2253
Opened 2022-02-04 08:50 UTC by Xxell-8

2022-02-05 00:22 UTC, liquidjoo requested changes
안녕하세요 이번 로또 미션 리뷰어를 맡은 김성주 입니다 :)
미션 구현 잘해주셨어요 👍 
몇가지 고민해볼 코멘트들을 남겼어요~ 확인하고 다시 요청주세요

2022-02-05 00:34 UTC, liquidjoo requested changes
안녕하세요 이번 로또 미션 리뷰어를 맡게된 김성주 입니다
미션 구현 잘해주셨어요 👍 
몇가지 코멘트 남겼어요 확인하고 다시 요청 주세요~

2022-02-10 17:02 UTC, Xxell-8 commented on src/test/java/lotto/domain/WinningNumberTest.java
> +class WinningNumberTest {
확인하고 수정했습니다👍

2022-02-10 17:03 UTC, Xxell-8 commented on src/main/java/lotto/domain/machine/LottoGenerator.java
> +    List<Integer> get();
리팩토링하면서 Lotto를 생성해 반환하도록 수정해봤습니다..!

2022-02-10 17:33 UTC, Xxell-8 commented on src/main/java/calculator/controller/CalculatorController.java
> +public class CalculatorController {
무상태 객체로 만들면 변경될 여지가 있는 상태 자체가 사라지면서 객체의 동작이 변경되지 않도록 보장될 것 같고, 동시에 여러 번 호출되더라도 서로한테 영향을 주지 않으니까 안정성(?)이 높아질 수 있지 않을까요?🙃

2022-02-10 17:35 UTC, Xxell-8 commented on src/main/java/calculator/view/InputView.java
> +        Scanner scanner = new Scanner(System.in);
static final로 Scanner 객체를 하나 만들어두고 사용하는 방식으로 수정해봤습니다!

2022-02-11 04:31 UTC, Xxell-8 commented on src/main/java/lotto/controller/LottoController.java
> +        OutputView.printPurchaseTicket(lottoManager.getLottos());
현재 호춣하고 있는 메서드를 콜하는 상위 메서드를 하나 더 만들어서 해당 메서드를 콜하는 방식으로 변경해봤습니다!

2022-02-11 06:14 UTC, Xxell-8 commented on src/main/java/lotto/domain/WinningResult.java
> +        return result;
외부에서 값을 변경할 수 있게 될 것 같네요! 우선은 원본이 아닌 복사본을 반환하도록 수정해봤습니다,,

2022-02-11 08:58 UTC, Xxell-8 commented on src/main/java/lotto/controller/LottoController.java
> +    private List<Rank> getRanksFrom(LottoManager lottoManager, WinningNumber winningNumber) {
이 기능 자체는 리팩토링 과정에서 사라지기는 했는데, List를 감싸는 객체를 만들면 외부에서 해당 데이터를 조작하는 일을 방지할 수 있게 되지 않을까 싶습니다..!

2022-02-11 09:00 UTC, Xxell-8 commented on src/main/java/lotto/domain/Ticket.java
> +    }
입력 값이 1000원 단위가 아닐 때 예외 처리를 하면서 연산 과정이 정수로만 이루어지게 될 것 같아서 일단은 int 형을 유지했는데, 이 부분은 조금 더 고민해보겠습니당 !!

2022-02-11 09:03 UTC, Xxell-8 commented
작성해주신 리뷰를 최대한 반영하면서 제가 하고 싶었던 리팩토링까지 추가해봤습니다 : )
더 수정할 부분이 있거나 참고할 만한 부분이 있다면 말씀해주세요😃

좋은 리뷰 감사합니다 👍

2022-02-13 04:44 UTC, liquidjoo requested changes
피드백 반영 잘해주셨어요 💯 
몇가지 코멘트 남겼어요~ 확인하고 다시 요청주세요 🙇

2022-02-13 04:44 UTC, liquidjoo commented on src/main/java/lotto/controller/LottoController.java
> +        OutputView.printWinningResult(result, profitRate);
컨트롤러의 역할이 무엇일까요?
역할에 맞게 책임을 나누어 볼 수 있을까요?

2022-02-13 04:44 UTC, liquidjoo commented on src/main/java/lotto/domain/WinningResult.java
> +    private final Map<Rank, Integer> result;
Map 을 통한 일급컬렉션을 만들어 통계만을 위한 객체를 만들어봐도 좋을 것 같아요 :)
> Map<1등, 당첨자 수>, Map<2등, 당첨자 수> ...

2022-02-13 04:44 UTC, liquidjoo commented on src/main/java/lotto/domain/lottogenerator/RandomLottoGenerator.java
> +    }
static 을 통해 Integer 를 캐시 처럼 사용해도 좋으나 LottoNumber 객체를 활용해보는 것이 어떨까요?

2022-02-13 04:44 UTC, liquidjoo commented on src/main/java/lotto/domain/lottogenerator/LottoGenerator.java
> +import java.util.List;
사용하지 않고있는 패키지는 삭제 해주세요~

2022-02-13 04:44 UTC, liquidjoo commented on src/main/java/lotto/dto/LottosDTO.java
> +    }
사용하지 않고 있는 메서드는 과감히 삭제해주세요 :)
> 생성자가 있기 때문에 set 은 필요 없을 것 같네요~

2022-02-13 08:47 UTC, Xxell-8 commented on src/main/java/lotto/domain/lottogenerator/RandomLottoGenerator.java
> +    }
저번 리팩토링을 하면서 불필요한 객체 생성을 막기 위해 LottoNumber를 생성하는 방식을 바꿨는데요!
그러면서 RandomGenerator 객체도 shuffle하는 과정까지는 정수로 하고,
Lotto가 생성될 때 LottoNumber로 변환되도록 코드를 구성해봤습니다 : )

LottoNumber 객체를 다시 이용하도록 바꾸는 게 좋을까요?.?

2022-02-16 03:33 UTC, Xxell-8 commented on src/main/java/lotto/controller/LottoController.java
> +        OutputView.printWinningResult(result, profitRate);
컨트롤러는 모델이랑 뷰 사이에서 애플리케이션 흐름을 제어하는데, InputView를 통해 입력 받고 domain에 있는 비즈니스 로직을 처리해서 그 결과를 OutputView로 출력하도록 하는 역할로 이해를 했습니다.

지금 작성한 로또 컨트롤러에서 어떤 부분을 더 나눌 수 있는지 잘 모르겠어서 일단은 관련된 부분을 메서드로 묶는 작업까지만 수행을 해봤습니다 😹

2022-02-17 09:26 UTC, liquidjoo commented on src/main/java/lotto/domain/lottogenerator/RandomLottoGenerator.java
> +    }
WinningLotto 때에는 of, 로또를 생성시에는 from 을 사용하고 있는데요~ 하나로 통일하는게 좋을 것 같아요!

2022-02-17 12:21 UTC, liquidjoo requested changes
피드백 반영 잘하셨어요 👍 
몇 가지 코멘트 남겼어요~ 확인하고 다시 요청주세요 🙇

2022-02-17 12:21 UTC, liquidjoo commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
generator 에서 이미 만들었는데 또 한번 캐싱 처럼 처리해야할 필요가 있을까요?
캐싱 되어진 것을 가져다 쓰면 어떨까요?

2022-02-17 12:21 UTC, liquidjoo commented on src/main/java/lotto/domain/Lottos.java
> +    public Map<Rank, Integer> mapResult(WinningLotto winningLotto) {
결과에 대한 책임이 Lottos 보단 다른 객체에 어울려보여요 :)
메시지 전달로 구현해보는 것이 어떨까요?

2022-02-17 12:21 UTC, liquidjoo commented on src/main/java/lotto/domain/Lottos.java
> +    }
책임을 적절한 역할에 맞추어 이동해보는 것이 좋을 것 같아요 :)

2022-02-17 12:21 UTC, liquidjoo commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
보너스 번호의 유무를 코드로 표현해보면 어떻게 할 수 있을까요?

2022-02-17 12:21 UTC, liquidjoo commented on src/main/java/lotto/dto/LottosDTO.java
> +public class LottosDTO {
DTO 는 현재 구조에서 굳이 필요할 것 같진 않아요 :)
DTO 없이 개발해 보아요 :)

2022-02-17 12:21 UTC, liquidjoo commented on src/main/java/lotto/utils/Converter.java
> +public class Converter {
Converter 가 오히려 객체의 응집도를 방해하는 요소가 될 수 있을 것 같네요 :)
아래의 책임을 적절한 객체로 옮겨 보아요

2022-02-18 03:54 UTC, Xxell-8 commented on src/main/java/calculator/domain/StringCalculator.java
> +            if (number < 0) {
네!

2022-02-18 03:58 UTC, Xxell-8 commented on src/main/java/lotto/controller/LottoController.java
> +    }
이전 피드백을 통해 컨트롤러 클래스를 무상태로 바꾸면서, 컨트롤러를 활용할 때 새로운 객체를 생성하지 않아도 같은 동작을 보장할 수 있다는 생각을 했습니다!
그래서 불필요한 객체 생성을 하지 않으면 좋겠다는 생각에 싱글톤을 적용해봤는데, 이렇게 하는 게 좋은 방식이 아닌 걸까요?.?😢

2022-02-18 04:17 UTC, Xxell-8 commented on src/main/java/lotto/domain/Lottos.java
> +    }
Lottos 클래스에 있는 Result 관련 메서드들은 WinningResult가 가지는 게 더 좋을 것 같다는 생각이 들어서 옮겨봤습니다!

2022-02-18 11:05 UTC, Xxell-8 commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
보너스 매칭 결과가 Rank 전체가 아니라 SECOND와 THIRD에만 영향을 주는 요소라 고민이 되었는데요! 우선은 추상 클래스를 활용하는 방식으로 바꿔봤습니다,,

2022-02-22 14:28 UTC, liquidjoo approved these changes
피드백 반영 잘해주셨어요 👍 
1단계 머지할게요~ 다음 단계 진행해주세요

2022-02-22 14:28 UTC, merged

2022-02-23 00:26 UTC, Xxell-8 commented on src/main/java/lotto/domain/Lottos.java
> +        return lottos;
이 부분도 다음 미션 진행하면서 반영하겠습니다 : 0