[김윤경] 문자열 덧셈 계산기 및 로또 (1단계)
next-step/java-lotto pull request #2255
Opened 2022-02-04 09:39 UTC by fpal95

안녕하세요!

전지원(@kworkbee)님과 함께 페어 미션 진행했습니다.
확인부탁드립니다:)

2022-02-06 12:43 UTC, joswlv requested changes
안녕하세요 윤경님!
구현을 깔끔하게 잘 해주셨네요 👍 
몇 가지 코멘트 남깁니다.
확인 부탁드립니다. 🙇

2022-02-06 12:43 UTC, joswlv commented on src/main/java/lotto/domain/lotto/PrizeRatio.java
> +        return totalPrize.divide(new BigDecimal(purchased), ROUND_SCALE, RoundingMode.DOWN);
BigDecimal 연산 👍

2022-02-06 12:43 UTC, joswlv commented on src/main/java/lotto/domain/generator/LottoGenerator.java
> +public interface LottoGenerator {
LottoGenerator 인터페이스 👍 이런 형태의 인터페이스를 함수형 인터페이스라고 부른답니다. @FunctionalInterface가 무엇인지 찾아보고 공부해 보세요.

2022-02-06 12:43 UTC, joswlv commented on src/main/java/lotto/domain/lotto/Numbers.java
> +    private final List<Integer> numbers;
`Integer`원시값을 Number로 포장해보면 어떨까요?

2022-02-06 12:43 UTC, joswlv commented on src/main/java/lotto/domain/lotto/Rank.java
> +        this.matches = matches;
`(howManyMatches, bonusContains) -> 각 rank에 맞는 상태`처럼 `FunctionalInterface`를 사용해 Rank의 value로 추가해보면 어떨까요?
`getRank`를 직관적으로 표현 할 수 있을 것 같습니다.

2022-02-08 08:06 UTC, fpal95 commented on src/main/java/lotto/domain/lotto/Rank.java
> +        this.matches = matches;
안녕하세요, 리뷰어님!
해당 부분에 대해 페어의 도움을 받았습니다ㅠㅠ
결과적으로 BiFunction이라는 인터페이스에 대해 알게되었는데 아직 개념이 부족해서 그런지 기존 코드가 저에게 좀 더 쉽게 다가왔던 것 같습니다.
아직 반영하지는 않았지만 혹시 biFunction말고 다른 방법도 있을까요?

2022-02-12 11:25 UTC, joswlv requested changes
안녕하세요 윤경님! 
코드를 잘 작성해주셨네요 👍 
몇 가지 코멘트를 남겨 드렸습니다.
확인 부탁드립니다. 🙇

2022-02-12 11:25 UTC, joswlv commented on src/main/java/lotto/domain/lotto/Numbers.java
> +        return Collections.unmodifiableList(numbers);
방어적 복사 👍 

참고 
https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/

2022-02-12 11:25 UTC, joswlv commented on src/main/java/lotto/domain/generator/LottoAutoGenerator.java
> +    }
```suggestion
    private List<Number> lottoNumberPool;

    public LottoAutoGenerator() {
        this.lottoNumberPool = IntStream.rangeClosed(LOTTO_MIN_NUMBER, LOTTO_MAX_NUMBER)
          .mapToObj(LottoNumber::new)
          .collect(Collectors.toList());
    }

    @Override
    public LottoNumbers generateNumbers() {
        Collections.shuffle(lottoNumberPool);
        return new LottoNumbers(lottoNumberPool.stream()
          .limit(LOTTO_NUMBERS)
          .collect(Collectors.toList()));
    }
```
로또 번호 풀을 만들고 셔플 한 뒤에 6개를 잘라 티켓을 만드는 로직은 같습니다.

로또 숫자를 Integer로 표현하는 것보다 Number로 표현하는 것은 어떨까요?
상수/객체의 의미를 명확하게 하기 위해 네이밍을 수정해 보는 것은 어떨까요?

2022-02-12 11:25 UTC, joswlv commented on src/main/java/lotto/view/OutputView.java
> +    }
```suggestion
    private static final String MESSAGE_RESULT = "총 수익률은 %f 입니다.";
    public static void printResult(final BigDecimal calculateRatio) {
        System.out.println(String.format(MESSAGE_RESULT, calculateRatio));
    }
```
String.format을 이용해보는 것은 어떨까요?

2022-02-12 11:25 UTC, joswlv commented on src/main/java/lotto/controller/LottoController.java
> +}
파일의 마지막은 개행이 필요합니다.

참고 
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

2022-02-22 13:44 UTC, fpal95 commented on src/main/java/lotto/domain/generator/LottoAutoGenerator.java
> +    }
훨씬 코드가 명확하게 파악되는 것 같습니다. 
네이밍을 좀 더 명확하게 할 수 있도록 많이 생각하겠습니다!
감사합니다.

2022-03-05 02:56 UTC, joswlv approved these changes
안녕하세요 윤경님!
리뷰내용을 잘 반영해주셨네요!
1단계 머지 하겠습니다.

2022-03-05 02:56 UTC, merged