.
next-step/java-lotto pull request #2272
Opened 2022-02-04 15:27 UTC by sk11ingyuhwang

.

2022-02-06 10:21 UTC, hyunniiii commented
> 정적 메소드를 언제 써야 할까?

정적 메소드는 클래스가 메모리에 올라갈 때 자동적으로 생성이 됩니다. 한번 생성된 것을 계속해서 사용하기 때문에 메서드를 재사용할 때 유용합니다. 메서드가 공유되고, 변화하지 않고, 상태를 가지고 있지 않을 때 사용하시면 됩니다. 예시로, 자바가 제공해주는 정적 메서드도 많이 있습니다. ″̮  
https://kookyungmin.github.io/language/2018/06/14/java_22/

> getter 사용에 대한 고민

값을 가져오기 위해서 getter를 사용하는건 괜찮다고 생각합니다. 단, 비즈니스 로직에서 객체에게 메시지를 던져서 처리할 수 있는 부분은 getter를 사용하지 않는게 좋습니다. 아래 글에 잘 설명되어있네요. 참고해주세요 ″̮ 
https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/

2022-02-06 10:23 UTC, hyunniiii requested changes
안녕하세요 인규님~
몇가지 코멘트 남겼습니다.
확인 부탁드립니다 ″̮

2022-02-06 10:26 UTC, hyunniiii commented
사용하지 않는 empty.txt 파일은 삭제해주세요 ″̮

2022-02-06 10:53 UTC, sk11ingyuhwang commented
질문 내용을 다시 읽어보니 조금 모호한 부분이 있다는걸 느꼈어요. 
그럼에도 불구하고 자세하게 답변 남겨주셔서 감사합니다. 
보내주신 피드백은 반영해서 다시 리뷰 요청 드릴게요. 감사합니다!

2022-02-07 08:04 UTC, sk11ingyuhwang commented on src/main/java/stringadder/domain/Adder.java
> +
반영했습니다. :)

2022-02-07 08:15 UTC, sk11ingyuhwang commented on src/main/java/stringadder/domain/Adder.java
> +        }
`Adder` 클래스를 보니 `validate` 메소드로 빼는것 외에도 stream 줄바꿈, 매직 넘버, 리터럴이 적용되어 있지 않았네요 ㅠㅠ.
반영했습니다.

2022-02-07 11:52 UTC, sk11ingyuhwang commented on src/main/java/stringadder/domain/Adder.java
> +
아!! 책임을 나눠줘야 하는것에 대해 이해했습니다.
파싱과 검증 로직은 add메서드에 대한 책임이 아니에요.
메소드로 따로 빼주었어요! :) 감사합니다.

2022-02-07 11:57 UTC, sk11ingyuhwang commented on src/main/java/stringadder/utils/StringUtils.java
> +    public static List<String> splitStr(final String input) {
넵! 반영하였습니다. :)

2022-02-07 17:27 UTC, sk11ingyuhwang commented on src/main/java/stringadder/utils/StringUtils.java
> +        Matcher matcher = Pattern.compile(CUSTOM_DELIMITER).matcher(input);
오 네! `static` 하게 만들어 주었어요!
이게 의도하신 말씀이신지 모르겠어요!
반영했습니다!!

2022-02-07 21:45 UTC, sk11ingyuhwang commented on src/main/java/stringadder/utils/StringUtils.java
> +        if (input.contains(SLASH)) {
처음에 Application 에서 입력으로 `//\n`을 처리하면 NPE가 발생하는것으로 이해했어요.
그래서, 이것 저것 트라이 해보는데 잘 안되서 계속 의문이었어요. 
그러다, 테스트 코드로 써서  확인해보니 Application단에서 \n는 개행문자 처리가 안되는것을 확인했네요 😱

코멘트 감사드립니다. :)
반영했습니다.

2022-02-07 22:34 UTC, sk11ingyuhwang commented on src/main/java/lotto/domain/Winning.java
> +        if (winningLottoNumber.getLottoNumber().contains(bonusLottoNumber.getValue())) {
넵!! 반영했습니다 :)

2022-02-07 22:36 UTC, sk11ingyuhwang commented on src/test/java/lotto/domain/WinningTest.java
> +    @DisplayName("위닝_숫자_검증")
오! 맞습니다. ㅜㅜ
`지난_주_당첨번호에_보너스볼이_중복으로_들어가있는지_검증` 으로 변경했습니다.

2022-02-07 23:58 UTC, sk11ingyuhwang commented on src/main/java/lotto/domain/RankCount.java
> +    public HashMap<Rank, Integer> rankCount(){
반영했습니다. :)

리팩토링 과정에서 인자로 받아서 처리하는 부분의 파라미터 개수가 증가했어요. 그러면서 상태값을 가지는 필드가 3개가 되었습니다. 문득, 객체 지향 생활 체조에서 아래 글을 보아서 리팩토링이 적절하게 되었는지 모르겠어요.
`3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다. ` 

리뷰어님의 생각이 어떤지 궁금합니다. 감사합니다.!

### before 
`RankCount.java`
```java
public HashMap<Rank, Integer> rankCount() {
        HashMap<Rank, Integer> result = new HashMap<>();
        for (Rank rank : Rank.values()) {
            result.put(rank, INITIAL_VALUE);
        }

        for (Lotto lotto : lottos.lottos()) {
            Rank rank = Rank.countMatch(winning, lotto);
            result.put(rank, result.get(rank) + 1);
        }
        return result;
    }
```
`RankResult.java`
```java
package lotto.domain;

import java.util.HashMap;
import java.util.Map;

public class RankResult {

    private final Map<Rank, Integer> rankResult;

    public RankResult(Map<Rank, Integer> rankResult) {
        this.rankResult = new HashMap<>(rankResult);
    }

    public RankResult(RankCount rankCount) {
        Map<Rank, Integer> rankResult = new HashMap<>(rankCount.rankCount());
        this.rankResult = rankResult;
    }

    public Map<Rank, Integer> getRankResult() {
        return rankResult;
    }

    public Money getTotalPrize() {
        return new Money(rankResult.entrySet().stream()
            .mapToInt(entry -> entry.getKey().getPrize(entry.getValue()).getValue())
            .sum());
    }
}
```

### after
`RankCount.java` 삭제
`RankResult.java`
```java
package lotto.domain;

import java.util.HashMap;
import java.util.Map;

public class RankResult {

    private static final int INITIAL_VALUE = 0;
    private Map<Rank, Integer> rankResult;
    private final Lottos lottos;
    private final Winning winning;


    public RankResult(Lottos lottos, Winning winning) {
        this.lottos = lottos;
        this.winning = winning;
        this.rankResult = rankCount(this.lottos,this.winning);
    }

    public Map<Rank, Integer> getRankResult() {
        return rankResult;
    }

    public Money getTotalPrize() {
        return new Money(rankResult.entrySet().stream()
            .mapToInt(entry -> entry.getKey().getPrize(entry.getValue()).getValue())
            .sum());
    }

    public HashMap<Rank, Integer> rankCount(Lottos lottos, Winning winning) {
        HashMap<Rank, Integer> rankResult = new HashMap<>();
        for (Rank rank : Rank.values()) {
            rankResult.put(rank, INITIAL_VALUE);
        }

        for (Lotto lotto : lottos.lottos()) {
            Rank rank = Rank.countMatch(winning, lotto);
            rankResult.put(rank, rankResult.get(rank) + 1);
        }
        return rankResult;
    }
}
```

2022-02-08 08:22 UTC, sk11ingyuhwang commented on src/main/java/lotto/domain/LottoFullNumber.java
> +public class LottoFullNumber {
네! 무슨 말씀인지 이해했습니다.
감사합니다. :)

2022-02-08 11:07 UTC, sk11ingyuhwang commented on src/main/java/lotto/view/UserConsole.java
> +        int money = Integer.valueOf(scanner.nextLine());
예외 처리 신경쓰겠습니다. 반영했습니다. :)
말씀해주신 예외 처리해주면서 `View` 에서 `Validation` 로직을 제외하고 이를 `Money` 클래스에 포함시켰어요. 
그리고 다른 로직을 보니까 `winningLottoNumber` 메소드에 입력 클래스에 적절하진 못한 로직이 포함되어있다는것을 느꼈어요.
감사합니다.

2022-02-08 14:45 UTC, sk11ingyuhwang commented on src/main/java/lotto/view/UserResult.java
> +    }
리뷰어님 안녕하세요. 🙇‍♂️
이 부분은 잘 이해가  안돼요. 😥
View에서 `rank`를 아예 사용하면 안되는 걸까요? 
저도 이 부분이 염려되어 코드를 구현할 때 어떻게 처리해야 할까 고민이 많았어요.
제가 생각한 방법은 파라미터로 객체 자체를 넘겨주자 였어요. 
그러면 UserResult 클래스에서는 외부에서 받아온 클래스에 대해 모른다고 생각했어요. 
리뷰어님의 생각이 궁금해요.
도와주세요. 🙏

2022-02-09 11:25 UTC, hyunniiii commented on src/main/java/lotto/domain/Money.java
> +    }
`validateTypeLessThousand`, `validateTypeNegativeNumber`는 `Integer.parseInt(value)`의 반환값만 있으면 validation 이 가능할 것 같습니다. 
반환값을 이용해서 validation을 해주면 어떨까요? 

또한 `validateTypeInput`의 반환값은 여전히 사용되고 있지 않는 것 같습니다. 
16번째 라인과 42번째 라인 둘 중 하나만 사용해보면 어떨까요?

2022-02-09 11:25 UTC, hyunniiii commented on src/main/java/lotto/view/UserConsole.java
> +    public static LottoNumber inputBbonusLottoNumber() {
```suggestion
    public static LottoNumber inputBonusLottoNumber() {
```
오타가 있네요 ″̮

2022-02-09 11:25 UTC, hyunniiii commented on src/main/java/lotto/controller/Controller.java
> +        UserResult.printPrizeRatio(new RankResult(lottoBundle, winning).getTotalPrize(), money);
30,31번 라인에 동일한 값을 가진 `RankResult`객체를 두번 생성해주네요.
변수로 받아서 값을 넣어주면 객체를 두번 생성하지 않아도 될 것 같습니다.

2022-02-09 11:25 UTC, hyunniiii commented on src/main/java/lotto/domain/RankCount.java
> +    public HashMap<Rank, Integer> rankCount(){
`lottos, winning`을 필드로 가지고 있지 않아도 될 것 같아요.
그러면 변수가 1개가 될 것 같습니다 ″̮ 
생성자 인자로 받아주도록 해보면 어떨까요?

2022-02-09 11:27 UTC, hyunniiii commented on src/main/java/lotto/view/UserResult.java
> +    }
`rank == rank.SECOND`라는 로직이 문제가 되는 것 같아요.
순서가 보장되도록 하면 `rank == rank.SECOND`를 하지 않아도 되지 않을까요? ″̮

2022-02-09 11:29 UTC, hyunniiii approved these changes
안녕하세요 인규님 ″̮ 
미션 반영 잘해주셨습니다 👍 
코드가 상당히 깔끔해졌네요.
몇가지 코멘트 남겼으니 다음 미션에 함께 반영부탁드립니다~!

2022-02-09 11:29 UTC, merged

2022-02-09 14:56 UTC, sk11ingyuhwang commented
리뷰어님 리뷰 감사드려요!
어제 뷰 를 도메인 으로부터 분리해야 된다에 대해 생각해봤어요.
피드백 주신 내용으로 Rank 를 왜 숨겨야 하는지도 이해했어요.
문득, 아래처럼 설계하면 조금 더 의미가 명확해지지 않을까 생각했어요.
ResultView 는 결과만 받아오고 DTO 에 해당 데이터에 대한 스펙을 정의한다면 데이터 보안, 스펙을 명확하게 정의하지 않을까? 접근해 봤어요.
리뷰어님은 어떻게 생각하시나요? 궁금해요!
읽어주셔서 감사드립니다. :절하는_남성:

2022-02-11 16:37 UTC, sk11ingyuhwang commented on src/main/java/lotto/domain/Shuffle.java
> +public interface Shuffle {
좋은 말씀 감사합니다. 🙇‍♂️

2022-02-11 17:23 UTC, sk11ingyuhwang commented on src/main/java/lotto/view/UserConsole.java
> +    public static LottoNumber inputBbonusLottoNumber() {
🥲

2022-02-11 17:24 UTC, sk11ingyuhwang commented on src/main/java/lotto/controller/Controller.java
> +        UserResult.printPrizeRatio(new RankResult(lottoBundle, winning).getTotalPrize(), money);
아아... 아아!!!! 😱