[정다훈] 로또(수동) 리뷰 요청드립니다.
next-step/java-lotto pull request #2280
Opened 2022-02-09 15:02 UTC by PandaHun

안녕하세요 리뷰어님 🙇
2단계 수동 로또 구매 기능 구현해 리뷰 요청드립니다. 🔥 

우선 피드백 반영은 

https://github.com/next-step/java-lotto/pull/2277#discussion_r802536490 해당 코멘트에 대해서는 9ba0880cee3381c1444008bb81c396545118e522 에서 외부 주입으로 통일시켜 해결을 했습니다.
그리고 https://github.com/next-step/java-lotto/pull/2277#discussion_r802534513 이 코멘트에 대해서는 답변 달았지만,
```
우선 엘레강트 오브젝트를 완독하거나 하진 않아서 잘 모르겠으나,
해당 내용을 본다면,

우선 제 코드들의 대다수는 생성자에서

할당 전 인자 값의 안전성 검사
할당
값의 유효성 검사를 진행합니다.

위의 아티클을 보면서 느낀건 생성자에 할당문만 있는 것은 매우 좋아보였습니다!
다만, 인자값에 대해 유효성 검사를 뒤로 미루며 lazy하게 유효성 검사를 하게 될텐데 과연 이게 맞는가 하는? 의문이 듭니다.

물론 엘레강트 오브젝트에서 제안하고 있는 것이 극단적인 객체지향인 것은 알고 있으나, 그 이점이 있는지 궁금하고
리뷰어님의 생각은 어떠신지 궁금합니다!
```

실제 2단계 수동 로또 구매는 62032dcd736e1a419aad3d3d149ffcc3e53e310e 커밋 부터 입니다. 

이상입니다!
그럼 리뷰 잘 부탁 드립니다 🙇

2022-02-10 15:22 UTC, vsh123 requested changes
다훈님 안녕하세요!
Step2도 깔끔하게 구현해주셨네요 👍 

몇가지 코멘트와 질문에 대한 답변을 남겼으니 확인부탁드리겠습니다!

2022-02-10 15:22 UTC, vsh123 commented on src/main/java/lotto/domain/LottoCount.java
> +    public static LottoCount from(String lottoCount) {
```
우선 엘레강트 오브젝트를 완독하거나 하진 않아서 잘 모르겠으나,
해당 내용을 본다면,

우선 제 코드들의 대다수는 생성자에서

할당 전 인자 값의 안전성 검사
할당
값의 유효성 검사를 진행합니다.

위의 아티클을 보면서 느낀건 생성자에 할당문만 있는 것은 매우 좋아보였습니다!
다만, 인자값에 대해 유효성 검사를 뒤로 미루며 lazy하게 유효성 검사를 하게 될텐데 과연 이게 맞는가 하는? 의문이 듭니다.

물론 엘레강트 오브젝트에서 제안하고 있는 것이 극단적인 객체지향인 것은 알고 있으나, 그 이점이 있는지 궁금하고
리뷰어님의 생각은 어떠신지 궁금합니다!
```

마땅히 코멘트를 넣을 공간이 없어 이곳에 작성할게요!!

우선 https://github.com/next-step/java-lotto/pull/2277#discussion_r802534513에 코멘트를 드린 이유는 생성자에서의 validation은 `할당하는 값에 대한 검증`만을 수행하면 어떨까라는 관점에서 말씀드렸습니다!!

예를 들어 지금 작성해주신 Lotto의 생성자를 본다면

```java
public class Lotto {

    private List<LottoNumber> lotto;

    public Lotto(List<LottoNumber> lotto) {
        validateDuplicates(lotto);  //값에 대한 유효성 검증
        this.lotto = lotto; // 할당
        validateLotto(); // validation
    }

    public Lotto(Set<LottoNumber> lotto) {
        this.lotto = new ArrayList<>(lotto); //할당
        validateLotto(); // validation
    }
```
과 같은 구조인데요! 

이런식으로 생성자 오버로딩이 지속적으로 발생한다면 모든 생성자에 대해 
* 할당
* validation
이라는 일종의 중복이 발생할 수 있을 것이고, 이는 추후 운영측면에서의 유지보수성을 떨어뜨린다고 생각해요.

또한 각 생성자의 validation을 위한 메서드가 지속적으로 추가된다면, 해당 클래스가 길어지게 될 것이고, 이로 인한 **핵심 비즈니스로직 파악**도 어려워질 수 있을 것 같네요!

그래서 만약 변경을 한다면, 아래와 같이 변경을할 수 있을 것 같아요

```java

public class Lotto {

    private List<LottoNumber> lotto;

    public Lotto(List<LottoNumber> lotto) {
        this.lotto = lotto;
        validateLotto();
    }

    public static Lotto from(List<LottoNumber> lottoNumbers) {
        validateDuplicates(lottoNumbers);
        return new Lotto(lottoNumbers);
    }

    public static Lotto from(Set<LottoNumber> lottoNumbers) {
        return new Lotto(new ArrayList<>(lottoNumbers));
    }
```

이처럼 생성자는 정말 값을 할당(그리고 해당 값에 대한 검증정도)까지의 역할만 수행을 하고, 나머지 역할은 외부에서 수행하는 게 올바르지 않나라는 관점에서 코멘트를 드렸었습니다! 생성자가 많아진다면, 그대로 떼서 팩토리 클래스로 만들수도 있구요!! 만약 아리송하거나, 추가 의견있으시면 코멘트 주세요!

2022-02-11 00:42 UTC, PandaHun commented on README.md
> +## 기능 목록
푸시를 안했네요 ㅜㅜ

2022-02-11 06:14 UTC, PandaHun commented on src/main/java/lotto/domain/lottogenerator/ManualLottoGenerator.java
> +    public Set<Integer> generateLotto() {
두가지 선택지가 있겠네요!
메서드 네이밍을 바꾸거나, `Lotto`를 리턴해 주거나

저는 후자를 택하겠습니다!

2022-02-11 06:34 UTC, PandaHun commented on src/main/java/lotto/controller/LottoMachine.java
>              .collect(Collectors.toList());
`ManualLottoGenerator`로도 옮길 수 있지만, `WinningLotto` 자체로도 옮길 수 있다고 생각됐습니다

그래서 후자로 진행해봤습니다.

2022-02-11 06:47 UTC, PandaHun commented
안녕하세요 선호님! 😎 

우선 주신 리뷰에 맞춰 수정을 진행해 봤습니다.

다만, 이번 피드백을 반영하면서 느꼈던 것이 있어 질문드리고 싶습니다.

https://github.com/next-step/java-lotto/pull/2277#discussion_r802534513 에서 생성자에 대해 생각해 보라하셨고, 대안을 제시해주셨습니다.

그래서 해당하는 다른 클래스들에 대해서도 적용이 가능함을 확인하고 수정했는데
막상, 적용하다보니 과연 정적 팩터리 메서드, 정적 메서드가 객체지향적인가 하는 궁금증이 생겼습니다.
https://www.yegor256.com/2017/11/14/static-factory-methods.html 엘레강트 오브젝트 저자는 이런 아티클을 쓰기도 했더라구요,

그래서 해당 내용에 대한 리뷰어님의 생각이 궁금했습니다.

제 생각은 아무래도 설계나 구현은 트레이드 오프의 결정체라, 최소한의 static 메서드를 사용하거나, 정적팩터리 메서드를 사용하는 것이 필요하다고 생각했습니다.

그럼 리뷰 부탁드립니다!

2022-02-12 12:52 UTC, vsh123 requested changes
다훈님 안녕하세요!
피드백 반영 잘해주셨네요 💯 

몇가지 코멘트를 남겼으니 확인부탁드리겠습니다!
다음 요청에는 머지하도록 할게요!!

2022-02-12 12:52 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/WinningLotto.java
> +    public static WinningLotto from(List<LottoNumber> lottoNumbers) {
* 해당 메서드는 테스트에서만 사용하고있는데요! 제거하는게 어떨까요? (테스트코드도 수정이 필요하겠네요 :) )

* 해당 메서드에있는 두개의 validation은 모두 WinningLotto객체 자체에 대한 validation으로 생성자에 위치하는게 어떨까 싶은데, 어떻게 생각하시나요?

2022-02-12 12:52 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/WinningLotto.java
> +    public static WinningLotto of(String winningLottoLine, String bonusBall) {
`String winningLottoLine`과 같이 view에서 전달된 값을 domain에 필요한 값으로 변환해주는 작업(`여기서는 winningLottoLine -> List<String> lottoNubmers정도 되겠네요!`)은 도메인 레이어가 아닌, 서비스레이어나, 컨트롤러 레이어에서 해주는게 어떨까 싶은데요! 이에 대해서 어떻게 생각하시나요?

2022-02-12 12:52 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/WinningLotto.java
> +                Collectors.toList(), list -> {
Return값에 대해 `list`라는 네이밍보다 의미를 조금 더 명확히 할 수 있는 네이밍을 해주면 어떨까요?

2022-02-12 12:52 UTC, vsh123 commented on src/main/java/lotto/domain/lotto/Lotto.java
> +    private List<LottoNumber> lottoNumbers;
`final` 선언이 가능해보입니다!

2022-02-15 01:54 UTC, vsh123 approved these changes
다훈님 안녕하세요~!
로또 미션 잘 구현해주셨네요!! 💯 

특별히 코멘트 드릴부분이 없어, 머지하도록 하겠습니다~!
남은 미션도 화이팅하세요!!!

2022-02-15 01:54 UTC, merged