[김태준] 로또 - Step2
next-step/java-lotto pull request #2282
Opened 2022-02-10 11:22 UTC by kimtaejun97

수동 로또 기능 구현하였습니다!
이번에도 잘 부탁드립니다! 🙇‍♂️

수동 로또 리스트와 자동 로또 리스트를 합칠 때 객체 생성 비용을 조금 낭비 하더라도,
합쳐서 새로운 객체를 생성하는 것이 더 자연스럽다고 생각해 그렇게 진행하였습니다. 이에 대한 리뷰어님의 의견도 듣고 싶습니다!

또 다른 분들의 코드를 읽어보면 String.format 이나  printf의 포멧을 상수로 빼내었는데, "%d개" 와 같은 간단한 포멧이나. 역할을 설명하기 어려운 포멧을 상수화 하는것이 더 가독성을 해치는 것 같아 리팩토링 하지 않았습니다.
여러곳에서 반복되어 사용되는 포멧이 아니라면 그냥 상수화 하지 않는 편이 나을까요? 이것에 대한 의견도 궁금합니다!

2022-02-11 15:32 UTC, hyunniiii requested changes
안녕하세요 태준님!
미션 잘 구현해주셨네요 😄 
코멘트 남겼으니 확인 부탁드립니다.

2022-02-11 15:32 UTC, hyunniiii commented on src/main/java/lotto/domain/judge/Judge.java
> +        return new LottoRanks(lottoRanks);
추가로 `lottos.get.forEach`는 아래의 디미터 법칙을 위반하고 있습니다.
lottos의 내부 값에 접근하지 않고 LottoRanks를 반환하면 어떨까요?

```java
public LottoRanks getRanks(final Lottos lottos) {
    return lottos.getLottoRanks();
}
```

2022-02-11 15:32 UTC, hyunniiii commented on src/main/java/lotto/domain/judge/Judge.java
> +        return new LottoRanks(lottoRanks);
forEach 내부에서 lottoRanks 지역 변수 컬렉션의 add를 호출하지 않고 Stream을 통해 바로 불변의 결과를 얻도록 구현해보면 어떨까요?

2022-02-11 15:32 UTC, hyunniiii commented on src/main/java/lotto/domain/statistics/Statistics.java
> +        );
`getOrDefault(rank,0)`을 해주는 이유가 결과가 없는 `LottoRank`의 값을 0으로 넣어주기 위해서인 것 같아요. 
view단을 위해서 `First,0`이런식으로 맵을 만들어주는거겠죠?

가독성을 위해서 rankStatistics는 결과가 있는 `LottoRank`값만 반환해주고 view 단에서 처리해주도록 해도 괜찮을 것 같아요.

```java
 return lottoRanks
                .stream()
                .collect(Collectors.groupingBy(Function.identity(), Collectors.summingInt(x -> 1)));
```

이렇게 stream으로 표현이 가능하니 참고부탁드립니다!

2022-02-11 15:32 UTC, hyunniiii commented on src/main/java/lotto/view/InputView.java
> +        System.out.println(INPUT_MANUAL_LOTTO_NUMBERS);
`수동으로 구매할 번호를 넣어주세요.`라는 안내문구가 나오지만 그전에 수동으로 사야할 로또 수를 받는 안내문구가 없는것 같아요.
안내문구를 넣어주세요 ″̮

2022-02-11 15:53 UTC, hyunniiii commented
>수동 로또 리스트와 자동 로또 리스트를 합칠 때 객체 생성 비용을 조금 낭비 하더라도,
합쳐서 새로운 객체를 생성하는 것이 더 자연스럽다고 생각해 그렇게 진행하였습니다. 이에 대한 리뷰어님의 의견도 듣고 싶습니다!

현재 로또 요구사항에서는 수동과 자동을 굳이 나누지 않아도 되니 합치는 것은 괜찮다고 생각합니다. 
다만, 객체 생성 비용이 들지 않도록 리스트를 합친 후 로또 객체를 생성해주는 방법도 있을 것 같아요 ″̮ 

> 또 다른 분들의 코드를 읽어보면 String.format 이나 printf의 포멧을 상수로 빼내었는데, "%d개" 와 같은 간단한 포멧이나. 역할을 설명하기 어려운 포멧을 상수화 하는것이 더 가독성을 해치는 것 같아 리팩토링 하지 않았습니다.
여러곳에서 반복되어 사용되는 포멧이 아니라면 그냥 상수화 하지 않는 편이 나을까요? 이것에 대한 의견도 궁금합니다!

이건 개발을 같이 하는 팀 컨벤션이나 취향에 따라 자유롭게 작성해주시면 될 것 같아요 ″̮

2022-02-12 02:45 UTC, kimtaejun97 commented on src/main/java/lotto/view/InputView.java
> +        System.out.println(INPUT_MANUAL_LOTTO_NUMBERS);
문구를 상수화하면서 지워두고 빈칸으로 두었네요!😅 감사합니다!

2022-02-13 12:08 UTC, kimtaejun97 commented
> > 수동 로또 리스트와 자동 로또 리스트를 합칠 때 객체 생성 비용을 조금 낭비 하더라도,
> > 합쳐서 새로운 객체를 생성하는 것이 더 자연스럽다고 생각해 그렇게 진행하였습니다. 이에 대한 리뷰어님의 의견도 듣고 싶습니다!
> 
> 현재 로또 요구사항에서는 수동과 자동을 굳이 나누지 않아도 되니 합치는 것은 괜찮다고 생각합니다. 다만, 객체 생성 비용이 들지 않도록 리스트를 합친 후 로또 객체를 생성해주는 방법도 있을 것 같아요 ″̮
> 
> > 또 다른 분들의 코드를 읽어보면 String.format 이나 printf의 포멧을 상수로 빼내었는데, "%d개" 와 같은 간단한 포멧이나. 역할을 설명하기 어려운 포멧을 상수화 하는것이 더 가독성을 해치는 것 같아 리팩토링 하지 않았습니다.
> > 여러곳에서 반복되어 사용되는 포멧이 아니라면 그냥 상수화 하지 않는 편이 나을까요? 이것에 대한 의견도 궁금합니다!
> 
> 이건 개발을 같이 하는 팀 컨벤션이나 취향에 따라 자유롭게 작성해주시면 될 것 같아요 ″̮

감사합니다~~ 🙇‍♂️

2022-02-13 12:52 UTC, kimtaejun97 commented on src/main/java/lotto/domain/budget/Budget.java
> +    }
fianl을 제거해가면서 까지 값을 변경했던걸 반성합니다 😓
감사합니다! 불변객체로 변경하였습니다!

2022-02-13 13:47 UTC, kimtaejun97 commented on src/main/java/lotto/domain/lotto/Lottos.java
> +        return new Lottos(lottos);
IntStream을 사용하는 방법이 있었군요! 감사합니다~
ArrayList를 생성해둘 필요 없어 훨씬 나은거같아요

2022-02-13 15:46 UTC, kimtaejun97 commented on src/main/java/lotto/domain/judge/Judge.java
> +        return new LottoRanks(lottoRanks);
`public LottoRanks getRanks(final Lottos lottos) {

        return new LottoRanks(Collections.unmodifiableList(
                lottos.get().stream()
                        .map(this::getRank)
                        .collect(Collectors.toList())));
    }

    private LottoRank getRank(final Lotto lotto) {
        final int matchCount = lotto.matchNumber(correctNumbers.getWinningNumbers());
        final boolean isBonus = lotto.contains(correctNumbers.getBonusNumber());
        
        return LottoRank.getRank(matchCount, isBonus);
    }`

객체 자신의 메서드, 또는 파라미터로 넘어온 객체의 메서드의 호출은 디미터 법칙을 위반하지 않는다고 생각하여
lottos의 메서드가 아닌 lotto를 받아 lotto의 메서드를 호출하는 Judge의 메서드를 위와 같이 구현하였습니다.
이 같은 경우는 디미터 법칙을 위반하지 않을까요?

2022-02-13 16:06 UTC, kimtaejun97 commented on src/main/java/lotto/domain/statistics/Statistics.java
> +        );
네 맞습니다! 해당 부분을 고민할 때 View 단에서 복잡하게 처리하는 것 보다. Map으로 기본값을 초기화해주고 View 단에서는 그저 출력만 할 수 있도록 구현하자고 생각했었습니다.

View 단에서 이에 대한 처리를 하게 되면 LottoRank에 대한 참조를 가지거나, 출력해 주어야 할 각 등수에 대한 정보(당첨금, 매칭수) 를 따로 가지고 있게 될 것 같은데요. 두 방법 모두 좋지 않다고 느껴집니다.
혹시 다른 방법이 있을까요? 😂

2022-02-13 16:08 UTC, kimtaejun97 commented on src/main/java/lotto/domain/statistics/Statistics.java
> +        );
groupingBy 에서 자기 자신을 넣는 방법을 찾고있었는데 Function.identity() 라는게 있군요 ! 많이 알아갑니다! 감사합니다

2022-02-14 15:49 UTC, hyunniiii requested changes
안녕하세요 태준님 ~! 
피드백 반영 잘해주셨습니다! 
불변을 잘 이용해주셨네요. 👍 💯 
마지막 피드백 반영 부탁드립니다 😃

2022-02-14 15:49 UTC, hyunniiii commented on src/main/java/lotto/view/InputView.java
>      }
이 부분에 대한 테스트가 없는 것 같아요 ″̮

2022-02-14 15:49 UTC, hyunniiii commented on src/main/java/lotto/view/PrintView.java
> +        System.out.printf(NUMBER_OF_LOTTO_FORMAT, manualSize, totalSize - manualSize);
`totalSize - manualSize` 는 `Budget`에서도 구할 수 있지 않을까요? 
비즈니스 로직으로도 볼 수 있을 것 같습니다 ″̮

2022-02-14 16:36 UTC, kimtaejun97 commented on src/test/java/lotto/domain/lotto/LottoTest.java
> +        // given
네 제거했습니다 감사합니다!

2022-02-14 16:41 UTC, kimtaejun97 commented on src/main/java/lotto/view/InputView.java
>      }
앗 감사합니다! 추가했습니다!

2022-02-14 17:04 UTC, kimtaejun97 commented on src/main/java/lotto/view/PrintView.java
> +        System.out.printf(NUMBER_OF_LOTTO_FORMAT, manualSize, totalSize - manualSize);
계산을 위한 새로운 메서드를 만드는 것 보다 객체의 생성비용을 조금 더 쓰는 것이 낫다고 생각하여
`budget.deductionPerLotto(manualSize).getNumberOfPurchase()` 와 같이 계산하였습니다.

2022-02-14 17:36 UTC, kimtaejun97 commented on src/main/java/lotto/domain/statistics/Statistics.java
> +        );
List<LottoRank> 에서 모두 포함되게 하려면 아래와 같이 LottoRank를 모두 하나씩 넣어주게 됩니다.

```
List<LottoRank> lottoRanks = lottos.get().stream()
        .map(this::getRank)
        .collect(Collectors.toList());

lottoRanks.addAll(Arrays.asList(LottoRank.values()));

return new LottoRanks(Collections.unmodifiableList(lottoRanks));
```
하지만 포함시키는 과정에서 당첨 등수의 카운트가 1씩 증가하기 때문에 View에서 다시 빼주는 과정이 필요합니다.
이런 과정이 코드를 이해하는데 어려움을 줄 것 같은데요 제가 잘못 이해한 부분이 있을까요? 😅

2022-02-15 07:49 UTC, hyunniiii commented on src/main/java/lotto/domain/statistics/Statistics.java
> +        );
https://github.com/next-step/java-lotto/pull/2282#discussion_r805984417
아 여기는 제가 잘못된 힌트를 남겨드린 것 같네요. 다른 부분이랑 헷갈린 것 같습니다. 죄송합니다 😭 

```java
Arrays.stream(LottoRank.values()).collect(Collectors.toMap(
                i1 -> i1,  i1 -> Collections.frequency(lottoRanks, i1)));
```

이런 방법도 있겠네요 : ) 
조금만 더 고민해보면 개선이 가능할 것 같았어요 😃

2022-02-15 07:51 UTC, hyunniiii approved these changes
안녕하세요 태준님!
로또 미션 진행하시느라 고생 많으셨습니다.
다음 미션도 화이팅입니다.
로또 미션은 머지하겠습니다 😃

2022-02-15 07:52 UTC, merged

2022-02-17 01:29 UTC, kimtaejun97 commented on src/main/java/lotto/domain/statistics/Statistics.java
> +        );
순서를 정렬하기 위해

```
Arrays.stream(LottoRank.values()).collect(Collectors.toMap(
                rank -> rank, rank -> Collections.frequency(lottoRanks, rank), (r1, r2) -> r1,
                LinkedHashMap::new));
```
와 같이 작성하였습니다! stream 공부가 더 필요하겠네요 😓 감사합니다!!