[이호찬] 문자열 덧셈 계산기, 로또 (Step 2)
next-step/java-lotto pull request #2287
Opened 2022-02-16 02:16 UTC by hochan222

---
## 반영 리뷰 사항

- [x] 불필요한 stream 삭제 
  - https://github.com/hochan222/java-lotto/commit/6a182ef038a64584714b77df10168dc8fdb03015
  - https://github.com/hochan222/java-lotto/commit/90ed4ab897e69271ee925018525df53894a9fc4b
- [x] anyMatch 및 메서드 참조 활용하기 
  - https://github.com/hochan222/java-lotto/commit/fa0fbc07864c6921910df104a1ba3160f2f65acb
  - https://github.com/hochan222/java-lotto/commit/0985f7a0dbdbd3d3f2b875b65ac3260447ff0d6e
  
- [ ] 맴버 변수는 this를 사용해 표현해보는 것은 어떨까요?
  
- [ ] String.format 사용해보기
> StringBuilder vs String.format
> - For instance String Builder will be faster, but the code will be much more unreadable, and and it would be easier to make a mistake.
> - On the other hand String.format() produces more readable code at the cost of performance.

가독성에 더 큰 점수를 주어서 String.format을 선택했습니다. 성능에 나중에 문제가 있다면 StringBuilder로의 전환을 고려할 예정입니다.

 ---
 ## 참고 자료
 
 - https://stackoverflow.com/questions/44117788/performance-between-string-format-and-stringbuilder

2022-02-18 13:38 UTC, joswlv requested changes
안녕하세요 호찬님!
1단계에서 구조를 잘 잡으셔서 쉽게 수동로또기능을 추가할 수 있었던 것 같습니다.
몇 가지 코멘트를 남겼습니다.
확인 부탁드립니다. 🙇

2022-02-18 13:38 UTC, joswlv commented on src/main/java/lotto/domain/LottoTicketGenerator.java
>          validatePrice(price.getValue());
Price생성시 체크하면 더 깔끔한 코드가 될 수 있을 것 같습니다.

2022-02-18 13:38 UTC, joswlv commented on src/main/java/lotto/controller/LottoMachine.java
> +        final LottoTicket lottoTicket = purchaseLotto(purchaseAmount(), purchaseManualLotto());
구매 액션을 담당하는 객체로 구매행위를 분리해 보면 어떨까요?
구매행위는 자동 로또 구입, 수동 로또 구입이 있겠네요

2022-02-18 13:38 UTC, joswlv commented on src/main/java/lotto/view/InputView.java
> +    public static int readInt() {
`readInt()`를 private로 변경하고 의미를 명확하게 `manualLottoGameCount()`, `purchasingPrice()`와 같이 표현해보는 것은 어떨까요?

개인 취향이지만 다음과 같이 수동로또 숫자를 리턴하는 대신 수동로또 List를 리턴하게 표현할 수 있습니다. 

```java
  private Optional<List<String[]>> manualLottoGameNumbers(Integer manualLottoGameCount) {
    return Optional.of(queryAndManualNumberToLimit(PLEASE_INPUT_MANUAL_NUMBER, manualLottoGameCount));
  }

  private List<String[]> queryAndManualNumberToLimit(String query, Integer limit) {
    if (limit <= ZERO) {
      return Collections.EMPTY_LIST;
    }
    System.out.println(query);
    return Stream.iterate(ZERO, integer -> integer + INC)
        .limit(limit)
        .map(integer -> splitByComa(SCANNER.nextLine()))
        .collect(Collectors.toList());
  }
```

2022-02-22 09:30 UTC, hochan222 reviewed
리뷰 주셔서 감사합니다.

좋은 하루 보내세요 :)

2022-02-22 09:30 UTC, hochan222 commented on src/main/java/lotto/view/InputView.java
> +    public static int readInt() {
- https://github.com/next-step/java-lotto/pull/2287/commits/307a5b865cf4a6a7788d9966d065c56a166fb5f9

inputView에 순수한 scanner에 대한 로직이 있어야 책임 분리가 잘 된다고 생각했었습니다.

주신 피드백을 보고, 바꿔보았는데 lottoMachine에서 for문이 사라지는것을보았고, 가독성 측면에서도 훨씬 좋아보여서 좋은 생각이라는 결론을 내렸습니다. 감사합니다.

2022-02-22 09:30 UTC, hochan222 commented on src/main/java/lotto/controller/LottoMachine.java
> +        final LottoTicket lottoTicket = purchaseLotto(purchaseAmount(), purchaseManualLotto());
**문제 인식**

purchaseLotto 메소드가 purchaseManualLotto 메소드를 인자로 받는것은 부자연스러워 보입니다. 뿐만아니라 auto, manual 에 따른 행위 분리가 명확하지 않습니다.

```
purchaseLotto(purchaseAmount(), purchaseManualLotto());
```

**해결 과정**

원래 계획은

```
public interface PurchaseLottoStrategy {

    public LottoTicket purchaseLotto(int price);
}

public class PurchaseAutoLotto implements PurchaseLottoStrategy {
...
}

public class PurchaseManualLotto implements PurchaseLottoStrategy {
...
}
```

이렇게 분리하는것이였지만(Override), purchaseLotto의 매개변수가 일정하지 못해서 이 방법의 경우 다른 메서드로 구현해야함을 알았습니다.

따라서 기존 코드도

```
public void run() {
        final LottoTicket lottoTicket = purchaseLotto(purchaseAmount(), purchaseManualLotto());
        final LottoStatistics lottoStatistics = calculateWinningResult(lottoTicket);

        printResult(lottoStatistics);
}
```

객체로 나눌때, 최선의 변경이
 1. 각각 공통점 없는 PurchaseManualLotto, PurchaseAutoLotto를 구현하거나
 2. (행위 분리 불가)  PurchaseManualLotto 객체안에서 PurchaseAutoLotto의 생성자를 호출하는 형식으로 구현하는 것이라고 생각합니다. (+ InputView는 controller에서만 호출되게 구현해야하기에)

```
public void run() {
        final LottoTicket lottoTicket = PurchaseManualLotto.purchaseLotto(purchaseAmount(), purchaseManualLotto());
        final LottoStatistics lottoStatistics = calculateWinningResult(lottoTicket);

        printResult(lottoStatistics);
}
```

이는 리뷰 주신 방향과는 조금 거리가 있는 반영이라고 생각해서 슬랙드렸습니다.

어떤 방향으로 코드를 작성하면 좋을지 힌트를 조금 더 주실 수 있으신가요?

감사합니다.

2022-03-02 14:46 UTC, joswlv requested changes
안녕하세요 호찬님!
몇 가지 리뷰를 남겼습니다.
확인 부탁드립니다.

2022-04-04 06:08 UTC, closed without merging