[박효정] 문자열 덧셈 계산기, 로또 (Step 2)
next-step/java-lotto pull request #2289
Opened 2022-02-19 15:59 UTC by judy5050

안녕하세요! 선호 리뷰어님 😊

1단계 머지해주시면서 말씀하신 부분들 중 lottoPlayTest 부분을 제외하고 반영했습니다.
lottoPlayTest를 구현하지 못한 이유는 수동로또를 만들면서 lottoTicket 클래스의 makeRandomLottoTickets, makeManualLottoTickets라는 메서드안에서 랜덤로또 및 수동로또를 만드는 메서드를 호출하기 때문이라는 생각이 드는데 어떤 방향으로 변경해야할 지 잘 떠오르지 않아, 선호 리뷰어님의 조언을 구하고자 합니다.
어떻게 하면 랜덤, 수동로또 클래스를 유연하게 테스트할 수 있는 코드로 변경할 수 있을지 방향성이 궁금합니다. 🧐

이번 step2 리뷰또한 잘 부탁드립니다. 😊

2022-02-20 13:08 UTC, vsh123 requested changes
효정님 안녕하세요!
로또 2단계 구현잘해주셨네요 :)

몇가지 코멘트를 남겼으니 확인부탁드리겠습니다!

2022-02-20 13:08 UTC, vsh123 commented on src/main/java/lotto/domain/LottoTickets.java
> +    }
두개의 생성자에서 수동로또를 생성하는 부분말고는 모두 공통된 로직인 것 같은데요!

두개의 생성자에서 공통된 로직을 하나로 모으면 어떨까요?

2022-02-20 13:08 UTC, vsh123 commented on src/main/java/lotto/controller/LottoController.java
> +            lottoPlay.run(new LottoMachine(inputView.getWinNumbers(), inputView.getBonusNumber()));
`inputView.getManualLottoNumbers(purchaseManualLottoNumber)`는 `List<List<Integer>>를 리턴하고
`inputView.getWinNumbers()`는  `List<LottoNumber>`를 리턴하고 
`inputView.getBonusNumber()`는 `int` 리턴해주는데요!

같은 로또 넘버를 받는 로직인데, 리턴값이 어떤 것은 Integer, 어떤 것은 LottoNumber인게 이상해보여요! 하나로 통일해보면 어떨까요?

2022-02-20 13:08 UTC, vsh123 commented on src/main/java/lotto/domain/LottoPlay.java
> +    public LottoPlay(final int totalPrice, final int manualLottoNumber,
> 1단계 머지해주시면서 말씀하신 부분들 중 lottoPlayTest 부분을 제외하고 반영했습니다.
lottoPlayTest를 구현하지 못한 이유는 수동로또를 만들면서 lottoTicket 클래스의 makeRandomLottoTickets, makeManualLottoTickets라는 메서드안에서 랜덤로또 및 수동로또를 만드는 메서드를 호출하기 때문이라는 생각이 드는데 어떤 방향으로 변경해야할 지 잘 떠오르지 않아, 선호 리뷰어님의 조언을 구하고자 합니다.
어떻게 하면 랜덤, 수동로또 클래스를 유연하게 테스트할 수 있는 코드로 변경할 수 있을지 방향성이 궁금합니다. 🧐

이부분이군요!!
결국 자동로또 생성이 들어간 부분이 있는 곳은 테스트가 불가능하게 되는데요! 해당 클래스를 제외한 모든 도메인클래스에서 최대한 많은 테스트를 할 수 있도록 구조를 잘 짜주신 것 같아요 :) 만약 LottoPlay를 테스트하고 싶다면 AutoLottoGenerator를 LottoController에서 핸들링하면 될 것 같은데요! 요 부분은 효정님의 선택에 따라 해주시거나, 지금 그대로 냅두어도 괜찮아보여요~ :)

[참고](https://bperhaps.tistory.com/entry/%EB%9E%9C%EB%8D%A4%EC%97%90-%EB%8C%80%ED%95%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%9D%B4%EB%A3%A8%EC%96%B4-%EC%A0%B8%EC%95%BC-%ED%95%98%EB%8A%94%EA%B0%80)

2022-02-21 14:37 UTC, judy5050 commented on src/main/java/lotto/controller/LottoController.java
> +            lottoPlay.run(new LottoMachine(inputView.getWinNumbers(), inputView.getBonusNumber()));
LottoNumber이라는 객체로 한번 감싸 반환하도록 수정했습니다. 😊

2022-02-21 15:46 UTC, judy5050 commented on src/main/java/lotto/domain/LottoTickets.java
> +                new Lotto(new ManualLottoGenerator(line).getLottoGeneratorNumbers()));
추가했습니다~

2022-02-21 15:51 UTC, judy5050 commented on src/main/java/lotto/domain/ManualLottoGenerator.java
> +        this.lottoNumbers = line.stream().limit(COUNT).sorted()
저는 클래스 간 의존성이 생겨서 별도의 상수로 만든다는 생각이 드는데, 
저의 생각이 맞을까요?

2022-02-21 15:52 UTC, judy5050 commented on src/main/java/lotto/domain/LottoTickets.java
> +        final List<List<Integer>> manualLine) {
string 값이 한 문장으로 들어오기 때문에 Line이라는 네이밍을 하게 되었고
수동 로또다보니.. manualLine을 추가하게 된 거 같습니다. 😁

2022-04-04 06:08 UTC, closed without merging