java-lotto mission step 3
next-step/java-lotto pull request #2302
Opened 2022-04-20 06:00 UTC by DahamLeee

안녕하세요 지훈님!

벌써 로또 미션의 반을 진행했습니다~! 매번 좋은 피드백 감사드립니다!

이번 미션을 진행하면서 궁금한 점이 생겨서 코드 리뷰와 함께 질문을 해봅니다!

- Rank enum의 findRank에서 2등과 3등의 matchCount가 5로 동일하기 때문에 if문을 통해 3등을 얼리 리턴시킨 후에 스트림을 타도록 했습니다~! 혹시 if문을 사용하지 않고 스트림만으로 1등부터 꼴등까지 한 번에 처리할 수 있는 방법이 있을까요?? 
- [461ba3f](https://github.com/next-step/java-lotto/commit/461ba3f354679d93c3bc8eec972f7782c0ccb412) 보너스 번호 일치 여부를 구하는 기능에서 실패하는 테스트 -> 성공하는 테스트 -> 리팩토링의 작업을 하기 위해서 public static boolean으로 구현하였습니다~! 그런데 등수를 구하는 findRank 메소드를 LottoMachine 내부에서 사용중이기 때문에 public으로 선언하지 않고 private을 사용해도 되는데 이렇게 되면 테스트를 할 수 없게 됩니다 ㅠㅠ
- 이런 상황에서 isMatchedBonusNumber 메소드를 private으로 바꾼 이후에 public 메소드를 통해 private으로 바꾼 메소드를 테스트해야 하는 것이 바람직한가요?? 아니면 그대로 public을 유지하는 것이 바람직한가요??

감사합니다~!

2022-04-21 04:48 UTC, vagabond95 commented
public / private 접근 제한자는 테스트 만을 위해 바뀌어서는 안된다고 생각해요!

https://www.slipp.net/questions/253
위 글에서 많은 힌트를 얻으실 수 있을 것 같습니다 :)

2022-04-21 04:49 UTC, vagabond95 requested changes
큰 구조 변경 없이 3단계도 잘 마무리해주셨네요 👍 

질문 주신 내용 및 구현 내용에 대한 코멘트 남기었는데요, 확인 후 리뷰요청 부탁드리겠습니다!

2022-04-21 04:49 UTC, vagabond95 commented on src/main/java/lotto/Rank.java
> +        if (matchCount == 5 && !matchBonus) {
enum 필드에서 '보너스 번호를 체크해야하는지' 에 대한 필드를 가지면, 특정 등수에 대한 if 문을 제거할 수 있지 않을까요? ㅎㅎ

2022-04-21 06:05 UTC, DahamLeee commented
안녕하세용~! 지훈님!

좋은 정보 공유해주셔서 감사드립니다~~

리팩토링 한 내용을 말씀드리면 다음과 같습니다.

1. 어제 온라인 강의 중에 재성님께서 접근 제어자를 적극 활용하라고 하셔서 클래스 내부에서 사용되지만 테스트 코드는 있어야 안심이 되었기 때문에 질문한 메서드에 default 접근 제어자를 붙여 봤습니다.
2. 피드백 주신 내용대로 2등 이외에는 보너스 번호와 일치하던지 말던지 상관 없기 때문에 "보너스 번호 일치 여부"에 관한 필드를 추가해줬습니다. 또한 당첨 번호와 보유한 번호의 일치 개수가 5개일 경우 보너스 번호가 있는지 확인하고, 그 이외에는 일치 여부와 상관 없이 다 false를 사용했습니다.
3. 1, 2번대로 리팩토링 하다가 어제 온라인 강의에서 getter를 지양하는 쪽으로 생각을 해보고 바꿔보라고 말씀해주셔서 LottoMachine에서 Lotto에 있는 리스트를 get해서 match하던 메서드를 Lotto에게 질문을 던지는 형식으로 리팩토링 해보니 질문드린 메서드가 Lotto로 들어가서 테스트를 하기 좋은 모습과 함께 역할과 책임이 명확한 구조로 바뀐 거 같습니다~!

좋은 정보와 좋은 아이디어 감사드립니다~!

2022-04-22 04:47 UTC, vagabond95 approved these changes
default 접근 제한자도 사용빈도가 많지는 않지만, 잘 사용하면 꽤나 유용하죠 :)

피드백 의도대로 잘 수정해주셔서 3단계도 머지하도록 하겠습니다~!

2022-04-22 04:47 UTC, merged