Step2 리뷰요청드립니다.
next-step/java-lotto pull request #2326
Opened 2022-04-24 13:03 UTC by itdar

안녕하세요 지훈님!~
로또 2단계 리뷰요청 드립니다.
예전에 했었는데도 다시하니 새롭고 그러네요..ㅎㅎ
클라이언트(메인) -> 컨트롤러 -> 서비스 -> 도메인
레이어로 구분하려다가, 서비스는 불필요할 것 같아서 제외했습니다.
감사합니다!!

2022-04-25 09:23 UTC, vagabond95 requested changes
적절하게 레이어 단계를 선택해주셨네요 👍 

구조적으로는 크게 피드백 드릴 부분이 없을 만큼 깔끔하게 잘 짜주셨네요!
세부적인 구현내용에서 일부 코멘트를 남겼는데요, 확인 후 리뷰요청 부탁드리겠습니다!

2022-04-25 09:23 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoResult.java
> +    public static final int REWARD_FIRST_GRADE = 2000000000;
```suggestion
    public static final int REWARD_FIRST_GRADE = 2_000_000_000;
```
하이픈을 활용하면 가독성을 좀 더 살릴 수 있습니다 ㅎㅎ

2022-04-25 09:23 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoResult.java
> +    private static Map<Integer, Grade> gradeMap = new HashMap<>();
등수를 찾기 위해 gradeMap 을 따로 두기보다 Grade enum 의 values() 메소드를 활용해 보는 것은 어떨까요?

2022-04-25 09:23 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoTicket.java
> +    private static final List<Integer> allLottoNumbers = new ArrayList<>();
로또 번호 캐싱 👍

2022-04-25 09:23 UTC, vagabond95 commented on src/main/java/lotto/view/CommandlineUserInterface.java
> +        System.out.println("3개 일치 (5000원)-" + lottoResults.countOf(3) + "개");
특정 등수에 의존하지 않고 결과값을 표현해보는 것이 가능할까요?

현재 구조에서는 등수가 추가될때마다 코드에 변경사항이 발생하는 구조일 것 같아요!

2022-04-25 15:31 UTC, itdar commented on src/main/java/lotto/view/CommandlineUserInterface.java
> +        System.out.println("3개 일치 (5000원)-" + lottoResults.countOf(3) + "개");
각 등수마다 몇개 맞아야 하는지에 대한 것이 변경될 수 있을 것 같아서 매직넘버로 넣어두긴 했었는데요
음.. 한번 수정을 해보겠습니다~!

2022-04-26 03:06 UTC, vagabond95 approved these changes
피드백 의도대로 잘 수정해주셨네요 👍 

2단계는 머지하도록 하겠습니다!

2022-04-26 03:06 UTC, vagabond95 commented on src/main/java/lotto/view/CommandlineUserInterface.java
> +        for (Grade grade : grades) {
등수가 추가되더라도 View 에서는 더이상 변경사항이 발생하지 않겠네요 👍

2022-04-26 03:06 UTC, merged