Step1. 문자열 계산기 PR.
next-step/java-lotto pull request #2334
Opened 2022-04-25 16:35 UTC by Wu22e

안녕하세요. 이번 로또미션을 수행할 김형우 라고 합니다!
앞으로 잘 부탁드립니다~!

문자열 계산기 리뷰 요청 드립니다!

2022-04-26 16:03 UTC, orgojy requested changes
안녕하세요~! 형우님 만나 뵙게 되어서 반갑습니다.
"로또"를 함께할 안이민이라고 합니다. 😄 
몇 가지 코멘트를 남겨드렸습니다. 고민하시고, 다시 요청을 부탁드릴게요.
궁금하신 점이나 같이 생각해볼 부분이 있으시면, 코멘트나 DM을 주셔서 같이 고민해보면 좋겠습니다.
좋은 밤되세요!

2022-04-27 04:52 UTC, Wu22e commented on src/main/java/calculator/Calculator.java
> +public enum Calculator {
이민님이 말씀해주신 것처럼 Operator에 더 가깝다고 생각합니다! 
해당 클래스는 `연산자` 클래스 책임으로, 하나의 표현식 (피연산자, 연산자, 피연산자) 에 대한 처리를 맡고있기 때문에 
`계산기` 클래스 보다는 `연산자` 클래스가 맞는 것 같습니다.
해당 부분은 수정하도록 하겠습니다!

2022-04-27 04:54 UTC, Wu22e commented on src/main/java/calculator/Calculator.java
> +    public int calculate(int a, int b) {
해당 부분은 `연산자` 클래스로 봤을때, 하나의 표현식에 대한 `계산`을 한다 라고 생각했습니다!
이 부분에 대해서는 계산`기`라고 생각하지는 않았던 것 같습니다.
`calculate`, `operate`, `calculation`, `operation` 정도로 이름을 정할 수 있을 것 같은데 어떻게 생각하시나요?

2022-04-27 17:26 UTC, Wu22e commented on src/main/java/calculator/Calculator.java
> +        return BY_OPERATOR.get(operator);
valueOfOpeartor가 단 한번의 연산 `O(1)`으로 값을 return 해주기 위해 클래스변수에 Map을 통해 미리 캐싱을 하였습니다.
해당 방법으로 FP 방식을 사용하게 된다면 valueOfOperator가 호출될때마다 연산자의 위치를 찾는 최소 1번 최대 4번 거치지 않을까 라는 생각이 드네요. `O(N)`

2022-04-29 13:21 UTC, orgojy commented
형우님 재요청을 안해주셔서 혹시 까먹고 놓치신건지 싶어서 코멘트 남깁니다! 😄 
아직 반영이 덜 된건가요?

2022-04-29 17:39 UTC, orgojy commented on src/main/java/calculator/Calculator.java
> +    public int calculate(int a, int b) {
이 부분 제가 놓쳤네요. 늦게 나마 코멘트 드립니다! 🙇 
네 충분히 시도해보실 수 있는 부분이라고 생각합니다.
답을 정해두고 리뷰를 드리는 것은 아니기 때문에 시도해보시는 것도 과정이라고 생각하구요.
명시 해주신 calculate, operate, calculation, operation 는 제가 리뷰 과정에서 살펴보겠습니다.

2022-04-29 17:41 UTC, orgojy commented on src/main/java/calculator/Calculator.java
> +        return BY_OPERATOR.get(operator);
네 말씀이 맞습니다. 👍 
FP 방식을 하나 소개시켜드리려는 목적이었습니다.

2022-04-29 18:18 UTC, orgojy approved these changes
안녕하세요. 형우님! 😄 
코멘트 드렸던 부분을 잘 이해하시고 개선도 잘해보셨네요.
개선 과정에서 생각되었던 부분에 대해서 코멘트 추가도 남겨드렸구요.
다음 미션에서 반영해주시면 됩니다.
먼저 코멘트에서 제가 답변하지 않았던 부분도 추가로 답변 드렸습니다.
참고 부탁드릴게요.
다음 미션을 위해서 PR은 머지하도록 하겠습니다.
즐거운 주말되세요~! 다음 미션에서 뵙겠습니다. 👍

2022-04-29 18:18 UTC, orgojy commented on src/main/java/calculator/Operand.java
> +public class Operand {
잘 구현해주셨습니다. 👍

2022-04-29 18:18 UTC, orgojy commented on src/main/java/calculator/SplitString.java
> +    private static final String BLANK_DELIMITER = " ";
클래스 정적 상수와 생성자는 줄바꿈으로 구분해주면 가독성이 좋아집니다.
보통 컨벤션으로 인스턴스 필드와도 줄바꿈으로 구분하는 방식으로 표현을 합니다.
공유드립니다. 😄 
```suggestion
    private static final String BLANK_DELIMITER = " ";
    
```

2022-04-29 18:18 UTC, orgojy commented on src/main/java/calculator/StringCalculator.java
> +    private static final int FIRST_OPERAND_INDEX = 0;
클래스 정적 상수와 생성자는 줄바꿈으로 구분해주면 가독성이 좋아집니다.
보통 컨벤션으로 인스턴스 필드와도 줄바꿈으로 구분하는 방식으로 표현을 합니다.
공유드립니다. 😄
```suggestion
    private static final int FIRST_OPERAND_INDEX = 0;
    
```

2022-04-29 18:18 UTC, orgojy commented on src/main/java/calculator/StringCalculator.java
> +        for (int index = 1; index < elements.size(); index += 2) {
index에 사용된 `1`과 `2`에 대해서도 매직 넘버로 보이는데요.
정적 상수로 가독성을 높여보면 좋을것 같습니다. 😄 
15라인에 있는 `1`도 마찬가지 입니다.

2022-04-29 18:18 UTC, orgojy commented on src/main/java/calculator/StringCalculator.java
> +        Operand resultValue = new Operand(elements.get(FIRST_OPERAND_INDEX));
👍

2022-04-29 18:18 UTC, orgojy commented on src/test/java/calculator/SplitStringTest.java
> +    }
👍

2022-04-29 18:19 UTC, merged