Step2 - 로또(자동)
next-step/java-lotto pull request #2347
Opened 2022-04-28 18:26 UTC by kang-jisu

안녕하세요 재석님 !! 2단계 로또 미션 진행해보았습니다! ☺️

1단계 문자열 계산기에서 일급 컬렉션을 사용하면서 복잡해진 부분은 다시 고쳐보려고 했는데 변경 방법이 잘 안떠올라서 일단 보류하고 로또 미션 먼저 구현했습니다 😢 미션 진행하면서 계속 고민해보겠습니답!!

일단은 최대한 요구사항에 맞게 돌아가기만이라도 하는걸 목표로 구현했습니다! ㅠㅠ 부족한 부분은 리뷰 후에 다시 보완해보도록 하겠습니다🔥
이번 리뷰도 잘 부탁드리겠습니다!! 🙇‍♀️

2022-04-29 00:06 UTC, seok-2-o requested changes
로또 미션도 잘 진행해주셨어요 👍 
잘해주셨지만 몇가지 고민거리 남겨드렸으니 확인 후 리팩토링해보면 좋을 것 같아요.
행복한 금요일 되시길 바라요.

2022-04-29 00:06 UTC, seok-2-o commented on src/main/java/lotto/view/StatisticsResultView.java
> +    }
수익율을 구하는 로직은 비교적 간단하지만, 이번 수업 목적에 맞게 도메인영역에서 계산이 이뤄지는 것은 어떤가요?

2022-04-29 00:06 UTC, seok-2-o commented on src/main/java/lotto/model/Money.java
> +    public static final Money MONEY_BASE = new Money(1000);
로또의 개당 가격은 금액보다 로또 스토어나 로또에서 관리하는게 더 좋아보이는데 지수님 생각은 어떤가요?

2022-04-29 00:06 UTC, seok-2-o commented on src/main/java/lotto/dto/WinnerLottos.java
> +public class WinnerLottos {
현재는 Lottos와 완전히 동일한 속성을 가지는데 한번 더 랩핑 해주신 이유가 있으신가요?

2022-04-29 00:06 UTC, seok-2-o commented on src/main/java/lotto/model/Lottos.java
> +    public Lottos(List<Integer> lottos) {
로또 마켓을 통해서만 생성되긴 하지만 46 의 번호로도 로또를 생성할 수 있는 것 같아요.
이를 방지하기 위해선 어떻게 할 수 있을까요?

2022-04-29 00:06 UTC, seok-2-o commented on src/main/java/lotto/model/Lottos.java
> +    private final List<Integer> lottos;
중복되지 않는 자료형을 다루는 더 나은 자료구조는 없을까요?

2022-04-29 00:06 UTC, seok-2-o commented on src/main/java/lotto/model/RandomLottoGenerator.java
> +        List<Integer> numbers = new LinkedList<>();
매번 새로운 리스트를 생성할 필요가 있을까요?

2022-04-29 00:06 UTC, seok-2-o commented on src/main/java/lotto/model/RandomLottoGenerator.java
> +        List<Integer> numbers = new LinkedList<>();
LinkedList 를 사용하신 이유가 궁금합니다.

2022-04-29 15:00 UTC, kang-jisu commented on src/main/java/lotto/view/StatisticsResultView.java
> +    }
아하 넵! 도메인 영역에서 최대한 기능을 구현하고, View에서는 정말 출력만 하도록 변경해보겠습니다!!

2022-04-29 15:02 UTC, kang-jisu commented on src/main/java/lotto/model/Money.java
> +    public static final Money MONEY_BASE = new Money(1000);
아아 그러네요!! Money라는 클래스는 가격을 나타내는 역할만을 하도록 하고, 로또 관련 클래스에서 필요한 가격에 대한 값을 Money를 활용해 사용하는게 맞겠네요!! 감사합니다 😊

2022-04-29 15:04 UTC, kang-jisu commented on src/main/java/lotto/dto/WinnerLottos.java
> +public class WinnerLottos {
이부분에 대해서는 String 입력값을 받아서 Lottos로 변환해주는 DTO라는 생각으로 구현을 해보았는데, 지금보니 DTO를 의미하는건지 불필요하게 중복된 클래스가 만들어진건지 저도 구분이 안되네요 😢 제가 처음에 클래스를 만들때 의도한 대로 DTO로 사용할 수 있는지 조금 더 고민해보고 의견 남기겠습니다!!

2022-04-29 15:06 UTC, kang-jisu commented on src/main/java/lotto/model/Lottos.java
> +    public Lottos(List<Integer> lottos) {
아아 !  로또 번호에 대해서 그냥 Integer를 사용하는것이 아니라 확실히 1~45 범위의 숫자값만 가지도록 래퍼 클래스를 생성해 사용해보겠습니다!!

2022-04-29 15:09 UTC, kang-jisu commented on src/main/java/lotto/model/Lottos.java
> +    private final List<Integer> lottos;
단순히 숫자를 담는다는 생각만 했는데 `Set`을 사용하면 실제로 중복값이 존재하지 않으면서, 명시적으로도 나타낼 수 있겠네요 ! 변경해보겠습니다!!

2022-04-29 15:15 UTC, kang-jisu commented on src/main/java/lotto/model/RandomLottoGenerator.java
> +        List<Integer> numbers = new LinkedList<>();
처음에 전역으로 리스트를 선언했다가, 로또 번호를 추출함에 따라 계속 리스트의 값이 변경(remove할때마다 하나씩 삭제됨) 되어서 매번 새로운 리스트를 생성하며 초기화해보았는데 지금 보니 문제 해결을 잘못 한 것 같네요 😢
1~45값을 넣어둔 리스트를 전역으로 하나 만들고, 로또 번호 생성시에 전역 리스트는 변경 없이 무작위 추출 로또 번호를 6개 얻어내는 방식으로 다시 구현해보겠습니다!

2022-05-01 04:02 UTC, kang-jisu commented
안녕하세요 리뷰어님!!☺️

저번 리뷰 참고해서 다시 리팩토링 해보았습니다!
역할에 맞게 불변 클래스, 일급 컬렉션을 생성해보았고 로또 생성 로직을 변경하고 input, result를 위한 DTO를 최대한 입,출력과 Lotto관계에서 값을 전달해주는 역할만 하도록 변경해보았습니다! 감사합니다 ㅎㅎ

> LottoResult DTO 사용에 대해 조금 설명하자면, 
`Lottos.getLottoStatistics` 에서는 로또 당첨 번호와의 matchCount를 계산해 저장할만한 Rank값(3,4,5,6)에 대해서만 임시 Map에 담고 
이를 LottoResult DTO로 변환해서 Main에 돌려주는 방식으로 구현해보았습니다.!
이 때 mathCount가 3,4,5,6 인 순으로 LottoResult의 rankResult가 정렬되어야 출력할 때 편할 것 같아서 TreeMap으로 사용하고 3,4,5,6중 빈 값은 `LottoResult.fillRankDefault` 메서드로 0(default value)로 채워주었습니다.!
이 부분이 뭔가 복잡하게 된 것 같아서 걱정이네요 ㅎㅎ ㅠㅠ 

다시 한번 리뷰 잘 부탁드리겠습니다!🙇‍♀️

2022-05-01 07:33 UTC, seok-2-o requested changes
피드백 반영 잘해주셨네요 👍 

바로 다음 미션으로 넘어가도 될 만큼 잘해주셨지만 
값 객체에 대해서 조금 더 피드백 드리고 싶은게 있어 코멘트로 남겨두었어요

확인 후 고민해보시면 좋겠네요.

즐거운 주말 되시길 바라요.

2022-05-01 07:33 UTC, seok-2-o commented on src/main/java/lotto/controller/LottoMarket.java
> +public class LottoMarket {
Lottos 에서도 수행 가능한 일인데, LottoMarket 을 통해서 할 필요가 있을까요?
지금 구조가 나쁘거나 잘못된 것은 아니고 궁금해서 여쭤봅니다 ~

2022-05-01 07:33 UTC, seok-2-o commented on src/main/java/lotto/dto/LottoResult.java
> +    private final Map<Rank, Integer> rankResult;
`List<Rank> ` 로 표현하는것이 Map 보다 간결하다고 생각하는데 어떻게 생각하세요?

2022-05-01 07:33 UTC, seok-2-o commented on src/main/java/lotto/dto/LottoResult.java
> +    private final Map<Rank, Integer> rankResult;
리스트를 순회하는것이 누계(accumulate)를 구하는것보다 조금 더 직관적이지 않을까 해서 여쭤봅니다.

2022-05-01 07:33 UTC, seok-2-o commented on src/main/java/lotto/model/Lotto.java
> +    public int getMatchCount(Lotto result) {
Set 에서 제공하는 retainAll 메소드를 이용하면 어떤가요?

2022-05-01 07:33 UTC, seok-2-o commented on src/main/java/lotto/model/LottoNumber.java
> +public class LottoNumber {
로또 번호와 같은 값 객체의 경우 객체를 재사용하기 좋은데요.

정적 팩토리 메소드의 장점 중 하나인 객체 재사용을 적용할 수 있을 것 같아요.

```java
public static Integer valueOf(int i) {
        if (i >= IntegerCache.low && i <= IntegerCache.high)
            return IntegerCache.cache[i + (-IntegerCache.low)];
        return new Integer(i);
}
```

위 코드인 Integer.valueOf 구현을 보면 특정 값은 Cache하여 사용하는 것을 볼 수 있어요.
플라이웨이트 패턴 키워드로 검색하시면 도움이 되실 것 같아요

2022-05-01 07:33 UTC, seok-2-o commented on src/main/java/lotto/model/Lottos.java
> +        return new LottoResult(lottoStatistics, winningsSum);
getWinningsSum 은 LottoResult가 구할 수 있지 않을까요?

winningsSum 의미가 뭔지는 조금 햇갈리네요

2022-05-01 07:33 UTC, seok-2-o commented on src/main/java/lotto/model/RandomLottoGenerator.java
> +        return new LinkedHashSet<>(LOTTO_NUMBERS.subList(0, LOTTO_SIZE));
정렬은 출력에서만 필요 할 것 같은데 LinkedHashSet을 사용할 필요가 있을까요?

2022-05-02 07:02 UTC, kang-jisu commented on src/main/java/lotto/controller/LottoMarket.java
> +public class LottoMarket {
입력 받은 구매 가격을 가지고 로또를 몇개 구매할지 판단하는 책임을 LottoMarket이 가지도록 설계했었습니다!! 
다만 구매 개수에 따라서 로또를 생성하는 부분은 Lottos가 하는게 맞을 것 같습니다!! 조금 수정해보겠습니다!!

2022-05-02 07:42 UTC, kang-jisu commented on src/main/java/lotto/model/Lotto.java
> +    public int getMatchCount(Lotto result) {
오! 이런 메소드가 있었군요 🤩 감사합니다 활용해보겠습니다!!

2022-05-03 07:02 UTC, kang-jisu commented on src/main/java/lotto/model/Lottos.java
> +        return new LottoResult(lottoStatistics, winningsSum);
그렇네요,,! LottoResult에서 Rank 결과를 가지고 계산하는 방식으로 변경해보겠습니다!
수익률을 계산하는데 있어서 총 합이 필요할 것이라 생각했는데, 수익률 계산 메서드 내부에서 Sum을 구하고 따로 변수로 저장하지 않아도 될 것 같네요!! 수정해보겠습니다!!

2022-05-03 07:11 UTC, kang-jisu commented on src/main/java/lotto/model/RandomLottoGenerator.java
> +        return new LinkedHashSet<>(LOTTO_NUMBERS.subList(0, LOTTO_SIZE));
이전 구현에서 로또 번호를 하나씩 뽑아오는 순서를 지켜보려고 LinkedHashSet을 사용했었는데, 이전 구현에서도 , 6개를 한번에 가져오는 지금도 로또 번호 자체에 순서 유지가 필요 없는 것 같네요..!! 단순 HashSet으로 변경하겠습니다!

2022-05-03 08:13 UTC, kang-jisu commented on src/main/java/lotto/model/LottoNumber.java
> +public class LottoNumber {
오오 넵! 미리 객체를 생성해놓고 캐시하는 방법 사용해보도록 하겠습니다! 감사합니다 👍

2022-05-03 08:29 UTC, kang-jisu commented
안녕하세요 리뷰어님!! 피드백 바탕으로 코드 수정해보았습니다 😄 

LottoMarket에서 이전에 구현했던 것 처럼 유틸클래스로 사용하며 여러 정적 팩토리 메소드를 구현하기 전에 로또 구매, 생성과 같은 책임이 다른 곳(ex: Lottos) 에 있지는 않은지 더 고민을 해봐야겠습니다!! 다만 이번에는 구매 금액에 대한 처리는 LottoMarket에서 하는게 어떨까 싶어서 모두 Lottos로 넘기지 않고 남겨두었습니다!!

로또 당첨 결과를 List<Rank>로 저장 하고 출력하는 ResutView에서만 따로 처리를 해주는 것으로 변경해보았는데, 3,4,5,6에 대해 당첨 개수가 0인 경우 default 처리를 하는 부분은 어떻게 해야 가장 적절한 방법일지 조금 어렵네요.. ㅎㅎ ㅠㅠ 

그리고 말씀해주신 캐시 방식으로 LottoNumber의 1~45 값을 미리 생성해놓고, new LottoNumber(숫자)가 아닌 정적 팩토리 메소드로만 미리 생성된 객체를 가져오도록 변경해보았습니다! 
> Integer클래스도 new Integer는 deprecated된 것 같아서 new LottoNumber(숫자) 생성자는 private로 변경해 추가로 생성할 수 없도로 만들어보았습니다!

이번에도 다시 한번 잘 부탁드리겠습니다! 👍

2022-05-03 12:20 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨어요 👍 

마지막으로 소소한 피드백 남겨두었으니 다음 미션과 함께 고민해보면 좋을 것 같아요.

이어서 다음 미션 진행하시죠 🔥

2022-05-03 12:20 UTC, seok-2-o commented on src/main/java/lotto/model/Rank.java
> +    FIRST(6, 2_000_000_000),
Money 객체를 사용하기로 했다면 winings 도 Money 로 만들어주면 어떤 장점이 있을까요?

2022-05-03 12:20 UTC, seok-2-o commented on src/main/java/lotto/model/Money.java
> +    public double getYield(long result) {
get- 보다 더 적합한 메소드 명은 없을까요 ?

2022-05-03 12:20 UTC, seok-2-o commented on src/main/java/lotto/model/Lottos.java
> +                .collect(Collectors.toList()));
```suggestion
        this(Stream.generate(lottoGenerator::get)
                .limit(count)
                .collect(toList()));
```

2022-05-03 12:20 UTC, merged

2022-05-04 10:51 UTC, kang-jisu commented on src/main/java/lotto/model/Rank.java
> +    FIRST(6, 2_000_000_000),
Money로 만들면서 음수값 조건 처리나, Money라는 의미를 명시하는데도 장점이 있을 것 같습니다!! Money 객체로 사용해보겠습니다!! 🧐

2022-05-04 10:58 UTC, kang-jisu commented on src/main/java/lotto/model/Money.java
> +    public double getYield(long result) {
음.. 구현에서 수식 계산이 있다는 것, 수익률을 얻어낸다는 의미를 좀 더 나타내도록 `calculateYieldFrom` 과 같이 변경해보려고 합니다!!

2022-05-04 11:01 UTC, kang-jisu commented on src/main/java/lotto/model/Lottos.java
> +                .collect(Collectors.toList()));
오 감사합니다! Stream.generate에 대해서 더 알아보겠습니다!!

2022-05-04 11:44 UTC, kang-jisu commented on src/main/java/lotto/model/Money.java
> +    public double getYield(long result) {
뭔가 Yield라는 값이 아닌, A라는 money를 인자로 받은 B로 나누는 메서드를 Money에서 만들고 그걸 LottoResult에서는 수익률 계산을 위해 쓰는 것이 둘의 의존성을 줄이는 것 같아서 
this로 쓰는 기준객체를 앞에 두고, 분모 Money로 나누는 메서드로 변경하겠습니다!
```java
    public double divideBy(Money denominator) {
        return this.money / (double) denominator.money;
    }
```