[devgony] step2 lotto auto
next-step/java-lotto pull request #2361
Opened 2022-05-01 02:07 UTC by devgony

## Step2: Lotto auto

### Requirements

- 로또 구입 금액을 입력
    - [x] LotteryController 통해 전체 로직 관리
    - [x] LotteryController.money = InputView.scan
- 로또 1장의 가격은 1000원, money로 살 수 있는 로또 개수 연산
    - [x] LotteryController.numberOfLotterys = money / 1000
- 로또 객체 생성
    - [x] Lottery Class with box[45], numbers[6]
    - [x] Lottery.numbers 는 Collections.shuffle() 로 생성
- numberOfLotteries 만큼 Lottery class 생성
    - [x] for 1..numberOfLotteries: new Lottery()
    - [x] Collections.sort() 로 정렬해서 보관
- 자동으로 생성 된 로또 번호들을 출력
    - [x] ResultView.toString(lotto)
    - [x] ResultView.printLotteries
- 정답 번호를 입력
    - [x] LotteryController.answerNumbers = LotteryController.parse(InputView.scan)
- 정답 번호와 비교하여 win 횟수 세기
    - [x] for lotto of lotteries: lotto == answer ? cnt++ : null
    - [x] 비교는 ArrayList.contains() 활용
    - [x] WinStatistics Class 생성하여 3,4,5,6 field 에 save
- 당첨 통계 출력
    - [x] WinStatistics.toPayload 에서 출력할 문구 생성
    - [x] ResultView.printResult 에서 해당 문구를 출력
- 총 당첨 금액 계산
    - [x] winStatistics.getEarnedMoney
- 수익률 계산
    - [x] winStatistics.getEarningRate
- 수익률 출력
    - [x] ResultView.printEarningRate

### Result output

```
Put your money.
14000
14 lotteries are purchased.
[1, 5, 14, 17, 40, 44]
[2, 3, 11, 19, 30, 39]
[2, 9, 15, 23, 38, 43]
[6, 10, 15, 18, 32, 34]
[17, 18, 30, 31, 33, 41]
[3, 4, 6, 8, 16, 35]
[5, 6, 7, 10, 27, 33]
[2, 9, 24, 29, 33, 43]
[3, 12, 20, 23, 27, 35]
[1, 6, 7, 10, 42, 45]
[5, 11, 12, 16, 26, 30]
[6, 9, 13, 23, 29, 35]
[7, 15, 21, 24, 34, 44]
[7, 12, 18, 20, 25, 33]
Put lottery answer.
7, 12, 18, 24, 34, 44
Win Statistics
------------------
3 matches (₩5000): 1
4 matches (₩50000): 1
5 matches (₩1500000): 0
6 matches (₩2000000000): 0

Earning rate: 3.9285714285714284
```

2022-05-01 02:17 UTC, devgony reviewed
Step 2로 다시 찾아 뵙게 되었습니다.
이번에도 잘 부탁드립니다!
구현하면서 궁금했던 부분 코드 아래에 코멘트로 질문 드립니다!

2022-05-01 02:17 UTC, devgony commented on src/main/java/lotto/Lottery.java
> +    public final static List<Integer> box = IntStream.rangeClosed(1,45).boxed().collect(Collectors.toList());
1부터 45까지의 정수를 생성하는게 생각보다 번거로웠습니다.. 더 나은 방법이 있는지 궁금합니다.

2022-05-01 02:17 UTC, devgony commented on src/main/java/lotto/LotteryController.java
> +        this.answerNumbers = parseAnswerNumbers(scanned);
값을 멤버 변수에 저장하는 void 메소드와
다음 단계를 위해 값을 return 하는 메소드 두 개 를 섞어서 사용하고 있는데
어느 방법이 더 나은지 궁금합니다.
전 단계에서 클래스 내 멤버변수를 줄이는게 좋다고 하셨는데.. 그런면에서는 모두 메소드로 처리하는 함수형 구현이 더 나을것같기도합니다.

2022-05-01 02:17 UTC, devgony commented on src/main/java/lotto/LotteryController.java
> +    public void findWins() {
이 메소드 역시 void 로 내부에서 처리를 하는 메소드이다보니 테스트가 어려웠습니다. 테스트를 위해서는 값을 리턴하는 함수로 바꾸는게 좋을까요? 아니면 loop 내에 있는 findWin은 테스트를 했으니 생략해도 괜찮을까요?

2022-05-01 10:43 UTC, yongdae requested changes
안녕하세요. 형관님 ~ :)
주말에도 열심히 미션을 수행해주셨네요. 👍 

진행해주신 내용에 대해 리뷰를 진행하였습니다.

추가로 [이전 단계에서 드린 의견](https://github.com/next-step/java-lotto/pull/2310)은 아직 반영되어 있지 않은 것 같아요.
이 부분도 같이 확인 부탁드릴께요!

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/Lottery.java
> +    public final static List<Integer> box = IntStream.rangeClosed(1,45).boxed().collect(Collectors.toList());
이미 잘 만들어주셨다고 생각요!
더 나은 방법은 생각나지 않네요. 😅 

다만 로또 번호를 생성하는 부분은 별개의 객체로 분리해보면 어떨까요?

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +        this.answerNumbers = parseAnswerNumbers(scanned);
값을 멤버 변수에 저장하는 부분은 45 라인인 것 같은데
다음 단계를 위해 값을 return하는 메소드를 두 개 섞어서 사용한다는 부분은 어느 내용인지 잘 모르겠어요.

2번째 케이스를 어디인지 이야기해주시면 확인한 후에 답변드리도록 하겠습니다.

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +    public void findWins() {
테스트를 하는게 맞다고 생각해요.
내부적으로 처리하는 findWin은 lotteries을 따라 가변적으로 실행되기 때문에 결과가 달라지기 때문입니다.

일단 이 부분은 지금 설계에서는 반환하는 형태로 하는게 좋다고 생각합니다. :)

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/LotteryApp.java
> +    public static void main(String[] args) {
<img width="1039" alt="스크린샷 2022-05-01 오후 7 15 28" src="https://user-images.githubusercontent.com/4317804/166141631-e3f46a1c-c88c-40d7-a359-ac1b17269eed.png">

미션과 같이 득실 여부를 출력해보면 좋겠어요. :)

<img width="568" alt="스크린샷 2022-05-01 오후 7 16 35" src="https://user-images.githubusercontent.com/4317804/166141652-cd92fe4c-504f-4d3e-8166-288ae8ab2882.png">

2022-05-01 10:43 UTC, yongdae commented on src/test/java/lotto/LotteryTest.java
> +    void create45NumbersInBox() {
로또 번호는 1부터 45까지 중복되지 않는 숫자를 가지고 있는데
지금은 `중복`이라는 부분에 대해서는 검증되지 않은 것 같아요.

중복되지 않은 1 ~ 45의 숫자만 가지고 있다는 부분을 검증 해 볼 수 있는 방법은 없을까요?

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +            lotteries.add(new Lottery());
구매 할 수 있는 로또 갯수만큼 Lottery(로또 번호 생성과 로또 번호들)를 만들기보다는
로또 번호를 만들어내는 부분은 별개의 객체로 분리해서 Lottery에 전달하는 형태로 변경해보면 어떨까요?

[질의 주신 부분](https://github.com/next-step/java-lotto/pull/2361/files#r862413840)에 대한 부분과도 연관되어 있다고 생각해요.

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +    private double earningRate;
`규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.`
여기는 이 규칙을 적용해보면 좋을 것 같아요.

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +    }
1000은 상수로 선언해서 사용해보면 어떨까요?

2022-05-01 10:43 UTC, yongdae commented on src/test/java/lotto/MoneyTest.java
> +public class MoneyTest {
MoneyTest에 `로또는 장당 1000원으로 구매 할 수 있다`에 대한 테스트를 추가해보면 어떨까요?

<img width="847" alt="스크린샷 2022-05-01 오후 7 36 45" src="https://user-images.githubusercontent.com/4317804/166142241-64be9d0d-d10f-4c41-bbdb-dcc5ac5c1862.png">

LottoControllerTest를 보면 LottoController가 많은 책임을 가지고 있다는 생각도 들고
지금 `로또 구매`에 대한 테스트는 결국 Money를 사용하고 있어요.

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/WinStatistics.java
> +    private final static Map<Integer, Integer> rewordMap = new HashMap(Map.of(3, 5000, 4, 50000, 5, 1500000, 6, 2000000000));
로또 당첨 등급을 Map 대신 Enum을 사용해서 정의해보면 어떨까요?

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/Money.java
> +        if (price < 1000) {
1000을 상수로 선언해서 사용해보면 좋을 것 같아요.

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +        }
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

여기는 이 규칙을 적용해볼 수 있겠네요. :)

2022-05-01 10:43 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +        for (String s : split) {
변수명을 축약해서 사용하지 않으면 좋겠어요.

2022-05-02 04:11 UTC, devgony commented on src/main/java/lotto/LotteryController.java
> +        this.answerNumbers = parseAnswerNumbers(scanned);
https://github.com/next-step/java-lotto/blob/d4270391070ae6e2f231081378e4ca795c876fec/src/main/java/lotto/LotteryController.java#L49

2022-05-02 04:46 UTC, devgony commented on src/main/java/lotto/LotteryController.java
> +            lotteries.add(new Lottery());
음.. 이부분은 그때마다 box(1~45)를 생성하는게 비효율적이라 생각해서 static 으로 선선한 변수였는데 분리를하지않으니 모호한 부분이 있으셨겠군요.. 분리해서 참조하도록 하겠습니다

2022-05-03 14:26 UTC, devgony reviewed
리뷰 주신 내용들을 아래와 같이 반영하고 3개의 질문을 드렸습니다.
이번에도 잘 부탁 드립니다!

- [x] 1~45 box 생성 별도 분리
- [x] 로또 번호 생성 부분 별도 객체 분리해서 Lottery 에 전달
- [x] findWins를 반환 형태로 변환하여 테스트
  - 테스트는 작성하였으나 반환형태가 아닌 인스턴스 변수활용 
- [x] 적자, 흑자 여부 출력
- [x] 로또 번호가 중복되지 않는 유일한 45개의 수인지 테스트 추가
- [x] 1000은 const 선언
- [x] MoneyTest에 로또는 장당 1000원으로 구매 할 수 있다에 대한 테스트를 추가
- [x] 로또 당첨 등급을 Map 대신 Enum을 사용해서 정의
- [x] 2단 indent 제거
- [x] 축약된 변수명 제거
- [x] Controller포함 모든 Class의 3개 이하로 인스턴스 변수 줄이기
- [x] 1단계 string_calculator 추가 수정
  - [x] 연산(계산식)도 BiFunction을 활용해서 Operator Enum이 가지게 적용
  - [x] 상수와 멤버 변수의 선언 순서 변경
  - [x] Interface Value 제거 
  - [x] Class Integer 제거
  - [x] step1: 규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
- [x] step2: 규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

2022-05-03 14:26 UTC, devgony commented on src/main/java/string_calculator/Parser.java
> +    public List<Object> values = new ArrayList();
Integer를 없애다보니 파싱한 결과(int, Operator) values에 담기 위해 List<Object> 가 되어버렸습니다.
이렇게 사용해도 괜찮을까요?

2022-05-03 14:26 UTC, devgony commented on src/main/java/string_calculator/Operator.java
> +    MODULO("%", (acc, operand) -> acc % operand);
가이드 주신대로 BiFunction을 두번째 인자로 가지게 해보았는데.. 바로 선언하니 조금 지저분한 것 같습니다.
다른곳에서 이름을 가진 람다로 선언하고 여기서는 그 이름만 사용할수도 있을까요? 시도해봤더니 선언보다 사용이 먼저 라서 그런지 "illegal forward reference" 에러가 났습니다.

2022-05-03 14:26 UTC, devgony commented on src/main/java/lotto/LotteryApp.java
> +        lotteryController.findWins(lotteryController.scanAnswer());
멤버변수를 2개 이하로 줄일려다 보니 스캔받은 값은 바로 전달하는 식으로 적게 되어버렸습니다.
APP에서는 로직에 맞게 차례대로 실행만 하는 형태로 정렬을 하고싶었는데.. 좀더 좋은 방법이 없을까요?

2022-05-04 04:44 UTC, yongdae approved these changes
형관님! 열심히 의견 드린 부분을 반영해주셨네요. 💯 
수고하셨습니다.

고민도 많이 하시고 열심히 질문해주셔서 재미있게 리뷰를 진행하고 있네요. :)

이번 단계는 여기서 마무리하고 다음 단계로 넘어가도록 하겠습니다.
의견을 남겨 놓은 부분은 다음 단계에서 같이 반영 부탁드리도록 하겠습니다. 🙇

2022-05-04 04:44 UTC, yongdae commented on src/test/java/lotto/WalletTest.java
> +    Wallet wallet = new Wallet(14000);
Wallet을 공용으로 사용하지 않고 @Test 마다 개별로 선언해서 사용하면 어떨까요?
더 정확히는 [Given - When - Then](https://brunch.co.kr/@springboot/292)을 적용해보면 좋겠어요.

2022-05-04 04:44 UTC, yongdae commented on src/main/java/lotto/Wallet.java
> +    public int money;
money를 객체로 포장해보면 어떨까요?
그리고 `돈`을 표현한 객체가 수익률 계산을 할 수 있다면 돈과 관련 된 책임을 높일 수 있을 것 같아요.

2022-05-04 04:44 UTC, yongdae commented on src/main/java/lotto/Reward.java
> +    public int value;
value 대신 money 같은 변수명이 더 좋을 것 같아요. :)

2022-05-04 04:44 UTC, yongdae commented on src/main/java/lotto/Reward.java
> +    Reward(int win) {
`상금` 외에도 `당첨 번호 갯수`를 포함하게 한다면 더 좋지 않을까요?

2022-05-04 04:44 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +    public void findWins(Answer answer) {
Answer를 사용해야 할 이유를 잘 모르겠어요.
Answer 대신 Lottery를 사용해보면 어떨까요?

2022-05-04 04:44 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +        if (answerNumbers.contains(number)) {
직접 로또 번호를 가지고 판별하는게 아니라
Lottery를 사용해서 당첨 갯수를 판별할 수 있게 만드는게 좋을 것 같아요! :)

2022-05-04 04:44 UTC, yongdae commented on src/main/java/lotto/LotteryController.java
> +            saveWin(win);
saveWin(win) 부분을 뺄 수는 없을까요?
메서드 이름은 findWins인데 당첨된 로또를 찾으면서 동시에 통계도 저장하고 있어요.

2022-05-04 04:44 UTC, yongdae commented on src/main/java/lotto/Lottery.java
> +    }
shuffleBox()과 findSixNumbers()를 LotteryBox에서 하게 바꾼다면
조금 더 `로또 번호 생성`에 대한 책임을 완전히 LotteryBox에게 넘길 수 있지 않을까요?

2022-05-04 04:44 UTC, yongdae commented on src/main/java/lotto/LotteryApp.java
> +    public static void main(String[] args) {
<img width="356" alt="스크린샷 2022-05-04 오후 1 39 10" src="https://user-images.githubusercontent.com/4317804/166623825-25adc41c-e4f4-4dce-8f49-ff2f6873d150.png">

실행 결과를 보니 피드백을 잘 반영해주셨네요. 👍

2022-05-04 04:44 UTC, merged

2022-05-04 05:19 UTC, devgony commented on README.md
> +Earning rate: Infinity
이제서야 확인했는데 rate 출력에 문제가 있군요.. 반올림 처리를 해야겠어요!