2단계 - 로또(자동)
next-step/java-lotto pull request #2377
Opened 2022-05-02 16:50 UTC by rumor1993

안녕하세요 준보님!

제가 작업 간에 깃을 잘못 사용해서 기능 단위별로 커밋을 찍어야했는데
어쩌다 보니 못해서 전체로 해서 올리게 되었습니다

리뷰 하시는데 조금 불편하실거 같아서 미리 사과드립니다..ㅎㅎ;

2022-05-02 19:21 UTC, simjunbo requested changes
본격적인 로또 미션이 시작 되었네요!
2단계 로또 미션 진행 하시느라 수고하셨습니다 👏 👏 👏 

몇가지 리뷰 남겨 놓았으니 확인해 보시고 재요청 부탁드립니다.
객체의 역할에 대해서도 좀 더 고민해 보시면 좋을 것 같습니다!

미션 진행 하시면서 궁금하신 부분이나 논의해보고 싶은 부분이 있다면
편하게 코멘트나 DM 남겨 주시기 바랍니다.

화이팅 입니다 ❗❗❗

2022-05-02 19:21 UTC, simjunbo commented on src/main/java/lotto/domain/Numbers.java
> +        Collections.sort(lottoNumbers);
참고만 하세요.

```
        this.lottoNumbers = numbers.stream()
                .limit(6)
                .sorted()
                .collect(Collectors.toList());
```
이런식으로 stream을 이용하면 한번에 처리도 가능합니다 😄 

그리고 로또 번호에 대한 생성 부분을 별도 클래스로 분리해도 좋을 것 같네요.
ex) LottoGenerator ?

2022-05-02 19:21 UTC, simjunbo commented on src/main/java/lotto/domain/Numbers.java
> +    public Numbers(List<Integer> numbers) {
방어적 복사를 사용하면 좀 더 간단하게 구현할 수 있습니다.

참고) https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/

2022-05-02 19:21 UTC, simjunbo commented on src/main/java/lotto/domain/Revenue.java
> +        lotto1st = findByRanking(lottos, 6);
enum으로 처리해 볼 순 없을까요 ?! 🤔

2022-05-05 02:51 UTC, rumor1993 commented on src/main/java/lotto/Main.java
> +        for (int i = 0; i < price / 1000; i++) {
넵!! 좀 더 역할이 명확해지도록 수정하겠습니다

2022-05-05 02:51 UTC, rumor1993 commented on src/main/java/lotto/Main.java
> +        List<Integer> prevLottoNumbers = inputView.findPrevLottoNumbers();
넵!

2022-05-05 02:57 UTC, rumor1993 commented on src/main/java/lotto/contoller/InputView.java
> +        for (String number : value.split(", ")) {
넵 stream을 사용하니 먼가 더 보기가 편하네요!

2022-05-05 02:58 UTC, rumor1993 commented on src/main/java/lotto/contoller/ResultView.java
> +public class ResultView {
음.. 단순히 결과를 출력해주는 역할만을 해야하는 것 같은데
제가 짠 부분에서는 출력을 여기저기서 하고 또 출력값을 생성자에 받을 필요가 없었던거 같은데 그렇게 처리한거 같아요 ㅠ

2022-05-05 03:00 UTC, rumor1993 commented on src/main/java/lotto/domain/Numbers.java
> +        for (int i = 1; i <= 45; i++) {
매직넘버를 상수로 변경해보겠습니다

2022-05-05 03:02 UTC, rumor1993 commented on src/main/java/lotto/domain/Customer.java
> +    public Customer(int money) {
구매자가 가지고 있는 금액은 money
로또의 가격은 price
로 정의했었는데 소스를 확인해보니 price가 money가 되고 실수를 한 부분들이 있어서 
수정하겠습니다!

2022-05-05 03:48 UTC, rumor1993 commented on src/main/java/lotto/domain/Customer.java
> +public class Customer {
일급 컬렉터로 변경해보겠씁니다

2022-05-05 04:15 UTC, rumor1993 commented on src/main/java/lotto/domain/Numbers.java
> +    private final List<Integer> numbers = new ArrayList<>();
그런 부분을 고려하지 못한거 같습니다!
그러면 해당 부분은 지역변수로 선안해서 사용하는게 더 좋을까요?

2022-05-05 04:17 UTC, rumor1993 commented on src/main/java/lotto/domain/Revenue.java
> +    public String toString() {
아! 지금까지... toString을 목적에 맞지 않게 사용을 했던거 같습니다
감사합니다!

2022-05-05 12:18 UTC, simjunbo commented on src/main/java/lotto/domain/Numbers.java
> +    private final List<Integer> numbers = new ArrayList<>();
@rumor1993 저는 내부에서만 사용되기 때문에 지역 변수로 사용해도 될것 같습니다 😄

2022-05-08 17:51 UTC, simjunbo approved these changes
피드백 반영하시느라 수고 많으셨습니다. 

몇 가지 추가적인 의견 드렸으니 다음 단계 진행 시, 참고 하시기 바라며
이번 2단계 로또 미션은 머지하도록 하겠습니다.
다음 3단계 미션도 화이팅 입니다 ❗❗❗

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/Main.java
> +//        ResultView resultView = new ResultView(new Revenue(lists, price));
불필요한 주석은 삭제 하는게 좋을 것 같습니다 😄 

참고) https://velog.io/@kwj1270/%ED%81%B4%EB%A6%B0%EC%BD%94%EB%93%9C-%EC%A3%BC%EC%84%9D

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/contoller/ResultView.java
> +    public ResultView() {
기본 생성자를 별도 선언해 주신 이유가 있을까요 ?! 🤔

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/contoller/InputView.java
> +                .map(number -> Integer.parseInt(number))
Arrays.strema 형태로 잘 반영해 주셨네요 👍 

```suggestion
                .map(Integer::parseInt) 
```
메소드 레퍼런스 형태로도 사용해 볼 수 있겠네요 😄

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/contoller/ResultView.java
> +        System.out.println(" 당첨 통계 ");
System.out.println 은 생각보다 성능에 좋지 않습니다.
해당 메시지를 하나로 묶어서 한꺼번에 처리할 수 있는 방법은 없을까요 ? 🤔

참고) https://donggov.tistory.com/53

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/domain/Customer.java
> +        this.totalAmount = 14000;
값들이 하드코딩 되어 있는것 같은데
의도하신 생성자가 맞는것인지 확인 부탁드립니다.

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/domain/Lotto.java
> +    private int price;
price가 현재 사용되고 있지 않는것 같습니다.

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/domain/Lottos.java
> +                .forEach(System.out::println);
출력을 담당하는것은 ResultView의 역할인것 같은데
lottos 의 값을 넘겨서 처리해 보는것은 어떨까요?!

그리고 일반적으로 stream().forEach 는 성능이 좋지 않습니다.
단순 반복일 경우 lottos.forEach 형태로 사용하시기 바랍니다. 😄 

참고) https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
당첨에 대한 정보를 enum으로 멋지게 도출해 주셨군요 👍

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/domain/Rank.java
> +    TWO(5, 1500000),
앞에서 피드백 드린대로 java7 부터는 숫자에 언더스코어(_)를 사용할 수 있습니다.
천 단위에 끊어서 사용해 보시면 좀더 가독성이 올라 갈 것 같네요 😄 

참고) https://madplay.github.io/post/underscores-in-numeric-literals

2022-05-08 17:51 UTC, simjunbo commented on src/main/java/lotto/domain/Numbers.java
> +    public int matchCount(List<Integer> winningNumbers) {
참고만 해주세요.
저는 개인적으로 생성자 밑에 정적 메소드, 그 다음 기본 메소드, 그 다음에 오버로딩 메소드 순으로 사용하는것을 선호 하는데
리뷰이님도 공통의 규칙을 정해보시면 좀 더 통일성 있게 사용할 수 있을 것 같습니다.

참고) https://stackoverflow.com/questions/4668218/are-there-any-java-method-ordering-conventions

2022-05-08 17:51 UTC, merged

2022-05-10 16:10 UTC, rumor1993 commented on src/main/java/lotto/domain/Revenue.java
> +        lotto1st = findByRanking(lottos, 6);
넵! 해당부분은 Rank enum으로 변경했습니다!

2022-05-10 16:12 UTC, rumor1993 commented on src/main/java/lotto/Main.java
> +//        ResultView resultView = new ResultView(new Revenue(lists, price));
넵 제거하겠습니다!

2022-05-10 16:14 UTC, rumor1993 commented on src/main/java/lotto/contoller/ResultView.java
> +    public ResultView() {
생성자를 추가하려다 필요가 없어졌는데 지우지 못한거 같습니다...ㅎㅎ

2022-05-10 16:16 UTC, rumor1993 commented on src/main/java/lotto/contoller/InputView.java
> +                .map(number -> Integer.parseInt(number))
이런걸 메서드 레퍼런스라고 하는군요!

2022-05-10 16:22 UTC, rumor1993 commented on src/main/java/lotto/contoller/ResultView.java
> +        System.out.println(" 당첨 통계 ");
멀티쓰레드 환경이 아니라고 판단하여서 StringBuilder를 사용해서 처리해보았습니다!

2022-05-10 16:24 UTC, rumor1993 commented on src/main/java/lotto/domain/Lotto.java
> +    private int price;
넵!

2022-05-10 16:27 UTC, rumor1993 commented on src/main/java/lotto/domain/Lottos.java
> +                .forEach(System.out::println);
아.. 무조건 스트림을 사용하는건 지양해야겠네요! 
상황에 맞는 메서드를 사용하도록 노력하겠습니다

2022-05-10 16:34 UTC, rumor1993 commented on src/main/java/lotto/domain/Rank.java
> +    TWO(5, 1500000),
확실히 가독성이 올라가네요!

2022-05-10 16:35 UTC, rumor1993 commented on src/main/java/lotto/domain/Numbers.java
> +    public int matchCount(List<Integer> winningNumbers) {
무언가 공통의 규칙을 만들어 보도록 하겟습니다!