Step3 - 로또(2등)
next-step/java-lotto pull request #2401
Opened 2022-05-06 08:22 UTC by kang-jisu

안녕하세요 리뷰어님 ! ☺️ 
3단계 보너스 번호를 이용한 로또 2등 계산 미션 구현해보았습니다!!

수요일 진행된 강의에서 클래스의 변수나 메서드 파라미터가 2개 이하가 되도록 리팩토링하라는 부분이 있어서, 당첨 번호와 보너스 번호를 저장하는 WinnerLotto 클래스로 분리해보았습니다!
당첨 번호를 가지고 있는 클래스에서 등수를 계산하는 책임이 있어야 할 것 같아 Lotto의 getRank를 winnerLotto로 옮겨보았습니다!!

그리고 이전에 Set의 `retainAll`메서드가 입력값과의 교집합을 계산하며 Set내부 값 자체를 변경하고 있길래 교집합을 계산할 Set을 복사한 뒤 사용하는 방식으로 변경했습니다. -> `Lotto`의 `getMatchCount, intersectionBy 메서드`

추가로 구현하면서 조금 궁금했던 점 질문드립니다!
- Enum 값에 대한 테스트
Enum은 equals말고 `==`로 비교해도 되는것으로( ==비교를 권장하는 것으로 ? ) 알고있는데, 테스트를 할 때 isEqualTo를 이용하는 방식과 isTrue를 이용하는 방식중 어떤걸 사용하는게 좋을지 궁금합니다! 개인적으로는 isEqualTo가 코드를 읽을 때 잘 들어와서 선호하는 편인데, `==`비교를 하는것이 Enum을 더 잘 활용하는 방식인가 싶어서요! 아니면 `boolean isSame(Rank)`같은 메서드를 만들고 그 결과가 True/False 인지 테스트 한다면 더 좋은 방식이 될까요? 
```java
assertThat(rank).isEqualTo(Rank.FIRST);  
```

```java
assertThat(rank == Rank.FIRST).isTrue();
``` 

보너스 번호 로직이 좀 헷갈려서 중간에 헤맸네요.. 😢 커밋 내용들이 뒤죽박죽인 점 양해부탁드립니다 ㅠㅠ 
이번 리뷰도 잘 부탁드리겠습니다!! ㅎㅎ 🙇‍♀️

2022-05-06 08:51 UTC, seok-2-o requested changes
이미 전 단계에서 구조가 탄탄하게 잡혀있어 어렵지 않게 2등을 구할 수 있었네요
좋은 코드의 장점이라고 생각합니다.

질문하신 부분은 단언문 에서는 비교하지 않도록 하는 것이 테스트에 유리하다고 생각합니다.

관련하여 블로그하나 첨부하니 확인 부탁드릴께요.
[단언문 (expect/assert) 안에서 비교하지 않기](https://jojoldu.tistory.com/663)

그외에도 몇가지 코멘트 남겨드렸으니 확인 후 리펙토링 진행해주세요.

2022-05-06 08:51 UTC, seok-2-o commented on src/main/java/lotto/model/Lotto.java
> +    }
구지 나눠야 할 메소드일지 고민이 되네요.
나누신 이유가 있으실까요?

2022-05-06 08:51 UTC, seok-2-o commented on src/main/java/lotto/model/Rank.java
> +    public static List<Rank> reverseValues() {
출력을 위한 메소드를 정의할 필요가 있을까요?

2022-05-06 08:51 UTC, seok-2-o commented on src/main/java/lotto/model/Rank.java
> +        }
해당 로직이 제거되어도 목적하는데로 동작할것 같은데 어떻게 생각하시나요?

2022-05-06 08:51 UTC, seok-2-o commented on src/main/java/lotto/model/Money.java
>      }
왜 스태틱 메소드로 만드셨는지 궁금합니다.

2022-05-06 08:51 UTC, seok-2-o commented on src/main/java/lotto/model/Lottos.java
> +    public LottoResult getLottoResult(WinnerLotto winnerLotto) {
get 은 getter 와 햇갈리는 이름이라고 생각하는데 더 좋은 접두어를 고민해보는것은 어떤가요 ?

2022-05-06 08:51 UTC, seok-2-o commented on src/main/java/lotto/model/Lottos.java
> +        return new LottoResult(getLottoStatistics(winnerLotto));
바이패스하는 메소드가 필요할까요 ?
`.collect(collectingAndThen(toList(), LottoResult::new));`

2022-05-06 15:42 UTC, kang-jisu commented on src/main/java/lotto/model/Lotto.java
> +    }
음.. 이부분은 저도 제일 마지막에 혹시 이것도 분리해야할까!하고 수정해보았는데요, 
getMatchCount가 set의 size를 가져오는것이고, intersectionBy가 Set의 교집합을 구한다. 하는 의미로 나누어보긴했는데
결국 Set(또는 어떤 컬렉션)을 생성해서 size를 구해야 matchCount라는 값을 가져올 수 있는거고 메서드를 분리하면서 unmodifiableSet으로 전달해주거나 좀 복잡해보이는 과정이 생기는 것 같기도하네요..!! 어쩌면 메서드를 분리하는데 메서드 이름도 좀 애매해서 더 이해하기 복잡해진 것 같기도 하구요 ㅠㅠ 
이 부분은 하나로 다시 합치는 것이 좋을 것 같습니다!

2022-05-06 16:15 UTC, kang-jisu commented on src/main/java/lotto/model/Rank.java
> +    public static List<Rank> reverseValues() {
아아..! 그러네요 출력 형식이 바뀌면 또 Rank에 선언한 이 메서드 구현이 달라져야할 수도 있고, 출력을 할 필요가 없다면 Rank에서 괜한 메서드를 static으로 선언한게 되는 것 같습니다.!! 실제로 사용할 ResultView 클래스에서 그대로 사용하고 해당 메서드는 지우도록하겠습니다!

2022-05-06 16:49 UTC, kang-jisu commented on src/main/java/lotto/model/Rank.java
> +        }
아 ! 제가 이부분이 좀 헷갈려서 SECOND를 분리했었는데, 말씀해주신대로 이 조건문을 제거하고 아래 stream filter에 추가로 수정할 수 있겠네요! 테스트코드로 Rank 등수마다 잘 반환되는 것 확인해서 사용할 수 있을 것 같습니다!! 다시 변경해보겠습니다 ☺️

2022-05-07 02:49 UTC, kang-jisu commented on src/main/java/lotto/model/Money.java
>      }
```java
// Integer.java
    public static int sum(int a, int b) {
        return a + b;
    }
```
일단은 Integer 클래스의 sum을 참고해서 만들기도 하고, reduce의 인자가 BinaryOperator라고 나와있어서 두개 인자를 받게 만들게되면 인스턴스 변수가 필요하지 않은 것 같아서 static으로 만들었습니다!
그런데 static 이 아니라 그냥 하나의 인자만 받아서 this.money랑 덧셈을 해도 stream reduce에서 수행이되네요..!!
static 메서드가 아닌 일반 메서드를 사용하는게 좋을까요? 두개중에 어떻게 구현할지를 고르는 기준을 아직은 잘 모르겠습니다!! ㅠㅠ 
뭔가 add라는 메서드가 인자 두개를 더해서 결과를 반환해 새로운 Money를 생성하게 되니까, 인스턴스 선언 없이 사용할 수 있는 static 유틸 메서드처럼 쓸 수 있지 않을까 했는데, A.add(B)나 add(A,B)나 A,B 두개가 필요한 건 똑같으니 굳이 static을 안사용하는게 더 좋은 것 같기도하네요..! 😣

2022-05-07 03:13 UTC, kang-jisu commented on src/main/java/lotto/model/Lottos.java
> +        return new LottoResult(getLottoStatistics(winnerLotto));
아! `collectingAndThen` 메서드 사용할 수 있군요 🥺 감사합니다!! 사용이 아직 익숙하지 않아서 불필요한 전달 메서드를 생성해버리네요,, 수정하고 다른 곳에서도 계속 적용해보려구 하겠습니다!!ㅎㅎ

2022-05-07 03:26 UTC, kang-jisu commented on src/main/java/lotto/model/Lottos.java
> +    public LottoResult getLottoResult(WinnerLotto winnerLotto) {
아!! 넵 ! 제가 그냥 getter가 아닌 것들도 거의 모든 메서드를 getXX 네이밍으로 사용하고 있던 것 같네요.!! 실제로 getter더라도 getXX로 사용하지 않는게 좋겠지만요!!
최대한 getter가 아닌 메서드들부터라도 그 의미를 더 나타내도록 다른 접두어를 사용해보겠습니다! 혹시 수정한 부분에서 더 추천할만한 이름이 있다면 제안해주시면 감사하겠습니다 😖

2022-05-07 03:36 UTC, kang-jisu commented
안녕하세요 리뷰어님! ☺️
피드백 해주신 부분 변경해보았습니다!!
먼저 링크주신 단언문에서 비교하지 않기에 대한 내용을 보니 제가 궁금했던 부분이 한번에 해결되기도 하고, 앞으로 테스트 코드를 짤 때도 주의할 부분인 것 같아서 너무 도움이됐습니다!! 감사합니다 😭👍

뭔가 클래스를 설계하고 기능을 구현하는 것 만큼이나 이번 피드백 주신 부분들을 고민하는게 오히려 더 어렵기도 한 것 같습니다.. ㅎㅎ 나름대로 고민해보고 변경해보았는데 보시고 다시 가감없이 피드백 주시면 감사하겠습니다 😁

리뷰 잘 부탁드리겠습니다! 좋은 주말 보내세요 감사합니다!! 🚀

2022-05-07 05:45 UTC, seok-2-o commented on src/main/java/lotto/model/Money.java
>      }
static method 로 만들지 않으면 아래와 같은 연산도 가능합니다.
소소한 방법이지만 은근히 쓸모 있는 패턴이니 알아두면 좋으실 것 같아요.

```java
public Money add(Money other) {
if(other.money == 0) {
   return this;
}
return new Money(this.money + other.money)
}
```

2022-05-07 05:45 UTC, seok-2-o commented on src/main/java/lotto/model/Lottos.java
> +    public LottoResult getLottoResult(WinnerLotto winnerLotto) {
어떤 단어를 추천해드리긴 어려운 부분이고 상황에 맞는 동사를 잘 선택해보면 좋을 것 같아요 💯

2022-05-07 05:48 UTC, seok-2-o approved these changes
피드백 반영잘해주셨네요 👍 
이전 코멘트에 소소한 첨언 남겨두었으니 확인 부탁드릴게요.
이어서 다음 미션진행해주세요.

지수님도 행복한 주말 보내시길 바라요. 😄

2022-05-07 05:48 UTC, merged

2022-05-07 05:57 UTC, kang-jisu commented on src/main/java/lotto/model/Money.java
>      }
this를 이용해 추가 연산 없이 바로 반환하는 점, other이라는 변수네이밍 모두 .. 너무 좋은 팁인 것 같습니다 🥺 앞으로의 구현에 활용해보도록 하겠습니다!! 감사합니다 ☺️