Step2
next-step/java-lotto pull request #2418
Opened 2022-05-08 15:35 UTC by alicesister1

안녕하세요 리뷰어님, 
미션 2단계 로또 (자동) 입니다.
이번 미션에서는 Money 객체와 LottoTickets, 로또 숫자 등을 일급 객체로 포장하는데 집중했습니다.
로또 금액을 갖고있는 클래스를 정할 때 LottoTicket과 LotteryRetailer에서 고민하다가 LotteryRetailer에 위치시켰는데, 이런 경우 어디서 가격을 갖고 있는게 더 나은 방향인가요?
리뷰 잘 부탁드립니다!

2022-05-09 14:31 UTC, orgojy requested changes
안녕하세요. 경희님! 😄 
이번 미션도 잘 구현해주셨습니다.
1단계보다 많은 신경을 써서 구현해주셨네요.
몇 가지 코멘트 남겼습니다.
코멘트 한 번 생각해보시고 다시 요청부탁드릴게요.

2022-05-09 14:31 UTC, orgojy commented on src/main/java/lotto/domain/LottoTickets.java
> +public class LottoTickets {
일급 컬렉션이 꼭 불변일 이유는 없지만,
방어적 복사와 불변으로 사용하는 이유와 과정에 대해서 잘 쓰여진 글이 있어서 공유드립니다. 😄 
[일급 컬렉션을 사용하는 이유](https://tecoble.techcourse.co.kr/post/2020-05-08-First-Class-Collection)

테스트도 작성해보면 좋겠네요.

2022-05-09 14:31 UTC, orgojy commented on src/main/java/lotto/domain/Money.java
> +  public static Money of(int amount) {
정적 팩토리 메서드 네이밍 참고용으로 공유드립니다. 😄 
[Effective Java Item 1. 생성자 대신 정적 팩토리 메서드를 고려하라](https://sun-22.tistory.com/84)

2022-05-09 14:31 UTC, orgojy commented on src/main/java/lotto/domain/LottoTicket.java
> +    checkDuplicatedNumbers(lottoNumbers);
객체 검증이 시간적 응집도가 있는 경우,
묶어서 메서드 추출하는 방법도 응집도를 높이는 방법 중에 하나입니다.
[시간적 결합도에 대하여](https://brunch.co.kr/@myner/83)
[응집도의 종류](https://itwiki.kr/w/%EC%9D%91%EC%A7%91%EB%8F%84)

2022-05-09 14:31 UTC, orgojy commented on src/main/java/lotto/domain/LottoTicket.java
> +  }
주 생성자를 사용하는 것도 한 번 적용해보시는 것도 좋겠네요. 😄 
[엘레강트오브젝트 1.2 생성자 하나를 주 생성자로 만드세요.](https://jackjeong.tistory.com/148)

2022-05-09 14:39 UTC, orgojy commented
LotteryRetailer 가 따로 로또의 판매 책임을 가져가는 경우이기 때문에,
LotteryRetailer에 Money가 위치하는 것이 적절하다고 생각합니다. 😄

2022-05-10 11:54 UTC, alicesister1 commented on src/main/java/lotto/domain/LotteryRetailer.java
> +public class LotteryRetailer {
<img width="806" alt="image" src="https://user-images.githubusercontent.com/10322828/167622248-3137f1d1-3b0f-452b-bc6b-e7b688415589.png">

저도 C로 시작해서 너무 소름돋네요 😱

2022-05-10 12:27 UTC, alicesister1 commented on src/main/java/lotto/domain/LotteryRetailer.java
> +  public LottoTickets sell(Money purchaseAmount, LottoNumberGenerator lottoNumberGenerator) {
네 현재는 LottoTickets만 반환하고 있습니다!
나중에 잔돈은 반환해야 하는 요구사항이 추가된다면 charge와, lottoTickets 라는 반환 객체로 묶어서 반환하는 방법을 생각했습니다.
이 방법이 맞는 방향일까요?

2022-05-10 12:33 UTC, alicesister1 commented on src/test/java/lotto/domain/LottoNumberGeneratorTest.java
> +    assertThat(generate).doesNotHaveDuplicates();
좋은 테스트 방법 공유 감사합니다🙏

2022-05-10 12:40 UTC, alicesister1 commented on src/main/java/lotto/domain/Money.java
> +  private static final String WON_FORMAT = "%d원";
네 말씀하신대로 비즈니스 메서드로 사용하기 보다 객체가 가진 주요 정보를 나타내는 방법으로 사용하는게 맞는 것 같습니다.

2022-05-10 13:10 UTC, alicesister1 commented on src/main/java/lotto/domain/LottoTickets.java
> +public class LottoTickets {
넵 지난 라이브 강의 때 포비님이 반환 시 참조보다 불변 또는 primitive로 반환하는 것을 고려해보라고 하셔서 불변을 사용해봤습니다!

앗 LottoTickets 테스트가 없네요😱

2022-05-11 03:01 UTC, orgojy commented on src/main/java/lotto/domain/LotteryRetailer.java
> +  public LottoTickets sell(Money purchaseAmount, LottoNumberGenerator lottoNumberGenerator) {
네 묶어서 비즈니스를 캡슐화는 방법도 적절하다고 생각합니다. 👍 
지금은 비즈니스 요구사항은 없어서 꼭 구현할 이유는 없습니다.

2022-05-11 05:46 UTC, orgojy commented
안녕하세요. 경희님! @alicesister1 
혹시 넥스트 스탭 홈에서 리뷰 요청을 잊으신건가요?

2022-05-11 06:25 UTC, alicesister1 commented
> 안녕하세요. 경희님! @alicesister1 혹시 넥스트 스탭 홈에서 리뷰 요청을 잊으신건가요?

안녕하세요! 여기 페이지에서 re request 드렸는데, 넥스트 스텝홈에서 다시 요청드리겠습니다! 감사합니다.

2022-05-11 06:51 UTC, orgojy commented
> > 안녕하세요. 경희님! @alicesister1 혹시 넥스트 스탭 홈에서 리뷰 요청을 잊으신건가요?
> 
> 안녕하세요! 여기 페이지에서 re request 드렸는데, 넥스트 스텝홈에서 다시 요청드리겠습니다! 감사합니다.

아 네네 ㅎㅎ 👍 
넥스트 스탭 홈에서 요청주시면, 리뷰어의 PR 리뷰 리스트로 올라가거든요.
다음에는 넥스트 스탭에서 리뷰요청도 부탁드릴게요~ 😄

2022-05-11 17:38 UTC, orgojy requested changes
안녕하세요. 경희님! 😄 
이번 단계가 가장 힘든데, 잘 구현해주셨네요. 👍 
생각 많이 하신게 코드에서 느껴지네요.
몇가지 코멘트를 남겼습니다.
참고 자료 확인해보시면서, 개선 해보시면 좋겠네요.
해보시고, 다시 요청 주세요~!

2022-05-11 17:38 UTC, orgojy commented on src/main/java/lotto/domain/Statistic.java
> +    if (matchedPriceCount < 0) {
<참고자료><br/>[매직 리터럴(매직 넘버)을 다루는 법](https://orgojy.oopy.io/2e24b1bc-c412-4d58-8b76-1edb0cac49cc)

2022-05-11 17:38 UTC, orgojy commented on src/main/java/lotto/domain/money/Money.java
> +  }
객체 생성시, 검증을 진행해보는건 어떨까요?

2022-05-12 12:16 UTC, alicesister1 commented on src/main/java/lotto/domain/Statistic.java
> +    if (matchedPriceCount < 0) {
리뷰어님, 숫자 0을 매직넘버로 바꾸는것을 제안해주신걸까요?
제 생각에, 이 부분은 `requireNonNegative`라는 메서드 이름에서 충분한 맥락 정보를 제공한다고 생각해서 놔두었는데 
그래도 매직넘버로 빼는게 좋을까요?

2022-05-12 13:52 UTC, alicesister1 commented on src/main/java/lotto/domain/money/Money.java
> +  }
private 접근자에 createWon이라는 static 메서드로 생성하고 있어 해당 생성자의 접근점이 하나이고 내부적으로 Locale을 지정하고 있어으며 테스트를 할 수가 없어서 검증을 추가하지 않았습니다.
private 메서드도 검증해야 하는걸까요? .. 🥹

2022-05-12 14:19 UTC, alicesister1 commented on src/main/java/lotto/domain/Statistics.java
> +        .filter(prizes -> prizes != Prizes.NOT_PRIZE)
넵 말씀하신대로 PRIZE에서 수행하고 결과만 반환 하는게 적절한 것 같습니다.

객체의 정보를 가져와서 무엇을 하지 말고 메세지를 보내야한다. 
들어서 머리로는 알고는 있지만 코드로 잘 나타내지 못하고 있는것 같아요. 
매번 좋은 참고자료와 리뷰 감사합니다 !

2022-05-13 06:37 UTC, orgojy commented on src/main/java/lotto/domain/Statistic.java
> +    if (matchedPriceCount < 0) {
숫자 0이 매직넘버라서,
가독성있는 상수나 메서드로 바꾸는 형태로 보여주는 것을 말씀드린 것이구요.
지금은 말씀하신대로 충분합니다. 👍 

하지만, 비즈니스가 추가되거나 변경되는 시점에 매직넘버의 사이드 이펙트가 발생하기 시작하더라구요.
저는 개인적으로 if로 깊이가 증가하기 시작하면 조건절 매직넘버는 메서드로 추출합니다.
이 부분은 경희님이 선택하시면 될 사항이라고 생각합니다.

2022-05-13 06:50 UTC, orgojy commented on src/test/java/lotto/domain/money/MoneyTest.java
> +  @DisplayName("")
테스트 케이스 이름을 실수로 누락하신것 같네요. 😄

2022-05-13 07:05 UTC, orgojy commented on src/main/java/lotto/domain/Statistics.java
> +  }
주 생성자는 객체 인스턴스의 상태를 초기화하는 역할에 주력해야합니다.
나중에 비즈니스 복잡도가 증가하게되면,
객체가 어디서 검증과 생성되는지 찾기가 힘들어지더라구요.
결국 주 생성자를 두고 재사용하게 됩니다.
이해에 도움이 되게 코드를 첨부하겠습니다.
``` java
    public static Statistics of(WinningLottoTicket winningLottoTicket, LottoTickets lottoTickets, Money lottoPrice) {
        validate(winningLottoTicket, lottoTickets, lottoPrice);
        return new Statistics(createStatistics(winningLottoTicket, lottoTickets), lottoPrice.multiply(lottoTickets.size()));
    }

    private static List<Statistic> createStatistics(WinningLottoTicket winningLottoTicket, LottoTickets lottoTickets) {
        return Arrays.stream(Prizes.values())
                .filter(Prizes::hasPrize)
                .map(prize -> new Statistic(lottoTickets.getMatchedCountPerPrize(prize, winningLottoTicket),
                        prize))
                .collect(Collectors.toList());
    }

    private static void validate(WinningLottoTicket winningLottoTicket, LottoTickets lottoTickets, Money lottoPrice) {
        if (winningLottoTicket == null) {
            throw new IllegalArgumentException("winningLottoTicket must not be null.");
        }
        if (lottoTickets == null) {
            throw new IllegalArgumentException("lottoTickets must not be null.");
        }
        if (lottoPrice == null) {
            throw new IllegalArgumentException("lottoPrice must not be null.");
        }
    }

    public Statistics(List<Statistic> statistics, Money purchaseAmount) {
        validate(statistics, purchaseAmount);
        this.statistics = statistics;
        this.purchaseAmount = purchaseAmount;
    }

    private void validate(List<Statistic> statistics, Money purchaseAmount) {
        if (statistics == null || statistics.isEmpty()) {
            throw new IllegalArgumentException("statistics must not be null.");
        }
        if (purchaseAmount == null) {
            throw new IllegalArgumentException("purchaseAmount must not be null.");
        }
    }
```

2022-05-13 07:27 UTC, orgojy commented on src/main/java/lotto/domain/money/Money.java
> +  }
네 테스트는 진행하지 않으셔도 됩니다.
하지만 private 생성자라도 상태 초기화를 담당하고 있어서,
호출하는 메서드 쪽에서 검증하지 않으면 NPE 가 발생할 수 있습니다.
검증만 추가해주시면 된다고 생각합니다.

2022-05-13 07:51 UTC, orgojy approved these changes
안녕하세요. 경희님! 😄 
주신 질문에 대한 답변 코멘트로 남겼습니다.
다음 미션에 반영해주세요. 살펴보겠습니다.
미션 진행을 위해서 PR은 머지하도록 하겠습니다!
고생하셨어요. 다음 미션도 응원합니다.

2022-05-13 07:51 UTC, orgojy commented on src/main/java/lotto/domain/Statistics.java
> +public class Statistics {
일급 컬렉션의 역할에 맞게 잘 구현해주셨네요. 👍

2022-05-13 07:51 UTC, orgojy commented on src/main/java/lotto/domain/money/Money.java
> +  private Money(Currency currency, int amount) {
이 부분 지난 리뷰에서 놓쳤네요. 😄 
currency를 잘 검증해주셨네요.
amount도 음수가 될 수는 없을 거라고 생각합니다. 검증을 추가해주셔도 좋겠네요.

2022-05-13 07:51 UTC, orgojy commented on src/main/java/lotto/domain/Statistic.java
> +  private boolean isNegative(int matchedPriceCount) {
👍

2022-05-13 07:51 UTC, orgojy commented on src/test/java/lotto/domain/StatisticsTest.java
> +
의미없는 빈칸은 제거해도 좋습니다. 😄 
```suggestion

```

2022-05-13 07:51 UTC, merged

2022-05-14 07:40 UTC, alicesister1 commented on src/main/java/lotto/domain/Statistics.java
> +  }
생성자에서 this()로 주 생성자를 호출하는 방벙을 시도했을 때 createStatistics 메서드를 호출할 수 없었는데, new 키워드로 생성하는 방법이 있었네요. 첨부해주신 코드가 이해하는데 큰 도움이 되었습니다. 감사합니다. 😁