Step3 - 로또(2등) 리뷰 요청드립니다
next-step/java-lotto pull request #2439
Opened 2022-05-11 10:52 UTC by ssamzag

안녕하세요. 4단계 리뷰 요청드립니다.
질문이 몇 가지 있습니다!!

Money 클래스의 수령관련 상태/기능들을 Quantity 클래스로 분리하였습니다.
그런데 이렇게 분리하니 buyPrice 가 원시값으로 남는데, Money라는 클래스를 이름을 다른 것으로 바꾸고 원시값 buyPrice를 다시 클래스로 분리해 주는 게 맞는 걸까요? 이름 짓기 너무 어렵네요..😢

구매로또 번호를 출력해주는 ResultView의 printBuyLottoNumbers 함수 인자값을 작은단위로 바꿨습니다. 이전은 lottoGame 인스턴스를 통으로 넘겼지만, 해당 메소드에서 필요로하는 최소단위인 List를 넘기도록 바꿨는데요.
또 생각해보니 List 보다는 List으로 바꾸는 게 맞지 않냔 생각이 듭니다. 하지만 그렇게 되면 model에서 ui를 위한 기능이 만들어지는 거 같아 mvc에 맞지 않는다는 생각이 들었지만, 또 다른 생각으로는 오직 ui를 위한 getter 인 List 형식이므로 맞다는 생각도 드는데요.. 어떨까요. 😢

2022-05-12 04:50 UTC, ydh6226 requested changes
요청 드린 테스트와 3단계도 잘 진행해주셨네요 :)
질문해주신 내용에 대한 답변과 몇가지 코멘트 남겨드렸으니
확인해보시고 다시 리뷰요청 부탁드립니다 🙂

2022-05-12 04:50 UTC, ydh6226 commented on src/main/java/lotto/domain/App.java
> +    public static void main(String[] args) {
적절한 단위로 개행하면 어떨까요? 🙂

2022-05-12 04:50 UTC, ydh6226 commented on src/main/java/lotto/domain/App.java
> +        ResultView.printBuyLottoNumbers(lottoGame.getBuyLottoNumbers());
우선 정답이 있는 부분은 아니라고 생각해요 :)
개인적으로는 불필요한 변환이 도메인에 있는걸 선호하지 않아서 printBuyQuantityMessage() 파라미터로는 UserLottos 만 넘기고 
view 내부에서 getter를 사용하는 방향으로 할 것 같아요.

뷰를 위한 로직이기도 하고 단순히 getter만 호출하는 구조이기 때문에 뷰에 있어도 되는 로직이라고 생각합니다 🙂

2022-05-12 04:50 UTC, ydh6226 commented on src/main/java/lotto/domain/Money.java
> +    private Quantity quantity;
개인적으로 돈을 나타내는 Money 객체에 
수량관련 로직이나 Quantity 객체가 있는 구조가 다소 어색하기도 한데요.
어떻게 생각하시나요?

결국 어떤 객체에서는 원시 값을 그대로 들고 있어야 하기 때문에 int::buyPrice는 좋다고 생각해요 :)

2022-05-12 04:50 UTC, ydh6226 commented on src/main/java/lotto/domain/Money.java
>  public class Money {
Rank::winningMoney에서도 Money 객체를 활용해보는건 어떨까요?

2022-05-12 06:26 UTC, ssamzag commented on src/main/java/lotto/domain/App.java
> +    public static void main(String[] args) {
넵 비슷한 역할끼리 묶어봤습니다!

2022-05-12 06:30 UTC, ssamzag commented on src/main/java/lotto/domain/Money.java
> +    private Quantity quantity;
money 객체에서 수량 상태를 가지는 게 짜면서도 많이 찝찝했습니다.  분리토록 할게요

2022-05-13 04:54 UTC, ydh6226 approved these changes
코멘트 잘 반영해주셨네요 👍👍
이번 단계는 이만 머지하겠습니다
한 가지 고민거리 남겨드렸으니 확인부탁드려요 :)

2022-05-13 04:54 UTC, ydh6226 commented on src/main/java/lotto/domain/UserLottos.java
> +    private Quantity quantity;
멤버 변수 하나가 추가되면서 일급컬렉션이었던 UserLottos가 더 이상 일급 컬렉션이 아니게 되었는데요.
꼭 UserLottos를 일급 컬렉션으로 만들 필요는 없기 때문에 어떤 구조가 좋을지에 대해서 고민해보시면 좋을 것 같아요 :)

2022-05-13 04:54 UTC, ydh6226 commented on src/main/java/lotto/domain/Money.java
> +    public Money(String money) {
주생성자 / 부생성자 활용 좋습니다 :)

2022-05-13 04:54 UTC, ydh6226 commented on src/main/java/lotto/domain/Rank.java
> +    private final Money winningMoney;
Money객체 활용 👍

2022-05-13 04:54 UTC, ydh6226 commented on src/test/java/lotto/domain/MoneyTest.java
> +    void sumMoney() {
테스트도 잘 작성해주셨네요 🙂

2022-05-13 04:54 UTC, merged

2022-05-13 05:56 UTC, ssamzag commented on src/test/java/lotto/domain/MoneyTest.java
> +    void sumMoney() {
아이고 displayName을 적다 말았네요. 수정해야겠어요 🥲

2022-05-13 05:59 UTC, ssamzag commented on src/main/java/lotto/domain/Money.java
> +    public Money(String money) {
부 생성자에서 parInt를 호출하고 있는데 해당 함수는 생성자 바로 아래에 위치하는 게 맞을까요?
메소드같은 경우는 가이드대로 실행 순서로 두는데, 생성자 메소드 생성자 순서가 되도록 하는 게 맞는지 궁금합니다.

2022-05-13 06:02 UTC, ssamzag commented on src/main/java/lotto/domain/UserLottos.java
> +    private Quantity quantity;
고민해 보겠습니다

2022-05-14 01:42 UTC, ydh6226 commented on src/main/java/lotto/domain/Money.java
> +    public Money(String money) {
저는 **부 생성자에서 parInt를 호출하고 있는데 해당 함수는 생성자 바로 아래에 위치하는 게 맞을까요?** 방식을 선호하는 편입니다!
정답은 없는 내용 같아요 🙂