Step4 로또(수동)
next-step/java-lotto pull request #2471
Opened 2022-05-18 16:56 UTC by 0319easy

안녕하세요!
로또 step4 리뷰 요청드립니다
마지막까지 잘 부탁드려요!!

+) 요구사항 중에
> 예외 처리를 통해 에러가 발생하지 않도록 한다.

는 try-catch 구문을 통해 에러 발생을 잡아서 처리하라는 것으로 받아들였는데 제가 제대로 이해한게 맞을까요..?

2022-05-18 23:00 UTC, seok-2-o requested changes
마지막 로또 미션 잘 수행해주셨네요 💯 
몇가지 추가로 반영하였으면 하는 부분이 있어 코멘트로 남겨 놓았습니다.
확인 부탁드릴게요.

말씀하신것처럼 에러가 나지 않도록 try catch 구문으로 처리해주시면 될 것 같습니다 :)

2022-05-20 19:17 UTC, 0319easy commented on src/main/java/lotto/domain/Lotto.java
> +    public LottoReward hasWinningNumbers(Lotto winningLotto, LottoNumber bonusNumber) {
> Lotto winningLotto, LottoNumber bonusNumber
> 
> `winningLotto.hasNumber(bonusNumber) ` 가 true 라면 어떤 문제가 있을까요?

https://github.com/0319easy/java-lotto/blob/4ccf64e7626cd850220fed8114449e49bdf8d254/src/main/java/lotto/domain/Winner.java#L19-L21

에서 Winner 객체 생성시에 bonusNumber가 중복으로 들어오지 않게 처리하고 있습니다


> winner.check(lotto) 의 방향으로 변경하면 어떤가요?

https://github.com/0319easy/java-lotto/blob/4ccf64e7626cd850220fed8114449e49bdf8d254/src/main/java/lotto/domain/Winner.java#L35-L37

winner.findWinners()로 당첨자 체크는 winner에서부터 시작되게 구현되어있습니다

2022-05-20 19:18 UTC, 0319easy commented
안녕하세요~ 코멘트 주신 부분 수정 반영하였습니다
말씀해주신 플라이웨이트 패턴을 적용해보았는데 잘 적용한것인지 확인 부탁드립니다!!

2022-05-21 10:12 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요.

이번 피드백을 마지막으로  저와의 미션은 마무리가 되네요 🙇 

저와 미션은 여기까지지만 앞으로 궁금한점이나 어려운점 있으면 편하게 DM 주세요 :)
좋은 개발자로 성장하는데 조금이나마 도움이 되기를 바라봅니다.

감사드리며,
이재석 드림

2022-05-21 10:12 UTC, seok-2-o commented on src/main/java/lotto/domain/LottoNumberFactory.java
> +public class LottoNumberFactory {
플라이웨이트 패턴을 잘 적용해주셨네요 👍 
다만 별도의 팩토리로 분리해주신 이유가 있으실까요?

2022-05-21 10:12 UTC, merged

2022-05-31 17:27 UTC, 0319easy commented on src/main/java/lotto/domain/LottoNumberFactory.java
> +public class LottoNumberFactory {
@seok-2-o
앗 제가 확인이 너무 늦었습니다ㅠㅡㅠ
기 생성된 LottoNumber 객체를 LottoNumber가 들고 있는게 어색해서 분리하였는데
지금 생각해보니 Lotto 클래스에 넣어놔도 괜찮았겠다는 생각이 드네요...