[3단계] 로또(2등)
next-step/java-lotto pull request #2473
Opened 2022-05-18 17:54 UTC by zieunx

안녕하세요!

3단계 로또(2등) 리뷰 요청 드립니다😁

## 고민스러운 부분 및 의견 궁금해요
###  '보너스번호'를 설계하는 방법
많은 고민 끝에 LottoNumber 가 type을 가지도록 설계했습니다.
몇 가지 고민됐던 방향이 있어서 나누면서 의견 들어보고자 합니다! 

1) 상속 구조

LottoNumber 를 상속하는 BonusNumber를 구현할까 고민했습니다.

```java
public class BonusNumber extends LottoNumber {
   // (생략)
}
```

해당 구조로 가는 경우 대부분의 메인 로직은 LottoNumber가 가지고 BonusNumber는 '보너스번호인지' 구분할수 있는 정도의 역할밖에 없다고 생각이 들었습니다.  
상속구조를 구현해본 경험이 별로 없어서.. 괜찮은 방법인지 스스로 의문이 들었습니다.

2) 추상클래스 상속 구조

LottoNumber를 추상클래스로 바꾸고 DefaultLottoNumber, BonusNumber 도메인으로 나누는 방법입니다.

```java
public abstract class LottoNumber {
   // (생략)
}

public class DefaultLottoNumber extends LottoNumber {
   // (생략)
}

public class BonusNumber extends LottoNumber {
   // (생략)
}
```

이렇게 되면 DefaultLottoNumber 와 BonusNumber 에 중복되는 코드가 너무 많아질 것 같아서 아니라고 생각했습니다. 

-------------

여러가지 고민을 했지만... 애초에 이런 고민의 방향성이 맞는가? 에 대해서 자신이 없습니닷...
설계 부분에서 고민스럽고 확신이 안들어서 리뷰요청을 통해 의견 들어보고 싶습니다..! 🙏

2022-05-19 04:16 UTC, simjunbo requested changes
기능 구현하시느라 고생하셨습니다. 

앞에서 드린 리뷰도 잘 반영해 주시고
객체의 들의 역할이 잘 나누어져 있어서 리뷰하기 편했습니다 👍 

고민 하셨던 부분에 대해서는 저는 LottoNumber에 type이 들어가면 ValueObject에 대한
재사용성이 제한적이 될것 같아서 type, 또는 추상화 구분 없이 공통으로 사용해보면 어떨까 합니다.

자세한 부분은 밑에 코멘트로 남겨 놓았으니
피드백 확인 후 재요청 부탁드립니다!

2022-05-19 04:16 UTC, simjunbo commented on src/main/java/lotto/domain/RankingResult.java
>  		rankResults.forEach(this::countLottoRank);
stream을 이용한 map 형태로 변환해 보면
기본 생성자나 countLottoRank 메소드의 사용을 줄여볼 수 있을것 같습니다! 😄 

힌트) Collectors.toMap

2022-05-19 04:16 UTC, simjunbo commented on src/main/java/lotto/domain/WinningNumbers.java
> +	private final List<LottoNumber> numbers;
이 부분에 대한 고민이 가장 크신것 같아서 여기에 의견 남겨 놓습니다!

```
private final Lotto lottos;
private final LottoNumber bonusNumber;
```

저는 WinningNumbers 가 당첨 번호 + 보너스 번호를 묶는 역할의 클래스라 생각이 되며
기존에 사용하고 있던 Lotto 일급컬렉션 및 LottoNumber 원시값 포장 클래스를 재사용해도 되지 않을까 생각되네요.

사실 `List<LottoNumber>`에 보너스 번호를 함께 녹이기 위해서 LottoNumberType이 추가된것 같은데
역할을 분리하면 재사용성이나, 로또 당청금 체크 방식이 좀 더 간단해 지지 않을까 생각되네요.

2022-05-19 04:16 UTC, simjunbo commented on src/main/java/lotto/domain/WinningNumbers.java
> +	public WinningNumbers(String input) {
input 이라고 하면 뭔가 view 데이터에 도메인이 결합되는 것 같아서
파라미터 명을 명확하게 수정하거나 `List<Intger>` 형태를 받아와서 변환 해 보는건 어떨까 생각되네요. 😄

2022-05-19 04:16 UTC, simjunbo commented on src/main/java/lotto/domain/WinningNumbers.java
> +	public WinningNumbers(List<LottoNumber> numbers) {
아직 사용되고 있지 않는 부분 같은데 삭제 해보는것은 어떨까요 ?! 🤔

2022-05-19 04:16 UTC, simjunbo commented on src/main/java/lotto/view/OutputView.java
> +		printBuffer.append("당첨 통계\n");
```suggestion
		printBuffer.append("당첨 통계").append(ENTER);
```
이런식으로 명확하게 분리해 보면 좀 더 가독성에 좋을 것 같습니다 😄

2022-05-19 04:16 UTC, simjunbo commented on src/test/java/lotto/domain/WinningNumbersTest.java
> +	@CsvSource(value = {"1,2,3,4,5,6/7/7,5,4,3,2,1/1", "1,2,3,4,5,6/8/7,5,4,3,2,1/0"}, delimiter = '/')
사소한 부분이지만 사용하시는 delimiter 도 통일 시켜보면 좋을것 같습니다 😄

2022-05-21 13:48 UTC, zieunx commented on src/main/java/lotto/controller/LottoController.java
> +		long lottoQuantity = calculateLottoQuantity(new Amount(InputView.inputPurchaseAmount()));
피드백 감사합니다~

로또미션을 떠나 궁금한 것은, 다른 메소드에서도 호출하게되는경우도 있는데 다양한 케이스들이 모이다보면 바로밑에 인접시키기 애매한 경우도 있더라구요.
그러다보니 public과 private을 분리하여 private을 맨 밑으로 위치하는 습관이 생기게 된것같아요.
예를들면 이런식의 구조가 몇가지 반복되면 말씀하신 의도대로 흘러가기 어려워지기도 하는거같아요 ..!

* public a -> private b
* public a -> private d
* public c -> private b

이럴 때는 어떻게 하시는 편이신가요??

2022-05-21 15:37 UTC, zieunx commented on src/main/java/lotto/domain/PurchaseLottoGroup.java
>  	public String toString() {
이 부분도 너무 고민스러워요..!

앞전에 `RankingResult`를 출력을 위해 상태를 아래와같이 넘겨줬었습니다.

```
public class RankingResult {
	private final Map<LottoRank, Long> ranking = new LinkedHashMap<>();

	public Map<LottoRank, Long> ranking() {
		return ranking;
	}
}
```

이렇게 되면 외부에서 ranking() 메소드로 얻어진 map을 변경할 수있어서 마음이 불편했지만 일단 이렇게 해봤었습니다!
근데 `PurchaseLottoGroup` 또한 `List<Lotto> lottoGroup`를 리턴해주는 방법밖에 생각이 안나네요...

방법이 두 방법밖에 없다는 가정을 하자면, 저는 차라리 출력과 조금 연관이 되더라도 객체 자체가 처리하도록 하는게 나을 것 같은데
혹시 이 방법 두 가지 말고 다른 방법이 있을까요? 🙏

2022-05-21 16:39 UTC, zieunx commented on src/main/java/lotto/domain/RankingResult.java
>  		rankResults.forEach(this::countLottoRank);
toMap()으로는 Map<LottoRank, Long(수량)> 구조로 뽑을 방법을 찾지 못해서 groupingBy로 해결해봤습니다!
훨씬 간결해지고 메소드를 생략할 수 있게 됐네요 👍🏻

2022-05-21 16:51 UTC, zieunx commented on src/main/java/lotto/view/OutputView.java
> +		printBuffer.append("당첨 통계\n");
\n을 상수로 뺀다는 생각을 못했네요! 훨씬 깔끔해졌네요! 👍

2022-05-21 16:53 UTC, zieunx commented on src/test/java/lotto/domain/WinningNumbersTest.java
> +	@CsvSource(value = {"1,2,3,4,5,6/7/7,5,4,3,2,1/1", "1,2,3,4,5,6/8/7,5,4,3,2,1/0"}, delimiter = '/')
`:`로 통일해서 사용하고 있었으나, 값이 많아지다보니 구분이 잘 안돼서 해당 테스트만 `/`로 바꿔보았습니다.

보편적으로 delimiter는 통일해서 사용하나요??

2022-05-24 02:47 UTC, simjunbo commented on src/main/java/lotto/controller/LottoController.java
> +		long lottoQuantity = calculateLottoQuantity(new Amount(InputView.inputPurchaseAmount()));
@zieunx 저도 그런경우는 private을 public 클래밑에선언하는 편입니다.
통일성 있게 자신만의 규칙을(또는 팀규칙) 을
세워서 지키기만 하면 될것 같습니다 😄

2022-05-24 03:37 UTC, simjunbo commented on src/main/java/lotto/domain/LottoRank.java
> +	public static LottoRank findBySameQuantity(long sameQuantity, long bonusQuantity) {
@zieunx 대략적으로 생각했던 방향 밑에 공유 드립니다 😄 

```
    public static LottoRank findBySameQuantity(long sameQuantity, long bonusQuantity) {
        if (isSecond(sameQuantity, bonusQuantity)) {
            return LottoRank.SECOND;
        }

        return Arrays.stream(LottoRank.values())
                .filter(rank -> LottoRank.SECOND != rank)
                .filter(rank -> rank.sameQuantity == sameQuantity)
                .findAny()
                .orElse(NOTHING);
    }
```

2022-05-24 03:40 UTC, simjunbo commented on src/main/java/lotto/domain/PurchaseLottoGroup.java
>  	public String toString() {
@zieunx 저도 게터를 지양하지만 DTO나 단순 뷰 출력에서는 단순 정보를 사용하는 부분이기 때문에 
크게 영향이 없다고 생각합니다.
그리고 상태를 넘길때 방어적 복사 또는 Unmodifiable Collection 방식을 사용해 보시기 바랍니다. 😄 
그러면 부수효과를 줄일 수 있습니다.

참고) https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/

2022-05-24 03:45 UTC, simjunbo commented on src/test/java/lotto/domain/WinningNumbersTest.java
> +	@CsvSource(value = {"1,2,3,4,5,6/7/7,5,4,3,2,1/1", "1,2,3,4,5,6/8/7,5,4,3,2,1/0"}, delimiter = '/')
참고만 하세요.
제가 선호 하는 방식인데 저는 탭으로 파라미터 값들 끼리 구분합니다.

```
    @DisplayName("당첨번호와 보너스번호와 로또간 일치 갯수")
    @CsvSource(value = {
            "1,2,3,4,5,6	|7		|7,5,4,3,2,1		|1",
            "1,2,3,4,5,6	|8		|7,5,4,3,2,1		|0"
    }, delimiter = '|')
```

2022-05-24 04:53 UTC, simjunbo approved these changes
@zieunx 
피드백 잘 반영해 주셨습니다 👍 
질문 하신 부분 답변과 몇가지 코멘트 남겨 놓았으니 다음 미션 진행 시, 같이 고민해 주시기 바랍니다.

그리고 **궁금해요** 남겨 주신 부분은 여기에서 답변 드리면
@MethodSource 를 사용해 보시면 List<LottoNumber> 형태로 값을 받아서 처리할 수 있습니다!
관련 해서 링크 첨부했으니 같이 확인해 보시기 바랍니다.

참고) https://gmlwjd9405.github.io/2019/11/27/junit5-guide-parameterized-test.html

2022-05-24 04:53 UTC, simjunbo commented on src/main/java/lotto/domain/PurchaseLottoGroup.java
> +		lottoGroup =LongStream.rangeClosed(1, quantity)
사소한 부분이지만 현업에서 정렬도 코드스타일을 통일 시키기 위해 중요한 요소 입니다.
개발 후, 한번씩 확인해 보시면 좋을것 같습니다 😄 

참고) https://gocoder.tistory.com/2440

2022-05-24 04:53 UTC, simjunbo commented on src/main/java/lotto/domain/WinningNumbers.java
> +		this.numbers = winningNumbers;
유효성 체크를 먼저 하고 값을 주입하는게 좀 더 자연스러울 것 같네요.

this.numbers 에 대한 부분도 validateDuplicationBonusNumber 이후 할당해 보면 어떨까요 ?! 🤔

2022-05-24 04:53 UTC, simjunbo commented on src/main/java/lotto/view/OutputView.java
> +			.map(Lotto::toString)
여기도 출력을 위해 toString을 사용하고 있는데 별도 분리해 보는것은 어떨까요 ?! 🤔

2022-05-24 04:53 UTC, simjunbo commented on src/main/java/lotto/view/OutputView.java
> +			.collect(Collectors.joining("\n")));
```suggestion
			.collect(Collectors.joining(ENTER)));
```

2022-05-24 04:54 UTC, merged