step3
next-step/java-lotto pull request #2477
Opened 2022-05-21 06:49 UTC by duck-ayoung

안녕하세요 step3의 요구사항과
저번 PR에서 피드백주신 부분 반영하였습니다.
리뷰 부탁드립니다!

2022-05-22 02:23 UTC, seondongpyo requested changes
3단계 미션도 잘 구현해주셨네요 👍
몇 가지 코멘트 드렸는데 확인 부탁드릴게요.
궁금하시거나 의견 나누고 싶은 내용 있으시면 코멘트 또는 Slack으로 DM 주시길 바랍니다.
조금만 더 힘내주시고 남은 주말도 즐거운 시간 되세요 🔥

2022-05-22 02:23 UTC, seondongpyo commented on src/main/java/lotto/domain/Lottos.java
> +    public int[] getTotalRank(WinningLotto winningLotto) {
배열 대신 `List`를 활용해보는 건 어떨까요?
등수에 대한 요구사항이 변경된다면 배열의 크기를 그 때마다 변경해야 하는 번거로움이 생길 것 같아요.

2022-05-22 02:23 UTC, seondongpyo commented on src/main/java/lotto/domain/Rank.java
> +    public int getMatchCount() {
사용하지 않는 메서드는 제거하는 건 어떨까요?
나중에 사용하기 위해 미리 선언해놓으신 걸까요?

2022-05-22 02:23 UTC, seondongpyo commented on src/main/java/lotto/domain/WinningMoneyCalculator.java
> +    public static int getTotalWinningMoney(WinningLotto winningLotto, Lottos buyingLottos) {
모든 로또 당첨 결과를 갖는 일급 콜렉션을 생성하여 해당 일급 콜렉션에서 처리해보는 것도 좋을 것 같아요

2022-05-28 07:37 UTC, duck-ayoung commented on src/main/java/lotto/domain/WinningLotto.java
> +    private final Set<LottoNumber> numbers;
넵 그렇게하니 중복코드가 많이 제거되네요!

2022-05-28 07:37 UTC, duck-ayoung commented on src/main/java/lotto/domain/WinningLotto.java
> +        return lotto.getNumbers().contains(this.bonusNumber);
메시지를 보내서 처리해보았습니다

2022-05-28 07:38 UTC, duck-ayoung commented on src/main/java/lotto/domain/Lotto.java
> +    private int getMathCount(WinningLotto winningLotto) {
ㅎㅎㅎ 수정했습니다.

2022-05-28 07:38 UTC, duck-ayoung commented on src/main/java/lotto/domain/Lottos.java
> +    public int[] getTotalRank(WinningLotto winningLotto) {
Map 으로 활용해보았습니다!

2022-05-28 07:38 UTC, duck-ayoung commented on src/main/java/lotto/domain/Rank.java
> +    public int getMatchCount() {
제거하는 걸 깜밖했습니다 감사합니다!

2022-05-28 14:43 UTC, duck-ayoung commented on src/main/java/lotto/domain/WinningMoneyCalculator.java
> +    public static int getTotalWinningMoney(WinningLotto winningLotto, Lottos buyingLottos) {
넵 그렇게 변경해보았습니다!

2022-05-29 03:05 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍💯
추가로 몇 가지 코멘트 드렸는데, 다음 단계에서 반영해보시면 좋을 것 같습니다. 
다음 단계도 힘내시고, 남은 주말도 좋은 시간 되시길 바랍니다 🔥

2022-05-29 03:05 UTC, seondongpyo commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean isContain(LottoNumber bonusNumber) {
아시겠지만, 콜렉션 인터페이스에는 특정 요소의 포함 여부를 확인할 수 있는 `contains()`라는 메서드가 있는데요,
해당 메서드도 그와 기능이 유사하기 때문에 `contains`라는 이름으로 지어보는 건 어떻게 생각하시나요?

2022-05-29 03:05 UTC, seondongpyo commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
👍

2022-05-29 03:05 UTC, seondongpyo commented on src/main/java/lotto/domain/TotalRank.java
> +    }
해당 비즈니스 로직을 `Lottos`가 처리하도록 역할을 위임해보면 좋을 것 같습니다.

2022-05-29 03:05 UTC, seondongpyo commented on src/main/java/lotto/domain/WinningLotto.java
> +    private final LottoNumber bonusNumber;
👍

2022-05-29 03:05 UTC, seondongpyo commented on src/main/java/lotto/domain/WinningLotto.java
> +    }
현재 `Lotto`에서 로또 번호들을 getter로 꺼내서 처리하고 있는데요, getter를 사용하지 않는 방법은 없을까요?

2022-05-29 03:05 UTC, seondongpyo commented on src/main/java/lotto/view/ResultView.java
> +        System.out.println("6개 일치 (2000000000원)-" + totalBuyingLottoRank.count(Rank.FIRST) + "개");
각각의 등수에 대한 일치하는 번호의 개수와 당첨 금액도 `Rank` 객체를 활용하여 출력해볼 수 있지 않을까요?

2022-05-29 03:05 UTC, merged