로또(자동) 미션 Step2
next-step/java-lotto pull request #2499
Opened 2022-09-27 15:39 UTC by devcs96

안녕하세요 , 지훈 리뷰어님! 

이번 로또 미션 진행하면서 이렇게 설계해도 되나 싶은 부분이나 여쭤보고싶은사항들은 코멘트 부분에 달아두었습니다,

리뷰 해주셔서 감사합니다 🙇🏻

2022-09-27 16:04 UTC, devcs96 commented on src/main/java/lotto/model/MatchNumber.java
> +
일치된 로또 개수에 따라 상금 금액이 달라지니 , enum type으로 만들어 상금 상수와 일치된 숫자 상수를 관리하면 좋겠다고 생각을하였는데 막상 구현해보니 , enum 변수명이랑 일치된 숫자 이름이 중복이 발생하는 것 같아서 고민이 되었습니다!

2022-09-27 16:04 UTC, devcs96 commented on src/main/java/lotto/service/impl/RelativeProfitStrategy.java
> +    }
수익률 계산하는 로직이 간단해서 람다로 넣어도 되겠다고 생각은 하였는데 , 향후 확장을 고려하면 람다보다는 인터페이스 구현체를 만드는 게 이상적일까요! 정답은 없겠지만 어떤 쪽을 선호하시는지 궁금합니다!

2022-09-28 13:39 UTC, vagabond95 commented on src/main/java/lotto/LottoStore.java
> +    private int getLottoNum(int input) {
input 이 음수 일 경우에는 어떻게 처리되면 좋을까요?

2022-09-28 13:39 UTC, vagabond95 commented on src/main/java/lotto/controller/LottoApp.java
> +            throw e;
에러메세지를 상세히 적으면 충분히 감지할 수 있지 않을까요? (코드 라인, 파일 위치, 원인 등)

구현해주신 방법도 괜찮지만, 예외를 추가로 던질경우 외부에서 catch 가 항상 필요하므로 트레이드 오프를 잘 고민해보면 좋을 것 같아요~!

2022-09-28 13:39 UTC, vagabond95 commented on src/main/java/lotto/model/MatchNumber.java
> +
enum 변수명을 숫자가 아닌 등수로 표현해보면 어떨까요?

2022-09-28 13:47 UTC, vagabond95 requested changes
2단계부터 거의 구조를 완성해주신 것 같은데요 ㅎㅎ

커밋로그와 구현에 대한 생각들을 자세히 남겨주셔서 수월하게 리뷰를 할 수 있었어요.
질문주신 내용 및 구현에 대한 코멘트 남겼는데요, 확인 후 리뷰요청 부탁드리겠습니다~!

2022-09-28 13:47 UTC, vagabond95 commented on src/main/java/lotto/controller/LottoApp.java
> +        try (BufferedReader br = new BufferedReader(new InputStreamReader(System.in))) {
bufferReader 는 InputView 내부에서만 관리해도 괜찮지 않을까요?

2022-09-28 13:47 UTC, vagabond95 commented on src/main/java/lotto/model/MatchNumber.java
> +public enum MatchNumber {
enum 으로 접근 👍

2022-09-28 13:47 UTC, vagabond95 commented on src/main/java/lotto/model/MatchNumber.java
> +    FOUR(4, 50000),
```suggestion
    FOUR(4, 50_000),
```

언더스코어(_) 를 활용하면 가독성을 좀 더 올릴 수 있습니다!

2022-09-28 13:47 UTC, vagabond95 commented on src/main/java/lotto/service/impl/RelativeProfitStrategy.java
> +    }
케이스마다 다르겠지만 확장성을 고려한다면, 저도 인터페이스를 활용하는 것을 더 선호합니다 :)

2022-09-28 13:47 UTC, vagabond95 commented on src/main/java/lotto/model/Lottos.java
> +    }
저는 어느정도 독립적으로 잘 구현해주셨다고 생각됩니다 ㅎㅎ

말씀하신것 같은 요구사항이 발생하면, 통계에 대한 컬렉션을 받은 후 View 레벨에서 순서를 조정해주면 될 것 같아요!

2022-09-28 13:47 UTC, vagabond95 commented on src/main/java/lotto/model/Lottos.java
> +    }
다만 개수를 표현할 때 Long 타입이 사용해주셨는데요, 이는 stream 의 operator 로 인해 사용해주신 것 같은데 특별한 이유가 없다면 Int 정도로 제한해줘도 충분할 것 같습니다!

2022-09-28 13:47 UTC, vagabond95 commented on src/main/java/lotto/model/Lottos.java
> +        return lottos;
Collections.unmodifiableList(...) 를 활용하시면 read - only 콜렉션만 리턴할 수 있습니다. 참고만 부탁드려요~

2022-09-29 07:10 UTC, vagabond95 approved these changes
코멘트 의도대로 잘 반영해주셨고, 추가로 리뷰를 부분은 보이지 않아서 2단계도 머지하도록 하겠습니다~!

2022-09-29 07:10 UTC, merged