Step1 문자열 계산기
next-step/java-lotto pull request #2500
Opened 2022-09-27 18:19 UTC by ssw207

2022-09-29 22:21 UTC, lxxjn0 requested changes
승우님, 미션 진행하시느라 수고하셨습니다 👍🏼 

몇 가지 피드백 남겼으니 한번 확인하고 개선 부탁드릴게요 :)

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +public enum Operator {
enum을 활용해서 연산자의 로직을 멋있게 처리했네요 💯 💯

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +    DIVIDE("/", (result, num) -> result / num);
나눗셈의 경우 정수로 나누어 떨어지는 값만 한정한다고 되어있던데 그렇지 않은 경우에 대해서 예외를 발생시키거나 하는 식으로 처리해보는 것은 어떨까요?

추가로 num이 0일 경우 예상치 못한 예외가 발생할 것 같아요!! 이런 부분에 대해서도 처리해보면 좋을 것 같아요!!

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +    private IntBinaryOperator operate;
enum 클래스의 경우 필드를 final로 명시해서 불변으로 관리해도 좋을 것 같아요!!

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +    }
해당 로직은 parse나 isOperator에서 더 좋은 성능으로 사용하기 위함일까요?

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +    public int operate(Integer result, Integer number) {
매개변수 타입이 Wrapper class가 아니여도 될 것 같아요!!

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +    private static final Map<String, Operator> operatorMap;
메서드나 필드 명에는 불용어를 쓰기를 지양하고 있어요. 추후 자료구조의 변경 등에 있어서 유연하기 위함이죠. 만약 해당 상수를 관리하고 싶다면 CACHE 등의 용어를 활용해도 좋을 것 같습니다!! 추가로 상수의 경우 대문자로 명명해주세요 :)

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +    }
이펙티브 자바에서는 정적 팩토리 메서드에 대한 몇 가지 네이밍을 제안하고 있는데, 이러한 보편적인 네이밍을 따르면 사용자가 메서드를 사용할 때 이름만 보고 행위를 유추할 수 있어서 좋은 것 같아요!!

https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +        return operatorMap.get(code) != null;
Map이 제공하는 `containsKey()` 메서드를 사용해도 좋을 것 같아요 👍🏼

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/CalculateInfo.java
> +}
해당 인터페이스는 어떠한 행위를 수행시키려는 목적으로 작성하였을까요? 단순히 인터페이스 명을 봤을 때는 계산정보 인데 계산정보가 계산을 진행한다는 것이 어색한 것 같아요. 

그리고 실제로 해당 인터페이스를 구현한 NumberValue나 OperatorValue는 각각 하는 행위가 달라요. 인터페이스는 명세에 따라 내부적인 동작이 다를 경우 유연하게 사용할 수 있는데 현재는 두 클래스에서 인터페이스 명세의 행위 자체가 달라지는 느낌이에요.

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/CalculateResult.java
> +public class CalculateResult {
클래스 명을 보면 계산 결과를 저장하는 로직으로 보여지는데 실제는 계산하기 위한 값들과 연산까지 진행하고 있어요. 객체가 가지는 책임과 행위가 적절히 분리되었는지 한번 더 살펴보면 좋을 것 같아요!!

2022-09-29 22:21 UTC, lxxjn0 commented on src/main/java/calculator/domain/Calculator.java
> +    }
해당 로직을 보면 계산정보(CalculateInfo)에 계산결과(calculateResult)를 넘겨줘서 계산을 진행하도록 시키고 있어요! 정보(피연산자, 연산자)가 연산을 직접 수행하는 것도 약간 일반적으로 우리가 생각하는 흐름에서 어색함이 느껴지고 그러기 위해서 result 객체를 넘겨주는 것 또한 어색한 것 같아요.

코드의 구조를 짜면서 인터페이스가 추가되었다기 보다는 약간 인터페이스를 활용하기 위해서 짜맞춰진 코드처럼 보여져요. 간단한 계산기 로직이라면 좀 더 간결하고 명확하게 로직을 작성할 수 있을 것 같아요!! 

코드는 비즈니스가 보여지는 코드가 좋은 코드라고 생각합니다. 계산기라면 단순하게 계산기에 숫자를 전달해서 연산이 진행되는 것을 기대할 거에요. 코드 레벨에서 조금 더 들어간다면 연산자에게 피연산자 2개를 전달해서 연산을 진행하는 것도 포함될 수가 있죠. 그런 관점에서 지금의 코드는 그런 비즈니스 로직이 보이기엔 코드를 따라가기가 어려운 것 같아요!!

승우님께서 한번 더 코드를 고민해보고 누군가 읽었을 때 계산기의 비즈니스 로직이 자연스럽게 드러나고 따라가지도록 한번 개선해보면 좋을 것 같아요!!

2022-10-02 14:27 UTC, ssw207 commented on src/main/java/calculator/domain/CalculateType.java
> +public enum CalculateType {
앗 리팩토링중에 삭제해야했는데 같이 커밋된것 같네요

2022-10-02 14:39 UTC, ssw207 commented on src/main/java/calculator/domain/Operator.java
> +    }
맞습니다

2022-10-02 14:47 UTC, ssw207 commented on src/main/java/calculator/domain/Operator.java
> +    private static final Map<String, Operator> operatorMap;
"상수의 경우 대문자로 명명해주세요" 말씀하시분 부분이 operatorMap 를 말씀하시는 걸까요??
불변 클래스가 아닌 이상 static final로 선언되었더라도 내부 값이 변경 될 수 있으니 객체의 경우는 final로 선언됐더라도 변수처럼 카멜케이스로 짓는게 적절하다고 생각해서 카멜 케이스로 지었는데 
혹시 리뷰어님이 말씀하신 상수가 operatorMap가 맞다면 리뷰어님은 이부분에 대해서 어떻게 생각하실지 궁금합니다

2022-10-02 15:40 UTC, ssw207 commented on src/main/java/calculator/domain/CalculateResult.java
> +    private int result = 0;
초기값이 할당되지 않은 상태에서 연산이 있는 경우를 대비해 초기값 0을 할당했는데요.

현재 요구사항에서 계산기가 실행 될 떄 계산된 값을 필요로 하지 않고 
계산기 특성상 최초 시작시 특정 값으로 시작해야 하는 경우가 없을 것 같은데
생성자를 통해 외부에서 값을 받는건 오히려 가독성이 떨어지지 않을까요?

계산기 클래스를 처음 사용하는 사용자는 생성시 초기화 값이 뭔지 불필요하게 확인하고 입력해야 해서 오히려 사용하기 불편할것 같아서요. 
만약 요구사항이 변경되면 그때 초기값을 주입받도록 변경하는게 더 가독성이 좋을것 같은데 리뷰어님 생각은 어떠실까요?

2022-10-02 15:48 UTC, ssw207 commented on src/main/java/calculator/domain/CalculateInfo.java
> +}
리팩토링 하면서 해당 클래스 삭제했습니다

2022-10-02 15:49 UTC, ssw207 commented on src/main/java/calculator/domain/CalculateResult.java
> +public class CalculateResult {
리팩토링 하면서 변경했습니다

2022-10-02 15:49 UTC, ssw207 commented on src/main/java/calculator/domain/Calculator.java
> +    }
수정했습니다

2022-10-04 17:01 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
> +    private static final Map<String, Operator> operatorMap;
사실 저도 승우님께서 말씀하신 부분이 어느정도는 맞다고 생각합니다. 

예로 Kotlin에서는 자바와 다르게 상수처럼 사용하는 값을 const 제약어를 붙여서 사용하는데, 이때 기본 타입(Integer, Long, String 등)을 제외한 나머지 클래스 타입에는 const를 붙일 수 없습니다. 즉 말씀하신대로 가지고 있는 값 자체를 불변하게 관리하지 못한다는 이유 때문이 아닐까? 생각을 하긴 합니다 ㅎㅎ

자바에서도 말씀하신 부분이 맞지만 보편적으로 final static을 붙인 필드는 전역에서 값의 재할당이 불가능하기 때문에 상수로 보고 상수 네이밍을 적용하는 것 같아요!! 자바의 특성상 값의 재할당이 불가능하다고 하더라도 내부적으로 가지고 있는 참조 값들에 대해서 변경이 가능하긴 하지만 1차원 표면적으론 상수의 성격을 가지고 있어서 그렇게 쓰는 것 아닐까? 생각합니다.

그래서 보편적으로 상수 네이밍을 쓴다 정도로만 이해해주셔도 좋을 것 같아요 :) 그래도 승우님께서 꼼꼼하고 깊게 생각을 하셔서 저도 다시 한번 이런 부분에 대해서 생각할 수 있는 계기가 되었네요 👍🏼

2022-10-04 18:25 UTC, lxxjn0 requested changes
승우님, 피드백 반영하느라 수고하셨습니다 👍🏼 

전체적으로 잘 마무리해주셨는데 마지막으로 한 가지만 더 개선해보고 미션을 마무리하면 좋을 것 같아서요!! 현재 코드를 보면 전체적으로 메서드가 하나의 행위가 아닌 여러 행위를 하는 것으로 보여집니다. 또한 메서드가 단순히 보여지는 이름 이상으로 숨겨진 행위들을 많이 하고 있어요.

예를 들어 객체에 add라는 메서드는 원소를 추가하거나 무엇인가를 더한다는 의미를 가지고 그러한 행위를 할 것이라고 예상할 수 있어요. 하지만 실제 내부에서는 어떤 경우에는 더하고 다른 경우에는 패스하는 식으로 로직이 짜져 있습니다. 

public 메서드는 외부에 공개되는 메서드, 즉 누구나 접근하고 사용할 수 있는 메서드입니다. 그런 만큼 누구나 예상할 수 있고 이름에 적합한 로직으로 구현되고 동작해야 해요.

이번 코드에서 이러한 점들이 조금 아쉬웠는데 이 부분만 한 번 더 고민하고 개선해보고 미션 마무리하는 걸로 할게요!! :)

2022-10-04 18:25 UTC, lxxjn0 commented on src/main/java/calculator/domain/Calculator.java
> +    public void calculate(InputValue inputValue) {
해당 메서드의 경우에도 메서드의 행위와 이름이 적절하지 않은 것 같아요!! 계산해야 할 데이터를 넣어주는 메서드와 실제로 적제된 데이터들을 기반으로 계산을 하는 메서드를 분리하는 것이 어떤가요??

지금 메서드는 '계산을 하겠다'라는 행위를 명시하고 있는데 실제로 로직은 계산을 할 수도, 안할 수도 있습니다. 유효하지 않은 상황에 대해서 계산을 하지 않고 아무 행위도 안한다면 괜찮은데 여기서는 계산이 아닌 연산자를 추가하는 다른 행위를 하고 있죠. 이런 경우 public 메서드를 사용하는 사용자는 내부 구현을 보지 않고는 메서드의 동작을 예상할 수 없습니다.

메서드의 행위는 한 가지만 하도록, 두 가지 이상을 하는 그리고 숨겨진 행위를 하는 메서드는 분리를 해서 명확히 구분하면 좋을 것 같아요!!

2022-10-04 18:25 UTC, lxxjn0 commented on src/main/java/calculator/domain/Operator.java
>      }
라이브러리 코드가 아닌 만큼 deprecated 된 메서드는 삭제하는 것이 더 적절하지 않나 생각합니다 :)

2022-10-04 18:25 UTC, lxxjn0 commented on src/main/java/calculator/service/CalculatorService.java
> +public class CalculatorService {
현재 로직 수준에서는 따로 Service를 두지 않고 구현하는 것을 추천드릴게요! 단순한 서비스 로직 정도는 따로 적합한 클래스에 빼서 구현할 수 있을 것 같아요!!

2022-10-05 04:21 UTC, ssw207 commented on src/main/java/calculator/domain/Operator.java
>      }
넵 리팩토링하면서 Deprecated 처리후 완료되면 삭제하려고 했는데 누락된것 같네요

2022-10-05 15:52 UTC, ssw207 commented on src/main/java/calculator/domain/Calculator.java
> +    public void calculate(InputValue inputValue) {
int 연산하는 calculate 메소드와 Operator를 객체에 넣는 set 메소드로 분리했습니다.

2022-10-05 15:52 UTC, ssw207 commented on src/main/java/calculator/domain/CalculateResult.java
>  public class CalculateResult {
클래스 삭제하고 int타입으로 처리하게 바꿨습니다

2022-10-05 16:02 UTC, ssw207 commented on src/main/java/calculator/Application.java
> +            input.type().CalculatorOperate(calculator, input);
process 라는 메서드명이 모호한거 같고 내부에서 type 변환과 type의 연산을 실행하는게 여러가지 일을 하는게 아닌가.. 싶어서 타입에 따른 계산기 연산을 실항하는 로직을 밖으로 분리해는데 어느쪽이 적절한 방법일까요??

2022-10-05 22:10 UTC, lxxjn0 approved these changes
승우님, 피드백 반영하시느라 정말 수고하셨습니다!! 👍🏼 

간단하게 피드백 남겨뒀고 질문에 대해서도 피드백에 의견 남겨두었습니다 :) 이번 단계는 여기서 마무리하고 다음 단계 진행해주세요 :)

2022-10-05 22:10 UTC, lxxjn0 commented on src/main/java/calculator/domain/Calculator.java
> +    public void set(Operator operator) {
push라는 이름이 좀 더 자연스러울 것 같아요!! set은 setter의 느낌이 조금 나는 듯 합니다!!

2022-10-05 22:10 UTC, lxxjn0 commented on src/main/java/calculator/domain/Input.java
> +    public InputType type() {
메서드 명은 동사형으로 작성하면 좋을 것 같아요!! 지금은 `findType`과 같은 이름도 자연스러워 보이네요!! :)

https://newwisdom.tistory.com/96

2022-10-05 22:10 UTC, lxxjn0 commented on src/main/java/calculator/Application.java
> +            input.type().calculatorOperate(calculator, input);
InputType에서 타입에 맞게 처리 로직을 실행시키고자 한다면 지금의 로직으로 진행해도 괜찮을 것 같아요!!

만약 그렇지 않다면 InputType이 필드로 가지는 실행 로직을 없애고 Calculator에 InputType을 넘겨서 분기로 처리하면 될 것 같은데 후자가 좀 더 자연스럽긴 한데 지금 작성해주신 로직도 나쁘진 않은 것 같아서 원하는 방향으로 진행하시면 될 것 같아요!! 👍🏼

2022-10-05 22:11 UTC, merged

2022-10-05 23:48 UTC, ssw207 commented on src/main/java/calculator/domain/Input.java
> +    public InputType type() {
강의 내용에 빌더의 경우 명사형으로 지으라는 내용을 보고 
새로운 InputType을 만들어 반환하니까 빌더라고 생각해서 명사형으로 지었습니다.
혹시 이부분에  대해서 어떻게 생각하실까요?? 
https://edu.nextstep.camp/s/DVVUSLFe/ls/yD1TBIWo

2022-10-05 23:54 UTC, ssw207 commented on src/main/java/calculator/Application.java
> +            input.type().calculatorOperate(calculator, input);
처음에 아래같은 형태로 작업했는데요.
의미상 계산기에 입력값으로 처리를 한다 라고 읽히는것 같긴한데..
내부에서 input을 InputType으로 변환 하는 작업과 inputType에 따른 기능을 실행하는 작업 두가지 일을 하는게 아닌가?
this로 Calculator를 받게 되어있는데 일반적으로 사용하는 방식이 아니라 가독성이 떨어지지  않을까?
하는생각에 지금처럼 바꿨습니다.

if 분기처리도 고려해봤는데, if문을 쓰면 처음 리뷰하신것처럼 하나의 메소드에서 입력 또는 계산 하는 작업을 같이하게 되서 같은 문제가 있는거 아닌가.. 하는 생각이 들어 if문을 제거하고 inputType에 조건에 따른 로직을 위임하는 형식으로 작업했습니다.

```
public class Application {

    public static void main(String[] args) {
        List<Input> convert = MessageConverter.convert(InputView.read());

        Calculator calculator = new Calculator();

        for (Input input : convert) {
            calculator.process(input);
        }

        int result = calculator.getResult();

        System.out.println(result);
    }
}



public class Calculator {
  public void process(Input input) {
        InputType indexType = InputType.from(input);
        indexType.operate(this, input);
    }
}
```