로또미션 - Step3 로또 (수동)
next-step/java-lotto pull request #2505
Opened 2022-09-29 17:25 UTC by devcs96

안녕하세요 지훈 리뷰어님 리뷰 부탁드립니다! 

개발하면서 의문을가졌던 부분은 코멘트 달아두었습니다 감사합니다 🙇🏻

2022-09-29 17:35 UTC, devcs96 commented on src/main/java/lotto/model/LottoBall.java
> +
로또 추첨 번호를 감싼 wrapping class인데 , 문제가 bonusBall일떄와 bonus Ball 이 아닐떄를 구분해서 사용하려고 , `isBonusBall `필드를 추가하였는데, 

최초에 랜덤하게 로또 번호를 추첨할떄는 `isBonusBall `필드를 `false `로 초기화하고 , 
사용자가 보너스볼을 입력할떄만 `true` 로 초기화되도록 하였는데,

문제가 발생한 부분이 equals , hashCode method로 비교시 ,  최초에 뽑았던 로또 번호랑 사용자가 입력한 보너스볼이랑 번호가 같아도 , isBonusBall필드값이 달라서 다른 객체로 비교되는 문제가 있어서,
로또 번호 필드만  equals , hashCode method를 재정의하였는데, 이렇게 구현하는 방식이 올바른 방식인지 궁금합니다!

비즈니스 로직을 위해서 객체의 모든 필드가 아닌 특정 필드부분만 equals , hashCode method를 재정의해도될까요?

2022-09-29 17:35 UTC, devcs96 commented on src/main/java/lotto/model/LottoBall.java
> +
아니면 설계에서부터 문제가 있었는지 고민이됩니다ㅠ

2022-09-30 12:27 UTC, vagabond95 commented on src/main/java/lotto/model/MatchNumber.java
> +        if (isSecondRank(matchNumbers, lottoBalls)) {
만약 다른 등수에도 보너스볼 개념이 추가된다면, 계속해서 특정 등수를 체크하는 if 문이 추가되어야하는 구조가 될 것 같은데요!
특정 등수인지 여부를 검사하지 않도록 (보너스볼 변경사항에 유연하도록) 리펙토링해볼 수 있을까요?

2022-09-30 12:27 UTC, vagabond95 commented on src/main/java/lotto/model/LottoBall.java
> +    private final boolean isBonusBall;
질문 주신 부분이라 추가 코멘트 남겨보면,

LottoBall 에서 보너스볼 여부를 구별해줄 필요가 있을까 고민해보면 좋을 것 같아요.
결국 어디선가는 보너스볼에 대한 정보를 알고 있으면 되는 것이므로 더 상위레벨 객체에서 보너스볼을 '따로' 저장하고 있으면 괜찮지 않을까요? :)

2022-09-30 12:27 UTC, vagabond95 commented on src/main/java/lotto/model/LottoBall.java
> +
코드에 코멘트 남겼습니다~!

2022-09-30 12:27 UTC, vagabond95 commented
3단계는 (수동) 에 대한 스펙이 아니라 2등 (보너스볼) 스펙에 대한 구현입니다! 
맞게 구현하신 것으로 보이는데, 혼동 방지를 위해 참고차 공유드려요 :)

2022-09-30 12:29 UTC, vagabond95 requested changes
LottoBall 클래스로 한번 더 구별지어주는 시도 좋은 것 같아요 👍 

질문주신 내용을 비롯하여, 개선해보면 좋을 점에 대해 코멘트 남겼는데요.
확인 후 리뷰요청 부탁드립니다!

2022-10-01 05:05 UTC, devcs96 commented on src/main/java/lotto/model/MatchNumber.java
> +        if (isSecondRank(matchNumbers, lottoBalls)) {
같은 count값을 가지면 금액순서대로 정렬해서 보너스볼을 가진 경우 더 높은 상금금액을 받도록 구현해보았습니다!

2022-10-01 05:06 UTC, devcs96 commented on src/main/java/lotto/model/LottoBall.java
> +    private final boolean isBonusBall;
좋은 피드백 감사합니다!

2022-10-01 05:06 UTC, devcs96 commented on src/main/java/lotto/model/LottoBall.java
> +
step3 미션이름변경하였습니다! 헷갈렸네요 ㅜ

2022-10-02 07:24 UTC, vagabond95 approved these changes
코멘트의 의도대로 잘 반영해주셨네요 👍 

보너스볼 개선 사항을 통해 전달드리고 싶었던점은, 구현이 잘 안풀릴때는 한 depth 바깥에서 생각하면 쉽게 풀리는 경우가 있다는 것이었어요 :)

3단계는 머지하도록 하겠습니다. 마지막 단계도 화이팅이십니다!

2022-10-02 07:24 UTC, merged