1단계 - 문자열 계산기
next-step/java-lotto pull request #2507
Opened 2022-09-30 04:18 UTC by kingkk31

안녕하세요, 리뷰 요청 드립니다!
(git user 정보가 꼬였는지 이번 커밋들에 kingkk31 말고도 다른 사용자 정보가 같이 기재되어있는데요, 다음 단계부터는 이 점 주의하겠습니다.)

2022-10-01 13:28 UTC, kingkk31 commented
@ksy90101 안녕하세요~ 제 PR에 매칭된 리뷰어로 알고 있는데요, 리뷰가 늦어지는거 같아 혹시 누락되었을까봐 코멘트 하였습니다!

2022-10-02 03:06 UTC, ksy90101 commented on src/main/java/calculator/Calculator.java
> +public class Calculator {
enum과 함수형 인터페이스를 사용하면, 훨씬 더 깔끔한 코드가 될듯 한데, 한번 만들어 보면 어떨까요?
https://rutgo-letsgo.tistory.com/167
위 글을 한번 참고해보세요~

2022-10-02 03:07 UTC, ksy90101 commented on src/main/java/calculator/FormulaCalculator.java
> +        Integer leftOperand = null;
Integer를 쓰지 말고 int를 써서 0부터 계산하게 하는게 더 좋을듯 한데요 :)

2022-10-02 03:08 UTC, ksy90101 commented on src/main/java/calculator/FormulaCalculator.java
> +    }
이 부분은 제가 위에서 드린 부분을 참고하면 쉽게 수정할 수 있을듯 하네요!

2022-10-02 03:08 UTC, ksy90101 commented on src/main/java/calculator/FormulaCalculator.java
> +public class FormulaCalculator {
해당 클래스에 책임이 너무 많은거 같네요.
결국 이건, 계산만 하면 되는데, 입력으로 들어온 숫자를 split해서 convert를 한다거나, 숫자를 검증한다거나.
한번, 책임을 분리해보면 어떨까요?

2022-10-02 03:09 UTC, ksy90101 commented on src/main/java/calculator/FormulaCalculator.java
> +        Queue<String> splitFormula = getSplitFormula(formula);
혹시, 우선순위를 생각하신건가요?

2022-10-02 03:10 UTC, ksy90101 commented on src/test/java/calculator/FormulaCalculatorTest.java
> +    }
테스트 케이스가 실제 하나인데, ParameterizedTest를 사용하신 이유가 있나요?

2022-10-02 03:11 UTC, ksy90101 requested changes
안녕하세요 :) 리뷰가 조금 늦었네요 ㅠㅠ
제가 리뷰 알림을 놓쳤습니다 ㅠㅠ
간단한 피드백을 남겼으니, 한번 수정해보시면 좋을듯 합니다.
질문이 있다면 자유롭게 DM주세요~

2022-10-02 04:09 UTC, kingkk31 commented on src/main/java/calculator/FormulaCalculator.java
> +        Integer leftOperand = null;
@ksy90101 첫 피연산자는 계산할 연산자가 없어서 null 일 경우를 첫 피연산자로 구분하고 그 이후부터 연산자와 피연산자를 하니씩 뽑아내는 방식이어서 null을 사용했었습니다. 전반적으로 로직을 변경하여 말씀해주신 int 0 적용해보겠습니다!

2022-10-02 04:10 UTC, kingkk31 commented on src/main/java/calculator/FormulaCalculator.java
> +        Queue<String> splitFormula = getSplitFormula(formula);
@ksy90101 앞에서부터 차례로 계산하면 되는 상황이니 우선순위는 따로 생각하지 않습니다. 그래서 Queue를 사용한거구요.

2022-10-02 04:11 UTC, kingkk31 commented on src/test/java/calculator/FormulaCalculatorTest.java
> +    }
@ksy90101 사실 여러개의 테스트 케이스를 넣으려고 했었는데 귀찮아서 하나씩만 넣었네요;; 테스트 케이스를 추가하거나 @Test 로 변경하겠습니다.

2022-10-02 06:44 UTC, kingkk31 commented
@ksy90101 안녕하세요, 피드백 주신 내용을 토대로 리펙토링 하였습니다! FormulaCalculator 의 연산 외의 책임을 분리하는데 중점을 뒀으며, 질문하신 사항은 코멘트로 답변드렸습니다. 다시 리뷰 부탁드립니다!

2022-10-02 07:02 UTC, ksy90101 commented on src/main/java/calculator/Operator.java
> +            return leftOperand / rightOperand;
나누기에 분모로 0이 들어오면 어떻게 될까요!?

2022-10-02 07:26 UTC, kingkk31 commented on src/main/java/calculator/Operator.java
> +            return leftOperand / rightOperand;
@ksy90101 아 나눗셈이 정수로 나눠지니까 무심코 그 조건을 빼먹었네요;; 추가하였습니다.

2022-10-03 12:08 UTC, ksy90101 commented on src/main/java/calculator/FormulaCalculator.java
> +        Queue<String> splitFormula = getSplitFormula(formula);
앗 넵 :)

2022-10-03 12:11 UTC, ksy90101 commented on src/main/java/calculator/FormulaElements.java
> +    private final Queue<String> formulaElementQueue;
Collection에선 굳이 이름을 사용할 필요는 없어보여요.
충분히 복수형으로 작성하면 Collection이라는것을 알수 잇을듯 합니다

2022-10-03 12:13 UTC, ksy90101 commented on src/main/java/calculator/FormulaElements.java
> +    private final Queue<String> formulaElementQueue;
Deque를 사용하는것이였더면, Deque를 처음부터 타입으로 지정하면 어떨까요?
어차피 Deque도 추상 인터페이스이니깐요 :)

2022-10-03 12:13 UTC, ksy90101 commented on src/main/java/calculator/Operator.java
> +    public abstract int apply(int leftOperand, int rightOperand);
추상메서드도 좋지만, 요즘엔 함수형 인터페이스를 많이 사용하는 편입니다.
함수형 인터페이스로 해보시면 어떨까요?

2022-10-03 12:14 UTC, ksy90101 commented on src/main/java/calculator/Operator.java
> +    }
2depth이네요.
근데, 좀 더 잘 작성해볼수 있는데요.
1. Stream의 FindFirst를 찾아서 조회한다.
2. Map을 이용해 캐싱해놓고 찾는다

한번 두가지 방법중 하나로 변경해보시면 어떨까요?

2022-10-03 12:15 UTC, ksy90101 commented on src/main/java/calculator/Operator.java
> +    private final String operatorStr;
Str이라는 타입은 잘 작성하지 않습니다.
저같은 경우엔 이런 케이스인 경우에 Symbol이라는 단어를 사용하긴 하는데요. 한번 이름을 다시 지어보면 어떨까요?

2022-10-03 12:15 UTC, ksy90101 commented on src/test/java/calculator/FormulaCalculatorTest.java
> +    @ValueSource(strings = {"", "  "})
여담이지만,     @EmptySource 라는것도 있습니다!

2022-10-03 12:16 UTC, ksy90101 commented on src/test/java/calculator/FormulaCalculatorTest.java
> +    }
이 테스트는 여기의 테스트가 맞을까요?
Operator에 있어야 하지 않을까 생각해봅니다 ㅎㅎ

2022-10-03 12:16 UTC, ksy90101 commented on src/main/java/calculator/Operator.java
> +public enum Operator {
이거에 대한 테스트 코드도 작성해보면 어떨까요?

2022-10-04 11:10 UTC, kingkk31 commented on src/main/java/calculator/Operator.java
> +    public abstract int apply(int leftOperand, int rightOperand);
@ksy90101 추상클래스/메소드를 지양하는 추세다보니 abstact 를 사용할때마다 항상 걱정부터 되는데, 좋은 방법을 알게 되었네요! functional interface 필드를 추가해 생성자로 받아, 기존의 apply 메소드는 이를 호출하는 public 메소드로 변경하였습니다.

2022-10-04 11:10 UTC, kingkk31 commented on src/main/java/calculator/Operator.java
> +    }
@ksy90101 아차 놓쳤네요 객체지향생활체조를 어겼군요;; 1번 방식으로 수정하였습니다.

2022-10-04 11:11 UTC, kingkk31 commented on src/main/java/calculator/Operator.java
> +    private final String operatorStr;
@ksy90101 네이밍은 항상 어렵네요 마땅한 단어들이 바로바로 안떠오르네요ㅎㅎ;;

2022-10-04 11:12 UTC, kingkk31 commented on src/main/java/calculator/Operator.java
> +public enum Operator {
@ksy90101 enum 이라 별 생각없이 넘겼는데 생각해보니 충분히 테스트를 작성할 수 있고, 테스트 작성 요구사항에 포함되겠네요. 추가하였습니다.

2022-10-04 11:13 UTC, kingkk31 commented on src/test/java/calculator/FormulaCalculatorTest.java
> +    }
@ksy90101 Operator 테스트 코드 추가 시 위 내용도 기재했습니다. 다만 이 테스트는 '0으로 나누는 연산을 포함하는 수식에 대한 테스트 '라는 의미를 가지고 싶어서 테스트명만 변경하고 나뒀습니다.

2022-10-04 11:14 UTC, kingkk31 commented
@ksy90101 안녕하세요, 피드백 주신 내용 반영 및 코멘트하였습니다. 다시 리뷰 부탁드립니다!

2022-10-04 11:24 UTC, ksy90101 commented on src/main/java/calculator/Operator.java
> +    }
메서드가 위에 있는게 어색하네요 :) 적절한 위치로 두면 어떨까요?

2022-10-04 11:25 UTC, ksy90101 approved these changes
안녕하세요 :)
1단계 미션 너무 고생 많으셨습니다 💯 
전체적으로 잘 구현해주셔서 1단계는 이만 머지하도록 하겠습니다~
그럼 2단계때 다시 뵐게요~ 💯

2022-10-04 11:25 UTC, merged