java-lotto step1
next-step/java-lotto pull request #2516
Opened 2022-10-01 16:52 UTC by wonsakku

안녕하세요. 앞으로 java-lotto 좋은 리뷰 부탁드립니다~

2022-10-02 08:43 UTC, csh0034 requested changes
안녕하세요. 원식님!
로또 미션을 함께하게 된 최승훈입니다. 

1단계 문자열 계산기 구현 관련하여 
몇가지 피드백 남겨두었는데 확인해주시고
다시 리뷰 요청 부탁드립니다!

혹시 코멘트가 이해 안가시거나 추가로 궁금하신 사항 있으시면
편하게 DM 주세요 😄

2022-10-02 08:43 UTC, csh0034 commented on src/main/java/step1/OperatorFactory.java
> +public class OperatorFactory {
심플 팩토리 잘 적용해주셨네요 👍

String 타입의 operation 과 Operator 타입을 가지는 Enum 을 선언하여 if return 구조를 개선해볼수도 있을것 같습니다.

또다른 방법으론 하단과 같이 Map 을 활용해볼수도 있겠네요 🙂

```java
private static final Map<String, Operator> OPERATORS = Map.of(
    "+", AddOperator.getInstance(),
    "-", SubstractOperator.getInstance(),
    "*", MultiplyOperator.getInstance(),
    "/", DivideOperator.getInstance()
);

public static Operator getInstance(String operation) {
    return OPERATORS.get(operation);
}
```

2022-10-02 08:43 UTC, csh0034 commented on src/main/java/step1/StringCalculator.java
> +public class StringCalculator {
유틸성 클래스로 잘 작성해주셨습니다.

인스턴스 생성이 필요하지 않으므로 class 선언에 final 추가 및 생성자를 private 으로 만들어
확장이 불가능한 형태로 선언해주시면 명확할것 같습니다.

추가로 생성자 내부에서 throw 를 한다면 내부에서 인스턴스화도 막을수 있습니다.

`java.util.Objects` 같이 보시면 도움되실것 같습니다. 😃

2022-10-02 08:43 UTC, csh0034 commented on src/main/java/step1/StringCalculator.java
> +//    private static final String[] OPERATIONS = {"+", "-", "*", "/"};
불필요한 주석은 삭제해주세요!

2022-10-02 08:43 UTC, csh0034 commented on src/main/java/step1/StringCalculator.java
> +    private static final List<String> OPERATIONS = Arrays.asList("+", "-", "*", "/");
`List.of("+", "-", "*", "/")`

2022-10-02 08:43 UTC, csh0034 commented on src/main/java/step1/StringCalculator.java
> +    private static void validateInput(String[] split) {
2 + 3 * 4 / 2
(숫자 공백 연산자 공백)반복 숫자

상단과 같은 패턴이기 때문에 정규식을 통해 검증해볼수도 있겠네요!

`Pattern.compile("^(\\d+[  ][-+*/][  ])+\\d+$");`

2022-10-02 08:43 UTC, csh0034 commented on src/main/java/step1/StringCalculator.java
> +        String[] split = input.split(DELIMITER);
예를들어 tokens 등의 명확한 변수명은 사용해보는건 어떨까요?

2022-10-02 08:43 UTC, csh0034 commented on src/main/java/step1/StringCalculator.java
> +        while(!isEnd(arrayIndex, split.length)){
2씩 증가하는 for 문을 사용해보면 좋을것 같습니다.

2022-10-02 08:43 UTC, csh0034 commented on src/test/java/step1/CalculatorTest.java
> +    void 덧셈_테스트(){
테스트 이름을 `@DisplayName` 을 통해 표현해보는건 어떨까요?

2022-10-02 08:43 UTC, csh0034 commented on src/test/java/step1/StringCalculatorTest.java
> +    void 여러_숫자_덧셈_테스트(){
`@ParameterizedTest` 와 `@CsvSoruce` 를 활용해보면 좋을것 같습니다.


```java
@ParameterizedTest
@CsvSource(value = {
    "10 + 10 + 10 + 10 + 10 = 50",
    "20 + 20 + 20 + 20 + 20 = 100",
    "10 + 20 + 30 + 40 + 50= 150"
}, delimiter = '=')
```

2022-10-02 08:49 UTC, csh0034 commented
추가로 교육 과정진행하는 동안 아래 사항들 적용 부탁드려요.

1. commit 로그 요구사항 적용

현재 구현내용이 한 커밋에 되어있네요.
기능별로 분리하여 커밋하며 메세지의 경우 하단 링크를 참조하여 적용해주세요
[AngularJS Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)

2. 패키지구조 스텝별로 구분 X

 각 미션의 1단계 이후엔 본 미션이 진행되며 각 스텝별로 요구사항이 추가되므로
step 별 구분이 아닌 구현 기능별로 나눠주시면 좋을것 같습니다.

ex) src/main/java/caculator, src/main/java/lotto


3. IDE 의 정렬기능 이용

현재 코드 정렬이 안되어 있습니다. 🥲 
인텔리제이의 경우 code formatting 단축키(Windows : Ctrl + Alt + L. Mac : ⌥ (Option) + ⌘ (Command) + L.)를
사용하여 정렬후 커밋 부탁드려요.

2022-10-02 14:30 UTC, wonsakku commented on src/main/java/step1/StringCalculator.java
> +    private static void validateInput(String[] split) {
정규식은 항상 필요할 때마다 검색해서 복붙하는 식이었는데, 이참에 한번 재대로 공부해봐야 겠네요.

2022-10-02 14:31 UTC, wonsakku commented on src/main/java/step1/StringCalculator.java
> +        while(!isEnd(arrayIndex, split.length)){
while문을 잘못쓰면 무한루프를 돌 수 있기 때문인가요?

2022-10-02 14:34 UTC, wonsakku commented on src/main/java/step1/OperatorFactory.java
> +public class OperatorFactory {
enum에는 항상 문자열이나 원시값만 넣어봤었는데 그러한 방식으로도 사용이 가능하군요!
그리고 enum 뿐만 아니라 다른 방안에 대해서도 코멘트 남겨주셔서 감사합니다.

2022-10-02 14:42 UTC, wonsakku commented on src/main/java/step1/AddOperator.java
> +    public static Operator getInstance() {
싱글톤을 그냥 공식처럼 기억하고 있었는데, 이런 부분도 고려할 수 있네요

2022-10-02 15:30 UTC, wonsakku commented on src/main/java/step1/Operator.java
> +public interface Operator {
새로운 기능 하나 배워갑니다. 
구글링해보면서 이에 맞게 코드를 수정해보았지만, 아직 제가 이 기능에 대해 이해가 많이 부족하네요...
시간을 들여가면서 공부해보겠습니다~

2022-10-02 16:07 UTC, wonsakku commented on src/test/java/calculator/StringCalculatorTest.java
> +    }
정상적인 케이스와 예외가 발생하는 케이스를 ParameterizedTest를 사용해서 테스트할 수 있는 방법은 있을까요?

2022-10-03 06:32 UTC, csh0034 commented on src/main/java/step1/StringCalculator.java
> +        while(!isEnd(arrayIndex, split.length)){
while 문 사용시 말씀해주신 부분도 주의 해야하지만
이경우엔 while 문의 조건과 내부에서 arrayIndex 즉, index 값을 활용하고 있으므로
초기식과 증감식을 지정할수있는 for 문이 적절해 보여서 리뷰 드렸습니다 😃

2022-10-03 06:38 UTC, csh0034 commented on src/test/java/calculator/StringCalculatorTest.java
> +    }
`[Clean Code] 9장 단위 테스트` 를 보면 테스트당 assert 하나 또는 테스트당 개념 하나로 설명합니다.
이는 단위 테스트는 하나의 개념만 테스트하여야 쉽게 파악할수 있기 때문인데요
추가로 테스트코드도 유지보수 대상이기때문이기도 합니다.

결론적으로 정상동작의 개념과 실패했을때의 개념을 분리하여 작성하는걸 추천드립니다.

2022-10-03 06:44 UTC, csh0034 approved these changes
리뷰내용 잘 반영해주셨네요 💯 
다음 단계 진행해주세요!

2022-10-03 06:44 UTC, csh0034 commented on src/main/java/calculator/Operator.java
> +    IntBinaryOperator operate();
전에 드렸던 리뷰는 작성해주셨던 Operator 와 IntBinaryOperator 가 동일했기 때문에
IntBinaryOperator 를 리턴타입으로 사용하는것이 아닌 AddOperator 가 IntBinaryOperator 를 구현해보는건 
어떤지에 대한 내용이었습니다.

하단과 같은 형태가 되겠네요
```java
public class AddOperator implements IntBinaryOperator
```
또는 `OperatorEnum` 안에 람다식을 사용해 표현해볼수도 있을것 같습니다.

2022-10-03 06:44 UTC, csh0034 commented on src/main/java/calculator/OperatorEnum.java
> +public enum OperatorEnum {
enum 타입이기 때문에 Enum 이라는 이름을 빼도 될것 같습니다. 🙂

2022-10-03 06:46 UTC, csh0034 commented
다음 단계 구현시엔 `commit 로그 요구사항` 을 확인하여 적용 해주세요!
ex) feat: Operator enum 추가, refactor: Operator 리턴타입 변경

2022-10-03 06:46 UTC, merged