Wonsakku step2
next-step/java-lotto pull request #2548
Opened 2022-10-05 16:21 UTC by wonsakku

java-lotto step2입니다.
이번 미션을 진행하면서 힘들었던 부분은 수익 통계를 어떻게 구현할지였습니다.
3개가 일치하는 것은 몇 개이며,
4개가 일치하는 것은 몇 개이며,
5개가 일치하는 것은 몇 개이며,
6개가 일치하는 것은 몇 개인지를 통계내는 것이 어려웠습니다. 

이 부분에 대해서 한 수 부탁드리겠습니다.

2022-10-06 07:16 UTC, csh0034 requested changes
안녕하세요. 원식님.
2단계 잘 구현해주셨네요 👍 

코멘트 남겨두었는데 확인후에 다시 요청
부탁드려요!

2022-10-06 07:23 UTC, csh0034 commented
### 도메인 설계 관련

"객체지향은 현실 세계를 모방한 것이 아니라 현실 세계를 참조하여 새로운 세상을 탄생시키는 것이다."
객체지향의 사실과 오해(조영호) 에 나오는 구절입니다.

현재 현실세계에 로또구매를 표현하기위해 로또, 로또구매자, 로또판매점등을 표현해주셨는데요.
이렇게 모방하기보단 참조하여 새롭게 만들어 보는걸로 고민해보시면 좋을것 같습니다.

모방이 아니라고 하는건 예를 들어 콘솔로 로또 프로그램을 실행한다면 판매점은 
작성해주신 어플리케이션이 되며 로또구매자는 콘솔에 값을 입력하는 행위가 되기 때문입니다.

처음접하기엔 난해할수 있지만 고민해보시면 도움 되실것 같습니다. 😄

2022-10-09 08:16 UTC, wonsakku commented on src/main/java/lotto/strategy/RandomNumberGenerateStrategy.java
> +    private final int NUMBER_MIN_BOUND = 1;
상수로 사용한다면 꼭 static이 있어야 하나요?

2022-10-09 08:20 UTC, wonsakku commented on src/main/java/lotto/domain/MatchingResult.java
> +    private List<Integer> matchingNumbers;
로또 당첨번호 조회해보면 어느 번호가 일치하는지 보여주기 때문에 이렇게 코드를 짜봤는데,
요구사항에는 해당 내용이 없으니 굳이 당첨 번호를 가지고 있을 필요가 없을까요?

2022-10-09 13:24 UTC, csh0034 commented on src/main/java/lotto/strategy/RandomNumberGenerateStrategy.java
> +    private final int NUMBER_MIN_BOUND = 1;
상수라는건 항상 같은 값이기때문에 객체별로 메모리에 할당될 필요없이 static 키워드를 통해 한번만 로딩하는것이 좋겠죠 😃

2022-10-09 13:28 UTC, csh0034 commented on src/main/java/lotto/domain/MatchingResult.java
> +    private List<Integer> matchingNumbers;
요구사항에 맞게 개발해보는것도 좋을것 같습니다.

2022-10-09 13:36 UTC, wonsakku commented on src/main/java/lotto/controller/LottoBuyerController.java
> +public class LottoBuyerController {
"MVC 패턴에서 컨트롤러의 역할은 Input, Output 처리" 에 대해서 이해를 잘 못하겠습니다.

이 말에 대해 제가 어떻게 이해했는지 말씀드리자면.
controller가 다루고 있는 도메인에 대해 query 또는 command 한다고 이해했습니다.

제가 이해한 게 맞다면 controller가 도메인을 상태로 가지고 있어야 해당 도메인에 접근하는 것이 용이하지 않나요?
아니면 도메인을 상태값으로 가지고 있기 보단 파라미터로 받아 input, output 처리를 해야하나요?

2022-10-10 06:45 UTC, csh0034 commented on src/main/java/lotto/controller/LottoBuyerController.java
> +public class LottoBuyerController {
현재 코드에선 Main.java 가 컨트롤러에 해당됩니다. 
InputView 를 통해 값을 입력받고 도메인 생성 및 로직 처리후 ResultView 를 통해 Output 을 처리하기 때문입니다.

controller 는 비지니스로직을 처리할수 있는대상에게 처리를 위임하는 역할을 합니다.

말씀해주신 도메인에 대해 query 또는 command 에 관하여 답변드리면 4계층의 레이어드 아키텍처에서 보면 식별자를 통해 도메인을 찾는것과 도메인에 대해서 변경을 하는부분은 도메인영역에 속하므로 MVC 에서의 컨트롤러(레이어드 아키텍처에서의 표현 계층)의 역할은 아니라고 생각합니다.

현재 LottoController 라는 대상에서 처리하는 일을 보면 가격에 맞는 로또를 생성하는 일은 `List<Lotto>` 에 대한 일급컬렉션을 추가하여 생성의 책임을 담당하게 하고 결과생성의 경우 WinningStatistic 또는 일급컬렉션에서 처리하도록 한다면 불필요할것 같습니다.

2022-10-10 07:12 UTC, csh0034 approved these changes
안녕하세요. 원식님.
코멘트 잘 반영해주셨네요 💯

몇가지 고민해볼만한 사항만 남겨드리고
머지하도록 하겠습니다.

다음단계 진행해주세요!

2022-10-10 07:12 UTC, csh0034 commented on src/main/java/lotto/domain/WinningStatistic.java
> +public class WinningStatistic {
`Map<WinningPrice, Integer>` 와 같이 추가해주는 Enum 이 그자체로 키가되어  
WinningPrice.THREE(3개일치) 가 2개 이런식으로 표현해보면 WinningStatistic 구현이 간결해질것 같습니다.

추가로 WinningPrice 에게 `matchingResult.matchingNumberCount()` 값을 보내서 몇등인지 
받아보면 좋을것 같습니다.

2022-10-10 07:12 UTC, csh0034 commented on src/main/java/lotto/domain/LottoMachine.java
> +public class LottoMachine {
static 메서드만 제공하며 객체생성을하지 않고있는데 도메인이라고 할수있을까요?

2022-10-10 07:12 UTC, csh0034 commented on src/main/java/lotto/domain/WinningPrice.java
> +    SIX(6, 2000000000)
`2_000_000_000` 와 같이 표현해볼수도 있을것 같습니다.

2022-10-10 07:12 UTC, merged