Step2
next-step/java-lotto pull request #2554
Opened 2022-10-06 12:31 UTC by wisdompark96

제가 nextstep remote에서 pr이 머지되기전 origin에서 브랜치딴 뒤 커밋을 해서 이전 PR 기록이 남아서 rebase를 해도 커밋 기록이 남네요ㅠ
base 브랜치에 직접 커밋한 기록은 force-push해서 해결하였지만 PR이 머지된 기록은 어떻게 해결할 수 있을까요?
이 PR은 체리픽해서 커밋 히스토리를 정리하였습니다.

2022-10-09 05:11 UTC, ddaaac requested changes
안녕하세요 지혜님 👋 

리뷰가 조금 늦었네요. 죄송합니다 😭 

몇 가지 코멘트를 남겼으니 확인 부탁드려요!

-------

이전 pr 커밋은 어떻게 할 수가 없습니다. 그런데 제가 봤을 떄 지금 커밋 내역은 정상적으로 보이는데 어떤 부분이 남은걸까요?

2022-10-09 05:11 UTC, ddaaac commented on src/test/java/lotto/LottoTest.java
> +        );
자리가 다르지만 숫자가 다른 경우도 케이스로 있으면 좋겠네요 😄

2022-10-09 05:11 UTC, ddaaac commented on src/test/java/lotto/PrizeServiceTest.java
> +}
이전에 코멘트 드렸던 posix 설정이 잘 안될걸까요?

2022-10-09 05:11 UTC, ddaaac commented on src/test/java/lotto/PrizeServiceTest.java
> +        );
enum에 있는 값과 일치하지 않는 경우도 테스트가 있으면 좋을 것 같아요.

2022-10-09 05:11 UTC, ddaaac commented on src/main/java/lotto/LottoService.java
> +    private final OutputView outputView;
서비스도 굳이 따지자면 모델 영역에 가깝습니다. View를 알면 안 될 것 같아요.
제 생각엔 서비스 없이 컨트롤러에서 LottoService에서 다루는 로직들을 처리해도 충분해보이는데 지혜님 생각은 어떠신가요?

2022-10-09 05:11 UTC, ddaaac commented on src/main/java/lotto/OutputView.java
> +    private final PrizeService prizeService;
여기도 마찬가지로 View가 Model을 알고 있습니다. View와 Model은 서로 모르게 하고, 둘 사이는 컨트롤러에서 중재하도록 변경해주세요.

2022-10-09 05:11 UTC, ddaaac commented on src/main/java/lotto/Calculator.java
> +    private static final BigDecimal PRICE_PER_LOTTO = BigDecimal.valueOf(1000);
LottoFactory에 있는 상수와 값이 겹치네요. 이런 부분은 리팩토링할 수 있는 부분이라고 생각해주시면 될 것 같아요.

왜 상수가 겹칠까 생각해보면 LottoFactory 내부에 있어도 되는 로직이 Calculator에 있는건 아닐까 생각해볼 수 있겠네요 😄

2022-10-11 02:37 UTC, wisdompark96 commented on src/main/java/lotto/Lotto.java
> +    public Lotto(List<Integer> numbers) {this.numbers = numbers;}
@ddaaac 
reformat하였습니다.

2022-10-11 02:38 UTC, wisdompark96 commented on src/main/java/lotto/Lotto.java
> +    public Lotto(List<Integer> numbers) {this.numbers = numbers;}
@ddaaac 
Lotto에 로또 수를 validation하는 로직을 추가하였습니다.

2022-10-11 02:42 UTC, wisdompark96 commented on src/test/java/lotto/LottoTest.java
> +        );
@ddaaac 
케이스를 추가하였습니다.

2022-10-11 02:43 UTC, wisdompark96 commented on src/test/java/lotto/PrizeServiceTest.java
> +}
@ddaaac 
posix설정 추가해서 reformat했습니다.

2022-10-11 02:45 UTC, wisdompark96 commented on src/test/java/lotto/PrizeServiceTest.java
> +        );
@ddaaac 
enum에 해당하는 값이 정확하게 들어가는지 확인하는 테스트로 일치하지 않는 케이스는 의도에 맞지 않는다 판단하여 넣지 않았습니다.

2022-10-11 02:45 UTC, wisdompark96 commented on src/main/java/lotto/LottoService.java
> +    private final OutputView outputView;
@ddaaac 
controller에서 처리하도록 수정하였습니다.

2022-10-11 02:46 UTC, wisdompark96 commented on src/main/java/lotto/Calculator.java
> +    private static final BigDecimal PRICE_PER_LOTTO = BigDecimal.valueOf(1000);
@ddaaac 
Calculator에서 계산하도록 수정하였습니다.

2022-10-11 02:47 UTC, wisdompark96 commented on src/main/java/lotto/Lotto.java
> +    }
@ddaaac 
getNumber메소드를 추가하여 number의 복사본을 view에서 출력하도록 수정하였습니다.

2022-10-11 05:13 UTC, ddaaac requested changes
안녕하세요 지혜님 👋 

리뷰 반영 잘 해주셨어요 👍 

몇 가지 더 고려해보면 좋을 부분들 코멘트 남겼습니다. 확인 부탁드려요~

2022-10-11 05:13 UTC, ddaaac commented on src/main/java/lotto/service/LottoService.java
> +public class LottoService {
이번 교육 과정동안에는 xxService와 같은 서비스 레이어를 만들지 않는 걸 추천드려요. 
LottoService 하는 일은 1. 로또 구매 2. 랭크 계산 두 가지인데
1. 로또 구매는 컨트롤러에서 LottoFactory를 통해 직접할 수 있고
2. 랭크 계산은 WinningNumber라는 [일급 컬렉션](https://jojoldu.tistory.com/412)를 통해 할 수 있을 것 같습니다.

이 부분 리팩토링을 한 번 해보시는 걸 추천드립니다 :)

2022-10-11 05:13 UTC, ddaaac commented on src/main/java/lotto/Calculator.java
> +                    BigDecimal.valueOf(rankMap.get(value.getWinningCount())).multiply(value.getPrizeMoney()));
```suggestion
            BigDecimal prize = BigDecimal.valueOf(rankMap.get(value.getWinningCount())).multiply(value.getPrizeMoney());
            prizeMoney = prizeMoney.add(prize);
```
파라미터 안에 계산식이 들어가면 읽는데 막힘이 생겨요. 한 번 끊어주고 가면 좋을 것 같습니다!

2022-10-11 05:13 UTC, ddaaac commented on src/main/java/lotto/service/LottoService.java
> +    public Map<Integer, Integer> confirmLottoRank(List<Lotto> lottos, List<Integer> winningNumber) {
리턴타입이 `Map<Prize, Integer>`라면 조금 더 빠르게 어떤 값을 리턴하는지 파악할 수 있을 것 같아요.
또, 확인한다라는 confirm 대신 계산/구하다라는 단어를 사용하는 것도 좋을 것 같구요 (혹시 confirm에 그런 뜻이 있다면 그대루 두셔도 됩니다!)

2022-10-13 01:10 UTC, wisdompark96 commented on src/main/java/lotto/service/LottoService.java
> +public class LottoService {
@ddaaac 
LottoService를 제거하고 두 클래스에게 책임을 분산하였습니다.

2022-10-13 10:34 UTC, ddaaac approved these changes
안녕하세요 지혜님 👋 
전반적으로 리뷰 반영 너무 잘해주셨어요 💯 

몇 가지 코멘트를 남겼으니 다음 단계 진행에 참고해주세요.

2022-10-13 10:34 UTC, ddaaac commented on src/main/java/lotto/Calculator.java
> +                                      .multiply(value.getPrizeMoney()));
```suggestion
            BigDecimal bigDecimal = BigDecimal.valueOf(rankMap.get(value));
            prizeMoney = prizeMoney.add(bigDecimal.multiply(value.getPrizeMoney()));
```
코멘트를 모호하게 남겼네요. 변수로 분리하고 가면 조금 더 읽기 쉬운 코드일 것 같습니다.

2022-10-13 10:34 UTC, ddaaac commented on src/main/java/lotto/service/LottoFactory.java
> +        for (int i = 1; i <= 45; i++) {
만약 로또 번호가 1~50으로 바뀐다면 코드에서 어디 부분을 수정해야할까요?
지금 코드로는 LottoFactory와 LottoNumber 모두를 수정해야 될 거에요. 실수로 개발자가 이를 고치다가 LottoNumber의 숫자만 고치면 이 부분에서 버그가 발생할 것 같습니다.
LottoNumber의 상수를 public으로 열고 여기서 사용하는 건 어떨까요?

2022-10-13 10:34 UTC, ddaaac commented on src/main/java/lotto/service/LottoFactory.java
> +        Collections.shuffle(lottoNumbers);
멀티스레드 환경에서 이 메서드가 동시에 실행되면 어떤 일이 일어날까요?

2022-10-13 10:34 UTC, ddaaac commented on src/main/java/lotto/domain/Lotto.java
> +    public List<LottoNumber> getLottoNumbers() {
개행이 필요해보여요!

2022-10-13 10:34 UTC, ddaaac commented on src/main/java/lotto/domain/WinningNumber.java
> +        for (LottoNumber lottoNumber : lotto.getLottoNumbers()) {
getter가 보이면 리팩토링을 생각해볼 수 있습니다.
Lotto로 WinnerNumber를 넘기면 getter를 제거할 수 있지 않을까요?

2022-10-13 10:34 UTC, ddaaac commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int findMatchingCount(List<Integer> winningNum) {
6개의 숫자를 LottoNumber 또는 WinningNumber의 일급컬렉션으로 감쌌는데 여기서는 다시 감싸지지 않은 일반 컬렉션이 등장하고 있어요. 이 부분도 WinningNumber가 파라미터로 올 수 있지 않을까요? 또는 반대로 WinningNumber에 LottoNumber가 파라미터로 넘어갈 수도 있구요. 이 부분은 다음 단계를 진행하면서 해결해보면 좋을 것 같습니다!

2022-10-13 10:50 UTC, merged