step 2 - 로또(자동)
next-step/java-lotto pull request #2567
Opened 2022-10-07 16:04 UTC by yerin-158

### step 2 - 로또(자동)
안녕하세요.
TDD로 작성하였으며 패키지 구조와 기능 분리에 중점을 두었습니다.

항상 수고 많으십니다. 감사합니다.

2022-10-08 08:37 UTC, hyunssooo requested changes
안녕하세요.
몇 가지 코멘트 남겼습니다. 확인 부탁드릴게요.
궁금한 점이나 함께 고민해 보고 싶은 부분이 있으시면 편하게 연락주세요.

2022-10-08 08:37 UTC, hyunssooo commented on src/main/java/lotto/services/LottoService.java
> +    private final PickNumberService pickNumberService;
service 라는 네이밍은 layered architecture 의 application service를 의미하실까요??
이 부분에 대해서 같이 고민해 보면 좋을 것 같아요.

2022-10-08 08:37 UTC, hyunssooo commented on src/main/java/lotto/models/Lotto.java
> +
`Lotto`는 1 ~ 45 중 중복되지 않는 숫자 6개로 구성되어 있습니다. 
Lotto class는 이를 만족할까요?
1~45의 숫자도 의미있게 포장해 보는 것은 어떨까요?

2022-10-08 08:37 UTC, hyunssooo commented on src/test/java/lotto/services/LottoStatisticsServiceTest.java
> +    private final static int PAYMENT = 3500;
`private static final` 이 맞습니다. 전체적으로 확인해 보면 좋을 것 같아요.

IDEA에서 `prsf` 을 입력하시면 쉽게 자동완성할 수 있어요.

2022-10-08 08:37 UTC, hyunssooo commented on src/test/java/lotto/services/LottoStatisticsServiceTest.java
> +    }
`@BeforeAll` 을 나눈 이유가 있을까요? 🤔

```suggestion
    @BeforeAll
    static void setLotto() {
        lottos.add(Lotto.of(List.of(1,2,3,4,5,6)));
        lottos.add(Lotto.of(List.of(1,2,3,7,8,9)));
        lottos.add(Lotto.of(List.of(11,12,13,14,15,16)));
    }

    @BeforeAll
    static void setDuplicatedLottos() {
        duplicatedLottos.add(Lotto.of(List.of(1, 2, 3, 4, 5, 6)));
        duplicatedLottos.add(Lotto.of(List.of(1,2,3,4,5,6)));
        duplicatedLottos.add(Lotto.of(List.of(1,2,3,4,5,6)));
    }
```
 스페이스도 컨벤션이 있습니다 IDEA의 auto formatting 기능을 적극 활용하면 좋을 것 같네요.

2022-10-08 08:37 UTC, hyunssooo commented on src/main/java/lotto/models/Lotto.java
> +
Lotto의 책임과 역할을 고민해 보시고 이를 테스트로 작성해 보면 좋을 것 같아요.

2022-10-08 09:08 UTC, yerin-158 commented on src/main/java/lotto/services/LottoService.java
> +    private final PickNumberService pickNumberService;
네 맞습니다.
도메인 당 하나의 서비스로 분리하는게 익숙해서 그렇게 처리했는데 문제있을까요?

2022-10-08 09:08 UTC, yerin-158 commented on src/test/java/lotto/services/LottoStatisticsServiceTest.java
> +    private final static int PAYMENT = 3500;
아 넵넵 감사합니다

2022-10-08 09:10 UTC, yerin-158 commented on src/main/java/lotto/models/Lotto.java
> +
number를 받을 때 중복되지 않는 1~45의 중복되지 않는 6개 숫자로 받도록 되어있습니다.
테스트 코드도 있어요.
(Strategy내에서 Set에 넣어서 6개를 채우기 때문에 중복되지 않는 것은 보장하여 테스트 코드에 없습니다.)

- PickNumberService.pickNumbers
- PickNumberServiceTest
참고 부탁드립니다.

2022-10-08 09:11 UTC, yerin-158 commented on src/test/java/lotto/services/LottoStatisticsServiceTest.java
> +    }
음.. 다른 객체라서 각각 셋팅해 주는게 좋을 것 같아 나눠보았습니다.
ide는 셋팅해보겠습니다.

2022-10-08 13:45 UTC, hyunssooo commented on src/main/java/lotto/models/Lotto.java
> +
mvc 패턴에서 model이 어떤 역할을 하나요? model은 도메인 로직을 담고 있습니다. 
단순 모델일 뿐이라고 생각하시는 부분은 객체를 그저 데이터로 보시는걸까요? Lotto에서 가질수 있는 역할과 책임중 하나는 `중복되지 않는 숫자 6개를 받는다` 아닐까요? 현재 생성자로 `List<Ingeger>` 를 받고 있는데 이 경우 6개를 받을 수 있지만 20개 100개도 받을 수 있는 구조 아닐까요? 이 책임을 service에서 하는 것이 맞을까요? 말씀하신 application service의 역할은 무엇인가요?

2022-10-08 13:46 UTC, hyunssooo commented on src/main/java/lotto/services/LottoService.java
> +    private final PickNumberService pickNumberService;
> 도메인 당 하나의 서비스로 분리하는게 익숙해서 

lotto 미션의 도메인은 무엇인가요?

2022-10-09 08:03 UTC, yerin-158 commented on src/main/java/lotto/models/Lotto.java
> +
Lotto가 가질 수 있는 숫자의 조건은 언제든지 변할 수 있기 때문에 strategy를 이용했구요.
말씀하시는 역할과 책임을 서비스에 위임했다고 생각하시면 될 것 같은데요..
그 조건이 변하지 않을게 보장된다면 굳이 인터페이스를 받아서 여러개의 전략으로 숫자를 받게 구성하지 않았을겁니다.

말씀하신대로 조건이 고정된다면 생성자에서 벨리데이션을 돌려버리면 되는거구요.
이전 과제하면서 보니 미션 수행하는데에 늘 단계가 있기에 미션에서 요구하는 사항외에는 임의로 추가작성하지 않고 있습니다.
벨리데이션 관련 요구사항(잘못된 값이 들어오는 경우 Exception 발생 등의 요구사항)이 없길래 추가하지 않았구요.

지금 그럼 `반복되지 않는 여섯개의 숫자`가 `이번 경우`의 조건이고 그 책임을 Lotto가 가진다면 1) 벨리데이션을 추가한다. 2) 여섯개의 값을 각각의 필드로 만든다. 이정도 인가요?

2022-10-09 08:05 UTC, yerin-158 commented on src/main/java/lotto/services/LottoService.java
> +    private final PickNumberService pickNumberService;
도메인이라는 말이 다양하게 혼용되다보니 질문하신 것 같은데 저는 여기서 모델이라는 의미로 사용했습니다.
Lotto, LottoStatistics라는 모델을 만들었고 이와 관련된 서비스를 만들었데요.
문제있으실까요?

2022-10-09 15:10 UTC, hyunssooo commented on src/main/java/lotto/models/Lotto.java
> +
개인적으로 코드를 직접 작성해서 드리진 않는데요. 이러는 이유는 수강하시는 분들이 고민하고 코드를 작성하는 편이 성장하는데 더욱 도움이 된다고 생각해서입니다. 
OOP에서 상태와 행위는 객체가 관리하는데요. 현재 코드에서 Lotto는 단순한 데이터일 뿐이라고 생각했어요. service에 위임한 부분은 두 클래스가 결합도가 높다고 생각했고요. 

application service에서는 비즈니스 로직을 다루지 않습니다. tx 관리와 도메인 모델의 순서를 제어해요. (비즈니스를 풀기 위해) 비즈니스 로직이 application service에 작성된다면 그것은 
transaction script pattern 이라고 볼 수 있습니다. 간단한 비즈니스일 경우 그렇게 작성될 수 있다고 생각하지만 복잡한 비즈니스인 경우 transaction script pattern으로 작성하기에 한계가 있다고 생각해요. 수 많은 분기가 생길거고 코드는 계속 길어지겠죠. 그런 코드는 테스트, 유지보수하기도 힘들 것이라고 생각해요. 
지금은 oop를 학습하는 입장에서 최대한 비즈니스 로직은 도메인 모델에 위임하고 도메인 모델들의 협력으로 비즈니스를 풀어내야 한다고 생각합니다. 

이번 미션은 DDD에 나오는 패턴들과는 전혀 관련 없습니다. 또한, DDD에서 OOP가 필수도 아닙니다. 나오는 패턴 중 OOP를 정면으로 위반하는 패턴들도 있고요. 

아래에 제가 이번 미션에서 가볍게 생각한 코드 남겨요. 

```java
public class Lotto {

    private final Set<LottoNumber> numbers;

    public Lotto(Set<LottoNumber> numbers) {
        validNumbers(numbers);
        this.numbers = numbers;
    }

    private void validNumbers(Set<LottoNumber> numbers) {
        if (numbers.size() != 6) {
            throw new IllegalArgumentException();
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Lotto)) {
            return false;
        }
        Lotto lotto = (Lotto) o;
        return Objects.equals(numbers, lotto.numbers);
    }

    @Override
    public int hashCode() {
        return Objects.hash(numbers);
    }
}

public class LottoNumber {

    private final int value;

    public LottoNumber(int value) {
        validValue(value);
        this.value = value;
    }

    private void validValue(int value) {
        if (value < 1 || value > 45) {
            throw new IllegalArgumentException();
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof LottoNumber)) {
            return false;
        }
        LottoNumber that = (LottoNumber) o;
        return value == that.value;
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }
}

```

`LottoNumber` 는 1~45까지의 숫자에 대한 책임을 가집니다. 
`Lotto` 는 `LottoNumber` 6개에 대한 책임을 가집니다.

2022-10-10 15:36 UTC, hyunssooo approved these changes
안녕하세요. 
몇 가지 코멘트 남겼습니다. 
다음 step에서 진행하시면서 참고해 주세요.

2022-10-10 15:36 UTC, hyunssooo commented on src/main/java/lotto/LottoApplication.java
> +        LottoService lottoService = new LottoService(pickNumberService);
굉장히 많은 service가 존재하는데 지금 미션에서 service가 필요할까 싶어요. 
controller에서 도메인 모델들에게 비즈니스 규칙을 위임해 보는 것은 어떨까요?

2022-10-10 15:36 UTC, hyunssooo commented on src/main/java/lotto/LottoApplication.java
> +        List<Lotto> lottos = lottoService.issueLotto(Integer.parseInt(payment) / 1000);
로또 구매를 위한 금액 또한 객체로 포장해 볼 수 있겠네요.

2022-10-10 15:36 UTC, hyunssooo commented on src/main/java/lotto/models/enums/Rank.java
> +
```suggestion

    FIRST(6, 2_000_000_000),
    SECOND(5, 1_500_000),
    THIRD(4, 50_000),
    FOURTH(3, 5_000),
    OTHER(0, 0);

```
언더바로 세 자리씩 띄워주면 가독성을 높일 수 있겠네요.

2022-10-10 15:36 UTC, hyunssooo commented on src/main/java/lotto/services/LottoStatisticsService.java
> +    }
winningNumber 또한, Lotto라고 볼 수 있지 않을까요? 
이 메서드가 실행되면 `String#split` 이 계속 실행되는데 한 번만 `split`하고 재사용 하는 방법은 없을까요?

내부에서만 사용하는 메서드면 private이 맞을 것 같네요.

2022-10-10 15:36 UTC, hyunssooo commented on src/main/java/lotto/strategy/NormalPickNumberStrategy.java
> +    }
객체가 생성될 때 마다 1~45 숫자는 생성되고 있는데요. 캐싱을 고려해 보는 것도 좋을 것 같아요.

2022-10-10 15:36 UTC, hyunssooo commented on src/main/java/lotto/validator/LottoValidator.java
> +
유틸성 클래스는 생성자를 private으로 선언해 인스턴스화를 막는 것이 좋습니다. 
이펙티브 자바 아이템 4. 인스턴스화를 막으려거든 private 생성자를 사용하라. 를 읽어보면 좋을 것 같아요.

2022-10-10 15:36 UTC, merged