2단계 - 로또(자동)
next-step/java-lotto pull request #2593
Opened 2022-10-11 06:51 UTC by gmelon

리뷰 요청 드립니다!

getter나 dto 값 설정 부분 등 고민되는 부분들이 아직 좀 있는데 🥲
피드백 주신 것 확인하고 질문드리거나 수정해보겠습니다.

감사합니다! :)

2022-10-12 08:34 UTC, pkch93 requested changes
상혁님 안녕하세요 :)
전반적으로 잘 구현해주셨네요! 몇가지 생각해볼 부분이랑 피드백 드렸는데 한번 확인 부탁드릴께요.
궁금하신 점 있으시면 코멘트나 DM 주세요 ㅎㅎ

2022-10-12 08:34 UTC, pkch93 commented on src/main/java/lottery/Lottery.java
> +        List<LotteryNumber> lotteryNumbers = lotteryNumberCandidates.subList(0, LOTTERY_NUM_COUNT);
```java
List<LotteryNumber> lotteryNumbers = lotteryNumberCandidates.subList(0, LOTTERY_NUM_COUNT)
                .stream()
                .sorted()
                .collect(Collectors.toList());
```
이렇게도 사용할 수 있지 않을까 싶어요.

2022-10-12 08:34 UTC, pkch93 commented on src/main/java/lottery/Lottery.java
> +    private static final List<LotteryNumber> lotteryNumberCandidates = IntStream
상수는 대문자 snake_case로 정의해주시면 코드에서도 바로 상수로 알아 볼 수 있을거 같아요 :)

2022-10-12 08:34 UTC, pkch93 commented on src/main/java/lottery/Lottery.java
> +    private static List<LotteryNumber> generateLotteryNumbers() {
`generateLotteryNumbers`를 static으로 정의하신 이유가 있을까요?

2022-10-12 08:34 UTC, pkch93 commented on src/main/java/lottery/LotteryWallet.java
> +    public LotteryWallet(List<Lottery> lotteries) {
위 메서드는 LotteryWallet의 인자가 없는 생성자와 테스트에서만 사용하네요.
다만 위 생성자가 테스트에서 사용된다는 것은 프로덕션에서도 위 생성자를 활용할 수 있도록 변경할 수 있어보이는데요.
기존에 사용하는 인자가 없는 생성자를 사용하는 방법에서 위 생성자를 사용하도록 구조를 변경해보면 어떨까요?

2022-10-12 08:34 UTC, pkch93 commented on src/main/java/lottery/Lottery.java
> +        return lotteryNumbers.stream().map(LotteryNumber::new).collect(Collectors.toList());
```java
lotteryNumbers.stream()
        .map(LotteryNumber::new)
        .collect(Collectors.toList());
```
한 줄엔 하나의 점 `.`만 사용해주시면 보다 읽기 좋은 코드가 될 거 같아요 :)

2022-10-12 08:34 UTC, pkch93 commented on src/main/java/lottery/Lottery.java
> +    public static Lottery getInstanceByInt(List<Integer> lotteryNumbers) {
`getInstanceByInt`도 테스트에서만 사용하네요. `getInstanceByInt` 에서 사용하는 `List<LotteryNumber>`를 받는 생성자도 결국은 테스트에서 사용되는 거라고 할 수 있겠네요. 인자 없는 `Lottery` 생성자를 사용하지 않고 `List<LotteryNumber>`를 받는 생성자를 사용하면 어떨까요?

2022-10-12 08:34 UTC, pkch93 commented on src/main/java/lottery/LotteryCompany.java
> +        lotteries.forEach(lottery -> lotteryResult.addWonCountOf(lottery.countEqualNumbers(wonLottery)));
set을 쓰기 보다 생성할 때 필요한 데이터를 넘겨서 생성하면 어떨까요?

2022-10-12 08:34 UTC, pkch93 commented on src/main/java/lottery/Lottery.java
> +            .range(1, LotteryNumber.LOTTERY_NUM_MAX + 1)
```java
.rangeClosed(1, LotteryNumber.LOTTERY_NUM_MAX)
```
`rangeClosed`를 사용하면 1 이상, 45 이하로 생성할 수 있을꺼에요!

2022-10-12 08:35 UTC, pkch93 commented on src/main/java/lottery/LotteryResult.java
> +public class LotteryResult {
결과 객체 👍

2022-10-13 03:06 UTC, gmelon commented on src/main/java/lottery/Lottery.java
> +            .range(1, LotteryNumber.LOTTERY_NUM_MAX + 1)
앗 closed로 만들 수도 있군요..! 감사합니다!!

2022-10-13 03:17 UTC, gmelon commented on src/main/java/lottery/Lottery.java
> +    private static List<LotteryNumber> generateLotteryNumbers() {
막연하게 static으로 정의하면 테스트가 용이하니깐~ 이러고 static으로 정의했던 것 같습니다 🥲
그래놓고 private 메소드로 만들어놨네요...ㅎ

우선 public static으로 선언하고 `LotteryWallet`에서 `List<LotteryNumber>`를 주입하는 용도로 사용하도록 변경해보겠습니다.
바로 아래에 생성자 관련해서 드린 질문과도 연관이 있을 것 같아요!

2022-10-13 03:24 UTC, gmelon commented on src/main/java/lottery/Lottery.java
> +    public static Lottery getInstanceByInt(List<Integer> lotteryNumbers) {
@pkch93 네 그렇게 변경해보겠습니다.
`List<LotteryNumber>`의 주입은 상위 클래스에서 아래와 같이 하도록 변경해봤는데 이러한 방식이 괜찮을까요?
```
new Lottery(Lottery.generateLotteryNumbers())
```
(제 생각에는 수동으로 로또 생성 방식이 변경될 때 변경이 용이하겠다는 생각이 드네요!)


만약 이렇게 한다면 테스트에서는 아래와 같이 `Lottery` 객체를 생성할 수 있을 것 같은데 
```
Stream.of(1, 2, 3).map(LotteryNumber::new).collect(Collectors.toList())
```
혹시 더 좋은 방법에 대한 의견이 있으실지도 궁금합니다!

2022-10-16 03:52 UTC, gmelon commented
경철님 안녕하세요!
피드백 주신 내용들 생각해보고 리팩토링해보았습니다.

먼저 로또를 자동으로 생성하는 로직을 `LotteryCompany`로 분리하고, 상위 계층인 `Customer`에서 함수를 호출하여 리스트에 넣어주도록 변경했습니다.
구조 관련해서는 `LotteryWallet`을 삭제하고 `Customer`가 `Lottery`의 일급 콜렉션 역할을 하도록 해보았습니다.

피드백 기다리고 있겠습니다! 감사합니다 :)

2022-10-16 14:16 UTC, pkch93 requested changes
안녕하세요 상혁님 :) 저번에 드린 피드백 반영 확인했습니다 ㅎㅎ 반영 감사합니다.
질문 남겨주신 부분에 대한 답변과 몇가지 추가 피드백 드렸는데 한번 확인부탁드릴께요 ㅎㅎ

2022-10-16 14:16 UTC, pkch93 commented on src/main/java/lottery/LotteryResult.java
> +public class LotteryResult {
`결과 객체는 모든 값을 직접 들고있어야 하는게 아닌가?` 라고 의문이 들었다고 하셨는데요.
이 의미는 `LotteryRanks` 에서 관리하는 등수별 값들을 `LotteryResult`에서 가지고 있어야하는가 일까요?

2022-10-16 14:16 UTC, pkch93 commented on src/main/java/lottery/LotteryResult.java
> +    private final Map<Integer, Integer> wonCounts = new HashMap<>();
당첨에 대해 표현하는 `LotteryRanks` enum을 정의하신 만큼 EnumMap을 활용해보면 어떨까요?

2022-10-16 14:16 UTC, pkch93 commented on src/main/java/lottery/LotteryCompany.java
> +    }
`createLotteryResult` 함수에서 초기 `LotteryResult`를 생성하고 그 후에 하나씩 값을 계산하여 결과를 세팅해주는데요.
때문에 `addWonCountOf` 같은 메서드도 필요하고 테스트에서 사용하는 `setWonCountOf`가 필요한게 아닐까 싶어요.
결과를 위 메서드에서 계산하고 계산 결과를 생성시점에 인자로 전달해서 생성해보면 어떨까요?

2022-10-16 14:16 UTC, pkch93 commented on src/test/java/lottery/LotteryCompanyTest.java
> +    static Lottery createLottery(Integer... values) {
첫번째 질문이 위 메서드와 관련이 있는거 같네요.

테스트 데이터를 생성하고 관리하는 것도 꽤 중요한 작업이라고 생각하는데요. 위와 같이 테스트 데이터를 만드는 메서드를 활용하는 것도 좋은 방법이라고 생각해요.
다만, 여러 테스트에서 동일한 로직이 사용된다면 프로덕션 코드에서 접근하지 못하도록 test SourceSet 하위에 테스트 생성용 클래스를 `에를들어 TestLotteryCompany` 정의하여 여러 테스트에서 사용하는 로직을 공통화하여 사용할 수 있을거 같아요 :)

2022-10-16 14:16 UTC, pkch93 commented on src/main/java/lottery/LotteryCompany.java
> +    public static LotteryResult createLotteryResult(Lottery wonLottery, List<Lottery> lotteries) {
`wonLottery` 도 일반 로또인 `Lottery`로 표현해주셨는데요. 당첨 로또를 가리키는 별도의 클래스로 정의할수도 있을거 같아요 :)

2022-10-16 14:29 UTC, gmelon commented on src/main/java/lottery/LotteryResult.java
> +public class LotteryResult {
@pkch93 네네 맞습니다! `LotteryRanks`와 `LotteryResult`의 연결을 끊어주는게 더 좋은 설계일지 아니면 중복을 줄이는 게 좋은 방향일지 고민이 되더라고요.

2022-10-16 14:30 UTC, gmelon commented on src/test/java/lottery/LotteryCompanyTest.java
> +    static Lottery createLottery(Integer... values) {
@pkch93 테스트 생성용 클래스 반영해보겠습니다! 감사합니다 :)

2022-10-16 14:34 UTC, gmelon commented on src/main/java/lottery/LotteryResult.java
> +    private final Map<Integer, Integer> wonCounts = new HashMap<>();
key값이 Enum 클래스일 경우에 EnumMap을 활용하면 성능에 이점이 있군요! 활용해 보겠습니다!

2022-10-16 23:04 UTC, pkch93 commented on src/main/java/lottery/LotteryResult.java
> +public class LotteryResult {
제 생각은 `LotteryResult`는 로또 게임의 최종 결과물을 담는 DTO 역할로 보여서요. `LotteryResult`가 등수 관련된 `LotteryRanks`와의 의존을 없애기는 쉽지 않아 보이네요. Rank 관련된 로직을 `LotteryRanks`에서 관리하고 결과값만 `LotteryResult`로 담도록 하면 어떨까요?

2022-10-16 23:07 UTC, pkch93 commented on src/main/java/lottery/LotteryResult.java
> +    private final Map<Integer, Integer> wonCounts = new HashMap<>();
네넵 성능상으로도 이점이 있고 `LotteryRanks` enum의 값을 키로 사용하니 지금보다 더 이해하기 쉬운 코드가 될거 같아요 ㅎㅎ
[Effective Java item 37](https://hirlawldo.tistory.com/m/90)에도 EnumMap 관련 내용이 있으니 참고해보셔도 좋을거 같습니다!

2022-10-17 02:20 UTC, gmelon commented on src/main/java/lottery/LotteryResult.java
> +    private final Map<Integer, Integer> wonCounts = new HashMap<>();
네 감사합니다!

2022-10-17 14:33 UTC, gmelon commented on src/main/java/lottery/LotteryCompany.java
> +    public static LotteryResult createLotteryResult(Lottery wonLottery, List<Lottery> lotteries) {
당첨 번호를 저장하는 `Lottery`를 `WinningLottery`로 분리하고 결과를 구하는 로직도 해당 클래스로 분리했습니다!

2022-10-17 14:34 UTC, gmelon commented on src/main/java/lottery/LotteryResult.java
> +public class LotteryResult {
넵, 감사합니다!
`rank` 관련 값과 로직은 `LotteryRank`에서 관리하도록 하고, 실제 구매한 로또에 대한 결과 값들만 `LotteryResult`에 저장하도록 변경해봤습니다.

2022-10-17 14:35 UTC, gmelon commented on src/main/java/lottery/LotteryCompany.java
> +    }
생성자에서 모든 값을 받고, setter는 사용하지 못하도록 변경했습니다.

2022-10-18 10:20 UTC, pkch93 approved these changes
고생하셨습니다 상혁님 ㅎㅎㅎ
2단계 피드백 반영해주셨군요 💯 감사합니다.
로또 2단계는 이만 머지할께요. 다음 단계에서 뵙겠습니다 👋

2022-10-18 10:20 UTC, merged

2022-10-19 14:52 UTC, gmelon commented
감사합니다! 리뷰하시느라 고생많으셨습니다ㅎㅎ
3단계도 얼른 pr 올리도록 할게요!!