Step2
next-step/java-lotto pull request #2598
Opened 2022-10-11 16:05 UTC by wugatama

2022-10-13 09:44 UTC, ddaaac requested changes
안녕하세요 정욱님 👋 

2단계 미션 잘 작성해주셨어요. 

몇 가지 코멘트를 남겼으니 확인 부탁드려요.

2022-10-13 09:44 UTC, ddaaac commented on src/main/java/step1/Separator.java
> +			even.add(Integer.parseInt(split));
`checkEven`, `validateNumber`에서 실제로 하는 일은 even에 값을 추가해주는 행위를 하고 있어요.
메서드명과 실제로 하는 일을 일치시키면 읽기 편할 것 같습니다 :)

2022-10-13 09:44 UTC, ddaaac commented on src/main/java/step2/Game.java
> +	public static void start(int input) {
[OOP에서 static method](https://medium.com/att-israel/should-you-avoid-using-static-ae4b58ca1de5)는 어떤 의미를 가질까요? 

개인적으로(아마 교육과정에서도) 이번 교육과정 동안 유틸성 클래스는 최대한 지양해보는 걸 추천드려요!

2022-10-13 09:44 UTC, ddaaac commented on src/main/java/step2/Main.java
> +		Game.start(InputView.input());
지금은 Main과 Game이 모두 컨트롤러 성격을 갖고 모델과 View 사이를 중개해주고 있습니다. 둘 중 하나만 컨트롤러의 역할을 하면 좋을 것 같아요.

2022-10-13 09:44 UTC, ddaaac commented on src/main/java/step1/Separator.java
> +		}
depth가 2로 깊어졌어요. continue를 제거하고 로직을 작성한 뒤에 메서드 분리를 해볼 수 있을 것 같네요.

2022-10-13 09:44 UTC, ddaaac commented on src/main/java/step2/Lotto.java
> +		}
randomStart가 없이 처음 6개만 뽑아도 랜덤한 값이 나오지 않을까요?

2022-10-13 09:44 UTC, ddaaac commented on src/main/java/step2/Lotto.java
> +		Collections.shuffle(balls);
이 셔플이 멀티스레드 환경에서 동시에 발생한다면 어떤 문제가 발생할지 고민해보시면 좋을 것 같습니다 😄

2022-10-13 09:44 UTC, ddaaac commented on src/test/java/step2/GameTest.java
> +	void name() {
테스트의 이름이 필요해보여요!

2022-10-13 09:44 UTC, ddaaac commented on src/main/java/step2/Game.java
> +		Result result = new Result(list);
이 라인은 어떤 일을 하나요?

2022-10-13 09:44 UTC, ddaaac commented on src/main/java/step2/Lotto.java
> +		for (int i = 1; i <= 45 ; i++) {
의미 있는 값은 상수로 분리해주세요.

2022-10-16 16:06 UTC, wugatama commented on src/main/java/step2/Lotto.java
> +		Collections.shuffle(balls);
키워드를 알려 주실 수 있을까요?

2022-10-17 10:45 UTC, ddaaac commented on src/main/java/step2/Result.java
> +	}
이 부분도 depth를 1로 맞추면 좋을 것 같아요!

2022-10-17 10:45 UTC, ddaaac commented on src/main/java/step2/Game.java
> +		// Prize.result(guestResult, makeWinningResult(InputView.input().split(", ")));
사용하지 않는 라인은 git을 믿고 과감하게 지워도 좋을 것 같아요 😄

2022-10-17 10:45 UTC, ddaaac commented on src/main/java/step2/Result.java
> +	private final List<Set<Integer>> list;
중첩된 컬렉션을 사용하면 해당 list가 어떤 의미인지 파악하기 쉽지 않습니다.
[강의 영상](https://edu.nextstep.camp/s/DVVUSLFe/ls/OIpOpvNp) 중에 일급 컬렉션에 관한 영상을 보고 리팩토링 해보시면 좋을 것 같아요!

2022-10-17 10:45 UTC, ddaaac commented on src/main/java/step2/Result.java
> +	}
일급 컬렉션을 만든다면 이 부분 로직이 일급 컬렉션으로 이동 + 테스트하기도 용이해질 것 같네요.

2022-10-17 10:45 UTC, ddaaac commented on src/main/java/step2/Lotto.java
> +		Collections.shuffle(balls);
다른 분 코드와 헷갈렸네요 🥲

매번 Lotto()를 생성하지 않고 클래스의 인스턴스 변수로 사용하는 경우가 많은데, 그 경우에 멀티 스레드에서 동시에 해당 메서드가 실행되는 경우에 셔플 -> 리턴 -> 셔플 -> 리턴의 순서가 아닌 셔플 -> 셔플 -> 리턴 -> 리턴의 결과가 발생할 수도 있습니다. 
현재 정욱님의 코드에서는 발생하지 않는 문제입니다. 
다만, 매번 Lotto 객체를 생성해야할까에 대해서는 고민해보시면 좋을 것 같아요.

2022-10-17 10:45 UTC, ddaaac approved these changes
안녕하세요 정욱님 👋 

리뷰 반영 잘 해주셨습니다 💯 머지해도 될 것 같아서 다음 단계 진행해주세요!

몇 가지 코멘트를 남겼으니 다음 단계 진행에 참고해주세요~

2022-10-17 10:46 UTC, merged