[Step 3] 로또(2등)
next-step/java-lotto pull request #2600
Opened 2022-10-12 05:15 UTC by yerin-158

### [Step 3] 로또(2등)

- **`request` 모델 추가**
ㄴ 사용자에게 입력 받은 내용을 Request로 랩핑하였습니다. : `WinningLottoRequest`, `PaymentRequest`
ㄴ 리퀘스트 모델은 Printer에서 사용자 입력을 primitive type으로 가져온 뒤 같은 메소드 내에서 모델로 만들어 리턴하도록 하였습니다.
ㄴ 기존의 `LottoApplication`에서는 사용자 입력값은 랩핑된 모델로 전달받고 필요한 서비스 메소드에 그대로 전달합니다.

- **`LottoNumbers` 일급컬렉션 추가**
ㄴ List\<Integer> numbers만 포함하는 일급 컬렉션을 만들고 기존 Lotto의 필드를 대치시켰습니다.

- **`Lotto` 모델을 상속받는 `WinningLotto` 추가**
ㄴ 당첨 번호를 List로 받아 매번 split 하는 로직이 불필요하게 반복되고 있었기에 이를 제거하고 1차로는 당첨 번호로 구성된 Lotto를 만들도록 리팩토링 하였습니다. (step2 마지막 피드백 반영)
ㄴ 보너스 번호 필드가 새롭게 추가되어 `Lotto`와 기본적으로 동일한 필드인 LottoNumbers를 포함하도록 이를 상속받는 WinningLotto를 추가하였으며, 해당 모델은 WinningLottoRequest를 인자로 받아서 생성하도록 구성하였습니다.
ㄴ WinngLottoRequest의 벨리데이션은 `WinningLotto`를 생성하는 `from`에서 수행하도록 하였습니다.

-**`Rank` enum에 hasBonusNumber 추가**
ㄴ 동일하게 5개의 당첨 숫자를 가지는 경우, 보너스 숫자 일치여부로 2등과 3등을 구분하여 Rank를 반환해주기 위하여 추가하였습니다.

-**`LottoService.issueLotto(..)`가 `PickNumberStrategy`를 인자로 받도록 수정**
ㄴ 기존에는 해당 메소드 내에서 PickNumberStrategy 를 생성하여 `pickNumberService.pickNumbers`에 전달하도록 되어있었습니다.
ㄴ `issueLotto`에서는 특정 전략에 따라 숫자를 뽑아내는 작업을 하는 것이 명확하기 때문에 `PickNumberStrategy`를 인자로 받도록 수정하여 LottoService와 PickNumberStrategy의 결합도를 낮추도록 하였습니다. 

-**피드백 반영**
ㄴ 컨벤션 맞췄습니다.
ㄴ 상수값으로 뺄 수 있는 것들은 static final로 변경하였습니다.
ㄴ 사용자 입력값을 전달하기 위해  `request` 모델 추가하였습니다.
ㄴ `NormalPickNumberStrategy`의 기본 생성자 내에서 `Lis\<Integer> numberRange`를 초기화 시킨 뒤에 `getNumbers`에서 `numberRange`에서 get으로 Integer값을 가져와서 LottoNumbers에 넣어주고 있어서 기존 코드에서 캐싱이 되고 있었기에 따로 수정한 부분은 없습니다.
ㄴ 서비스가 많아서 복잡하다는 피드백을 주셨는데, `LottoApplication`에서 LottoService, LottoStatisticsService만 생성하여 사용하도록 정리하였습니다. 사실 `run`에서 서비스가 호출하는 메소드는 3개 뿐이라 서비스가 많아서 복잡한 건 아니라고 생각됩니다. 저는 모델은 데이터의 값을 가지고 있는 정도로써 최소한의 컨버팅과 벨리데이션만 포함시키고 싶기에 서비스에 나머지 기능들을 위임하였습니다. Printer가 각 메소드 전후에 호출되고 있어 `run` 메소드 내 로직이 복잡하게 보이는 것 같습니다. 줄바꿈으로 구분한 각 단계를 `LottoApplication` 내에서 private 메소드로 분리할까 고민도 해보았지만 각 문단에 `(1) 사용자 입력받기 (2) 서비스 메소드 실행 (3) 텍스트 출력`이라는 서로 상이한 목적의 로직들이 포함되어있기에 확신이 서지않아 일단 그대로 두었습니다. 이 부분은 좀 더 고민해본 뒤 리팩토링 해보겠습니다.

감사합니다.

2022-10-13 12:00 UTC, hyunssooo requested changes
안녕하세요. 
개인적인 사정 때문에 확인이 좀 늦었네요. 🙇‍♂️
몇 가지 코멘트 남겼습니다. 확인 부탁드려요.

2022-10-13 12:00 UTC, hyunssooo commented on src/main/java/lotto/models/enums/Rank.java
> +    }
[객체지향 생활 체조 원칙](https://edu.nextstep.camp/s/DVVUSLFe/ls/oy8limcQ)
- 규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

getter를 많이 사용하고 있는데 이번 과정에서는 getter를 최대한 사용하지 않는 것은 어떨까요? 
getter를 사용하지 말라고 하니 많은 분들이 오해하시는 부분이 있는데 view에서는 getter로 데이터를 꺼내는 것이 맞습니다. 
하지만 비즈니스 로직을 풀어내기 위해서 getter를 사용하면 내부의 필드들이 외부로 드러나는데요. 이 과정에서 결합도가 높아질 수 있습니다. 객체에서 필요한 인터페이스(public method)만 제공해서 객체에게 메시지를 보내보면 어떨까요?

2022-10-13 12:00 UTC, hyunssooo commented on src/main/java/lotto/models/request/PaymentRequest.java
> +    }
`정적 팩터리 메서드` 👍 
개인적으로 이 경우는 팩터리 메서드가 필요할까 싶기는해요. 이유는 생성자를 그대로 바이패스 하고 있기 때문입니다.

2022-10-13 12:00 UTC, hyunssooo commented on src/main/java/lotto/validator/LottoNumberValidator.java
> +    }
유틸성 클래스 인스턴스화를 막은 점 👍

2022-10-13 12:00 UTC, hyunssooo commented on src/test/java/lotto/models/enums/RankTest.java
> +    }
`Lotto.of(1, 2, 3, 4, 5, 6)` 이런 메서드가 추가 된다면 테스트를 좀 더 하기 편하지 않을까요? 
클래스를 사용하는 입장에서도 좀 더 편하게 사용할 수 있을 것 같아요.

2022-10-13 12:00 UTC, hyunssooo commented on src/main/java/lotto/services/LottoService.java
>      }
`PickNumberService` 는 필요한가요? 메서드가 `PickNumberStrategy#getNumbers` 만 하고 있어서요.

2022-10-17 09:40 UTC, yerin-158 commented
안녕하세요.
회사 업무가 급해 리뷰 요청이 늦었습니다.

- WinningLotto가 Lotto를 상속받지 않고 필드로 가지도록 수정
- Lotto, WinningLotto가 LottoNumbers의 List\<Integer> numbers를 가져오는 경우, getNumbers() 메소드를 사용해 외부에 필드노출없이 가져오도록 수정
ㄴ `객체에서 필요한 인터페이스(public method)만 제공해서 객체에게 메시지를 보내보면 어떨까요`라는 부분이 이런걸 말씀하시는게 맞을까요?
ㄴ 보통 getNumbers 호출 시 LottoNumbers를 가져오는게 아니라 바로 List\<Integer> 를 가져오게 작성해왔는데 이번 과제에서는 고민을 좀 하다가 저렇게 작성을 했었습니다. 이 부분 언급해주셨길래 다시 수정해보았습니다.
- Lotto.of(LottoNumbers)제거하고 String을 받아 List\<Integer>를 받는 경우와 동일하게 LottoNumbers를 내부에서 생성하도록 변경
- PickNumberService제거, LottoService에서 stategy.getNumbers() 바로 호출하도록 변경

감사합니다.

2022-10-17 12:09 UTC, hyunssooo approved these changes
안녕하세요~ 
몇 가지 코멘트 남겼습니다. 
다음 step 진행하시면서 참고 부탁드려요.

2022-10-17 12:09 UTC, hyunssooo commented on src/main/java/lotto/models/WinningLotto.java
> +    }
> 보통 getNumbers 호출 시 LottoNumbers를 가져오는게 아니라 바로 List<Integer> 를 가져오게 작성해왔는데 이번 과제에서는 고민을 좀 하다가 저렇게 작성을 했었습니다. 이 부분 언급해주셨길래 다시 수정해보았습니다.

의도가 조금 다르게 전달된 것 같아요. 😅 (일반적으로 getter는 필드 그대로를 꺼내는 것이 맞습니다.)
객체에게 역할을 부여하고 메세지(public method)를 보내볼 수 있을 것 같아서요. 
예를 들어 `WinningLotto`는 하나의 `Lotto` 를 받아 해당 `Lotto`의 `Rank`를 리턴 할 수 있지 않을까 생각했어요~

2022-10-17 12:09 UTC, hyunssooo commented on src/main/java/lotto/models/Lotto.java
>      }
제가 처음 생각했던 건 가변 인자를 받는 거였는데 String도 괜찮은 선택인 것 같네요~

2022-10-17 12:09 UTC, hyunssooo commented on src/main/java/lotto/services/LottoService.java
개인적으로 이 부분은 `Lotto` 에 public 상수로 관리해도 괜찮지 않을까 생각해요.
`Lotto. PRICE` 도 어색하진 않은 것 같아서요.

2022-10-17 12:09 UTC, merged