Step2 - 로또(자동)
next-step/java-lotto pull request #2603
Opened 2022-10-12 09:12 UTC by jungwoonson

### 로또 구현 목록
- 입력
  - [x] 돈을 입력 받는다.
  - [x] 지난 주 당첨 번호를 입력받는다.
- 출력
  - [x] 거스름돈을 출력한다.
  - [x] 주어진 로또 수를 출력한다.
  - [x] 주어진 로또들을 출력한다.
  - [x] 당첨 통계를 출력한다.
  - [x] 수익률을 출력한다.
- 돈
  - [x] 돈의 액수를 입력 받는다.
  - [x] 돈이 아닌 문자를 입력 받으면 예외가 발생한다.
  - [x] 0이상의 수가 아니면 예외를 발생시킨다.
  - [x] 주어진 단위로 나눈 수를 준다.
- 판매원
  - [x] 돈을 받는다.
  - [x] 1000원 단위의 돈이 아니면 예외를 발생시킨다.
  - [x] 플레이 가능한 로또 수를 알려준다.
  - [x] 거스름돈을 알려준다.
- 로또 생성기
  - [x] 주어진 수 만큼 로또들을 생성한다. 
- 로또 번호
  - [x] 1~45 사이의 숫자.
  - [x] 6개의 수.
  - [x] 중복되지 않아야함.
  - [x] 오름차순으로 정렬된 로또 숫자들을 문자형으로 반환한다.
  - [x] 중복되는 숫자 개수를 알려준다.
- 당첨정보
  - [x] 일치 수에 따른 상금을 알고 있다.
  - [x] 일치 수에 따른 당첨정보를 알려준다.
  - [x] 총 구매 금액에 따른 수익률을 알려준다.
- 당첨통계
  - [x] 로또리스트와 지난주 당첨 로또로 로또통계를 생성한다.
  - [x] 주어진 당첨정보와 일치하는 당첨정보 수를 반환한다.
  - [x] 수익률을 알려준다.
- Application
  - [x] 입력이 올바르지 않으면 다시 입력하도록 유도한다.

2022-10-12 09:23 UTC, jungwoonson commented
PR이 많이 늦어졌네요ㅠ 그래도 세심한 리뷰 부탁드립니다:) 아! 그리고 이전 PR에 리뷰해주신 사항들을 이번 PR 이후에 수정해보도록 하겠습니다! PR이 너무 늦어져서 먼저 올렸습니다. 그래도 이번 미션에는 최대한 반영하려고 노력했습니다ㅎ 잘부탁드립니다!!

2022-10-12 09:23 UTC, jungwoonson commented on src/main/java/lotto/domain/NullCheckUtil.java
> +}
null 체크를 하기위해 유티 클래스를 만들었는데 이 방식이 최선인이 모르겠습니다. 혹시 더 좋은 방법이 있을까요?

2022-10-13 04:21 UTC, testrace requested changes
안녕하세요 정운님 😃 
2단계 구현 잘해주셨네요 👍 
작은 단위로 커밋을 남겨주셔서 진행 과정을 파악하는데 도움이 많이 되었고 굉장히 인상 깊었습니다!

몇 가지 코멘트 남겨두었는데, 확인해 주시고 리뷰 요청 부탁드립니다!

2022-10-13 04:21 UTC, testrace commented on src/main/java/lotto/domain/LottoGenerator.java
> +            throw new IllegalArgumentException("1이상의 size가 필요합니다.");
커스텀 예외와 자바 표준 예외를 모두 사용하시네요!
정운님만의 커스텀 예외와 자바 표준 예외를 사용하시는 기준이 있으실까요?

2022-10-13 04:21 UTC, testrace commented on src/main/java/lotto/domain/NullCheckUtil.java
> +}
jdk에서 제공하는 Objects.isNull을 활용해 보시면 어떨까요?
유틸성 클래스를 domain 패키지보다 다른 패키지에 있으면 더 좋을 것 같습니다.
코드가 중복이 되어서 하나의 클래스로 분리하는 것은 좋은 판단이라고 생각합니다 👍

2022-10-13 04:21 UTC, testrace commented on src/main/java/lotto/domain/exception/InvalidLottoNumberSizeException.java
> +    }
커스텀 예외 클래스에 정적 팩토리를 활용을 많이 하시네요 😃 
이 예외 클래스를 사용해야하는 다른 개발자가 of 라는 메서드명으로 원하는 예외를 생성할 수 있는지도 고민해 보시면 좋을 것 같아요.

2022-10-13 04:21 UTC, testrace commented on src/main/java/lotto/view/InputView.java
> +                .map(String::trim)
trim 👍

2022-10-13 04:21 UTC, testrace commented on src/test/java/lotto/domain/LottoTest.java
> +    }
재정의한 toString이 요구사항의 어떤 로직을 구현하고 있어서 단위 테스트를 작성하셨을까요?

2022-10-13 04:21 UTC, testrace commented on src/test/java/lotto/domain/MoneyTest.java
> +    @Nested
Nested를 활용한 테스트 👍

2022-10-13 04:21 UTC, testrace commented on src/test/java/lotto/domain/MoneyTest.java
> +    @DisplayName("뺄셈")
다른 단위 테스트처럼 조금 더 테스트의 의도를 명시하면 좋을 것 같습니다 😃

2022-10-13 04:21 UTC, testrace commented on src/test/java/lotto/domain/WinningInformationTest.java
> +    }
로또의 번호가 45개가 아닌 450개로 변경 된다면 이 테스트 fixture는 어떻게 변경될까요?

2022-10-13 22:50 UTC, jungwoonson commented on src/main/java/lotto/domain/Lotto.java
> +    public static Lotto of(final List<String> elements) {
https://7942yongdae.tistory.com/147 이 글을 참고해봤는데 저는 일반적으로 of를 많이 사용하는 것 같아서 그냥 썼던 것 같습니다. 위 처럼 사용할때는 from()이 좀 더 어울릴 것 같네요! 좋은 피드백 감사합니다:)

2022-10-13 22:54 UTC, jungwoonson commented on src/main/java/lotto/domain/LottoGenerator.java
> +            throw new IllegalArgumentException("1이상의 size가 필요합니다.");
Application에서 커스텀된 예외들을 catch해 재입력되도록 했는데 위의 경우에는 그렇지 않아서 IllegalArgumentException으로 만들었습니다. 리뷰어님은 어떻게 생각하시는지요?

2022-10-13 22:55 UTC, jungwoonson commented on src/main/java/lotto/domain/exception/InvalidLottoNumberSizeException.java
> +    }
넵 이것도 마찬가지로 getInstance()가 더욱 적절할 것 같아요 수정해보겠습니다!

2022-10-13 22:56 UTC, jungwoonson commented on src/test/java/lotto/domain/LottoTest.java
> +    }
print 할때 오름차순으로 정렬 되어 출력되더라구요. 이 책임을 옮겨 view쪽에서 처리해보겠습니다.

2022-10-13 23:09 UTC, jungwoonson commented on src/test/java/lotto/domain/MoneyTest.java
> +    @DisplayName("뺄셈")
넵 설명을 조금 더 추가해보는 것이 좋겠네요!

2022-10-13 23:13 UTC, jungwoonson commented on src/main/java/lotto/domain/Cashier.java
> +        }
위와 같은 경우에는 긍정형이 한번에 알아보기 더 좋은 것 같아요! 연산을 한번 생각해야하기 때문에 더 불편해 지네요.
하지만 긍정형과 부정형 둘 다 만들 필요는 없을 것 같다는 생각이 들었어요. 만약 기능은 같은데 반대의 결과를 도출하는 메소드가 있다면 그냥 '!'연산자를 사용하는 것도 좋을 것 같아요.:)

2022-10-15 05:33 UTC, jungwoonson commented on src/main/java/lotto/domain/Cashier.java
> +    }
정말 모든 기본 타입을 포장해야하는군요! 넵 한번 해보겠습니다:)

2022-10-15 08:43 UTC, jungwoonson commented on src/main/java/lotto/domain/Lotto.java
> +    private final Set<Integer> elements;
미처 생각하지 못했네요... 실제로 책임을 분리해보니 엄청 많은 수정이 필요하네요ㅠ

2022-10-15 08:44 UTC, jungwoonson commented on src/main/java/lotto/domain/Lotto.java
> +    }
위의 코멘트와 같은 이야기네요!!

2022-10-15 08:45 UTC, jungwoonson commented on src/main/java/lotto/domain/Lotto.java
> +    }
네 확실히 두개이상의 책임을 준거 같습니다. 수정해보겠습니다!

2022-10-15 10:19 UTC, jungwoonson commented on src/test/java/lotto/domain/WinningInformationTest.java
> +    }
이런류의 테스트는 어떻게 하는것이 좋을까요? valses() 메소드로 모든 값을 초기화한수 from 메소드 테스트를 만들어 봤는데 결국 의미 없는 테스트 코드가 되더라구요 혹시 좋은 방법이 있을까요? 아니면 굳이 모든 값을 테스트 할 필요 없이 하나만 테스트 하면 될까요?

2022-10-15 10:19 UTC, jungwoonson commented on src/main/java/lotto/domain/Cashier.java
> +    }
거스름돈 계산 책임을 Money로 옮기다 보니 Cachier가 필요없다는 생각이 들이 Money로 합쳤습니다!

2022-10-16 09:13 UTC, testrace commented on src/main/java/lotto/domain/LottoGenerator.java
> +            throw new IllegalArgumentException("1이상의 size가 필요합니다.");
정운님의 기준도 괜찮아 보입니다 😃 
저는 개인적으로 비즈니스와 관련된 로직은 커스텀 예외를 가능하면 사용하려하는 편입니다.

2022-10-16 09:16 UTC, testrace commented on src/test/java/lotto/domain/WinningInformationTest.java
> +    }
가능하면 경계값, 임계값 위주의 테스트가 이상적이겠지만, 경우에 따라서는 많은 경우의 수를 테스트해야할 수도 있을 것 같아요!
Enum에 대한 테스트 코드이니,` @EnumSource`를 활용하면 어떨까요?

2022-10-16 09:48 UTC, testrace approved these changes
안녕하세요 정운님 😃 
피드백 반영 잘해주셨네요!
코드량이 많이 변경되어서 쉽지 않으셨을 텐데 원시값 포장으로 인해 책임이 잘 나누어진것 같아요 👍 
바로 다음 단계 진행해 주세요 🔥 
몇 가지 코멘트 남겨두었는데 다음 단계 진행하시면서 확인 부탁드려요!

2022-10-16 09:48 UTC, testrace commented on src/main/java/lotto/domain/AutoLottoGenerator.java
> +            Set<LottoNumber> lottoNumbers = new HashSet<>(copiedLottoNumbers.subList(0, MAX_SIZE));
Nit: 지난번에 정렬하던 로직이 사라졌네요!
정렬 기능을 지원하는 자료구조를 사용해 보시면 어떨까요?

2022-10-16 09:48 UTC, testrace commented on src/main/java/lotto/domain/Lotto.java
> +        return elements.contains(lottoNumber);
메서드명 isMatch보다 contains는 어떻게 생각하세요? 🤔

2022-10-16 09:48 UTC, testrace commented on src/main/java/lotto/domain/Lotto.java
> +        return elements.toString();
출력을 위해 toString을 사용하기보다 getter와 같은 별도의 메서드를 제공하면 어떨까요?
관련해서 이펙티브 자바의 `toString을 항상 재정의하라` 를 참고해 보시면 좋을 것 같아요! 😃

2022-10-16 09:48 UTC, testrace commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
Comparable 구현하셨네요 👍

2022-10-16 09:48 UTC, testrace commented on src/main/java/lotto/domain/PlayLottoCount.java
> +    public int getValue() {
클래스 구현 순서는 다음과 같이 중요한 순서로 위치하면 어떨까요?

```
class  T {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

2022-10-16 09:48 UTC, testrace commented on src/main/java/lotto/domain/WinningInformation.java
>                  .filter(w -> w.matchesCount == matchesCount)
스트림 내부의 변수라고 해도 w 와 같은 변수명보다 조금 더 의미 있는 이름이 부여되면 좋을 것 같아요!

2022-10-16 09:48 UTC, testrace commented on src/test/java/lotto/domain/LottoNumberTest.java
> +        }
경계값 테스트 👍 
예외 메시지에 어떤 값을 입력이 되어서 예외가 발생했는지도 알려줘도 좋을 것 같아요 😃

2022-10-16 09:48 UTC, testrace commented on src/test/java/lotto/domain/PlayLottoCountTest.java
> +    }
정상 생성에 대한 테스트도 있으면 좋을 것 같아요 😃

2022-10-16 09:48 UTC, testrace commented on src/test/java/lotto/domain/WinningStatisticsTest.java
> +                        .collect(Collectors.toSet()))
중복을 제거하면 테스트 코드의 가독성을 높일 수 있을 것 같은데 어떻게 생각하세요?

2022-10-16 09:48 UTC, merged

2022-10-16 14:03 UTC, jungwoonson commented on src/main/java/lotto/domain/PlayLottoCount.java
> +    public int getValue() {
getter setter 를 제일 마지막에 배치하는 것이  컨벤션이라고 해서 그렇게 했었는데 getter setter는 기본 메소드 위에 배치해야 하는건가요? 혹시 참고할 만한 글이 있을까요?

2022-10-16 14:05 UTC, jungwoonson commented on src/main/java/lotto/domain/Lotto.java
> +        return elements.contains(lottoNumber);
코드를 처음 봤을때 contains가 코드의 흐름을 이해하기 더 좋은 것 같네요!

2022-10-16 14:06 UTC, jungwoonson commented on src/main/java/lotto/domain/Lotto.java
> +        return elements.toString();
넵 한번 참고해보겠습니다 감사합니다!!

2022-10-16 14:07 UTC, jungwoonson commented on src/main/java/lotto/domain/WinningInformation.java
>                  .filter(w -> w.matchesCount == matchesCount)
스트림 내부에서 사용하는 변수명이 정말 애매한 것 같아요 많은 사람들이 it을 사용하던데 이유가 있을까요? 아니면 규칙이 있을까요?

2022-10-16 14:09 UTC, jungwoonson commented on src/test/java/lotto/domain/WinningStatisticsTest.java
> +                        .collect(Collectors.toSet()))
올리기 전에 수정했어야 하는 부분인데 미처 확인하지 못했던 것 같아요. 다음 PR에 정리해보겠습니다!

2022-10-16 14:11 UTC, jungwoonson commented on src/test/java/lotto/domain/LottoNumberTest.java
> +        }
어떤 값인지 알려준다면 확실히 클라이언트에게 도움이 되겠네요. 다음 PR에 반영해보겠습니다!

2022-10-16 14:13 UTC, jungwoonson commented on src/main/java/lotto/domain/AutoLottoGenerator.java
> +            Set<LottoNumber> lottoNumbers = new HashSet<>(copiedLottoNumbers.subList(0, MAX_SIZE));
굳이 정렬이 필요 없을 것 같아서 그냥 없애봤는데 다음 PR에 정렬해보겠습니다:)

2022-10-17 10:04 UTC, jungwoonson commented on src/main/java/lotto/domain/Lotto.java
> +        return elements.toString();
읽어보니 toString의 용도는 제가 생각했던 것과 많이 다르네요! 인텔리제이의 toString 자동 생성 도구를 사용하면 빠르게 재정의가 가능해서 좋네요ㅎㅎ 참고자료를 포함해서 설명해주시는 것 많은 도움이 되는 것 같아요:) 감사합니다!!

2022-10-17 10:18 UTC, jungwoonson commented on src/test/java/lotto/domain/PlayLottoCountTest.java
> +    }
현재 구현 로직에서 필요한 생성자는 하나인데 테스트를 위한 생성자를 하나 만드는게 나을까요? 아니면 단순히 getter를 사용헤 주입된 값이 같은지 비교하는 식으로 생성자 테스트를 하는것이 좋을까요?

2022-10-17 12:55 UTC, testrace commented on src/main/java/lotto/domain/PlayLottoCount.java
> +    public int getValue() {
컨벤션에는 사실 정답은 없다고 생각해요! ㅎㅎ
팀마다 다르고, 가장 많이 사용하는 구글 컨벤션을 기반으로 팀의 상황에 맞게 필요한 부분만 변경해서 사용하는 경우가 가장 많은 것 같아요.
저는 오라클에서 정의한 컨벤션은 기본적인 가이드 정도로 받아들이고 있습니다.
제시해드린 클래스 구성 순서도 오라클에서 정의한 것과는 크게 다르진 않다고 생각해요.

기본 메서드(equals, hashCode, toString)은 모든 클래스가 Object를 자동으로 상속하면서 재정의할 때 쓰이기 때문에, 
도메인 객체가 가지는 책임과는 무관하다고 생각해요.
그렇기 때문에 getter와 같이 객체가 수행해야하는 책임이 기본 메서드들보다 상위에 위치하는게 더 좋다고 생각합니다 😃

2022-10-17 12:58 UTC, testrace commented on src/main/java/lotto/domain/WinningInformation.java
>                  .filter(w -> w.matchesCount == matchesCount)
코틀린에서 it 을 사용을 하기 때문에 많은 분들이 그렇게 사용하는 것 같아요.
스트림의 내부 코드 또한 코드이기 때문에 특별한 네이밍 규칙을 정하지 않으셨다면 
객체의 인스턴스 변수나, 메서드 내에서의 지역변수를 선언하듯이 축약하지 않고 사용하시는 것도 좋은 연습이 될거라고 생각합니다!
팀내의 컨벤션에서 관련 규칙이 생긴다면 거기에 따르면 되니, 
학습 과정에서는 모든 네이밍에 축약하지 않고 구현해 보시는 것을 추천드려요 😃

2022-10-17 13:03 UTC, testrace commented on src/test/java/lotto/domain/PlayLottoCountTest.java
> +    }
가능하면 객체끼리 비교하는 것을 추천드려요. 
테스트를 위한 생성자도 사이드 이펙트가 생기지만 않는다면 괜찮다고 생각합니다! 😃