3단계 - 로또(2등)
next-step/java-lotto pull request #2624
Opened 2022-10-14 06:17 UTC by Yunsik-Choi

안녕하세요 지훈님 3단계 리뷰 부탁드립니다!

3단계를 진행하면서 제 코드를 읽어보니 Service클래스나 Controller클래스에서 로직에대한 이해가 없으면 읽기 힘들다고 느꼈습니다.

혹시 지훈님도 그렇게 생각하시면 어떤 부분에서 그런지 알려주실 수 있을까요??

2022-10-14 07:53 UTC, vagabond95 requested changes
3단계 구현하시느라 고생많으셨습니다 👍 

질문주신 내용을 포함하여, 구현해주신 내용에 대하여 리뷰 남겼는데요. 확인 부탁드릴게요!

2022-10-14 07:53 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoReward.java
> +    private int rank;
각 enum 의 element 에 이미 등수가 드러나는데, rank 라는 값을 중복으로 두어야할 이유가 있을까요?

2022-10-14 07:53 UTC, vagabond95 commented on src/main/java/lotto/LottoController.java
> +        LottoOutput.match(3, LottoReward.FIFTH.reward(), checkLotto.get(LottoReward.FIFTH.rank()));
반복적으로 나오는 코드들을 줄여볼 수 있을까요? 각 등수마다 코드를 적어주어야하는 것은 상대적으로 비효율적일 것 같아요.

2022-10-14 07:53 UTC, vagabond95 commented on src/main/java/lotto/domain/Money.java
> +    private long money;
long 으로 바꾸신 이유가 있을까요?

2022-10-14 07:53 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoWinner.java
> +        if (this.lottoNumbers.match(lotto.numbers()) == 3) {
등수를 각각 검사하는 것은 비효율적일 것 같아요.

어떤 등수가 들어오더라도 코드가 늘어나지 않는 구조로 리펙토링해볼 수 있을까요?

2022-10-14 07:53 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoWinner.java
> +        if (this.lottoNumbers.match(lotto.numbers()) == 3) {
enum 을 좀 더 활용해봐도 좋을것 같습니다 ㅎ

2022-10-14 09:04 UTC, Yunsik-Choi commented
안녕하세요 3단계 코멘트 잘읽었습니다 감사합니다. 🙇‍♂️

1. rank를 만든 이유
rank를 enum의 순서에 따라 사용하는 것이 아닌 상태로 가지고 있으면 더 편하게 사용할 수 있다고 생각했습니다! 우선 rank를 없애는 방향으로 리팩토링을 진행해봤습니다.

2. long으로 바꾼 이유
로또 추첨 후 수익율을 계산하는 로직에서 int값의 한계는 21억정도이기에 총 상금이 21억을 벗어나면 에러가 날 수 있다고 생각해 long으로 변경하였습니다.

변경사항
[x] LottoController에 출력하는 부분 변경
[x] LottoReward에 count 추가

코멘트 바탕으로 리팩토링을 진행해보았는데 리뷰 부탁드립니다! 
추가로 말씀해주신대로 하드코딩 된 값들을 리팩토링 해보았는데 이 부분도 확인 부탁드립니다!

긴 글 읽어주셔서 감사합니다 🙇‍♂️

2022-10-15 08:16 UTC, vagabond95 requested changes
수정한 내용에 대한 생각을 남겨주셔서 감사해요! 덕분에 코드의 맥락을 좀 더 이해하기 쉬웠습니다 ㅎㅎ

수정해주신 내용 중에 가볍게 개선해볼 부분이 추가로 보여 리뷰 남겼어요. 확인 부탁드려요!

2022-10-15 08:16 UTC, vagabond95 commented on src/main/java/lotto/LottoController.java
> +    private boolean bonus_rank(int i) {
자바에서 메소드 네이밍 컨벤션상 snake case 는 지양하고 있습니다!

2022-10-15 08:16 UTC, vagabond95 commented on src/main/java/lotto/LottoController.java
> +    private boolean bonus_rank(int i) {
파라미터에 대한 이름을 좀 더 구체적으로 지어주는것은 어떨까요?

2022-10-15 09:11 UTC, Yunsik-Choi commented
안녕하세요 저런 문제를 만들어 놨었군요 왜 리뷰 요청 보낼 때는 안보일까요 😅

리뷰 요청을 보내기 전에 한 번 더 꼼꼼히 읽어보도록 하겠습니다!!

말씀해주신 대로 프로젝트 코드상에서 파라미터 네이밍이 부족한 부분들을 살피고 변경해보았습니다

리뷰 부탁드립니다 🙏

2022-10-16 03:53 UTC, vagabond95 approved these changes
당시에 집중하시는 문제의 포커스가 달랐어서 잘 안보이셨을수도 있죠! ㅎㅎ

3단계는 추가적으로 리뷰 드릴 부분이 없어 머지하겠습니다. 고생 많으셨어요!

2022-10-16 03:53 UTC, merged