3단계 - 로또(2등)
next-step/java-lotto pull request #2628
Opened 2022-10-14 16:10 UTC by kingkk31

안녕하세요, 개인 사정이 생겼어서 부득이하게 다음 단계를 이제야 진행했습니다ㅜㅜ
2등과 저번 PR 마지막 피드백을 적용하였습니다. 리뷰 부탁드립니다!!

2022-10-16 12:31 UTC, ksy90101 requested changes
안녕하세요 :)
리뷰가 조금 늦었네요. 죄송합니다.
간단한 피드백을 남겼으니, 한번 확인해주시면 감사하겠습니다.
질문은 언제든 환영입니다 💯

2022-10-16 12:31 UTC, ksy90101 commented on src/main/java/lotto/domain/number/LottoBalls.java
> +    public LottoBalls(List<LottoBall> lottoBalls) {
파일이 안보여서, LottoBall의 equals에 아래와 같이 class가 동일한지 먼저 검증하면 더 좋을듯 해요.

```
    public boolean equals(Object obj) {
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        LottoBall lottoBall = (LottoBall) obj;
        return this.number == lottoBall.getNumber();
    }

```

2022-10-16 12:31 UTC, ksy90101 commented on src/main/java/lotto/view/LottoInputView.java
> +        LottoBalls lottoBalls = new LottoBalls(
Static 메서드만 있을 경우엔 기본 생성자로 인스턴스 생성하지 못하도록 막는게 좋을듯 합니다!

2022-10-16 12:31 UTC, ksy90101 commented on src/test/java/lotto/domain/winner/WinningConditionTest.java
>      @DisplayName("주어진 일치 횟수에 해당하는 당첨 조건이 없다면 예외 발생")
getConditionsWithPrize 메서드에 대한 테스트 코드는 없군요!

2022-10-16 12:31 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoMachine.java
> +    default int getTicketCount(PurchasePrice purchasePrice, int ticketPrice) {
default는 생략이 가능합니다.
아울러 혹시 defualt 접근제어자를 사용하신 이유가 있나요!?

2022-10-16 12:31 UTC, ksy90101 commented on src/main/java/lotto/domain/number/WinningTicket.java
> +                .anyMatch(ball -> ball.getNumber() == bonusBall.getNumber());
ball과 bonusBall은 결국 LottoBall이죠.
그렇다면, getter를 사용하지 않고 동일성을 판단할 수 있지 않을까요?

2022-10-16 12:31 UTC, ksy90101 commented on src/main/java/lotto/domain/winner/WinningCondition.java
> +                                && (!condition.requiredBonus || condition.bonusMatch == bonusMatch))
지금과 같이 조건이 좀 길면, private 메서드로 하는것도 방법이에요~

2022-10-16 12:31 UTC, ksy90101 commented on src/main/java/lotto/view/LottoInputView.java
> +                Arrays.stream(insertData().split(", "))
", " 매직스트링!

2022-10-16 12:31 UTC, ksy90101 commented on src/test/java/lotto/domain/winner/WinningReportTest.java
>          );
지금과 같이 모든 등수 검증을 하나의 테스트 코드를 해도 좋지만, 각각에 대해선 독립성을 가져야 할수 있다고도 생각해요.
그런경우엔 @ParamterziedTest를 많이 사용하는데, 한번 변경해보면 어떨까요?

2022-10-19 11:08 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoMachine.java
> +    default int getTicketCount(PurchasePrice purchasePrice, int ticketPrice) {
👍 여쭤본 이유는 default 생성자를 아무 이유 없이 사용하는 경우가 많더라구요.
그래서 한번 여쭤보았습니다 👍

2022-10-19 11:16 UTC, ksy90101 approved these changes
안녕하세요 :) 사정이 있어 리뷰가 초큼 늦었네요 ㅠㅠ 죄송합니다.
3단계 피드백 적용도 고생 많으셨습니다 💯 
간단한 피드백을 좀 더 남기긴 하였는데 4단계가 있기 때문에 4단계에서 충분히 적용가능할거라 생각합니다.
그럼 4단계때 뵙겠습니다!

2022-10-19 11:16 UTC, ksy90101 commented on src/test/java/lotto/domain/winner/WinningConditionTest.java
> +                MATCH_SIX);
이 부분도 @ParamterziedTest로 작성한다면 더 좋을듯 합니다.

2022-10-19 11:16 UTC, ksy90101 commented on src/test/java/lotto/domain/winner/WinningConditionTest.java
> +        ).isEqualTo(5);
assertAll()을 아시나요?
한번 알아보시고 사용해보시면 좋을듯 합니다.

아울러 현재 assertThat()에 로직 자체가 들어가 있는데, 이러면 어떤것이 actual값이 알기가 힘든거 같아요. 변수로 빼서 작성해두면 더 보기 좋을듯 합니다.

2022-10-19 11:16 UTC, merged

2022-10-19 11:19 UTC, kingkk31 commented on src/test/java/lotto/domain/winner/WinningConditionTest.java
> +        ).isEqualTo(5);
@ksy90101 평소에 assertAll 로 여러 assert 문을 묶어 사용하긴합니다. 다만 귀찮아서 빼먹었습니다ㅜㅜ 다음 단계에서 추가하겠습니다!