3단계 - 로또(2등)
next-step/java-lotto pull request #2633
Opened 2022-10-15 15:02 UTC by yeonsuyang

3단계도 잘 부탁드립니다~

2022-10-16 12:48 UTC, pkch93 requested changes
안녕하세요 연수님 👋
빠르게 3단계도 구현해주셨네요 ㅎㅎ
몇가지 피드백 드렸는데 확인부탁드립니다!

2022-10-16 12:48 UTC, pkch93 commented on src/main/java/step3/domian/Prize.java
> +    public final String text;
text는 콘솔에 보여지는 메세지로 보이는데요. 도메인 영역에 두신 이유가 있을까요?

2022-10-16 12:48 UTC, pkch93 commented on src/main/java/step3/domian/Revenue.java
> +    public Revenue(int revenue) {
테스트에서만 사용하는 생성자네요. 위 List를 인자로 받는 생성자로 테스트할 수 없었을까요?

2022-10-16 12:48 UTC, pkch93 commented on src/main/java/step3/domian/Revenue.java
> +    private int revenue;
```suggestion
    private final int revenue;
```
final 키워드를 붙이면 어떨까요?

2022-10-16 12:48 UTC, pkch93 commented on src/main/java/step3/domian/Revenue.java
> +        result += (Prize.SIX_PRIZE.prizeMoney * results.get(Prize.SIX_PRIZE.position));
지금은 상이 추가될때마다 여기에 로직이 변경되어야하는데요.
Prize enum과 함께 stream이나 for문으로 처리해서 상 추가가 되면 위 로직을 변경하지 않더라도 반영이 되도록 수정해보면 어떨까요?

2022-10-16 12:48 UTC, pkch93 commented on src/main/java/step3/domian/LottoWallet.java
> +    }
position이 굳이 필요할까 싶네요. 코드를 이해하기 어렵게 만드는 원인이라고 생각이 드는데요.
EnumMap과 Prize를 활용해보면 어떨까요? getPosition가 하는 로또 당첨을 구하는 부분도 더 적절한 클래스로 역할을 옮겨보면 어떨까요?

2022-10-16 12:48 UTC, pkch93 commented on src/main/java/step3/domian/Revenue.java
> +    public float calculatePercentage(int lottoPrice) {
https://github.com/next-step/java-lotto/pull/2583#discussion_r995187922

이전 단계 머지하면서 위와 같이 피드백을 드렸었는데요. 피드백 반영을 하지 않으셔도 괜찮은데 하지 않으신 이유를 알려주시면 좋을거 같아요 ㅎㅎ

2022-10-19 06:41 UTC, yeonsuyang commented on src/main/java/step3/domian/Prize.java
> +    public final String text;
view영역에서 등수가 늘어날 때마다, 상수를 추가해줘야하는데 상수가 늘어날 수록 관리가 어렵다고 생각하였고 view객체가 domain패키지에 의존하는 것은 괜찮다고 생각하여 그렇게 하였습니다..!

2022-10-19 16:44 UTC, yeonsuyang commented on src/main/java/step3/domian/Revenue.java
> +        result += (Prize.SIX_PRIZE.prizeMoney * results.get(Prize.SIX_PRIZE.position));
감사합니다. 반영하였습니다~

2022-10-19 16:45 UTC, yeonsuyang commented on src/main/java/step3/domian/LottoWallet.java
> +    }
EnumMap을 사용하는 것이 좋은 것 같아 반영하였습니다. 다만 enumMap의 경우 0으로 map을 초기화하는 법을 찾지 못하여 부득이하게 메서드를 하나 더 만들고 그렇기 위해 클래스를 생성하였습니다. 관련하여 map을 초기화하는 방법을 혹시 아신다면 조언 부탁드립니다~

2022-10-19 16:45 UTC, yeonsuyang commented on src/main/java/step3/domian/Revenue.java
> +    public float calculatePercentage(int lottoPrice) {
헉 죄송합니다 리뷰를 보고 double과 float의 차이점도 찾아봐놓고 반영하는걸 깜박하였습니다 반영하였습니다~

2022-10-19 16:46 UTC, yeonsuyang commented on src/main/java/step3/domian/Prize.java
> +    public final String text;
기존으로 돌아가겠습니다

2022-10-20 10:57 UTC, pkch93 commented on src/main/java/step3/domian/Revenue.java
> +    public Revenue(int revenue) {
한번 논의가 되었었군요 👍 
저의 입장은 테스트를 위해 프로덕션 코드에 기능을 추가하거나 생성 지점을 추가하는 것은 지양해야한다고 생각해요.

`asdfas` 분께서 말씀하신 것처럼 이미 정의한 생성자는 같이 유지보수하는 다른 개발자 분이 오용할수도 있구요. 의도와 다르게 사용될 수 있기 때문에 테스트를 위한 코드는 프로덕션 코드에 두면 안된다고 생각해요.

또 객체의 생명주기에서 생성 지점을 관리하는 것은 중요하다고 생각하는데요. 이 생성지점이 늘어날수록 해당 객체의 변경에 영향을 받는 지점이 늘어날꺼에요. 특히나 프로덕션에서 사용하지 않는 생성자라면 더더욱 정의할 필요가 없겠죠. 불필요하게 생성 지점을 노출하게 되니깐요.

하지만 테스트 fixture를 매번 테스트마다 정의하는 것은 매우 귀찮고 테스트를 작성하기 어렵게 만드는 일이라고 생각해요. (특히 크기가 크고 복잡한 객체일수록...) 이 경우에는 gradle의 도움을 받을 수 있을텐데요. gradle의 java 플러그인은 main과 test SourceSet을 제공해줘요. main에는 실제 프로덕션 코드를 정의하고 test에는 테스트 코드와 테스트 내에서 사용할 코드를 정의하는데요. 테스트에서 사용하는 편의 메서드나 utils는 test SourceSet 내에서 정의해서 사용하면 어떨까요?

물론 수익값을 직접 넣는 부분이 사라지겠지만 Prize를 쉽게 넣을 수 있도록 만들어 테스트 객체를 만들기 편하게 해줄 수 있지 않을까 싶어요.

시간이 되시면 test fixture를 위한 SourceSet을 제공해주는 [java-test-fixture](https://toss.tech/article/how-to-manage-test-dependency-in-gradle)에 대해서도 학습해보시면 좋을거 같아요 ㅎㅎ

2022-10-20 11:29 UTC, pkch93 requested changes
안녕하세요 연수님 ㅎㅎ
피드백 반영 확인했습니다 ㅎㅎ 감사합니다. 👍 
다만, 몇가지 개선할 점이 있는거 같아 피드백 추가로 드렸는데요 한번 확인 부탁드립니다 ㅎㅎ

2022-10-20 11:29 UTC, pkch93 commented on src/main/java/step3/domian/Prize.java
> +    public final String text;
네넵 ㅎㅎ 감사합니다. 위 text 부분은 View 영역에서 담당해야할 영역이라 생각해서 위와 같이 피드백 드린거였어요 :)

2022-10-20 11:29 UTC, pkch93 commented on src/main/java/step3/domian/Revenue.java
> +        this.revenue = Arrays.stream(Prize.values()).map(it -> it.prizeMoney * results.getResultCount(it)).mapToInt(it -> it.intValue()).sum();
```java
this.revenue = Arrays.stream(Prize.values())
                .map(it -> it.prizeMoney * results.getResultCount(it))
                .mapToInt(it -> it.intValue())
                .sum();
```
stream을 사용하실때 한줄에 하나의 점 `.` 만 사용하면 가독성이 좋아질거 같네요 ㅎㅎ

2022-10-20 11:29 UTC, pkch93 commented on src/main/java/step3/domian/LottoWallet.java
> +    }
Prize enum을 키로 가지기는 하지만 EnumMap이 아니라 HashMap을 사용하고 계시네요.

```java
.collect(Collectors.toMap(
    prize -> prize,
    prize -> 1L,
    Long::sum,
    () -> new EnumMap<>(Prize.class)))
);
```
이런 식으로 `toMap`의 `mapFactory`로 EnumMap을 반환하도록 만들면  EnumMap을 사용하도록 만들수 있을거 같아요.

지금도 0으로 초기화 하는 부분은 없어보이는데 어떤 부분을 말씀하시는걸까요?

2022-10-20 15:02 UTC, yeonsuyang commented on src/main/java/step3/domian/LottoWallet.java
> +    }
mergefuntion의 활용법을 몰랐습니다! 합치고 싶은데, 그러면 null과 합치게 돼서 여쭤본거였습니다 mergefuntion을 알게되어 공부했네요 감사합니다

2022-10-20 15:03 UTC, yeonsuyang commented on src/main/java/step3/domian/Revenue.java
> +    public Revenue(int revenue) {
잘 읽어보았습니다. 감사합니다. 해당 생성자를 테스트하는 테스트메서드는 제거하고 lastwinner의 변수들이 private으로 될 수 있도록 몇가지 메서드들의 위치를 변경하였습니다.

2022-10-21 03:32 UTC, pkch93 approved these changes
로또 3단계 미션 고생하셨습니다 :)
이제 로또 마지막 단계만 남았네요. 조금만 힘내서 로또 미션 잘 마무리하면 좋겠네요 ㅎㅎ
몇가지 추가 의견 드린게 있는데 이건 다음 단계 진행하시면서 같이 고민해봐도 좋을거 같아요..!
연수님의 로또 3단계는 이만 머지하겠습니다 ㅎㅎ 다음단계에서 뵈요 👋

2022-10-21 03:32 UTC, pkch93 commented on src/main/java/step3/domian/LottoWallet.java
> +        return new LottoResult(this.lottos.stream().map(lotto -> {
```suggestion
        return new LottoResult(this.lottos
        .stream()
        .map(lotto -> {
                    int count = lastWinner.countSameNumber(lotto);
                    return Prize.getPrize(count, checkBonus(count, lastWinner, lotto));
                })
```
점 하나당 한줄로 사용하면 좋을거 같네요 :)
추가로 map 내부에 들어가는 등수를 판단하는 로직은 별도 메서드로 빼도 좋을거 같아요 :)

2022-10-21 03:32 UTC, pkch93 commented on src/main/java/step3/domian/Prize.java
> +    }
지금은 만약 상이 새롭게 생기거나 8개가 맞았을때 같은 상황에 대응하려면 getPrize에 변경이 필요할거 같은데요. (물론 Enum 값 추가가 필요하겠지만...)

Prize Enum의 객체에서 판단할 수 있도록 메서드를 정의할 수도 있을거 같네요 ㅎㅎ

2022-10-21 03:32 UTC, merged