로또(TDD) - STEP4
next-step/java-lotto pull request #2639
Opened 2022-10-16 06:11 UTC by jbpark-in-seoul

희주님, 안녕하세요! 😄

로또 3단계 피드백 주신 내용과 로또 4단계 진행하였습니다.
코드 리뷰 부탁드리겠습니다. 🙇🏻‍♂️

감사합니다.

2022-10-16 13:54 UTC, choihz requested changes
안녕하세요, 재범님!

구현해 주신 내용을 보고 피드백을 몇 가지 남겨 두었는데 확인해 주시고, 궁금한 점이나 의견이 있으실 땐 부담 없이 코멘트나 DM 주세요!

2022-10-16 13:54 UTC, choihz commented on README.md
> +  * `winningLotto`: 당첨 번호를 `Lotto`타입으로 반환
<img width="239" alt="스크린샷 2022-10-16 오후 10 18 23" src="https://user-images.githubusercontent.com/18049492/196037661-00155092-1e49-4646-b968-68c79fbaa2c0.png">

불필요한 파일들이 커밋에 포함되어 있네요. 커밋 시마다 항상 확인해 주세요.

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/controller/LottoController.java
> +import java.util.Arrays;
27497286 커밋과 daa11257 커밋 모두 크기가 너무 커요! 하위에 리스팅된 각각의 항목을 따로 커밋해 주시는 것이 가장 좋습니다. 실수 확률도 적어지고, 롤백도 쉽고, 지금 또는 나중에 이력을 확인하기에도 좋고요.

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/domain/Lotto.java
> +    }
중복을 허용하지 않는 자료구조를 활용해 보는 건 어떨까요?

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/view/Input.java
> +import java.util.*;
위에 사용되지 않는 `import` 문이 있는데 항상 정리해 주세요~

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/domain/Payment.java
>      }
`validateAmount()`가 `validateManualCount()`보다 먼저 사용되므로, 메서드 배치 순서도 이에 맞추면 코드를 읽기 더 편하지 않을까요?

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/domain/Payment.java
> +    }
<img width="797" alt="스크린샷 2022-10-16 오후 10 27 22" src="https://user-images.githubusercontent.com/18049492/196038043-601ef10f-8601-44e6-8c40-4b53637dac91.png">

🤔

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/controller/LottoController.java
>          Output.printReturnOnInvestment(resultStats.returnOnInvestment(payment.amount()));
<img width="196" alt="스크린샷 2022-10-16 오후 10 30 10" src="https://user-images.githubusercontent.com/18049492/196038221-b5b2948c-898c-45cd-99d4-39b25e501e2d.png">

스펙이 정확히 작성되어 있지는 않지만, 요구사항의 예시로 봐서는 수익률을 소수점 둘째자리까지 출력해야 하는 것 같아요.

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/view/Output.java
> +    }
이 모든 조건을 매번 이해하며 읽기 쉽지 않을 것 같아요. 각 조건에 이름을 붙여줄 방법은 없을까요?

2022-10-16 13:54 UTC, choihz commented on src/test/java/lotto/domain/LottoMachineTest.java
> +        assertThat(new LottoMachine(lottoNumbers()).automaticIssue(10).size()).isEqualTo(10);
```suggestion
        assertThat(new LottoMachine(lottoNumbers()).automaticIssue(10)).hasSize(10);
```

이런 메서드도 적극 활용해 보아요~ (리뷰하며 보니 다른 곳에서는 사용 중이시네요 😮)

2022-10-16 13:54 UTC, choihz commented on src/test/java/lotto/domain/LottoMachineTest.java
>      @DisplayName("로또 발급 검증")
정확히는 로또 개수만 검증하고 있는 것 같아요. 테스트 이름도 상황을 자세히 설명해 준다면 좋겠죠?

2022-10-16 13:54 UTC, choihz commented on src/test/java/lotto/domain/LottoTest.java
> +        assertThat(new Lotto(LottoNumber.lottoNumbers().subList(0,6)).lottoNumbers().size()).isEqualTo(6);
```suggestion
        assertThat(new Lotto(LottoNumber.lottoNumbers().subList(0, 6)).lottoNumbers()).hasSize(6);
```

1. 포맷팅도 항상 신경 써 주세요 😎
2. 그런데 이 테스트는 정확히 무엇을 검증하는 걸까요?

2022-10-16 13:54 UTC, choihz commented on src/test/java/lotto/domain/LottoTest.java
>      @DisplayName("생성자 의존성 주입 - 로또 번호")
현 맥락에서 "의존성 주입"이라고 할 게 있을까요? 생성자로 값을 넘기면 모두 의존성 주입인가요?

2022-10-16 13:54 UTC, choihz commented on src/test/java/lotto/domain/LottoTest.java
>          assertThatThrownBy(() -> new Lotto(LottoNumber.lottoNumbers().subList(0, 7))).isInstanceOf(IllegalArgumentException.class);
```suggestion
        assertThatThrownBy(() -> new Lotto(LottoNumber.lottoNumbers().subList(0, 7)))
                .isInstanceOf(IllegalArgumentException.class);
```

1. 이렇게 줄바꿈이 한 번 들어가면 가독성이 더 좋아질 것 같아요.
2. `LottoNumber.lottoNumbers().subList(0, 7)`처럼 배경지식을 요하는 메서드를 사용하기보다, 딱 봐도 바로 어떤 숫자가 들어가는지 알 수 있게 하면 명확성, 가독성 등에서 더 좋지 않을까요? 숫자를 넣으면 바로 해당 숫자들로 `List<LottoNumber>`를 만드는 메서드를 테스트 코드에 만드는 방법은 어떨까요?

2022-10-16 13:54 UTC, choihz commented on src/test/java/lotto/domain/LottoTest.java
> +    @DisplayName("생성자 의존성 주입 - 당첨 번호 중복 예외")
```suggestion
    @DisplayName("중복되는 숫자로 로또 생성 시 예외가 발생한다")
```

이런 방식의 테스트 네이밍은 어떨까요? (당연히도 꼭 수정해 달라는 의미는 아니에요 😉)
또한 이 테스트와 바로 위의 테스트의 경우 테스트 이름에 "당첨 번호"가 들어가는데 실제로는 별로 상관이 없어 보이네요.

2022-10-16 13:54 UTC, choihz commented on src/test/java/lotto/domain/LottoTest.java
>      @DisplayName("발급 로또 티켓, 당첨 티켓 비교")
이 테스트도 마찬가지인데요, 테스트 코드를 읽고 이해하는 데 오랜 시간이 걸리면 이걸 유지하기가 너무 힘들어져요. 전체적으로 최대한 간결하게, 하나의 메서드에서는 한 가지만 검증하도록, 그리고 이름은 명확하게(어떤 상황에서 무엇을 검증하는지) 작성해 주시면 정말 좋을 것 같아요.

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/controller/LottoController.java
> +    }
이것이 컨트롤러의 역할이어야만 할까요? `Lotto`에 생성자를 하나 더 만드는 건 어떨까요?

2022-10-16 13:54 UTC, choihz commented on src/main/java/lotto/controller/LottoController.java
> +        WinningLotto winningLotto = new WinningLotto(parseLotto(Input.winningNumberOfLastWeek()), LottoNumber.lottoNumber(Input.bonusNumberOfLastWeek()));
전체적으로 `.`으로 너무 많이 연결되어 있고, 코드를 읽기가 어려운 것 같아요. 또한 이는 컨트롤러가 하는 일이 많다는 것을 의미하겠지요? 도메인 객체들에게 더 맡길 수 있는 일은 없는지 점검해 보고 그렇지 못하더라도 메서드를 분리해서 가독성을 향상시킬 수 없을지 고민해 보시면 좋을 것 같아요.

2022-10-16 16:59 UTC, jbpark-in-seoul commented
희주님, 피드백 내용 반영했습니다. 😄
재검토 부탁드립니다.
감사합니다. ☺️

2022-10-17 14:01 UTC, choihz approved these changes
안녕하세요, 재범님!

수정해 주신 내용을 확인하고 몇 가지 코멘트를 더 남겨 두었습니다. 다만 이번 미션은 이제 마무리해도 충분할 것 같아서 머지하려고 해요. 혹시나 궁금한 점이 더 있으시다면 부담 없이 DM 주세요.

그동안 고생 많으셨습니다~

2022-10-17 14:01 UTC, choihz commented on src/test/java/lotto/domain/WinningLottoTest.java
>      }
```suggestion
    void constructorDIExceptionForWinningLottoNull() {
        assertThatThrownBy(() -> new WinningLotto(null, LottoNumber.lottoNumber(7)))
                .isInstanceOf(IllegalArgumentException.class);
    }
```

1. 적절한 줄바꿈으로 가독성 향상
2. 테스트 메서드 이름에서 사용된 DI라는 부적절한 표현
3. `@DisplayName` 설명의 모호함

포인트가 여럿 있군요 😉

2022-10-17 14:02 UTC, merged