2단계 - 로또(자동)
next-step/java-lotto pull request #2641
Opened 2022-10-16 14:46 UTC by nhs219

안녕하세요. 
리뷰요청 드립니다.
감사합니다!

2022-10-17 02:11 UTC, gch01410 requested changes
안녕하세요!
깔끔하게 구현해주셔서 코드 읽기가 편했네요! 👍 
코멘트 남겼으니 확인부탁드릴게요~

2022-10-17 02:11 UTC, gch01410 commented on src/main/java/autoLotto/Calculator.java
> +    }
matchNumQuantity가 3,4,5,6이 아니라면 NullPointerException이 발생할것 같아요!
방어로직이 필요해보입니다.

2022-10-17 02:11 UTC, gch01410 commented on src/main/java/autoLotto/Calculator.java
> +        Long result = 0L;
primitive 타입으로 선언하지 않고 reference타입으로 선언한 이유가 있을까요~?

2022-10-17 02:11 UTC, gch01410 commented on src/main/java/autoLotto/OutputView.java
> +        System.out.println("6개 일치 (2000000000원)-"+ SIX.getCountOfMatch() + "개");
View영역에서 domain영역에 직접 접근해서 각 등급의 당첨 횟수를 가져오고 있네요!
View영역이 domain영역에 직접 접근하지않고, 컨트롤러가 필요한 데이터를 View영역에 전달해야하지 않을까요~?

2022-10-17 02:11 UTC, gch01410 commented on src/main/java/autoLotto/Lotto.java
> +    }
Lotto 의 getMatchQuantity 메서드에 대해서도 테스트 코드가 있으면 좋을 것 같습니다~

2022-10-17 02:11 UTC, gch01410 commented on src/test/java/autoLotto/NumberTest.java
> +public class NumberTest {
1~45숫자가 입력됐을때 예외가 발생하지않고 정상적으로 값이 저장됐는지도 확인해보면 좋을 것 같아요!

2022-10-18 00:02 UTC, nhs219 commented on src/main/java/autoLotto/OutputView.java
> +    }
getter를 사용하지 않으려고 하다보니 일반 for문을 사용하게 되었고 그것보다는 위와 같이 개발하는 게 더 좋을 것 같았습니다. 향상된 for문을 이용하기 위해서는 Lottos의 getter 메소드를 사용해서 lottos값을 빼야해서 위와 같이 개발을 하였는데, 이런 경우 getter를 사용하는 게 더 좋을까요? 아니면 getter를 사용하지 않고 향상된 for문을 만들 수 있을까요? 리뷰 꼼꼼하게 잘 해주셔서 다시 한번 제 코드를 점검할 수 있게 해주셔서 감사합니다!!

2022-10-18 05:12 UTC, nhs219 commented on src/main/java/autoLotto/OutputView.java
> +        System.out.println("6개 일치 (2000000000원)-"+ SIX.getCountOfMatch() + "개");
View 영역에서 직접 접근하지 않는 다면 변수로 넘겨줘야 하는데, 변수로 4개의 값이 넘기게 된다면 변수의 개수가 많아지는 거 같은데 다른 좋은 방법이 있을까요?? ㅜㅜ

2022-10-18 12:28 UTC, gch01410 commented on src/main/java/autoLotto/Lotto.java
> +    private static final int NUMBER_SIZE = 6;
조금 더 구체적으로 네이밍하면 좋을 것 같아요~
LOTTO_NUMBER_MIN, LOTTO_NUMBER_MAX, LOTTO_NUMBER_SIZE 등..

2022-10-18 12:30 UTC, gch01410 commented on src/main/java/autoLotto/WinningNumbers.java
> +        winningNumbers.forEach(n -> checkMaxNum(n));
살짝 과하게 forEach를 사용하고 있는 느낌이 있네요!
이 [사이트](https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/)를 참고해봐도 좋을 것 같습니다!

2022-10-18 12:32 UTC, gch01410 commented on src/main/java/autoLotto/WinningNumbers.java
> +    private static final int MAXIMUM_NUMBER = 45;
무엇의 최대숫자가 45인지를 알기 어려울것 같아요.
길어져도 괜찮습니다. 구체적으로 설명할수록 좋아요!
`LOTTO_MAXIMUM_NUMBER`

2022-10-18 12:35 UTC, gch01410 commented on src/main/java/autoLotto/OutputView.java
> +    public static void outputResult(double result, int threeMatch, int fourMatch, int fiveMatch, int sixMatch) {
결과 값들을 담고 있는 객체를 넘기면 파라미터로 어떨까요?
```suggestion
    public static void outputResult(GameResult gameResult) {
```

2022-10-18 12:39 UTC, gch01410 commented on src/main/java/autoLotto/Calculator.java
> +    private static void getTotalCount(int matchNumQuantity) {
보통 메서드명이 get- 형식일때는 반환값이 있는것으로 기대합니다.
메서드 시그니쳐에 맞도록 메서드명을 변경하면 좋을 것 같아요~

구글링해서 찾아봐도 좋고 이 [사이트](https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/)를 참고해봐도 좋습니다.

2022-10-18 12:41 UTC, gch01410 commented on src/test/java/autoLotto/LottosTest.java
> +    void matchQuantity() {
몇몇 테스트 코드는 설명이 누락되어있네요.
어떤것을 검증하는 메서드인지 테스트 코드에 설명해주면 코드파악하기가 한결 수월해집니다!
@DisplayName 을 사용해도 좋고, 메서드명에 한글을 입력해도 좋습니다.

2022-10-18 12:47 UTC, gch01410 commented on src/main/java/autoLotto/OutputView.java
> +    }
지금 구조에서는 향상된 for문을 만드려면 getter를 만들 수 밖에 없어보이네요!
getter를 사용하지않고 구현할 수 있는 로직을 getter를 이용해서 구현하려는 경향이 있어서 반드시 필요한 경우를 제외하곤 getter사용을 지양하라는 의미라고 생각해요. 
이 [사이트](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/)를 참고해보면 좋을 것 같아요!
여기에서도 나와있듯이 getter자체가 나쁜게 아니라 무분별하게 사용하는게 안좋다고 생각해요.
보통 View영역에서 출력하기 위한 경우가 반드시 필요한 경우에 해당해서 getter를 만들 수 밖에 없긴합니다.

2022-10-18 12:48 UTC, gch01410 requested changes
안녕하세요!
피드백 잘 반영해주셨네요! 💯 
질문에 대한 답과 추가 피드백 남겼으니 확인 부탁드릴게요!

2022-10-19 10:54 UTC, gch01410 approved these changes
안녕하세요!
피드백 잘 반영해주셨네요! 💯 
간단한 피드백 하나 남겼으니 확인 부탁드릴게요.
이번 단계는 머지하겠습니다. 수고하셨습니다.

2022-10-19 10:54 UTC, gch01410 commented on src/main/java/autoLotto/Calculator.java
> +        if (matchNumQuantity >= 3) {
상수로 선언하면 좋을 것 같아요!

2022-10-19 10:54 UTC, merged