feat : 로또(자동) 기능구현
next-step/java-lotto pull request #2651
Opened 2022-10-17 09:25 UTC by nautilus-alpha

2단계 PR 드립니다. 리뷰 부탁드립니다 : )

2022-10-18 08:05 UTC, JunHoPark93 requested changes
안녕하세요~ 로또 2단계 고생하셨습니다.
피드백 몇가지 남겼는데 확인 후 의견 및 반영부탁드려요 😊

2022-10-18 08:05 UTC, JunHoPark93 commented on src/main/java/com/nextstep/lotto/lottoGame/domain/LottoGame.java
> +    private static final int LOTTO_TICKET_PRICE = 1000;
로또 티켓 가격은 로또 티켓이 가지고 있어야 하지 않을까요?

2022-10-18 09:01 UTC, nautilus-alpha commented
@JunHoPark93 꼼꼼히 리뷰해 주셔서 감사합니다! 리뷰해 주신 내용 반영하여 다시 리뷰 요청 드립니다 👍 👍 : )

2022-10-19 12:46 UTC, JunHoPark93 approved these changes
안녕하세요~ 로또 2단계 피드백 잘 반영해주셨어요!
간단한 추가코멘트 남겨두었는데 다음 step에서 반영부탁드려요!
다음 step에서 뵐게요 😊

2022-10-19 12:46 UTC, merged