[로또] 3단계 - 로또(2등)
next-step/java-lotto pull request #2655
Opened 2022-10-17 14:19 UTC by suchanmyoung

안녕하세요 석홍 님.

2단계 머지 때 피드백 해주신 내용까지 보강하여 3단계 미션을 수행해보았는데요. 몇 가지 어려웠던 점에 대해 조언을 받고 싶습니다!

1.  LottoNumbers에서 Integer가 아닌 하나하나의 int를 감싼 LottoNumber 도메인을 만드는 것이 어떨까 조언을 주셨었는데, 막상 실제로 구현하려고 하니 어려움이 많았습니다. LottoNumber로 하나하나가 감싸져 있어서 내부 int 를 일일이 꺼내서 확인하는 점이나, LottoNumbers.from 메서드로 LottoNumber를 생성할 때, List<Integer> 를 파라미터로 받는 것을 통해 테스트가 용이했었는데, LottoNumber 하나하나를 받을 경우는 다소 어려워졌습니다. LottoNumberGenerator, LottoNumber, LottoNumbers 세 가지 클래스를 잘 조합하면 될 것 같은데, 조금 상세하게 조언을 들을 수 있을까요?

2. Prize enum에서 valueOf 메소드를 구현하는데, if 분기가 너무 많이 생기는 게 불편했는데요, Prize.SECOND와 Prize.THIRD를 매끄럽게 구분할 수 있는 방법이 있을까요?

3. 도메인 객체를 활용하고, View 와 의존을 최대한 끊으려고 하다보니 OutputView 에서 출력 방식을 가공하면서 OutputView 가 조금씩 복잡해지는 것을 느꼈습니다. UI를 위한 클래스들이 다소 복잡해짐을 감소하더라도 의존성을 끊는 것이 더 좋은 선택이라고 개념적으로 미약하게 알고 있으나(결국 비즈니스 로직이 중요하고, 테스트의 용이함을 위해?), 이해를 위해 조금 더 설명을 듣고 싶습니다. 왜 UI 클래스들이 복잡해지더라도 도메인과의 의존성을 끊는 것이 중요한가요?

2022-10-20 13:55 UTC, seokhongkim requested changes
수찬님, 로또 3단계 미션 잘 구현해주셨습니다. 👍 

질문주신 부분에 대해 제 생각과 힌트를 말씀드려요. :)
보시고도 고민되시면 슬랙 DM으로 말씀 부탁드립니다!

1. `LottoNumber` 를 능동적인 객체로 구현해보시면 수월할 것 같습니다.
`LottoNumber.getValue()` 를 해서 내부의 값을 꺼내서 사용하는 것이 아니고, `LottoNumber.equals(lottoNumber)` 와 같이 값이 일치하는지 `LottoNumber` 에게 물어보는 형태로 구현해보시면 좋겠습니다. 예를 들어, `Integer` 를 사용하실 때 값을 확인하기 위해 `intValue()` 로 꺼내지 않고, `compareTo()` 를 바로 사용하는 것처럼 `LottoNumber` 도 필요한 기능을 구현하고 사용해보시면 도움이 될 것 같아요.
2. `Prize` 코드에 코멘트를 남겼으니 참고 부탁드립니다.
3. 우선 책임의 분리 측면에서, 도메인은 비즈니스 로직을 관리하고 UI는 화면에 보여주는 역할을 관리하고 집중할 수 있습니다. 이는 비즈니스의 요구사항 변경과 UI의 요구사항 변경에 대해 서로 다른 코드를 수정하면 되는 구조를 제공해주고, 확장과 변경에 더 유연하게 대처할 수 있습니다.
의존을 분리하는 것 중에서도 특히 도메인이 UI에 의존하지 않는 것이 더 중요하다고 생각합니다. UI의 요구사항은 상대적으로 더 잘 변하는 경향이 있으며, 특정 UI에 의존적인 도메인 코드는 재사용을 어렵게 만듭니다. 현재 콘솔 기반으로 작성된 코드를 웹으로 제공한다고 했을 때, 도메인을 그대로 사용할 수 있는지와 같은 고민을 해보셔도 좋을 것 같습니다. :)

이외에 코드에 코멘트를 조금 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-10-20 13:55 UTC, seokhongkim commented on src/main/java/step3/domain/LottoNumbers.java
> +    public boolean isBonusBallMatch(int bonusBall) {
메소드의 인자로 전달되는 값이 `bonusBall` 인지 알 수 있을까요?
메소드가 하는 일은 `인자로 전달된 번호를 가지고 있는지 여부 확인` 인 것 같아요.
역할을 더 잘 설명할 수 있는 이름을 사용해보면 어떨까요?

2022-10-20 13:55 UTC, seokhongkim commented on src/main/java/step3/domain/LottoResult.java
> +        for (LottoNumbers eachLottoNumber : allLottoNumbers) {
`matchCount` 를 계산하는 책임을 `LottoNumbers` 에 위임하여 `LottoResult` 의 구현이 한결 이해하기 쉬워졌네요! 👍

2022-10-20 13:55 UTC, seokhongkim commented on src/main/java/step3/domain/LottoResult.java
> +        drawResult.remove(Prize.MISS);
결과 출력을 위해 `MISS` 를 제거하신 걸까요?
도메인에서는 총 수량을 알기 위해 데이터를 모두 가지고 있고, 출력하는 곳에서만 상금에 당첨된 정보를 출력해보면 어떨까요? :)

2022-10-20 13:55 UTC, seokhongkim commented on src/main/java/step3/domain/Prize.java
> +    public static int calculateTotalIncome(final Map<Prize, Integer> drawLottoResult){
`LottoResult` 가 `Prize` 를 알고 있는데, 상금 계산을 위해 `Prize` 가 다시 `LottoResult` (타입은 다르지만 동일한 데이터)를 알게 되는 순환참조 구조로 보여요.
`LottoResult` 가 `Prize` 를 알고 있고, 몇 장이 당첨되었는지 알고 있으니 상금도 계산해볼 수 있지 않을까요? :)
각 등수에 대한 상금 계산만 `Prize` 에게 계산을 위임하는 방법도 있겠네요!

2022-10-20 13:55 UTC, seokhongkim commented on src/main/java/step3/domain/Prize.java
> +        if (matchBonus && countOfMatch == 5) {
1등부터 5등까지 당첨 조건을 써보면 아래와 같은 것 같아요.

1등: countOfMatch == 6
2등: countOfMatch == 5 && matchBonus == true
3등: countOfmatch == 5 && matchBonus == false
4등: countOfMatch == 4
5등: countOfMatch == 3
미당첨: 그 외

각 enum 이 `boolean isWin(int countOfMatch, boolean matchBonus)` 를 구현하면, `valueOf` 의 로직은 단순히 모든 값을 순회하면서 `isWin` 에 포함되는지만 확인해보고, 해당되지 않으면 미당첨을 반환해주면 되곘네요!

hint: `private final BiFunction<Integer, Boolean, Boolean>` 필드를 가지고 있거나, `abstract boolean isWin` 을 추가해볼까요?

2022-10-20 13:55 UTC, seokhongkim commented on src/test/java/step3/domain/LottoNumberTest.java
> +public class LottoNumberTest {
`LottoNumbersTest` 를 작성하신거겠죠? :)

2022-10-20 13:55 UTC, seokhongkim commented on src/test/java/step3/domain/LottoNumberTest.java
> +    @DisplayName("MatchCount 계산 시 당첨 번호와 로또 번호 일치 개수를 반환")
꼼꼼한 단위 테스트 좋습니다. 👍

2022-10-20 13:55 UTC, seokhongkim commented on src/main/java/step3/domain/LottoNumbers.java
> +        lottoNumbers.addAll(generatedNumbers);
`LottoNumbers` 라면 만족해야 하는 조건이 있지 않을까요?

hint: 로또는 항상 일정한 개수의 숫자를 골라야해요!

2022-10-20 13:55 UTC, seokhongkim commented on src/test/java/step3/domain/PrizeTest.java
> +    @DisplayName("3이 인자로 들어오면 5000원을 보상한다")
`3` 이 인자로 들어온다는 것은 로또에서 무슨 의미일까요?
테스트 내용도 도메인의 언어를 활용해서 작성해주시면 이해하기 더 좋은 것 같아요!

2022-10-23 14:33 UTC, suchanmyoung commented
안녕하세요 준영 님! 피드백 주신 내용 반영하여 리팩토링 해보았습니다.

![스크린샷 2022-10-23 오후 11 26 52](https://user-images.githubusercontent.com/87016418/197397632-b5ae8b1e-8a4d-478f-87b1-7c8c004d3f98.png)
내용 중 이부분은 이해가 조금 어려워서 해결하지 못했는데, 힌트를 조금 더 주시면 다시 개선해보겠습니다!

또, Prize.valueOf 메서드를 추상메서드를 통해서 리팩토링 한 부분이 이번 PR에서 가장 고민했던 부분인데 기존보다 개선은 되었으나, 추상 메서드를 각각 구현하는 부분이 코드에서 다소 지저분한 것 같아서 말씀주신 대로 BiFunction 으로 개선해보려고 했는데 자바 8에 대한 이해도가 낮아서인지 실패했는데요! 더 상세하게 이부분을 코멘트 주실 수 있을까요?

2022-10-24 03:25 UTC, suchanmyoung commented
안녕하세요 석홍 님!

BiFunction으로 리팩토링 할 방법을 좀 더 찾아보다가 적용해보았습니다!

2022-10-24 03:29 UTC, seokhongkim approved these changes
수찬님 안녕하세요. 3단계 미션 피드백 잘 반영해주셨습니다! 💯 
3단계 PR도 이만 머지하도록 하겠습니다.

질문 남겨주신 부분은 코드에 코멘트 남겼습니다. 다음 단계 미션 진행하실 때 참고 부탁드립니다.
4단계 미션에서 뵙겠습니다. 😀

2022-10-24 03:29 UTC, seokhongkim commented on src/main/java/step3/domain/Prize.java
> +        return Arrays.stream(Prize.values())
저는 이전 코드보다 충분히 이해하기 좋아진 것으로 보이네요!
`BiFunction` 을 사용하는 법을 문의주셔서 코멘트 남깁니다. 이건 반영하지 않으셔도 괜찮습니다. :)

```java
public enum Prize {
  FIRST(2_000_000_000, (countOfMatch, isMatchBonus) -> countOfMatch == 6)
  ;

  private final int reward;
  private final BiFunction<Integer, Boolean, Boolean> winningChecker;

  // 중략

  public static Prize getPrize(int countOfMatch, boolean isMatchBonus) {
    // 밸리데이션

    return Arrays.stream(Prize.values())
      .filter(prize -> prize.getWinningChecker().apply(countOfMatch, isMatchBonus))
      .findFirst()
      .orElse(Prize.MISS);
  }
}
```

2022-10-24 03:29 UTC, seokhongkim commented on src/main/java/step3/domain/Prize.java
> +    private final int countOfMatch;
맞는지 검증을 각 객체가 직접 수행하므로 `countOfMatch` 는 이제 관리하지 않아도 될 것 같아요!

2022-10-24 03:29 UTC, seokhongkim commented on src/main/java/step3/domain/Prize.java
> +    public static int calculateTotalIncome(final Map<Prize, Integer> drawLottoResult){
`Prize` 에서 `LottoResult` 혹은 비슷한 데이터에 의존하지 않는 방법으로, 저는 아래 두 가지 방법이 생각납니다.
1. `Prize` 에서는 `reward` 만 제공해주고, `LottoResult` 에서 각 등수별로 금액을 가져와서 총 당첨금을 계산한다.
2. `Prize` 의 각 등수에서 `당첨 수량` 을 전달 받아서, `상금` 을 계산해주고, `LottoResult` 에서는 전체 등수에 대해 `Prize` 에게 계산을 요청한다.

1번은 직접 구현하실 수 있을 것으로 생각되고, 2번은 글로 쓰여 있으니 설명이 어려워서 예시 코드를 전달드려요!
```java
public enum Prize {
  FIRST((countOfMatch, isMatchBonus) -> countOfMatch == 6) {
    @Override
      public long calculateReward(int countOfWin) {
        return 2_000_000_000L * countOfWin;
      }
  }
  ;

  private final BiFunction<Integer, Boolean, Boolean> winningChecker;

  public abstract long calculateReward(int countOfWin); 
```

2022-10-24 03:29 UTC, merged

2022-10-24 03:30 UTC, seokhongkim commented
> 안녕하세요 석홍 님!
> 
> BiFunction으로 리팩토링 할 방법을 좀 더 찾아보다가 적용해보았습니다!

수찬님 안녕하세요!
제가 리뷰 작성하고 올린 후에 `BiFunction` 적용하신 것을 봤습니다.
잘 적용해주셔서 제가 남긴 코멘트는 넘어가셔도 될 것 같습니다. :)