3단계 - 로또(2등)
next-step/java-lotto pull request #2672
Opened 2022-10-19 16:09 UTC by jimbaemon

일단 문제 해결에만 집중해 봤는데 기능 변경에 따른 추가 수정사항이 너무 많아서 설계를 다시 고려해 봐야 할것 같습니다 ㅜㅜ

2022-10-20 04:00 UTC, csh0034 requested changes
3단계 구현 잘해주셨네요 👍

몇가지 고민해볼만한 사항 남겨드렸는데 
확인후에 리뷰 요청 해주세요~

2022-10-20 04:36 UTC, jimbaemon commented on src/main/java/lotto/LottoResult.java
> +        winners.add(bonus);
제가 로또를 안해봐서... 잘 모르겠는데 보너스 번호를 포함해서 우승자를 구하는거 아닌가요??
예시로
로또 번호 : 2, 3, 4, 5, 6, 7 일경우
추첨 번호 : 1, 2, 3, 4, 5, 6 이면 원래는 2등이지만 추첨번호가 7인경우는 1등으로 될것 같아서 우승자 번호에 보너스 번호를 추가해줬습니다 :)

2022-10-20 04:37 UTC, jimbaemon commented on src/main/java/lotto/LottoResult.java
> +        return lottos.stream().map(lotto -> lotto.checkRank(winners, bonus)).collect(Collectors.toUnmodifiableList());
네 알겠습니다 :) 
default컨벤션으로 정렬해 주니까 자동으로 한줄로 변경해서 그대로 두었습니다.
기존에 리뷰 해주신분은 컨벤션을 유지해줄것을 요구하셔서 그대로 했는데 다양한 의견 듣는것도 재밌네요 :)

2022-10-20 04:37 UTC, jimbaemon commented on src/main/java/lotto/LottoResult.java
> +    public LottoResult(List<Lotto> lottos, Set<Number> winners, Number bonus) {
:) 좋은 의견인것 같습니다. 그렇게 뒤집어서 설계 변경 해보겠습니다

2022-10-20 04:38 UTC, jimbaemon commented on src/main/java/lotto/LottoController.java
> +        Set<Number> winnerNumbers = Input.inputWinnerNumbers();
아래 나온 피드백대로 Class 로 변환해서 검증로직 추가해 볼게요 :)

2022-10-20 05:18 UTC, jimbaemon commented on src/main/java/lotto/LottoController.java
>  public class LottoController {
알겠습니다! :)

2022-10-20 06:51 UTC, csh0034 commented on src/main/java/lotto/LottoResult.java
> +        winners.add(bonus);
로또의 기본 룰이 이번 미션의 요구사항이기 때문에 다시 한번 확인해보시면 좋을것 같아요.

- 1등: 추첨번호 6개 일치
- 2등: 추첨번호 5개 일치 + 보너스 번호 일치
- 3등: 추첨번호 5개 일치 + 보너스 번호 불일치
- 4등: 추첨번호 4개 일치 + 보너스 번호 관련없음
- 5등: 추첨번호 3개 일치 + 보너스 번호 관련없음

말씀해주신 경우엔 보너스번호를 추첨번호에 보너스 번호를 넣어 1등이 되면 안되고 2등이어야 합니다.

2022-10-22 03:17 UTC, jimbaemon commented on src/main/java/lotto/Rank.java
> +    public static Rank valueOf(final int matchedCount, final boolean withBonus) {
음 활용해 보려 했는데 어렵네요.... ㅜㅜ

2022-10-23 04:11 UTC, csh0034 approved these changes
리뷰 반영 잘해주셨네요 💯 
다음 단계 진행해주세요!

2022-10-23 04:11 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +        if (!(numbers instanceof TreeSet)) {
타입체크를 하는 방법도 좋지만 방어적 복사를 해보면 어떨까요?
외부에서 전달된 numbers 에 대한 추가, 삭제를 방지할수 있는 장점도 있습니다.

```java
public Lotto(Set<Number> numbers) {
    validate(numbers);
    this.numbers = new TreeSet<>(numbers);
}
```

2022-10-23 04:11 UTC, csh0034 commented on src/main/java/lotto/domain/LottoNumberStrategy.java
> +package lotto.domain;
전략은 도메인 패키지가 맞을까요? 🤔

2022-10-23 04:11 UTC, csh0034 commented on src/main/java/lotto/domain/Lottos.java
> +        List<Rank> ranks = lottos.stream()
stream 사용 👍
아래와 같이 표현해볼수도 있겠네요

```java
return lottos.stream()
    .map(lotto -> lotto.checkRank(winnerNumbers))
    .collect(Collectors.collectingAndThen(Collectors.toUnmodifiableList(), LottoResult::new));
```

2022-10-23 04:11 UTC, merged

2022-10-23 05:16 UTC, jimbaemon commented on src/main/java/lotto/domain/Lotto.java
> +        if (!(numbers instanceof TreeSet)) {
좋은 아이디어네요 :) 인사이트 주셔서 감사합니다.

2022-10-23 05:17 UTC, jimbaemon commented on src/main/java/lotto/domain/Lottos.java
> +        List<Rank> ranks = lottos.stream()
감사합니다 :) 좋은도구 활용 방안을 좀더 공부해야겠네요 :)

2022-10-23 08:10 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +        if (!(numbers instanceof TreeSet)) {
제가 리뷰를 잘못 드린 부분이있네요..

numbers 에 대한 추가, 삭제를 방지하는것은 Unmodifiable Collection 적용시에 내용이고
방어적 복사의 경우엔 전달된 numbers 에 대해서 새로운 컬렉션을 생성하기 때문에
기존 컬렉션에 추가, 삭제를 해도 내부에 컬렉션엔 영향을 끼치지 않는다는 내용입니다.

2022-10-24 10:36 UTC, jimbaemon commented on src/main/java/lotto/domain/LottoNumberStrategy.java
> +package lotto.domain;
어느쪽이 맞을까요?? ㅜㅜ 잘 모르겠습니다.

2022-10-24 11:32 UTC, csh0034 commented on src/main/java/lotto/domain/LottoNumberStrategy.java
> +package lotto.domain;
도메인(모델, 객체)이란 요구사항 구현 및 문제 해결을 위해 상태(필드)와 행위(메소드) 를 가지면서 메세지를 주고받으며
협력을 하는 대상입니다.

전략의 경우 상태가 존재하지 않으므로 별도로 strategy 등과 같은 패키지에 두는것이 명확해 보입니다 😄