4단계 - 로또(수동)
next-step/java-lotto pull request #2682
Opened 2022-10-20 12:12 UTC by kingkk31

안녕하세요, 수동 로또 기계가 추가되었습니다. 리뷰 요청드립니다!

2022-10-22 01:26 UTC, ksy90101 requested changes
안녕하세요.
4단계도 너무 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니 확인해주시면 감사하겠습니다.

2022-10-22 01:26 UTC, ksy90101 commented on src/main/java/lotto/Lotto.java
>      public static void main(String[] args) {
<img width="622" alt="image" src="https://user-images.githubusercontent.com/53366407/197310213-086f1801-c4cb-4d59-8e67-881ff2861bf0.png">

수익률 계산이 조금 이상해 보이네요.
만원을 구매해서 1등을 2개 했는데 손해가 나오는게 이상한거 같아요 ㅎㅎ 
확인부탁드려요 ㅎㅎ

2022-10-22 01:26 UTC, ksy90101 commented on src/main/java/lotto/Lotto.java
> +        printResult(purchasePrice, ticketBox);
main에 모두 진행되는게 아니라 Controller나 Game과 같은 객체가 실제 게임을 실행하게 하면 어떨까요?

2022-10-22 01:26 UTC, ksy90101 commented on src/main/java/lotto/domain/ManualLottoMachine.java
> +    private final MarkingPaper markingPaper = new MarkingPaper();
차후에 갈아끼우기 쉽게 생성자 주입이 더 좋을듯 한데 어떻게 생각하시나요?

2022-10-22 01:26 UTC, ksy90101 commented on src/main/java/lotto/domain/TicketBox.java
>  public class TicketBox {
LottoBall은 45개로 결정되어 있죠.
이런 경우 계속 생성하는게 성능상 좋지 않을수 있어요.
(계속 인스턴스가 생성되니깐요.)
한번 캐싱을 적용해보면 어떨까요? Map이나 List와 같은 컬렉션으로 미리 넣어둘수 잇을듯 하네요.
그러나 Map이 조회시 O(1)이기 때문에 더 좋을수 있을거 같아요!

2022-10-24 01:58 UTC, kingkk31 commented on src/main/java/lotto/Lotto.java
>      public static void main(String[] args) {
@ksy90101 수익률 계산 로직에는 이상이 없었습니다. 다만 수익값을 구하기 위해 당첨금을 곱하는 과정에서 int 범위를 넘어갔습니다...WinningCondition 의 prizeMoney 를 long 으로 변경하니 해소되었습니다.

![image](https://user-images.githubusercontent.com/10459593/197432863-e6f93938-e4d5-4691-a035-b223c6e7b137.png)

2022-10-24 02:08 UTC, kingkk31 commented on src/main/java/lotto/domain/ManualLottoMachine.java
> +    private final MarkingPaper markingPaper = new MarkingPaper();
@ksy90101 사실 이 부분에서 고민을 했었어요. 로또기계가 눈 앞에 있을때,
1. 기계에 번호를 입력하고 발급(기존 내부에서 마킹지 생성 및 마킹 메소드 사용) 이 맞는지.
2. (생성자 주입으로 하여) 미리 마킹한 마킹지를 넣고 티켓을 발급받는게 맞는지.

제가 로또를 산 경험이 없어서;; 예전에 다른사람이 종이에 마킹하고 그걸 점원에게 내는걸 본 기억이 있는데 그게 맞다면 말씀하신 생성자 주입 방식이 더 현실감 있어 보입니다:)

2022-10-24 02:09 UTC, kingkk31 commented
@ksy90101 안녕하세요, 피드백 주신 사항 반영하였습니다. 다시 리뷰 부탁드립니다!

2022-10-24 13:04 UTC, ksy90101 commented on src/main/java/lotto/Lotto.java
>      public static void main(String[] args) {
👍 로또 미션에서 많이 실수하는 부분인듯 해요!
저도 이전에 했을때 실수 했던...ㅎㅎ

2022-10-24 13:06 UTC, ksy90101 commented on src/main/java/lotto/domain/ManualLottoMachine.java
> +    private final MarkingPaper markingPaper = new MarkingPaper();
2번이 맞긴 합니다.
그러나 1번이던 2번이던 이러한 부분이 고려가 되는 이유가 무엇일까요?

2022-10-24 13:15 UTC, ksy90101 approved these changes
안녕하세요 :)
로또 마지막 단계까지 너무 고생하셨습니다 💯 
이만 마무리 하겠습니다.
추가 질문이 있다면 언제든 dM보내주세요~

2022-10-24 13:15 UTC, ksy90101 commented on src/main/java/lotto/domain/number/LottoBall.java
> +    private static final Map<Integer, LottoBall> BUCKET;
👍

2022-10-24 13:15 UTC, ksy90101 commented on src/main/java/lotto/domain/number/LottoBall.java
> +        BUCKET = new HashMap<>();
static final에 구현해두고, Steam으로 한번 작성해볼수 있을듯 해요.
이건 그냥 참고만 해주세요.

2022-10-24 13:16 UTC, merged