로또 Step4 보강
next-step/java-lotto pull request #2686
Opened 2022-10-21 04:39 UTC by gumsu

안녕하세요 시영님!

이미 4단계까지 pr 머지 해주셨지만, #2668 에서 해주셨던 피드백에 대해서
제가 잘 이해하고 구현한건지 확인 받고 싶어서 다시 요청드렸습니다. 🙂

꽤 긴 기간이라고 하셔서 확인해보니 16일을 했더군요 😅
아직 레이싱카, 로또 두 가지 미션밖에 완료하지 못했지만, 돌이켜보면 정말 많이 발전한 저를 느낄 수 있어서,
그리고 그렇게 할 수 있도록 긴 시간동안 꼼꼼하게 코드 리뷰 해주시고 도와주신 시영님께 정말 감사드립니다. 😇

#2668 에서 피드백 해주셨던 아래 사항에 대해서만 코드 확인 부탁드립니다.!
```
만약에 캐싱을 Map<Integer(번호), LottoNumber> 로 했다면 문제없이 가능할까요?
```
```
요 부분도 객체로 분리될 수 있을 것 같아요🙂 LottoTickets에 있어도 자연스럽지만 객체를 조금 더 나눠보는 연습을 하면 좋을 것 같습니다.
입력값을 바탕으로 몇장/몇장을 구매해야하는지 찾아주는 객체가 될 것 같아요.
```

2022-10-23 07:33 UTC, KIMSIYOUNG requested changes
안녕하세요!
구현 잘 해주셨는데 궁금한 부분 몇가지 코멘트 남겼습니다.
확인 부탁드려요!

2022-10-23 07:33 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoNumber.java
> +        return LOTTO_NUMBERS.get(number);
네네 잘 구현해주신 것 같아요🙂

2022-10-23 07:33 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoRandomGenerator.java
>          Collections.shuffle(shuffleNumbers);
요 부분은 리스트만 셔플이 가능해서 매번 생성해야하긴 하네요😭

저라면 1~45사이의 난수 생성기를 통해서 값 6개를 뽑고 LOTTO_NUMBERS.get()을 통해서 반환하는 형태로 구현할 것 같아요!

2022-10-23 07:33 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoRandomGenerator.java
> +            .map(LottoNumber::from)
요렇게 구현한다면 value로 접근하면 될 것 같네요ㅎㅎ

2022-10-23 07:33 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/OrderInformation.java
> +        valid(money);
금액에 대한 검증은 Money에서 구현하는게 좋을 것 같아요. LottoTickets에도 동일한 로직이 있네요!

2022-10-23 07:33 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/OrderInformation.java
> +public class OrderInformation {
이름이 너무 범용적인 것 같아요. LottoCount (?) 이름은 참 어렵군요.. 각각 몇 장을 구매할 수 있다 라는 것을 드러내는 이름..이 좋을 것 같아ㅣ요.

2022-10-23 07:33 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/OrderInformation.java
> +    private List<Lotto> manualLottos;
우리가 처음 설계할 땐 수동로또와 자동로또가 각각 몇장인지만 확인하는 역할로 설계하기로 했던 것 같아요! List<Lotto>를 직접 가지는 이유가 있을까요?

2022-10-24 03:15 UTC, gumsu commented on src/main/java/lotto/domain/OrderInformation.java
> +    private List<Lotto> manualLottos;
현재 view에서 수동로또 몇 장을 구매할 것인지 받은 후에, 로또 6자리도 받아서 바로 List<Lotto> 로 반환하는 형식이라서 List를 가져갔습니다.

2022-10-24 03:35 UTC, gumsu commented on src/main/java/lotto/domain/LottoRandomGenerator.java
>          Collections.shuffle(shuffleNumbers);
난수생성기라면 Random 을 말씀하시는 건가요?!  
```
        List<LottoNumber> lottoNumbers = new ArrayList<>();
        Random random = new Random();
        while (lottoNumbers.size() < Lotto.LOTTO_NUMBER_SIZE) {
            lottoNumbers.add(LottoNumber.from(random.nextInt(LottoNumber.MAX_NUMBER) + LottoNumber.MIN_NUMBER));
        }
```
이런식으로 변경해보려하니 또 중복 숫자 때문에 문제가 생기네요,,

그리고 저는 Collections.shuffle() 을 사용해서 구현하고 싶은데 매번 new arraylist() 를 하지 않고 구현하려고 한다면 어떻게 해야할 지 모르겠습니다. 😥

2022-10-24 03:39 UTC, gumsu commented
시영님 로또 미션이 끝났음에도 추가적으로 피드백 해주시고 봐주신 점 정말 감사드립니다!! 😇
이제 머지 해주셔도 괜찮을 것 같아요~ 감사합니다 🙏

2022-10-24 08:08 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoRandomGenerator.java
>          Collections.shuffle(shuffleNumbers);
Set으로 관리하면 해결될 것 같아요. COllections.shuffle을 사용한다면 매번 선언하지 않고는 해결되지 않는 것 같습니다ㅎㅎ

2022-10-24 08:09 UTC, KIMSIYOUNG approved these changes
안녕하세요.
리뷰가 끝났음에도 궁금하신 부분을 계속 고치시는 모습이 인상 깊은 것 같아요.
다음 미션에서도 화이팅입니다. 궁금한게 있으시다면 디엠으로 편하게 더 물어봐주셔도 됩니다!

2022-10-24 08:09 UTC, merged