🚀 3단계 - 로또(2등)
next-step/java-lotto pull request #2689
Opened 2022-10-21 13:11 UTC by gmelon

안녕하세요! step3 리뷰 요청드립니다.

step3의 기능 요구사항 반영 외에 `LotteryRank`와 `LotteryResult` 간에 연관된 로직에서 기존에 `int rank`와 `LotteryRank lotteryRank`를 인자로 받아 계산하는 메서드들이 모두 `LotteryRank lotteryRank`를 받도록 통일하여 중복 코드를 제거하고,

당첨되지 않은 상태의 value인 `NONE` 을 추가하여 `LotteryResult`가 모든 로또의 결과를 들고 있도록 하여 `로또 구매 횟수`와 같은 인스턴스 변수를 삭제하고 계산하도록 했습니다.

피드백 기다리고 있겠습니다! 감사합니다 :)

2022-10-22 08:13 UTC, pkch93 requested changes
상혁님~ 3단계도 잘 구현해주셨네요 👍 
몇가지 피드백 드렸는데 확인부탁드릴께요 ㅎㅎ

2022-10-22 08:13 UTC, pkch93 commented on src/main/java/lottery/WinningLottery.java
>  public class WinningLottery extends Lottery {
`Lottery`는 일반 로또를 표현하는 클래스로도 사용중인데요.
`Lottery`와 `WinninLottery`의 공통점을 추상화한 추상 클래스를 정의해서 사용하면 어떨까요??

아니면 상속 방식말고 `WinningLottery` 내부에서 `Lottery`를 필드로 가져서 기능을 제공하는 조합 방식도 고민해볼 수 있을거 같네요.

2022-10-22 08:13 UTC, pkch93 commented on src/test/java/lottery/LotteryRankTest.java
> +    void valueOf_일반(int matchingCount, boolean isBonusMatched, LotteryRank expectedRank) {
`@ParameterizedTest`를 사용하셨군요..! :+1:
4, 5등에 대한 테스트는 누락일까요?

2022-10-22 08:13 UTC, pkch93 commented on src/main/java/lottery/LotteryRank.java
>      }
LotteryRank 쪽 로직이 깔끔해졌네요 :+1: 

filter를 두번 쓰기보다 filter를 하나만 사용하는 쪽으로 가져가면 어떨까요?

2022-10-23 12:33 UTC, gmelon commented on src/main/java/lottery/Controller.java
> +        WinningLottery winningLottery = new WinningLottery(getWinningLotteryNumbers(), getBonusLotteryNumber());
앗.. 제가 놓친 것 같아요. 객체 생성해서 반환하도록 수정하겠습니다!

2022-10-23 12:34 UTC, gmelon commented on src/main/java/lottery/Lottery.java
>          if (lotteryNumbers.size() != LotteryCompany.LOTTERY_NUM_COUNT) {
네ㅜㅜ 저도 계속 고민하다가 결국 까먹고 그냥 올려버렸네요.
넵 고민해보고 옮긴 후 다시 푸시하겠습니다.

2022-10-23 13:38 UTC, gmelon commented on src/test/java/lottery/LotteryRankTest.java
> +    void valueOf_일반(int matchingCount, boolean isBonusMatched, LotteryRank expectedRank) {
`valueOf` 로직에서 값을 필터링할 때

1) 일치하는 `matchingCount`가 없거나 0이면 `NONE`을 반환하고,
2) 나머지는 그대로 찾아서 반환하며,
3) 2, 3등의 경우 `isBonusMatched`가 영향을 주기 때문에 

위 1), 2), 3) 경우에 대해 하나의 테스트 케이스씩 작성한다는 느낌으로 (`NONE`을 반환하는 경우에는 0과 1 두개) 테스트 코드를 작성했는데 생략된 부분에 대해서도 혹시 테스트를 하는게 좋을까요?

2022-10-23 13:57 UTC, gmelon commented on src/main/java/lottery/WinningLottery.java
>  public class WinningLottery extends Lottery {
@pkch93 넵 반영해보겠습니다!
관련 키워드를 여쭤보려고 했는데 이런 기가막힌 [자료](https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/)가 있군요..! ㅋㅋㅋ 감사합니다! :)

2022-10-24 10:07 UTC, pkch93 commented on src/test/java/lottery/LotteryRankTest.java
> +    void valueOf_일반(int matchingCount, boolean isBonusMatched, LotteryRank expectedRank) {
4, 5등도 비슷한 로직이긴 하지만 등수를 결정하는 핵심 비즈니스 로직이라고 생각해요. 비즈니스 요구사항인 4등 조건일 때 제대로 나타나는지, 5등 조건일 때 제대로 나타나는지에 대해서 테스트가 반드시 있어야한다고 생각합니다.

2022-10-24 14:17 UTC, gmelon commented on src/test/java/lottery/LotteryRankTest.java
> +    void valueOf_일반(int matchingCount, boolean isBonusMatched, LotteryRank expectedRank) {
앗 넵 핵심 비즈니스 로직이기 때문에 각 조건에 대한 테스트가 필요한 것이군요!
이해했습니다! 감사합니다 :)

2022-10-26 09:32 UTC, pkch93 approved these changes
안녕하세요 상혁님 :)
피드백 반영 확인했습니다. 감사합니다 ㅎㅎ
상혁님의 로또 3단계는 마무리해도 될거 같네요!
이제 마지막 4단계인데 조금더 화이팅하면 좋겠습니다 :) 다음단계에서 뵈어요 👋

2022-10-26 09:32 UTC, merged