🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #2699
Opened 2022-10-22 11:22 UTC by sungjun1116

리뷰 잘 부탁드립니다!

2022-10-24 15:56 UTC, ddaaac requested changes
안녕하세요 성준님 👋 

2단계 잘 구현해주셨어요 👍 

몇 가지 코멘트를 남겼으니 확인해주시고 리뷰 요청해주세요!

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
로또 번호를 값 객체로 만들어주셨네요 👍 

인스턴스 풀 개념을 도입해보자는 주석이 있는데 [`Integer`](https://meetup.toast.com/posts/185)의 사례를 참고한 걸까요? 이 부분도 구현이 되면 좋을 것 같아요!

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/domain/LottoResult.java
> +        }
```java
    ranks.stream()
                .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
```

동일한 연산을 stream으로 이렇게도 표현할 수 있어요. 항상 stream이 정답인 건 아니지만 학습 때는 이것저것 시도해보는 것도 좋을 것 같습니다!

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/domain/LottoResult.java
> +public class LottoResult {
결과 객체 잘 구현해주셨어요 💯 

추가로 잘 작동하는지 확인하는 테스트가 있으면 좋을 것 같습니다 😄

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/domain/LottoTicket.java
> +    public Rank match(final List<LottoNumber> winningLottoTicket) {
- 메서드 사이에는 개행을 넣어주세요!
- 테스트 코드도 있으면 좋을 것 같습니다 :)

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/domain/LottoTicket.java
> +        int count = (int) result;
강제로 int로 캐스팅한다면 long으로 선언하지 않고 int로 선언해도 되지 않을까요?

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/domain/LottoTicket.java
> +        HashSet<LottoNumber> nonDuplicateNumbers = new HashSet<>(lottoNumbers);
중복 확인을 잘 구현해주셨네요 👍 
로또 번호들의 순서가 중요하지 않다고 하면 아예 set으로 저장하는 방법도 있습니다.

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/domain/LottoTicket.java
> +        }
depth가 2가 되었어요. 1로 줄여볼 수 있을 것 같아요!

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/domain/Store.java
> +        for (int i = 1; i <= 45; i++) {
1, 45라는 상수 어디서 본 것 같지 않나요?
만약 로또 번호가 50까지로 요구사항이 변경된다면 어떤 부분이 변경 포인트가 될까요? 최대한 변경 포인트를 줄여보는 방향으로 코딩해보시면 좋을 것 같습니다 :)

2022-10-24 15:56 UTC, ddaaac commented on src/main/java/lotto/view/InputView.java
> +        scanner.close();
만약 요구사항이 추가돼서 이 이후에 input을 받아야한다면 어떻게 될까요?

2022-10-24 15:56 UTC, ddaaac commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    void 로또_번호_생성_범위초과() {
경계값들에 대한 테스트가 모두 이뤄지면 좋을 것 같아요. 이 경우에 0, 1, 45, 46이 되겠네요.

2022-10-24 15:56 UTC, ddaaac commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    void 로또_생성_중복번호() {
테스트 이름에서 어떤 테스트인지 조금 더 직관적으로 알 수 있으면 좋을 것 같아요.
~가 주어졌을 때, ~을 하면, ~한 결과가 나온다와 같이요.

또, 예외만 테스트하는 것이 아닌 정상적인 경우에 대한 테스트도 있으면 좋을 것 같다는 생각이 들어요. 테스트를 보고 이 메서드가 무슨 역할을 하는지 파악할 때가 있는데, 예외에 대한 테스트만 있으면 이 부분을 파악하기가 쉽지 않더라구요 😄

2022-10-27 14:58 UTC, sungjun1116 commented on src/main/java/lotto/view/InputView.java
> +        scanner.close();
애플리케이션이 종료되기 전에 언데 input을 받아야할 일이 생길지 모른다면 scanner 리소스를 반납하기 어려워 보여 scanner.close() 메서드 제거했습니다.

2022-10-28 02:04 UTC, ddaaac approved these changes
안녕하세요 성준님 👋 

전반적으로 리뷰 반영 너무 잘해주셔서 머지해도 될 것 같아요.

다음 단계 진행해주세요!

2022-10-28 02:04 UTC, ddaaac commented on src/main/java/lotto/domain/Store.java
> +    public List<Rank> match(final List<LottoNumber> winningNumbers) {
이 메서드에 대한 테스트가 없는 것 같아요. 현재 구조에서는 아마 테스트코드 작성이 쉽지 않을 것 같은데, 다음 단계를 진행하면서 테스트 가능한 구조로 개선해보시면 좋을 것 같습니다 😄

2022-10-28 02:04 UTC, merged