step3 : 로또 2등
next-step/java-lotto pull request #2710
Opened 2022-10-24 04:40 UTC by sienna011022

2022-10-26 04:45 UTC, seondongpyo requested changes
3단계 미션 잘 작성해주셨네요 👍
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁드릴게요 🔥

2022-10-26 04:45 UTC, seondongpyo commented on src/main/java/step2/model/Rank.java
> +	FIRST(6, 2_000_000_000),
enum 활용 👍

2022-10-26 04:45 UTC, seondongpyo commented on src/main/java/step2/model/Rank.java
> +
객체지향 생활 체조 원칙의 `규칙 4: 한 줄에 점을 하나만 찍는다.`를 준수해보면 좋을 것 같아요.
```suggestion
		return Arrays.stream(values())
			.filter(rank -> rank.getCountOfMatch() == countOfMatch)
			.findFirst()
			.orElse(MISS);
```

2022-10-26 04:45 UTC, seondongpyo commented on src/main/java/step2/model/WinningLotto.java
> +	private List<Integer> winLotto;
상수와 인스턴스 변수의 구분을 위해 공백 라인을 추가해보면 좋을 것 같아요.
```suggestion
	private static final int SECOND_MATCH_NUM = 5;
	
	private List<Integer> winLotto;
```

2022-10-26 04:45 UTC, seondongpyo commented on src/main/java/step2/model/WinningLotto.java
> +		return new WinningLotto(winNumList, bonusNumber);
당첨 번호와 보너스 번호가 중복되면 어떻게 될까요?

2022-10-26 04:45 UTC, seondongpyo commented on src/main/java/step2/model/WinningLotto.java
> +		return false;
다음처럼 작성해볼 수 있을 것 같아요.
```suggestion
		return countOfBonus > 0;
```

2022-10-26 04:45 UTC, seondongpyo commented on src/main/java/step2/view/OutputView.java
> +			showResult(key, bonusMatchCount, totalCount);
로또 당첨 결과가 정상적으로 출력되지 않는 것 같은데 확인해주시면 좋을 것 같아요.

2022-10-26 04:45 UTC, seondongpyo commented on src/main/java/step2/view/OutputView.java
>  		return true;
다음처럼 줄여서 작성해볼 수 있을 것 같아요.
```suggestion
		return rate > BENEFIT_STANDARD;
```

2022-10-26 04:45 UTC, seondongpyo commented on src/main/java/step2/model/Lotteries.java
> +			totalMatch.put(countOfMatch, totalMatch.get(countOfMatch) + ADD_MATCH_COUNT);
구매한 로또의 당첨 결과를 구할 때 로또 등수인 `Rank`를 활용해보는 건 어떨까요?

2022-10-26 08:02 UTC, sienna011022 commented on src/main/java/step2/model/Lotteries.java
> +	private static WinningLotto winningLotto;
Winnig Lotto안에 속성으로 당첨 번호와 보너스 번호를 가지고 있는데, 제 생각엔 프로그램 시작부터 끝까지 객체가 딱 한번 생성되고 고정 되어야 한다고 생각했습니다. 그래서 static으로 선언을 했습니다!불 필요할까요? 😄

2022-10-26 08:18 UTC, sienna011022 commented on src/main/java/step2/model/Payment.java
>  		}
아 지난번 커멘트를 제가 잘못 이해했네요 ㅎㅎ

![image](https://user-images.githubusercontent.com/90383376/197972628-c7b423c6-b264-45e1-a55a-8c6db480829e.png)
이런 커멘트를 보고 나누어 떨어지지 않는 경우를 구현해보시라는 줄 알았는데 "테스트" 코드였네요 ㅎㅎ

2022-10-26 13:38 UTC, sienna011022 commented on src/main/java/step2/view/OutputView.java
> +			showResult(key, bonusMatchCount, totalCount);
엇 저는 잘 되는데 혹시 예시가 있으실까요?

2022-10-26 14:34 UTC, sienna011022 commented on src/main/java/step2/view/OutputView.java
>  	private void showResult(Rank rank, int bonusMatchCount, HashMap<Rank, Integer> totalCount) {
아무리 고민해도 파라미터를 3개던지게 되는데 ....이는 좋지 못한 코드라고 알고 있습니다.
파라미터를 줄일 좋은 방법이 있을까요?

2022-10-26 14:34 UTC, sienna011022 commented on src/main/java/step2/controller/LottoController.java
>  		Lotteries lotteries = Lotteries.of(totalTicket, lottoFactory);
보통 immutable한 객체는 다음과 같이 static builder로 생성하는게 맞나요?

2022-10-27 02:23 UTC, sienna011022 commented
OOP에 대한 개념을 클린 코드를 하면서 처음으로 같이 알아가는 중이라 신경을 쓰며 코드를 구현하였는데 혹시 코드 중에 객체 지향적으로 짜이지 않은 부분이 있는지 궁금합니다!

2022-10-27 03:09 UTC, seondongpyo approved these changes
피드백 반영하시느라 고생하셨습니다.
몇 가지 추가로 코멘트 드렸는데 다음 단계 진행하시면서 확인 부탁드릴게요.
어느덧 마지막 단계만 남았는데 조금만 더 힘내주세요 🔥

2022-10-27 03:09 UTC, seondongpyo commented on src/main/java/step2/view/OutputView.java
>  	private void showResult(Rank rank, int bonusMatchCount, HashMap<Rank, Integer> totalCount) {
전체 로또 당첨 결과를 담고 있는 `HashMap<Rank, Integer>` 만으로도 충분히 결과를 출력할 수 있을 것 같아요.
이 부분은 다음 단계 진행하시면서 조금 더 고민해보시면 답을 찾으실 수 있을 것 같아요.

2022-10-27 03:09 UTC, seondongpyo commented on src/main/java/step2/view/OutputView.java
> +	private void rankSecondMessage(int countOfBonus, int countOfMatch) {
2등과 3등 결과 메시지가 제대로 출력되지 않는 것 같은데 확인 부탁드릴게요.

![image](https://user-images.githubusercontent.com/64854054/198180994-56e6aa98-a01a-4204-b82a-5b393ec71bcb.png)

2022-10-27 03:09 UTC, seondongpyo commented on src/main/java/step2/model/Lotto.java
>  		this(lottoFactory.getLottoNum());
현재 `RandomLottoFactory`는 로또 생성 시 중복되는 로또 번호를 제공할 가능성이 높은 구조입니다.
로또를 여러 장 발급하는 경우 어떤 부분에서 문제가 될지 체크해보시면 좋을 것 같아요.

2022-10-27 03:09 UTC, merged