Step3 - 로또(2등)
next-step/java-lotto pull request #2724
Opened 2022-10-25 06:11 UTC by jwoo-o

step3 로또 2등 pr 올립니다

2022-10-26 10:36 UTC, JunHoPark93 requested changes
안녕하세요~ 로또 3단계 고생하셨어요.
간단한 피드백 몇가지 남겼는데 확인 후 의견 및 반영부탁드려요~

2022-10-26 10:36 UTC, JunHoPark93 commented on src/main/java/lotto/domain/LottoPlace.java
> +    }
static value에서 다시 stream 매번 계산하는 방식으로 바꾼 이유가 있을까요?

2022-10-26 10:36 UTC, JunHoPark93 commented on src/main/java/lotto/domain/LottoWinners.java
> +        return winners;
불변 결과를 리턴해보면 어떨까요?

2022-10-26 10:36 UTC, JunHoPark93 commented on src/main/java/lotto/domain/Lotto.java
> +    }
계속해서 보너스 볼을 수정할 수 있는 구조인데요, 개선해볼 수 있을까요?

2022-10-26 10:36 UTC, JunHoPark93 commented on src/main/java/lotto/domain/LottoPlace.java
> +    public static LottoPlace getLottoPlace(int count, boolean matchBonus) {
전체적으로 중괄호 컨벤션도 같이 확인 부탁 드려요~

2022-10-27 08:57 UTC, jwoo-o commented on src/main/java/lotto/domain/LottoPlace.java
> +    }
2등 3등이 key가 5로 중복되어 static map 자체가 compile에러가 발생해 변경 하게 되었습니다

2022-10-28 14:14 UTC, JunHoPark93 approved these changes
안녕하세요~ 로또 피드백 반영하느라 고생많으셨어요.
추가적으로 몇 가지 피드백 남겼는데 다음 step에서 확인 부탁드려요 😊

2022-10-28 14:14 UTC, JunHoPark93 commented on src/test/java/lotto/domain/LottoWinnersTest.java
> +    void setUp() {
전체적으로 컨벤션들 신경쓰느라 고생많으셨어요~
누락된 부분들도 함께 확인 부탁드려요 :)

2022-10-28 14:14 UTC, JunHoPark93 commented on src/main/java/lotto/controller/LottoController.java
> +        LottoWinners winners = LottoWinners.of(lottoList.getLottoList(), weekendLotto, weekendBonusNumber);
valid한 보너번호인지 밖에서 판단은 하고있는데요, LottoWinners.of로 둘 다 들어가고있어요. 실수할수 있는 구조인거같은데요, LottoWinners안에서 검증하든지 혹은 다른 검증방법이 있을지 고민해보면 어떨까요? 🤔

2022-10-28 14:14 UTC, merged