2단계 - 로또(자동)
next-step/java-lotto pull request #2737
Opened 2022-10-26 15:47 UTC by hocaron

## 📃 개요
- 2단계 - 로또(자동)에 관한 PR입니다.
- 테스트 코드 네이밍은[ Given_Preconditions_When_StateUnderTest_Then_ExpectedBehavior](https://dzone.com/articles/7-popular-unit-test-naming) 을 따릅니다.

## ✏️ 변경사항
### 로또(자동) 코드 작성
- View - 무엇을 입력받거나 출력하기 위한 역할
  - InputView 클래스 : 입력 및 문자열을 입력받아서 문자 배열로 반환 처리
  - OutputView 클래스 : 출력 처리
- Contoller - 데이터를 어떻게 처리할지 알려주는 역할
  - 인풋 값 입력부터 계산, 출력까지 처리
- Model - 내부 비즈니스 로직을 처리하기 위한 역할
  - Lotto 클래스 : 로또에 관한 로직을 처리
    - 로또 생성
    - 일치하는 숫자 개수 반환
  - Lottos 클래스 : 로또 리스트에 관한 로직을 처리
    - 로또 리스트 생성
    - 로또 리스트와 일치하는 숫자 개수를 hashMap으로 반환 
  - WinningAmount Enum: 일치하는 숫자와 상금에 관리

### 로또(자동) 테스트 코드 작성

코드리뷰 감사합니다🙇‍♀️

2022-10-26 23:09 UTC, neojjc2 commented
#tag @neojjc2

2022-10-26 23:35 UTC, neojjc2 requested changes
안녕하세요 선우님 😄 

2단계 미션 잘 구현해주셨습니다 💯 
조금만 다듬어지면 좋을 것 같아서
소소한 의견 몇 가지 드렸는데요
한번 검토해주시면 좋을 것 같습니다 🙇 

그럼 재 리뷰 요청 기다리고 있겠습니다 🙏

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step1/model/number/Number.java
> +	public Number plus(int a) {
요청사항 반영 👍

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/Main.java
> +	private static final LottoController lottoController = new LottoController();
정적 상수로 선언하신 이유가 궁금합니다 😄 
정적 상수의 영역에 들어가면 프로그램이 종료 될 때 까지 메모리에 남아있게 됩니다 
보통은 그래서 상수이거나 (변하지 않는 값), 한번 초기화 하면 
그 이후 사용함에 있어서 `thread-safe`하고 `instance`로 생성하는 비용이 많이 드는경우에 사용하는데요 🤔 

어떤 목적이신지 궁금해서 질문드려봤습니다 😄 
참고로 지난 리뷰에서도 의견 드린 것 처럼 정적상수는 대문자 컨벤션 입니다 🙇 
> https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/Main.java
> +		lottoController.purchase();
`Controller`를 사용하신 것 좋습니다 👍

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/controller/LottoController.java
> +		final int count = getLottoCount(inputView.getPurchaseAmount());
이 부분에 대한 예외처리도 보완되면 더 좋을 것 같습니다 😄 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/68527004/198156959-270a6a05-6b61-441b-82f7-2b2e9e069f12.png">

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/controller/LottoController.java
> +		winningLotto = new Lotto(inputView.getWinningNumber());
이 부분도 같이 고민해주시면 감사하겠습니다 🙏 

<img width="440" alt="image" src="https://user-images.githubusercontent.com/68527004/198157033-5d5befd2-2532-4e9a-a618-c0d97e05e540.png">

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/controller/LottoController.java
> +	private double getPrize(HashMap<Integer, Integer> countMap) {
`LottoController`의 어깨가 무거워보입니다 😅 
로또 개수도 구해야 하고 당첨결과도 알아와야 하고 당첨 통계 및 수익률도 담당하고 있습니다 
적절하게 객체를 추출하면 `Controller` 고유의 역할인 흐름제어에만 집중할 수 있을 것 같습니다 😄 
지금도 요구사항 충분히 잘 구현해주셨는데요
한번 구조에 대해서도 개선 고민 해주시면 감사하겠습니다 🙇

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/model/lotto/Lotto.java
> +	private static final List<Integer> AVAILABLE_NUMBERS = range(MIN_NUMBER, MAX_NUMBER + 1).boxed().collect(Collectors.toList());
재사용 객체 상수 선언 💯

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/model/lotto/Lotto.java
> +		if (numbers.size() != LOTTO_SIZE) {
검증 하는 로직이 있는건 👍 
하지만 이 부분도 같이 검증되면 더 좋을 것 같습니다 🙏 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/68527004/198157418-4138cf5c-9eaf-447c-9a3d-ec34d93f4b74.png">

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/model/lotto/Lottos.java
> +		HashMap<Integer, Integer> countMap = range(1, winningLotto.getNumbers().size() + 1).boxed()
`stream`을 연습해보시는건 좋지만 때로는 `for-loop`가 더 가독성이 좋을 때도 있습니다 😄 
`stream`을 생성하는 비용도 절약할 수 있고요 😅 
환기 차원에서 이 내용 한번 보고가시면 좋을 것 같습니다 🙇 
> https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/

2022-10-26 23:35 UTC, neojjc2 commented on src/main/java/step2/model/lotto/WinningAmount.java
> +	SIX_MATCH(6, 2000000000);
`Enum`을 통한 당첨조건 관리하신 부분 좋네요 👍 
소소하지만 가독성을 위해서 이렇게도 표현 가능합니다 🙏 
```java
THREE_MATCH(3, 5_000),
FOUR_MATCH(4, 50_000),
FIVE_MATCH(5, 1_500_000),
SIX_MATCH(6, 2_000_000_000);
```

2022-10-27 03:41 UTC, hocaron commented on src/main/java/step2/controller/LottoController.java
> +		winningLotto = new Lotto(inputView.getWinningNumber());
오.. 혹시 이 부분은 수익률을 소수점 둘째자리까지 보여주는 것이 아닌(0.00) 정수(0)으로 보이면 더 좋을 같다고 말씀해주신게 맞을까요?!🤔

2022-10-27 03:48 UTC, hocaron commented on src/main/java/step2/model/lotto/WinningAmount.java
> +	SIX_MATCH(6, 2000000000);
가독성이 확 높아지는 군요👍
[34385dc](https://github.com/next-step/java-lotto/pull/2737/commits/34385dc11066823be7eb3d425786e5f6abedf788) 에 반영완료 하였습니다🙇‍♀️

2022-10-27 03:49 UTC, hocaron commented on src/main/java/step2/model/lotto/Lotto.java
> +		if (numbers.size() != LOTTO_SIZE) {
번호에 중복되는 정수가 있는 경우에 `"로또 번호는 중복될 수 없습니다."` 예외처리를 추가하였습니다.
[34385dc](https://github.com/next-step/java-lotto/pull/2737/commits/34385dc11066823be7eb3d425786e5f6abedf788) 에 반영완료🙇‍♀️

2022-10-27 03:50 UTC, hocaron commented on src/main/java/step2/controller/LottoController.java
> +		final int count = getLottoCount(inputView.getPurchaseAmount());
구매 금액이 로또 가격(1000)이 넘지 않는 경우에 대해 `입력가능한 최소 구매 금액은 1000 입니다.` 예외처리를 추가하였습니다.
[34385dc](https://github.com/next-step/java-lotto/pull/2737/commits/34385dc11066823be7eb3d425786e5f6abedf788) 에 반영완료🙇‍♀️

2022-10-27 03:55 UTC, hocaron commented on src/main/java/step2/Main.java
> +	private static final LottoController lottoController = new LottoController();
Main 에서 사용하려다보니 정적 상수를 사용했습니다.
Main을 사용한 이유는 동작 시키기 편해서 였고, 이외에는 다른 이유가 없으니 위치를 Main내로 옮기겠습니다.

[73794db](https://github.com/next-step/java-lotto/pull/2737/commits/73794db5437e84ec841a70522e93736b1eb5621f) 에 반영완료🙇‍♀️

2022-10-27 03:59 UTC, hocaron commented on src/main/java/step2/model/lotto/Lottos.java
> +		HashMap<Integer, Integer> countMap = range(1, winningLotto.getNumbers().size() + 1).boxed()
> *요즘 함수형 프로그래밍이 대세니 무조건 반복문 대신 Stream을 써야지!* 라는 생각을 하는 당신, 모든 for문을 Stream의 foreach로 구현하려고 했다면… 그 손 키보드에서 떼기 바란다!

키보드에서 손을 떼야겠네요😇 공유 감사합니다.
코드 한줄 줄이려다가, 오히려 가독성을 떨어뜨린 것 같습니다!

[6549e33](https://github.com/next-step/java-lotto/pull/2737/commits/6549e333c90e207aa97862ea59ce6c8a9307cbae) 에 반영완료🙇‍♀️

2022-10-27 04:31 UTC, hocaron commented on src/main/java/step2/controller/LottoController.java
> +	private double getPrize(HashMap<Integer, Integer> countMap) {
당첨 결과를 처리하는 객체를 생성하였습니다.
[5981176](https://github.com/next-step/java-lotto/pull/2737/commits/59811766202445d4f5f0902f4cd9fd14bebfce1b) 에 반영완료🙇‍♀️

만들고 나니, 구매한 로또와 당첨 로또를 final로 관리하여 당첨 결과와 상금까지 final로 관리할 수 있어서 좋은 것 같습니다.👍
피드백 감사합니다. 준철님😀

2022-10-27 04:41 UTC, neojjc2 commented on src/main/java/step2/controller/LottoController.java
> +		winningLotto = new Lotto(inputView.getWinningNumber());
@hocaron 님 
아 제가 혼선을 드렸네요 😄 당첨번호 입니다

2022-10-27 04:42 UTC, neojjc2 commented on src/main/java/step2/Main.java
> +	private static final LottoController lottoController = new LottoController();
네 그런 이유라면 크게 문제 되지는 않을 것 같습니다 😄 👍

2022-10-27 04:43 UTC, neojjc2 commented on src/main/java/step2/model/lotto/Lottos.java
> +		HashMap<Integer, Integer> countMap = range(1, winningLotto.getNumbers().size() + 1).boxed()
@hocaron 님
문득 저도 떼야 할것 같습니다 😨 😆😆😆😆😆

2022-10-27 07:45 UTC, hocaron commented on src/main/java/step2/controller/LottoController.java
> +		winningLotto = new Lotto(inputView.getWinningNumber());
숫자 범위를 체크하는 메서드 및 테스트 클래스 작성하였습니다.
validation 부분에서 제가 놓친 부분이 많군요🥲

[ecd5bc3](https://github.com/next-step/java-lotto/pull/2737/commits/ecd5bc3c53935d528956b9502a442ff65a435e58) 에 반영완료🙇‍♀️

2022-10-27 23:40 UTC, neojjc2 approved these changes
안녕하세요 선우님 😄 

다소 많은 요청사항을 드린게 아닌가 걱정했는데
하나하나 꼼꼼히 고민해주시고 잘 반영해주셨네요 👍 

정말 수고 많으셨습니다 🙏 
다음 단계 진행하시죠

`merge`하겠습니다 👍

2022-10-27 23:40 UTC, merged