Step3 - 3단계 - 로또(2등)
next-step/java-lotto pull request #2750
Opened 2022-10-30 08:40 UTC by shineyuno

리뷰 잘부탁드랍니다.

## 변경사항 
* step2  피드백 반영
* 로또 2등 구현 

## 문의사항
Enum 클래스가 기본으로 제공하는 values() 메서드를 활용해서 아래처럼 당첨등수 프린트를 하나씩 하드코딩하는거에서 
피드백을 받고 for 문으로 변경하였습니다.
Enum에 정의한 순서와  1등( FIRST) -> 4등(FOURTH)  와  콘솔창에 보여줄때는  4등 -> 1등 으로 정의한 순서의  역순이라
아래와 같이 for 문을 작성하였는데요. 혹시 더 좋은 방법으로  역순으로 프린트할수 있는 방법이 있었을까요?

```java 
//before
        printRank(Rank.FOURTH, rankMap);
        printRank(Rank.THIRD, rankMap);
        printRank(Rank.SECOND, rankMap);
        printRank(Rank.FIRST, rankMap);

//after
        Rank[] rankList = Rank.values();
        for (int i = rankList.length - 2; i >= 0; i--) {
            Rank rank = rankList[i];
            printRank(rank, rankMap);
        }
```

2022-10-31 03:36 UTC, testrace requested changes
안녕하세요 윤호님 😃
3단계 구현 잘해주셨네요 👍
몇 가지 코멘트 남겨두었으니 확인해 주시고 주시고 리뷰 요청 부탁드립니다.
궁금한 내용이 있으시면 편하게 DM 주세요!

2022-10-31 03:36 UTC, testrace commented on src/main/java/lotto/LottoMain.java
> +        WinnigTicket winnigTicket = new WinnigTicket(lottoWinningTicket, bonusNumber);
지난주 당첨번호에 대한 유효성 검증이 필요할 것 같아요.
테스트 코드를 통해서 로직을 검증하면 어떨까요?
<img width="470" alt="image" src="https://user-images.githubusercontent.com/8064743/198925310-357f1128-3875-45ea-b47a-63d7f41730a5.png">

2022-10-31 03:36 UTC, testrace commented on src/main/java/lotto/domain/WinnigTicket.java
> +public class WinnigTicket {
Ticket과 LottoNumber를 활용해 당첨 번호를 구현해 주셨네요 👍 
클래스명에 오타가 있는 것 같아요
```suggestion
public class WinningTicket {
```

2022-10-31 03:36 UTC, testrace commented on src/main/java/lotto/view/ResultView.java
> +        }
질문 주신 부분이네요!
enum의 values 메서드는 enum에 열거된 순서대로 배열이 생성되는데요,
아래와 같이 낮은 등수부터 작성해 주시면 원하시는 결과가 나올 것 같아요 😃 
또는 Collections.reverse() 메서드를 활용해 보셔도 좋을 것 같아요!
```java
    FIFTH(3, 5_000),
    FOURTH(4, 50_000),
    THIRD(5, 1_500_000),
    SECOND(5, 30_000_000),
    FIRST(6,2_000_000_000),
```

2022-10-31 03:36 UTC, testrace commented on src/main/java/lotto/domain/WinnigTicket.java
> +    public WinnigTicket(Ticket ticket, LottoNumber bonusNumber) {
모든 객체의 로직에 단위 테스트를 추가해 보시면 좋을 것 같아요! 😃 
생성자도 로직으로 취급하고 객체 생성이 정상적으로 되는 경우와
생성되지 않는 경우의 테스트가 있으면 어떨까요?

2022-10-31 12:19 UTC, shineyuno commented on src/main/java/lotto/LottoMain.java
> +        WinnigTicket winnigTicket = new WinnigTicket(lottoWinningTicket, bonusNumber);
아래 커밋에서 유효성 검증 추가했습니다. 
https://github.com/next-step/java-lotto/pull/2750/commits/1728edc63eccebecc3e4c17252706da4ab95e1de

TicketTest 와 WinnigTicketTest  에서 테스트 진행하였습니다.

2022-10-31 12:19 UTC, shineyuno commented on src/main/java/lotto/domain/WinnigTicket.java
> +public class WinnigTicket {
오타 수정하엿습니다.

2022-10-31 12:23 UTC, shineyuno commented on src/main/java/lotto/domain/WinnigTicket.java
> +    public WinnigTicket(Ticket ticket, LottoNumber bonusNumber) {
WinningTicketTest 테스트 추가하였습니따.

2022-11-01 03:48 UTC, testrace approved these changes
안녕하세요 윤호님 😃 
피드백 반영 잘해주셨네요 👍 
바로 다음 단계로 넘어가겠습니다!
로또 미션의 끝이 보이네요. 마지막까지 화이팅입니다 🔥

2022-11-01 03:48 UTC, testrace commented on src/main/java/lotto/domain/Ticket.java
> +                .count();
stream을 활용해 중복을 제거해 주셨네요 👍 
Set 자료 구조를 활용해 보시는 것도 추천드립니다!

2022-11-01 03:48 UTC, merged