Step2 코드리뷰 요청 드립니다.
next-step/java-lotto pull request #2770
Opened 2022-11-01 15:49 UTC by heoseungyeon

안녕하세요 지훈님! 🙇  Step 2 코드리뷰 요청 드립니다!

최대한 TDD 원칙을 지키면서 싸이클을 돌려고 노력했지만,,,
마지막에 [출력 기능 커밋](https://github.com/next-step/java-lotto/commit/99024703bb6df9c492587e7b737ab1042771c6cc) 을 할 때, 기존에 TDD를 통해 테스트 코드 바탕으로 작성했던 기능 코드를 대거 수정하게 되었네요 😂 

많은 피드백 부탁드립니다 !!

2022-11-02 13:13 UTC, vagabond95 requested changes
2단계 마무리 잘해주셨네요 👍 
구현해주신 내용에 대하여 몇가지 리뷰 남겼는데 확인 후 다시 리뷰요청 부탁드려요!

2022-11-02 13:13 UTC, vagabond95 commented on src/main/java/lotto/LotteryApp.java
> +			final PurchaseCountDto purchaseCountDto = PurchaseCountDto.of(lottos.getCount());
도메인을 그대로 넘겨주는 것이 아니라 DTO 를 잘 활용해주셨네요 👍

2022-11-02 13:13 UTC, vagabond95 commented on src/main/java/lotto/domain/Lotto.java
> +	public final List<Integer> candidates = IntStream.rangeClosed(1, 45).boxed().collect(Collectors.toList());
로또 숫자의 후보군을 계속 상태로 가지고 있을 필요가 있을까요~?
번호를 생성해주는 부분은 별도 클래스에 다루는 것도 괜찮을 것 같아요.

2022-11-02 13:13 UTC, vagabond95 commented on src/main/java/lotto/domain/Lotto.java
> +		if (!isValidNumbersSize(numbers)) {
숫자 중복 체크도 진행되면 좋을 것 같아요.

2022-11-02 13:13 UTC, vagabond95 commented on src/main/java/lotto/domain/Reward.java
> +	FIVE_MATCH_REWARD(5, 1500000),
```suggestion
	FIVE_MATCH_REWARD(5, 1_500_000),
```
언더스코어를 활용하면 가독성을 좀 더 확보할 수 있습니다!

2022-11-02 13:13 UTC, vagabond95 commented on src/main/java/lotto/exception/InvalidMatchCountException.java
> +public class InvalidMatchCountException extends RuntimeException {
커스텀 예외 이용 👍

2022-11-02 13:13 UTC, vagabond95 commented on src/main/java/lotto/view/ResultView.java
> +	private static final String UNDER_LINE = "----------";
매직 리터럴 상수화 👍

2022-11-03 07:01 UTC, heoseungyeon commented
안녕하세요 지훈님!
피드백 반영하여 다시 한번 코드리뷰 요청드립니다!! 👍

2022-11-03 07:02 UTC, heoseungyeon commented on src/main/java/lotto/domain/Reward.java
> +	FIVE_MATCH_REWARD(5, 1500000),
요건 처음 알았네요....! 👍

2022-11-04 09:37 UTC, vagabond95 approved these changes
리뷰 내용의 의도에 맞게 잘 수정해주셨네요 👍 
2단계도 머지하도록 하겠습니다~!

2022-11-04 09:37 UTC, merged