Step3 - 로또(2등)
next-step/java-lotto pull request #2776
Opened 2022-11-02 14:32 UTC by allstarkenny

- 잘 부탁 드립니다 🙇‍♂️

2022-11-03 15:47 UTC, KIMSIYOUNG requested changes
안녕하세요.
깔끔하게 잘 구현해주셨네요.
몇가지 코멘트 남겼는데 확인 부탁드려요!

2022-11-03 15:47 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/Lotto.java
>          int matchCount = (int) lottoNumbers.stream().filter(w -> winningLotto.contains(w)).count();
스트림은 줄바꿈을 해주는게 가독에 좋은 것 같아요.

2022-11-03 15:47 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoNumber.java
> +    public LottoNumber getLottoNumber(){
이런 형태의 반환이 필요한 이유가 있나요? 해당 객체를 이미 생성한 쪽에선 이미 this를 쓰고 있는 것 아닌가요?

2022-11-03 15:47 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoNumberGenerator.java
>  public class LottoNumberGenerator {
캐싱 잘 적용해주셨네요🙂

취향이지만 요정도 캐싱은 LottoNumber에서 직접해주는게 역할이 분산되지 않아 좋은 것 같아요.

LottoNumber의 역할이 많아진다면 현재와 같은 구조도 좋은 것 같습니다.

2022-11-03 15:47 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoResult.java
> +    SECOND_PRIZE(5, 30000000),
필드에 보너스여부를 관리하면 보다 가독이 용이할 것 같아요.

2022-11-03 15:47 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningsCalculator.java
>  public class WinningsCalculator {
해당 객체는 사실상 static 한 형태네요. 

객체처럼 만들 순 없을까요?

2022-11-04 00:19 UTC, allstarkenny commented on src/main/java/lotto/controller/LottoGameController.java
> +        LottoNumber bonusNumber = new LottoNumber(InputView.getBonusNumber());
오호 합쳐볼 생각을 못했네요. ❤️ 
한번 합쳐볼께요.

2022-11-04 00:20 UTC, allstarkenny commented on src/main/java/lotto/domain/Lotto.java
>          return numbers.replaceAll(" ", "");
아하 앞단에서 전처리를 할 수 있도록 수정해보겠습니다

2022-11-04 00:20 UTC, allstarkenny commented on src/main/java/lotto/domain/Lotto.java
>          int matchCount = (int) lottoNumbers.stream().filter(w -> winningLotto.contains(w)).count();
엇 수정만 하고 줄바꿈이 빠졌네요 😅 
수정하겠습니다.

2022-11-04 00:21 UTC, allstarkenny commented on src/main/java/lotto/domain/LottoNumber.java
> +    public LottoNumber getLottoNumber(){
엇 수정해볼께요.

2022-11-04 00:21 UTC, allstarkenny commented on src/main/java/lotto/domain/LottoResult.java
> +    SECOND_PRIZE(5, 30000000),
오 너무 좋습니다.

2022-11-04 00:22 UTC, allstarkenny commented on src/main/java/lotto/domain/WinningsCalculator.java
>  public class WinningsCalculator {
흠.. 조금 더 고민해볼께요. 요부분은 참 어렵네요 😢

2022-11-04 01:40 UTC, allstarkenny commented
생각보다 대공사였네요 👨‍🔧 😢

2022-11-06 05:04 UTC, KIMSIYOUNG approved these changes
안녕하세요.
리뷰가 늦어 죄송합니다.
리뷰 반영 잘 해주셨네요!
몇가지 코멘트 추가로 드렸는데 다음 단계에서 같이 고민해보시면 좋을 것 같습니다.

2022-11-06 05:04 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/Lotto.java
>          for (String number : numbers.split(",")) {
도메인에서 다양한 생성을 지원해주는 것은 좋은 것 같습니다.

다만 이정도로 뷰와 밀접한 형태를 지원해줄 필요가 있는지는 고민해보면 좋을 것 같아요.

뷰에서 입력하는 형태가 달라지면 현재는 도메인도 달라져야하는 구조인데 List<Integer>혹은 List<String>정도만 지원을 해줘도 적절하지 않을까요?

2022-11-06 05:04 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +    public static Map<Integer, LottoNumber> lottoNumbers = new HashMap<>();
아래와 같이 구현할 수도 있을 것 같아요.
```java
private static final Map<Integer, LottoNumber> lottoNumbers = IntStream.rangeClosed(1, MAX_LOTTO_NUMBER)
        .mapToObj(LottoNumber::new)
        .collect(Collectors.toMap(LottoNumber::getNumber, Function.identity()));


```

2022-11-06 05:04 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoResults.java
> +    public boolean equals(Object o) {
equals hashcode는 어떤 기준으로 재정의하고 계신가요?

2022-11-06 05:04 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoResults.java
> +public class LottoResults {
객체로 깔끔하게 잘 분리해주셨네요👏

2022-11-06 05:04 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoResults.java
> +        return lottoResults;
불변객체에 대해서도 학습해보고 적용해보면 좋을 것 같습니다.

2022-11-06 05:04 UTC, merged

2022-11-09 10:47 UTC, allstarkenny commented on src/main/java/lotto/domain/WinningLotto.java
> +    public LottoResult getResult(Lotto lotto) {
흠.. 어떤게 더 나을지 고민이네요.
제 생각에는 일반 로또에게 물어보는게 더 나을거 같네요. 수정해볼께요 🙏

2022-11-09 10:53 UTC, allstarkenny commented on src/main/java/lotto/domain/LottoResults.java
> +    public boolean equals(Object o) {
엇 다른 메소드 지우다가 함께 지워졌나보네요.
추가해볼께요.