로또 3단계
next-step/java-lotto pull request #2778
Opened 2022-11-03 09:23 UTC by samkimuel

안녕하세요 지훈님! 이번 단계도 잘 부탁드립니다🙇‍♂️

궁금한 점 코멘트로 남겨두었는데, 확인 부탁드려요 ㅎㅎ 감사합니다!

2022-11-03 09:29 UTC, samkimuel commented on src/main/java/lotto/domain/LottoStatistics.java
> +        calculateMatchingBonusNumberCount(countsByWinningAccordance, countOfSecondWinningAccordance);
2등 당첨 통계를 위해 보너스 볼을 포함해 계산하는 코드입니다.

일단 LottoStatistics의 역할로 할당했는데, 이 역할을 AccordanceCount 클래스로 위임해야할지 고민이 됩니다.
계산했던 결과(countsByWinningAccordance)를 매개변수로 넘겨주면서 값이 변하게 되는데, 올바른 방법일까요?
피드백 부탁드립니다!

2022-11-04 12:32 UTC, vagabond95 commented
보너스 번호 요구사항으로 인해 고민이 많으실 것 같습니다. 😭 

제 생각을 조금 남겨보겠습니다. 참고만 부탁드려요~!
1. 특정 등수 (2등) 에 대한 코드가 많이 보이는데요, 보너스 번호를 가진 등수가 2등이기에 이렇게 구현된 것으로 이해됩니다. 그런데 만약 보너스 번호를 가질 수 있는 등수가 앞으로 늘어나게 된다면 현재 2등과 관련된 모든 코드에 추가적인 분기코드가 추가되어야만해요. 변경에 유연하지 않은 형태인 것 같습니다.

2. 각 클래스의 역할을 조금 더 명확히 해보면 좋을 것 같아요. 가령
- LottoStatistics : 당첨된 등수를 기준으로 당첨금을 계산하는데 집중. 등수를 어떻게 선정하는데는 결정하지 않음.
- Lotto : 당첨번호 일치 횟수 / 보너스 번호 일치 횟수만 체크하는데 집중
- WinningAccordance : 당첨번호 일치 횟수 / 보너스 번호 일치 횟수를 전달받아 등수를 가져오는데 집중.

2022-11-04 12:34 UTC, vagabond95 requested changes
3단계 구현하시느라 고생 많으셨습니다. 보너스 번호 조건이 생각보다 까다롭죠 😿 

질문 주신 내용을 베이스로 제 생각을 남겨봤어요. 참고부탁드릴게요~!

2022-11-04 14:03 UTC, samkimuel commented
피드백 주신대로 수정했습니다.

- 당첨번호 일치 횟수 / 보너스 번호 일치 여부를 담는 Accordance 클래스를 정의
- WinningAccordance에서 Accordance를 바탕으로 등수 추출
- LottoStatistics는 등수를 기준으로 통계 산출

클래스 역할을 명확하게 분리해서 리팩토링하니 코드도 말끔해진 것 같습니다!
올바른 방향으로 리팩토링했는지 확인 한 번 더 부탁드립니다. 감사합니다!

2022-11-05 03:48 UTC, vagabond95 approved these changes
많은 구조를 건드리는 것이라 간단한 리펙토링이 아니였을텐데, 빠르게 잘 구현해주셨네요!

리펙토링해주신 부분 빠짐없이 제 리뷰 의도와 일치합니다 :) 고생많으셨어요.
3단계도 머지하도록 하겠습니다~!

2022-11-05 03:48 UTC, merged