4단계 - 로또(수동)
next-step/java-lotto pull request #2780
Opened 2022-11-04 12:47 UTC by gmelon

4단계 리뷰 요청 드립니다!

추가로 한 가지 질문드리겠습니다.
라이브 강의에서 포비님께서는 원시 값을 포장하면서 테스트 코드가 복잡해지는 문제를 여러 개의 생성자를 두어 해결해도 괜찮다고
(생성자는 많을 수록 좋다고) 말씀하셨는데
혹시 저번 리뷰에서 테스트만을 위한 생성자 사용을 지양하라고 리뷰해주신 것은 어떤 이유에서 일까요??

감사합니다!! :)

2022-11-04 20:44 UTC, pkch93 requested changes
안녕하세요 상혁님 ㅎㅎ
구조를 잘 잡아두셔서 수동 기능을 무리없이 추가가 된거 같네요 💯 
테스트 관련해서 몇가지 피드백드렸는데 확인부탁드릴께요.

2022-11-04 20:44 UTC, pkch93 commented on src/main/java/lottery/Lottery.java
> +    private void validate(Set<LotteryNumber> lotteryNumbers) {
6개로 구성되어있지 않은 경우에 대해 테스트가 누락된거 같아요.

2022-11-04 20:44 UTC, pkch93 commented on src/main/java/lottery/LotteryResult.java
>          return winningCounts.getOrDefault(lotteryRank, 0);
기본값이 0이 제대로 나오는지도 테스트되면 좋겠네요 :)

2022-11-04 20:44 UTC, pkch93 commented on src/test/java/lottery/LotteryResultTest.java
> +    void returnRate() {
메서드 명이 수정되면서 메서드 명과 같은 이름을 가진 테스트 메서드 명도 같이 수정이 되었는데요.

테스트 메서드 명은 테스트하고자하는 상황과 예상 결과를 표현하면 위 같은 상황이 벌어지지 않고 테스트를 이해하기도 좋을거 같아요. junit5의 `@DisplayName`을 사용하는 것도 좋은 방법일거 같네요.

2022-11-04 20:48 UTC, pkch93 commented
> 추가로 한 가지 질문드리겠습니다.
> 
> 라이브 강의에서 포비님께서는 원시 값을 포장하면서 테스트 코드가 복잡해지는 문제를 여러 개의 생성자를 두어 해결해도 괜찮다고
(생성자는 많을 수록 좋다고) 말씀하셨는데 혹시 저번 리뷰에서 테스트만을 위한 생성자 사용을 지양하라고 리뷰해주신 것은 어떤 이유에서 일까요??

아 위 질문에 답변드린다고 생각했었는데 리뷰하면서 까먹고 못했었네요 ㅎㅎ;;

포비께서 강의 중 어떤 맥락에서 위와같이 말씀하셨는지는 모르겠지만 일단 제 생각을 말씀드릴께요.

테스트에서만 사용하는 생성자는 최후의 수단으로 사용해야한다고 생각해요. 사용하더라도 프로덕션 코드의 로직을 사용하도록 만들어야한다고 생각해요. 지금 각각의 생성자가 따로 로직을 구성하고 있는데 만약 요구사항이 바껴서 프로덕션에서 사용하는 생성자의 로직만 바뀐다면 테스트는 성공하면서 실제 프로덕션 코드는 버그가 발생할 가능성도 있죠. 즉, 테스트가 제 기능을 못하는 상황이 발생할 수 있지 않을까요?

추가로 생성자를 추가한다는 의미는 생성 지점을 추가한다는 의미가 될꺼에요. 생성 지점이 늘어난다는 의미는 해당 객체가 변경될때마다 이를 확인해야하는 지점이 늘어난다는 의미가 되는데요. 굳이 생성 지점을 늘릴 필요는 없다고 생각해요. 만약 필요하다면 프로덕션에서 사용하는 생성자를 활용하여 test SourceSet 내부에 테스트 객체를 생성하기 위한 편의 메서드를 구현하는게 더 나은 선택이라고 생각합니다.

위와 같은 생각에서 드린 피드백이었어요. 제 말이 정답은 아니니깐 하나의 의견으로 봐주시고 혹시 의견있으시면 말씀주세요 ㅎㅎ

2022-11-08 06:43 UTC, gmelon commented on src/main/java/lottery/Lottery.java
> +    private void validate(Set<LotteryNumber> lotteryNumbers) {
@pkch93 값이 3개인 테스트 케이스는 이미 존재하는데 6개 미만, 6개 초과 이런식으로 조금 더 구체화하면 좋겠다는 말씀이실까요??

2022-11-08 06:47 UTC, gmelon commented on src/test/java/lottery/LotteryResultTest.java
> +    void returnRate() {
네, 이 부분 고민이었는데 참고하겠습니다!! 감사합니다 :)

2022-11-08 07:01 UTC, gmelon commented
@pkch93 네, 답변 감사합니다. 제가 잘 이해한 건지 추가로 몇 가지만 더 여쭤볼게요!

`지금 각각의 생성자가 따로 로직을 구성하고 있는데 만약 요구사항이 바껴서 프로덕션에서 사용하는 생성자의 로직만 바뀐다면 테스트는 성공하면서 실제 프로덕션 코드는 버그가 발생할 가능성도 있죠.`

그럼 위 말씀은 프로덕션 코드에서 사용되는 생성자를 테스트하지 않은 상황에 한정되는 것일까요? 만약 테스트를 위한 생성자를 추가했다고 하더라도, 프로덕션에서 사용되는 생성자 또한 별도로 테스트 해주면 (관리가 어렵긴 할 것 같아요!) 문제가 줄어든다고 할 수 있을까요??

2022-11-09 13:16 UTC, pkch93 commented on src/main/java/lottery/Lottery.java
> +    private void validate(Set<LotteryNumber> lotteryNumbers) {
Lottery 내부에 validate 로직이 있는데 그걸 테스트하는 케이스가 없는걸로 보여서 말씀드린건데요. 제가 놓쳤었나보네요 ㅎㅎ;;

2022-11-09 13:30 UTC, pkch93 commented
> @pkch93 네, 답변 감사합니다. 제가 잘 이해한 건지 추가로 몇 가지만 더 여쭤볼게요!
> 
> `지금 각각의 생성자가 따로 로직을 구성하고 있는데 만약 요구사항이 바껴서 프로덕션에서 사용하는 생성자의 로직만 바뀐다면 테스트는 성공하면서 실제 프로덕션 코드는 버그가 발생할 가능성도 있죠.`
> 
> 그럼 위 말씀은 프로덕션 코드에서 사용되는 생성자를 테스트하지 않은 상황에 한정되는 것일까요? 만약 테스트를 위한 생성자를 추가했다고 하더라도, 프로덕션에서 사용되는 생성자 또한 별도로 테스트 해주면 (관리가 어렵긴 할 것 같아요!) 문제가 줄어든다고 할 수 있을까요??

따로 프로덕션을 위한 생성자를 테스트하더라도 로직이 다르게 구성되어있다면 문제는 발생할 수 있을거 같아요. 로직이 다르게 구성이 되어있을 경우 프로덕션을 위한 생성자만 수정을 한 상태에서 테스트를 돌리면 버그가 있더라도 테스트는 그대로 통과를 할것으로 보여요. 왜냐면 테스트에서 사용하는 생성자의 로직은 수정이 되지 않았고 수정이 되지 않았기 때문에 그대로 테스트가 통과할거니깐요. 자동화된 테스트를 만드는 이유 중에 하나가 로직이 수정되었을때 발생하는 사이드 이펙트, 버그 등을 확인함도 있을텐데요. 이렇게 따로 가져간다는 것 자체는 별로 좋지 않은 방법이라고 생각해요.

만약 로직을 같게 가져간다면 (this를 통해 프로덕션에서 사용하는 생성자의 로직을 사용하도록 만드는 경우) 위 문제에서 해소 될 수는 있다고 생각은 합니다. 다만, 객체의 생성 경로를 여러개 두는건 유지보수에 그렇게 좋지 못하다고 생각해요. 객체의 변경에 대해 확인해야하는 부분이 늘어나기 때문에요. 따라서 이전에 말씀드렸던거처럼 테스트를 위한 생성자를 따로 하나 더 두는건 최후의 수단으로 두고 테스트 데이터를 만들기 위한 편의 메서드, 팩토리를 둬야한다면 test SourceSet (src/test 하위) 에 정의해서 사용하는게 더 나은 방법이라고 생각합니다.

2022-11-09 13:31 UTC, merged

2022-11-11 14:19 UTC, gmelon commented
> 안녕하세요. 상혁님 :) 로또 미션 고생하셨습니다. 이만 머지해도 될 거 같네요 ㅎㅎㅎ 질문주신 부분에 대해서 답변드렸는데 한번 확인부탁드릴께요. 추가로 궁금하신 점 있으시면 머지 후라도 말씀주세요 ㅎㅎ 다음 과정도 화이팅 하시길 바랄께요 👍

네 감사합니다!!
답변 달아주신 내용은 다시 한 번 곰곰히 생각해보고 다음 미션에서 반영해보도록 하겠습니다.

고생 많으셨습니다~!