3단계 - 로또(2등)
next-step/java-lotto pull request #2791
Opened 2022-11-06 06:45 UTC by Hamstory

2022-11-06 10:51 UTC, seokhongkim requested changes
성한님, 3단계 미션 잘 구현해주셨습니다. 👍 
2단계에서 드린 코멘트도 잘 반영해주셨네요!

이번 단계에는 코멘트 드릴 내용이 많지 않아서 조금만 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-11-06 10:51 UTC, seokhongkim commented on src/main/java/lotto/WinningLotto.java
> +        if (uniqNumbers.size() != WINNING_LOTTO_NUMBER_COUNT){
`winningNumbers` 가 가지고 있는 제약 조건이 `LottoTicket` 의 제약조건과 동일할 것 같아요.
`LottoTicket` 을 이용해서 `winningNumbers` 도 관리해보면 어떨까요? 필요하시면 `LottoTicket` 의 이름도 한번 더 고민해보면 좋겠네요 :)

2022-11-06 10:51 UTC, seokhongkim commented on src/main/java/lotto/WinningLotto.java
> +public class WinningLotto {
보너스 번호 추가를 `WinningLotto` 객체만 추가해서 잘 동작하도록 구현해주셨네요. 👍 
클래스 이름과 역할 모두 잘 이해되네요!

2022-11-06 10:51 UTC, seokhongkim commented on src/main/java/lotto/WinningLotto.java
> +    public WinningLotto(int bonusNumber, int... winningNumbers) {
테스트만을 위한 생성자로 보이네요! 이 로직은 테스트에서 관리해보면 어떨까요?

2022-11-06 10:51 UTC, seokhongkim commented on src/main/java/lotto/LottoResult.java
> +    BONUS(5, 30000000),
미션 제목에 있듯이, 5개의 번호가 일치하고 보너스 번호가 맞는 경우가 로또에서는 2등 입니다. :)
`BONUS` 이하의 enum 이름을 하나씩 변경해보시면 좋겠습니다.

2022-11-06 10:51 UTC, seokhongkim commented on src/main/java/lotto/LottoResult.java
> +        if (matchingCount == 5 && bonus) {
enum 객체가 `matchingCount` 와 `bonus` 를 인자로 받아서 당첨 여부를 반환해주는 함수를 필드로 가지고 있으면, 객체를 좀 더 능동적으로 활용해볼 수 있을 것 같아요.

hint:
```java
enum class LottoResult {
  FIRST((matchingCount, bonus) -> matchingCount == 6, 2_000_000_000);

  private final BiFunction<Integer, Boolean, Boolean> match;
  private final int prize;

  public static LottoResult of(int matchingCount, boolean bonus) {
    return Arrays.stream(values())
      .filter(lottoResult -> lottoResult.match.apply(matchingCount, bonus)
      .findFirst()
      .orElse(NONE);
  } 
}
```

2022-11-06 10:51 UTC, seokhongkim commented on src/main/java/lotto/LottoTicket.java
> +        List<LottoNumber> candidates = new ArrayList<>(LottoNumber.selectableNumbers());
리팩토링 좋습니다. 👍

2022-11-06 14:48 UTC, Hamstory commented on src/main/java/lotto/WinningLotto.java
> +        if (uniqNumbers.size() != WINNING_LOTTO_NUMBER_COUNT){
리뷰 감사합니다 :) 
우선 제안주셨던 방법으로 수정했고, 다만 `LottoTicket` 네이밍은 저도 약간 고민이 되네요.
수업에서는 `Lotto`를 사용하는 것 같은데 (갠적으로) 두개가 큰 차이는 없어 보이고, `LottoNumbers`는 더 아닌것 같고.. 좋은 의견 주시면 반영해보겠습니다!

2022-11-07 03:26 UTC, seokhongkim approved these changes
성한님, 3단계 미션 코멘트 잘 반영해주셨습니다. 💯 
3단계 PR은 이만 머지하도록 하겠습니다.

코멘트 남긴 내용은 다음 단계 미션 진행하실 때 참고해보시면 도움이 될 것 같습니다.
4단계 미션에서 뵙겠습니다. 😀

2022-11-07 03:26 UTC, seokhongkim commented on src/test/java/lotto/LottoResultTest.java
> +    void test_bonus() {
테스트 메소드 이름도 함께 변경이 필요할 것 같아요!

2022-11-07 03:26 UTC, seokhongkim commented on src/main/java/lotto/WinningLotto.java
> +        if (uniqNumbers.size() != WINNING_LOTTO_NUMBER_COUNT){
`LottoNumbers` 도 괜찮은 것 같네요! :)
로또를 구매해보시면, 로또 한 장에 N개의 로또 번호 목록이 있습니다.
사용자가 구매한 로또(현재 `LottoRound`)를 `Lotto` 로 변경하고 `LottoNumbers` 를 가지고 있으면 제가 보기에는 자연스러워 보이네요. :)

2022-11-07 03:27 UTC, merged