4단계 - 로또(수동)
next-step/java-lotto pull request #2804
Opened 2022-11-09 16:04 UTC by Hamstory

2022-11-10 11:10 UTC, seokhongkim requested changes
성한님, 4단계 미션 잘 구현해주셨습니다. 👍 
일부 코드를 리팩토링하신 후, 수동으로 구매하는 로직을 위한 코드 변경은 많지 않았던 것 같네요.

코드를 보고 제가 고민했던 부분을 성한님께서도 고민해보시면 도움이 될 것 같아서 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-11-10 11:10 UTC, seokhongkim commented on src/main/java/lotto/Main.java
> +                () -> LottoNumbers.of(InputView.queryLottoNumbers()));
`Lotto` 도메인을 그대로 남겨놓고, 콘솔 -> 웹으로 프로그램을 전환한다고 할 때, `() -> LottoNumbers.of(InputView.queryLottoNumbers())` 를 사용하기는 어려울 것 같아요.
이 코드로 `Lotto` -> `InputView` 로의 직접적인 의존 관계는 숨겨졌지만, 사용 과정에서 의존 관계가 생기는 것으로 보입니다. 도메인을 UI에 의존하지 않도록 구조를 개선해보시면 좋을 것 같아요. 그래야 입/출력 방법이 변경될 때 도메인(`Lotto`) 코드를 그대로 사용할 수 있을 것 같네요!

2022-11-10 11:10 UTC, seokhongkim commented on src/main/java/lotto/Main.java
> +        InputView.printQueryWinningNumbersMessage();
외부에서 `InputView` 의 구현을 자세히 아는 코드가 된 것 같습니다.
기존에는 우승 번호를 가져올 때 `InputView.queryWinningNumbers()` 를 호출하면, 내부에서 알아서 사용자에게 적절한 메시지를 보여주고 값을 입력받았는데, 지금은 `InputView.printQueryWinningNumbersMessage()` 를 외부에서 반드시 호출해줘야만 하네요. ui 의 관심사는 `InputView` 가 알아서 처리하도록 구현해보시면 좋을 것 같아요.

2022-11-10 11:10 UTC, seokhongkim commented on src/main/java/lotto/WinningLotto.java
> +    private final LottoNumbers winningTicket;
`Ticket` 이름을 `Numbers` 로 변경했으니, 사용하는 곳의 이름도 맞춰서 변경해보시면 좋겠습니다. :)

2022-11-11 12:56 UTC, seokhongkim requested changes
성한님, 3단계 코멘트 잘 반영해주셨습니다. 💯 
어제 리뷰하면서 제가 놓친 부분이 하나 있어 코멘트를 추가로 남겼습니다. 😅 
로또 구매 금액과 수동 수량, 자동 수량 사이의 관계에 대한 부분입니다. 코멘트 내용 확인하신 후 반영 부탁드립니다. 🙏

2022-11-11 12:56 UTC, seokhongkim commented on src/main/java/lotto/Main.java
> +        List<LottoNumbers> lottoNumbers = InputView.queryManualLottoNumbers(manualCount).stream()
로또 구입 금액과 수동 구매 수량 사이의 밸리데이션과 자동 구매 수량을 계산하는 로직이 추가되어야 할 것 같네요.
1. 로또 구입 금액이 10,000원일 때 수동으로 구매하는 수량이 11장이면 예외가 발생해야 합니다. 현재는 구입 금액과 무관하게 수동으로 구매하는 수량을 결정할 수 있네요.
2. 자동으로 구매하는 수량은 구입 금액에서 수동 구매 수량을 구매한 후 남은 수량만큼 구매해야 합니다. 자동 구매 수량을 계산하는 로직이 추가되어야 할 것 같아요.

2022-11-11 15:08 UTC, Hamstory commented on src/main/java/lotto/Main.java
> +        List<LottoNumbers> lottoNumbers = InputView.queryManualLottoNumbers(manualCount).stream()
수정하였습니다 :)

2022-11-12 03:09 UTC, seokhongkim approved these changes
성한님, 4단계 미션 수동 구매 수량에 대한 밸리데이션까지 잘 구현해주셨습니다. 💯 
4단계 PR도 이만 머지하도록 하겠습니다.

이제 교육 기간 종료까지 얼마 남지 않았네요.
남은 기간도 힘내셔서 처음 목표하신 학습과 성장 모두 이루시길 응원하겠습니다. 💪

2022-11-12 03:09 UTC, seokhongkim commented on src/main/java/lotto/LottoStore.java
> +    public static List<LottoNumbers> purchaseAuto(int purchasePrice, int manualCount) {
금액, 수량에 대한 책임을 누가 담당할지 고민이 된다고 하셔서 제 생각 코멘트로 남겨봅니다. :)

먼저, 지금처럼 `LottoStore` 를 통해 관리하는 것도 방법이라고 생각합니다.
다만 전달되는 인자의 타입이 모두 int 이며, `manualCount` 가 `autoCount` 값만을 계산하기 위해 사용되므로 외부에서 계산해서 `자동 로또`를 구매하기 위한 수량만 전달해주는 것도 좋을 것 같아요. 이렇게 하려면 밸리데이션이 일부는 다른 클래스로 옮겨질 필요가 있겠네요.

저도 두 가지 방법을 고민해봤습니다.
1. `LottoPurchaseRequest` 클래스를 추가하고, 구매할 금액과 수동 수량, 수동 번호를 저장하도록 한다. 로또 구매를 위해 필요한 요청을 관리한다.
2. `LottoPurchaser` 클래스를 추가하고, 위의 요청을 포함하며 구매한 `Lotto` 도 함께 관리하도록 한다. 클래스의 이름을 봤을 때 `구매하는 사람` 이므로, `구매 요청` 보다는 더 많은 역할을 할 것으로 생각했습니다.

정답은 잘 모르겠네요. 😅 여러 방법을 고민해보며 더 이해하기 좋고, 변경하기 좋은 설계를 고민해보시면 도움이 될 것 같습니다.

2022-11-12 03:09 UTC, merged