Step2: 문자열덧셈계산기, 로또
next-step/java-lotto pull request #2842
Opened 2023-03-10 03:34 UTC by dh-son

문자열덧셈계산기 및 로또 리뷰 부탁 드립니다.

2023-03-11 11:51 UTC, shared-moon requested changes
대현님 안녕하세요 :)
1단계 미션 잘 진행 해 주셨네요!
코멘트를 좀 남겨 두었는데, 확인 후 다시 리뷰 요청 부탁드릴게요!
고생 많으셨습니다. 화이팅하세요 🔥

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
이 클래스는 Utility 클래스로 만들어봐도 좋을 것 같네요!

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +    public static void main(String[] args) {
main은 별도의 클래스에서 시작하는 게 어떨까요 ? `HitLotto`의 책임이 아닌데 코드가 섞여있어서 가독성이 떨어지는 것 같아요

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +    // 로또 구매 수
주석은 메서드 명 등으로 파악이 어려운 내용에 대해서만 적는 걸 추천드려요! 기본적으로는 주석 없이도 이해가 되도록 메서드명과 변수명을 짓고 잘 나누는걸 목표로 하는것이 좋습니다!

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +        LongStream.rangeClosed(1, purchaseCount)
LongStream도 마찬가지로 `mapToObj()`를 이용해 다른 타입의 객체로 이루어진 스트림을 반환할 수 있어 전체를 선언형으로 표현 할 수 있어요! 지금은 두가지 방식이 섞여있어서 조금 자연스럽지 못한 상태인 것 같네요 :)

추가로, LongStream으로 만들어진 숫자가 객체 생성에 전혀 쓰이고 있지 않은데, 개인적으로 이럴땐 그냥 반복문이 더 자연스럽지 않나 싶습니다!

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +        List<Integer> numbers = new ArrayList<>();
로또 번호 목록을 매번 새로 만들 필요가 있을까요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +        return Arrays.stream(winningNumbers.split(", "))
입력받은 번호가 로또 번호 범위 (1 ~ 45)를 벗어나면 어떻게 되나요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Level.java
> +    FIRST(6, 2000000000),
숫자는 3자리마다 _를 넣어보는게 어떨까요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Level.java
> +    public static Level valueOf(long value) {
value는 약간 범용적인 이름 같아요! `hitCount` 같은 이름은 어떨까요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Level.java
> +    FIFTH(2, 0),
2, 1, 0 은 그냥 낙첨으로 퉁 쳐도 되지 않을까요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Level.java
> +    BONUS(7, 30000000);
오? 보너스는 왜 7이죠?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/LottoNumber.java
> +    public String printNumber() {
`toString()`을 오버라이딩 하는건 어떨까요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/LottoNumber.java
> +        for (Integer number : numbers) {
String으로 변환 후 `Collectors.joining()`을 사용하시면 선언형으로 표현할 수 있을 것 같아요! 그리고 반복문 내에서 String concat 연산은 좋지 않은 코드로 분류됩니다. [이 블로그 글](https://dkswnkk.tistory.com/584) 참고해보시면 좋을 것 같아요!

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/LottoNumber.java
> +    public void setLevel(Level level) {
Level을 LottoNumber가 상태로 가지고 있어야 할까요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Level.java
> +public enum Level {
Enum 사용 좋습니다!

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Lotto.java
> +    public List<LottoNumber> getLottoNumbers() {
안쓰이는 메서드같아요!

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Lotto.java
> +                .forEach(it -> System.out.println(it.printNumber()));
컬렉션에서는 스트림을 안열어도 `forEach()`를 사용할 수 있어요!

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Lotto.java
> +    public void printToLotto() {
이것도 toString을 오버라이딩 해보는 건 어떨까요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +        return Arrays.stream(winningNumbers.split(", "))
동일한 번호가 입력됐을 경우는 어떻게 되나요 ?

2023-03-11 11:51 UTC, shared-moon commented on src/main/java/lotto/model/Lotto.java
> +                .filter(it -> it.getLevel().equals(Level.SECOND) && it.getNumbers().contains(bonusNumber))
아 Level의 이름이 등수가 아니라 그냥 숫자를 의미하는거였군요 ..?

2023-03-12 08:41 UTC, dh-son commented on src/main/java/lotto/view/InputView.java
> +    public long PurchaseAmount() {
수정 완료했습니다.

2023-03-12 13:10 UTC, dh-son commented on src/main/java/stringCalculator/StringCalculator.java
> +    public int add(final String text) {
별도의 sum method가 있어서 add로 이름 지었습니다.

2023-03-12 13:10 UTC, dh-son commented on src/main/java/stringCalculator/StringCalculator.java
> +        Matcher matcher = Pattern.compile("//(.)\n(.*)").matcher(text);
수정 완료했습니다.

2023-03-12 13:10 UTC, dh-son commented on src/main/java/stringCalculator/StringCalculator.java
> +            throw new RuntimeException();
수정 완료했습니다.

2023-03-12 13:10 UTC, dh-son commented on src/main/java/stringCalculator/StringCalculator.java
> +                .map(this::parsePositiveNumber)
수정 완료했습니다.

2023-03-12 13:11 UTC, dh-son commented on src/main/java/stringCalculator/StringCalculator.java
> +        if (Integer.parseInt(text) >= 0) {
수정 완료했습니다.

2023-03-12 13:12 UTC, dh-son commented on src/test/java/stringCalculator/StringCalculatorTest.java
> +    @ParameterizedTest
NullAndEmptySource 사용하기 위해 ParameterizedTest를 사용했습니다.

2023-03-12 13:12 UTC, dh-son commented on src/main/java/lotto/view/InputView.java
> +        Scanner scanner = new Scanner(System.in);
수정 완료했습니다.

2023-03-12 13:19 UTC, dh-son commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
수정 완료했습니다.

2023-03-12 13:19 UTC, dh-son commented on src/main/java/lotto/HitLotto.java
> +    public static void main(String[] args) {
수정 완료했습니다.

2023-03-12 13:19 UTC, dh-son commented on src/main/java/lotto/HitLotto.java
> +    // 로또 구매 수
네 알겠습니다.

2023-03-12 13:21 UTC, dh-son commented on src/main/java/lotto/HitLotto.java
> +        LongStream.rangeClosed(1, purchaseCount)
제안 해주신 대로 반복문을 쓰면 더 자연스러울 것입니다. 그러나 이번 교육에서는 개인적으로 반복문을 자제해보려고 합니다.

2023-03-12 13:22 UTC, dh-son commented on src/main/java/lotto/HitLotto.java
> +        List<Integer> numbers = new ArrayList<>();
번호 목록을 새롭게 만들지 않으면 기존에 생성된 번호들이 마지막 번호로 변경됩니다. (메모리 참조) 혹시 좋은 구현 방법 있으면 예시 부탁 드립니다.

2023-03-12 14:50 UTC, dh-son commented on src/main/java/lotto/HitLotto.java
> +        return Arrays.stream(winningNumbers.split(", "))
수정 완료했습니다.

2023-03-12 14:51 UTC, dh-son commented on src/main/java/lotto/model/Level.java
> +    FIRST(6, 2000000000),
제안 해주신 방법도 괜찮지만, 수익률 계산을 위한 값이므로 string이 아닌 long 타입으로 정의했으면 합니다.

2023-03-12 14:52 UTC, dh-son commented on src/main/java/lotto/model/Level.java
> +    public static Level valueOf(long value) {
수정 완료했습니다.

2023-03-12 14:53 UTC, dh-son commented on src/main/java/lotto/model/Level.java
> +    FIFTH(2, 0),
당첨 개수 카운트 의미입니다.

2023-03-12 14:54 UTC, dh-son commented on src/main/java/lotto/model/Level.java
> +    BONUS(7, 30000000);
Level의 value는 당첨 구분을 위한 값으로 정의했습니다. 그래서 보너스는 별도로 7로 구분했습니다.

2023-03-12 15:10 UTC, dh-son commented on src/main/java/lotto/model/LottoNumber.java
> +        for (Integer number : numbers) {
수정 완료했습니다.

2023-03-12 15:11 UTC, dh-son commented on src/main/java/lotto/model/LottoNumber.java
> +    public void setLevel(Level level) {
로또 별로 당첨 내역을 확인 할 수 있도록 Level 상태를 추가했습니다.

2023-03-12 15:12 UTC, dh-son commented on src/main/java/lotto/model/Lotto.java
> +    public List<LottoNumber> getLottoNumbers() {
수정 완료했습니다.

2023-03-12 15:12 UTC, dh-son commented on src/main/java/lotto/model/Lotto.java
> +                .forEach(it -> System.out.println(it.printNumber()));
수정 완료했습니다.

2023-03-12 15:14 UTC, dh-son commented on src/main/java/lotto/model/Lotto.java
> +    public void printToLotto() {
수정 완료했습니다.

2023-03-12 15:23 UTC, dh-son commented on src/main/java/lotto/model/Lotto.java
> +                .filter(it -> it.getLevel().equals(Level.SECOND) && it.getNumbers().contains(bonusNumber))
네, 당첨 구분 값입니다.

2023-03-12 15:28 UTC, dh-son commented on src/main/java/lotto/HitLotto.java
> +        return Arrays.stream(winningNumbers.split(", "))
수정 완료했습니다.

2023-03-13 01:53 UTC, shared-moon commented on src/main/java/stringCalculator/StringCalculator.java
> +    public int add(final String text) {
매개변수가 달라서 괜찮지 않을까 싶었습니다! 꼭 바꿔야되는 부분이 아니니 대현님 취향대로 하셔도 될 것 같아요 :)

2023-03-13 01:56 UTC, shared-moon commented on src/main/java/lotto/model/Lotto.java
> +    public void printToLotto() {
약간 정보를 출력하는 느낌이어서, Lotto가 책임지기에 적합한 기능일까 싶긴 하네요! 여기서 짚었던 부분은 `내가 직접 정보를 출력` 하느냐, `출력 할 정보를 전달`하느냐 였는데요!

>핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.

이 관점에서 이 부분도 한번 다시 생각해 보면 좋을 것 같습니다!

2023-03-13 02:18 UTC, shared-moon approved these changes
대현님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
코멘트를 몇 개 남겨 두었는데, 확인 후 다음 미션 진행 부탁드려요!
고생 많으셨습니다 👍

2023-03-13 02:18 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +        List<Integer> winningNumber = Arrays.stream(winningNumbers.split(", "))
요거 `1,2,3,4` 처럼 입력하면 깨지겠네요! `,`로 split 하고 따로 `trim()`으로 공백제거를 해주는 건 어떨까요 ?

2023-03-13 02:18 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +                throw new IllegalArgumentException("1 ~ 45 만 입력 가능");
👍

2023-03-13 02:18 UTC, shared-moon commented on src/main/java/lotto/HitLotto.java
> +//        LongStream.rangeClosed(1, purchaseCount)
안쓰는 코드는 지워주세요!

2023-03-13 02:18 UTC, shared-moon commented on src/main/java/lotto/model/Lotto.java
> +        lottoNumbers.forEach(it -> it.setLevel(Level.hitCount(getHitCount(it, winningNumbers, bonusNumber))));
👍

2023-03-13 02:18 UTC, shared-moon commented on src/main/java/stringCalculator/StringCalculator.java
> +        Matcher matcher = Pattern.compile(REGULAR_EXPRESSION).matcher(text);
👍

2023-03-13 02:18 UTC, shared-moon commented on src/main/java/stringCalculator/StringCalculator.java
> +                .mapToInt(this::parsePositiveNumber)
👍

2023-03-13 02:18 UTC, shared-moon commented on src/main/java/stringCalculator/StringCalculator.java
> +            throw new RuntimeException("양수만 입력 가능");
메세지 입력 좋습니다! 하지만 `RuntimeException`은 너무 상위의 예외라 IllegalArgumentException이나 커스텀 예외를 작성하는게 좀 더 좋을 것 같아요 :)

2023-03-13 02:18 UTC, merged