Auto lotto
next-step/java-lotto pull request #2853
Opened 2023-03-13 11:40 UTC by givxq

로또 자동생성기

2023-03-14 09:29 UTC, heowc requested changes
안녕하세요~ 리뷰어를 맡은 허원철입니다
리뷰가 다소 늦어진 점 죄송합니다. 😢 

원시값 포장, 객체 분리 등등 잘해주신 것 같아요~
다만, 약간의 아쉬움이 있어 이를 확인하고자 코멘트 드렸습니다. 🙏 

궁금하신 점이나 의논할 것이 있다면 깃헙 코멘트나 슬랙 DM 으로 연락주세요

2023-03-14 09:29 UTC, heowc commented on src/main/java/domain/Lotto.java
> +    public boolean isHaveBonusNumer(FirstPlaceLotto firstPlaceLotto) {
```suggestion
    public boolean hasBonusNumber(FirstPlaceLotto firstPlaceLotto) {
```
은 어떨까요? 🤔

2023-03-14 09:29 UTC, heowc commented on src/main/java/domain/LottoNumber.java
> +    private int number;
원시값 포장 잘 해주셨습니다 👍 

다만, 여기서 조금 더 개선 해보면 좋을 것 같아 코멘트 드려요~
위 코드처럼 `LottoNumber`는 1~45까지의 숫자로 이루어져 있기 때문에 동일한 숫자라면 불필요하게 여러 번 생성되는 것 보다는 이를 캐싱해둔다면 나름의 효과를 얻을 수 있을 것 같습니다.

자바에서도 이처럼 사용하는 부분이 있는데요.
- `Integer`/`IntegerCache`
- https://jwdeveloper.tistory.com/140

이를 참고하시어 개선해보는 건 어떨까요?

2023-03-14 09:29 UTC, heowc commented on src/main/java/domain/LottoNumbers.java
> +    }
로또 번호 생성기와 로또 번호가 강하게 결합되어 있는 것 같아요~
이를 분리하거나 자동/수동의 의미를 담을 수 있는 정적 팩토리 메소드를 만들어 보는건 어떨까요?
- https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2023-03-14 09:29 UTC, heowc commented on src/main/java/domain/LottoUtil.java
> +public class LottoUtil {
유틸 클래스라면 생성이 필요하지 않으므로 이를 막아보는건 어떨까요?
- https://camel-context.tistory.com/37

2023-03-14 09:29 UTC, heowc commented on src/main/java/domain/LottoUtil.java
> +            e.printStackTrace();
`e.printStackTrace();`를 사용하신 이유가 있을까요? 🤔

2023-03-14 09:29 UTC, heowc commented on src/main/java/domain/type/LottoRankResult.java
> +public enum LottoRankResult {
enum 활용 잘 해주셨습니다 👍

2023-03-14 09:29 UTC, heowc commented on src/main/java/view/InputView.java
> +    }
이것은 InputView가 아닌 ResultView이지 않을까 싶은데요~ 어떻게 생각하시나요? 🤔

2023-03-14 09:29 UTC, heowc commented on src/test/java/domain/LottoGeneratorTest.java
> +    void generateLottoNumbersTDD() {
어떤 것을 테스트하고자 함인지 알 수 있을까요? 🤔 

1) `LottoNumberGenerator`는 정적 메소드만 존재하기 때문에 굳이 생성할 필요가 없어보여요
2) 테스트 작성시 출력에 의존하기 보다는 `assertThat` 과 같은 검증 메소드를 활용해보는 건 어떨까요? 
    - 다른 테스트 코드도 한번 확인 부탁드릴게요 👍

2023-03-15 01:46 UTC, givxq commented on src/main/java/domain/LottoUtil.java
> +public class LottoUtil {
private 생성자와 예외처리로 수정하였습니다.

2023-03-15 02:08 UTC, givxq commented on src/main/java/domain/LottoUtil.java
> +            e.printStackTrace();
디버그하려고 추가했었는데 성능이슈도 있다보니 삭제 하겠습니다.

2023-03-15 04:18 UTC, givxq commented on src/main/java/domain/Lotto.java
> +    }
LottoRankResult를 반환하게 구현한다면
Lotto 외부에서 객체를 핸들링 하게 될 것 같습니다.

해당 방식으로 구현하는것도 고민하였으나 
LottoRankResult는 각 Lotto의 결과이고, 결국 Lotto에 종속된 값이라고 생각이 들었습니다.

도메인 설계적인 관점에서 Lotto에서 반환하고 외부에서 핸들링 하는것보다는 
Lotto 도메인이 핸들링하는게 맞다는 생각이 들다보니 이렇게 구현하게 되었네요.

2023-03-15 04:31 UTC, givxq commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(17)
hamcrest는 아시겠지만 test코드를 좀 더 명시적으로 사용하기 위해 추가했습니다.

자바 17 부터 stream 에 toList 가 추가되어 collection을 사용하지 않아도 되는 장점이 있구요.
제 개발환경이 윈도우,맥,리눅스 여러 환경에서 자바 17로 개발을 하고 있다보니 기존 사용하는 gradle을 사용하려고 버전을 수정했습니다.

버전을 올려도 과제에는 영향이 없을 것 같습니다.

2023-03-15 09:26 UTC, heowc commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(17)
넵 :) 인지하고 리뷰하도록 하겠습니다 👍

2023-03-16 03:22 UTC, givxq commented on src/main/java/domain/Lotto.java
> +public class Lotto {
🙌

2023-03-16 04:06 UTC, givxq commented on src/main/java/domain/LottoNumbers.java
> +    }
좋은 의견 감사합니다.
로또 번호 생성기는 로또 번호 내부로직을 캡슐화하여 만든 객체이기때문에 결합도가 강한건 의도한 바입니다.

팩토리 메소드는 좋은 방법인듯합니다.
로또 번호, 로또 번호 생성기 모두 생성자를 사용하지 않고 정적 팩토리 메소드로 사용하게끔 수정했습니다.

2023-03-16 12:52 UTC, givxq commented on src/test/java/domain/LottoGeneratorTest.java
> +    void generateLottoNumbersTDD() {
TDD 함수는 실제 코드를 작성하기전, 구현할 기능에 대해 의도한 결과를 출력하는지 테스트용으로 작성하였습니다.
detail한 요건을 구현하기전 단순하고 빠르게 구현값을 확인하기 위해 출력문을 이용하였습니다.
구현 후에 테스트를 하면서 요건들을 assert 와 같은 검증 메소드를 추가하려 했는데 깜빡했네요.
추가해놓겠습니다.

2023-03-16 13:45 UTC, givxq commented on src/main/java/view/InputView.java
> +    }
네 말씀하신 내용이 맞는것 같습니다. 수정했습니다

2023-03-16 14:38 UTC, givxq commented on src/main/java/domain/LottoNumber.java
> +    private int number;
말씀해주신 내용 참고하여 cache 형태로 구현하였습니다.

2023-03-17 01:45 UTC, heowc approved these changes
세세하게 보시고 피드백을 반영해주셔서 감사합니다 👍 

다음 단계을 진행하기에 충분하여 이만 머지하도록 하겠습니다.
다만 아직 resolve 되지 않은 코멘트 or 추가된 코멘트를 확인해보시고
다음 단계에 반영해주시거나 코멘트 달아주면 좋을 것 같아요~ 

궁금하신 점이나 의논할 것이 있다면 깃헙 코멘트나 슬랙 DM 으로 연락주세요 🙏

2023-03-17 01:45 UTC, heowc commented on src/main/java/domain/LottoNumber.java
> +    private static final List<LottoNumber> CACHE = new ArrayList<>();
👍

2023-03-17 01:45 UTC, heowc commented on src/main/java/domain/type/LottoPrice.java
> +public enum LottoPrice {
여기서 enum을 활용하신 이유가 무엇일까요? 🤔

2023-03-17 01:45 UTC, heowc commented on src/test/java/domain/LottoTest.java
> +    void calculateLottoRankTest() {
이것 이외에도 출력에만 의존되는 코드가 보이는 것 같아요~
테스트를 잘 작성해주셔서 읽기는 쉬웠지만 `assertThat`으로 결과를 검증해주면 더욱 좋을 것 같습니다 👍

2023-03-17 01:45 UTC, merged

2023-03-17 01:53 UTC, heowc commented on src/test/java/domain/LottoGeneratorTest.java
> +    void generateLottoNumbersTDD() {
테스트는 의도한 결과가 정상적으로 도출되었는지를 검증하기 위함인데요. 
테스트에 결과를 만들기 위한 코드가 담아져 있는걸로 보여서요~

어떤 의도였는지는 알 것 같습니다 👍 
확인 감사합니다 👍