문자열 계산기 및 로또 Step1
next-step/java-lotto pull request #2857
Opened 2023-03-14 15:13 UTC by rheehyerin

2023-03-15 00:10 UTC, wooobo requested changes
안녕하세요 혜린님!
이번미션 함께하게되어 반갑습니다! 😄 

몇가지 코멘트 남겨드렸는데 확인 후 재요청 부탁드려요~ 🙏 
궁금한점이 있으시다면, DM 이나 코멘트를 통해 이야기 해보아요! 👍

2023-03-15 00:10 UTC, wooobo commented on src/test/java/lotto/LottoTest.java
> +        int[] sample = IntStream.rangeClosed(1, 45).toArray();
### 범위 관련코드
- `45` 관련 => `private static final int LOTTERY_LIMIT = 45;`
- `1` 관련 => `private static final List<Integer> lotteryRange = IntStream.rangeClosed(1, LOTTERY_LIMIT)... `
- 테스트 코드 =>  `int[] sample = IntStream.rangeClosed(1, 45).toArray();` 

범위 관련코드가 다소 흩어져 있는것 같아요.

프로덕션코드에서 `1~45`의 범위의 정의가 다른방식으로 되어있고(`45`는 상수 `1`은 바로 선언)
테스트 코드에서도 따로 정의되어 있습니다.

그렇다면, 범위가 수정될 때 각각의 위치를 찾아서 수정해줘야하는 어려움이 있습니다.
그리고, 관련된 개념들이 어디서 흩어져있는지 알아차리게 힘들어질 수 있습니다.

좀 더 유지보수성을 좋게하고, 일관성을 유지하기 위해 고민해보면 좋을듯해요! 🙏

2023-03-15 00:10 UTC, wooobo commented on src/main/java/casino/Casino.java
> +    public Lotto buyLottery2() {
`buyLottery2` 메소드에 숫자를 붙이는것보다, 의미를 분명하게 하는 네이밍을 짓는게 더 좋다고봐요!

---

생성자를 다양하게 가지고 싶을땐, [정적 팩토리 메서드(Static Factory Method)는 왜 사용할까?](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)을 활용해보아요~

2023-03-19 14:12 UTC, wooobo requested changes
안녕하세요! 혜린님!

몇가지 추가 코멘트 남겨 놓았습니다 🙏 

확인 후 재요청 부탁드려요~

2023-03-19 14:12 UTC, wooobo commented on src/test/java/lotto/LottoTest.java
> +        Lotto lotto = LottoFactory.auto();
개인적인 생각으론, 주 테스트 메소드가 `LottoFactory.auto`라고 생각되어요.
그렇다면, `LottoFactoryTest`에 있는게 더 적합 할 것 같기도 하네요 🤔 

`"발급된 로또 번호는 1~45 사이의 값 중 6개 이다."` 에 대한 테스트라면,

```
List<LottoNumber> numbers = ...;
Lotto actual = new Lotto(numbers);
```

**직접** `Lotto` 생성자를 테스트 하거나, `Lotto`가 가진 메소드를 테스트하는게 더 좋을것 같습니다 🤔

2023-03-19 14:12 UTC, wooobo commented on src/test/java/lotto/LottoTest.java
> +    void 이등() {
작성된 테스트 코드는 모두 정상작동되어야 합니다.
해당 테스트 실패되어지는데 확인부탁드립니다. 🙏 

(제 PC 환경에서만 실패되는것일 수도 있습니다. )

2023-03-21 13:09 UTC, rheehyerin commented
안녕하세요 태화님 !
꼼꼼하고 좋은 리뷰 너무 감사합니다
리뷰 주신 내용으로 리팩토링을 하다 보니 수동 로또까지 손을 대 버렸는데요
제가 너무 성급하게 수동 로또까지 했다면 이번 부분은 짧은 리뷰로 응답해주시고 수동 로또 부분은 다음 Step2 에서 부탁드리게습니다!
리뷰로 주신 의견 열심히 반영해보았습니다 잘 부탁드립니다!

2023-03-21 14:54 UTC, wooobo approved these changes
안녕하세요 혜린님!

1단계 잘 진행해주셨습니다!
개인적인 관점 코멘트 남겨 드렸습니다.
다음 단계 진행전에 참고해주세요~! 😄 

2단계도 기대하겠습니다 ^^
화이팅! 💯 💯

2023-03-21 14:54 UTC, wooobo commented on src/main/java/view/ResultView.java
> +        System.out.println("6개 일치 (2000000000원) - "+winners[0]+"개");
`winners`의 
4번째 인덱스가 3개일치이고 그것이 5000원인지,
3번째 인덱스가 4개 일치이고 그것이 50000원인지
이러한 규칙을 견고하게 유지될수 있다고 보장 할 수 있을지 의문이에요 🤔 

만약 단순한 자료구조인 `int[] winners` 순서가 바뀌면 사용자가 보는 프론트단에서 정보를 잘못 표시되기 너무나도 쉬운 형태입니다. 

이렇게 생각 할 수도있겠죠, "그건 개발하면서 같이 수정하면 되는것이 아닌가?" 라구요.
프로젝트가 점점 방대해지고, 복잡해지는 상황에서 엔드 포인트를 어디까지 유지보수영역을 넣어야 할까요? 
결국 하나를 수정하기 위해 프로젝트 전체영역을 신경써야하는 상황이 벌어질수 있습니다.

이는, 비지니스적으로 치명적인 이슈로 다가 올 수 있고, 유지보수 비용을 기하급수적으로 증가시킬수 있다고 생각합니다 😢

2023-03-21 14:54 UTC, wooobo commented on src/test/java/lotto/LottoFactoryTest.java
> +        assertThat(lottoNumber.size()).isEqualTo(6);
```suggestion
        assertThat(lottoNumber.size()).isNotZero();
        혹은
        assertThat(lottoNumber.size()).isEqualTo(LottoFactory.LOTTO_SIZE);
```

`private static final int LOTTO_SIZE = 6;` 
코드 처럼 `private`으로 설정 해주셨습니다.
그렇다는것은 외부에서 알지 않아야 한다고 규정해 놓은것이라 저는 생각했어요! 🤔 

그런데 외부에서 `.isEqualTo(6);` 이라는 조건을 검증하고 있어요.
이는 외부에서 과도하게 정보를 알려고 `예측` 하는것 아닐까요? 🤔 
만약, `6`에 대한 조건이 변경되는 상황에서 예측못하는 부분에서 에러가 발생할 수 있구요. 😢 

꼭 테스트 하려면 외부에서도 알수 있도록 `public`으로 오픈시키는게 좋을것 같기도 하네요. (개인적인 관점입니다)

2023-03-21 14:54 UTC, wooobo commented on src/main/java/exception/LottoException.java
> +        if (numbers.getLottoNumbers().size() != numbers.getLottoNumbers().stream().distinct().count()) {
<img width="1212" alt="스크린샷 2023-03-21 오후 11 40 56" src="https://user-images.githubusercontent.com/12059592/226641603-9893ea69-a77f-4101-ac11-03683a1d230c.png">

[[객체지향 생활체조 원칙] 규칙 4. 한 줄에 점을 하나만 찍는다](https://limdingdong.tistory.com/10)

2023-03-21 14:54 UTC, wooobo commented on src/main/java/Order/LottoOrder.java
> +    public LottoOrder(int money, int manualTicketCounts) {
`합성` 보다 `상속`으로 구현하신 이유가 궁금해요! 🤔 
개인적으론 합성이 더 적합하기도 하고 쉽지 않을까 생각이 되어서요!

[[OOP] 코드의 재사용, 상속(Inheritance)보다 합성(Composition)을 사용해야 하는 이유](https://mangkyu.tistory.com/199)
```suggestion
    public LottoOrder(Money money, int manualTicketCounts) {
```

2023-03-21 14:54 UTC, merged

2023-04-09 06:16 UTC, rheehyerin commented on src/main/java/exception/LottoException.java
> +        if (numbers.getLottoNumbers().size() != numbers.getLottoNumbers().stream().distinct().count()) {
감사합니다 처음에는 능동적인 객체가 어떤 것인지 알쏭달쏭했지만 이번 설명으로 조금 더 이해할 수 있게 되었습니다!
감사합니다!