Step2 수동로또구현
next-step/java-lotto pull request #2862
Opened 2023-03-18 13:57 UTC by jh35jh

2023-03-19 13:47 UTC, shared-moon requested changes
정현님 안녕하세요!
2단계 미션 잘 진행 해 주셨네요 :)
수동 추가 내용은 간단하게 잘 적용해 주셨는데, 요구사항에 안 맞는 부분이 있어보여서 리뷰 요청 다시 부탁드려요!
추가로, `Lottos`에 대한 테스트 작성 및 안쓰는 import나 메서드 제거도 같이 부탁드릴게요 :)

2023-03-19 13:47 UTC, shared-moon commented on src/main/java/Lotto/InputView.java
> +        return Arrays.stream(manuelLottoNumbers.split(","))
구분자는 상수로 빼는게 어떨까요 ?

2023-03-19 13:47 UTC, shared-moon commented on src/main/java/Lotto/InputView.java
> +                .map(Integer::parseInt)
parse 전에 `trim()` 으로 공백을 제거해보는 건 어떨까요 ?

2023-03-19 13:47 UTC, shared-moon commented on src/main/java/Lotto/Lottos.java
> +        InputView inputView = new InputView();
`핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.`
이 요구사항이 잘 지켜지지 않은 것 같아요!
로직을 분리하려면 어떻게 해야 할까요 ?

2023-03-19 13:47 UTC, shared-moon commented on src/main/java/Lotto/Lottos.java
>      public List<Lotto> buyLottos(java.math.BigDecimal buyAmt) {
`java.math`는 굳이 안붙여도 될 것 같아요 ?

2023-03-21 14:09 UTC, jh35jh commented on src/main/java/Lotto/InputView.java
> +        return Arrays.stream(manuelLottoNumbers.split(","))
적용하였습니다. 감사합니다!

2023-03-21 14:09 UTC, jh35jh commented on src/main/java/Lotto/Lottos.java
>      public List<Lotto> buyLottos(java.math.BigDecimal buyAmt) {
적용하였습니다. 감사합니다!

2023-03-22 13:14 UTC, shared-moon requested changes
정현님 안녕하세요!
피드백 반영 잘 진행 해 주셨는데요! 마지막 미션이라 한가지 짚고 넘어가면 좋을 것 같아서 다시 한번 리뷰 요청 부탁드립니다!
내용은 코멘트에 남겨 두었어요!
추가로 질문이 있으시면 언제든 DM 주시기 바랍니다!
화이팅 하세요 🔥

2023-03-22 13:14 UTC, shared-moon commented on src/main/java/Lotto/Lotto.java
> +    public static Lotto setLotto(List<Integer> lottoNumber){
이건 제 추측인데, ui 부분을 분리 한다는게 잘 와닿지 않으신 것 같아요!
아마 분리를 하더라도 어디선가는 ui와 비즈니스 로직을 같이 의존해야 서비스를 구현 할 텐데 이걸 어디서 책임지는게 맞을지를 고민하시지 않았나 싶습니다!

분리를 한다는 건, 상호 의존성을 제거한다는 말과 같습니다. 이 말은, 비즈니스 로직과 ui는 서로가 있는지조차 몰라도 각각이 개별적으로는 정상적으로 동작을 할 수 있게 한다는 뜻이에요.

지금같은 경우는 Lotto에서 inputView를 의존하고 있기 때문에 inputView가 사라지거나, 혹은 다른 녀석으로 대체가 되는 경우 Lotto에서 변경이 이루어져야 하는데요, 이를 결합도가 높다고 얘기하고 SOLID원칙에서 `개방폐쇄 원칙`이 지켜지지 않았다고 볼 수 있습니다.

현재는 패키지가 잘 분리되어 있지 않은데요, Lotto 관련된 내용이 들어갈 패키지와 io 역할을 하는 클래스들을 넣을 패키지를 따로 정의하시고 그 두 패키지에 의존성을 가진 (LottoMain이 가장 유력할 것 같네요) 클래스를 통해 서비스를 할 수 있도록 설계 해 보시는 게 좋을 것 같아요!

2023-03-22 13:14 UTC, shared-moon commented on src/main/java/Lotto/Lotto.java
> +    public static Lotto setLotto(List<Integer> lottoNumber){
추가로 의문이 있으시면 언제든 DM으로 문의 주세요 :)

2023-03-24 08:16 UTC, shared-moon approved these changes
정현님 안녕하세요!
피드백 잘 반영 해 주셨네요 :)
제 리뷰는 여기서 마무리 하도록 하겠습니다! 코멘트를 몇 개 남겨 두었는데 확인 부탁드릴게요 :)
나머지 미션도 화이팅 하시기 바랍니다! 고생 많으셨어요 👍

2023-03-24 08:16 UTC, shared-moon commented on src/main/java/Lotto/InputView.java
> +//        return ;
안쓰는 코드는 제거해주세요!

2023-03-24 08:16 UTC, shared-moon commented on src/main/java/Lotto/Lottos.java
> +        List<Lotto> lottoList = lottoForm.getManualLottosNumber().stream()
스트림 전문가가 되셨군요 ..! 👍

2023-03-24 08:16 UTC, shared-moon commented on src/main/java/Lotto/Lottos.java
> +                .map(it -> Lotto.createManualLotto(it))
요거는 메서드 레퍼런스도 가능해보입니다!
`Lotto::createManualLotto`요렇게요!

2023-03-24 08:16 UTC, shared-moon commented on src/main/java/Lotto/Lottos.java
> +                .map(it -> Arrays.stream(it.split(SPLIT_CHAR))
이런식의 처리도 좋긴 한데, 안쪽 Stream 연산은 별도의 메서드로 빼면 더 보기 좋을 것 같아요! 스트림 연산은 선언형 프로그래밍을 표방하는데, 선언형에서는 `어떻게` 보단 `무엇을` 하는지에 초점을 맞춰야 가독성이 좋아지거든요!

2023-03-24 08:16 UTC, merged