[Step3][feature] 로또(2등) 생성
next-step/java-lotto pull request #2964
Opened 2023-04-25 12:15 UTC by yong-kwon

https://github.com/next-step/java-lotto/pull/2936 
 먼저 리뷰 부탁드립니다

👍

2023-04-28 05:23 UTC, younlll requested changes
안녕하세요.
로또 미션 3단계 구현하시느라 고생 많으셨습니다.
몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다.
확인 후 다시 리뷰요청 부탁드립니다!

2023-04-28 05:23 UTC, younlll commented on README.md
> +* Rank : enum, 일치 개수와 보너스 일치 여부에 따른 상금, 등수를 가짐
기능 구현 목록 정리 👍

2023-04-28 05:23 UTC, younlll commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
유틸리티 클래스로 보이는데 인스턴스화 방지를 해보는건 어떨까요?
https://suintodev.tistory.com/35?category=1043045

2023-04-28 05:23 UTC, younlll commented on src/test/java/lotto/LottoNumbersTest.java
> +                )
반복적으로 생성되는 부분을 Method로 분리해서 테스트 할 수 있을 것 같습니다.

2023-04-28 05:23 UTC, younlll commented on src/main/java/lotto/view/InputView.java
> +        String[] split = SCANNER.next().split(",");
지난주 당첨번호를 중복 입력해도 로또가 진행이 되고 있습니다.

2023-04-28 05:23 UTC, younlll commented on src/main/java/lotto/domain/LottoNumber.java
> +        return number == that.number;
eqauls를 override한만큼 활용해서 사용해보시면 좋을 것 같습니다.

2023-04-28 05:23 UTC, younlll commented on src/main/java/lotto/domain/enums/Rank.java
> +    }
- 반복문 또는 조건문을 중첩으로 사용하게 되면 indent가 2가 되는데요... 😥
이번 미션에서 경험하는 객체지향 생활 체조 원칙은
    
    ```
    규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.
    규칙 2: else 예약어를 쓰지 않는다.
    
    ```
    
    입니다.
    
    규칙1을 따라 한 단계의 들여쓰기만 되도록(즉, 한번의 반복문 혹은 조건문만 사용되고 중첩은 되지 않도록 연습해보는 것도 좋을 것 같습니다~ 🙂

2023-04-29 04:42 UTC, yong-kwon commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
@younlll 좋습니다 👍

2023-04-29 05:07 UTC, yong-kwon commented on src/main/java/lotto/view/InputView.java
> +        String[] split = SCANNER.next().split(",");
@younlll 

생성자 코드를 통해서, 진행이 정상적으로 되지 않도록 수정할게요 👍

2023-04-29 05:08 UTC, yong-kwon commented on src/main/java/lotto/domain/LottoNumber.java
> +        return number == that.number;
@younlll 
활용해서 사용해보라는 의미가 어떤 목적인지 궁금합니다.
여러 코드들에 걸쳐서 실제로 사용되고 있어서 문의드리게 됐습니다 :)

2023-04-29 05:10 UTC, yong-kwon commented on src/main/java/lotto/domain/enums/Rank.java
> +    }
@younlll 

넵 수정해둘게요 감사합니다 :)
하나 궁금한점이, for문이랑 if문만 썼을 때는 각 반복문, 중첩문의 indent가 1인지, 2인지가 궁금합니다.

2023-04-29 05:37 UTC, yong-kwon commented on src/test/java/lotto/LottoNumbersTest.java
> +                )
@younlll  👍

2023-04-29 05:46 UTC, yong-kwon commented on src/main/java/lotto/domain/LottoNumber.java
> +        return number == that.number;
@younlll 

isEquql와 중복 구현이 됐군요 감사합니다 👍

2023-05-05 06:07 UTC, younlll commented on src/main/java/lotto/domain/enums/Rank.java
> +    }
메서드 안에 반복문 혹은 조건문이 한 번 사용되면 indent 1입니다.
반복문 안에 반복문 혹은 조건문이 사용되어서 중첩이 되면 indent2가 됩니다!

2023-05-05 06:07 UTC, merged