Step2
next-step/java-lotto pull request #2972
Opened 2023-04-26 09:10 UTC by garden-2

step1 피드백 반영과 step2 구현 입니다.
util class 만드는건 별로 선호하는 방법이 아니어서 parser 는 그대로 두었습니다.

2023-04-27 11:03 UTC, lxxjn0 requested changes
미션 구현하시느라 수고하셨습니다!!

로또 미션도 생각보다 고민할 만한 부분이 많았을 것 같은데 잘 구현해주셨네요 👍🏼 우선 이번에 남긴 리뷰가 좀 많아서 해당 부분 먼저 반영하시고 추후 변경사항 적용해주시면 다시 리뷰 추가적으로 남겨보도록 할게요!!

2023-04-27 11:03 UTC, lxxjn0 commented on src/main/java/step2/LottoTicket.java
> +            .collect(ArrayList::new, ArrayList::add, ArrayList::addAll);
해당 값은 상수가 아니라 변수로 되어있어서 충분히 변조가 가능하지 않을까요?

2023-04-27 11:03 UTC, lxxjn0 commented on src/main/java/step2/LottoGame.java
> +                .forEach(matchCount -> results.putIfAbsent(matchCount, 0L));
MatchCount의 values 메서드를 활용하는 것이라면 MatchCount 클래스에 역할을 위힘하는 것이 어떨까요?

2023-04-27 11:03 UTC, lxxjn0 commented on src/main/java/step2/YourLottoTicket.java
> +    private static final String DELIMITER = ",";
입력과 관련된 값으로 보여져요!! 로또 입력하는 방식이 변경되면 해당 도메인 객체에 변경점이 생길 것 같아요!!

2023-05-08 09:56 UTC, garden-2 commented on src/main/java/step2/Money.java
> +    }
개인 스타일입니다
생성자 노출보다 필요한 상황에 필요한 정적팩토리 메소드 제공을 선호합니다.

2023-05-09 14:28 UTC, lxxjn0 commented on src/main/java/step2/Money.java
> +    }
정적 팩토리 메서드를 사용하신다면 그 목적이나 이유가 명확히 드러나면 좋을 것 같은데 지금의 코드는 그러한 장점이 보이지 않는 것 같아요. 생성자와 동일한 파라미터를 가지고, 내부의 어떠한 로직없이 단순히 생성자를 래핑한 메서드에 불과합니다. 이름으로 특정한 의도나 목적을 표현하는 것도 아니고요. 이러한 코드는 동일한 행위를 하는 중복된 코드를 만든 것이라고 생각해요. 

아래의 글에서 정적 팩토리 메서드를 사용할 때 얻을 수 있는 장점이 어떠한 것들이 있는지 한번 보시고 이러한 상황이나 의도에 맞게 활용하신다면 코드를 더 풍부하고 설득력 있게 작성할 수 있을 것 같아요 👍🏼 

https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2023-05-09 14:42 UTC, lxxjn0 approved these changes
피드백 반영하시느라 수고 많으셨습니다!! 👍🏼 

기존에 부족했던 유효성 검증 등이 추가되면서 코드가 훨씬 더 안전하고 안정적이어진 것 같아요!! 추가로 남긴 부분에 대해서는 한번 읽어보시고 공부해보시면 좋을 것 같아요!! 다음 단계를 진행하시면서 같이 반영해도 충분할 것 같아서 이번 단계는 여기서 머지하도록 하겠습니다 💯

2023-05-09 14:42 UTC, lxxjn0 commented on src/main/java/step2/AutoLottoTicket.java
>      }
지금의 toString 메서드는 적절하지 않은 것 같아요. 아래 문서를 참고해보시기를 추천드릴게요.

https://hudi.blog/java-correct-purpose-of-tostring/

2023-05-09 14:42 UTC, lxxjn0 commented on src/main/java/step2/Money.java
> +    }
자바에서는 프로퍼티(필드)의 정보를 전달할 때는 보통 getter 형태를 사용하니깐 네이밍도 getAmount와 같이 가져가도 괜찮을 것 같아요!!

2023-05-09 14:42 UTC, lxxjn0 commented on src/main/java/step2/Money.java
> +        }
에러 메시지와 조건이 일치하지 않는 것 같아요.

2023-05-09 14:42 UTC, lxxjn0 commented on src/main/java/step2/MatchCount.java
>      }
사실 이 부분은 저도 조금 애매하긴 한데, 보통은 enum의 생성자를 필드와 같은 타입으로 두고 사용하는 것 같아요. `FIVE(5, new Money(1_500_000))` 이런 식으로요. Enum 객체를 볼 때 이러한 형식으로 적혀있으면 필드 타입이 바로 파악될 것 같은데 지금의 코드는 필드와 생성자를 확인해야지 이해가 되는 것 같아서요.

물론 이 부분은 저도 확실한 정답이나 방법을 알고 있진 않아서 제 생각을 적어봤습니다!! ㅎㅎㅎ 한번 참고만 해주세요 :)

2023-05-09 14:42 UTC, lxxjn0 commented on src/main/java/step2/LottoTicket.java
> +    static final List<Integer> LOTTO_NUMBERS = IntStream.rangeClosed(LOTTO_MIN_NUMBER, LOTTO_MAX_NUMBER)
이번 단계에서는 따로 작업할 필요는 없는데 로또 번호를 감싸는 객체를 만들어 보는 것도 좋을 것 같아요!! 그렇다면 로또 번호에 대한 비즈니스 로직(1부터 45까지의 숫자만 가능) 등을 한 곳에 둘 수 있을 것 같아서요 👍🏼

2023-05-09 14:42 UTC, lxxjn0 commented on src/main/java/step2/Parser.java
> +public interface Parser {
파서를 인터페이스로 둔 이유가 있을까요?? 하나의 클래스만 존재하고 있어서 인터페이스로의 역할을 하기엔 불필요할 것 같아서요

2023-05-09 14:42 UTC, merged