Step4 - 로또(수동)
next-step/java-lotto pull request #2995
Opened 2023-04-27 14:45 UTC by kyeongminlee

## Step4 - 로또(수동)
### Step3 2차 피드백 수정
- [X] 정적 팩토리 메서드명 init으로 변경

### 기능 요구사항
- 현재 로또 생성기는 자동 생성 기능만 제공한다. 사용자가 수동으로 추첨 번호를 입력할 수 있도록 해야 한다.
- 입력한 금액, 자동 생성 숫자, 수동 생성 번호를 입력하도록 해야 한다.

### 구현 목록
- [X] 수동 구매 로또 수 입력 기능
- [X] 수동 로또 구매 번호 입력 기능
- [X] 로또 구매 장수 출력 기능(수동/자동)
- [X] 자동 로또 수 계산 기능
- [X] 수동 로또와 자동 로또 합쳐서 수익 계산

---
이전 단계에서 워낙 리뷰를 잘 해주신 덕분인지 미션 구현 자체는 어렵진 않았던것 같습니다.
그런데 뭔가 디테일을 놓치고 있을것 같은데요, 관련해서 리뷰 부탁드립니다!

2023-04-28 06:41 UTC, testrace requested changes
안녕하세요 경민님 😃 
4단계도 빠르고 깔끔하게 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요
궁금한 점이나 의견 있으시면 편하게 DM 주세요

2023-04-28 06:41 UTC, testrace commented on src/main/java/lotto/view/InputView.java
> +    }
`public static Lottos initLottos(Money amount)` 메서드가 제거되고 InputView에 같은 로직이 추가되었네요
주어진 수량만큼 로또를 생성하는 로직은 도메인 로직이 아니라고 판단하셨던걸까요?

2023-04-30 03:25 UTC, kyeongminlee commented
### Step4 1차 피드백 수정
- [X] wrapper 타입 대신 원시 타입으로 수정
- [X] isGreaterThanZero 생성자에서 검증
- [X] concat 대신 list의 addAll 메서드 사용
- [X] Output View에서 String.format을 활용
- [X] MoneyTest에서 ParameterizedTest 활용
- [X] 수동으로 구매한 로또 메서드는 도메인에서 계산하도록 수정

---
안녕하세요~ 용주님.
리뷰 감사합니다!
일단 dm으로 문의드린 부분은 계속 dm으로 문의하는것 보다는 제가 생각한 부분까지 구현을 하고 다시 피드백 받으면서 수정하는게 좋을것 같아서 지금까지 수정한 내용으로 리뷰요청 드립니다.
사실 `Lottos` 객체에서의 테스트 내용에 대해서도 고민은 좀 있었는데요, 테스트를 위한 getter메서드를 만드는걸 지양하다보니 테스트가 좀 부실했던것 같습니다. 특히 객체 생성 부분에 대한 테스트가 없었네요.
그래서 이번에는 해당 테스트 코드를 추가하긴 했는데, 단순히 객체 생성 후 값을 검증하는 메서드가 아니라 Instance 클래스가 맞는지 정도만 체크해서 이것도 약간 부실해 보이긴 합니다.
코드 보시고 계속 이야기 해 나갔으면 좋겠습니다!

2023-05-01 07:14 UTC, testrace approved these changes
안녕하세요 경민님 😃 
어려운 피드백이 많았는데 잘 반영해 주셨네요 💯 
로또 미션은 여기서 마무리 하겠습니다!
다음 미션도 파이팅입니다 🔥

2023-05-01 07:14 UTC, merged