Step3 - 로또(2등) PR 올립니다
next-step/java-lotto pull request #3001
Opened 2023-04-28 01:34 UTC by d-h-k

## 안녕하세요 리뷰어님 Step3 PR 올립니다! 

<br><br><br><br>

### 이번 Step3 PR 에서의 기능추가 && 개선점은 아래와 같습니다

-

2023-04-28 08:11 UTC, heowc requested changes
3단계를 잘 작성해주셨어요~

다만, 약갼의 아쉬움이 있어 코멘트를 드려보았습니다!
확인해보시고 코멘트 or 수정 부탁드려요~

궁금하시거나 어려움이 있으시다면 DM or 코멘트 주세요~ 💪

2023-04-28 08:11 UTC, heowc commented on src/main/java/lotto/domain/WinnerTicket.java
> +    public int countWinner(List<Ticket> challengeTickets, Prize prize) {
비슷하지만 다른 메소드가 WinnerTicket과 Ticket에도 존재하는 것 같아요. 이를 합쳐보는 것은 어떨까요?
어느 도메인이 담당해야하는지 고민해볼 필요가 있을 것 같아요 🤔

2023-04-28 08:11 UTC, heowc commented on src/main/java/lotto/domain/Issuer.java
> +    public void issueTickets(int ticketCount) {
피드백 반영 👍

2023-04-28 08:11 UTC, heowc commented on src/test/java/lotto/domain/StaticsTest.java
> +    public void second() {
테스트를 잘 작성해주셨어요 👍 

다만 추가된 클래스 `WinnerTicket`, `Ticket`에 집중된(?) 테스트가 없는 것 같은데 필요하진 않을까요?

2023-04-28 08:23 UTC, d-h-k commented on src/main/java/lotto/domain/Issuer.java
> +    public void issueTickets(int ticketCount) {
좋은 리뷰 감사합니다!

2023-04-29 02:48 UTC, d-h-k commented on src/main/java/lotto/domain/WinnerTicket.java
> +    private final Set<Integer> numbers;
이부분은 사실 Ticket 정보를 저장하려고 만든 컬렉션이라 제안해주신 코드가 조금더 적절해 보이네요!! 감사합니다

2023-04-29 02:51 UTC, d-h-k commented on src/main/java/lotto/domain/WinnerTicket.java
> +    public int countWinner(List<Ticket> challengeTickets, Prize prize) {
넵 이부분은 더 고민해보고 돌아오겠습니다. 사실 몇가지 방법을 두고 고민을 했었는데. 

1) 상속하는 방법 : Ticker >>(상속)>> (자식클래스) WinnerTicker

2023-04-29 03:01 UTC, d-h-k commented on src/test/java/lotto/domain/StaticsTest.java
> +    public void second() {
WinnerTicket, Ticket 클래스에 기능(도메인 요구사항)이 많이 달라붙어있는데, 테스트가 부족하다는 의견에 공감합니다 코드에 반영하겠습니다!

2023-04-29 06:50 UTC, d-h-k commented on src/main/java/lotto/domain/WinnerTicket.java
> +    public int countWinner(List<Ticket> challengeTickets, Prize prize) {
위 3가지 안(상속, 인터페이스, 컴포지션) 3가지 중에서 컴포지션으로 해당 부분을 처리했으며, WinnerTicket 에서 구현해야하는 메서드를 WinnerTicket 만 구현하고, Ticket 으로 위임 할 수 있는 메시지는 최대한 위임하는 방향으로 수정하였습니다!

2023-04-29 06:50 UTC, d-h-k commented on src/test/java/lotto/domain/StaticsTest.java
> +    public void second() {
테스트코드 추가 했습니다!

2023-04-29 07:02 UTC, d-h-k commented
안녕하세요 리뷰어님 피드백 주신 내용 감사합니다! 

이번 PR 에서는 두가지를 공유드리고 싶어서 메시지를 남겨봅니다

## Ticket 클래스와 WinnerTicket 클래스 사이의 관계
- 두 클래스 사이의 관계에 대해서 고민이 있었습니다. 두 클래스간의 관계를 3가지 방법으로 처리를 할 수 있을꺼같은데요 (상속, 인터페이스, 컴포지션) 저는 여기서 컴포지션 관계로써, WinnerTicket 클래스가 Ticket 클래스를 포함하는 관계로 작성하였습니다.


## 여러 각도에서의 검증을위한 테스트코드
- WinnerTicketTest, StaticsTest 두 클래스에서 동일한 기능 (등수별 당첨자의 수를 구하는 기능) 을 검증하는 메서드를 각각 구현했습니다. 어떤 관점에서 보면 동일한 기능에 대한 테스트코드의 중복 이라고 생각 할 수도 있을꺼같은데요 객체간의 협력으로 어플리케이션을 구현하는 OOP 특성 상 각각의 객체의 관점에서 테스트코드가 모두 존재해야한다는 생각으로 테스트코드를 만들었습니다. 예를들어
  - `WinnerTicketTest`  :  당첨인원 명수를 구하는 관점
  - `StaticsTest` : 통계를 구하는 관점에서의 당첨인원 확인

이상입니다 감사합니다!

2023-04-29 10:08 UTC, heowc approved these changes
피드백 반영 감사합니다~
굉장히 많이 고민을 해보신 것 같아 제가 다 뿌듯한 것 같아요~

이만 머지하도록 할게요~ 마지막 단계까지 화이팅입니다 👍 
소소하게 남겨둔 코멘트가 있는데 확인부탁드려요~

2023-04-29 10:08 UTC, heowc commented on src/main/java/lotto/domain/Statics.java
> +    private int aggregate(List<Ticket> challengerTickets, WinnerTicket winnerTicket, Prize prize) {
제 개인적인 생각으로는 `Tlcket`이 불필요한(?) 책임을 가지고 있다고 생각이 들었는데요.

- `Ticket`이 다른 `Ticket` 들에 대한 `Prize` 횟수를 체크 해야함

`List` 라서 처리하기 어려운 것이라면 `Tickets` 라는 일급 콜렉션을 만들어보는 것은 어땠을까 라는 생각이 들엇습니다.
아마 이번 단계에 요구사항 중 `규칙 8: 일급 콜렉션을 쓴다.` 라는 것이 있었던 걸로 기억해요 🤔

2023-04-29 10:08 UTC, heowc commented on src/main/java/lotto/domain/Statics.java
> +    private int aggregate(List<Ticket> challengerTickets, WinnerTicket winnerTicket, Prize prize) {
문득 든 생각인데, Prize 마다 List를 반복적으로 순회하는 것보다는 List를 순회하면서 Prize를 결정하는 것이 효율적이지 않을까요? 🤔

2023-04-29 10:08 UTC, heowc commented on src/test/java/lotto/domain/TicketTest.java
> + */
제거해도 되는 주석인 것 같아요~

2023-04-29 10:08 UTC, merged

2023-04-30 02:08 UTC, d-h-k commented
리뷰 감사합니다! 피드백 주신 사항은 다음단계에서 반영하겠습니다!

2023-04-30 02:43 UTC, d-h-k commented on src/test/java/lotto/domain/TicketTest.java
> + */
넵 해당부분 제거하겠습니다

2023-04-30 02:52 UTC, d-h-k commented on src/main/java/lotto/Lotto.java
> +        WinnerTicket winnerTicket = inputPresent.winningNumbers().winnerTicket(inputPresent.bonusNumber());
넵 Ticket이 WinnerTicket을 생성해주는 부분은 지금 보니 약간 이상하다는 생각이 듭니다. 지금 구조는 Set<Integer> numbers 를 Deepcopy 하기 위해서 작성됬는데, Set<Integer> numbers 를 굳이 Deepcopy 를 해야하지는 않을꺼같아요! 피드백 감사합니다

2023-05-05 12:29 UTC, d-h-k commented on src/main/java/lotto/domain/Statics.java
> +    private int aggregate(List<Ticket> challengerTickets, WinnerTicket winnerTicket, Prize prize) {
해당 부분 개선완료 하였습니다