Step 2 (로또 자동)
next-step/java-lotto pull request #3022
Opened 2023-04-29 16:56 UTC by hyungkishin

늦은 시간 감사드립니다 :)

2023-04-30 13:24 UTC, parkeeseul requested changes
2단계 미션 잘 진행해 주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다 
좋은 밤 되세요 😄

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/domain/LottoStatistics.java
> +        }
indent depth가 2네요 🤔

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/domain/Rounds.java
> +public class Rounds {
Rounds 에서 로또를 생성해 주고 있는데요, 
개인적으로 Rounds 가 로또를 생성한다가 문맥적으로 조금 어색해 보입니다.
LottoStrategy가 생성한 로또 번호들로 로또를 생성해 반환해도 좋을 것 같은데 어떻게 생각하시나요? 😄

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/domain/WinnerLotto.java
> +public class WinnerLotto {
WinnerLotto 와 LottoNumbers 는 어떠한 차이가 있나요? 😄

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/domain/Lotto.java
> +    public int countMatch(List<Integer> winningNumbers) {
해당 메서드에 대한 테스트도 작성해 주세요 😄

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/util/LottoValidationUtils.java
> +    }
LottoNumber 객체를 분리해 볼 수도 있을 것 같네요 😄

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/util/LottoValidationUtils.java
> +    }
해당 로직을 따로 utils로 분리하신 이유가 있으신가요?
LottoNubmers에 위치해도 좋을 것 같은데 어떻게 생각하시나요? 😄

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/domain/LottoNumbers.java
> +public class LottoNumbers {
LottoNumbers에 대한 테스트 코드가 없네요 😢

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/enums/LottoPrize.java
> +public enum LottoPrize {
LottoPrize에 대한 테스트 코드를 작성해 보면 어떨까요? 😄

2023-04-30 13:24 UTC, parkeeseul commented on src/main/java/lotto/enums/LottoPrize.java
> +    }
UI로직을 위한 코드일까요? 🤔

2023-04-30 14:42 UTC, hyungkishin commented on src/main/java/lotto/constants/Constants.java
> +public class Constants {
고민중인 부분입니다 :) 
Winner 와, Lotto 가 같은 값을 사용하게 되는데 2개 이상 사용하려니, 
공통 상수를 사용하는 부분으로 작성하게 되었습니다.

도메인별 필요한 상수마다 모으려니 배보다 배꼽이 더 큰것 같기도 해서 일단 중복상수만 모아 두었네요 :)

2023-04-30 14:43 UTC, hyungkishin commented on src/main/java/lotto/domain/Lotto.java
> +    private LottoNumbers lottoNumbers;
Numbers 가 낫겠어요 !!

2023-04-30 14:44 UTC, hyungkishin commented on src/main/java/lotto/util/LottoValidationUtils.java
> +    }
winnerLotto 도 같은 로직을 사용하고 있습니다 :) ㅠㅠ

2023-04-30 14:44 UTC, hyungkishin commented on src/main/java/lotto/enums/LottoPrize.java
> +    }
네 맞습니다 :)

2023-04-30 14:45 UTC, hyungkishin commented on src/main/java/lotto/util/LottoValidationUtils.java
> +    }
원사타입 Wrapping 은 하였는데 WinnerLotto 로직과 동일하여 Util 로 분리해 보았습니다 :)

2023-05-01 15:15 UTC, parkeeseul requested changes
피드백 반영해 주시느라 고생 많으셨습니다 👍 
몇 가지 추가 코멘트 남겨 두었으니 확인 부탁드립니다.
즐거운 활요일 되세요! 🔥

2023-05-01 15:15 UTC, parkeeseul commented on src/test/java/lotto/domain/LottosTest.java
> +        assertThat(lottos.getLottoList().size()).isEqualTo(COUNT);
hasSize()를 사용해 볼 수도 있겠네요 😄 
```suggestion
        assertThat(lottos.getLottoList()).hasSize(COUNT);
```

2023-05-01 15:15 UTC, parkeeseul commented on src/test/java/lotto/domain/NumbersTest.java
> +    void test3() {
테스트 메서드 네이밍을 단순히 test1, test2, test3 으로 하는 것 보다 의미있는 네이밍을 해주면 어떨까요? 😄

2023-05-01 15:15 UTC, parkeeseul commented on src/test/java/lotto/enums/LottoPrizeTest.java
> +    }
테스트 검증 로직에서 비슷한 코드가 중복되고 있는데요
`@ParameterizedTest ` 를 활용해 개선해 볼 수도 있겠네요 😄

2023-05-02 16:47 UTC, hyungkishin reviewed
감사합니다. 

재리뷰 요청 드려요 :)

2023-05-03 14:43 UTC, parkeeseul approved these changes
피드백 반영해 주시느라 고생 많으셨습니다 😄 
몇 가지 코멘트 남겨두었으니 확인해 보시고
추가적인 수정 사항은 다음 단계와 함께 반영 부탁드립니다
다음 단계 진행해 주세요 🔥

2023-05-03 14:43 UTC, merged

2023-05-03 15:52 UTC, hyungkishin commented on src/main/java/lotto/domain/LottoStatistics.java
> +    private final List<Lotto> lottoList;
일급 컬렉션을 만들어 두었는데 위임해두어야겠네요 감사합니다 :)