[1단계 - 문자열 계산기]미션 1 완료
next-step/java-lotto pull request #3044
Opened 2023-05-01 08:52 UTC by woonys

안녕하세요, 미션 1단계 - 문자열 계산기 완료해 리뷰 요청드립니다.

2023-05-02 00:40 UTC, catsbi requested changes
안녕하세요 우니님. 로또 미션을 함께하게 된 이한솔입니다 👍 
첫 번째 문자열 계산기 미션 잘 구현해주셨네요. 

몇 가지 피드백이 필요한 부분에 코멘트 남겨드렸으니 확인 후 다시 리뷰요청 부탁드립니다.

2023-05-02 00:40 UTC, catsbi commented on src/main/java/Calculator.java
> +    private int answer;
해당 계산기는 별도의 상태를 가질 필요가 없어보여요. 
그냥 매개변수로 문자열을 받고 바로 계산 후에 반환하면 되니까요. 사용할 때마다 객체 생성을 할 필욘 없을 것 같은데 무상태(stateless)객체로 만들어볼 수 없을까요?

2023-05-02 00:40 UTC, catsbi commented on src/main/java/Calculator.java
> +        this.answer = 0;
- 0을 기본값으로 초기화하는데 매직넘버는 상수로 분리해주면 관리하기 더 편하고 가독성도 높아집니다

2023-05-02 00:40 UTC, catsbi commented on src/main/java/Calculator.java
> +        String[] result = inputVal.split(" ");
```suggestion
        String[] result = inputVal.split(DELIMITER);
```
지금은 공백이지만 나중엔 아닐 수도 있겠죠?

2023-05-02 00:40 UTC, catsbi commented on src/main/java/Calculator.java
> +            || Objects.equals(" ", inputVal)) {
IsBlank메서드를 활용해보는건 어떨까요

2023-05-02 00:40 UTC, catsbi commented on src/main/java/Calculator.java
> +        LinkedList<String> queue = new LinkedList<>();
LinkedList를 사용한 이유가 있을까요?

2023-05-02 00:40 UTC, catsbi commented on src/main/java/Calculator.java
> +        String start = inputValue.remove();
remove()라는 시그니처는 삭제로 보이는데 start가 반환된다는 이 로직은 가독성이 너무 떨어집니다. 좀 더 이해하기 쉽게 바꿔보는건 어떨까요?

2023-05-02 00:40 UTC, catsbi commented on src/main/java/Calculator.java
> +    }
- addition이 됐더라도 나머지 로직이 전부실행됩니다. 4개가 아니라 수십 수백개일 경우 성능상에 이슈가 있을 것 같네요. 열거타입이나 추상화를 통해 간결하게 바꿀 수 없을까요?

2023-05-02 00:40 UTC, catsbi commented on src/main/java/IntConverter.java
> +}
- 들여쓰기 depth가 3인게 보이네요. 2로 줄여볼 수 없을까요? 
- Integer의 parseInt 메서드 내부적으로 또 숫자인지 유효성검증을 하고 있습니다. 그래서 중복된 유효성 검증이에요. 차라리 Number같은 일급 객체를 만든 뒤 parseInt시도와 NumberFormatException을 캐치하는건 어떨까요?

2023-05-02 00:40 UTC, catsbi commented on src/test/java/CalculatorTest.java
> +    @DisplayName("'a + b'를 입력 시 계산값을 반환한다.")
a와 b가 무엇인지에 대한 조건 설명이 없습니다.  🤔

2023-05-02 00:40 UTC, catsbi commented on src/test/java/CalculatorTest.java
> +    void returnResult_whenAPlusB() {
덧셈 뺼셈 나눗셈 등 결국 다 사칙연산인건 공통점이고, 유효상 값을 테스트한다는 공통점이 있는데 이런건 parameterizedTest를 이용해 하나로 묶어도 될 것 같네요.

2023-05-02 00:40 UTC, catsbi commented on src/test/java/CalculatorTest.java
> +    }
빈 값이 아닌 0을 나눌 때 생기는 ArithmeticException 에 대한 테스트도 있으면 어떨까요

2023-05-03 13:48 UTC, woonys commented on src/main/java/Calculator.java
> +    private int answer;
@catsbi 피드백 감사합니다 한솔님 :) 말씀해주신대로 무상태 객체로 변경해봤습니다. 🙇

2023-05-03 13:48 UTC, woonys commented on src/main/java/Calculator.java
> +        this.answer = 0;
@catsbi 피드백 감사합니다 :) 상수로 분리했습니다.

2023-05-03 13:49 UTC, woonys commented on src/main/java/Calculator.java
> +        String[] result = inputVal.split(" ");
@catsbi 피드백 감사합니다 :) 역시 따로 선언해 분리했습니다.

2023-05-03 14:51 UTC, woonys commented on src/main/java/IntConverter.java
> +}
@catsbi 피드백 감사드립니다. 말씀해주신 부분을 반영해 Number 객체를 만들어봤습니다. 한 가지 고민은, Number 객체를 만들면서 Operator에서 구현했던 계산 로직 중 일부가 Number 객체로 넘어가도록 했습니다. 상태와 행위를 Number 내에서 관리하는 게 맞겠다고 판단해서인데요, 고민인 점은 이 부분이 Operator의 책임과 겹치는 건 아닌가 하는 고민입니다. 잘된 구현일까요?

2023-05-03 14:51 UTC, woonys commented on src/test/java/CalculatorTest.java
> +    @DisplayName("'a + b'를 입력 시 계산값을 반환한다.")
@catsbi 피드백 감사합니다 :) 해당 부분 수정했습니다.

2023-05-03 14:51 UTC, woonys commented on src/test/java/CalculatorTest.java
> +    void returnResult_whenAPlusB() {
@catsbi 피드백 감사드립니다. 해당 부분 수정했습니다.

2023-05-03 14:51 UTC, woonys commented on src/test/java/CalculatorTest.java
> +    }
@catsbi 이 부분은 미처 생각 못했네요 :) 해당 테스트 역시 추가했습니다. 감사합니다 :)

2023-05-03 17:00 UTC, catsbi commented on src/main/java/IntConverter.java
> +}
@woonys Number는 일종의 일급 객체로써 값에 대한 핸들링을 하는 것은 적절한 책임으로 보입니다. 
Operator는 연산자 정보로 값을 다룬다기보단 어떤 연산을 지원하는지에 대해 책임을 지는것이죠. 
언뜻 비슷해보이지만 책임지는 actor가 분리되어 있기에 그 부분만 유념하면 될 것 같습니다.

2023-05-03 17:01 UTC, catsbi approved these changes
재운님 피드백 반영 잘 해주셨네요 💯 
1단계는 여기서 마무리하겠습니다. 바로 2단계로 진행하시죠!

2023-05-03 17:01 UTC, merged