[Step3] 로또(2등) 리뷰 요청
next-step/java-lotto pull request #3074
Opened 2023-05-02 17:55 UTC by soochangoforit

꼼꼼한 리뷰 항상 감사합니다 😄 

이번 목표는 VO객체와 일급 콜렉션을 좀 더 적극적으로 활용하고자 했습니다!!
궁금한 부분은 Comment로 남기겠습니다!! 감사합니다 ~

2023-05-03 16:41 UTC, shared-moon commented
질문이 엄청 정성스럽네요..!

> View는 과연 VO 객체와 의존성을 가져도 괜찮을까요??

네 상관 없습니다 :) 패키지 의존성은 바깥에서 안쪽으로 향하면 크게 문제가 없어요. 반대로 VO에서 View에 의존성을 가진다면, View가 바뀌었을 때 ( e.g. CLI -> Web 으로 변경되는 경우 ) 안쪽의 VO나 서비스가 영향을 받게 되기 때문에 그런걸 유의해주시면 됩니다 !

> Controller에서 여러 Domain과 의사소통을 하고 있는데 괜찮은지 궁금해요!!

현재 구현하신 부분은 컨트롤러라기보단 `메인` 이라고 봐야 할 것 같아요. 여러 도메인에 의존성이 있는건 필요한 부분이라 어쩔 수 없을 것 같습니다 :)

> 만약 위처럼 구성하면, Controller가 Domain의 로직을 알고 있지 않을까?? 라는 의문점이 들어요

로직을 알게된다는 게 어떤 의미일까요 ? 숨겨야 하는 건 privat으로 처리하면 되지 않을까 싶어요 ?

> 위의 사진처럼 Controller는 하나의 Domain과 의사소통 하도록 추구 해야할까요?

이건 역할분담을 어떻게 하느냐에 따라 달려있을 것 같아요. 위에서 말씀 드렸듯이 현재는 이름이 Controller일 뿐, 그냥 main 혹은 서비스의 역할을 하고 있기 때문에 크게 문제는 없어보입니다. 원하시는게 컨트롤러에서 I/O 처리를 하고 서비스를 따로 두어 I/O와 완전 분리를 하시려는거라면 밑에 말씀하신 것 처럼 구현하셔도 됩니다 :)

> View의 책임 범위는 어디까지가 적당할까요??

유효성 검사의 범위에 대한 질문인 것 같아요. 이것도 정답은 없습니다만, View는 요청이 들어오는 가장 끝단에 위치하는 녀석이라 유효성 검사가 여기에 들어가면 내부의 서비스 등에서는 해당 스펙에 대해 검증이 안될 수 있다는 단점이 있어요. 정하기 나름이지만, 말씀하신대로 빈값 입력이나 입력이 없거나 숫자/문자 구분정도는 해도 되지 않을까 싶습니다.

> 보너스넘버가 생성 되는 시점에, 당첨 번호와 중복이 있는지 검사 진행???

요런건, 보너스 넘버와 당첨번호 중복이 있으면 안된다는 스펙이 누구의 책임인지 생각해 보시면 될 것 같습니다. InputView는 입력을 위한 녀석이고, 보너스 넘버의 중복 검사는 비즈니스 로직이니 비즈니스 수행 주체가 가져가면 될 것 같아요 :)

> Enum의 static method에 대해.. 의문점이 들어요

네, 전혀 문제 없어보입니다. 어떤 부분이 맘에 걸리신걸까요 ?

> 객체에게 메시지를 보내다 보니, 더 헷갈리는 느낌이 들었어요

기존 코드도 객체에게 메세지를 보내서 잘 처리하고 있었던 것 같아요. getter는 배제하는 것이 아니라 무분별한 사용을 지양하는 것입니다. 오히려 아래 코드는 순환참조가 일어나서 객체들이 강하게 결합되어 별로 좋은 구조가 아닌걸로 보입니다 :)

2023-05-03 17:29 UTC, shared-moon requested changes
수찬님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 다음 미션 진행 전 정리 한번 하고 가면 좋을 것 같아요!
확인 후 리뷰 재요청 부탁드려요 ~

2023-05-03 17:29 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoTickets.java
> +        .collect(Collectors.groupingBy(prize -> prize, () -> new EnumMap<>(Prize.class),
`prize -> prize` 처럼 자기 자신이 필요할때는 `Function.identity()`를 사용할 수 있어요!

2023-05-03 17:29 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoTickets.java
> +    EnumMap<Prize, Long> results = tickets.stream()
변수 타입은 상위의 인터페이스로 선언하는게 어떨까요 ?

2023-05-03 17:31 UTC, shared-moon commented
추가로, 저희는 지금 깃을 쓰고 있기 때문에 이전 히스토리는 다 볼 수 있어서  나눌 이유가 없다고 생각하는데, 패키지를 분리해서 작업하신 이유가 있으실까요 ? 패키지를 분리해서 새로 작업해주시면 깃 변경사항에 전체가 잡혀서 리뷰하기가 어려워져서요 :)

2023-05-04 05:10 UTC, soochangoforit commented on src/main/java/lotto3/domain/BonusNumber.java
> +  public void validateDuplicate(WinningNumbers winningNumbers) {
> 이게 BonusNumber의 책임이 맞을까요 ?

@shared-moon 
제 생각으론, WinningNumbers에게 중복 확인 책임을 위임하면 좋을 것 같다고 다시 판단했습니다.
리뷰어님은 해당 책임이 WinningNumbers에게 위임해도 괜찮다고 생각하실까요? 😄

2023-05-04 05:11 UTC, soochangoforit commented on src/main/java/lotto3/domain/LottoTickets.java
> +        .collect(Collectors.groupingBy(prize -> prize, () -> new EnumMap<>(Prize.class),
> `prize -> prize` 처럼 자기 자신이 필요할때는 `Function.identity()`를 사용할 수 있어요!

아하!! 그렇군요 감사합니다~ 관련해서 더 공부해보겠습니다!!

2023-05-04 05:17 UTC, soochangoforit commented on src/main/java/lotto3/domain/LottoTickets.java
> +        .collect(Collectors.groupingBy(prize -> prize, () -> new EnumMap<>(Prize.class),
> EnumMap을 사용하신 이유가 어떤게 있을까요 ~?

@shared-moon 
EnumMap은 Map 인터페이스의 구현체 중 하나로, 키로 사용하는 객체가 Enum 타입일 경우에 사용할 수 있습니다. 

1. EnumMap은 내부적으로 배열을 사용하여 키-값 쌍을 저장하므로, Key 값을 Hashing 하는 HashMap에 비해 시간 복잡도와 공간 복잡도가 낮습니다. 따라서 빠른 조회 및 삽입이 가능합니다.

2. Enum 상수 값의 순서를 인덱스로 사용하여 배열에 키-값 쌍을 저장하기 때문에, 일반적인 HashMap과 비교해 메모리 사용량이 적습니다.

3. EnumMap의 키는 반드시 Enum 타입이어야 하므로, 컴파일 시간에 잘못된 키 타입의 사용을 방지할 수 있습니다.

4. EnumMap은 키가 Enum 상수의 선언 순서대로 정렬됩니다. 이렇게 하면 순서가 중요한 경우에 유용하게 사용할 수 있습니다.

유연성을 좀 더 높이기 위해, 리뷰어님이 말씀하신 대로 Map으로 선언해서 사용할 수도 있습니다!!

2023-05-04 05:18 UTC, soochangoforit commented on src/main/java/lotto3/domain/LottoTickets.java
> +    EnumMap<Prize, Long> results = tickets.stream()
> 변수 타입은 상위의 인터페이스로 선언하는게 어떨까요 ?

유연성을 위해 상위 타입으로 선언하는게 더 적절한 방향인것 같습니다! 감사합니다 ~ 😄

2023-05-07 05:57 UTC, soochangoforit commented on src/main/java/lotto3/domain/LottoNumbers.java
> +  private final List<Integer> numbers;
> 이 안에 있는 Integer도 VO로 바꿔볼 수 있지 않을까요 ?

List<Integer> 대신 List<LottoNumber>로 수정해서 다시 작업을 했어요 감사합니다 😄

2023-05-07 06:13 UTC, soochangoforit commented
BonusNumber 와 LottoNumber가 서로 비슷한 책임을 갖고 있기에, 따로 BonusNumber 라는 객체를 만들지 않고
![image](https://user-images.githubusercontent.com/91618389/236660788-91d786ab-1882-4e75-b6c2-e30d9d14edd6.png)
변수가 가지는 네이밍을 통해 그 의미를 부여하고자 했습니다

코드를 점검하는 과정에서 로또 기계에 투입한 돈에 맞게 LottoNumber를 가지는 `LottoNumbers`와 지난주 당첨 번호를 입력 받은 `WinningNumbers`가 **보너스 번호에 대한 중복 체크하는 로직을 제외**하고는 거의 같은 책임구조를 갖고 있습니다

WinningNumbers 와 LottoNumbers를 지금처럼 구분해서 구현해도 괜찮을까요??
![image](https://user-images.githubusercontent.com/91618389/236660922-9f5d45aa-0fc9-44b7-981b-f8e67a2ab500.png)
![image](https://user-images.githubusercontent.com/91618389/236660934-a15f6ce9-efc0-4dfc-ba94-4d127a0bae7b.png)

2023-05-07 08:11 UTC, shared-moon commented on src/main/java/lotto3/domain/BonusNumber.java
> +  public void validateDuplicate(WinningNumbers winningNumbers) {
BonusNumber는 그 자체로 수행할 수 없는 기능이기때문에 WinningNumbers가 가져가는게 맞다고 생각합니다 :)

2023-05-07 08:23 UTC, shared-moon approved these changes
수찬님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 다음 미션 진행 전 확인 부탁드려요!
고생 많으셨어요 :)

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoNumber.java
> +public class LottoNumber {
👍

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoNumbers.java
> +  private List<LottoNumber> convertToLottoNumbers(List<Integer> numbers) {
👍

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoNumbers.java
> +  public boolean contains(LottoNumber bonusNumber) {
그대로 contains 쓰셔도 되지 않을까요 ?

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoResults.java
> +  private final Map<Prize, Long> results;
👍

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoResults.java
> +  private long calculateTotalPrizeMoney() {
👍

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoTicket.java
> +    this(new LottoNumbers(numbers));
👍

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/LottoTickets.java
> +        .collect(Collectors.groupingBy(Function.identity(), () -> new EnumMap<>(Prize.class),
취향이긴 한데, 저는 java에서 제공해주는 유틸리티에 대해서는 `static import`를 사용하는 편이에요 :)

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/WinningNumbers.java
> +  private final List<LottoNumber> winningNumbers;
contains 연산이 자주 일어나는 것 같은데, List에서 contains 시 어떤 방법으로 포함여부를 판단하게 될까요 ? Set과의 차이점도 고민 해 보시면 좋을 것 같아요 :)

2023-05-07 08:23 UTC, shared-moon commented on src/main/java/lotto3/domain/WinningNumbers.java
> +    validateDuplicate();
유효성 검사를 변수 대입보다 앞에서 하고, 검사 대상을 전달받은 값으로 하는 게 어떨까요 ? 지금 구조로 추가 요구사항이 들어오는 경우 만약 구조를 잘 모르는 사람이 앞에서 this.winningNumbers에 변경을 가한다면 원하는 대로 동작하지 않을 수도 있을 것 같아요 :)

2023-05-07 08:23 UTC, merged

2023-05-07 13:02 UTC, soochangoforit commented on src/main/java/lotto3/domain/WinningNumbers.java
> +  private final List<LottoNumber> winningNumbers;
> contains 연산이 자주 일어나는 것 같은데, List에서 contains 시 어떤 방법으로 포함여부를 판단하게 될까요 ? Set과의 차이점도 고민 해 보시면 좋을 것 같아요 :)

List는 내부적인 요소를 순회하면서 contains의 파라미터를 equals의 인수로 하여 호출합니다. equals 메서드가 요소에 대해 true를 반환하면 contains 메서드는 true를 반환합니다. 만약 일치 항목을 찾지 못한 채 반복이 완료되면 contains 메서드는 false를 반환합니다.

하지만 중복된 숫자를 방지하기 위해 Set 자료구조를 사용한다고 하면 equals와 hashCode를 같이 정의해줘야 합니다.
hash 값을 사용하는 Collection(HashMap, HashSet, HashTable) 은 hashCode 메서드의 Return 값이 우선 일치하고, equals 메서드의 Return 값이 true여야 논리적으로 같은 객체라고 판단합니다.

만약, hashCode를 재정의를 하지 않느다면 Object 클래스의 hashCode 메서드를 사용하게 되는데 이는 객체의 고유한 주소 값을 int 값으로 변환하기 때문에 아무리 같은 상태값을 가지더라도, 다른 객체로 인식하게 됩니다.

2023-05-07 13:04 UTC, soochangoforit commented on src/main/java/lotto3/domain/WinningNumbers.java
> +    validateDuplicate();
> 유효성 검사를 변수 대입보다 앞에서 하고, 검사 대상을 전달받은 값으로 하는 게 어떨까요 ? 지금 구조로 추가 요구사항이 들어오는 경우 만약 구조를 잘 모르는 사람이 앞에서 this.winningNumbers에 변경을 가한다면 원하는 대로 동작하지 않을 수도 있을 것 같아요 :)

객체에게 먼저 값을 할당하기 전에, 미리 유효성 검사를 진행함으로서 해결할 수 있을 것 같습니다!! 감사합니다 😄