Step2
next-step/java-lotto pull request #3076
Opened 2023-05-03 02:26 UTC by devcat36

step 2 리뷰 부탁드립니다.

2023-05-03 13:48 UTC, csh0034 requested changes
안녕하세요. 재형님 😃 
2단계 잘 구현해주셨네요 👍 
몇가지 코멘트 남겨두었는데 확인 부탁드려요!

2023-05-03 13:48 UTC, csh0034 commented on src/main/java/lottery/PnLResult.java
> +    public Float ror;
가시성은 가능한 최대한 낮춰주세요~

특히 인스턴스 변수의 경우엔 private 으로 주로  사용합니다.

2023-05-03 13:48 UTC, csh0034 commented on src/main/java/lottery/LotteryController.java
> +    public void runLotterySequence() {
적절한 개행을 통해 구분이 된다면 더 좋을것 같아요!

2023-05-03 13:48 UTC, csh0034 commented on src/main/java/lottery/LotteryCalculatorConsoleView.java
> +            PnLType.LOSS, "기준이 1이기 때문에 결과적으로 손해라는 의미임",
`기준이 1이기 때문에 결과적으로 XX라는 의미임` XX 를 제외하곤 모두 동일하네요. PnLType 에 손해, 본전, 이득 이라는 필드를 두고
해당 문구에 따라 보여주는건 어떨까요?

2023-05-03 13:48 UTC, csh0034 commented on src/main/java/lottery/LotteryCalculator.java
> +    public List<Integer> getLotteryCountForNumMatches(List<Lottery> lotteries, Set<Integer> numbers) {
`List<Integer>` 와 같은 리턴타입보단 로또의 결과를 명확하게 표현하는 객체라면 더좋을것 같습니다 🙂

2023-05-03 13:48 UTC, csh0034 commented on src/main/java/lottery/LotteryCalculatorView.java
> +public interface LotteryCalculatorView {
구현체가 반드시 하나인 경우인데 인터페이스가 필요할까요? 🤔

2023-05-03 13:52 UTC, csh0034 commented
## 1. 기능목록 작성후 기능단위 커밋

프로그래밍 요구사항중 `모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다.` 의 내용이 있습니다.
현재 요구사항만 정리되어있고 요구사항으로부터 구현할 기능목록이 작성되어 있지 않은데요.
기능목록 작성후 해당단위로 TDD 를 적용하여 기능단위 커밋을 해주시면 더 좋을것 같아요.

## 2. 로또 정렬 및 출력 결과 수정 

현재 하단과 같이 6개일치의 1등이 출력되지 않는 부분과 기능요구사항과 다르게 정렬되어 출력되지 않고있습니다.
확인 부탁드려요 😃 

```text
구매금액을 입력해 주세요.
2000
2개를 구매했습니다.
[16, 34, 37, 40, 44, 46]
[19, 3, 4, 42, 27, 30]
지난 주 당첨 번호를 입력해 주세요.
19, 3, 4, 42, 27, 30
당첨 통계
---------
3개 일치 (5000원)- 0개
4개 일치 (50000원)- 0개
5개 일치 (1500000원)- 0개
총 수익률은 0.00입니다.(기준이 1이기 때문에 결과적으로 손해라는 의미임)
```

2023-05-09 00:31 UTC, devcat36 commented on src/main/java/lottery/LotteryCalculatorConsoleView.java
> +            PnLType.LOSS, "기준이 1이기 때문에 결과적으로 손해라는 의미임",
PnLType 에 손해, 본전, 이득 이라는 필드를 둔다면, 모델을 자연어로 렌더링하는 뷰의 역할이 모델에 침범하는 것 같습니다.
또한 XX라는 의미임 에서 XX 를 제외하고 모두 동일하지 않습니다. 한국어/한글 자연어 구조상 "이" 가 적절하게 붙어야 합니다.

2023-05-09 00:32 UTC, devcat36 commented on src/main/java/lottery/LotteryCalculatorConsoleView.java
> +public class LotteryCalculatorConsoleView implements LotteryCalculatorView {
결과계산은 view 에서 담당하고 있지 않지만, 당첨금액 표시를 위해 당첨금액이 정의되어 있습니다.

2023-05-09 00:36 UTC, devcat36 commented
따로 코멘트 드린것을 제외하고 리뷰 반영하였습니다. 리뷰 부탁드립니다.

2023-05-09 10:15 UTC, csh0034 approved these changes
리뷰 잘 반영 해주셨네요 👍 
몇가지 코멘트 남겨두었는데 다음단계 진행하시면서
고민부탁드려요!
다음 단계에서 뵙겠습니다 😄

2023-05-09 10:15 UTC, csh0034 commented on src/main/java/lottery/LotteryStatistics.java
> +            var matchCnt = LotteryRow.fromGiven(lottery.getNumbers()).getMatchCount(winningRow);
wrapping 된 LotteryNumber 를 다시 Integer 로 만들어서 LotteryRow 를 생성하는 부분이 어색해보이네요 🤔
변환없이 사용할수 있도록 고민해보면 좋을것 같습니다.

2023-05-09 10:15 UTC, csh0034 commented on src/main/java/lottery/LotteryRow.java
> +        var randomLotteryNumbers = new HashSet<LotteryNumber>();
현재 결과가 정렬되어 출력되지 않고있는데요.
HashSet 이 아닌 TreeSet 과 같은 정렬 가능한 컬렉션을 사용해보면 좋을것 같아요.

2023-05-09 10:15 UTC, csh0034 commented on src/main/java/lottery/LotteryRow.java
> +        return new LotteryRow(Arrays.stream(numbers.replace(" ", "").split(","))
구분자가 변경된다면 모델이 수정되어야겠네요 🤔
구분된 형태로 받아보는것도 좋을것 같습니다.

2023-05-09 10:15 UTC, merged