Step2 로또(자동) 구현
next-step/java-lotto pull request #3080
Opened 2023-05-03 13:44 UTC by don-garu

2023-05-05 03:09 UTC, ksy90101 requested changes
안녕하세요 :)
2단계 고생 많으셨습니다!
간단한 피드백을 남겼습니다.
전체적으로 구조를 잘 짜신거 같아서 인상깊었어요!
궁금한게 있다면 언제든 슬랙으로 연락주세요~

2023-05-05 03:09 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +    PLUS("+", (x, y) -> x + y),
x, y도 좋지만, 더 의미있는 이름으로 하면 어떨까 해요.
예를들면 number같은 단어가 있겟죠 ㅎㅎ

2023-05-05 03:09 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +    DIVIDE("/", (x, y) -> x / y);
여기서 y가 0이면 어떻게 될까요?
validate가 필요해보여요~

2023-05-05 03:09 UTC, ksy90101 commented on src/main/java/lotto/domain/Lotto.java
> +    private final Set<LottoNumber> lottoNumbers;
Set 👍

2023-05-05 03:09 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoGenerator.java
> +public class LottoGenerator {
여기도 랜덤값이기 떄문에 테스트 코드에서 해당 부분을 사용하면 제어하기가 힘들거 같아요.
자동차 경주게임에서 랜덤값처럼 인터페이스로 OCP를 지켜보면 어덜까요?

2023-05-05 03:09 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoGenerator.java
> +    private static final List<LottoNumber> LOTTO_NUMBERS = new ArrayList<>();
👍 캐싱

2023-05-05 03:09 UTC, ksy90101 commented on src/main/java/lotto/domain/Match.java
> +                .orElse(null);
null이면 NPE가 발생하지 않을까요?
차라리 에러를 던지는게 어떨까요?

2023-05-05 03:09 UTC, ksy90101 commented on src/main/java/lotto/dto/LottoPrize.java
> +public enum LottoPrize {
Match랑 다른게 무엇인가요?ㅎㅎ

2023-05-09 11:03 UTC, don-garu commented on src/main/java/lotto/dto/LottoPrize.java
> +public enum LottoPrize {
제가 봐도 별다른 점이 없어보여 LottoPrize 를 삭제하고, Match 에서 해당 기능까지 수행하도록 변경했습니다.

2023-05-10 05:21 UTC, ksy90101 approved these changes
안녕하세요 :)
2단계 수정 하시느라고 고생하셨습니다!!!!
간단한 피드백을 남겼으니, 한번 확인해주세요~
3단계때 다시 뵐게요!

2023-05-10 05:21 UTC, ksy90101 commented on src/main/java/lotto/domain/Lotto.java
> +        return LottoNumberParser.parseToString(lottoNumbers);
toString의 목적은 무엇일까요?
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/3%EC%9E%A5/12_toString%EC%9D%84_%ED%95%AD%EC%83%81_%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

해당 글을 읽어보시면 좋을거 같습니다 :)

2023-05-10 05:21 UTC, ksy90101 commented on src/test/java/lotto/domain/LottoTest.java
> +        assertThatThrownBy(() -> Lotto.from("1, 2, 3, 4, 5, 6, 7"))
차후 assertAll을 알아보시면 좋을거 같아요~

2023-05-10 05:21 UTC, merged