Step4 4단계 - 로또(수동)
next-step/java-lotto pull request #3097
Opened 2023-05-04 14:12 UTC by SightStudio

로또 수동단계를 구현하였습니다.

구현하면서 로또 게임에 필요한 파라미터들이 많아 별도 설정 객체로 뺏고,
생성자에 뜻을 가진이름을 부여하기 위해 정적 팩터리 메서드를 썻는데 

쓰다보니 상속을 못시킨다는 점과 테스트하기 어려울것같은... 느낌이 들어서 
살짝 애매할수도 있겠다는 생각이 조금 드네요

2023-05-05 07:17 UTC, Hyeon9mak requested changes
안녕하세요 동민님, 수동 로또 기능 구현 고생하셨습니다.

상속이 필요하다고 느끼신 포인트가 어딜까요? 함께 고민해보면 좋을 것 같습니다!
테스트 하기 어려운 부분은 자동차 경주 미션의 피드백처럼,
하나의 객체가 갖고 있는 로직을 별개 객체로 분리하여 파라미터나 생성자에 주입하여 사용하는 방식을 취하면
테스트가 더욱 용이해질 것 같습니다.

궁금하신 점 추가 코멘트 남겨주세요 🙇‍♂️

2023-05-05 07:17 UTC, Hyeon9mak commented on src/main/java/lotto/LottoApplication.java
> +    return LottoGame.ofAutoManualMixed(manualLottoRounds, lottoPrice, gameSetting);
로또 발급 기능만을 전담하는 별개 객체가 생기면, 분기 조건도 숨기고 테스트도 용이해지겠네요!

```java
@DisplayName("수동로또 수에 따라 ... ")
```

2023-05-05 07:17 UTC, Hyeon9mak commented on src/main/java/lotto/domain/round/LottoRound.java
> +  private final LottoGameType gameType;
발급된 로또(로또종이 혹은 로또티켓)에서 roundNo 와 type 를 꼭 알아야할까 고민 되네요 🤔 
roundNo 는 활용처가 불분명한 것 같고, type 은 발급 전의 관심사 아닌가 싶어요!

2023-05-05 07:17 UTC, Hyeon9mak commented on src/main/java/lotto/domain/round/LottoRound.java
> +  private final LottoGameType gameType;
발급한 수동로또 리스트와 자동로또 리스트를 view 에 전달하여 각각의 개수를 표기해주는 방법도 있겠네요!

2023-05-05 07:17 UTC, Hyeon9mak commented on src/main/java/lotto/domain/number/LottoNumber.java
> +    this.number = number;
`LottoNumber` VO 는 중복해서 사용될 값이므로, 
인스턴스를 미리 캐싱해두면 싱글톤도 지킬 수 있고, 주어진 번호에 알맞는 VO 를 재빠르게 반환해줄 수 있겠네요!

2023-05-05 08:09 UTC, SightStudio commented on src/main/java/lotto/domain/round/LottoRound.java
> +  private final LottoGameType gameType;
roundNo는 LottoRound (로또 게임 하나) 에 대한 고유값이 없어 그걸 구분하기위해서 만들었습니다.
생각해보니 사용하는곳이 없어 제거해도 될것같네요.

type은 생각해보니 발급 전의 관심사가 맞는것같네요.
어떻게 만들어졌는지에 대한 데이터가 필요하다고 생각했는데
요구사항에선 필요없어보이네요

2023-05-05 08:10 UTC, SightStudio commented on src/main/java/lotto/LottoApplication.java
> +    return LottoGame.ofAutoManualMixed(manualLottoRounds, lottoPrice, gameSetting);
넵 생각해보니 요거는 클래스로 분리할 수 있겠네요 ㅎㅎ :)

2023-05-05 08:15 UTC, SightStudio commented on src/main/java/lotto/LottoApplication.java
> +    return LottoGame.ofAutoManualMixed(manualLottoRounds, lottoPrice, gameSetting);
생각해보니  이부분은 수동이 존재할 경우 수동으로 구매할 번호를 입력받는 부분이 있어서
클래스로 안만들었었네요 (로직이 View단과 결합되어있는 문제)

이부분은 좀더 고민해보도록 하겠습니다.

2023-05-05 08:53 UTC, SightStudio commented on src/main/java/lotto/LottoApplication.java
> +    return LottoGame.ofAutoManualMixed(manualLottoRounds, lottoPrice, gameSetting);
이 부분은... ofAutoOnly 나 ofAutoManualMixed가 호출되었는지 체크해야해서..
mockito의 verify가 필요해보이네요

2023-05-05 10:11 UTC, SightStudio commented on src/main/java/lotto/LottoApplication.java
> +    return LottoGame.ofAutoManualMixed(manualLottoRounds, lottoPrice, gameSetting);
view단과 결합없이 구현할 수 있었네요 분리 완료하였습니다 :)

2023-05-05 10:13 UTC, SightStudio commented on src/main/java/lotto/domain/number/LottoNumber.java
> +    this.number = number;
그렇네요 인티저캐싱같은 느낌으로도 쓸 수 있겠군요! 
인스턴스를 캐싱해보도록 하겠습니다 :)

2023-05-05 10:29 UTC, SightStudio commented on src/main/java/lotto/domain/game/LottoGameGenerator.java
> +  public LottoGameWrapper generateLottoGame() {
테스트 코드를 작성하다보니 이부분의 테스트가 진행하기 어려워 일급객체로 한번 더 래핑을 했는데요 (LottoGameWrapper)
mockito를 써서 verify로 메서드 실행을 검증해야하나 고민을 하다가 래핑으로 적용했습니다.

mock 프레임워크 없이 테스트가 가능한게 더 좋다고 생각하는데 어떻게 생각하시나요?

2023-05-05 10:32 UTC, SightStudio commented
최소에 상속이 필요하다고 생각한 부분은 LottoRound (로또 티켓 하나) 그 자체였는데요.  (수동게임, 자동게임)
생각해보니 그렇게되면 더 복잡하다는 생각이 들었습니다. 
차라리 피드백처럼 게임을 생성 할 때 LottoRound 자체가 자동인지 수동인지 알 필요도 없게 하니 코드를 작성하기 훨씬 간결해진것같네요 :)

2023-05-07 01:35 UTC, Hyeon9mak commented on src/main/java/lotto/domain/round/LottoRound.java
> +  private final LottoGameType gameType;
roundNo 와 같은 정보는 실제 데이터를 구별하기 위한 고유식별자라도, 별개로 관리해주는게 더 편리해보여요.
데이터 중심으로 객체를 설계해두면, 유스케이스 단위로 전달되는 유지보수 요청과 간극이 생겨서 헷갈리더라구요. 👍

2023-05-07 01:58 UTC, Hyeon9mak requested changes
안녕하세요 동민님!
로또(종이) 발급에 대한 객체를 말씀드리고 싶었는데, 
로또게임을 결정하는 객체로 전달되는 오해가 있었던거 같아요 🤣 
다른 부분은 너무 잘 리팩터링해주셨습니다 👍 👍 

복잡도를 살짝 낮추어 테스트를 편하게 작성하는 방법에 대해서만 
가벼운 마음으로 나눠보면 좋을 것 같습니다.
마지막까지 화이팅입니다 💪

2023-05-07 01:58 UTC, Hyeon9mak commented on src/main/java/lotto/domain/game/LottoGame.java
> +    }
로또 발급 과정에 생성자에 포함되어 있기 때문에 테스트 코드 작성이 번거롭지 않나 생각이 들어요. 🤔 
생성자에서 호출하는 로직은 그대로 두되, 발급을 전담하는 객체를 만들면 문제가 해결되지 않을까요?

2023-05-07 01:58 UTC, Hyeon9mak commented on src/main/java/lotto/domain/game/LottoGameGenerator.java
> +  public LottoGameWrapper generateLottoGame() {
동민님께서 테스트 하고 싶은 내용이 "수동/자동 숫자 발급이 잘 되는가" 인 것 같아요.
꼭 LottoGame 이 꼭 수동인지, 자동인지, 아니면 둘 다 인지 타입을 알아야하고 나뉠 필요 없이
총 수량과 수동로또 번호가 전달 되었을 때 수동로또를 먼저 발급하고, 
나머지 수량만큼 자동로또를 발급할 수 있는 별개 객체가 만들어지면 쉽게 해결될 것 같아요.

2023-05-07 01:58 UTC, Hyeon9mak commented on src/main/java/lotto/domain/game/LottoGameWrapper.java
> +    return includeGameTypes;
테스트만을 위해서 프록시가 하나 생겨난 느낌 🥲

2023-05-07 01:58 UTC, Hyeon9mak commented on src/main/java/lotto/domain/number/LottoNumber.java
> +  }
👍 👍 
LottoNumber 는 VO 니까 equals, hashcode  를 오버라이딩 해놓으면 동등성 비교가 쉬워지겠네요.

2023-05-07 07:48 UTC, SightStudio commented on src/main/java/lotto/domain/number/LottoNumber.java
> +  }
아... 어떤뜻인지 이해하였습니다. 
생각해보니 아직 LottoNumber로 래핑하지 못한 곳이 조금 있었네요

2023-05-07 08:05 UTC, SightStudio commented on src/main/java/lotto/domain/game/LottoGame.java
> +    }
그렇네요 생각해보니 이런 책임을 분리하려고 LottoGameGenerator를 만들었는데 
실제로는 로또 발급에 대한 책임이 분리가 안되어있네요

2023-05-07 13:33 UTC, SightStudio commented on src/main/java/lotto/domain/game/LottoGameWrapper.java
> +    return includeGameTypes;
넵  이부분은 로또 라운드 생성에 대한 책임을 분리하고, 자동 수동 구분할 필요가 없다고 생각하니 없어도 되겠네요

2023-05-08 14:52 UTC, Hyeon9mak approved these changes
안녕하세요 동민님! 로또 미션 마지막까지 고생 많으셨습니다!
LottoRoundGenerator 를 분리해주신 덕분에 LottoGame 도 간결해졌고,
자동/수동 로또 발급에 대한 테스트도 굉장히 직관적으로 변신한 것 같아요.
또한 LottoNumber 에 동등성을 부여하여 도메인 전반적인 위치에 사용해주신 덕분에
입/출력을 제외한 모든 곳에서 신뢰도 있게 사용할 수 있게 된 것 같습니다.

요구사항도 잘 충족되었고, 피드백도 너무 잘 반영해주셨습니다.
로또 미션 이만 마무리 하도록 하겠습니다.
피드백 항상 긍정적으로 받아들여주시고 리팩터링 고민해주셔서 감사합니다.
덕분에 너무 즐거운 코드리뷰였습니다.

다음 미션도 화이팅입니다 💪

2023-05-08 14:52 UTC, Hyeon9mak commented on src/test/java/lotto/LottoRoundGeneratorTest.java
> +  }
👍 👍 👍

2023-05-08 14:52 UTC, Hyeon9mak commented on src/main/java/lotto/domain/game/LottoGame.java
>    }
`LottoGame` 이 살이 쪽 빠졌네요 😄 👍

2023-05-08 14:52 UTC, merged