Step4 완료
next-step/java-lotto pull request #3108
Opened 2023-05-05 10:43 UTC by player-geun

안녕하세요 선동님❗️ 마지막 리뷰 잘 부탁드립니다 😁 몇 가지 질문사항 남겨 놓을게요!!
1. 선동님은 메서드의 파라미터에도 `final` 키워드를 붙이시나요..??
2. `LottoTicketMachine` 에서 정적 팩토리 메서드 안의 로직에 정적 인스턴스 변수에 값을 할당하는 부분이 존재합니다. 해당 로직이 팩토리 메서드에 같이 있어도 괜찮을까요..??
3. 정적 팩토리 메서드 특성상 검증 로직을 추가하고 싶다면, 해당 검증 메서드도 `static` 으로 선언해야 하는데 너무 많은 `static` 메서드가 만들어지는 것이 아닐까 싶어 조심스럽습니다..! 이 부분 괜찮을까요..??

2023-05-06 05:21 UTC, seondongpyo requested changes
마지막 단계도 잘 작성해주셨네요 👍 
몇 가지 고민해보실만한 부분에 대해 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다.
연휴 잘 보내시고 조금만 더 힘내주세요 🔥

2023-05-06 05:21 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoTicketMachine.java
>  public class LottoTicketMachine {
`LottoTicketMachine`의 이름만 봤을 땐, 로또 티켓을 발매해주는 자동판매기와 같은 느낌이 듭니다.
금액을 투입하고 구매할 매수와 번호들을 입력하면 원하는 매수만큼 로또 티켓(LottoTickets)을 반환해주는 역할을 할 것 같은데
내부에서 당첨 여부까지 계산해서 결과를 반환해주는 역할도 수행하고 있습니다.
`LottoTicketMachine`의 책임과 역할을 어디까지 부여할지 고민해보시면 좋을 것 같아요.

2023-05-06 05:21 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoTickets.java
> +        this.lottoTickets = lottoTickets;
외부에서 사용되지 않는 생성자로 보이는데, 제거해도 될 것 같아요.

2023-05-06 05:21 UTC, seondongpyo commented on src/main/java/lotto/controller/LottoController.java
> +        lottoTicketMachine.createAutoLottoTickets(autoPurchaseCount);
해당 일련의 과정을 로또 티켓 발급을 담당하는`LottoTicketMachine` 내부로 옮겨보는 건 어떨까요?
`LottoTicketMachine`에게 수동 티켓과 자동 티켓을 발급하도록 일일이 메시지를 보내지 않아도 된다면
`LottoTicketMachine`을 사용하는 다른 개발자 입장에서 훨씬 편안한 느낌을 받을 수 있을 것 같아요.
마치 라이브러리를 만든다고 생각하고 사용하기 편한 API를 제공하는 입장으로 리팩토링해보면 어떨까 생각합니다.

2023-05-06 05:26 UTC, seondongpyo commented
> 선동님은 메서드의 파라미터에도 final 키워드를 붙이시나요..??

소속된 팀에 따라 다르겠지만, 저는 보통 `final` 키워드는 붙이지 않습니다.

> 정적 팩토리 메서드 특성상 검증 로직을 추가하고 싶다면, 해당 검증 메서드도 static 으로 선언해야 하는데 너무 많은 static 메서드가 만들어지는 것이 아닐까 싶어 조심스럽습니다..! 이 부분 괜찮을까요..??

1~2개 정도라면 괜찮다고 생각하는데,  그 이상이라면 보통 해당 클래스를 조금 더 작게 분리해볼만한 여지가 있다고 생각합니다.
클래스를 작게 유지하면 그만큼 검증 메서드를 많이 갖지 않을테니, 클래스를 더 분리해 볼 여지는 없는지 고민해보시면 좋을 것 같아요.

2023-05-07 00:53 UTC, player-geun commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +    public LottoTicketMachine(LottoTickets lottoTicketsTotal) {
LottoController 에서 사용하고 있습니다!

2023-05-07 00:57 UTC, player-geun commented on src/main/java/lotto/domain/LottoTickets.java
> +        this.lottoTickets = lottoTickets;
라이브 시간에 포비님이 주생성자를 통해서 부생성자를 호출하는 방식으로 하라고 말씀하신 것 같아서 이렇게 진행했습니다! 만약 주생성자를 사용하지 않는다면, 부생성자만 만들어도 될까요?? 저는 부생성자를 사용하려면 주생성자를 무조건 만들어야 한다고 이해했었습니다!

2023-05-07 01:17 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +    public LottoTicketMachine(LottoTickets lottoTicketsTotal) {
13라인의 기본 생성자는 사용 중인데, 16라인의 생성자는 사용되지 않는 것으로 보여요.

2023-05-07 01:55 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoTickets.java
> +        this.lottoTickets = lottoTickets;
주생성자라면 말 그대로 주(main)로 사용되어야 할 것 같은데, 그렇지 않은 것 같아서 말씀 드려봤어요.
주로 사용할 정적 팩토리 메서드를 추가하고, 생성자는 접근 제어자를 `private`으로 변경하는 것도 방법일 것 같습니다.
https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2023-05-07 04:55 UTC, player-geun commented
안녕하세요 선동님 😁 피드백 반영하였습니다 ❗️ 질문사항 남겨놓도록 할게요 :)
1. 생성자에는 로직이 많이 들어가면 안되는 것으로 알고있는데, `LottoTicketMachine` 의 생성자 정도는 괜찮을까요??

2023-05-08 01:16 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍 
크게 드릴 말씀은 없어서 마지막 단계는 여기서 merge 하겠습니다.
그동안 로또 미션 진행하시느라 고생 많으셨습니다.
마지막 미션까지 파이팅하시길 응원하겠습니다 🔥

2023-05-08 01:16 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +    public void createLottoTickets(List<List<Integer>> tickets) {
메서드 이름처럼 로또를 생성하고 이를 반환하는 구조로 변경해봐도 좋을 것 같아요.
```suggestion
    public LottoTickets createLottoTickets(List<List<Integer>> tickets) {
```

2023-05-08 01:16 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +        if (tickets.size() == 0) {
`List`의 `isEmpty()`를 활용해봐도 좋을 것 같아요.
```suggestion
        if (tickets.isEmpty()) {
```

2023-05-08 01:21 UTC, seondongpyo commented on src/main/java/lotto/domain/LottoTicketMachine.java
> +    public LottoTicketMachine(int manualPurchaseCount, int purchaseAmount) {
> 생성자에는 로직이 많이 들어가면 안되는 것으로 알고있는데, LottoTicketMachine 의 생성자 정도는 괜찮을까요??

`autoPurchaseCount`를 상태로 유지할 필요가 있을지 고민해보시면 좋을 것 같아요.
금액이 투입되고 수동 매수와 로또 번호를 입력 받았을 때 해당 검증 로직을 수행해도 충분하지 않을까 생각합니다.

2023-05-08 01:21 UTC, merged