[step1, step4] 문자열 계산기, 로또 수동
next-step/java-lotto pull request #3147
Opened 2023-05-08 08:54 UTC by SeokkAng

안녕하세요~
4단계 로또 수동 PR 입니다.

step1이 지난 자동차 경주와 동일한건줄 착각해서 진행을 안했는데요.
확인해보니 달라서 이번에 같이 코드 올렸습니다!

같이 확인 부탁드립니다!

감사합니다!

2023-05-09 17:09 UTC, brainbackdoor requested changes
마지막 단계 미션 진행 및 피드백 반영하느라 고생하셨어요~ 👍🏻 
몇가지 리팩토링 도전할만한 부분이 보여 Comment 남겨두었는데요.
확인해보시고 혹시 추가 설명이 필요하시면 DM 남겨주세요~
좋은 하루 보내세요~

2023-05-09 17:09 UTC, brainbackdoor commented on src/main/java/lotto/step4/domain/WinningNumbers.java
> +    }
```suggestion
    private Rank matchLotto(Lotto lotto) {
        int matchCount = lotto.matchCount(winningNumbers);
        boolean matchBonus = lotto.contains(bonusNumber);
        return Rnak.of(matchCount, matchBonus);
    }
```
- https://github.com/next-step/java-lotto/pull/3096#discussion_r1186790882 에 질문 남기신거 확인이 늦었군요. 위와 같이 작성해보면 어떨까요

2023-05-11 12:17 UTC, SeokkAng commented on src/main/java/lotto/step1/domain/Calculator.java
> +    private final Deque<String> mathOperationQueue = new ArrayDeque<>();
아하 네네! 원시값으로 포장 적용했습니다!
객체를 작은 단위로 쪼개는 생각을 할 수 있어서 좋았습니다!
감사합니다!

2023-05-11 12:17 UTC, SeokkAng commented on src/main/java/lotto/step4/Test.java
> +    }
앗 지운줄알았는데, 감사합니다!ㅜㅜ

2023-05-12 17:50 UTC, SeokkAng commented on src/main/java/lotto/step4/domain/LottoCount.java
> +    private final List<Lotto> lottoFromManual;
그러네요... 
Lottos에 위임하여 수정하였습니다!
피드백 너무 감사합니다!

2023-05-12 17:52 UTC, SeokkAng commented on src/main/java/lotto/step4/domain/WinningNumbers.java
> +    }
이렇게 하니깐 훨씬 좋네요...
힌트를 주시면 금방 알겠는데, 혼자할때는 자꾸 이상한길로 뺑뺑 돌아서 작업하는거 같네요 ㅠㅠ
피드백 감사합니다!

2023-05-12 17:54 UTC, SeokkAng commented
@brainbackdoor 
피드백 주신것들 수정했습니다!
다시한번 꼼꼼한 피드백 감사드려요! 👍 👍

2023-05-14 06:15 UTC, brainbackdoor approved these changes
피드백 반영 확인했어요~ 👍🏻 
로또 미션이 성장에 유의미한 시간이었길 바래요~
주일 잘 보내세요~

2023-05-14 06:15 UTC, merged

2023-05-14 13:22 UTC, SeokkAng commented
@brainbackdoor 
감사합니다~
알려주신것들 도움 많이 됐고 메모도 하면서 다시 리마인드 했습니다 ㅎㅎ
행복한 주일되세요~