Step2 리뷰요청 드립니다.
next-step/java-lotto pull request #3151
Opened 2023-05-08 12:47 UTC by woorido

안녕하세요. 피효정입니다.
기능에 비해 테스트 코드가 부족하다고 느껴지는데, 맞을까요?
테스트 코드 작성이 어렵다는건, 함수 분리가 잘 안된 것이라고 배웠습니다. 
잘 부탁드립니다!

2023-05-09 13:48 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 참고 부탁드립니다.

2023-05-09 13:48 UTC, kyucumber commented on README.md
>  ## 온라인 코드 리뷰 과정
> 테스트 코드 작성이 어렵다는건, 함수 분리가 잘 안된 것이라고 배웠는데 맞을까요?

말씀하신 부분이 어느정도 맞아요. 하지만 다양한 케이스가 있을 수 있습니다.

로직 자체에 랜덤이나 I/O 등이 들어가 테스트 하기 까다로울 수 있고, 말씀하신 것 처럼 함수 하나에 너무 많은 책임이 들어가있어서 그럴수도 있고 이외에 if 같은 분기문이 많으면 모든 케이스를 다 테스트가 어려울 수 있어요.

2023-05-09 13:48 UTC, kyucumber commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
로또라는 특성이 있어서 상관은 없을 수 있는데요.
`List<Integer>`를 래핑한 일급 컬렉션 형태기 때문에 LottoNumbers가 더 적절하지 않을까 하는 의견이 있네요.

2023-05-09 13:48 UTC, kyucumber commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int getHitCount(List<Integer> winningLotto) {
여기서 int를 반환하는게 아니라 Rank를 반환하면 다른 쪽의 책임이 줄어들 수 있지 않을까요?

`LottoNumber`가 `Rank`와 결합이 생긴다는 단점이 있겠지만 두 클래스 모두 연관도가 높기 때문에 추가로 결합이 되고 다른 쪽의 책임을 줄이는게 더 나은 방향일수도 있을 것 같아요. 한번 고민해보시면 좋겠네요.

2023-05-09 13:48 UTC, kyucumber commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int getHitCount(List<Integer> winningLotto) {
winningLotto도 동일한 로또인데요. LottoNumber와 동일한 특성(1 - 45 사이, 6개)을 가집니다.
파라미터로 `List<Integer>`가 넘어오기 때문에 7개의 숫자가 넘어오거나 45를 넘는 숫자가 들어올수도 있을 것 같은데요. `WinningNumber`를 사용하는건 어떨까요?

2023-05-09 13:48 UTC, kyucumber commented on src/main/java/lotto/domain/LottoShop.java
> +    }
Stream.generate를 활용해 볼 수 있지 않을까요?

2023-05-09 13:48 UTC, kyucumber commented on src/main/java/lotto/domain/result/WinCount.java
> +    }
plusOne 등 메서드 명이 조금 더 구체적이어야 할 것 같습니다.

2023-05-09 13:48 UTC, kyucumber commented on src/main/java/lotto/domain/WinningNumber.java
> +        }
당첨 번호든, 로또 번호든 둘다 동일하게 6개 그리고 1 - 45까지의 제약을 가지는 부분은 동일합니다.

`LottoNumber`와 중복이 있는 것 같은데 중복을 제거할 수 없을까요?

2023-05-11 13:02 UTC, woorido commented on src/main/java/lotto/domain/result/LottoResult.java
> +    private final WinCount winCount;
Long 을 어떤 값으로 사용하라는 의미일까요?

2023-05-11 18:17 UTC, woorido commented
'Rank 반환' 말씀 주신 것과 'Map<Rank, Long> 사용' 말씀 주신 부분이 같은 맥락일까요?
저 두 부분이 잘 이해가 안가는데, 조금만 더 설명해주실 수 있을까요?
잘 부탁드립니다!

2023-05-13 14:11 UTC, kyucumber commented
1. Rank 반환

```java
public Rank getRank(List<Integer> winningLotto) {
```

지금 getHitCount 호출 이후에 hitCount로 Rank를 다시 찾고 있는데 그 로직이 흩어져 있는 것 보다 위처럼 getRank로 관리하면 어떨까 싶어 말씀드렸습니다.

3. `Map<Rank, Long>` 사용

위와 같이 Map 자료구조에 FIRST:1000, SECOND:2100 이렇게 당첨 결과를 Map 형태로 저장하는건 어떨까 해서 말씀드렸습니다. Stream을 활용하면 groupBy 등을 통해 간단하게 저 형태로 데이터를 추출하는것도 가능할 것 같아요.

2023-05-13 14:13 UTC, kyucumber requested changes
안녕하세요. 

남겨두신 질문에 코멘트 남겨두었어요. 참고 부탁드립니다.

2023-05-13 14:13 UTC, kyucumber commented on src/main/java/lotto/domain/ExceptionHandler.java
> +        if(overNumber.isPresent()) {
`if ( `, `if(`와 같이 코드가 일관성이 없는데요.

IDE의 자동 정렬 기능들을 습관적으로 사용하시거나 해서 포맷을 맞춰 주시면 좋을 것 같아요

2023-05-16 05:05 UTC, woorido commented on src/main/java/lotto/domain/ExceptionHandler.java
> +        if(overNumber.isPresent()) {
감사합니다. 자동 정렬 기능을 습관적으로 사용해야겠어요!

2023-05-16 05:11 UTC, woorido commented
안녕하세요.
말씀 주신 것처럼 수정해봤습니다.
두 부분 모두 말씀하신 의도에 맞게 수정했는지 확인 부탁드립니다. 
특히 Map<Rank, Long> 사용하여 LottoResult 를 재구현 해봤는데, 
1. LottoResult 의 getKey() 와 getValue() 를 사용하여 LottoResults 의 groupingByLottoResult() 를 구현한 부분과
2. ResultView 에서 groupingByLottoResult() 의 리턴 값을 이용한 부분이 
의도에 맞게 수정된 것인지 궁금합니다.
오늘도 잘 부탁드립니다!

2023-05-16 12:08 UTC, woorido commented
안녕하세요.
말씀 주신 것처럼 수정해봤습니다.
두 부분 모두 말씀하신 의도에 맞게 수정했는지 확인 부탁드립니다.
특히 Map<Rank, Long> 사용하여 LottoResult 를 재구현 해봤는데,

LottoResult 의 getKey() 와 getValue() 를 사용하여 LottoResults 의 groupingByLottoResult() 를 구현한 부분과
ResultView 에서 groupingByLottoResult() 의 리턴 값을 이용한 부분이
의도에 맞게 수정된 것인지 궁금합니다. 그리고 테스트코드도 잘 작성했는지 의견 부탁드립니다.
오늘도 잘 부탁드립니다!

2023-05-16 13:40 UTC, kyucumber approved these changes
안녕하세요.

몇가지 코멘트 남겨두었는데요, 다음 단계 진행에 참고 부탁드립니다.

2023-05-16 13:40 UTC, kyucumber commented on src/main/java/lotto/domain/result/LottoResults.java
> +    public List<LottoResult> lottoResults;
이미 아래 자료 구조가 LottoResult안에 들어있는데 또 한번 더 List로 감쌀 이유가 있을까요?

```java
private Map<Rank, Long> result;
```

2023-05-16 13:40 UTC, kyucumber commented on src/main/java/lotto/domain/result/LottoResults.java
> +    public List<LottoResult> lottoResults;
해당 자료구조는 1, 2, 3, 4, 5등에 해당하는 Rank 별 당첨 횟수를 저장할 수 있습니다.
여기서 또 `List`로 한번 더 감싼 `LottoResults`가 필요한 이유가 있을지 한번 더 고민해보시면 좋겠네요.

2023-05-16 13:40 UTC, kyucumber commented on src/main/java/lotto/domain/Lottos.java
> +        }
이렇게 win을 하나씩 호출하는 형태가 아니라 `List<Lotto>` -> `List<Rank>`로 변환 후 거기서 스트림을 통해 `Map<Rank, Long>` 형태로 변환하시는 걸 스트림을 이용해서 한번 추출해보시면 좋겠네요.

2023-05-16 13:40 UTC, merged