Step3 리뷰 요청 드립니다
next-step/java-lotto pull request #3162
Opened 2023-05-09 07:33 UTC by wsdf25867

안녕하세요 광현님 step3 리뷰 요청 드리겠습니다!

나름 view 와 도메인을 분리해 봤는데 잘된 건지 모르겠네요

이제 보니 `LottoStore`가 굳이 있어야 하나 싶어요

피드백 부탁드립니다!

2023-05-09 10:58 UTC, nokchax requested changes
안녕하세요, 지우님!
세번째 단계도 잘 구현해 주셨네요 👍
다만 아직 view를 분리하지 못했어요,
관련해서 코멘트 남겼으니 확인 부탁드립니다 🙇

2023-05-09 10:58 UTC, nokchax commented on src/main/java/lotto/LottoGame.java
> +        RankResult rankResult = lottoBuyer.checkWinning(winningLotto, bonus);
LottoGame 내부의 start()함수에 있는 내용을 보면 전반적인 흐름을 제어하고 있는데요,
그러면서 input과 output에 관련된 view 코드가 포함되어버렸네요.
흐름 제어는 LottoApplication(controller)에서 하는게 어떨까요?

2023-05-09 10:58 UTC, nokchax commented on src/main/java/lotto/domain/LottoBuyer.java
> +    public RankResult checkWinning(Lotto winningLotto, LottoNumber bonus) {
winningLotto 와 LottoNumber를 하나로 합쳐서
WinningLotto 라는 클래스는 만들어 보는 건 어떨까요?

2023-05-09 10:58 UTC, nokchax commented on src/main/java/lotto/domain/Lottos.java
> +        return lottos.stream()
스트림을 잘 활용해주셨네요 👍

2023-05-09 10:58 UTC, nokchax commented on src/main/java/lotto/domain/Rank.java
> +    MISS(0, new Money(0L), "");
'x개 일치 (xxx원)- %d개'
는 콘솔 로또 게임에서만 활용하고 있는 문자열 입니다.
만약 요구사항이 바뀌어서, 출력할때의 문구를 바꾸면, 이 Rank라는 도메인도 함께 수정을 해야겠네요
도메인에서 view를 분리한다는 의미는 view의 변경이 발생 했을때, 도메인에서는 수정이 일어나서는 안 됨을 뜻 합니다.

2023-05-09 10:58 UTC, nokchax commented on src/main/java/lotto/domain/Rank.java
> +        }
매칭에 대한 로직을 필드로 뺄 수 없을까요?

2023-05-09 10:58 UTC, nokchax commented on src/test/java/stringcalculator/OperatorTest.java
> +        assertThat(Operator.of("-")).isEqualTo(Operator.MINUS);
저도 놓쳤네요 ㅎㅎ 👍

2023-05-11 13:59 UTC, wsdf25867 commented on src/main/java/lotto/LottoGame.java
> +        RankResult rankResult = lottoBuyer.checkWinning(winningLotto, bonus);
아하 넵 다음 리뷰에 반영해 보겠습니다!

2023-05-12 11:25 UTC, closed without merging