Lotto/step3 second
next-step/java-lotto pull request #3176
Opened 2023-05-11 11:56 UTC by Laminett

### Lotto - 2등
* 보너스 숫자  포함하여 등수계산 하도록 추가하였습니다.
* 지난 단계 코멘트 주신부분 반영하였습니다.
* 반영을 한다고 했는데 억지스러운 부분이 생긴 것 같습니다..

아 그리고 TDD를 하려고 하는데.. 테스트부터가 아닌 로직부터 작성하고 로직에 맞춰서 테스트를 작성하게 되서 쉽지 않네요..
혹시 팁같은게 있으시면 부탁드려도 될까요? 감사합니다~! 🙇

2023-05-11 16:20 UTC, nooose requested changes
코멘트 남겼으니 확인해 보시고 재요청 부탁드립니다!
(답변도 남겼어요!)

---

> 반영을 한다고 했는데 억지스러운 부분이 생긴 것 같습니다..

정확히 어떤 부분이 그런지 코멘트 남겨주시면 제가 추가 코멘트 남겨 놓겠습니다!

> 아 그리고 TDD를 하려고 하는데.. 테스트부터가 아닌 로직부터 작성하고 로직에 맞춰서 테스트를 작성하게 되서 쉽지 않네요..
혹시 팁같은게 있으시면 부탁드려도 될까요? 

이 부분은 저도 처음에 어려웠고 어렵게 느끼시는 것이 정상입니다.
연습과 시간이 필요하고 단기간 내에 변하기에는 어렵겠죠?
테스트 코드부터 작성하기 어렵다면 일단 로직부터 작성하고 나중에 테스트 코드를 작성하는 것도 방법입니다. 
그런데 지금 상황에서 아쉬운 부분들이 있어 보여요
현재 경일님이 README 마크다운 문서에 작성하신 요구사항 목록을 봤을 때 너무 추상화시켜서 작성하신 것 같아요
사실 내부적으로 보면 필요한 부분들이 더 많습니다.

예를 들어 다음과 같은 요구사항들이 나올 수 있습니다.
- 로또 번호 6개인지 검증
- 로또 숫자 범위는 1 ~ 45
- 로또 숫자 범위를 벗어나면 예외를 던진다.
- 등등...

이 처럼 세부적으로 작성할 수 있습니다.

미리 요구사항을 상세하게 적고 작성한 요구사항에 따라 테스트 코드를 작성한다면
이전보다는 쉽게 작성할 수 있을거에요 😄

2023-05-12 10:46 UTC, Laminett commented on src/main/java/lottoauto/model/Constant.java
> +        public static final String DELEGATOR = ",";
상수 응집도 라는건 전혀 생각하지 못했습니다..그냥 쓰는 상수 클래스에 분류를 나누기 위해 내부에 추가로 클래스를 선언했는데 이게 오히려 독이 되었네요..

2023-05-12 10:47 UTC, Laminett commented on src/main/java/lottoauto/model/Lotto.java
>          return Objects.hash(numbers);
테스트 상에서 lotto의 비교를 위해서 재정의 하게 되었습니다

2023-05-12 10:49 UTC, Laminett commented on src/main/java/lottoauto/model/WinningReward.java
> +    MATCH_6(6, 2000000000, "6개 일치 (2_000_000_000원)");
지난번과 똑같은 실수를 범했네요. 사실 2등의 `5개 일치, 보너스 숫자 일치` 때문에 enum에 출력문자를 사용하게 되었습니다.
match와 reward만으로 2등을 표현할 수 있는 방법이 있을까요?

2023-05-12 10:50 UTC, Laminett commented on src/test/java/lottoauto/LottoFixture.java
> +    public static List<Integer> intListFixture() {
자료구조가 변경될꺼라는 생각은 하지 못하였네요. 다만 테스트에서 사용하는 객체이고 Fixture가 크게 변경되지 않을 것 같아서 좀 더 명확하게 표현하기 위해서 사용하게 되었습니다 😢

2023-05-12 10:51 UTC, Laminett commented on src/main/java/lottoauto/model/WinningLotto.java
>      private void winningNumberValidation(List<Integer> winningNumber) {
winningLotto는 사용자가 직접 입력하는 반면에 lotto는 범위를 지정하여 셔플 후 6자리만 잘라내기 때문에 특별하게 검증을 해야 할 생각은 못했네요 😨

2023-05-13 07:59 UTC, nooose commented on src/main/java/lottoauto/model/WinningLotto.java
>      private void winningNumberValidation(List<Integer> winningNumber) {
다른 개발자가 생성자를 사용해서 번호가 8개, 10개인 로또를 만들 수 있으니 생성자에서 검증을 하는 것이 좋아요!

2023-05-13 08:04 UTC, nooose commented on src/main/java/lottoauto/model/Lotto.java
>          return Objects.hash(numbers);
테스트 코드 검증을 위해 프로덕션 코드를 수정하는 방법이 맞냐 아니냐는 의견이 항상 갈리는 것 같아요
저는 개인적으로 설득을 제대로 할 수 있다면 사용가능하다고 생각합니다.
이런 부분들은 항상 염두하시고 사용하시면 좋을 것 같습니다.

2023-05-13 08:07 UTC, nooose commented on src/main/java/lottoauto/model/WinningReward.java
> +    MATCH_6(6, 2000000000, "6개 일치 (2_000_000_000원)");
정답은 없지만 Enum이 가지는 변수에 bonus 필드를 넣어서 체크 후 보너스 일치 문자열을 출력하는 방법이 있고,
`MATCH_5_BONUS` 타입인 경우에는 보너스 일치라는 문자열을 추가 출력할 수 있지 않을까요?

2023-05-13 08:08 UTC, nooose commented on src/test/java/lottoauto/LottoFixture.java
> +    public static List<Integer> intListFixture() {
넵. 사실 거의 변경이 없겠지만 😅 자료구조에 의존한 변수명은 좋은 방향은 아닌 것 같습니다

2023-05-14 05:38 UTC, Laminett commented on src/test/java/lottoauto/LottoFixture.java
> +    public static List<Integer> intListFixture() {
넵 앞으로 자료구조에 의존되는 변수명은 지양하겠습니다 감사합니다 🙇

2023-05-14 05:42 UTC, Laminett commented on src/main/java/lottoauto/model/Lotto.java
>          return Objects.hash(numbers);
다시 소스를 확인해보니 객체를 비교하는 테스트는 삭제하고 재정의 부분은 삭제하지 못한 것 같네요 😓  삭제하였습니다~!

2023-05-14 05:46 UTC, Laminett commented
유틸 클래스나 상수를 선언할 때 항상 고민되는 부분이 static에 대한 부분인데요. static 변수나 메소드들은 메모리에 올라가서 사용되는 걸로 인식하고 있습니다(잘못된 부분이라면 말씀주세요!). 물론 무분별하게 사용하는거는 잘못되고, 서비스마다 많은 차이가 있겠지만, 어느정도까지의 사용을 대비하여 사용해야 할까요? 그리고 지금 하드웨어 성능이 많이 좋아져서 메모리에 올라가는 수준은 신경 안써도 되는 수준인지 성준님의 의견이 궁금합니다. 🙇

2023-05-14 06:36 UTC, nooose commented
> 유틸 클래스나 상수를 선언할 때 항상 고민되는 부분이 static에 대한 부분인데요. static 변수나 메소드들은 메모리에 올라가서 사용되는 걸로 인식하고 있습니다(잘못된 부분이라면 말씀주세요!). 물론 무분별하게 사용하는거는 잘못되고, 서비스마다 많은 차이가 있겠지만, 어느정도까지의 사용을 대비하여 사용해야 할까요? 그리고 지금 하드웨어 성능이 많이 좋아져서 메모리에 올라가는 수준은 신경 안써도 되는 수준인지 

네 static 변수나 메서드는 프로그램의 시작 부터 종료까지 메모리에 존재하게 됩니다.
GC에 의해 관리되지않기 때문에 사용을 하지 않아도 제거또한 되지 않습니다.
말씀대로 무지성 static으로 떡칠하지 않는 이상 큰 영향이 없을 것 같습니다.
제 경험상 성능 문제는 애플리케이션도 물론 있지만 대부분 외부 인프라(DB, 네트워크, 외부 시스템) 요소에서 결정되는 것 같아요

제 개인적인 의견이지만, static 변수나 메서드로 인해 걱정될 정도의 민감한 서비스라면
 JVM 계열이 아닌 다른 언어를 고려해야 할 것 같은 생각도 듭니다.

> 성준님의 의견이 궁금합니다. 🙇

성준혁입니다. 😅😭

2023-05-14 06:40 UTC, nooose requested changes
잘 반영해 주셨는데요
약간 아쉬운 부분들이 있네요
해당 부분 빠르게 수정하고 넘어가도록 해요

재요청 주시면 빠르게 보도록 하겠습니다!

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/utils/ViewUtils.java
> +
Inner 클래스로 Input, Output 두 가지를 가지기보다는
이전 처럼 InputView, OutputView를 따로 관리하는 것이 유지보수 관점에서 좋습니다.

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/utils/ValidationUtils.java
> +
로또 금액 체크를 위해 따로 분리하신 것 같아요
LottoRequest 같은 클래스를 만들고 이 클래스에서 validation 체크 후 수량을 구할 수 있지 않을까요?

util 패키지에 위치한 클래스들은 어디에서나 범용적으로 사용할 때 사용하는 것 같습니다.

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/domain/LottoService.java
>          }
서비스 내에서 로직을 전개하는 방식보다는
```java
LottoResult result = winningLotto.result(lottos); 
```
도메인이 직접 처리하도록 변경할 수 있을 것 같아요

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/model/Lotto.java
> +            throw new IllegalStateException("로또의 숫자가 6개가 아닙니다.");
생성자에서 호출하고 있으니 생성자 아래에 있는 getNumbers 메서드 위치와 바뀌면 좋을 것 같아요

혹시 메서드 배치 순서를 정하실 때 경일님만의 규칙이 있나요?

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/model/Lotto.java
> +        if (lotto.size() != 6) {
로또와 헷갈릴 수 있으니 변수명을 적절하게 변경하면 좋을 것 같습니다.

```suggestion
    private void lottoValidation(List<Integer> lottoNumbers) {
        if (lotto.size() != 6) {
```

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/model/WinningLotto.java
> +        boolean existBonus = lotto.getNumbers().contains(bonusNumber);
```suggestion
        boolean existBonus = lotto.contains(bonusNumber);
```

디미터 법칙을 지키지 않고 있는 것 같아요
lotto가 직접 처리할 수 있을 것 같아요

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/model/WinningLotto.java
> +        if (matchNumbers.size() == 5) {
매직넘버가 포함된 것 같아요 🥲

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/model/WinningReward.java
> +    MATCH_6(6, 2000000000, false);
```java
MATCH_5_BONUS.hasBonus(); // true
```
getBonus 보다 좀 더 자연스러운 메서드 명을 쓰면 좋을 것 같아요

2023-05-14 06:40 UTC, nooose commented on src/main/java/lottoauto/model/WinningReward.java
> +                .filter(x -> x.matchCount == match)
축약된 변수명이 보이네요 변경하면 좋을 것 같습니다 😄

2023-05-14 09:20 UTC, Laminett commented
> > 유틸 클래스나 상수를 선언할 때 항상 고민되는 부분이 static에 대한 부분인데요. static 변수나 메소드들은 메모리에 올라가서 사용되는 걸로 인식하고 있습니다(잘못된 부분이라면 말씀주세요!). 물론 무분별하게 사용하는거는 잘못되고, 서비스마다 많은 차이가 있겠지만, 어느정도까지의 사용을 대비하여 사용해야 할까요? 그리고 지금 하드웨어 성능이 많이 좋아져서 메모리에 올라가는 수준은 신경 안써도 되는 수준인지
> 
> 네 static 변수나 메서드는 프로그램의 시작 부터 종료까지 메모리에 존재하게 됩니다. GC에 의해 관리되지않기 때문에 사용을 하지 않아도 제거또한 되지 않습니다. 말씀대로 무지성 static으로 떡칠하지 않는 이상 큰 영향이 없을 것 같습니다. 제 경험상 성능 문제는 애플리케이션도 물론 있지만 대부분 외부 인프라(DB, 네트워크, 외부 시스템) 요소에서 결정되는 것 같아요
> 
> 제 개인적인 의견이지만, static 변수나 메서드로 인해 걱정될 정도의 민감한 서비스라면 JVM 계열이 아닌 다른 언어를 고려해야 할 것 같은 생각도 듭니다.
> 
> > 성준님의 의견이 궁금합니다. 🙇
> 
> 성준혁입니다. 😅😭

아..너무 죄송합니다 큰 결례를 범했습니다...ㅠㅠ 죄송합니다 😢

2023-05-14 09:24 UTC, Laminett commented on src/main/java/lottoauto/utils/ValidationUtils.java
> +
특정한 동작을 하기위한 유틸을 모아서 사용한다고 생각했었는데 말씀하신 방향이 더 맞는 것 같습니다. 감사합니다!

2023-05-14 09:40 UTC, Laminett commented on src/main/java/lottoauto/model/Lotto.java
> +            throw new IllegalStateException("로또의 숫자가 6개가 아닙니다.");
특별하게 규칙을 정하고 있진 않은데 보통 접근제어자를 기준으로해서 퍼블릭-프라이빗 순으로 작성해왔었는데요.
준혁님 말씀을 듣고 생각해보니 관련이 있는 메소드들 끼리 붙어있으면 소스확인이 편할 것 같습니다. (이전에 작성했던 방식은 위아래는 많이 왔다 갔다 했었네요..) 😶‍🌫️

2023-05-14 09:49 UTC, Laminett commented on src/main/java/lottoauto/model/WinningLotto.java
> +        boolean existBonus = lotto.getNumbers().contains(bonusNumber);
아..자꾸 잊게 되네요..감사합니다!

2023-05-14 12:20 UTC, nooose approved these changes
피드백이 많았는데요
반영해 주시느라 수고 많으셨습니다.

코멘트 확인해 보시고 마지막 4단계 진행해 주세요!

2023-05-14 12:20 UTC, nooose commented on src/main/java/lottoauto/model/Lotto.java
>          this.numbers = numbers;
오라클에서 제공하는 컨벤션 가이드가 있으니 [링크](https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html#11684) 확인해 보시면

필드 다음 생성자, 메서드 순인데요
관례를 따라주시면 다른 사람이 소스 코드를 읽는데 있어서 더 편해질 것 같습니다.

2023-05-14 12:20 UTC, nooose commented on src/main/java/lottoauto/model/Lotto.java
>          this.numbers = numbers;
```java
    public Lotto(List<Integer> numbers) {
        lottoValidation(numbers);
        this.numbers = numbers;
    }

    private void lottoValidation(List<Integer> lottoNumber) {
        if (lottoNumber.size() != LOTTO_LIMIT_SIZE) {
            throw new IllegalStateException("로또의 숫자가 6개가 아닙니다.");
        }

        HashSet<Integer> distinctNumbers = new HashSet<>(lottoNumber);
        if (distinctNumbers.size() != LOTTO_LIMIT_SIZE) {
            throw new IllegalStateException("중복되는 숫자가 있습니다.");
        }
    }

    public static Lotto auto() {
        List<Integer> lottoNumbers = new ArrayList<>(LOTTO_NUMBER_RANGE);
        Collections.shuffle(lottoNumbers);
        lottoNumbers = lottoNumbers.subList(0, 6);
        Collections.sort(lottoNumbers);

        return new Lotto(lottoNumbers);
    }

```

생성자는 생성, 검증 역할만 하고 자동 로또는 `정적 팩터리 메서드`를 사용해서 생성하는 것이 어떨까요??

2023-05-14 12:20 UTC, nooose commented on src/main/java/lottoauto/domain/LottoService.java
> +    public Lottos generateLottoNumber(int quantity) {
생성한 LottoRequest를 받아서 처리할 수 있을 것 같습니다
```suggestion
    public Lottos generateLottoNumber(LottoRequest request) {
```

2023-05-14 12:20 UTC, nooose commented on src/main/java/lottoauto/view/InputView.java
> +    public static final String INPUT_BONUS = "보너스 숫자를 입력해 주세요";
외부에서 사용하지 않는다면 private 으로 접근 제한범위를 줄여볼 수 있겠네요

2023-05-14 12:20 UTC, nooose commented on src/main/java/lottoauto/model/WinningLotto.java
> +
이 부분도 앞선 피드백대로 메서드 위치를 변경해 볼 수 있겠네요 😄

2023-05-14 12:22 UTC, merged