Step3: 로또 당첨 2등
next-step/java-lotto pull request #3211
Opened 2023-05-15 09:18 UTC by seonuk

로또 보너스 기능 추가 구현

2023-05-16 00:29 UTC, mskangg requested changes
2등 요구사항을 특별한 변경사항없이 깔끔하게 잘 구현해주셨네요 👏 
몇가지 피드백 남겨드렸으니 확인부탁드려요!

2023-05-16 00:29 UTC, mskangg commented on src/main/java/lotto/Lotto.java
> +        winningNumbers.add(bonus);
List<Integer> winningNumbers 는 클래스로 만들지 않았네요 🤔 
WinLotto 와 같이 객체화해서 비즈니스를 캡슐화할 수 있을 것 같아요 😄

2023-05-16 00:29 UTC, mskangg commented on src/main/java/lotto/Lotto.java
> +    }
> List winningNumbers 는 클래스로 만들지 않았네요 🤔
WinLotto 와 같이 객체화해서 비즈니스를 캡슐화할 수 있을 것 같아요 😄

위 리뷰의 연장선인데, WinLotto 클래스가 있다면 당첨로또에게 메세지를 보내어 보너스 유무를 확인할수 있지 않을까요?

2023-05-16 00:29 UTC, mskangg commented on src/main/java/lotto/LottoStatistics.java
> +        FIFTH(BigDecimal.valueOf(5_000), 3),
당첨타입 enum은 당첨에대한 상태를 온전히 갖고있는게 좋아보여요!
1,2등은 6개 매치카운트인데 어떤 값으로 판별하지? 의문이 들 수 있을것 같아요 🤔 
isBonus 와 같은 값을 넣어 true, false 유무로 판단할 수 있게 만들면 어떨까요??

2023-05-16 00:29 UTC, mskangg commented on src/main/java/lotto/README.md
> +- [ ] 보너스 번호 view
체크가 빠졌네용 😄

2023-05-16 11:55 UTC, seonuk commented on src/main/java/lotto/Lotto.java
> +        winningNumbers.add(bonus);
winningNumbers도 클래스가 될 수 있었군요!
lotto만 클래스로 감쌀 수 있다고 생각했네요. 
WinLotto 만들어서 캡슐화 더 강화했습니다! 감사합니다~

2023-05-16 11:55 UTC, seonuk commented
@mskangg 코드 리뷰 반영했습니다~

2023-05-17 05:06 UTC, mskangg requested changes
피드백 반영잘해주셨습니다!
다만, 조금 더 리팩토링이 될 수 있을 것 같아 추가적으로 리뷰드렸어요
확인부탁드립니다 🙇

2023-05-17 05:06 UTC, mskangg commented on src/main/java/lotto/Lotto.java
>      }
WinLotto 객체를 받아서 사용하는게 좋아보여요 🤔 

```java
    public int getMatchCount(WinLotto winLotto) {
        return (int) this.numbers.stream()
                .filter(winLotto::match)
                .count();
    }
```

이런식으로 메세지로 대화하는 방식으로 코딩하는건 어떠신가요?
현재 1등도 6개일치 2등도 6개일치로 되어있는데, 2등을 5개일치로 바꾸고 보너스볼 유무를 확인하게 변경하는것도 좋아보입니다. (실제 로또도 6개 추첨하고 보너스볼은 추가로 추첨하고 있기도 하구요)

2023-10-09 14:29 UTC, closed without merging