Step4
next-step/java-lotto pull request #3218
Opened 2023-05-16 03:20 UTC by lehdqlsl

시간이 너무 끌려서 피드백 받기 위해 PR 요청 드립니다.

객체의 책임을 분리하면서 자연스럽게 역할들이 나눠진거 같았는데,
이 역할들을 가지고 중간에 수동구매 로직을 넣으려니까, 제가 원하는 객체간에 매끄러운 개념? 메시지 이동이 뜻대로 잘 안되네요.
역할은 분명 잘 쪼갠거같은데,, 그래서 약간 수동구매 로직이 **야매** 입니다.

- 기존에는 입력 받은 price를 단순히 for 문을 통해 로또 객체를 생성했다면
- 수동 로또를 추가하면서, price 값을 들고있는 상태에서 구매하는 개념으로 가야될거같은데, 그럼 어떤 객체가 price 값을 가지고 있으며, 언제 초기화 해야되는지가 좀 어렵네요. 
- 만약에 특정 객체가 price를 들고있는 상태라면, 이 price의 값도 함부러 바뀌지 않게 잘 관리도 필요할꺼구요...

제가 너무 어렵게 생각하고있거나 방향이 맞지않는 고민을 하고있는건지, 의견 부탁드립니다 ㅠㅠ

2023-05-17 04:42 UTC, testrace requested changes
안녕하세요 동빈님 😃 
4단계 구현도 잘해주셨네요 👍 
작성한 코드가 마음에 들지 않거나 안정감이 부족하다고 느껴질 때 필요한 것이 기능 목록 정의와 테스트 코드라고 생각해요!
질문 주셨던 내용에 대한 코멘트 남겼으니 확인 부탁드려요
궁금한 점이나 의견 있으시면 편하게 DM 주세요

2023-05-17 04:42 UTC, testrace commented on src/main/java/lotto/domain/LottoGame.java
> +        }
코멘트로 질문 주신 부분이네요
수동 로또를 생성할 때 price와 listOfNumbers를 활용하다 보니 매끄럽지 않다고 느끼신 것 같아요
로또를 생성할 때 금액이 꼭 필요한지 고민해 보시면 좋을 것 같아요
주어진 수량만큼 생성하거나 주어진 숫자들로만 생성하는 책임을 수행하고
그 수량을 결정하는 객체가 별도로 있다면 어떨까요?

수동 로또 구매에 대한 테스트 코드가 없는 것 같은데요(수동 구매 수량만큼 생성하는 테스트)
테스트 코드가 없다면 작성한 코드(설계)에 대해 신뢰도가 떨어질 수 있다고 생각해요
테스트 코드를 활용해 코드에 대한 안정감을 확보하면서 구현해 보시면 좋을 것 같아요
쉽지 않으시겠지만 천천히 TDD로 다시 구현해 보시면 책임과 역할을 나누어 보시면 어떨까요?

2023-05-17 04:42 UTC, testrace commented on src/main/java/lotto/domain/LottoMatcher.java
> +    FIRST_MATCH(6, 2_000_000_000, "first"),
enum은 name() 메서드로 상수명을 string으로 반환할 수 있습니다
first, second 등의 문자열은 제거하고 enum의 기본 메서드를 활용해 보시면 좋을 것 같아요 😃

2023-05-17 04:42 UTC, testrace commented on src/main/java/lotto/domain/LottoScore.java
> +    private Map<String, Integer> map;
이렇게도 가능합니다 😃 
```suggestion
    private Map<LottoMatcher, Integer> map;
```

2023-05-17 04:42 UTC, testrace commented on src/main/java/lotto/domain/LottoMatcher.java
> +        map.computeIfPresent(mapKey, (k, v) -> v + 1);
LottoScore에서 이미 0으로 초기화를 하고 있으니 putIfAbsent는 없어도 될 것 같아요 😃 
```suggestion
        map.computeIfPresent(mapKey, (k, v) -> v + 1);
```

2023-05-17 04:42 UTC, testrace commented on src/main/java/lotto/domain/WinningNumbers.java
> +public class WinningNumbers {
WinningNumbers 💯

2023-05-17 04:42 UTC, testrace commented on src/test/java/lotto/LottoGameTest.java
LottoGameTest가 제거되었네요 😲 
어떤 이유로 단위 테스트가 필요 없다고 판단하셨을까요?

2023-05-17 04:42 UTC, testrace commented on src/main/java/lotto/view/InputView.java
> +        System.out.printf("수동으로 %d장, 자동으로 %d개를 구매했습니다.\n", manualQuantity, autoQuantity);
ResultView에 어울리는 메서드인 것 같아요 😃

2023-05-18 11:00 UTC, lehdqlsl commented on src/main/java/lotto/domain/Lotto.java
> +    }
기존 비즈니스로직과 테스트코드들이 모두 List로 되어있어서, 
모두 다 바꾸기에는 너무 큰 작업이라, Lotto객체 생성할때 간단하게 처리하는 식으로 했습니다!

2023-05-18 11:02 UTC, lehdqlsl commented on src/test/java/lotto/LottoGameTest.java
객체를 분리하다보니, 해당 테스트는 WinningNumbers, Price Test로 이동하였습니다!

2023-05-31 10:02 UTC, testrace approved these changes
안녕하세요 동빈님 😃 
피드백 반영 잘해주셨네요 👍 
로또 미션은 여기서 마무리하겠습니다!
그 동안 고생 많으셨습니다

2023-05-31 10:02 UTC, testrace commented on src/main/java/lotto/domain/LottoScore.java
> +    private Map<LottoMatcher, Integer> map;
피드백 반영 👍

2023-05-31 10:02 UTC, merged