🚀 3단계 - 로또(2등)
next-step/java-lotto pull request #3226
Opened 2023-05-17 09:35 UTC by ynoolee

안녕하세요 리뷰어님 3단계 과제 제출합니다 

감사합니다

2023-05-18 09:04 UTC, testrace requested changes
안녕하세요 연우님 😃 
커밋 메시지가 항상 인상적이네요 👍 
고민해 보시면 좋을 것 같은 코멘트 몇가지 남겼으니 확인해 주시고 다시 리뷰 요청 부탁드려요
궁금한 점이나 의견 있으시면 편하게 DM 주세요!

2023-05-18 09:04 UTC, testrace commented on src/main/java/autolotto/machine/lotto/LottoWallet.java
> +                                .winningMoney())
당첨 합산 금액을 구하는 책임을 LottoWallet이 아니라 당첨금에 대해서 가장 잘 아는 객체에게 위임하면 어떨까요?
LottoWallet이 당첨금에 대해 잘 아는 객체를 알고 있다면 직접 계산하기 보다 해당 객체에게 메시지를 보낼 수 있을 것 같아요

2023-05-19 10:42 UTC, ynoolee commented on src/main/java/autolotto/machine/BonusNumber.java
> +    private final int number;
아하 최대한 작은 단위로 검증조건을 갖는 것이 필요한 것 같네요!  처음에는 Lotto 의 생성자 자체를 protected 로 막고 Generator 와 같은 패키지에 둘까 생각했었는데, 그보다도 로또 숫자는 1 ~ 45 의 값이다 라는 로또 숫자 조건을 체크할 수 있는 객체를 따로 두는게 좋을 것 같습니다. 반영하겠습니다!

2023-05-22 13:41 UTC, ynoolee commented on src/main/java/autolotto/Main.java
> +                lottoMachine.profitRate(winningNumbers, bonusNumber).toPlainString(),
WinningNumber 가 일급 컬렉션 같은 존재라고 생각했어 둘을 따로 두는 것으로 생각했었습니다. 
또한, 별도로 입력을 받기 때문에 따로 있어야 한다고 생각을 했었습니다. 

그런데 지금은 말씀 하신 것 처럼 당첨의 기준이 '일치개수 + 보너스 일치 여부' 를 하나로 하여 보는 것으로 변경 되었기 때문에 WinningNumbers 가 일급 컬렉션이 아닌 '당첨 기준이 되는 번호들' 로 하는 것이 좋을 것 같습니다. 
- 먼저 당첨번호들과 보너스 번호는 겹치는 번호가 아님을 하나의 클래스 내에서 검증하는 것도 가능할 듯합니다. 이런면에서 응집도가 높아진다고 볼수 있을 거 같군여

2023-05-24 07:51 UTC, testrace approved these changes
안녕하세요 연우님 😃 
피드백 잘해주셨네요 👍 커밋 메시지도 👍 💯 
소소하게 코멘트 남겼는데 확인해 주시고 다음 단계 진행해 주세요!
궁금한 점이나 의견 있으시면 편하게 DM 주세요

2023-05-24 07:51 UTC, testrace commented on src/main/java/autolotto/machine/lotto/Lotto.java
> +    }
Lotto 는 중복되지 않는 6개의 숫자를 가져야 하니 List대신 Set 자료구조를 활용할 수 있을 것 같아요 😃

2023-05-24 07:51 UTC, testrace commented on src/main/java/autolotto/machine/lotto/Lotto.java
> +        ArrayList<LottoNumber> winningNumbers = new ArrayList<>(comparisonTarget.winningNumbers());
```suggestion
        List<LottoNumber> winningNumbers = new ArrayList<>(comparisonTarget.winningNumbers());
```

2023-05-24 07:51 UTC, testrace commented on src/main/java/autolotto/machine/lotto/LottoNumber.java
> +public class LottoNumber {
원시값 포장 👍

2023-05-24 07:51 UTC, testrace commented on src/test/java/autolotto/machine/lotto/LottoNumberTest.java
> +    }
범위를 가지는 원시값이니 경계 값(0, 46)으로 테스트해도 좋을 것 같아요

2023-05-24 07:51 UTC, merged