Step3
next-step/java-lotto pull request #3245
Opened 2023-05-20 14:29 UTC by joooahn

피드백 항상 감사합니다

2023-05-21 05:16 UTC, dave915 requested changes
주안님 안녕하세요! 3단계도 구현 잘 해주셨습니다! 👍 
몇가지 피드백 남겼습니다. 확인 부탁드릴게요 :)

2023-05-21 05:16 UTC, dave915 commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> candidateNumbers = IntStream.rangeClosed(MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER)
MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER, SIZE_LOTTO_NUMBER, LOTTO_PRICE 값은 Ticket에 관련된 값들 같은데, Constants 보단 Ticket 에서 static필드로 관리하는건 어떨까요? 
Constants 도 Utils 과 같은 성격으로 보이네요 🤔

2023-05-21 05:16 UTC, dave915 commented on src/main/java/lotto/domain/WinningNumber.java
> +    BonusBall bonusBall;
`BonusBall`에 접근제어자가 없는 이유가 있을까요?

2023-05-21 05:16 UTC, dave915 commented on src/main/java/lotto/domain/Ticket.java
> +        return (int) winningNumber.getWinningNumber().stream()
WinningNumber 에서 값을 꺼내서 비교하는것이 아닌, WinningNumber 에게 메세지(numbers) 을 보내 매칭된 번호 갯수를 물어보세요!

2023-05-21 05:16 UTC, dave915 commented on src/test/java/lotto/domain/LottoGameServiceTest.java
>      public void countOfMatchingNumber() {
1,2,3,4,5,11 로 테스트를 해봤는데요, `THIRD_PRIZE`가 안나오네요! 
한번 확인 부탁드릴게요 :)

2023-05-22 09:38 UTC, joooahn commented on src/main/java/lotto/domain/LottoGenerator.java
> +        List<Integer> candidateNumbers = IntStream.rangeClosed(MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER)
@dave915 아하 연관된 상수들은 객체 안으로 넣는게 캡슐화에도 더 좋겠네요ㅎㅎ감사합니다

2023-05-22 09:39 UTC, joooahn commented on src/main/java/lotto/domain/WinningNumber.java
> +    BonusBall bonusBall;
@dave915 실수입니다 ㅎㅎ;

2023-05-22 10:37 UTC, joooahn commented on src/test/java/lotto/domain/LottoGameServiceTest.java
>      public void countOfMatchingNumber() {
로직에 문제가 있었네요 수정해서 올리겠습니다!

2023-05-23 16:32 UTC, dave915 approved these changes
주안님 안녕하세요! 
피드백 반영 확인했습니다. 다음 단계 진행해 주세요 :)
다음번 피드백 반영 할 땐 수정한 단위로 커밋을 해주시면 좋을 것 같아요!

2023-05-23 16:32 UTC, dave915 commented on src/main/java/lotto/domain/PrizeType.java
> +    private final boolean bonusMatching;
👍

2023-05-23 16:32 UTC, dave915 commented on src/main/java/lotto/domain/Ticket.java
> +    public static final int LOTTO_PRICE = 1000;
👍

2023-05-23 16:32 UTC, merged