[Step4] Step 3 피드백 반영 및 Step 4 기능 구현
next-step/java-lotto pull request #3249
Opened 2023-05-21 11:22 UTC by dhkimneer

1. Step 3 피드백 반영
2. Step 4 기능 구현
 - Lotto를 Set<LottoNumber>로 받다 보니, 수동으로 만들어진 로또의 경우 sort가 안 된 상태로 보여지는 문제

2023-05-22 04:15 UTC, sah3122 commented
`Lotto를 Set로 받다 보니, 수동으로 만들어진 로또의 경우 sort가 안 된 상태로 보여지는 문제` 와 같은 이슈가 있으셨다고 남겨두셨는데 Set Collection에서 Sorting을 보장하는 TreeSet과 같은 타입을 선언하여 해결해볼수도 있을것 같네요 !

2023-05-22 04:17 UTC, sah3122 requested changes
수동 로또 구현 잘해주셨습니다 👍 
몇가지 고민거리를 남겨두었는데 확인 부탁드려요 😄

2023-05-22 04:17 UTC, sah3122 commented on src/main/java/lotto/domain/LottoPurchaseCount.java
> +public class LottoPurchaseCount {
구매 정보를 담고있는 클래스 정의 좋네요 👍

2023-05-22 04:17 UTC, sah3122 commented on src/main/java/lotto/domain/ManuallyCreatedLottos.java
> +public class ManuallyCreatedLottos {
수동 로또는 로또를 구입하는 방법에 한 종류입니다. 
별도의 클래스로 정의하는것에 대한 어떤 이점이 있을까요 ?

2023-05-22 04:17 UTC, sah3122 commented on src/main/java/lotto/view/InputView.java
> +    public List<Lotto> requestManuallyPurchaseNumbers(int requestManuallyPurchaseCount) {
InputView와 같은 UI Layer에 연관된 클래스는 Domain과의 결합이 없어야 한다고 생각해요. 
Lotto 를 생성하여 전달한다면 어떤 단점이 있을까요 ?

2023-05-31 13:46 UTC, dhkimneer commented on src/main/java/lotto/domain/ManuallyCreatedLottos.java
> +public class ManuallyCreatedLottos {
자동 로또의 경우 생성 개수, 생성 전략에 따라 좌우되므로 수동 로또와는 성격이 다르다고 생각합니다.
따라서 수동 로또가 별도의 클래스로 정의되어야 한다고 생각했고 이에 더해 추후 수동 로또에 독립적인 추가 로직이 들어갈 경우 추가하는 작업이 좀 더 편하게 이루어질 것이라 생각합니다.

2023-06-02 00:37 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
그동안 로또 미션 진행해주신다고 고생많으셨습니다 🙏 
남은 미션들도 끝까지 완주해보시길 바랄게요 !

2023-06-02 00:37 UTC, merged