Step3
next-step/java-lotto pull request #3250
Opened 2023-05-22 05:30 UTC by MJeong00

2023-05-22 15:09 UTC, parkeeseul requested changes
몇 가지 코멘트 남겨 두었으니 확인 부탁드립니다 😄 
화이팅 입니다 🔥

2023-05-22 15:09 UTC, parkeeseul commented on src/main/java/step2/Winner.java
> +        if(matchCount >= 3){
매직 넘버를 사용하기 보다는 상수화를 통해 값에 의미를 부여해주면 어떨까요? 😄

2023-05-22 15:09 UTC, parkeeseul commented on src/main/java/step2/Ticket.java
>      }
해당 생성자는 사용하지 않으므로 제거해 줘도 좋을 것 같아요 😄

2023-05-22 15:09 UTC, parkeeseul commented on src/main/java/step2/Ticket.java
>      }
생성자 -> 메서드(정적 팩터리 메서드 포함)  순으로 위치하는 것이 컨벤션 입니다 😄 
[3. 1. 3 Class와 Interface 선언](https://myeonguni.tistory.com/1596)

2023-05-27 08:10 UTC, MJeong00 commented on src/main/java/step2/Winner.java
> +    private static Map<Double, Integer> winnerMap = new HashMap<>();
해당 변수명에는 타입을 명시하지 않았는데 어떤걸 말씀하시는걸까요?_?

2023-05-28 07:08 UTC, parkeeseul approved these changes
몇 가지 추가 코멘트 남겨 두었으니 확인해 보시고
추가적인 수정 사항은 다음 단계와 함께 반영 부탁드립니다 😄 
다음 단계 진행해 주세요 🔥

2023-05-28 07:08 UTC, parkeeseul commented on src/main/java/step2/WinnerMap.java
> +    public static void plusWinnerMapCount(LottoMatch lottoMatch, int matchCount) {
matchCount는 사용하고 있지 않네요 😄 
```suggestion
    public static void plusWinnerMapCount(LottoMatch lottoMatch) {
```

2023-05-28 07:08 UTC, merged