Step4 코드리뷰 부탁드립니다.
next-step/java-lotto pull request #3261
Opened 2023-05-26 07:33 UTC by woorido

안녕하세요. 피효정입니다.
groupingBy 활용하는 부분 꼭 적용하고 싶었습니다.
Rank 별로 그룹화하고 summingLong 사용해서 개수를 세어 맵으로 다시 변환하게 했습니다. 개수를 셀 때 현재 Rank 와 동일한 경우 +1L 을 하여 반환하도록 했습니다.
Rank 의 개수가 업데이트된 새로운 result 맵을 생성하여 저장했는데, 의견 부탁드립니다.

그리고 궁금한 점이 있습니다.
compute 메서드를 알게 되었는데 이 메소드를 사용하여
result.compute(rank, (key, value) -> (value == null) ? 1L : value + 1L);
이렇게 구현하여 Map 의 value 값을 업데이트하는건 어떻게 생각하시는지 의견 부탁드립니다!

오늘도 잘 부탁드립니다!

2023-05-26 09:56 UTC, kyucumber requested changes
안녕하세요.

마지막 미션까지 수고 많으셨습니다.

간단한 코멘트 하나 남겨두었으니 확인 부탁드려요. 다시 요청주시면 머지하도록 하겠습니다.

2023-05-26 09:56 UTC, kyucumber commented on src/main/java/lotto/domain/result/LottoResult.java
> +                ));
> groupingBy 활용하는 부분 꼭 적용하고 싶었습니다. Rank 별로 그룹화하고 summingLong 사용해서 개수를 세어 맵으로 다시 변환하게 했습니다. 개수를 셀 때 현재 Rank 와 동일한 경우 +1L 을 하여 반환하도록 했습니다. Rank 의 개수가 업데이트된 새로운 result 맵을 생성하여 저장했는데, 의견 부탁드립니다.

저는 Stream을 활용해 `List<Rank>` -> `Map<Rank, Long>`으로 한번에 결과를 추출할 수 있을 것이다를 말씀드렸는데 의도한 방향과 맞지 않는 것 같아요. 하지만 이렇게 구현하셔도 무방합니다.

> result.compute(rank, (key, value) -> (value == null) ? 1L : value + 1L); 이렇게 구현하여 Map 의 value 값을 업데이트하는건 어떻게 생각하시는지 의견 부탁드립니다!

정해진 하나의 방법이 있는것은 아니라, 이렇게 하셔도 무방할 것 같습니다.

2023-05-26 09:56 UTC, kyucumber commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final Integer number;
👍

2023-05-27 07:42 UTC, woorido commented
안녕하세요. 피효정입니다.

제가 이해력이 부족했습니다.
주어진 Rank 기준으로 그룹화된 맵의 값을 계산하는 메소드와 계산된 값을 적용하여 result 맵을 재설정하는 메소드를 생성했는데, 다시 의견 부탁드립니다.

잘 부탁드립니다!

2023-05-27 13:27 UTC, kyucumber approved these changes
마지막 미션까지 수고 많으셨습니다.

코드는 머지했는데, 조금 더 학습해보고 싶으시면 코멘트 남긴 부분 확인하시고 개선해보시면 좋겠습니다.

2023-05-27 13:27 UTC, kyucumber commented on src/main/java/lotto/domain/result/LottoResult.java
> +    }
이 또한 제가 의도한 형태의 코드는 아닙니다. 코드에 정답이 있는 것은 아니니 이정도까지만 개선 해주시면 될 것 같습니다.

조금 더 개선해보고 싶으시면 이후에 아래 내용을 별도로 학습해보세요.

1. void 메서드에서 result 프로퍼티에 값을 할당하는게 아니라, 메서드를 호출한 시점에 `Map<Rank, Long>`을 반환하도록 순수함수 형태로 작성하는 부분
2. Rank 하나씩 넘기는게 아니라 `List<Rank>` 전체를 받아 한번에 Stream으로 연산하는 것

2023-05-27 13:27 UTC, merged