Step1 : 로또 기능 구현
next-step/java-lotto pull request #3274
Opened 2023-07-12 07:30 UTC by worldii

안녕하세요 우테캠 교육생 박종하입니다.

리뷰 잘 부탁 드립니다! 

# 구현 사항 
구현 사항은 Docs에 정리하였습니다.

# 질문 사항
enum을 상수, 객체로 사용할 수 있는데, 혼용해서 쓰는 것은 안된다고 강의시간에 들었습니다. 
현재  total 수익률 계산 하는 부분을 winningResult 객체에서 진행하고 있는데, rank의 reward를 가져와 비즈니스 로직을 처리하고 있는 부분이 존재합니다. getter를 쓰는 부분이 조금 이상하다고 느껴, rank의 객체에서 reward 를 처리하게끔 수정을 할까 생각도 했지만, rank에게 책임을 주는 부분이 조금 이상하다고 생각하여,  현재는 winningResult 객체에서 처리하게끔 그대로 두었습니다. 이에 대해 어떻게 생각하시는지 여쭙고 싶습니다. 감사합니다 ! 😊 

바쁘실 텐데 시간 내주셔서 감사합니다! 

# 리팩토링 후 변화 
- Lottos 일급 컬렉션 생성
 기존 purchasedLotto 객체를 없애고 lotto 와 비교하는 비즈니스 로직을 넣었습니다. 
- WinningResultDto, LottosDto 생성
 WinningResponse 변수명이 모호하다고 생각되어, WinningResultDto 로 수정하였고, 기존에는 로또들을 바로 OutputView로 출력하였지만, dto로 만들어 출력하게 하였습니다. 
- LottoRandomGenerator 의 interface 정의
NumberGenerator interface 를 생성하고 이를 오버라이드하였습니다. 
- Controller private 필드 부분 삭제
멀티 thread 환경일 시 동시성 이슈를 고려하여 필드 부분을 삭제하고 로컬변수로 진행하였습니다. 
- 기타 피드백 반영 
public 인 상수들 -> private 으로 변경, illegalArgumentException-> illegalStateException 으로 변경하였습니다.

2023-07-12 15:17 UTC, begaonnuri requested changes
안녕하세요 종하님, 1단계 요구사항을 잘 구현해주셨네요.
몇가지 코멘트 남겼는데 확인해주세요.

2023-07-12 15:17 UTC, begaonnuri commented on src/main/java/lotto/model/WinningResponse.java
> +    }
getProfit은 profit 변수를 그대로 반환한다고 오해할 여지가 있을 것 같아요. `calculate` 등 적절한 표현으로 변경해보면 어떨까요?

2023-07-12 15:24 UTC, begaonnuri commented
https://github.com/next-step/java-lotto/pull/3274#issue-1800363099 에 대한 답변입니다.

Q. enum을 상수, 객체로 사용할 수 있는데, 혼용해서 쓰는 것은 안된다고 강의시간에 들었습니다.
현재 total 수익률 계산 하는 부분을 winningResult 객체에서 진행하고 있는데, rank의 reward를 가져와 비즈니스 로직을 처리하고 있는 부분이 존재합니다. getter를 쓰는 부분이 조금 이상하다고 느껴, rank의 객체에서 reward 를 처리하게끔 수정을 할까 생각도 했지만, rank에게 책임을 주는 부분이 조금 이상하다고 생각하여, 현재는 winningResult 객체에서 처리하게끔 그대로 두었습니다. 이에 대해 어떻게 생각하시는지 여쭙고 싶습니다. 감사합니다 ! 😊

말씀해주신 부분은 객체 설계에 따라 달라지는 부분이라 정답이 없는 부분 같아요. 다만 Rank에서 profit이 아니라 profit을 직접적으로 계산하는 함수형 필드를 갖도록 해서 더 큰 책임을 줄 수도 있다고 생각하고, 그게 별로라면 종하님이 구현하신것 처럼 WinningResult 객체에서 처리하는것도 나쁘지 않아 보입니다.

다만 WinningCalculator -> WinningResult -> WinningResponse 과정에서 이해하는데 어려움이 조금 있었는데요, 이러한 흐름은 좋지만 Result, Response 등의 표현이 모호해서 수익을 계산하는것을 더 명확하게 표현하거나 수익 계산을 Rank같은 클래스에 위임하는 대신 한 곳에서 결과에 대한 책임을 모두 갖도록 해버리는것도 좋을 것 같네요. 이건 정답이 없는 부분이라 선택적으로 반영해주세요.

2023-07-13 05:07 UTC, worldii commented on src/main/java/lotto/model/Lotto.java
> +            throw new IllegalStateException("로또 번호는 " + LOTTO_LENGTH + "개이여야 합니다");
사용자 입력이 잘 못된 경우이므로 illegalArgumentException 이 적절하다고 생각합니다. 검색해보니 IllegalStateException은 사용자 입력은 제대로 되었지만, 메소드가 요구된 처리를 하기에 적합한 상태에 있지 않을때 사용하네요. 감사합니다!

2023-07-13 05:48 UTC, worldii commented on src/main/java/lotto/model/LottoNumber.java
> +    }
멤버변수, 속성이 같다면 같은 객체로 보는 비즈니스 로직을 포함한 경우, equals , hashcode 로 재정의 하였습니다. 따라서 LottoNumber 에는 구현을 하였습니다.
생각해보니, 로또 머니 또한 가격이 같으면 동일 객체로 보는 것이 맞는 것 같아, LottoMoney에도 적용하였습니다.

2023-07-13 05:52 UTC, worldii commented on src/main/java/lotto/Application.java
> +    private LottoMoney lottoMoney;
멀티뜨레드 환경일 경우, 필드의 상태가 변화 될 수 있다는 문제점이 있을 거 같습니다. 리팩토링 시에 이를 run 메서드 안에서 로컬 변수로 생성할 수 있도록 변경하도록 하겠습니다.

2023-07-13 06:11 UTC, worldii commented on src/main/java/lotto/Application.java
> +public class Application {
사실 Controller 로 이름명을 지을까 고민을 했었는데,  InputView, OutputView 객체만 다루는 게 아니라 run 메소드 안에서 전체적인 서비스 로직 ( 로또를 사는 로직, winning 로또와 비교하는 로직) 이 도는 것이 Controller 의 역할이 맞을까, 따로 서비스를 처리하는 객체를 두어 위임해야하지 않을까라는 고민을 했습니다.  사실 이부분이 헷갈려 질문을 드리고 싶었습니다.

2023-07-13 08:03 UTC, worldii commented on src/main/java/lotto/model/AutoLottoGenerator.java
> +    }
멀티 thread 환경에서 1~45 넘버가 shuffle 될때 동시성 이슈가 생길 것이라 생각하였습니다.

2023-07-13 08:34 UTC, worldii commented on src/main/java/lotto/model/AutoLottoGenerator.java
> +    }
전략 패턴을 통해서 LottoGenerator 를 생성하고 override를 하여 구현하는 방식으로 리팩토링하고, generate 메서드 하여 List<LottoNumber> 를 반환하도록 바꾸었습니다. 이는 추후에  Lotto에서 List<LottoNumber> 로 생성자를 받는 것으로 바꾸었는데 어떤 테스트를 진행할지 모르겠습니다..  자세하게 알려주실 수 있으실까요?

2023-07-13 08:41 UTC, worldii commented on src/main/java/lotto/model/WinningResponse.java
> +    }
dto 느낌이 안나는 거 같아서 floorProfit 으로 바꾸겠습니다!

2023-07-13 08:47 UTC, worldii commented on src/main/java/lotto/model/WinningResponse.java
> +    }
floorProfit으로 변경하도록 하겠습니다.!

2023-07-13 14:57 UTC, begaonnuri commented on src/main/java/lotto/Application.java
> +public class Application {
> 로또를 사는 로직, winning 로또와 비교하는 로직

이런 로직은 서비스 로직이라기보단 도메인 로직이라고하는게 더 적절할거에요. 도메인 객체 안에 메서드들로 로직들이 있는데 서비스를 처리하는 객체를 추가해야겠다는 생각을 하신 이유는 무엇인가요? 그리고 서비스의 역할은 뭐라고 생각하시나요?

2023-07-13 15:15 UTC, begaonnuri approved these changes
안녕하세요 종하님, 리뷰를 잘 이해하고 반영해주셨네요.
1단계는 충분히 잘 해주신것같아서 머지하겠습니다. 2단계도 화이팅입니다 💪🏻 

몇가지 코멘트도 남겼는데 확인해주세요!

2023-07-13 15:15 UTC, begaonnuri commented on src/main/java/lotto/model/dto/LottosDto.java
> +public class LottosDto {
DTO가 나온 이유는 무엇인가요?

2023-07-13 15:15 UTC, begaonnuri commented on src/main/java/lotto/model/util/AutoLottoGenerator.java
> +package lotto.model.util;
자동 생성으로 로또 번호를 생성한다는것도 비즈니스 규칙인데 util 클래스에 있는게 어색하게 느껴지네요. util 클래스에 두신 이유가 있을까요?

2023-07-13 15:15 UTC, merged

2023-07-14 05:33 UTC, worldii commented on src/main/java/lotto/model/util/AutoLottoGenerator.java
> +package lotto.model.util;
음.. 비즈니스 로직이니까 util에 있으면 안되겠네요. 짚어주셔서 감사합니다!

2023-07-14 06:06 UTC, worldii commented on src/main/java/lotto/model/AutoLottoGenerator.java
> +    }
넵 해당 부분 이해하여 다음 step2 에 적용하였습니다 .테스트 코드가 빈약했던 것 같습니다. 자세히 설명해주셔서 감사합니다. dcd5155c53ba61040155150897b46ada448b8e88

2023-07-14 06:12 UTC, worldii commented on src/main/java/lotto/model/dto/LottosDto.java
> +public class LottosDto {
Lottos 를 일급 컬렉션으로 만들고 Lotto 와 비교하는 로직을 담고 있습니다. 이때 output view 에서 lottos 를 getter 로 가져오는 것 보다, dto 를 생성하여 outputview 에 전달하는게 낫지 않을 까 생각했습니다. WinningResultDto 또한 마찬가지 이유로 dto 를 생성했습니다.

2023-07-14 06:28 UTC, worldii commented on src/main/java/lotto/Application.java
> +public class Application {
음... 일단 service는 controller에서 온 요청을 처리하고 이를 다시 결과값으로 반환하는 역할로 생각했습니다. 또한 지금은 비즈니스 로직이 로또를 사는 로직, winning 로또를 비교하고 결과값을 계산하는 로직밖에 없지만, 다른 비즈니스 로직이 생기면 컨트롤러에서 이를 처리하는 것이 부자연스럽다고 느꼈던 거 같습니다. 따라서 서비스 객체에 이를 넘겨주고 반환값을 출력하는 것만 관여를 해야하는게 아닌가 생각했습니다. 제가 잘못 생각하고 있다면 정정 부탁 드립니다.

2023-07-16 06:54 UTC, begaonnuri commented on src/main/java/lotto/Application.java
> +public class Application {
레이어드 아키텍처의 영향으로 Controller-Service 관계가 익숙하시겠지만, 서비스의 역할은 외부 컴포넌트(데이터베이스 등)와의 통합입니다. 지금 로또에선 데이터베이스와 같은 외부 컴포넌트의 요구사항이 없기 때문에 컨트롤러에서 진행해도 충분하다고 생각해요. 다만 컨트롤러에서 로직을 진행하기보다는 도메인 객체에게 위임을 통해 로직을 진행하는 것 좋다고 생각해요.