Step1: 로또 자동
next-step/java-lotto pull request #3278
Opened 2023-07-12 09:08 UTC by ProtoSeo

## 로또 자동 구현

### 궁금한 점

- `validate` 메서드에서 검증 할 요소가 여러개인 경우, 검증할 요소들을 따로 메서드로 빼는 것이 좋은지 아니면 그대로 두는 것이 좋은지 궁금합니다!
- 반복문을 사용할 때, 처음을 지정하는 0과 같이 큰 의미가 없는 수도, 따로 상수로 빼야하는지 궁금합니다.
  - `LottoGenerator` 에서 구매한 개수만큼 로또를 구매할 때, [0, 구매한 개수) 만큼 반복문을 돌리는데, 이 때 0을 매직 넘버로 봐야하는지 궁금했습니다.

2023-07-12 12:48 UTC, Laterality requested changes
안녕하세요.

잘 구현해주셨습니다.

몇 군데 궁금한 곳에 코멘트와 의견 남겨드렸습니다. 확인 부탁드릴게요.

궁금하신 점은 언제든 DM 주세요 :)

## Q&A

* 검증 메서드 분리
    * 메서드 분리를 고민하시는 목적은 무엇일까요? 둘 중 어느 방법이 목적에 더 어울린다고 생각하시나요?
* 상황에 따라 다르겠네요. 똑같이 0으로 시작하는 루프라도 어떤 곳에서는 특별한 의미가 있는 상수일 수도, 어떤 곳에서는 단순히 for 루프의 초깃값으로 사용될 수 있으니까요. 만약 말씀하신 상수가 도메인에서 의미를 갖는 중요한 숫자라면 상수로 분리하는 게 좋겠습니다. 그렇지 않다면 분리하지 않더라도 상수의 의미를 이해하는 데는 어려움이 없을 테니 굳이 분리할 필요는 없다고 생각해요.

2023-07-12 12:48 UTC, Laterality commented on src/main/java/lotto/domain/Lotto.java
> +    public LottoResult compareLottoRule(final Lotto winningLotto, final Ball bonusBall) {
`WinningLotto`를 인자로 받아도 되지 않을까요?

2023-07-12 12:48 UTC, Laterality commented on src/main/java/lotto/domain/Lotto.java
> +        return this.balls;
내부의 리스트를 그대로 반환해도 괜찮을까요?

2023-07-12 12:48 UTC, Laterality commented on src/main/java/lotto/domain/LottoGenerator.java
> +                .mapToObj(i -> lottoGenerateStrategy.generate(balls))
`lottoGenerateStrategy`가 인자로 받은 `balls`에 항목을 추가하거나 제거할 수도 있지 않을까요?

2023-07-12 12:48 UTC, Laterality commented on src/main/java/lotto/domain/LottoResult.java
> +public class LottoResult {
`LottoRule`과 이 클래스는 어떤 차이가 있을까요?

2023-07-12 12:48 UTC, Laterality commented on src/main/java/lotto/domain/LottoRule.java
> +public enum LottoRule {
로또 등수 별 상금을 가진 클래스인데 Rule은 다소 포괄적인 의미로 읽히네요. 더 좋은 이름이 있을까요?

2023-07-12 12:48 UTC, Laterality commented on src/main/java/lotto/domain/WinningStatistics.java
> +    private final Map<Integer, Integer> rankWithCount;
변수명으로 짐작할 수는 있겠지만 키와 값이 각각 무엇을 의미하는지 잘 구분되지 않네요. 맵의 구조를 더 명확하게 나타낼 방법이 있을까요?

2023-07-12 12:48 UTC, Laterality commented on src/main/java/lotto/view/WinningStatisticsWriter.java
> +        } else if (lottoRule.equals(LottoRule.SECOND)) {
else if 대신 if만 사용해도 되지 않을까요?

2023-07-12 12:48 UTC, Laterality commented on src/test/java/lotto/domain/LottoGeneratorTest.java
> +    @DisplayName("받은 금액만큼 로또를 생성하는지 테스트")
로또 가격보다 적은 금액을 받은 경우에는 어떻게 될까요?

2023-07-12 14:27 UTC, ProtoSeo commented on src/main/java/lotto/domain/Lotto.java
> +    public LottoResult compareLottoRule(final Lotto winningLotto, final Ball bonusBall) {
맞네요! WinningLotto를 생성하고 이 부분에도 적용하는 것을 놓쳤네요!

2023-07-12 14:48 UTC, ProtoSeo commented on src/main/java/lotto/view/WinningStatisticsWriter.java
> +        } else if (lottoRule.equals(LottoRule.SECOND)) {
맞네요! else if 를 사용할 이유가 없네요!

2023-07-12 15:05 UTC, ProtoSeo commented on src/test/java/lotto/domain/LottoGeneratorTest.java
> +    @DisplayName("받은 금액만큼 로또를 생성하는지 테스트")
이미 Money 에서 로또 가격 보다 적은 금액, 혹은 하루에 살 수 있는 로또의 제한 금액인 10만원을 초과하는 경우에 대한 테스트가 있으므로 Lotto를 생성할 때 굳이 테스트하지 않았던 것 같습니다!

로또 가격보다 적은 금액을 받은 경우, 하루 구매 가능한 로또 가격 보다 초과한 금액을 받은 경우에 대한 테스트를 추가했습니다.

2023-07-12 15:10 UTC, ProtoSeo commented on src/main/java/lotto/domain/LottoResult.java
> +public class LottoResult {
이 클래스를 구현할 때 처음 생각했던 것은, `LottoRule` 에서 Lotto 끼리의 중복된 수, 보너스 볼의 유무를 통해서 당첨 여부를 판단하고 이에 대한 결과를 전달하는 용도로 사용하려고 했어요. 

그런데 사용하는 목적을 보니 거의 `LottoRule`의 하위 호환 역할을 하는, 역할이 겹치는 클래스라는 생각이 드네요! `LottoResult` 클래스는 제거하고, `LottoRule` 을 사용하도록 수정했습니다!

2023-07-12 23:32 UTC, ProtoSeo commented on src/main/java/lotto/domain/Lotto.java
> +        return this.balls;
이 부분에 대해서는 고민을 많이 했었는데요, 해당 `getBalls()` 메서드는 출력을 위해서만 사용되기 때문에, 괜찮지 않을까? 라는 생각을 했어요!

최대한 getter를 사용하지 않고 미션을 진행해보려 했는데, 이 메서드가 없이 출력을 하려면 Lotto에서 출력을 하기 위한 메서드가 생겨야 할 것 같다는 생각이 들어서, 그대로 반환하게 했습니다. 

혹시 리스트를 반환하지 않고 어떻게 해결할 수 있을까요? 제가 생각해봤을 때는, `toString()` 을 사용하는 방법 밖에 떠오르지 않는데, 더 좋은 방법이 있을까요?

2023-07-13 00:06 UTC, ProtoSeo commented on src/main/java/lotto/domain/WinningStatistics.java
> +    private final Map<Integer, Integer> rankWithCount;
해당 맵을 포장하는, 일급 컬렉션으로 만들면 어떨까요? 그렇게 하면 이 맵이 하는 역할을 좀 더 명확하게 표현할 수 있을 것 같아요!

2023-07-13 02:24 UTC, ProtoSeo commented on src/main/java/lotto/domain/LottoGenerator.java
> +                .mapToObj(i -> lottoGenerateStrategy.generate(balls))
맞네요! 로또에서 사용할 공들을 생성하는 책임이 `LottoGenerator`에 있기 때문에 생성한 공들을 `lottoGenerateStrategy.generate()` 에 넘겨줘서 이렇게 되어버린 것 같아요.

생각해보니, 로또에서 사용할 공들을 생성하는 책임은 `LottoGenerator`가 아니라 `LottoGenerateStrategy`에 있어야 했을 것 같아요. 왜냐하면 로또 게임마다 사용할 공들의 수가 다를 수 있기 때문이에요. 그래서 이번에 `LottoGenerateStrategy` 에서 로또에서 사용할 공을 생성하는 책임을 가지도록 수정해봤습니다.

2023-07-13 04:11 UTC, ProtoSeo commented on src/main/java/lotto/domain/LottoRule.java
> +public enum LottoRule {
그렇네요! 처음 생각에는 로또 당첨 규칙을 담고 있으니, `LottoRule`로 지었는데, 너무 넓은 의미인 것 같아요.

등수와 상금, 그리고 해당 등수를 위한 정보를 담고 있어서, `LottoRank` 라는 이름으로 수정해봤습니다. 이렇게 수정하고나서 상금을 읽을 때는, `lottoRank.getPrize()` 와 같이 자연스럽게 읽힐 것 같아요.

2023-07-13 04:40 UTC, ProtoSeo commented on src/main/java/lotto/domain/Lotto.java
> +        return this.balls;
계속 고민해봤는데, `toString()` 을 사용하더라도, 결국 `toString()`에서 출력에 대한 짐을 짊어지게 될 것 같다는 생각이 들어서 `toString()`을 사용하는 것도 좋은 방법은 아닌 것 같아요.

지금은 `Collections.unmodifiableList()`로 List를 반환하더라도 출력 뷰에서 `Ball`을 추가하거나, 삭제하지 못하도록 수정해봤습니다!

2023-07-13 05:40 UTC, ProtoSeo commented
> ## Q&A
> * 검증 메서드 분리
>   
>   * 메서드 분리를 고민하시는 목적은 무엇일까요? 둘 중 어느 방법이 목적에 더 어울린다고 생각하시나요?

메서드 분리를 고민했던 이유는, 여러 if문을 남겨서 검증하는 방법과, 그 if문을 메서드로 각각 빼서 표시하는 방법(분리하는 방법) 중 어떤 방법이 더 코드를 읽는데 더 명확한지에 대한 고민 때문이었어요.

예를 들어 로또에 대한 검증을 할 때, 로또에 대해서 길이에 대한 검증, 중복에 대한 검증을 `validate()` 메서드에서 진행하는 데, if문 두 개로 하는 것보다 메서드로 빼내는 것이 더 코드가 잘 읽힐 것이라고 생각했어요. 하지만 로또 길이에 대한 검증을 정확히 어떻게 하는지 궁금하다면, 해당 메서드를 들어가서 어떻게 검사하는지 로직을 읽어야 할 것 같다는 단점이 있을 것 같아서 두 방법 중 어떤 방법이 나은 방법인가? 에 대한 고민을 많이 했었습니다.

결국 두 방법 다 장단점이 있는것 같은데, 코드가 잘 읽히는 것에 대한 목적을 두고 `validate()`에서 여러 개를 검증해야 하는 경우 어떻게 하시는걸 선호하시는지가 궁금했었습니다!

2023-07-13 12:00 UTC, Laterality approved these changes
피드백 잘 반영해주셨습니다 👍 

이번 단계는 이만 머지하도록 하겠습니다.

남겨드린 피드백은 다음 단계 진행하시면서 참고해주세요.

고생하셨습니다 :) 

## Q&A

저는 두 방법 모두 사용하기도 하고, 가독성은 주관이 강한 영역이라 함께 작업하는 팀원들의 의견을 구해보시면 어떨까요?

2023-07-13 12:02 UTC, merged

2023-07-13 12:35 UTC, ProtoSeo commented on src/main/java/lotto/domain/LottoGenerateStrategy.java
> +    public LottoGenerateStrategy(final int minNumber, final int maxNumber) {
맞네요! `protected`로 좁혀주는게 좋을 것 같습니다!

2023-07-13 12:56 UTC, ProtoSeo commented on src/main/java/lotto/view/WinningStatisticsWriter.java
> +    }
한 메서드로 합치고, if문을 이용해서 "보너스볼 일치 ..." 관련 출력만 바꾸면 되겠네요! 반영했습니다. 

해당 메서드에서 조건문을 받으니까, `formatToStatistics()`를 호출하는 `printEachStatistics()`메서드에서는 또 조건문을 넣을 필요가 없어져서 더욱 더 간결해지네요!

2023-07-13 13:03 UTC, ProtoSeo commented on src/main/java/lotto/domain/RankWithWinningCount.java
> +                    this.rankWithCount.getOrDefault(lottoRank, DEFAULT_COUNT) + 1);
아하! `putIfAbsent`, `computeIfPresent` 메서드를 잘 사용해보지 않아서 몰랐는데, 이렇게 두 호출로 나누는게 좀 더 가독성이 좋아보이는 것 같아요!