Step 1 : 로또 자동 구현
next-step/java-lotto pull request #3280
Opened 2023-07-12 09:17 UTC by hwihwi523

안녕하세요!
OOP 미션 1단계 '로또 자동' 코드 리뷰를 요청 드리게 된 윤재휘입니다!

---

Bottom-Up 방식으로 작은 단위부터 점점 키워나가며 구현했으며, 도메인별 기능 및 구조는 다음과 같습니다.

- Ball : 로또를 구성하는 번호이며, 아래의 기능을 갖습니다.
    - 1 ~ 45의 값을 갖도록 유효성을 검증하는 기능
    - 숫자만 포함되어 있는지 검증하는 기능

- Lotto : Ball 객체를 리스트로 관리하는 컬렉션이며, 아래의 기능을 갖습니다.
    - 주어진 Ball 객체들이 중복되지 않는지 검증하는 기능
    - 주어진 Ball 객체가 6개인지 검증하는 기능
    - 당첨 Lotto를 전달받아 당첨 결과를 반환하는 기능

- WinningLotto : 당첨 번호, 보너스 볼 등 지난 주 당첨 정보를 관리하며, 아래와 같은 기능을 갖습니다.
    - Ball 리스트를 전달받아 당첨 번호와 일치하는 개수를 반환하는 기능
    - Ball을 전달받아 보너스 볼이 포함되어 있는지 여부를 반환하는 기능

- BoughtLottos : 사용자가 구매한 Lotto 객체를 리스트로 관리하는 컬렉션이며, 아래의 기능을 갖습니다.
    - 당첨 번호와 보너스 번호를 전달받아, 관리하는 모든 Lotto 객체 리스트의 당첨 결과를 리스트로 반환하는 기능

- LottoResult : Lotto 의 당첨 결과를 의미하며, 아래와 같은 필드를 갖습니다.
    - 일치하는 번호의 개수
    - 보너스 번호를 맞혔는지 여부
    - 등수 enum

- LottoResults : LottoResult 리스트를 관리하는 컬렉션이며, 아래와 같은 기능을 갖습니다.
    - LottoResult 리스트에 대한 당첨 통계를 반환하는 기능

- WinningCriteria : 등수를 의미하는 enum이며, 아래와 같은 기능을 갖습니다.
    - 일치하는 개수, 보너스 번호 포함 여부를 입력받아 등수를 계산하는 기능

- WinningStatistics : 당첨 통계를 의미하며, 아래와 같은 기능을 갖습니다.
    - 총 수익금을 계산하여 반환하는 기능
    - 수익률을 계산하여 반환하는 기능

- Money : 구입 금액을 의미하며, 아래와 같은 기능을 갖습니다.
    - 1,000 ~ 100,000 범위의 값을 갖는지 검증하는 기능
    - 숫자만 포함하는지 검증하는 기능

---

- LottoGenerator : 주어진 생성 전략에 따라 랜덤값을 생성하며, 아래와 같은 기능을 갖습니다.
    - 생성 전략에 따라 구입 금액만큼 Lotto 를 생성하고, BoughtLottos 로 취합하여 반환하는 기능
    - 생성 전략 1. RandomLottoGenerateStrategy : 1 ~ 45 범위의 Ball 에 대해 shuffle 을 수행하는 전략
    - 생성 전략 2. test.SequenceLottoGenerateStrategy : 테스트를 위해 1부터 6개씩 잘라서 생성하는 전략

---

시간 내어 읽어주셔서 감사합니다!

2023-07-13 11:20 UTC, fucct requested changes
안녕하세요!

시스템 구조를 잘 작성해주셨네요! 전체적으로 큰 문제 없었습니다.
다만 Layer의 경계에 대해 한번 생각해보시면 좋을것 같습니다. statistics, result와 같은 객체들이 정말로 domain인지 한번 고민해주세요.
그 외 자잘한 피드백 남겨놓았으니 확인 부탁드려요!

2023-07-13 11:20 UTC, fucct commented on src/main/java/lotto/domain/LottoResult.java
> +package lotto.domain;
LottoResult가 domain이 맞을까요? 
View를 위한 객체가 아닌가 싶네요.

2023-07-13 11:20 UTC, fucct commented on src/main/java/lotto/domain/LottoResult.java
> +    public boolean equals(Object o) {
equals&hashcode는 무분별하게 재정의되면, 예상치 못한 예외를 발생시킬 수 있습니다.

2023-07-13 11:20 UTC, fucct commented on src/main/java/lotto/domain/WinningCriteria.java
> +    private final Set<Boolean> bonusResults;
bonusResults가 SetBoolean이어서 어색한것 같아요. 왜 단순한 boolean이 아니라 Set인걸까요?

true이면 bonus결과를 보고, false면 bonus결과를 안보는 식으로도 구현가능해보이네요 :)

2023-07-13 11:20 UTC, fucct commented on src/main/java/lotto/domain/WinningLotto.java
> +    public int matchCount(final List<Ball> balls) {
파라미터를 balls로 하지말고 lotto로 하는건 어떨까요? 
winningLotto는 lotto와 비교하는게 의미상 좋지않을까요?

2023-07-13 11:20 UTC, fucct commented on src/main/java/lotto/domain/LottoGenerator.java
> +public class LottoGenerator {
LottoGenerator가 있어야하나요? 그냥 Controller에서 RandomLottoGenerator를 이용해서 생성하면 될것 같습니다

2023-07-13 11:20 UTC, fucct commented on src/main/java/lotto/domain/WinningStatistics.java
> +        return sum;
stream 을 활용해서 sum을 해볼까요?

2023-07-13 11:20 UTC, fucct commented on src/main/java/lotto/controller/LottoController.java
> +        LottoGenerator lottoGenerator = new LottoGenerator();
메서드가 실행될때마다 LottoGenerator를 생성할텐데, 괜찮을까요?

2023-07-14 06:35 UTC, hwihwi523 commented on src/main/java/lotto/domain/LottoGenerator.java
> +public class LottoGenerator {
처음에는 RandomLottoGenerator만으로 번호 뽑는 것을 생각했습니다!

그런데 현실에서 반자동이나 수동으로도 로또를 생성하는 것이 갑자기 떠올랐고, 추후 확장성을 고려해 전략 패턴을 사용했습니다!

2023-07-14 07:24 UTC, hwihwi523 commented on src/main/java/lotto/domain/LottoResult.java
> +    public boolean equals(Object o) {
말씀 듣고 다시 보니 두 메서드 모두 필요가 없었습니다!

따라서 두 메서드 모두 삭제했고, 삭제한 결과, LottoResult 클래스가 기존의 WinningCriteria enum과 다를 바 없어 LottoResult는 전부 해당 enum으로 대체했습니다!

2023-07-14 07:42 UTC, hwihwi523 commented on src/main/java/lotto/controller/LottoController.java
> +    private final LottoReader lottoReader;
처음에는 구매 금액과 로또 번호는 다른 개념이라고 생각해 Reader, Writer를 나누어 구현했습니다.

그런데 말씀을 듣고 다시 보니 입력을 받거나 출력을 하는 역할은 같은데도 나누어 구현해서 난잡해 보이는 것 같습니다!

그래서 Reader와 Writer를 각각 하나로 합쳐서 응집도를 개선했습니다!

2023-07-14 07:48 UTC, hwihwi523 commented on src/main/java/lotto/domain/WinningCriteria.java
> +    private final Set<Boolean> bonusResults;
가능한 하나의 조건문으로 일반화하여 등수를 판별하고 싶었습니다!

곰곰이 생각해보니 보너스볼을 기준으로 아래와 같이 세 가지의 상태로 나눌 수 있었습니다.
2등 : 보너스볼을 포함해야 한다.
3등 : 보너스볼을 포함하지 않아야 한다.
그 외 : 포함하든 포함하지 않든 상관없다.

따라서, 일치하는 공의 개수와, 현재 보너스볼의 상태가 각 등수의 Set에 포함되는지에 따라 결정되도록 했습니다!

2023-07-14 07:50 UTC, hwihwi523 commented on src/main/java/lotto/domain/WinningCriteria.java
> +    private final Set<Boolean> bonusResults;
이 상태에서 궁금한 점이 있습니다!

혹시 가독성을 위해 여러 개의 조건문으로 구현하는 것과, 위처럼 일반화를 위한 구현 중 어느 게 더 나은 코드일까요??

2023-07-14 08:34 UTC, hwihwi523 commented on src/main/java/lotto/controller/LottoController.java
> +        LottoGenerator lottoGenerator = new LottoGenerator();
리뷰해 주신 것 보고 다시 확인해 보니 LottoGenerator는 매 게임에서 계속 사용될 수 있을 것 같아서, 한 번 생성하고 계속 사용하도록 수정했습니다!

2023-07-15 06:34 UTC, fucct commented on src/main/java/lotto/domain/WinningCriteria.java
> +    private final Set<Boolean> bonusResults;
고민되는 질문이네요. 

개인적으로, 현업에선 코드를 깔끔하게 짜는것도 중요하지만, 가독성이 굉장히 중요한 요소라고 생각해요.
코드를 관리하는 개발자는 자주 바뀌고, 새로운 개발자가 코드를 이해하는데 오랜 시간이 걸리거나 혹은 설명없이 이해할 수 없다면 오랫동안 유지될 수 없는 코드라고 생각하거든요. 

이는 재휘님께서도 스스로 고민해보시고 본인의 기준을 만들어보세요. 조직마다 상황이 워낙 다양해서 어떤게 정답이다 라는건 없는것 같네요.

2023-07-15 06:37 UTC, fucct commented on src/main/java/lotto/domain/LottoGenerator.java
> +public class LottoGenerator {
그렇군요 :) 

다만 만약 반자동, 수동 요구사항이 생기더라도, LottoGenerator를 인터페이스로 두고, RandomLottoGenerator, ManualLottoGenerator로 구현해볼 수도 있을것 같아요. 이런게 진정한 전략패턴이 아닐까 생각이 드네요.

2023-07-15 06:39 UTC, fucct approved these changes
안녕하세요 :) 

기존에도 워낙 잘 작성해주셔서 크게 변경사항이 없었는데요, 리팩토링 이후 코드가 더욱 깔끔해진것 같아서 좋네요! 
주신 질문들에 대해서 현업 개발자의 관점에서 답변을 드렸는데, 혹시 이해가 안되시는 부분이 있으시면 질문 부탁드려요!

다음 단계도 화이팅 해주세요! 수고 많으셨습니다!

2023-07-15 06:39 UTC, merged