Step1 : 로또 페어 프로그래밍
next-step/java-lotto pull request #3283
Opened 2023-07-12 10:03 UTC by jjungsk

## 안녕하세요! 우테캠 6기 교육생 정세권입니다 :)
바쁘신 와중에 이렇게 코드 리뷰 해주신 점 너무 감사합니다!! 아직 부족한 실력이지만 1주차 미션을 진행하면서 새롭게 배웠던 객체 지향적인 사고, 클린 코드, TDD 등을 최대한 적용하며 연습중에 있습니다. 아직 수정할 부분이 많이 있다고 생각하지만 우선 시간이 조금 부족하다는 핑계로 구현은 마무리 되어 리뷰 요청을 먼저 보냈습니다. 아래는 미션을 진행하며 궁금했던 점들을 적었습니다!

## 질문
MVC 패턴을 기준으로 초기 View 에서 넘어온 입력값을 객체에 저장한 뒤, 출력 또는 로직 수행을 위해 그 객체값을 리턴 받을 때 원시 값을 받는것이 나은지 또는 객체 그대로 리턴을 받아 그곳에서 get 또는 다른 메서드를 사용해서 값을 받아 처리하는 것이 나은지 궁금합니다. 특히 Service 에서 일급 컬렉션 안에 래퍼 클래스로 감싼 값을 받아야 하는 경우 getA().getB().getC().. 하는 경우가 있었습니다.

2023-07-13 11:47 UTC, fucct requested changes
안녕하세요! 

미션 잘 수행해주셨네요! 다만 아직 MVC 레이어간 경계가 모호합니다. View관련 로직이 도메인에 들어있고, 도메인을 가지고 View를 그리는 모습이 많이 보이고있어요. 
따라서 우선 패키지를 명확하게 구분하는것부터 시작해보시면 좋을것 같아요. 어디까지가 진짜 View고 어디까지가 domain이고, 어디까지가 Service고, 어디까지가 Controller인지에 대해서 정리해보시고, 그 기준에 맞게 객체들을 리팩토링 해보시길 권해드릴게요.

혹시나 궁금하신 부분 있으시면 편하게 질문주세요 :)

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/Lotto.java
> +package lottogame;
패키지 구조가 불분명한것 같아요. MVC 패턴에 맞게 나뉘어져 있나요?

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/Lotto.java
> +        if (values.size() != 6) {
6같은 매직넘버는 상수화하면 좋을것 같습니다 :)

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/Payment.java
> +        validateBlank(text);
validateBlank와 같은 행위가 Payment의 역할이 맞을까요?

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/LottoService.java
> +    private final Payment payment;
Lotto와 관련된 속성들은 어느 객체에서 가지고 있는게 올바를까요?

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/LottoService.java
> +            Collections.shuffle(lottoPossibleNumbers);
Collection.shuffle은 랜덤을 유발하는 함수입니다. generateLottos를 테스트할 수 있을까요? 

https://jojoldu.tistory.com/674 의 2-1을 읽어보세요 :)

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/LottoService.java
> +        return lottoStatistics.getProfitRate(payment);
LottoStatistics에 profitRate를 계산할 수 있으면, statistics에 profitRate도 필드로 담아서 응답하는건 어떨까요?

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/LottoStatistics.java
> +package lottogame;
Lotto 결과랑 Lotto, WinningNumber등이랑 동일한 패키지에 있는게 괜찮을까요?

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/LottoStatistics.java
> +        float profit = 0;
double형을 사용하시지 않은 이유가 있을까요?

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/LottoStatistics.java
> +        if (matchCount >= 3) {
3, 5같은 값들은 매직넘버는 상수화 하면 좋겠네요.

2023-07-13 11:47 UTC, fucct commented on src/main/java/view/LottoView.java
> +    }
지금 View와 Model의 경계가 온전히 나뉘어지지 않은것 같아요.

우선 LottoMatch, resultMap 모두 도메인 내에서 만들어지는 응답인데, 이를 활용하여 다시 View를 그리는데 사용하고 있어요. 

LottoService가 있다면, LottoService에서 나온 응답을 Controller 단계에서 응답에 맞게 잘 변환을 해준 뒤 View로 던져주거나, Service 단계에서 애초에 View에 적합한 응답객체를 내려주는게 어떨까요?

2023-07-13 11:47 UTC, fucct commented on src/main/java/lottogame/LottoStatistics.java
> +        return String.format("%.2f", profit / payment.getMoney());
이걸 String으로 응답하는것도 View의 로직을 도메인안에 내포하고 있는 형태인것 같아요!

2023-07-13 12:31 UTC, jjungsk commented on src/main/java/lottogame/Lotto.java
> +        if (values.size() != 6) {
넵~!

2023-07-13 12:42 UTC, jjungsk commented on src/main/java/lottogame/Payment.java
> +        validateBlank(text);
View 에 있는게 맞습니다! 추가로 한가지 질문이 있습니다. String 값으로 입력을 받고 숫자로 변환하는 parsing 같은 경우 View 에서 해야할지 Payment 객체에서 해야할지 의문이 듭니다. 그것이 숫자인지 문자인지 판단하는 역할은 Payment가 맞을까요??

2023-07-13 12:53 UTC, jjungsk commented on src/main/java/lottogame/LottoStatistics.java
> +        float profit = 0;
소숫점 5자리 아래 까지는 float 로 해도 충분하다고 생각했지만 보다 정확한 값을 얻기 위해서는 double이 나을것 같습니다!

2023-07-13 12:56 UTC, jjungsk commented on src/main/java/lottogame/LottoStatistics.java
> +        if (matchCount >= 3) {
넵 해당 부분은 코드 수정을 통해 불필요한 if 문을 삭제하는것이 나을것 같습니다!

2023-07-13 14:42 UTC, jjungsk commented on src/main/java/lottogame/Lotto.java
> +package lottogame;
패키지를 불분명하게 나눈것 같습니다
Controller <-> View
Controller <-> Model
이 명확하게 구조를 나누고 해당 기능만 온전히 수행하도록 고민하겠습니다

2023-07-13 15:49 UTC, jjungsk commented on src/main/java/lottogame/LottoService.java
> +            Collections.shuffle(lottoPossibleNumbers);
1차 미션을 토대로 랜덤값 생성을 상위 의존성에 두고 그 값을 Lotto 생성자 변수로 만든다면 Lotto 생성 test는 인자값을 임의로 생성해서 테스트가 가능할 것 같습니다

2023-07-13 16:07 UTC, jjungsk commented on src/main/java/lottogame/LottoService.java
> +        return lottoStatistics.getProfitRate(payment);
객체에 담아서 데이터를 이동하는 것이 원시값으로 넘기는 것 보다 보안, 안정성 측면에서 더 낫다라는 생각이 듭니다!

2023-07-13 16:13 UTC, jjungsk commented on src/main/java/lottogame/LottoStatistics.java
> +package lottogame;
우선 domain 패키지 안에서 통계 결과 패키지 (statistics) 와 로또 게임 (game) 패키지로 나누는 것이 더 나을 것 같습니다. 이 부분에 대해서는 시간을 갖고 신중하게 고민해보겠습니다!

2023-07-13 17:12 UTC, jjungsk commented on src/main/java/lottogame/LottoStatistics.java
> +        return String.format("%.2f", profit / payment.getMoney());
응답 객체를 넘겨주어 View 에서 출력 값을 get 하는 형식이 맞는것 같습니다!

2023-07-13 17:43 UTC, jjungsk commented
리뷰어님의 코드 리뷰를 바탕으로 코드 수정 진행헀습니다! 바쁘신 와중에 꼼꼼한 리뷰 정말 감사합니다 :)

아직 실제 서비스 설계 중 MVC에 맞게 패키지를 나누고 각 객체의 역할을 어디서 어디까지 부여해야 하는지 부족한 부분이 많은 것 같습니다. 지속적인 학습을 통해 성장하도록 노력하겠습니다.

## 2차 수정 사항
- MVC 구조에 맞게 패키지 분리
- View와 Model 역할을 명확히 나누도록 코드 수정
- 매직넘버 수정

2023-07-14 11:13 UTC, fucct commented on src/main/java/lottogame/Payment.java
> +        validateBlank(text);
이 부분은 아마 콘솔 애플리케이션이기 때문에 헷갈리실텐데요. 

현업 코드를 생각해보시면, 쉽게 이해하실 수 있습니다.
일반적으로 현업에서는 프론트엔드 개발자와 백엔드 개발자가 스펙을 정하고, 스펙에 맞게 프론트엔드 개발자가 서버로 정해진 스펙에 맞는 요청으로 전달합니다. 스펙을 정할때 일반적으로 money라는 값은 Long 같은 숫자타입으로 정하겠죠?
따라서 String -> Integer는 프론트엔드에서 변환한 후 서버는 Integer라고 예상하고 요청을 수신하는것이죠. 

이를 콘솔애플리케이션에서 적용해보면, 프론트엔드는 View, 서버는 Controller 부터라고 봐주시면 됩니다. 그럼 당연하게 문자열을 숫자로 변환하는 역할은 View에서 하는게 일반적이라고 볼 수 있습니다 :)

2023-07-14 11:14 UTC, fucct commented on src/main/java/lottogame/LottoStatistics.java
> +        float profit = 0;
차이점을 인지하고 계신다면 굳이 바꾸시지 않으셔도 좋습니다! 혹시나 해서 여쭤봤어요 ㅎㅎ

2023-07-14 11:20 UTC, jjungsk commented on src/main/java/lottogame/Payment.java
> +        validateBlank(text);
아하 현업 입장에서 생각해 봤을 때 View 역할인것이 자연 스럽군요! 자세한 설명 감사합니다!!

2023-07-14 11:25 UTC, fucct approved these changes
안녕하세요 :) 

전체적으로 피드백을 잘 이해하신것 같아서 다행입니다!
우선 아키텍처를 MVC 형태에 잘 맞게 리팩토링 해주신것 같아요! 
다만 여전히 shuffle과 같은 테스트 불가능한 부분이 분리가 안되었고, Service가 가지는 필드들과 메서드 단위가 모호한것 같아서 일부 피드백 남겨드렸어요.
이 부분들은 다음단계를 진행하시면서 함께 반영 부탁드려요. 다만 반드시 알고 넘어가야 하는 부분이라, 직접 코드를 수정해보시면서 개념을 익히시면 좋을것 같습니다.

수고 많으셨고 다음단계 진행해주세요 :)

2023-07-14 11:25 UTC, fucct commented on src/main/java/lotto/service/LottoService.java
> +    private LottoStatistics lottoStatistics;
Payment, LottoStatistics는 굳이 필드로 가지지 않아도 괜찮을것 같아요.

어떻게 보면 Payment가 요청(입력값), LottoStatistics가 응답(출력값)이라고 볼 수 있죠?

2023-07-14 11:25 UTC, fucct commented on src/main/java/lotto/service/LottoService.java
> +        this.lottos = generateLottos();
LottoService와 Lottos가 함께 생성되는게 어색한것 같아요. 사용자의 요청이 들어오는 순간 로또를 만들어야 하지 않을까요?

2023-07-14 11:25 UTC, fucct commented on src/main/java/lotto/service/LottoService.java
> +            autoLottos.add(new Lotto(numberGenerator.shuffleNumbers(), true));
여전히 NumberGenerator의 shuffle 메서드로 인해 로또를 만드는 테스트가 불가능한것 같아요. NumberGenerator를 사용하는 클래스를 어떻게 하면 테스트 가능한 클래스로 만들 수 있을까요?

2023-07-14 11:25 UTC, fucct commented on src/main/java/lotto/service/LottoService.java
> +
ProfitRate도 Result라고 생각해요. 하나의 메서드로 리턴할 수 있을까요?

2023-07-14 11:25 UTC, fucct commented on src/test/java/lotto/LottoServiceTest.java
> +public class LottoServiceTest {
LottoService가 하는일에 비해 테스트가 너무 부족합니다. NumberGenerator가 Shuffle이라는 랜덤을 발생시키고 있기 때문에 테스트를 못하는게 아닐까요?

2023-07-14 11:25 UTC, merged

2023-07-14 11:52 UTC, jjungsk commented on src/main/java/lotto/service/LottoService.java
> +    private LottoStatistics lottoStatistics;
넵!
Payment : View 에서 응답 받은 값을 객체로 담아두 Service 에서 초기 생성할 때 로직 한번만 필요하므로 굳이 필드로 갖을 필요가 없는것 같습니다!
LottoStatistics : 응답 반환 객체로 "로또 결과 값" 과 "수익률" 두가지 필드를 가지고 있는데 "로또 결과 값"의 경우 그대로 View에 보내면 View에서 처리할 로직이 많아 지기 때문에 응답 객체인 LottoResult를 추가했습니다. 이 때 View에 출력을 할 떄 lottSatistics를 2번 이상 호출하여 필드 값으로 빼놨었는데 조금만 더 고심하면 굳이 갖지 않는 방법도 있을 것 같습니다. 해당 부분은 시간을 들여 고민해보겠습니다!

2023-07-14 12:12 UTC, jjungsk commented on src/main/java/lotto/service/LottoService.java
> +        this.lottos = generateLottos();
Lottos 에 역할을 위임하는 것이 더 자연스러운 것 같습니다!

2023-07-14 12:13 UTC, jjungsk commented on src/main/java/lotto/service/LottoService.java
> +            autoLottos.add(new Lotto(numberGenerator.shuffleNumbers(), true));
해당 부분 좀 더 고민해보도록 하겠습니다!

2023-07-14 12:15 UTC, jjungsk commented on src/main/java/lotto/service/LottoService.java
> +
이익률도 결과의 통계 중 하나라고 생각해서 LottoStatistics 필드에서 관리했었습니다. 이 부분도 따로 값을 빼는 것이 나아보입니다!

2023-07-15 16:29 UTC, jjungsk commented on src/main/java/lotto/service/LottoService.java
> +    private LottoStatistics lottoStatistics;
코드 리팩토링 중 LottoService 에서 명확히 지녀야할 역할이 없다고 판단하여 삭제했습니다.
필요한 역할은 알맞은 객체에 위임하였습니다.

2023-07-15 16:30 UTC, jjungsk commented on src/main/java/lotto/service/LottoService.java
> +        this.lottos = generateLottos();
Lottos 역할 위임에 따른 LottoService를 삭제했습니다!

2023-07-15 16:38 UTC, jjungsk commented on src/main/java/lotto/service/LottoService.java
> +            autoLottos.add(new Lotto(numberGenerator.shuffleNumbers(), true));
NumberGenerator 자체를 인자값으로 내려 보내 numberGenerator 함수를 재정의하여 테스트를 진행했습니다!

2023-07-15 16:56 UTC, jjungsk commented on src/test/java/lotto/LottoServiceTest.java
> +public class LottoServiceTest {
NumberGenerator 를 인자값으로 넘겨주어 테스트 가능하도록 수정했습니다!