Step2. 수동 로또 미션
next-step/java-lotto pull request #3298
Opened 2023-07-15 17:25 UTC by jjungsk

안녕하세요 ☺️  바쁘신 와중에 항상 꼼꼼한 리뷰 정말 감사합니다!!
1차 미션 때 꼼꼼하게 해주신 리뷰 바탕으로 코드 리팩토링 및 2차 미션 진행했습니다

## 수정 사항
- LottoService 삭제 : 각 역할에 맡는 메소드를 객체에 위임하면서 불필요한 LottoService 삭제했습니다
- NumberGenerator 를 인자값으로 넘겨주고 실제 Test에서 관련 메소드를 overriding 하여 Lotto 생성 및 테스트를 진행했습니다
- 각 메소드를 객체에 맞게 다시 위임하였습니다

## 추가 사항
- 수정, 자동 로또 생성에 따른 각 로또릐 갯수를 필드 값으로 가지고 있는 LottoCount 객체를 추가했습니다

2023-07-17 03:11 UTC, fucct requested changes
안녕하세요 :) 

생각보다 많은 변경이 있었네요.
미션의 2단계는 기본적으로 1단계의 내용의 변경을 최소화 하면서 추가 요구사항을 구현하는건데, 요구사항과 관계없는 리팩토링이 많아진것 같아요.
리팩토링 과정에서 어색한 부분이 보여 피드백 남겨드렸으니 확인 부탁드려요.

2023-07-17 03:11 UTC, fucct commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(lottoCount, lottoManuals, numberGenerator);
NumberGenerator는 구현체라 런타임에 유동적으로 변경할 수 없을것 같아요. 따라서 Lottos 테스트도 불가능할것 같아요

2023-07-17 03:11 UTC, fucct commented on src/main/java/lotto/controller/LottoController.java
> +        // 1-1. 구입
불필요한 주석은 제거해주세요. 그리고 주석으로 분류된 기준을 메서드로 나누면 메서드를 라인 수 제한 요구사항을 만족할 수 있을것 같아요

2023-07-17 03:11 UTC, fucct commented on src/main/java/lotto/controller/LottoController.java
> +        LottoStatistics lottoStatistics = new LottoStatistics(lottos, winningNumber, payment);
좀 어색한 부분이 있어요.
객체의 행위는 상태를 아는 객체가 수행해야 합니다.
여기서 로또의 상태는 lottos가 알고있는데, lottos는 단순히 데이터만 들고있고, 행위는 모두 LottoStatistics에서 수행하고 있어요. 

lottos를 좀 더 능동적으로 만들고, LottoStatistics대신 바로 LottoResults를 반환하도록 해서 domain과 View를 명확하게 구분하면 좋을것 같아요. 

LottoStatistics가 View와 도메인의 중간 객체 포지션인데, 핵심 비즈니스를 모두 가지고있네요.

2023-07-17 03:11 UTC, fucct commented on src/main/java/lotto/controller/LottoController.java
> +        lottoView.printProfitRate(lottoStatistics);
심지어 이익률은 LottoStatistics로 출력하고 있는데, View와 도메인이 완전히 분리된게 맞을까요?

2023-07-17 03:11 UTC, fucct commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(lottoCount, lottoManuals, numberGenerator);
Service를 제거하게 되신 계기도 궁금합니다.

2023-07-17 03:11 UTC, fucct commented on src/main/java/lotto/domain/game/Lottos.java
> +    private List<Lotto> generateLottos(
현재 로또 생성 방식이 꽤 복잡하네요. 

이렇게 생성자의 역할이 복잡해질때, Factory 클래스를 활용해보는것도 좋은것 같아요.

2023-07-17 03:11 UTC, fucct commented on src/main/java/lotto/domain/game/Lotto.java
> +        if (!isAuto && (values.size() < LOTTO_SIZE || (LOTTO_SIZE < values.size()))) {
auto와 manual이 다른 이유가 있나요?

2023-07-17 03:11 UTC, fucct commented on src/main/java/lotto/domain/game/Lotto.java
> +    private List<Integer> toIntegers(final String text) {
View와 관련된 로직이 도메인에 침투해있는것 같아요

2023-07-17 04:39 UTC, jjungsk commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(lottoCount, lottoManuals, numberGenerator);
interface를 만들고 NumberGenerator가 구현체가 되도록 하는것이 나을것 같습니다.

2023-07-17 04:40 UTC, jjungsk commented on src/main/java/lotto/controller/LottoController.java
> +        // 1-1. 구입
넵 불필요한 주석은 제거하는것이 맞는것 같습니다.

2023-07-17 05:02 UTC, jjungsk commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(lottoCount, lottoManuals, numberGenerator);
Service에서 관리하는 Payment 및 다른 필드값들이 굳이 필요가 없어졌습니다. 또한 Service에서 진행하는 행위들을 각 객체에 맡게 위임하니 Service에서 특별히 관리하는게 없다고 판단되어 제거하게 되었습니다!

2023-07-17 05:02 UTC, jjungsk commented on src/main/java/lotto/controller/LottoController.java
> +        lottoView.printProfitRate(lottoStatistics);
이익률도 Payment 객체를 분리하여 관리하는 것이 자연스러워 보입니다!

2023-07-17 15:12 UTC, jjungsk commented on src/main/java/lotto/controller/LottoController.java
> +        LottoStatistics lottoStatistics = new LottoStatistics(lottos, winningNumber, payment);
초기에 Lottos에 통계까지 담당하는 행위는 과하다는 생각이 들어 결과 통계와 이익률을 필드로 갖고 그 행위를 하는 domain을 만들 목적으로 LottoStatistics를 설계했습니다. 하지만 리뷰어님 말처럼 객체의 행위는 상태를 아는 객체가 수행해야 된다는 말씀이 맞는것 같습니다! Lottos에 행위를 위임하고 Profit을 관리하는 domain을 추가하는 것이 자연스러워 보입니다. 그렇다면 LottoStatistics가 하는 일이 없어 자연스럽게 사라질것 같습니다.

2023-07-17 15:24 UTC, jjungsk commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = new Lottos(lottoCount, lottoManuals, numberGenerator);
혹시 이부분에 대해서 제가 간과한 부분이 있다면 알려주시면 감사하겠습니다!

2023-07-17 15:55 UTC, jjungsk commented on src/main/java/lotto/domain/game/Lottos.java
> +    private List<Lotto> generateLottos(
생성자의 역할이 복잡해지거나 객체 생성이 중요해질 때 정적 팩토리 메서드를 사용한다고 배웠습니다! 실제로 그렇게 리팩토링 해보니 Controller에서
List<Lotto> lottosManul = Lottos.createMaual(text);
List<Lotto> lottosAuto = Lottos.createAuto(integers, new RandomGeneratorImpl);
Lottos lotts = new Lottos(lottosManual, lottosAuto); <- 오토와 메뉴얼의 모든 lottos를 관리하기 위해
즉, 객체를 굳이 나눌 필요성이 현재 로직에서는 조금은 불필요하고 Controller 에서 객체 생성이 많아 지는것 같습니다. 해당 부분은 혹시 제가 잘못 이해하고 코드를 작성하려는 것인지 궁금합니다!

2023-07-17 16:01 UTC, jjungsk commented on src/main/java/lotto/domain/game/Lotto.java
> +        if (!isAuto && (values.size() < LOTTO_SIZE || (LOTTO_SIZE < values.size()))) {
Lotto가 6개의 숫자를 가지고 있다라는 사실은 Lotto 객체가 가지고 있다는 판단이 들었습니다. 하여 Lotto에서 해당 상수를 관리하고 있으며 RandomGenerator에서 생성한 자동 로또는 1~45의 숫자 리스트 전부를 shuffle해서 Lotto로 넘겨줍니다. 이 때 자동 생성 로또는 validateSize 굳이 판별할 필요가 없습니다. 하지만 수동 로또 생성의 경우 정확히 6개의 숫자가 넘어오면 판별해야하기 때문에 해당 부분은 true/false 값으로 넘겨 주었습니다. 또한 추가 사항으로 수동 로또와 자동 로또의 분기를 나눌 가능성이 생길수도 있겠다고 판단하여 Lotto 생성에서의 인자로 boolean을 넘겨주긴 했습니다.
추가로 동기 친구들과 얘기를 나눠보며 그럴때는 차라리 class를 나눠서 관리하는것이 각 객체가 본인만의 역할을 수행하는데 있어 관리하기가 쉬울 것 같다라는 생각이 들었습니다.

2023-07-17 16:25 UTC, jjungsk commented on src/main/java/lotto/domain/game/Lotto.java
> +    private List<Integer> toIntegers(final String text) {
해당 부분 View에서 처리하는게 맞는것 같습니다.
console 애서 숫자의 리스트를 String 타입으로 받기 때문에 List<Integer> 변환시 List<List<Integer>> 로 반환 하게 되어 List<Integer>를 필드로 갖고 String을 List<Integer>로 변환하는 행위를 갖는 LottoManual 객체를 RequestDto로 만들어 View에서 해당 객체의 List로 응답 받는 식으로 코드를 리팩토링 했습니다!

2023-07-17 16:33 UTC, jjungsk commented
주말에 코드를 보고 생각이 많아져서 불필요한 코드 수정이 있었던 것 같습니다!
조금 더 생각하고 코드를 작성하는 자세를 갖도록 노력하겠습니다. 수정사항 및 질문들은 위에 답글로 달아 놓았지만 아래 부분에 요약해놓았습니다!

## 코드리뷰 후 수정 사항
- NumberGenerator Interface 추가하여 test 가능하도록 작성했습니다.
- 이익률의 역할만 수행하는 ProfitRate 객체를 추가했습니다.
- View에서 Lotto 리스트를 String type 으로 받아 List<List<Integer>로 응답을 반환하기 때문에 LottoManual RequestDto를 추가했습니다.
- Lottos에서 lotts의 필드를 가지고 있으므로 로또의 결과에 대한 행위를 위임하고 LottoResult에 그 결과값을 담아 리턴했습니다.

2023-07-19 08:01 UTC, fucct approved these changes
안녕하세요! 코드리뷰가 좀 늦어져서 죄송합니다. 😢

전체적으로 코드는 깔끔한데, Manual 로또와 Auto 로또의 구분이 약간 아쉽네요. 생성방식의 차이이지, 내부적으로 동일한 로또라고 생각하거든요. 굳이 구분하지 않고 수동로또의 경우 사용자가 입력한 List<Integer> (6개 숫자), 자동로또의 경우 RandomGenerator가 만들어준 List<Integer> (6개 숫자)로 한다면, 생성 방식이 달라질 필요는 없는것 같아요.

그 외에는 특별히 리뷰드릴 내용은 없는것 같습니다. 잘 작성해주셨기때문에 이만 Merge  하도록 할게요. 로또 생성방식에 대해선 한번 더 고민해보시면 좋을듯 합니다 :) 

수고많으셨습니다!

2023-07-19 08:01 UTC, merged