🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #3319
Opened 2023-11-10 10:41 UTC by kimgwanghoon

로또자동 구현했습니다.
리뷰 잘부탁드리겠습니다~

2023-11-10 23:27 UTC, wooobo requested changes
안녕하세요 광훈님!

2단계 잘 진행해주셨네요~!
코멘트 남겨 놓았는데 확인 부탁드려요~

그럼 화이팅입니다!

2023-11-10 23:27 UTC, wooobo commented on src/main/java/lotto/domain/RankLotto.java
> +    FIRST(6, 2000000000),
```suggestion
    FIRST(6, 2_000_000_000),
```
이렇게 표기하면 단위를 알아보기 더 쉽더라구요!

2023-11-10 23:27 UTC, wooobo commented on src/main/java/lotto/domain/WinnerResult.java
> +        this.result = Collections.unmodifiableMap(result);
엇 생성자에서도 지정을 하는 관점도 있군요!

2023-11-10 23:27 UTC, wooobo commented on src/main/java/lotto/view/ResultView.java
> +    public void print(String result) {
내부상태를 가지지 않는다면, static 메소드로 전환하고, 
기본 생성자를 `private`을 만들어줘도 좋을것 같아요!

2023-11-10 23:27 UTC, wooobo commented on src/test/java/lotto/domain/LottoTest.java
> +        assertThat(result).isEqualTo(4);
```suggestion
Lotto lotto = new Lotto(List.of(
                new LottoNumber(10),
                new LottoNumber(2),
                new LottoNumber(3),
                new LottoNumber(40),
                new LottoNumber(5),
                new LottoNumber(6)
        ));
        Lotto lottoNumber = new Lotto(List.of(
                new LottoNumber(1),
                new LottoNumber(2),
                new LottoNumber(3),
                new LottoNumber(4),
                new LottoNumber(5),
                new LottoNumber(6)
        ));
        // when
        int result = lotto.match(lottoNumber);
        // then
        assertThat(result).isEqualTo(4);
```

개인적으로는 테스트 하고자 하는것은 `lotto.match(lottoNumber);`인것 같아요!
그런면에서 `FixtureNumberStrategy`에 대한 의존성이 추가되어야할까? 생각이 들어요~

아니면, `FixtureNumberStrategy.로또넘버_생성함(10,2,3,40,5,6);` 이렇게해서 테스트의 가독성을 증가시켜볼것같아요!

2023-11-11 00:06 UTC, kimgwanghoon commented on src/test/java/lotto/domain/LottoNumberTest.java
> +        lottoNumber = new LottoNumber(number);
@BeforeEach 를 사용하지않은건 int numbe값을 테스트시 넣어서 사용하려고 안걸었습니다.

2023-11-11 00:08 UTC, kimgwanghoon commented on src/main/java/lotto/domain/RankLotto.java
> +    FIRST(6, 2000000000),
놓치고 있었네요

2023-11-11 00:17 UTC, kimgwanghoon commented on src/main/java/lotto/domain/WinnerResult.java
> +        this.result = Collections.unmodifiableMap(result);
생성할때 데이터가 변할 필요가 없으면 생성자에 지정해도 되지않을까 생각해서 적용해봤습니다.

2023-11-11 00:22 UTC, kimgwanghoon commented on src/main/java/lotto/view/ResultView.java
> +    public void print(String result) {
main에서 도 print로 출력을 해야해서 private로 변경은 하지않고 static로 전환은 해야겠네요.

2023-11-11 00:48 UTC, kimgwanghoon commented on src/test/java/lotto/domain/LottoTest.java
> +        assertThat(result).isEqualTo(4);
실제처럼 자동테스트 번호를 만들고 당첨결과를 비교하는 테스트를 하려고 했습니다.
지금보니 `Lotto lotto = numberStrategy.create(1).get(0);` 로 로또를 받으면 되는데 못보고 넘어갔네요.
변수명도 수정했습니다.

2023-11-11 00:49 UTC, kimgwanghoon commented on src/main/java/lotto/domain/Lotto.java
> +        return lottoNumbers.stream()
여기엔 `Collections.unmodifiableList` 를 적용안했었네요. 수정했습니다.

2023-11-11 08:11 UTC, wooobo commented on src/test/java/lotto/domain/LottoNumberTest.java
> +        lottoNumber = new LottoNumber(number);
아하! 그런거였군용 ㅎ
https://jojoldu.tistory.com/611
포스팅 관점 참고해보아도 좋을듯해요!

2023-11-11 08:11 UTC, wooobo commented on src/test/java/lotto/domain/LottoNumberTest.java
> +        lottoNumber = new LottoNumber(number);
아하! 그런거였군용 ㅎ
https://jojoldu.tistory.com/611
포스팅 관점 참고해보아도 좋을듯해요!

2023-11-11 19:26 UTC, wooobo approved these changes
안녕하세요 광훈님!

2단계 잘 진행해주셨습니다 :)
몇가지 코멘트 남겨 놓았는데,
다음단계 진행하시기 전에 참고 붙가드립니다~

그럼 화이팅입니다!

2023-11-11 19:26 UTC, wooobo commented on src/test/java/lotto/validate/NumberValidationTest.java
> +        }).withMessageMatching("로또 번호는 1부터 45까지의 숫자만 가능합니다.");
```suggestion
        }).withMessageMatching("로또 번호는 1부터 45까지의 숫자만 가능합니다.");
```
미션에서는 로또 범위가 변경되지 않지만,
만약 변경된다면 불필요하게 테스트가 실패될수 있지 않을까? 라는 생각을 해볼수도 있을것 같아요!

`일반화`하거나 `변하는 부분과 변하지 않는 부분 분리`같은 방법들이 있을것 같아요.
일반화 한다면, `로또번호는 숫자만 가능합니다` 이런식으로요!

2023-11-11 19:26 UTC, merged

2023-11-12 08:13 UTC, kimgwanghoon commented on src/main/java/lotto/domain/WinnerResult.java
> +        sb.append("당첨 통계\n");
main 콘솔에서만 하면 view에 책임을 넘기면 되지만 다른것으로 구동할경우 문구생성을 동일하게 해야하지않을까 해서 toString에 만드는게 어떨까 생각했습니다.

2023-11-12 08:13 UTC, kimgwanghoon commented on src/main/java/lotto/view/InputView.java
> +    public static int inputMoney() {
이건 몰랐던 부분이네요. 참고해서 수정하겠습니다😀