Step3 - 로또(2등)
next-step/java-lotto pull request #3325
Opened 2023-11-11 09:04 UTC by G0RANI

안녕하세요 석홍 리뷰어님!
3번째 PR 보내 드립니다.
잘 부탁드리겠습니다.
클래스를 잘게 쪼개다 보니까 어디까지 객체를 랩핑 해야 하는지 기준이 잘 나오지 않는데 혹시 기준이 있으실까요?
이번에 미션 하면서 numbers와 number까지 클래스를 일급객체로 나누는것에 대하여 너무 과하다 생각하여 numbers에 있던 기능을 lotto로 위임 하게 되었습니다...!
감사합니다 : )

2023-11-11 11:44 UTC, seokhong commented
> 클래스를 잘게 쪼개다 보니까 어디까지 객체를 랩핑 해야 하는지 기준이 잘 나오지 않는데 혹시 기준이 있으실까요?

정우님, 질문에 대한 제생각을 먼저 코멘트로 남깁니다.

저도 말씀하신 부분이 참 어렵고, 기준이 모호하다고 생각합니다. 어느정도 휴리스틱한 부분도 있음을 부정하기는 어렵네요.
큰 원칙은 낮은 결합도, 높은 응집도를 지향하고, SOLID 원칙을 지키려고 노력하면서도, 현재의 요구사항을 만족하며 동작하는 가장 단순한 형태로 구현하고자 합니다. 책을 통해 학습하고 고민해보시는 것을 추천드리고 싶은데, 클린 소프트웨어라는 책과 오브젝트라는 책이 도움이 될 것 같습니다.

더 구체적인 상황과 선택할 수 있는 안을 놓고 이야기를 나눠보면 더 깊은 이야기를 나눠볼 수 있을 것 같습니다.

한편, 구체적인 사례를 가지고 이야기 하더라도 답을 찾을 수는 없을거라고 생각합니다. 이유는 현재의 코드의 품질은 장기적인 측면에서 평가되는데(장기적으로 유지보수하기 용이한가와 같은 측면), 장기적으로 요구사항이 어떻게 변할지 알기 어렵기 때문입니다. 즉, 제 생각은 "답이 계속해서 변할 수 있는 상황에서 답을 찾고자 하는 것이 아닐까?" 라는 것입니다. 그래서, 미래의 변화에 맞는 최적의 답을 찾기보다는, 현재 동작하는 가장 단순한 형태로 구현하는 것을 지향하게 된 것 같기도 합니다.

2023-11-11 12:12 UTC, seokhong requested changes
정우님, 3단계 미션 잘 구현하셨습니다. 👍 
질문 남겨주신 내용에 대한 답변 포함하여 코드에 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-11-11 12:12 UTC, seokhong commented on src/test/java/lotto/domain/WinningLottoTest.java
>      void 당첨로또번호로_구입로또_등수를_알_수_있다() {
모든 등수에 해당하는 케이스를 확인해봐도 좋을 것 같아요!
보너스 번호 포함 여부까지 함께 테스트 코드가 있으면, `LottoRank` 가 의도한 조건대로 잘 반환되는지 확인할 수 있을 것으로 보이네요.

2023-11-11 13:40 UTC, G0RANI commented on src/main/java/lotto/domain/Bonus.java
> +public class Bonus {
이부분은 제가 놓친 부분중 하나입니다...!
WinningLotto의 numbers는 해당 내용과 비슷한 성격이여서 캐치를 하여 Lotto로 교체를 하였는데 클래스를 계속 나누는데 집중하고 이렇게 세세하세 나눈적은 없어 아직은 눈에 잘 들어오지 않는듯합니다...!

2023-11-11 13:42 UTC, G0RANI commented on src/main/java/lotto/domain/Lotto.java
> +        for(LottoNumber lottoNumber : lottoNumbers) {
아래도 비슷한 내용이 있고 전 미션에도 비슷한 내용이 있었는데 체크하기가 힘드네요 ㅠㅠ 말해주신것처럼 설정을 꼭 찾아서 적용해보겠습니다.
감사합니다!!

2023-11-11 13:47 UTC, G0RANI commented on src/main/java/lotto/controller/LottoController.java
> +        BuyingAmount buyingAmount = new BuyingAmount(InputView.inputAmount(scanner));
해당 내용은 솔직하게 딱히 생각을 하지 않고 만들었습니다.
Input이나 Result같은 경우 어디에서나 변화하지 않고 편하게 생성해서 사용을 안하며 인스턴스 변수로 꼭 써야하나 생각을 하였으나, 조금 더 생각해보니 IO 가 일어나는 부분이 꼭 Scanner가 되라는 법이 없고 파일업로드 라던지 여러 경우가 생길 경우를 생각하여 생성자로 관리하여 주입받는것이 더 좋은 방법이겠구나 라는 생각을 하게 되었습니다.
좋은 의견 감사합니다!! 😀

2023-11-11 14:46 UTC, G0RANI commented
남겨주신 내용이 정말 도움이 많이 되었습니다.
감사합니다!!

2023-11-12 08:04 UTC, seokhong approved these changes
정우님, 3단계 미션 코멘트 잘 반영하셨습니다. 👍 
3단계 PR 머지하겠습니다.
4단계 미션에서 뵙겠습니다. 🙂

2023-11-12 08:04 UTC, seokhong commented on src/main/java/lotto/view/InputView.java
> +    private final Scanner scanner;
상수와 필드 사이에도 공백을 추가해서 영역을 나눠주면 가독성이 더 좋아질 것 같아요! :)

2023-11-12 08:04 UTC, merged