🚀 1단계 - 문자열 계산기 PR
next-step/java-lotto pull request #3343
Opened 2023-11-12 14:07 UTC by gkssk4163

안녕하세요, 리뷰어님
로또 - TDD 미션 잘 부탁드립니다 😁

2023-11-13 04:00 UTC, csh0034 requested changes
안녕하세요. 한나님!
로또 미션을 함께하게 된 최승훈입니다. 

1단계 문자열 계산기 구현 관련하여 
몇가지 코멘트 남겨두었는데 확인해주시고
다시 리뷰 요청 부탁드립니다!

혹시 코멘트가 이해 안가시거나 추가로 궁금하신 사항 
있으시면 편하게 DM 주세요 😄

2023-11-13 04:00 UTC, csh0034 commented on src/main/java/step1/README.md
> +### 구현할 기능 목록
기능목록 작성 잘해주셨네요 👍

기능요구사항과 프로그래밍 요구사항은 추가하지 않으셔도 될 것 같습니다.
추가로 README.md 파일은 별도 추가가 아닌 프로젝트 최상위에 있는 파일에  작성 부탁드려요!

2023-11-13 04:00 UTC, csh0034 commented on src/main/java/step1/domain/Number.java
> +public class Number {
원시값을 포장  👍

하지만 별도 내부에 검증이 없고 생성자를 통해 문자열을 정수값으로 변경한다는것만 제외하면
int 자료형과 동일한데요. 이러한 경우 원시값을 꼭 포장해야하는걸까요? 🤔

2023-11-13 04:00 UTC, csh0034 commented on src/main/java/step1/domain/Operator.java
> +    private String op;
`규칙 5: 줄여쓰지 않는다(축약 금지).` 를 지켜보시면 좋을것 같아요.

2023-11-13 04:00 UTC, csh0034 commented on src/main/java/step1/domain/Operator.java
> +        String fourOperators = "+-*/";
매직리터럴은 상수로 표현해보면 좋을것 같습니다.

2023-11-13 04:00 UTC, csh0034 commented on src/main/java/step1/domain/StringCalculator.java
> +        if (op.isAdd()) return calculator.add(left, right);
https://google.github.io/styleguide/javaguide.html#s4.1-braces

구글 자바 스타일 가이드에 맞춰 한줄이더라도 중괄호는 추가해주세요!

2023-11-13 04:00 UTC, csh0034 commented on src/test/java/step1/domain/CalculatorTest.java
> +class CalculatorTest {
구현하려는 사칙연산에 대해서 테스트 코드 잘 추가해주셨네요 👍

2023-11-13 04:00 UTC, csh0034 commented on src/main/java/step1/domain/Operator.java
> +public class Operator {
각 연산자들을 Enum 으로 표현해보면 어떨까요 🤔

2023-11-13 04:00 UTC, csh0034 commented on src/main/java/step1/domain/StringCalculator.java
> +        Calculator calculator = new Calculator();
Calculator 의 경우 상태를 가지지 않으므로 매번 객체를 생성하지 않고
한번만 생성해보면 좋을것 같습니다.

2023-11-13 04:00 UTC, csh0034 commented on src/main/java/step1/domain/StringCalculator.java
> +public class StringCalculator {
Enum 과 IntBinaryOperator 또는 `Map<연산자, IntBinaryOperator>` 의 캐싱처리를 통하여 사칙연산에 대한 중복코드를 제거해보시면 좋을것 같습니다.

2023-11-13 04:00 UTC, csh0034 commented
## 1. gitkeep 삭제

.gitkeep 파일의 경우 git 은 디렉토리에 파일이 없을 경우 업로드 되지않아 
디렉토리 구조를 유지시키기 위한 파일입니다. 파일을 추가해주셨으니 삭제해주셔도 됩니다.

## 2. 패키지 구조

step1 이후에 step 2,3,4 의 경우 로또에서 요구사항이 점점 추가되어 기존 코드를 수정하므로 
/src/main/java/calculator, /src/main/java/lotto 등과 같이 기능별로
패키지 분리를 하시는걸 추천드립니다.

또한 모두 domain 패키지에 구현이 되어있습니다.
domain 인 클래스와 아닌 클래스를 구분해서 패키지를 나눠보시면 좋을것 같아요!

2023-11-14 15:28 UTC, gkssk4163 commented on src/main/java/step1/domain/Number.java
> +public class Number {
> 원시값을 포장 👍
> 
> 하지만 별도 내부에 검증이 없고 생성자를 통해 문자열을 정수값으로 변경한다는것만 제외하면 int 자료형과 동일한데요. 이러한 경우 원시값을 꼭 포장해야하는걸까요? 🤔

`규칙 3: 모든 원시값과 문자열을 포장한다.` 라는 규칙을 지키기 위해 원시값 포장을 진행해보았습니다!

하면서도 이렇게까지 포장을 해줘야 할까 하는 생각이 들었는데요,
질문을 주셔서 관련 내용을 찾아보니 간단한 기능이어도 원시값 포장을 해두면 유연하게 관리를 할 수 있어서 좋을 것 같습니다!
예를 들어, 지금은 int 타입 계산기 이지만, float 타입으로 변경이 필요하면 `Number` 객체에 대해서만 수정해주면 되기 때문에 유지보수하기 더 좋을 것 같습니다.

다만 제가 구현한 `StringCalculator`는 원시값 포장을 사용한 부분과 int 자료형을 사용한 부분이 섞여있어 자료형이 변경되면 수정해줘야 하는 부분이 많은 상태네요😅
원시값으로 통일을 해주는 방향으로 수정해보겠습니다!

2023-11-15 23:18 UTC, gkssk4163 commented on src/main/java/step1/domain/StringCalculator.java
> +public class StringCalculator {
원시 값을 포장해둬서 `BiFunction` 사용해서 구현해보았습니다!

2023-11-16 03:26 UTC, gkssk4163 commented
피드백 내용 반영하여 다시 리뷰요청드립니다!

Q. 유지보수를 위해 사용하는 게 좋다고 생각하여 숫자를 Number로 포장한 상태로 진행을 해보았습니다. 이 부분에 대해 리뷰어님은 어떻게 생각하시는지 의견이 궁금합니다!

2023-11-16 09:29 UTC, csh0034 approved these changes
리뷰 잘 반영해주셨네요! 💯 
몇가지 코멘트 남겨 두었는데 다음단계 진행전에
반영 부탁드려요 😄 
다음단계에서 뵙겠습니다.

2023-11-16 09:29 UTC, csh0034 commented on src/main/java/calculator/domain/StringCalculator.java
> +        Queue<String> operatorSequence = new ArrayDeque<>();
```suggestion
Queue<String> operatorSequence = new ArrayDeque<>(List.of(split(strOperation)));
```

2023-11-16 09:29 UTC, csh0034 commented on src/main/java/calculator/domain/StringCalculator.java
> +        Number cumulativeValue = firstValue;
cumulativeValue 는 사용하지 않아도 될 것 같아요!

2023-11-16 09:29 UTC, merged

2023-11-16 09:39 UTC, csh0034 commented
질문에 대해서 답변드립니다.

현재 Number 클래스에 대해서는 우선 이름을 보았을때
숫자라는점을 제외하곤 어떠한 비지니스적인 개념이 들어가있지 않다고 생각해요
Intenger 의 super class 의 Number 와 동일한 이름을가지고 있기도합니다.

또한 현재 내부 별다른 검증이 없기 때문에 int 를 사용한것과 비교하면
dot 를 통해서 value() 에 접근하기 때문에 객체의 탐색 깊이가 길어지는 단점이 있습니다. 

따라서 String 이란 타입을 단순히 Input 이라고 감싸놓은것과 동일한것 같아
비지니스적으로 명확하게 이름을 표현할수없으며 내부 검증 및 기능이 없다면 
wrapping 하지 않는것이 좋다라고 생각합니다.

`모든 원시값과 문자열을 포장해보는점`은 리뷰 진행하시면서 여러 부분에 적용하시다보면
적절한 기준이 생기며 다양한 인사이트를 얻게 되실수 있기 때문에 고민해보시면서 
적극적으로 적용해보시면 좋을것같아요!