[step2] 2단계 - 로또(자동)
next-step/java-lotto pull request #3347
Opened 2023-11-12 17:53 UTC by jin-mook

안녕하세요 2단계 - 로또(자동) 미션 리뷰 요청드립니다.

기존 리뷰에 함수형 인터페이스 관련 댓글에 질문 하나 남겼는데 같이 확인 부탁드리겠습니다!!

감사합니다.

2023-11-12 17:54 UTC, jin-mook commented
기존 step1 리뷰 url 입니다. 함수형 인터페이스 관련 질문 남겼습니다!!
[step1](https://github.com/next-step/java-lotto/pull/3322)

2023-11-13 07:47 UTC, testrace requested changes
안녕하세요 진묵님 😃 
2단계 빠르게 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요
궁금한 점이나 의견 있으시면 DM 남겨주세요

2023-11-13 07:47 UTC, testrace commented on src/main/java/lottoauto/domain/aggregate/LottoShuffler.java
> +                .collect(Collectors.toList());
로또에서 사용되는 번호들을 미리 만들어 두고 재사용하면 어떨까요?

2023-11-13 07:47 UTC, testrace commented on src/main/java/lottoauto/domain/aggregate/WinnerBoard.java
> +        winnerBoard.put(6, 0);
3, 4, 5, 6은 Aggregator 클래스에서도 사용되었는데요
곳곳에 동일한 의미를 가진 값들이 여러 곳에서 사용될 경우 의도치 않은 이슈 발생 확률이 높다고 생각해요
`등수` 라는 클래스를 도출해서 WinnerBoard에서도 사용하면 어떨까요?

2023-11-13 07:47 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lotto.java
> +    }
로또 한 장은 중복되지 않은 6개의 번호를 가져야 하니 관련 유효성 검증도 추가하면 어떨까요?

2023-11-13 07:47 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Numbers.java
> +    }
메서드명이 match 이니 일치 여부 true/false 를 반환하면 어떨까요?
외부에서 메서드를 봤을 때 result 값을 누적해서 반환해 줄거라는 기대를 하기 힘들 것 같아요

2023-11-13 07:47 UTC, testrace commented on src/test/java/lottoauto/domain/aggregate/AggregatorTest.java
> +    }
의도하지 않는 상황에 대한 제약을 충분히 검증해 보시면 좋을 것 같아요
![image](https://github.com/next-step/java-lotto/assets/8064743/5dbadcd2-69d2-4260-9a30-8b009810c88a)

2023-11-13 07:47 UTC, testrace commented on src/main/java/lottoauto/LottoAuto.java
미션 페이지 하단을 보시면 아래와 같은 요구사항이 있는데요
> 프로그래밍 요구사항
> - 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다

>기능 목록 및 commit 로그 요구사항
> - 기능을 구현하기 전에 README.md 파일에 구현할 기능 목록을 정리해 추가한다.
> - git의 commit 단위는 앞 단계에서 README.md 파일에 정리한 기능 목록 단위로 추가한다.

TDD로 구현하기 위해선 기능 목록이 도움이 됩니다
1단계 미션 페이지의 `기능 분리 힌트`를 참고하셔서 기능 목록을 만드시고 작은 단위로 커밋해 보시면 좋을 것 같습니다

2023-11-13 18:12 UTC, jin-mook commented on src/main/java/lottoauto/domain/aggregate/Aggregator.java
> +public class Aggregator {
당첨 로또인지 확인하는 부분은 Lottos 객체로 넘겼습니다

2023-11-13 18:14 UTC, jin-mook commented on src/main/java/lottoauto/domain/aggregate/Aggregator.java
> +    private static final int EACH_LOTTO_PRICE = 1000;
Lottos 객체에 public static final 변수로 설정했습니다. 공통으로 사용되는 변수라고 생각해서 위치는 Lottos에 존재하는게 맞는것같고 대신 static 변수로 설정했습니다.

로또를 생성하는 LottosMaker 클래스를 만들었습니다. 기존에는 Aggregator클래스에서 Lotto 들을 생성했는데 Lotto 리스트를 갖는 Lottos 클래스를 설정하고 LottosMaker 를 통해 해당 객체를 만들 수 있도록 변경했습니다.

2023-11-13 18:16 UTC, jin-mook commented on src/main/java/lottoauto/domain/aggregate/Aggregator.java
> +                    }
로또 번호의 경우는 LottoShuffler 를 통해 랜덤으로 생성하고 있습니다. 이때 랜덤으로 값을 생성하다보니 repeated 테스트를 통해 제약에 대한 테스트를 했는데 이런 식으로 테스트를 하는건 어떤가요?? LottoShuffler에서 명확하게 조건에 맞춰서 로또 번호를 생성해주고 있는지를 확인하는 쪽으로 생각했습니다.

2023-11-13 18:16 UTC, jin-mook commented on src/main/java/lottoauto/domain/aggregate/Aggregator.java
> +    }
넵 출력과 관련된 메서드는 전부 View 쪽으로 이동시켰습니다.

2023-11-13 18:17 UTC, jin-mook commented on src/main/java/lottoauto/domain/aggregate/Aggregator.java
> +    }
View에서 단순히 Object를 변수로 받아서 바로 출력을 하게 하려다 보니 toString을 재정의하게 되었는데 수정하고 전부 View쪽으로 이동시켰습니다.

2023-11-13 18:17 UTC, jin-mook commented on src/main/java/lottoauto/domain/aggregate/LottoShuffler.java
> +                .collect(Collectors.toList());
넵 static 변수로 미리 만들어서 매번 랜덤하게 돌리도록 변경했습니다.

2023-11-13 18:18 UTC, jin-mook commented on src/main/java/lottoauto/domain/aggregate/WinnerBoard.java
> +        winnerBoard.put(6, 0);
피드백 주신대로 WinnerBoard에 등수와 로또 상금을 같이 갖고 있도록 해서 중복으로 작성하지 않도록 변경했습니다. 모두 WinnerBoard 생성 시 초기화 시켰습니다.

2023-11-13 18:18 UTC, jin-mook commented on src/main/java/lottoauto/domain/lotto/Lotto.java
> +    }
넵 요구사항에서 놓친부분이었는데 말씀해주셔서 추가했습니다.

2023-11-13 18:19 UTC, jin-mook commented on src/main/java/lottoauto/domain/lotto/Numbers.java
> +    }
넵 따라서 메서드 명을 result를 누적해서 반환한다는 의미를 추상화 하기 위해 getLottoScore 로 변경했습니다.

2023-11-13 18:21 UTC, jin-mook commented on src/test/java/lottoauto/domain/aggregate/AggregatorTest.java
> +    }
넵 사이즈가 6개가 맞는지, 중복은 있는지, 1 ~ 45 사이의 숫자가 맞는지 검증하도록 변경했습니다.

2023-11-13 18:22 UTC, jin-mook commented on src/main/java/lottoauto/LottoAuto.java
넵 말씀해주신 대로 기능 분리에 대한 부분을 readme 파일에 작성해서 작은 단위로 커밋했습니다. 기존에 이미 만들어진 기능이 있다보니 완전 하나하나 진행하지는 못했는데 이후에는 좀더 작은 단위로 커밋하도록 하겠습니다.

감사합니다.

2023-11-14 10:24 UTC, testrace requested changes
안녕하세요 진묵님
피드백 반영 잘해주셨네요 
몇 가지 더 고민해 보면 좋을 것 같아서 코멘트 남겼습니다
확인해 주시고 다시 리뷰 요청 부탁드려요

2023-11-14 10:24 UTC, testrace commented on src/main/java/lottoauto/view/OutputView.java
> +                .append(earningRate >= 1 ? "이득이" : "손헤")
```suggestion
                .append(earningRate >= 1 ? "이득이" : "손해")
```

2023-11-14 10:24 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lottos.java
> +    }
메서드명을 봤을 때 winnerBoard를 update 해줄 것이라고 기대하기 어려울 것 같아요
winnerBoard를 인자로 받지 말고 메서드 내부에서 생성해서 리턴을 하면 어떨까요?

2023-11-14 17:40 UTC, jin-mook commented on src/main/java/lottoauto/controller/LottoController.java
> +public class LottoController {
기존에 개발할때 항상 컨트롤러 부분에서 입력값에 대한 검증을 진행하다보니 controller에서 단순 검증을 하도록 코드를 작성했었습니다. controller를 통해서 무조건 lotto를 생성할거라고 생각을 하다보니 실제 로또를 직접 생성하는 경우에 대해 대비하지 못한것 같습니다.

관련해서 로또 클래스에서 검증을 하도록 피드백 주신내용으로 수정했습니다!!

2023-11-14 17:41 UTC, jin-mook commented on src/main/java/lottoauto/domain/aggregate/Aggregator.java
> +public class Aggregator {
넵 해당 클래스는 EarningRateCalculator 클래스로 이름을 변경했습니다. 말씀하신대로 aggregate 패키지도 삭제하였습니다.

단, lotto 패키지는 그대로 두었습니다. lotto와 관련된 domain들은 domain/lotto 에 모아두고 나머지 도메인은 domain 패키지에  두었습니다.

2023-11-14 17:44 UTC, jin-mook commented on src/main/java/lottoauto/domain/lotto/Lotto.java
> +    private final Numbers numbers;
만약 로또 번호에 대한 제약이 없더라도 LottoNumber로 포장하는게 좋을까요??

이번 미션에는 로또 범위가 1~45라는 서비스 조건이 있어서 원시값을 포장하는게 훨씬 구조적으로 깔끔해진것 같습니다. 근데 위 질문처럼 만약 이런 조건 없이 아무 숫자 다 가능하더라도 리뷰어님께서는 원시값을 포장하실지 궁금합니다.

아직 제가 어떻게 객체를 설계해야 하는지 정확히 감이 잘 안잡히다보니 이번 프로젝트를 하며 원시값이더라도 로직이 존재한다면 포장하면 좋을것 같다고 느꼈는데 이런 식으로 생각을 해도 괜찮을까요??

2023-11-14 17:44 UTC, jin-mook commented on src/main/java/lottoauto/domain/lotto/Lottos.java
> +    private final int lottoCount;
넵 말씀하신대로 수정했습니다.

2023-11-14 17:44 UTC, jin-mook commented on src/main/java/lottoauto/view/OutputView.java
> +                .append(earningRate >= 1 ? "이득이" : "손헤")
오타가 있었네요 ㅠㅠ 감사합니다!!

2023-11-14 17:46 UTC, jin-mook commented on src/main/java/lottoauto/domain/lotto/Lottos.java
> +    }
넵 피드백 주신대로 WinnerBoard를 따로 받지 않고 생성해서 반환하도록 변경했습니다. 매개변수로 받을때보다 훨씬 의존성이 줄어든것 같습니다
감사합니다.

2023-11-14 17:51 UTC, jin-mook commented
안녕하세요 리뷰 다시 요청드립니다.

이번에 피드백 주신 부분 토대로 수정을 하면서 느꼈는데, 아직 제가 어떻게 객체를 설계 해야하는지에 대한 감이 많이 부족한것 같습니다... 물론 처음이라 설계가 어렵다고 느껴지는게 당연한데, 그럼에도 사실 뭔가 명확한 기준이란게 아직 스스로 잡히지 않았고, 기준이란게 있는지도 잘 모르겠어서 더욱 답답하게 느껴지는것 같습니다.

혹시 리뷰어님께서는 설계를 하실때 어떤 기준을 갖고 하시는지 방법이 있으시다면 조금 조언을 주시면 다음 미션할때 좀 더 다양하게 고민해볼 수 있을것 같습니다 ㅠㅠ

추가로 혹시 객체 설계와 관련된 서적이나 참고 자료같은게 있을까요??

2023-11-14 17:55 UTC, jin-mook commented
안녕하세요 리뷰 다시 요청드립니다.

이번에 피드백 주신 부분 토대로 수정을 하면서 느꼈는데, 아직 제가 어떻게 객체를 설계 해야하는지에 대한 감이 많이 부족한것 같습니다... 물론 처음이라 설계가 어렵다고 느껴지는게 당연한데, 그럼에도 사실 뭔가 명확한 기준이란게 아직 스스로 잡히지 않았고, 기준이란게 있는지도 잘 모르겠어서 더욱 답답하게 느껴지는것 같습니다.

혹시 리뷰어님께서는 설계를 하실때 어떤 기준을 갖고 하시는지 방법이 있으시다면 조금 조언을 주시면 다음 미션할때 좀 더 다양하게 고민해볼 수 있을것 같습니다 ㅠㅠ

추가로 혹시 객체 설계와 관련된 서적이나 참고 자료같은게 있을까요??

2023-11-15 09:28 UTC, testrace commented on src/main/java/lottoauto/domain/aggregate/Aggregator.java
> +                    }
LottoShuffler 내부에서 `Collections#shuffle` 를 사용하고 있어서 명확하게 조건에 맞는지 검증하기 힘들지 않을까요?
멱등성이 보장되지 않는 기능을 검증하는건 무리가 있어 보여요

2023-11-15 09:42 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lotto.java
> +    private final Numbers numbers;
제약이 없더라도 원시값을 포장하면 이름을 부여할 수도 있고 불변객체로 활용할 수 있는데요
VO(ValueObject)에 대해서 찾아보시면 도움이 될 것 같습니다

저도 가능하면 원시값은 포장하려고 노력하고 있지만 모든 이론을 실무에 적용하기는 쉽지 않은 것 같아요 😅 

진묵님 의견대로 이번 과정에서 모든 원시값을 의식적으로 포장해 보시면 객체 설계에 도움이 될 것 같아요

2023-11-15 10:55 UTC, testrace commented
> 안녕하세요 리뷰 다시 요청드립니다.
> 
> 이번에 피드백 주신 부분 토대로 수정을 하면서 느꼈는데, 아직 제가 어떻게 객체를 설계 해야하는지에 대한 감이 많이 부족한것 같습니다... 물론 처음이라 설계가 어렵다고 느껴지는게 당연한데, 그럼에도 사실 뭔가 명확한 기준이란게 아직 스스로 잡히지 않았고, 기준이란게 있는지도 잘 모르겠어서 더욱 답답하게 느껴지는것 같습니다.

이번 피드백을 통해서 굉장히 깔끔한 구조로 개선되었다고 생각합니다!
저였다면 한번의 피드백만으로 이정도로 개선할 수 있을지 잘 모르겠네요 😅 
미션 페이지를 보시면 학습 목표에 `경험할 객체지향 생활 체조 원칙`이 있는데요
다른 사람이 만든 기준을 따라가 보시면 자연스럽게 진묵님만의 기준을 만들 수 있을거라 생각해요

> 혹시 리뷰어님께서는 설계를 하실때 어떤 기준을 갖고 하시는지 방법이 있으시다면 조금 조언을 주시면 다음 미션할때 좀 더 다양하게 고민해볼 수 있을것 같습니다 ㅠㅠ

모든 미션마다 존재하는 기능목록 요구사항이 도움이 되실 것 같아요
1단계에 보시면 `기능 분리 힌트`를 참고해 보시면 좋을 것 같아요
예를 들어 로또 미션의 기능을 분리할 때 작은 단위로 나누어 보는 연습을 해보시는걸 추천드립니다
```markdown
* 로또
  - [x] 로또 번호 6개
    - [ ] 범위 1 ~ 45
  - [x] 중복 숫자 없음
  - [x] 당첨 번호와 일치하는 개수 구하기
* 당첨 등수
  - [ ] ...
* 출력
  - [x] 로또 번호 오름차순 정렬
```

> 추가로 혹시 객체 설계와 관련된 서적이나 참고 자료같은게 있을까요??

`객체지향의 사실과 오해`, `오브젝트` 를 추천드립니다

2023-11-15 10:55 UTC, testrace approved these changes
안녕하세요 진묵님
적지 않은 피드백이었는데 잘 반영해 주셨네요 👍 
몇 가지 코멘트 남겼는데 다음 단계에서 반영해 주시면 될 것 같아요!
다음 단계도 화이팅입니다 🔥

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/CustomShuffle.java
> +    List<Integer> makeShuffle();
LottoNumber 객체를 활용하면 어떨까요?
```suggestion
    List<LottoNumber> makeShuffle();
```

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lotto.java
> +    public Lotto(List<Integer> lottoNumbers) {
Set 타입으로 로또를 생성할 수 있는 생성자를 추가하면 어떨까요?
```suggestion
    public Lotto(Set<Integer> lottoNumbers) {
```

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lotto.java
> +        if (lottoNumbers.size() != 6) {
매직 넘버 `6`을 상수로 치환해서 이름을 부여해도 좋을 것 같아요

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lotto.java
> +    }
출력을 위해 재정의 된 것 같은데요
toString 재정의는 디버깅용으로 사용하시는걸 추천드립니다
OutputView에서 오름차순 정렬한 후 출력하면 어떨까요?

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/LottoNumber.java
> +    private final int number;
불변 객체 👍

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/LottoNumber.java
> +    }
private 생성자와 정적 팩토리 메서드 👍 
매직넘버는 상수로 치환하면 좋을 것 같아요

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/LottoShuffler.java
> +            .collect(Collectors.toList());
여기서도 Integer 대신 LottoNumber를 활용하면 좋을 것 같아요

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lottos.java
> +    public static final int EACH_LOTTO_PRICE = 1000;
```suggestion
    public static final int EACH_LOTTO_PRICE = 1000;
    
    private final List<Lotto> lottoList;
```

2023-11-15 10:55 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lottos.java
> +    public WinnerBoard checkWinnerLotto(String winNumbersString) {
당첨 번호를 메서드 내부에서 Lotto 타입으로 생성하고 있는데요
인자의 타입을 Lotto로 변경하면 어떨까요?
```suggestion
    public WinnerBoard checkWinnerLotto(Lotto winNumbers) {
```

2023-11-15 10:55 UTC, testrace commented on src/test/java/lottoauto/domain/lotto/LottoShufflerTest.java
> +    }
Integer 타입 대신 LottoNumber 를 활용한다면 숫자의 범위는 LottoNumber가 책임을 수행하고 있으니 
LottoShuffler는 숫자의 범위에 대해 검증하지 않아도 될 것 같아요

2023-11-15 10:55 UTC, merged

2023-11-15 12:55 UTC, jin-mook commented on src/main/java/lottoauto/domain/lotto/CustomShuffle.java
> +    List<Integer> makeShuffle();
사실 이 부분을 수정하면서 Integer 로 할지 LottoNumber 로 할지 정말 많이 고민했습니다. 

처음 생각은 CustomShuffle 인터페이스는 순수하게 숫자만 shuffle 해주는 역할을 하게 하기 위해 Integer로 리턴하고 받은 숫자를 Lotto 클래스에서 Lotto 클래스를 생성할 때 번호가 6개이고 중복이 없는지를 확인하려고 했었는데 아래 피드백 내용중에 

```
src/main/java/lottoauto/domain/lotto/LottoShuffler.java

private final List<Integer> defaultLottoNumbers =  IntStream.range(1, 46)
            .boxed()
            .collect(Collectors.toList());
```

이 부분을 먼저 LottoNumber로 변환해서 내부 필드로 저장하고 있으면 LottoShuffler 클래스에 대한 단위 테스트도 훨씬 작성하기 편해지고 Lotto 클래스의 생성자에서 중복이나 6개의 숫자가 맞는지에 대한 코드도 줄어들 수 있을것 같아서 말씀해주신 것처럼 바꾸는게 훨씬 좋은것 같습니다. 

다음 미션에는 해당 내용 반영해서 진행하도록 하겠습니다.
감사합니다

2023-11-15 13:02 UTC, jin-mook commented on src/main/java/lottoauto/domain/lotto/Lottos.java
> +    public WinnerBoard checkWinnerLotto(String winNumbersString) {
피드백 감사합니다. 개인적으로 질문이 있습니다.

매개변수를 Lotto로 변경하게 되면 LottoAuto 클래스에서 inputView를 통해 받은 사용자 입력을 Lotto 클래스로 한번 변환해야 하는 과정이 있는데 (현재는 checkWinnerLotto 내부에서 진행하고 있는 부분입니다.)

Lotto 클래스로 변환하는 클래스를 추가로 만드는게 좋을까요?? 아니면 inputView에서 조작을 하는게 좋을까요?? 혹은 LottoAuto 클래스에서 변환해서 넘기는게 좋을까요??

저는 view에서는 다른 로직 없이 입력받은 값을 그대로 전달하는게 좋다고 생각해서 그대로 넘긴 후에 checkWinnerLotto 내부에서 Lotto 클래스로 만들어줬는데 리뷰어님은 어느 부분에 입력받은 문자를 Lotto로 변환하는 작업을 진행하도록 수정하실지 궁금합니다!!

감사합니다.

2023-11-15 13:06 UTC, jin-mook commented
질문 내용이 구체적이지 못했다고 생각했는데 편하게 답변주셔서 감사합니다

"경험할 객체지향 생활 체조 원칙" 을 못보고 읽어보지 못했는데 참고해서 진행하도록 하겠습니다 감사합니다!!

좀 더 요구사항을 세부적으로 정말 꼼꼼히 작성해보겠습니다!!

추천해주신 책은 바로 주문했습니다~~

감사합니다!!

2023-11-16 01:23 UTC, testrace commented on src/main/java/lottoauto/domain/lotto/Lottos.java
> +    public WinnerBoard checkWinnerLotto(String winNumbersString) {
특정 방식이 좋다는 정답은 없는 것 같아요 😃 
저라면 컨트롤러 역할을 하는 LottoAuto 에서 변환할 것 같은데요
컨트롤러가 직접 변환을 할지 변환하는 클래스(DTO)를 활용할지는 옵션인 것 같아요

2023-11-16 04:08 UTC, jin-mook commented on src/main/java/lottoauto/domain/lotto/Lottos.java
> +    public WinnerBoard checkWinnerLotto(String winNumbersString) {
피드백 감사합니다!!
클래스를 활용할지 직접 변환할지 좀더 고민해보고 다음 미션에 같이 적용하겠습니다!!