1단계 - 문자열 계산기
next-step/java-lotto pull request #3353
Opened 2023-11-13 11:56 UTC by pawoo0211

안녕하세요~ 로또 미션 참여하게된 박상권입니다. 로또 미션 잘 부탁드리겠습니다!

2023-11-13 13:19 UTC, csh0034 requested changes
안녕하세요. 상권님!
로또 미션을 함께하게 된 최승훈입니다. 

1단계 문자열 계산기 구현 관련하여 
몇가지 피드백 남겨두었는데 확인해주시고
다시 리뷰 요청 부탁드립니다!

혹시 코멘트가 이해 안가시거나 추가로 궁금하신 사항 있으시면
편하게 DM 주세요 😄

2023-11-13 13:19 UTC, csh0034 commented on src/main/java/Operation.java
> +public enum Operation {
Enum 타입 추상메서드 구현 👍

하단 코멘트는 꼭 적용은 안하셔도 됩니다!

추상메서드를 보니 IntBinaryOperator 와 동일한데요!
IntBinaryOperator 를 두번째 필드로 가지는 방법도 있을것 같습니다.

2023-11-13 13:19 UTC, csh0034 commented on src/main/java/Operation.java
> +    public static Operation getOperationByElement(String element) {
이번단계 요구사항에는 `else를 사용하지 마라.` 라는 부분이 있습니다.

`Operation.values()` 를 순회하며 operation 값을 비교한다면 해당 else if 를
제거할수 있을것 같아요!

2023-11-13 13:19 UTC, csh0034 commented on src/test/java/CalculatorTest.java
> +public class CalculatorTest {
상세하게 단위테스트 잘 작성해주셨네요 👍

추가로 junit5 에서는 테스트 클래스와 메서드에 public 을 제거하는걸 추천하므로 
적용해보면 좋을것 같아요.

- https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods

2023-11-13 13:19 UTC, csh0034 commented on src/main/java/Numbers.java
> +        return element.matches("[+-]?\\d+");
`Pattern.matches` 의경우 `Pattern.compile` 을 매번 호출하여 객체를 생성합니다.
`Pattern.compile` 을 상수로 선언하여 사용해보면 좋을것 같아요.

2023-11-13 13:19 UTC, csh0034 commented on src/main/java/Calculator.java
> +    int result = 0;
calculate 메서드에서 sum() 을 바로 반환한다면 result 는 제거가능할것 같습니다!

2023-11-13 13:19 UTC, csh0034 commented on src/main/java/Calculator.java
> +    private void addOperationAndNumber(String element) {
이부분에서도 else 를 제거해보면 좋을것 같아요!

2023-11-13 13:19 UTC, csh0034 commented on src/main/java/Operations.java
> +    private static final Pattern OPERATION_PATTERN = Pattern.compile(OPERATION_REGULAR_EXPRESSION);
상수선언 👍

String 상수는 Pattern 이외엔 참조하지 않으므로 하나로 선언해두어도 될 것 같습니다 🙂

2023-11-13 13:22 UTC, csh0034 commented
## 1. gitkeep 삭제

.gitkeep 파일의 경우 git 은 디렉토리에 파일이 없을 경우 업로드 되지않아 
디렉토리 구조를 유지시키기 위한 파일입니다. 파일을 추가해주셨으니 삭제해주셔도 됩니다.

## 2. 패키지 구조

step1 이후에 step2,3,4 의 경우 로또에서 요구사항이 점점 추가되어 기존 코드를 수정하므로 
/src/main/java/calculator, /src/main/java/lotto 등과 같이 기능별로
패키지 분리를 하시는걸 추천드립니다.

2023-11-13 13:55 UTC, pawoo0211 commented on src/main/java/Operation.java
> +    public static Operation getOperationByElement(String element) {
else문이 else if도 포함이였군요~

2023-11-14 03:00 UTC, csh0034 approved these changes
리뷰 잘 반영해주셨네요 💯 
몇가지 코멘트만 드리고 머지하겠습니다.
다음단계에서 봬요! 😄

2023-11-14 03:00 UTC, merged

2023-11-14 12:48 UTC, pawoo0211 commented on src/main/java/calculator/Operations.java
> +        if (operationMatcher.find()) {
오 이렇게 바로 리턴할 수 있군요 감사합니다~