로또 🚀 1단계 - 문자열 계산기
next-step/java-lotto pull request #3355
Opened 2023-11-13 13:01 UTC by hoho282

로또 - TDD 리뷰 잘 부탁드립니다.

2023-11-13 15:12 UTC, ohtaeg requested changes
안녕하세요 혜진님 👋 
이번 로또 미션을 같이 함께할 리뷰어 오태경이라고 합니다 :)
잘 부탁 드립니다 😄 

1단계 미션을 잘 구현해주셨어요 👍 
다음 미션을 진행하기전에 같이 리팩토링하면 좋은 경험이 될 것 같아 Request changes 하였습니다!
코멘트를 드렸는데 확인해주신 후 반영하여 재요청주세요 :)
화이팅입니다 🔥

2023-11-14 03:13 UTC, hoho282 commented on src/main/java/domain/StringCalculator.java
> +        calculator = new BasicOperator();
재사용해야지 했는데... 감기 걸려서 좀 오락가락 한듯합니다. ;;;

2023-11-14 14:38 UTC, hoho282 commented
리뷰어님이 아래의 2개 방법을 제안 주셨는데요. 공부하는 차원에서 2개다 시도 해보았습니다. 소스 보시기에 좀 불편하실 수도 있어요. 양해 부탁드려요! 
1. Map을 필드로 가져 key에 연산자 문자를 담고 value를 해당 연산자의 객체나 람다식을 담아 get하는 방식
2. Enum을 활용하여 값과 그 값에 따른 메서드를 매핑

2023-11-14 15:33 UTC, ohtaeg approved these changes
피드백을 잘 반영해주셨어요 👍 👍 
기대 이상으로 피드백을 반영해주셨네요 :)
소소한 코멘트들을 드렸는데 확인해주시면 감사하겠습니다!
이제 본격적으로 로또 미션을 진행해볼까요? 화이팅입니다 🔥

2023-11-14 15:33 UTC, ohtaeg commented on src/main/java/domain/StringCalculator.java
> +        Map<String, Calculator> operatorMap = new HashMap<>();
제가 의도하신대로 잘 구현해주셨네요 👍 👍 
operatorMap은 한번 생성되고 나면 변경될 일이 많이 없어보이기에 생성자에서 초기화해주어 재사용하는 방향도 괜찮아 보이네요 😄

2023-11-14 15:33 UTC, ohtaeg commented on src/main/java/domain/Calculator.java
> +    int calculator(int num1, int num2);
👍 👍

2023-11-14 15:33 UTC, ohtaeg commented on src/main/java/domain/BasicOperator.java
> +public enum BasicOperator {
enum으로도 잘해주셨네요 👍

2023-11-14 15:33 UTC, ohtaeg commented on src/main/java/domain/BasicOperator.java
> +                .collect(toMap(BasicOperator::getOperator, Function.identity()));
1번 방법과는 다르게 해당 방법은 Map으로 안바꾸고 다른 람다식을 통해 변환해볼 수 있을 것 같아요 :)
filter 와 find 함수를 이용하여 리팩토링해보시면 좋을 것 같아요 😄

2023-11-14 15:33 UTC, ohtaeg commented on src/main/java/domain/StringCalculator.java
> +        Set<String> validOperators = new HashSet<>(Arrays.asList("+", "-", "*", "/"));
만약 해당 피드백이 반영이 된다면 Map에 해당 key들이 없는지 물어보도록 변경하면 어딸까요 :) ?

2023-11-14 15:33 UTC, ohtaeg commented on src/main/java/domain/StringCalculator.java
> +    private List<String> input;
해당 입력값은 파라미터에 좀 더 가깝다고 생각이 드네요 😄

2023-11-14 15:39 UTC, merged