🚀 1단계 - 문자열 계산기
next-step/java-lotto pull request #3363
Opened 2023-11-13 18:21 UTC by hoon25

안녕하세요 리뷰어님

https://github.com/next-step/java-lotto/pull/3327#discussion_r1390401816 요청에 따라서
Step1 구현을 먼저 진행하였습니다.

리뷰 감사합니다🙇‍♂️🙇‍♂️🙇‍♂️

2023-11-15 15:41 UTC, kyucumber requested changes
안녕하세요 리뷰가 늦어 죄송합니다.
몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-11-16 14:11 UTC, hoon25 commented on src/main/java/calculator/exception/DivisionResultFloatException.java
> +public class DivisionResultFloatException extends RuntimeException {
두번째 예외는 사례가 어떤 상황일까요? 떠오르지 않아서 추가 질문 드립니닷

2023-11-16 14:11 UTC, hoon25 commented on src/main/java/calculator/exception/DivisionResultFloatException.java
> +public class DivisionResultFloatException extends RuntimeException {
해당 내용은 적절한 값이 있이면 통과하는 사례이기 때문에 `IllegalArgumentException`으로 구현했습니다!

2023-11-16 14:49 UTC, hoon25 commented on src/main/java/calculator/domain/operator/OperatorFactory.java
> +        switch (operator) {
Bifunction을 사용해서 Class를 없애고 더 단순하게 만들었습니다. 
그 과정에서 궁금한 점이 생겨서 질문드립니다.

1. OperatorFactory가 적절한 클래스명일까?
2. 모든 연산들이 하나의 클래스 안에있어서 SRP를 위반할 것 같습니다.

2023-11-16 14:56 UTC, hoon25 commented on src/test/java/calculator/domain/CalculatorTest.java
> +        int result = calculator.calculate();
반영완료했습니다!

2023-11-16 14:57 UTC, hoon25 commented
반영 완료했습니다. 리팩토링 과정중에 궁금한 부분은 코멘트로 달아두었습니다! 🙇‍♂️🙇‍♂️

2023-11-17 07:25 UTC, kyucumber commented on src/main/java/calculator/exception/DivisionResultFloatException.java
> +public class DivisionResultFloatException extends RuntimeException {
> 동일한 예외가 여러번 발생하는데 특정 예외를 잡아 캐치해야 하는 경우 사례는 어떤 상황일까요? 떠오르지 않아서 추가 질문 드립니닷

예를 들면 A라는 로직 내부에서 표준 예외를 활용해 처리하다보니

1. 주문 처리에 대해 IllegalArgumentException 발생
2. 메시지 발생에 대해 IllegalArgumentException 발생

위와 같이 동일한 표준 예외를 두번 던지는데, 상위에서 두 예외 중 하나를 catch 등으로 잡아서 별도로 로그 등의 처리해주어야 하는 경우가 있다면 동일한 예외를 던지고 있기 때문에 구분해 처리하기 어려울 수 있습니다. 이런 경우라면 별도의 주문 실패 등의 커스텀 예외를 만들고 그 예외를 잡아서 처리하는게 더 나은 선택이 될 수 있을 것 같네요.

2023-11-17 07:28 UTC, kyucumber commented on src/main/java/calculator/domain/operator/OperatorFactory.java
> +        switch (operator) {
일단 구현한 방식이 제가 의도한 방식과는 조금 다르네요. 저는 Operator Enum이 내부에 BiFunction 인터페이스를 가지고 그에 대한 생성을 lambda를 통해 간결하게 생성하길 의도했어요. 예를 들면 아래와 같은 형태가 되겠네요.

```
PLUS("+", a, b -> a + b)
```

2023-11-17 07:29 UTC, kyucumber commented on src/main/java/calculator/domain/operator/OperatorFactory.java
> +        switch (operator) {
> OperatorFactory가 적절한 클래스명일까?

일단 Operator 인터페이스 구현체를 생성해 반환하는 점에서 Factory라는 이름이 이상하다고 생각되진 않네요.

2023-11-17 07:30 UTC, kyucumber commented on src/main/java/calculator/domain/operator/OperatorFactory.java
> +        switch (operator) {
그리고 디자인 패턴 별 이름을 나누고 외우듯 하는 걸 선호하지는 않지만, 학습의 단계에 계시지 코멘트를 추가로 남겨드리면 인터페이스의 구현체를 교체하는 전략 패턴의 형태로 보이기도 하고. 람다를 활용해 익명 클래스를 상요하고 있어 템플릿 콜백 패턴을 사용하는 것으로 볼 수도 있겠네요.

2023-11-17 07:32 UTC, kyucumber commented on src/main/java/calculator/domain/operator/OperatorFactory.java
> +        switch (operator) {
> 모든 연산들이 하나의 클래스 안에있어서 SRP를 위반할 것 같습니다.

SPR 같은 부분들은 모두 트레이드오프를 가지고 있습니다. 각각의 구현체를 직접 클래스로 생성하는 케이스라면 분리하는게 맞아보입니다. 다만 BiFunction 및 람다를 사용한 시점에서는 SPR을 위반하더라도 응집도를 높이는 것이 좋다는 생각은 드네요.

2023-11-17 07:33 UTC, kyucumber approved these changes
남겨두신 질문에 코멘트 남겨두었으니 참고 부탁드려요.

다음 단계 진행을 위해 머지하겠습니다.

2023-11-17 07:33 UTC, merged