3단계 - 로또(2등)
next-step/java-lotto pull request #3365
Opened 2023-11-14 10:10 UTC by beyondorder

2023-11-14 13:17 UTC, nooose requested changes
3단계 빠르게 요청주셨네요
피드백 남겼으니 읽어보시고 재요청 부탁드립니다.

2023-11-14 13:17 UTC, nooose commented on src/main/java/step3/domain/ResultProcessor.java
> +        }
Lottos에 로또 리스트를 담고 Lottos에서 리스트를 꺼내와서 로직을 전개하네요
이런 부분들도 Lottos 일급컬렉션에서 해결할 수 있지 않을까요?

2023-11-14 13:17 UTC, nooose commented on src/main/java/step3/view/InputView.java
> +                .collect(Collectors.toList());
캐시에 직접 접근하고 있네요
LottoNumber 정적 팩터리 메서드에서 캐싱된 값을 바로 받도록 변경할 수 있어보여요

2023-11-14 13:17 UTC, nooose commented on src/main/java/step3/view/InputView.java
> +                .collect(Collectors.toList());
<img width="556" alt="image" src="https://github.com/next-step/java-lotto/assets/36617783/d1f8be78-083f-4637-9304-8086f5f27016">

Integer 정적 팩터리 메서드 참고해 보시면 도움이 될거에요!

2023-11-14 13:17 UTC, nooose commented on src/main/java/step3/view/OutputView.java
> +        DecimalFormat df = new DecimalFormat("#.##");
df는 너무 줄인것 같아요 😅
`decimalFormat`을 사용해도 되지 않을까요?
그렇게 긴 변수명은 아닌 것 같아요

2023-11-14 13:17 UTC, nooose commented on src/main/java/step3/view/OutputView.java
> +        ;
```suggestion
        }
```

2023-11-14 13:17 UTC, nooose commented on src/test/java/step2/domain/WinningLottoTest.java
> +        Lotto winningNumbersLotto = lottoFixture(1, 2, 3, 4, 5, 6);
👍

2023-11-14 13:17 UTC, nooose commented on src/main/java/step3/domain/LottoNumber.java
> +        if (number < 1 || number > 45) {
1, 45도 상수로 치환될 수 있어보입니다.

2023-11-14 13:17 UTC, nooose commented on src/main/java/step3/domain/WinningNumbers.java
> +
WinningNumbers가
멤버변수를 `Lotto lotto`와 `LottoNumber bonusNumber`를 받았더라면 좋았을 것 같네요
LottoNumber가 isBonus를 매번 들고다닐 필요도 없으니까요 😄

2023-11-15 04:21 UTC, beyondorder commented on src/main/java/step3/domain/WinningNumbers.java
> +
of 정적 팩토리 메소드에서 lotto와 bonusNumber를 받으면서 생성하고있습니다.
다른 방식을 말씀주신거라면, 가이드 부탁드리겠습니다 👍🏻

2023-11-15 04:21 UTC, beyondorder commented on src/main/java/step3/domain/LottoNumber.java
> +        if (number < 1 || number > 45) {
반영하겠습니다 :)

2023-11-15 04:22 UTC, beyondorder commented on src/main/java/step3/view/OutputView.java
> +        ;
반영하겠습니다 :)

2023-11-15 04:22 UTC, beyondorder commented on src/main/java/step3/view/OutputView.java
> +        DecimalFormat df = new DecimalFormat("#.##");
반영하겠습니다 :)

2023-11-15 04:22 UTC, beyondorder commented on src/main/java/step3/domain/ResultProcessor.java
> +        }
위로직처리를 lottos로 이동하겠습니다.

2023-11-15 04:22 UTC, beyondorder commented on src/main/java/step3/domain/ResultProcessor.java
> +        return lottos.lottos().size() * PRICE_PER_LOTTO;
반영하겠습니다 :)

2023-11-15 04:24 UTC, beyondorder commented on src/main/java/step3/domain/Lottos.java
> +    }
아래 조언주신 
lotto별 winningnumber와 매칭하는 로직을 lottos로 옮기게되면서 lottos의 존재를 유지하기로 하였습니다.!

2023-11-15 04:24 UTC, beyondorder commented on src/main/java/step3/domain/Lotto.java
> +                .collect(Collectors.joining(", ", "[", "]"));
반영하겠습니다 :)

2023-11-15 04:27 UTC, beyondorder commented on src/main/java/step3/Application.java
> +public class Application {
요구사항에 퍼센티지로 표시하지않고
(총당첨금액 / 총구매금액) 값으로 표기하는 것으로 이해해서 그렇게 출력을 하고있는데,
혹시 제가 누락한 부분이 있을까요? ㅠ

위에 첨부주신케이스에서는 구매금액이 얼마일까요?

2023-11-15 11:23 UTC, nooose commented on src/main/java/step3/Application.java
> +public class Application {
수익률 문제는 없어보이고
3개, 0개 일치 부분이 잘 못 된것같습니다

2023-11-15 11:33 UTC, nooose commented on src/main/java/step3/domain/WinningNumbers.java
> +
제가 너무 애매하게 설명드렸네요
of 메서드로 두개를 받지만 
WinningNumbers로 다시 풀어져있네요
단순하게 로또와 보너스번호만 멤버 변수로 갖도록 해도 될 것같아요

이렇게 되면 로또넘버가 보너스 번호를 위해 
isBonus 필드를 가지지 않아도 될 것 같습니다.

2023-11-15 12:36 UTC, beyondorder commented on src/main/java/step3/Application.java
> +public class Application {
헛... !!! 0개 일치가 출력되는것을 계속 보면서도 인지 못했네요. 0개 일치는 결과에 포함하지 않도록 반영하겠습니다.

2023-11-15 13:08 UTC, beyondorder commented on src/main/java/step3/domain/WinningNumbers.java
> +
그러네요. 반영해보겠습니다.
isBonus가 있음으로써 캐시를 사용할때 비효율적인것같은 고민이 있었는데
말씀주신 부분을 반영하면 그 고민도 해소가 될 것 같습니다.

2023-11-15 13:37 UTC, nooose requested changes
피드백 반영 잘 해주셨습니다. 👍
요구사항과 다른 부분이 있어서 이 부분만 해결하고 넘어가기로 해요
재요청 부탁드립니다!

2023-11-15 13:37 UTC, nooose commented on src/main/java/step2/Application.java
>  }
## 요구사항
<img width="356" alt="image" src="https://github.com/next-step/java-lotto/assets/36617783/3e6a431c-db8a-4f88-b36d-b339cc086eae">

## 실행 결과
<img width="331" alt="image" src="https://github.com/next-step/java-lotto/assets/36617783/a803b627-4e65-4e08-bd15-b9ffdf4f89e0">

요구사항에 맞게
모든 결과에서 몇개가 일치하는 지 출력이 되어야합니다. 🥲

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/domain/WinningNumbers.java
> +        }
```java
lotto.contains(bonusNumber);
```
이 부분은 위 조건으로 간단하게 유효성 검증을 할 수 있을 것 같아요
Lotto 자체적으로 중복되지 않은 6개의 로또 번호가 들어가는 것을 보장하니까요

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/view/InputView.java
> +                .map(LottoNumber::of)
👍

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/view/OutputView.java
> +            if(rank == LottoRank.SECOND){
```suggestion
            if (rank.isSecond()){
```
메시지를 직접 전달하는 것이 좋을 것 같습니다.

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/view/OutputView.java
> +            if(rank == LottoRank.SECOND){
추가로 for 내부 depth도 줄여보면 좋겠네요

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/domain/LottoRank.java
> +        }
요기 부분도 2단계 depth를 줄여보면 좋겠네요

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/domain/LottoRank.java
> +    MISS(0, 0);
👍

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/view/OutputView.java
> +                    .sorted()
이 부분에서도 저도 고민을 했는데요
로또가 정렬된 로또 번호를 가져야할지 아님 view에서 출력할 때 sort해야할지 고민을 했습니다.

보통 서비스들이 정렬된 데이터를 제공하지,
정렬되지 않은 데이터를 반환한 다음에 프론트에서 정렬을 하도록 내보내지는 않는 것 같습니다.
로또 생성 시점에 정렬되도록 변경해 보는 게 어떨까요?

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/domain/Lottos.java
> +        }
이 부분도 개선할 수 있어보여요!

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/domain/LottoMachine.java
> +        }
로또 머신 박에서도 `lottos.addLotto`를 사용하여 로또를 추가할 수 있을 것 같습니다.
로또 일급컬렉션 생성자에 `List<Lotto>`를 전달하고 생성 시 초기화를 하면 좋을 것 같아요

2023-11-15 13:37 UTC, nooose commented on src/main/java/step3/domain/WinningNumbers.java
> +    private final Lotto lotto;
```suggestion
    private static final int WINNING_NUMBER_SIZE = 7;

    private final Lotto lotto;
```

2023-11-15 13:52 UTC, beyondorder commented on src/main/java/step2/Application.java
>  }
아하.. 이해했습니다..!!

2023-11-15 13:52 UTC, beyondorder commented on src/main/java/step3/domain/WinningNumbers.java
> +        }
반영하겠습니다.

2023-11-15 14:12 UTC, beyondorder commented on src/main/java/step3/view/OutputView.java
> +            if(rank == LottoRank.SECOND){
반영하겠습니다

2023-11-15 14:16 UTC, beyondorder commented on src/main/java/step3/domain/LottoRank.java
> +        }
넵 줄이겠습니다.

2023-11-15 14:22 UTC, beyondorder commented on src/main/java/step3/domain/LottoMachine.java
> +        }
반영하겠습니다.

2023-11-15 17:36 UTC, nooose approved these changes
기능 오류로 인해 머지가 안 되었었는데
그 사이 피드백 주고받으면서 많이 개선된 것 같아요
다음 단계 진행해 주세요~

2023-11-15 17:36 UTC, nooose commented on src/main/java/step3/domain/Lotto.java
> +    }
로또 넘버가 캐싱되어있으니 그냥 참조 비교를 바로해도 될 것 같아요

캐싱이 보장 되지 않는다면
로또넘버가 가진 번호를 꺼내서 비교하는 방식 보다는
LottoNumber에 equals를 재정의하고 해당 메서드를 사용하여 비교하는 것이 좋을 것 같아요
equals를 재정의하면서 hashCode도 같이 재정의하는 것이 좋습니다.

2023-11-15 17:36 UTC, nooose commented on src/main/java/step3/domain/LottoMachine.java
> +                .map(LottoNumberCache::getLottoNumber)
로또 넘버 자체를 가지는 박스를 셔플하는 방법도 있겠네요
여기서도 LottoNumber의 정적 팩토리 메서드를 활용해도 되지 않을까요?

2023-11-15 17:36 UTC, nooose commented on src/main/java/step3/cache/LottoNumberCache.java
> +
<img width="346" alt="image" src="https://github.com/next-step/java-lotto/assets/36617783/d2ba0ac2-e9f5-46b7-8c83-db39bda166ac">

Integer가 내부에 캐시를 가지고 있는 것 처럼
LottoNumber 자체적으로 캐시를 갖고 있어도 될 것 같아요

꼭 반영할 사항은 아니고 참고만 해주세요~

2023-11-15 17:36 UTC, nooose commented on src/main/java/step3/cache/LottoNumberCache.java
> +        return LottoNumberCache.get(number);
없으면 만들어서 준다는 느낌으로 `getOrDefault` 메서드를 사용하면 null을 반환하지 않아 편리할 것 같아요

2023-11-15 17:36 UTC, nooose commented on src/main/java/step3/domain/LottoMachine.java
> +        return new Lottos(lottoList);
이런 부분에서 복수형 변수명이 참 난감하죠 🥲

2023-11-15 17:36 UTC, nooose commented on src/main/java/step3/domain/Lottos.java
> +                .forEach(lottoRank -> result.put(lottoRank, result.getOrDefault(lottoRank, 0) + 1));
map에 있는 merge라는 메서드도 이때 사용할 수 있을 것 같아요
참고해 주세요

2023-11-15 17:36 UTC, nooose commented on src/main/java/step3/domain/Lottos.java
> +                .forEach(lottoRank -> result.put(lottoRank, result.getOrDefault(lottoRank, 0) + 1));
매칭 결과를 `List<Rank>`로 반환하고 맵을 구성하는 로직은 
ResultProcessor가 해도 될 것 같은데 어떻게 생각하시나요?

2023-11-15 17:36 UTC, nooose commented on src/main/java/step3/domain/WinningNumbers.java
> +        }
Lotto의 번호는 6개 보장이 되고 LottoNumber도 번호 하나 보장이 되니까 7개가 확정된 것 같네요
여기서는 null 체크와 중복만 체크 해줘도 될 것 같네요

2023-11-15 17:36 UTC, merged

2023-11-16 01:03 UTC, beyondorder commented on src/main/java/step3/domain/LottoMachine.java
> +                .map(LottoNumberCache::getLottoNumber)
말씀주신대로 넘버박스를 LottoNumber가 담기게 하고,
이 메소드에서는 섞고, 앞6자리만 가져오도록 반영하겠습니다.

2023-11-16 01:04 UTC, beyondorder commented on src/main/java/step3/cache/LottoNumberCache.java
> +
반영해보겠습니다. :)

2023-11-16 01:08 UTC, beyondorder commented on src/main/java/step3/cache/LottoNumberCache.java
> +        return LottoNumberCache.get(number);
반영하겠습니다. :)

2023-11-16 01:20 UTC, beyondorder commented on src/main/java/step3/domain/LottoMachine.java
> +        return new Lottos(lottoList);
lottoList를... lottos로.. 변경했습니다.

2023-11-16 13:51 UTC, nooose commented on src/main/java/step3/domain/WinningNumbers.java
> +        }
값이 정상적일 때는 필요없지만 null을 직접 넣을 수 있으니까요 😄

2023-11-16 13:51 UTC, nooose commented on src/main/java/step3/domain/LottoMachine.java
> +        return new Lottos(lottoList);
바꿔달라는 피드백은 아니었는데 바꾸셨네요 😅