로또 Step2
next-step/java-lotto pull request #3367
Opened 2023-11-14 11:18 UTC by henry174

1이상 45이하의 중복되지 않은 숫자 조합 6개를 편하게 관리할 방법을 찾다가 아예 클래스로 독립시켜 봤습니다. 클래스 이름이 조금 조악하긴 한데 적절한 이름을 못 짓겠군요.

2023-11-14 12:48 UTC, dhmin5693 requested changes
승준님 안녕하세요.

고민해볼만한 부분을 잡아서 몇 가지 의견을 드렸어요.
확인 후 다시 요청주세요.

어려운 점 있다면 언제든 부담없이 DM 보내주신다면 최대한 빠르게 답변드리도록 하겠습니다.

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/view/Question.java
> +    }
생성 제한 👍

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/view/Question.java
> +        Scanner scanner = new Scanner(System.in);
`Scanner` 인스턴스는 한 번만 선언해도 됩니다.

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/lotto/type/SixNumberComposition.java
> +    private final List<Integer> numberList;
`List`, `Map` 등 컬렉션명은 변수명으로 안쓸 수 있으면 안쓰는게 좋습니다.
[여기](https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming)를 참고해주세요.

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/lotto/type/SixNumberComposition.java
> +public class SixNumberComposition {
네이밍에 고민을 많이 하셨군요 ㅎㅎ
작명이란건 가장 어려운 일이죠...

다른 분들은 `LottoNumbers` 를 많이 사용하십니다.

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/lotto/type/SixNumberComposition.java
> +    }
이 클래스의 필드가 `List<Integer>` 형인데요,
'로또 번호 1개' 도 도메인으로 만든다면 어떤 장점이 있을까요?

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/lotto/type/SixNumberComposition.java
> +        }
2depth입니다. 1depth로 줄여주세요.

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/lotto/type/WinningLevel.java
> +    ONE(1);
1개 적중은 의미가 없지 않나요?

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/lotto/type/WinningLevel.java
> +        throw new IllegalArgumentException("알 수 없는 등수: " + winningLevel);
이 부분은 조금 더 간략화할 수 있어요.

1. `this.values()` 는 enum의 모든 값을 순회합니다. 여기서 `Stream`으로 조건에 맞는 데이터를 뽑습니다.
2. 혹은 모든 값을 포함하는 `Map<Integer(맞춘 개수), WinningLevel>` 으로 만들어두고 map.get(개수) 로 뽑아올 수도 있습니다.

위의 두 가지, 혹은 다른 방법을 사용해주시되, 지금처럼 if 반복은 피해주세요.

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/controller/LottoController.java
> +    public void play() {
play 메소드가 너무 깁니다.

> 프로그래밍 요구사항
> 
> 함수(또는 메소드)의 길이가 15라인을 넘어가지 않도록 구현한다.

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/lotto/WinningAmount.java
> +    }
여기에 이 정보를 사용하기보다는 `WinningLevel` 에 상금 정보가 함께 있는 것도 나쁘진 않을 것 같습니다.
너무 if문의 반복이에요.

아니면 상금 정보만을 표현할 클래스를 enum으로 구현하고 `WinningLevel` 를 필드로 갖는 방법도 있겠네요.

2023-11-14 12:48 UTC, dhmin5693 commented on src/main/java/lotto/WinningNumber.java
> +        }
여기도 과한 if문은 제거해주세요.

if문 5개만 넣어도 15줄이며 프로그래밍 요구사항인 15줄을 넘기게 됩니다.

2023-11-14 23:49 UTC, henry174 commented on src/main/java/lotto/type/WinningLevel.java
> +    ONE(1);
이 클래스는 몇 개를 적중하였는지가 아니라 당첨 등수를 의미합니다. (1등인지 3등인지, 4등인지, 5등인지를 나타냅니다.)

2023-11-14 23:50 UTC, henry174 commented on src/main/java/lotto/type/WinningLevel.java
> +        throw new IllegalArgumentException("알 수 없는 등수: " + winningLevel);
이번에 stream을 쓰지 말라고 해서 2번으로 해 봤습니다.

2023-11-15 00:55 UTC, henry174 commented
안녕하세요. 코멘트를 반영하여 다시 리팩토링 해 봤습니다. 거의 대부분 다 반영했는데 한 군데 for문 내부의 if문을 다른 메서드로 빼지 못하고 2중첩 상태로 남겨 놓은 곳이 있습니다. 어떻게 해보려고 했는데 안 되네요. 같이 봐 주셨으면 합니다. //TODO 주석으로 표기해 놓았으니 이 곳을 찾아 보시면 됩니다.

그리고 이번 미션에서는 StreamAPI와 람다를 쓰지 말고 작성해 보라고 해서 이것들은 쓰지 않았습니다.

감사합니다.

2023-11-15 10:40 UTC, dhmin5693 commented on src/main/java/lotto/type/SingleNumber.java
> +public class SingleNumber implements Comparable<SingleNumber> {
역할 분리 👍

2023-11-15 10:40 UTC, dhmin5693 commented on src/main/java/lotto/type/SingleNumber.java
> +    private int lottoNumber;
```suggestion
    private final int lottoNumber;
```

lottoNumber는 항상 있어야만 이 클래스의 의미가 살아납니다.
그런 경우엔 final을 붙여서 의미를 명확하게 표현해주세요.

2023-11-15 10:40 UTC, dhmin5693 commented on src/main/java/lotto/type/SingleNumber.java
> +        return lotto;
```suggestion
        return new SingleNumber(lottoNumber);
```

생성 후 설정해주기보다는 한 번에 완전한 불변 클래스를 만들어주는 방법에 대해서도 고민해보세요.
어떤 장점이 있을까요?

2023-11-15 10:40 UTC, dhmin5693 commented on src/main/java/lotto/type/SingleNumber.java
> +    }
int는 초기화가 되지 않으면 0이기 때문에 굳이 wrapper를 사용하지 않아도 괜찮지 않을까요?
nullable한 경우에만 wrapper를 사용해주세요.

2023-11-15 10:40 UTC, dhmin5693 commented on src/main/java/lotto/type/WinningLevel.java
> +    ONE(1);
제가 오해했군요.
2가 없는 이유도 2등은 다음 미션에서 구현을 위해 남겨놓으신 것 같네요.

2023-11-15 10:51 UTC, dhmin5693 reviewed
승준님 안녕하세요.

코드가 변한걸 보면 그만큼 많이 고민하고 실행에 옮기신 것으로 보이네요 👍 
다음 단계 진행하셔도 좋을 것 같습니다.

몇 가지 의견을 추가로 드렸으니 다음 단계 PR 전에 반영해주시면 감사하겠습니다. 🙏

2023-11-15 10:51 UTC, dhmin5693 commented on src/main/java/lotto/type/WinningLevel.java
> +    }
보통 getInstance() 라는 명칭은 새 인스턴스를 생성하기보다는 singleton으로 생성된 단 하나의 인스턴스를 반환하는 용도로 사용됩니다.

2023-11-15 10:51 UTC, dhmin5693 commented on src/main/java/lotto/WinningNumber.java
> +        );
rules은 1번만 선언되어도 괜찮은 상수가 아닐까요?
매번 같은 상황을 반복하거든요.

2023-11-15 10:51 UTC, dhmin5693 commented on src/main/java/lotto/WinningNumber.java
> +        }
`WinningRule` 을 추상화한건 굉장히 좋은 시도였다고 생각합니다.
다만 `Stream`을 사용하지 않는 상황에서 2 depth를 제외하려면 등수 로직을 `Map` 에다 넣고 `Map.getOrDefault(등수, WinningLevel.NONE)` 같은 방식을 활용하는게 최선이 아닐까 싶네요.

2023-11-15 10:51 UTC, dhmin5693 commented on src/test/java/lotto/LottoGeneratorTest.java
> +package lotto;
이 클래스를 말하는건 아닙니다.

새로 생성된 도메인 클래스가 꽤 많은데 적당한 단위 테스트를 작성해주세요.

2023-11-15 10:52 UTC, merged