Step2
next-step/java-lotto pull request #3394
Opened 2023-11-16 01:41 UTC by hghgusrl

테스트 코드 작성이 너무 어렵네요 제가 기능 분리를 잘못한거 같습니다.

2023-11-16 13:15 UTC, seokhong requested changes
현진님, 2단계 미션 잘 구현하셨습니다. 👍 
테스트 코드 작성과 관련한 코멘트를 남겼고, 이외에도 코드에 코멘트를 남겼습니다. 컨벤션 관련 코멘트가 있는데, 여러 곳에 비슷한 코멘트가 적용될 수 있으므로 코멘트 하나를 반영하실 때 전체 코드를 함께 살펴보고 적용해주시면 좋겠습니다.
코멘트 확인 부탁드립니다. 🙂

2023-11-16 13:15 UTC, seokhong commented on src/main/java/lotto/domain/ResultWinner.java
> +        if(Integer.parseInt(number) > 45){
45라는 값도 상수로 관리해보면 어떨까요?

2023-11-16 13:15 UTC, seokhong commented on src/main/java/lotto/domain/ResultWinner.java
> +        resultMap.put(3,0);
3-6이라는 값도 `WinningToLotto`에서 관리하고 있는 값으로 보이네요. 이 값을 사용해보면 어떨까요?

2023-11-16 13:15 UTC, seokhong commented on src/test/java/lotto/LottoTest.java
> +public class LottoTest {
테스트 작성이 어렵다고 하셔서, 여기에 코멘트 남깁니다. :)

테스트 코드 작성이 어려운 이유가 몇 가지 있을 수 있는데, static 메서드의 사용, 클래스간의 강한 결합도 이유 중 하나입니다.
우선 작은 기능을 할 수 있는 클래스를 하나 만들고, 이에 대한 테스트 코드 작성을 하는 것으로 시작해보면 어떨까요?

`Lotto` 라는 클래스를 아래와 같이 한 번 구현하고 테스트를 작성한 후, 이 클래스를 사용해서 구현을 해보시는 것도 도움이 될 것 같습니다.
* `Lotto`는 6개의 번호로 구성된다.
* 각 번호는 1-45 사이의 값을 가진다. (`int` 에서 제한되는 조건을 가지고 있으니, 이를 관리하는 클래스를 만들어 보셔도 될 것 같네요)
* `Lotto` 생성을 위해서 1-45 사이의 값을 갖는 6개의 번호를 전달해야 한다. (생성자)
* `Lotto`는 다른 `Lotto`를 받아서 몇 개의 번호가 일치하는지 반환한다.

2023-11-19 03:24 UTC, seokhong requested changes
현진님, 2단계 미션 코멘트 잘 반영하셨습니다. 👍 
코드에 코멘트를 추가로 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/controller/LottoController.java
> +        int lottoCount = new InputView().buyOfLottoPrice();
`InputView`를 `lottoCount`를 입력 받을 때도 사용하고, `lastWeekLottoNumber`를 입력 받을 때도 사용하니 변수로 저장해놓고 재사용하는 건 어떨까요?

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/controller/LottoController.java
> +        ResultView.buyLottoList(buyLottoList);
`ResultView`는 static 메서드를 사용하신 이유가 있을까요?
static 메서드를 사용하시지 말라는 것은 아니고, 사용하신 이유가 무엇인지 궁금해서 여쭤봅니다. :)

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/controller/LottoController.java
> +        ResultView.buyLottoList(buyLottoList);
`ResultView`의 메서드명을 보면, `buyLottoList`, `resultView` 와 같이 되어 있는데요.
`구매한 로또 목록을 출력한다`, `당첨 결과를 출력한다`와 같이 기능을 나타낼 수 있는 이름을 사용해보면 어떨까요?

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto() {
`new Lotto()`로 객체를 생성하면 1-45의 값을 가지고 있고, `new Lotto(numbers)`를 통해 객체를 생성하면 특정 번호 목록을 가지고 있네요.
`Lotto`를 하나의 목적으로만 사용해보시면 좋겠습니다. 즉, 모든 로또 번호를 관리하는 클래스라면 항상 `lottos`에 45개의 번호를 관리하고, 한 장의 로또(1-45 사이의 6개의 번호를 가지는 로또 복권)라면 항상 `lottos`에는 6개의 번호만 관리되도록 해보시면 좋겠습니다.

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/Lotto.java
> +    static final int LOTTO_MAX_NUMBER = 45;
내부에서 사용하는 상수, 필드라면 private 접근 제어자로 관리해보면 어떨까요?

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/Lotto.java
> +    private List<Integer> lottos;
`lottos`에 관리되는 번호는 중복될 수 없으니, 이를 나타내는 컬렉션을 사용해보면 어떨까요?

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/LottoGame.java
> +
이 메서드에서도 불필요한 공백은 삭제해보시면 좋겠습니다.

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/LottoShuffleStrategy.java
> +    public List<Integer> shufflable(List<Integer> list) {
메서드의 이름은 동사 또는 동사구로 작성하시는 것을 권장합니다.
`shufflable` 대신 `shuffle` 이라는 이름을 사용해보면 어떨까요?

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/LottoShuffleStrategy.java
> +        List<Integer> buyLotto;
변수의 선언은 사용하는 시점과 가장 가까운 곳에서 하는 것을 권장합니다.
15행의 코드를 `List<Integer> buyLotto = new ArrayList<>(list.subList(0, 6));`과 같이 변경해보면 어떨까요?

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/LottoShuffleStrategy.java
> +    public List<Integer> shufflable(List<Integer> list) {
인자로 들어오는 `list`는 모든 로또 번호일까요? 그렇다면 이를 나타낼 수 있는 이름을 사용해보면 어떨까요?

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/ResultWinner.java
> +    public EnumMap<Rank, Integer> countOfWinner(List<List<Integer>> list, List<String> lastWeekWinner) {
`lastWeekWinner`도 `Lotto`와 동일한 제약조건을 가질 것(1-45 사이의 6개의 번호로 구성)으로 보이니, `Lotto`를 사용하는 `WinnerLotto`를 만들어서 관리해보면 어떨까요?
`validation` 메서드의 중복도 제거할 수 있을 것으로 보입니다.

2023-11-19 03:24 UTC, seokhong commented on src/main/java/lotto/domain/ResultWinner.java
> +
이 메서드에서도 불필요한 빈 줄은 삭제해보시면 좋겠습니다.

2023-11-19 03:24 UTC, seokhong commented on src/test/java/lotto/LottoTest.java
> +    public void 로또생성(){
테스트에서만 생성자를 사용하지 말고, `Lotto` 클래스를 만들었으니 1-45 사이의 6개의 번호를 관리하는 역할을 `Lotto` 클래스를 이용해서 구현해보시면 어떨까요?

2023-11-19 03:24 UTC, seokhong commented on src/test/java/lotto/LottoTest.java
> +        assertThat(Rank.valueOf(6).get()).isEqualTo(Rank.FIRST);
`Rank` 에 대한 테스트는 `RankTest` 파일로 관리해보면 어떨까요?

2023-11-19 12:26 UTC, hghgusrl commented on src/main/java/lotto/controller/LottoController.java
> +        ResultView.buyLottoList(buyLottoList);
resultView를 미리 생성해서 가지고 있으면 속도면에서 조금 더 빠를거 같다는 이유 말고 다른 부분은 없었습니다. 혹시 resultView를 static으로 사용하는 것과 사용하지 않는것에서 어떤게 조금더 좋은 방향일까요?

2023-11-20 02:59 UTC, seokhong commented on src/main/java/lotto/controller/LottoController.java
> +        ResultView.buyLottoList(buyLottoList);
스태틱 메서드를 사용하신 이유가 있다면 사용하는 게 맞다고 생각합니다. 이유가 없다면, 개인적으로 스태틱 메서드의 사용은 유의해야 한다고 생각합니다.
왜냐하면 스태틱 메서드는 클래스를 분리하고 코드가 분리된 것처럼 보이지만, 강한 결합을 가지고 있는 코드이기 때문입니다.
예를 들어서, 스태틱 메서드를 호출하는 메서드를 테스하기 위해서는 사용하는 모든 메서드의 로직을 함께 테스트해야 합니다. 객체를 통한 메서드 호출이 아니므로 테스트에서 의존성을 변경할 수 있는 방법이 없습니다. 만약 의존성 주입을 통해 객체의 메서드를 사용한다면, 전달하는 객체를 변경해서 행위를 제어하거나 테스트 대상의 범위를 좁힐 수 있겠죠. :)

2023-11-20 03:07 UTC, seokhong approved these changes
현진님, 2단계 미션 코멘트 잘 반영하셨습니다. 👍 
2단계 PR 머지하겠습니다.
남긴 코멘트는 다음 단계 미션에서 참고해보시면 좋겠습니다.
3단계 미션에서 뵙겠습니다. 🙂

2023-11-20 03:07 UTC, seokhong commented on src/main/java/lotto/domain/Lotto.java
> +        while (iter.hasNext())
while 문의 범위를 중괄호를 사용해 코드 블록으로 관리해보면 어떨까요?
* if, for, while code block 의 범위를 한 눈에 볼 수 있습니다. 한 줄의 코드만 있다고 하더라도, 해당 코드만 블록에 속한다는 것을 바로 알 수 있습니다.
* 코드 변경이 발생하여 코드 블록 내에 줄이 추가되거나 삭제될 때, 중괄호는 변경이 없으므로 추가/삭제된 코드의 diff 를 보는 것이 용이합니다.
* 코드 변경이 발생할 때, 코드 블록이 명확하므로 장애가 발생할 위험을 낮출 수 있습니다. 예를 들어, 한 줄의 코드만 있는 상황에서 해당 코드를 삭제했을 때, 다음 줄이 임의로 if, for, while 코드 블록에 포함되어 실행되는 상황을 방지할 수 있습니다.

2023-11-20 03:07 UTC, seokhong commented on src/main/java/lotto/domain/Lotto.java
> +        if(iter.next() < LOTTO_MIN_NUMBER || iter.next() > LOTTO_MAX_NUMBER){
`if` 키워드와 여는 소괄호(`(`) 사이에 공백이 누락됐네요.
IDE의 자동 줄맞춤 단축키를 사용하시거나, 파일을 저장할 때마다 자동으로 줄맞춤이 되도록 설정해보시면 좋겠습니다.

intellij를 사용하신다면 Preferences > Tools > Actions on Save 에서 자바 코드도 Reformat Code, Optimize Imports를 설정해서 수정하는 코드를 자동 줄맞춤, 임포트 최적화를 실행하도록 하실 수 있습니다. :)

2023-11-20 03:07 UTC, seokhong commented on src/main/java/lotto/domain/Lotto.java
> +        if(numbers.size() != 6){
6이라는 숫자도 상수로 관리해보시면 좋겠습니다.

2023-11-20 03:07 UTC, seokhong commented on src/main/java/lotto/domain/ResultWinner.java
> +            answerCount = getAnswerCount(lottos.getLottoIndex(i), lastWeekWinner, answerCount);
`answerCount`를 여기에서 선언하고 전달해 줄 필요가 있을까요?
`getAnswerCount` 메서드 내에서 지역 변수로 선언하고, 값만 반환해도 괜찮지 않을까요? :)

2023-11-20 03:08 UTC, merged