4단계 로또(수동)
next-step/java-lotto pull request #3399
Opened 2023-11-16 09:42 UTC by beyondorder

리뷰주신 내용들 반영한 후 작업하였는데
Optional 적용 시 뭔가 더 아름다운(?) 패턴이 있을 것만 같은데 떠오르지 않아 고민이 많았습니다...

2023-11-16 13:38 UTC, nooose requested changes
피드백 대부분 잘 반영되어있네요 👍
코멘트 남겼으니 읽어보시고 재요청 부탁드립니다.

2023-11-16 13:38 UTC, nooose commented on src/main/java/step3/Application.java
> -        Lotto winningNumberLotto = InputView.inputWinningNumbers();
![image](https://github.com/next-step/java-lotto/assets/36617783/5566ca16-9c2a-4dea-b1a9-21298e536dc5)

자바스크립트의 콜백 지옥을 연상케하는 코드가 나왔네요 😱
InputProcessor로 시도해 보신 점은 좋은 것 같아요
다만 InputView에서 Optional을 처리해서 재입력 하게 끔 유도했다면 좋았을 것 같아요
지금은 그냥 Optional 내부 값이 비어있다면 어떤 메시지도 없이 종료되어 버립니다.

사용자 경험을 위해서 그렇게 변경되면 좋은 코드가 되지 않을까요?

2023-11-16 13:38 UTC, nooose commented on src/main/java/step3/domain/Lotto.java
> +                .anyMatch(number -> number.equals(lottoNumber));
👍

2023-11-16 13:38 UTC, nooose commented on src/main/java/step3/domain/LottoMachine.java
> +        return new Lottos(lottos);
```suggestion
        return Stream.concat(autoLottos.lottos().stream(), manualLottos.lottos().stream())
                .collect(Collectors.collectingAndThen(Collectors.toList(), Lottos::new));
```
빈 리스트를 만들고 추가하는 방식보다
리스트를 이어서 리스트를 만드는 게 어떨까요?

2023-11-16 13:38 UTC, nooose commented on src/main/java/step3/domain/LottoMachine.java
> +        return numberBox.subList(0, LOTTO_SIZE);
```java
        List<LottoNumber> numberBox = new ArrayList<>(BOX);
        Collections.shuffle(numberBox);
        return numberBox.subList(0, LOTTO_SIZE);
```
BOX를 재사용하면서도 리스트를 새로 만들어 참조만 끊어줘도 되지 않을까요?
넘버가 캐싱되어있어도 매번 스트림을 돌릴 필요는 없을 것 같아요

2023-11-16 13:38 UTC, nooose commented on src/main/java/step3/domain/LottoNumber.java
> +    static class LottoNumberCache {
👍

2023-11-16 13:38 UTC, nooose commented on src/main/java/step3/view/InputView.java
>          scanner.nextLine();
Optional로 반환하는 이유가 있을까요?
석현님의 의견을 들어보고 싶습니다.

2023-11-16 13:38 UTC, nooose commented on src/test/java/step3/view/InputViewTest.java
> +}
🤔😅

2023-11-16 14:46 UTC, beyondorder commented on src/main/java/step3/Application.java
> -        Lotto winningNumberLotto = InputView.inputWinningNumbers();
처음에 말씀주신 방향으로 인풋에서 입력검증하면서 재시도하게 하려는 시도를 했었는데, 계속 강하게 밀어붙일껄하는 후회가 남네요. 다시 해보겠습니다.!

2023-11-16 15:15 UTC, beyondorder commented on src/main/java/step3/domain/LottoMachine.java
> +        return numberBox.subList(0, LOTTO_SIZE);
반영하겠습니다.

2023-11-16 15:21 UTC, beyondorder commented on src/main/java/step3/view/InputView.java
>          scanner.nextLine();
위에 콜백지옥 조언주신 부분의 댓글내용에 해당합니다..
inputView에서 해결해보겠습니다 !

2023-11-17 11:17 UTC, nooose approved these changes
2단계 때와 비교했을 때 정말 많이 개선된 것 같아요
매 단계마다 피드백이 많았었는데
다 반영해 주시느라 고생 많았습니다. 👍
끝까지 열심히 하셔서 잘 마무리하시길 바랄게요!

2023-11-17 11:17 UTC, nooose commented on src/main/java/step3/view/Input/InputHandler.java
> +    }
이 부분도 depth를 줄여보면 좋겠네요
참고로 재입력 로직은 while이 아닌 재귀 호출로도 해결할 수도 있어요

2023-11-17 11:18 UTC, merged

2023-11-17 11:20 UTC, nooose commented
추가로 리뷰 받으시면서 해결된 부분은 
<img width="433" alt="image" src="https://github.com/next-step/java-lotto/assets/36617783/28ee9b8e-011e-4ba7-afff-2cef4ab53c8e">

사진에 있는 버튼 `Resolve conversation`을 눌러주시면 좋습니다.
이래야 커뮤니케이션이 편해집니다.

다음 미션 때부터 이렇게 해주시면 다음 리뷰어 분이 편하게 리뷰 가능할 것 같아요