Step2 - 로또(자동)
next-step/java-lotto pull request #3403
Opened 2023-11-16 15:51 UTC by pilming44

퇴근하고나서 부지런히 하는데도 진행속도가 느리네요..ㅠ^ㅠ
갑자기 이번 단계부터 훅 할게 많아지고 난이도가 어려워진거같은건 기분탓일까요..
그래도 열심히 구현해봤습니다!

2023-11-17 07:54 UTC, wooobo reviewed
안녕하세요 재현님!

몇가지 코멘트 남겨놓았어요~
확인 후 재요청 부탁드려요~

2023-11-17 07:54 UTC, wooobo commented on src/main/java/lotto/domain/Lotto.java
> +        for (int number = 1; number <= 45; number++) {
`1`,`45`는 로또 만드는 과정에서 의미가 큰 숫자같아요!
그런의미에서 상수로 정의해서 쉽게 알아 볼 수 있도록 해도 좋을것 같아요! ㅎ

2023-11-17 07:54 UTC, wooobo commented on src/main/java/lotto/domain/Lottos.java
> +            winnigAmount += lotto.winningInfo(winningNumber).getWinningAmount();
`Amount` 원시값 포장을 해봐도 좋을것 같아요.
`amount.plus`이런식으로 메시지를 전달할수 있을것 같기도 하구요!

2023-11-17 07:54 UTC, wooobo commented on src/main/java/lotto/domain/Parser.java
> +public class Parser {
[static method만을 가지는 utility class는 private 생성자를 가지도록 구현한다.](https://www.slipp.net/questions/360)

😄

2023-11-17 07:54 UTC, wooobo commented on src/main/java/lotto/view/ResultView.java
> +    }
```suggestion
    public static void purchaseCount(Lottos lottos) {
        System.out.println(lottos.size() + "개를 구매했습니다.");
    }
```

상태를 가진 객체에게 물어봐도 좋을것 같아요 ㅎ

2023-11-17 07:54 UTC, wooobo commented on src/test/java/lotto/domain/LottosTest.java
> +        assertThat(lottos.getLottos().size()).isEqualTo(14000 / Lotto.LOTTO_PRICE);
[검증부 (assert / expect)는 하드코딩한다](https://jojoldu.tistory.com/615)

참고해도 좋을것 같아요~

2023-11-17 07:54 UTC, wooobo requested changes
안녕하세요 재현님!

몇가지 코멘트 남겨놓았어요~
확인 후 재요청 부탁드려요~

2023-11-17 14:54 UTC, pilming44 commented
리뷰내용을 반영해서 수정해봤습니다! 
확실히 amount를 포장하니 코드가 객체끼리 메세지를 주고받는다는 느낌이 많이 듭니다!
다른값도 포장해볼만한게 있나 찾아봤는데 딱히 없는것같아서 amount만 포장해봤어요!
그리고 하다보니 들여쓰기 2번한것도 있었어서 얼른 고쳐버렸습니다! ^^;;
리뷰 부탁드립니다!

2023-11-18 05:27 UTC, wooobo approved these changes
안녕하세요 재현님!

자동미션 수고많으셨습니다 :)
`merge`진행하겠습니다!

다음 단계 진행해주세요~

2023-11-18 05:27 UTC, wooobo commented on src/test/java/lotto/domain/LottoTest.java
> +        assertThat(lotto.winningInfo("1,2,3,45,5,6"))
`usingRecursiveComparison` 보단 그냥 객체간 비교해보는것도 좋을것 같아요.

2023-11-18 05:27 UTC, wooobo commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
여기도 스태틱 메소드만 있으니, private 기본생성자 있으면 좋을것 같네요 :)

2023-11-18 05:27 UTC, merged