step1
next-step/java-lotto pull request #3408
Opened 2023-11-17 08:00 UTC by FineRoot1253

----
## StringCalculatorTest.java
add inputSplit()
add input_nullOrBlank_Exception()
add input_Array_Exception()
add add()
add subtract()
add multiply()
add divide()
add advancedOperate()
----
## Calculator.java
add execute()
add inputValidate()
add inputArrayValidate()
add checkAndCalculate()
add isOdd()
add calculate()

2023-11-18 11:13 UTC, mskangg requested changes
안녕하세요!
이번 미션 리뷰를 맡은 강민수입니다. 🙇‍♂️

1단계 미션 군더더기 없이 깔끔하게 잘구현해주셨네요!
몇가지 피드백 드렸는데, 확인부탁드립니다!

2023-11-18 11:13 UTC, mskangg commented on src/main/java/study/Calculator.java
> +    public static int execute(String input) {
현재 view 와 비즈니스가 분리되어있지 않는것 같아요.
자동차 미션과 같이 view 를 분리해보시는건 어떨까요?

2023-11-18 11:13 UTC, mskangg commented on src/main/java/study/Calculator.java
> +    private static int calculate(int sum, String operator, int other) {
Operator는 + - * / 4개의 기호를 관리하고 있습니다.
그렇다면, enum 으로 관리하는건 어떨까요!? 🤔

그리고 if 부분을 함수형 인터페이스로 작성할 수 있어보입니다!
number1, number2 2개의 변수가 필요하니 BinaryOperator 를 사용하면 될것 같습니다 :)

2023-11-18 11:13 UTC, mskangg commented on src/main/java/study/Calculator.java
> +public class Calculator {
책임이 `Calculator` 에 너무 많은것 같아요!
클래스를 책임별로 분리해보는건 어떠신가요?

2023-11-18 11:13 UTC, mskangg commented on src/test/java/study/StringCalculatorTest.java
> +class StringCalculatorTest {
요구사항을 README 에 마크다운으로 체크리스트를 작성하고 하나씩 처리해보시는건 어떠신가요?

- [ ] 사용자가 입력한 문자열 값에 따라 사칙연산을 수행할 수 있는 계산기를 구현해야 한다.
- [ ] 입력 문자열의 숫자와 사칙 연산 사이에는 반드시 빈 공백 문자열이 있다고 가정한다.
- [ ] 문자열을 더한다.

이렇게 정리한 뒤, 작업을 시작하면 빠지는것 없이 진행할 수 있습니다!

그리고, 정리한 요구사항을 테스트 클래스에 먼저 작성한뒤 비즈니스를 구현하면 더 좋아요!

1. 요구사항 정리
2. @DisplayName("문자열을 더한다.")
3. 비즈니스 구현

이 순서대로 작업하고 체크리스트단위로 커밋해보시는건 어떠신가요~?

2023-11-19 12:24 UTC, mskangg approved these changes
피드백 반영 잘해주셨습니다 😄
추가 코멘트 남겨드렸는데, 확인해주세요!
그럼 2단계 진행해주세요!

2023-11-19 12:24 UTC, mskangg commented on src/main/java/study/Calculator.java
> +    }
이부분을 Operator 안의 책임으로 두는게 나을것 같다는 의견이었습니다 😅

```java
public enum Operator {
    ADD("+", (a, b) -> a + b),
    SUBTRACT("-", (a, b) -> a - b),
    MULTIPLY("*", (a, b) -> a * b),
    DIVIDE("/", (a, b) -> a / b),

    NONE("NONE", null);

    private String value;
    private BinaryOperator<Integer> binaryOperator;

    Operator(String value, BinaryOperator<Integer> binaryOperator) {
        this.value = value;
        this.binaryOperator = binaryOperator;
    }

    public static Operator from(String value) {
        return Arrays.stream(Operator.values())
                .filter(operator -> operator.value.equals(value))
                .findFirst()
                .orElse(NONE);
    }

    public Integer apply(int a, int b){
        return binaryOperator.apply(a, b);
    }
}
```

이렇게 하면 operator 의 책임을 한군데에 캡슐화 할수 있을것 같아 말씀드렸습니다 :)
지금도 틀린건 아니니 적용하시는건 고려해봐주세요~! 😄

2023-11-19 12:24 UTC, merged

2023-11-19 15:25 UTC, FineRoot1253 commented on src/main/java/study/Calculator.java
> +    }
BinaryOperator관련 로직인 findOperator를 Operator에 넣을지 말지 고민고민했었습니다...!
역시...ㅍ좋은 피드백을 남겨주셔서 감사합니다...!