🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #3409
Opened 2023-11-17 09:01 UTC by kyunghyun-Park

안녕하세요 리뷰어님!
2단계.......너무 어려워서 .. ㅠㅠ 한참 걸렸네요..
질문이 길어질 것 같아 DM으로 하겠습니다!

2023-11-18 02:46 UTC, bingbingpa requested changes
2단계 미션 어려워하셨는데 잘 구현해주신 것 같아요! 👍
몇 가지 생각해봤으면 하는 부분들 리뷰 남겨드렸는데
한 번 확인해보시고 다시 한번만 리뷰 요청 부탁드려요.

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/LottoApp.java
> +        controller.run();
`LottoController` 의 static 메소드를 호출하는데 인스턴스를 생성할필요 없지 않을까요?
 그리고 지금과 같이 불필요한 인스턴스 생성을 막기 위해 
이런 경우에는 기본 생성자를 private 를 해주는건 어떨까요?

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/controller/LottoController.java
> +        int quantity = amount / PRICE_OF_LOTTO;
사용자가 입력한 금액이 딱 맞아 떨어지지 않는 경우나 마이너스 금액 등등 
사용자의 금액 입력에 대한 유효성 체크도 필요하지 않을까요?

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/domain/Lotto.java
> +        return numbers;
컬렉션을 리턴할 땐 불변으로 리턴해주는게 어떨까요?

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/domain/Lotto.java
> +        return numbers;
컬렉션을 리턴할 땐 불변으로 리턴해주는게 어떨까요?

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/domain/Lotto.java
> +            if (numbers.contains(number)) {
이번 미션의 프로그래밍 요구사항에 다음과 같은 내용이 있는데요.
`indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.`
이 부분을 만족 하도록 해보면 어떨까요?

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/controller/LottoController.java
> +        LottoWinningMachine winningMachine = new LottoWinningMachine(new Lotto(winningNumbers));
사용자가 입력한 값이 로또 번호가 아닌 경우에 대한 검증도 있어야 하지 않을까요?

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/domain/LottoWinningMachine.java
> +        this.rankCounts = new HashMap<>();
EnumMap 을 사용하는건 어떨까요?

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/domain/Rank.java
> +        return Arrays.stream(values())
values 를 재사용할 수 있지 않을까요?

2023-11-18 02:46 UTC, bingbingpa commented on src/test/java/lotto/domain/LottoWinningMachineTest.java
> +class LottoWinningMachineTest {
1등 말고 다양한 등수에 대한 테스트를 해보는건 어떨까요?

2023-11-18 02:46 UTC, bingbingpa commented on md/lotto.md
> +## 기능 요구사항
요구 사항 정리 잘해주셨네요! 👍
실제 구현한 항목 들은 체크해주는것도 좋을 것 같아요.

2023-11-18 02:46 UTC, bingbingpa commented on src/main/java/lotto/domain/Lotto.java
> +    public int matchCount(Lotto winningLotto) {
override 한 메소드를 마지막에 써주는게 어떨까요?

2023-11-18 13:19 UTC, kyunghyun-Park commented on src/main/java/lotto/domain/LottoWinningMachine.java
> +        this.rankCounts = new HashMap<>();
좋은 컬렉션 배워갑니다!

2023-11-18 14:11 UTC, kyunghyun-Park commented on src/main/java/lotto/controller/LottoController.java
> +        LottoWinningMachine winningMachine = new LottoWinningMachine(new Lotto(winningNumbers));
view 단 에는 검증값?같은 프로젝트의 정보를 안 담는게 맞는 것 같아 Validator로 이관을 했습니다.

이미 InputView에서 List<Integer>로 변환을 해주기 때문에 로또번호 패턴에 대한 유효성 검증을 할수가없어서
이렇게 수정했는데 Lotto 클래스의 validateSize() 가 의미가 사라진 것 같네요.ㅠㅠ

controller에서 검증 할 필요 없고 각 도메인에게 다 이관해도 괜찮은 걸까요?
뭔가 컨트롤러단에서도 먼저 걸러줄 필요가 있다고 생각했거든요!

2023-11-18 14:27 UTC, kyunghyun-Park commented on src/main/java/lotto/domain/Lotto.java
> +            if (numbers.contains(number)) {
이 부분도 조금 어거지로 줄인 것 같네요ㅠㅠ
메서드 인수를 변경해서 return하는건 안 좋다고 본 것 같은데..

Lotto가 갖고있는 numbers를 기준으로 LottoNumber를 인수로 넘겨서 판단하는거라 아래처럼 LottoNumber에게 시키기는 이상하지 않나 싶어서요!
```java
for (LottoNumber number : winningLotto.getNumbers()) {
    count = number.plusCountIfContains(numbers, count);
}
```

2023-11-19 06:29 UTC, bingbingpa commented on src/main/java/lotto/controller/LottoController.java
> +        LottoWinningMachine winningMachine = new LottoWinningMachine(new Lotto(winningNumbers));
유효성 검증에 대해서는 항상 의견이 다양한 것 같은데 저는 기본적으로 도메인 영역에서 검증 하는게 좋다고 생각해요. 
도메인은 하나의 컨트롤러뿐만 아니라 다양한 컨트롤러에서 쓰일수도 있는데 각 컨트롤러마다 검증을 하게 되면
중복된 검증이 생기지 않을까 해서요.
하지만 하나의 도메인에 대해서 각각의 컨트롤러에서 다르게 검증이 필요하다면 컨트롤러에서 검증을 할 수도 있을꺼구 
상황에 따라 다를 것 같다고 생각해요

2023-11-19 06:39 UTC, bingbingpa approved these changes
리뷰 반영 잘해주셨네요! 👍
이번 미션은 머지하도록 하겠습니다!

2023-11-19 06:39 UTC, bingbingpa commented on src/main/java/lotto/exceptions/InvalidLottoAmountException.java
> +public class InvalidLottoAmountException extends RuntimeException {
커스텀한 익셉션 좋네요! 👍

2023-11-19 06:39 UTC, bingbingpa commented on src/main/java/lotto/controller/LottoController.java
> +        final int quantity = amount / PRICE_OF_LOTTO;
금액에 대한 검증과 수량을 계산하는 별도의 `Money` 클래스 같은걸 만들어 활용해 보는것도 좋을 것 같아요.

2023-11-19 06:39 UTC, merged