🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #3420
Opened 2023-11-18 10:56 UTC by hoho282

리뷰 요청합니다.

2023-11-18 19:05 UTC, ohtaeg requested changes
2단계 미션도 구현을 잘해주셨네요 👍 👍 
다음 미션을 진행하기전에 같이 고민해보면 좋을 포인트들이 존재하여 Request changes 하였습니다..!

몇 개의 코멘트를 드렸는데 확인해주시면 감사하겠습니다 :)
정답이 없는 부분들이기에 부담없이 의견을 말해주세요!!
화이팅입니다 🔥

2023-11-18 19:05 UTC, ohtaeg commented on src/main/java/autolotto/strategy/LottoNumberGeneratorImpl.java
> +        return IntStream.rangeClosed(1, MAX_LOTTO_NUMBER)
이 부분은 같이 고민해보면 좋을 것 같아요 :)
매번 로또 번호를 생성해야하는 경우 아래와 같은 로직들이 계속 동작을 하게 될텐데요!

사실 로또라는 번호는 1 ~ 45개의 번호가 정해져있기에
미리 45개의 번호를 생성해놓고 재사용하는 방법도 괜찮을 것 같아요 :)

그럼 아래 로직도 단순해지고 매번 반복문을 계속 돌지 않는 장점이 있을 것 같은데 혜진님의 의견이 궁금하네요 😄

2023-11-18 19:05 UTC, ohtaeg commented on src/main/java/autolotto/domain/Lotto.java
> +    private List<Integer> lottoNumbers;
수정을 위한 리뷰는 아니오니 같이 고민해보면 좋을 것 같아요!

로또 번호를 Integer로 관리하는것도 좋지만 int 값 하나 자체는 의미를 부여하기 힘든 스칼라 값일 뿐이라고 생각해요.

예로 메서드에 여러개의 int 타입을 파라미터로 받는 경우가 존재한다고 가정할 때, 
foo(int a, int b, int c)
파라미터 순서를 잘못해서 입력할 경우 컴파일 시점에서는 문법에 오류없이 해석되지만
런타임 시점에서는 사이드 이펙트가 발생할 요지가 있지 않을까 합니다!

원시값을 포장해서 객체로 다룬다면 아주 사소하더라도 프로그래머에게 그 값이 어떤 값이며,
왜 쓰고 있는지에 대한 정보를 전할 수 있는 장점이 있다고 생각되어지며
객체로 분리함으로써 책임도 전가하여 코드도 간결해지는 장점도 있다고 생각합니다 :)

Lotto에서 하나의 로또 번호라는 객체를 더 분리해도 괜찮을지 고민해보시면 좋을 것 같아요!! 😄

2023-11-18 19:05 UTC, ohtaeg commented on src/main/java/autolotto/domain/LottoStatistics.java
> +    private List<Integer> lastWeekWinNumber;
당첨 번호도 Lotto가 아닐까 싶은데 어떻게 생각하시나요 :) ?

2023-11-19 08:21 UTC, hoho282 commented on src/main/java/autolotto/ui/InputView.java
> +        if(number < 1 || number > 45){
이 부분이 참... 저는 업무 하면서 validation 체크는 컨트롤러단, 즉, 값이 들어오는 input과 밀접한 곳에서 체크 되어 지도록 했거든요. 비즈니스로직을 다루는 service 단 이 과정에서 domain 이라고 표현하는 곳에서는 validation 체크를 왠만하면 하지 않거든요. 어느 것이 맞는 건지 모르겠지만, 저는 제가 하는 스타일이 역할 분담 차원에서 맞다고 믿고 살아서... 아직 온전히 객체지향으로 넘어오지 못해서 일까요? 과정이니깐 최대한 lotto 라고 생각하는 부분에 모아볼게요. 리뷰어 님도 한번 더 고민 부탁드립니다.

2023-11-19 09:42 UTC, hoho282 commented on src/test/java/autolotto/domain/LottoGameTest.java
> +            assertTrue(lotto.lottoNumbers().stream().allMatch(n-> n >= 1 && n <=45));
테스트 코드 잘 작성하고 있는 지 늘 고민 이였는데 가이드 주셔서 고맙습니다.!!!

2023-11-19 14:38 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨어요 👍 👍 
소소한 코멘트 하나를 드렸는데 확인해주시면 감사하겠습니다 :)
다음 미션도 화이팅입니다 🔥

2023-11-19 14:38 UTC, ohtaeg commented on src/test/java/autolotto/domain/LottoGameTest.java
> +            assertTrue(lotto.lottoNumbers().stream().allMatch(n-> n >= 1 && n <=45));
테스트 코드 내에 stream을 통해 반복하는 행위 자체도 결국 로직으로 생각이 되어지는데요 :)
해당 테스트 코드가 검증하고자 하는 것은 결국 1 ~ 45 내에 번호를 잘 가지고 있는지 확인하기 위함이라고 생각이 되어집니다!
그렇다면 객체의 `동등성`을 이용하여 검증하도록 해보면 어떨까싶기도 하네요 😄

2023-11-19 14:38 UTC, ohtaeg commented on src/main/java/autolotto/domain/Lotto.java
> +    public int matchCount(Lotto lottoNumber, Lotto winNumber) {
피드백 반영 👍 👍

2023-11-19 14:38 UTC, ohtaeg commented on src/main/java/autolotto/strategy/LottoNumberGeneratorImpl.java
> +                .collect(Collectors.toList());
👍 👍

2023-11-19 14:38 UTC, merged