3단계 - 로또(2등)
next-step/java-lotto pull request #3442
Opened 2023-11-19 14:25 UTC by jhest

2023-11-20 14:51 UTC, mskangg requested changes
3단계 로또 2등도 잘구현해주셨네요! 👍 
몇가지 코멘트 남겨드렸는데, 확인 부탁드립니다! 🙇

2023-11-20 14:51 UTC, mskangg commented on src/main/java/lotto/view/InputView.java
> +    public int bonusNumberInput() {
보너스볼이 당첨번호와 중복이면 어떻게되나요? 🤔

2023-11-20 14:51 UTC, mskangg commented on src/main/java/lotto/domain/Lotto.java
> +    private Rank rank;
로또가 당첨결과를 갖고 있는게 어색해보입니다.
LottoCenter 에서 당첨결과를 확인하고 있는데, Lotto가 본인의 당첨결과를 알고 있군요..!
Lotto 는 번호만 알고 있고, center 는 당첨번호를 알고있어 당첨결과를 확인하면 Rank 를 리턴하는게 자연스러워보여요!
리턴값이 있으니 테스트코드로도 검증하기도 수월해보이구요!

2023-11-20 14:51 UTC, mskangg commented on src/main/java/lotto/Main.java
> +        int bonusNumber = inputView.bonusNumberInput();
당첨번호와 bonumNumber를 갖고 있는 WinningLotto 클래스를 만들어보시는건 어떠신가요?
WinningLotto에게 Lotto 를 넘겨주면 Rank 를 알수 있을것 같아요!

2023-11-21 02:47 UTC, jhest commented on src/main/java/lotto/view/InputView.java
> +    public int bonusNumberInput() {
WinningLotto에 예외 처리 추가하였습니다.

2023-11-22 01:26 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요 👍 
추가로 코멘트 남겨드렸는데, 이부분은 다음 단계 진행하시면서 같이 고민해봐주세요!
그럼 화이팅 🔥

2023-11-22 01:26 UTC, merged