🚀 3단계 - 로또(2등)
next-step/java-lotto pull request #3483
Opened 2023-11-22 13:53 UTC by ventulus95

안녕하세요. 로또 (2등) 구현하여 리뷰 부탁드립니다. 
해당건 file 변경이 많은건 step2 진행중 step3를 진행하다가... Step2 리뷰를 받고 리펙토링 하다가 보니 그 간격이 꼬여서 머지하다보니까 이렇게 되었구요 ㅎㅎ;

## 질문 드리고 싶은건이 있는데요

보너스 볼 자체가 생기다보니까 해당건에 대한 파라미터가 늘려가는 방향으로 설계 했는데요. 해당하는 형태의 코드를 수정하기 위해서는 파라미터가 늘어나다 보니까 테스트코드도 바꿔야해... 커플링되어있는 메소드도 바꿔야해.. 이러니까 코드를 재대로 리펙토링하는게 맞나.. 싶더라구요

1. 파라미터가 늘어나는 형태의 리펙토링 올바르게 한게 맞을까요?
2. 현재 랭크에서 보너스볼 일치를 맞추다보니까 이렇게 되었고 그렇다면 **보너스볼**에 대한 책임을 저는 `lottoGame`으로 봤는데 이게 맞을까요?
> 사실 이걸 `lotto`가 들고 있을까도 생각해봤는데, 그렇게 되면 로또 사는 경우도 그 로또 클래스에서 보너스볼을 가지고 있어야하는데, 이게 맞는지에 대해서 의문이 많이 들어서요. 로또는 6개의 숫자를 들고 그게 값이랑 보너스번호가 맞는지 여부만 가지고 있으면 되는거 아닌가 싶어서요

2023-11-23 13:17 UTC, shared-moon commented
>파라미터가 늘어나는 형태의 리펙토링 올바르게 한게 맞을까요?

먼저 짚고 넘어가고 싶은게 있는데, 리팩토링은 기본적으로 기능의 변화가 없이 코드의 형태가 달라지는 걸 말합니다. 지금은 기능 추가이기 때문에 리팩토링이라고 부르는 건 적절하지 않아요

기능 추가는 필요하다면 파라미터가 늘어나거나 하는건 뭐 별 문제 없을 것 같은데, 아마 변경을 하면서 여기저기 같이 바뀌는게 있어서 그러시지 않았나 싶네요. 요건 코드 보면서 의견 드릴게요 ~

>현재 랭크에서 보너스볼 일치를 맞추다보니까 이렇게 되었고 그렇다면 보너스볼에 대한 책임을 저는 lottoGame으로 봤는데 이게 맞을까요?

보너스볼을 가지고 있는 책임을 말씀하시는걸까요 ? 제 생각엔 구매용 로또 번호와 당첨용 번호를 아예 따로 가져가는게 좋지 않나 싶습니다. 랭크는 그냥 맞은 개수 + 보너스볼 유무만 가지고 판단할 수 있으면 될 것 같구요 요것도 코드 보면서 의견 드릴게요 ~

2023-11-23 13:28 UTC, shared-moon requested changes
창섭님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 다음 미션 전에 적용 해보면 좋을 것 같아요
확인 후에 리뷰 재요청 부탁드려요 ~
고생 많으셨습니다!

2023-11-23 13:28 UTC, shared-moon commented on src/main/java/lotto/Lotto.java
> +    public boolean matchBonusNumber(LottoNumber bonus) {
Lotto 입장에서 전달받는 LottoNumber가 보너스 번호인지 알 수 있나요 ? 넘겨주는 측에서만 알 수 있을 것 같은데, 좀 더 범용적으로 선언하고 위에 countMatchingWinningLotto에서도 같이 쓸 수 있을 것 같아요 ~

2023-11-23 13:28 UTC, shared-moon commented on src/main/java/lotto/LottoGame.java
> +    public void registerBonusBall(Integer number) {
이거 이렇게 setter를 만들 필요가 있나요 ? 그냥 생성자에서 받으면 굳이 열어 줄 필요 없는 부분으로 보여요

2023-11-23 13:28 UTC, shared-moon commented on src/main/java/lotto/LottoGame.java
> +    public void registerBonusBall(Integer number) {
위에 다른 register~~ 도 마찬가지구요!

2023-11-23 13:28 UTC, shared-moon commented on src/main/java/lotto/Rank.java
> +    private static boolean isSecond(int count) {
여기 해당되는게 SECOND, THIRD인데 메서드명이 isSecond가 맞을까요 ?

2023-11-23 13:28 UTC, shared-moon commented on src/main/java/lotto/LottoStatics.java
> +    public Integer matchCountRanks(int count, boolean matchBonus) {
고민인 부분은 이런식으로 보너스 번호나 보너스 번호 유무가 여기저기 다 영향을 주게 돼서 그러시는거같은데, 원인은 저번 미션에서도 말씀 드린대로 역할 분리가 제대로 안돼서 그런 것 같구요

말씀드린대로 일단 멤버변수로 관리하는 구조부터 바꿔보시면 좀 다르게 풀 수 있을 것 같네요 ~

2023-11-25 04:15 UTC, ventulus95 commented
해당하는 리뷰 잘 보았습니다. 😄 궁금한 질문 하나더 드리고 싶은데요
1. 생성자가 좋은가? 메소드가 좋은가?
`register...` 함수가 만들어지게 된 배경은 로또 등록하기처럼 등록을 하기위해서 이용 된건데요. 생성자로 바꾸는 형태가 된다면 오히려 더 명확하게 로또를 등록한다라고 명확하게 인지하기 어렵다고 생각해서 생성자보다는 Setter메소드 처럼 만들게 된거라서요. 답이 있는 문제는 아닌거 같고, 의견 공유 받아보면 좋을 거 같아서요!

2023-11-25 13:31 UTC, shared-moon commented
답이 있는 문제가 아닌 것 같다고 하셨는데 개인적으론 지금 방식은 오답이라고 생각하구요
굳이 다른 답을 찾자면 빌더 패턴을 이용해서 named 파라미터처럼 전달하는 방식과 비교해 볼 수는 있을 것 같네요

생성자와 setter는 비교 대상이 아닙니다.
생성자에서 받는 파라미터는 해당 객체가 `생성되기 위해 필요한 재료` 들로, 반드시 가지고 있어야 한다는 의미를 이미 가지고 있습니다.
setter는 `만들어진 객체의 상태를 변경 할 수 있게 허용` 해주는 메서드로 근본적으로 캡슐화로 얻은 정보의 보호 라는 이득을 상쇄시킵니다.

LottoGame을 만들 때 로또 번호들과 당첨번호를 받는건 꼭 필요한 일이니 생성자에서 받는게 맞다고 생각합니다. setter로 받게 되면 외부에서 setter 호출을 안하고 게임을 진행할 때 정상적으로 돌아가지 못할테니까요.

물론 상태를 변경하면서 사용해야 하는 경우도 있으니 setter가 필요한 경우도 생기긴 하고, 그럴 땐 말씀하신것처럼 의미를 명확히 드러내도록 역할을 정해줘야 하겠지만. 지금은 애초에 setter가 필요한 경우가 아닌 것 같다는 의견이었습니다 :)

2023-11-25 13:38 UTC, shared-moon approved these changes
창섭님 안녕하세요 ~
피드백 반영 잘 해 주셨네요 ~
질문 남기신거에 코멘트 달아뒀는데, 다음 미션 진행 전 확인 부탁드려요 ~
고생 많으셨습니다 :)

2023-11-25 13:38 UTC, shared-moon commented on src/main/java/lotto/LottoStatics.java
> +    private WinningLottos winningLottos;
혹시 멤버변수를 유지하시는 특별한 이유가 있을까요 ?

2023-11-25 13:38 UTC, merged

2023-11-26 05:15 UTC, ventulus95 commented on src/main/java/lotto/LottoStatics.java
> +    private WinningLottos winningLottos;
이게 버릇이되니까 남겨놓게되네요. ㅎㅎ; 수정하겠습니다.