3단계 - 로또(2등)
next-step/java-lotto pull request #3485
Opened 2023-11-22 14:41 UTC by pawoo0211

승훈님 안녕하세요~ 회사일이 바빠서 PR 주셨는데 늦게 반영했네요ㅠ 

이번 3단계도 잘 부탁드립니다!

2023-11-23 06:56 UTC, csh0034 requested changes
3단계 잘 구현해주셨네요 😄 
몇가지 코멘트 남겨두었는데 확인후에
다시 리뷰요청 부탁드립니다!

2023-11-23 06:56 UTC, csh0034 commented on src/main/java/lotto/domain/WinningFinder.java
>      private final List<LottoNumber> WINNING_NUMBER;
상수 컨벤션으로 되어있네요!
인스턴스변수는 winngerNumber 로 해주세요!

또한 Lotto 타입으로 선언해보면 좋을것 같습니다.

2023-11-23 06:56 UTC, csh0034 commented on src/main/java/lotto/ui/ResultView.java
> +        System.out.println(matchCount + "개 일치, 보너스 볼 일치(" + amount + ")-" + count + "개");
보너스 일치가 아니라면 출력 문구에 `보너스 볼 일치` 라는 부분이 제거되어야할것 같아요!

2023-11-23 06:56 UTC, csh0034 commented on src/main/java/lotto/domain/WinningFinder.java
> +        return bonusNumber != null;
보너스번호가 로또번호에 포함되었는지로 체크해야되지 않을까요? 🤔

![image](https://github.com/next-step/java-lotto/assets/44543456/3a417dfe-f3b1-4ab5-9ec8-c9764f42b319)

2023-11-23 06:56 UTC, csh0034 commented on src/main/java/lotto/domain/Lottos.java
> +    public Lottos(List<Lotto> lottoList, List<Integer> winningLottoNumbers) {
보너스번호가 없는 상태로 생성되지 않아야 하지 않을까요? 🤔

2023-11-23 06:56 UTC, csh0034 commented on src/main/java/lotto/domain/WinningFinder.java
>  public class WinningFinder {
WinningFinder 라는 이름보다 하단과 같이 적용을 고려해보면 좋을것 같아요.

`WinningLotto 가 로또번호인 Lotto 와 보너스번호인 LottoNumber 를 같는다.` 

추가로 출력 결과에 대해선 필드로 가지고있지 않고 메서드 호출시점에
만들어서 내려주도록 개선해보면 좋을것 같습니다.

2023-11-24 08:30 UTC, pawoo0211 commented on src/main/java/lotto/domain/WinningAmount.java
> +    FIVE_MATCH_AND_BONUS(5,30000000),
자바 7부터는 언더스코어가 있어도 컴파일 에러가 안나느군요!

2023-11-24 08:45 UTC, pawoo0211 commented on src/main/java/lotto/common/LottoGenerator.java
> +        for (int number = lottoNumber.START_NUMBER; number <= lottoNumber.END_NUMBER; number++) {
기본적인 것인데 놓쳤네요ㅠ

2023-11-24 09:12 UTC, pawoo0211 commented on src/main/java/lotto/domain/Lotto.java
> +    private Integer addIfEqualWinningNumber(
피드백 감사합니다!

2023-11-24 09:22 UTC, pawoo0211 commented on src/main/java/lotto/domain/WinningFinder.java
>      private final List<LottoNumber> WINNING_NUMBER;
피드백 감사합니다!

2023-11-24 11:50 UTC, pawoo0211 commented on src/main/java/lotto/domain/WinningFinder.java
> +        return bonusNumber != null;
아 제가 계속 뭔가 놓치고 있다고 생각했는데 이 부분이였군요.... 이거를 기능 구현할 때 생각을 못했네요ㅠㅠ

2023-11-24 22:13 UTC, csh0034 approved these changes
리뷰 잘 반영해주셨네요 👍 
몇가지 코멘트 남겨두었는데
다음단계 진행하시면서 고민해주시면 좋을것 같습니다.
마지막단계에서 봬요!

2023-11-24 22:13 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +        numbers.sort(Comparator.comparingInt(LottoNumber::getLottoNumber));
값을 꺼내와서 정렬을 진행하고있네요 🥲

inputLottoNumbers 에 대해서 정렬 처리를 하거나
하단 코드가 가능하도록 적용해보시면 좋을것 같습니다.

`Collections.sort(numbers);`

2023-11-24 22:13 UTC, csh0034 commented on src/main/java/lotto/domain/WinningLotto.java
> +    public WinningLotto(Lotto winningLotto) {
테스트코드에서만 사용하는 bonusNumber 가 없는 winningLotto 가 존재하네요 🥲

당첨로또의 경우엔 로또번호 6자리와 보너스번호를 가진다라는 도메인 규칙을 지켜보면 좋을것 같습니다.

추가로 당첨번호엔 보너스번호가 포함되지 않도록 검증하는 부분도 추가되면 좋을것 같아요!

2023-11-24 22:13 UTC, csh0034 commented on src/main/java/lotto/domain/WinningLotto.java
> +        if (bonusNumber == null) {
bonusNumber 가 null 인 경우가 존재해야 하는걸까요? 🥲

2023-11-24 22:13 UTC, csh0034 commented on src/main/java/lotto/domain/WinningLotto.java
> +public class WinningLotto {
현재 WinningLotto 의 당첨 통계를 계산하는 부분이 다소 복잡한것 같아요.
이부분은 간략하게 개선해보면 좋을것 같습니다.

2023-11-24 22:13 UTC, merged

2023-11-25 00:23 UTC, pawoo0211 commented on src/main/java/lotto/domain/WinningLotto.java
> +        if (bonusNumber == null) {
Step2에서는 보너스 번호가 존재했었기에 해당 요구사항을 유지하면서 나머지 요구사항에 대해 기능 구현을 하려고 했기에 유지를 했었는데 없애도록 하겠습니다!