4단계 - 로또(수동)
next-step/java-lotto pull request #3502
Opened 2023-11-23 17:33 UTC by myunghoonju

안녕하세요~  

매번 감사드려요 많이 배웁니다 ㅎㅎ  
3단계 코멘트와 함께 리뷰 부탁드려요~

감사해요ㅎ

2023-11-24 12:31 UTC, seokhong commented on src/main/java/step4/domain/Winning.java
> +    public void setBonusWinNumber(String number) {
보너스 번호는 우승 번호에 반드시 필요한 요소로 보입니다.
`setBonusWinNumber`를 통해 값을 설정하기보다는, 생성자(`public static Winning from(String winNumber)`)에 `String bonusNumber` 인자를 추가해서 `Winning` 객체를 만들어보면 어떨까요? 객체에 반드시 필요한 값은 객체를 생성하는 시점에 전달하도록 해서, 생성된 객체에는 해당 값이 항상 존재하도록 해보시면 좋겠습니다.

또한, 보너스 번호는 당첨번호(`win`)와 중복될 수 없으므로, 생성자에서 검증도 해보시면 좋겠습니다.

2023-11-24 12:32 UTC, seokhong commented on src/main/java/step4/domain/Winning.java
> +        int winCount = getWinCount(lottery.getNumbers());
`lottery.getNumbers()`로 값을 꺼내지 말고, `lottery.matchCount(win)`과 같이 당첨번호를 전달해서 일치되는 개수를 물어보는 형태로 구현해보시면 좋겠습니다.

2023-11-24 12:35 UTC, seokhong commented on src/main/java/step4/constant/Prize.java
> +    FIRST(6, 2_000_000_000, (correct, bonus) -> correct == 6 && !bonus),
1, 4, 5, 미당첨(`BAD_LUCK`)은 보너스 번호의 일치여부가 중요하지 않습니다.
`&& !bonus` 조건을 제거해보면 어떨까요?

`Winning#matchBonus`에서 당첨번호와 5개가 일치할 때만 보너스 번호의 일치여부를 확인한 후 인자로 전달하는데요.
`Prize`를 직접 사용해도 `getPrize`가 잘 동작하도록 구현해보시면 좋겠습니다. 현재는 `getPrize`를 사용할 때, `Winning#matchBonus`의 로직을 동일하게 구현하지 않으면 1, 4, 5, 미당첨이 제대로 조회되지 않을 것으로 보입니다.

2023-11-24 12:35 UTC, seokhong commented on src/main/java/step4/LotteryApplication.java
> +        int manualTicketCount = InputView.getManualTicketCount();
`manualTicketCount`가 `allTicketCount`보다 큰 경우 어떻게 될까요?

2023-11-24 12:37 UTC, seokhong commented on src/main/java/step4/domain/Lottery.java
> +    private final List<Integer> numbers;
`Integer` 대신 아래와 같은 클래스를 만들어서 활용해보면 어떨까요?
로또 번호는 1-45 사이의 값만 들어와야 하므로 이를 클래스로 만들어서 관리해볼 수 있을 것 같아요.

```java
public class LottoNumber {

    private static final List<LottoNumber> ALL_NUMBERS;

    private final int value;

    static {
        // ALL_NUMBERS 초기화
    }

    private LottoNumber(int value) {
        validate(value);    // 1-45 사이의 숫자인지 검증
        this.value = value;
    }

    public static LottoNumber of(int number) {
        return ALL_NUMBERS.get(number - 1);
    }

    public List<LottoNumber> allNumbers() {
        return new ArrayList<>(ALL_NUMBERS);
    }

    // 이외에 필요한 메서드 구현
}
```

2023-11-24 12:37 UTC, seokhong commented on src/test/java/step4/domain/WinningTest.java
> +}
파일 마지막에 newline 이 없다고 깃헙에서 경고를 띄워주네요.  
파일 마지막의 newline 은 무슨 역할을 하는지 학습해보신 후, IDE 설정을 통해 휴먼 에러를 방지해보시면 좋겠습니다.

2023-11-25 17:00 UTC, myunghoonju commented on src/main/java/step4/domain/Lottery.java
> +    private final List<Integer> numbers;
https://github.com/next-step/java-lotto/pull/3502#discussion_r1404310436 랑 동일한 부분이네요.  
둘중에 무엇을 택할까 하다가 링크에 있는 것 해보았어요ㅎ

2023-11-26 03:06 UTC, seokhong requested changes
명훈님, 4단계 미션 코멘트 잘 반영하셨습니다. 👍 
조금 더 수정해보시면 도움이 될 것 같은 내용이 있어 코멘트 추가로 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-11-26 03:06 UTC, seokhong commented on src/main/java/step4/util/LotteryUtil.java
> +    public static final int WINNING_STREAK = 6;
6개로 구성되어야 한다는 것은 `Lottery`의 제약조건이니, `Lottery` 에서 상수를 관리하고 밸리데이션을 해보는 것도 좋겠네요! :)

2023-11-26 03:06 UTC, seokhong commented on src/main/java/step4/util/LotteryUtil.java
> +        for (int ball = 1; ball <= 45; ball++) {
`balls` 대신 `LotteryNumber`에 있는 `ALL_NUMBERS`를 꺼내와서(`allNumbers()` 와 같은 메서드를 구현하고, `ALL_NUMBERS`를 복사해서 반환) 사용해보는 건 어떨까요?

2023-11-26 03:06 UTC, seokhong commented on src/main/java/step4/util/LotteryUtil.java
> +    public static void validateNumber(int number) {
1-45 사이의 숫자만 생성될 수 있다는 제약 조건은 `LotteryNumber`에서 관리해보면 어떨까요?
상수도 `LotteryNumber`에서 관리할 수 있을 것 같아요.

2023-11-26 03:06 UTC, seokhong commented on src/main/java/step4/util/LotteryUtil.java
> +        if (46 > number) {
`number`가 46보다 작으면 정상적인 번호로 보이네요! 식이 반대로 된 것 같습니다. :)

2023-11-26 03:06 UTC, seokhong commented on src/main/java/step4/util/LotteryUtil.java
> +public class LotteryUtil {
`LotteryUtil`과 같이 유틸리티 클래스를 통해 중복 코드를 줄이는 방법도 좋은 방법입니다.
다만, 특정 클래스와 관련된 코드(e.g., 상수, 밸리데이션)는 해당 클래스에 먼저 구현해보시면 좋겠습니다. 각 클래스는 스스로의 제약 조건, 비즈니스 규칙을 가장 잘 아는 곳이어야 합니다. 이렇게 조건을 하나의 클래스에 모아서 관리하면 사용할 때 더 편리하고(해당 클래스를 사용하면 모든 제약 조건이 잘 지켜질 것이라고 예측할 수 있음), 코드의 변경이 필요한 순간에도 해당 클래스만 수정하면 됩니다.

2023-11-26 14:50 UTC, myunghoonju commented on src/main/java/step4/constant/LotteryNumber.java
> +        ALL_NUMBERS = new ArrayList<>();
1~45사이 6개 로또 번호를 입력 받을 때 번호별로 LotteryNumber 객체를 생성하고 ALL_NUMBERS 에서 관리하는데요  
미리 생성해 놓는다는 것은 어떤 의미일까요?

```
 public class Lottery {
    private final List<LotteryNumber> lotteryNumbers;

    public Lottery(List<LotteryNumber> numbers) {
        this.lotteryNumbers = numbers;
    }
    public static Lottery of(List<Integer> numbers) {
        return new Lottery(LotteryNumber.of(numbers));
    }  
```  

```
 public static List<LotteryNumber> of(List<Integer> numbers) {
        for (int number : numbers) {
            ALL_NUMBERS.add(new LotteryNumber(number));
        }
        return ALL_NUMBERS;
    }
```

2023-11-26 15:04 UTC, myunghoonju commented on src/main/java/step4/domain/Lottery.java
> +    private final List<LotteryNumber> lotteryNumbers;
LotteryNumber 라는 객체가 그저 45개의 공을 관리하는 클래스라면  
제가 만든 객체는 역할이 달라서 코멘트를 잘 못 적용  한 것 같은데 맞을까요?  
저는 이 객체가 각각의 추점 공 하나를 관리하고 ALL_NUMBERS에 6개의 입력받은 로또 번호들이 들어 있다고 생각했어요  


```
    public static List<LotteryNumber> of(List<Integer> numbers) { // 지난주 당첨번호 OR 자동 / 수동 추점번호
        for (int number : numbers) {
            ALL_NUMBERS.add(new LotteryNumber(number));
        }

        return ALL_NUMBERS;
    }
```

2023-11-26 15:30 UTC, myunghoonju commented on src/main/java/step4/util/LotteryUtil.java
> +        for (int ball = 1; ball <= 45; ball++) {
https://github.com/next-step/java-lotto/pull/3502#discussion_r1405416530  이것이 이해가 되면 같이 해결될 이야기군요 ㅠ

2023-11-26 15:35 UTC, myunghoonju commented
으 불현듯 코멘트 내용을 잘 이해 못하고 있는 것 같네요 ㅠ

2023-11-26 17:35 UTC, myunghoonju commented
아하! 이거군요!

```
  static {
        for (int i = LOTTO_MIN; i <= LOTTO_MAX; i++) {
            LOTTERY_NUMBERS.add(new LotteryNumber(i));
        }
    }
```

```
    private static LotteryNumber getLotteryNumber(int number) {
        return LOTTERY_NUMBERS.get(number - 1);
    }
```


```
    public static List<LotteryNumber> of(List<Integer> numbers) {
        List<LotteryNumber> lotteryNumbers = new ArrayList<>();
        for (int number : numbers) {
            lotteryNumbers.add(getLotteryNumber(number));
        }

        return lotteryNumbers;
    }
```

2023-11-26 17:36 UTC, myunghoonju commented on src/main/java/step4/constant/LotteryNumber.java
> +        ALL_NUMBERS = new ArrayList<>();
https://github.com/next-step/java-lotto/pull/3502#issuecomment-1826843535 이거죠? 후후

2023-11-26 17:48 UTC, myunghoonju commented on src/main/java/step4/util/LotteryUtil.java
> +        for (int ball = 1; ball <= 45; ball++) {
https://github.com/next-step/java-lotto/pull/3502#issuecomment-1826843535 처럼 하면  
고럼 이거슨 이렇게 !! 후후훗
```

public static void prepare() {
        balls = LotteryNumber.getAllLotteryNumber();
}
```

2023-11-26 17:48 UTC, myunghoonju commented
오호 새벽갬성에 문제가 해결됨 +_+

2023-11-26 17:49 UTC, myunghoonju commented on src/main/java/step4/domain/Lottery.java
> +    private final List<LotteryNumber> lotteryNumbers;
https://github.com/next-step/java-lotto/pull/3502#issuecomment-1826843535

2023-11-27 08:15 UTC, seokhong commented on src/main/java/step4/domain/Lottery.java
> +        validateNumbers(numbers);
`Lottery` 객체를 생성하는 시점에 이미 `lotteryNumbers`는 6개인 것이 보장되므로, `getLotteryNumbers`에서 값을 꺼낼 때는 6개인지 검증하지 않아도 괜찮을 것 같네요.

2023-11-27 08:20 UTC, merged