🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #3517
Opened 2023-11-25 18:07 UTC by jmnl225

안녕하세요, 리뷰어님!
지난번 코멘트를 참고해서 최대한 노력을 해봤는데.. 그래도 많이 부족한 것 같네요. ㅠㅠ
이번 미션을 하면서 확인 부탁드리고 싶은 부분들이 있습니다.

1. 클래스를 최소한으로 분리하려고 노력했는데 더 신경써야할 점이 있을까요?
2. UI클래스가 아니어도 출력 기능을 가져도 될까요?
3. 제 코드의 PrizeType과 Prize 클래스 부분이 너무 엉망인 것 같은데 어떻게 개선을 해야할지 방향을 못 잡겠습니다. 😭 살려주세요..

2023-11-27 00:35 UTC, mskangg requested changes
리뷰를 드린줄 알았는데, pending상태였네요 😂
기다리셨을텐데, 죄송합니다 🙇

2단계 정말 잘구현해주셨네요!
몇가지 코멘트 남겨드렸는데, 확인 부탁드립니다!

2023-11-27 00:35 UTC, mskangg commented on src/main/java/step2/Lotto.java
> +    }
> UI클래스가 아니어도 출력 기능을 가져도 될까요?

같이 고민을 해봐요! 🤔
만약 출력에 대한 요구조건, 즉 로또 번호를 1, 2, 3, 4, 5 가 아닌 1 - 2 - 3 - 4 - 5 로 변경되면 지금 구조에서 어디를 바꿔야할까요?
분명 출력의 요구사항임에도 도메인을 수정해야하는 경우가 생기네요..!
그렇다면 이부분은 출력의 책임으로 봐야할것 같은데, 어떻게 생각하시나요?

2023-11-27 00:35 UTC, mskangg commented on src/main/java/step2/PrizeType.java
> +    private final Prize prize;
여기선 함수형인터페이스 보단, 
일치개수, 상금 정도면 될것 같아요!

2023-11-27 00:35 UTC, mskangg commented on src/main/java/step2/Winnings.java
> +    private final Map<Integer, Integer> winnings;
PrizeType 으로 관리함에도, 여기선 Integer로 맵을 구성하셨네요!
EnumMap 으로 변경하는게 좋을것 같아요 🙂
추가로 일반 hashMap 과 enumMap 의 차이에 대해 살펴보시는것도 추천드립니다.
(enumSet 도 보시면 더욱좋아요)

2023-11-27 00:35 UTC, mskangg commented on src/main/java/step2/Winnings.java
> +    public void addLottoValue(int key){
당첨결과를 관리하는 클래스 좋아요 👍

2023-11-27 00:35 UTC, mskangg commented on src/main/java/step2/PlayLotto.java
> +    public int playLottos(int[] winningNumber){
winningNumber 도 엄연히 lotto 클래스의 책임을 다해야할 것 같아요.
winningNumber 를 lotto 로 받는건 어떠신가요?
그렇다면, 1-45 와 같은 숫자, 6개의 숫자, 중복되지 않는 숫자 모두 로또와 동일하게 가져갈 수 있을것 같아요

2023-11-30 09:33 UTC, mskangg requested changes
피드백 반영 잘해주셨네요! 👏 
아직 반영이 안된부분들이 보이는것 같아요 🫠
추가적으로 코멘트 남긴부분들까지 확인해주시고 재요청 부탁드립니다! 🙏

2023-11-30 09:33 UTC, mskangg commented on src/main/java/step2/Lotto.java
> +    }
이부분도 아직 반영이 안된것 같아요..!

2023-12-01 11:28 UTC, jmnl225 commented on src/main/java/step2/Lotto.java
> +    private final List<Integer> lotto;
이 부분을 어떻게 해야하는지 잘 모르겠습니다. ㅠㅠ값 객체 캡슐화라는 말씀은 
private final List<Integer> lotto; 부분을 삭제하는 건가요? ㅠㅠㅠㅠ

2023-12-01 14:17 UTC, mskangg commented on src/main/java/step2/Controller.java
> +                System.out.println("입력 오류가 발생했습니다. 다시 입력해주세요.");
이렇게 한곳에서 핸들링 하는방법이 좋아요!
예외 전략에 관하여 찾아보시는 것 추천드립니다!
인사이트를 위해 관련 링크 남겨드릴게요 :)

https://cheese10yun.github.io/spring-guide-exception/

2023-12-01 14:19 UTC, mskangg commented on src/main/java/step2/Prize.java
> +    UNKNOWN(0,0);
👏 👏 👏

2023-12-01 14:21 UTC, merged