🚀 4단계 - 로또(수동)
next-step/java-lotto pull request #3524
Opened 2023-11-26 14:37 UTC by hvoiunq

3단계 때 디테일한 부분까지 리뷰 해주신 것 너무 감사드립니다..!
덕분에 많은 내용과 인사이트 얻을 수 있었던 것 같아요!!
로또 마지막 미션도 잘 부탁드립니다!☺️

2023-11-26 15:25 UTC, catsbi requested changes
효정님 드디어 로또 마지막 단계 미션이네요 👏
현재 기능 구현 이전에 패키지가 계속 java 디렉토리에 바로 계층 패키지와 애플리케이션 코드가 있어요. 이는 별로 권장되는 사항이 아니기에 제가 링크드린 글 참고해서 리팩토링되면 좋을 것 같아요. 

그리고 EnumMap을 사용하신건 좋은데 이에 대한 타입 선언은 최대한 추상화된 타입으로 바꾸는걸 권장드립니다. 
다음으로, 클래스명과 인스턴스 필드명도 동일하게 하지 않는걸 권장드리는데 이 역시 코멘트에 있으니 체크하시면 좋을 것 같아요. 

피드백 확인 후 다시 리뷰요청 부탁드려요!

2023-11-26 15:25 UTC, catsbi commented on src/main/java/domain/LottoNumber.java
> +    }
앗....캐싱이 되지 않았네요.
이렇게 된다면 매번 LottoNumber(1)을 100번 요청하면 새로운 LottoNumber가 100개 생성될 것 같아요. 
equals and hashcode를 재정의해서 동등성은 만족할 수 있지만 이러면 동일성 만족을 하지 못할 것 같네요!

2023-11-26 15:25 UTC, catsbi commented on src/main/java/domain/WinningLotto.java
> +    private static void validateBonusNumber(Set<LottoNumber> lottoNumbers, int bonus) {
int bonus가 아니라 LottoNumber bonusNumber이면 더 간단하지 않을까요?

2023-11-26 15:25 UTC, catsbi commented on src/main/java/AppConfig.java
>  public class AppConfig {
현재 Config class와 Application Class가 java 패키지 바로 아래 있네요. 
이는 패키지 구조 없이 클래스를 프로젝트에 소스 디렉토리에 위치시키는 것으로 안티패턴입니다. 

java 라는 소스 디렉토리 안에 내가 만들고자 하는 기능의 패키지명을 지정했다면 이 패키지 명 아래에 도메인 혹은 계층기반으로 패키지를 분리하는게 좋습니다. 

참고: https://rules.sonarsource.com/java/RSPEC-1220

2023-11-26 15:25 UTC, catsbi commented on src/main/java/LottoApplication.java
> +        userLottoService.buyRandomLottoTickets(totalTicketCount - manualTicketCount);
현재 해당 메인 함수 안의 로직이 15줄을 넘어가는 것 같아요. 그렇다면 리팩토링 대상이 될 것 같네요!

2023-11-26 15:25 UTC, catsbi commented on src/main/java/domain/Lotto.java
>      public Lotto(int num1, int num2, int num3, int num4, int num5, int num6) {
점층적 생성자 패턴에서 중요한건 간단한 기본값만 설정( 말 그대로 로직을 추가해서 기본값을 만드는게 아니라 그냥 정해진 값들을 넣어주는 정도)하는 이상의 작업이 들어가면 제가 이전 피드백에서 말했던 생성자에 비즈니스 로직을 넣는게 되기 때문에 안티패턴입니다.

2023-12-11 10:19 UTC, hvoiunq commented on src/main/java/domain/LottoNumber.java
> +    }
ㅠ_ㅠ 지식이 얕다보니 정적팩토리 메소드를 활용하면 캐싱 역할이 되는 거라고 착각했습니다..
캐싱으로 다시 수정해볼게요!

2023-12-11 11:23 UTC, hvoiunq commented on src/main/java/domain/Lotto.java
>      public Lotto(int num1, int num2, int num3, int num4, int num5, int num6) {
로또 숫자가 6개라는 검증을 다른 생성자에서 마다 하는게 너무 비효율적이지 않을까? 해서 이렇게 개발했습니다,
이런 경우라도 각 생성자마다 중복 호출로 체크하는게 나을까요??

2023-12-11 11:39 UTC, hvoiunq commented on src/main/java/domain/Lotto.java
>      public Lotto(int num1, int num2, int num3, int num4, int num5, int num6) {
그리고 각 점층적 생성자에서 호출해보는거 연습하려고 했는데.. stream 사용하는 곳에서 막혀버렸습니다..ㅠㅠ

2023-12-12 11:04 UTC, catsbi commented on src/main/java/domain/Lotto.java
>      public Lotto(int num1, int num2, int num3, int num4, int num5, int num6) {
앗 정적팩토리함수를 활용해보면 어떨까요 ㅠㅠ

2023-12-12 11:07 UTC, catsbi commented on src/main/java/util/LottoNumberGenerator.java
>      public static final Integer MAX_LOTTO_NUMBER = Integer.valueOf(45);
```suggestion
    public static final Integer MIN_LOTTO_NUMBER =1
    public static final Integer MAX_LOTTO_NUMBER =45
```
그냥 이렇게 작성하셔도 됩니다! ㅎㅎ

2023-12-12 11:08 UTC, catsbi commented on src/main/java/util/LottoNumberGenerator.java
>      public static List<Integer> generateLottoNumber() {
반환타입을 Integer가 아니라 LottoNumber로 해도 되지 않을까요? 
```suggestion
    public static List<LottoNumber> generateLottoNumber() {
```

2023-12-12 11:08 UTC, catsbi commented on src/main/java/util/LottoNumberGenerator.java
> +    public static LottoNumber getNumber(int num) {
num이 1~45에 포함되지 않는 값인지에 대한 검사도 되면 좋을 것 같네요!

2023-12-12 11:09 UTC, catsbi commented on src/main/java/util/LottoNumberGenerator.java
>  public class LottoNumberGenerator {
유틸리티 클래스로 관리할것이라면 생성자 제한을 해보면어떨까요?

private 로 기본생성자를 선언해두면 외부에서 객체 생성을 하지 못할 것 같네요!

2023-12-12 11:11 UTC, catsbi commented on src/main/java/service/LottoGameHandler.java
> +        Optional<Currency> optionalCurrency = Optional.of(Currency.KRW);
Optional 타입을 매개변수로 활용하는건 권장되지 않습니다.! 
참조: https://velog.io/@sangmin7648/Java-Optional-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

2023-12-12 11:12 UTC, merged