🚀 3단계 - 로또(2등)
next-step/java-lotto pull request #3532
Opened 2023-11-27 16:13 UTC by gkssk4163

안녕하세요, 승훈 리뷰어님!

2단계 피드백 반영 및 3단계 구현 완료하여 리뷰 요청드립니다!

추가로 2단계 피드백 내용 주신 내용 중 궁금한 내용에 댓글 작성해두었습니다!
이미 답변해주신 부분도 있는데 추가로 작성한 부분이 있어 해당 내용도 확인해주시면 좋을 것 같습니다 😄
[🚀 2단계 - 로또(자동) PR 링크](https://github.com/next-step/java-lotto/pull/3444)

3단계도 잘 부탁드립니다! 🙇

2023-11-28 03:02 UTC, csh0034 requested changes
3단계도 잘 구현해주셨네요 👍 
몇가지 코멘트 남겨두었는데 확인 부탁드려요!

2023-11-28 03:02 UTC, csh0034 commented on src/test/java/lotto/domain/LottoTest.java
> +                Arguments.of(Arrays.asList(1, 2, 3, 4, 5, 7), LottoResult.BONUS),
추가된 보너스에 대한 테스트 추가 👍

2023-11-28 13:50 UTC, gkssk4163 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final Integer value;
Comparable 객체로 만들기 위해 `compareTo` 함수를 구현하면서 Integer 의 compareTo 를 통해 비교하려고 Wrapper Class로 변경하게 되었습니다.
굳이 변수 선언을 변경하지 않고 `Integer.compare(this.value, other.value)` 로도 비교가 가능하네요! 해당 방법으로 수정해보았습니다

2023-11-29 04:12 UTC, csh0034 approved these changes
리뷰 잘 반영해주셨네요 💯 
몇가지 코멘트 남겨두었는데 다음단계 진행하시면서
고민해보시면 좋을것 같습니다.
마지막 단계에서 봬요!

2023-11-29 04:12 UTC, csh0034 commented on src/main/java/lotto/domain/WinningLotto.java
> +        this.winningLotto.numbers().stream()
값을 꺼내와서 비교하기보다 Lotto 의 hasNumber 를 호출하면 되지 않을까요? 🤔
추가로 적절한 예외메세지를 추가해보면 좋을것 같습니다.

2023-11-29 04:12 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
>      public Lotto(List<Integer> numbers) {
내부 컬렉션이 Set 이므로 생성자의 전달받는 타입도 Set 으로 해보는건 어떨까요?

2023-11-29 04:12 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +                .filter(value -> this.hasNumber(value))
`.filter(this::hasNumber)` 와 같이 메서드 레퍼런스를 사용해볼수도 있을것 같습니다.

2023-11-29 04:12 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +        return this.numbers.stream().collect(Collectors.toList());
반환시 방어적 복사를 하기위함이라면 하단과 같이 가능할것 같아요.
`return new ArrayList<>(this.numbers);`

다만 반환시엔 컬렉션에 대해 추가 삭제를 하지 못하도록 unmodifiable collection 을 적용해볼수도
있을것 같습니다.

2023-11-29 04:12 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +        return this.numbers().contains(lottoNumber);
바로 필드인 numbers 에 접근하지 않고 방어적복사를하는 메서드를 호출할
필요가 있을까요? 🤔

2023-11-29 04:12 UTC, merged

2023-12-03 13:27 UTC, gkssk4163 commented on src/main/java/lotto/domain/Lotto.java
> +        return this.numbers.stream().collect(Collectors.toList());
추가 삭제를 방지해주는 기능이 있는지 몰랐네요! 👍