🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #3533
Opened 2023-11-27 19:08 UTC by h3yon

안녕하세요. 1단계 리뷰해주신 부분 바탕으로 2단계도 수정해보았습니다.
리뷰 및 승인 부탁드립니다.
감사합니다~!

2023-11-28 14:38 UTC, catsbi requested changes
희윤님 2단계 미션 잘 해주셨어요 👍 
그런데 현재 패키지 구조가 auto가 루트 패키지로 되어있는데, 로또서비스를 다루는데 오토 패키지라고 하니 이게 로또기능을 다루는지 자동(?)이라는 무엇인가인지 알기 힘든 것 같네요. 추가적으로 피드백 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/AutoApplication.java
> +    private static final int LOTTERY_PRICE = 1000;
로또의 가격 정보는 어디서 관리하는게 적절할까요?

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/AutoApplication.java
> +public class AutoApplication {
이 클래스는 어떤 계층이라고 보시나요? 지난 미션(자동차 경주)에서 마지막 리팩토링 단계에서 MVC Pattern에 대해 나왔는데, 해당 클래스는 어떤 계층으로 보이시나요?

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/AutoApplication.java
> +        int lotteryCount = purchaseAmount / LOTTERY_PRICE;
로또를 몇 장 구매할 수 있는지에대한 로직들이 계산되고 있는데 테스트 케이스가 작성되었을까요? 

그런데 해당 클래스에는 UI 로직들이 있네요. 

요구사항중에 UI Layer는 테스트 예외대상이라고 했는데 그럼 이 로직은 테스트 예외 대상인걸까요?

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/application/AutoService.java
> +public class AutoService {
오토 서비스라는 객체명은 무엇을 책임지는 클래스로 보이시나요? 🤔
자동? 그럼 자동에 대한 모든걸 담당하는걸까요? 자동 로봇? 자동 로봇 청소기,등등 이름이 너무 포괄적으로 작성되는 것은 해당 객체에 대한 책임 분리와 가독성측면에서 매우 효율이 떨어지게 만듭니다. 마치 xxxUtils 클래스와 마찮가지로요.

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/application/AutoService.java
> +    }
```java
IntStream.range(0, Long.MAX_VALUE).map(createLotteryNumbers()).collect(toList());
```

위와 같은 로직을 호출하면 어떤일이 생길까요? 매번 1부터 45까지 반복문을 Wrapper 타입으로 박싱하고 이를 섞고, 0~6개를 잘라서 반환해야할까요? 

미리 만들어두고 재활용하는 식으로는 할 수 없을까요?

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/application/AutoService.java
> +    private List<Integer> createLotteryNumbers() {
로또 생성 로직이 바뀌게 된다면 서비스 로직을 계속 바꿔야 할까요? 아니면 내부적으로 createLotteryNumbers2() 이런식으로 넘버링을 해야할까요.  전략패턴을 통해 생성에 대한 책임을 분리하고 서비스계층에선 추상화에 의존하도록 로직을 개선해보면 어떨까요?

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/application/MatchService.java
> +public class MatchService {
전체적으로 로직들이 서비스 계층에 전부 작성되어 있어요. 지금 구조를 보면 트랜잭션 스크립트 패턴으로 작성되있는걸 알 수 있습니다. 이 방식은 예전에 구현 난이도가 낮아서 자주 사용되었지만, 유지보수 및 확장성의 문제로 현재는 잘 사용되지 않는 방법으로 현재는 도메인 모델 패턴이 주로 사용됩니다. 

참고: [트랜잭션 스크립트 패턴 vs 도메인 모델 패턴](https://velog.io/@hoyun7443/%ED%8A%B8%EB%9E%9C%EC%9E%AD%EC%85%98-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%ED%8C%A8%ED%84%B4-vs-%EB%8F%84%EB%A9%94%EC%9D%B8-%EB%AA%A8%EB%8D%B8-%ED%8C%A8%ED%84%B4)

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/application/MatchService.java
> +                                            .mapToInt(number -> winningNumbersLastWeek.contains(number) ? 1 : 0)
삼항연산자역시 if-else로 취급되어 안티패턴에 속합니다

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/application/MatchedAmount.java
> +            return NONE;
단 한줄짜리 분기문이라도 블럭`{}` 생략은 지양해주세요. 
코드의 전체적인 일관성을 깨트리고 가독성을 낮출 수 있습니다.

2023-11-28 14:38 UTC, catsbi commented on src/main/java/auto/application/MatchService.java
> +    private static final Map<Integer, Integer> matchedCountMap = MatchedAmount.getMatchedCountMap();
서비스 계층인데 정적 필드가 있고, 동시성 이슈가 발생할 수 있지 않을까요?

2023-11-28 14:38 UTC, catsbi commented on src/test/java/auto/application/AutoServiceTest.java
> +        });
이 역시 for() { for(){ for(){... logic } } } 과 같은 구현으로 검증에서도 코드 indent레벨에 신경써주면 좋을 것 같아요. 
테스트도 가독성은 중요한 요소입니다 😅

2023-12-10 03:23 UTC, h3yon commented on src/main/java/auto/AutoApplication.java
> +    private static final int LOTTERY_PRICE = 1000;
로또 도메인을 둬서 해야겠네요! 3단계 때 Lotto 객체 생성해놓았는데 거기로 옮기겠습니다. 감사합니다~

2023-12-10 03:25 UTC, h3yon commented on src/main/java/auto/AutoApplication.java
> +public class AutoApplication {
음 진입점이다 보니까 다른 메인 클래스들처럼 계층 밖에 있어야 된다고 생각했습니다! 계층을 고려하여야 할까요??

2023-12-10 03:28 UTC, h3yon commented on src/main/java/auto/AutoApplication.java
> +        int lotteryCount = purchaseAmount / LOTTERY_PRICE;
오 분리하는 게 좋겠네요! 감사합니다ㅎㅎ

2023-12-10 03:30 UTC, h3yon commented on src/main/java/auto/application/AutoService.java
> +public class AutoService {
아하 프로젝트 명이 java-lotto 라고 명시되어 있다보니 그냥 Auto 로 할까 했는데 확실히 헷갈리는 감이 있는 거 같습니다.
반영하겠습니다. 감사합니다~

2023-12-10 03:32 UTC, h3yon commented on src/main/java/auto/application/AutoService.java
> +    }
오 좋은 의견 감사합니다!

2023-12-10 03:38 UTC, h3yon commented on src/main/java/auto/application/MatchService.java
> +public class MatchService {
도메인 모델..! 더 학습해보겠습니다. 감사합니다~!

2023-12-10 03:39 UTC, h3yon commented
안녕하세요. 제가 잘못 이해한 부분 있으면 반영하겠습니다.
PR 리뷰 및 승인 재요청드립니다.
감사합니다~

2023-12-10 13:40 UTC, catsbi approved these changes
희윤님 피드백 반영 열심히 해주셨네요. 계층 분리에 대해서 노력해주신 것 같습니다 👍 
몇 가지 피드백 남겨드렸는데 확인 후 다음 미션에서 같이 반영해보는걸로 하죠. 

피드백들을 정리하면 다음과 같아요. 
1. 일급 객체, 일급 컬렉션을 활용하자. 
2. 서비스가 아닌 도메인에 상태를 다루는 핵심 로직을 둬서 트랜잭션 스크립트 패턴을 피하자. 
3. 리포지토리 계층과 서비스 계층이 무슨 차이인지 고민해보자.

2023-12-10 13:40 UTC, catsbi commented on src/main/java/auto/AutoLotteryApplication.java
> +    private static final MatchLotteryService matchLotteryService = new MatchLotteryService();
자동 로또를 만드는 것과 로또 번호를 매칭하는기능들은 모두 로또에 대한 서비스 로직같은데 로또에 대한 기능들을 다루는 서비스를 모두 다 분리하는건, 안되는건 아닌데고민해보면 좋을 것 같네요. 너무 서비스 계층이 많아질 것 같네요

2023-12-10 13:40 UTC, catsbi commented on src/main/java/auto/application/AutoLotteryService.java
> +    public List<List<Integer>> createLotteryNumbersList(int lotteryCount) {
현재 로또 번호묶음을 가지는 로또의 묶음을 반환하고 있는데, 파악하기가 쉽지 않을 것 같아요. 
일급 객체, 일급 컬렉션을 활용해보면 어떨까요? 

로또번호는 결국 1~45로 정해져있어요. 그럼 이 1~45까지의 숫자를 책임지는 LottoNumber라는 일급 객체가 나올수 있고, 이 번호 6개 묶음을 가지는 객체가 Lotto라는 도메인 계층이 생길 수 있겠죠. 

여기서 끝이 아닙니다. 이 로또가 내가 구매하고자 한 만큼의 갯수로 로또 묶음이 생길 수 있으니 로또의 묶음은 Lottos 일급 컬렉션이 나올 수 있겠네요. 

이렇게 일급객체와 일급 컬렉션을 만든다면, 가장중요한 핵심 도메인에 대한 로직들이 "서비스"가 아니라 "도메인"에서 이뤄져서 제가 피드백드렸던 트랜잭션 스크립트 패턴을 피할 수 있지 않을까요?

2023-12-10 13:40 UTC, catsbi commented on src/main/java/auto/application/MatchLotteryService.java
> +                                            .mapToInt(number -> getMatchCount(winningNumbersLastWeek, number))
return 1 or 0을 하기보단 boolean 타입으로 필터링한다음 count를 하는게 좀 더 적절하지 않을까요?

2023-12-10 13:40 UTC, catsbi commented on src/main/java/auto/domain/AutoLotteryRepositoryImpl.java
> +public class AutoLotteryRepositoryImpl implements AutoLotteryRepository {
repository라는 이름을 관례적으로 본다면 데이터베이스와 같이 저장소역할을 하는 곳에서 값을 crud하는 공간으로 알기 쉬운데, 내부적인 로직을 보면 사실상 서비스 계층처럼 보입니다.

2023-12-10 13:40 UTC, catsbi commented on src/main/java/auto/infrastructure/AutoLotteryRepository.java
> +public interface AutoLotteryRepository {
인터페이스를 활용해보셨네요 👍

2023-12-10 13:40 UTC, merged