🚀 4단계 - 로또(수동)
next-step/java-lotto pull request #3540
Opened 2023-11-28 16:22 UTC by hoon25

안녕하세요! 벌써 로또 마지막 미션이네요!

잘 부탁드립니다🙇‍♂️🙇‍♂️

### 고민했던 부분
수동 로또를 Lotto를 조합한 `ManualLotto`로 클래스를 만들까 했는데, 
로직이없는 데이터 클래스를 만드는 것은 지양하라고 배워서 만들지 않았습니다. 괜찮은 선택이였는지 궁금하네요!

2023-11-29 15:04 UTC, kyucumber requested changes
수고 많으셨습니다.

변경이 그리 많지 않아서 간단한 코멘트만 몇개 남겨두었는데요. 한번 확인 부탁드려요. 다음 요청 시 머지하도록 하겠습니다.

2023-11-29 15:04 UTC, kyucumber commented on src/main/java/lotto/LottoApplication.java
>  public class LottoApplication {
수동 요구사항이 추가되어도 크게 바뀌는 것이 없게 깔끔하게 잘 구현해주셨네요 👍

2023-11-29 15:04 UTC, kyucumber commented on src/main/java/lotto/domain/WinningLotto.java
> +            throw new IllegalArgumentException("보너스볼이 로또와 중복됩니다.");
이런 예외가 프로덕션에서 나면 어떤 값이 겹쳤는지 찾기가 어려울 것 같아요. 어떤 값이 겹쳤는지 예외 메시지에 남기는건 어떨까요?

2023-11-29 22:54 UTC, hoon25 commented on src/main/java/lotto/domain/WinningLotto.java
> +            throw new IllegalArgumentException("보너스볼이 로또와 중복됩니다.");
[refactor(exception): 중복된 보너스볼 메시지 정보 추가](https://github.com/next-step/java-lotto/pull/3540/commits/6761bd5c88ef37e28b701dfab05087f7159813ed)로 작업을 진행했어요.

진행하면서 궁금했던 점이 있었습니다!
만약 Lotto도 메시지에 추가하기 위해서 Lotto, lottoNum에 toString을 구현하였습니다.

결과적으로 메시지가 찍히는 것을 보면
`보너스볼 1는 로또번호 Lotto{lottoNums=[LottoNum{num=1}, LottoNum{num=2}, LottoNum{num=3}, LottoNum{num=4}, LottoNum{num=5}, LottoNum{num=6}]}와 중복될 수 없습니다.`
인데 이대로도 괜찮을까요? (우선 드는 걱정은 도메인이 바로 노출된다는 점입니다.)

실무에서는 어떻게 작업하시나요?

2023-11-30 08:29 UTC, kyucumber commented on src/main/java/lotto/domain/WinningLotto.java
> +            throw new IllegalArgumentException("보너스볼이 로또와 중복됩니다.");
> 결과적으로 메시지가 찍히는 것을 보면
보너스볼 1는 로또번호 Lotto{lottoNums=[LottoNum{num=1}, LottoNum{num=2}, LottoNum{num=3}, LottoNum{num=4}, LottoNum{num=5}, LottoNum{num=6}]}와 중복될 수 없습니다.
인데 이대로도 괜찮을까요? (우선 드는 걱정은 도메인이 바로 노출된다는 점입니다.)

일반적으로 벡엔드에서 남긴 예외 메시지가 클라이언트단에 그대로 노출되도록 설계하지 않습니다. 사용자는 에러 메시지를 볼 일이 없기 때문에 로그 상으로는 회원의 주민번호 등 개인정보와 관련된게 아니면 노출되어도 무방하지 않을까 생각되네요.

2023-11-30 08:29 UTC, kyucumber approved these changes
마지막까지 수고 많으셨습니다.

https://github.com/next-step/java-lotto/pull/3540#discussion_r1410319595

간단한 코멘트 남겨두었으니 참고 부탁드려요.

2023-11-30 08:29 UTC, merged