[Step1] 문자열 계산기 구현
next-step/java-lotto pull request #3578
Opened 2024-03-15 09:30 UTC by DevRunner21

안녕하세요! 리뷰어님!
이번 미션 잘 부탁드립니다!

저번 미션에서는 너무 생각이 많았어서 시간이 좀 오래걸렸다보니..
이번 미션은 우선 빠르게 만들어서 리뷰 드리게되었습니다.

많이 부족한 코드지만 리뷰 잘 부탁드립니다!

2024-03-15 09:31 UTC, DevRunner21 commented on src/main/java/calculator/Operator.java
> +	static {
연산자 검색 기능을  static 블록에 Map을 넣어서 구현했습니다.

2024-03-16 01:12 UTC, Hyeon9mak requested changes
안녕하세요  지훈님! 로또 미션을 함께할 최현구입니다. 🙇‍♂️ 
문자열 계산기 잘 구현해주셨어요!
간단한 코멘트 남겼으니 확인해주세요.

2024-03-18 04:37 UTC, DevRunner21 commented
@Hyeon9mak 
안녕하세요! 피드백 반영이 좀 늦었습니다.. ㅜㅜ
말씀주신 부분 반영해봤는데 리뷰 부탁드립니다.

## PR 포인트

기존애 Calculator에서 입력받은 계산식에 대한 ValidationCheck의 책임까지 가지고 있었습니다.
그에 따라서 Calculator에서 
식을 분해하고 
검증하고 
계산까지 진행하고 있었는데요..
Calculator에게 너무 과한 책임이 부여된 듯하여 이 부분을 분리해보았습니다.

분리한 부분은 아래와 같습니다.
- 문자열을 분해하는 책임을 별도의 Separator 객체로 분리했습니다.
  - 공백 이외에 다른 구분자로 요구사항이 변경되었을 시 유연하게 대처하기 위해 추상클래스를 선언해서 사용했습니다.
  - 인터페이스가 아니라 추상클래스로 선언한 이유는?
    - Separator의 경우 구현체들에서 공통적으로 구현해야 하는 기능이 있었습니다. 
     공백이나 null 입력 시 예외를 던지는 부분인데요..
  이 부분을 템플릿화하기 위해 인터페이스가 아닌 추상클래스로 만들게 되었습니다. 
 
- 잘못된 계산식에 대한 검증의 책임을 Formula 객체에게 부여했습니다.
 
이로써 Calculator는 검증된 Formula를 입력받아서 계산만 하면 되도록 바꿔봤습니다.

2024-03-18 04:45 UTC, DevRunner21 commented on src/main/java/calculator/Calculator.java
> +	public int calculate(String input) {
이 부분의 경우 생각해봤는데,
저는 View 보다는 Domain 객체에서 수행하는게 더 적합하다고 생각합니다.
그 이유로는 비즈니스 요구 사항이 문자열 계산식을 분해해서 계산을 진행해야 하기 떄문입니다.

View의 경우 비즈니스 로직과의 의존성을 최대한 베제해야 한다고 생각합니다.

다만 현재 Calculator 객체에게 너무 많은 책임이 부여된 것도 사실입니다.
그래서 이번에 Calculator에게 부여된 책임을 분리해보았는데,
피드백 부탁드립니다!

2024-03-18 04:49 UTC, DevRunner21 commented on src/main/java/calculator/Calculator.java
> +		}
이 부분의 경우 메서드 네이밍을 어떻게 해야 할지 애매해서 그냥 놔두고 넘어간 부분이었는데.. ㅎㅎ
꼼꼼한 피드백 감사드립니다!

이 부분 네이밍을 고민해봤는데,
Calculator 객체에서 계산식의 정합성을 검증하는 메서드의 이름을 지으려니까
네이밍이 길어지고 또 이 로직이 Calculator에 있는게 맞을까? 라는 고민을 하게 되었습니다.

고민해본 결과 Calculator 객체가 부담해야하는 책임이 아니라는 생각이 들어서
Formula 라는 객테에게 이 책임을 위임했고
Class 이름과 함께 의미 전달이 충분히 가능 할 것 같아서
 Method 이름을"validate()"라는 식으로 추상화하여 네이밍했습니다.

2024-03-18 15:22 UTC, Hyeon9mak approved these changes
안녕하세요 지훈님! 피드백 잘 반영해주셨습니다 👍 

> Calculator에게 너무 과한 책임이 부여된 듯하여 이 부분을 분리해보았습니다.

과한 책임이라는 것은, 문자열 계산기에 유지보수가 필요할 때
A 라는 이유에서도 `Calculator` 클래스를 열어봐야하고, 
B 라는 이유에서도 `Calculator` 를 열어보아야해서 부담되기 때문에 분리를 해주셨다는 의미겠지요? 😄 
클래스를 분리하는 이유는 결국 유지보수 하기 좋은 코드 배치를 위함임을 잘 알고 계시리라 믿습니다!!

잘 구현해주셨으니 바로 다음 단계에서 뵙겠습니다 👍 👍

2024-03-18 15:22 UTC, Hyeon9mak commented on src/main/java/calculator/Formula.java
> +	private final StringSeparator separator;
> 저는 View 보다는 Domain 객체에서 수행하는게 더 적합하다고 생각합니다.
그 이유로는 비즈니스 요구 사항이 문자열 계산식을 분해해서 계산을 진행해야 하는 것이기 때문입니다.

👍 👍 구현 대상이 "문자열 계산기" 이므로, 말씀해주신 대로 공백까지도 비즈니스 정책으로 볼 수도 있겠네요!!

2024-03-18 15:22 UTC, Hyeon9mak commented on src/main/java/calculator/Formula.java
> +		if (splitedFormula.size() % 2 != 1) {
생성자 체이닝 활용 👍 👍 
체이닝 순서에 따라 정렬해주면 가독성이 조금 더 오르겠네요!!

2024-03-18 15:22 UTC, Hyeon9mak commented on src/main/java/calculator/BlankSeparator.java
> +
학습을 위한 여러가지 시도 + 유연한 대응을 위한 추상화는 언제나 응원합니다...만!!
(당연히 잘 하시겠지만) 꼭 분리가 필요했는지도 함께 고민해주시면 더욱 좋을거 같습니다 😄 👍

2024-03-18 15:22 UTC, merged