[Step1] 로또 문자열 계산기 구현
next-step/java-lotto pull request #3587
Opened 2024-03-16 16:53 UTC by NaayoungKwon

안녕하세요 리뷰어님!
로또 Step1 PR 올립니다.
한 주간 잘부탁드립니다 :)

2024-03-17 04:28 UTC, Hyeon9mak requested changes
안녕하세요 나영님! 로또 미션을 함께할 최현구입니다. 🙇‍♂️ 
문자열 계산기 잘 구현해주셨어요!
간단한 코멘트들 남겼으니 확인해주세요.

2024-03-17 04:28 UTC, Hyeon9mak commented on src/main/java/Calculator.java
> +  );
bi function 을 활용한 관리 👍 
별도 클래스 파일로 분리해주면 추후 다른 연산자를 추가하거나, 연산 행위를 수정하고자 할 때
연산자 관련 로직을 탐색하기 더욱 편리할 것 같아요.

2024-03-17 04:28 UTC, Hyeon9mak commented on src/main/java/Calculator.java
> +
stream api 호출부를 각각 메서드로 분리하여 이름을 붙여주면, 어떤 값들을  가져오는 건지 한눈에 읽힐 것 같아요!

2024-03-17 04:28 UTC, Hyeon9mak commented on src/main/java/Calculator.java
> +  }
메세지를 던져주어 사용자가 오류를 인지하고 다음 행동을 결정할 수 있도록 해주는 건 어떨까요?
https://hyeon9mak.github.io/writing-helpful-error-messages/

2024-03-17 04:28 UTC, Hyeon9mak commented on src/main/java/Calculator.java
> +  }
연산자 클래스를 잘 분리해두면 그 클래스에게 물어볼 수 있겠네요 😉

2024-03-19 01:05 UTC, NaayoungKwon commented
안녕하세요! 리뷰 감사합니다~ 피드백 반영해서 다시 커밋올렸습니다!

2024-03-19 09:46 UTC, Hyeon9mak approved these changes
안녕하세요 나영님! 피드백 잘 반영해주셨습니다.
간단한 코멘트 남겼으니 확인해주세요!
다음 단계에서 뵙겠습니다 👍

2024-03-19 09:46 UTC, Hyeon9mak commented on src/main/java/Operator.java
> +  }
상수의 모음집이라면, enum class 를 써도 좋겠네요! 👍

2024-03-19 09:46 UTC, Hyeon9mak commented on src/main/java/Calculator.java
> +  }
👍

2024-03-19 09:46 UTC, merged