feat(step2): 로또(자동)
next-step/java-lotto pull request #3598
Opened 2024-03-17 15:38 UTC by chyjeon

안녕하세요 리뷰어님!
본격 단계인 로또 부분을 리뷰요청드립니다!
이번 과제도 잘부탁드립니다!!

2024-03-18 12:18 UTC, dhmin5693 commented
커밋 내역을 보니 한 번에 모든 작업을 완료하신 것 같아요.
한 번의 커밋에 작업을 어디까지 할지 쪼개보는 연습을 해보세요.

2024-03-18 14:23 UTC, dhmin5693 requested changes
안녕하세요. 리뷰가 조금 늦었네요 😢 
그만큼 더 꼼꼼하게 보고 의견을 남겨두었습니다.
확인해보시고 수정 후 다시 요청주세요.

2024-03-18 14:23 UTC, dhmin5693 commented on src/main/java/lotto/view/OutputView.java
> +    }
`List` 인덱스에 과하게 의존하다 보니 view 클래스에서도 도메인 정보를 다루고 있습니다.
view에서 도메인을 의존할 수는 있으나 너무 과하게 의존하면 도메인과 view에서 코드 중복이 발생합니다.
과한 도메인 의존은 제거해주세요.

`List` 를 생성하던 클래스를 수정해주시면 자연스레 해결될 것 같습니다.

2024-03-18 14:23 UTC, dhmin5693 commented on src/main/java/lotto/view/OutputView.java
> +    private static List<Integer> benefit = new ArrayList<>(Arrays.asList(2000000000, 1500000, 50000, 5000));
당첨액수도 도메인 정보입니다.
domain으로 옮겨주세요.

2024-03-18 14:23 UTC, dhmin5693 commented on src/main/java/lotto/BuyLottos.java
> +package lotto;
패키지 구조가 잡혀있지 않습니다.

자동차 경주의 [step5](https://edu.nextstep.camp/s/E42ziiPQ/ls/BKOyHCz5) 를 참조하여 domain, view 등 적절하게 분리해주세요.

2024-03-19 17:53 UTC, chyjeon commented on src/main/java/lotto/LottoMatch.java
> +    private List<Integer> rankOfLotto = new ArrayList<>(Arrays.asList(0,0,0,0));
enum으로 하면 인덱스를 사용하지 않아도 괜찮겠네요..! 수정하겠습니다

2024-03-19 17:59 UTC, chyjeon commented on src/main/java/lotto/view/OutputView.java
> +    private static List<Integer> benefit = new ArrayList<>(Arrays.asList(2000000000, 1500000, 50000, 5000));
리뷰 반영 과정에서 삭제 하였습니다 :)

2024-03-20 14:29 UTC, dhmin5693 approved these changes
굉장히 많이 개선되었네요 👍 
수고하셨습니다.
step3에서 뵈어요 😄

2024-03-20 14:29 UTC, dhmin5693 commented on src/main/java/lotto/domain/Lotto.java
> +    private List<Integer> lotto = new ArrayList<>();
로또 번호 하나를 `LottoNumber` 같은 클래스로 책임을 이관하면 어떨까요?

2024-03-20 14:29 UTC, merged