feat : [Step2] 로또(자동)
next-step/java-lotto pull request #3599
Opened 2024-03-17 16:34 UTC by astrid-dm

안녕하세요 멘토님, 주말 잘 보내셨나요?
주말동안 힐링을 하느라 과제를 많이 하지 못했습니다만, 아쉬운대로 차주부터는 좀더 분발하도록 하겠습니다.

이번 과제부터는 커밋 양이 보다 많아질것으로 보여,
완성할때 한 번에 PR을 작성하지 않고 기능별로 완성이 되었을때, 동시에 하루 작업량이 완료되었을때 커밋을 하려고 합니다.
불완전한 부분은 아직 작성중인걸로 이해해주시길 바라며, 작성된 부분 중 개선이 필요되는 부분이 있다면 피드백 주시면 감사드리겠습니다.

그럼 이번 step2도 잘 부탁드립니다!

2024-03-18 14:48 UTC, testrace requested changes
안녕하세요 다미님 😃 
무조건 완성해서 PR을 생성하기 보다 지금의 방법도 굉장히 좋다고 생각합니다 👍 
몇 가지 코멘트 남겨두었는데요 확인해 주시고 다시 리뷰 요청 부탁드려요!

2024-03-18 14:48 UTC, testrace commented on README.md
> +# STEP 2 : 로또 (자동)
개인적으로 지난 단계의 요구사항을 지우지 않았어도 괜찮을 것 같아요 😃

2024-03-18 14:48 UTC, testrace commented on src/main/java/AutoLotto/model/LottoGenerator.java
> +    private static List<Integer> randomNumbers = new ArrayList<>();
클래스 변수는 모든 인스턴스가 공유할 수 있는 변수입니다
LottoGenerator 객체를 두 번 생성한다면 randomNumbers의 요소는 90개가 됩니다 
이는 의도치 않는 버그를 발생시킬 수 있다고 생각하는데요
인스턴스 변수를 관리하지 않는다면 생성자를 제한하고 static 메서드를 제공하면 어떨까요?

2024-03-18 14:48 UTC, testrace commented on src/main/java/AutoLotto/model/LottoGeneratorStrategy.java
> +}
FunctionalInterface 👍 
로또 생성을 전략 패턴으로 구현하실 계획이시군요!

2024-03-18 14:48 UTC, testrace commented on src/main/java/AutoLotto/model/Lottos.java
> +    private List<List<Integer>> lottos = new ArrayList<>();
List-List 구조는 코드를 작성하기에도, 읽기에도 쉽지 않은 구조라고 생각하는데요
컬렉션을 중첩하기 보다 내부의 List를 하나의 객체로 도출해보면 어떨까요?
`Integer`는 1개의 로또 번호, `List<Integer>` 타입은 6개의 로또 번호이니 원시 값을 포장하고 일급 컬렉션을 적용하면 어떨까요?

2024-03-18 14:48 UTC, testrace commented on src/main/java/AutoLotto/model/Lottos.java
> +    private LottoGenerator lottoGenerator = new LottoGenerator();
Lottos를 일급 컬렉션으로 의도하셨다면 LottoGenerator는 멤버 변수에서 제외하면 좋을 것 같아요
일급 컬렉션은 컬렉션 변수 외에 아무런 변수도 가지지 않아야해요

2024-03-18 14:48 UTC, testrace commented on src/main/java/AutoLotto/model/Lottos.java
> +    private List<List<Integer>> buyLottos(int chances, LottoGeneratorStrategy lottoGeneratorStrategy) {
클래스명이 LottoMachine 이었다면 적절한 메서드명이었을 것 같아요
`LottoMachine.buy(...)`;

2024-03-18 14:48 UTC, testrace commented on src/main/java/Application.java
> +import AutoLotto.AutoLotto;
패키지명 [컨벤션](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names) 확인 부탁드려요

2024-03-18 14:48 UTC, testrace commented on src/main/java/AutoLotto/view/InputView.java
> +        return input.endsWith("000") && input.length() >= 4;
scanner에서 String 타입으로 입력을 받아서 생긴 조건이라고 생각되는데요
로또 한장의 가격이 1000이라면 입력 값을 숫자로 변환 후 1000으로 나누어서 나머지 값을 검증하는 것이 직관적인 것 같아요

2024-03-18 14:48 UTC, testrace commented on src/main/java/AutoLotto/view/InputView.java
> +        String strippedInput = input.substring(0, input.length() - 3);
3을 왜 빼는지 이해하기 쉽지 않다고 생각해요
로또 한 장의 가격을 상수로 선언하고 이름을 부여한다면 조금 더 이해하기 쉬운 코드가 될 수 있지 않을까요?

구입 금액으로 로또를 몇 장 구매할 수 있을지 계산하는 로직은 view보단 도메인의 로직에 적합할 것 같아요
999원 이하로는 로또를 구매할 수 없다는 단위 테스트도 추가해서 기능을 검증하면 어떨까요?

2024-03-19 14:02 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoGenerator.java
> +    private static List<Integer> randomNumbers = new ArrayList<>();
피드백 감사합니다. 이 부분은 제가 다시 Commit을 했을때 의도하신 부분과 맞게 수정이 됐을지 한번 부탁드리겠습니다.

2024-03-19 14:30 UTC, astrid-dm commented on src/main/java/AutoLotto/model/Lottos.java
> +    private List<List<Integer>> lottos = new ArrayList<>();
피드백 감사합니다. 결론적으로 `List<Lotto> lottos`로 개선을 진행하는데, 이 부분은 의도하신 부분과 방향이 같을지 커밋 이후 검토 부탁드리겠습니다.

2024-03-19 14:52 UTC, astrid-dm commented on src/main/java/AutoLotto/view/InputView.java
> +        return input.endsWith("000") && input.length() >= 4;
제가 작성했던 방법도 무난해 보이는데, 제안하신 방법도 괜찮아 보이네요. 개선하도록 하겠습니다.

2024-03-21 11:21 UTC, testrace requested changes
안녕하세요 다미님 😃 
2단계 구현 쉽지 않으셨을텐데 잘 구현해 주셨네요
코멘트를 좀 남겨두었는데요 코멘트가 달린 코드 뿐만 아니라 모든 코드에 적용할 수 없는지 전체적으로 검토하시면 좋을 것 같아요
확인해 주시고 다시 리뷰 요청 부탁드려요

2024-03-21 11:21 UTC, testrace commented on src/main/java/AutoLotto/model/LottoProfitChecker.java
> +        }
전체 당첨 금액을 구하기 위해 왜 start_index, end_length가 사용되었는지 알기 어렵네요
상수로 선언하신 1, 4는 어떤 의미인가요?

2024-03-21 11:21 UTC, testrace commented on src/main/java/AutoLotto/model/LottoWinChecker.java
> +    private static final int VALID_WIN_NUMBERS_LENGTH = 6;
동일한 의미의 상수가 여러 곳에 선언되어 있네요
그만큼 로또 번호의 범위, 로또가 가져야할 로또 번호의 개수에 대한 책임이 흩어져 있습니다
높은 응집도를 위해 책임을 한 곳으로 모아보시면 좋을 것 같아요

2024-03-21 11:21 UTC, testrace commented on src/main/java/AutoLotto/model/LottoWinChecker.java
> +    public LottoWinChecker(String winNumbersInString, List<Lotto> lottos) {
당첨번호 6개도 결국 로또 번호 6개로 이루어져 있는데요
그렇다면 로또나 당첨 번호나 동일한 제약을 가지지 않을까요?
view에서 입력 받은 String을 그대로 활용하기 보다 도메인 객체를 활용하시면 어떨까요?

2024-03-21 11:21 UTC, testrace commented on src/main/java/AutoLotto/model/LottoWinChecker.java
> +    }
도메인 객체가 콤마로 분리해야한다는 사실을 알고 있다는 것은 view에 의존하고 있다는 것과 동일합니다
MVC 패턴을 적용했으니 view 계층과 도메인 계층을 분리했으니 
입력을 콤마로 구분할지 탭문자로 구분할지 세미콜론으로 구분할지 도메인이 알고 있을 필요가 없을 것 같아요

2024-03-21 11:21 UTC, testrace commented on src/main/java/AutoLotto/model/PrizeResultEnum.java
> +    private int index;
enum에 index 값을 추가하셨군요
index 대신 번호 일치 개수를 상태로 가지면 어떨까요?
`THREE_MATCHED(3, 5000L)`

index는 임의로 지정한 값이기에 내림차순으로 작성했다면 SIX_MATCHED가 1index를 가질 수 있습니다
혹여나 중간에 index 값이 바뀐다면 index로 접근하는 모든 코드를 수정해야하구요
이러한 혼동이 생길 여지를 남기는 것 보다 일치 개수를 상태로 가진다면 외부에서 index에 의존하지 않고 enum 객체를 활용할 수 있을 것 같아요

2024-03-21 11:21 UTC, testrace commented on src/test/java/autoLotto/model/LottoProfitCheckerTest.java
> +        assertThat(profit).isEqualTo(ALL_WIN_PRIZES / PURCHASE_AMOUNT_FLOAT);
displayname, 검증 코드가 일치하지 않네요
객체 성공을 테스트하고 싶으셨던 걸까요 예상한 당첨률이 나오길 기대하셨던걸까요
혹은 객체 성공 자체가 당첨률을 정상적으로 계산하는거라고 봐야하는 걸까요
설명이 필요한 테스트보다 설명 없이 코드만으로 쉽게 이해할 수 있는 테스트를 고민해 보시면 좋겠습니다

2024-03-21 15:06 UTC, astrid-dm commented on src/main/java/AutoLotto/model/Lotto.java
> +    private int[] lotto;
로또의 사이즈가 (이번 과제에서는) 고정되어있다보니 `int[]`로 선언했는데, 
선언하면서도 이게 좋은 방법일지 고민을 했습니다. 현업에서도 `int[]`는 본적이 없었거든요 😅
피드백 감사합니다. `int[]`는 모두 `List<Integer>`로 변경하겠습니다.
(단, inputView에서 검증하는 로직에 사용된 int[]는 그냥 두도록 하겠습니다.)

2024-03-21 15:15 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoWinChecker.java
> +    private static final int VALID_WIN_NUMBERS_LENGTH = 6;
의견 감사합니다. 
공용적으로 곳곳에 사용되는 상수들은 pubic class로 선언된 `LottoConstants`안에 public static final로 재선언 했습니다.

2024-03-21 15:30 UTC, astrid-dm commented on src/main/java/AutoLotto/model/Lotto.java
> +        }
피드백 감사합니다. 
아래와 같이 각 메서드별로 검증 로직을 분리했습니다.
`isNotDuplicated()`가 중복된 숫자가 있는지를 체크하는 메서드 입니다.

``` java
    public Lotto(List<Integer> lotto) {
        if (!isValidLottoSize(lotto) || isNotDuplicatedNumbers(lotto) || !isValidLottoNumbers(lotto)) {
            throw new IllegalArgumentException(INVALID_LOTTO_NUMBERS);
        }
        this.lotto = lotto;
    }
```

2024-03-21 15:36 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoGenerator.java
> +        for (int i = MIN_NUMBER, j = 0; i <= MAX_NUMBER; i++, j++) {
말씀주신 내용은 위의 상수 관리 클래스와 연관이 있어 보입니다.
상수가 모인 클래스에서 로또의 번호 범위를 관리하도록 로직을 개선했습니다.
피드백 감사합니다!

2024-03-21 15:48 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoMachine.java
> +    }
피드백 감사합니다! `retrieveLotto()`는 제거 완료했습니다.

2024-03-21 15:53 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoProfitChecker.java
> +    }
1. 우선 생성자에서는 비즈니스 로직이 수행되지 않도록 개선하겠습니다.
2. 결론적으로 `LottoProfitChecker`의 `profit`에는 당첨 결과에 따른 총 당첨금액을, 
동시에 `LottoProfitChecker`에서는 로또 구매 금액 대비 실제 수익률을 제공하는 `calculateProfitRation()` 메서드를 생성하도록 하겠습니다.

피드백 감사합니다!

2024-03-21 16:20 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoProfitChecker.java
> +        }
`List<Integer> winLottos`에서 0번째 인덱스는 당첨금액이 없음을 뜻하고,
1번째는 3개 일치
2번째는 4개 일치
...
4번째는 6개 일치로 구성을 했습니다. (`PrizeResultEnum` 참고)

0~2개가 일치하는 경우에는 사실상 상금이 0원이기에, 
0~2개의 당첨개수까지 각각 따로 저장할 필요가 없다고 생각해 모두 0번째 인덱스에 저장하는것을 고려하여 위와 같은 로직이 나왔습니다.

아래 `PrizeResultEnum`의 피드백과 함께 고려해서
3개가 일치하는 경우 1번째 index가 아닌  3번째 index에 저장되도록 로직을 개선하겠습니다.
이 경우에 0,1,2번째 인덱스는 사실상 저장만 하고 실제로는 쓰는 값은 없게되지만, 
해당 프로젝트를 잘 모르는 사람이 보기에는 기존 로직보다는 이해하기 나은 방식인것 같네요.

2024-03-21 16:34 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoWinChecker.java
> +    public LottoWinChecker(String winNumbersInString, List<Lotto> lottos) {
음.. 그렇다면 `Lotto` 객체를 `LottoProfitChecker`에서 활용하라는걸로 이해했는데요, 제안주신 피드백으로 반영하겠습니다.

2024-03-21 16:52 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoWinChecker.java
> +    }
피드백 감사합니다. 해당 내용은 바로 위의 내용을 수정하면서 제거됐습니다.

2024-03-22 09:33 UTC, testrace approved these changes
안녕하세요 다미님 😃 
피드백 반영 잘해주셨네요 👍 
코멘트를 좀 남겨두었는데요 확인해 주시고 다음 단계에서 함께 반영 부탁드려요

2024-03-22 09:33 UTC, testrace commented on src/main/java/AutoLotto/model/PrizeResultEnum.java
>      private int index;
변수의 용도가 변경되었으니 이름도 변경하면 어떨까요?
matchedCount 등으로 표현할 수 있을 것 같아요

2024-03-22 09:33 UTC, testrace commented on src/main/java/AutoLotto/model/PrizeResultEnum.java
>      private String description;
description 은 출력의 포맷을 그대로 가지고 있는데요
출력 포맷은 view의 책임으로 이동하고 도메인 객체는 기능에 중점을 두면 어떨까요?

2024-03-22 09:33 UTC, testrace commented on src/main/java/AutoLotto/model/RandomLottoGeneratorStrategy.java
> +        return lotto.subList(0, 6);
subList 👍

2024-03-22 09:33 UTC, testrace commented on src/main/java/AutoLotto/view/ResultView.java
> +    }
메서드 호출부에서는 리턴 값을 활용하는 곳이 없네요 👀 
제거하면 어떨까요?

2024-03-22 09:33 UTC, testrace commented on src/main/java/AutoLotto/view/ResultView.java
> +        }
당첨이 없다면 결과가 나오지 않도록 해주셨군요 😃

2024-03-22 09:33 UTC, testrace commented on src/main/java/AutoLotto/view/InputView.java
> +        if (values.length != VALID_LOTTO_LENGTH) {
무엇이 잘못된 걸까요? 🤔 
<img width="297" alt="image" src="https://github.com/next-step/java-lotto/assets/8064743/543e55a0-ad1d-4d4d-89e2-e4407bd8c9fe">

2024-03-22 09:33 UTC, testrace commented on src/test/java/autoLotto/model/LottoProfitCheckerTest.java
> +        float profit = lottoProfitChecker.getProfitRatio(PURCHASE_AMOUNT_STRING);
테스트 코드가 변경되었으니 DisplayName의 내용도 테스트의 의도를 파악할 수 있게 변경하면 어떨까요?
더 이상 객체 생성을 검증하는 테스트는 아닌 것 같아요

2024-03-22 09:33 UTC, merged

2024-03-23 02:46 UTC, astrid-dm commented on src/main/java/AutoLotto/view/InputView.java
> +        if (values.length != VALID_LOTTO_LENGTH) {
공백(= 스페이스바)없이 쉼표와 6개의 숫자만을 입력해야하는데,
디테일한 노티가 없다보니 실제 사용자였다면 이게 뭘까 싶었을것 같네요 😬
좀더 디테일한 안내사항을 기입하도록 하겠습니다!

2024-03-23 02:49 UTC, astrid-dm commented on src/main/java/AutoLotto/view/ResultView.java
> +        }
문제에 당첨금액이 없을 경우에 대해 제약이 없어서 아무런 문구를 출력하지 않았는데,
당첨금액이 없다는 확인사살 문구를 남겨줘도 괜찮을것같네요 ㅎㅎ

2024-03-23 03:33 UTC, astrid-dm commented on src/main/java/AutoLotto/model/Lotto.java
> +        this.lotto = parseLottoNumbers(lotto);
좋은 피드백 감사합니다. 
이번 기회에 정적 팩토리 메서드를 제대로 익히고 활용하도록 하겠습니다.

2024-03-23 03:37 UTC, astrid-dm commented on src/main/java/AutoLotto/model/Lotto.java
> +        return numbers.stream().distinct().count() == winNumbers.size();
``` java 
public class Lotto {
    private List<Integer> lotto;
```

기존의 위와 같았던 `List<Integer>`을 `Set<Integer>`로 활용해도 괜찮을것같다는 말씀으로 이해했는데, 맞으실까요?
사실 로또의 값 자체가 중복된 값이 없는 숫자들로 이루어져있다보니, 말씀주신대로 `Set<Integer>`로 선언해도 좋을것 같습니다. 한번 시도해볼게요~

그리고 언급주신대로 `winNumbers`대신 보다 명시적인 변수명으로 변경하도록 하겠습니다.

2024-03-23 05:08 UTC, astrid-dm commented on src/main/java/AutoLotto/model/Lotto.java
>      }
``` java
public class Lotto {
    private Set<LottoNumber> lotto;
```
요렇게 개선을 진행해보겠습니다!

2024-03-23 07:24 UTC, astrid-dm commented on src/main/java/AutoLotto/model/LottoProfitChecker.java
> +    public float getProfitRatio(String purchaseAmount) {
놓쳤던 부분인데, 좋은 피드백 감사합니다 👍 
아래와 같이 초기 실행 메서드인 `run()`에서 구입가격인 `purchaseAmount`를 Long으로 받도록 로직 수정하겠습니다.

``` java
    public void run() {
        Long purchaseAmount = Long.valueOf(inputView.inputPurchase());
        // ...  생략
```

2024-03-23 08:11 UTC, astrid-dm commented on src/main/java/AutoLotto/model/PrizeResultEnum.java
>      private String description;
말씀주신 방법도 좋아보입니다. 반영하도록 하겠습니다~

2024-03-23 08:17 UTC, astrid-dm commented on src/main/java/AutoLotto/view/ResultView.java
> +    }
헛.. 중요한 출력 부분을 활용 못하고 있었네요. 피드백 감사합니다!