2단계 - 로또(자동)
next-step/java-lotto pull request #3601
Opened 2024-03-18 05:54 UTC by sm9171

규남님 안녕하세요. 2번째 미션 구현했습니다.
레이싱 미션이랑 비교해서 도메인 복잡도가 높아진거 같아서 도메인 분리에 애를 먹었네요... 어찌어찌 구현은 했지만 뭔가 깔끔하게 분리가 되지 않은것 같습니다.

2024-03-18 13:38 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/domain/AmountEnum.java
> +	public abstract Integer getAmount();
collectedCount와 다르게 당첨 금액을 abstract method로 구현해야 하는 이유가 있을까요?

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/domain/AmountEnum.java
> +		throw new IllegalArgumentException("당첨 개수가 아닙니다.");
중요한 부분은 아니지만 이런 경우 어떤 count 값이 들어왔는지 정도를 기록해주시면 좋을 것 같네요.

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/domain/Number.java
> +public class Number {
Number는 너무 포괄적인 이름으로 보여요. 1 - 45까지의 숫자를 표현하기 위함이라면 `LottoNumber`와 같은 이름은 어떨까요?

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/domain/Seller.java
> +    public Integer getBuyLottoNumber(final int amount) {
Seller라는 이름이 적절할지, 이렇게 적은 책임을 가진 클래스가 존재해야 할지에 대해 고민해보시면 좋을 것 같습니다.

단순히 금액 대비 몇장의 로또를 살 수 있을지 계산하는 역할로 보이는데요.

MyLottos의 정적 팩터리 등으로 책임을 분리해볼 수 있지 않을까 하는 생각이 드네요.

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/view/OutputView.java
> +		System.out.println("6개 일치 (2000000000원)- " + hashMap.get(6) + "개");
이부분의 출력이 하드코딩 형태로 되어있네요. enum을 만든 김에 enum에 포함된 데이터를 활용하면 어떨까요?

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/domain/Lotto.java
> +    private static void validateDuplicateNumber(List<Number> newNumbers, Number newNumber) {
메서드 이름은 validate인데 단순히 검증하는게 아니라 `List` 컬렉션 내부에 요소를 추가하거나 검증하는 등 복잡한 연산을 수행하고 있는 것으로 보여요. 메서드 이름이 적절한지 한번 체크해보시면 좋겠습니다.

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/domain/Lotto.java
> +    private static void validateDuplicateNumber(List<Number> newNumbers, Number newNumber) {
중복 제거를 위해 `Set` 자료구조를 사용해볼 수 있을까요?

순서를 보장하기 위함이라면 조회할 때 정렬한 뒤 `List`로 변환해서 내려주거나 다양한 방법을 사용해볼 수 있습니다.

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/domain/Lotto.java
> +        validateDuplicateNumber(newNumbers, newNumber);
랜덤으로 뽑는 경우 가장 번거로운 처리가 중복 처리일 것 같은데요.

로또에서 뽑는 숫자는 정해져 있으므로 정해진 숫자를 Collections.shuffle로 섞고 subList로 뽑아오는 방법도 고려해볼 수 있을 것 같네요.

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/domain/Lotto.java
> +    }
사용처에서 결국 int 값을 받아 AmountEnum으로 변환해야 등수나 그에 따른 당첨 금액을 알 수 있을 것 같은데요.

개수가 아닌 enum을 반환해 로또의 등수를 바로 표현하는건 어떨까요? enum과 결합이 생기지만 Enum의 경우 복잡한 비즈니스 로직이 많이 들어가지 않으므로 결합이 생겨도 크게 문제가 없는 경우가 많습니다.

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/view/OutputView.java
> +			findWinner(count, hashMap);
이 부분은 비즈니스 로직으로 보여요. view가 아닌 도메인 클래스로 옮기면 좋겠습니다.

2024-03-18 13:38 UTC, kyucumber commented on src/main/java/lotto/view/OutputView.java
> +	public Map<Integer, Integer> printWinnersStatistics(final String winNumber, final MyLottos myLottos) {
winNumber도 Lotto와 동일한 특성(1 - 45, 6개, 중복 안됨 등)을 가질 것 같아요. winNumber String이 아닌 Lotto 클래스를 사용해보면 어떨까요?

2024-03-19 02:01 UTC, sm9171 commented on src/main/java/lotto/domain/AmountEnum.java
> +	public abstract Integer getAmount();
당첨금액이 주입받는  collectedCount 별로 달라지기 때문에 추상화 메소드를 사용했습니다!

2024-03-19 02:37 UTC, sm9171 commented on src/main/java/lotto/domain/Number.java
> +public class Number {
네 LottoNumber가 더 명시적인거 같아요 ㅎㅎ

2024-03-19 04:28 UTC, sm9171 commented on src/main/java/lotto/domain/Seller.java
> +    public Integer getBuyLottoNumber(final int amount) {
처음에 tdd로 구현했을때 무작정 클래스와 메서드를 생성하여 만들다 보니까 책임이 적네요 ㅎㅎ.. MyLottos의 정적 팩터리안으로 넣어도 괜찮을것 같습니다!

2024-03-19 05:24 UTC, sm9171 commented on src/main/java/lotto/view/OutputView.java
> +		System.out.println("6개 일치 (2000000000원)- " + hashMap.get(6) + "개");
당첨금은 enum으로 바꾸고 void 메소드로 분리해서 중복도 제거하였습니다.

2024-03-19 05:28 UTC, sm9171 commented
안녕하세요 규남님~! 생각보다 꼼꼼한 피드백을 주셔서 감사합니다.
덕분에 코드가 훨씬 깔끔해진것 같아요.

2024-03-19 05:42 UTC, sm9171 commented on src/main/java/lotto/domain/Lotto.java
> +    private static void validateDuplicateNumber(List<Number> newNumbers, Number newNumber) {
규남님 말씀대로 검증뿐만 아니라 생성의 두 가지 기능이 들어가 있는것 같아서 메소드를 분리하여 재정립 했습니다!

2024-03-19 06:20 UTC, sm9171 commented on src/main/java/lotto/domain/Lotto.java
> +    private static void validateDuplicateNumber(List<Number> newNumbers, Number newNumber) {
`Set` 타입으로 변경하니 한결 깔끔해졌네요!

2024-03-19 06:56 UTC, sm9171 commented on src/main/java/lotto/domain/Lotto.java
> +        validateDuplicateNumber(newNumbers, newNumber);
자료구조를 Set으로 바꿔서 size가 6이 될때 까지 뽑도록 구현해보았습니다.
```java
    private static Set<LottoNumber> createLottoNumbers() {
        Set<LottoNumber> newLottoNumbers = new HashSet<>();
        while (newLottoNumbers.size() < 6) {
            addLottoNumber(newLottoNumbers);
        }
        return newLottoNumbers;
    }

    private static void addLottoNumber(Set<LottoNumber> lottoNumbers) {
        LottoNumber newLottoNumber = new LottoNumber(RANDOM.nextInt(RANDOM_BOUND_NUMBER) + 1);
        lottoNumbers.add(newLottoNumber);
    }
```

2024-03-19 08:14 UTC, sm9171 commented on src/main/java/lotto/view/OutputView.java
> +			findWinner(count, hashMap);
네 도메인 클래스로 옮겨 보았습니당!

2024-03-19 08:54 UTC, sm9171 commented on src/main/java/lotto/domain/Lotto.java
> +    }
이 부분을 고민하다가 AmountEnum 객체로 반환 받아서 Map에 카운트 하는식으로 구성을 했는데 이렇게 구현해도 괜찮을까요?

2024-03-19 09:46 UTC, sm9171 commented on src/main/java/lotto/view/OutputView.java
> +	public Map<Integer, Integer> printWinnersStatistics(final String winNumber, final MyLottos myLottos) {
우승번호가 들어올 때도 중복체크하는 로직으로 구현했습니다

2024-03-19 09:58 UTC, sm9171 commented on src/main/java/lotto/domain/AmountEnum.java
> +	}
기존에는 값이 없을때 예외처리를 했는데 숫자 맞는 갯수가 4,5,6이 아니면 예외처리가 나더라구요. 그래서 OTHER이라는 enum필드를 하나 더 추가해서 나머지는 OTHER로 반환하게 했는데 더 좋은 방법이 있을까요??

2024-03-19 10:00 UTC, sm9171 commented on src/main/java/lotto/domain/MyLottos.java
> +        return hashMap;
이 부분도 hashMap으로 사용해서 구현했는데 더 좋은 방법이 있을까요?

2024-03-19 10:24 UTC, kyucumber commented on src/main/java/lotto/domain/AmountEnum.java
> +	public abstract Integer getAmount();
이미 Enum 자체가 분리되어 있고 collectedCount도 정해진 상황이라 아래처럼 구현해도 될 것 같았어요. 

```
FIRST(6, 2000000000),
SECOND(5, 1500000)
```

혹시 제가 놓친 부분이 있다면 코멘트 부탁드립니다!

2024-03-19 10:26 UTC, kyucumber commented on src/main/java/lotto/domain/AmountEnum.java
> +	}
OTHER을 당첨되지 않은 케이스로 보고 집계하지 않으면 될 것 같아서 현재 요구사항 기준으로 좋은 방법으로 보여요.

2024-03-19 10:33 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드려요.

2024-03-19 10:33 UTC, kyucumber commented on src/main/java/lotto/domain/MyLottos.java
> +        return hashMap;
가독성이 높아진다고 표현할 수 있을진 모르겠지만 groupingBy와 Function.identity 키워드로 검색해보시면 `List` 타입을 한번에  `Map<AmountEnum, Long>` 형태로 추출해보실 수 있을 것 같네요. 한번 시도해보시겠어요?

스트림이 익숙한 사람을 기준으로는 훨씬 가독성이 좋아질 것 같아요.

2024-03-19 10:33 UTC, kyucumber commented on src/main/java/lotto/domain/MyLottos.java
> +        Map<Integer, Integer> hashMap = new HashMap<>();
Map의 제네릭 타입을 명시하는게 어떨까요?

2024-03-19 10:33 UTC, kyucumber commented on src/main/java/lotto/domain/MyLottos.java
> +        Map<Integer, Integer> hashMap = new HashMap<>();
`Map<AmountEnum, Long>` 과 같은 타입을 사용하면 어떨까요?

2024-03-19 10:33 UTC, kyucumber commented on src/main/java/lotto/domain/Lotto.java
> +    }
네 기존에 제가 코멘트에서 의도했던 방향과 동일합니다.

2024-03-19 10:33 UTC, kyucumber commented on src/main/java/lotto/domain/Lotto.java
> +        splitNumbers.forEach(number -> this.lottoNumbers.add(new LottoNumber(Integer.parseInt(number))));
map으로 바꿔서 lottoNumbers에 바로 할당하는건 어떨까요?

2024-03-19 10:33 UTC, kyucumber commented on src/main/java/lotto/domain/MyLottos.java
> +        }
Stream.generate와 같은 메서드를 사용해보아도 괜찮을 것 같네요.

2024-03-19 10:33 UTC, kyucumber commented on src/main/java/lotto/view/OutputView.java
> +		}
Map의 키로 0이 들어간 부분은 제거해도 괜찮을 것 같아요. 
이후 Map의 entry를 순회하도록 해서 처리할 수 있을까요?

3, 6 매직 넘버를 코드에서 제거해보면 좋겠습니다.

2024-03-19 11:24 UTC, sm9171 commented on src/main/java/lotto/domain/AmountEnum.java
> +	public abstract Integer getAmount();
고정된 상수값이라서 이렇게 구현하는게 깔끔하게 좋겠네요 ㅎㅎ

2024-03-19 11:51 UTC, sm9171 commented on src/main/java/lotto/domain/MyLottos.java
> +        Map<Integer, Integer> hashMap = new HashMap<>();
타입 명시를 빼먹었었네요.. 허허

2024-03-19 11:53 UTC, sm9171 commented on src/main/java/lotto/domain/MyLottos.java
> +        Map<Integer, Integer> hashMap = new HashMap<>();
Integer보다 AmountEnum이 더 파악하기 쉽겠네요.

2024-03-19 14:31 UTC, sm9171 commented on src/main/java/lotto/domain/MyLottos.java
> +        return hashMap;
네 훨씬 간결해진것 같습니다!

2024-03-19 14:48 UTC, sm9171 commented on src/main/java/lotto/domain/Lotto.java
> +        splitNumbers.forEach(number -> this.lottoNumbers.add(new LottoNumber(Integer.parseInt(number))));
네 map으로 바꿔서 바로 할당되도록 하였습니다!

2024-03-20 00:26 UTC, sm9171 commented on src/main/java/lotto/domain/MyLottos.java
> +        }
arrayList를 선언안하고 이런식으로 사용할 수 있군요!

2024-03-20 00:40 UTC, sm9171 commented on src/main/java/lotto/view/OutputView.java
> +		}
맞힌 갯수를 가지고 Map의 key값을 넣어서 Map의 entry를 순회하면 count가 0인 금액은 map에 안들어있어서 노출이 되지 않아요. 어쩔 수 없이 3에서 6까지 roop문을 이용해야될 것 같습니다. 혹시 다른방법이 있으시면 알려주시면 감사하겠습니다!

```java
public Map<AmountEnum, Long> findWinner(final Lotto winLotto) {
		return lottos.stream()
				.collect(Collectors.groupingBy(
						lotto -> lotto.getAmountEnumCompareWinNumber(winLotto)
						, counting()));
	}
```

2024-03-20 00:43 UTC, sm9171 commented
안녕하세요 규남님 이번 과정을 통해서 Stream을 원없이 사용하고 있는거 같아서 뿌듯합니다 ㅎㅎ 주신 피드백 중에 몇몇군데는 작업을 못해서 답글 달아놨는데 확인해주시면 감사하겠습니다!

2024-03-20 09:11 UTC, kyucumber commented on src/main/java/lotto/view/OutputView.java
> +		}
Map에 초기 값을 넣는 것도 방법일 것 같네요. 크게 다르진 않아서 지금처럼 구현하셔도 무방할 것 같습니다.

2024-03-20 09:11 UTC, kyucumber approved these changes
간단한 코멘트 남겨두었으니 참고 부탁드려요.

다음 단계 진행을 위해 머지할게요.

2024-03-20 09:12 UTC, merged