Step1  기능을 구현했습니다.
next-step/java-lotto pull request #3606
Opened 2024-03-18 11:44 UTC by yuus95

## 작업 내용
- 사칙연산 구현

## 회고
프로젝트가 커질수록 많아지는 클래스를 어떻게 관리할까? 라는 생각이 들었습니다!
그리고 조금씩 책임을 각자가 갖도록 노력하는게 보여져 뿌듯..? 한 1단계 미션이였습니당

2024-03-18 14:06 UTC, kyucumber requested changes
문자열 계산기 잘 구현해주셨네요. 👍 

간단한 코멘트 하나 남겨두었으니 참고 부탁드립니다.

남겨둔 코멘트는 반영하셔도 되고 안하셔도 되는데요 확인하신 뒤 리뷰 요청 주시면 머지하도록 하겠습니다.

2024-03-19 09:34 UTC, yuus95 commented on src/main/java/operations/CalculateStrategy.java
> +}
인터페이스로 구현했을 때 생각못했던 단점이 있었네요.!
해당방식으로 구현하여 다시 리뷰요청해보겠습니다!

2024-03-19 10:12 UTC, yuus95 commented
리뷰해주셔서 감사합니다!
말씀해주신 방식대로 한번 더 수정해봤습니다! 

한눈에 볼 수 있었서 좋겠지만, 하나의 ENUM에서 관리한다면 
코드가 길어질 경우 가독성이 안좋을 것 같은데 보통 
복잡한 비즈니스 로직일 경우에는 클래스로 분리할까요??

2024-03-19 10:23 UTC, kyucumber approved these changes
기존 피드백 잘 반영해주셨네요.

남겨두신 질문에 답변 남겨두었으니 확인 부탁드리겠습니다.

다음 단계 진행을 위해 머지할게요.

2024-03-19 10:23 UTC, kyucumber commented on src/main/java/operations/enums/OperationEnum.java
> +    MULTIPLICATION("*", (a, b) -> a * b);
자바 8의 스트림 등 여러 기능들이 익숙하지 않으신 분들도 있어서 다른 방향으로 한번 더 구현해보시면 어떨까 하고 코멘트를 남겨드렸었는데요, 깔끔하게 잘 구현해주셨네요 👍 

> 하나의 ENUM에서 관리한다면 코드가 길어질 경우 가독성이 안좋을 것 같은데
> 보통 복잡한 비즈니스 로직일 경우에는 클래스로 분리할까요??

이런 단순한 연산자나 덧셈 뺄셈 나눗셈 등의 비교적 간단한 연산은 함수형 인터페이스나 lambda로 깔끔하게 처리가 가능해서 이번 방법이 나쁘지 않았겠지만 복잡한 비즈니스 로직인 경우는 기존에 구현하셨던 방법대로 하는게 더 좋을 것 같습니다.

한눈에 구현체가 잘 들어오지 않는 단점은 사실 패키지 분리나 IDE의 기능을 활용하면 큰 문제는 되지 않을 것 같고, OperationStrategies에 구현체 추가가 누락되면 문제가 발생하는 케이스는 테스트 등에서 추가된 로직의 구현이 누락되진 않았는지를 테스트하는 부분이 추가되면 되지 않을까 싶습니다.

2024-03-19 10:23 UTC, merged

2024-03-19 12:30 UTC, yuus95 commented on src/main/java/operations/enums/OperationEnum.java
> +    MULTIPLICATION("*", (a, b) -> a * b);
아하 그렇군요!
상황마다 다르겠지만, 비교적 간단하다면 한눈에 보이도록 설계 하는방법도 좋은 것 같습니다. 
참고해서 실제 현업에서도 사용해보겠습니다 감사합니다!!