🚀 1단계 - 문자열 계산기
next-step/java-lotto pull request #3616
Opened 2024-03-19 07:18 UTC by 026854

로또1단계 PR 요청드립니다!
잘 부탁드립니다!

2024-03-20 10:37 UTC, testrace requested changes
안녕하세요 지은님 😃 
로또 미션을 함께 하게 된 송용주입니다. 잘 부탁드려요!
다음 단계에서 패키지가 중복될 것 같아 정리하고 진행하면 좋을 것 같아요
몇 가지 코멘트 남겨두었으니 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-03-21 04:31 UTC, 026854 commented on LOTTO_TODO.md
리뷰어님! 꼼꼼하게 봐주셔서 감사합니다!
step2를 진행한게 있어서 기존 패키지를 그대로 두고 calculator패키지를 새로 구성하였습니다. :)

2024-03-21 11:53 UTC, testrace approved these changes
안녕하세요 지은님 😃 
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겼는데 확인 부탁드려요
본격적인 로또 미션 화이팅입니다 🔥

2024-03-21 11:53 UTC, testrace commented on src/main/java/calculator/util/CalcuOperater.java
> +public enum CalcuOperater {
클래스명, 변수명 등은 축약하지 않고 네이밍하면 어떨까요?

2024-03-21 11:53 UTC, testrace commented on src/main/java/calculator/util/CalcuOperater.java
> +                return op;
>indent(들여쓰기) depth를 2단계에서 1단계로 줄여라.
depth의 경우 if문을 사용하는 경우 1단계의 depth가 증가한다. if문 안에 while문을 사용한다면 depth가 2단계가 된다.

indent 요구사항도 지켜주시면 좋을 것 같아요

2024-03-21 11:53 UTC, testrace commented on src/main/java/comm/view/InputView.java
> +package comm.view;
여기도 축약이네요

2024-03-21 11:53 UTC, testrace commented on src/main/java/calculator/util/CalcuOperater.java
> +import java.util.function.IntFunction;
사용하지 않는 코드는 제거해 주세요

2024-03-21 11:53 UTC, merged