2단계 - 로또(자동)
next-step/java-lotto pull request #3620
Opened 2024-03-19 14:22 UTC by oht1221

안녕하세요 세윤님! 2 단계 로또(자동) 리뷰 요청드립니다 :)

2024-03-20 09:50 UTC, ksy90101 requested changes
로또 미션까지 오셨군요!
간단한 피드백을 남겼으니 확인부탁드려요~
언제든 질문이 있다면 DM주세요!

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/Amount.java
> +  private final Currency currency;
https://docs.oracle.com/javase/8/docs/api/java/util/Currency.html
Java에 이미 이런 클래스가 있는데요. 이런 클래스를 사용해볼수 있지 않을까요?

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/Lotteries.java
> +    @Override
```suggestion
    private int cursor = 0;
    
    @Override
```

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/Lottery.java
> +  private final LotteryNumbers numbers;
(개인적인 의견)
우리는 Lotto의 숫자를 Ball이라는 단어로 LottoBall이라고 부르는거 같아요;.
도메인 관점에서도 도메인과 맞는 단어를 쓰는게 좋을거라고 생각을 하는데 혹시 LottoBall이라는 단어를 쓰는거에 대해서 어떻게 생각하시는지 궁금합니다~

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/LotteryFactory.java
> +public class LotteryFactory {
이건 어떤 일을 하는걸까요?

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/LotteryNumbers.java
> +//    }
주석은 제거하는게 좋을거 같습니다!

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/LotteryNumbers.java
> +    return new LotteryNumbers(Arrays.stream(numbers).mapToObj(LotteryNumber::of).collect(Collectors.toList()));
한줄의 점 하나씪을 작성해서, 훨씬 가독성을 좋게 하면 어떨까요?

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/PositiveNumber.java
> +public final class PositiveNumber {
사실 이 VO가 있어야 하나? 라는 생각이 들어요.
혹시라도 양수가 아니라 음수까지 받아야 하는 숫자가 있어야 한다. 라고 하면 또 Number라는 걸 만들어야 하는거 같아요.

VO도 도메인 관점에서 생각해보면 좋은데, 지금처럼 Amount, LottoNumber 이 두가지가 그냥 한번더 감싸지 않고 int number를 가지고 있는건 어떤지 궁금하비다 ㅎㅎ

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/Prize.java
> +    return Arrays.stream(values()).filter(prize -> prize.result.equals(result)).findFirst().orElse(Prize.NONE);
여기도 한줄의 점 하나씩으로 하면 좋을거 같아요.
아울러 prize.result.equals(result) 이부분을 객체에게 메시지를 던져서 해보면 어떨까요?

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/domain/Results.java
> +              return acc;
이런부분들은 메서드를 분리해서 해도 좋았을꺼 가탕요.
(가독성 측면 및 SRP관점에서.)

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/factory/RandomFactory.java
> +  private static Random random = new Random();
final을 붙여두는게 어떨까요?

2024-03-20 09:50 UTC, ksy90101 commented on src/main/java/factory/RandomFactory.java
> +  }
매번 인스턴스를 만드는것보다 캐싱을 해두면 어떨까요?
https://steadyjay.tistory.com/15
이글을 한번 참고해보면 어떨까요?

2024-03-20 11:05 UTC, oht1221 commented on src/main/java/domain/PositiveNumber.java
> +public final class PositiveNumber {
아 네, 사실 저도 좀 억지스러운 클래스 분리라고 생각은 했습니다 ㅎㅎ 그냥 최대한 모든 원시값을 포장한다는 생각으로 만든 클래스라고 생각해주시면 될 것 같습니다. 사실 저도 매번 `PositiveNumber`로 감싸서 넘기는게 귀찮고 불편하긴 했습니다 ㅠㅠ 



> VO도 도메인 관점에서 생각해보면 좋은데, 지금처럼 Amount, LottoNumber 이 두가지가 그냥 한번더 감싸지 않고 int number를 가지고 있는건 어떤지 궁금하비다 ㅎㅎ

사실 이렇게 해도 충분히 괜찮을 것 같습니다!

2024-03-20 11:08 UTC, oht1221 commented on src/main/java/domain/LotteryNumbers.java
> +    return new LotteryNumbers(Arrays.stream(numbers).mapToObj(LotteryNumber::of).collect(Collectors.toList()));
지난번 미션부터 계속 나오는 리뷰인데 아직 습관이 안됐네요 ㅠㅠ 고쳤습니다! 감사합니다 :)

2024-03-20 11:15 UTC, oht1221 commented on src/main/java/domain/Prize.java
> +    return Arrays.stream(values()).filter(prize -> prize.result.equals(result)).findFirst().orElse(Prize.NONE);
습관처럼 객체를 불러내서 비교하는 방식으로 구현했네요 ㅠㅠ 말씀하신대로 Prize 객체에게 물어보는 메서드를 추가했습니다! 리뷰 감사합니다 :)

2024-03-20 11:17 UTC, oht1221 commented on src/main/java/factory/RandomFactory.java
> +  private static Random random = new Random();
`final` 추가하였습니다 :)

2024-03-20 11:17 UTC, oht1221 commented on src/main/java/domain/LotteryNumbers.java
> +//    }
최초 구현한 부분을 참고 삼아 뒀다가 깜박했네요 ㅠㅠ  제거했습니다!

2024-03-20 11:19 UTC, oht1221 commented on src/main/java/domain/LotteryFactory.java
> +public class LotteryFactory {
아마 `factory` 패키지에 있는 `LotteryFactory` 클래스를 처음에 `domain` 패키지에 잘 못 만들고 삭제를 하지 않은 것 같네요 ㅠ 삭제했습니다!

2024-03-20 11:30 UTC, oht1221 commented on src/main/java/domain/Lottery.java
> +  private final LotteryNumbers numbers;
네 이번 미션 이름이 '로또'인 만큼 도메인 단어들을 최대한 실제 Lotto 로 맞추는게 나을 것 같습니다. 관련하여 일괄 수정하였습니다 :)

2024-03-20 14:31 UTC, oht1221 commented on src/main/java/domain/Results.java
> +              return acc;
넵 말씀하신 부분이랑 마지막 combiner부분 까지 메서드로 분리했습니다! 리뷰 감사합니다 :)

2024-03-20 14:34 UTC, oht1221 commented on src/main/java/domain/Amount.java
> +  private final Currency currency;
해당 클래스로 대체하였습니다!  몰랐던 클라스라 메뉴얼 조금 더 읽어보겠습니다 :) 감사합니다!

2024-03-20 14:34 UTC, oht1221 commented on src/main/java/domain/Lotteries.java
> +    @Override
수정하였습니다!  :)

2024-03-20 14:35 UTC, oht1221 commented on src/main/java/factory/RandomFactory.java
> +  }
생각해보니까 로또 100장만 만들어도 객체가 엄청 생기겠네요. 팩토리 메서드를 만들 때에는 항상 캐싱도 고려하겠습니다! 감사합니다 :)

2024-03-21 05:37 UTC, ksy90101 approved these changes
리뷰 반영하시느라고 고생하셨어요~
아직 단계가 많이 있으니 2단게는 마무리 하도록 할게요~
간단한 고민거리 하나 드렸으니 3단계에서 같이 적용고민해보면 좋을거 같습니다!
홧팅입니다!

2024-03-21 05:37 UTC, ksy90101 commented on src/main/java/domain/LottoBalls.java
> +}
EOF~

2024-03-21 05:37 UTC, ksy90101 commented on src/main/java/domain/PositiveNumber.java
> +public final class PositiveNumber {
네네!! 이해했습니다~ 👍

2024-03-21 05:37 UTC, ksy90101 commented on src/main/java/domain/Amount.java
> +  private final PositiveNumber value;
혹시 이런거 한번 고민해보시면 좋을거 같아서요.

> int보다 더 큰값의 가격을 사용자가 입력하면 어떻게 될까요?

2024-03-21 05:37 UTC, merged