3단계 - 로또(2등)
next-step/java-lotto pull request #3654
Opened 2024-03-21 16:36 UTC by oht1221

안녕하세요 세윤님 : ) 3단계 리뷰 요청드립니다!

2024-03-22 12:44 UTC, ksy90101 requested changes
3단계도 너무 잘 해주셨네요!
간단한 피드백을 남겨봤으니 참고해주시면 감사하겠습니ㅏㄷ~
홧팅입니다!

2024-03-22 12:44 UTC, ksy90101 commented on src/main/java/domain/Lotto.java
> +    this.bonusBall = balls.lastBall();
마지막 볼이 보너스 볼이여도 좋지만, 이렇게 하면 혹시라도 실수하면 잘못될거 같은데요.

흐름을 따가라가보면 6개를 먼저 받고, 마지막에 보너스볼을 받을거 같은데 이런 형식으로 로직을 작성해서 안정성을 더 가져가 볼수 있지 않을까요?

2024-03-22 12:44 UTC, ksy90101 commented on src/main/java/domain/Condition.java
> +  }
toString이 이렇게 View와 너무 의존적이면 좋을까요?

https://github.com/Meet-Coder-Study/book-effective-java/blob/main/3%EC%9E%A5/12_toString%EC%9D%84_%ED%95%AD%EC%83%81_%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

한번 이글을 읽어보시면 어떨까요?

2024-03-22 12:44 UTC, ksy90101 commented on src/main/java/domain/PositiveNumber.java
> +  public PositiveNumber sub(int number) {
축약어 보다, 풀 네임을 쓰면 어떨까요?

2024-03-22 12:44 UTC, ksy90101 commented on src/main/java/domain/Prize.java
> +  FIRST(new Condition(6, BonusBallCondition.DONT_CARE), new Amount(PositiveNumber.of(2000000000), Currency.getInstance(Locale.KOREA))),
👍

2024-03-22 12:44 UTC, ksy90101 commented on src/main/java/domain/Result.java
> +    this.bonusBallMatched = bonusBallMatched;
정적팩터리를 쓸꺼면, 생성자를 아예 막아버리면 어떨까요?

2024-03-22 12:44 UTC, ksy90101 commented on src/main/java/domain/Results.java
> +            .filter(prize -> !prize.equals(Prize.NONE))
여기도 모델에 메시지를 던지면 어떨까요?

2024-03-22 12:44 UTC, ksy90101 commented on src/test/java/domain/LottoTest.java
>    void 당첨숫자에_대한_복권_결과() {
MethodSource를 한번 사용해보면 어떨까요?

2024-03-22 12:44 UTC, ksy90101 commented on src/test/java/domain/PrizeTest.java
> +  @MethodSource("generateTestParameters")
👍

2024-03-22 14:24 UTC, oht1221 commented on src/main/java/domain/Condition.java
> +  }
제가 이번 미션에 매몰돼서 너무 View 의존적으로 `toString`에 의존적이게 만들었네요 ㅠㅠ 실제 현장에서 쓰는 코드라면 디버깅과 같은 용도로 사용될 여지가 크기 때문에 해당 객체를 대표할 수 있는 형태로 구현해야할 것 같습니다. 리뷰 감사합니다!

2024-03-22 16:07 UTC, oht1221 commented on src/main/java/domain/PositiveNumber.java
> +  public PositiveNumber sub(int number) {
넵 subtract로 수정하였습니다! :)

2024-03-22 16:07 UTC, oht1221 commented on src/main/java/domain/Result.java
> +    this.bonusBallMatched = bonusBallMatched;
정적 팩터리를 클래스의 생성자 접근 제어자를 private으로 수정하였습니다! :)

2024-03-22 16:17 UTC, oht1221 commented on src/test/java/domain/LottoTest.java
>    void 당첨숫자에_대한_복권_결과() {
넵 `@MethodSource` 사용하여 테스트하도록 변경하였습니다 ~ :)

2024-03-22 16:20 UTC, oht1221 commented on src/main/java/domain/Lotto.java
> +    this.bonusBall = balls.lastBall();
네 저도 사실 약간 구부분 구현하면서 찜찜한 구석이 있었습니다. ball 입력 순서는 바뀔 수도 있기도 하고... 말씀해주신대로 입력 받은 ball들을 normal과 bonus로 구분하도록 구조를 개선했습니다 :)

2024-03-22 16:55 UTC, oht1221 commented on src/main/java/domain/Results.java
> +            .filter(prize -> !prize.equals(Prize.NONE))
Prize에게 상금이 있는지 없는지 메세지를 보내서 물어보는 방식으로 변경하였습니다 :) 리뷰 감사합니다!

2024-03-23 05:05 UTC, oht1221 commented on src/main/java/domain/Condition.java
> +  }
toString을 디버깅이나 로깅 용도로 수정하면 결국 ResultView에서 보여줄 문자열은 따로 만들어야할 것 같은데요, 이 문자열 생성은 Domain 객체에 둘 것인지 ResultView에 둘 것인지 어떤게 더 좋을지 좀 고민이 됩니다. 저는 ResultView의 책임이라고 보는데, 그렇게 되면 Domain 객체의 내부를 ResultView에 너무 오픈하게되는게 아닌가 하는 생각이 듭니다! 출력하려면 결국 내부 정보를 getter 형태로 제공해야할 것 같아서요. 그러면 결국 Domain 로직에서 View용 스트링을 제공하는 형태로 구현해야하는 것인가 싶기도 한데... Domain 로직이 실제 로또 로직과는 무관한 부분에 대한 책임을 가져야하는지 하는 고민도 되네요... 혹시 리뷰어님 생각을 여쭤봐도 될까요?

2024-03-23 13:54 UTC, ksy90101 commented on src/main/java/domain/Condition.java
> +  }
이런 경우를 위해 DTO라는 개념이 나오지 않을까요?
View에 필요한 정보는 DTO로 주고, 이와같이 View는 View단에서 하는거죠.
우리가 웹을 할떄도 View에 그려지는건 프론트에서 하는것과 같이 생각해보면 어떨까요?

2024-03-23 14:02 UTC, ksy90101 requested changes
간단한 피드백을 좀 더 남겨봤습니다~
질문이 있다면 언제든 DM주세요!

2024-03-23 14:02 UTC, ksy90101 commented on src/main/java/domain/PositiveNumber.java
> +  }
보다 보니, 이런 부분들이 조금 애매할숴 있어요
불변이라 좋을수 있는데 이렇게 계속 생성하게 되면 인스턴스가 계속 메모리에 쌓이고
성능적으로 그렇게 안좋을수 있을거라고 생각이 들어요 ㅠㅠ

2024-03-23 14:02 UTC, ksy90101 commented on src/main/java/domain/Prize.java
>  public enum Prize {
뭔가.. 1등, 2등과 같이 이 값이 굉장히 중요한거 같은데
실질적으로 당첨이 되는 부분에 대한 테스트가 없어보여요 ㅠㅠ

2024-03-24 02:30 UTC, oht1221 commented on src/main/java/domain/Condition.java
> +  }
아! DTO 개념 활용해서 한 번 작성해겠습니다. 조언 감사드립니다!

2024-03-24 04:22 UTC, oht1221 commented on src/main/java/domain/Amount.java
> +  }
넵 제 생각에도 `isPositive`로 변경하는게 조금 더 정확한 의미일 것 같습니다. 사실 `nonZero` 0이 아니다라는 뜻이라 음수일 가능성도 내포하는 이름 같기도 하네요 ㅠㅠ `isPositive`로 수정하였습니다!

2024-03-24 04:39 UTC, oht1221 commented on src/main/java/domain/Condition.java
> +    return this.bonusBallCondition.equals(BonusBallCondition.TRUE) == result.bonusBallMatched();
네 말씀해주신대로 객체 메서드로 만들어서 물어보는 형식으로 수정하였습니다! 리뷰 감사합니다 :)

2024-03-24 04:49 UTC, oht1221 commented on src/main/java/domain/Condition.java
> +    if (!this.matchCount.equals(result.matchCount())) {
넵 긍정 의미 메서드로 만들고 그에 따라 메서드 구현을 변경하였습니다! 감사합니다 :)

2024-03-24 05:20 UTC, oht1221 commented on src/main/java/domain/Lottery.java
> +              return acc;
아하 그러면 stream 내부에선 최대한 if, for 블럭 같은 부분은 지양하는 것이 맞겠네요! 
처음에 내부 private method로 분리했다가, 분리 하고 나니 조금 다른 방식으로 구조 개선이 가능할 것 같아서 수정해보았습니다. 리뷰 감사합니다!

2024-03-24 05:23 UTC, oht1221 commented on src/main/java/domain/LottoBalls.java
>      return size.equals(this.balls.size());
넵 말씀해주신대로 수정했다가, `Collection`의 size()가 원시값  `int`를  반환해서 `==` 비교로 수정하였습니다! 감사합니다 :)

2024-03-24 05:33 UTC, oht1221 commented on src/main/java/domain/LottoBalls.java
> +    public LottoBall next() {;
수정하였습니다 :)

2024-03-24 05:33 UTC, oht1221 commented on src/main/java/domain/LottoBalls.java
> +    return PositiveNumber.of(this.balls.size());
제가 생각해도 이건 좀 억지스럽다 싶어서... 원시값으로 수정했습니다 ㅠㅠ 자바에서 제공해주는 부분이 아닌 제가 작성한 도메인 로직에서 양수임이 보장돼야함을 꼭 명시해줘야할 때 주로 사용하는 방향으로 해야할 것 같네요! 리뷰 감사합니다!

2024-03-24 06:06 UTC, oht1221 commented on src/main/java/domain/PositiveNumber.java
> +  }
리팩토링 하면서 불필요해진 메서드들이라 제거하기는 했는데요 음... 처음에 메서드를 만들 때는 불변을 유지해야하는 VO 객체라는 측면을 중점적으로 보고 만들었습니다. 다만 말씀해주신 것 처럼 프로그램 내에서 매우 자주 사용되는 경우 성능 저하는 필연적으로 올 것 같은데... 해결책을 좀 생각해본다면, 

1. 만약 범위가 어느정도 정해진 값이라면 예전에 리뷰해주신 것 처럼 클래스 내부에 캐싱을 하거나
2. 캐싱이 불가능하다면 용처를 조금 제한한다거나
3. 아니면 불변성을 포기?하고 메서드를 호출하는 객체의 필드에 더해 주고 해당 객체를 다시 return 해주는 방법
 
정도가 있을 것 같습니다!

결국은 정답이 있다기 보다는, 서로 trade-off 라서 운영 상황에 맞게 구현하는게 맞는 것 같습니다 ㅠㅠ  리뷰 감사합니다!

2024-03-24 07:29 UTC, oht1221 commented on src/main/java/domain/Prize.java
>  public enum Prize {
당첨 여부 메서드 테스트를 추가하였습니다! 그리고 `valid`라는 메서드명이 의미가 명확하지 않은 것 같아서 당첨인지를 물어보는 `isWin`으로 수정하였습니다 :)

2024-03-25 13:21 UTC, ksy90101 approved these changes
피드백 수정 고생하셨습니다~
큰 의견 없으니 이만 머지할게요!
허들에서 이야기 한대로 스스로 다 이해하셔서 깜짝놀랐습니다..하하
마지막 단계도 홧팅입니다!

2024-03-25 13:21 UTC, merged