Lotto 2
next-step/java-lotto pull request #3662
Opened 2024-03-22 14:27 UTC by seungsu12

2024-03-23 08:18 UTC, catsbi requested changes
승수님 2단계 미션 진행하시느라 고생하셨습니다 👍 
피드백 필요한부분들이 좀 있어 코멘트 남겨드렸으니 확인해보면 좋을 것 같습니다. 

그리고 현재 로또 금액 이하의 (ex: 100원)금액을 입력할 경우에도 그대로 진행이 되는 것 같아요. 

그리고 고민하고 계신 Money에 대한 필요성을 고민하셨는데, 승수님이 해당 일급 객체의 책임이 어떻게 되는가 그 바운더리를 어떻게 정하냐에 따라 달라질 것 같아요. 
해당 객체는 말 그대로 돈이라는 개념에 대한 책임을 지는 것이고, 이 돈이라는 상태를 어떻게 관리할지를 고민해보세요. 제 생각에는 사용자로부터 입력받는 정보의 유효성 검증 책임과 연산, 차후 확장성을 고려해 다른 나라의 재화인경우 환율반영등 존재 의의는 얼마든지 있을 것 같네요. 수익율을 위해 타입 변경은 반대로 수익율 계산 객체에서 책임질 문제라고 보구요. 

ㅎㅎ 피드백 고민 후 다시 리뷰요청 부탁드려요.

2024-03-23 08:18 UTC, catsbi commented on src/main/java/lotto/LottoList.java
> +        this(IntStream.range(0, count).mapToObj(x -> new Lotto()).collect(Collectors.toUnmodifiableList()));
Stream API는 각 오퍼레이션의 결과값도 Stream이기 때문에 디미터 법칙을 그대로 적용해야하는건 아니지만 개인적으로 
개행이 행위에 대한 전환하는 포인트가 되기에 저는 적절히 개행으로 작업의 단위를 구분하여 가독성을 높히기를 권장드립니다!

2024-03-23 08:18 UTC, catsbi commented on src/main/java/lotto/LottoList.java
> +    }
출력에 대한 책임을 도메인에서 가지고 있는 것 보다는 View Layer에서 책임지도록 하는게 어떨까요?

2024-03-23 08:18 UTC, catsbi commented on src/main/java/lotto/LottoMatcher.java
> +public class LottoMatcher {
유틸리티 클래스라면 생성자 제한 혹은 싱글턴 패턴을 사용하는건 어떨까요?

2024-03-23 08:18 UTC, catsbi commented on src/main/java/lotto/LottoPrize.java
> +    MATCH_3(3, 5000),
자바에서는 숫자의 가독성읖 높히기 위해 언더바(`_`)를 허용합니다. 
```suggestion
    MATCH_3(3, 5_000),
```

2024-03-23 08:18 UTC, catsbi commented on src/main/java/lotto/LottoPrize.java
> +    }
매 번 열거타입 인스턴스를 모두 순회하며 카운트 체크를 해야하는데, 캐싱을 활용하면 O(1)의 시간복잡도를 가지는 검색도 가능할 것 같네요!

```suggestion
    public static LottoPrize from(int count) {
        if (cache.containsKey(count)) {
            return cache.get(count);
        }
        return LottoPrize.NONE:
    }
```

2024-03-23 08:18 UTC, catsbi commented on src/main/java/lotto/LottoResult.java
> +        return (calculateTotalEarnings()) / (double) (result.size() * lottoPrice);
수익율 계산은 복권의 종류나 지역/나라별로 바뀔수도 있는데 전략패턴으로 추상화를 해보는건 어떨까요?

2024-03-23 08:18 UTC, catsbi commented on src/main/java/lotto/LottoShop.java
> +    public void enter(){
Controller와 UI계층을 한 군데 섞어놨는데 분리해보면 어떨까요?

2024-03-23 08:18 UTC, catsbi commented
그리고 현재 패키지 구조가 root 패키지 하위에 모두 동일하게 작성되어있기에 어떤게 어떤 역할을 가지는지 파악하기가 힘듭니다. 적절한 패키지 분리를 해주시면 좋을 것 같습니다!

2024-03-25 10:17 UTC, seungsu12 commented on src/main/java/lotto/Lotto.java
> +    private final List<Integer> numbers;
넵 감사합니다!

2024-03-25 10:20 UTC, seungsu12 commented on src/main/java/lotto/Lotto.java
> +        numbers = LOTTO_NUMBERS.stream().limit(LOTTO_NUMBER_COUNT).sorted().collect(Collectors.toList());
저번 리뷰에서도 말씀해주신거였는데, 기본 생성자에서 필드를 생성하면, 캡슐화가 적용되지않나(외부는 어떻게 로또가 생성되는지 모르므로) 라는 생각으로 계속 비지니스 로직을 추가햇었습니다. 오히려 복잡도가 증가하군요 ㅜㅜ. 영상감사합니다. 해당 값을 생성하는 로직은 별도 util클래스로 분리를 진행하였습니다!

2024-03-25 10:20 UTC, seungsu12 commented on src/main/java/lotto/LottoList.java
> +        this(IntStream.range(0, count).mapToObj(x -> new Lotto()).collect(Collectors.toUnmodifiableList()));
넵, 개행분리 적용했습니다.

2024-03-25 10:20 UTC, seungsu12 commented on src/main/java/lotto/LottoList.java
> +    }
넵, 문자열 리스트 반환으로 리팩토링 진행하였습니다.

2024-03-25 10:21 UTC, seungsu12 commented on src/main/java/lotto/LottoMatcher.java
> +public class LottoMatcher {
생성자 제한으로 리팩터링 진행하였습니다.

2024-03-25 10:21 UTC, seungsu12 commented on src/main/java/lotto/LottoPrize.java
> +    MATCH_3(3, 5000),
이런 기능이 있을줄이야!! 감사합니다.

2024-03-25 10:22 UTC, seungsu12 commented on src/main/java/lotto/LottoPrize.java
> +    }
이런 부분은 신선했습니다! static block에서 초기화 한후 , 캐시를 도입해봤습니다.

2024-03-25 10:22 UTC, seungsu12 commented on src/main/java/lotto/LottoResult.java
> +        return (calculateTotalEarnings()) / (double) (result.size() * lottoPrice);
네, 외부에서 전략을 주입받는 쪽으로 추상화를 진행해 보았습니다.

2024-03-25 10:23 UTC, seungsu12 commented on src/main/java/lotto/LottoShop.java
> +    public void enter(){
이 부분은 잘 모르겠던 포인트입니다. 단순히 저 main 메서드를 controller로 분리를 하면 되는걸까요?

2024-03-25 13:41 UTC, catsbi approved these changes
승수님 피드백 반영하느라 고생하셨습니다 👍 
전체적으로 한결 보기 좋아졌네요! 2단계는 머지하겠습니다 바로 3단계로 가시죠!

2024-03-25 13:41 UTC, catsbi commented on src/main/java/lotto/domain/LottoMaker.java
> +    private static final List<Integer> LOTTO_NUMBERS = IntStream.range(1, 50).boxed().collect(Collectors.toList());
로또 번호는 1~45까지인데 50까지 포장하는 이유가 있을까요?

2024-03-25 13:41 UTC, catsbi commented on src/main/java/lotto/domain/LottoMaker.java
> +        return LOTTO_NUMBERS.stream().limit(LOTTO_NUMBER_COUNT).collect(Collectors.toUnmodifiableList());
list 의 subList함수를 활용하면 더 간단하게 가져올 수 있을 것 같아요

2024-03-25 13:41 UTC, merged