3단계 - 로또(2등)
next-step/java-lotto pull request #3665
Opened 2024-03-22 15:08 UTC by sm9171

안녕하세요 규남님 세번째 미션 완료했습니다.
이번에 보너스 넘버가 추가되면서 enum객체부터 의존하고 잇는 도메인 객체와 view 객체를 다 손보게 되었습니다. 특히 enum객체에서 convert메소드인 from쪽과 통계출력 부분이 조금 지저분한 느낌입니다.

2024-03-23 16:31 UTC, kyucumber requested changes
안녕하세요

간단한 몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2024-03-23 16:31 UTC, kyucumber commented on src/main/java/lotto/domain/AmountEnum.java
> +	public static AmountEnum from(final Integer collectedCount, final Boolean isBonus) {
> 특히 enum객체에서 convert메소드인 from쪽과 통계출력 부분이 조금 지저분한 느낌입니다.

현재도 그렇게 복잡하진 않은 것 같은데 객체지향 생활 체조 원칙을 위반하고 있긴 하네요. 이 부분은 메서드 추출 혹은 Stream 및 filter를 통해 조금 더 개선해볼 수 있지 않을까요?

2024-03-23 16:31 UTC, kyucumber commented on src/main/java/lotto/view/OutputView.java
> +		totalAmount += AmountEnum.from(5,true).getAmount() * hashMap.getOrDefault(AmountEnum.from(5,true), 0L);
totalAmount를 구하는 부분도 결국 도메인 로직입니다.

현재 View쪽에서 연산을 통해 도메인 로직을 수행하고 있는 것으로 보여요. 이 부분을 비즈니스 클래스로 옮기고 출력 쪽에서는 도출된 결과만 받아 출력하는 형태로 변경해보세요.

2024-03-23 16:31 UTC, kyucumber commented on src/main/java/lotto/domain/Lotto.java
> +    public AmountEnum getAmountEnumCompareWinNumber(Lotto winNumber, LottoNumber bonusNumber) {
validateBonusNumber를 Lotto라는 클래스 내에서 수행하는 것이 다소 어색해보이네요.

Lotto 타입인 winNumber와 bonusNumber가 합쳐진 별도의 클래스를 뽑아볼 순 없을까요? 컴포지션 등을 활용해 Lotto의 제약을 그대로 유지한 클래스를 추출해볼 수 있을 것 같습니다.

2024-03-23 16:31 UTC, kyucumber commented on src/test/java/lotto/LottoTest.java
> +    }
테스트 DisplayName과 실제 테스트가 일치하지 않는 것 같습니다.

2024-03-24 15:23 UTC, sm9171 commented on src/main/java/lotto/domain/Lotto.java
> +    public AmountEnum getAmountEnumCompareWinNumber(Lotto winNumber, LottoNumber bonusNumber) {
컴포지션 클래스인 BonusLotto으로 추출해 보았습니다.

2024-03-24 15:28 UTC, sm9171 commented
피드백 주신 부분을 토대로 리팩토링 해보았습니다.

2024-03-25 09:07 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

간단한 코멘트 남겨두었으니 다음 단계 진행에 참고 부탁드려요.

다음 단계 진행을 위해 머지하겠습니다.

2024-03-25 09:07 UTC, kyucumber commented on src/main/java/lotto/domain/Winners.java
> +        return winners;
중요한 부분은 아니나 참조가 아무 조치 없이 외부로 노출되고 있어서 외부에서 변조가 가능해보이네요.

Collections.unmodifableList나 Stream의 toList를 통해 수정을 막으면 좋을 것 같아요.

2024-03-25 09:07 UTC, merged