🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #3678
Opened 2024-03-23 19:31 UTC by hisomini

안녕하세요! 준혁님! 🙂
2단계 과제 진행했습니다

이번 과제 진행하면서 
1. LottoTicket 클래스가 int 변수 6개를 가질지, List<Integer>를 가질지
2. 당첨결과를 어떤방법으로 컬렉션에 담고 출력할 것인지

요 2가지가 가장 고민됐던 부분이였던 것 같아요!

계속 고민하면서 과제 제출 시간이 늦어졌는데, 계속 붙잡고 있는 것 보다는 리뷰받고 고쳐나가는게 좋을거같아서 후다닥 올려봅니다!
잘부탁드려요 🙌

2024-03-24 07:01 UTC, nooose commented
> LottoTicket 클래스가 int 변수 6개를 가질지, List Integer 컬렉션을 가질지

고민하셨는데 `List`컬렉션을 일급컬렉션인 로또 티켓으로 잘 설계하셨네요

6개를 가지게되면 필드가 많아져 유지보수를 어렵게하며,
객체 생성 시 필요한 필드가 늘어나게됩니다.
잘 선택하신 것 같네요 😄

2024-03-24 07:08 UTC, nooose requested changes
고민이 있다면 이렇게 바로바로 PR 요청하는 게 좋을 것 같아요
물론 혼자서 고민하는 것도 좋지만, 시간이라는 제약사항이 있으니까요 🥲
코멘트 남겼어요 확인해 보시고 재요청 드립니다.
혹시나 이해가 되지 않거나 미션 중간 궁금한 부분 생기면
언제든지 DM 또는 코멘트 남겨주세요

2024-03-24 13:57 UTC, hisomini commented on src/test/java/LottoTicketTest.java
> +        LottoTicket ticket = LottoTicket.createTicket(new ArrayList<>(List.of(1, 2, 3, 4, 5, 6)));
List.of가 ImmutableCollections을 return하면서 
createTicket 메서드 내부에 Collections.sort(inputs)로직으로 컬렉션을 변경하려고 해서 런타임 오류가 발생했습니다..!
그래서 단순히 ArrayList로 감싸서 보내는 방법을 선택했는데 다른 방법을 찾아보겠습니다!!

2024-03-25 16:36 UTC, nooose commented on src/test/java/LottoTicketTest.java
> +        LottoTicket ticket = LottoTicket.createTicket(new ArrayList<>(List.of(1, 2, 3, 4, 5, 6)));
제가 미처 그부분을 파악하지 못했네요 😄
인자는 불변으로 받고 내부에서 가변처리후 정렬해도 될 것 같아요
가변리스트로 열어두면 부작용이 발생할 수 있습니다.

2024-03-26 14:48 UTC, hisomini commented
안녕하세요 준혁님!
피드백 주신 내용 바탕으로 수정했습니다.

준혁님이 말씀해주신 것 처럼 controller - service- repository 요 형태가 익숙하다 보니 그냥 service에다 넣어버리는 나쁜 습관이 있었던 것 같아요 🙃 
말씀해주셔서 감사해요 습관처럼 쓰고있어서 이상한지도 몰랐네요 ... 🥺

---
```
LottoTicketGenerator - 로또티켓을 발생하는 클래스
LottoResultManager - 발행된 티켓과 당첨번호를 바탕으로 결과를 도출하고 최종 당첨금 계산하는 클래스
```
- LottoTicketGenerator, LottoResultManager 두 클래스를 만들어서 무거웠던 서비스 클래스를 역할에 따라서 분리했습니다!
- LottoTicket안에 LottoNumber라는 객체를 만들어서 로또티켓의 책임을 나눴습니다.
- ui 패키지 분리하고 각 클래스에 맞게 테스트코드 작성했습니다.

아직 찜찜하게 남아있는 부분은
```
1. 정적 팩토리 메소드 활용방안
2. 당첨결과 도출 로직
```
요 2가지인 것 같아요 계속 고민해보겠습니다 🔥

2024-03-27 15:04 UTC, nooose approved these changes
소민님이 처음에 걱정을 많이 하셨는데
지금은 걱정하지 않아도 될 만큼 많이 개선되었네요
리뷰가 좀 늦어서 죄송한 만큼 꼼꼼하게 봤어요 🙇
피드백 받을 부분 처리하고 3단계 미션 시작하면 좋을 것 같아요.
2단계 미션 수고하셨습니다!

2024-03-27 15:04 UTC, nooose commented on src/main/java/lotto/LottoTicketGenerator.java
> +
필드가 내부에서 초기화되네요
LottoTicketGenerator가 LottoTicketBall을 의존한다고 볼 수 있는데요
의존주입을 생성자를 통해서 받아보면 어떨까요?
```java
new LottoTicketGenerator(lottoTicketBall);
```
이전 방법과 어떤 차이가 있는지 고민해 보면 좋겠네요!

2024-03-27 15:04 UTC, nooose commented on src/main/java/lotto/LottoTicketGenerator.java
> +    private LottoTicketBall lottoTicketBall = new LottoTicketBall();
상수와 멤버변수 간 개행을 주면 좋겠네요 
```suggestion
    private static final int PRICE_PER_TICKET = 1000;
    
    private LottoTicketBall lottoTicketBall = new LottoTicketBall();
```

2024-03-27 15:05 UTC, merged