Step4 - 로또(수동)
next-step/java-lotto pull request #3686
Opened 2024-03-24 14:31 UTC by sinterhoo

### 피드백 반영 부분

- EnumMap 적용 : HashMap에 비해서 성능이 좋고, 메모리 효율성도 좋은 자료구조인 거 같아 적용했습니다! 감사합니다.
- isNumberic은 유지 : parseInt 내부에서 예외처리가 되고 있기 때문에 중복이지 않냐고 하셨지만, 커스텀 메시지를 명확하게 주기 위해 우선은 유지하는 게 좋을 거 같다고 생각했습니다!
- 로또 등수 확인하는 getPrizeLevel 로직은 PrizeLevel이 맞는 거 같아서 이동시켰고, 이름도 명확하게 변경하였습니다.

### 구현 부분

- 설계 고민을 했는데 이미 많은 클래스로 나눠놔서 새로 만든 클래스는 없고, 기존 클래스를 최대한 활용했습니다.
- LottoStore에 돈과 수동으로 찍은 용지를 가져가면 한 뭉텅이의 로또 목록을 받는다고 생각하고, LottoStore에 생성자를 하나 더 만들었고 Lottos에 수동으로 로또 목록을 생성하는 메서드를 추가한 뒤, LottoStore에서 자동 로또 + 수동 로또를 합치도록 구현했습니다.

### 고민되는 부분

- LottoStore에 생성자에서 너무 많은 일을 진행하는 거 같은데, 좀 더 메서드를 나눠서 생성자를 가볍게 하는 게 좋을까요?
- InputView에서 수동 로또 개수 부분을 검증하고 있는데, 맞는 위치에 둔 건지 모르겠습니다. 설계를 잘못한 건지 view에서 검증을 해도 되는 부분인지 애매하더라고요. 돈은 LottoStore에서 검증하고 있는데, 수동 로또 구매 수는 View에서 진행하고 있다 보니까 순서랑 위치가 괜찮은지 고민이 됩니다.

2024-03-24 14:46 UTC, dhmin5693 commented
> isNumberic은 유지 : parseInt 내부에서 예외처리가 되고 있기 때문에 중복이지 않냐고 하셨지만, 커스텀 메시지를 명확하게 주기 위해 우선은 유지하는 게 좋을 거 같다고 생각했습니다!

`Integer.parseInt`의 역할은 별도의 설명이 없더라도 개발자가 잘 인지하고 있을 정도로 범용적이고 유명한 메소드입니다.
예외도 굉장히 명백하죠. `숫자가 아니면` 예외가 발생합니다.
따라서 parsing 부분을 별도의 메소드로 분리하고 try로 감싸 한 번만 parseInt를 호출하는 것 대비 validation -> Integer.parseInt 순서대로 진행한다 한들 메시지가 눈에 띄게 좋아지는 정도는 아니지 않을까요?

요샌 컴퓨터 성능이 좋아 가독성이 더 비싼 자원인건 맞습니다만, 같은 메소드를 굳이 2번 호출해서 성능에 영향을 줄 필요도 없습니다.

2024-03-24 15:04 UTC, dhmin5693 requested changes
너무 잘해주셨네요 👍 
아쉽게도 요구사항의 일부가 충족되지 않아 수정 요청을 드리려고 합니다.
확인해보시고 다시 요청주세요.

2024-03-24 15:04 UTC, dhmin5693 commented on src/main/java/step2/PrizeLevel.java
> +    }
`PrizeLevel` 의 필드 레벨에 `Map` 상수를 미리 설정해두고 찾는 방법도 있습니다.
지금처럼 매번 순회하면 O(n)의 시간복잡도를 가지나 `Map`에 미리 만들어둔다면 O(1)이 되겠네요.

[참고자료](https://pjh3749.tistory.com/279)

2024-03-24 15:04 UTC, dhmin5693 commented on src/main/java/step2/view/InputView.java
이 파일의 문자열도 포장해주세요.
`String.format` 이랑 함께 사용하면 더 깔끔할 수 있습니다.

2024-03-26 12:48 UTC, sinterhoo commented on src/main/java/step2/LottoNumbers.java
> +    }
처음부터 Set으로 진행했으면 더 좋았을 거 같네요.. 중복 값 제거 set 자료구조 계속 생각하겠습니다!

2024-03-26 12:48 UTC, sinterhoo commented on src/main/java/step2/LottoStore.java
> +    public LottoStore(String money, NumberGenerator numberGenerator, List<String> manualLottoNumbers) {
생성자가 더 깔끔하게 된 거 같습니다! 적용했습니다!

2024-03-26 12:49 UTC, sinterhoo commented on src/main/java/step2/PrizeLevel.java
> +    }
좋은 방법 알아갑니다! 한번 만들어두면 중복 작업이 필요가 없어서 좋은 거 같습니다. 적용했습니다!

2024-03-26 14:08 UTC, dhmin5693 commented on src/main/java/step2/LottoNumbers.java
> +    }
`다른 자료구조로 쉽게 해결할 수 있다` 라는 인사이트를 얻으셨으면 충분합니다.

2024-03-26 14:10 UTC, dhmin5693 commented on src/main/java/step2/PrizeLevel.java
> +    }
실무에서도 굉장히 자주 사용하는 기법 중 하나입니다.
숙지하시면 분명 큰 도움이 되실거에요.

2024-03-26 14:17 UTC, dhmin5693 approved these changes
좋습니다 👍 
step4 마무리해도 되겠군요.

항상 생각했던 내용을 잘 정리해주셔서 저도 리뷰드리기가 편했던 것 같습니다.
로또 진행하시느라 수고하셨고 다음 미션 진행도 잘 헤쳐나가시길 바라겠습니다.

2024-03-26 14:17 UTC, merged