[Step 4] 로또(수동)
next-step/java-lotto pull request #3687
Opened 2024-03-24 15:56 UTC by Yejikwon

2024-03-24 17:23 UTC, Yejikwon commented on src/main/java/lotto/domain/LottoNo.java
> +    for (int number = LOTTO_MIN_NUMBER; number <= LOTTO_MAX_NUMBER; number++) {
minNumber(0) 와 maxNumber(45)의 위치를
고민하다가
LottoTicketCreateGenerator 에 두었는데요!
혹시 더 좋은 위치 있다면, 의견 부탁드립니다 (_ _)~!

2024-03-25 15:38 UTC, dhmin5693 requested changes
안녕하세요 :)

step4도 되게 잘 해주셨네요.
지금 당장 머지해도 크게 문제는 없는데 마지막이니 1번 더 고민해보셨으면 좋겠어서 일단 몇 개의 피드백을 남겨보았습니다.
특별히 필요하진 않다고 느껴지신다면 본인의 생각을 간단히 적어주시고 바로 요청주시면 머지하겠습니다.

2024-03-25 15:38 UTC, dhmin5693 commented on src/main/java/lotto/view/InputView.java
> +  }
input에서 사실상 수동 구매 로또의 기능의 일부를 담당하고 있는게 아닐까요?
입력 + 파싱 + 6개로 깔끔하게 묶어서 전달하고 있네요.

2024-03-25 15:38 UTC, dhmin5693 commented on src/main/java/lotto/domain/PurchaseAmount.java
> +    if (totalPurchaseAmount <= 0 || totalPurchaseAmount % PRICE_PER_TICKET != 0) {
> 프로그래밍 요구사항) 규칙 3: 모든 원시값과 문자열을 포장한다.

0 도 포장해주세요.

2024-03-25 15:38 UTC, dhmin5693 commented on src/main/java/lotto/domain/LottoNo.java
> +    for (int number = LOTTO_MIN_NUMBER; number <= LOTTO_MAX_NUMBER; number++) {
저는 `LottoNo` 내부가 더 맞다고 생각합니다.
로또 번호의 범위는 생성기보다는 로또 자체의 도메인이 조금 더 적합하지 않을까요?

2024-03-25 15:38 UTC, dhmin5693 commented on src/main/java/lotto/domain/strategy/ShuffleStrategy.java
> +  }
POSSIBLE_LOTTO_NUMBER_CANDIDATES는 내부 데이터가 절대로 수정되면 안됩니다.
unmodifiableList 로 묶어주세요.

2024-03-25 15:38 UTC, dhmin5693 commented on src/main/java/lotto/domain/LottoTickets.java
> +  }
`LottoTickets` 에서 `PurchaseAmount` 도 해석하고 수동 로또번호까지 해석하여 생성하는 책임이 생겼습니다.
여기에 두어도 큰 문제는 없어보이긴 합니다만, `LottoTickets` 은 단순하게만 보면 로또의 묶음이거든요.
그렇다면, `LottoTickets` 의 관점에서 다시 생각해보았을 때 구매한 로또가 수동인가 자동인가는 큰 상관이 없지 않을까요?
그저 로또 N개만 받아다가 묶음으로 관리하면 되는 클래스니까요.

지금 방향도 틀린 것 같지는 않습니다.
명확한 답은 없으니 무엇이 더 나을지는 한 번 고민해보세요 :)

2024-03-25 15:38 UTC, dhmin5693 commented on src/main/java/lotto/domain/type/RewardPrice.java
>      if (it.matchCount == 5) {
5가 왜 5일까요?
여기도 포장해주세요~

2024-03-25 15:38 UTC, dhmin5693 commented on src/test/java/lotto/WinningNumbersTest.java
>    @DisplayName("당첨 번호 관리 기능 테스트")
이런 데도 답이 있는건 아닌데요, 보통 테스트는 given - when - then 의 순서로 작성합니다.
이를 BDD라고 하거든요. 행동 기반 검증 기법입니다.
내가 테스트하는 대상이 "어떤 상황"일 때, 특정 기능을 작동시키면 "어떤 결과"를 갖게 된다(혹은 반환한다) 의 순서를 이루고 있어요.
이 순서대로 `@DisplayName` 에 적어보면 테스트 이해하는데에 도움이 너무 잘 되더라구요.

예를 들면 이렇습니다.
```java
@DisplayName("당첨 번호 6개와 보너스 번호를 입력하여 생성하고 `WinningNumbers` 를 생성할 수 있으며 같은 번호를 갖는지 검증할 수 있다")
```

2024-03-26 04:34 UTC, Yejikwon commented on src/main/java/lotto/domain/LottoNo.java
> +    for (int number = LOTTO_MIN_NUMBER; number <= LOTTO_MAX_NUMBER; number++) {
오 동휘님 감사합니다! 
저도 생각해보니, LottoNo 가 제일 적합해 보여요!
생성기는 단순 생성 역할,
로또 번호 범위는 도메인이 관리하는 게 좋을 거 같습니다 (_ _)~

2024-03-26 04:37 UTC, Yejikwon commented on src/main/java/lotto/view/InputView.java
> +  }
@dhmin5693 
동휘님 안녕하세요! 
혹시 요부분 부연 설명 부탁드려도 될까요?!

입력 + 파싱 + 6개 
<-- input 의 역할을 벗어난 것이라 개선이 필요하다고 말씀주신 것 같은데요!
개선 방향을 못잡아서 여쭤봅니다!

2024-03-26 05:09 UTC, Yejikwon commented on src/main/java/lotto/domain/LottoTickets.java
> +  }
@dhmin5693 동휘님 감사합니다!! 
아직도 한 도메인에서 역할을 많이 갖게 설계하게 되네요 ㅜ-ㅜ
말씀주셔서 감사합니다!!!

2024-03-26 07:26 UTC, Yejikwon commented
@dhmin5693 동휘님 피드백 리뷰 정말 감사드려요! (짱!)
https://github.com/next-step/java-lotto/pull/3687#discussion_r1538576248
요 부분은 제가 이해를 못해서 수정을 못했습니다!
우선 다른 말씀주신 부분 피드백 반영했습니다 (_ _)~

시간되실 때 검토부탁드려요!
미리 감사드립니다!

2024-03-26 14:02 UTC, dhmin5693 commented on src/main/java/lotto/view/InputView.java
> +  }
@Yejikwon 
한 번 엔터가 입력되는 순간까지를 하나의 String으로 처리하여 입력을 받게 됩니다.
강의노트의 예시로 진행해볼게요.

```plaintext
8, 21, 23, 41, 42, 43
3, 5, 11, 16, 32, 38
7, 11, 16, 35, 36, 44
```

1줄마다 1개의 String으로 변환이 될거에요.
그리고 이 클래스의 convertIntegerSet에서는 `SANNER`를 활용, 입력을 처리합니다.
그 다음 int로 변환하고 `Set`으로 모아옵니다.

개인적으로 입력과 파싱까지는 그래도 하나의 메소드에서 진행하기에 충분하다고는 생각합니다만,
첫 줄로 입력한 `8, 21, 23, 41, 42, 43` 을 `Set<Integer>`으로 묶는다는건 여러 가지 의미를 내포할 수 있다고 보입니다.

1. 입력받은 문자열을 쉼표로 구분할 수 있다.
2. 구분된 문자는 전부 숫자이다.
3. 중복을 제거한다.
4. 입력받은 하나의 문자열은 한 개의 묶음으로 관리한다.

input은 "입력한다" 라는 것만 알면 되지만 위처럼 나열해보면 input이 도메인을 알고 있는 느낌이 조금 들어서 말씀드린 내용입니다.

저라면 여기선 `List<String>` 만 입력받고 receiveManualPurchaseLottos 를 호출한 곳에서 `List<Set<Integer>>` 로 변환할 것 같아요.

2024-03-26 14:06 UTC, dhmin5693 approved these changes
반영 잘 해주셨군요 😄 
마지막으로 남기신 질문에 대한 답변도 달아두었습니다.
확인 부탁드립니다.

만약 이 부분에 대해 궁금한게 있으시다면 마지막 미션인 만큼 로또 미션 안에서 답변드리긴 어려우니 DM 보내주세요.

그 동안 수고 많으셨습니다 🙇‍♂️

2024-03-26 14:06 UTC, merged