🚀 2단계 - 로또(자동)
next-step/java-lotto pull request #3689
Opened 2024-03-24 16:15 UTC by eldertree777

안녕하세요~!

처음 기본적인 기능 명세 후, TDD 하도록 테스트 작성 후 기능 구현하고자 하였습니다.

하지만, 기능 구현 후 UI 와 리팩터링 단계로 넘어가면서 구조와 코드들이 변경되면서 TDD스럽지 못한것 같습니다.
리팩터링 후 만들어지는 메서드나 새로운 클래스는 테스트 작성 이전 만들어져, 테스트를 추가하기 어렵다는 생각이 듭니다.

처음 기능 명세와 테스트를 더 세밀하게 설계가 필요한 것 인지 어떤 부분에 더 신경 쓰면 좋을지 아직 감이 안 잡히는 것 같습니다.

리뷰 부탁드립니다.
감사합니다~!

2024-03-26 05:05 UTC, Hyeon9mak requested changes
안녕하세요 제원님! 로또 미션 완성도 높게 잘 구현해주셨습니다 💯 

우려하신 것과 다르게 클래스간 역할과 관계는 잘 배분해주셨다고 생각하는데요,
구현해주신 로또 게임 특성상 "이 부분에서 변경이 자주 일어날 것 같아."
"당첨 금액 조절할 땐 다른 코드를 굳이 볼 필요가 없지. 여기만 보면 될 것 같아." 라는 기준으로
코드를 배치해주셨다면 그게 좋은 설계 아닐까요?
그리고 "`Winnings` 라고 이름을 지어두면, 어떤 로직을 가진 객체인지 느낌이 오겠지?" 라는 기준으로
클래스의 이름을 부여해주셨다면, 그게 좋은 역할 아닐까요? 😄 

> 리팩터링 하면서 만들어지는 메서드나 새로운 클래스는 테스트 작성 먼저하고 만든 것이 아니기 때문에, 테스트를 추가하기 어렵다는 생각이 듭니다.

꼭 리팩터링 시점에 테스트를 먼저 작성하지 않아도 될 것 같은데요,
리팩터링 전에 작성해둔 테스트가 제원님께 심리적인 안정감을 제공했다면 성공적인 TDD 를 해내신거고,
아니라면 정말 추가 테스트 코드 작성 후 리팩터링이 필요했다고 생각해요.
제원님의 경험은 어떠셨나요?

몇 가지 간단한 코멘트 남겼으니 확인해주세요!

2024-03-26 10:48 UTC, eldertree777 commented on src/main/java/lotto/controller/LottoController.java
> +    }
UI와 핵심로직을 중계하는 역할이 Controller, 주요 핵심 로직은 Service라는 명칭의 클래스에 있어야 한다고 생각하여 습관적으로 만들었습니다.

2024-03-26 11:43 UTC, eldertree777 commented
질문이 있습니다.

Controller와 Service에서 습관적으로 의존성 주입과 비슷한 코드를 만드려다 보니 다음과 같은 생성자가 만들어진것 같습니다.

해당 미션에서는 단순히 static메서드만으로 구현해도 문제가 없을 것 같다는 생각이 듭니다.
하지만 static 메서드를 너무 많이 작성하는 것도 좋지 않은 코드로 알고 있는데 클래스 구현시 어떻게 설계하는게 좀 더 바람직할까요.

이전 질문인 "클래스간 역할과 관계"에 대해 이어 질문드립니다. 

감사합니다!
리뷰 부탁드리겠습니다.

2024-03-28 00:08 UTC, Hyeon9mak approved these changes
안녕하세요 제원님! 피드백 잘 반영해주셨습니다 👍 

> 해당 미션에서는 단순히 static메서드만으로 구현해도 문제가 없을 것 같다는 생각이 듭니다.
하지만 static 메서드를 너무 많이 작성하는 것도 좋지 않은 코드로 알고 있는데 클래스 구현시 어떻게 설계하는게 좀 더 바람직할까요.

이전 답변에서 제가 추구하는 바가 예측되셨을텐데요,
"static 메서드를 너무 많이 작성하는게 왜 좋지 않은가?" 를 먼저 여쭙고 싶어요.
결국 중요한 것은 많고 적음이 아니라 그로 인해 유지보수가 쉬워지는가 어려워지는가... 라고 생각해요.

현재 로또 프로젝트는 static 메서드의 수로 인해 유지보수가 어려워질 부분이 존재할까요?
혹은 반대로 static 하게 사용해서 유지보수성이 늘어날까요?
제원님의 생각을 공유해주세요 😄 👍 

몇 가지 피드백만 간단히 남겼습니다!
다음 단계에서 뵐게요!

2024-03-28 00:08 UTC, Hyeon9mak commented on src/main/java/lotto/model/Number.java
> +}
동등성 부여까지 👍

2024-03-28 00:08 UTC, Hyeon9mak commented on src/main/java/lotto/model/Number.java
> +    }
1~45 까지의 숫자만 다룰 수 있다는 걸 검증해줘도 좋겠어요 😄 👍

2024-03-28 00:08 UTC, Hyeon9mak commented on src/main/java/lotto/model/RandomNumbersGeneratorImpl.java
> +    }
`NumbersGenerator` 에서 `Integer` 대신 `Number` VO 를 바로 생성하는 건 어떨까요?

2024-03-28 00:08 UTC, merged