Step3 - 로또2등
next-step/java-lotto pull request #3698
Opened 2024-03-25 15:22 UTC by boy0516

3단계 리뷰 부탁드립니다.

구조가 클래스 안에 클래스가 있는 구조다보니 테스트 코드를 작성할때 너무 복잡합니다. 생성자를 추가해서 해결하는게 맞는 방향인가요?

2024-03-26 15:27 UTC, wooobo requested changes
안녕하세요 지훈님~

3단계 잘 진행해주셨습니다!
코멘트 남겨 놓았는데 확인 후 재요청 부탁드릴께요~ 

👍

2024-03-26 15:27 UTC, wooobo commented on src/main/java/lotto/view/ResultView.java
>                  .map(lottoNumber -> String.valueOf(lottoNumber.getValue()))
```suggestion
                .map(LottoNumber::stringValue)
```

LottoNumber가 문자열을 변환해주면 값을 꺼내와서 변환시키는(`get-`)을 안써도 되겠네요.

ex)
<img width="510" alt="스크린샷 2024-03-27 오전 12 00 50" src="https://github.com/next-step/java-lotto/assets/12059592/b0192100-6d05-4d4e-8a41-f924d6c48124">

2024-03-26 15:27 UTC, wooobo commented on src/main/java/lotto/controller/LottoController.java
> +        ResultView.showLottoQuantity(budget.divide(Lotto.LOTTO_PRICE));
`Lotto.LOTTO_PRICE`가 좀 더 상위로 올라왔군요!
좋네요 👍 

> 그렇다면 이런 생각도 드네요.
> - 로또 가격은 변하지 않을까? 
> - Lotto객체 내부에서는 사용하지 않는데 Lotto가 가져야할까?
> - 어쩌면 `로또가격`이라는 단어때문에 좀 더 추상적으로 보지 못하는게 아닐까?
> - 그냥 가격 아닐까?
> - 그럼 Price 객체가 된다면 어떨까?
> - Budget이 가지는게 더 자연스러운가?

설계에 따라 다양한 상상을 해볼 수 있을것 같아서 생각을 공유해봅니다~

2024-03-26 15:27 UTC, wooobo commented on src/main/java/lotto/domain/WinLotto.java
> +    private List<LottoNumber> winLotto;
`Lotto`객체와 상태가 같네요.
그렇다면, 같은 객체라고 봐야하지 않을까요?
`winLotto`는 6개 이상의 `LottoNumber`를 가져도 괜찮을까요?

2024-03-26 15:27 UTC, wooobo commented on src/main/java/lotto/domain/WinLotto.java
> +        return lotto.getLotto().contains(bonus);
> 규칙 4: 한 줄에 점을 하나만 찍는다.
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

규칙들의 본질적인 의미가 무엇일까요?
객체에게 메시지를 보내고, 객체간의 비교를 해보면 어떨까요?

2024-03-26 15:27 UTC, wooobo commented on src/test/java/lotto/domain/BudgetTest.java
> +        int result = budget.divide(1000);
👍

2024-03-26 15:27 UTC, wooobo commented on src/test/java/lotto/domain/LottosTest.java
> +        WinLotto winLotto = WinLotto.ofNumbers(List.of(1, 2, 3, 4, 5, 7), 6);
```suggestion
Lottos lottos = 로또생성됨(List.of(1,2,3,4,5,6));
WinLotto winLotto = 당첨로또생성됨(List.of(1,2,3,4,5,6), 6);
```

생성자를 다양하게 하셔도 됩니다~
테스트픽스쳐를 활용하셔도 되구요~

[테스트 픽스처 올바르게 사용하기](https://jojoldu.tistory.com/611)

2024-03-26 15:27 UTC, wooobo commented on src/test/java/lotto/domain/StatisticTest.java
> +        assertThat(resultWithoutBonus).isEqualTo(Statistic.THIRD);
[테스트당 개념 하나](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2009%20-%20%EB%8B%A8%EC%9C%84%20%ED%85%8C%EC%8A%A4%ED%8A%B8.md#%ED%85%8C%EC%8A%A4%ED%8A%B8%EB%8B%B9-%EA%B0%9C%EB%85%90-%ED%95%98%EB%82%98)

2024-03-27 21:08 UTC, boy0516 commented on src/main/java/lotto/domain/WinLotto.java
> +    private List<LottoNumber> winLotto;
이게 무슨 의미인지 잘 모르겠습니다. Lotto 객체의 List<LottoNumber>에 bonus 번호도 같이 저장하라는 말씀인가요?

2024-03-30 14:48 UTC, boy0516 commented on src/main/java/lotto/controller/LottoController.java
> +        ResultView.showLottoQuantity(budget.divide(Lotto.LOTTO_PRICE));
약간 생각을 잘못하고있었던거같아요. Price를 어떤 class에서 반드시 포함하고있어야한다는 생각에 사로잡혀서 Budget에도 넣었다가 뺏다가 하다보니 이상한 방향으로 크게 돌았네요. 요구사항에 가격을 입력하는부분이 없으니 enum으로 관리하는것으로 변경했습니다.

2024-03-30 14:53 UTC, boy0516 commented on src/main/java/lotto/domain/WinLotto.java
> +    private List<LottoNumber> winLotto;
Lotto를 확장하는걸로 변경했습니다. 말씀하신 의도가 이게 맞는지 잘 모르겠네요

2024-03-30 15:13 UTC, boy0516 commented on src/test/java/lotto/domain/LottosTest.java
> +        WinLotto winLotto = WinLotto.ofNumbers(List.of(1, 2, 3, 4, 5, 7), 6);
@BeforeEche로 빼는거나 @methodsource를 사용하는것도 좋을거같네요. 테스트케이스가 하나라서 우선 생성자를 하나 추가하는걸로 라인 한 줄 줄였습니다.

2024-03-31 11:09 UTC, wooobo approved these changes
안녕하세요 지훈님~

3단계 잘진행해주셨습니다!
이만 `merge`진행하겠습니다!

그럼 다음 단계도 화이팅입니다! 👍

2024-03-31 11:09 UTC, merged

2024-04-01 14:48 UTC, boy0516 commented on src/main/java/lotto/domain/WinLotto.java
> +    private List<LottoNumber> winLotto;
음 제가 푸쉬를 안하고 리뷰요청을 했나봅니다..