feat : 🚀 4단계 - 로또(수동)
next-step/java-lotto pull request #3728
Opened 2024-03-28 12:27 UTC by gutenLEE

2024-03-28 12:31 UTC, gutenLEE commented on src/main/java/ui/LottoProgram.java
> +        System.out.println(String.format("수동으로 %d장, 자동으로 %d개를 구매했습니다.", manualLottoCount, (total = manualLottoCount)));
LottoSeller에게 수동, 자동 번호 전략을 결정하는 로직을 서비스 로직이라 판단하여 
Program에 두었습니다.

2024-03-28 12:31 UTC, gutenLEE commented on src/main/java/lotto/LottoSeller.java
> +    public static Lottos sell(BuyLotto buyLotto) {
파라미터 개수가 늘어나서 `BuyLotto` 클래스로 분리했습니다.

2024-03-29 08:44 UTC, dhmin5693 requested changes
굉장히 많이 좋아진게 느껴집니다 👍 
딱 한 부분만 수정해주시면 될 것 같으니 남긴 리뷰 확인해보시고 다시 요청주세요.

2024-03-29 08:44 UTC, dhmin5693 commented on src/main/java/ui/LottoProgram.java
> +        System.out.println(String.format("수동으로 %d장, 자동으로 %d개를 구매했습니다.", manualLottoCount, (total = manualLottoCount)));
전략 결정은 여기가 맞습니다만, System.out.println 의 사용은 view에서만 해주셔야 합니다.
이 부분을 적당히 나눠보시겠어요?

buyLottos 에서 너무 많은걸 하려고 해서 그런게 아닌가 싶은데요,
수동 로또 구매는 별도의 메소드에서 해주시고 lotto를 merge하는 메소드 정도로 책임을 분리해보시는건 어떤가요?

2024-03-29 16:01 UTC, gutenLEE reviewed
➕ 답변주신 내용 감사합니다 도움이 되었습니다!
---

`BuyLotto`를 서브타이핑한 클래스 `BuyAutoLotto`, `BuyManualLotto` 두 개를 만들고
번호 전략 생성 책임을  LottoProgram에서 BuyLotto 서브타이핑 클래스로 옮겼습니다!

번호 전략 생성에 필요한 데이터를 BuyLotto이 가장 잘 알고있고 코드 응집도도 높아졌다 생각했습니다

2024-03-30 09:34 UTC, dhmin5693 approved these changes
잘 수정해주셨네요 :)
로또 미션 마무리하겠습니다.
수고하셨습니다.

2024-03-30 09:34 UTC, merged