[Step2] 로또 (자동)
next-step/java-lotto pull request #3729
Opened 2024-03-28 13:34 UTC by duyankim

안녕하세요. 2단계 - 로또 구현하였습니다.
잘 부탁드립니다.

2024-03-28 23:36 UTC, testrace requested changes
안녕하세요 😃 
2단계 구현 잘해주셨네요 👍 
몇 가지 코멘트를 남겨두었는데요 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/LottoApplication.java
> +        System.out.println(Const.GET_TRY_NO);
입력을 받기 위한 메시지 출력은 InputView 내부에서 수행하면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/LottoApplication.java
> +        LottoGame lottoGame = new LottoGame(tryNo);
미션 페이지의 예시처럼 구입한 로또 목록을 출력하면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/README.md
> +  - [x] 일치 갯수, 금액을 Enum으로 관리
기능 목록 👍 
하나의 항목을 구현완료할 때 마다 체크 표시와 함께 커밋해 보시면 좋을 것 같아요

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/constants/Const.java
> +    public static final List<Integer> NUMBER_LIST = IntStream.rangeClosed(1, 45)
view를 위한 값과 로또 도메인에서 사용되는 값 모두를 관리하고 있는데요
SRP를 지키기 위해 상수를 사용하는 객체가 상수를 관리하면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/domain/Lotto.java
> +    }
필드의 타입대로 생성하는 생성자를 주 생성자라고 합니다.
생성자에서 유효성 검증등 코드가 추가된다면 모든 생성자를 수정해야하는데요
생성에 대한 책임을 모두 주 생성자가 처리하도록 부 생성자는 주 생성자를 호출하도록 하면 어떨까요?
```java
public Lotto() {
    this(...);
}
```

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/domain/Lotto.java
> +        this.autoLotto = autoLotto;
로또는 6개의 번호를 가져야합니다.
InputView를 거치지 않으면 로또는 숫자를 6개 외의 개수를 가질 수 있는 상태인데요
6개라는 제약을 Lotto 내부에서 검증하면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/domain/Lotto.java
> +    }
메서드를 분리하지 않아도 충분할 것 같은데요
어떤 이유로 메서드를 분리해주셨는지 궁금합니다 🤔 
인자의 변수명도 축약하지 않고 사용해 주시면 좋을 것 같아요

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/domain/LottoGame.java
> +public class LottoGame {
LottoGame의 책임이 너무 많은 것 같아요
Lottos를 생성하는 책임, 수익률을 구하는 책임, 당첨 결과를 구하는 책임.
모두 각각의 객체로 도출하면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/domain/LottoGame.java
> +        countMap.put(6, 0);
3, 4, 5, 6이 무엇을 의미하는지 쉽게 파악하기 힘든 것 같은데요
RewardEnum이 있으니 활용해 보면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/domain/Lottos.java
> +public class Lottos {
Lottos에 대한 테스트가 없네요 
모든 도메인 로직에는 단위 테스트를 추가해 주세요
로또 미션의 주제가 TDD이니 가급적 테스트를 먼저 작성해 보시길 추천드립니다

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/enums/RewardEnum.java
> +    SIX(6, 2000000000);
큰 숫자는 `_`를 활용해 가독성을 향상 시킬 수 있습니다
```suggestion
    SIX(6, 2_000_000_000);
```

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/enums/RewardEnum.java
> +public enum RewardEnum {
패키지명과 클래스명에 enum을 붙이시는 이유가 궁금합니다
enum도 하나의 클래스인데 타입에 따라 패키지를 나눌 필요가 있을까요?

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/enums/RewardEnum.java
> +        return null; // or throw an exception
이 메서드도 테스트가 없네요 😢 
matchingCount에 해당하는 타입이 없다면 null을 리턴하기 보다 미당첨 타입을 리턴하면 어떨까요?
```java
return MISS;
```

2024-03-28 23:36 UTC, testrace commented on src/main/java/lotto/view/InputView.java
> +            throw new IllegalArgumentException("금액이 모자랍니다.");
금액이 모자라는 것은 도메인 규칙이라고 생각합니다
로또를 구입할 수 있는지 없는지는 도메인에서 검증하면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/test/java/lotto/domain/LottoGameTest.java
> +        Map<Integer, Integer> map = new HashMap<>();
변수명을 expected로 지으면 어떨까요?
테스트 코드라고 하더라도 변수명은 이해하기 쉬운 이름으로 지어주면 좋을 것 같습니다

2024-03-28 23:36 UTC, testrace commented on src/test/java/lotto/domain/LottoGameTest.java
> +        double rate = game.profitRate();
`game.countLottosByMatchingCount` 메서드를 호출하지 않으면 수익률은 항상 0이 나올텐데요
다른 개발자가 수익률을 구하기 위해 선행 메서드가 필요하다는 사실을 모른다면 소스코드를 분석 이후에야 선행 메서드의 존재를 알 수 있을 것 같아요
앞서 드린 코멘트처럼 당첨 결과를 객체로 도출한다면 수익률은 당첨 결과에게 조회하면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/test/java/lotto/domain/LottoTest.java
> +class LottoTest {
로또의 제약인 숫자의 범위, 로또가 가지는 숫자의 개수 등에 대한 테스트도 추가하면 어떨까요?

2024-03-28 23:36 UTC, testrace commented on src/test/java/lotto/view/ResultView.java
> +public class ResultView {
이 클래스는 제거해도 좋을 것 같아요

2024-03-31 07:41 UTC, duyankim commented
용주님, 꼼꼼한 리뷰 감사드립니다!
말씀해주신 부분을 최대한 반영해보았는데, 
RanksTest를 작성해보니 당첨 결과에 대한 책임 분리가 매끄럽게 이루어지지 않은 것 같습니다. 
당첨결과 부분은 좀 더 고민이 필요한 부분 같습니다.

2024-03-31 08:37 UTC, duyankim commented on src/main/java/lotto/enums/RewardEnum.java
> +public enum RewardEnum {
enum이라고 이름을 꼭 붙일 필요는 없는 것 같습니다.

2024-04-01 01:11 UTC, testrace approved these changes
안녕하세요 😃 
피드백 반영 잘해주셨네요 👍 
몇 가지 코멘트를 남겨두었는데요
확인해 주시고 다음 단계에서 함께 반영 부탁드려요

2024-04-01 01:11 UTC, testrace commented on src/test/java/lotto/domain/LottoNumbersTest.java
> +        assertThat(lottoNumberList1.getNumbers()).isNotEqualTo(lottoNumberList2.getNumbers());
DisplayName에는 shuffle을 명시하고 있지만 
생성자에서 shuffle을 수행하는지 getNumbers에서 수행하는지 알기가 어려운데요
LottoNumbers의 책임이 shuffle이라면 이름을 LottoNumberShuffler 라고 지으면 어떨까요?
혹은 lottoNumbers.shuffle() 의 결과 두 개를 비교하면 어떨까요?
```java
LottoNumbers lottoNumberList = new LottoNumbers();
assertThat(lottoNumberList.shuffle()).isNotEqualTo(lottoNumberList.shuffle());
```

2024-04-01 01:11 UTC, testrace commented on src/test/java/lotto/domain/LottoTest.java
> +        assertThrows(IllegalArgumentException.class, () -> new Lotto(lottoNumbers).validate(lottoNumbers));
assertThrows 내부에 검증 대상이 new Lotto 생성자 인가요, validate 메서드인가요?
validate를 수행하지 않으면 6개가 아닌 개수로 로또를 생성할 수 있을 것도 같은데요
예외 검증시에는 테스트할 대상만 인자로 전달하면 어떨까요?

2024-04-01 01:11 UTC, testrace commented on src/test/java/lotto/domain/RankTest.java
> +        assertFalse(rank3.isMatching(5));
EnumSource를 활용해 중복 코드를 제거해 보셔도 좋을 것 같아요

2024-04-01 01:11 UTC, testrace commented on src/main/java/lotto/LottoApplication.java
> +        Set<Integer> winningNo = inputView.winningNo(inputView.getWinningNoInput());
당첨번호는 로또번호와 동일한 제약을 가져야합니다
로또 번호와 다른 제약을 가진 당첨 번호를 가진다면 로또를 구입하는 사람은 없을 것 같아요
<img width="267" alt="image" src="https://github.com/next-step/java-lotto/assets/8064743/f5a9e32b-2c4d-4bf8-a24d-45dcac60de54">

2024-04-01 01:11 UTC, merged

2024-04-06 06:22 UTC, duyankim commented on src/main/java/lotto/domain/LottoNumbers.java
> +public class LottoNumbers {
LottoNumbers를 NumbersGenertor로 명칭을 바꾸었습니다.
- 로또 번호 관리를 LottoFactory에서 하도록 이동하였습니다.
- Generator는 로또 번호 자동 추첨만 하는 책임으로 수정하였습니다.