[Step1] 문자열 계산기
next-step/java-lotto pull request #3740
Opened 2024-03-31 09:28 UTC by giraffeb

안녕하세요. 단계가 많이 늦었습니다.

아직도 많은 부분이 어색하네요.
사소한 부분도 모두 피드백 주시면 감사하겠습니다.

2024-04-01 13:57 UTC, ksy90101 requested changes
안녕하세요~
간단한 피드백을 남겼으니 참고해주세요~
구조를 변경해야 하는 부분이라서 Request Change를 한번 하겠습니다
언제든 궁금한게 있다면 DM주세요!

참고로 테스트 코드를 잘 작성하시네요 👍 
이번에 구조 변경을 하는것도 테스트코드가 있어서 잘 리팩토링 되지 않을까 생각이 드네요 ㅎㅎ

2024-04-01 13:57 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +    public int calc(){
축약어 보단, 풀 네임을 쓰는게 좋을거 같아요.

calculate같은 단어가 어울리겠네요!

2024-04-01 13:57 UTC, ksy90101 commented on src/main/java/calculator/calc/Calculator.java
> +public class Calculator {
이걸 한번 enum으로 만들어서 전략패턴처럼 해보면 어떨까요?

https://rutgo-letsgo.tistory.com/entry/OCP%EC%99%80-%EC%A0%84%EB%9E%B5%ED%8C%A8%ED%84%B4

위글을 한번 참고해보세요!

2024-04-01 13:57 UTC, ksy90101 commented on src/main/java/calculator/parse/ExpressionParser.java
> +    private String op;
의미잇는 단어를 쓰는걸 추천합니다.

2024-04-01 13:57 UTC, ksy90101 commented on src/main/java/calculator/ui/InputView.java
> +        Scanner scanner = new Scanner(System.in);
입력을 받을때마다 Scanner를 생성할 필요가 있을까요?

2024-04-11 05:26 UTC, giraffeb commented
피드백 주신 부분 반영해 보았습니다. 확인 부탁드리겠습니다.

2024-04-11 20:21 UTC, ksy90101 approved these changes
고생하셨습니다!
간단한 피드백을 남겼는데, 2단게 진행전에 적용해보시면 좋을거 같습니다!
2단계에서 같이 리뷰 요청 주시면 확인해볼게요~

언제든 질문이 있다면 DM주세요~ 홧팅입니다!

2024-04-11 20:21 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +    public int calculate(){
```suggestion
    public int calculate() {
```

이러한 띄어쓰기들을 잘 지켜보면 좋을거 같습니다.

IntelliJ에서는 reformat code 기능이 존재하는데 한번 사용해보시면 좋을거 같아요~

2024-04-11 20:21 UTC, ksy90101 commented on src/main/java/calculator/calc/Operator.java
> +        }
람다로 한번 써봐도 좋을거 같습니다!

2024-04-11 20:21 UTC, ksy90101 commented on src/main/java/calculator/calc/Operator.java
> +            return firstOperand / secondOperand;
secondOperand 해당 값이 0이 되면 어떻게 될까요?

2024-04-11 20:21 UTC, merged