Step4
next-step/java-lotto pull request #3768
Opened 2024-04-06 13:04 UTC by boy0516

안녕하세요!

4단계 리뷰 부탁드립니다.
에러 처리와 재입력 로직을 추가했습니다.

작성을 하다보니 LottoController의 로직이 너무 길어지는거같습니다. 
어떻게 코드를 정리해야하나요?

2024-04-07 01:45 UTC, wooobo requested changes
안녕하세요 지훈님!

4단계 잘진행해주셨습니다~
코멘트 남겨 놓았어요,
확인 후 재요청 부탁드려요~

2024-04-08 09:18 UTC, boy0516 commented on src/main/java/lotto/view/InputView.java
> +        }
파싱할 때 잘못된 폼으로 입력하면 오류가 발생하는데 임시로 처리해둔다는걸 그대로 둬버렸네요..

2024-04-08 13:03 UTC, wooobo requested changes
안녕하세요 지훈님!

코멘트 남겨 놓았어요~
확인 후 재요청 부탁드려요~

2024-04-08 13:03 UTC, wooobo commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos autoLottos = getAutoIssuedLottos(budget);
위는 저의 관점일 뿐입니다.

> 어떻게 코드를 정리해야하나요?

최고의 정리방법은 구현하면서 느꼈던 점을 상기시키면서 다시 구현하는거라고 개인적으론 생각합니다 🤔 
물론 그과정은 지루하고 괴롭고 번거롭겠지만요. 😂

2024-04-08 14:06 UTC, boy0516 commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos autoLottos = getAutoIssuedLottos(budget);
다시 구현한다면 어떻게 하면 좋을까요? 로또 생성에 대한 정보는 순차적으로 입력받는데 어떻게 객체지향적으로 개발할지 잘 모르겠습니다.

2025-03-26 14:12 UTC, closed without merging