3단계 - 로또(2등)
next-step/java-lotto pull request #3779
Opened 2024-04-10 15:30 UTC by jinnie-j

로또 3단계 리뷰 부탁드립니다 !

2024-04-11 14:55 UTC, mskangg requested changes
3단계 잘 구현해주셨네요!
몇가지 피드백남겼으니 확인부탁드립니다 🙇

2024-04-11 14:55 UTC, mskangg commented on src/main/java/lotto/domain/WinningLotto.java
> +    private final List<LottoNumber> lottoNumbers;
```suggestion
    private final Lotto lotto;
```

위와 같이 Lotto 를 갖고 있는게 더 어울려보여요!
로또가 6개에서 7개로 변한다거나, 1-50 까지의 숫자 요구사항이 변한다면, 같이 변해야하기 때문이에요 🤔

2024-04-11 14:55 UTC, mskangg commented on src/main/java/lotto/domain/LottoFactory.java
> +    public double calculateRateOfReturn(WinningLotto winningLotto, List<Lotto> lottos) {
계산을 하는 책임이 LottoFactory 클래스에 있는것이 어색하네요 🤔

2024-04-11 14:55 UTC, mskangg commented on src/main/java/lotto/domain/Rank.java
> +                .filter(rank -> rank != NONE)
https://github.com/next-step/java-lotto/pull/3760/files#r1551171766

피드백 반영이 안된것 같아요 😅

2024-04-14 15:22 UTC, jinnie-j commented
피드백이 맞게 반영되었는지 확인 부탁드립니다~̆̈!

2024-04-15 08:52 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요 💯 
그럼 다음 단계 진행해주세요! 🔥

2024-04-15 08:52 UTC, mskangg commented on src/main/java/lotto/domain/WinningLotto.java
> +    private final LottoNumber bonusNumber;
👍

2024-04-15 08:52 UTC, merged