[step4] 로또(수동)
next-step/java-lotto pull request #3783
Opened 2024-04-14 07:08 UTC by duyankim

안녕하세요. 4단계 미션 완료하였습니다.

상세한 리뷰 항상 감사드립니다.

2024-04-15 05:56 UTC, testrace requested changes
안녕하세요 😃 
4단계도 잘 구현해 주셨네요 👍 
소소하게 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-04-15 05:56 UTC, testrace commented on src/main/java/lotto/domain/Bonus.java
> +    public Bonus(int bonusNumber) {
Bonus 객체는 더 이상 책임이 없는 상태가 되었으니 제거하면 어떨까요?

2024-04-15 05:56 UTC, testrace commented on src/main/java/lotto/domain/LottoFactory.java
> +        if (buyingAmount < LOTTO_COST || buyingAmount / LOTTO_COST < manualLottoCount) {
조건이 추가되니 가독성이 낮아진 것 같아요
메서드 분리 등을 통해 가독성을 높이면 어떨까요?

2024-04-15 05:56 UTC, testrace commented on src/main/java/lotto/view/InputView.java
> +                .orElseThrow(() -> new IllegalArgumentException("값이 없습니다."));
optional로 변경하신 이유가 궁금합니다 🤔

2024-04-15 05:56 UTC, testrace commented on src/test/java/lotto/domain/LottoFactoryTest.java
> +        Lottos lottos = LottoFactory.createLottos(money, 0, new Lottos(0));
자동 로또를 생성하기 위해 항상 수동 로또`new Lottos(0)`를 전달해야하는데요 (반대도 마찬가지)
필요한 인자만 전달하도록 자동 구매와 수동 구매를 분리하면 어떨까요?

2024-04-16 03:15 UTC, duyankim commented on src/main/java/lotto/view/InputView.java
> +                .orElseThrow(() -> new IllegalArgumentException("값이 없습니다."));
미션 힌트에 'java8에 추가된 Optional을 적용해 NullPointerException이 발생하지 않도록 한다.'라는 항목이 있어 적용해보았습니다. 

sonarlint에서 Optional로 return된 값을 꼭 사용해야 한다고 안내가 나와서, 
현재는 다시 null 체크를 하는 방식으로 원복하였습니다.

2024-04-16 16:35 UTC, testrace approved these changes
피드백 반영 잘해주셨네요 👍 
로또 미션은 여기서 마무리 하겠습니다.
남은 미션도 화이팅입니다 🔥

2024-04-16 16:35 UTC, merged