2단계 - 로또(자동)
next-step/java-lotto pull request #3818
Opened 2024-10-08 14:36 UTC by Park1122

안녕하세요, 리뷰 부탁드립니다!
- 1단계 문자열 계산기 미션 리팩토링
- 2단계 로또(자동) 구현

2024-10-09 15:07 UTC, catsbi requested changes
정욱님, 리뷰가 좀 늦어 죄송합니다. 😢 
2단계 로또 미션 잘 진행해주셨는데, 고민해보면 좋을 부분들이 몇 보여 피드백 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2024-10-09 15:07 UTC, catsbi commented on src/main/java/step2/domain/Lotto.java
> +    public List<Integer> getNumbers() {
lotto.getNumbers().clear().addAll(list.of(1,2,3,4,5,6)); 

이런식으로 로또번호 위변조도 가능해보이는데, 불변성을 확보해야 하지 않을까요?

2024-10-09 15:07 UTC, catsbi commented on src/main/java/step2/domain/LottoMachine.java
> +    }
로또 생성은 임의로 섞은 자동로또 방식만 대응이 가능한 함수로 보이는데, 좀 더 유연성과 확장성을 챙길 수 없을까요?

2024-10-09 15:07 UTC, catsbi commented on src/main/java/step2/domain/LottoMachine.java
> +                .mapToInt(p -> p.getPrizeMoney() * countMap.getOrDefault(p.getMatchCount(), 0))
countMap의 key와 Prize의 key가 1:1 관계라는걸 가정하고 함수를 작성한 것 같으신데, 좀 더 명확하게 countMap의 key가 prize인게 낫지 않을까요?  관계까 1:1이 안될수도 있으니까요

2024-10-09 15:07 UTC, catsbi commented on src/main/java/step2/domain/LottoMachine.java
> +        return String.format("%.2f", (double) sum / cashAmount);
이익 계산율은 무조건 해당 수식으로 고정될까요?!

2024-10-09 15:07 UTC, catsbi commented on src/main/java/step2/view/ResultView.java
> +        System.out.println(sb.toString());
로직의 전체적인 가독성을 위해 적절히 출력 메세지의 성격에 따라 분리하여 가독성을 높힐 수 없을까요?

2024-10-09 15:07 UTC, catsbi commented on src/test/java/step2/LottoMachineTest.java
> +public class LottoMachineTest {
작성된 기능이 비해 작성돈 테스트가 너무 부족해보입니다. 
다음 포스팅을 참고하여 테스트 커버리지를 좀 더 높혀보면 좋을 것 같아요. 이번 미션의 과정이 미션개발이아니라 TDD(Test Driven Development)니까요 ㅎㅎ 

https://catsbi.oopy.io/7c084479-c9d0-44a1-acb9-f6b43a19e332

2024-10-11 08:17 UTC, Park1122 commented on src/main/java/step2/domain/LottoMachine.java
> +        return String.format("%.2f", (double) sum / cashAmount);
그나마 생각한 것은 소숫점 아래 단위에 대한 변경이 될 수도 있을거 같습니다.

2024-10-11 08:19 UTC, Park1122 commented on src/main/java/step2/LottoMain.java
> +        }
일단 해당 로직이 실제 비즈니스 로직 중에서 큰 비중을 차지한다면, 별도의 메소드로 빼서 테스트를 시도해보는 것도 좋을거 같습니다.

2024-10-11 09:26 UTC, catsbi commented on src/main/java/step2/domain/LottoMachine.java
> +        return String.format("%.2f", (double) sum / cashAmount);
@Park1122  도시별로 세율이 적용될수도 있고, 복권 회차별 정책이 바뀔수도 있고, 계산 수식자체가 바뀔수가 있겠죠 ㅎㅎ 
이런 정책(policy)들에 대한 유연성을 확보하고싶다면, 전략패턴을 활용해볼 수 있을 것 같아요 👍

2024-10-11 09:33 UTC, catsbi approved these changes
정욱님 로또 2단계 피드백 반영까지 잘 해주셨습니다 👍 

추가적으로 몇 가지 피드백 더 남겨드리긴 했는데, 큰 문제는 없기에 다음 미션에서 같이 참고해보는것으로 해요. 2단계 머지하도록 하겠습니다!

2024-10-11 09:33 UTC, catsbi commented on src/main/java/lotto/LottoMain.java
> +        }
Controller Layer에서 비즈니스 로직이 있다보니, 테스트 대상이 되야할 것 같네요. 서비스나 혹은 당첨확인 도메인을 만들어서 제공해도 분리해도 되지 않을까 싶네요.

2024-10-11 09:33 UTC, catsbi commented on src/main/java/lotto/constant/LottoConstant.java
> +public class LottoConstant {
별도의 상수만을 위한 상수 클래스는 권장드리지 않습니다. 
적절한 도메인 그리고 적절한 일급 객체로 해당 값들이 모두 옮겨질 수 있을 것 같네요.

2024-10-11 09:33 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
> +            throw new IllegalArgumentException("로또 번호는" + LottoConstant.LOTTO_SIZE + "개여야 합니다.");
예외메세지를 친절하게 잘 작성해주고 계시네요 👍

2024-10-11 09:33 UTC, catsbi commented on src/main/java/lotto/domain/Lotto.java
> +        if (numbers.stream().distinct().count() != LottoConstant.LOTTO_SIZE) {
numbers의 자료구조가 List가 아니라 Set이라면 단순 사이즈만 체크해도 되지 않을까요?

2024-10-11 09:33 UTC, catsbi commented on src/main/java/lotto/domain/LottoMachine.java
> +    }
생성자 내에서 별도의 로직을 수행하는건 권장드리지 않아요 객체 "생성" 외의 로직은 사용자가 의도치 않은 사이드 이펙트를 발생할 수 있어요. 그래서 안티패턴에 속합니다. 이럴 경우 차라리 정정 팩토리 메서드 패턴을 활용하시는것을 권장드리니다 👍

2024-10-11 09:33 UTC, catsbi commented on src/main/java/lotto/domain/LottoMachine.java
> +    }
불변성 확보 👍

2024-10-11 09:33 UTC, merged