2단계 - 로또(자동)
next-step/java-lotto pull request #3826
Opened 2024-10-09 09:07 UTC by JeonJe

안녕하세요 민수님!

2단계 - 로또(자동) 리뷰 요청드립니다.

객체의 역할 간단하게 작성하여 같이 공유드립니다!

# 객체 
## LottoGame
로또 게임을 실행합니다. 
- InputView를 통해 사용자로부터 입력을 받고, ResultView로 사용자에게 결과를 출력합니다.
- 로또 기계에게 금액을 전달하여 로또 티켓을 발행받습니다. 
- 로또 티켓과 당첨번호를 LottoResultCalculator로 전달하여 로또 결과를 받습니다.
- 로또 결과와 상금정보를 LottoProfitCalculator로 전달하여 수익률을 받습니다.
## LottoMachine
- 로또를 발행합니다. 로또 번호를 발행할 수 있는 전략을 주입받습니다.
## WinningNumber
- 당청번호를 가지고 있습니다. 로또 티켓 번호와 당첨번호를 비교할 수 있습니다.
## LottoPrize
-  로또 당첨 등수에 따른 당첨금액을 가지고 있습니다.
## LottoResult
- 로또에서 몇 개의 번호가 맞았는지를 저장하고 있습니다.
## LottoResultCalculator
- 티켓과 당첨번호를 통해 로또의 당첨 등수와 횟수를 계산합니다.
## LottoProfitCalculator
- 로또 당첨 등수 & 횟수 결과와 당첨 금액을 통해 수익률을 계산합니다.
## LottoNumberStrategy
### RandomNumberStrategy
- 로또 번호를 랜덤하게 생성합니다.
### FixedNumberStrategy
- 테스트용으로 로또 번호를 지정할 수 있습니다.
## LottoTicket
- 로또 번호를 가지고 있습니다.
## InputView
- 사용자로부터 입력을 받습니다.
## ResultView
- 사용자에게 결과를 출력합니다.

2024-10-10 08:21 UTC, mskangg requested changes
2단계 정말 잘해주셨네요!
전략패턴에 예외테스트까지 정말 꼼꼼하게 잘 짜주셨네요 👍 💯 
몇가지 피드백 남겨드렸는데, 확인하시고 반영부탁드립니다~! 🙇

2024-10-10 08:21 UTC, mskangg commented on README.md
> +  - [x] ArrayList의 contains() 메소드를 활용하면 어떤 값이 존재하는지 유무를 판단
체크리스트 👍

2024-10-10 08:21 UTC, mskangg commented on src/main/java/lotto/Application.java
> +        LottoGame lottoGame = new LottoGame(new InputView(), new ResultView());
👍

2024-10-10 08:21 UTC, mskangg commented on src/main/java/lotto/prize/LottoPrize.java
> +    private static final int MATCHED_SIX_LOTTO_NUMBER_PRIZE = 2000000000;
enum 으로 등수와 상금을 갖게 표현할 수 있을것 같아요 :)

2024-10-10 08:21 UTC, mskangg commented on src/main/java/lotto/winningnumber/WinningNumber.java
> +public class WinningNumber {
LottoTicket 과 다른점이 무엇일까요? 
공통된 사항이 많은것 같아요 🤔

만약 다른게 있다면, LottoTikect 을 WinningNumber 가 갖게 하는 방향으로 하는건 어떨까요?

2024-10-10 08:21 UTC, mskangg commented on src/main/java/lotto/ticket/LottoTicket.java
> +    }
👍

2024-10-10 08:21 UTC, mskangg commented on src/test/java/lotto/strategy/FixedLottoNumberStrategy.java
> +public class FixedLottoNumberStrategy implements LottoNumberStrategy {
👍

2024-10-10 08:21 UTC, mskangg commented on src/main/java/lotto/result/LottoResult.java
> +public class LottoResult implements Comparable<LottoResult> {
Prize 를 enum 으로 관리하고 Prize 별로 당첨 수를 판단하면 수익률도 계산할 수 있으니 이 클래스는 필요가 없을것 같아요 :)

2024-10-10 08:21 UTC, mskangg commented on src/main/java/lotto/strategy/LottoNumberStrategy.java
> +public interface LottoNumberStrategy {
👍

2024-10-10 08:21 UTC, mskangg commented on src/test/java/lotto/calculator/LottoResultCalculatorTest.java
> +        LottoMachine lottoMachine = new LottoMachine(new FixedLottoNumberStrategy(List.of(1, 2, 3, 4, 5, 6)));
👏

2024-10-10 08:21 UTC, mskangg commented on src/test/java/lotto/ticket/LottoTicketTest.java
> +    }
예외 테스트 👍

2024-10-10 08:21 UTC, mskangg commented on src/main/java/lotto/ticket/LottoTicket.java
> +    private final List<Integer> lottoNumbers;
로또공이라는 값객체를 선언할 수 있을것 같아요 :)

2024-10-11 11:30 UTC, JeonJe commented on src/main/java/lotto/prize/LottoPrize.java
> +    private static final int MATCHED_SIX_LOTTO_NUMBER_PRIZE = 2000000000;
enum LottoPrize을 사용하도록 변경하였습니다. 클래스로 구현했을 때는 다른 곳에서 계속 클래스를 주입받았어야 했는데 그럴 필요가 없어져서 코드가 훨씬 깔끔해졌습니다👍

2024-10-11 11:32 UTC, JeonJe commented on src/main/java/lotto/winningnumber/WinningNumber.java
> +public class WinningNumber {
WinningNumber와 LottoTicket 모두 로또 번호를 들고 비슷한 기능을 수행하고 있어서 LottoBalls로 묶었습니다. LottoBalls안에는 LottoNumber 객체를 두어 로또 숫자 범위값을 체크하도록 책임을 분리해보았습니다.

2024-10-11 11:36 UTC, JeonJe commented on src/main/java/lotto/result/LottoResult.java
> +public class LottoResult implements Comparable<LottoResult> {
LottoResult와 Calculator를 제거하고, 아래와 같은 구조로 변경하였습니다.
PrizeCountr - 발행한 로또티켓과 당첨숫자로 당첨 횟수를 PrizeCount에게 카운팅하라고 메시지를 보냅니다.
PrizeCount - 당첨 횟수를 카운트합니다. 횟수를 가지고 있기 때문에 Prize Enum을 사용하여 총상금과 수익률을 계산합니다.

2024-10-12 08:56 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요!
추가적인 피드백 남겨드렸는데, 이부분은 다음 단계 진행하시면서 같이 고민해주세요!
그럼 화이팅 🔥

2024-10-12 08:56 UTC, mskangg commented on src/main/java/lotto/number/LottoBalls.java
> +    private static void validateNumberOfLottoNumbers(Set<Integer> lottoNumbers) {
static 일 필욘 없을것 같아요 :)

2024-10-12 08:56 UTC, mskangg commented on src/main/java/lotto/number/LottoNumber.java
> +    }
👍

2024-10-12 08:56 UTC, mskangg commented on src/main/java/lotto/prize/LottoPrize.java
> +public enum LottoPrize {
👍

2024-10-12 08:56 UTC, mskangg commented on src/main/java/lotto/prize/PrizeCount.java
> +    private final Map<Integer, Integer> prizeCountMap;
EnumMap 으로 Prize 가 키로 있는게 의미상 전달이 잘될것 같기도 하네요.
어떻게 생각하시나용?

2024-10-12 08:56 UTC, mskangg commented on src/main/java/lotto/strategy/RandomLottoNumberStrategy.java
> +public class RandomLottoNumberStrategy implements LottoNumberStrategy {
👍

2024-10-12 08:56 UTC, merged

2024-10-12 09:13 UTC, JeonJe commented on src/main/java/lotto/number/LottoBalls.java
> +    private static void validateNumberOfLottoNumbers(Set<Integer> lottoNumbers) {
이 부분 놓쳤네요. 감사합니다!!