step1 - 문자열 계산기
next-step/java-lotto pull request #3837
Opened 2024-10-10 07:38 UTC by seulpi

안녕하세요.
리뷰 요청드립니다.

2024-10-10 11:52 UTC, nooose requested changes
안녕하세요, 슬비님! 리뷰어 성준혁입니다. 👋
구현해 주신 enum을 더 활용해 볼 수 있을 것 같아 코멘트 남겼어요.
수정 후 다시 요청 부탁드립니다!

2024-10-10 11:52 UTC, nooose commented on src/main/java/controller/Calculator.java
> +    public void start() {
1단계에도 MVC 패턴이 적용되었네요 👍👍

2024-10-10 11:52 UTC, nooose commented on src/main/java/controller/Calculator.java
> +        // 로직
요건 뭘까요 ?_?

2024-10-10 11:52 UTC, nooose commented on src/main/java/controller/Calculator.java
> +        Integer calculatedValue = calculatorService.calculate(inputValue);
```suggestion
        int calculatedValue = calculatorService.calculate(inputValue);
```
래퍼클래스일 필요가 있을까요?

null을 다루지 않는다면 primitive 타입을 사용하는 것이 적절할 것 같습니다.

2024-10-10 11:52 UTC, nooose commented on src/main/java/service/CalculatorImpl.java
> +public interface CalculatorImpl {
interface인데 구현체를 뜻하는 Impl 접미어가 붙어있네요 😲
Impl 접미어를 제거해도 되지 않을까요?

2024-10-10 11:52 UTC, nooose commented on src/main/java/service/Preprocessor.java
> +        return true;
```suggestion
        return !calculationFormula.isBlank();
```
한줄로 줄여볼 수 있겠네요

2024-10-10 11:52 UTC, nooose commented on src/main/java/service/Preprocessor.java
> +            return values;
```suggestion
            return Collections.emptyList();
```
비어있는 리스트를 반환할 때 `emptyList` 사용을 권장드립니다. 왜 그럴까요?

2024-10-10 11:52 UTC, nooose commented on src/main/java/service/Preprocessor.java
> +    private final Pattern compile = Pattern.compile("\\d+|[+\\-*/]");
```suggestion
    private static final Pattern compile = Pattern.compile("\\d+|[+\\-*/]");
```
클래스마다 고정된 값을 가져갈테니 클래스 변수로 선언하면 더 좋을 것 같습니다!

2024-10-10 11:52 UTC, nooose commented on src/main/java/constants/Operator.java
> +    , DIVISION("DIVISION", "/");
```suggestion
      PLUS("+", new Plus())
    , MINUS("-", new Minus())
    , MULTIPLICATION("*", new Multiplication())
    , DIVISION("/", new Division());
    
    public int operate(num1, num2) {
        this.operator.calculate(num1, num2)
    }
```
만들어둔 연산자들을 위 방식으로 만들어보면 어떨까요?

2024-10-10 11:52 UTC, nooose commented on src/main/java/service/CalculatorService.java
> +        }
만드신 Operator enum을 활용하면 제거할 수 있는 코드같아요 😄

2024-10-10 11:52 UTC, nooose commented on src/test/java/CalculatorTest.java
> +public class CalculatorTest {
제일 중요한 연산 테스트가 없네요 🥲

2024-10-11 09:05 UTC, seulpi commented on src/main/java/controller/Calculator.java
> +        // 로직
이 부분은 제가 로직을 구현해야 된다고 표시해둔것인데 지우지 않고 커밋한것 같습니다ㅠㅠ

2024-10-11 09:06 UTC, seulpi commented on src/main/java/controller/Calculator.java
> +        Integer calculatedValue = calculatorService.calculate(inputValue);
넵, 해당 코드 작성할때 null도 리턴할 수 있다는 부분을 고려해서 로직을 만들려고 했는데

2024-10-11 09:09 UTC, seulpi commented on src/main/java/service/CalculatorImpl.java
> +public interface CalculatorImpl {
보통 회사에서 impl을 많이 사용해서 interface 이름을 짓기도 하는데 제거하고 사용하는게 더 가독성이 있는걸까요?
아무래도 저렇게 많이 사용하다 보니 저는 저게 더 한번에 알 수 있을것같아 사용하게 되었는데
사용하지 않는다면 어떻게 이름을 짓는게 더 적절한 예시일까 궁금합니다!

2024-10-11 09:12 UTC, seulpi commented on src/test/java/CalculatorTest.java
> +public class CalculatorTest {
아무래도 테스트 코드를 작성할때 고민이 되는 부분이 있는데요.
제가 지금 테스트 코드를 작성한게 단위테스트보다 통합테스트에 더 가까운거 맞나요?
단위테스트를 쪼개는 부분이 아직은 좀 많이 어렵다보니 한번에 로직을 그냥 호출하게 되어버려 그런것 같습니다.
method 단위별로 테스트 코드를 작성하는게 좋을까요?

2024-10-11 09:15 UTC, seulpi commented on src/main/java/service/Preprocessor.java
> +            return values;
아마 new ArrayList()를 생성하면 계속해서 빈 객체를 생성해서 할당하는데 emptyList를 사용하면 계속해서 생성하지 않고 동일한 인스턴스를 반환해서 메모리 성능의 효율성도 높이고 가독성도 좋아져서일까요?

2024-10-11 09:18 UTC, seulpi commented on src/main/java/controller/Calculator.java
> +        Integer calculatedValue = calculatorService.calculate(inputValue);
아, 궁금한게 있는데 예전에 듣기론 반환타입을 primitive타입보단 객체 타입을 사용하는게 좋다고 들었는데 
그게 맞는 말인지 좀 궁금합니다.
( 그 이유는 null을 반환할수도 있기 때문이라고 들었습니다.)

2024-10-11 14:12 UTC, nooose commented on src/main/java/controller/Calculator.java
> +        Integer calculatedValue = calculatorService.calculate(inputValue);
보너스를 주제로해서 정말 간단한 상황으로 예시를 들어볼게요

### 보너스가 int 타입일 때 
보너스를 줬지만 알고리즘으로 인해 0원이 지급될 수 있습니다.
이러면 보너스를 안 받았는지, 받았는데 0원인지 헷갈릴 수 있습니다.

### 보너스가 Integer 일 때
보너스를 받지 않으면 null, 받았다면 실제 값이 할당됩니다.

실제 로직은 이렇지 않지만... 이렇게 null 인 상황이 필요하냐 안하냐로 나뉘기 때문에 
맞고 틀리고는 없고 상황에 따라 다를 것 같습니다 😄

추가로 제네릭을 다룰 때 primitive 타입을 사용할 수 없기 때문에 래퍼 클래스를 사용합니다

2024-10-11 14:29 UTC, nooose approved these changes
안녕하세요 슬비님 
잘 반영된 것 같네요!
1단계 머지할게요
수고하셨습니다!

2024-10-11 14:29 UTC, nooose commented on src/main/java/service/CalculatorService.java
> +        }
```suggestion
        Optional<Operator> operator = Operator.find(calculateTarget);
```
null을 반환하는 대신 Optional을 사용해봐도 좋을 것 같아요
null 반환이 싫다면 find 내부에서 찾지못했을 때 예외를 던지는 방법도 있겠네요!

2024-10-11 14:29 UTC, nooose commented on src/test/java/CalculatorTest.java
> +        boolean isEmpty = preprocessor.verificationOfInputValue(value);
`verificationOfInputValue`이 public 노출될 필요는 없을 것 같아요
process 메소드만으로 검증할 수 있다고 생각합니다.

2024-10-11 14:29 UTC, nooose commented on src/test/java/CalculatorTest.java
> +    }
테스트로 볼 수 있을까요?

테스트에는 행위를 검증하는 부분이 꼭 있어야합니다.

2024-10-11 14:29 UTC, nooose commented on src/test/java/CalculatorTest.java
> +public class CalculatorTest {
> 아무래도 테스트 코드를 작성할때 고민이 되는 부분이 있는데요. 제가 지금 테스트 코드를 작성한게 단위테스트보다 통합테스트에 더 가까운거 맞나요? 단위테스트를 쪼개는 부분이 아직은 좀 많이 어렵다보니 한번에 로직을 그냥 호출하게 되어버려 그런것 같습니다. method 단위별로 테스트 코드를 작성하는게 좋을까요?

추가 테스트코드 잘 작성해 주셨습니다.
public 메소드만 검증하셔도 좋습니다.

Operator enum을 테스트하는 케이스가 있었으면 더 좋았을 것 같아요!
```java
var 결과 = Opeartor.find("+").calculate(3, 5);
assertThat(결과).isEqualTo(8);
```

2024-10-11 14:29 UTC, merged