3단계 - 로또(2등)
next-step/java-lotto pull request #3846
Opened 2024-10-11 13:53 UTC by ksh9891

안녕하세요 리뷰어님 :)
3단계 미션 완료하여 PR 요청드려요
리뷰 자세하게 해주셔서 감사드립니다.
이번에도 잘 부탁드리겠습니다

2024-10-11 15:43 UTC, jinyoungchoi95 requested changes
안녕하세요 상현님 😄

몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-11 15:43 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoRank.java
> +public enum LottoRank {
enum 활용 👍

2024-10-11 15:43 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoRank.java
> +        return lottoRank;
`matchedNumeber`와 더불어 `LottoRank`가 `isMatchedBonusNumber`의 사용유무도 판단하도록해주면 이런 분기처리로직이 없어도 되지 않을까요?

2024-10-11 15:43 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoRank.java
> +    private final int matchedNumber;
(반영하지 않으셔도 됩니다.) 어떻게보면 `NONE`은 0, 1, 2의 모든 `matchedNumber`를 가지고 있는 것이므로 List로 관리해도 좋을 것 같네요 :)

2024-10-11 15:43 UTC, jinyoungchoi95 commented on src/test/java/lotto/domain/LottoRankTest.java
> +    @DisplayName("5개의 번호가 일치하고, 보너스번호가 일치하다면 2등이 반환된다.")
👍

2024-10-11 15:43 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/Lotto.java
> +        }
null인 `LottoNumber`로 비교하는 것은 예외 상황이 아닐까요?

2024-10-11 15:43 UTC, jinyoungchoi95 commented on src/main/java/lotto/view/LottoInputView.java
> +        return lottoNumber;
보너스 번호가 당첨 번호가 중복될 수 없다는 것은 어떻게보면 로또라는 도메인의 로직이라고 보여져요. View에서 이런 로직을 처리하기보다는 당첨 번호와 보너스 번호를 가진 객체를 만들고 해당 객체 생성시에 이런 검증을 처리하면 View에서 해당 로직을 분리해낼 수 있을 것 같네요 😄

2024-10-11 15:43 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static final int MAX_NUMBER = 45;
public으로 수정 후 파편화는 막을수있기는 한데요, 제가 드렸던 리뷰의 의도는 `LottoNumber`에서 private으로 완전히 막음으로써 1과 45에 대한 책임 자체를 `LottoNumber`가 관리할 수 있게끔 하도록 하는 것이었어요.

예를 들면 `LotttoNumber`가 ALL_LOTTO_NUMBERS를 모두 넘겨받고 이런 로직을 만들 수도 있겠죠.
```java
private static final int MIN_NUMBER = 1;
private static final int MAX_NUMBER = 45;
private static final List<LottoNumber> ALL_LOTTO_NUMBERS;

// ...

public static List<LottoNumber> getNewLottoNumbers(int generateCount) {
    // generateCount가 소유한 List의 갯수보다 많은 경우 예외
    // 섞는 로직
    // count 갯수만큼 리턴
}
```

2024-10-12 12:36 UTC, ksh9891 commented on src/main/java/lotto/domain/Lotto.java
> +        }
네 예외 상황이므로 정상적인 반환값이 아닌, 예외를 던지는게 맞는 것 같습니다

2024-10-12 14:17 UTC, ksh9891 commented
안녕하세요. 리뷰어님 :)
리뷰 해주신 내용 확인 후 수정하여 다시 PR 드립니다.

2024-10-12 14:24 UTC, ksh9891 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static final int MAX_NUMBER = 45;
이 부분에서 질문이있습니다.
1. 도메인 종속 상수(MIN_NUMBER, MAX_NUMBER)를 public 접근 제어자로 선언하는 것이 적절한 경우는 언제인지 궁금합니다
2. LottoNumber 클래스가 단일 로또 번호 관리와 번호 목록 생성 두 가지 책임을 동시에 가지게 된 것으로 보이는데, 이렇게 작성하게 되면 단일책임원칙을 위반한 것이 아닌지 궁금합니다.

2024-10-12 15:05 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static final int MAX_NUMBER = 45;
> 1. 도메인 종속 상수(MIN_NUMBER, MAX_NUMBER)를 public 접근 제어자로 선언하는 것이 적절한 경우는 언제인지 궁금합니다!
적절한 경우를 정의하는 건 따로 없는 것 같고 설계단에서 도메인에 응집가능하도록 설계가 가능하면 지양하는 편이에요.

> 2. LottoNumber 클래스가 단일 로또 번호 관리와 번호 목록 생성 두 가지 책임을 동시에 가지게 된 것으로 보이는데, 이렇게 작성하게 되면 단일책임원칙을 위반한 것이 아닌지 궁금합니다
로또 번호 관리는 원래 가지고 있던 책임이고, 번호 목록 생성도 어떻게보면 생성이라는 새로운 책임이라기보다는 본인이 관리하던 번호를 반환하는 행위이기 때문에 다른 책임으로 보이지는 않아요.

단일 책임 원칙이라는 것이 사실 하나의 책임을 가져야한다는 원칙이나 이 관점 자체가 매우 주관적이기 때문에 객관적으로 원칙을 벗어났다라고 판단하기가 매우 힘든 원칙 중의 하나인데요. 개인적인 팁은 변경의 여파를 보는 것입니다. 본인이 가지는 책임이 아닌 다른 책임을 분산하여 가졌다면 변경의 여파가 다른 클래스로 불필요하게 전파되므로 이는 책임을 벗어난 경우에 해당하고, 본인의 수정에 따른 여파가 없다면 단일 책임 원칙을 지켰다라고 볼 수도 있는거죠.

2024-10-12 15:11 UTC, jinyoungchoi95 approved these changes
안녕하세요 상현님 😄

피드백 잘 반영해주셨네요 👍 몇가지 코멘트 남겨두었는데 다음 미션 진행하시면서 함께 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-12 15:11 UTC, merged