1단계 - 문자열 계산기
next-step/java-lotto pull request #3862
Opened 2024-10-13 01:37 UTC by sunggyun-jo

2024-10-13 02:45 UTC, testrace requested changes
안녕하세요 성균님 😃 
로또 미션을 함께 하게 된 송용주입니다.
1단계 깔끔하게 잘 구현해 주셨네요 👍 
누락된 테스트가 있어 코멘트 남겼습니다.
확인해 주시고 다시 리뷰 요청해 주세요.

2024-10-13 02:45 UTC, testrace commented on README.md
> +- [x] 피연산자 + 연산자 + 피연산자 순서대로 반복해서 계산한다.
기능 분리 힌트를 참고해서 조금 더 구체적인 기능 목록을 작성해 보시면 좋을 것 같아요.

2024-10-13 02:45 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +    private void parse(String text) {
>프로그램 요구사항
>메소드의 크기가 최대 10라인을 넘지 않도록 구현한다.
method가 한 가지 일만 하도록 최대한 작게 만들어라.

메서드를 분리해 보시면 좋을 것 같아요

2024-10-13 02:45 UTC, testrace commented on src/main/java/calculator/Operator.java
> +    Integer operate(Integer left, Integer right);
원시 타입을 활용하면 어떨까요?

2024-10-13 02:45 UTC, testrace commented on src/main/java/calculator/Operators.java
> +            "/", (left, right) -> left / right
Operator의 구현이 총 4가지가 있습니다.
모두 단위 테스트 대상으로 봐야하지 않을까요?

2024-10-13 02:45 UTC, testrace commented on src/main/java/calculator/Operators.java
> +    public static Operator getOperator(String key) {
테스트가 누락되었네요 😢

2024-10-13 02:45 UTC, testrace commented on src/main/java/calculator/StringCalculator.java
> +        return new Calculator(text).calculate();
calculate 메서드를 한 번 더 호출하면 어떻게 될까요?
```java
Calculator calculator = new Calculator("2 + 3 * 4 / 2");
calculator.calculate();
calculator.calculate();
```

2024-10-13 02:45 UTC, testrace commented on src/test/java/calculator/StringCalculatorTest.java
> +        assertThat(StringCalculator.calculate("2 + 3 * 4 / 2")).isEqualTo(10);
테스트의 설명이 없어서 10이라는 결과가 맞나 생각이 들 수 있을 것 같아요
사칙연산의 우선순위가 아닌 입력 순 연산한다는 내용을 DisplayName에 추가하면 어떨까요?

2024-10-13 08:28 UTC, sunggyun-jo commented on README.md
> +- [x] 피연산자 + 연산자 + 피연산자 순서대로 반복해서 계산한다.
기능 목록 더 상세하게 작성하였습니다~!

2024-10-13 08:29 UTC, sunggyun-jo commented on src/main/java/calculator/Calculator.java
> +    private void parse(String text) {
연산자, 피연산자를 구하는 부분들을 별도 메서드로 분리 하였습니다.

2024-10-13 08:31 UTC, sunggyun-jo commented on src/main/java/calculator/Operators.java
> +            "/", (left, right) -> left / right
단위 테스트 추가했습니다~!

2024-10-13 08:32 UTC, sunggyun-jo commented on src/main/java/calculator/Operators.java
> +    public static Operator getOperator(String key) {
단위 테스트 추가 했습니다~!

2024-10-13 08:32 UTC, sunggyun-jo commented on src/main/java/calculator/StringCalculator.java
> +        return new Calculator(text).calculate();
calculate 호출했을 때 항상 동일한 결과 반환하도록 개선했습니다.

2024-10-13 08:34 UTC, sunggyun-jo commented on src/test/java/calculator/StringCalculatorTest.java
> +        assertThat(StringCalculator.calculate("2 + 3 * 4 / 2")).isEqualTo(10);
DisplayName 추가했습니다

2024-10-13 08:38 UTC, sunggyun-jo commented on src/main/java/calculator/Operator.java
> +    Integer operate(Integer left, Integer right);
int 원시타입으로 변경 하였습니다~!

2024-10-14 01:53 UTC, testrace approved these changes
안녕하세요 성균님 😃 
피드백 반영 잘해주셨네요 👍 
몇 가지 코멘트 남겼으니 확인해 주시고 다음 단계 진행해 주세요

2024-10-14 01:53 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +
```suggestion
```

2024-10-14 01:53 UTC, testrace commented on src/main/java/calculator/Calculator.java
> +        Integer right = operand.poll();
여기서도 null을 허용하지 않는다면 원시타입을 활용해 보시면 좋을 것 같아요

2024-10-14 01:53 UTC, testrace commented on src/main/java/calculator/Operators.java
> +    private static final Map<String, Operator> operators = Map.of(
```suggestion
    private static final Map<String, Operator> OPERATORS = Map.of(
```

2024-10-14 01:53 UTC, testrace commented on src/test/java/calculator/StringCalculatorTest.java
> +    }
사칙 연산 기능은 Operators 에 구현이 되어 있으니 OperatorsTest 클래스를 만들어 이동하면 좋을 것 같아요.

2024-10-14 01:53 UTC, testrace commented on src/test/java/calculator/StringCalculatorTest.java
> +    }
위 코멘트와 동일합니다.
예외를 발생시키는 로직은 Operators 클래스에 존재합니다.

2024-10-14 01:53 UTC, testrace commented on src/test/java/calculator/StringCalculatorTest.java
> +    }
앞의 코멘트에 이어 두 테스트도 클래스를 분리하면 어떨까요?
테스트 코드도 유지보수 대상이니 중복된 테스트를 제거하면 좋을 것 같아요

2024-10-14 01:53 UTC, merged