3단계 - 로또(2등)
next-step/java-lotto pull request #3871
Opened 2024-10-13 13:05 UTC by sinyebin

안녕하세요 로또 3단계 리뷰 부탁드립니다!
저번 피드백중 로또 번호 랜덤 생성하는 것을 정적 변수로 만들어 두어 사용하는 것이 있었는데 이를 반영하여 따로 클래스를 분리하여 static메소드로 만들었는데 이렇게 해도 되는걸까요?

2024-10-13 16:04 UTC, jinyoungchoi95 requested changes
안녕하세요 예빈님 😄

3단계 잘 진행해주셨네요 👍 몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-13 16:04 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoNumbers.java
> +    }
테스트에도 적어두었는데 이런 생성자를 추가해두면 List를 처리하지 않아도되어서 좀 더 유연한 객체 생성을 도와줄 수 있을 것 같네요 :) 

```java
public LottoNumbers(Integer... lottoNumbers) {
    this(Arrays.stream(lottoNumbers).collect(toList()));
}
```

2024-10-13 16:04 UTC, jinyoungchoi95 commented on src/test/java/lotto/domain/WinningLottoTest.java
> +        );
assertAll은 모든 assertion을 함께 테스트해보기 위함으로 함께 합쳐주는 것이 좋습니다 :)

2024-10-13 16:04 UTC, jinyoungchoi95 commented on src/test/java/lotto/domain/LottoTest.java
> +        assertThat(lotto.getLottoResult(winningLotto)).isEqualTo(SECOND);
공백은 줄일수록 가독성을 올려주기보다는 적절한 공백이 오히려 가독성을 올려주기 때문에 적절하게 줄바꿈을 통해서 가독성을 올려주시면 좋을 것 같아요 😄

2024-10-14 13:42 UTC, sinyebin reviewed
피드백 반영하였습니다!
기존 LottoNumbers를 LottoNumber로 변경하여 로또 번호 1개만을 갖게 하여 int 형식으로 변경하였으며, 
Lotto를 List<LottoNumber>로 변경하였습니다.
그리고 2등을 계산하는 로직을 LottoRank로 옮겼습니다.

2024-10-14 15:46 UTC, jinyoungchoi95 approved these changes
안녕하세요 예빈님 😄

남겨둔 코멘트는 다음 단계 진행하시면서 함께 참고부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-14 15:46 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
(반영하지 않으셔도 됩니다.) 결국 1부터 45의 숫자만 사용한다고 생각하면 생성자를 막고 `List<LottoNumber>`를 본인이 들고있으면서 캐싱의 개념으로 사용하는 방법도 있어요.

그러면 지금 어플리케이션에서 1이라는 번호는 요청올때마다 새로운 객체를 생성하는 것이 아닌 동일한 `LottoNumber`를 재사용할 수 있도록 하는 것이죠. 이럴 때 사용되는 것이 정적팩토리메소드이기도 하구요. `Integer` 구현체도 동일한 방식으로 구현되어있으니 기회가 되시면 해당 구현체 내용을 뜯어보시는 것도 도움이 되실 것 같습니다 😄

2024-10-14 15:46 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
```suggestion
    public static List<Integer> generateAutoLottoNumbers(int requestSize) {
        List<Integer> numbers = new ArrayList<>(randomLottoNumbers);
        Collections.shuffle(numbers);
        return numbers.subList(0, requestSize);
    }
```
(반영하지 않으셔도 됩니다.) 의도했던 바는 이런식으로 요청값을 받는 것이에요. 결국 6이라는 `Lotto`가 가질 수 있는 갯수로 `Lotto`에서만 관리된다고 생각한다면 `Lotto`는 6이라는 상수를 가지고 이 메소드를 호출하도록하면 필요한 도메인 정보가 응집할 수 있겠죠 :)

2024-10-14 15:46 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoRank.java
> +    NONE(0, 0, 0, false);
(반영하지 않으셔도 됩니다.) matchCount라는 것은 일치하는 갯수를 나타내는 것이고 `NONE`은 따지고보면 0, 1, 2 개 모두 포함되는 값이니 matchCount라는 단일값보다는 List로 matchCounts를 가질 수 있도록 하는 것이 더 적절할 수 있어요.

예를들어 `matchRank`메소드에서의 문제는 matchCount가 6이하의 값이 들어온다는 가정하에 7개가 들어오면 `NONE`으로 반환하게 되는에 이는 에러케이스에 해당하니까요. List로 관리하게되면 7개가 들어온다고 하더라도 마지막 처리를 `orElseThrow`로 예외에 대한 처리를 할 수 있고 1 혹은 2와 같은 값이 들어온다고 하더라도 `NONE`에 필터링되는 안정적인 로직을 만들 수 있을 것 같아요 😄

2024-10-14 15:46 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/Lotto.java
> +        if (lottoNumbers.size() != 6) {
6과 같은 정보는 `Lotto` 번호의 갯수로 상수로 표현되면 좋을 것 같네요 :)

2024-10-14 15:46 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/Lotto.java
> +        this.lottoNumbers = makeLotto(lottoNumbers);
여기도 부생성자로 표현되어 주생성자를 사용하는 형태로 사용한다면, 주생성자로 객체 생성의 안정성을 지키며 부생성자로 여러 객체 생성에 대한 유연성을 보장하는 좋은 생성자 모델이 될 수 있습니다 :)

2024-10-14 15:47 UTC, merged