2단계 - 문자열 덧셈 계산기
next-step/java-lotto pull request #3887
Opened 2024-10-15 00:56 UTC by kdfasdf

안녕하세요 승훈님!
2단계 미션 어느정도 정리 된 것 같아 리뷰 요청 드립니다
이번에도 부족한 부분이나 고민할만한 내용 알려주시면 감사하겠습니다!!

2024-10-15 11:21 UTC, csh0034 requested changes
2단계 구현 수고 많으셨습니다 😄 
몇가지 코멘트 남겨두었는데 확인 부탁드려요!

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/README.md
> +## 기능 목록
기능목록 먼저 작성후 수정해주신점 좋네요 💯

main/java 패키지는 코드가 위치하는곳이므로 최상단으로 README.md 를 옮겨보시면 좋을것 같아요!

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> lotto;
로또번호가 1 ~ 45 이라는것을 검증하거나 값 객체로 분리해보는건 어떨까요?

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/domain/Lottos.java
> +    public Lottos() {
인자없는 생성자가 필요한걸까요? 🤔

만약 객체 생성후에 buyLotto 를 호출하지 않는다면 불완전한 객체가 됩니다.
생성자 또는 정적팩토리메서드를 사용하여 생성시점에 내부 값을 가지고있도록 해보시면 좋을것 같아요!

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/domain/Prize.java
> +    public static int getValueByHit(int hit) {
`indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.` 를 지켜보시면 좋을것 같아요!

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/domain/WinningNumber.java
> +    private final List<Integer> winningNumber = new ArrayList<>();
WinningNumber 와 Lotto 클래스로 표현해볼순 없을까요? 🤔

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/domain/WinningNumber.java
> +        return stringWinningNumber.split(", ");
어떠한 문자로 구분될지는 ui 에 영역이라고 생각해요.
즉, 도메인이 ui 에 의존적이므로 고민해보시면 좋을것 같아요!

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/domain/WinningCheck.java
> +public class WinningCheck {
Lottos 에게 당첨번호를 전달하여 당첨정보를 계산해볼순 없을까요? 🤔

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/JavaLotto.java
> +public class JavaLotto {
1단계에서 학습한 MVC 구조를 적용해볼때 JavaLotto 와 Main 은 컨트롤러라고 볼 수 있지 않을까요? 🤔

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/service/WinningStatistic.java
> +package lotto.service;
service 라는 패키지를 사용하기보다 도메인에 비지니스로직을 담당하게 한후에 
적절하게 필요한 부분에 할당해 보시면 좋을것 같아요!

2024-10-15 11:21 UTC, csh0034 commented on src/main/java/lotto/JavaLotto.java
> +    public void playLotto() {
`함수(또는 메소드)의 길이가 15라인을 넘어가지 않도록 구현한다`

개행을 제거하면 15라인이 넘진 않지만 기능을 적절하게 분리해보시면 좋을것 같습니다.

2024-10-15 11:22 UTC, csh0034 commented
pr 제목이 문자열 덧삼 계산기로 되어있네요 😄

2024-10-16 05:26 UTC, kdfasdf commented on src/main/java/lotto/domain/WinningNumber.java
> +        return stringWinningNumber.split(", ");
단순 입출력만이 UI의 역할이 될 수 있다는 고정관념을 가졌던 것 같습니다😅

2024-10-16 05:28 UTC, kdfasdf commented on src/main/java/lotto/domain/WinningNumber.java
> +    private final List<Integer> winningNumber = new ArrayList<>();
입력 문자를 `,` 로 구분해야 한다는 점에서 기존의 Lotto와 구분된다고 생각했었는데 해당 로직을 View로 옮긴다면 Lotto 클래스로 표현해볼 수 있을 것 같습니다!

2024-10-16 05:38 UTC, kdfasdf commented on src/main/java/lotto/service/WinningStatistic.java
> +package lotto.service;
이번에 기능 목록 작성하면서 한 객체가 가질 책임을 적게해보려고 노력했는데요. 그 결과 불필요한 서비스 계층이 생기고 관리해야할 코드가 많아졌던 것 같네요. 오히려 객체의 책임을 조금 늘리고 어떤 메시지를 보낼지 고민해보니까 불필요한 서비스계층이랑 JavaLotto playLotto 메서드의 복잡도를 낮춰  전체적인 코드량을 줄일 수 있었네요.

2024-10-16 05:53 UTC, kdfasdf commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> lotto;
LottoNumber 클래스로 감싸주어 1 - 45 값을 보장하도록 해보았습니다. LottoNumber 클래스를 구현하면서 연쇄적으로 고친부분이 많아 개인적으로 이부분이 제일 어려웠던 것 같습니다😅

2024-10-16 05:54 UTC, kdfasdf commented
안녕하세요 승훈님!
피드백 반영했다고 생각하여 다시 리뷰 요청 드립니다!
감사합니다!!

2024-10-16 16:36 UTC, csh0034 requested changes
코멘트 반영 잘해주셨네요 😄 
도메인에 대한 단위테스트도 작성해보시면 좋을것 같습니다.
추가로 몇가지 코멘트 추가로 남겨두었는데 확인 부탁드려요!

2024-10-16 16:36 UTC, csh0034 commented on src/test/java/lotto/service/WinningStatisticTest.java
> +public class WinningStatisticTest {
제거된 부분에 대한 테스트네요!
해당 로직을 처리하는 도메인 코드 테스트로 옮겨보시면 좋을것 같습니다.

2024-10-16 16:36 UTC, csh0034 commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
원시값 wrapping 클래스 추가 👍
검증부분에 대한 단위테스트도 추가해보시는건 어떨까요?

2024-10-16 16:36 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(List<LottoNumber> lotto) {
중복이 있는지와 6개인지를 체크해야하지 않을까요? 🤔

2024-10-16 16:36 UTC, csh0034 commented on src/main/java/lotto/domain/Lottos.java
> +    private int LottoWinningStatus(Lotto lotto, Lotto winningLotto) {
메서드 명이 대문자로 시작하네요 🥲

추가로 lotto 로 부터 모두 값을 꺼내와서 비교하고있습니다.
lotto 에게 다른 lotto 를 인자로 보내서 몇개가 일치하는지 메세지는 보내는 방식으로 개선해보시면
좋을것 같아요!

2024-10-16 16:36 UTC, csh0034 commented on src/main/java/lotto/domain/Lottos.java
> +    public Stack<Integer> calculateStatistic(int totalPrize, Stack<Integer> stack) {
Stack 당첨결과를 표현하기에 적절한 타입이 아닌것 같아요.

Prize 별 당첨수를 표현하는 형태로 처리해보시는건 어떨까요?

2024-10-16 16:36 UTC, csh0034 commented on src/main/java/lotto/controller/JavaLotto.java
> +        resultView.printResult(lottos.calculateStatistic(prize, new Stack<>()));
calculateStatistic 가 두번 호출되고있네요!

당첨 통계를 구하는데 Stack 을 보내는부분이 필요한걸까요? 🤔
위에 드린 코멘트와 같이 Prize 별로 몇개가 당첨되었는지만 반환하여 계산해보는건 어떨까요?

2024-10-17 04:17 UTC, kdfasdf commented on src/main/java/lotto/controller/JavaLotto.java
> +        resultView.printResult(lottos.calculateStatistic(prize, new Stack<>()));
저도 저부분 다시 읽어보니 Stack이 메서드 내에서 어떤 용도로 쓰이는지 바로 파악이 안돼는 것 같네요ㅋㅋㅋ 메서드에 메시지를 보낼 때 비즈니스적으로 의미있는 것만을 보내고 자료구조가 필요하다면 메서드 구현부에서 선언하고 반환하는게 더 나은방식일까요?(피드백은 이렇게 진행하긴 했습니다)

2024-10-17 04:37 UTC, kdfasdf commented
안녕하세요 승훈님!
피드백 반영했다고 생각하여 다시 리뷰 요청 드립니다!! 
감사합니다!!
추가로 기존에 Lottos가 가지고 있던 calculateProfit 메서드와 calculateStatistic 메서드는 Lottos가 가지는 상태값에 대해서 연산을 하는 것이 없어 Prize로 옮겨보았습니다!

2024-10-18 00:55 UTC, csh0034 approved these changes
리뷰 반영 잘해주셨네요!
몇가지 코멘트 남겨두었는데 다음단계
진행하시면서 고민해주시면 좋을것 같습니다 😄

2024-10-18 00:55 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    private void validDuplicate(List<LottoNumber> lotto) {
list 를 set 에 인자로 전달하고 size 가 같은지로 검증도 가능하겠네요!

2024-10-18 00:55 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +                .collect(Collectors.joining(" ","중복 요소: ","가 하나 이상 존재"));
예외 메세지에 대한 내용은 커스텀 예외인 LottoDuplicateNumberException 에서 처리해야하지 않을까요?

2024-10-18 00:55 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    public int lottoWinningStatus(Lotto lotto, Lotto winningLotto) {
자기 자신인 lotto 를 전달 받을 필요가 있을까요? 🤔

2024-10-18 00:55 UTC, csh0034 commented on src/main/java/lotto/domain/Lottos.java
> +    public int getWinningPrize(Lotto winningLotto) {
현재 모든 상금을 더한후에 Prize 에서 다시 Map 으로 만들고 있네요!
Lottos 에서 `Map<Prize, Integer>` 형태로 반환해보는건 어떨까요?

2024-10-18 00:55 UTC, csh0034 commented on src/main/java/lotto/domain/Prize.java
> +    public static LinkedHashMap<Prize, Integer> calculateStatistic(int totalPrize) {
반환타입엔 변경가능하므로 가능한 추상화된 타입을 쓰는것을 권장드립니다.

`Map<Prize, Integer> `

2024-10-18 00:55 UTC, csh0034 commented on src/main/java/lotto/controller/JavaLotto.java
> +        resultView.printResult(lottos.calculateStatistic(prize, new Stack<>()));
네 맞습니다. 이경우 LottoResult 등과 같이 로또 통계또는 로또 결과등의 대상을 추가하여 Lottos 에서 반환하도록 해볼수도 있겠네요!

2024-10-18 00:55 UTC, merged

2024-10-18 11:49 UTC, kdfasdf commented on src/main/java/lotto/domain/Lotto.java
> +    private void validDuplicate(List<LottoNumber> lotto) {
커스텀 예외에 어떤 요소도 중복되는지 알려주면 좋겠다 생각해 부득이하게 코드량이 늘어나는 방향으로 진행하였습니다.😅

2024-10-18 11:49 UTC, kdfasdf commented on src/main/java/lotto/domain/Lotto.java
> +                .collect(Collectors.joining(" ","중복 요소: ","가 하나 이상 존재"));
앗... 그러네요 하나를 생각하면 하나를 놓치네요...😵

2024-10-18 11:53 UTC, kdfasdf commented on src/main/java/lotto/domain/Lottos.java
> +    public int getWinningPrize(Lotto winningLotto) {
처음에 lottos 에서 Prize로 calculateProfit 메서드와 calculateStatisti 메서드를 옮긴 것은 테스트 코드의 량을 줄이기 위해서였는데요 enum 클래스 내에 가지고 있는 상수를 이용하는 것이라도 enum 클래스 내에서  비즈니스 로직을 수행되는 것이 권장되지 않는건가요?