Step1- 문자열 계산기
next-step/java-lotto pull request #3906
Opened 2024-10-16 14:15 UTC by lee-won-suk

안녕하세요, 1단계 문자열 계산기 미션 Pull request 드립니다.

감사합니다.

2024-10-16 17:42 UTC, csh0034 requested changes
안녕하세요. 원석님!
로또 미션을 함께하게 된 최승훈입니다. 

1단계 문자열 계산기 구현 관련하여 
몇가지 코멘트 남겨두었는데 확인해주시고
다시 리뷰 요청 부탁드립니다!

미션을 진행하면서 궁금하신 사항 있으시면
편하게 DM 주세요 😄

2024-10-16 17:42 UTC, csh0034 commented on src/main/java/step1stringcalculator/README.md
> +## 기능 명세
main/java 의 경우 코드가 위치하는곳이므로 
최상단 README.md 로 옮겨 보시면 좋을것 같습니다.

추가로 `[x]`, `[ ]`체크박스를 통해 표현해보시는것도 좋을것 같아요!

## 기능 명세

- [x] 기능1
- [x] 기능2
- [ ] 기능3

2024-10-16 17:42 UTC, csh0034 commented on src/main/java/step1stringcalculator/CurrentNumber.java
> +public class CurrentNumber {
CurrentNumber 라는 이름이 어떤걸 표현하는지 명확하지 않은것 같아요.

`클린코드 2장, 의미있는 이름` 에 대해서 찾아보시고 적절한 네이밍을 고민해보시면 좋을것 같습니다.

2024-10-16 17:42 UTC, csh0034 commented on src/main/java/step1stringcalculator/CurrentNumber.java
> +    public void choiceCalculate(String currentOperator, int nextNumber) {
프로그래밍 요구사항을 보면 else 를 사용하지 않는 요구사항이 있습니다.

연산자에 따라 다르게 동작하는 부분은 Enum 을 적용해보는 방식으로 고민해보시면 좋을것 같습니다.

2024-10-16 17:42 UTC, csh0034 commented on src/main/java/step1stringcalculator/InputView.java
> +public class InputView {
1단계의 경우 입출력 처리등은 고려하지 않고 기능 구현 및 단위테스트   
작성을 TDD 로 구현해 보시면 좋을것 같습니다 🙂

2024-10-16 17:42 UTC, csh0034 commented on src/main/java/step1stringcalculator/CalculatorString.java
> +public class CalculatorString {
String 이라는 이름은 java 에서 문자열 타입을 뜻하므로 적절한 이름에 대해서 고민해 보시면
좋을것 같아요!

2024-10-16 17:42 UTC, csh0034 commented on src/main/java/step1stringcalculator/Calculator.java
> +public class Calculator {
`계산기에서 계산식을 받아 결과를 반환한다고` 하면 Calculator CalculatorString CurrentNumber  
등으로 분리하지 않을수 있을것 같습니다!

만약 분리해야한다면 명확한 이름과 책임에 대해서 고민후에 적용해보시면 좋을것 같아요!

2024-10-16 17:42 UTC, csh0034 commented
### 1. 커밋메세지 

AngularJS Commit Message Conventions 포맷에 대해서 찾아보시고 적용해보시는걸 추천드립니다.
또한 `1단계 문자열 계산기` 등의 문구는 커밋메세지에 포함하지 않고 기능만 표현해보시면 좋을것 같습니다.

### 2. 패키지명 

패지키명에도 동일하게 step1 등은 제거해보시면 좋을것 같아요!

### 3. gitkeep 삭제

.gitkeep 의 경우 디렉토리 유지를 위해 존재하므로 코드를 커밋해 주셨기 때문에 제거해주셔됩니다!

2024-10-17 10:52 UTC, lee-won-suk commented on src/main/java/step1stringcalculator/README.md
> +## 기능 명세
감사합니다 맨 끝에 붙여보았을때는 계속 뜨지 않았는데 앞에다 붙이면 됐었군요..! 
수정 완료했습니다.

2024-10-17 11:15 UTC, lee-won-suk commented on src/main/java/step1stringcalculator/CurrentNumber.java
> +public class CurrentNumber {
감사합니다. 저 객체의 목적은 현재까지 계산된 숫자를 저장하려는 필드를 감싼 것이었기 때문에,
CurrentCalculationResult로 변경해보았습니다.

2024-10-17 14:33 UTC, lee-won-suk commented on src/main/java/step1stringcalculator/CurrentNumber.java
> +    public void choiceCalculate(String currentOperator, int nextNumber) {
enum을 사용해서 메서드를 분기하는 방식은 생각해보지 못했네요 감사합니다. enum을 추가해서 구현해보았습니다

2024-10-17 14:35 UTC, lee-won-suk commented on src/main/java/step1stringcalculator/InputView.java
> +public class InputView {
넵 입출력기능은 우선 main 메서드로 이관해서 수정했습니다.

2024-10-17 14:43 UTC, lee-won-suk commented on src/main/java/step1stringcalculator/CalculatorString.java
> +public class CalculatorString {
감사합니다. 숫자와 사칙연산 기호가 추가된 문자열이니 MathExpression으로 수정해보았습니다.

2024-10-17 15:45 UTC, lee-won-suk commented on src/main/java/step1stringcalculator/Calculator.java
> +public class Calculator {
좋은 말씀 감사합니다.
분리하지 않는 것도 생각해 보았으나, 문자열 및 원시값을 가급적 포장하고 싶어서 그대로 분리하는 것으로 생각했습니다. 왜냐하면 결국 계산식은  문자열값이기 떄문입니다.
다만 CurrentNumber(CurrentCalculationResult)값의 경우, MathExpression에 의존하고 있는데요, 이건 Calculator 클래스으로 책임을 넘기는게 낫겠다고 판단해서 수정했습니다.

2024-10-18 06:52 UTC, csh0034 approved these changes
코멘트 반영하시느라 수고 많으셨습니다 😄 
몇가지 추가로 남겨두었는데 다음단계 진행전에 
고민해보시면 좋을것 같아요!

2024-10-18 06:52 UTC, csh0034 commented on src/main/java/stringcalculator/MathOperator.java
> +public enum MathOperator {
enum 과 추상메서드로 잘 표현 해주셨네요 💯

2024-10-18 06:52 UTC, csh0034 commented on src/main/java/stringcalculator/MatcherUtil.java
> +public class MatcherUtil {
util 의 경우 static 키워드를 사용하여 객체 생성을 하지 않는것이 일반적입니다.

현재 객체지향을 연습하고 있으므로 과정중엔 util 보단 명확한 이름과 책임을 가지는 대상을
추가해보시면 좋을것 같아요!

2024-10-18 06:52 UTC, csh0034 commented on src/main/java/stringcalculator/Calculator.java
> +    public void checkMathExpression() {
생성한 이후 외부에서 checkMathExpression 를 호출하지 않을수 있기 때문에
생성자에서 호출하도록 해보시면 좋을것 같아요!

2024-10-18 06:52 UTC, csh0034 commented on src/main/java/stringcalculator/MathOperator.java
> +        return null;
null 을 반환하기보단 예외를 발생하는것이 어떨까요? 🤔

2024-10-18 06:52 UTC, csh0034 commented on src/test/java/stringcalculator/CarculatorTest.java
> +
개행은 제거해보시면 좋을것 같아요 🙂

2024-10-18 06:52 UTC, merged

2024-10-19 05:49 UTC, lee-won-suk commented on src/main/java/stringcalculator/MathOperator.java
> +public enum MathOperator {
감사합니다 :) 저도 if문 말고 enum 메서드로 표현하는 방법도 있다는걸 느낄 수 있었네요!

2024-10-19 06:41 UTC, lee-won-suk commented on src/test/java/stringcalculator/CarculatorTest.java
> +
불필요한 개행이 있었네요 제거 완료했습니다.

2024-10-19 07:14 UTC, lee-won-suk commented on src/main/java/stringcalculator/MathOperator.java
> +        return null;
좋은 의견 감사합니다. throw하도록 수정했습니다.

2024-10-19 07:22 UTC, lee-won-suk commented on src/main/java/stringcalculator/Calculator.java
> +    public void checkMathExpression() {
생각해보지 못했던 관점 같습니다. 필수로 호출이 필요한 로직에 강제성을 부여하는 느낌으로 이해했습니다.
감사합니다