4단계 - 로또(수동)
next-step/java-lotto pull request #3931
Opened 2024-10-19 07:02 UTC by sinsu1004

안녕하세요. 리뷰어님!
4단계 - 로또(수동)을 완료했습니다.
리뷰 부탁드리겠습니다. :)

2024-10-19 23:31 UTC, seondongpyo requested changes
마지막 단계도 잘 진행해주셨네요 👍 
조금만 더 개선해보면 좋을 것 같아서 몇 가지 코멘트 드렸습니다.
확인 후 다시 리뷰 요청 부탁 드리겠습니다 🔥

2024-10-19 23:31 UTC, seondongpyo commented on src/main/java/lottogame/domain/lotto/Lottos.java
> +                .map(lotto -> Rank.from(lotto.countMatchingNumbers(winningLotto.getWinningLotto()), lotto.isMatchingBonus(winningLotto.getBonusNumber())))
Nit: `WinningLotto`를 기준으로 당첨 결과를 비교하도록 변경해보고 차이점을 비교해보시는 것도 좋을 것 같습니다.
```suggestion
                .map(lotto -> Rank.from(winningLotto.countMatchingNumbers(lotto), winningLotto.isMatchingBonus(lotto)))
```

2024-10-19 23:31 UTC, seondongpyo commented on src/main/java/lottogame/domain/lotto/Lottos.java
> +    public double calculateTotalPrizeAmount(WinningLotto winningLotto) {
위에서 계산한 당첨 결과(`Map<Rank, Integer>`)를 담는 클래스를 만들고, 해당 클래스 내부에서 총 당첨 금액을 계산하도록 해보면 어떨까요? 지금은 총 당첨 금액을 구하기 위해 `calculateWinningStatistics()`처럼 로또 당첨 결과를 다시 한 번 계산하는 게 다소 비효율적이지 않나란 생각이 듭니다.

2024-10-19 23:31 UTC, seondongpyo commented on src/main/java/lottogame/domain/lotto/WinningLotto.java
> +public class WinningLotto {
👍

2024-10-19 23:31 UTC, seondongpyo commented on src/main/java/lottogame/ui/LottoOutputView.java
> +        System.out.printf("수동으로 %d장, 자동으로 %d개를 구매했습니다.\n", manualCount, autoCount);
- `printf()`를 호출한다면 줄바꿈 문자 `\n` 대신에 위처럼 `%n`을 사용해보시면 좋을 것 같습니다.
- 줄바꿈 문자를 사용하신다면 플랫폼에 독립적인 줄바꿈 문자를 사용해보시면 어떨까요?
https://www.baeldung.com/java-string-newline#2-using-platform-independent-line-separators

2024-10-21 12:22 UTC, sinsu1004 commented on src/main/java/lottogame/domain/lotto/Lottos.java
> +    public double calculateTotalPrizeAmount(WinningLotto winningLotto) {
변경하겠습니다 :)

2024-10-21 23:43 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍 
로또 미션은 여기서 마무리하도록 하겠습니다.
그동안 미션 진행하시느라 고생 많으셨고, 마지막까지 완주하시길 응원하겠습니다 🔥

2024-10-21 23:43 UTC, seondongpyo commented on src/main/java/lottogame/domain/lotto/WinningResult.java
> +public class WinningResult {
👍

2024-10-21 23:43 UTC, seondongpyo commented on src/test/java/lottogame/domain/LottoGameServiceTest.java
> +    @DisplayName("당청 로또를 생성한다.")
```suggestion
    @DisplayName("당첨 로또를 생성한다.")
```

2024-10-21 23:43 UTC, merged