feat : 로또 > Step3 - 로또 (2등)
next-step/java-lotto pull request #3932
Opened 2024-10-19 08:18 UTC by BananMoon

### step2 피드백 반영 및 질문 (refactor)
refactor
- null일 가능성을 제거하여 null 체크 로직을 제거한다. (피드백 반영)
-  functional interface 역할을 하는 인터페이스에 `@FunctionalInterface`를 명시적으로 붙여주자. (피드백 반영)
- 클래스 이름을 적절하게 수정한다. (LottoRankingSystem -> LottoRank) (피드백 반영)
- LottoWinningStatistics 초기화 방식 변경에 따른 테스트 코드 추가
- 사용자가 구입한 금액을 관리하는 로또 금액(LottoPrice) 객체를 생성하고 필요한 메서드를 생성한다.
	> "status 메소드를 푸는거보다는 LottoPrice를 생성하는게 더 나을 것 같네요."
	> 👉 `validatePurchaseAmount()` static 메서드로 처리하는 것보다는 `LottoPrice` 객체를 만드는 것을 얘기해주신 것으로 이해했습니다.
	>  로또 금액을 객체로 만들고 이 객체를 만들 때 유효성을 체크하도록 수정했습니다 !
	>  > 로또 금액의 역할
	>  > - 사용자의 구매 금액을 갖고 있는다.
	>  > - 로또 구매 가격이 최소 1000원 이상인지 체크한다.
	>  > - 구매한 로또 갯수를 계산하여 반환한다.
- 불변 객체이므로 깊은 복사하지 않아도 된다.
- 함수형 인터페이스가 유지되도록 `@FunctionalInterface` 를 추가한다.
- 로또 랭킹에 들지 않는 0~2개의 로또 매칭 갯수도 LottoRank 상수로 관리한다.
	> `LottoWinningStatistics` 객체를 생성할 때 랭킹에 포함되지 않는 로또들도 모두 '등수에 포함되지 않는다는 의미의 enum' 필드로 저장하고,  
	> 출력할 때는 해당 필드를 제외하고 출력하도록 하는 것으로 이해했습니다. 
	> 좋은 방법인 것 같은데 리뷰어님이 말씀해주신 방법을  
	> 어떤 의도로 접근해야 하는지 확실하게 와닿지는 않는 것 같아요..!
	> 0~2개 당첨된 로또도 동일하게 enum으로 관리해주는게 좋은 방향이라 그런 걸까요??

### step3 구현 사항 (feature)
- 사용자 로또번호와 보너스볼이 매칭되는지 확인한다.  (pr 생성하고 나니 보였는데, 커밋이 두개로 나눠져 들어가고 커밋 메세지도 잘못 남겨졌네요.. 🙏🏻)
- 로또 랭킹 2등을 추가한다.
- feat: 로또 랭킹 별 설명 값을 반환한다.

#### 참고 사항
-  README에 기능 요구사항 분리 내용을 작성였습니다.

2024-10-20 06:12 UTC, jinyoungchoi95 requested changes
안녕하세요 윤지님 😄

3단계 잘 진행해주셨네요 👍 몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-20 06:12 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoRank.java
> +    }
출력문을 도메인에서 가지는 것을 의도한 피드백은 아니었기 때문에 해당 로직은 모두 view에서 처리해주세요 :)

2024-10-20 06:12 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoPrice.java
> +
```suggestion
    public float value() {
        return this.lottoPrice;
    }

```
이미 반환 타입에 어떻게 반환될 것인지 표현이 되기 때문에 메소드 이름에서는 가능하면 반환 타입을 지정해줄 필요는 없습니다. List와 같은 것들도 마찬가지이구요.

2024-10-20 06:12 UTC, jinyoungchoi95 commented on src/main/java/lotto/LottoInterface.java
> +        LottoPrice lottoAmountPurchased = new LottoPrice(InputView.getLottoPricePurchased());
실행이 안되는 것 같아요 :) 

<img width="1111" alt="스크린샷 2024-10-20 오후 3 08 26" src="https://github.com/user-attachments/assets/f9dda5d1-3c7d-4c60-b6bc-321af81e6ff6">

2024-10-20 06:12 UTC, jinyoungchoi95 commented on src/main/java/lotto/application/LottoWinningStatistics.java
> +    public LottoWinningStatistics(List<Lotto> userLottos, Lotto winningLotto, LottoNumber bonusBall) {
`Lotto`와 `LottoNumber`를 가지는 로또 당첨번호라는 도메인 클래스를 만들어보면 어떨까요? `LottoRank`를 계산해주는 책임을 넘겨줄 수 있을 것 같네요 :)

2024-10-20 12:00 UTC, BananMoon commented on src/main/java/lotto/domain/LottoRank.java
> +                .filter(value -> value.getMatchingCount() == matchingCount)
보너스 볼 매칭 여부와 랭킹에 포함되지 않는 매칭 카운트를 LottoRank enum에서 관리할 수 있는 방법을 알맞게 생각해내지 못했네요. 
로직이 더 간단해지네요 👍

2024-10-20 12:15 UTC, BananMoon commented on src/main/java/lotto/LottoInterface.java
> +        LottoPrice lottoAmountPurchased = new LottoPrice(InputView.getLottoPricePurchased());
흑.. 이런 실수를..! 추가 커밋했습니다

2024-10-20 12:28 UTC, BananMoon commented on src/main/java/lotto/application/LottoWinningStatistics.java
> +    public LottoWinningStatistics(List<Lotto> userLottos, Lotto winningLotto, LottoNumber bonusBall) {
😮😮!! 
로또를 개발하는 과정에서 저도 '로또의 당첨번호 클래스가 필요하지 않을까'를 고민했던 적이 있는데
리뷰어님이 말씀주셨던 것처럼 `LottoRank`를 계산하는 책임을 넘기려는 의도로 그렇게 생각하지는 못했고

로또 당첨번호가 여러 로직에서 사용되는 듯해서 별도 클래스를 둘까 고민을 했었는데요

리뷰어님은, LottoRank를 생성하기 위해 필요한 로직이 `LottoWinningStatistics` 클래스에 있는 것이 적절하지 않다는 생각에서 출발하여(?) 말씀해주신 걸까요?? 

(생각의 과정이 궁금해서 질문드립니다 ㅎㅎ)

2024-10-20 14:56 UTC, jinyoungchoi95 commented on src/main/java/lotto/application/LottoWinningStatistics.java
> +    public LottoWinningStatistics(List<Lotto> userLottos, Lotto winningLotto, LottoNumber bonusBall) {
말씀해주신 내용보다는 요구사항을 분석해보았을때 "당첨 로또"는 "로또번호"와 "보너스번호"를 가진다에서 시작하여 출발한 것 같아요 :)

2024-10-20 14:58 UTC, jinyoungchoi95 approved these changes
안녕하세요 윤지님 😄

피드백 잘 반영해주셨네요 👍 다음미션 진행해주세요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-20 14:58 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/WinningLotto.java
> +    private final LottoNumber lottoNumber;
```suggestion
    private final LottoNumber bonuslottoNumber;
```
보너스 번호임을 명시해주는건 어떨까요?

2024-10-20 14:58 UTC, merged

2024-10-21 03:05 UTC, BananMoon commented on src/main/java/lotto/application/LottoWinningStatistics.java
> +    public LottoWinningStatistics(List<Lotto> userLottos, Lotto winningLotto, LottoNumber bonusBall) {
기능 관점에서만 요구사항을 추가해갔는데, 객체 관점으로도 생각해야겠군요 ! 👍