로또 2단계 코드 리뷰 요청
next-step/java-lotto pull request #3933
Opened 2024-10-19 16:05 UTC by coongya

안녕하세요.
로또 미션 2단계 코드 리뷰 요청 드립니다.

아직 적절한 역할과 책임을 가지는 객체를 분리하는 것이 어려운 것 같습니다.
특히 LottoResults 클래스를 따로 분리하는 것이 맞는지 그리고 LottoResults를 만드는 역할을 Lottos 내부에 getResults()로 구현하는게 맞는지 헷갈리는데 피드백 부탁드립니다!!

그리고 아직 TDD cycle에 따라 단위테스트를 구현하고 리팩토링하는 방식이 익숙하지 않은 것 같습니다ㅠㅠ
특히 기능 요구사항을 작은 단위로 쪼개서 기능 목록을 작성하는 것이 어렵게 느껴지는데 좀 더 쉽게 작성할 수 있는 방법이 있다면 알려주시면 감사하겠습니다.
제 README.md 파일에 작성한 기능목록은 단순히 미션 2단계 페이지에 써있는 기능 요구사항을 그대로 옮겨다 놓은 것에 불과한 것 같아요.
TDD cycle로 개발할 수 있도록 더 작은 기능 단위로 쪼개서 작성하는 기준이나 방법이 있다면 알려주시면 감사하겠습니다!!

2024-10-20 12:59 UTC, jinyoungchoi95 requested changes
안녕하세요 소현님 😄

몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/main/java/lotto/Lotto.java
> +    }
```suggestion
    public int countMatchingNumbers(Lotto otherLottoNumbers) {
        return (int) otherLottoNumbers.lottoNumbers
                .stream()
                .filter(lottoNumbers::contains)
                .count();
    }
```
객체를 서로 호출하도록하면 같은 `Lotto`객체이므로 외부에서 getter를 따로 호출하여 선언할 필요가 없을 것 같아요 😄

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/test/java/lotto/LottoTest.java
> +        assertThat(lotto.countMatchingNumbers(Arrays.asList(1, 2, 3, 4, 5, 6))).isEqualTo(6);
1. `assertAll`을 사용하면 여러 테스트가 동작할때 테스트 실패로 인해 돌아가지 않는 테스트 없이 모든 테스트실행 결과 여부를 확인할 수 있습니다.
2. 가능하면 하나의 테스트에서는 하나의 케이스를 검증하도록 하는 것이 좋아요. 3개가 일치하는 경우와 6개가 일치하는 경우는 똑같은 메소드를 쓰기는 하지만 "상황"자체가 다르기 때문에 테스트를 하나의 문서로 보는 관점에서는 이들을 분리해주시는 것이 조금 더 테스트 가독성이 올라갈 수 있습니다 :)

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/main/java/lotto/LottoRankEnum.java
> +    FIRST(2000000000),
```suggestion
    FIRST(2_000_000_000),
```
숫자의 경우 세자리 간격으로 `_`를 달아주시면 가독성에 도움이 됩니다 :)

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/main/java/lotto/Lottos.java
> +    private static final int SIX = 6;
매칭되는 갯수는 여기에 두지 말고 `LottoRankEnum`에 필드로 두면 어떨까요?

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/main/java/lotto/LottoRankEnum.java
> +public enum LottoRankEnum {
```suggestion
public enum LottoRank {
```
클래스 네임에 enum을 굳이 명칭할 필요는 없을 것 같아요 😄

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/main/java/lotto/Lottos.java
> +    }
화면에 출력되는 부분은 모두 도메인 로직에 해당하므로 자동차때와 동일하게 `View`로 옮겨주세요 :)

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/test/java/lotto/LottosTest.java
> +    }
```suggestion
    private Lottos lottos = new Lottos(Arrays.asList(
            new Lotto(Arrays.asList(1, 2, 3, 4, 5, 6)),
            new Lotto(Arrays.asList(1, 2, 3, 7, 8, 9)),
            new Lotto(Arrays.asList(7, 8, 9, 10, 11, 12)))
    );
    private Lotto lastWinningLotto = new Lotto(Arrays.asList(1, 2, 3, 4, 5, 6));
```
junit의 기본 라이프사이클은 테스트메소드당이기 때문에 바로 선언해주셔도 되어요.

https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/test/java/lotto/LottosTest.java
> +    }
일반적으로 테스트에서 모든 테스트에서 쓰이는 기본값의 경우에 대해서는 테스트 메소드 외부에서 선언하여 공통되게 사용하지만 해당 데이터의 경우 `로또_결과`에만 국한되어 사용될 것으로 보여 테스트 내부로 이동해주시는 것이 좋을 것 같아요.

bdd(given-when-then)에서 given에 대해서 학습해보시면 도움이 될 것 같네요 :)

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/main/java/lotto/LottoMain.java
> +        int quantity = amount / LOTTO_PRICE;
계산하는 로직도 도메인 로직이므로 Main, View가 아닌 도메인 코드로 넘겨주세요 :) 

로또를 실행하는데 사용되는 모든 정책은 도메인이라고 생각해주시면 되어요.

2024-10-20 12:59 UTC, jinyoungchoi95 commented on src/main/java/lotto/LottoMain.java
> +    private static List<Integer> createLottoNumbers() {
이런 로직도 도메인에 해당 될 것 같네요 ~

2024-10-22 17:01 UTC, coongya commented on src/main/java/lotto/Lotto.java
> +    private static final String DELIMITER = ",";
안녕하세요🙇🏻‍♀️. 해당 피드백과 관련해서 질문이 있습니다..!
지난 라이브 강의 때 Test Fixture를 만들 때 생성자를 활용하는 것이 좋다고 하셔서 Lotto의 생성자를 두 가지로 만들었습니다.
하나는 파라미터로 String을 받고, 하나는 List<Integer> lottoNumbers를 받아서 로또 객체를 생성합니다.
String으로 로또 번호를 받는 경우 직접 ,로 분리해서 this()를 호출하는데요!
이렇게 생성자를 다양하게 활용하는 것과 들어온 입력값을 ,로 분리하는 역할은 View가 가지는 것이 맞다라는 두 가지 관점 중에 어느 것이 더 적절한지 판단할 수 있는 기준이 있는지 궁금합니다!

2024-10-23 16:52 UTC, jinyoungchoi95 commented on src/main/java/lotto/Lotto.java
> +    private static final String DELIMITER = ",";
어떤 관점이 더 적절하다기보다는 view를 어디까지를 바라보느냐에 따라서 달라요. 저는 입력시 화면에 출력되는 조건 자체를 바라보았기 때문에 생성자가 아닌 view에서 처리되길 말씀드린 내용이었고, delimiter 자체까지도 로또의 도메인이라고 생각하면 그럴수도 있는거죠 :)

2024-10-23 16:56 UTC, jinyoungchoi95 approved these changes
안녕하세요 소현님 😄

남겨둔 코멘트는 다음 미션 진행하면서 함께 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-23 16:56 UTC, jinyoungchoi95 commented on src/main/java/lotto/InputView.java
> +public class InputView {
생성자를 사용하지 않는다면 private으로 막아주는 것도 좋을 것 같아요 :)

2024-10-23 16:56 UTC, jinyoungchoi95 commented on src/main/java/lotto/Lotto.java
> +                });
이렇게 돌리면 예를들어 46, 1, 2, 3, 4, 5로 들어온다면 모든 값을 filter돌린 후에 forEach가 돌게될텐데요. filter를 굳이 돌리지 않고 forEach로만 돌리면 fail fast하게 처리할 수 있지 않을까요?

2024-10-23 16:56 UTC, jinyoungchoi95 commented on src/main/java/lotto/LottoResults.java
> +
```suggestion

```
👀

2024-10-23 16:56 UTC, jinyoungchoi95 commented on src/main/java/lotto/Lottos.java
> +    private static final int SIX = 6;
반영을 혹시 놓치신걸까요??

2024-10-23 16:56 UTC, merged