feat : 로또 > Step4 - 로또 (수동)
next-step/java-lotto pull request #3942
Opened 2024-10-21 13:19 UTC by BananMoon

## step3 피드백 반영 사항
- refactor: `WinningLotto`의 보너스 로또 번호 필드명을 알맞게 수정한다.

## step4 미션 구현 사항
### 기능 요구사항 분리  
- 현재 로또 생성기는 자동 생성 기능만 제공한다. 사용자가 수동으로 추첨 번호를 입력할 수 있도록 해야 한다.  
- 사용자가 수동으로 입력하길 원하는 로또 갯수를 입력받는다.  
- 사용자가 입력한 갯수만큼 수동으로 로또 번호를 입력받아 로또를 생성한다.  
- 입력한 금액 만큼의 갯수에서 수동으로 입력한 로또 외의 로또는 자동으로 생성한다.  
### 수정 사항  
- InputView : 수동으로 구매할 로또 수와 로또 번호들을 입력받는다.  
- LottoInterface : 수동으로 응모한 로또 번호와 자동으로 생성된 로또 번호를 전달받는다.
  - 로또 수 이상의 라인을 입력하면 "수동으로 구매한 로또 수만큼만 로또를 입력해주세요." 예외 처리한다.
- LottoProgram : 수동 로또를 생성한다.
- OutputView
  - 수동으로 구매한 로또 수, 자동으로 구매한 로또 수를 출력한다.  

### 고민 사항
1. 수동 로또 생성하는 로직을 어디에 둘지 고민하였습니다.
	1. `LottoNumberGenerator` 를 구현하는 자식 클래스에 두려니 인터페이스의 `generate()` 메서드의 인자를 맞추기 어려웠습니다. 수동 로또 생성기 에서는 로또번호와 로또 갯수 둘다 전달해야 했습니다.
	2. 그래서 `LottoNumberGenerator`에 default 메서드로 구현하였는데, 단순히 `List<Lotto>` 객체를 만드는 로직만 있었고, 제 코드에서는 `LottoProgram`에서 `Lotto` 객체를 만들고 있기 때문에 `LottoProgram`에 수동 로또 생성 로직을 구현하는 것으로 최종 push했습니다.

2. 수동 로또 입력 기능을 추가하면서 LottoProgram, OutputView, InputView 에 
   수동 로또 입력 값에 대한 조건 처리 로직 (수동 로또가 비었는지, 수동 로또 갯수가 0인지 체크) 이 흩어진 것 같아서 어떻게 해야할지 고민했습니다.
	- 수동 로또를 의미하는 클래스를 별도 생성하기엔 `Lotto`와 겹치는 것 같았습니다.
	- 그래서 당첨 로또 (WinningLotto) 처럼 '사용자 로또' 혹은 '응모 로또' (구성 필드 : 자동 로또 번호 List, 수동 로또 번호 List) 클래스를 생성할까 하였는데, 사용자 로또 객체를 생성한 후의 비즈니스 로직이 거의 없어, 이렇게 개발하기에는 오버인 듯하였습니다.
	- 결국은, 필요한 위치에 유효성 체크하도록 하였습니다. 😂

> 그외 커밋 (개선, 버그 픽스)
- bugfix : LottoRank 객체 생성 시 SECOND를 기준으로 값을 다르게 체크한다.
- refactor: 메서드명 개선한다.
- refactor : 사용자 입력 값에서 콤마 앞뒤 공백을 제거한다.

2024-10-21 15:08 UTC, jinyoungchoi95 requested changes
안녕하세요 윤지님 😄

몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-10-21 15:08 UTC, jinyoungchoi95 commented on src/main/java/lotto/domain/LottoRank.java
> +                        : value.matchingCounts.contains(matchingCount))
filter 내부의 로직이 복잡한데 메소드로 빼는건 어떨까요?

stream의 함수형프로그래밍을 생각해보면 행위를 적절하게 함수로 표현할 수 있어야하는데 조금이라도 복잡한 로직이라면 메소드로 분리하고 메소드명으로 그 함수를 적절하게 표현하도록 할 수 있을 것 같아요 😄

2024-10-21 15:08 UTC, jinyoungchoi95 commented on src/main/java/lotto/application/LottoProgram.java
> +                new WinningLotto(new Lotto(winningLottoNumbersInput), new LottoNumber(bonusBall)));
`WinningLotto`에서 `List<String>`과 `int`를 받는 생성자를 만들어 그 생성자에서 `Lotto`와 `LottoNumber`로 생성하도록 하면 조금 더 유연한 `WinningLotto` 생성자가 될 수 있을 것 같아요 :)

2024-10-21 15:08 UTC, jinyoungchoi95 commented on src/main/java/lotto/LottoInterface.java
> +        List<Lotto> totalLottos = lottoProgram.generateLottos(lottoQuantityWithoutManual, manualLottosInput);
`List<Lotto>`를 가지는 일급컬랙션을 추가해보면 좋을 것 같네요

2024-10-22 10:14 UTC, BananMoon commented on src/main/java/lotto/domain/LottoRank.java
> +                        : value.matchingCounts.contains(matchingCount))
filter 내부를 메서드로 분리할 수 있겠군요! 👍
분리하면서 중복되는 로직도 발견해서 수정했습니다

2024-10-22 10:17 UTC, BananMoon commented on src/main/java/lotto/domain/Lotto.java
> +    public Boolean checkContainsLottoNumber(LottoNumber lottoNumber) {
피드백 감사해요! 
해당 메서드가 개발하는 과정에 생겼는데, 마지막에 방식을 바꾸면서 사용하지 않게 됐는데 이 부분을 제거하지 못했던 것 같아요.. 
그래서 해당 메서드와 테스트 코드 제거하였습니다. 😭

2024-10-22 10:22 UTC, BananMoon commented on src/main/java/lotto/application/LottoProgram.java
> +                new WinningLotto(new Lotto(winningLottoNumbersInput), new LottoNumber(bonusBall)));
오 그렇네요! 덕분에 LottoProgram에서의 코드도 덜 복잡해진 듯해요 :)

2024-10-22 12:23 UTC, BananMoon commented on src/main/java/lotto/LottoInterface.java
> +        List<Lotto> totalLottos = lottoProgram.generateLottos(lottoQuantityWithoutManual, manualLottosInput);
여러 장의 로또를 의미하는 일급컬렉션 `Lottos`를 추가했습니다.

> 일급 컬렉션의 필드를 불변 객체로 유지하기 위해 `Lottos`에 `size()`, `valueAt()` 과 같은 메서드들을 생성&사용하여
불변으로 유지할 수 있었으나,
그로인해 외부에서 for문 로직이 좀 많이 생긴 것 같습니다.

2024-10-22 13:44 UTC, jinyoungchoi95 approved these changes
안녕하세요 윤지님 😄

미션 수고하셨습니다 👍 
다음 단계도 화이팅하세요!

감사합니다 🙇‍♂️

2024-10-22 13:44 UTC, merged