🚀 4단계 - 로또(수동) 구현 및 리뷰요청
next-step/java-lotto pull request #3943
Opened 2024-10-21 13:38 UTC by joonkb

안녕하세요, 리뷰어님! 😊

[STEP4] 리뷰 사항을 반영하여 PR 요청드립니다.

이번 구현에서는 리뷰 중 언급해주셨던 `규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.`를 최대한 신경 쓰면서 작업해보았는데, 이 부분이 가장 어려웠던 것 같습니다.

또한, 저번 주 강의에서 학습했던 자동차 경주 미션의 도메인인 RacingNumber에 캐시를 적용한 내용을 이번 로또 미션에도 한번 적용해보았습니다!

추가적으로 피드백해주실 사항이 있으시면 언제든지 부탁드리겠습니다! 🙇

2024-10-22 02:44 UTC, mskangg requested changes
4단계 구현 잘해주셨네요!
캐싱한것도 좋아요 👍 
질문에 대한 답변과 추가피드백 남겨드렸는데, 확인부탁드릴게요! 🙇

2024-10-22 02:44 UTC, mskangg commented on src/main/java/lotto/LottoMain.java
> +        List<Lotto> userLottos = LottoGenerator.generatorLottos(manualLottoNumbers, lottoQuantity.getTotalQuantity());
- [X] 입력받은 수동로또 수만큼 로또를 발급하고 금액을 차감한다.
- [X] 금액의 나머지는 자동로또로 발급한다.

```
로또 발급기:
    로또가격 = 1000

    발급(입력받은 금액, 입력 받은 수동 숫자):
        수동 로또의 수 만큼 금액 차감
        수동 로또 생성
        자동 로또 생성
        로또 반환
```

위처럼 구현했을것 같아요 :)

2024-10-22 02:44 UTC, mskangg commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final Map<Integer, LottoNumber> cachedLottoNumber;
👍

2024-10-22 02:44 UTC, mskangg commented on src/main/java/lotto/utils/LottoGenerator.java
> +public class LottoGenerator {
아직 유틸 패키지에 있군요 🤔

2024-10-22 02:44 UTC, mskangg commented on src/main/java/lotto/utils/LottoGenerator.java
> +    public static List<Lotto> generatorLottos(String[] manualLottos, int totalQuantity) {
이 클래스는 객체화하지 않고 static 구성한 이유는 무엇일까요?
정적으로 구성된 클래스는 추상화 및 다형성 등 객체를 사용함으로서 얻을 수 있는 장점을 사용할 수 없습니다.

간단한 예로 이 코드를 모킹하려면 어떻게 해야할까요?
일반 클래스라면 오버라이딩하여 fake 클래스로 의도된 동작을 하게 만들수 있지만, static은 그러지 못하여 테스트하기에도 힘든 구조가 되기도 합니다 🫠

2024-10-22 15:56 UTC, joonkb commented on src/main/java/lotto/utils/LottoGenerator.java
> +    public static List<Lotto> generatorLottos(String[] manualLottos, int totalQuantity) {
안녕하세요, 리뷰어님!

어떤 개념을 객체화한다는 것이 아직 숙달되지 않은 탓인지, 생각을 해내기가 어려웠던 것 같습니다. 현실 세계에 대한 대입을 저도 모르게 하게 되는 것 같습니다..

LottoGenerator의 경우, 객체로서 어떤 상태를 가져야 하며, List<Lotto>를 반환하는 목적만으로 사용할 것이기에 객체를 생성하여 사용하는 것이 맞을까? 라는 고민 자체를 못했던 것 같습니다.

위에서 말씀하신 부분이 완전히 이해되지 않지만, 리뷰어님 덕분에 대략적인 감은 잡힌 것 같습니다. 감사합니다.

LottoQuantity를 없애고 LottoGenerator를 객체화하여 수정해 보았는데요. 아쉬운 부분이나 추가적으로 생각해볼 거리가 있다면 말씀해 주시면 감사하겠습니다!

2024-10-22 15:59 UTC, joonkb commented
안녕하세요 리뷰어님 😊

좋은 아이디어를 주셔서 감사합니다.

코멘트 확인해주시면 감사하겠습니다.
https://github.com/next-step/java-lotto/pull/3943#discussion_r1810999381


아쉬운 부분이나 추가적으로 생각해볼 거리가 있다면 말씀해 주시면 감사하겠습니다! 🙇

2024-10-23 07:55 UTC, mskangg requested changes
피드백 잘 반영해주셨네요!
추가적으로 생각해볼 거리가 있어서 피드백 드렸어요.
확인부탁드립니다! 🙇

2024-10-23 07:55 UTC, mskangg commented on src/main/java/lotto/domain/LottoGenerator.java
> +    private static Lotto createLotto() {
static 일 필요 없을것 같아요 :)

2024-10-23 07:55 UTC, mskangg commented on src/test/java/lotto/domain/LottoGeneratorTest.java
> +class LottoGeneratorTest {
`수동로또만큼 발급하고 나머지 금액은 자동로또로 발급한다` 와 같은 비즈니스를 검증하는 테스트는 존재하지 않네요 🤔
그리고 자동 로또가 랜덤 전략을 가지고 생성되는 지도 검증을 할 수가 없는것 같아요!

전략패턴을 적용해보는건 어떨까요?
지금 구조에서 전략패턴을 적용한다면 더 좋은 구조가 될것 같아요!
자연스럽게 테스트도 할 수 있을것 같구요

2024-10-23 07:55 UTC, mskangg commented on src/main/java/lotto/domain/LottoGenerator.java
> +public class LottoGenerator {
금액과 카운트를 관리하고 수동을 구매하고 싶은만큼하고 나머지는 자연스레 자동으로 발급되게 잘 구현해주셨네요 👍

2024-10-23 13:55 UTC, joonkb commented
안녕하세요, 리뷰어님 😊

이번 미션을 통해 많은 것을 배울 수 있었고, 여러 가지 인사이트를 얻게 된 것 같습니다. 🙇

로또(자동/수동) 생성 로직을 전략 패턴을 사용해 구현해 보았습니다.
로또 생성 부분을 전략 패턴으로 분리하면서 구조가 훨씬 개선된 것 같습니다.

LottoGenerator 클래스에서 로또를 생성하는 기능을 LottoGeneratorStrategy 구현체로 옮기면서 코드가 더 깔끔해지고, 책임도 명확해졌다는 느낌이 들었습니다. 또한 로또 자동/수동 생성 로직 모두 개별적으로 테스트할 수 있게 되었습니다.

> 이 클래스는 객체화하지 않고 static 구성한 이유는 무엇일까요?
> 정적으로 구성된 클래스는 추상화 및 다형성 등 객체를 사용함으로서 얻을 수 있는 장점을 사용할 수 없습니다.
> 
> 간단한 예로 이 코드를 모킹하려면 어떻게 해야할까요?
> 일반 클래스라면 오버라이딩하여 fake 클래스로 의도된 동작을 하게 만들수 있지만, static은 그러지 못하여 테스트하기에도 힘든 구조가 되기도 합니다 🫠

> 전략패턴을 적용해보는건 어떨까요?
> 지금 구조에서 전략패턴을 적용한다면 더 좋은 구조가 될것 같아요!
> 자연스럽게 테스트도 할 수 있을것 같구요

구현하면서 "왜 나는 이런 생각을 못했을까?"라는 생각이 들었습니다. 물론, 경험이 부족해서일 수도 있겠지만, 
리뷰어님께서 주신 피드백을 보니 주로 테스트가 용이한 구조를 염두에 두고 설계를 하신 것 같습니다.

항상 기능을 테스트 가능한 구조로 설계하는 것이 실제로 도움이 되는지 궁금합니다. 
혹시 리뷰어님만의 방법이나 팁이 있다면 공유해 주실 수 있을까요?

감사합니다!🙇

2024-10-24 06:09 UTC, mskangg approved these changes
> 항상 기능을 테스트 가능한 구조로 설계하는 것이 실제로 도움이 되는지 궁금합니다.
혹시 리뷰어님만의 방법이나 팁이 있다면 공유해 주실 수 있을까요?

테스트 가능한 구조로 설계하는 것은 유지보수와 확장성에 매우 도움이 됩니다!
 
1. 리팩토링 시 자신감있게 코드를 수정할 수 있습니다.
2. 버그 발견이 용이하여 빠르게 수정하고 사이드이펙트를 빠르게 파악할 수 있어요
3. 의존성을 낮추고 독립적으로 테스트가 가능한 구조가 되어 유연한 구조가 됩니다.

개인적인 팁을 공유드리자면,

재성님께서 수업때도 말씀해주신것처럼 도메인의 이해도를 높이기 위해 우선 코드를 작성해봅니다.
그런 다음 코드를 제거한 후 요구사항을 다시 작성해보면 훨씬 세부적으로 작성할 수 있으실거에요.
그러면서 요구사항을 하나씩 테스트코드로 만들어 TDD 사이클을 돌립니다.
그럼 자연스럽게 테스트가 가능한 구조로 개발이 되어질거고 개발이 진행되면서 더 좋은구조가 눈에 들어올거에요!
그럴 때 이미 테스트코드가 있으니 자신감있게 리팩토링을 진행하곤 합니다.
위와 같은 사이클을 돌리면서 요구사항을 하나씩 지워가면서 커밋하여 일을 처리해요 :)

피드백 반영 잘해주셨네요! 👍 
마지막 단계까지 로또하시느라 고생하셨습니다.
모든 미션을 잘 마무리하여 원하시는바 이루시길 바랄게요 🙏 
그럼 화이팅 🔥 🚀

2024-10-24 06:09 UTC, merged