4단계 : 로또 (수동)
next-step/java-lotto pull request #3948
Opened 2024-10-22 07:55 UTC by hanhub-ux

리뷰어님 , 안녕하세요 

4단계를 완료하여 리뷰요청드립니다. 

진행 하면서 고민되었던 부분이 하나가 있었는데요 
수동 방식 일 경우, 수동 전략 클래스에서 로또번호를 입력받도록 구현을 하였는데 ...
이렇게 할 경우 , domain에 있는 객체가 view패키지 객체를 참조하게 되네요 ...
그냥 로또번호들만 입력 받아서 수동전략 클래스에 전달을 해주는게 더 맞을까요 ?

그럼 마지막까지 잘 부탁드리겠습니다. 
많은 의견 부탁드립니다. 

감사합니다.

2024-10-23 07:17 UTC, mskangg requested changes
4단계도 잘 구현해주셨네요! 👍 
질문에 대한 답변과 몇가지 피드백 남겨드렸는데, 확인부탁드릴게요! 🙇

2024-10-23 14:10 UTC, hanhub-ux commented on src/main/java/lotto/domain/LottoCount.java
> +    public LottoNumberGenerator getLottoNumberGenerator() {
로또횟수(LottoCount)에서 로또 생성기를 리턴하는 이유는 (자동/수동) 횟수에 따라 어떤 생성기를 쓸지 결정할수 있다고 생각을 해서 입니다. (전체횟수=자동횟수 > 자동생성기, 전체횟수=수동횟수 > 수동생성기, 기타 > 복합생성기)

2024-10-24 05:11 UTC, hanhub-ux commented on src/main/java/lotto/domain/ManualLottoNumberGenerator.java
> +        return InputView.inputManualLottoNumbers(count);
입력 받는 걸로 변경 하겠습니다.

2024-10-24 05:12 UTC, hanhub-ux commented on src/main/java/lotto/LottoGame.java
> +    }
제거 하겠습니다.

2024-10-24 05:12 UTC, hanhub-ux commented on src/main/java/lotto/domain/LottoCount.java
> +    public LottoNumberGenerator getLottoNumberGenerator() {
이 부분은 로또 생성기 생성 팩토리를 다시 만들었습니다

2024-10-24 05:13 UTC, hanhub-ux commented on src/main/java/lotto/LottoGame.java
> +    private LottoCount lottoCount;
제거 했습니다.

2024-10-24 07:27 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요! 👍 
로또 미션 진행하시느라 고생 많으셨습니다! 👏 
남은 미션도 잘 마무리하셔서 원하시는 목표를 꼭 이루시길 바랍니다. 
그리고 리뷰 받아주시느라 고생 많으셨어요 😄 
그럼 이만 로또미션은 머지하도록 할게요!
화이팅 🔥

2024-10-24 07:27 UTC, mskangg commented on src/main/java/lotto/domain/LottoBuyDetails.java
> +public class LottoBuyDetails {
로또구매정보를 관리하는 클래스군요

2024-10-24 07:27 UTC, mskangg commented on src/main/java/lotto/domain/numbergenerator/AutoLottoNumberGenerator.java
> +}
미션의 내용과는 별개지만 참고하시라고 코멘트 남깁니다.

<img width="189" alt="image" src="https://github.com/user-attachments/assets/a846adfc-0d28-4115-9b65-4e7fa791f209">

newline을 넣어주시면 좋을 것 같아요!

Github에서는 newline을 남기지 않으면 위와 같이 표식이 남습니다.

POSIX 표준에 맞지 않기도 하고 작업시 newline을 붙이는데, 다른 작업자가 붙이지 않을 경우 불필요한 file change가 생기기도 합니다.

저 같은 경우 IntelliJ에서 newline을 자동으로 추가하는 설정을 사용하고 있습니다.

<img width="703" alt="image" src="https://github.com/user-attachments/assets/859c8a73-27a3-467a-8357-df67a6e884b7">

`Ensure every saved file ends with a line break`

2024-10-24 07:27 UTC, mskangg commented on src/main/java/lotto/domain/numbergenerator/LottoNumberGeneratorFactory.java
> +    public  LottoNumberGenerator createGenerator() {
https://github.com/next-step/java-lotto/pull/3948#discussion_r1814261330

👍

2024-10-24 07:27 UTC, merged

2024-10-24 07:30 UTC, hanhub-ux commented on src/main/java/lotto/domain/numbergenerator/AutoLottoNumberGenerator.java
> +}
오~!!! 감사합니다! ^^