4단계 - 로또(수동)
next-step/java-lotto pull request #3950
Opened 2024-10-23 09:32 UTC by kdfasdf

안녕하세요 승훈님!!
이전 단계 피드백 반영하고 4단계 진행해서 리뷰 요청 드립니다!
감사합니다!!

이번 미션 진행할 때 로또를 수동으로 만드는 책임을 LottoGenerator 인터페이스의 구현 클래스를 새로 만들을까 생각했었는데 수동으로 만드는게 입력이라 View의 책임으로 해야할지 고민되더라구요 
로또를 수동으로 생성한다 라는 말로 생각하면 구현 클래스를 만들어주는 것도 적절하다고 생각했는데요. 하필 그 수동의 방식이 사용자 입력이어서 구현 클래스에 책임을 가지게 하면  결국 Scanner를 들고 있어야 하고 InputView가 가져야 할 책임을 도메인 객체가 가지게 되는 모순이 생기는 것 같더라구요.
만약 사용자 입력이 아니라 다른 방식이었다면(짝수로만 뽑는다든지) 인터페이스의 구현체로 해주었을 텐데 사용자 입력 방식이 예외적인 경우라 생각하고 InputView가 책임을 가지도록 했는데 타당한 생각이었을까요?

2024-10-24 04:05 UTC, csh0034 requested changes
4단계 구현 잘해주셨네요 😄 
몇가지 고민해볼 사항 남겨두었는데
확인 부탁드립니다!

2024-10-24 04:05 UTC, csh0034 commented on src/main/java/lotto/controller/JavaLotto.java
>          LottoResultStatistic lottoResultStatistic
인자로 전달하는 대상의 경우 인라인으로 처리하기보다 변수선언을 하여 표현하는것이
가독성 측면에서 좋다고 생각해요 🙂

```suggestion
              WinningLotto winningLotto = new WinningLotto(inputView.inputWinnerNumber(), inputView.inputBonusNumber());
      LottoResultStatistic lottoResultStatistic = lottos.getResultStatistic(winningLotto);
```

2024-10-24 04:05 UTC, csh0034 commented on src/main/java/lotto/view/InputView.java
> +    private List<Lotto> inputManualLottos(PurchaseInfo purchaseInfo) {
이부분이 질문 주신 내용이네요!

잘 적용해주셨다고 생각해요. 수동의 경우 사용자 `입력` 을 받아야 하는 부분이기 때문에  
InputView 의 책임이 적절하다고 생각합니다.


추가로 현재 입력단계에서 예외가 발생하면 바로 종료됩니다.
`예외 처리를 통해 에러가 발생하지 않도록 한다.` 의 요구사항을 고민해보시면 좋을것 같아요!

2024-10-25 05:03 UTC, kdfasdf commented on src/main/java/lotto/domain/PurchaseInfo.java
> +public class PurchaseInfo {
검증은 구현하고 테스트 코드까지 작성했었는데 정작 프로덕션 코드에서는 값을 잘못전달하고 있었네요😅

2024-10-25 05:22 UTC, kdfasdf commented on src/main/java/lotto/domain/PurchaseInfo.java
> +public class PurchaseInfo {
오버플로 예외는 제가 실제 로또가 진행되는 방식을 제가 이해한대로 가장 편하게 구현한건데요 실제 로또는 판매금액에 따라 달라지겠지만 각회 최대 상금은 정해져있는 것으로 이해했어요. 
그래서 로또 게임 미션에서는 최대 상금을 20억으로 정해두고 만약 1등이 2번 당첨되면 지금 상금계산 로직에서는 음수로 오버플로우가 발생해서 넣어준 예외에요

2024-10-25 06:17 UTC, kdfasdf commented on src/main/java/lotto/domain/Lottos.java
> +    private final PurchaseInfo purchaseInfo;
다시 보니 resultView에 넘기는데 말고는 사용되지가 않네요 JavaLotto에서 resultView로 넘기는게 낫겠군요!

2024-10-25 07:32 UTC, kdfasdf commented on src/main/java/lotto/domain/Lottos.java
> +    public void additionalLottos(Lottos lottos) {
당장에 쉬워보이는 방향으로 구현하다보니 이렇게 되었던 것 같네요 도메인 객체의 비즈니스 로직이 컨트롤러에 노출되서 MVC에 위배된 것으로 보면 될까요?

2024-10-26 01:29 UTC, kdfasdf commented
안녕하세요 승훈님!
피드백 반영했다고 생각하여 다시 리뷰요청 드립니다
감사합니다!!

2024-10-26 05:23 UTC, closed without merging

2024-10-26 05:47 UTC, csh0034 commented on src/main/java/lotto/domain/Lottos.java
> +    public void additionalLottos(Lottos lottos) {
현재 요구사항에선 Lottos 가 생성시점에 모두 초기화가 가능합니다.
add 를 하는 메서드를 별도로 둘 경우엔 실수로 호출하지 않게 될 수도 있기 때문에 가능하다면 생성시점에 
완전한 객체가 되도록 코멘트 드린 내용입니다 😄