🚀 4단계 - 로또(수동)
next-step/java-lotto pull request #3955
Opened 2024-10-25 03:06 UTC by stoneHee99

안녕하세요 리뷰어님!
4단계 미션 완료하여 리뷰 요청 드립니다~!

이번 미션 역시 지난 1, 2, 3 단계에서 진행한 미션을 기반으로 리팩토링 하니 수월한 느낌을 받았습니다~! 

미션을 진행하면서 생긴 간단한 질문사항들이 있어서 질문 드립니다!

1. 주 생성자의 변경
저는 `LotteryMachine` 클래스의 주 생성자를 해당 클래스 내의 속성 `lottos` 를 그대로 매개변수로 받아 생성하는 생성자를 만들고 다른 매개변수로 받는 부 생성자들을 결국엔 내부에서 주 생성자를 호출하도록 구성하여 1, 2, 3단계 미션을 진행하였습니다.
이렇게 하니 주 생성자가 명확해서 다른 생성자를 구현하기 수월한 느낌을 받았습니다.
하지만 이번 미션에서 새롭게 수동 번호를 입력 받아야 하다보니 기존 구조에 한계를 느껴 주 생성자를 변경하게 되었고, 해당 객체를 바라보던 거의 모든 클래스 (테스트 코드 포함) 에서 수정이 일어났습니다.
뭔가 이 미션을 진행하면서 주 생성자를 잘 정해놓았으면 하는 아쉬움이 있었는데요. (사실 어떻게 하는게 정답인지는 아직 고민중입니다) 관련해서 리뷰어님의 인사이트를 여쭙고 싶습니다!

2. CQRS 패턴
포비님의 라이브강의를 들으며 CQRS 패턴에 대한 언급이 나왔는데요! `InputView` 와 `OutputView` 클래스에 해당 CQRS 패턴을 적용하면 더 명시적인 코드가 나올 것 같았습니다.
지금은 InputView의 메서드를 호출하면 한번에 콘솔을 통해 입력된 값을 바로 반환받는 형태였다면, 두개의 메서드로 나누어 콘솔에서 입력 받은 값을 InputView에 저장하고 해당 값을 전달받는 메서드를 따로 만들어 가져오면 더 좋게 작성할 수 있었을까? 하는 의문이 들었습니다.
예를 들어, 현재 Lotto Controller 에서는 실제 콘솔에서 수동 로또 번호도 함께 입력받지만, 메서드 구현상 수동 로또 번호를 컨트롤러에 가져오지 않았기 때문에 결과 리스트에서 다시 `size()` 메서드로 길이를 구하는 등 이런 부분이 아쉬웠습니다.
그런데 또 그렇게 변경하자니 너무 오버 엔지니어링이 아닌가 하는 생각도 들어서 이부분이 궁금했습니다!

이번에도 가감없는 피드백과 리뷰 부탁드립니다! 🔥🔥 감사합니다 :)

2024-10-25 15:09 UTC, mskangg requested changes
4단계도 정말 잘 구현해주셨네요!
이전 단계에서 구조를 잘 잡아주셔서인지, 구조 변경없이 추가 요구사항을 만족하게해주셨네요 💯 
질문에 대한 답변 남겨드렸으니, 확인해보시고 고민부탁드릴게요 🙇 
미션은 머지해도되나, 석희님의 고찰이 궁금해서 RC 드릴게요!
그럼 화이팅 🔥

2024-10-26 23:53 UTC, stoneHee99 commented on src/main/java/lotto/ui/InputView.java
> +
이부분은 리뷰어님이 말씀해주신 의견에 100% 공감합니다 💯

다만, 제가 생각했던 부분은 라이브강의에서 명령과 조회를 분리하는 패턴에 이점에 대해 들었는데요. 이부분에서 개선할 수 있지 않을까 하는 마음에 직접 적용까지는 아니지만 코멘트 드렸던 부분이에요!

제가 생각했던 부분은 다음과 같습니다.

`AS-IS`
```java
List<String> manualLottoNumbers = InputView.readManualLottoNumbers(); // 이 안에서 로또 개수와 로또 번호 입력받음
LotteryMachine lotteryMachine = new LotteryMachine(manualLottoNumbers, purchasePrice); // 로또의 컬렉션 생성
ResultView.printLottoInfo(lotteryMachine, manualLottoNumbers.size()); // 결과 출력을 위해 로또 번호를 다시 구함
```
이런식으로 `LottoController` 부분이 구현되어 있는데요. 로또 개수를 `InputView` 에서 입력받지만 직접 사용할 수가 없는 구조입니다.

`TO-BE`
```java
int manualLottoCount = InputView.readManualLottoCount(); // 로또 개수를 먼저 입력받음
List<String> manualLottoNumbers = InputView.readManualLottoNumbers(manualLottoCount);
ResultView.printLottoInfo(lotteryMachine, manualLottoCount);
```
이런식으로 구현할 수도 있겠지만, 이것보다도 CQRS 패턴을 적용시켜

`TO-BE 2`
```java
InputView.readManualLotto(); // 로또 개수와 번호를 상태로 가지게 됨
List<String> manualLottoNumbers = InputView.readManualLottoNumbers();
ResultView.printLottoInfo(lotteryMachine, InputView.readManualLottoCount());
```

이런식으로 구현하면 조금더 명확하게 분리가 되지 않을까 생각이 들어 질문드렸던 내용인데요! 리뷰어님 인사이트를 듣고 간단히 적용해본 결과 이렇게 구현했을 때의 이점이 단점에 비해 명확히 적다는 생각이 드네요

좋은 인사이트 나눠주셔서 감사드립니다. 👍👍

2024-10-27 11:02 UTC, stoneHee99 commented
안녕하세요 리뷰어님~! 좋은 인사이트 나누어주셔서 감사합니다~!

정적 팩토리 메서드에 대한 적용을 통해 주 생성자와 생성에 필요한 부가 로직들을 나눠놓는 것을 적용해보니 더 좋은 구조가 된 것 같습니다~!

```
로또머신 = new 로또머신(금액)
로또머신.수동발급(로또)
로또머신.자동발급
```
사실은 이 구조가 더 좋아보인다고 느꼈는데 이 부분은 이후에 미션을 진행하면서 자연스러운 흐름을 더 생각해보는 연습을 해볼 수 있을  것같아서 피드백 주신 정적 팩토리 메서드 패턴을 먼저 적용해보았답니다 :) 잘 되었는지는 모르겟네요..ㅎㅎ

이번에도 가감없는 리뷰와 피드백 부탁드립니다!

2024-10-28 09:02 UTC, mskangg approved these changes
> 사실은 이 구조가 더 좋아보인다고 느꼈는데 이 부분은 이후에 미션을 진행하면서 자연스러운 흐름을 더 생각해보는 연습을 해볼 수 있을 것같아서 피드백 주신 정적 팩토리 메서드 패턴을 먼저 적용해보았답니다 :) 잘 되었는지는 모르겟네요..ㅎㅎ

직접 구현해보고 더 마음에 드는것으로 골라보시죠! ㅎㅎ

피드백 반영 잘해주셨습니다 👏 
로또미션은 여기까지 해도 충분하겠네요 😄
미션 진행하시느라 고생많으셨습니다.
마지막까지 완수하셔서 원하시는바 이루시길 바랄게요~! 🙏

2024-10-28 09:02 UTC, mskangg commented on src/main/java/lotto/domain/LotteryMachine.java
> +        return new LotteryMachine(combinedLottos);
이렇게 해결하셨군요 👍

2024-10-28 09:02 UTC, merged