Step2
next-step/java-lotto pull request #3962
Opened 2024-10-27 14:48 UTC by wiseongjun

리뷰 부탁드립니다!

2024-10-28 00:08 UTC, neojjc2 commented
#tag @neojjc2

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/docs/README.md
> +- org.junit.jupiter:junit-jupiter:5.8.2
요구사항 정리에 클래스 다이어그램, 시퀀스 다이어그램 까지 너무 잘 해주셨네요 💯💯💯💯💯

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/Lotto.java
> +		}
로또 번호 개수를 검증하신 부분 좋습니다 💯 
당첨번호도 결국 `Lotto` 객체와 동일한 속성을 가지고 있습니다 😄 
이 부분도 같이 검증되면 좋을 것 같습니다 🙇 
<img width="314" alt="image" src="https://github.com/user-attachments/assets/32aa2efd-b621-4d3f-815d-82c6a7805fc9">

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/Lotto.java
> +	}
이미 `Money`라는 객체를 잘 정의 해주셨네요 
`money`에서 `getMoney()`를 해서 계산하기 보다 
`Money`한테 직접 물어보시죠 😄 

로또 금액과 관련된 모든 것을 관리하는 역할과 책임을 부여해주셨으니,
그게 좀 더 자연스러울 것 같습니다 🙇 

그럼 굳이 `LottoGame`에서도 `Lotto.getPossibleAmountByMoney`를 통하지 않아도 될 것 같습니다 🙏 

```java
// LottoGame.buyLotto
// AS IS
int amount = Lotto.getPossibleAmount(money);
		
// TO BE
int amount = money.getPossibleAmountByMoney();
```

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/Lotto.java
> +	}
`toString`을 `Overriding`하신 부분은 좋습니다만,
`toString`이 출력 `format`으로 사용되면 안됩니다.

`ResultView`에서 사용하고 있는 출력은 언제든지 변경될 수 있고, 
`toString`은 객체의 디버깅, 혹은 로깅용으로  사용될꺼라는 
암묵적인 룰이 있기 때문에, `toString`의 내용은 언제든 변경이 될 수 있기 때문입니다. 나중에 이 부분을 수정할 수도 있는 동료 개발자가 
`toString`이니까 아무 거리낌 없이 수정할 수도 있습니다.
그렇기 때문에 요구사항을 만족하기 위해 `toString`을 사용하면 
향 후 전혀 관련없는 수정으로 인해 영향이 발생할 수 있습니다 🤔 

그리고 출력 포맷 역시 변경 된다면 (예를들어 `json` 등등) 이 부분은 비즈니스로직과는 상관없이 계속 수정이 발생합니다.

`get`을 사용하지 말라는 요구사항 때문에 이렇게 작업해주신 것 같은데,
제 개인적인 생각으로는 `get`을 아예 사용안하는 건 불가능 하다고 생각합니다.
사용하더라도 안전한 방식으로 사용한다면 크게 문제는 없다는 입장인데요,
* `get`을 사용하되 `lottoNumbers`를 불변객체, 혹은 복제하여 반환하거나 (원본에 이상이 없도록)
* `ResultView`에서 사용할 수 있도록 최소한의 정보를 담은 출력용 `method`를 제공하거나

하는 방식으로 개선해볼 수 있을 것 같습니다.
이 부분은 한번 수정검토 부탁 드릴께요 🙇 

요 내용도 함께 정리하고 가시면 좋을 것 같습니다 😄 
> toString 재 정의에 관해
> https://lelecoder.com/42

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/Lotto.java
> +	}
`equals`, `hashCode` `@Override`도 좋네요 👍

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/LottoNumber.java
> +	public static List<LottoNumber> listFromString(String winningNumbers) {
이미 인자로 `String`이 전달되고 있으니 `String`이란 네이밍은 제거해도 좋을 것 같습니다. 
왜냐하면 인자가 `String`이 아닌 다른객체로 혹시 변경된다면 `method`의 네이밍도 어색해 집니다. 
```java
listFromString(Object winningNumbers); // ?? 
```
`asList` 같은 네이밍도 좋을 것 같습니다 🙏

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/LottoNumber.java
> +	}
이 부분 약간 `flow`가 어색했습니다. 이미 `LottoNumber`를 생성해주실 때 범위 값에 대한 검증을 해주시고 `Exception`을 던져주셨는데요, 해당 부분에서 이미 `Unchecked exception`인 `IllegalArgumentException`을 던지고 있는데 
여기에서 다시 `catch`를 해서 같은 `Exception`을 던진다?? 좀 어색합니다 🤔 

그리고 예외 문구 또한 형식이 잘못된게 아니라 당첨번호가 범위를 벗어나서 
이미 잘 정의해주신 `"로또번호는 1~45의 숫자만 가능합니다."` 가 표시되는게 
더 자연스럽다고 생각합니다 🙇 

<img width="773" alt="image" src="https://github.com/user-attachments/assets/78c7dc5e-26b0-451e-9653-09512e905b61">

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/LottoNumber.java
> +		}
검증 코드 좋고 `LottoNumber` 원시 객체 포장도 좋고 캐시 적용도 너무 좋네요 👍

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/LottoShuffleManager.java
> +		List<LottoNumber> lottoNumbers = numberList.subList(0, 6);
이미 상수로 잘 정의해주신 값을 사용하는게 더 좋을 것 같습니다 🙇 
```suggestion
		List<LottoNumber> lottoNumbers = numberList.subList(0, LottoConstant.LOTTO_COUNT);
```

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/LottoStast.java
> +public class LottoStast {
아주 소소한 의견인데 `status`의 오타로 보여집니다 😅

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/LottoStast.java
> +	private int gainnedMoney = 0;
```suggestion
	private int gainedMoney = 0;
```

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/LottoStast.java
> +		int inputtedMoney = lottos.size() * LOTTO_PRICE;
차라리 `Money`객체를 같이 넘기고 이런 역할들을 위임하는게 어떨까요??
돈과 관련된 계산 부분은 한쪽에서 관리되는게 향후 유지보수 관점에서도 
더 좋을 것 같습니다. 필요할 때 마다 `money`에서 `get`해서 연산을 하거나, 
상수를 통해 필요한 `method` 마다 연산을 한다면, 수정범위 찾기도 어렵고
중복된 코드들도 계속 발생할 수 있을 것 같아요 🤔

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/LottoStast.java
> +		}
요구사항 구현 잘 해주셨습니다 👍

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/Money.java
> +public class Money {
저는 `Money`객체를 만들어주신 부분 너무 좋았습니다 😄 
`LottoGame.checkMoneyRange` 야말로 `Money`의 역할이라고 보이는데 어떠신가요?? 🤔 

`Money`의 생성자가 호출되는 시점으로 옮겨진다면, 검증이 누락될 염려도 줄어들 수 있을 것 같고 `LottoGame`에서 매번 호출되었는지 체크하는 수고도 덜 수 있을 것 같습니다 🙇

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/domain/var/LottoPrize.java
> +}
💯 💯 💯 💯 💯

2024-10-28 00:58 UTC, neojjc2 commented on src/main/java/step2/service/LottoGame.java
> +	}
위에서도 의견 드렸습니다만, 요 부분은 `Money`로 가시죠 😄

2024-10-28 00:58 UTC, neojjc2 commented on src/test/java/step2/service/LottoGameTest.java
> +}
만들어진 도메인 객체에 비해 테스트가 좀 부족한 것 같습니다. 
각 도메인들이 가지고 있는 method들이 최대한 테스트가 되면 좋을 것 같네요 🙇 

> **프로그래밍 요구사항**
모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, System.in) 로직은 제외

2024-10-28 00:59 UTC, neojjc2 requested changes
안녕하세요 성준님 🙇 

2단계 구현 엄청난데요 😮 
각종 다이어그램들도 인상적이었고, 구조도 잘 잡아주셨습니다 👍 

조금만 정리되면 완성도가 더 올라갈 것 같아서
소소한 의견 몇 가지 드렸는데요
보시고 개선 검토 해주시면 좋을 것 같습니다 😄 

그럼 재 리뷰 요청 기다리고 있겠습니다 🙏

2024-10-30 13:30 UTC, wiseongjun commented on src/main/java/step2/domain/Lotto.java
> +	}
int amount = money.getPurchasableLottoCount();
로 Money에서 관리하게 했습니다!

2024-10-30 13:43 UTC, wiseongjun commented on src/main/java/step2/domain/Lotto.java
> +		}
헉 이부분 검증하려니까 정말 그렇네요!
Lotto에서 검증하게 바꾸겠습니다!

2024-10-30 13:44 UTC, wiseongjun commented on src/main/java/step2/domain/Lotto.java
> +	}
하면서 이게 맞나 싶었는데 너무 안일하게 처리한것 같네요 ㅜㅜ.. 이런 부분 귀찮다고 막 하는 습관을 바꿔야겠습니다..

2024-10-30 13:57 UTC, wiseongjun commented on src/main/java/step2/domain/LottoNumber.java
> +	public static List<LottoNumber> listFromString(String winningNumbers) {
예전에 from으로만 썼더니 조금더 명확하게 해달라고 피드백을 받았어서
return값 parameter 값을 명시적으로 선언했는데 (같은 레벨이라고 생각해서??)
이 피드백 듣고 찾아보니 관례적인 부분도있고 함수의 다형성때문에 
말씀하신대로 처리하는게 확실히 좋은것같습니다! 유명한 오픈소스 코드 네이밍 방식도 학습해봐야겠네요..

2024-10-30 14:01 UTC, wiseongjun commented on src/main/java/step2/domain/LottoNumber.java
> +	}
앗 제가 의도한거는 parseInt 오류났을때 처리하려고했던건데 LottoNumber를 할때 걸리나보네요..
조금더 정확하게 처리하도록 해보겠습니다.

2024-10-30 14:01 UTC, wiseongjun commented on src/main/java/step2/domain/Lotto.java
> +		}
List<LottoNumber> distinctLottoNumbers = lottoNumbers.stream().distinct().collect(Collectors.toList());
		if (distinctLottoNumbers.size() != LOTTO_COUNT) {
			throw new IllegalArgumentException("로또 번호는 중복되지 않는 " + LOTTO_COUNT + "개의 번호여야 합니다.");
		}

2024-10-30 14:18 UTC, wiseongjun commented on src/main/java/step2/domain/LottoStast.java
> +public class LottoStast {
통계라 statistics 인데 항상 이 단어가 애매하네요 ㅋㅋㅋ..

2024-10-30 14:19 UTC, wiseongjun commented on src/main/java/step2/domain/LottoNumber.java
> +	}
String[] splittedNumbers = winningNumbers.split(",");
		return Arrays.stream(splittedNumbers)
			.map((numberStr) -> {
				int number;
				try {
					number = Integer.parseInt(numberStr.trim());
				} catch (Exception e) {
					throw new IllegalArgumentException("지난 주 당첨번호를 올바른 형식으로 넣어주세요. \nex) 1, 2, 3, 4, 5, 6");
				}
				return new LottoNumber(number);
			})
			.collect(Collectors.toList());
			
이게 맞는지는 잘 모르겠네용...

2024-10-30 14:20 UTC, wiseongjun commented on src/main/java/step2/domain/LottoStast.java
> +	private int gainnedMoney = 0;
허걱

2024-10-30 14:26 UTC, wiseongjun commented on src/main/java/step2/domain/Money.java
> +public class Money {
만약 Money 가 여러군데에서 쓰이는 객체라면.. Lotto뿐만이아니라 뭐 음식을사거나 음료를사거나...
Lotto를 한주에 10만원밖에 못산다고 생각하면 그거는 로또 게임을 하는 곳에서 처리하는게 맞지않나..싶어서 이렇게 구현했는데 어떻게생각하시나요?? 

그리고 비슷한 느낌으로 제가 SI에서 개발해서 그런지는 모르겠는데 뭔가 객체에 너무 많은 로직을 넣어버리면..
처음보는 개발자가 이 서비스 함수만 보고는 비즈니스 로직이 어떻게 돌아가는지 제대로 파악이 힘들것같습니다 ㅠㅜㅜ...

이런부분에 대해서 혹시 좋은 글이나 방법론이 있을까요.. LottoMoney처럼 상속받는 객체를 하나 더 만들어야할까요?

2024-10-30 14:31 UTC, wiseongjun commented on src/main/java/step2/service/LottoGame.java
> +	}
일단은 위와같이 생각해서 
`money.checkMinMoney(LOTTO_PRICE);
		money.checkMaxMoney(MAX_LOTTO_PURCHASE_AMOUNT);
		List<Lotto> lottos = buyLotto(money);
		Money change = money.pay(lottos.size() * LOTTO_PRICE);
		return new LottoPlayResultDto(lottos, change);`
		이렇게 처리했습니다..

2024-10-30 14:34 UTC, wiseongjun commented on src/main/java/step2/domain/LottoStast.java
> +public class LottoStast {
public class LottoStatistics 로 변경했습니닷

2024-10-30 14:36 UTC, wiseongjun commented on src/main/java/step2/domain/LottoStast.java
> +		int inputtedMoney = lottos.size() * LOTTO_PRICE;
돈 체크하는거랑 수익률 계산하는건 Money에서 충분히 할수있을거같아서 그쪽으로 옮기겠습니다!

2024-10-30 14:52 UTC, wiseongjun commented on src/main/java/step2/domain/LottoStast.java
> +		int inputtedMoney = lottos.size() * LOTTO_PRICE;
```
public LottoStatistics(List<Lotto> lottos, Lotto winningLotto) {
		setWinCountMap(lottos, winningLotto);
		Money inputtedMoney = new Money(lottos.size() * LOTTO_PRICE);
		this.profitRatio = inputtedMoney.getProfitByGainedMoney(gainedMoney);
	}
```

2024-10-30 15:25 UTC, wiseongjun commented
코드 꼼꼼하게 봐주셔서 감사합니다!! 코드 수정했으니 리뷰 부탁드립니다~

2024-10-30 15:26 UTC, wiseongjun commented on src/test/java/step2/service/LottoGameTest.java
> +}
넵 테스트 최대한 해보겠습니닷

2024-10-30 23:03 UTC, neojjc2 approved these changes
안녕하세요 성준님 🙇 

다소 많은 의견을 드린거 아닌가 걱정했는데,
깔끔하게 개선해주셨네요 😄 

소소한 의견들 남겼는데요 다음단계 진행하시면서
참고 정도 해주시면 감사하겠습니다.

정말 수고 많으셨습니다.
이만 `merge`하겠습니다.
다음단계 진행하시죠 🔥

2024-10-30 23:03 UTC, neojjc2 commented on src/main/java/step2/domain/LottoNumber.java
> +		} catch (NumberFormatException e) {
`parseAndCreate` 네이밍 좋은데요?? 굳이 `method` 내용까지 확인하러 오지 않아도 될 것 같습니다 👍 

아주 소소한 의견입니다만, 저희 조직 같은경우
기존의 있는 객체들을 조합해서 새로운 객체를 만든다면 `generate`를, 
아예 new로 처음 만드는 객체는 `create`를 사용하는 편입니다. 
이런 컨벤션 룰도 있구나, 하고 참고 정도만 해주시면 될 것 같습니다 😄

2024-10-30 23:03 UTC, neojjc2 commented on src/main/java/step2/view/ResultView.java
> +				.collect(Collectors.toList());
차라리 `Lotto`객체한테 `List<Integer>`를 달라고 하는 것도 하나의 방법이 될 수 있을 것 같습니다. 
`Lotto`번호에 대한 권한 및 책임을 가진 `Lotto`객체에게 출력용 번호 목록을 달라고 요청하는건,
역할과 책임 관점에서도 충분히 가능할 것 같습니다. 😄

2024-10-30 23:04 UTC, merged