3단계 - 로또(2등)
next-step/java-lotto pull request #3967
Opened 2024-10-30 15:28 UTC by lee-won-suk

안녕하세요, 3단계 리뷰 요청드립니다..!

2024-11-01 07:56 UTC, csh0034 requested changes
3단계 잘 진행 해주셨네요 😄 
몇가지 코멘트 남겨두었는데 확인 부탁드립니다!

2024-11-01 07:56 UTC, csh0034 commented on src/main/java/lotto/LottoRank.java
> +public enum LottoRank {
LottoRank 와 LottoWinningCountDecision 를 분리할 필요가 있는걸까요? 🤔

매칭되어야하는수와 금액을 표현해보는건 어떨까요?

2024-11-01 07:56 UTC, csh0034 commented on src/main/java/lotto/ResultText.java
> +public enum ResultText {
출력에 관한 문자열은 ui 영역에서 처리해보시면 좋을것 같아요.

2024-11-01 07:56 UTC, csh0034 commented on src/main/java/lotto/controller/LottoMain.java
>          Scanner scanner = new Scanner(System.in);
`Scanner(System.in)` 를 통한 입력은 InputView 에서 처리해보시면 좋을것 같습니다.

2024-11-01 07:56 UTC, csh0034 commented on src/main/java/lotto/domain/BonusBall.java
> +public class BonusBall {
LottoNumber 를 외부에서 bonus 라고 변수명을 두고 사용해보는건 어떨까요?
BonusBall 이 꼭 필요한지에 대해서 고민해보시면 좋을것 같습니다.

2024-11-01 07:56 UTC, csh0034 commented on src/main/java/lotto/domain/BonusBall.java
> +    public boolean checkMatching(List<LottoNumber> lottoNumberList) {
`List<LottoNumber> lottoNumberList` 를 외부에서 getter 를 통해 전달하기보다
LottoNumbers 에게 LottoNumber 를 전달하는것이 자연스럽지 않을까요?

2024-11-01 07:56 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +                .mapToInt(lottoNumbers -> winningLottoNumbers.lottoRank(lottoNumbers.getLottoNumberList(), bonusBall))
getter 를 통해 전달하고 있네요 LottoNumbers 를 전달해볼순 없을까요?

2024-11-01 07:56 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    public List<List<Integer>> totalRoundLottoNumberList() {
LottoNumber 에 toString 을 override 한다면 바로 출력가능할것 같습니다.

2024-11-01 07:56 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    public List<Integer> lottoRankList(LottoNumbers winningLottoNumbers, BonusBall bonusBall) {
LottoResult 에 전달하기 위함이라면 Lotto 에서 LottoResult 를 만들어 보는건 어떨까요?

2024-11-01 11:57 UTC, lee-won-suk commented on src/main/java/lotto/ResultText.java
> +public enum ResultText {
ui쪽으로 옮기는 방향으로 수정했습니다.

2024-11-01 12:02 UTC, lee-won-suk commented on src/main/java/lotto/controller/LottoMain.java
>          Scanner scanner = new Scanner(System.in);
내부에서 처리하도록 수정했습니다.

2024-11-01 12:10 UTC, lee-won-suk commented on src/main/java/lotto/domain/BonusBall.java
> +public class BonusBall {
좋은 방식이라고 생각합니다.
LottoNumber로 보너스볼도 활용이 가능할 것 같네요! 수정 완료했습니다.

2024-11-01 13:05 UTC, lee-won-suk commented on src/main/java/lotto/domain/BonusBall.java
> +    public boolean checkMatching(List<LottoNumber> lottoNumberList) {
getter 사용을 지양하기 위해서 객체 자체를 넘겨 전달해보았습니다.

2024-11-01 13:06 UTC, lee-won-suk commented on src/main/java/lotto/domain/Lotto.java
> +                .mapToInt(lottoNumbers -> winningLottoNumbers.lottoRank(lottoNumbers.getLottoNumberList(), bonusBall))
동일하게  lottoNumbers 자체를 넘겨서 해결해보았습니다.

2024-11-01 13:32 UTC, lee-won-suk commented on src/main/java/lotto/domain/Lotto.java
> +    public List<List<Integer>> totalRoundLottoNumberList() {
이런 방법이 있었네요; 좀 어려웠는데 일단 LottoNumber를 ToString으로 오버라이디아고,
Lotto자체를 ui에 넘겨서 List<LottoNumbers>를 내부에서 출력하도록 수정해보았습니다.

2024-11-02 01:30 UTC, lee-won-suk commented on src/main/java/lotto/domain/Lotto.java
> +    public List<Integer> lottoRankList(LottoNumbers winningLottoNumbers, BonusBall bonusBall) {
확실히 lotto안에 넣으니 main쪽 로직이 좀 더 줄어드는 것 같고, 더 명확한 것 같습니다.
수정완료했습니다.

2024-11-02 05:19 UTC, lee-won-suk commented on src/main/java/lotto/LottoRank.java
> +public enum LottoRank {
넵 1개로 수정했습니다.
보너스볼이 2등에만 적용되고 다른 등수에는 당첨개수에 영향을 주지 않는데 이부분에서 미스가 있어서 더 나눠진 것 같습니다.
LottoRank 자체를 랭크로 반환하도록 수정했습니다.

2024-11-03 03:26 UTC, csh0034 requested changes
리뷰 반영 잘 해주셨네요 😄 
몇가지 코멘트 남겨두었는데
다음단계 진행하면서 고민해보시면 좋을것 같습니다.

2024-11-03 03:26 UTC, csh0034 commented on src/main/java/lotto/LottoRank.java
> +    LottoRank(int lottoMatchingCount, int lottoWinningAmount) {
```suggestion
    LottoRank(int lottoMatchingCount, int lottoWinningAmount) {
        this(lottoMatchingCount, lottoWinningAmount, MatchBonus.NONE);
    }
```

2024-11-03 03:26 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    private LottoResult lottoResult;
인스턴스 변수로 관리할 필요가 있을까요?

외부에서 `LottoNumbers winningLottoNumbers, LottoNumber bonusNumber` 를 전달하면 바로 LottoResult 를 반환해보는건 어떨까요?

2024-11-03 03:26 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    public void updateWinningRankList(LottoNumbers winningLottoNumbers, LottoNumber bonusNumber) {
`LottoNumbers winningLottoNumbers, LottoNumber bonusNumber` 의 경우
1,2,3,4,5,6 + 6 과 같이 winningLottoNumbers 안에 bonusNumber 가 포함되면 안됩니다.

두개를 포함하면서 검증을 처리하는 WinningLotto 등과 같은 대상을 추가해보는건 어떨까요?

2024-11-03 03:26 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    public double calculateMarginPercent(int purchaseAmount) {
해당부분은 Lotto 에서 처리하지않고 lottoResult 를 직접 호출 할 수 있지 않을까요?

2024-11-03 03:26 UTC, csh0034 commented on src/test/java/lotto/testrandom/DefaultLottoList.java
> +        return IntStream.range(1, 7).mapToObj(LottoNumber::new).collect(Collectors.toList());
```suggestion
        return IntStream.rangeClosed(1,6)
            .mapToObj(LottoNumber::new)
            .collect(Collectors.toList());
```

2024-11-03 03:26 UTC, merged

2024-11-04 03:05 UTC, lee-won-suk commented on src/main/java/lotto/LottoRank.java
> +    LottoRank(int lottoMatchingCount, int lottoWinningAmount) {
감사합니다. 주생성자를 호출하도록 변경했습니다.

2024-11-04 03:13 UTC, lee-won-suk commented on src/main/java/lotto/domain/Lotto.java
> +    private LottoResult lottoResult;
넵.. 확인해보니 Lotto내부의 값과 상호작용하는게 아니라서 분리해서 선언했습니다.

2024-11-04 03:15 UTC, lee-won-suk commented on src/main/java/lotto/domain/Lotto.java
> +    public double calculateMarginPercent(int purchaseAmount) {
맞습니다. 직접 호출하도록 수정했습니다.

2024-11-04 03:15 UTC, lee-won-suk commented on src/test/java/lotto/testrandom/DefaultLottoList.java
> +        return IntStream.range(1, 7).mapToObj(LottoNumber::new).collect(Collectors.toList());
감사합니다. 가독성이 좀 더 좋게 변경할 수 있을 것 같습니다.