4단계 - 로또(수동)
next-step/java-lotto pull request #3969
Opened 2024-11-04 14:03 UTC by lee-won-suk

안녕하세요, 어느덧 마지막 단계인데요,
기간이 기간이다보니 조금은 급해지는 것 같습니다.
부족하지만 마지막까지 잘 부탁드립니다.
감사합니다.

2024-11-05 00:33 UTC, csh0034 requested changes
4단계 잘 진행해주셨네요 😄 
몇가지 고민해볼 사항 남겨두었는데
확인 부탁드립니다!

2024-11-05 00:33 UTC, csh0034 commented on src/main/java/lotto/domain/WinningLotto.java
> +    public WinningLotto(LottoNumbers lottoNumbers, LottoNumber lottoNumber) {
입력번호에 보너스번호가 포함되어있는지에 대한 검증을 추가해보는건 어떨까요?

2024-11-05 00:33 UTC, csh0034 commented on src/main/java/lotto/domain/WinningLotto.java
> +    public LottoRank lottoRank(LottoNumbers lottoNumbers) {
LottoRank 조회 하는부분을 적절하게 잘 옮겨주셨네요 👍

2024-11-05 00:33 UTC, csh0034 commented on src/main/java/lotto/domain/TryCount.java
> +    public void updateWithManualTry(int manualTry) {
추후에 변경을 하기보다 생성시점에 금액과 수동수를 전달 받아보는건 어떨까요?

2024-11-05 00:33 UTC, csh0034 commented on src/main/java/lotto/domain/LottoNumbers.java
>      public boolean bonusMatchingCount(LottoNumber bonusNumber) {
bonusMatchingCount 와 checkMatching 는 동일하지 않을까요? 🤔

2024-11-05 00:33 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +    public LottoResult updateWinningRankList(WinningLotto winningLotto) {
updateWinningRankList 와 lottoRankList 는 목적이 동일해보입니다.
LottoResult 를 반환하는 메서드명을 수정하여 합쳐보는건 어떨까요?

2024-11-05 00:33 UTC, csh0034 commented on src/main/java/lotto/domain/TryCount.java
> +            throw new IllegalArgumentException();
적절한 예외 메세지를 추가해보시면 좋을것 같습니다.

2024-11-05 00:33 UTC, csh0034 commented on src/main/java/lotto/ui/PrintView.java
> +    public static void printManualAndRandomTryCount(int manualTryCount, int lottoTryCount) {
상단 미사용 코드는 제거해주세요!

2024-11-05 12:20 UTC, lee-won-suk commented on src/main/java/lotto/domain/WinningLotto.java
> +    public WinningLotto(LottoNumbers lottoNumbers, LottoNumber lottoNumber) {
이것도 도메인 지식이 부족했네요;ㅜ
입력번호안에 보너스볼이 겹치는 케이스 검증 추가했습니다.

2024-11-05 12:21 UTC, lee-won-suk commented on src/main/java/lotto/domain/WinningLotto.java
> +    public LottoRank lottoRank(LottoNumbers lottoNumbers) {
감사합니다 🙏 당첨번호 관련 객체에서 처리하는게 자연스러웠습니다.

2024-11-05 12:37 UTC, lee-won-suk commented on src/main/java/lotto/domain/TryCount.java
> +    public void updateWithManualTry(int manualTry) {
안그래도 좀 고민이 됐습니다.
같이 받자니 수동수를 입력받는 시점 다음에 에러처리되는걸 좀 피하고 싶었습니다. 내부에 검증을 추가를 더 하고 내부 로직을 LottoMain에서 TryCount 안으로 집어넣었습니다!

2024-11-05 12:43 UTC, lee-won-suk commented on src/main/java/lotto/domain/Lotto.java
> +    public LottoResult updateWinningRankList(WinningLotto winningLotto) {
맞습니다. 하나로 합친후, 명칭을 변경했습니다.

2024-11-05 12:44 UTC, lee-won-suk commented on src/main/java/lotto/domain/TryCount.java
> +            throw new IllegalArgumentException();
넵 추가완료했습니다!

2024-11-06 03:11 UTC, csh0034 requested changes
리뷰 반영 잘해주셨네요 😄 
간단한 리뷰 몇가지 남겨두었으니 확인 부탁드립니다!

2024-11-06 03:11 UTC, csh0034 commented on src/main/java/lotto/domain/WinningLotto.java
> +           throw new IllegalArgumentException("보너스볼은 당첨번호와");
메세지가 잘렸네요 😁

2024-11-06 03:11 UTC, csh0034 commented on src/test/java/lotto/WinningLottoTest.java
> +    public void checkBonusInWinningLottoTest() {
검증또한 잘 추가해주셨네요 👍

Rank 를 구하는 부분도 추가되었다면 더 좋았을것 같아요!

2024-11-06 03:11 UTC, csh0034 commented on src/main/java/lotto/domain/Lotto.java
> +        List<LottoRank> lottoRanks = lottoNumbersList.stream()
하단과 같은 방법으로도 반환 가능하겠네요!

```suggestion
        return lottoNumbersList.stream()
                .map(winningLotto::lottoRank)
                .filter(lottoRank -> lottoRank != LottoRank.NONE)
                .collect(Collectors.collectingAndThen(Collectors.toList(), LottoResult::new));
```

2024-11-06 03:11 UTC, csh0034 commented on src/test/java/lotto/LottoNumbersTest.java
>      public void 당첨번호_일치개수별_랭크테스트_보너스볼포함(int startNumber, int endNumber, int bonusNumber, LottoRank lottoRank) {
당첨번호에 보너스번호 포함 검증이 추가되며
테스트케이스가 실패하네요 🥲

코드수정이후엔 테스트케이스 실행을 해보는 습관을 가져보시면 좋을것 같습니다!

2024-11-06 12:19 UTC, lee-won-suk commented on src/test/java/lotto/WinningLottoTest.java
> +    public void checkBonusInWinningLottoTest() {
넵넵 감사합니다. 테스트를 빼먹었군요 🫤  추가 완료했습니다.

2024-11-06 12:35 UTC, lee-won-suk commented on src/test/java/lotto/LottoNumbersTest.java
>      public void 당첨번호_일치개수별_랭크테스트_보너스볼포함(int startNumber, int endNumber, int bonusNumber, LottoRank lottoRank) {
부끄러운 얘기지만 테스트코드들이 에러가 났는지만 파악했습니다 🤕🤕🤕
앞으로는 꼭 코드수정이후 모든 테스트코드들을 실행해봐야겠습니다.
수정완료했습니다!

2024-11-07 00:51 UTC, csh0034 approved these changes
리뷰 반영 잘 해주셨네요 💯 
마지막 단계는 이만 머지하도록 하겠습니다.
그동안 수고 많으셨습니다 😄

2024-11-07 00:51 UTC, merged