[Step04] - 로또(수동) pr입니다.
next-step/java-lotto pull request #753
Opened 2020-08-19 15:59 UTC by samkko

안녕하세요 ~ :)
step04 - 로또(수동) 미션 pr입니다.
어느새 마지막 미션이네요!
피드백을 받아 점점 나아지는 코드를보며 기분이 좋았던 미션이였습니다~!!
이번 리뷰도 잘부탁드립니다. 👏🏻

2020-08-20 10:52 UTC, gwonsungjun requested changes
안녕하세요. 미션 진행하느라 고생하셨습니다 :)

구현 잘 해주셨는데, 실행 결과가 조금 다른 거 같아요!
코멘트도 몇 개 달았는데 같이 확인 부탁드립니다.

마지막이네요! 화이팅입니다 😄

2020-08-20 10:52 UTC, gwonsungjun commented on src/main/java/com/hskim/lotto/model/ManualTicketingNum.java
> +public class ManualTicketingNum {
해당 클래스를 프로덕션 코드에서 사용하고 있지 않아 보여요. 아니면 제가 못 찾는걸까요~?
확인 부탁드립니다 😄

2020-08-20 10:52 UTC, gwonsungjun commented on README.md
> +### Todo
꼼꼼한 Todo 작성 👍

2020-08-20 10:52 UTC, gwonsungjun commented on src/main/java/com/hskim/lotto/exception/LottoExceptionMessage.java
>      INVALID_PURCHASE_PRICE("구매 가격이 잘못되었습니다. 로또 한장의 가격은 " + LottoTicket.LOTTO_PRICE + "입니다."),
LottoExceptionMessage의 `INVALID_PURCHASE_PRICE` 상수는 사용하고 있지 않은 것 같네요 :)

2020-08-20 10:52 UTC, gwonsungjun commented on src/main/java/com/hskim/lotto/model/BonusNumber.java
> +        this.bonusNumber = new LottoNumber(bonusNumber);
합성으로 구현 잘 해주셨습니다! 💯

2020-08-20 10:52 UTC, gwonsungjun commented on src/main/java/com/hskim/lotto/model/LottoMachine.java
> +    public static List<LottoTicket> automaticIssuance(PurchasePrice purchasePrice, LottoNumberMaker numberMaker) {
리턴 타입을 `List<LottoTicket>` 대신 `LottoTickets` 클래스를 활용해보는 것이 어떨까요~?

2020-08-24 02:04 UTC, gwonsungjun approved these changes
안녕하세요! 피드백 반영 잘 해주셨습니다 💯 

이번 로또 미션은 여기서 마무리 지을게요!
많은 피드백들이 있었는데 끝까지 반영해주시느라 고생하셨습니다. 

다음 미션에서는 더 많이 배우시길 바랄게요! 😄

2020-08-24 02:04 UTC, merged

2020-08-24 02:33 UTC, samkko commented
성준님 덕분에 많이 배워갑니다!! 
감사합니다 🙇