3단계 - 로또(2등)
next-step/java-lotto pull request #786
Opened 2020-08-24 19:31 UTC by ap-jylee

실수로 브란치를 만들지 않고 푸쉬해버렸습니다.. ㅠㅠ

2020-08-25 04:09 UTC, gale34 commented on src/main/java/step3/domain/LottoNo.java
> +public class LottoNo implements Comparable {
Comparable의 타입을 명확히 해주는건 어떨까요?:)
```suggestion
public class LottoNo implements Comparable<LottoNo> {
```
이렇게 되면 compareTo()도 바꿔야하긴 합니다:)
제네릭 타입을 사용할땐 Raw 타입을 그대로 사용하지 않도록 주의해야 합니다!
아래 블로그를 참고해주세요!
https://madplay.github.io/post/dont-use-raw-types

2020-08-25 04:11 UTC, gale34 commented on src/main/java/step3/domain/LottoNo.java
> +public class LottoNo implements Comparable {
그리고 LottoNumber로 풀네임을 사용하는건 어떨까요? :)
https://myeonguni.tistory.com/1596 **9. 2 Classes** 를 참고해주세요!

> 완전한 단어를 사용하고 두 문자어와 약어는 피하도록 한다(만약, 약어가 URL이나 HTML과 같이 더 많이 ,더 넓게 사용되고 있다면 약어를 사용하는 것도 괜찮다).

2020-08-25 04:12 UTC, gale34 commented on src/main/java/step3/domain/LottoNo.java
> +    private final boolean matchBonus;
LottoNo는 어떤 역할과 책임을 가진 객체인가요?:)
Lotto 번호만 포장하는 객체라면 matchBonus는 다른 객체(아마 WinningNumbers)에서 가지고 있는게 나을 것 같습니다:)

2020-08-25 04:14 UTC, ap-jylee commented on src/main/java/step3/domain/LottoNo.java
> +public class LottoNo implements Comparable {
앗.. 이거 다음 스텝 요구사항이 LottoNo 로 구현하는거라서 이렇게 했습니다!

2020-08-25 04:15 UTC, gale34 commented on src/main/java/step3/domain/LottoNo.java
> +        }
1~45의 LottoNo을 static으로 관리하는건 어떨까요?
같은 값이고 변다른 추가 속성이 없다면(matchBonus가 분리된다면) enum을 사용하듯 static으로 관리하고 캐시해서 사용하면 좋을 것 같습니다:)

2020-08-25 04:16 UTC, gale34 commented on src/main/java/step3/domain/LottoNo.java
> +    }
LottoNo의 책임으로 어울릴 지, WinningNumbers에 어울릴지 다시 한번 생각해보세요! :)

2020-08-25 04:17 UTC, ap-jylee commented on src/main/java/step3/domain/LottoNo.java
> +    private final boolean matchBonus;
그럼 BonusBall 정도의 객체가 하나 더 필요할 것 같은데요..!
WinningNumbers 에 List<LottoNo> 와 BonusBall 을 가지고 있어야할까요?
일급콜렉션에는 하나의 자료구조만 있어야 한다고 했는데 BonusBall 을 가지고 있는건 상관이 없는건지요

2020-08-25 04:21 UTC, gale34 commented on src/main/java/step3/domain/Lotto.java
> +                .isPresent();
```suggestion
        return numbers.stream()
                .anyMatch(winningNumbers::isMatchBonus);
```
로 축약할수있을 것 같네요:)

2020-08-25 04:21 UTC, gale34 commented on src/main/java/step3/domain/Lotto.java
> +    public int findWinningNumbersCount(WinningNumbers winningNumbers) {
private으로 바꿔도 될 것 같네요:)

2020-08-25 04:24 UTC, gale34 commented on src/main/java/step3/domain/Rank.java
> +    }
안쓰는 메소드는 지워주세요!

2020-08-25 04:24 UTC, gale34 commented on src/main/java/step3/domain/Rank.java
> +    public static Rank valueOf(int countOfMatch, boolean matchBonus) {
enum에 기본적으로 valueOf라는 메소드가 있기 때문에, 헷갈릴 수 있을 것 같습니다 :) 다른 이름을 사용해보는 건 어떨까요?

2020-08-25 04:25 UTC, ap-jylee commented on src/main/java/step3/domain/Rank.java
> +    public static Rank valueOf(int countOfMatch, boolean matchBonus) {
앗.. 이것도 제공해준 코드라서..

2020-08-25 04:25 UTC, gale34 commented on src/main/java/step3/domain/Rank.java
> +                .orElse(Rank.MISS);
enum 조회 성능을 높이는 방법을 참고하세요!
https://pjh3749.tistory.com/279

2020-08-25 04:26 UTC, gale34 commented on src/main/java/step3/domain/Rank.java
> +public enum Rank {
enum 잘 적용해주셨습니다:)
step2까지 사용하셨던 Map 방식과 비교해보시고, 어떤 장단점이 있을지 생각해보시는 것도 좋을 것 같네요!

2020-08-25 04:30 UTC, gale34 commented on src/main/java/step3/domain/LottoFactory.java
> +                .collect(Collectors.toList()));
스트림을 사용하신다면, 아래처럼 바꿔도 될 듯 하네요:)
```suggestion
        return LOTTO_NUMBERS.subList(0, PICK_COUNT)
                .stream()
                .map(LottoNo::new)
                .collect(Collectors.toList());
```

2020-08-25 04:31 UTC, gale34 commented on src/main/java/step3/domain/LottoFactory.java
> +
이 클래스는 static 메소드만 있네요! priavte 생성자로 객체 생성을 막는건 어떨까요?

2020-08-25 04:33 UTC, gale34 commented on src/main/java/step3/domain/LottoResults.java
> +    public int calculateWinningNumbersCount(Rank rank) {
자기 자신과, 같은 패키지인 테스트 코드에서만 사용된다면, default 접근 제한자를 사용해도 좋을 것 같습니다:)

2020-08-25 04:40 UTC, gale34 commented on src/test/java/step3/domain/LottoTest.java
> +    }
Lotto 클래스의 생성자나 정적 팩토리 메소드로 해당 내용을 구현해두는건 어떨까요?
테스트만을 위한 메소드 생성은 지양해야하지만, 유연한 구조를 위해 다양한 정적 팩토리 메소드는 권장하는 편입니다:)

2020-08-25 04:40 UTC, gale34 commented on src/test/java/step3/domain/LottoTest.java
> +    }
`@ParameterizedTest`를 사용해서 반복 코드를 줄여보는 건 어떨까요?:)

2020-08-25 04:41 UTC, gale34 commented on src/test/java/step3/domain/RankTest.java
> +import org.junit.jupiter.params.provider.CsvSource;
안쓰는 import문은 제거해주세요!

2020-08-25 04:42 UTC, gale34 commented on src/test/java/step3/domain/LottoTest.java
> +public class LottoTest {
LottoFactory, Lottos, Money에 대한 테스트 코드도 필요합니다!

만약 실무라면, 간단한 기능이라 테스트 코드가 필요없을지도 모르지만.
지금 과정은 TDD 싸이클을 익히는 게 목적이므로, 테스트 코드가 항상 먼저 존재해야 한다는걸 잊지마세요!:)

2020-08-25 04:43 UTC, gale34 requested changes
미션 진행하느라 고생하셨습니다!
몇 가지 코멘트를 드렸는데요, 어렵지 않게 반영하실 수 있을 듯 합니다:)
궁금하신 점 있으면 DM 주세요!

2020-08-26 17:37 UTC, ap-jylee commented on src/test/java/step3/domain/LottoTest.java
> +public class LottoTest {
step2 에서 변한게 없어서 step3 에는 따로 추가하지 않았습니다..!ㅎㅎ

2020-08-29 06:46 UTC, ap-jylee commented on src/main/java/step3/domain/Rank.java
> +                .orElse(Rank.MISS);
countOfMatch 로 해시맵을 만들려고 했는데 2등과 3등이 중복되어 조금 애매한 것 같습니다.

2020-08-29 11:55 UTC, gale34 commented on src/main/java/step3/domain/Rank.java
> +                .orElse(Rank.MISS);
이 경우엔 두 가지 해결 방법이 있을 듯 합니다:)
1. 구현하신 것 처럼 valueOf() 내에서 먼저 2등인지 3등인지 판별 후, Map을 이용한 캐시 방법 적용. (실제 캐시에는 2등은 없고 3등만 포함되어 있겠죠.
2. countOfMatch 외에 보너스 볼 일치 유무 까지 조건으로 넣어서 캐시 사용. 이 경우엔 일종의 식별자? 객체를 따로 만들어야 하긴 합니다.
1번 방법이 간편하긴 하지만, 확장성을 위한 설계를 한다면 2번 방법도 괜찮을 것 같네요.
생각해보시고 반영해주세요!

2020-08-29 12:02 UTC, gale34 commented on src/main/java/step3/domain/LottoNo.java
> +    private final boolean matchBonus;
> 일급콜렉션에는 하나의 자료구조만 있어야 한다고 했는데 BonusBall 을 가지고 있는건 상관이 없는건지요

네. 일급 콜렉션에는 하나의 컬렉션만 가지고 있어야 합니다:) (상수는 포함가능)
그렇다면 어떻게 해야할까요??

List<LottoNo> winningNumbers 대신에 Lotto 객체를 가지고 있는 건 어떨까요?
그러니까 일종의 구성(Composition) 구조를 사용하는 겁니다:)
다시 말해, WinningNumbers는 일급컬렉션이 아닌, 그냥 객체가 되는 것이지요.
구성 구조 관련해서는 아래 글도 참고해보세요!
https://lelecoder.com/63

2020-08-29 12:10 UTC, gale34 commented on src/main/java/step3/domain/WinningNumbers.java
> +    }
https://github.com/next-step/java-lotto/pull/786#discussion_r479642737
를 참고하셔서 구성 구조를 가진다면, 이 메소드들도 약간의 변화를 주는 것이 좋아보입니다.

LottoNo의 getRank()를 WinningNumbers 객체가 갖도록 하는건 어떨까요?
**구입한 로또**라는 객체가 **당첨 로또 번호**를 메시지로 받아 **당첨 결과**를 반환하는 역할을 갖도록 할 것인지
**당첨 로또 번호**라는 객체가 **구입한 로또**를 메시지로 받아 **당첨 결과**를 반환하는 역할을 갖도록 할 것인지
의 차이 인데요.
객체의 **역할과 책임**에 비추어 봤을 때는 양쪽 다 무리는 없을 듯 합니다.

다만, 제가 말씀드린 구성 구조로 구현한다면, WinningNumbers의 상태값인 Lotto에서도 **당첨 결과**를 확인하는 역할을 가지고 있기 때문에, WinningNumbers가 자기 자신의 당첨 결과를 확인할 수 있는 어색한 구조가 될 것 같아서요.
주영님 생각은 어떠신가요? :)

2020-08-29 12:13 UTC, ap-jylee commented on src/main/java/step3/domain/WinningNumbers.java
> +    }
네 이 부분은 아무래도 로직을 몰아줄 수 있는 곳에 몰아주는 게 좋을 것 같습니다.

2020-08-29 12:19 UTC, gale34 commented on src/main/java/step3/domain/LottoNo.java
> +    }
https://github.com/next-step/java-lotto/pull/786#discussion_r476147153
이 피드백의 의도는
new Lotto(1) ~ new Lotto(45)를 미리 만들어두고, static으로 캐시처럼 관리해서 같은 객체가 불필요하게 많이 생성되는 걸 방지하고자 하는 거였습니다!

지금 LottoNo은 일종의 불변 객체인데요. 불변 객체의 장점도 많지만, 크리티컬한 단점 중 하나는 각 객체의 값마다 새로운 객체가 생성되야 하기 때문에, 리소스 관리가 필연적이라는 점입니다.
(불변 객체에 대해선 이 블로그를 참고해주세요:) https://velog.io/@conatuseus/Java-Immutable-Object%EB%B6%88%EB%B3%80%EA%B0%9D%EC%B2%B4)

그래서, LottoFactory의 LOTTO_NOS 처럼 미리 만들어두고, 정적 팩토리 메소드를 이용하여, 전혀 새로운 객체가 생성되지 못하도록 바꿔보는 건 어떨까요?

2020-08-29 12:22 UTC, gale34 commented on src/test/java/step3/domain/LottoTest.java
> +public class LottoTest {
아 그렇군요. 죄송합니다 😭  step별로 패키지가 따로 있어서 헷갈렸네요;

2020-08-29 12:23 UTC, gale34 commented on src/test/java/step3/domain/WinningNumbersTest.java
> +
WinningNumbers의 객체 생성 테스트를 추가하는건 어떨까요?
두 개의 상태값이 비정상적으로 들어올 때, 적절한 예외를 발생시키는 지도 체크하면 좋겠습니다 :)

2020-08-29 12:25 UTC, gale34 commented on src/test/java/step3/domain/LottoResultsTest.java
> +
`calculateWinningCountStatistics()` 에 대한 테스트 코드도 추가하는건 어떨까요?:)

2020-08-29 12:26 UTC, gale34 approved these changes
피드백 반영하느라 고생하셨습니다! 💯 
이전 피드백에 댓글과, 몇 가지 코멘트를 달았으니 반영해주시면 될 것 같습니다 :)
다음 단계에서 함께 진행해주세요!
머지할게요

2020-08-29 12:26 UTC, merged