Step3
next-step/java-lotto pull request #791
Opened 2020-08-25 15:06 UTC by great0417

step3 리뷰 요청 드립니다!

2020-08-26 13:33 UTC, ohtaeg requested changes
리뷰가 늦어 죄송합니다 🙏 
2등 구하는 미션을 잘 구현해주셨네요 👍 

몇 개의 고민거리를 드렸는데요. 마지막 미션을 진행하기전에 고민해보시면 좋은 경험이 될 것 같아
Request changes 하였습니다. 
피드백 반영 후 재요청 주시면 감사하겠습니다!

2020-08-26 13:33 UTC, ohtaeg commented on README.md
> +# 의문점1. enum인 WinningPrice에서 2등 3등을 구분짓는 static final 상수도 일급컬렉션에서는 제거되어야 할까요..?
어떤 일급컬렉션을 말씀하시는지는 이해를 못했습니다 ㅠㅠ
만약 WinningPrice에 대해 말씀을 하시는거라면 이미 2등, 3등을 구분짓는 값을 enum에서 가지고 있기 때문에 SECOND_PRIZE_CONDITION 상수는 제거해도 된다고 생각합니다.

2020-08-26 13:33 UTC, ohtaeg commented on README.md
> +# 매번 메소드 위치를 헷갈리는데 혹시 어디에 넣는게 가장 좋을까요..?
WinningStatistics 객체는 당첨을 통계해주는 책임을 가진 객체라고 생각이 됩니다.
WinningStatistics가 아닌 당첨을 판단해주는 책임을 가진 객체를 만드시고, 
해당 객체가 당첨 번호와 보너스 볼을 상태값으로 가지고 있는다면 어떨까요 :) ?
그렇다면 자연스럽게 당첨을 판단해주는 정보를 가지고 있기 때문에 캡슐화가 될 뿐더러 
WinningStatistics 객체의 책임을 위임할 수 있을 것 같습니다!

2020-08-26 13:33 UTC, ohtaeg commented on src/main/java/step3/domain/LottoFactory.java
> +    private int buyPrice;
LottoFactory 객체는 Lotto 객체를 만드는 생성 책임을 가지고 있다고 생각합니다.
구매 가격의 쓰임새를 보니 생성하는데 이용하지 않고 있으므로 구매 가격을 Factory가 가지고 있는것은 어색한 것 같아요. LottoGame같은 게임을 중재하는 객체를 만들어 구매 가격을 가지고 있고 main함수에서 다른 객체들에게 메시지를 보내고 있는것을 LottoGame을 통해 게임의 실행을 관리하는것도 좋을 것 같습니다 :)
희엽님의 의견은 어떠신가요?

2020-08-26 13:33 UTC, ohtaeg commented on src/main/java/step3/domain/WinningPrice.java
> +    private static final int SECOND_PRIZE_CONDITION = 5;
SECOND_PRICE, THIRD_PRICE가 이미 같은 값을 가지고 있으므로 상수로 관리할 필요가 있는지 고민해보아요 :)

2020-08-26 13:33 UTC, ohtaeg commented on src/main/java/step3/domain/WinningPrice.java
> +    }
winningNumbers 라는 네이밍 보다는 당첨 갯수 같은 네이밍이 더 자연스러울 것 같아요 :)
```suggestion
    public static WinningPrice valueOf(int winningCount, boolean matchBonus) {
        if (winningCount== SECOND_PRIZE_CONDITION && matchBonus) {
            return WinningPrice.SECOND_PRICE;
        }

        if (winningCount== SECOND_PRIZE_CONDITION && !matchBonus) {
            return WinningPrice.THIRD_PRICE;
        }

        return Arrays.stream(WinningPrice.values())
                .filter(priceValue -> priceValue.checkCount(winningCount))
                .findAny()
                .orElse(OTHER);
    }
```

2020-08-26 13:33 UTC, ohtaeg commented on src/main/java/step3/domain/WinningStatistics.java
> +    private LottoNumber bonusBall;
당첨 통계 객체가 많은 정보를 가지고 있는것 같아요. 
객체지향 생활 체조 원칙
>  규칙 7. 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

최대 3개의 인스턴스 필드를 가지도록 리팩토링하면 좋을 것 같습니다 :)
https://edu.nextstep.camp/s/CHzaWZ6z/ls/h0MfplLj

해당 코멘트에서 말씀드린것처럼 당첨 판단 책임을 가진 객체를 분리해보시면 어떨까요 :) ?

2020-08-26 13:33 UTC, ohtaeg commented on src/main/java/step3/view/PrintResult.java
> +            if(key.getPrice() == 30000000) {
해당 미션의 프로그래밍 요구사항이 존재하는데요 :)
- indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
    - 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
    - 힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 된다.

indent가 1이 되도록 수정해주세요!

2020-08-26 14:52 UTC, great0417 commented on src/main/java/step3/domain/LottoFactory.java
> +    private int buyPrice;
맞습니다 조건에 matchBonus가 true면 2등이므로 2등에서 true로 들어오는게 자연스럽게 되겠군요..ㅠㅠ

2020-08-26 14:53 UTC, great0417 commented on src/main/java/step3/domain/WinningPrice.java
> +    private static final int SECOND_PRIZE_CONDITION = 5;
맞습니다 ㅠㅠ matchBonus 가 이미 true,false이므로 2등 조건자체가 2등의 WinningNumbers로 구분지으면 되는군요 ㅠㅠ

2020-08-27 14:28 UTC, great0417 commented on src/main/java/step3/domain/LottoFactory.java
> +    private int buyPrice;
궁금한게 있습니다! 저번 리뷰어분도 그러셨고, Factory에 대한 저의 이해 개념이 리뷰어분들과 살짝 다른것 같아서 의견을 듣고 싶은데요! 저는 공장이라는 개념이라기에 어떤 가격이 주어지면 그 가격에 대한 수량이 뽑아지거나 한다고 생각을 해서 가격을 넣었는데, 이 경우에 LottoGame이랑 LottoFactory의 객체를 분리해서 LottoFactory의 구매가격에 대한 책임을 위임하면 되는건가요? 테스트를 작성 할때, LottoFactory에서 구매가격이 0원이라도 생성자에 선언을 해야하는 불편함이 있는데, 그 부분을 분리를 해야 하는걸까요..? 
아니면 태경님 말씀은, 메인 함수 내에서 다량의 생성자를 만드는 게 아니라, LottoGame이라는 생성자만 선언 후에, 메인메소드에서 해당 생성자만 선언할 수 있게 하라는 말씀이신걸까요..? 자바는 어렵네요..ㅠㅠ

2020-08-27 17:52 UTC, ohtaeg commented on src/main/java/step3/domain/LottoFactory.java
> +    private int buyPrice;
이전 리뷰어분과 제 생각이 같다면, 아마도 디자인 패턴의 팩토리 패턴에 가깝게 설명드리지 않았을까 합니다!
디자인 패턴에서 팩토리 패턴은 객체 생성 책임을 가진 패턴인데요!
Lotto를 생성하는 책임을 가진 객체로써, 오로지 Lotto 생성 책임 외에 책임을 가지지 않게됨으로써
변경을 최소화 하려는 것으로써, 해당 비지니스 로직을 가진 구매 가격을 생성 책임을 가진 팩토리가 가지게 된다면
변경의 이유가 추가가 되기에 해당 이유로 인해 리뷰를 드렸습니다!

말씀하신대로 디자인 패턴을 떠나 공장 개념으로 가격에 맞는 로또를 뽑는 객체라고 한다면 잘 설계해주셨습니다 👍 
말씀해주신대로 LottoFactory에서 구매가격이 0원이라도 생성자에 선언을 해야하는 불편함이 있다면 리팩토링을 어떻게 해야할지 고민해보시면 좋을 것 같아요. 물론 현재 설계 그대로 유지하셔도 좋은 설계라고 생각합니다 :)

> 메인 함수 내에서 다량의 생성자를 만드는 게 아니라, LottoGame이라는 생성자만 선언 후에, 메인메소드에서 해당 생성자만 선언할 수 있게 하라는 말씀이신걸까요..?

개인적으로 메인 함수를 호출한다는것은 클라이언트가 프로그램을 시작한다고 해석됩니다.
현재 클라이언트에서 다량의 생성자를 만들고 있고, 많은 로직이 수행되고 있어 정보가 많이 노출되었다고 생각합니다.
게임 실행을 중재하는 객체가 있다면 클라이언트에 노출되는 정보가 적어질거라고 생각하여 리뷰를 드렸습니다 :)

2020-08-28 11:04 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨습니다!
객체를 작게 분리 잘해주셨어요 👍

몇개의 피드백을 드렸는데, 다음 미션을 진행하시면서 반영해주세요!
마지막 미션도 화이팅입니다 💪

2020-08-28 11:04 UTC, ohtaeg commented on src/test/java/step3/domain/WinningStatisticsTest.java
> +        WinningStatistics winningStatistics = new WinningStatistics(lottoList, winningLottoNumbers);
두 메서드의 테스트가 실패하고 있습니다 😭 
확인해주세요!

2020-08-28 11:04 UTC, ohtaeg commented on src/main/java/step3/domain/WinningJudgement.java
> +    private final WinningLotto winningLotto;
winningLotto를 가지고 있을 필요가 있을지 고민해보아요 :)

2020-08-28 11:04 UTC, ohtaeg commented on src/main/java/step3/domain/LottoGame.java
> +        WinningJudgement winneingJudgement = new WinningJudgement(winningLotto);
변수명이 오타가 난 것 같아요!

2020-08-28 11:05 UTC, merged

2020-08-29 12:29 UTC, great0417 commented on src/main/java/step3/domain/WinningJudgement.java
> +    private final WinningLotto winningLotto;
WinningLotto  자체가 고정적이기때문에 파라미터로 빼는 방법으로 step4에 변경을 했는데요, WinningLotto를 WinninJudgement에 넣게 되면 객체 생성이 더 무거워져서 빼야 하는건가요..?
해당 부분도 그러면 빈 생성자인데.. static으로 빼야 하는..걸까요..?

2020-08-29 15:25 UTC, ohtaeg commented on src/main/java/step3/domain/WinningJudgement.java
> +    private final WinningLotto winningLotto;
WinningStatistics도 WinningLotto를 가지고 있는데 WinningJudgement 도 가지게 될 경우
두 객체가 WinningLotto를 관리하게 되는데요! 두 객체는 당첨이란 범주내에 있지만 서로 독립적인 객체이기에
같은 WinningLotto를 가지고 있다는 데이터 일관성을 보장할 수 없기에
WinningLotto가 여러 객체에 분포되어 관리 되고 있기에 관리포인트를 줄이고자 리뷰 드렸습니다 :)