Step4 4단계 - 로또(수동)
next-step/java-lotto pull request #796
Opened 2020-08-26 13:40 UTC by jhPark-CH

안녕하세요 리뷰어님,

4단계에서 로또(수동) 진행하였습니다.

리뷰 잘 부탁드립니다. 감사합니다❗

2020-08-26 13:59 UTC, seogi89 requested changes
기능 구현 잘 해주셨네요.
코멘트 드릴 사항이 많지는 않지만, 로또를 생성하는 부분의 복잡도가 너무 높은 것 같아요
해당부분 고민해보고 리펙토링 진행해주세요.

2020-08-26 13:59 UTC, seogi89 commented on src/main/java/lotto/controller/LottoController.java
>          final Rankings rankings = Rankings.of(lottos.matchesWinningLotto(winningLotto));
`Rankings rankings = lottos.matchesWinningLotto(winningLotto)` 로 작성하는건 어떤가요?

2020-08-26 13:59 UTC, seogi89 commented on src/main/java/lotto/domain/LottoStore.java
> +                .concat(new AutoLottoGenerator(lottoCount.calculateCount(money.getPrice())).generate());
메소드의 중첩이 너무 심해서 가독성도 떨어지고 무슨 동작을 하는지 이해할 수 없어요.
[규칙 4: 한 줄에 한 점만 사용](https://developerfarm.wordpress.com/2012/01/30/object_calisthenics_5/) 도 심각하게 위반하고 있구요.

2020-08-26 13:59 UTC, seogi89 commented on src/main/java/lotto/domain/AutoLottoGenerator.java
>          List<LottoNumber> lottoNumbers = LottoNumber.findLottoNumberValues();
해당 객체가 값을 가지고 있는것이 자연스럽지 않을까요?

2020-08-26 13:59 UTC, seogi89 commented on src/main/java/lotto/domain/AutoLottoGenerator.java
> +    private final int issueCount;
해당 객체가 가지고 있어야 하는 상태 일까요?

2020-08-26 13:59 UTC, seogi89 commented on src/main/java/lotto/domain/ManualLottoGenerator.java
> +    private final List<List<Integer>> manuals;
해당 객체가 가지고 있어야 하는 상태 일까요?
중첩이 생겨서 가독성이 떨어지는것 같아요.

2020-08-26 13:59 UTC, seogi89 commented on src/main/java/lotto/domain/Lottos.java
> +    public Lottos concat(Lottos others) {
concat 을 할 필요가 있을까요
생성된 List<Lotto> 를 한번에 Lottos 로 만들어줘도 될것 같아요.

2020-08-26 13:59 UTC, seogi89 commented on src/main/java/lotto/domain/LottoCount.java
> +public class LottoCount {
어떤 역할을 하는 객체인지 설명해주실수 있으신가요 ?

2020-08-26 13:59 UTC, seogi89 commented on src/main/java/lotto/domain/AutoLottoGenerator.java
> +                .collect(collectingAndThen(toList(), Lottos::of));
`
```suggestion
        return Stream.generate(this::generateAutoNumbers)
                .limit(issueCount)
                .collect(collectingAndThen(toList(), Lottos::of));

```

와 같이 생성하는것이 좀 더 명확하게 의미를 전달 할 수 있을 것 같아요.

2020-08-27 11:45 UTC, jhPark-CH reviewed
안녕하세요 리뷰어님,
말씀하신 부분 리팩토링 했습니다. 리뷰 부탁드립니다. 🙏

2020-08-27 14:39 UTC, seogi89 approved these changes
로또 미션 진행하시느라 너무 고생 많으셨습니다.
좋은 개발자로 성장하는데 조금이나마 도움이 되셨기를 바라봅니다.

마지막으로 몇가지 코멘트 및 팁 남겨 놓았으니 확인해주시면 감사하겠습니다.

저와의 미션은 종료되었지만, 궁금한점이나 어려운점 있으면 편하게 DM 주세요.
다시 한 번 너무 고생 많으셨습니다.

사다리 미션과 볼링 미션도 무사히 완주하세요 🔥 
감사합니다.

2020-08-27 14:39 UTC, seogi89 commented on src/main/java/lotto/domain/AutoLottoGenerator.java
> +    private final List<Integer> numbers;
인스턴스 필드에 재할당하여 사용하는 이유는 무엇인가요 ? 🤔

2020-08-27 14:39 UTC, seogi89 commented on src/main/java/lotto/domain/AutoLottoGenerator.java
>          return Lotto.of(generateAutoNumbers());
```suggestion
        return numbers.stream()
                   .limit(Lotto.LOTTO_SIZE)
                   .map(LottoNumber::of)
                   .collect(collectingAndThen(toSet(), Lotto::of))
```

2020-08-27 14:39 UTC, seogi89 commented on src/main/java/lotto/domain/AutoLottoGenerator.java
>                  .limit(Lotto.LOTTO_SIZE)
의미가 중복되는것 같아요 ㅎ

2020-08-27 14:39 UTC, seogi89 commented on src/main/java/lotto/domain/LottoStore.java
> +    public static final int ZERO = 0;
너무 범용적인 상수 이름인 것 같아요. 어떤 의미일까요 ? 🤔

2020-08-27 14:39 UTC, seogi89 commented on src/main/java/lotto/domain/LottoStore.java
>  public class LottoStore {
객체지향에서 유틸리티클래스를 만드는걸 선호하진 않지만, 해당 클래스를 유틸리티 클래스로 작성했을때 장/단점과
일반 클래스로 작성했을때 장/단점을 고민해보면 좋을 것 같아요.

2020-08-27 14:39 UTC, seogi89 commented on src/main/java/lotto/domain/LottoStore.java
> +                .map(numberText -> ManualLottoGenerator.of(numberText).generate())
ManualLottoGenerator가 꼭필요할지는 고민이드네요.

2020-08-27 14:39 UTC, seogi89 commented on src/main/java/lotto/domain/LottoStore.java
> +                .limit(calculateCount(money.getPrice()))
getter 를 사용하지 않고 Money에 메세지를 보내서 구매할 수 있는 장수를 구하는건 어떤가요?

2020-08-27 14:39 UTC, seogi89 commented on src/test/java/lotto/domain/LottoStoreTest.java
> +                .isEqualTo((price / LottoStore.LOTTO_PRICE) - manualLotto.size());
@MethodSource 를 이용하면 입력값과 기대값을 같이 인자로 받을 수 있어요.

2020-08-27 14:39 UTC, seogi89 commented on src/test/java/lotto/domain/LottoStoreTest.java
>      void findWinningLottoTest() {
6가지 케이스 모두 테스트하는건 어떤가요?

2020-08-27 14:39 UTC, merged

2020-08-28 06:04 UTC, jhPark-CH commented on src/test/java/lotto/domain/LottoStoreTest.java
>      void findWinningLottoTest() {
넵 테스트 케이스를 좀 더 작성해보겠습니다.

2020-08-28 06:06 UTC, jhPark-CH commented on src/main/java/lotto/domain/LottoStore.java
> +    public static final int ZERO = 0;
로또 번호의 matching count의 시작점인데 고민하고 변경하겠습니다 ㅠ

2020-08-28 06:10 UTC, jhPark-CH commented on src/main/java/lotto/domain/LottoStore.java
>  public class LottoStore {
처음에는 유틸리티 클래스로 수정했다가 나중에 재수정했는데 이 부분도 한번 고민해보겠습니다.