Step4 리뷰 요청 드립니다!
next-step/java-lotto pull request #801
Opened 2020-08-29 13:58 UTC by great0417

항상 친절한 설명 감사드립니다. step4 리뷰 요청 드립니다! 감사합니다!

2020-08-30 11:54 UTC, ohtaeg requested changes
리뷰가 늦어 죄송합니다 🙏 마지막 미션까지 구현을 잘해주셨습니다 👍 
미션 초기보다 객체 분리와 책임이 명확해지도록 잘 설계 된 것 같아요!

몇 개의 피드백을 드렸는데 확인 후 리팩토링 해주신다면 더 좋은 결과물이 나올 것 같아
Request changes 하였습니다. 

반영 후 재요청 주시면 감사하겠습니다 :)

2020-08-30 11:54 UTC, ohtaeg commented on README.md
> + # 만약에 현재 step3를 계속 사용하기 위해서, 복사해서 사용하고 있는데요, 바뀐 부분만 테스트를 진행해도 괜찮을까요..?
step마다 코드를 복사하게되면 중복해서 존재하는 단점이 존재합니다!
하나의 패키지에서 미션을 수행하시고 미션마다 요구사항대로 테스트 + 리팩토링하시는게 좋을 것 같아요 :)

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/LottoGame.java
> +    public LottoGame(int buyPrice, int manualQuantity) {
생성자에서 validation하는 부분을 메서드로 분리한다면 가독성이 좋을 것 같아요!

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/LottoGame.java
> +    public int autoQuantity() {
LottoGame 내부에서만 사용한다면 접근 제한을 최소화 하면 좋을 것 같아요!

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/LottoGame.java
> +        List allLottoList = LottoFactory.allLottoList(autoLottoList, manualLottoList);
```suggestion
        List<Lotto> manualLottoList = LottoFactory.makeLottoManualList(manualQuantity);
        List<Lotto> autoLottoList = LottoFactory.makeLottoRandomList(autoQuantity());
        List<Lotto> allLottoList = LottoFactory.allLottoList(autoLottoList, manualLottoList);
```

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/LottoFactory.java
> +            lottoList.add(makeLottoRandom());
'랜덤으로 로또를 만들어준다' 라는 메서드 명은 이미 존재하고 있어 명확하게 '자동으로 로또를 발급해준다'
라는 의미를 가진 네이밍은 어떨까요~?

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/LottoFactory.java
> +    public static Lotto makeLottoRandom() {
불필요한 공백은 제거해주세요!
```suggestion
    }

    public static Lotto makeLottoRandom() {
```

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/WinningJudgement.java
> +    }
makeWinningMap 메서드가 위에 위치하고 initWinningMap 메서드가 그 아래 위치한다면
자연스럽게 물 흐르듯 읽을 수 있을 것 같아요! 코드는 위에서 아래로 이야기처럼 읽혀야 좋다고 생각합니다 :)

```suggestion
    public Map<WinningPrice, Integer> makeWinningMap(List<Lotto> lottoList, WinningLotto winningLotto) {
        initWinningMap();
        for (Lotto lotto : lottoList) {
            putWinningMap(lotto, winningLotto);
        }
        winningMap.remove(WinningPrice.OTHER);
        return winningMap;
    }
    
    private void initWinningMap() {
        winningMap = new EnumMap(WinningPrice.class);
        for (WinningPrice winningPrice : WinningPrice.values()) {
            winningMap.put(winningPrice, 0);
        }
    }
```

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/WinningJudgement.java
> +    }
기본생성자를 생성하도록 구현하셨네요 :)

이전의 질문 주셨던 답변을 참고하시면 좋을 것 같아요!
https://github.com/next-step/java-lotto/pull/791#discussion_r479660021

makeWinningMap()을 호출해야만 winningMap이 초기화되도록 하는 것보다
정적 팩터리 메서드를 통해 winningMap을 초기화하는 방법도 좋아보입니다!
```
WinningJudgement.init();
```

[생성자 대신 정적 팩터리 메서드를 고려하라](https://velog.io/@litien/%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC)

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/WinningJudgement.java
> +    }
피드백 반영 👍

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/WinningPrice.java
> +    }
지역 변수를 생성하지 제거할 수 있을 것 같아요 :)
```suggestion
        if (winningCount == SECOND_PRICE.winningNumbers && matchBonus) {
            return WinningPrice.SECOND_PRICE;
        }

        if (winningCount == SECOND_PRICE.winningNumbers && !matchBonus) {
            return WinningPrice.THIRD_PRICE;
        }

        return Arrays.stream(values())
                .filter(priceValue -> priceValue.checkCount(winningCount))
                .findAny()
                .orElse(OTHER);
    }
```

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/WinningLotto.java
> +        }
넘어온 파라미터를 먼저 검사한 후 값을 넣어주는게 올바른 순서이지 않을까 합니다!

2020-08-30 11:54 UTC, ohtaeg commented on src/test/java/step4/domain/LottoTest.java
> +    }
무엇을 위한 테스트 인가요 :) ?

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/WinningStatistics.java
> +public class WinningStatistics {
아직도 테스트가 실패하고 있습니다. 확인 부탁드릴께요!

https://github.com/next-step/java-lotto/pull/791#discussion_r479130096

2020-08-30 11:54 UTC, ohtaeg commented on src/test/java/step4/domain/LottoFactoryTest.java
> +public class LottoFactoryTest {
수동으로 로또를 만드는 테스트를 추가해주세요!

2020-08-30 11:54 UTC, ohtaeg commented on src/main/java/step4/domain/WinningJudgement.java
> +public class WinningJudgement {
해당 객체는 당첨 결과를 관리하는 책임을 가지고 있는 것 같아요.
당첨을 판단한다는 네이밍보단 WinningResult 와 같은 당첨 결과를 관리한다는 네이밍으로 바꾸면 좋을 것 같아요!

2020-08-30 11:57 UTC, ohtaeg commented
기능단위로 commit 시 AngularJS Commit Message Conventions을 지켜주시면 좋을 것 같아요 :)
```
commit message 종류를 다음과 같이 구분

feat (feature)
fix (bug fix)
docs (documentation)
style (formatting, missing semi colons, …)
refactor
test (when adding missing tests)
chore (maintain)
```
https://edu.nextstep.camp/s/CHzaWZ6z/ls/XnkcO6ed

2020-08-30 16:03 UTC, great0417 commented on README.md
> + # 만약에 현재 step3를 계속 사용하기 위해서, 복사해서 사용하고 있는데요, 바뀐 부분만 테스트를 진행해도 괜찮을까요..?
중복해서 존재하는데.. 제가 각 리뷰사항마다 했던 단점들이나 실수들을 좀 돌아보고 싶어서요..ㅠㅠ

2020-08-30 16:16 UTC, great0417 commented on src/main/java/step4/domain/WinningStatistics.java
> +public class WinningStatistics {
WinningStatisticsTest의 경우 수정했습니다. 
WinningPrice 테스트의 경우 2등 3등을 비교하기 위해서 실패해야 하는게 의도된 테스트 코드인데, 의도대로 실패시, 성공하게 변경해야 할까요..?

2020-08-30 16:50 UTC, ohtaeg commented on src/main/java/step4/domain/WinningStatistics.java
> +public class WinningStatistics {
모든 테스트는 성공적으로 수행될 수 있도록 해주시면 좋을 것 같아요.
테스트가 실패한다는것은 불완전한 테스트라고 해석할 수 있으며, 코드의 신뢰가 떨어질 수 있다고 생각해요.
2등, 3등의 비교하여 실패하는 테스트는 결국 서로 다른 등수에 대한 테스트로 해석할 수 있으므로
실패에 대한 초점을 서로 다르다의 관점으로 옮겨 작성하시면 좋을 것 같습니다!

2020-08-30 16:52 UTC, ohtaeg commented on README.md
> + # 만약에 현재 step3를 계속 사용하기 위해서, 복사해서 사용하고 있는데요, 바뀐 부분만 테스트를 진행해도 괜찮을까요..?
그런 의도라면 중복해서 작성하셔도 좋을 것 같아요!
테스트도 똑같이 복사하여 이전 미션과 비교하는것도 좋지 않을까요 :) ?

2020-08-30 17:20 UTC, ohtaeg requested changes
피드백 반영을 잘해주셨습니다 👍 
미션을 마무리 하고싶지만 아쉬운 부분이 존재하여 해당 부분에 대하여 피드백을 드렸습니다.
확인 부탁드릴께요! 마지막 까지 화이팅입니다 💪 😄

2020-08-30 17:20 UTC, ohtaeg commented on src/main/java/step4/domain/LottoMap.java
> +    }
무조건 컬렉션을 포장한다고 해서 일급 컬렉션이라고 생각되지 않습니다 :)
일급 컬렉션은 말 그대로 오직 컬렉션을 보관하는 일종의 자료구조이며, 해당 컬렉션에 대한 비지니스 로직을 갖는
객체라고 할 수 있습니다. 해당 객체는 불필요하게 Wrapping 된 것 같아요 ㅠㅠ

[해당 피드백](https://github.com/next-step/java-lotto/pull/801#discussion_r479758685)에서 드렸던 의도는
메서드의 순서와 정적 팩터리 메서드의 활용을 고려하시면 더 좋은 설계와 가독성이 좋아질 것 같아 리뷰를 드렸습니다.  WinningResult 자체를 일급 컬렉션으로 잘 구현해주셨는데 제가 의도를 잘못 전달드려 기존의 설계가 깨진 것 같아 죄송하네요 ㅠㅠ

2020-08-30 17:20 UTC, ohtaeg commented on src/main/java/step4/domain/WinningLotto.java
> +public class WinningLotto {
당첨 객체가 매우 깔끔해졌네요 👍

2020-08-30 17:20 UTC, ohtaeg commented on src/main/java/step4/domain/WinningStatistics.java
> +        if (lottoList.size() == 0) {
```suggestion
        if (lottoList.isEmpty()) {
```

2020-08-31 13:45 UTC, great0417 commented on src/main/java/step4/domain/LottoMap.java
> +    }
오잉 아닙니다ㅋㅋㅋㅋ 어차피 리뷰 자체가 공부하는 입장이라..많은 도움이 되고 있습니다 감사합니다!

2020-08-31 16:58 UTC, ohtaeg approved these changes
수많은 피드백을 반영하시느라 고생 많으셨습니다 🎉 
로또 미션을 진행하면서 희엽님께 드린 피드백이 많은 도움이 되었으면 하는 바램이네요 😄 
남은 사다리, 볼링 미션도 응원하겠습니다 :)

비록 저와 미션은 끝이 났지만 의논할 게 있다면 언제든지 편하게 슬랙으로 DM 주세요 :)
그동안 수고 하셨습니다. 🥇
감사합니다. 🙇

2020-08-31 16:58 UTC, ohtaeg commented on README.md
> + # 꼼꼼하게 리뷰해주셔서 너무너무 감사합니다. 혹시나 또 수정사항이나, 고쳐야 할 사항이 알려주시면 감사하겠습니다!
😄 👍

2020-08-31 16:58 UTC, ohtaeg commented on src/main/java/step4/domain/WinningResult.java
>              winningMap.put(winningPrice, 0);
정적 팩터리 메서드를 이용한다면 다음과 같이 구현할 수 있을 것 같아요 :)
```
    private final Map winningMap;

    private WinningResult(final Map winningMap) {
        this.winningMap = winningMap;
    }
    
    public static WinningResult init() {
        Map winningMap = new EnumMap(WinningPrice.class);
        for (WinningPrice winningPrice : WinningPrice.values()) {
            winningMap.put(winningPrice, 0);
        }
        return new WinningResult(winningMap);
    }
```

2020-08-31 17:03 UTC, merged