Step4 - 로또 (수동)
next-step/java-lotto pull request #802
Opened 2020-08-29 14:16 UTC by LimHanGyeol

마지막 단계네요 .. !

이번에도 잘 부탁드리겠습니다 .. !
덕분에 많이 배우고 발전하고 있습니다.

코로나 조심하세요 !!

2020-08-30 08:34 UTC, tramyu requested changes
안녕하세요

간단한 몇가지 코멘트 남겨두었으니 확인 부탁드립니다~

2020-08-30 08:34 UTC, tramyu commented on src/main/java/lotto/domain/BonusNumber.java
> +}
원시값을 포장한 이점이 별로 없는것 같아요.

관리할 클래스가 늘어날 것 같은데, 아무 역할(validation)이 없다면  제거하는건 어떨까요.

2020-08-30 08:34 UTC, tramyu commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +        String[] manualLottoNumbers = new StringUtils(manualLottoNumber).split(INPUT_WINNING_NUMBER_DELIMITER);
StringUtils에 생성자로 String을 받은 뒤 split, toInt를 해주는 것 같은데

static으로 toInt, split등의 기능을 제공하는게 Utils라는 이름에 좀 더 맞지 않을까요?

2020-08-30 08:34 UTC, tramyu commented on src/main/java/lotto/domain/LottoTicket.java
> +        return winningNumbers.isContainsLottoNumber(getLottoTicketNumber((int) number)) ? new Count(NUMBER_ZERO).update() : new Count(NUMBER_ZERO).getCount();
위에도 남겨두었지만

```suggestion
        return winningNumbers.isContainsLottoNumber(getLottoTicketNumber((int) number)) ? 1 : 0;
```

와 같이 쓰면 어떨까요?

2020-08-30 08:34 UTC, tramyu commented on src/main/java/lotto/domain/LottoTicket.java
> +    private boolean isBonusNumber(final WinningNumber winningNumber, long matchCount) {
2등인지, 3등인지 여부를 체크하는것으로 보입니다.

isBonusNumber는 혼란을 줄 수 있지 않을까요?

`isSecondRank` 등의 이름은 어떨까요.

2020-08-31 12:48 UTC, LimHanGyeol commented on src/main/java/lotto/LottoGame.java
>          Scanner scanner = new Scanner(System.in);
네 알겠습니다 ! Scanner는 InputView에서만 사용을 하여 InputView에서 초기화를 해줬습니다 !

2020-08-31 12:48 UTC, LimHanGyeol commented on src/main/java/lotto/domain/LottoService.java
> +    }
이 부분 변경점을 파악하고 InputView에서 처리하게 변경 했습니다 !

2020-08-31 12:49 UTC, LimHanGyeol commented on src/main/java/lotto/view/InputView.java
> +    public static String setManualLottoNumber(Scanner scanner) {
네 앞으로 값을 입력받는 기능을 구현할 경우에는 input으로 처리를 해야겠네요 ,, !

2020-08-31 12:49 UTC, LimHanGyeol commented on src/main/java/lotto/domain/Count.java
> +public class Count {
원복 했습니다 ! 특별한 역할이 없는데 원시값을 그냥 다 래핑해도 되나 ?? 라는 의문점이 있었는데,
무조건 래핑하는것이 좋은게 아님을 알았습니다 !

2020-08-31 12:50 UTC, LimHanGyeol commented on src/main/java/lotto/domain/BonusNumber.java
> +}
Count, BonusNumber 클래스 제거했어요 !

2020-08-31 12:52 UTC, LimHanGyeol commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +        String[] manualLottoNumbers = new StringUtils(manualLottoNumber).split(INPUT_WINNING_NUMBER_DELIMITER);
이 부분에 대해서는, 레이싱카 미션이 끝나고 다른 분들의 코드를 구경한 일이 있었어요.
그 중 유틸 클래스로
https://www.mimul.com/blog/oop-alternative-to-utility-classes/
위 링크의 피드백을 보았고,
해당 부분을 보고 적용을 하게 됐는데요.

그래서 유틸 클래스는 어떻게 쓰는게 좋을까? 라는 생각도 들더군요.
규남님 시간이 괜찮으시다면 위 포스팅에 대한 생각을 여쭙고 싶어요.

2020-08-31 12:53 UTC, LimHanGyeol commented on src/main/java/lotto/domain/LottoTicket.java
> +    private boolean isBonusNumber(final WinningNumber winningNumber, long matchCount) {
그 부분을 간과했네요 ! 네이밍 변경했습니다 !

2020-08-31 13:30 UTC, tramyu commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +        String[] manualLottoNumbers = new StringUtils(manualLottoNumber).split(INPUT_WINNING_NUMBER_DELIMITER);
저 방법 자체는 괜찮은 것 같아요, 하지만 만약 저렇게 사용할거라면 저는 Util 대신 다른 용어를 사용해 클래스를 정의할 것 같습니다.

StringParser 라던가..사실 큰 차이는 없겠지만 저렇게 객체지향적인 느낌을 살릴거라고 한다면 Util이란 이름도 사용하지 않는게 좋을 것 같아요.

Spring이나 대부분 라이브러리들의 Utils로 제공되는 클래스들은 static 메소드를 통해 기능을 제공하는 경우가 많아서 헷갈릴 수 있을 것 같네요.

2020-08-31 13:31 UTC, tramyu commented
요거 혹시 못보실까봐 밑에 별도로 코멘트 따두었어요.

질문

```
이 부분에 대해서는, 레이싱카 미션이 끝나고 다른 분들의 코드를 구경한 일이 있었어요.
그 중 유틸 클래스로
https://www.mimul.com/blog/oop-alternative-to-utility-classes/
위 링크의 피드백을 받으신 내용을 보았고,
해당 부분을 보고 적용을 하게 됐는데요.

그래서 유틸 클래스는 어떻게 쓰는게 좋을까? 라는 생각도 들더군요.
규남님 시간이 괜찮으시다면 위 포스팅에 대한 생각을 여쭙고 싶어요.
```

저 방법 자체는 괜찮은 것 같아요, 하지만 만약 저렇게 사용할거라면 저는 Util 대신 다른 용어를 사용해 클래스를 정의할 것 같습니다.

StringParser 라던가..사실 큰 차이는 없겠지만 저렇게 객체지향적인 느낌을 살릴거라고 한다면 Util이란 이름도 사용하지 않는게 좋을 것 같아요.

new StringParser(manualLottoNumber).split()
DELIMITER도 아예 SringParser 안에 숨겨도 괜찮을 것 같기도 하구요..

Spring이나 대부분 라이브러리들의 Utils로 제공되는 클래스들은 static 메소드를 통해 기능을 제공하는 경우가 많아서 헷갈릴 수 있을 것 같네요.

2020-08-31 13:33 UTC, tramyu approved these changes
마지막 단계까지 구현하시느라 고생 많으셨습니다.

남겨두신 질문에는 코멘트 남겨두었으니 별도로 확인 부탁드릴게요

고생 많으셨습니다. 머지할게요!

2020-08-31 13:33 UTC, merged

2020-08-31 13:41 UTC, LimHanGyeol commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +        String[] manualLottoNumbers = new StringUtils(manualLottoNumber).split(INPUT_WINNING_NUMBER_DELIMITER);
네 이해 됐습니다. 답변 감사합니다 !!