4단계 - 로또(수동)
next-step/java-lotto pull request #806
Opened 2020-08-30 08:24 UTC by skid901

2020-08-31 11:46 UTC, sah3122 commented
```
UI 클래스에서 도메인 클래스를 알고 있어야 하는 의문점이 생길것 같아요.
개인적으로는 UI 클래스는 도메인 클래스를 모르고 있는것이 의존성을 낮추기 위해 더 좋은 방향인것 같아요.
저는 이런 경우 DTO 클래스를 만들어 값을 넘겨주곤 합니다. 😄
```

DTO 클래스를 만들어 UI클래스에서 도메인 객체 또는 Service객체에게 값을 전달 해 의존성을 낮춰보는것이 목적 이었습니다. 
설명하기에 앞서 몇가지 용어들을 알려드릴게요 ! (알고 계시다면 패스해주세요 😄 )
DTO 클래스란 Data Transfer Object로서 단순히 값을 전달하기 위해 사용하는 객체 입니다. 
반면에 VO 와 Entity 는 DTO 와 비슷한것 같지만 다른 의미를 가지고 있죠. 
Value Object는 값을 전달 하면서도 불변 객체가 되어 특정한 의미를 가지게 되고 Entity는 식별자를 가지게 되며 식별자를 통해서 서로 다른 객체이고 구분을 할수 있는 상태가 됩니다. 

```java
    private LotteryNumber enterBonusLotteryNumber() throws NumberFormatException {
        System.out.println("보너스 볼을 입력해 주세요.");
        String bonusNumber = SCANNER.nextLine();
        return LotteryNumber.getLotteryNumber(bonusNumber);
    }

    public WinningLottery setupWinningLottery() {
        return (WinningLottery) tryCatchInputExceptions(() -> {
            System.out.println("지난 주 당첨 번호를 입력해 주세요.");
            Set<LotteryNumber> winningLotteryNumbers = enterLotteryNumberManually();
            LotteryNumber bonusLotteryNumber = (LotteryNumber) tryCatchInputExceptions(this::enterBonusLotteryNumber);
            return new WinningLottery(winningLotteryNumbers, bonusLotteryNumber);
        });
    }
```

 `LotteryNumber`와 `WinningLottery`을 예시로 이야기 해볼게요. 
두 객체의 차이점을 생각해보면 LotteryNumber 는 DTO 일까요 ?  답은 Value Object 일거에요. 
불변 객체이면서 LotteryNumber는 로또 게임에서 사용하는 숫자 객체라는 의미를 가지고 있죠. 
그렇다면 WinningLotttery는 어떨까요 ? 
WinningLottery 객체는 매주 값이 변하게 될것이고, 한 주 마다 값을 식별할 수 있는 식별자를 가져야 할거에요. 
그렇다면 WinningLottery는 Entity가 될 수 있습니다. 

InputView 라는 UI 클래스에서 식별자를 가져야 하는 객체를 만드는것이 적절할까요 ? 
만약 요구사항이 변경되어 주어지는 Input 값이 변경된다면 WinningLottery를 생성하는 로직이 수정되어야 할거에요. 
도메인(엔티티)객체는 가장 Pure하게 관리되어야 하고 최대한 의존성을 낮추는것이 중요합니다. 그러기 위해선 도메인을 생성하는 곳이 일반적으론 Service Layer 가 될것이고요. Input값을 Service Layer 까지 전달하기 위해서 필요한 객체가 DTO 입니다.  DTO 는 값을 전달하기만 할 뿐, 어떠한 비즈니스 로직도 갖지 않게 되니 여러 Layer 에서 사용할 수 있습니다.

위 예제를 기반으로 DTO 클래스를 정의해본다면 
```java
class WinningLottoeryDto {
List<String> lotteryNumbers;
또는 
Set<LotteryNumber> lotteryNumbers;
}

```
정도가 될거같네요. 

WinningLotteryDto 값을 ServiceLayer에 전달하여 WinningLottery 객체를 생성한다면 요구사항이 변경되더라도 Dto 클래스만 수정된다면 도메인 클래스는 그대로 유지할 수 있을거에요. 

설명이 길어졌네요.. ㅠㅠ 
이해가 힘들거나 궁금한점이 있다면 DM 주시면 될것 같아요 !

2020-08-31 11:47 UTC, sah3122 requested changes
리뷰가 늦어서 죄송합니다 😢 

몇가지 피드백과 질문 주신 부분 코멘트 달아두었습니다. 
확인후 설명이 부족하거나 이해가 되지 않는다면 편하게 DM 주시면 될것 같아요 !

2020-08-31 11:47 UTC, sah3122 commented on src/main/java/com/lotto/domain/Deposit.java
>  public class Deposit {
수동로또에 대한 금액 처리 좋네요 💯

2020-08-31 11:47 UTC, sah3122 commented on src/main/java/com/lotto/domain/Lotteries.java
> +    public void addLottery(Lottery lottery) {
일급 컬렉션을 불변으로 만들고 싶다면 add, remove와 같은 로직은 사라지는게 어울릴것 같아요. 
외부 클래스에서 List<lottery> 를 생성하고 생성된 lotteries 를 일급 컬렉션의 생성자로 받아 불변 객체로 사용할수 있답니다 👍 
일급 컬렉션을 불변으로 유지하느냐 가변으로 유지하느냐는 고민해 보시면 좋을것 같아요 😄

2020-08-31 11:47 UTC, sah3122 commented on src/main/java/com/lotto/domain/Lotteries.java
> +    public void publishLotteryAutomatically(int lotteryCount) {
불변과 관련해서 `로또 묶음은 자동 로또를 구입할 수 있다. ` 라는 모델링이 적합한지 고민해보세요.

2020-08-31 11:47 UTC, sah3122 commented on src/main/java/com/lotto/domain/Lotteries.java
> +    public Statistics calculateStatistics(WinningLottery winningLottery) {
마찬가지로 `로또 묶음은 통계를 계산할 수 있다.` 라는 모델링이네요. 
개인적으로는  수동 / 자동 로또를 구입하고 로또 결과를 계산하는 클래스는 유지 되는것이 좋을것 같아요. 
모델링이나 설계를 할때 소리내어 읽어보신다면 좋을것 같아요 ! 
`로또 묶음은 통계를 계산할 수 있다.` 보다는 `로또 게임(가칭)은 Deposit 을 사용하여 로또를 구입할 수 있다. 로또 게임은 로또 통계를 계산할 수 있다.` 와 같은 모델링이 조금더 적절할것 같습니다.

2020-09-01 12:19 UTC, skid901 commented
안녕하세요, 동철 님.

친절하고 상세하게 조언해 주셔서 진심으로 감사드립니다.

조언해 주신 내용을 바탕으로 `Entity`가 `View`와 분리되어야 하는 이유를 공부하여 아래와 같이 이해했습니다.

```
Entity 는 여러 서비스(로직)에서 빈번히 사용되는 피 의존성(?) 이 높은 객체이기 때문에,

순수성을 높여 직접적인 수정에 의해 사이드 이펙트가 발생하는 경우를 방지해야 하고,

View 객체에서는 요구사항(?) 이 빈번하게 변하기 때문에 그 사이에 완충 역할을 하는 DTO 객체가 필요하다.
```

한편, 위와 같은 논리로 `InputView` 뿐만 아니라 'ResultView' 에서도 `DTO`를 사용해보려고 고민을 했습니다.

하지만 `InputView` 과는 다르게 'ResultView' 에서는 `Entity` 내의 상태를 가공한 데이터가 필요함에 따라

2020-09-01 13:27 UTC, sah3122 commented
```
View 객체에서는 요구사항(?) 이 빈번하게 변하기 때문에 그 사이에 완충 역할을 하는 DTO 객체가 필요하다.
```
네 여러 레이어 간의 데이터 전달을 위해 DTO 객체가 필요한것 입니다 👍 

언급해주신것 처럼 Result값을 전달하기 위해서도 DTO를 사용합니다. 
도메인 객체를 response(Result)로 전달하는 것은 반드시 피해야하는 패턴입니다. 
Response DTO를 사용하는 이유는 도메인 객체가 외부로 노출되는것을 막을 뿐만아니라 도메인 하나가 Request와 1대1 매칭되는 경우는 없기 때문에 필요한 값만 전달하기 위한 Response DTO를 만들어서 사용합니다. 도메인 객체는 많은 상태(정보)를 가지고 있지만 항상 모든 정보가 필요한것은 아니기 때문이죠. 

VO 객체를 Input이나 Result view 에서 그대로 사용하는것을 허용하는 이유는 알고 계신것처럼 VO객체는 불변함을 정의하고 의미를 가지는 객체이고 외부로 노출된다 하더라도 시스템상 문제가 없기 때문이에요 😄 

ResultView로 어떤 값을 전달해야 하는지에 대한 결론은 `ResultView 에서 요구하는 값을 가진 DTO객체를 전달해줘야 한다.`입니다. 
또한 코멘트에서도 남겨둔것 처럼 DTO는 Entity 내부로직을 통해 생성하는것을 피해야 합니다. 😄 

DTO에 관한 내용은 이번 교육 과정을 진행하면서 구현해야하는 내용은 아닙니다 !

2020-09-01 13:30 UTC, sah3122 approved these changes
마지막 피드백까지 반영 잘해주셨습니다. 💯 

처음 부터 구조를 잘 잡아주시고 마지막 까지 깔끔하게 구현해주셔서 많은 피드백을 드리진 못했네요 🙏 
질문에 대한 답변은 코멘트로 남겨두었습니다. 
지금처럼 하시면 남은 미션들은 충분히 완주하실수 있을것 같아요 😄 
미션이 끝나도 개발 관련 이야기는 언제든 환영이니 편하게 DM 주세요 !

2020-09-01 13:30 UTC, sah3122 commented on src/main/java/com/lotto/dto/DepositDTO.java
> +    int amount;
특별한 이유가 없다면 인스턴스 변수는 private 접근제어자를 사용하여 외부 클래스에서의 접근을 막아주세요 😄

2020-09-01 13:30 UTC, sah3122 commented on src/main/java/com/lotto/dto/DepositDTO.java
> +    public Deposit of() {
일반적으로 DTO 객체에서 Entity 나 VO 를 생성하는 기능은 허용합니다. 하지만 반대로 Entity나 VO 객체에서는 DTO를 생성하는 기능을 구현하시면 안됩니다 😄 
VO와 Entity는 DTO의 존재를 알면 안되거든요 !

2020-09-01 13:31 UTC, merged