Step2 - 로또(자동)
next-step/java-lotto pull request #843
Opened 2020-09-13 11:26 UTC by Teatreeessential

몇가지 질문사항이 있습니다.

1. public String showLottoNumber() 메소드를 LOTTO내부에서 구현하였습니다. 올바른 책임인지 모르겠습니다. 뷰단에서 로또번호를 렌더링 할때 로또번호 리스트를 차례대로 보여줘야하는데
리스트를 그대로 GET하는것 보다 상태값을 가진 LOTTO에 해당 책임을 부여하는게 낫다고 생각했습니다. 하지만 렌더링 부분은 RenderView의 책임인데 이런식으로 구현해도 될지 궁금합니다.

2. indent를 두번 쓰지 말라고 적혀있으나 for문 내부에 조건에 따라서 if문을 사용하는 경우가 결국 생기게 되는데 이경우에는 메서드를 나눠야하는건가요??

3. public static Map<Rank, Integer> getInitRankInfo() 메소드를 Rank 내부에서 구현하였습니다. 해당 책임이 올바른지 궁금합니다. 등수를 관리하는 클래스 내부에서 당첨여부를 카운팅하는 
map을 초기화시키는게 가장 정확할 것이라고 생각하여 이곳에 구현하였습니다.

4. 최초에는 기능리스트를 생각하고 테스트코드부터 시작하지만 코드를 만들게 될수록 프로덕션 코드를 고친후 테스트코드를 작성하게됩니다.. 특정 클래스에 특정 메소드를 구현하고자 한다면
테스트코드부터 작성후에 생각하는게 맞는건가요??

2020-09-13 11:27 UTC, Teatreeessential commented
커밋 메세지를 잘못 넣었습니다.. 죄송합니다. 로또 (자동) 단계 입니다.

2020-09-13 12:49 UTC, ohtaeg requested changes
기능 구현을 잘해주셨습니다 👍 
주셨던 질문에 대해선 코멘트를 남겨드렸는데, 확인 부탁드릴께요!

구현해주신 기능에 대해 몇가지 피드백을 드렸는데 다음 미션을 진행하기전에 리팩토링을 해주시면
다음 미션을 원활하게 진행할 것 같아 Request changes 하였습니다!

반영후 재요청 주시면 감사하겠습니다 :)

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/Lotto.java
> +        ;
불필요한 세미콜론은 제거해주세요!

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/LottoIssuer.java
> +    }
재사용을 위한 로또 번호 숫자 캐싱 👍
정수타입으로 가지지 않고  LottoNumber 타입으로 변환해서 가지고 있는다면 
불필요하게 LottoNumber 를 생성할 일이 줄어 들고 재사용성이 더 좋아질 것 같은데 어떻게 생각하시나요 :) ?

```suggestion
    private static final List<LottoNumber> LOTTO_NUMBER_STORE = new ArrayList<>();

    static {
        for (int i = 1; i <= 45; i++) {
            LOTTO_NUMBER_STORE .add(new LottoNumber(i));
        }
    }
```

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber>{
Comparable 구현 👍 
```suggestion
public class LottoNumber implements Comparable<LottoNumber> {
```

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/LottoNumber.java
> +        return this.lottoNumber - other.lottoNumber;
해당 미션에서는 발생하지는 문제이지만 개인적으로 compare시 뺄셈 연산은 권장드리지 않아요 :)
뺄셈 연산 수행시 Integer.MIN_VALUE 혹은Integer.MAX_VALUE의 범위를 넘을경우 overflow가 발생할 수도 있으니
참고하시면 좋을 것 같아요! 

```suggestion
        return Integer.compare(this.lottoNumber, other.lottoNumber);
```

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/Dto/LottoDto.java
> +package step2.Dto;
패키지명은 소문자로 해주세요 :)

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/Lotto.java
> +    }
Q1. public String showLottoNumber() 메소드를 LOTTO내부에서 구현하였습니다. 올바른 책임인지 모르겠습니다. 뷰단에서 로또번호를 렌더링 할때 로또번호 리스트를 차례대로 보여줘야하는데
리스트를 그대로 GET하는것 보다 상태값을 가진 LOTTO에 해당 책임을 부여하는게 낫다고 생각했습니다. 하지만 렌더링 부분은 RenderView의 책임인데 이런식으로 구현해도 될지 궁금합니다.

말씀하신대로 이부분은 View에서 수행해야할 책임이라고 생각해요.
병찬님 말씀대로 상태값을 가지고 있는 객체에서 수행할 수 있다고 생각해요. 그렇기에
이렇게 메서드를 제공해주는것도 좋지만 객체가 가진 정보를 문자열로 만들어 출력하는
toString 메서드를 오버라이드하는건 어떨까요 :) ?

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/Lotto.java
> +            if (lottoNumbers.contains(lottoNumber)) {
Q2. indent를 두번 쓰지 말라고 적혀있으나 for문 내부에 조건에 따라서 if문을 사용하는 경우가 결국 생기게 되는데 이경우에는 메서드를 나눠야하는건가요??

프로그래밍 요구사항을 위배하셨네요 :)
충분히 나눠주실 수 있고 줄여주실 수 있다고 생각해요! 어떻게 리팩토링할지 고민해보면 좋을 것 같아요!

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/Lotto.java
> +    }
해당 정적 팩터리 메서드는 필요한 건지 고민해보시면 좋을 것 같아요 :)

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/PurChasedLotto.java
> +    private List<Lotto> purChasedLotto;
내부 구조를 잘 설계 해주셨기에 생성 이후로 값의 재 초기화가 될 일이 없는 것 같아요 👍
해당 인스턴스 필드에 final 키워드까지 추가하면 좋을 것 같아요!
외부에서 임의로 내부의 값을 제어할 수 없기 때문에 객체의 자율성이 보장되고 프로그램 내에서 변하지 않고
고정된 부분이 많아짐으로써 프로그램 안정도를 높일 수 있을 것 같아요!

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/PurChasedLotto.java
> +    private Map<Rank, Integer> rankInfo = Rank.getInitRankInfo();
구매한 로또에서 당첨 결과 정보를 가지게 된다면 많은 책임을 가지게 되는 것 같아요!
책임 분리를 위해 당첨 결과를 구매한 로또와 분리하면 어떨까요 :) ?

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/PurChasedLotto.java
> +            return;
return문은 제거해도 되지 않을까요 :) ?

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/Rank.java
> +    FIRST(6, 2000000000),
돈과 같은 1000단위로 구분은 다음과 같이 underbar(_)를 활용하면 코드의 가독성이 좋아질 수 있어요!
```suggestion
    FIRST(6, 2_000_000_000),
```

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/LottoIssuer.java
> +        int issueCnt = money / LOTTO_PRICE;
입력받은 금액을 VO로 만들어 관리한다면 어떤 장점이 있을까요 :) ?

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/Rank.java
> +    }
Q3. public static Map<Rank, Integer> getInitRankInfo() 메소드를 Rank 내부에서 구현하였습니다.
해당 책임이 올바른지 궁금합니다. 등수를 관리하는 클래스 내부에서 당첨여부를 카운팅하는
map을 초기화시키는게 가장 정확할 것이라고 생각하여 이곳에 구현하였습니다.

Rank에 대한 정보는 Rank가 알고 있으니 Rank 스스로가 만들어서 반환해주도록 잘 구현해주신 것 같아요 👍

2020-09-13 12:49 UTC, ohtaeg commented on src/main/java/step2/domain/PurChasedLotto.java
> +public class PurChasedLotto {
해당 객체에 테스트 코드가 존재하질 않네요!

2020-09-13 12:49 UTC, ohtaeg commented on src/test/java/step1/StringAddCalculatorTest.java
> +import org.junit.jupiter.api.Test;
Q4. 최초에는 기능리스트를 생각하고 테스트코드부터 시작하지만 
코드를 만들게 될수록 프로덕션 코드를 고친후 테스트코드를 작성하게됩니다.. 
특정 클래스에 특정 메소드를 구현하고자 한다면 테스트코드부터 작성후에 생각하는게 맞는건가요??

TDD를 진행하다보면 누구나 겪는 과정을 몸소 겪고 계시네요!! 
축하드립니다(?) 순항중이십니다 👍 
 
말씀해주신대로 테스트 코드를 작성하고, 테스트 코드에 맞게 프로덕션 코드가 리팩토링되는 과정은 정상이라고 생각해요. 현재 프로덕션 코드를 고친후 테스트 코드를 작성해주신다고 했는데, TDD를 고집하다보면 속도가 안나오는 경우가 있기에 이정도는 충분히 자신과의 타협이 될만한 부분이라고 생각합니다 ㅎㅎ
해당 객체에 해당 메서드를 구현하고자 한다면 테스트를 작성하면서 프로덕션 코드가 추가되는것이 맞는 것 같아요 :)

TDD의 최종목적은 잘 동작하는 깔끔한 코드를 작성하는 것입니다. 현재 겪고 계시는 고민들에 대한 과정을 겪다보시면 어느순간 목표 이미지를 미리 세운다 -> 자동화된 테스트 케이스를 작성한다 -> 만족시키는 로직을 작성하고 정제하는 과정이 몸에 베어 TDD를 능숙하게 하고 계시는 모습을 발견하게 되실거에요!

지금은 힘들어도 화이팅입니다!

2020-09-13 13:05 UTC, ohtaeg commented
현재 클린코드 과정은 AngularJS  진영의 커밋 방식을 채택하고 있습니다.
커밋 메시지 작성시 기능별로 작성해주시고 해당 컨벤션에 맞게 작성해주시면 감사하겠습니다 👍 
[AngularJS Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)

2020-09-14 13:18 UTC, Teatreeessential commented on src/main/java/step2/domain/Rank.java
> +    FIRST(6, 2000000000),
꿀팁 감사합니다

2020-09-15 05:30 UTC, ohtaeg requested changes
전반적으로 피드백 반영이 잘 안되어있네요 😭 
게임 진행을 위해 피드백 몇 개를 추가로 드렸는데, 이전 피드백과 이번에 드린 피드백을
함께 반영해주시고 재요청 주시면 감사하겠습니다 :)
함께 의논할 것이 있다면 언제든지 코멘트나 DM을 주세요 😄

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step1/algorithm/Calculate.java
> +public interface Calculate {
인터페이스도 클래스와 비슷한 네이밍 규칙을 따르며 able이나 ible 같은 형용사 어미를 붙일 수 있습니다.
동사를 사용하지 않고 명사 혹은 명사구를 사용해주시면 좋을 것 같아요 :)

[클린코드 - 의미있는 이름 (클래스)](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20%EC%9D%98%EB%AF%B8%20%EC%9E%88%EB%8A%94%20%EC%9D%B4%EB%A6%84.md#%ED%81%B4%EB%9E%98%EC%8A%A4-%EC%9D%B4%EB%A6%84)

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step1/StringAddCalculator.java
> +    public static int splitAndSum(String expression, Calculate calculate) {
외부로부터 의존성 주입 👍

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step1/util/PatternCache.java
> +public class PatternCache {
패턴 캐싱 👍

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step2/controller/LottoController.java
> +    public static void run() {
로또가 구매가 되질 않고 있네요 😭 확인 부탁드릴께요~
![image](https://user-images.githubusercontent.com/20432323/93168489-ef7a2480-f75d-11ea-850b-58d6fbb55df7.png)

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step2/domain/Money.java
> +    private int consumptionMoney = 0;
소비한 금액이 결국 구입 금액이라고 생각하는데요!
소비한 금액을 객체의 상태값으로 가질 필요가 있는지 고민해보아요 :)

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step2/domain/Money.java
> +    private static final int MINUMUM_MONEY = 1000;
오타가 난 것 같아요!
```suggestion
    private static final int MINIMUM_MONEY = 1000;
```

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step2/Dto/LottoDto.java
> +    public void setWinningLottoNumber(String winningLottoNumber) {
setter를 사용하지 않고 있는데, 남겨두신 이유가 있을까요~?

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step2/Dto/LottoDto.java
> +package step2.Dto;
아직 패키지명이 대문자로 되어있네요!

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step2/domain/Money.java
> +    private void updatePossessionMoney(int goodsPirce) {
```suggestion
    private void updatePossessionMoney(int goodsPrice) {
```

2020-09-15 05:30 UTC, ohtaeg commented on src/main/java/step2/main.java
> +public class main {
클래스명은 대문자로 시작해주세요!
```suggestion
public class Main {
```

2020-09-15 05:30 UTC, ohtaeg commented on src/test/java/step2/domain/LottoTest.java
> +    }
두개의 테스트가 실패하고 있습니다. 확인 부탁드릴께요~

2020-09-16 14:10 UTC, Teatreeessential commented on src/main/java/step2/domain/Money.java
> +    private int consumptionMoney = 0;
해당 객체가 향후에는 다른 물품을 구매할 수도 있다고 생각해서 로또 금액을 해당 객체의 상태값으로 두기가 좀 애매했습니다. 말씀하신대로 소비금액도 같이 관리하게되어 코드가 복잡해지고 로또 구매가 안되는 에러도 발생하게 되었네요..
만일 로또가 아닌 다른 상품을 구매한다고 하면 다른 인자값을 받아드리는게 좋을까요? 아니면 구매금액을 상태값으로 두는게 좋을까요.. 과정시작하게되면서 인자 두개받는것도 깔끔하지않다고 생각되네요 ㅠㅠ

2020-09-16 14:11 UTC, Teatreeessential commented on src/test/java/step2/domain/LottoTest.java
> +    }
해당 테스트가 올바르지 않은것 같습니다.. 동일번호의 로또가 있다고해서 두 로또가 동일하다고 여기는것은 문제가 있는것 같습니다... 삭제후 반영하겠습니다.

2020-09-17 04:37 UTC, ohtaeg commented on src/main/java/step2/domain/Money.java
> +    private int consumptionMoney = 0;
현재 요구사항에 맞는 도메인 도출이 된 것이기에 구매 금액을 상태값으로 가지고 있어도 무방하다고 생각됩니다.
만약 말씀해주신대로 다른 상품을 구매해야된다고 변경이 된다면 도메인의 변경이 일어나는 것이기에
그에 맞게 다른 인자값을 받는것도 고려해볼 수 있다고 생각됩니다 :)

2020-09-17 04:59 UTC, ohtaeg approved these changes
피드백이 아직 반영되지 않은 부분이 많이 있네요 😭 
추가로 드린 피드백과 이번에 드린 피드백을 반영해주신 후 다음 미션을 진행해주시면
좀 더 수월하게 미션을 진행하실 수 있을 것 같아요!
드렸던 피드백을 한번 고민해보시면 좋을 것 같습니다 :)
이만 머지하겠습니다! 다음 미션을 진행해주세요!

2020-09-17 04:59 UTC, ohtaeg commented on src/main/java/step1/algorithm/calculableUsingDelimiter.java
> +public class calculableUsingDelimiter implements Calculable {
클래스명이 소문자로 시작하고 있습니다 😭 
```suggestion
public class CalculableUsingDelimiter implements Calculable {
```

2020-09-17 04:59 UTC, ohtaeg commented on src/main/java/step1/algorithm/CalculationCache.java
>      private static class SingletonHelper{
```suggestion
    private static class SingletonHelper {
```

2020-09-17 04:59 UTC, ohtaeg commented on src/main/java/step1/algorithm/CalculationCache.java
> +        return SingletonHelper.CALCULABLE_USING_DELIMITER;
해당 메서드를 사용하지 않고있기에 사용하는 방향으로 리팩토링 해주시거나 제거하면 어떨까요 :) ?

2020-09-17 04:59 UTC, ohtaeg commented on src/main/java/step2/domain/LottoIssuer.java
> +        for (int i = 0, j = money.getNumberOfPurchases(LOTTO_PRICE); i < j; i++) {
로또 구매 금액에 대한 VO를 잘 만들어 주셨기 때문에 이제 LottoIssuer가 굳이 Lotto 가격을 관리하고 있을 필요없고 Money 객체가 로또 구매 금액을 알고 있기에 파라미터로 전달하지 않고 바로 물어봐도 되지 않을까요 :) ?
```suggestion
        for (int i = 0; i < money.getNumberOfPurchases(); i++) {
```

2020-09-17 04:59 UTC, ohtaeg commented on src/main/java/step2/domain/LottoIssuer.java
>      public static List<Lotto> issue(Money money) {
issue라는 네이밍보다 로또 번호, 로또 복권을 발급, 생성해주는 네이밍이면 더 직관적일 것 같습니다 :)

2020-09-17 04:59 UTC, ohtaeg commented on src/main/java/step2/domain/LottoIssuer.java
> +        for(int i = 1; i <= 45; i++){
```suggestion
        for (int i = 1; i <= 45; i++) {
```

2020-09-17 04:59 UTC, ohtaeg commented on src/main/java/step2/domain/LottoIssuer.java
> +    }
이전에 드렸던 해당 피드백을 한번 고민해주시면 좋을 것 같습니다 :)
https://github.com/next-step/java-lotto/pull/843/files#r487521113

2020-09-17 05:00 UTC, merged

2020-09-18 05:16 UTC, Teatreeessential commented on src/main/java/step2/domain/LottoIssuer.java
> +    public static List<Lotto> issue(int money) {
로또 발급기라는 의미 입니다

2020-09-18 16:50 UTC, ohtaeg commented on src/main/java/step2/domain/LottoIssuer.java
> +    public static List<Lotto> issue(int money) {
발급하다의 의미로 사용해주셨군요 👍 
보통 Issue라 하면 논쟁, 발표의 의미가 강해서 한번에 의미가 와닿지 않아 드렸던 리뷰였습니다 😄 
의견을 공유해주셔서 감사합니다! 네이밍은 그대로 사용해주시면 좋을 것 같아요 :)