ghojeong(고정완) [Step2] 로또(자동)
next-step/java-lotto pull request #874
Opened 2020-11-12 15:34 UTC by ghojeong

테스트 코드를 작성하다 보니, 코드가 엄청 길어지네요...
추가된 코드 줄 수가 2천줄이 넘는데, 리뷰어님 화이팅입니다!!

2020-11-12 15:37 UTC, ghojeong commented on src/main/java/lotto/controller/strategy/RandomStrategy.java
> +public class RandomStrategy implements GenerateStrategy {
컨트롤러 부분에서 랜덤하게 로또를 만드는 부분을 어떻게 해야할지 막막합니다. (generateLotto)

2020-11-12 15:37 UTC, ghojeong commented on src/main/java/lotto/domain/Lotto.java
> +    }
거의 동일한 로직에 타입만 다를 뿐인데,
이와 같은 코드 중복을 없애는 방법이 있을까요?

2020-11-12 15:53 UTC, ghojeong commented on src/main/java/lotto/domain/LottoNoPool.java
> +    }
Null Pointer Exception 에 대응하기 위해,
Optional 을 활용해봤는데, 이렇게 사용하는게 적절한지 여쭈어봅니다.
아무래도 Optional 을 처음 사용해봐서요.

2020-11-12 23:15 UTC, ghojeong commented on src/main/java/lotto/domain/Lotto.java
> +    }
Template 을 사용할까 고민을 해봤는데, 타입을 String 과 int 로 강제시키고 싶어서요.
Typescript 에는 [user-defined-type](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) 이라는게 있는데, 이런게 자바에도 있는지 궁금합니다.

2020-11-13 00:34 UTC, ghojeong commented
다음 부터는 array 자료형들도 전부 List  자료형으로 통일할까 생각하는데,
array 없이 List 인터페이스만 사용하는 것에 대해 어떻게 생각하세요?

성능상 단점을 감수하고서라도, 함수 인자 및 객체 맴버에 대한 인터페이스를 통일해야겠다는 생각이 들었습니다.

2020-11-13 01:21 UTC, ghojeong commented
클래스가 많아지다보니, intelliJ 의 code Iris 플로그인으로 클래스 및 패키지 다이어그램을 그렸을 때 해상도가 너무 낮게 나오는데,

@ohtaeg 리뷰어님은 어떻게 클래스 및 패키지 다이어그램을 그리시는지,
비법이 있으면 좀 알려주세요.

<img width="1132" alt="스크린샷 2020-11-13 오전 10 19 32" src="https://user-images.githubusercontent.com/38595650/99016144-c7f6db00-2599-11eb-8770-4375c9cf1baa.png">

2020-11-13 02:36 UTC, ghojeong commented on src/main/java/lotto/domain/LottoFactory.java
> +    }
`createLotto(List<Integer> lottoNos)`
`createLotto(List<String> lottoNos)`

이런식으로 오버로딩을 시도했지만 같은 List 인자라고 오버로딩에 실패하던데,
같은 createLotto 함수명을 사용하는 방법은 없을까요?

2020-11-13 02:38 UTC, ghojeong commented on src/main/java/lotto/utils/validator/LottoValidator.java
> +    }
이것도 하나의 validateLottoNos 이름으로 오버로딩 하고 싶은데, 어렵네요

2020-11-13 03:12 UTC, ghojeong commented on src/main/java/lotto/asset/ResultViewConst.java
> +    }
출력 텍스트를 모아둘려고 `JACKPOT_MSG` 와 `RATE_OF_RETURN_MSG` 를
ResultViewConst 안에 모아놓았는데,
따로 MessageGenerator 클래스를 만드는게 좋을까요?

2020-11-13 05:51 UTC, ghojeong commented on src/main/java/lotto/utils/validator/LottoValidator.java
> +    }
조언 주신 것에 따라 오버로딩을 시도하려다가,
`List<String> lottoNos`  자체가 군더더기라는 생각이 들어서,
lottoNo 는 항상 Integer 일 수 있도록 아예 삭제했습니다.

2020-11-13 05:51 UTC, ghojeong commented on src/main/java/lotto/domain/LottoFactory.java
> +    }
조언 주신 것에 따라 오버로딩을 시도하려다가,
`List<String> lottoNos`  자체가 군더더기라는 생각이 들어서,
lottoNo 는 항상 Integer 일 수 있도록 아예 삭제했습니다.

2020-11-13 05:56 UTC, ghojeong commented on src/main/java/lotto/domain/Lotto.java
> +    }
LottoNo 는 항상 Integer 일 수 있도록 `String no` 인 함수를 아예 삭제했습니다.

2020-11-13 06:20 UTC, ohtaeg commented on src/main/java/lotto/controller/strategy/RandomStrategy.java
> +public class RandomStrategy implements GenerateStrategy {
랜덤 이라는 요소는 일반적으로 테스트하지 않습니다.
이유는 테스트시 입력과 출력을 가정하고 특정 로직이 정상적으로 돌아가는가가 목적이 되는데,
랜덤 자체는 어떠한 규칙을 가지지 않는 불안정한 요소이기 때문에 테스트를 할 수가 없습니다 :)

랜덤 값을 테스트 하는게 아닌 랜덤 요소가 들어한 로직은 어떻게 구현하는지에 대해 초점을 맞춰 고민 해보시면 좋을 것 같아요 :)

2020-11-13 06:46 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +    }
앗 삭제를 하셨군요 ㅎㅎ
타입스크립트에 사용자 정의 타입을 찾아보니 호환이 가능하다면 그 특정 타입으로 추정하여 형변환이 가능한 것 같네요
즉, 런타임 시점에서 정해지는 부분이라 해당 기능과 같이 구현이 되려면 계층 구조를 가지게 설계하여 다형성을 이용하시는 방법이 떠오르네요!

제네릭을 고민해주셨는데, 제네릭이 오버로딩이 되지 않는 이유는 jdk1.5 부터 하위 호환성을 위해 `Type Erasure` 라는
개념을 도입하는데요. 즉 두개 메서드를 오버로딩 하려할때 제네릭 타입은 컴파일시 지워지기 때문에
같은 타입으로 인식되어 오버로딩이 되시지 않을거에요!
아래는 바이트코드로 된 부분인데 메서드 선언을 확인해보시면 Integer는 지워져있는게 확인하실 수 있습니다 😄 
![image](https://user-images.githubusercontent.com/20432323/99037600-59307680-25c7-11eb-905c-925b3aab563a.png)


LottoNo는 항상 Integer 이도록 해주신 설계로 잘해주신 것 같아요 👍

2020-11-13 06:52 UTC, ohtaeg commented on src/main/java/lotto/domain/LottoNoPool.java
> +    }
Optional을 적절하게 잘 활용을 잘해주셨어요 👍 
하지만 내부 설계를 보면 LottoNo에서 그리고 해당메서드에서 validation을 해주고 있기 때문에
Null pointer는 발생하지 않을 것 같아요.

현재 구조 같은 경우라면 Optional을 제거해주셔도 좋을 것 같아요 :)

2020-11-13 06:55 UTC, ghojeong commented on src/main/java/lotto/domain/LottoNoPool.java
> +    }
그렇군요! validation 이 중복되더라도,
각각의 클래스가 독립성을 유지하려면 추가로 validation 을 하는 쪽으로 개발을 했는데,
중복되는 validation 로직을 모두 지울까요?

만약 지운다면, InputView 에서 값을 입력받을 때 하는 validation 만 남기고 모두 지우려고 합니다.

2020-11-13 07:00 UTC, ghojeong commented on src/main/java/lotto/domain/LottoNoPool.java
> +    }
아, 그리고 위의 코드의 `lottoNoPool.get(no)` 에서는 Pool 에 LottoNo 가 미리 만들어져 있지 않으면,
`new LottoNo(no);` 과는 관계 없이 null 값을 반환합니다.

애초에 lottoNoPool 자체가 LottoNo 의 생성자가 호출되는 횟수를 최소화 할려고 만든 거라서요.
lottoNoPool 에서 의도적으로 null 을 리턴하고 있는 이상 Optional 은 유지하겠습니다.

2020-11-13 07:10 UTC, ohtaeg commented on src/main/java/lotto/domain/LottoFactory.java
> +    }
제네릭과 오버로딩에 관련된 부분이네요!
해당 피드백에 제네릭 오버로딩이 안되는 이유를 남겨드렸는데 확인해주시면 감사하겠습니다 :)
추가로 와일드카드 사용시 주의해야할 예제도 설명드리겠습니다.

2020-11-13 07:22 UTC, ghojeong commented on src/main/java/lotto/domain/Lotto.java
> +    }
오우, 오버로딩이 안될때 에러 메시지로  `Erasure` 라는 모르는 문구가 나와서 헤맸는데,
이제야 왜 안되는지 이해가 가네요.
런타임과 컴파일 타임에서의 차이를 알지 못했는데, 인지하게 해주셔서 감사합니다.

2020-11-13 07:27 UTC, ohtaeg commented on src/main/java/lotto/domain/LottoNoPool.java
> +    }
LottoPool에서 poll에 없는 값을 찾는다면 예외를 발생하는 설계도 좋을 것 같네요 😄

2020-11-13 07:53 UTC, ohtaeg requested changes
미션 구현을 잘해주셨습니다 👍 
남겨주신 코멘트들을 통해 정말 많은 고민을 하고 계시는게 느껴지네요 👍 
그만큼 저 또한 최선을 다해 도와드리고 싶습니다 🙇 

몇 개의 피드백을 드렸는데, 다음 미션을 진행하기전에 같이한번 고민해보면 좋을 것 같은 부분이 존재하여 Request changes 하였습니다!
피드백을 확인해주시고 언제든지 궁금한 사항이나 함께 의논할 것이 있다면 DM 주세요!

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/asset/LottoConst.java
> +public class LottoConst {
상수 클래스에 대해 고민해볼 필요도 있는 것 같아요 :)
한곳에서 상수를 관리한다는 장점이 있지만 그만큼 여러 객체가 사용하는 정보가 모여있기에 관리차원에서 좋지 않다고 생각되네요.
각 정보들을 필요한 객체들에게 적절한 분배를 한다면 해당 객체의 책임에 맞는 정보들이 한 곳에 응집될 것 같은데
정완님께서는 어떻게 생각하시나요 :) ?

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/controller/LottosGenerator.java
> +    private GenerateStrategy strategy;
전략 패턴 👍

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/controller/strategy/InputStrategy.java
> +        String lottoStr = InputView.askLottoStr();
입력을 도메인에서 수행하지 않고 외부로 분리해볼 수 있을까요 :) ?

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/domain/Jackpot.java
> +    SIX(6, 2000000000);
다음과 같이 언더스코어를 이용하여 가독성을 높일 수 있습니다 :)
```suggestion
    SIX(6, 2_000_000_000);
```

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +    private String hashString(List<LottoNo> original) {
hashString란 메서드 네이밍은 조금 모호한것 같아요!
의미를 명확하게 파악할 수 있는 네이밍으로 작성해주실 수 있을까요 :) ?

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/domain/Money.java
> +    }
해당 피드백을 고려해보신다면 이 메서드는 제거될 수 있을 것 같아요 :)

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/domain/Money.java
> +    private int money;
final 키워드까지 추가해줌으로써 견고한 Value Object로 만드시면 어떨까요 ~ ?

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/domain/Lottos.java
> +        }
현재 depth가 2인 로직이네요 😭  depth를 1로 줄여볼 수 있을까요 ~ ?
힌트는 Lottos가 Jackpot의 정보를 알 필요는 없을 것 같아요.
해당 정보를 잘 알고있는 객체에게 물어보면 되지 않을까요 :) ?

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/domain/Result.java
> +    private HashMap<Jackpot, Integer> result;
Map 인터페이스가 아닌 HashMap으로 해주신 이유가 있을까요 ~ ?

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/exception/BadDividerException.java
> +public class BadDividerException extends RuntimeException {
커스텀 익셉션 👍

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/utils/validator/LottoNoValidator.java
> +}
해당 validator를 만들어 주신 이유가 있을까요 :) ?
LottoNo에서 수행한다면 어떤 장점이 있을까요 ~ ?

2020-11-13 07:53 UTC, ohtaeg commented on src/main/java/lotto/utils/validator/LottoValidator.java
> +    }
현재 여러 소스에서 validation 로직이 중복해서 사용되어지고 있습니다.
즉, 해당 클래스가 변경된다면 다른 클래스에게도 변경의 이유가 전파가 되어지는데요. 그만큼 강한 결합을 하고 있다는 뜻으로
해석할 수 있습니다.

해당 validator를 제거하는 방향으로 리팩토링해보면 좋을 것 같은데 정완님의 생각은 어떠하신지 궁금하네요 😄

2020-11-13 07:53 UTC, ghojeong commented on src/main/java/lotto/controller/strategy/RandomStrategy.java
> +public class RandomStrategy implements GenerateStrategy {
RandomStrategy를 사용하는 LottosGenerator 에 대해서는 할 수 있는 만큼 테스트 코드를 작성했으므로,
스스로가 느끼기에 (제 착각일 수도 있지만) 그렇다면 충분하다는 자신감이 생기네요.

2020-11-13 07:54 UTC, ohtaeg commented
다음 부터는 array 자료형들도 전부 List  자료형으로 통일할까 생각하는데,
array 없이 List 인터페이스만 사용하는 것에 대해 어떻게 생각하세요?

성능상 단점을 감수하고서라도, 함수 인자 및 객체 맴버에 대한 인터페이스를 통일해야겠다는 생각이 들었습니다.


// Answer
지극히 개인적인 의견으로써 해당 미션들을 진행하면서 array를 사용해도 되고, List를 사용해도 크게 상관없다고 생각하고 있습니다.
물론 데이터를 대용량으로 처리해야된다면 이야기는 달라지겠습니다만,
제가 가장 중요하게 생각되는 점은 `일관된 코드를 작성하는 것`이라고 생각합니다.

List의 장점은 Array보다 이점이 있는 것은 확실하지만, 비용면에서 생각해보면 List는 연속적인 메모리를 사용하지 않아 
검색 성능이 더 좋지 않습니다. 

두 개의 장단점만 확실하게 알고 넘어가신 다음 일관된 코드를 작성하는게 중요하다고 생각합니다 ㅎㅎ
그렇기에 자료형 변경에 대해서는 정완님께서 자유롭게 해주시면 될 것 같아요 :)

2020-11-13 07:55 UTC, ghojeong commented on src/main/java/lotto/domain/Jackpot.java
> +    SIX(6, 2000000000);
오우! 언더스코어를 해도 숫자로 인식되는 건가요?
이건 몰랐는데 대단하네요.
엄청 좋습니다.

2020-11-13 07:56 UTC, ghojeong commented on src/main/java/lotto/utils/validator/LottoNoValidator.java
> +}
LottoNo 의 validator 에 대한 로직틀 InputView 에서도 사용하게 하고 싶었는데,
LottoNo 에서 로직을 만드는게, 확실히 객체 응집도가 더 높아지는 것 같습니다.

2020-11-13 07:58 UTC, ghojeong commented on src/main/java/lotto/utils/validator/LottoValidator.java
> +    }
validator 로직들을 전부 domain 객체 안으로 넣을 수 있도록 하는게,
객체 응집도 면에서 확실히 좋은 것 같습니다.
validator 를 전부 제거할 수 있도록 리팩토링 해보겠습니다.

2020-11-13 07:59 UTC, ghojeong commented on src/main/java/lotto/domain/Result.java
> +    private HashMap<Jackpot, Integer> result;
아, 생각이 짧았네요. 가능하면 Map 인터페이스로 선언할 수 있도록 하겠습니다.
의도적으로 저렇게 선언한 것은 아닙니다.

2020-11-13 08:02 UTC, ohtaeg commented on src/main/java/lotto/domain/LottoFactory.java
> +    }
제네릭과 오버로딩에 관련된 부분이네요!
해당 피드백에 제네릭 오버로딩이 안되는 이유를 남겨드렸는데 확인해주시면 감사하겠습니다 :)
https://github.com/next-step/java-lotto/pull/874#discussion_r522690375

추가로 와일드카드 사용시 주의해야할 점을 예제로 설명드리겠습니다!

```java
public class OverloadingExample {
    public static void generateLotto(RandomGenerator generator) {
        System.out.println("random");
    }

    public static void generateLotto(AutoGenerator generator) {
        System.out.println("auto");
    }

    public static void generateLotto(Object generator) {
        System.out.println("Object");
    }

    public static void main(String[] args) {
        List<?> list = Arrays.asList(new RandomGenerator(), new AutoGenerator());
        list.forEach(generator -> generateLotto(generator));
    }
}

interface Generator {
}

class RandomGenerator implements Generator {
}

class AutoGenerator implements Generator {
}
```

해당 코드만 봤을때 출력 결과는 어떻게 나올지 예상한번 해보시면 좋을 것 같아요.
보통 random 과 auto가 출력되길 기대하지만 실제론 그렇게 출력이 되지 않습니다.
왜냐하면 오버로딩은 컴파일 시점에 메서드가 결정되는 정적 디스패처이기 때문입니다. 

그렇기에 와일드카드 사용시 범위를 제한하면서 사용해야되는 점을 인지해주시면 좋을 것 같아요!

2020-11-15 12:27 UTC, ghojeong commented
구조를 싹 바꾸었습니다다.

<img width="847" alt="스크린샷 2020-11-15 오후 9 25 34" src="https://user-images.githubusercontent.com/38595650/99184845-4796cc80-2789-11eb-8244-14e6437dcfd3.png">

2020-11-15 12:33 UTC, ghojeong commented on src/main/java/lotto/domain/Money.java
> +    }
divide 함수를 지워보라고 하셨는데,
아무리 머리를 싸매도 어떻게 지워야 할지를 몰라서 유지했습니다.

현재 divide 함수는 로또 구매 갯수와, 총 수익률을 계산하는데 사용하고 있습니다.
divide  함수를 지울 수 있는 아이디어를 공유해주시면 감사하겠습니다.

2020-11-15 12:33 UTC, ghojeong commented on src/main/java/lotto/controller/Main.java
> +        int numOfLottos = (int) purchaseMoney.divide(lottoPrice);
`LOTTO_PRICE = 1000` 를 어디에 위치 시킬지 몰라서, LottoPriceMoney 라는 싱글톤 객체를 새로 만들어버렸습니다.

Main 클래스가 상수를 갖는 것은 조금 이상한 것 같고,
Money 에 위치 시키는 것도, LottoPrice 와는 관련 없는 다른 money 도 있으므로 (예: Profit),
Money 클래스 안에 LOTTO_PRICE 상수를 위치시키고, `getNumOfLottos` 함수를 만드는 것도 이상하다고 판단했습니다.

혹시 의도하셨던 생각이나, 더 좋은 아이디어가 있으면 부디 공유해주세요.
결국 LOTTO_PRICE 와, rateOfReturn 을 구하는 로직을 어디에 배치해야 적절한가?
에 대한 대답을 스스로 만족스럽게 내리지 못해서 divide 함수가 남게 되었습니다.

2020-11-15 12:40 UTC, ghojeong commented
서로 연관된 로직과 상수를 같은 클래스에 위치하도록 하여,
객체의 응집도가 높아질 수 있도록 다시 구성해보았습니다.

기존의 레거시에서 구조를 바꾸려 하다보니, 무척 괴로웠네요.
그냥 다 지우고 처음부터 할까 라는 유혹이 무척 강했는데,
리팩토링을 공부하는 겸 해내보았습니다.

divide 메서드를 제거해야하는 피드백 빼고,
나머지 피드백은 전부 반영할 수 있었던 것 같습니다.

2020-11-15 12:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Money.java
> +    }
앗 같은 메서드가 2개 존재하여 validate 로직이 들어간 메서드를 리뷰드렸어야했는데
다른 메서드로 리뷰드렸었네요 🙏 
제가 원하는 방향으로 두 개의 divide 메서드를 하나로 잘 구현해주셨습니다 👍 

```
// 해당 메서드를 지워보라는 리뷰였습니다!
public double divide(int divider) {
    DividerValidator.valiateDivider(dividor);
    return money / divider;
}

public double divide(int divider) {
    return divide(divider.money);
}
```

2020-11-15 13:46 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨습니다. 👍 
코드를 통해 많은 고민을 하신게 느껴지네요!! 👍 
몇 개의 코멘트를 드렸는데 다음 미션을 진행하시면서 함께 반영해주시면 감사하겠습니다!
다음 미션도 기대하겠습니다 😄

2020-11-15 13:46 UTC, ohtaeg commented on src/main/java/lotto/domain/Money.java
> +    }
앗 해당 리뷰는 같은 메서드가 2개 존재하여 충분히 하나로 합칠 수 있다고 생각되었습니다.
validate 로직이 들어간 메서드로 리뷰드렸어야했는데 다른 메서드로 리뷰드렸었네요 🙏
혼동을 드려 죄송합니다 🙇 
제가 원하는 방향으로 두 개의 divide 메서드를 하나로 잘 구현해주셨습니다 👍 

```
// 해당 메서드를 지워보라는 리뷰였습니다!
public double divide(int divider) {
    DividerValidator.valiateDivider(dividor);
    return money / divider;
}

public double divide(int divider) {
    return divide(divider.money);
}
```

2020-11-15 13:46 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +        }
현재 depth가 2로 되어있네요!
프로그래밍 요구사항에 맞게 depth 1로 줄여주시면 좋을 것 같아요 :)

2020-11-15 13:46 UTC, ohtaeg commented on src/main/java/lotto/domain/Result.java
> +    }
두 메서드를 하나로 줄여볼 수 있을 것 같아요 :)
```suggestion
    private void increaseNumOfLotto(int numOfCorrected) {
        result.put(numOfCorrected, result.getOrDefault(numOfCorrected, 0) + 1);
    }
```

2020-11-15 13:46 UTC, ohtaeg commented on src/main/java/lotto/view/ResultMessage.java
> +                .divide(purchaseMoney);
수익률은 출력메시지 객체에서 구하는건 어색한 것 같아요!
다음 미션을 진행하시면서 어디가 적절한지 고민해보시면 좋을 것 같습니다! ㅎㅎ

2020-11-15 13:46 UTC, merged

2020-11-15 14:54 UTC, ghojeong commented on src/main/java/lotto/controller/Main.java
> +public class Main {
> 현재 게임이 원활하게 진행이 되질 않네요

헙!! Profit 이 0일 때 발생하는 에러네요 ㅠ.ㅠ 수정하겠습니다.