Feature : 문자열 덧셈 계산기 구현
next-step/java-lotto pull request #880
Opened 2020-11-13 15:33 UTC by limmmee-bonjour

리뷰어님 반갑습니다 :)!
이번 과제도 열심히 달려보겠습니다! 잘부탁드립니다!

2020-11-14 03:04 UTC, sah3122 requested changes
안녕하세요. 동아님 😄 
로또 미션 리뷰를 맡게 된 이동철 입니다. 
간단한 피드백을 남겨두었는데 반영 부탁드려요 !

2020-11-14 03:04 UTC, sah3122 commented on src/test/java/Calculator/StringAddCalculatorTest.java
> +    @Test
@NullAndEmptySource를 활용해보세요.

2020-11-14 03:04 UTC, sah3122 commented on src/test/java/Calculator/StringAddCalculatorTest.java
> +    public void splitAndSum_숫자하나() throws Exception {
@PrameterizedTest를 활용한다면 중복된 테스트 코드를 줄일 수 있지 않을까요 ?

2020-11-14 03:04 UTC, sah3122 commented on src/test/java/Calculator/StringAddCalculatorTest.java
> +    public void splitAndSum_쉼표구분자() throws Exception {
Junit5 부터는 @DisplayName 을 활용하여 테스트의 의도를 분명히 나타낼수 있어요. 
메소드에 테스트를 의도를 나타내는것 보다 가독성이 좋으니 도전해보세요.
테스트 실행시 이름이 표시 되지 않는 경우 Build Tool -> Gradle -> Build and Run, Run testing 옵션을 Intellij 로 변경해보세요 !

2020-11-15 04:25 UTC, limmmee-bonjour commented on src/test/java/Calculator/StringAddCalculatorTest.java
> +    @Test
이번 과제를 읽어보니 아래 테스트케이스가 이미 존재하고 (소스코드)
그 테스트 케이스를 모두 통과시키는게 과제의 목표라고 생각했는데요.
(그래서 따로 테스트 케이스는 수정하지 않았습니다.)
제가 잘못 이해한걸까요? 
(테스트 케이스에 대해서 코드리뷰를 주셔서요)
https://edu.nextstep.camp/s/MNii0Puk/ls/BqEG7gXQ

2020-11-15 04:26 UTC, limmmee-bonjour commented on src/main/java/Calculator/StringAddCalculator.java
> +    public static int splitAndSum(String input) {
이 부분도 동일하게 테스트 케이스에서 호출하는 메소드명을 그대로 가져왔어요.
사실 spliteAndSum 은 splite 과 sum 라는 각각 분리된 메소드를 가지고 있는데요.
어떤걸 분리해보라는 말씀이신지 잘 이해가 되질 않습니다.
(약간 splitAndSum 이 메소드는 main() 함수라고 생각했어요 - 테스트케이스에서 테스트할)

2020-11-15 04:32 UTC, limmmee-bonjour commented
안녕하세요 동철님.
제가 댓글드린 부분을 제외하고는 리뷰 반영하였는데요. 확인 부탁드립니다!

2020-11-15 06:47 UTC, sah3122 reviewed
👍

2020-11-15 06:47 UTC, sah3122 commented on src/main/java/Calculator/StringAddCalculator.java
> +    public static int splitAndSum(String input) {
`splitAndSum 이 메소드는 main() 함수`라고 정의 해주신 부분이면 분리 하지 않아도 될것 같아요 😄 
현재 구조는 split 과 sum 메소드가 private으로 되어 있어 외부 클래스에서 단일 기능을 호출하지 못하는 구조라서 코멘트를 남겨두었습니다. 
만약 splitAndSum이 main의 역할을 하지 않는다면 각각 메소드가 public으로 오픈되어 있어야 외부에서 호출할수 있겠네요 👍

2020-11-15 06:47 UTC, sah3122 commented on src/test/java/Calculator/StringAddCalculatorTest.java
> +    @Test
미션에서 주어진 예제 테스트 코드는 힌트라고 생각해주시면 될것 같아요.
주어진대로 작성하지 않아도 될것 같습니다. 😄

2020-11-15 11:17 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
본격적인 로또 미션을 진행해주세요 !

2020-11-15 11:17 UTC, merged