Step2 로또(자동)
next-step/java-lotto pull request #912
Opened 2020-11-18 07:38 UTC by sehan

### feature
* 로또금액을 입력하면 금액에 해당하는 만큼 로또를 발급한다
* 1~45 숫자 6자리로 구성된 로또를 발급한다
* 당첨번호와 번호가 N개 일치하는 로또 찾기
* 당첨결과를 제공한다 (당첨여부, 수익율)
* 구입가격, 당첨번호 입력 추가 및 view 추가

### refactoring
* step1 피드백반영. validation 로직 분리 
* domain , view 패키지추가

2020-11-19 11:15 UTC, vagabond95 requested changes
요구사항에 맞게 빠르게 구현을 잘해주셨네요 👍 

구현 내용에 대하여 몇가지 코멘트를 남겼는데요, 확인 후 다시 리뷰요청 부탁드립니다~!
리뷰내용 중 궁금하거나 논의하고 싶은 점 있으시면 편하게 DM 주세요 :)

2020-11-19 11:15 UTC, vagabond95 commented on src/test/java/lotto/domain/LottoNumberGeneratorTest.java
> +        LottoNumber num1 = lottoNumberGenerator.generate();
아래 테스트 케이스를 통과했다고해서 다른 번호가 발급된다고 항상 보장될 수 있을까요~?
랜덤한 결과를 테스트하는 것에 대해 고민해보시면 좋을 것 같습니다!

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
현재는 interface 로 선언했을 때의 이점이 크지 않아보이는데요, 
interface + 정적 메소드로 구성하신 이유가 있을까요~?

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +                lottoNumberBalls = new ArrayList<>();
lottoNumberBalls 는 항상 같은 값이므로 캐싱해두는 전략도 좋을 것 같습니다!

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoNumberParser.java
> +            throw new RuntimeException("로또 숫자는 1~45 숫자만 허용합니다.");
RuntimeException 보다는 좀 더 낮은 추상화 수준의 예외를 던져보는 것은 어떨까요~? 

[추상화 수준에 적절한 커스텀 예외](https://jaehun2841.github.io/2019/03/10/effective-java-item73/)

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/view/InputView.java
> +        return getNumberFromStdin("구입금액을 입력해 주세요.");
문자열을 하드 코딩하기보다 상수로 빼서 관리해보는 것은 어떨까요?

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/LottoSimulation.java
> +        InputView inputView = new InputView();
InputView, OutputView 는 멤버변수를 가지고 있지 않으므로 별도 객체 생성없이 static 메소드만 제공해도 괜찮지 않을까요?

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/Lotto.java
> +    public void printNumber(PrintWriter writer) {
도메인 영역의 클래스에서는 view 와 관련된 로직이 빠져야하지 않을까요~?

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public void print(PrintWriter writer) {
이 부분도 위 코멘트와 동일한 관점에서 고려해주세요~!

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoNumber.java
> +        return (int) numbers.stream().filter(it -> numberMatcher.match(it)).count();
int 로 캐스팅을 해주신 이유가 있을까요~?

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/WinningNumber.java
> +    public WinningNumber(String expression) {
numbers 와 expression 는 아예 성격이 다른 파라미터로 보이는데요,
expression 을 받아 파싱해주는 로직이  WinningNumber 클래스의 역할에 적합할까요?

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/WinningNumber.java
> +            this.numbers = lottoNumberParser.parse(expression);
expression 을 받아 파싱해주는 로직이  WinningNumber 클래스의 역할에 적합할까요?

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/PrizeWinningResult.java
> +        return (double) total / this.paidMoney;
paidMoney 에 대한 validation 이 없으므로 0 으로 나눌 케이스에 대해서 고려가 되어야 할 거 같아요.

2020-11-19 11:15 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoMachine.java
> +    public List<Lotto> issue(int purchaseAmount) {
당첨 금액과 개수를 관리하는 클래스로 분리해볼 수 있을 것 같습니다!

2020-11-20 03:51 UTC, sehan commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
로또번호 발급을 담당하는 기능성이 명확하다고 생각해서 interface 로 명세를 했습니다. 
현재 코드상으로는 interface 사용여부가 큰 장점으로 작용할 부분은 없습니다. 
새로운 로또 번호 발급로직을 적용해 볼 수도 있고 많은수의 로또번호 발급시 성능에 문제가 있다면 개선된 로또번호 발급기로 교체해야 한다면 타 코드변경 영향도를 감소시켜 주는 효과를 기대해 볼 수 있지 않을까요? ^^

static 매소드를 사용해서 기본구현체를 생성하는 부분은 개인적으로 기본구현체를 생성할때 interface 의 static 매소드로 제공하면 사용하는 측에서 쉽게 기본구현체의 인스턴스를 생성하기가 용이하다고 생각해서 사용하고 있습니다.

2020-11-20 04:46 UTC, sehan commented on src/main/java/lotto/domain/LottoNumberParser.java
> +            throw new RuntimeException("로또 숫자는 1~45 숫자만 허용합니다.");
네, 아주 좋습니다.

2020-11-20 04:53 UTC, sehan commented on src/main/java/lotto/domain/LottoNumber.java
> +        return (int) numbers.stream().filter(it -> numberMatcher.match(it)).count();
.count() 의 return 타입이 long 이라 의미없이 타입을 캐스팅 해버렸네요 : )
getMatchedNumberCount 의 return 타입을 long 으로 변경해야 겠네요

2020-11-20 05:09 UTC, sehan commented on src/main/java/lotto/domain/WinningNumber.java
> +    public WinningNumber(String expression) {
parsing 역할을 Parser 에게 위임이 되어 있어서 expression ( 여기서는 numberString 이 적합하겠네요 ) 을 인자로 받는 WinningNumber 생성자는 괜찮다고 생각했습니다.

2020-11-20 05:25 UTC, sehan commented on src/main/java/lotto/domain/LottoMachine.java
> +    public List<Lotto> issue(int purchaseAmount) {
이 부분은 step3 에서 언급된 enum 으로 역할을 분리하도록 하겠습니다.

2020-11-20 05:29 UTC, sehan commented on src/test/java/lotto/domain/LottoNumberGeneratorTest.java
> +        LottoNumber num1 = lottoNumberGenerator.generate();
네, 맞습니다. 보장되지 않습니다. 테스트를 만들때 다른값들이 잘 나오는지 확인하려는 의도로 만들었는데 다시 보니 목적을 충족하지 못하네요.

이 테스트는 목적을 달리해서 작성을 다시 하도록 하겠습니다.

2020-11-21 03:06 UTC, vagabond95 commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
자바에서 interface 에 static 멤버들을 추가할 수 있도록 허용된 내용을 알았을 때 어떻게 활용할 수 있을지 고민했었는데 작성해주시는 코드를 보며 저도 힌트를 얻어가고 싶네요 :)

2020-11-21 03:07 UTC, vagabond95 approved these changes
각 리뷰내용의 의도에 맞게 잘 반영해주셨네요 :)

2단계는 머지하도록 하겠습니다~!

2020-11-21 03:08 UTC, merged