[oen142][Step3] 로또 2등
next-step/java-lotto pull request #918
Opened 2020-11-18 15:12 UTC by oen142

피드백 주신 정적팩토리메서드를 생성자에서는 받아서 처리하게끔 했습니다.

원시값을 가져야하는 클래스가많이 보이기도하고, 테스트코드가 더욱 용이하게 클래스를 더욱 분리를 했습니다

2020-11-19 12:28 UTC, misudev requested changes
안녕하세요 종완님~ 
3단계 요구사항 구현 잘 해주셨네요 👍 
저번 미션 피드백 반영까지 좋습니다 🔥
몇 가지 코멘트 남겨 놨는데요, 확인하시고 다시 리뷰 요청 부탁드려요 😀
화이팅 입니다~ 😁

2020-11-19 12:28 UTC, misudev commented on src/main/java/step3/domain/LottoMatcher.java
> +    private static EnumMap<LottoRank, Integer> result = new EnumMap<LottoRank, Integer>(LottoRank.class);
static으로 수정해주셨는데요,
제가 그때 드린 피드백의 의도는  ofMatch()에서 
result필드에 들어갈 Map을 만들어주고, 생성자는 이를 받아 초기화 하는 방향을 말씀 드린거였어요 😢
지금 구현방향에 대한 코멘트 아래 적어둘께요~!

2020-11-19 12:28 UTC, misudev commented on src/main/java/step3/domain/LottoMatcher.java
> +        return new LottoMatcher();
static 필드만을 가지는 LottoMatcher 객체를 매번 초기화, 생성해주는 방향이 맞을까요? 🤔

2020-11-19 12:28 UTC, misudev commented on src/main/java/step3/domain/LottoFactory.java
> +                .collect(Collectors.toList()));
IntStream을 사용하면 어떨까요??

2020-11-19 12:39 UTC, oen142 commented on src/test/java/step3/GameMoneyTest.java
> +package step3;
적용했습니다

2020-11-19 12:46 UTC, oen142 commented on src/test/java/step3/LottoMatcherTest.java
> +        assertThat(LottoMatcher.ofMatch(lottos, lastWeekLotto).getGamePrize()).isEqualTo(gameMoney);
적용해보았습니다.

2020-11-19 13:01 UTC, oen142 commented on src/test/java/step3/LottoMatcherTest.java
> +    void createLottosToString(Lottos lottos, LastWeekLotto lastWeekLotto, GameMoney gameMoney) {
수정했습니다~!

2020-11-19 13:08 UTC, oen142 commented on src/main/java/step3/domain/LottoFactory.java
> +                .collect(Collectors.toList()));
IntStream을 사용해보진 않았는데 적용해보겠습니다.

2020-11-19 13:10 UTC, oen142 commented on src/main/java/step3/domain/LottoRank.java
> +        if (findSecond(countOfMatch, matchBonusNumber)) return THIRD;
isThirdPrize로 바꾸면 좋을까요 ?

2020-11-19 22:54 UTC, misudev approved these changes
종완님~ 피드백 반영 잘 해주셨네요 👍
이번 스텝은 이만 머지하겠습니다~
마지막 단계도 화이팅입니다 🔥🔥

2020-11-19 22:54 UTC, misudev commented on src/main/java/step3/domain/LottoRank.java
> +    private static boolean isThirdPrize(int countOfMatch, boolean matchBonusNumber) {
👍👍

2020-11-19 22:54 UTC, misudev commented on src/main/java/step3/exception/LottoNumberRangeException.java
> +        super("로또 번호들은 제한된 범위에서 넘을수 없습니다.");
이부분도 다른 exception 처럼 상수로 분리해주세요~ 😀

2020-11-19 22:54 UTC, misudev commented on src/test/java/step3/domain/LottoMatcherTest.java
> +    void sumLottoMatchPrize(Lottos lottos, LastWeekLotto lastWeekLotto, GameMoney gameMoney) {
읽기 좋아졌네요 👍

2020-11-19 22:54 UTC, merged

2020-11-20 02:04 UTC, oen142 commented on src/main/java/step3/exception/LottoNumberRangeException.java
> +        super("로또 번호들은 제한된 범위에서 넘을수 없습니다.");
오잉 이게 안되있었네요 분리하고 다음 미션에서 올리겠습니다:D