Step3 로또 2등
next-step/java-lotto pull request #945
Opened 2020-11-21 12:40 UTC by sehan

rebase 과정에 문제가 있어서 step 별 개별 commit 이 그대로 포함되어 버렸습니다. ^^;;; 
commit 은 많지만 새로추가된 내용은 아래 2개 입니다.

### feature
* 보너스 볼 추가, 5개 + 보너스볼 일치하면 2등 당첨으로 처리한다

### refactoring
* 당첨순위를 Enum 으로 작성하고 상태와 로직을 위임 ( 당첨순위조건, 당첨금액 )

2020-11-22 06:01 UTC, vagabond95 requested changes
리펙토링 해주신 이후 각 클래스의 역할이 명확해지고 좀 더 변경에 유연한 구조가 된 것 같습니다 👍 

구현하신 내용에 대하여 간략한 코멘트 남겼는데요, 검토 및 수정 후 다시 리뷰요청 부탁드릴게요~! :)

2020-11-22 06:01 UTC, vagabond95 commented on src/main/java/lotto/domain/WinningNumber.java
> +    private final int bonusNumber;
개별 로또번호 (1 ~ 45 사이) 를 의미하는 클래스로 한번 더 분리해볼수도 있을 것 같습니다!

2020-11-22 13:53 UTC, sehan commented on src/main/java/lotto/domain/LottoRanking.java
> +    public static LottoRanking valueOf(Lotto lotto, WinningNumber winningNumber){
네, 저도 그부분이 고민되었습니다. 
1. valueOf 를 사용하기위해 matchedCount, matchedBonus 를 계산 후 넘겨주는 방식
2. 현재 코드와 같이 Lotto 와 WinningNumber 만 넘겨주면 valueOf 가 두 객체를 이용해서 역할을 수행하는 방식

의존성을 제거할 것인가... 맥락의 편의에 따라 matchedCount, matchedBonus 를 계산해서 넘겨주어야 하는가?

선택의 기로에서 matchedCount 와 matchedBonus 를 사용하는곳은 순위를 판별해주는 valueOf 뿐이지 않을까? 해서 matchedCount, matchBonus 계산을 valueOf 에 숨기고 의존을 가져가는 코드를 작성했습니다.

module 의 경계가 분명하게 나누어져 있다면 서로의 의존을 제거하는 선택을 했을거 같은데 여기서 저의 판단은 의존을 가져가는 쪽으로 전개가 되었네요.

test 입장에서 보면 의존으로 인해 lotto, winningnumber 가 따라다니는 부담이 있지만 객체생성 부담이 크지 않다고 판단했습니다. 하지만 의존성을 제거한거에는 미치지는 못하는게 사실입니다.

2020-11-22 13:55 UTC, sehan commented on src/main/java/lotto/domain/PrizeWinningResult.java
> +        long total = ((getRankedLottoCount(LottoRanking.FIRST) * LottoRanking.FIRST.getWinningMoney())
개선해보겠습니다. 코드를 작성하면서 아 괴롭다 라고 생각이 들었는데 못본척 마음에 넣어두었네요 ㅎㅎㅎ

2020-11-22 13:55 UTC, sehan commented on src/main/java/lotto/domain/WinningNumber.java
> +    private final int bonusNumber;
네, 좋은생각입니다. 개선해보겠습니다.

2020-11-23 02:10 UTC, sehan commented on src/main/java/lotto/domain/LottoRanking.java
> +    public static LottoRanking valueOf(Lotto lotto, WinningNumber winningNumber){
1번 방식으로 리팩토링하고 test 를 작성 해보고나니 괜한 고민을 했나 생각이 드네요 ^^
valueOf 에 비지니스 책임을 너무 떠안겨 놓았다고 생각되네요
관련 비지니스를 Lottos 로 올려주니 더 자연스럽고 LottoRanking.valueOf 는 enum 에서 value 만 찾아주면 되니 책임에 더 충실해 지네요. 

LottoRanking 에게 Lotto 와 WinningNumber 를 줄테니 Ranking 좀 알려줄래? 라고 메세지를 보내려고 했는데
LottoRanking 에게 matchedCount 와 matchedBounus 면 Ranking 이 뭐야? 라고 메세지를 보내고 보니 더 간결해 졌네요

2020-11-23 05:47 UTC, vagabond95 approved these changes
스스로 깨달은 점을 남겨주시는 것 너무 좋습니다 👍  제가 초기에 의도했던 부분보다 더 많은 깨달음을 얻고 가시는 것 같아 좋습니다 ㅎㅎ

3단계는 머지하도록 하겠습니다!

2020-11-23 05:47 UTC, merged