Step4 구현 완료
next-step/java-lotto pull request #976
Opened 2020-11-24 17:06 UTC by dudu0166

잘 부탁드립니다!

2020-11-25 08:50 UTC, slamdunk7575 requested changes
전반적으로 구조가 잘 잡혀있어 어렵지 않게 로또(수동)구하는 로직을 추가하셨네요 👍

몇가지 수정사항 제안 드렸는데 한번 검토해주시면 좋겠네요.

- SortedSet<LottoNumber> 이부분을 Wrapping한 일급 컬렉션(예:LottoTicket)을 만들어 보면 어떨까요?

- InputView 내부에서 두가지 일을 하고 있습니다.
  객체를 생성하는 역할을 다른 클래스에 위임해보는건 어떨까요?

자세한 내용은 코멘트로 남겨두었습니다.

궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 주세요. 함께 고민해보아요.🔥_🔥
건강조심하세요😷  끝까지 화이팅 입니다!

2020-11-25 08:50 UTC, slamdunk7575 commented on src/main/java/lotto/controller/LottoController.java
> +        List<SortedSet<LottoNumber>> lottoesNumbers = lottoes.getLottoes();
피드백 반영 좋습니다 👍 💯 

`SortedSet<LottoNumber>` 이부분을 Wrapping한 일급 컬렉션(예:LottoTicket)을 만들어 보면 어떨까요?

[일급 컬렉션을 사용하는 이유](https://woowacourse.github.io/javable/2020-05-08/First-Class-Collection)
[일급 컬렉션 (First Class Collection)의 소개와 써야할 이유](https://jojoldu.tistory.com/412)

2020-11-25 08:50 UTC, slamdunk7575 commented on src/main/java/lotto/model/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
LottoNumber 구현 잘해주셨네요 👍 💯

2020-11-25 08:50 UTC, slamdunk7575 commented on src/main/java/lotto/model/LottoNumber.java
> +        return inputNumber <= 0 || 45 < inputNumber;
매직넘버는 상수화 해보는게 어떨까요? 😄

2020-11-25 08:50 UTC, slamdunk7575 commented on src/main/java/lotto/model/LottoNumber.java
> +    }
equals() 와 hashCode() 재정의 👍

2020-11-25 08:50 UTC, slamdunk7575 commented on src/test/java/lotto/LottoNumberTest.java
> +public class LottoNumberTest {
테스트 작성 좋네요 👍

2020-11-25 08:50 UTC, slamdunk7575 commented on src/main/java/lotto/view/InputView.java
> +    }
이름을 지으실때 호진님도 느끼셨겠지만, 현재 InputView 내부에서 두가지 일을 하고 있습니다.

- 수동 로또 번호 입력
- `CandidateLotto` 객체를 생성해서 반환

`CandidateLotto` 객체를 생성하는 역할을 다른 클래스에 위임하여 처리해보는게 어떨까요? 😄

2020-11-25 08:50 UTC, slamdunk7575 commented on src/main/java/lotto/controller/LottoController.java
>          ResultView.printLottoes(lottoes.getLottoes());
나아가 buyLottoes() 내부에서 로또를 생성하는 부분을 
예:LottoShop 클래스를 만들어 위임해보면 좋을것 같네요 😄

2020-11-25 08:50 UTC, slamdunk7575 commented on src/main/java/lotto/model/LottoCount.java
> +    private int manualCount;
원시값 포장 좋습니다 👍 💯

2020-11-25 08:50 UTC, slamdunk7575 commented on src/main/java/lotto/model/LottoNumber.java
> +    }
나아가 아래 사항을 한번 확인해주세요. 😄 

`* LottoNumber의 생성자를 사용하지 않고도, LottoNumber의 객체를 만들 수 있는 방법을 설계하고 구현한다.`

[정적 팩토리 메서드는 왜 사용할까?](https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)

2020-11-25 09:48 UTC, slamdunk7575 commented
- 수익률 계산부분 확인 부탁드려요 😄 

![스크린샷 2020-11-25 오후 6 46 41](https://user-images.githubusercontent.com/15867808/100210807-c096e080-2f4e-11eb-9a62-0b26c4853447.png)

2020-11-25 17:15 UTC, dudu0166 commented on src/main/java/lotto/controller/LottoController.java
> +        List<SortedSet<LottoNumber>> lottoesNumbers = lottoes.getLottoes();
refactor: SortedSet<LottoNumber> 일급 컬렉션으로 Wrapping으로 커밋을 했는데 구조를 재수정하면서 기존에 있던 클래스를 사용해서 말씀해주신 부분 수정해보았습니다! 

int -> LottoNumber
SortedSet<LottoNumber> -> Lotto(CandidateLotto, WinningLotto) *기존에 이미 SortedSet<LottoNumber>가 Lotto로 Wrapping된 상태에서 또 LottoTicket을 만들면 이상한거 같아 구조를 변경했습니다!
List<CandidateLotto> -> Lottoes

2020-11-25 17:16 UTC, dudu0166 commented
> * 수익률 계산 부분 확인 부탁드려요 😄
> 
> ![스크린샷 2020-11-25 오후 6 46 41](https://user-images.githubusercontent.com/15867808/100210807-c096e080-2f4e-11eb-9a62-0b26c4853447.png)

로또 값을 넣어서 Amount 상태를 변경해야했는데 로또 개수를 넣었었습니다... 그래서 이런 실수를 방지하고자 LottoCount를 LottoPrice로 변경하고 값을 리턴하도록 했습니다!

2020-11-25 17:16 UTC, dudu0166 commented on src/main/java/lotto/model/LottoNumber.java
> +    }
좋은 참고 링크 감사합니다!

2020-11-25 17:17 UTC, dudu0166 commented on src/main/java/lotto/controller/LottoController.java
>          ResultView.printLottoes(lottoes.getLottoes());
이 부분은 위임을하면 다른 클래스를 또 만들어야하는데 너도 오버 코딩 같아서 구조를 변경해보았습니다!

2020-11-26 17:24 UTC, slamdunk7575 requested changes
피드백 반영하시느라 고생하셨어요👍
처음보다 구조가 많이 깔끔해진거 같아요.

몇가지 수정사항 제안 드렸는데 한번 검토해주시면 좋겠네요.

궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 주세요. 함께 고민해보아요.🔥_🔥
미션 마무리까지 얼마 남지 않으셨네요~ 끝까지 화이팅 입니다! 건강조심하세요😷

2020-11-28 08:11 UTC, dudu0166 commented on src/main/java/lotto/model/lotto/Lottoes.java
> +    }
두 역할을 분리하는 이유를 모르겠습니다!(객체는 하나의 역할만을 담당해야한다에는 동의합니다! 그런데 역할이 연관이 있다면 진리일수는 없다고 생각합니다!) Lottoes가 int 값과 List를 받아 List<Candidate>(로또 생성 결과)를 가지고 있고 이것에 대한 상태 및 결과(추첨&수익률 계산)를 반환하는 것 캡슐화 측면에서 더 좋다고 생각합니다... 두 역할을 분리하기 위해서 다른 Class를 만들고 Lottoes(생성된 로또들)를 받거나 넘겨주게 되면 구조가 더 복잡해지고 두 Class 간 결합도도 올라갈꺼 같습니다... 로또를 생성하는 Class를 만들고 추천 및 수익률을 계산하는 Class를 따로 만들어야하는 이유가 있을까요...? 객체는 하나의 역할만을 담당해야한다는 면에서 분리를 해야할까요?

2020-11-28 09:03 UTC, dudu0166 commented on src/main/java/lotto/model/LottoPrice.java
> +    }
UI로직과 비지니스 로직은 분리시키는게 좋다고 생각합니다! 하지만 모든 객체가 가지고 있는 toString을 오버라이드 한것이라서 toString이 완전한 UI 로직이라고 생각이 들지 않습니다....  UI 클래스의 출력 형태가 변경되고 String을 그대로 사용한다면 toString만 변경하면 되는 것이고 String 이 아닌 다른 형태로 값을 받아야한다면 도메인 객체를 변경하는 것이 아닌 말씀해주신 DTO를 만들어 변경하면 되지 않을까요...? 현재로써 이것을 분리하기 위해서 구조를 바꾸거나 과도한 DTO를 만드는 것은 오버 코딩이라고 생각합니다.... 또한 링크해주신 문서에서 지적한 DTO를 사용해야하는 이유와 현재는 거리가 멀구요.... 그래도 수정을 해야한다면 수정하겠습니다!

2020-11-29 11:45 UTC, slamdunk7575 commented on src/main/java/lotto/controller/LottoController.java
> +        amount.pay(lottoPrice.manualPrice());
피드백 반영 잘해주셨네요 👍 
`buyLottoes()`가 훨씬 깔끔해진거 같아요!

2020-11-29 11:45 UTC, slamdunk7575 commented on src/test/java/lotto/WinningLottoTest.java
>      }
피드백 반영 👍 💯

2020-11-29 11:45 UTC, slamdunk7575 commented on src/main/java/lotto/model/LottoPrice.java
> +    }
현재의 상태에서 구현하신 `toString()`를 제거하기 위해 구조를 바꾸는 것이 오버코딩으로 생각하시는점 충분히 이해합니다.
저도 이부분에 대해 피드백을 드릴때 고민을 했기 때문입니다.

제가 피드백을 드렸던 이유는 지금은 작은 프로젝트이지만 애플리케이션이 확장되고 요구사항이 바뀌어 
UI 출력부분을 변경한다고 했을 때 비지니스쪽 도메인을 신경써야 한다는 것은 분명 둘 사이에 결합도가 있다고 생각했기 때문입니다.

이 점을 생각해주시고 나중에 비슷한 상황에 부딪혔을때 호진님이 판단하셔서 더 좋은 결정을 하시길 바라겠습니다.
그리고 피드백과 드렸던 링크는 DTO 사용에 관한 내용이고 현재 상황과는 연관이 별로 없었네요. 혼란을 드려 죄송합니다. 🙇

2020-11-29 11:54 UTC, slamdunk7575 commented on src/main/java/lotto/model/lotto/Lottoes.java
> +    }
호진님 말씀대로 지금 상황에서 두 역할을 Lottoes 내에 같이 두는 것이 좋은 선택일 수 있습니다 👍 

하지만 만약 생성된 로또번호를 이용하는 또 다른 요구사항이 추가된다고 했을때 Lottoes에 계속 로직을 추가할 것인가? 에 대해 생각해봐야 할꺼 같습니다.

Lottoes 에서는 (수동/자동) 로또 번호를 생성하는 상태와 역할만 수행하고

`예: LottoResult`라는 클래스에게 로또의 추첨 결과와 수익률의 상태와 역할을 분리하는게 좋을 것 같아 피드백을 드렸던 것입니다.

정답은 없다고 생각합니다. 선택은 호진님이 하시면 됩니다.

다만 하지만 한가지 말씀드리고 싶은 점은 호진님도 이 과정을 신청하신 이유가 기존과는 다른 인사이트를 얻기 위함이라고 생각됩니다. 
다른 방법을 해보지 않는다면 그 방법이 좋고 나쁜지를 판가름 할 수 없다고 생각하기 때문에 이번 과정에서 해보시면 도움이 되실거 같아 말씀드린 것 이였습니다. 🙇

2020-11-29 12:10 UTC, slamdunk7575 approved these changes
마지막 미션 잘 구현해주셨네요.
질문에 대한 코멘트 남겨드렸는데 다음 미션으로 가시기 전에 확인해보시면 좋을것 같아요.

미션을 진행하면서 피드백도 잘 반영해주시고 많은 고민을 하셨기에
좋은 결과가 나온거 같습니다. 

저 또한 리뷰를 하면서 많이 배울 수 있었습니다.
제가 드렸던 피드백들이 앞으로 호진님께 조금이라도 도움이 되었으면 좋겠네요!

미션이 종료 되더라도 다른 사람 코드와 비교해보면서 장/단점을 비교해본다면
또 새로운 인사이트를 얻으실 수 있을꺼에요. 🔥_🔥

저와의 미션은 종료되었지만, 궁금한점이나 어려운점 있으면 언제든 편하게 DM 주세요!
그동안 고생 많으셨습니다. 감사합니다.

남은 미션도 꾸준히 진행하시고 끝까지 완주하시길 응원하겠습니다! 🎉

2020-11-29 12:11 UTC, merged