Step2 - 로또(자동)
next-step/java-lotto pull request #986
Opened 2020-11-25 17:34 UTC by jaehee0145

안녕하세요 리뷰어님 😄 
아직 출력부분을 완성하지 못했는데 
리뷰 남겨주시면 수정하면서 같이 완성하겠습니다!
감사합니다 🍎

2020-11-26 09:54 UTC, yongdae requested changes
안녕하세요. 재희님 🙇

로또 미션 2단계를 잘 진행해주셨네요~
특히 클래스를 최대한 나누기 위해서 노력하신 흔적이 곳곳에서 엿보이네요. 👍

리뷰 요청 하실 때 전달해주신 내용처럼 아직 당첨 통계 출력 부분이 미완성이라
이 부분을 제외하고 의견 남겨놓았습니다. 😄 

피드백 확인하시고 다시 리뷰 요청 부탁드려요~ 🔥🔥🔥

2020-11-26 09:54 UTC, yongdae commented on README.md
> +9. 로또목록으로 수익금을 계산한다. ProfitCalculator
구현해야 하는 기능을 잘 작성해주셨네요. 👍

2020-11-26 09:54 UTC, yongdae commented on src/main/java/lotto/domain/Calculator.java
> +        this.lottoTicketPrice = PRICE;
생성자를 통해 입력하시는 이유가 궁금해요. 🤔

15라인에서 PRICE를 직접 사용하는 것도 하나의 방법일 것 같은데
생성자를 이용해서 구현하신 이유가 있으신가요?

2020-11-26 09:54 UTC, yongdae commented on src/main/java/lotto/domain/Calculator.java
> +    final static int PRICE = 1000;
PRICE 변수명에대해서 한번더 고려해보시는 것은 어떨까요?

TICKET_PRICE 처럼 직접적인 의미를 주는것은 어떠세요?
Calculator(계산기)의 PRICE(가격)보다
Calculator(계산기)의 TICKET_PRICE(티켓 가격)이 명확한 의미를 지닌다고 생각해요~

2020-11-26 09:54 UTC, yongdae commented on src/main/java/lotto/domain/Generator.java
> +    private static final int LOTTO_NUMBER_BOUND = 60;
로또 숫자중 가장 큰 값은 45가 아닌가요?? 🤔

2020-11-26 09:54 UTC, yongdae commented on src/main/java/lotto/domain/Generator.java
> +    private final List<Integer> lottoNumbers;
원시값 대신에 일급컬렉션을 활용해보는 것은 어떨까요?

로또 번호를 Integer 타입을 통해 활용하고 계신데
일급 컬렉션을 활용해서 만들면 유효성 검사하기도 편하고 이름을 줄 수 있어서
인지하기도 더 좋을 것 같아요. :)

2020-11-26 09:54 UTC, yongdae commented on src/main/java/lotto/domain/Generator.java
> +    }
static 초기화를 적용해보는 것은 어떠세요?

외부에서 호출하는것도 좋은 방법이지만 [static 초기화](https://kamang-it.tistory.com/entry/Java-14%EC%B4%88%EA%B8%B0%ED%99%94%EC%99%80-%EC%B4%88%EA%B8%B0%ED%99%94%EB%B8%94%EB%9F%ADInitialize-Block)를 활용해보는 것도 좋을 것 같아요. 😄

2020-11-26 09:54 UTC, yongdae commented on src/main/java/lotto/domain/Generator.java
> +    public List<LottoTicket> generateLottoTickets(int input) {
input 변수명에 의미를 주는 것은 어떨까요?

generateLottoTickets이 하고 있는 일은 input을 받아서
for문을 활용해서 ticket을 만들고 있는데
이때 변수명을 input보다는 count 나 ticketCount 같은
이름을 사용하면 인자로 무엇을 할 수 있을지 더 잘 알 수 있지 않을까요?

2020-11-26 09:54 UTC, yongdae commented on src/main/java/lotto/domain/ProfitCalculator.java
> +        profitMap.put(6L, 2000000000);
Enum을 활용해보시는건 어떠세요?

로또 결과를 Map을 통해 정의하는 것보다 Enum을 활용하면
명시적으로도 활용면에서도 좋을 것 같아요 :)

2020-11-26 09:54 UTC, yongdae commented on src/main/java/lotto/view/InputView.java
> +    public List<Integer> split(String input) {
접근제한자를 변경하는것은 어떨까요?

inputWinningNumbers에서만 split을 사용하고
외부에서 사용 할 일이 없다면 노출시키지 않는게 좋아요.
다른 곳에서 어떻게 사용될지 알 수가 없어요. 😭

2020-11-26 09:54 UTC, yongdae commented on src/test/java/lotto/GeneratorTest.java
> +public class GeneratorTest {
로또 숫자 범위를 확인 할 수 있는 테스트를 포함시키는 것은 어떨까요?

로또는 1 ~ 45 범위의 숫자를 가지고 있는데
이 범위를 확인 하는 테스트도 있는게 좋을 것 같아요. 😄

2020-11-28 09:12 UTC, jaehee0145 commented on src/main/java/lotto/domain/Calculator.java
> +        this.lottoTicketPrice = PRICE;
Calculator 가 lottoTicketPrice 를 갖고 있어야 한다고 생각했는데 없어도 상관이 없겠네요 :)

2020-11-28 09:12 UTC, jaehee0145 commented on src/main/java/lotto/domain/Generator.java
> +    private static final int LOTTO_NUMBER_BOUND = 60;
로또 초보라서 헷갈렸네요 😂

2020-11-28 09:13 UTC, jaehee0145 commented on src/main/java/lotto/domain/Generator.java
> +    public List<LottoTicket> generateLottoTickets(int input) {
넵 수정했습니다 !

2020-11-28 09:13 UTC, jaehee0145 commented on src/main/java/lotto/domain/ProfitCalculator.java
> +        profitMap.put(6L, 2000000000);
Enum으로 수정해봤습니다 !

2020-11-28 12:22 UTC, jaehee0145 commented on src/test/java/lotto/GeneratorTest.java
> +public class GeneratorTest {
추가했습니다 👍

2020-11-29 02:30 UTC, yongdae requested changes
피드백을 잘 반영해주셨네요. 👍👍

미션 진행해주신 내용에 대해 의견 남겨놓았습니다. 😄
고민해보신 다음 반영해주시면 좋을 것 같아요!
추가로 도메인 중 LottoTicket에 대한 테스트를 작성부탁드려요~

궁금한점이나 이야기 하실 내용이 있다면 언제든 편하게 DM 주세요. 🔥

2020-11-29 02:30 UTC, yongdae commented on src/test/java/lotto/GeneratorTest.java
> +//    }
사용하지 않는 코드는 삭제해주세요 ~ 😄

2020-11-29 02:30 UTC, yongdae commented on src/test/java/lotto/LottoNumbersTest.java
> +    public void make_new_numbers() {
한번 더 고민해보면 어떨까요? :)

범위내에서 로또 번호가 생성되는지 확인을 하기위한 테스트인데
지금 작성하신 내용으로 테스트가 적합하게 이루어졌는지 고민해봐야 할 것 같아요.

LottoNumbers를 통해 가져오는 값은 범위는 정해져 있지만
자동차 미션 때와 마찬가지로 랜덤한 숫자가 출력되기 때문에
테스트가 항상 통과 할 수 있다는 보장이 되지 않아요. 😭

2020-11-29 02:30 UTC, yongdae commented on src/main/java/lotto/domain/LottoNumbers.java
> +public class LottoNumbers {
지금은 유틸리티 성격을 가진 클래스가 된 것 같아요. :)

2020-11-29 02:30 UTC, yongdae commented on src/main/java/lotto/domain/LottoNumbers.java
> +    public List<Integer> makeNewNumbers() {
static를 활용해도 괜찮을것 같아요.

지금 makeNewNumbers 메소드를 사용하고 있는 부분을 확인해보면
static을 활용해도 좋을 것 같아요. 😄

2020-11-29 02:30 UTC, yongdae commented on src/main/java/lotto/domain/LottoNumbers.java
> +        return lottoNumbers.stream().limit(LOTTO_NUMBER_SIZE).sorted().collect(Collectors.toList());
규칙 4: 한 줄에 점을 하나만 찍는다.

이 규칙을 적용해보시면 어떠신가요?
한줄에 점 하나만 찍는 규칙을 적용하면 코드를 읽기가 쉬워지는 장점이 있어요~

2020-11-29 02:30 UTC, yongdae commented on src/main/java/lotto/domain/LottoResult.java
> +    private double profitRatio;
규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

이 규칙을 적용해보는 것도 고민해보시면 어떨까요? 🤔

2020-11-29 02:30 UTC, yongdae commented on src/main/java/lotto/domain/ProfitRule.java
> +    String desc;
규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

이 부분도 고민해보시면 좋을 것 같아요~ 😄

2020-12-01 14:28 UTC, jaehee0145 commented on src/test/java/lotto/LottoNumbersTest.java
> +    public void make_new_numbers() {
이 테스트는 어떻게 수정해야할지 잘 모르겠습니다 😭 😭

2020-12-01 14:32 UTC, jaehee0145 commented
> 피드백을 잘 반영해주셨네요. 👍👍
> 
> 미션 진행해주신 내용에 대해 의견 남겨놓았습니다. 😄
> 고민해보신 다음 반영해주시면 좋을 것 같아요!
> 추가로 도메인 중 LottoTicket에 대한 테스트를 작성부탁드려요~
> 
> 궁금한점이나 이야기 하실 내용이 있다면 언제든 편하게 DM 주세요. 🔥

LottoTicket 에 대해서는 고민을 해봤는데요
List<Integer> 를 가지는 일급 컬렉션으로 생각하고 작업을 했는데 따로 역할이 필요한걸까요?
다른 클래스를 봐도 역할이 겹치거나 필요가 없지는 않은데 
어떤 방향으로 수정하면 좋을지 다시 의견 부탁드립니다 🙏🏻
감사합니다 🍊

2020-12-02 01:24 UTC, yongdae commented on src/main/java/lotto/domain/LottoResult.java
> +    private double profitRatio;
private final Map<ProfitRule, Integer> result;
    private int profit;
    private final int payment;

규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

한번 더 적용해보는 것은 어떨까요?
한개의 변수를 더 줄여 볼 수 있을 것 같아요.

2020-12-02 02:29 UTC, yongdae commented on src/test/java/lotto/LottoNumbersTest.java
> +    public void make_new_numbers() {
로또 번호를 가진 클래스를 하나 더 만들어 보는 것은 어떨까요?

예를 들면 LottoNumber 처럼 로또 번호를 표현하는 클래스를요
그러면 로또 번호가 유효한 범위에서만 만들어질 수 있다는 부분을 보장 할 수 있지 않을까요? 🤔

2020-12-02 02:47 UTC, yongdae requested changes
안녕하세요. 재희님 🙇

먼저 질문에대해 답변드리자면 이 [내용](https://jojoldu.tistory.com/412?fbclid=IwAR2NhwpyOJDJzbDWGUqLo7z71xfFsqyaBRvdznilS21-19o7x2IpbvE3sDA)을 참고하시면 될 것 같습니다. 
일급 컬렉션을 활용할 수 있는 내용에대해 정리한 글입니다. :)

문의해주신 피드백에대해서는 다시 답변 달아놓았습니다. 😄
https://github.com/next-step/java-lotto/pull/986#discussion_r532131257
https://github.com/next-step/java-lotto/pull/986#discussion_r532132094

확인하시고 다시 리뷰 요청해주시면 될 것 같습니다.

추가로 아직 반영되지 않은 피드백이 있는 것 같아요 ~
https://github.com/next-step/java-lotto/pull/986#discussion_r532130722
https://github.com/next-step/java-lotto/pull/986#discussion_r532131800
https://github.com/next-step/java-lotto/pull/986#discussion_r532131946
https://github.com/next-step/java-lotto/pull/986#discussion_r532132042

코멘트 남긴 내용에 대하여 궁금하시거나 논의하고 싶은 부분이 있으시면
언제든 DM 주세요. 🔥🔥

2020-12-02 09:04 UTC, jaehee0145 commented on src/main/java/lotto/domain/LottoNumbers.java
> +public class LottoNumbers {
역할에 맞게 이름을 수정했는데 더 수정해야하는 점이 있을까요?

2020-12-02 16:07 UTC, yongdae approved these changes
안녕하세요. 재희님 ~

피드백을 잘 반영해주셨네요. 💯
수고하셨습니다. 👍👍👍

이제 다음 단계를 진행하러 가시죠!!

미션 진행하신 내용에대해 의견 남겨 놓은 부분이 있으니
다음 미션 진행 전에 확인 부탁드려요. 😄

2020-12-02 16:07 UTC, yongdae commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
로또 번호를 잘 표현해주셨네요. 👍

2020-12-02 16:07 UTC, yongdae commented on src/test/java/lotto/LottoNumberTest.java
> +    }
다른 테스트 방법을 활용해보시는 것은 어떨까요?

[경계값 테스트](https://testmanager.tistory.com/200)를 활용하면
더 명확한 의미를 가지는 테스트가 될 수 있을것 같아요. 😄

2020-12-02 16:11 UTC, merged